Code::Blocks: advancedcompileroptionsdlg.cpp File Reference
advancedcompileroptionsdlg.cpp File Reference
#include "sdk.h"
#include "advancedcompileroptionsdlg.h"
Functions
wxString ControlCharsToString (const wxString &src)
wxString StringToControlChars (const wxString &src)
Function Documentation
ControlCharsToString()
wxString ControlCharsToString (const wxString & src) inline
Definition at line 33 of file advancedcompileroptionsdlg.cpp.
References _T, and wxString::Replace().
Referenced by AdvancedCompilerOptionsDlg::FillRegexDetails().
StringToControlChars()
wxString StringToControlChars (const wxString & src)
Definition at line 44 of file advancedcompileroptionsdlg.cpp.
References _T, AdvancedCompilerOptionsDlg::OnAddExt(), AdvancedCompilerOptionsDlg::OnCommandsChange(), AdvancedCompilerOptionsDlg::OnDelExt(), AdvancedCompilerOptionsDlg::OnExtChange(), AdvancedCompilerOptionsDlg::OnRegexAdd(), AdvancedCompilerOptionsDlg::OnRegexChange(), AdvancedCompilerOptionsDlg::OnRegexDefaults(), AdvancedCompilerOptionsDlg::OnRegexDelete(), AdvancedCompilerOptionsDlg::OnRegexDown(), AdvancedCompilerOptionsDlg::OnRegexTest(), AdvancedCompilerOptionsDlg::OnRegexUp(), and wxString::Replace().
Referenced by AdvancedCompilerOptionsDlg::SaveRegexDetails().