Code::Blocks: app.cpp File Reference
app.cpp File Reference
#include <sdk.h>
#include "app.h"
#include <wx/arrstr.h>
#include <wx/fs_zip.h>
#include <wx/fs_mem.h>
#include <wx/xrc/xmlres.h>
#include <wx/cmdline.h>
#include <wx/regex.h>
#include <wx/filefn.h>
#include <wx/log.h>
#include <wx/msgdlg.h>
#include <wx/choicdlg.h>
#include <wx/notebook.h>
#include <wx/clipbrd.h>
#include <wx/debugrpt.h>
#include <wx/ipc.h>
#include <wx/msgout.h>
#include <cbexception.h>
#include <configmanager.h>
#include <debuggermanager.h>
#include <editormanager.h>
#include <globals.h>
#include <loggers.h>
#include <logmanager.h>
#include <manager.h>
#include <personalitymanager.h>
#include <pluginmanager.h>
#include <projectmanager.h>
#include <scriptingmanager.h>
#include <sdk_events.h>
#include <sqplus.h>
#include "appglobals.h"
#include "associations.h"
#include "cbauibook.h"
#include "cbstyledtextctrl.h"
#include "crashhandler.h"
#include "projectmanagerui.h"
#include "splashscreen.h"
#include "exchndl.h"
#include <wx/msw/winundef.h>
Macros
#define APP_PREFIX ""
#define CMD_ENTRY(X) X
Functions
wxString GetResourcesDir ()
IMPLEMENT_APP (CodeBlocksApp) bool CodeBlocksApp
void EnableLFH ()
Macro Definition Documentation
APP_PREFIX
#define APP_PREFIX ""
Definition at line 68 of file app.cpp.
Referenced by IMPLEMENT_APP().
CMD_ENTRY
#define CMD_ENTRY (X) X
Definition at line 212 of file app.cpp.
Function Documentation
EnableLFH()
void EnableLFH () inline
Definition at line 838 of file app.cpp.
Referenced by CodeBlocksApp::OnRun().
GetResourcesDir()
wxString GetResourcesDir () inline
Definition at line 77 of file app.cpp.
References _T, CodeBlocksApp::AddFileToOpenDelayed(), CodeBlocksApp::AttachDebugger(), cbEVT_APP_CMDLINE, DDE_TOPIC, wxString::empty(), wxString::Find(), wxString::Format(), Manager::Get(), wxRegEx::GetMatch(), wxConnection::GetTextFromData(), CodeBlocksApp::LoadDelayedFiles(), wxRegEx::Matches(), wxString::Mid(), wxServer::OnAcceptConnection(), CodeBlocksApp::ParseCmdLine(), Manager::ProcessEvent(), wxString::Replace(), CodeBlocksApp::SetAutoFile(), wxString::StartsWith(), wxString::wx_str(), wxEmptyString, wxNOT_FOUND, wxSafeShowMessage(), wxT, and wxTheApp.
Referenced by IMPLEMENT_APP().
IMPLEMENT_APP()
IMPLEMENT_APP (CodeBlocksApp)
Definition at line 338 of file app.cpp.
References _T, APP_PREFIX, wxString::append(), wxString::assign(), wxString::Contains(), Manager::Get(), Manager::GetConfigManager(), GetResourcesDir(), wxLocale::GetSystemEncoding(), wxString::IsEmpty(), CodeBlocksApp::LoadConfig(), wxString::Replace(), ConfigManager::SetUserDataFolder(), ConfigManager::Write(), wxEmptyString, wxGetEnv(), and wxT.