Code::Blocks: associations.cpp File Reference
associations.cpp File Reference
#include <sdk.h>
#include <wx/radiobox.h>
#include <wx/xrc/xmlres.h>
#include "associations.h"
#include "appglobals.h"
#include <manager.h>
#include <configmanager.h>
#include <filefilters.h>
#include <wx/checklst.h>
Functions
void DoSetAssociation (const wxString &executable, int index)
bool DoCheckAssociation (const wxString &executable, int index)
Variables
const Associations::Assoc knownTypes []
Function Documentation
bool DoCheckAssociation (const wxString & executable, int index) inline
References Associations::DoCheckAssociation().
Referenced by Associations::Check().
void DoSetAssociation (const wxString & executable, int index) inline
References Associations::DoSetAssociation().
Referenced by ManageAssocsDialog::OnApply(), Associations::SetAll(), Associations::SetBatchBuildOnly(), and Associations::SetCore().
Variable Documentation
const Associations::Assoc knownTypes[]
Referenced by Associations::CountAssocs().