Code::Blocks: cbeditor.cpp File Reference
cbeditor.cpp File Reference
#include "sdk_precomp.h"
#include "cbstyledtextctrl.h"
#include "cbcolourmanager.h"
#include <wx/fontutil.h>
#include <wx/splitter.h>
#include "cbeditorprintout.h"
#include "cbdebugger_interfaces.h"
#include "editor_hooks.h"
#include "encodingdetector.h"
#include "filefilters.h"
#include "projectfileoptionsdlg.h"
Classes
struct cbEditorInternalData
Macros
#define ERROR_STYLE wxSCI_MARK_SMALLRECT
#define BOOKMARK_STYLE wxSCI_MARK_ARROW
#define BREAKPOINT_STYLE wxSCI_MARK_CIRCLE
#define DEBUG_STYLE wxSCI_MARK_ARROW
#define DEBUG_STYLE_HIGHLIGHT wxSCI_MARK_BACKGROUND
#define BREAKPOINT_OTHER_MARKER 1
#define BREAKPOINT_DISABLED_MARKER 2
#define BREAKPOINT_MARKER 3
#define BOOKMARK_MARKER 4
#define ERROR_MARKER 5
#define DEBUG_MARKER 6
#define DEBUG_MARKER_HIGHLIGHT 7
#define C_LINE_MARGIN 0
#define C_MARKER_MARGIN 1
#define C_CHANGEBAR_MARGIN 2
#define C_FOLDING_MARGIN 3
Functions
static void CountLineEnds (cbStyledTextCtrl *control, int &linesCR, int &linesLF, int &linesCRLF)
static int DetectLineEnds (cbStyledTextCtrl *control)
void OverrideUseTabsPerLanguage (cbStyledTextCtrl *control)
Variables
const wxString g_EditorModified = _T("*")
const int idEmptyMenu = wxNewId()
const int idEdit = wxNewId()
const int idUndo = wxNewId()
const int idRedo = wxNewId()
const int idClearHistory = wxNewId()
const int idCut = wxNewId()
const int idCopy = wxNewId()
const int idPaste = wxNewId()
const int idDelete = wxNewId()
const int idUpperCase = wxNewId()
const int idLowerCase = wxNewId()
const int idSelectAll = wxNewId()
const int idSwapHeaderSource = wxNewId()
const int idOpenContainingFolder = wxNewId()
const int idBookmarks = wxNewId()
const int idBookmarksToggle = wxNewId()
const int idBookmarksPrevious = wxNewId()
const int idBookmarksNext = wxNewId()
const int idBookmarksClearAll = wxNewId()
const int idFolding = wxNewId()
const int idFoldingFoldAll = wxNewId()
const int idFoldingUnfoldAll = wxNewId()
const int idFoldingToggleAll = wxNewId()
const int idFoldingFoldCurrent = wxNewId()
const int idFoldingUnfoldCurrent = wxNewId()
const int idFoldingToggleCurrent = wxNewId()
const int idInsert = wxNewId()
const int idSplit = wxNewId()
const int idSplitHorz = wxNewId()
const int idSplitVert = wxNewId()
const int idUnsplit = wxNewId()
const int idProperties = wxNewId()
const int idAddFileToProject = wxNewId()
const int idRemoveFileFromProject = wxNewId()
const int idShowFileInProject = wxNewId()
const int idOpenUrl = wxNewId()
const int idBookmarkAdd = wxNewId()
const int idBookmarkRemove = wxNewId()
const int idBookmarkRemoveAll = wxNewId()
const int idBreakpointAdd = wxNewId()
const int idBreakpointEdit = wxNewId()
const int idBreakpointRemove = wxNewId()
const long idBreakpointEnable = wxNewId()
const long idBreakpointDisable = wxNewId()
Macro Definition Documentation
BOOKMARK_MARKER
#define BOOKMARK_MARKER 4
Definition at line 64 of file cbeditor.cpp.
Referenced by cbEditor::ClearAllBookmarks(), cbEditor::GotoNextBookmark(), cbEditor::GotoPreviousBookmark(), cbEditor::HasBookmark(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), cbEditor::OnBeforeBuildContextMenu(), cbEditor::OnContextMenuEntry(), and cbEditor::ToggleBookmark().
BOOKMARK_STYLE
#define BOOKMARK_STYLE wxSCI_MARK_ARROW
Definition at line 56 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
BREAKPOINT_DISABLED_MARKER
#define BREAKPOINT_DISABLED_MARKER 2
Definition at line 62 of file cbeditor.cpp.
Referenced by cbEditor::BreakpointMarkerToggle(), cbEditor::HasBreakpoint(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), cbEditor::OnBeforeBuildContextMenu(), and cbEditor::RefreshBreakpointMarkers().
BREAKPOINT_MARKER
#define BREAKPOINT_MARKER 3
Definition at line 63 of file cbeditor.cpp.
Referenced by cbEditor::BreakpointMarkerToggle(), cbEditor::GotoNextBreakpoint(), cbEditor::GotoPreviousBreakpoint(), cbEditor::HasBreakpoint(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), cbEditor::OnBeforeBuildContextMenu(), and cbEditor::RefreshBreakpointMarkers().
BREAKPOINT_OTHER_MARKER
#define BREAKPOINT_OTHER_MARKER 1
Definition at line 61 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::RefreshBreakpointMarkers().
BREAKPOINT_STYLE
#define BREAKPOINT_STYLE wxSCI_MARK_CIRCLE
Definition at line 57 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
C_CHANGEBAR_MARGIN
#define C_CHANGEBAR_MARGIN 2
Definition at line 71 of file cbeditor.cpp.
Referenced by cbEditor::DoInitializations(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::OnBeforeBuildContextMenu().
C_FOLDING_MARGIN
#define C_FOLDING_MARGIN 3
Definition at line 72 of file cbeditor.cpp.
Referenced by cbEditor::DoInitializations(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::OnBeforeBuildContextMenu(), cbEditor::OnMarginClick(), and cbEditorInternalData::SetFoldingColWidth().
C_LINE_MARGIN
#define C_LINE_MARGIN 0
Definition at line 69 of file cbeditor.cpp.
Referenced by cbEditor::DoInitializations(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::OnBeforeBuildContextMenu(), cbEditor::Print(), cbEditorInternalData::SetLineNumberColWidth(), and cbEditor::Split().
C_MARKER_MARGIN
#define C_MARKER_MARGIN 1
Definition at line 70 of file cbeditor.cpp.
Referenced by cbEditor::DoInitializations(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnMarginClick().
DEBUG_MARKER
#define DEBUG_MARKER 6
Definition at line 66 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::SetDebugLine().
DEBUG_MARKER_HIGHLIGHT
#define DEBUG_MARKER_HIGHLIGHT 7
Definition at line 67 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::SetDebugLine().
DEBUG_STYLE
#define DEBUG_STYLE wxSCI_MARK_ARROW
Definition at line 58 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
DEBUG_STYLE_HIGHLIGHT
#define DEBUG_STYLE_HIGHLIGHT wxSCI_MARK_BACKGROUND
Definition at line 59 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
ERROR_MARKER
#define ERROR_MARKER 5
Definition at line 65 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::SetErrorLine().
ERROR_STYLE
#define ERROR_STYLE wxSCI_MARK_SMALLRECT
Definition at line 55 of file cbeditor.cpp.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
Function Documentation
CountLineEnds()
static void CountLineEnds (cbStyledTextCtrl * control, int & linesCR, int & linesLF, int & linesCRLF) static
Definition at line 598 of file cbeditor.cpp.
Referenced by DetectLineEnds().
DetectLineEnds()
static int DetectLineEnds (cbStyledTextCtrl * control) static
Definition at line 633 of file cbeditor.cpp.
References _(), _T, CountLineEnds(), InfoWindow::Display(), wxBell(), wxSCI_EOL_CR, wxSCI_EOL_CRLF, and wxSCI_EOL_LF.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen().
OverrideUseTabsPerLanguage()
void OverrideUseTabsPerLanguage (cbStyledTextCtrl * control) inline
Definition at line 1234 of file cbeditor.cpp.
References wxScintilla::GetLexer(), wxScintilla::SetUseTabs(), wxSCI_LEX_MAKEFILE, and wxSCI_LEX_PYTHON.
Referenced by cbEditor::SaveAs(), and cbEditor::SetEditorStyleBeforeFileOpen().
Variable Documentation
g_EditorModified
const wxString g_EditorModified = _T("*")
Definition at line 53 of file cbeditor.cpp.
Referenced by EditorManager::IsOpen().
idAddFileToProject
const int idAddFileToProject = wxNewId()
Definition at line 534 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idBookmarkAdd
const int idBookmarkAdd = wxNewId()
Definition at line 539 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idBookmarkRemove
const int idBookmarkRemove = wxNewId()
Definition at line 540 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idBookmarkRemoveAll
const int idBookmarkRemoveAll = wxNewId()
Definition at line 541 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idBookmarks
const int idBookmarks = wxNewId()
Definition at line 516 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::CreateContextSubMenu().
idBookmarksClearAll
const int idBookmarksClearAll = wxNewId()
Definition at line 520 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idBookmarksNext
const int idBookmarksNext = wxNewId()
Definition at line 519 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idBookmarksPrevious
const int idBookmarksPrevious = wxNewId()
Definition at line 518 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idBookmarksToggle
const int idBookmarksToggle = wxNewId()
Definition at line 517 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idBreakpointAdd
const int idBreakpointAdd = wxNewId()
Definition at line 543 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idBreakpointDisable
const long idBreakpointDisable = wxNewId()
Definition at line 547 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idBreakpointEdit
const int idBreakpointEdit = wxNewId()
Definition at line 544 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idBreakpointEnable
const long idBreakpointEnable = wxNewId()
Definition at line 546 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idBreakpointRemove
const int idBreakpointRemove = wxNewId()
Definition at line 545 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
idClearHistory
const int idClearHistory = wxNewId()
Definition at line 506 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idCopy
const int idCopy = wxNewId()
Definition at line 508 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idCut
const int idCut = wxNewId()
Definition at line 507 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idDelete
const int idDelete = wxNewId()
Definition at line 510 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idEdit
const int idEdit = wxNewId()
Definition at line 503 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::CreateContextSubMenu().
idEmptyMenu
const int idEmptyMenu = wxNewId()
Definition at line 502 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::CreateContextSubMenu().
idFolding
const int idFolding = wxNewId()
Definition at line 521 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::CreateContextSubMenu().
idFoldingFoldAll
const int idFoldingFoldAll = wxNewId()
Definition at line 522 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idFoldingFoldCurrent
const int idFoldingFoldCurrent = wxNewId()
Definition at line 525 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idFoldingToggleAll
const int idFoldingToggleAll = wxNewId()
Definition at line 524 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idFoldingToggleCurrent
const int idFoldingToggleCurrent = wxNewId()
Definition at line 527 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idFoldingUnfoldAll
const int idFoldingUnfoldAll = wxNewId()
Definition at line 523 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idFoldingUnfoldCurrent
const int idFoldingUnfoldCurrent = wxNewId()
Definition at line 526 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idInsert
const int idInsert = wxNewId()
Definition at line 528 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::CreateContextSubMenu().
idLowerCase
const int idLowerCase = wxNewId()
Definition at line 512 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idOpenContainingFolder
const int idOpenContainingFolder = wxNewId()
Definition at line 515 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idOpenUrl
const int idOpenUrl = wxNewId()
Definition at line 537 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idPaste
const int idPaste = wxNewId()
Definition at line 509 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idProperties
const int idProperties = wxNewId()
Definition at line 533 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), cbEditor::OnContextMenuEntry(), and BreakpointsDlg::OnRightClick().
idRedo
const int idRedo = wxNewId()
Definition at line 505 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idRemoveFileFromProject
const int idRemoveFileFromProject = wxNewId()
Definition at line 535 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idSelectAll
const int idSelectAll = wxNewId()
Definition at line 513 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idShowFileInProject
const int idShowFileInProject = wxNewId()
Definition at line 536 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idSplit
const int idSplit = wxNewId()
Definition at line 529 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu().
idSplitHorz
const int idSplitHorz = wxNewId()
Definition at line 530 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idSplitVert
const int idSplitVert = wxNewId()
Definition at line 531 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idSwapHeaderSource
const int idSwapHeaderSource = wxNewId()
Definition at line 514 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idUndo
const int idUndo = wxNewId()
Definition at line 504 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().
idUnsplit
const int idUnsplit = wxNewId()
Definition at line 532 of file cbeditor.cpp.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
idUpperCase
const int idUpperCase = wxNewId()
Definition at line 511 of file cbeditor.cpp.
Referenced by cbEditor::CreateContextSubMenu(), and cbEditor::OnContextMenuEntry().