Code::Blocks: cbexecute.h File Reference
cbexecute.h File Reference
#include "manager.h"
Classes
class cbExecuteProcess
Functions
long cbSyncExecute (const wxString &command, wxArrayString &output, wxArrayString &error)
long cbSyncExecute (const wxString &command, wxArrayString &output)
Function Documentation
cbSyncExecute() [1/2]
long cbSyncExecute (const wxString & command, wxArrayString & output, wxArrayString & error) inline
Definition at line 83 of file cbexecute.h.
References cbExecuteProcess::ExitCode(), Manager::IsAppShuttingDown(), wxProcess::Kill(), cbExecuteProcess::Running(), wxEXEC_ASYNC, wxExecute(), wxSIGTERM, and Manager::Yield().
cbSyncExecute() [2/2]
long cbSyncExecute (const wxString & command, wxArrayString & output) inline
Definition at line 102 of file cbexecute.h.
References cbExecuteProcess::ExitCode(), Manager::IsAppShuttingDown(), wxProcess::Kill(), cbExecuteProcess::Running(), wxEXEC_ASYNC, wxExecute(), wxSIGTERM, and Manager::Yield().