Code::Blocks: cbplugin.cpp File Reference
cbplugin.cpp File Reference
#include "sdk_precomp.h"
#include <wx/toolbar.h>
#include "annoyingdialog.h"
#include "cbdebugger_interfaces.h"
#include "cbstyledtextctrl.h"
#include "ccmanager.h"
#include "debuggermanager.h"
#include "editor_hooks.h"
#include "loggers.h"
Functions
bool HasBreakpoint (cbDebuggerPlugin &plugin, wxString const &filename, int line)
Function Documentation
HasBreakpoint()
bool HasBreakpoint (cbDebuggerPlugin & plugin, wxString const & filename, int line) inline
Definition at line 360 of file cbplugin.cpp.
References cbDebuggerPlugin::GetBreakpoint(), and cbDebuggerPlugin::GetBreakpointsCount().
Referenced by cbEditor::GetLastModificationTime().