Code::Blocks: cbproject.cpp File Reference
cbproject.cpp File Reference
#include "sdk_precomp.h"
#include <wx/choicdlg.h>
#include <wx/filedlg.h>
#include <wx/filename.h>
#include <wx/textdlg.h>
#include <wx/dir.h>
#include "cbproject.h"
#include "cbeditor.h"
#include "cbtreectrl.h"
#include "compiler.h"
#include "compilerfactory.h"
#include "configmanager.h"
#include "editormanager.h"
#include "filemanager.h"
#include "globals.h"
#include "infowindow.h"
#include "logmanager.h"
#include "macrosmanager.h"
#include "manager.h"
#include "pluginmanager.h"
#include "projectbuildtarget.h"
#include "projectfile.h"
#include "projectmanager.h"
#include "sdk_events.h"
#include <map>
#include "projectloader.h"
#include "projectlayoutloader.h"
#include "selecttargetdlg.h"
#include "filegroupsandmasks.h"
#include "filefilters.h"
#include "annoyingdialog.h"
#include "genericmultilinenotesdlg.h"
#include "compilercommandgenerator.h"
#include "cbcolourmanager.h"
Macros
#define wxUSE_CHOICEDLG 1
Functions
wxString cbGetDynamicLinkerPathForTarget (cbProject *project, ProjectBuildTarget *target)
Returns a string valid to be used as LD_LIBRARY_PATH (or equivalent).
wxString cbMergeLibPaths (const wxString &oldPath, const wxString &newPath)
Merges to LD_LIBRARY_PATH/PATH strings together to form a new valid string.
Macro Definition Documentation
#define wxUSE_CHOICEDLG 1
Function Documentation
wxString cbGetDynamicLinkerPathForTarget (cbProject * project, ProjectBuildTarget * target)
Returns a string valid to be used as LD_LIBRARY_PATH (or equivalent).
References Compiler::GetCommandGenerator(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerCommandGenerator::GetLinkerSearchDirs(), and GetStringFromArray().
Referenced by CompilerGCC::DoRunQueue(), and CompilerGCC::Run().
wxString cbMergeLibPaths (const wxString & oldPath, const wxString & newPath)
Merges to LD_LIBRARY_PATH/PATH strings together to form a new valid string.
Referenced by CompilerGCC::DoRunQueue().