Code::Blocks: cbproject.h File Reference
cbproject.h File Reference
#include <wx/datetime.h>
#include <wx/dynarray.h>
#include <wx/hashmap.h>
#include <wx/treectrl.h>
#include "settings.h"
#include "misctreeitemdata.h"
#include "compiletargetbase.h"
#include "cbplugin.h"
#include "projectbuildtarget.h"
#include "projectmanager.h"
#include <map>
#include <vector>
Classes
class FileTreeData
class cbProject
Represents a Code::Blocks project.
struct cbProject::Glob
Typedefs
typedef std::map< wxString, wxArrayString > VirtualBuildTargetsMap
Enumerations
enum PCHMode { pchSourceDir = 0, pchObjectDir, pchSourceFile }
Precompiled headers mode.
Functions
WX_DECLARE_STRING_HASH_MAP (ProjectFile *, ProjectFiles)
DLLIMPORT wxString cbGetDynamicLinkerPathForTarget (cbProject *project, ProjectBuildTarget *target)
Returns a string valid to be used as LD_LIBRARY_PATH (or equivalent).
DLLIMPORT wxString cbMergeLibPaths (const wxString &oldPath, const wxString &newPath)
Merges to LD_LIBRARY_PATH/PATH strings together to form a new valid string.
Typedef Documentation
VirtualBuildTargetsMap
typedef std::map<wxString, wxArrayString> VirtualBuildTargetsMap
Definition at line 35 of file cbproject.h.
Enumeration Type Documentation
PCHMode
enum PCHMode
Precompiled headers mode.
Defines where and how are the project's precompiled headers generated. Currently implemented only for GCC (3.4 and above).
Enumerator
pchSourceDir
pchObjectDir
In a dir (named by the PCH) on the same level as the source header (default).
pchSourceFile
In the objects output dir, along with other object files.
In a file alongside the source header (with .gch appended).
Definition at line 83 of file cbproject.h.
Function Documentation
cbGetDynamicLinkerPathForTarget()
DLLIMPORT wxString cbGetDynamicLinkerPathForTarget (cbProject * project, ProjectBuildTarget * target)
Returns a string valid to be used as LD_LIBRARY_PATH (or equivalent).
Definition at line 1751 of file cbproject.cpp.
References _T, Compiler::GetCommandGenerator(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerCommandGenerator::GetLinkerSearchDirs(), GetStringFromArray(), wxString::IsEmpty(), wxString::Length(), wxString::Mid(), wxString::Truncate(), and wxEmptyString.
Referenced by CompilerGCC::DoRunQueue(), and CompilerGCC::Run().
cbMergeLibPaths()
DLLIMPORT wxString cbMergeLibPaths (const wxString & oldPath, const wxString & newPath)
Merges to LD_LIBRARY_PATH/PATH strings together to form a new valid string.
Definition at line 1773 of file cbproject.cpp.
References _T, wxString::IsEmpty(), wxString::Length(), and wxString::Mid().
Referenced by CompilerGCC::DoRunQueue().
WX_DECLARE_STRING_HASH_MAP()
WX_DECLARE_STRING_HASH_MAP (ProjectFile * , ProjectFiles)