Code::Blocks: cbstyledtextctrl.cpp File Reference
cbstyledtextctrl.cpp File Reference
#include "sdk_precomp.h"
#include "cbstyledtextctrl.h"
#include <wx/gdicmn.h>
#include <wx/string.h>
#include <wx/timer.h>
#include "editorbase.h"
#include "editormanager.h"
#include "pluginmanager.h"
#include <wx/textfile.h>
#include "cbdebugger_interfaces.h"
#include "ccmanager.h"
#include "debuggermanager.h"
Functions
static const wxString s_leftBrace (_T("([{'\""))
static const wxString s_rightBrace (_T(")]}'\""))
static const int s_indicHighlight (20)
Function Documentation
static const int s_indicHighlight (20) static
Referenced by cbStyledTextCtrl::HighlightRightBrace().
static const wxString s_leftBrace () static
Referenced by cbStyledTextCtrl::OnKeyDown(), and cbStyledTextCtrl::OnKeyUp().
static const wxString s_rightBrace (_T(")]}'\"") static
Referenced by cbStyledTextCtrl::HighlightRightBrace(), cbStyledTextCtrl::OnKeyDown(), and cbStyledTextCtrl::OnKeyUp().