Code::Blocks: cclogger.cpp File Reference
cclogger.cpp File Reference
#include "cclogger.h"
#include <wx/event.h>
#include <wx/textfile.h>
#include <wx/utils.h>
#include <logmanager.h>
#include <globals.h>
Macros
#define TRACE_TO_FILE(msg)
#define TRACE_THIS_TO_FILE(msg)
Variables
bool g_EnableDebugTrace = false
Toggles tracing into file.
bool g_EnableDebugTraceFile = false
const wxString g_DebugTraceFile = wxEmptyString
Trace file name (if above is enabled).
long g_idCCAddToken = wxNewId()
long g_idCCLogger = wxNewId()
long g_idCCDebugLogger = wxNewId()
Macro Definition Documentation
TRACE_THIS_TO_FILE
#define TRACE_THIS_TO_FILE (msg)
Value:
if (!g_DebugTraceFile.IsEmpty())                                 \
    {                                                                \
        wxTextFile f(g_DebugTraceFile);                              \
        if ((f.Exists() && f.Open()) || (!f.Exists() && f.Create())) \
        {                                                            \
            f.AddLine(msg);                                          \
            bool exp = f.Write() && f.Close()                        \
            cbAssert(exp);                                           \
        }                                                            \
    }                                                                \
Definition at line 39 of file cclogger.cpp.
TRACE_TO_FILE
#define TRACE_TO_FILE (msg)
Value:
if (g_EnableDebugTraceFile && !g_DebugTraceFile.IsEmpty())       \
    {                                                                \
        wxTextFile f(g_DebugTraceFile);                              \
        if ((f.Exists() && f.Open()) || (!f.Exists() && f.Create())) \
        {                                                            \
            f.AddLine(msg);                                          \
            bool exp = f.Write() && f.Close();                       \
            cbAssert(exp);                                           \
        }                                                            \
    }                                                                \
Definition at line 27 of file cclogger.cpp.
Variable Documentation
g_DebugTraceFile
const wxString g_DebugTraceFile = wxEmptyString
Trace file name (if above is enabled).
Definition at line 23 of file cclogger.cpp.
g_EnableDebugTrace
bool g_EnableDebugTrace = false
Toggles tracing into file.
Definition at line 21 of file cclogger.cpp.
g_EnableDebugTraceFile
bool g_EnableDebugTraceFile = false
Definition at line 22 of file cclogger.cpp.
g_idCCAddToken
long g_idCCAddToken = wxNewId()
Definition at line 24 of file cclogger.cpp.
g_idCCDebugLogger
long g_idCCDebugLogger = wxNewId()
Definition at line 26 of file cclogger.cpp.
Referenced by CodeCompletion::CodeCompletion(), and CodeCompletion::~CodeCompletion().
g_idCCLogger
long g_idCCLogger = wxNewId()
Definition at line 25 of file cclogger.cpp.
Referenced by CodeCompletion::CodeCompletion(), and CodeCompletion::~CodeCompletion().