Code::Blocks: ccmanager.cpp File Reference
ccmanager.cpp File Reference
#include "sdk_precomp.h"
#include "ccmanager.h"
#include <wx/html/htmlwin.h>
#include <wx/display.h>
#include "cbcolourmanager.h"
#include "cbstyledtextctrl.h"
#include "editor_hooks.h"
Classes
class UnfocusablePopupWindow
struct TokenSorter
Namespaces
CCManagerHelper
Macros
#define CALLTIP_REFRESH_DELAY 90
#define AUTOCOMP_SELECT_DELAY 35
#define SCROLL_REFRESH_DELAY 500
#define FROM_TIMER 1
FROM_TIMER means the event is automatically fired from the ccmanager, not explicitly called by the user.
Enumerations
enum TooltipMode { tmDisable = 0, tmEnable, tmForceSinglePage, tmKeyboundOnly }
the CC tooltip options in Editor setting dialog
enum ACLaunchState { lsTknStart, lsCaretStart }
Functions
void CCManagerHelper::RipplePts (int &ptA, int &ptB, int len, int delta)
int CCManagerHelper::FindColumn (int line, int column, wxScintilla *stc)
bool CCManagerHelper::IsPosVisible (int pos, wxScintilla *stc)
static int CCManagerHelper::CallTipToInt (const wxString &firstTip, int numPages)
static void CCManagerHelper::BuildFontSizes (int *sizes, int size)
static int CCManagerHelper::GetDefaultHTMLFontSize ()
static void setupColours (cbEditor *editor, ColourManager *manager)
Variables
const int idCallTipTimer = wxNewId()
const int idAutoLaunchTimer = wxNewId()
const int idAutocompSelectTimer = wxNewId()
const int idShowTooltip = wxNewId()
const int idCallTipNext = wxNewId()
const int idCallTipPrevious = wxNewId()
Macro Definition Documentation
AUTOCOMP_SELECT_DELAY
#define AUTOCOMP_SELECT_DELAY 35
Definition at line 126 of file ccmanager.cpp.
Referenced by CCManager::OnAutocompleteSelect().
CALLTIP_REFRESH_DELAY
#define CALLTIP_REFRESH_DELAY 90
Definition at line 125 of file ccmanager.cpp.
Referenced by CCManager::OnAutocompleteHide(), and CCManager::OnEditorHook().
FROM_TIMER
#define FROM_TIMER 1
FROM_TIMER means the event is automatically fired from the ccmanager, not explicitly called by the user.
For example, if the code suggestion is fired by the client code, such as:
CodeBlocksEvent evt(cbEVT_COMPLETE_CODE);
Manager::Get()->ProcessEvent(evt);
Then the event has int value 0.
Definition at line 146 of file ccmanager.cpp.
Referenced by CCManager::OnCompleteCode(), CCManager::OnShowCallTip(), and CCManager::OnTimer().
SCROLL_REFRESH_DELAY
#define SCROLL_REFRESH_DELAY 500
Definition at line 127 of file ccmanager.cpp.
Referenced by CCManager::OnEditorHook().
Enumeration Type Documentation
ACLaunchState
enum ACLaunchState
Enumerator
lsTknStart
lsCaretStart
Definition at line 148 of file ccmanager.cpp.
TooltipMode
enum TooltipMode
the CC tooltip options in Editor setting dialog
Enumerator
tmDisable
tmEnable
tmForceSinglePage
tmKeyboundOnly
Definition at line 130 of file ccmanager.cpp.
Function Documentation
setupColours()
static void setupColours (cbEditor * editor, ColourManager * manager) static
Definition at line 634 of file ccmanager.cpp.
References wxScintilla::CallTipSetBackground(), wxScintilla::CallTipSetForeground(), wxScintilla::CallTipSetForegroundHighlight(), ColourManager::GetColour(), cbEditor::GetControl(), and wxT.
Referenced by CCManager::OnEditorOpen(), and CCManager::UpdateEnvSettings().
Variable Documentation
idAutocompSelectTimer
const int idAutocompSelectTimer = wxNewId()
Definition at line 116 of file ccmanager.cpp.
Referenced by CCManager::OnTimer().
idAutoLaunchTimer
const int idAutoLaunchTimer = wxNewId()
Definition at line 115 of file ccmanager.cpp.
Referenced by CCManager::OnTimer().
idCallTipNext
const int idCallTipNext = wxNewId()
Definition at line 118 of file ccmanager.cpp.
Referenced by CCManager::CCManager(), CCManager::OnMenuSelect(), and CCManager::~CCManager().
idCallTipPrevious
const int idCallTipPrevious = wxNewId()
Definition at line 119 of file ccmanager.cpp.
Referenced by CCManager::CCManager(), CCManager::OnMenuSelect(), and CCManager::~CCManager().
idCallTipTimer
const int idCallTipTimer = wxNewId()
Definition at line 114 of file ccmanager.cpp.
Referenced by CCManager::OnTimer().
idShowTooltip
const int idShowTooltip = wxNewId()
Definition at line 117 of file ccmanager.cpp.
Referenced by CCManager::CCManager(), CCManager::OnMenuSelect(), and CCManager::~CCManager().