Code::Blocks: cdb_commands.h File Reference
cdb_commands.h File Reference
#include <wx/string.h>
#include <wx/regex.h>
#include <wx/tipwin.h>
#include <globals.h>
#include <manager.h>
#include <cbdebugger_interfaces.h>
#include "debugger_defs.h"
#include "debuggergdb.h"
#include "debuggermanager.h"
#include "parsewatchvalue.h"
Classes
class CdbCmd_AddSourceDir
Command to add a search directory for source files in debugger's paths.
class CdbCmd_SetDebuggee
Command to the set the file to be debugged.
class CdbCmd_AddSymbolFile
Command to the add symbol files.
class CdbCmd_SetArguments
Command to set the arguments to the debuggee.
class CdbCmd_GetPID
Command to find the PID of the active child.
class CdbCmd_AttachToProcess
Command to the attach to a process.
class CdbCmd_Detach
Command to the detach from the process.
class CdbCmd_Continue
Command to continue execution and notify the debugger plugin.
class CdbCmd_AddBreakpoint
Command to add a breakpoint.
class CdbCmd_RemoveBreakpoint
Command to remove a breakpoint.
class CdbCmd_Watch
Command to get info about a watched variable.
class CdbCmd_TooltipEvaluation
Command to display a tooltip about a variables value.
class CdbCmd_Backtrace
Command to run a backtrace.
class CdbCmd_SwitchFrame
class CdbCmd_InfoRegisters
Command to run a disassembly.
class CdbCmd_Disassembly
Command to run a disassembly.
class CdbCmd_DisassemblyInit
Command to run a disassembly.
Functions
static wxRegEx reProcessInf (_T("id:[ \t]+([A-Fa-f0-9]+)[ \t]+create"))
static wxRegEx reWatch (_T("(\\+0x[A-Fa-f0-9]+)"))
static wxRegEx reBT1 (_T("([0-9]+) ([A-Fa-f0-9]+) ([A-Fa-f0-9]+) ([^[]*)"))
static wxRegEx reBT2 (_T("\\[([A-z]:)(.*) @ ([0-9]+)\\]"))
static wxRegEx reDisassembly (_T("^[0-9]+[ \t]+([A-Fa-f0-9]+)[ \t]+[A-Fa-f0-9]+[ \t]+(.*)$"))
static wxRegEx reDisassemblyFile (_T("[0-9]+[ \t]+([A-Fa-f0-9]+)[ \t]+[A-Fa-f0-9]+[ \t]+(.*)\\[([A-z]:)(.*) @ ([0-9]+)\\]"))
static wxRegEx reDisassemblyFunc (_T("^\\(([A-Fa-f0-9]+)\\)[ \t]+"))
static wxRegEx reSwitchFrame (wxT("[ \\t]*([0-9]+)[ \\t]([0-9a-z]+)[ \\t](.+)[ \\t]\\[(.+)[ \\t]@[ \\t]([0-9]+)\\][ \\t]*"))
Function Documentation
static wxRegEx reBT1 (_T("([0-9]+) ([A-Fa-f0-9]+) ([A-Fa-f0-9]+) ([^[]*)")) static
Referenced by CdbCmd_Backtrace::ParseOutput().
static wxRegEx reBT2 (_T("\\[([A-z]:)(.*) @ ([0-9]+)\\]")) static
Referenced by CdbCmd_Backtrace::ParseOutput().
static wxRegEx reDisassembly (_T("^[0-9]+[ \t]+([A-Fa-f0-9]+)[ \t]+[A-Fa-f0-9]+[ \t]+(.*)$")) static
Referenced by CdbCmd_Disassembly::ParseOutput().
static wxRegEx reDisassemblyFile (_T("[0-9]+[ \t]+([A-Fa-f0-9]+)[ \t]+[A-Fa-f0-9]+[ \t]+(.*)\\[([A-z]:)(.*) @ ([0-9]+)\\]")) static
Referenced by CdbCmd_DisassemblyInit::ParseOutput().
static wxRegEx reDisassemblyFunc (_T("^\\(([A-Fa-f0-9]+)\\)[ \t]+")) static
Referenced by CdbCmd_DisassemblyInit::ParseOutput().
static wxRegEx reProcessInf (_T("id:[ \t]+([A-Fa-f0-9]+)[ \t]+create")) static
Referenced by CdbCmd_GetPID::ParseOutput().
static wxRegEx reSwitchFrame (wxT("[ \\t]*([0-9]+)[ \\t]([0-9a-z]+)[ \\t](.+)[ \\t]\\[(.+)[ \\t]@[ \\t]([0-9]+)\\][ \\t]*")) static
Referenced by CdbCmd_SwitchFrame::ParseOutput().
static wxRegEx reWatch (_T("(\\+0x[A-Fa-f0-9]+)")) static