Code::Blocks: cbBacktraceDlg Class Reference
cbBacktraceDlg Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbBacktraceDlg ()
virtual wxWindow * GetWindow ()=0
virtual void Reload ()=0
virtual void EnableWindow (bool enable)=0
Detailed Description
Definition at line 18 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
~cbBacktraceDlg()
cbBacktraceDlg::~cbBacktraceDlg () virtual
Definition at line 9 of file cbdebugger_interfaces.cpp.
Member Function Documentation
EnableWindow()
virtual void cbBacktraceDlg::EnableWindow (bool enable) pure virtual
Implemented in BacktraceDlg.
Referenced by DebuggerManager::RefreshUI(), and DebuggerManager::SetInterfaceFactory().
GetWindow()
virtual wxWindow* cbBacktraceDlg::GetWindow () pure virtual
Implemented in BacktraceDlg.
Referenced by DebugInterfaceFactory::DeleteBacktrace(), DebuggerManager::ShowBacktraceDialog(), and DebuggerManager::UpdateBacktrace().
Reload()
virtual void cbBacktraceDlg::Reload () pure virtual
Implemented in BacktraceDlg.
Referenced by CdbCmd_Backtrace::ParseOutput(), CdbCmd_SwitchFrame::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), DebuggerDriver::ResetCurrentFrame(), and DebuggerGDB::SwitchToFrame().
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp