Code::Blocks: wxToolBarAddOnXmlHandler Class Reference
wxToolBarAddOnXmlHandler Class Reference
#include <xtra_res.h>
Public Member Functions
wxToolBarAddOnXmlHandler ()
virtual wxObject * DoCreateResource ()
virtual bool CanHandle (wxXmlNode *node)
Protected Member Functions
wxBitmap GetCenteredBitmap (const wxString &param=wxT("bitmap"), const wxArtClient &defaultArtClient=wxART_OTHER, wxSize size=wxDefaultSize)
Protected Attributes
bool m_isInside
bool m_isAddon
wxToolBar * m_toolbar
Detailed Description
Definition at line 17 of file xtra_res.h.
Constructor & Destructor Documentation
wxToolBarAddOnXmlHandler()
wxToolBarAddOnXmlHandler::wxToolBarAddOnXmlHandler ()
Definition at line 34 of file xtra_res.cpp.
References wxTB_3DBUTTONS, wxTB_DOCKABLE, wxTB_FLAT, wxTB_HORIZONTAL, wxTB_NOALIGN, wxTB_NODIVIDER, wxTB_NOICONS, wxTB_TEXT, and wxTB_VERTICAL.
Member Function Documentation
CanHandle()
bool wxToolBarAddOnXmlHandler::CanHandle (wxXmlNode * node) virtual
Implements wxXmlResourceHandler.
Definition at line 246 of file xtra_res.cpp.
References _T, wxXmlNode::GetAttribute(), IMPLEMENT_DYNAMIC_CLASS(), m_isInside, wxEmptyString, and wxT.
DoCreateResource()
wxObject * wxToolBarAddOnXmlHandler::DoCreateResource () virtual
Implements wxXmlResourceHandler.
Definition at line 89 of file xtra_res.cpp.
References _(), _T, wxToolBar::AddControl(), wxToolBar::AddSeparator(), wxToolBar::AddTool(), wxToolBar::EnableTool(), GetCenteredBitmap(), wxXmlNode::GetName(), wxXmlNode::GetNext(), wxToolBar::GetToolBitmapSize(), wxXmlNode::GetType(), m_isAddon, m_isInside, m_toolbar, NULL, wxToolBar::Realize(), wxToolBar::SetMargins(), wxToolBar::SetToolBitmapSize(), wxToolBar::SetToolPacking(), wxToolBar::SetToolSeparation(), wxART_TOOLBAR, wxASSERT_MSG, wxCHECK_MSG, wxCHECK_VERSION, wxDefaultPosition, wxDefaultSize, wxDynamicCast, wxEmptyString, wxITEM_CHECK, wxITEM_NORMAL, wxITEM_RADIO, wxNO_BORDER, wxStaticCast, wxTB_HORIZONTAL, and wxXML_ELEMENT_NODE.
GetCenteredBitmap()
wxBitmap wxToolBarAddOnXmlHandler::GetCenteredBitmap (const wxString & param = wxT("bitmap"), const wxArtClient & defaultArtClient = wxART_OTHER, wxSize size = wxDefaultSize) protected
Definition at line 48 of file xtra_res.cpp.
References wxBitmap::ConvertToImage(), wxImage::GetAlpha(), wxImage::GetData(), wxBitmap::GetHeight(), wxSize::GetHeight(), wxSize::GetWidth(), wxBitmap::GetWidth(), wxImage::HasAlpha(), wxImage::Resize(), and wxDefaultSize.
Referenced by DoCreateResource().
Member Data Documentation
m_isAddon
bool wxToolBarAddOnXmlHandler::m_isAddon protected
Definition at line 26 of file xtra_res.h.
Referenced by DoCreateResource().
m_isInside
bool wxToolBarAddOnXmlHandler::m_isInside protected
Definition at line 25 of file xtra_res.h.
Referenced by CanHandle(), and DoCreateResource().
m_toolbar
wxToolBar* wxToolBarAddOnXmlHandler::m_toolbar protected
Definition at line 27 of file xtra_res.h.
Referenced by DoCreateResource().
The documentation for this class was generated from the following files:
xtra_res.h
xtra_res.cpp