Code::Blocks: DocumentationHelper Class Reference
DocumentationHelper Class Reference
#include <doxygen_parser.h>
Public Types
enum Command {
cmdNone, cmdDisplayToken, cmdSearch, cmdSearchAll,
cmdOpenDecl, cmdOpenImpl, cmdClose
}
Public Member Functions
DocumentationHelper (CodeCompletion *cc)
~DocumentationHelper ()
void OnAttach ()
void OnRelease ()
wxString GenerateHTML (int tokenIdx, TokenTree *tree)
wxString GenerateHTML (const TokenIdxSet &tokensIdx, TokenTree *tree)
void RereadOptions (ConfigManager *cfg)
void WriteOptions (ConfigManager *cfg)
bool IsEnabled ()
void SetEnabled (bool enabled)
wxString OnDocumentationLink (wxHtmlLinkEvent &event, bool &dismissPopup)
Static Public Member Functions
static wxString DoxygenToHTML (const wxString &doc)
static wxString ConvertTypeToAnchor (wxString fullType)
static wxString ConvertArgsToAnchors (wxString args)
static wxString ExtractTypeAndName (wxString type, wxString *outName=0)
static wxString CommandToAnchor (Command cmd, const wxString &name, const wxString *args=0)
static wxString CommandToAnchorInt (Command cmd, const wxString &name, int arg0)
static Command HrefToCommand (const wxString &href, wxString &args)
Static Public Attributes
static const wxChar separatorTag = _T('+')
static const wxString commandTag = _T("cmd=")
Protected Member Functions
void SaveTokenIdx ()
Protected Attributes
CodeCompletion * m_CC
Pointer to CodeComplete object.
int m_CurrentTokenIdx
Documentation of which token was previously displayed.
int m_LastTokenIdx
bool m_Enabled
Detailed Description
Definition at line 107 of file doxygen_parser.h.
Member Enumeration Documentation
Command
enum DocumentationHelper::Command
Enumerator
cmdNone
cmdDisplayToken
cmdSearch
cmdSearchAll
cmdOpenDecl
cmdOpenImpl
cmdClose
Definition at line 111 of file doxygen_parser.h.
Constructor & Destructor Documentation
DocumentationHelper()
DocumentationHelper::DocumentationHelper (CodeCompletion * cc)
Definition at line 644 of file doxygen_parser.cpp.
References _(), Manager::Get(), Manager::GetColourManager(), ColourManager::RegisterColour(), wxBLACK, wxBLUE, wxT, and wxWHITE.
~DocumentationHelper()
DocumentationHelper::~DocumentationHelper ()
Definition at line 656 of file doxygen_parser.cpp.
Member Function Documentation
CommandToAnchor()
wxString DocumentationHelper::CommandToAnchor (Command cmd, const wxString & name, const wxString * args = 0) static
Definition at line 600 of file doxygen_parser.cpp.
References _T, and wxString::Format().
Referenced by GenerateHTML().
CommandToAnchorInt()
wxString DocumentationHelper::CommandToAnchorInt (Command cmd, const wxString & name, int arg0) static
Definition at line 613 of file doxygen_parser.cpp.
References _T, and wxString::Format().
Referenced by GenerateHTML().
ConvertArgsToAnchors()
wxString DocumentationHelper::ConvertArgsToAnchors (wxString args) static
Definition at line 529 of file doxygen_parser.cpp.
References _T, wxString::clear(), wxString::find_last_of(), wxString::size(), and wxString::SubString().
Referenced by GenerateHTML().
ConvertTypeToAnchor()
wxString DocumentationHelper::ConvertTypeToAnchor (wxString fullType) static
Definition at line 517 of file doxygen_parser.cpp.
References _T, wxString::find(), Token::IsValidAncestor(), wxString::replace(), and wxString::size().
Referenced by GenerateHTML().
DoxygenToHTML()
wxString DocumentationHelper::DoxygenToHTML (const wxString & doc) static
Definition at line 408 of file doxygen_parser.cpp.
References _T, arg0, Doxygen::B, HTMLTags::b0, HTMLTags::br, Doxygen::BRIEF, Doxygen::CODE, Doxygen::ENDCODE, Doxygen::DoxygenParser::FindNextKeyword(), Doxygen::DoxygenParser::GetArgument(), wxStringTokenizer::GetNextToken(), Doxygen::DoxygenParser::GetPosition(), wxStringTokenizer::HasMoreTokens(), wxString::insert(), Doxygen::KEYWORDS_COUNT, Doxygen::NO_KEYWORD, Doxygen::PARAM, HTMLTags::pre0, HTMLTags::pre1, Doxygen::RANGE_PARAGRAPH, Doxygen::RANGE_WORD, wxString::Replace(), Doxygen::DoxygenParser::ReplaceCurrentKeyword(), wxString::reserve(), Doxygen::RESULT, Doxygen::RETURN, Doxygen::SA, Doxygen::SEE, Doxygen::SHORT, wxString::size(), HTMLTags::tab, and wxString::Trim().
Referenced by GenerateHTML().
ExtractTypeAndName()
wxString DocumentationHelper::ExtractTypeAndName (wxString tok, wxString * outName = 0) static
returns argument base type
Returns
type
Definition at line 548 of file doxygen_parser.cpp.
References _T, wxString::clear(), wxString::Find(), wxString::find_last_of(), wxString::GetChar(), wxString::insert(), wxString::npos, wxString::Replace(), wxString::resize(), wxString::size(), wxString::SubString(), wxString::swap(), and wxString::Trim().
GenerateHTML() [1/2]
wxString DocumentationHelper::GenerateHTML (int tokenIdx, TokenTree * tree)
Definition at line 673 of file doxygen_parser.cpp.
References _T, arg0, TokenTree::at(), HTMLTags::b0, HTMLTags::br, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, cmdClose, cmdDisplayToken, cmdOpenDecl, cmdOpenImpl, CommandToAnchor(), CommandToAnchorInt(), ConvertArgsToAnchors(), ConvertTypeToAnchor(), DoxygenToHTML(), wxString::Format(), Manager::Get(), wxColour::GetAsString(), ColourManager::GetColour(), Manager::GetColourManager(), TokenTree::GetDocumentation(), Token::GetFormattedArgs(), Token::GetNamespace(), Token::GetStrippedArgs(), Token::GetTokenKindString(), Token::GetTokenScopeString(), wxString::IsEmpty(), Token::m_Args, Token::m_Children, m_CurrentTokenIdx, Token::m_FullType, Token::m_ImplLine, Token::m_Index, Token::m_IsConst, Token::m_IsNoExcept, m_LastTokenIdx, Token::m_Name, Token::m_ParentIndex, Token::m_Scope, Token::m_TokenKind, wxString::RemoveLast(), s_TokenTreeMutex, HTMLTags::sep, wxString::size(), tkAnyContainer, tkAnyFunction, tkClass, tkConstructor, tkDestructor, tkEnum, tkEnumerator, tkFunction, tkMacroDef, tkMacroUse, tkNamespace, tkTypedef, tkUndefined, tkVariable, tsUndefined, wxC2S_HTML_SYNTAX, wxEmptyString, and wxT.
Referenced by GenerateHTML(), and OnDocumentationLink().
GenerateHTML() [2/2]
wxString DocumentationHelper::GenerateHTML (const TokenIdxSet & tokensIdx, TokenTree * tree)
Definition at line 841 of file doxygen_parser.cpp.
References _T, TokenTree::at(), CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, cmdClose, cmdDisplayToken, CommandToAnchor(), CommandToAnchorInt(), GenerateHTML(), Manager::Get(), wxColour::GetAsString(), ColourManager::GetColour(), Manager::GetColourManager(), Token::GetNamespace(), Token::GetTokenKindString(), Token::m_Index, m_LastTokenIdx, Token::m_Name, HTMLTags::nbsp, s_TokenTreeMutex, wxC2S_HTML_SYNTAX, wxEmptyString, and wxT.
HrefToCommand()
DocumentationHelper::Command DocumentationHelper::HrefToCommand (const wxString & href, wxString & args) static
Definition at line 619 of file doxygen_parser.cpp.
References _T, wxString::clear(), commandTag, wxString::npos, wxString::rfind(), separatorTag, wxString::size(), wxString::StartsWith(), wxString::SubString(), and wxString::ToLong().
Referenced by OnDocumentationLink().
IsEnabled()
bool DocumentationHelper::IsEnabled () inline
Definition at line 145 of file doxygen_parser.h.
OnAttach()
void DocumentationHelper::OnAttach ()
Definition at line 660 of file doxygen_parser.cpp.
References m_Enabled.
Referenced by RereadOptions().
OnDocumentationLink()
wxString DocumentationHelper::OnDocumentationLink (wxHtmlLinkEvent & event, bool & dismissPopup)
Definition at line 920 of file doxygen_parser.cpp.
References _T, TokenTree::at(), cmdClose, cmdDisplayToken, cmdNone, cmdOpenDecl, cmdOpenImpl, cmdSearch, cmdSearchAll, wxString::find_last_of(), TokenTree::FindMatches(), GenerateHTML(), Manager::Get(), Manager::GetEditorManager(), Token::GetFilename(), Token::GetImplFilename(), NativeParser::GetParser(), ParserBase::GetTokenTree(), cbEditor::GotoTokenPosition(), HrefToCommand(), m_CC, Token::m_ImplLine, Token::m_Line, Token::m_Name, CodeCompletion::m_NativeParser, wxString::npos, EditorManager::Open(), wxString::rfind(), SaveTokenIdx(), wxString::size(), wxString::StartsWith(), wxString::SubString(), tkAnyContainer, tkAnyFunction, tkEnum, tkMacroDef, tkUndefined, wxString::ToLong(), wxString::Truncate(), wxEmptyString, and wxLaunchDefaultBrowser().
OnRelease()
void DocumentationHelper::OnRelease ()
Definition at line 668 of file doxygen_parser.cpp.
Referenced by RereadOptions().
RereadOptions()
void DocumentationHelper::RereadOptions (ConfigManager * cfg)
Definition at line 892 of file doxygen_parser.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), m_Enabled, OnAttach(), OnRelease(), and ConfigManager::ReadBool().
Referenced by CCOptionsDlg::OnApply().
SaveTokenIdx()
void DocumentationHelper::SaveTokenIdx () protected
Definition at line 914 of file doxygen_parser.cpp.
References m_CurrentTokenIdx, and m_LastTokenIdx.
Referenced by OnDocumentationLink().
SetEnabled()
void DocumentationHelper::SetEnabled (bool enabled) inline
Definition at line 146 of file doxygen_parser.h.
Referenced by CCOptionsDlg::OnApply().
WriteOptions()
void DocumentationHelper::WriteOptions (ConfigManager * cfg)
Definition at line 906 of file doxygen_parser.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), m_Enabled, and ConfigManager::Write().
Referenced by CCOptionsDlg::OnApply().
Member Data Documentation
commandTag
const wxString DocumentationHelper::commandTag = _T("cmd=") static
Definition at line 133 of file doxygen_parser.h.
Referenced by HrefToCommand().
m_CC
CodeCompletion* DocumentationHelper::m_CC protected
Pointer to CodeComplete object.
Definition at line 156 of file doxygen_parser.h.
Referenced by OnDocumentationLink().
m_CurrentTokenIdx
int DocumentationHelper::m_CurrentTokenIdx protected
Documentation of which token was previously displayed.
Definition at line 158 of file doxygen_parser.h.
Referenced by GenerateHTML(), and SaveTokenIdx().
m_Enabled
bool DocumentationHelper::m_Enabled protected
Definition at line 160 of file doxygen_parser.h.
Referenced by OnAttach(), RereadOptions(), and WriteOptions().
m_LastTokenIdx
int DocumentationHelper::m_LastTokenIdx protected
Definition at line 158 of file doxygen_parser.h.
Referenced by GenerateHTML(), and SaveTokenIdx().
separatorTag
const wxChar DocumentationHelper::separatorTag = _T('+') static
Definition at line 132 of file doxygen_parser.h.
Referenced by HrefToCommand().
The documentation for this class was generated from the following files:
doxygen_parser.h
doxygen_parser.cpp