Code::Blocks: CdbCmd_GetPID Class Reference
CdbCmd_GetPID Class Reference
Command to find the PID of the active child.
#include <cdb_commands.h>
Public Member Functions
CdbCmd_GetPID (DebuggerDriver *driver)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to find the PID of the active child.
Definition at line 135 of file cdb_commands.h.
Constructor & Destructor Documentation
CdbCmd_GetPID()
CdbCmd_GetPID::CdbCmd_GetPID (DebuggerDriver * driver) inline
Parameters
file The file to debug.
Definition at line 139 of file cdb_commands.h.
References _T, and DebuggerCmd::m_Cmd.
Member Function Documentation
ParseOutput()
void CdbCmd_GetPID::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 144 of file cdb_commands.h.
References _T, GetArrayFromString(), wxArrayString::GetCount(), wxRegEx::GetMatch(), DebuggerCmd::m_pDriver, wxRegEx::Matches(), reProcessInf(), DebuggerDriver::SetChildPID(), and wxString::ToLong().
The documentation for this class was generated from the following file:
cdb_commands.h