Code::Blocks: wxScintillaEvent Class Reference
wxScintillaEvent Class Reference
#include <wxscintilla.h>
Public Member Functions
wxScintillaEvent (wxEventType commandType=0, int id=0)
wxScintillaEvent (const wxScintillaEvent &event)
~wxScintillaEvent ()
void SetPosition (int pos)
void SetKey (int k)
void SetModifiers (int m)
void SetModificationType (int t)
void SetText (const wxString &t)
Kept for backwards compatibility, use SetString().
void SetLength (int len)
void SetLinesAdded (int num)
void SetLine (int val)
void SetFoldLevelNow (int val)
void SetFoldLevelPrev (int val)
void SetMargin (int val)
void SetMessage (int val)
void SetWParam (int val)
void SetLParam (int val)
void SetListType (int val)
void SetX (int val)
void SetY (int val)
void SetToken (int val)
void SetAnnotationLinesAdded (int val)
void SetUpdated (int val)
void SetListCompletionMethod (int val)
void SetDragText (const wxString &val)
Kept for backwards compatibility, use SetString().
void SetDragFlags (int flags)
void SetDragResult (wxDragResult val)
void SetDragAllowMove (bool allow)
This method is kept mainly for backwards compatibility, use SetDragFlags() in the new code.
int GetPosition () const
int GetKey () const
int GetModifiers () const
int GetModificationType () const
wxString GetText () const
Kept for backwards compatibility, use GetString().
int GetLength () const
int GetLinesAdded () const
int GetLine () const
int GetFoldLevelNow () const
int GetFoldLevelPrev () const
int GetMargin () const
int GetMessage () const
int GetWParam () const
int GetLParam () const
int GetListType () const
int GetX () const
int GetY () const
int GetToken () const
int GetAnnotationsLinesAdded () const
int GetUpdated () const
int GetListCompletionMethod () const
wxString GetDragText ()
Kept for backwards compatibility, use GetString().
int GetDragFlags ()
wxDragResult GetDragResult ()
bool GetDragAllowMove ()
bool GetShift () const
bool GetControl () const
bool GetAlt () const
virtual wxEvent * Clone () const
Private Attributes
int m_position
int m_key
int m_modifiers
int m_modificationType
int m_length
int m_linesAdded
int m_line
int m_foldLevelNow
int m_foldLevelPrev
int m_margin
int m_message
int m_wParam
int m_lParam
int m_listType
int m_x
int m_y
int m_token
int m_annotationLinesAdded
int m_updated
int m_listCompletionMethod
int m_dragFlags
wxDragResult m_dragResult
Detailed Description
Definition at line 5407 of file wxscintilla.h.
Constructor & Destructor Documentation
wxScintillaEvent() [1/2]
wxScintillaEvent::wxScintillaEvent (wxEventType commandType = 0, int id = 0)
wxScintillaEvent() [2/2]
wxScintillaEvent::wxScintillaEvent (const wxScintillaEvent & event)
~wxScintillaEvent()
wxScintillaEvent::~wxScintillaEvent () inline
Definition at line 5413 of file wxscintilla.h.
Member Function Documentation
Clone()
virtual wxEvent* wxScintillaEvent::Clone () const inline virtual
Definition at line 5490 of file wxscintilla.h.
References wxScintillaEvent.
GetAlt()
bool wxScintillaEvent::GetAlt () const
GetAnnotationsLinesAdded()
int wxScintillaEvent::GetAnnotationsLinesAdded () const inline
Definition at line 5473 of file wxscintilla.h.
GetControl()
bool wxScintillaEvent::GetControl () const
GetDragAllowMove()
bool wxScintillaEvent::GetDragAllowMove () inline
Definition at line 5483 of file wxscintilla.h.
References wxDrag_AllowMove.
GetDragFlags()
int wxScintillaEvent::GetDragFlags () inline
Definition at line 5480 of file wxscintilla.h.
GetDragResult()
wxDragResult wxScintillaEvent::GetDragResult () inline
Definition at line 5481 of file wxscintilla.h.
GetDragText()
wxString wxScintillaEvent::GetDragText () inline
Kept for backwards compatibility, use GetString().
Definition at line 5479 of file wxscintilla.h.
GetFoldLevelNow()
int wxScintillaEvent::GetFoldLevelNow () const inline
Definition at line 5463 of file wxscintilla.h.
GetFoldLevelPrev()
int wxScintillaEvent::GetFoldLevelPrev () const inline
Definition at line 5464 of file wxscintilla.h.
Referenced by cbEditor::OnEditorModified().
GetKey()
int wxScintillaEvent::GetKey () const inline
Definition at line 5455 of file wxscintilla.h.
GetLength()
int wxScintillaEvent::GetLength () const inline
Definition at line 5460 of file wxscintilla.h.
GetLine()
int wxScintillaEvent::GetLine () const inline
Definition at line 5462 of file wxscintilla.h.
GetLinesAdded()
int wxScintillaEvent::GetLinesAdded () const inline
Definition at line 5461 of file wxscintilla.h.
GetListCompletionMethod()
int wxScintillaEvent::GetListCompletionMethod () const inline
Definition at line 5475 of file wxscintilla.h.
GetListType()
int wxScintillaEvent::GetListType () const inline
Definition at line 5469 of file wxscintilla.h.
GetLParam()
int wxScintillaEvent::GetLParam () const inline
Definition at line 5468 of file wxscintilla.h.
GetMargin()
int wxScintillaEvent::GetMargin () const inline
Definition at line 5465 of file wxscintilla.h.
Referenced by cbEditor::OnMarginClick().
GetMessage()
int wxScintillaEvent::GetMessage () const inline
Definition at line 5466 of file wxscintilla.h.
GetModificationType()
int wxScintillaEvent::GetModificationType () const inline
Definition at line 5457 of file wxscintilla.h.
Referenced by CodeCompletion::EditorEventHook(), CCManager::OnEditorHook(), and cbEditor::OnEditorModified().
GetModifiers()
int wxScintillaEvent::GetModifiers () const inline
Definition at line 5456 of file wxscintilla.h.
GetPosition()
int wxScintillaEvent::GetPosition () const inline
Definition at line 5454 of file wxscintilla.h.
Referenced by CCManager::OnEditorHook(), and cbEditor::OnEditorModified().
GetShift()
bool wxScintillaEvent::GetShift () const
GetText()
wxString wxScintillaEvent::GetText () const inline
Kept for backwards compatibility, use GetString().
Definition at line 5459 of file wxscintilla.h.
Referenced by CCManager::OnEditorHook().
GetToken()
int wxScintillaEvent::GetToken () const inline
Definition at line 5472 of file wxscintilla.h.
GetUpdated()
int wxScintillaEvent::GetUpdated () const inline
Definition at line 5474 of file wxscintilla.h.
Referenced by CCManager::OnEditorHook().
GetWParam()
int wxScintillaEvent::GetWParam () const inline
Definition at line 5467 of file wxscintilla.h.
GetX()
int wxScintillaEvent::GetX () const inline
Definition at line 5470 of file wxscintilla.h.
Referenced by cbEditor::OnEditorDwellStart().
GetY()
int wxScintillaEvent::GetY () const inline
Definition at line 5471 of file wxscintilla.h.
SetAnnotationLinesAdded()
void wxScintillaEvent::SetAnnotationLinesAdded (int val) inline
Definition at line 5434 of file wxscintilla.h.
SetDragAllowMove()
void wxScintillaEvent::SetDragAllowMove (bool allow) inline
This method is kept mainly for backwards compatibility, use SetDragFlags() in the new code.
Definition at line 5445 of file wxscintilla.h.
References wxDrag_AllowMove, and wxDrag_DefaultMove.
SetDragFlags()
void wxScintillaEvent::SetDragFlags (int flags) inline
Definition at line 5440 of file wxscintilla.h.
SetDragResult()
void wxScintillaEvent::SetDragResult (wxDragResult val) inline
Definition at line 5441 of file wxscintilla.h.
SetDragText()
void wxScintillaEvent::SetDragText (const wxString & val) inline
Kept for backwards compatibility, use SetString().
Definition at line 5439 of file wxscintilla.h.
SetFoldLevelNow()
void wxScintillaEvent::SetFoldLevelNow (int val) inline
Definition at line 5424 of file wxscintilla.h.
SetFoldLevelPrev()
void wxScintillaEvent::SetFoldLevelPrev (int val) inline
Definition at line 5425 of file wxscintilla.h.
SetKey()
void wxScintillaEvent::SetKey (int k) inline
Definition at line 5416 of file wxscintilla.h.
SetLength()
void wxScintillaEvent::SetLength (int len) inline
Definition at line 5421 of file wxscintilla.h.
SetLine()
void wxScintillaEvent::SetLine (int val) inline
Definition at line 5423 of file wxscintilla.h.
SetLinesAdded()
void wxScintillaEvent::SetLinesAdded (int num) inline
Definition at line 5422 of file wxscintilla.h.
SetListCompletionMethod()
void wxScintillaEvent::SetListCompletionMethod (int val) inline
Definition at line 5436 of file wxscintilla.h.
SetListType()
void wxScintillaEvent::SetListType (int val) inline
Definition at line 5430 of file wxscintilla.h.
SetLParam()
void wxScintillaEvent::SetLParam (int val) inline
Definition at line 5429 of file wxscintilla.h.
SetMargin()
void wxScintillaEvent::SetMargin (int val) inline
Definition at line 5426 of file wxscintilla.h.
SetMessage()
void wxScintillaEvent::SetMessage (int val) inline
Definition at line 5427 of file wxscintilla.h.
SetModificationType()
void wxScintillaEvent::SetModificationType (int t) inline
Definition at line 5418 of file wxscintilla.h.
SetModifiers()
void wxScintillaEvent::SetModifiers (int m) inline
Definition at line 5417 of file wxscintilla.h.
SetPosition()
void wxScintillaEvent::SetPosition (int pos) inline
Definition at line 5415 of file wxscintilla.h.
SetText()
void wxScintillaEvent::SetText (const wxString & t) inline
Kept for backwards compatibility, use SetString().
Definition at line 5420 of file wxscintilla.h.
Referenced by CCManager::OnCompleteCode().
SetToken()
void wxScintillaEvent::SetToken (int val) inline
Definition at line 5433 of file wxscintilla.h.
SetUpdated()
void wxScintillaEvent::SetUpdated (int val) inline
Definition at line 5435 of file wxscintilla.h.
SetWParam()
void wxScintillaEvent::SetWParam (int val) inline
Definition at line 5428 of file wxscintilla.h.
SetX()
void wxScintillaEvent::SetX (int val) inline
Definition at line 5431 of file wxscintilla.h.
Referenced by cbEditor::OnEditorDwellStart().
SetY()
void wxScintillaEvent::SetY (int val) inline
Definition at line 5432 of file wxscintilla.h.
Referenced by cbEditor::OnEditorDwellStart().
Member Data Documentation
m_annotationLinesAdded
int wxScintillaEvent::m_annotationLinesAdded private
Definition at line 5518 of file wxscintilla.h.
m_dragFlags
int wxScintillaEvent::m_dragFlags private
Definition at line 5523 of file wxscintilla.h.
m_dragResult
wxDragResult wxScintillaEvent::m_dragResult private
Definition at line 5524 of file wxscintilla.h.
m_foldLevelNow
int wxScintillaEvent::m_foldLevelNow private
Definition at line 5504 of file wxscintilla.h.
m_foldLevelPrev
int wxScintillaEvent::m_foldLevelPrev private
Definition at line 5505 of file wxscintilla.h.
m_key
int wxScintillaEvent::m_key private
Definition at line 5497 of file wxscintilla.h.
m_length
int wxScintillaEvent::m_length private
Definition at line 5501 of file wxscintilla.h.
m_line
int wxScintillaEvent::m_line private
Definition at line 5503 of file wxscintilla.h.
m_linesAdded
int wxScintillaEvent::m_linesAdded private
Definition at line 5502 of file wxscintilla.h.
m_listCompletionMethod
int wxScintillaEvent::m_listCompletionMethod private
Definition at line 5520 of file wxscintilla.h.
m_listType
int wxScintillaEvent::m_listType private
Definition at line 5513 of file wxscintilla.h.
m_lParam
int wxScintillaEvent::m_lParam private
Definition at line 5511 of file wxscintilla.h.
m_margin
int wxScintillaEvent::m_margin private
Definition at line 5507 of file wxscintilla.h.
m_message
int wxScintillaEvent::m_message private
Definition at line 5509 of file wxscintilla.h.
m_modificationType
int wxScintillaEvent::m_modificationType private
Definition at line 5500 of file wxscintilla.h.
m_modifiers
int wxScintillaEvent::m_modifiers private
Definition at line 5498 of file wxscintilla.h.
m_position
int wxScintillaEvent::m_position private
Definition at line 5496 of file wxscintilla.h.
m_token
int wxScintillaEvent::m_token private
Definition at line 5517 of file wxscintilla.h.
m_updated
int wxScintillaEvent::m_updated private
Definition at line 5519 of file wxscintilla.h.
m_wParam
int wxScintillaEvent::m_wParam private
Definition at line 5510 of file wxscintilla.h.
m_x
int wxScintillaEvent::m_x private
Definition at line 5514 of file wxscintilla.h.
m_y
int wxScintillaEvent::m_y private
Definition at line 5515 of file wxscintilla.h.
The documentation for this class was generated from the following file:
wxscintilla.h