Code::Blocks: cbProjectTreeImages Class Reference
cbProjectTreeImages Class Reference
#include <globals.h>
Static Public Member Functions
static wxImageList * MakeImageList ()
static int WorkspaceIconIndex (bool read_only=false)
static int ProjectIconIndex (bool read_only=false)
static int FolderIconIndex ()
static int VirtualFolderIconIndex ()
Detailed Description
Definition at line 113 of file globals.h.
Member Function Documentation
FolderIconIndex()
int cbProjectTreeImages::FolderIconIndex () static
Returns
The folder icon index in the image list.
Definition at line 1528 of file globals.cpp.
References fvsFolder.
Referenced by ProjectManagerUI::BuildProjectTree(), and ProjectManagerUI::CheckForExternallyModifiedProjects().
MakeImageList()
wxImageList * cbProjectTreeImages::MakeImageList () static
Definition at line 1464 of file globals.cpp.
References cbLoadBitmap(), and ConfigManager::ReadDataPath().
ProjectIconIndex()
int cbProjectTreeImages::ProjectIconIndex (bool read_only = false) static
Returns
The project icon index in the image list.
Parameters
read_only Return the read-only icon for a project?
Definition at line 1520 of file globals.cpp.
References fvsProject, and fvsProjectReadOnly.
Referenced by ProjectManagerUI::BuildProjectTree().
VirtualFolderIconIndex()
int cbProjectTreeImages::VirtualFolderIconIndex () static
Returns
The virtual folder icon index in the image list.
Definition at line 1533 of file globals.cpp.
References fvsVirtualFolder.
Referenced by ProjectManagerUI::BuildProjectTree(), and ProjectManagerUI::CheckForExternallyModifiedProjects().
WorkspaceIconIndex()
int cbProjectTreeImages::WorkspaceIconIndex (bool read_only = false) static
Returns
The workspace icon index in the image list.
Parameters
read_only Return the read-only icon for a workspace?
Definition at line 1512 of file globals.cpp.
References fvsWorkspace, and fvsWorkspaceReadOnly.
Referenced by ProjectManagerUI::RebuildTree().
The documentation for this class was generated from the following files:
globals.h
globals.cpp