Code::Blocks: DebuggerDriver Class Reference
DebuggerDriver Class Reference abstract
#include <debuggerdriver.h>
Public Types
enum QueuePriority { Low = 0, High }
The priority used when adding a command in the queue.
typedef std::vector< cb::shared_ptr< cbStackFrame > > StackFrameContainer
typedef std::vector< cb::shared_ptr< cbThread > > ThreadsContainer
Public Member Functions
DebuggerDriver (DebuggerGDB *plugin)
virtual ~DebuggerDriver ()
void Log (const wxString &msg)
void DebugLog (const wxString &msg)
DebuggerGDB * GetDebugger ()
virtual void AddDirectory (const wxString &dir)
Add a directory in search list.
virtual void ClearDirectories ()
Clear directories search list.
virtual void SetWorkingDirectory (const wxString &dir)
Set the working directory.
virtual void SetArguments (const wxString &args)
Set the execution arguments.
virtual wxString GetCommandLine (const wxString &debugger, const wxString &debuggee, const wxString &userArguments)=0
Get the command-line to launch the debugger.
virtual wxString GetCommandLine (const wxString &debugger, int pid, const wxString &userArguments)=0
Get the command-line to launch the debugger.
virtual void SetTarget (ProjectBuildTarget *target)=0
Sets the target.
virtual void Prepare (bool isConsole, int printElements)=0
Prepares the debugging process by setting up search dirs etc.
virtual void Start (bool breakOnEntry)=0
Begin the debugging process by launching a program.
virtual void Stop ()=0
Stop debugging.
virtual void Continue ()=0
virtual void Step ()=0
virtual void StepInstruction ()=0
virtual void StepIntoInstruction ()=0
virtual void StepIn ()=0
virtual void StepOut ()=0
virtual void SetNextStatement (const wxString &filename, int line)=0
virtual void Backtrace ()=0
virtual void Disassemble ()=0
virtual void CPURegisters ()=0
virtual void SwitchToFrame (size_t number)=0
virtual void SetVarValue (const wxString &var, const wxString &value)=0
virtual void MemoryDump ()=0
virtual void RunningThreads ()=0
virtual void InfoFrame ()=0
virtual void InfoDLL ()=0
virtual void InfoFiles ()=0
virtual void InfoFPU ()=0
virtual void InfoSignals ()=0
virtual void EnableCatchingThrow (bool enable)=0
virtual void AddBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp)=0
Add a breakpoint.
virtual void RemoveBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp)=0
Remove a breakpoint.
virtual void EvaluateSymbol (const wxString &symbol, const wxRect &tipRect)=0
Evaluate a symbol.
virtual void UpdateWatches (cb::shared_ptr< GDBWatch > localsWatch, cb::shared_ptr< GDBWatch > funcArgsWatch, WatchesContainer &watches)=0
Update watches.
virtual void UpdateWatch (cb::shared_ptr< GDBWatch > const &watch)=0
virtual void UpdateWatchLocalsArgs (cb::shared_ptr< GDBWatch > const &watch, bool locals)=0
virtual void Attach (int pid)=0
Attach to process.
virtual void Detach ()=0
Detach from running process.
virtual void ParseOutput (const wxString &output)=0
Parse debugger's output.
virtual bool IsDebuggingStarted () const =0
Is debugging started.
bool IsProgramStopped () const
Is the program stopped?
void MarkProgramStopped (bool stopped)
bool IsQueueBusy () const
Is the driver processing some commands?
void SetChildPID (long pid)
Set child PID (debuggee's).
long GetChildPID () const
Get the child's (debuggee's) PID.
virtual void SwitchThread (size_t threadIndex)=0
Request to switch to another thread.
virtual bool UseDebugBreakProcess ()=0
Ask the driver if the debugger should be interrupted with DebugBreakProcess or Ctrl+C event.
wxString GetDebuggersWorkingDirectory () const
void ShowFile (const wxString &file, int line)
Show a file/line without changing the cursor.
void QueueCommand (DebuggerCmd *dcmd, QueuePriority prio=Low)
add a command in the queue. The DebuggerCmd will be deleted automatically when finished.
DebuggerCmd * CurrentCommand ()
returns the currently executing command
void RunQueue ()
runs the next command in the queue, if it is idle
void RemoveTopCommand (bool deleteIt=true)
removes the top command (it has finished)
const StackFrameContainer & GetStackFrames () const
returns the container with the current backtrace
StackFrameContainer & GetStackFrames ()
returns the container with the current backtrace
const ThreadsContainer & GetThreads () const
returns the thread container with the current list of threads
ThreadsContainer & GetThreads ()
returns the thread container with the current list of threads
const Cursor & GetCursor () const
Get debugger's cursor.
void SetCursor (const Cursor &cursor)
Set debugger's cursor.
void ResetCurrentFrame ()
int GetCurrentFrame () const
int GetUserSelectedFrame () const
void SetCurrentFrame (int number, bool user_selected)
void NotifyDebuggeeContinued ()
void NotifyCursorChanged ()
Called by implementations to notify cursor changes.
Protected Member Functions
void ResetCursor ()
Called by implementations to reset the cursor.
Protected Attributes
DebuggerGDB * m_pDBG
wxArrayString m_Dirs
wxString m_WorkingDir
wxString m_Args
bool m_ProgramIsStopped
wxString m_LastCursorAddress
Cursor m_Cursor
long m_ChildPID
DebuggerCommands m_DCmds
bool m_QueueBusy
StackFrameContainer m_backtrace
ThreadsContainer m_threads
int m_currentFrameNo
int m_userSelectedFrameNo
Detailed Description
Definition at line 31 of file debuggerdriver.h.
Member Typedef Documentation
StackFrameContainer
typedef std::vector<cb::shared_ptr<cbStackFrame> > DebuggerDriver::StackFrameContainer
Definition at line 43 of file debuggerdriver.h.
ThreadsContainer
typedef std::vector<cb::shared_ptr<cbThread> > DebuggerDriver::ThreadsContainer
Definition at line 44 of file debuggerdriver.h.
Member Enumeration Documentation
QueuePriority
enum DebuggerDriver::QueuePriority
The priority used when adding a command in the queue.
Low appends the new command in the queue, i.e. last in the queue. High inserts the command at the top of the queue.
Enumerator
Low
High
Definition at line 38 of file debuggerdriver.h.
Constructor & Destructor Documentation
DebuggerDriver()
DebuggerDriver::DebuggerDriver (DebuggerGDB * plugin)
Definition at line 16 of file debuggerdriver.cpp.
~DebuggerDriver()
DebuggerDriver::~DebuggerDriver () virtual
Definition at line 27 of file debuggerdriver.cpp.
References m_DCmds.
Member Function Documentation
AddBreakpoint()
virtual void DebuggerDriver::AddBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp) pure virtual
Add a breakpoint.
Parameters
bp The breakpoint to add.
editor The editor this breakpoint is set (might be NULL).
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerState::AddBreakpoint(), DebuggerState::ApplyBreakpoints(), GetDebugger(), DebuggerState::ResetBreakpoint(), and DebuggerState::ShiftBreakpoint().
AddDirectory()
void DebuggerDriver::AddDirectory (const wxString & dir) virtual
Add a directory in search list.
Definition at line 50 of file debuggerdriver.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_Dirs, and wxNOT_FOUND.
Referenced by DebuggerGDB::AddSourceDir(), and GetDebugger().
Attach()
virtual void DebuggerDriver::Attach (int pid) pure virtual
Attach to process.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DoDebug(), and GetDebugger().
Backtrace()
virtual void DebuggerDriver::Backtrace () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
ClearDirectories()
void DebuggerDriver::ClearDirectories () virtual
Clear directories search list.
Definition at line 45 of file debuggerdriver.cpp.
References wxArrayString::Clear(), and m_Dirs.
Referenced by DebuggerGDB::DoDebug(), and GetDebugger().
Continue()
virtual void DebuggerDriver::Continue () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), GdbCmd_AddBreakpointCondition::ParseOutput(), and DebuggerGDB::RunCommand().
CPURegisters()
virtual void DebuggerDriver::CPURegisters () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
CurrentCommand()
DebuggerCmd * DebuggerDriver::CurrentCommand ()
returns the currently executing command
Definition at line 118 of file debuggerdriver.cpp.
References m_DCmds.
Referenced by GetChildPID(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), and RunQueue().
DebugLog()
void DebuggerDriver::DebugLog (const wxString & msg)
Definition at line 40 of file debuggerdriver.cpp.
References cbDebuggerPlugin::DebugLog(), and m_pDBG.
Referenced by GdbCmd_TooltipEvaluation::GdbCmd_TooltipEvaluation(), and GdbCmd_TooltipEvaluation::ParseOutput().
Detach()
virtual void DebuggerDriver::Detach () pure virtual
Detach from running process.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DetachFromProcess(), and GetDebugger().
Disassemble()
virtual void DebuggerDriver::Disassemble () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
EnableCatchingThrow()
virtual void DebuggerDriver::EnableCatchingThrow (bool enable) pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::OnCatchThrow().
EvaluateSymbol()
virtual void DebuggerDriver::EvaluateSymbol (const wxString & symbol, const wxRect & tipRect) pure virtual
Evaluate a symbol.
Parameters
symbol The symbol to evaluate.
tipRect The rect to use for the tip window.
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::OnValueTooltip().
GetChildPID()
long DebuggerDriver::GetChildPID () const inline
Get the child's (debuggee's) PID.
Definition at line 164 of file debuggerdriver.h.
References CurrentCommand(), GetDebuggersWorkingDirectory(), GetStackFrames(), GetThreads(), Low, m_ChildPID, QueueCommand(), RemoveTopCommand(), RunQueue(), ShowFile(), SwitchThread(), and UseDebugBreakProcess().
Referenced by DebuggerGDB::DoBreak(), and DebuggerGDB::Stop().
GetCommandLine() [1/2]
virtual wxString DebuggerDriver::GetCommandLine (const wxString & debugger, const wxString & debuggee, const wxString & userArguments) pure virtual
Get the command-line to launch the debugger.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DoDebug(), and GetDebugger().
GetCommandLine() [2/2]
virtual wxString DebuggerDriver::GetCommandLine (const wxString & debugger, int pid, const wxString & userArguments) pure virtual
Get the command-line to launch the debugger.
Implemented in GDB_driver, and CDB_driver.
GetCurrentFrame()
int DebuggerDriver::GetCurrentFrame () const inline
Definition at line 194 of file debuggerdriver.h.
References m_currentFrameNo.
Referenced by DebuggerGDB::GetActiveStackFrame().
GetCursor()
const Cursor& DebuggerDriver::GetCursor () const inline
Get debugger's cursor.
Definition at line 189 of file debuggerdriver.h.
References m_Cursor.
Referenced by GdbCmd_DisassemblyInit::GdbCmd_DisassemblyInit(), DebuggerGDB::GetCurrentPosition(), DebuggerGDB::OnCursorChanged(), GdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_FindCursor::ParseOutput().
GetDebugger()
DebuggerGDB* DebuggerDriver::GetDebugger () inline
Definition at line 52 of file debuggerdriver.h.
References AddBreakpoint(), AddDirectory(), Attach(), Backtrace(), ClearDirectories(), Continue(), CPURegisters(), Detach(), Disassemble(), EnableCatchingThrow(), EvaluateSymbol(), GetCommandLine(), InfoDLL(), InfoFiles(), InfoFPU(), InfoFrame(), InfoSignals(), IsDebuggingStarted(), m_pDBG, MemoryDump(), ParseOutput(), Prepare(), RemoveBreakpoint(), RunningThreads(), SetArguments(), SetNextStatement(), SetTarget(), SetVarValue(), SetWorkingDirectory(), Start(), Step(), StepIn(), StepInstruction(), StepIntoInstruction(), StepOut(), Stop(), SwitchToFrame(), UpdateWatch(), UpdateWatches(), and UpdateWatchLocalsArgs().
Referenced by GdbCmd_TooltipEvaluation::ParseOutput().
GetDebuggersWorkingDirectory()
wxString DebuggerDriver::GetDebuggersWorkingDirectory () const
Definition at line 61 of file debuggerdriver.cpp.
References m_WorkingDir, wxGetCwd(), and wxSetWorkingDirectory().
Referenced by DebuggerGDB::DoDebug(), and GetChildPID().
GetStackFrames() [1/2]
DebuggerDriver::StackFrameContainer const & DebuggerDriver::GetStackFrames () const
returns the container with the current backtrace
Definition at line 164 of file debuggerdriver.cpp.
References m_backtrace.
Referenced by GetChildPID(), DebuggerGDB::GetStackFrame(), DebuggerGDB::GetStackFrameCount(), CdbCmd_Backtrace::ParseOutput(), and GdbCmd_Backtrace::ParseOutput().
GetStackFrames() [2/2]
DebuggerDriver::StackFrameContainer & DebuggerDriver::GetStackFrames ()
returns the container with the current backtrace
Definition at line 169 of file debuggerdriver.cpp.
References m_backtrace.
GetThreads() [1/2]
const DebuggerDriver::ThreadsContainer & DebuggerDriver::GetThreads () const
returns the thread container with the current list of threads
Definition at line 174 of file debuggerdriver.cpp.
References m_threads.
Referenced by GetChildPID(), DebuggerGDB::GetThread(), DebuggerGDB::GetThreadsCount(), GdbCmd_Threads::ParseOutput(), and DebuggerGDB::SwitchToThread().
GetThreads() [2/2]
DebuggerDriver::ThreadsContainer & DebuggerDriver::GetThreads ()
returns the thread container with the current list of threads
Definition at line 179 of file debuggerdriver.cpp.
References m_threads.
GetUserSelectedFrame()
int DebuggerDriver::GetUserSelectedFrame () const inline
Definition at line 195 of file debuggerdriver.h.
References m_userSelectedFrameNo, NotifyCursorChanged(), NotifyDebuggeeContinued(), ResetCursor(), and SetCurrentFrame().
Referenced by GdbCmd_Backtrace::ParseOutput().
InfoDLL()
virtual void DebuggerDriver::InfoDLL () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::OnInfoDLL().
InfoFiles()
virtual void DebuggerDriver::InfoFiles () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::OnInfoFiles().
InfoFPU()
virtual void DebuggerDriver::InfoFPU () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::OnInfoFPU().
InfoFrame()
virtual void DebuggerDriver::InfoFrame () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::OnInfoFrame().
InfoSignals()
virtual void DebuggerDriver::InfoSignals () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::OnInfoSignals().
IsDebuggingStarted()
virtual bool DebuggerDriver::IsDebuggingStarted () const pure virtual
Is debugging started.
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::ShowValueTooltip().
IsProgramStopped()
bool DebuggerDriver::IsProgramStopped () const inline
Is the program stopped?
Definition at line 157 of file debuggerdriver.h.
References m_ProgramIsStopped.
Referenced by DebuggerGDB::IsStopped(), and RunQueue().
IsQueueBusy()
bool DebuggerDriver::IsQueueBusy () const inline
Is the driver processing some commands?
Definition at line 160 of file debuggerdriver.h.
References m_QueueBusy.
Referenced by DebuggerGDB::IsBusy().
Log()
void DebuggerDriver::Log (const wxString & msg)
Definition at line 35 of file debuggerdriver.cpp.
References cbDebuggerPlugin::Log(), and m_pDBG.
Referenced by GdbCmd_AttachToProcess::GdbCmd_AttachToProcess(), GdbCmd_RemoteBaud::GdbCmd_RemoteBaud(), GdbCmd_RemoteTarget::GdbCmd_RemoteTarget(), CdbCmd_AddSourceDir::ParseOutput(), CDB_driver::ParseOutput(), DebuggerCmd::ParseOutput(), CdbCmd_SetDebuggee::ParseOutput(), GDB_driver::ParseOutput(), CdbCmd_AddSymbolFile::ParseOutput(), CdbCmd_AttachToProcess::ParseOutput(), CdbCmd_Detach::ParseOutput(), GdbCmd_AddSourceDir::ParseOutput(), GdbCmd_SetDebuggee::ParseOutput(), CdbCmd_AddBreakpoint::ParseOutput(), GdbCmd_AddSymbolFile::ParseOutput(), CdbCmd_RemoveBreakpoint::ParseOutput(), GdbCmd_AttachToProcess::ParseOutput(), GdbCmd_Detach::ParseOutput(), GdbCmd_AddBreakpoint::ParseOutput(), GdbCmd_AddDataBreakpoint::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_RemoveBreakpoint::ParseOutput(), GdbCmd_Start::ParseOutput(), GdbCmd_ChangeFrame::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_RemoteTarget::ParseOutput(), and GdbCmd_StepOrNextInstruction::ParseOutput().
MarkProgramStopped()
void DebuggerDriver::MarkProgramStopped (bool stopped) inline
Definition at line 158 of file debuggerdriver.h.
References m_ProgramIsStopped.
Referenced by GdbCmd_Start::ParseOutput().
MemoryDump()
virtual void DebuggerDriver::MemoryDump () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
NotifyCursorChanged()
void DebuggerDriver::NotifyCursorChanged ()
Called by implementations to notify cursor changes.
Definition at line 83 of file debuggerdriver.cpp.
References Cursor::address, Cursor::changed, DEBUGGER_CURSOR_CHANGED, m_Cursor, m_LastCursorAddress, and m_pDBG.
Referenced by GDB_driver::AddBreakpoint(), GetUserSelectedFrame(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), CdbCmd_Backtrace::ParseOutput(), CdbCmd_SwitchFrame::ParseOutput(), GdbCmd_FindCursor::ParseOutput(), and DebuggerGDB::RunCommand().
NotifyDebuggeeContinued()
void DebuggerDriver::NotifyDebuggeeContinued ()
Definition at line 92 of file debuggerdriver.cpp.
References DebuggerGDB::DebuggeeContinued(), m_pDBG, and ResetCursor().
Referenced by CdbCmd_Continue::Action(), GdbCmd_Continue::Action(), and GetUserSelectedFrame().
ParseOutput()
virtual void DebuggerDriver::ParseOutput (const wxString & output) pure virtual
Parse debugger's output.
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::ParseOutput().
Prepare()
virtual void DebuggerDriver::Prepare (bool isConsole, int printElements) pure virtual
Prepares the debugging process by setting up search dirs etc.
Parameters
isConsole If true, the debuggee is a console executable.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DoDebug(), and GetDebugger().
QueueCommand()
void DebuggerDriver::QueueCommand (DebuggerCmd * dcmd, QueuePriority prio = Low)
add a command in the queue. The DebuggerCmd will be deleted automatically when finished.
Definition at line 108 of file debuggerdriver.cpp.
References Low, m_DCmds, and RunQueue().
Referenced by CDB_driver::AddBreakpoint(), GDB_driver::AddBreakpoint(), GDB_driver::Attach(), GDB_driver::Backtrace(), CDB_driver::Continue(), GDB_driver::Continue(), CDB_driver::CPURegisters(), GDB_driver::CPURegisters(), CDB_driver::Detach(), GDB_driver::Detach(), CDB_driver::Disassemble(), GDB_driver::Disassemble(), CDB_driver::DoBacktrace(), DebuggerGDB::DoDebug(), GDB_driver::EnableCatchingThrow(), CDB_driver::EvaluateSymbol(), GDB_driver::EvaluateSymbol(), GdbCmd_FindTooltipAddress::GdbCmd_FindTooltipAddress(), GetChildPID(), GDB_driver::HandleMainBreakPoint(), GDB_driver::InfoDLL(), GDB_driver::InfoFiles(), GDB_driver::InfoFPU(), GDB_driver::InfoFrame(), GDB_driver::InfoSignals(), GDB_driver::InitializeScripting(), GDB_driver::MemoryDump(), DebuggerGDB::OnPrintElements(), GDB_driver::ParseOutput(), CdbCmd_AttachToProcess::ParseOutput(), GdbCmd_AttachToProcess::ParseOutput(), GdbCmd_AddBreakpointCondition::ParseOutput(), GdbCmd_AddBreakpoint::ParseOutput(), GdbCmd_AddDataBreakpoint::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_Start::ParseOutput(), GdbCmd_FindWatchType::ParseOutput(), GdbCmd_FindTooltipAddress::ParseOutput(), GdbCmd_FindTooltipType::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_StepOrNextInstruction::ParseOutput(), CDB_driver::Prepare(), GDB_driver::Prepare(), CDB_driver::RemoveBreakpoint(), GDB_driver::RemoveBreakpoint(), GDB_driver::RunningThreads(), DebuggerGDB::SendCommand(), GDB_driver::SetNextStatement(), GDB_driver::SetVarValue(), CDB_driver::Start(), GDB_driver::Start(), CDB_driver::Step(), GDB_driver::Step(), CDB_driver::StepIn(), GDB_driver::StepIn(), GDB_driver::StepInstruction(), GDB_driver::StepIntoInstruction(), CDB_driver::StepOut(), GDB_driver::StepOut(), CDB_driver::Stop(), GDB_driver::Stop(), GDB_driver::SwitchThread(), CDB_driver::SwitchToFrame(), GDB_driver::SwitchToFrame(), CDB_driver::UpdateWatch(), GDB_driver::UpdateWatch(), CDB_driver::UpdateWatches(), GDB_driver::UpdateWatches(), and GDB_driver::UpdateWatchLocalsArgs().
RemoveBreakpoint()
virtual void DebuggerDriver::RemoveBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp) pure virtual
Remove a breakpoint.
Parameters
bp The breakpoint to remove. If NULL, all reakpoints are removed.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerState::ApplyBreakpoints(), DebuggerState::CleanUp(), GetDebugger(), GdbCmd_AddBreakpointCondition::ParseOutput(), DebuggerState::RemoveAllBreakpoints(), DebuggerState::RemoveAllProjectBreakpoints(), DebuggerState::RemoveBreakpoint(), DebuggerState::ResetBreakpoint(), and DebuggerState::ShiftBreakpoint().
RemoveTopCommand()
void DebuggerDriver::RemoveTopCommand (bool deleteIt = true)
removes the top command (it has finished)
Definition at line 153 of file debuggerdriver.cpp.
References m_DCmds, and m_QueueBusy.
Referenced by GetChildPID(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), and RunQueue().
ResetCurrentFrame()
void DebuggerDriver::ResetCurrentFrame ()
Definition at line 191 of file debuggerdriver.cpp.
References Manager::Get(), DebuggerManager::GetBacktraceDialog(), Manager::GetDebuggerManager(), m_currentFrameNo, m_userSelectedFrameNo, and cbBacktraceDlg::Reload().
Referenced by DebuggerGDB::RunCommand(), and SetCursor().
ResetCursor()
void DebuggerDriver::ResetCursor () protected
Called by implementations to reset the cursor.
Definition at line 98 of file debuggerdriver.cpp.
References Cursor::address, Cursor::changed, wxString::Clear(), Cursor::file, Cursor::function, Cursor::line, m_Cursor, and m_LastCursorAddress.
Referenced by CDB_driver::Continue(), GDB_driver::Continue(), GetUserSelectedFrame(), NotifyDebuggeeContinued(), GDB_driver::SetNextStatement(), GDB_driver::Start(), CDB_driver::Step(), GDB_driver::Step(), CDB_driver::StepIn(), GDB_driver::StepIn(), GDB_driver::StepInstruction(), GDB_driver::StepIntoInstruction(), CDB_driver::StepOut(), GDB_driver::StepOut(), CDB_driver::Stop(), GDB_driver::Stop(), GDB_driver::SwitchThread(), CDB_driver::SwitchToFrame(), and GDB_driver::SwitchToFrame().
RunningThreads()
virtual void DebuggerDriver::RunningThreads () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
RunQueue()
void DebuggerDriver::RunQueue ()
runs the next command in the queue, if it is idle
Definition at line 123 of file debuggerdriver.cpp.
References DebuggerCmd::Action(), CurrentCommand(), DebuggerGDB::DoSendCommand(), DebuggerCmd::IsContinueCommand(), wxString::IsEmpty(), IsProgramStopped(), DebuggerCmd::m_Cmd, m_DCmds, m_pDBG, m_ProgramIsStopped, m_QueueBusy, and RemoveTopCommand().
Referenced by GetChildPID(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), and QueueCommand().
SetArguments()
void DebuggerDriver::SetArguments (const wxString & args) virtual
Set the execution arguments.
Definition at line 70 of file debuggerdriver.cpp.
References m_Args.
Referenced by DebuggerGDB::DoDebug(), and GetDebugger().
SetChildPID()
void DebuggerDriver::SetChildPID (long pid) inline
Set child PID (debuggee's).
Usually set by debugger commands.
Definition at line 162 of file debuggerdriver.h.
References m_ChildPID.
Referenced by GDB_driver::Attach(), GDB_driver::ParseOutput(), CdbCmd_GetPID::ParseOutput(), CdbCmd_AttachToProcess::ParseOutput(), and GdbCmd_InfoProgram::ParseOutput().
SetCurrentFrame()
void DebuggerDriver::SetCurrentFrame (int number, bool user_selected)
Definition at line 184 of file debuggerdriver.cpp.
References m_currentFrameNo, and m_userSelectedFrameNo.
Referenced by GetUserSelectedFrame(), GdbCmd_Backtrace::ParseOutput(), and DebuggerGDB::SwitchToFrame().
SetCursor()
void DebuggerDriver::SetCursor (const Cursor & cursor) inline
Set debugger's cursor.
Definition at line 191 of file debuggerdriver.h.
References m_Cursor, and ResetCurrentFrame().
Referenced by CdbCmd_Backtrace::ParseOutput(), CdbCmd_SwitchFrame::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_FindCursor::ParseOutput().
SetNextStatement()
virtual void DebuggerDriver::SetNextStatement (const wxString & filename, int line) pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::SetNextStatement().
SetTarget()
virtual void DebuggerDriver::SetTarget (ProjectBuildTarget * target) pure virtual
Sets the target.
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerState::StartDriver().
SetVarValue()
virtual void DebuggerDriver::SetVarValue (const wxString & var, const wxString & value) pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::SetWatchValue().
SetWorkingDirectory()
void DebuggerDriver::SetWorkingDirectory (const wxString & dir) virtual
Set the working directory.
Definition at line 56 of file debuggerdriver.cpp.
References m_WorkingDir.
Referenced by DebuggerGDB::DoDebug(), and GetDebugger().
ShowFile()
void DebuggerDriver::ShowFile (const wxString & file, int line)
Show a file/line without changing the cursor.
Definition at line 75 of file debuggerdriver.cpp.
References DEBUGGER_SHOW_FILE_LINE, and m_pDBG.
Referenced by GetChildPID(), and GdbCmd_Backtrace::ParseOutput().
Start()
virtual void DebuggerDriver::Start (bool breakOnEntry) pure virtual
Begin the debugging process by launching a program.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DoDebug(), and GetDebugger().
Step()
virtual void DebuggerDriver::Step () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
StepIn()
virtual void DebuggerDriver::StepIn () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
StepInstruction()
virtual void DebuggerDriver::StepInstruction () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
StepIntoInstruction()
virtual void DebuggerDriver::StepIntoInstruction () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
StepOut()
virtual void DebuggerDriver::StepOut () pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::RunCommand().
Stop()
virtual void DebuggerDriver::Stop () pure virtual
Stop debugging.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DetachFromProcess(), GetDebugger(), and DebuggerGDB::RunCommand().
SwitchThread()
virtual void DebuggerDriver::SwitchThread (size_t threadIndex) pure virtual
Request to switch to another thread.
Implemented in GDB_driver.
Referenced by GetChildPID(), and DebuggerGDB::SwitchToThread().
SwitchToFrame()
virtual void DebuggerDriver::SwitchToFrame (size_t number) pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::SwitchToFrame().
UpdateWatch()
virtual void DebuggerDriver::UpdateWatch (cb::shared_ptr< GDBWatch > const & watch) pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::AddWatch(), GetDebugger(), and DebuggerGDB::UpdateWatch().
UpdateWatches()
virtual void DebuggerDriver::UpdateWatches (cb::shared_ptr< GDBWatch > localsWatch, cb::shared_ptr< GDBWatch > funcArgsWatch, WatchesContainer & watches) pure virtual
Update watches.
Parameters
doLocals Display values of local variables.
doArgs Display values of function arguments.
tree The watches tree control.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DoWatches(), and GetDebugger().
UpdateWatchLocalsArgs()
virtual void DebuggerDriver::UpdateWatchLocalsArgs (cb::shared_ptr< GDBWatch > const & watch, bool locals) pure virtual
Implemented in GDB_driver, and CDB_driver.
Referenced by GetDebugger(), and DebuggerGDB::UpdateWatch().
UseDebugBreakProcess()
virtual bool DebuggerDriver::UseDebugBreakProcess () pure virtual
Ask the driver if the debugger should be interrupted with DebugBreakProcess or Ctrl+C event.
Implemented in GDB_driver, and CDB_driver.
Referenced by DebuggerGDB::DoBreak(), DebuggerGDB::DoDebug(), and GetChildPID().
Member Data Documentation
m_Args
wxString DebuggerDriver::m_Args protected
Definition at line 211 of file debuggerdriver.h.
Referenced by GDB_driver::Prepare(), and SetArguments().
m_backtrace
StackFrameContainer DebuggerDriver::m_backtrace protected
Definition at line 224 of file debuggerdriver.h.
Referenced by GetStackFrames().
m_ChildPID
long DebuggerDriver::m_ChildPID protected
Definition at line 218 of file debuggerdriver.h.
Referenced by GetChildPID(), GDB_driver::ParseOutput(), and SetChildPID().
m_currentFrameNo
int DebuggerDriver::m_currentFrameNo protected
Definition at line 226 of file debuggerdriver.h.
Referenced by GetCurrentFrame(), ResetCurrentFrame(), and SetCurrentFrame().
m_Cursor
Cursor DebuggerDriver::m_Cursor protected
Definition at line 216 of file debuggerdriver.h.
Referenced by GetCursor(), GDB_driver::HandleMainBreakPoint(), NotifyCursorChanged(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), ResetCursor(), and SetCursor().
m_DCmds
DebuggerCommands DebuggerDriver::m_DCmds protected
Definition at line 221 of file debuggerdriver.h.
Referenced by CurrentCommand(), GDB_driver::ParseOutput(), QueueCommand(), RemoveTopCommand(), RunQueue(), and ~DebuggerDriver().
m_Dirs
wxArrayString DebuggerDriver::m_Dirs protected
Definition at line 209 of file debuggerdriver.h.
Referenced by AddDirectory(), ClearDirectories(), CDB_driver::GetCommonCommandLine(), and GDB_driver::Prepare().
m_LastCursorAddress
wxString DebuggerDriver::m_LastCursorAddress protected
Definition at line 215 of file debuggerdriver.h.
Referenced by NotifyCursorChanged(), and ResetCursor().
m_pDBG
DebuggerGDB* DebuggerDriver::m_pDBG protected
Definition at line 206 of file debuggerdriver.h.
Referenced by DebugLog(), GDB_driver::GetCommandLine(), GetDebugger(), GDB_driver::GetRemoteDebuggingInfo(), GDB_driver::HandleMainBreakPoint(), GDB_driver::InitializeScripting(), Log(), NotifyCursorChanged(), NotifyDebuggeeContinued(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), GDB_driver::Prepare(), GDB_driver::RegisterType(), RunQueue(), ShowFile(), CDB_driver::Start(), GDB_driver::Start(), and GDB_driver::Stop().
m_ProgramIsStopped
bool DebuggerDriver::m_ProgramIsStopped protected
Definition at line 214 of file debuggerdriver.h.
Referenced by IsProgramStopped(), MarkProgramStopped(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), and RunQueue().
m_QueueBusy
bool DebuggerDriver::m_QueueBusy protected
Definition at line 222 of file debuggerdriver.h.
Referenced by IsQueueBusy(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), CDB_driver::Prepare(), RemoveTopCommand(), and RunQueue().
m_threads
ThreadsContainer DebuggerDriver::m_threads protected
Definition at line 225 of file debuggerdriver.h.
Referenced by GetThreads().
m_userSelectedFrameNo
int DebuggerDriver::m_userSelectedFrameNo protected
Definition at line 227 of file debuggerdriver.h.
Referenced by GetUserSelectedFrame(), ResetCurrentFrame(), and SetCurrentFrame().
m_WorkingDir
wxString DebuggerDriver::m_WorkingDir protected
Definition at line 210 of file debuggerdriver.h.
Referenced by GetDebuggersWorkingDirectory(), and SetWorkingDirectory().
The documentation for this class was generated from the following files:
debuggerdriver.h
debuggerdriver.cpp