Code::Blocks: ManagedThread Class Reference
ManagedThread Class Reference
#include <managedthread.h>
Public Member Functions
ManagedThread (bool *abortflag=nullptr)
virtual ~ManagedThread ()
bool * get_abort_location ()
void set_abort_location (bool *abortflag)
Static Public Member Functions
static unsigned long count_running ()
static unsigned long count_threads ()
static void abort_all ()
static void abort (bool *flag, bool delete_thread=true)
Protected Member Functions
virtual bool TestDestroy ()
virtual void * DoRun ()
virtual void * Entry ()
bool is_aborted ()
Static Protected Member Functions
static ManagedThread * GetThread (size_t n)
static void DeleteThreadFromList (ManagedThread *thread)
Protected Attributes
bool * m_pAbort
Static Protected Attributes
static wxCriticalSection s_count_running_mutex
Keeps count of running threads.
static wxCriticalSection s_list_mutex
static unsigned long s_running = 0
static bool s_abort_all = false
Constructor & Destructor Documentation
ManagedThread::ManagedThread (bool * abortflag = nullptr)
References s_list_mutex, and s_threadslist.
ManagedThread::~ManagedThread () virtual
References DeleteThreadFromList().
Member Function Documentation
void ManagedThread::abort (bool * flag, bool delete_thread = true) static
References count_running(), count_threads(), get_abort_location(), and GetThread().
void ManagedThread::abort_all () static
References count_running(), count_threads(), GetThread(), s_abort_all, s_list_mutex, and s_threadslist.
unsigned long ManagedThread::count_running () static
References s_count_running_mutex, and s_running.
Referenced by abort(), and abort_all().
unsigned long ManagedThread::count_threads () static
References s_list_mutex, and s_threadslist.
Referenced by abort(), and abort_all().
void ManagedThread::DeleteThreadFromList (ManagedThread * thread) static protected
References s_list_mutex, and s_threadslist.
Referenced by ~ManagedThread().
void * ManagedThread::DoRun () protected virtual
Referenced by Entry().
void * ManagedThread::Entry () protected virtual
References DoRun(), s_count_running_mutex, and s_running.
bool* ManagedThread::get_abort_location () inline
References m_pAbort.
Referenced by abort().
ManagedThread * ManagedThread::GetThread (size_t n) static protected
References s_list_mutex, and s_threadslist.
Referenced by abort(), and abort_all().
bool ManagedThread::is_aborted () protected
References m_pAbort, and s_abort_all.
Referenced by TestDestroy().
void ManagedThread::set_abort_location (bool * abortflag) inline
References m_pAbort.
bool ManagedThread::TestDestroy () protected virtual
References is_aborted().
Member Data Documentation
bool* ManagedThread::m_pAbort protected
Referenced by get_abort_location(), is_aborted(), and set_abort_location().
bool ManagedThread::s_abort_all = false static protected
Referenced by abort_all(), and is_aborted().
wxCriticalSection ManagedThread::s_count_running_mutex static protected
Keeps count of running threads.
Referenced by count_running(), and Entry().
wxCriticalSection ManagedThread::s_list_mutex static protected
Referenced by abort_all(), count_threads(), DeleteThreadFromList(), GetThread(), and ManagedThread().
unsigned long ManagedThread::s_running = 0 static protected
Referenced by count_running(), and Entry().
The documentation for this class was generated from the following files:
managedthread.h
managedthread.cpp