Code::Blocks: CdbCmd_SwitchFrame Class Reference
CdbCmd_SwitchFrame Class Reference
#include <cdb_commands.h>
Public Member Functions
CdbCmd_SwitchFrame (DebuggerDriver *driver, int frameNumber)
virtual void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Definition at line 477 of file cdb_commands.h.
Constructor & Destructor Documentation
CdbCmd_SwitchFrame()
CdbCmd_SwitchFrame::CdbCmd_SwitchFrame (DebuggerDriver * driver, int frameNumber) inline
Definition at line 480 of file cdb_commands.h.
References wxString::Format(), DebuggerCmd::m_Cmd, and wxT.
Member Function Documentation
ParseOutput()
virtual void CdbCmd_SwitchFrame::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 489 of file cdb_commands.h.
References Cursor::address, Cursor::changed, wxString::empty(), Cursor::file, Manager::Get(), GetArrayFromString(), DebuggerManager::GetBacktraceDialog(), wxArrayString::GetCount(), Manager::GetDebuggerManager(), wxRegEx::GetMatch(), Cursor::line, DebuggerCmd::m_pDriver, wxRegEx::Matches(), DebuggerDriver::NotifyCursorChanged(), cbBacktraceDlg::Reload(), reSwitchFrame(), DebuggerDriver::SetCursor(), wxString::ToLong(), and wxT.
The documentation for this class was generated from the following file:
cdb_commands.h