Code::Blocks: cbSplashScreen Class Reference
cbSplashScreen Class Reference
#include <splashscreen.h>
Public Member Functions
cbSplashScreen (wxBitmap &label, long timeout, wxWindow *parent, wxWindowID id, long style=wxSTAY_ON_TOP|wxNO_BORDER|wxFRAME_NO_TASKBAR|wxFRAME_SHAPED)
~cbSplashScreen ()
Static Public Member Functions
static void DrawReleaseInfo (wxDC &dc)
Private Member Functions
void DoPaint (wxDC &dc)
void OnPaint (wxPaintEvent &)
void OnTimer (wxTimerEvent &)
void OnCloseWindow (wxCloseEvent &)
void OnChar (wxKeyEvent &)
void OnMouseEvent (wxMouseEvent &event)
Private Attributes
wxBitmap m_label
wxTimer m_timer
Detailed Description
Definition at line 14 of file splashscreen.h.
Constructor & Destructor Documentation
cbSplashScreen()
cbSplashScreen::cbSplashScreen (wxBitmap & label, long timeout, wxWindow * parent, wxWindowID id, long style = wxSTAY_ON_TOP | wxNO_BORDER | wxFRAME_NO_TASKBAR | wxFRAME_SHAPED)
Definition at line 122 of file splashscreen.cpp.
References wxBitmap::Create(), wxBitmap::GetHeight(), wxBitmap::GetWidth(), m_label, m_timer, wxTimer::Start(), wxBOTH, wxEmptyString, wxNullBitmap, and wxWHITE_BRUSH.
~cbSplashScreen()
cbSplashScreen::~cbSplashScreen ()
Definition at line 181 of file splashscreen.cpp.
References m_timer, and wxTimer::Stop().
Member Function Documentation
DoPaint()
void cbSplashScreen::DoPaint (wxDC & dc) private
Definition at line 75 of file splashscreen.cpp.
References DrawReleaseInfo(), and m_label.
Referenced by OnPaint().
DrawReleaseInfo()
void cbSplashScreen::DrawReleaseInfo (wxDC & dc) static
Definition at line 32 of file splashscreen.cpp.
References _(), ConfigManager::GetRevisionString(), PluginManager::GetSafeMode(), RELEASE, wxBLACK, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, wxRED, and wxT.
Referenced by dlgAbout::dlgAbout(), and DoPaint().
OnChar()
void cbSplashScreen::OnChar (wxKeyEvent &) private
Definition at line 111 of file splashscreen.cpp.
OnCloseWindow()
void cbSplashScreen::OnCloseWindow (wxCloseEvent &) private
Definition at line 104 of file splashscreen.cpp.
References m_timer, and wxTimer::Stop().
OnMouseEvent()
void cbSplashScreen::OnMouseEvent (wxMouseEvent & event) private
Definition at line 116 of file splashscreen.cpp.
References wxMouseEvent::LeftDown().
OnPaint()
void cbSplashScreen::OnPaint (wxPaintEvent &) private
Definition at line 90 of file splashscreen.cpp.
References DoPaint().
OnTimer()
void cbSplashScreen::OnTimer (wxTimerEvent &) private
Definition at line 99 of file splashscreen.cpp.
Member Data Documentation
m_label
wxBitmap cbSplashScreen::m_label private
Definition at line 17 of file splashscreen.h.
Referenced by cbSplashScreen(), and DoPaint().
m_timer
wxTimer cbSplashScreen::m_timer private
Definition at line 18 of file splashscreen.h.
Referenced by cbSplashScreen(), OnCloseWindow(), and ~cbSplashScreen().
The documentation for this class was generated from the following files:
splashscreen.h
splashscreen.cpp