Code::Blocks: ManageAssocsDialog Class Reference
ManageAssocsDialog Class Reference
#include <associations.h>
Public Member Functions
ManageAssocsDialog (wxWindow *parent)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void OnApply (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnClearAll (wxCommandEvent &event)
Private Attributes
wxCheckListBox * list
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
ManageAssocsDialog::ManageAssocsDialog (wxWindow * parent)
References Associations::CountAssocs(), and Associations::DoCheckAssociation().
Member Function Documentation
void ManageAssocsDialog::OnApply (wxCommandEvent & event) protected
References Associations::DoClearAssociation(), DoSetAssociation(), ScriptBindings::EndModal(), list, and Associations::UpdateChanges().
void ManageAssocsDialog::OnCancel (wxCommandEvent & event) protected
References ScriptBindings::EndModal().
void ManageAssocsDialog::OnClearAll (wxCommandEvent & event) protected
References Associations::ClearAll(), ScriptBindings::EndModal(), and Associations::UpdateChanges().
Member Data Documentation
wxCheckListBox* ManageAssocsDialog::list private
Referenced by OnApply().
The documentation for this class was generated from the following files:
associations.h
associations.cpp