Code::Blocks: WizGenericSingleChoiceList Class Reference
WizGenericSingleChoiceList Class Reference
#include <wizpage.h>
Public Member Functions
WizGenericSingleChoiceList (const wxString &pageId, const wxString &descr, const wxArrayString &choices, int defChoice, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizGenericSingleChoiceList ()
int GetChoice () const
void SetChoice (int choice)
void OnPageChanging (wxWizardEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
GenericSingleChoiceList * m_pGenericSingleChoiceList
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 178 of file wizpage.h.
Constructor & Destructor Documentation
WizGenericSingleChoiceList()
WizGenericSingleChoiceList::WizGenericSingleChoiceList (const wxString & pageId, const wxString & descr, const wxArrayString & choices, int defChoice, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 708 of file wizpage.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), m_pGenericSingleChoiceList, ConfigManager::ReadInt(), GenericSingleChoiceList::SetChoices(), and GenericSingleChoiceList::SetDescription().
~WizGenericSingleChoiceList()
WizGenericSingleChoiceList::~WizGenericSingleChoiceList ()
Definition at line 721 of file wizpage.cpp.
Member Function Documentation
GetChoice()
int WizGenericSingleChoiceList::GetChoice () const
Definition at line 726 of file wizpage.cpp.
References GenericSingleChoiceList::GetChoice(), and m_pGenericSingleChoiceList.
OnPageChanging()
void WizGenericSingleChoiceList::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 738 of file wizpage.cpp.
References _T, Manager::Get(), GenericSingleChoiceList::GetChoice(), Manager::GetConfigManager(), wxWizardEvent::GetDirection(), WizPageBase::GetPageName(), m_pGenericSingleChoiceList, WizPageBase::OnPageChanging(), and ConfigManager::Write().
SetChoice()
void WizGenericSingleChoiceList::SetChoice (int choice)
Definition at line 732 of file wizpage.cpp.
References m_pGenericSingleChoiceList, and GenericSingleChoiceList::SetChoice().
Member Data Documentation
m_pGenericSingleChoiceList
GenericSingleChoiceList* WizGenericSingleChoiceList::m_pGenericSingleChoiceList private
Definition at line 189 of file wizpage.h.
Referenced by GetChoice(), OnPageChanging(), SetChoice(), and WizGenericSingleChoiceList().
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp