Code::Blocks: CdbCmd_AttachToProcess Class Reference
CdbCmd_AttachToProcess Class Reference
Command to the attach to a process.
#include <cdb_commands.h>
Public Member Functions
CdbCmd_AttachToProcess (DebuggerDriver *driver, int pid)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
int m_pid
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to the attach to a process.
Constructor & Destructor Documentation
CdbCmd_AttachToProcess::CdbCmd_AttachToProcess (DebuggerDriver * driver, int pid) inline
Parameters
file The file to debug.
References DebuggerCmd::m_Cmd.
Member Function Documentation
void CdbCmd_AttachToProcess::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
References DebuggerCmd::DebuggerCmd(), GetArrayFromString(), DebuggerDriver::Log(), DebuggerCmd::m_pDriver, DebuggerDriver::QueueCommand(), and DebuggerDriver::SetChildPID().
Member Data Documentation
int CdbCmd_AttachToProcess::m_pid private
The documentation for this class was generated from the following file:
cdb_commands.h