Code::Blocks: AskAssocDialog Class Reference
AskAssocDialog Class Reference
#include <associations.h>
Public Member Functions
AskAssocDialog (wxWindow *parent)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Member Functions
void OnOK (wxCommandEvent &event)
void OnESC (wxCommandEvent &event)
void OnCharHook (wxKeyEvent &event)
Detailed Description
Definition at line 75 of file associations.h.
Constructor & Destructor Documentation
AskAssocDialog()
AskAssocDialog::AskAssocDialog (wxWindow * parent)
Definition at line 378 of file associations.cpp.
References _T, wxXmlResource::Get(), wxXmlResource::LoadObject(), and wxID_NONE.
Member Function Documentation
OnCharHook()
void AskAssocDialog::OnCharHook (wxKeyEvent & event) protected
Definition at line 394 of file associations.cpp.
References ScriptBindings::EndModal(), wxKeyEvent::GetKeyCode(), WXK_ESCAPE, WXK_NUMPAD_ENTER, and WXK_RETURN.
Referenced by ManageAssocsDialog::OnClearAll().
OnESC()
void AskAssocDialog::OnESC (wxCommandEvent & event) protected
Definition at line 389 of file associations.cpp.
References ASC_ASSOC_DLG_NO_ONLY_NOW, and ScriptBindings::EndModal().
Referenced by ManageAssocsDialog::OnClearAll().
OnOK()
void AskAssocDialog::OnOK (wxCommandEvent & event) protected
Definition at line 384 of file associations.cpp.
References ScriptBindings::EndModal().
Referenced by ManageAssocsDialog::OnClearAll().
The documentation for this class was generated from the following files:
associations.h
associations.cpp