Code::Blocks: cbWatch Class Reference
cbWatch Class Reference abstract
#include <debuggermanager.h>
Public Member Functions
cbWatch ()
virtual void GetSymbol (wxString &symbol) const =0
virtual void GetValue (wxString &value) const =0
virtual bool SetValue (const wxString &value)=0
virtual void GetFullWatchString (wxString &full_watch) const =0
virtual void GetType (wxString &type) const =0
virtual void SetType (const wxString &type)=0
virtual wxString const & GetDebugString () const =0
void RemoveChild (int index)
void RemoveChildren ()
bool RemoveMarkedChildren ()
int GetChildCount () const
cb::shared_ptr< cbWatch > GetChild (int index)
cb::shared_ptr< const cbWatch > GetChild (int index) const
cb::shared_ptr< cbWatch > FindChild (const wxString &name)
int FindChildIndex (const wxString &symbol) const
cb::shared_ptr< const cbWatch > GetParent () const
cb::shared_ptr< cbWatch > GetParent ()
bool IsRemoved () const
bool IsChanged () const
void MarkAsRemoved (bool flag)
void MarkChildsAsRemoved ()
void MarkAsChanged (bool flag)
void MarkAsChangedRecursive (bool flag)
bool IsExpanded () const
void Expand (bool expand)
bool IsAutoUpdateEnabled () const
void AutoUpdate (bool enabled)
Static Public Member Functions
static void AddChild (cb::shared_ptr< cbWatch > parent, cb::shared_ptr< cbWatch > watch)
Protected Member Functions
virtual ~cbWatch ()
Private Member Functions
cbWatch & operator= (cbWatch &)
cbWatch (cbWatch &)
Private Attributes
cb::weak_ptr< cbWatch > m_parent
std::vector< cb::shared_ptr< cbWatch > > m_children
bool m_changed
bool m_removed
bool m_expanded
bool m_autoUpdate
Detailed Description
Definition at line 49 of file debuggermanager.h.
Constructor & Destructor Documentation
cbWatch() [1/2]
cbWatch::cbWatch (cbWatch &) private
cbWatch() [2/2]
cbWatch::cbWatch ()
Definition at line 45 of file debuggermanager.cpp.
~cbWatch()
cbWatch::~cbWatch () protected virtual
Definition at line 53 of file debuggermanager.cpp.
References m_children.
Member Function Documentation
AddChild()
void cbWatch::AddChild (cb::shared_ptr< cbWatch > parent, cb::shared_ptr< cbWatch > watch) static
Definition at line 58 of file debuggermanager.cpp.
Referenced by AddChild(), and SUITE().
AutoUpdate()
void cbWatch::AutoUpdate (bool enabled)
Definition at line 200 of file debuggermanager.cpp.
References m_autoUpdate.
Expand()
void cbWatch::Expand (bool expand)
Definition at line 190 of file debuggermanager.cpp.
References m_expanded.
FindChild()
cb::shared_ptr< cbWatch > cbWatch::FindChild (const wxString & name)
Definition at line 116 of file debuggermanager.cpp.
References m_children.
FindChildIndex()
int cbWatch::FindChildIndex (const wxString & symbol) const
Definition at line 128 of file debuggermanager.cpp.
References m_children.
GetChild() [1/2]
cb::shared_ptr< cbWatch > cbWatch::GetChild (int index)
Definition at line 102 of file debuggermanager.cpp.
References m_children.
Referenced by AppendChildren(), WatchToString(), and WatchRawDialog::WatchToString().
GetChild() [2/2]
cb::shared_ptr< const cbWatch > cbWatch::GetChild (int index) const
Definition at line 109 of file debuggermanager.cpp.
References m_children.
GetChildCount()
int cbWatch::GetChildCount () const
Definition at line 97 of file debuggermanager.cpp.
References m_children.
Referenced by AppendChildren(), WatchToString(), and WatchRawDialog::WatchToString().
GetDebugString()
virtual wxString const& cbWatch::GetDebugString () const pure virtual
Implemented in GDBWatch.
GetFullWatchString()
virtual void cbWatch::GetFullWatchString (wxString & full_watch) const pure virtual
Implemented in GDBWatch.
GetParent() [1/2]
cb::shared_ptr< const cbWatch > cbWatch::GetParent () const
Definition at line 143 of file debuggermanager.cpp.
References m_parent.
Referenced by GDBWatch::GetFullWatchString(), and DebuggerGDB::OnWatchesContextMenu().
GetParent() [2/2]
cb::shared_ptr< cbWatch > cbWatch::GetParent ()
Definition at line 148 of file debuggermanager.cpp.
References m_parent.
GetSymbol()
virtual void cbWatch::GetSymbol (wxString & symbol) const pure virtual
Implemented in GDBWatch.
Referenced by getName(), DebuggerGDB::OnWatchesContextMenu(), WatchToString(), and WatchRawDialog::WatchToString().
GetType()
virtual void cbWatch::GetType (wxString & type) const pure virtual
Implemented in GDBWatch.
Referenced by DebuggerGDB::OnWatchesContextMenu().
GetValue()
virtual void cbWatch::GetValue (wxString & value) const pure virtual
Implemented in GDBWatch.
Referenced by WatchToString(), and WatchRawDialog::WatchToString().
IsAutoUpdateEnabled()
bool cbWatch::IsAutoUpdateEnabled () const
Definition at line 195 of file debuggermanager.cpp.
References m_autoUpdate.
IsChanged()
bool cbWatch::IsChanged () const
Definition at line 158 of file debuggermanager.cpp.
References m_changed.
IsExpanded()
bool cbWatch::IsExpanded () const
Definition at line 185 of file debuggermanager.cpp.
References m_expanded.
IsRemoved()
bool cbWatch::IsRemoved () const
Definition at line 153 of file debuggermanager.cpp.
References m_removed.
MarkAsChanged()
void cbWatch::MarkAsChanged (bool flag)
Definition at line 173 of file debuggermanager.cpp.
References m_changed.
Referenced by GDBWatch::SetValue().
MarkAsChangedRecursive()
void cbWatch::MarkAsChangedRecursive (bool flag)
Definition at line 178 of file debuggermanager.cpp.
References m_changed, and m_children.
MarkAsRemoved()
void cbWatch::MarkAsRemoved (bool flag)
Definition at line 163 of file debuggermanager.cpp.
References m_removed.
MarkChildsAsRemoved()
void cbWatch::MarkChildsAsRemoved ()
Definition at line 168 of file debuggermanager.cpp.
References m_children.
operator=()
cbWatch& cbWatch::operator= (cbWatch &) private
RemoveChild()
void cbWatch::RemoveChild (int index)
Definition at line 64 of file debuggermanager.cpp.
References m_children.
RemoveChildren()
void cbWatch::RemoveChildren ()
Definition at line 92 of file debuggermanager.cpp.
References m_children.
RemoveMarkedChildren()
bool cbWatch::RemoveMarkedChildren ()
Definition at line 82 of file debuggermanager.cpp.
References m_children, and TestIfMarkedForRemoval().
SetType()
virtual void cbWatch::SetType (const wxString & type) pure virtual
Implemented in GDBWatch.
SetValue()
virtual bool cbWatch::SetValue (const wxString & value) pure virtual
Implemented in GDBWatch.
Member Data Documentation
m_autoUpdate
bool cbWatch::m_autoUpdate private
Definition at line 101 of file debuggermanager.h.
Referenced by AutoUpdate(), and IsAutoUpdateEnabled().
m_changed
bool cbWatch::m_changed private
Definition at line 98 of file debuggermanager.h.
Referenced by IsChanged(), MarkAsChanged(), and MarkAsChangedRecursive().
m_children
std::vector<cb::shared_ptr<cbWatch> > cbWatch::m_children private
Definition at line 97 of file debuggermanager.h.
Referenced by FindChild(), FindChildIndex(), GetChild(), GetChildCount(), MarkAsChangedRecursive(), MarkChildsAsRemoved(), RemoveChild(), RemoveChildren(), RemoveMarkedChildren(), and ~cbWatch().
m_expanded
bool cbWatch::m_expanded private
Definition at line 100 of file debuggermanager.h.
Referenced by Expand(), and IsExpanded().
m_parent
cb::weak_ptr<cbWatch> cbWatch::m_parent private
Definition at line 96 of file debuggermanager.h.
Referenced by GetParent().
m_removed
bool cbWatch::m_removed private
Definition at line 99 of file debuggermanager.h.
Referenced by IsRemoved(), and MarkAsRemoved().
The documentation for this class was generated from the following files:
debuggermanager.h
debuggermanager.cpp