Code::Blocks: ProfileTimer Class Reference
ProfileTimer Class Reference
#include <profiletimer.h>
Static Public Member Functions
static size_t Registry (ProfileTimerData *ptd, const wxString &funcName)
static void Log ()
Private Types
typedef std::map< ProfileTimerData *, wxString > ProfileMap
Static Private Attributes
static ProfileMap m_ProfileMap
Detailed Description
Definition at line 50 of file profiletimer.h.
Member Typedef Documentation
ProfileMap
typedef std::map<ProfileTimerData*, wxString> ProfileTimer::ProfileMap private
Definition at line 57 of file profiletimer.h.
Member Function Documentation
Log()
void ProfileTimer::Log () static
Definition at line 49 of file profiletimer.cpp.
References _T, LogManager::DebugLog(), Manager::Get(), Manager::GetLogManager(), and wxString::Printf().
Registry()
size_t ProfileTimer::Registry (ProfileTimerData * ptd, const wxString & funcName) static
Definition at line 43 of file profiletimer.cpp.
Member Data Documentation
m_ProfileMap
ProfileTimer::ProfileMap ProfileTimer::m_ProfileMap static private
Definition at line 58 of file profiletimer.h.
The documentation for this class was generated from the following files:
profiletimer.h
profiletimer.cpp