Code::Blocks: CCDebugInfo Class Reference
CCDebugInfo Class Reference
#include <ccdebuginfo.h>
Public Member Functions
CCDebugInfo (wxWindow *parent, ParserBase *parser, Token *token)
virtual ~CCDebugInfo ()
void FillFiles ()
void FillDirs ()
void FillMacros ()
void DisplayTokenInfo ()
void FillChildren ()
void FillAncestors ()
void FillDescendants ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Static Public Attributes
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_BUTTON1 = wxNewId()
static const long ID_STATICTEXT18 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_STATICTEXT10 = wxNewId()
static const long ID_STATICTEXT12 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_STATICTEXT6 = wxNewId()
static const long ID_STATICTEXT8 = wxNewId()
static const long ID_STATICTEXT37 = wxNewId()
static const long ID_STATICTEXT41 = wxNewId()
static const long ID_STATICTEXT14 = wxNewId()
static const long ID_STATICTEXT16 = wxNewId()
static const long ID_STATICTEXT33 = wxNewId()
static const long ID_STATICTEXT39 = wxNewId()
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_STATICTEXT20 = wxNewId()
static const long ID_STATICTEXT24 = wxNewId()
static const long ID_BUTTON4 = wxNewId()
static const long ID_COMBOBOX3 = wxNewId()
static const long ID_BUTTON5 = wxNewId()
static const long ID_COMBOBOX2 = wxNewId()
static const long ID_BUTTON3 = wxNewId()
static const long ID_COMBOBOX1 = wxNewId()
static const long ID_BUTTON2 = wxNewId()
static const long ID_STATICTEXT26 = wxNewId()
static const long ID_BUTTON7 = wxNewId()
static const long ID_STATICTEXT28 = wxNewId()
static const long ID_BUTTON8 = wxNewId()
static const long ID_STATICTEXT35 = wxNewId()
static const long ID_PANEL1 = wxNewId()
static const long ID_LISTBOX1 = wxNewId()
static const long ID_PANEL2 = wxNewId()
static const long ID_LISTBOX2 = wxNewId()
static const long ID_PANEL3 = wxNewId()
static const long ID_LISTBOX3 = wxNewId()
static const long ID_PANEL4 = wxNewId()
static const long ID_NOTEBOOK1 = wxNewId()
static const long ID_BUTTON6 = wxNewId()
Protected Member Functions
void OnInit (wxInitDialogEvent &event)
void OnFindClick (wxCommandEvent &event)
void OnGoAscClick (wxCommandEvent &event)
void OnGoDescClick (wxCommandEvent &event)
void OnGoParentClick (wxCommandEvent &event)
void OnGoChildrenClick (wxCommandEvent &event)
void OnSave (wxCommandEvent &event)
void OnGoDeclClick (wxCommandEvent &event)
void OnGoImplClick (wxCommandEvent &event)
Protected Attributes
wxComboBox * cmbChildren
wxStaticText * txtFullType
wxComboBox * cmbAncestors
wxTextCtrl * txtFilter
wxStaticText * txtArgsStripped
wxListBox * lstMacros
wxStaticText * txtID
wxStaticText * txtParent
wxStaticText * txtArgs
wxStaticText * txtNamespace
wxStaticText * txtBaseType
wxStaticText * txtIsOp
wxBoxSizer * BoxSizer11
wxStaticText * txtScope
wxPanel * Panel4
wxStaticText * txtKind
wxStaticText * txtDeclFile
wxListBox * lstFiles
wxListBox * lstDirs
wxStaticText * txtTemplateArg
wxStaticText * txtIsNoExcept
wxStaticText * txtInfo
wxStaticText * txtName
wxStaticText * txtIsLocal
wxStaticText * txtUserData
wxStaticText * txtIsTemp
wxBoxSizer * BoxSizer12
wxStaticText * txtImplFile
wxComboBox * cmbDescendants
wxButton * btnSave
wxBoxSizer * BoxSizer5
wxStaticText * txtIsConst
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Private Attributes
ParserBase * m_Parser
Token * m_Token
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 33 of file ccdebuginfo.h.
Constructor & Destructor Documentation
CCDebugInfo()
CCDebugInfo::CCDebugInfo (wxWindow * parent, ParserBase * parser, Token * token)
Definition at line 140 of file ccdebuginfo.cpp.
References OnFindClick(), OnGoAscClick(), OnGoChildrenClick(), OnGoDeclClick(), OnGoDescClick(), OnGoImplClick(), OnGoParentClick(), OnInit(), and OnSave().
~CCDebugInfo()
CCDebugInfo::~CCDebugInfo () virtual
Definition at line 383 of file ccdebuginfo.cpp.
Member Function Documentation
DisplayTokenInfo()
void CCDebugInfo::DisplayTokenInfo ()
Definition at line 439 of file ccdebuginfo.cpp.
References TokenTree::at(), Token::m_Name, and TokenTree::RecalcInheritanceChain().
FillAncestors()
void CCDebugInfo::FillAncestors ()
Definition at line 529 of file ccdebuginfo.cpp.
References TokenTree::at(), TokenTree::Clear(), and Token::m_Name.
FillChildren()
void CCDebugInfo::FillChildren ()
Definition at line 513 of file ccdebuginfo.cpp.
References TokenTree::at(), TokenTree::Clear(), and Token::m_Name.
FillDescendants()
void CCDebugInfo::FillDescendants ()
Definition at line 545 of file ccdebuginfo.cpp.
References TokenTree::at(), TokenTree::Clear(), and Token::m_Name.
FillDirs()
void CCDebugInfo::FillDirs ()
Definition at line 407 of file ccdebuginfo.cpp.
FillFiles()
void CCDebugInfo::FillFiles ()
Definition at line 389 of file ccdebuginfo.cpp.
References TokenTree::Clear(), BasicSearchTree::GetString(), TokenTree::m_FilenameMap, and BasicSearchTree::size().
FillMacros()
void CCDebugInfo::FillMacros ()
Definition at line 423 of file ccdebuginfo.cpp.
OnFindClick()
void CCDebugInfo::OnFindClick (wxCommandEvent & event) protected
Definition at line 578 of file ccdebuginfo.cpp.
References TokenTree::at(), cbGetSingleChoiceIndex(), Token::DisplayName(), Token::m_Name, and TokenTree::size().
Referenced by CCDebugInfo().
OnGoAscClick()
void CCDebugInfo::OnGoAscClick (wxCommandEvent & event) protected
Definition at line 631 of file ccdebuginfo.cpp.
Referenced by CCDebugInfo().
OnGoChildrenClick()
void CCDebugInfo::OnGoChildrenClick (wxCommandEvent & event) protected
Definition at line 678 of file ccdebuginfo.cpp.
Referenced by CCDebugInfo().
OnGoDeclClick()
void CCDebugInfo::OnGoDeclClick (wxCommandEvent & event) protected
Definition at line 809 of file ccdebuginfo.cpp.
References EditorBase::Activate(), Manager::Get(), Manager::GetEditorManager(), cbEditor::GotoLine(), EditorManager::IsBuiltinOpen(), and EditorManager::Open().
Referenced by CCDebugInfo().
OnGoDescClick()
void CCDebugInfo::OnGoDescClick (wxCommandEvent & event) protected
Definition at line 650 of file ccdebuginfo.cpp.
Referenced by CCDebugInfo().
OnGoImplClick()
void CCDebugInfo::OnGoImplClick (wxCommandEvent & event) protected
Definition at line 833 of file ccdebuginfo.cpp.
References EditorBase::Activate(), Manager::Get(), Manager::GetEditorManager(), cbEditor::GotoLine(), EditorManager::IsBuiltinOpen(), and EditorManager::Open().
Referenced by CCDebugInfo().
OnGoParentClick()
void CCDebugInfo::OnGoParentClick (wxCommandEvent & event) protected
Definition at line 669 of file ccdebuginfo.cpp.
Referenced by CCDebugInfo().
OnInit()
void CCDebugInfo::OnInit (wxInitDialogEvent & event) protected
Definition at line 561 of file ccdebuginfo.cpp.
Referenced by CCDebugInfo().
OnSave()
void CCDebugInfo::OnSave (wxCommandEvent & event) protected
Definition at line 697 of file ccdebuginfo.cpp.
References TokenTree::at(), cbGetSingleChoiceIndex(), cbMessageBox(), Token::DisplayName(), BasicSearchTree::dump(), TokenTree::FindTokensInFile(), Manager::Get(), Token::GetFormattedArgs(), BasicSearchTree::GetString(), Token::GetTokenKindString(), TokenTree::m_FilenameMap, Token::m_ImplLine, Token::m_Line, Token::m_Name, Token::m_TokenKind, TokenTree::m_Tree, CCDebugInfoHelper::SaveCCDebugInfo(), SearchTree< T >::Serialize(), BasicSearchTree::size(), tkFunction, and tkUndefined.
Referenced by CCDebugInfo().
Member Data Documentation
BoxSizer11
wxBoxSizer* CCDebugInfo::BoxSizer11 protected
Definition at line 115 of file ccdebuginfo.h.
BoxSizer12
wxBoxSizer* CCDebugInfo::BoxSizer12 protected
Definition at line 129 of file ccdebuginfo.h.
BoxSizer5
wxBoxSizer* CCDebugInfo::BoxSizer5 protected
Definition at line 133 of file ccdebuginfo.h.
btnSave
wxButton* CCDebugInfo::btnSave protected
Definition at line 132 of file ccdebuginfo.h.
cmbAncestors
wxComboBox* CCDebugInfo::cmbAncestors protected
Definition at line 105 of file ccdebuginfo.h.
cmbChildren
wxComboBox* CCDebugInfo::cmbChildren protected
Definition at line 103 of file ccdebuginfo.h.
cmbDescendants
wxComboBox* CCDebugInfo::cmbDescendants protected
Definition at line 131 of file ccdebuginfo.h.
ID_BUTTON1
const long CCDebugInfo::ID_BUTTON1 = wxNewId() static
Definition at line 49 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_BUTTON2
const long CCDebugInfo::ID_BUTTON2 = wxNewId() static
Definition at line 72 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_BUTTON3
const long CCDebugInfo::ID_BUTTON3 = wxNewId() static
Definition at line 70 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_BUTTON4
const long CCDebugInfo::ID_BUTTON4 = wxNewId() static
Definition at line 66 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_BUTTON5
const long CCDebugInfo::ID_BUTTON5 = wxNewId() static
Definition at line 68 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_BUTTON6
const long CCDebugInfo::ID_BUTTON6 = wxNewId() static
Definition at line 86 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_BUTTON7
const long CCDebugInfo::ID_BUTTON7 = wxNewId() static
Definition at line 74 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_BUTTON8
const long CCDebugInfo::ID_BUTTON8 = wxNewId() static
Definition at line 76 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_COMBOBOX1
const long CCDebugInfo::ID_COMBOBOX1 = wxNewId() static
Definition at line 71 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_COMBOBOX2
const long CCDebugInfo::ID_COMBOBOX2 = wxNewId() static
Definition at line 69 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_COMBOBOX3
const long CCDebugInfo::ID_COMBOBOX3 = wxNewId() static
Definition at line 67 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_LISTBOX1
const long CCDebugInfo::ID_LISTBOX1 = wxNewId() static
Definition at line 79 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_LISTBOX2
const long CCDebugInfo::ID_LISTBOX2 = wxNewId() static
Definition at line 81 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_LISTBOX3
const long CCDebugInfo::ID_LISTBOX3 = wxNewId() static
Definition at line 83 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_NOTEBOOK1
const long CCDebugInfo::ID_NOTEBOOK1 = wxNewId() static
Definition at line 85 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_PANEL1
const long CCDebugInfo::ID_PANEL1 = wxNewId() static
Definition at line 78 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_PANEL2
const long CCDebugInfo::ID_PANEL2 = wxNewId() static
Definition at line 80 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_PANEL3
const long CCDebugInfo::ID_PANEL3 = wxNewId() static
Definition at line 82 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_PANEL4
const long CCDebugInfo::ID_PANEL4 = wxNewId() static
Definition at line 84 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT1
const long CCDebugInfo::ID_STATICTEXT1 = wxNewId() static
Definition at line 63 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT10
const long CCDebugInfo::ID_STATICTEXT10 = wxNewId() static
Definition at line 52 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT12
const long CCDebugInfo::ID_STATICTEXT12 = wxNewId() static
Definition at line 53 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT14
const long CCDebugInfo::ID_STATICTEXT14 = wxNewId() static
Definition at line 59 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT16
const long CCDebugInfo::ID_STATICTEXT16 = wxNewId() static
Definition at line 60 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT18
const long CCDebugInfo::ID_STATICTEXT18 = wxNewId() static
Definition at line 50 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT2
const long CCDebugInfo::ID_STATICTEXT2 = wxNewId() static
Definition at line 51 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT20
const long CCDebugInfo::ID_STATICTEXT20 = wxNewId() static
Definition at line 64 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT24
const long CCDebugInfo::ID_STATICTEXT24 = wxNewId() static
Definition at line 65 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT26
const long CCDebugInfo::ID_STATICTEXT26 = wxNewId() static
Definition at line 73 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT28
const long CCDebugInfo::ID_STATICTEXT28 = wxNewId() static
Definition at line 75 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT33
const long CCDebugInfo::ID_STATICTEXT33 = wxNewId() static
Definition at line 61 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT35
const long CCDebugInfo::ID_STATICTEXT35 = wxNewId() static
Definition at line 77 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT37
const long CCDebugInfo::ID_STATICTEXT37 = wxNewId() static
Definition at line 57 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT39
const long CCDebugInfo::ID_STATICTEXT39 = wxNewId() static
Definition at line 62 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT4
const long CCDebugInfo::ID_STATICTEXT4 = wxNewId() static
Definition at line 54 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT41
const long CCDebugInfo::ID_STATICTEXT41 = wxNewId() static
Definition at line 58 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT6
const long CCDebugInfo::ID_STATICTEXT6 = wxNewId() static
Definition at line 55 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_STATICTEXT8
const long CCDebugInfo::ID_STATICTEXT8 = wxNewId() static
Definition at line 56 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
ID_TEXTCTRL1
const long CCDebugInfo::ID_TEXTCTRL1 = wxNewId() static
Definition at line 48 of file ccdebuginfo.h.
Referenced by CCDebugInfoHelper::SaveCCDebugInfo().
lstDirs
wxListBox* CCDebugInfo::lstDirs protected
Definition at line 121 of file ccdebuginfo.h.
lstFiles
wxListBox* CCDebugInfo::lstFiles protected
Definition at line 120 of file ccdebuginfo.h.
lstMacros
wxListBox* CCDebugInfo::lstMacros protected
Definition at line 108 of file ccdebuginfo.h.
m_Parser
ParserBase* CCDebugInfo::m_Parser private
Definition at line 138 of file ccdebuginfo.h.
m_Token
Token* CCDebugInfo::m_Token private
Definition at line 139 of file ccdebuginfo.h.
Panel4
wxPanel* CCDebugInfo::Panel4 protected
Definition at line 117 of file ccdebuginfo.h.
txtArgs
wxStaticText* CCDebugInfo::txtArgs protected
Definition at line 111 of file ccdebuginfo.h.
txtArgsStripped
wxStaticText* CCDebugInfo::txtArgsStripped protected
Definition at line 107 of file ccdebuginfo.h.
txtBaseType
wxStaticText* CCDebugInfo::txtBaseType protected
Definition at line 113 of file ccdebuginfo.h.
txtDeclFile
wxStaticText* CCDebugInfo::txtDeclFile protected
Definition at line 119 of file ccdebuginfo.h.
txtFilter
wxTextCtrl* CCDebugInfo::txtFilter protected
Definition at line 106 of file ccdebuginfo.h.
txtFullType
wxStaticText* CCDebugInfo::txtFullType protected
Definition at line 104 of file ccdebuginfo.h.
txtID
wxStaticText* CCDebugInfo::txtID protected
Definition at line 109 of file ccdebuginfo.h.
txtImplFile
wxStaticText* CCDebugInfo::txtImplFile protected
Definition at line 130 of file ccdebuginfo.h.
txtInfo
wxStaticText* CCDebugInfo::txtInfo protected
Definition at line 124 of file ccdebuginfo.h.
txtIsConst
wxStaticText* CCDebugInfo::txtIsConst protected
Definition at line 134 of file ccdebuginfo.h.
txtIsLocal
wxStaticText* CCDebugInfo::txtIsLocal protected
Definition at line 126 of file ccdebuginfo.h.
txtIsNoExcept
wxStaticText* CCDebugInfo::txtIsNoExcept protected
Definition at line 123 of file ccdebuginfo.h.
txtIsOp
wxStaticText* CCDebugInfo::txtIsOp protected
Definition at line 114 of file ccdebuginfo.h.
txtIsTemp
wxStaticText* CCDebugInfo::txtIsTemp protected
Definition at line 128 of file ccdebuginfo.h.
txtKind
wxStaticText* CCDebugInfo::txtKind protected
Definition at line 118 of file ccdebuginfo.h.
txtName
wxStaticText* CCDebugInfo::txtName protected
Definition at line 125 of file ccdebuginfo.h.
txtNamespace
wxStaticText* CCDebugInfo::txtNamespace protected
Definition at line 112 of file ccdebuginfo.h.
txtParent
wxStaticText* CCDebugInfo::txtParent protected
Definition at line 110 of file ccdebuginfo.h.
txtScope
wxStaticText* CCDebugInfo::txtScope protected
Definition at line 116 of file ccdebuginfo.h.
txtTemplateArg
wxStaticText* CCDebugInfo::txtTemplateArg protected
Definition at line 122 of file ccdebuginfo.h.
txtUserData
wxStaticText* CCDebugInfo::txtUserData protected
Definition at line 127 of file ccdebuginfo.h.
The documentation for this class was generated from the following files:
ccdebuginfo.h
ccdebuginfo.cpp