Code::Blocks: GdbCmd_Start Class Reference
GdbCmd_Start Class Reference
#include <gdb_commands.h>
Public Member Functions
GdbCmd_Start (DebuggerDriver *driver, const wxString &cmd)
virtual void ParseOutput (const wxString &output)
Public Member Functions inherited from DebuggerContinueBaseCmd
DebuggerContinueBaseCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
bool IsContinueCommand () const
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Constructor & Destructor Documentation
GdbCmd_Start::GdbCmd_Start (DebuggerDriver * driver, const wxString & cmd) inline
Member Function Documentation
virtual void GdbCmd_Start::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
References DebuggerCmd::DebuggerCmd(), GetArrayFromString(), DebuggerDriver::Log(), DebuggerCmd::m_pDriver, DebuggerDriver::MarkProgramStopped(), and DebuggerDriver::QueueCommand().
The documentation for this class was generated from the following file:
gdb_commands.h