Code::Blocks: DebuggerOptionsProjectDlg Class Reference
DebuggerOptionsProjectDlg Class Reference
#include <debuggeroptionsprjdlg.h>
Public Member Functions
DebuggerOptionsProjectDlg (wxWindow *parent, DebuggerGDB *debugger, cbProject *project)
virtual ~DebuggerOptionsProjectDlg ()
virtual wxString GetTitle () const
virtual wxString GetBitmapBaseName () const
virtual void OnApply ()
Called when the user chooses to apply the configuration.
virtual void OnCancel ()
Called when the user chooses to cancel the configuration.
Public Member Functions inherited from cbConfigurationPanel
cbConfigurationPanel ()
virtual ~cbConfigurationPanel ()
void SetParentDialog (wxWindow *dialog)
Sets the panel's parent dialog.
wxWindow * SetParentDialog ()
Gets the panel's parent dialog.
int cbMessageBox (const wxString &message, const wxString &caption=wxEmptyString, int style=wxOK, wxWindow *parent=NULL, int x=-1, int y=-1)
Call global cbMessageBox with m_parentDialog as parent window when no parent window specified.
Protected Member Functions
void OnTargetSel (wxCommandEvent &event)
void OnAdd (wxCommandEvent &event)
void OnEdit (wxCommandEvent &event)
void OnDelete (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Private Member Functions
void OnBuildTargetRemoved (CodeBlocksEvent &event)
void OnBuildTargetAdded (CodeBlocksEvent &event)
void OnBuildTargetRenamed (CodeBlocksEvent &event)
void LoadCurrentRemoteDebuggingRecord ()
void SaveCurrentRemoteDebuggingRecord ()
Private Attributes
DebuggerGDB * m_pDBG
cbProject * m_pProject
wxArrayString m_OldPaths
RemoteDebuggingMap m_CurrentRemoteDebugging
int m_LastTargetSel
Detailed Description
Definition at line 20 of file debuggeroptionsprjdlg.h.
Constructor & Destructor Documentation
DebuggerOptionsProjectDlg()
DebuggerOptionsProjectDlg::DebuggerOptionsProjectDlg (wxWindow * parent, DebuggerGDB * debugger, cbProject * project)
Definition at line 33 of file debuggeroptionsprjdlg.cpp.
References cbEVT_BUILDTARGET_ADDED, cbEVT_BUILDTARGET_REMOVED, cbEVT_BUILDTARGET_RENAMED, Manager::Get(), OnBuildTargetAdded(), OnBuildTargetRemoved(), OnBuildTargetRenamed(), and Manager::RegisterEventSink().
~DebuggerOptionsProjectDlg()
DebuggerOptionsProjectDlg::~DebuggerOptionsProjectDlg () virtual
Definition at line 66 of file debuggeroptionsprjdlg.cpp.
References Manager::Get(), and Manager::RemoveAllEventSinksFor().
Member Function Documentation
GetBitmapBaseName()
virtual wxString DebuggerOptionsProjectDlg::GetBitmapBaseName () const inline virtual
Returns
the panel's bitmap base name. You must supply two bitmaps: <basename>.png and <basename>-off.png...
Implements cbConfigurationPanel.
Definition at line 27 of file debuggeroptionsprjdlg.h.
References OnApply().
GetTitle()
virtual wxString DebuggerOptionsProjectDlg::GetTitle () const inline virtual
Returns
the panel's title.
Implements cbConfigurationPanel.
Definition at line 26 of file debuggeroptionsprjdlg.h.
LoadCurrentRemoteDebuggingRecord()
void DebuggerOptionsProjectDlg::LoadCurrentRemoteDebuggingRecord () private
Definition at line 160 of file debuggeroptionsprjdlg.cpp.
References RemoteDebugging::additionalCmds, RemoteDebugging::additionalCmdsBefore, RemoteDebugging::additionalShellCmdsAfter, RemoteDebugging::additionalShellCmdsBefore, RemoteDebugging::connType, RemoteDebugging::extendedRemote, cbProject::GetBuildTarget(), RemoteDebugging::ip, RemoteDebugging::ipPort, m_CurrentRemoteDebugging, m_LastTargetSel, m_pProject, RemoteDebugging::serialBaud, RemoteDebugging::serialPort, and RemoteDebugging::skipLDpath.
Referenced by OnBuildTargetAdded(), OnBuildTargetRemoved(), OnBuildTargetRenamed(), OnCancel(), and OnTargetSel().
OnAdd()
void DebuggerOptionsProjectDlg::OnAdd (wxCommandEvent & event) protected
Definition at line 232 of file debuggeroptionsprjdlg.cpp.
References CompileTargetBase::GetBasePath(), m_pProject, and PlaceWindow().
Referenced by OnCancel().
OnApply()
void DebuggerOptionsProjectDlg::OnApply () virtual
Called when the user chooses to apply the configuration.
Implements cbConfigurationPanel.
Definition at line 302 of file debuggeroptionsprjdlg.cpp.
References DebuggerGDB::GetRemoteDebuggingMap(), DebuggerGDB::GetSearchDirs(), m_CurrentRemoteDebugging, m_OldPaths, m_pDBG, m_pProject, and SaveCurrentRemoteDebuggingRecord().
Referenced by GetBitmapBaseName().
OnBuildTargetAdded()
void DebuggerOptionsProjectDlg::OnBuildTargetAdded (CodeBlocksEvent & event) private
Definition at line 97 of file debuggeroptionsprjdlg.cpp.
References cbProject::GetBuildTarget(), LoadCurrentRemoteDebuggingRecord(), m_CurrentRemoteDebugging, and m_pProject.
Referenced by DebuggerOptionsProjectDlg(), and OnCancel().
OnBuildTargetRemoved()
void DebuggerOptionsProjectDlg::OnBuildTargetRemoved (CodeBlocksEvent & event) private
Definition at line 71 of file debuggeroptionsprjdlg.cpp.
References cbProject::GetBuildTarget(), LoadCurrentRemoteDebuggingRecord(), m_CurrentRemoteDebugging, and m_pProject.
Referenced by DebuggerOptionsProjectDlg(), and OnCancel().
OnBuildTargetRenamed()
void DebuggerOptionsProjectDlg::OnBuildTargetRenamed (CodeBlocksEvent & event) private
Definition at line 130 of file debuggeroptionsprjdlg.cpp.
References LoadCurrentRemoteDebuggingRecord(), m_CurrentRemoteDebugging, m_pProject, and cbProject::SetTitle().
Referenced by DebuggerOptionsProjectDlg(), and OnCancel().
OnCancel()
virtual void DebuggerOptionsProjectDlg::OnCancel () inline virtual
Called when the user chooses to cancel the configuration.
Implements cbConfigurationPanel.
Definition at line 29 of file debuggeroptionsprjdlg.h.
References LoadCurrentRemoteDebuggingRecord(), OnAdd(), OnBuildTargetAdded(), OnBuildTargetRemoved(), OnBuildTargetRenamed(), OnDelete(), OnEdit(), OnTargetSel(), OnUpdateUI(), and SaveCurrentRemoteDebuggingRecord().
OnDelete()
void DebuggerOptionsProjectDlg::OnDelete (wxCommandEvent & event) protected
Definition at line 269 of file debuggeroptionsprjdlg.cpp.
Referenced by OnCancel().
OnEdit()
void DebuggerOptionsProjectDlg::OnEdit (wxCommandEvent & event) protected
Definition at line 249 of file debuggeroptionsprjdlg.cpp.
References CompileTargetBase::GetBasePath(), m_pProject, and PlaceWindow().
Referenced by OnCancel().
OnTargetSel()
void DebuggerOptionsProjectDlg::OnTargetSel (wxCommandEvent & event) protected
Definition at line 225 of file debuggeroptionsprjdlg.cpp.
References LoadCurrentRemoteDebuggingRecord(), and SaveCurrentRemoteDebuggingRecord().
Referenced by OnCancel().
OnUpdateUI()
void DebuggerOptionsProjectDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 279 of file debuggeroptionsprjdlg.cpp.
Referenced by OnCancel().
SaveCurrentRemoteDebuggingRecord()
void DebuggerOptionsProjectDlg::SaveCurrentRemoteDebuggingRecord () private
Definition at line 197 of file debuggeroptionsprjdlg.cpp.
References RemoteDebugging::additionalCmds, RemoteDebugging::additionalCmdsBefore, RemoteDebugging::additionalShellCmdsAfter, RemoteDebugging::additionalShellCmdsBefore, RemoteDebugging::connType, RemoteDebugging::extendedRemote, cbProject::GetBuildTarget(), RemoteDebugging::ip, RemoteDebugging::ipPort, m_CurrentRemoteDebugging, m_LastTargetSel, m_pProject, RemoteDebugging::serialBaud, RemoteDebugging::serialPort, and RemoteDebugging::skipLDpath.
Referenced by OnApply(), OnCancel(), and OnTargetSel().
Member Data Documentation
m_CurrentRemoteDebugging
RemoteDebuggingMap DebuggerOptionsProjectDlg::m_CurrentRemoteDebugging private
Definition at line 46 of file debuggeroptionsprjdlg.h.
Referenced by LoadCurrentRemoteDebuggingRecord(), OnApply(), OnBuildTargetAdded(), OnBuildTargetRemoved(), OnBuildTargetRenamed(), and SaveCurrentRemoteDebuggingRecord().
m_LastTargetSel
int DebuggerOptionsProjectDlg::m_LastTargetSel private
Definition at line 47 of file debuggeroptionsprjdlg.h.
Referenced by LoadCurrentRemoteDebuggingRecord(), and SaveCurrentRemoteDebuggingRecord().
m_OldPaths
wxArrayString DebuggerOptionsProjectDlg::m_OldPaths private
Definition at line 45 of file debuggeroptionsprjdlg.h.
Referenced by OnApply().
m_pDBG
DebuggerGDB* DebuggerOptionsProjectDlg::m_pDBG private
Definition at line 43 of file debuggeroptionsprjdlg.h.
Referenced by OnApply().
m_pProject
cbProject* DebuggerOptionsProjectDlg::m_pProject private
Definition at line 44 of file debuggeroptionsprjdlg.h.
Referenced by LoadCurrentRemoteDebuggingRecord(), OnAdd(), OnApply(), OnBuildTargetAdded(), OnBuildTargetRemoved(), OnBuildTargetRenamed(), OnEdit(), and SaveCurrentRemoteDebuggingRecord().
The documentation for this class was generated from the following files:
debuggeroptionsprjdlg.h
debuggeroptionsprjdlg.cpp