Code::Blocks: ProjectDepsDlg Class Reference
ProjectDepsDlg Class Reference
#include <projectdepsdlg.h>
Public Member Functions
ProjectDepsDlg (wxWindow *parent, cbProject *sel=nullptr)
virtual ~ProjectDepsDlg ()
virtual void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void FillList ()
bool SaveList ()
void OnProjectChange (wxCommandEvent &event)
Protected Attributes
int m_LastSel
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
ProjectDepsDlg::ProjectDepsDlg (wxWindow * parent, cbProject * sel = nullptr)
References Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetProjects(), and CompileTargetBase::GetTitle().
ProjectDepsDlg::~ProjectDepsDlg () virtual
Member Function Documentation
void ProjectDepsDlg::EndModal (int retCode) virtual
References ScriptBindings::EndModal(), and SaveList().
void ProjectDepsDlg::FillList () protected
References Manager::Get(), ProjectManager::GetDependenciesForProject(), Manager::GetProjectManager(), ProjectManager::GetProjects(), CompileTargetBase::GetTitle(), m_LastSel, and SaveList().
Referenced by OnProjectChange().
void ProjectDepsDlg::OnProjectChange (wxCommandEvent & event) protected
References FillList().
bool ProjectDepsDlg::SaveList () protected
References cbMessageBox(), ProjectManager::ClearProjectDependencies(), Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetProjects(), CompileTargetBase::GetTitle(), and m_LastSel.
Referenced by EndModal(), and FillList().
Member Data Documentation
int ProjectDepsDlg::m_LastSel protected
Referenced by FillList(), and SaveList().
The documentation for this class was generated from the following files:
projectdepsdlg.h
projectdepsdlg.cpp