Code::Blocks: wxSwitcherItem Class Reference
wxSwitcherItem Class Reference
#include <switcherdlg.h>
Public Member Functions
wxSwitcherItem ()
wxSwitcherItem (const wxSwitcherItem &item)
bool operator== (const wxSwitcherItem &item) const
void operator= (const wxSwitcherItem &item)
void Init ()
void Copy (const wxSwitcherItem &item)
wxSwitcherItem & SetTitle (const wxString &title)
const wxString & GetTitle () const
wxSwitcherItem & SetName (const wxString &name)
const wxString & GetName () const
wxSwitcherItem & SetDescription (const wxString &descr)
const wxString & GetDescription () const
wxSwitcherItem & SetId (int id)
int GetId () const
wxSwitcherItem & SetIsGroup (bool isGroup)
bool GetIsGroup () const
wxSwitcherItem & BreakColumn (bool breakCol=true)
bool GetBreakColumn () const
wxSwitcherItem & SetRect (const wxRect &rect)
const wxRect & GetRect () const
wxSwitcherItem & SetTextColour (const wxColour &colour)
const wxColour & GetTextColour () const
wxSwitcherItem & SetFont (const wxFont &font)
const wxFont & GetFont () const
wxSwitcherItem & SetBitmap (const wxBitmap &bitmap)
const wxBitmap & GetBitmap () const
wxSwitcherItem & SetRowPos (int pos)
int GetRowPos () const
wxSwitcherItem & SetColPos (int pos)
int GetColPos () const
wxSwitcherItem & SetWindow (wxWindow *win)
wxWindow * GetWindow () const
Protected Attributes
wxString m_title
wxString m_name
wxString m_description
int m_id
bool m_isGroup
bool m_breakColumn
wxRect m_rect
wxBitmap m_bitmap
wxColour m_textColour
wxFont m_font
int m_rowPos
int m_colPos
wxWindow * m_window
Detailed Description
wxSwitcherItem An object containing information about one item
Definition at line 25 of file switcherdlg.h.
Constructor & Destructor Documentation
wxSwitcherItem() [1/2]
wxSwitcherItem::wxSwitcherItem () inline
Definition at line 29 of file switcherdlg.h.
References Init().
wxSwitcherItem() [2/2]
wxSwitcherItem::wxSwitcherItem (const wxSwitcherItem & item) inline
Definition at line 30 of file switcherdlg.h.
References Copy(), Init(), and operator==().
Member Function Documentation
BreakColumn()
wxSwitcherItem& wxSwitcherItem::BreakColumn (bool breakCol = true) inline
Definition at line 59 of file switcherdlg.h.
References m_breakColumn.
Copy()
void wxSwitcherItem::Copy (const wxSwitcherItem & item)
Definition at line 47 of file switcherdlg.cpp.
References m_bitmap, m_breakColumn, m_colPos, m_description, m_font, m_id, m_isGroup, m_name, m_rect, m_rowPos, m_textColour, m_title, and m_window.
Referenced by operator=(), wxSwitcherItems::operator=(), wxSwitcherItem(), and wxSwitcherItems::wxSwitcherItems().
GetBitmap()
const wxBitmap& wxSwitcherItem::GetBitmap () const inline
Definition at line 72 of file switcherdlg.h.
References m_bitmap.
Referenced by wxSwitcherItems::PaintItems().
GetBreakColumn()
bool wxSwitcherItem::GetBreakColumn () const inline
Definition at line 60 of file switcherdlg.h.
References m_breakColumn.
GetColPos()
int wxSwitcherItem::GetColPos () const inline
Definition at line 78 of file switcherdlg.h.
References m_colPos.
Referenced by wxMultiColumnListCtrl::OnKey().
GetDescription()
const wxString& wxSwitcherItem::GetDescription () const inline
Definition at line 51 of file switcherdlg.h.
References m_description.
Referenced by wxSwitcherDialog::ShowDescription().
GetFont()
const wxFont& wxSwitcherItem::GetFont () const inline
Definition at line 69 of file switcherdlg.h.
References m_font.
Referenced by wxSwitcherItems::CalculateItemSize(), and wxSwitcherItems::PaintItems().
GetId()
int wxSwitcherItem::GetId () const inline
Definition at line 54 of file switcherdlg.h.
References m_id.
Referenced by wxSwitcherItems::FindItemById(), wxMultiColumnListCtrl::GenerateSelectionEvent(), and MainFrame::OnSwitchTabs().
GetIsGroup()
bool wxSwitcherItem::GetIsGroup () const inline
Definition at line 57 of file switcherdlg.h.
References m_isGroup.
Referenced by wxMultiColumnListCtrl::AdvanceToNextSelectableItem(), wxSwitcherItems::CalculateItemSize(), wxSwitcherItems::HitTest(), and wxSwitcherItems::PaintItems().
GetName()
const wxString& wxSwitcherItem::GetName () const inline
Definition at line 48 of file switcherdlg.h.
References m_name.
Referenced by wxSwitcherItems::FindItemByName().
GetRect()
const wxRect& wxSwitcherItem::GetRect () const inline
Definition at line 63 of file switcherdlg.h.
References m_rect.
Referenced by wxSwitcherItems::HitTest(), and wxSwitcherItems::PaintItems().
GetRowPos()
int wxSwitcherItem::GetRowPos () const inline
Definition at line 75 of file switcherdlg.h.
References m_rowPos.
Referenced by wxMultiColumnListCtrl::OnKey().
GetTextColour()
const wxColour& wxSwitcherItem::GetTextColour () const inline
Definition at line 66 of file switcherdlg.h.
References m_textColour.
Referenced by wxSwitcherItems::PaintItems().
GetTitle()
const wxString& wxSwitcherItem::GetTitle () const inline
Definition at line 45 of file switcherdlg.h.
References m_title.
Referenced by wxSwitcherItems::CalculateItemSize(), wxSwitcherItems::PaintItems(), and wxSwitcherDialog::ShowDescription().
GetWindow()
wxWindow* wxSwitcherItem::GetWindow () const inline
Definition at line 81 of file switcherdlg.h.
References m_window.
Referenced by wxSwitcherItems::GetIndexForFocus(), and MainFrame::OnSwitchTabs().
Init()
void wxSwitcherItem::Init ()
An object containing information about one item
Definition at line 37 of file switcherdlg.cpp.
References NULL.
Referenced by wxMultiColumnListCtrl::InvalidateLayout(), operator=(), wxSwitcherItems::operator=(), wxMultiColumnListCtrl::wxMultiColumnListCtrl(), wxSwitcherDialog::wxSwitcherDialog(), wxSwitcherItem(), and wxSwitcherItems::wxSwitcherItems().
operator=()
void wxSwitcherItem::operator= (const wxSwitcherItem & item) inline
Definition at line 38 of file switcherdlg.h.
References Copy(), and Init().
operator==()
bool wxSwitcherItem::operator== (const wxSwitcherItem & item) const
Definition at line 64 of file switcherdlg.cpp.
References m_breakColumn, m_colPos, m_description, m_font, m_id, m_isGroup, m_name, m_rect, m_rowPos, m_textColour, m_title, and m_window.
Referenced by wxSwitcherItem(), and wxSwitcherItems::wxSwitcherItems().
SetBitmap()
wxSwitcherItem& wxSwitcherItem::SetBitmap (const wxBitmap & bitmap) inline
Definition at line 71 of file switcherdlg.h.
References m_bitmap.
Referenced by wxSwitcherItems::AddItem().
SetColPos()
wxSwitcherItem& wxSwitcherItem::SetColPos (int pos) inline
Definition at line 77 of file switcherdlg.h.
References m_colPos.
SetDescription()
wxSwitcherItem& wxSwitcherItem::SetDescription (const wxString & descr) inline
Definition at line 50 of file switcherdlg.h.
References m_description.
Referenced by wxSwitcherItems::AddItem().
SetFont()
wxSwitcherItem& wxSwitcherItem::SetFont (const wxFont & font) inline
Definition at line 68 of file switcherdlg.h.
References m_font.
SetId()
wxSwitcherItem& wxSwitcherItem::SetId (int id) inline
Definition at line 53 of file switcherdlg.h.
References m_id.
Referenced by wxSwitcherItems::AddItem().
SetIsGroup()
wxSwitcherItem& wxSwitcherItem::SetIsGroup (bool isGroup) inline
Definition at line 56 of file switcherdlg.h.
References m_isGroup.
Referenced by wxSwitcherItems::AddGroup().
SetName()
wxSwitcherItem& wxSwitcherItem::SetName (const wxString & name) inline
Definition at line 47 of file switcherdlg.h.
References m_name.
Referenced by wxSwitcherItems::AddItem().
SetRect()
wxSwitcherItem& wxSwitcherItem::SetRect (const wxRect & rect) inline
Definition at line 62 of file switcherdlg.h.
References m_rect.
SetRowPos()
wxSwitcherItem& wxSwitcherItem::SetRowPos (int pos) inline
Definition at line 74 of file switcherdlg.h.
References m_rowPos.
SetTextColour()
wxSwitcherItem& wxSwitcherItem::SetTextColour (const wxColour & colour) inline
Definition at line 65 of file switcherdlg.h.
References m_textColour.
SetTitle()
wxSwitcherItem& wxSwitcherItem::SetTitle (const wxString & title) inline
Definition at line 44 of file switcherdlg.h.
References m_title.
Referenced by wxSwitcherItems::AddItem().
SetWindow()
wxSwitcherItem& wxSwitcherItem::SetWindow (wxWindow * win) inline
Definition at line 80 of file switcherdlg.h.
References m_window.
Member Data Documentation
m_bitmap
wxBitmap wxSwitcherItem::m_bitmap protected
Definition at line 92 of file switcherdlg.h.
Referenced by Copy(), GetBitmap(), and SetBitmap().
m_breakColumn
bool wxSwitcherItem::m_breakColumn protected
Definition at line 90 of file switcherdlg.h.
Referenced by BreakColumn(), Copy(), GetBreakColumn(), and operator==().
m_colPos
int wxSwitcherItem::m_colPos protected
Definition at line 96 of file switcherdlg.h.
Referenced by Copy(), GetColPos(), operator==(), and SetColPos().
m_description
wxString wxSwitcherItem::m_description protected
Definition at line 87 of file switcherdlg.h.
Referenced by Copy(), GetDescription(), operator==(), and SetDescription().
m_font
wxFont wxSwitcherItem::m_font protected
Definition at line 94 of file switcherdlg.h.
Referenced by Copy(), GetFont(), operator==(), and SetFont().
m_id
int wxSwitcherItem::m_id protected
Definition at line 88 of file switcherdlg.h.
Referenced by Copy(), GetId(), operator==(), and SetId().
m_isGroup
bool wxSwitcherItem::m_isGroup protected
Definition at line 89 of file switcherdlg.h.
Referenced by Copy(), GetIsGroup(), operator==(), and SetIsGroup().
m_name
wxString wxSwitcherItem::m_name protected
Definition at line 86 of file switcherdlg.h.
Referenced by Copy(), GetName(), operator==(), and SetName().
m_rect
wxRect wxSwitcherItem::m_rect protected
Definition at line 91 of file switcherdlg.h.
Referenced by Copy(), GetRect(), operator==(), and SetRect().
m_rowPos
int wxSwitcherItem::m_rowPos protected
Definition at line 95 of file switcherdlg.h.
Referenced by Copy(), GetRowPos(), operator==(), and SetRowPos().
m_textColour
wxColour wxSwitcherItem::m_textColour protected
Definition at line 93 of file switcherdlg.h.
Referenced by Copy(), wxSwitcherItems::Copy(), GetTextColour(), wxSwitcherItems::GetTextColour(), operator==(), wxSwitcherItems::operator==(), SetTextColour(), and wxSwitcherItems::SetTextColour().
m_title
wxString wxSwitcherItem::m_title protected
Definition at line 85 of file switcherdlg.h.
Referenced by Copy(), GetTitle(), operator==(), and SetTitle().
m_window
wxWindow* wxSwitcherItem::m_window protected
Definition at line 97 of file switcherdlg.h.
Referenced by Copy(), GetWindow(), operator==(), and SetWindow().
The documentation for this class was generated from the following files:
switcherdlg.h
switcherdlg.cpp