Code::Blocks: ProjectsFileMasksDlg Class Reference
ProjectsFileMasksDlg Class Reference
#include <projectsfilemasksdlg.h>
Public Member Functions
ProjectsFileMasksDlg (wxWindow *parent, FilesGroupsAndMasks *fgam)
virtual ~ProjectsFileMasksDlg ()
void OnUpdateUI (wxUpdateUIEvent &event)
void OnAdd (wxCommandEvent &event)
void OnEdit (wxCommandEvent &event)
void OnDelete (wxCommandEvent &event)
void OnSetDefault (wxCommandEvent &event)
void OnListChanged (wxCommandEvent &event)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void RebuildList ()
void ListChange ()
virtual void EndModal (int retCode)
DECLARE_EVENT_TABLE ()
Private Attributes
FilesGroupsAndMasks m_FileGroupsAndMasksCopy
FilesGroupsAndMasks * m_pFileGroupsAndMasks
int m_LastListSelection
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
ProjectsFileMasksDlg::ProjectsFileMasksDlg (wxWindow * parent, FilesGroupsAndMasks * fgam)
ProjectsFileMasksDlg::~ProjectsFileMasksDlg () virtual
Member Function Documentation
ProjectsFileMasksDlg::DECLARE_EVENT_TABLE () private
void ProjectsFileMasksDlg::EndModal (int retCode) private virtual
References FilesGroupsAndMasks::CopyFrom(), ScriptBindings::EndModal(), FilesGroupsAndMasks::GetFileMasks(), m_FileGroupsAndMasksCopy, m_LastListSelection, m_pFileGroupsAndMasks, and FilesGroupsAndMasks::SetFileMasks().
void ProjectsFileMasksDlg::ListChange () private
References FilesGroupsAndMasks::GetFileMasks(), m_FileGroupsAndMasksCopy, m_LastListSelection, and FilesGroupsAndMasks::SetFileMasks().
Referenced by OnAdd(), OnListChanged(), and RebuildList().
void ProjectsFileMasksDlg::OnAdd (wxCommandEvent & event)
References FilesGroupsAndMasks::AddGroup(), ListChange(), and m_FileGroupsAndMasksCopy.
void ProjectsFileMasksDlg::OnDelete (wxCommandEvent & event)
References cbMessageBox(), FilesGroupsAndMasks::DeleteGroup(), m_FileGroupsAndMasksCopy, and RebuildList().
void ProjectsFileMasksDlg::OnEdit (wxCommandEvent & event)
References m_FileGroupsAndMasksCopy, and FilesGroupsAndMasks::RenameGroup().
void ProjectsFileMasksDlg::OnListChanged (wxCommandEvent & event)
References ListChange().
void ProjectsFileMasksDlg::OnSetDefault (wxCommandEvent & event)
References m_FileGroupsAndMasksCopy, RebuildList(), and FilesGroupsAndMasks::SetDefault().
void ProjectsFileMasksDlg::OnUpdateUI (wxUpdateUIEvent & event)
void ProjectsFileMasksDlg::RebuildList () private
References FilesGroupsAndMasks::GetGroupName(), FilesGroupsAndMasks::GetGroupsCount(), ListChange(), m_FileGroupsAndMasksCopy, and m_LastListSelection.
Referenced by OnDelete(), and OnSetDefault().
Member Data Documentation
FilesGroupsAndMasks ProjectsFileMasksDlg::m_FileGroupsAndMasksCopy private
Referenced by EndModal(), ListChange(), OnAdd(), OnDelete(), OnEdit(), OnSetDefault(), and RebuildList().
int ProjectsFileMasksDlg::m_LastListSelection private
Referenced by EndModal(), ListChange(), and RebuildList().
FilesGroupsAndMasks* ProjectsFileMasksDlg::m_pFileGroupsAndMasks private
Referenced by EndModal().
The documentation for this class was generated from the following files:
projectsfilemasksdlg.h
projectsfilemasksdlg.cpp