Code::Blocks: ProjectLayoutLoader Class Reference
ProjectLayoutLoader Class Reference
#include <projectlayoutloader.h>
Public Member Functions
ProjectLayoutLoader (cbProject *project)
virtual ~ProjectLayoutLoader ()
bool Open (const wxString &filename)
bool Save (const wxString &filename)
bool LoadNotebookLayout ()
ProjectFile * GetTopProjectFile ()
Private Attributes
cbProject * m_pProject
ProjectFile * m_TopProjectFile
wxString m_NotebookLayout
Detailed Description
Definition at line 19 of file projectlayoutloader.h.
Constructor & Destructor Documentation
ProjectLayoutLoader()
ProjectLayoutLoader::ProjectLayoutLoader (cbProject * project)
Definition at line 30 of file projectlayoutloader.cpp.
~ProjectLayoutLoader()
ProjectLayoutLoader::~ProjectLayoutLoader () virtual
Definition at line 37 of file projectlayoutloader.cpp.
Member Function Documentation
GetTopProjectFile()
ProjectFile* ProjectLayoutLoader::GetTopProjectFile () inline
Definition at line 34 of file projectlayoutloader.h.
Referenced by cbProject::LoadLayout().
LoadNotebookLayout()
bool ProjectLayoutLoader::LoadNotebookLayout () inline
Definition at line 28 of file projectlayoutloader.h.
References Manager::Get(), Manager::GetEditorManager(), EditorManager::GetNotebook(), and cbAuiNotebook::LoadPerspective().
Referenced by cbProject::LoadLayout().
Open()
bool ProjectLayoutLoader::Open (const wxString & filename)
Definition at line 45 of file projectlayoutloader.cpp.
References _(), _T, cbC2U(), LogManager::DebugLog(), ProjectFile::editorFoldLinesArray, ProjectFile::editorOpen, ProjectFile::editorPos, ProjectFile::editorPos_2, ProjectFile::editorSplit, ProjectFile::editorSplitActive, ProjectFile::editorSplitPos, ProjectFile::editorTabPos, ProjectFile::editorTopLine, ProjectFile::editorTopLine_2, ProjectFile::editorZoom, ProjectFile::editorZoom_2, F(), wxString::Format(), Manager::Get(), cbProject::GetFileByFilename(), Manager::GetLogManager(), Manager::GetProjectManager(), Manager::IsBatchBuild(), wxString::IsEmpty(), TinyXML::LoadDocument(), m_NotebookLayout, m_pProject, m_TopProjectFile, AnnoyingDialog::OK, wxString::Prepend(), PROJECT_LAYOUT_FILE_VERSION_MAJOR, PROJECT_LAYOUT_FILE_VERSION_MINOR, cbProject::SetActiveBuildTarget(), AnnoyingDialog::ShowModal(), cbEditor::stNoSplit, CfgMgrConsts::version, wxString::wx_str(), wxART_INFORMATION, and wxART_WARNING.
Referenced by cbProject::LoadLayout().
Save()
bool ProjectLayoutLoader::Save (const wxString & filename)
Definition at line 249 of file projectlayoutloader.cpp.
References _T, cbSaveTinyXMLDocument(), cbU2C(), ProjectFile::editorFoldLinesArray, ProjectFile::editorOpen, ProjectFile::editorPos, ProjectFile::editorPos_2, ProjectFile::editorSplit, ProjectFile::editorSplitActive, ProjectFile::editorSplitPos, ProjectFile::editorTabPos, ProjectFile::editorTopLine, ProjectFile::editorTopLine_2, ProjectFile::editorZoom, ProjectFile::editorZoom_2, cbProject::ExpandedNodes(), Manager::Get(), cbProject::GetActiveBuildTarget(), EditorManager::GetBuiltinActiveEditor(), wxArrayString::GetCount(), Manager::GetEditorManager(), cbProject::GetFilesList(), cbEditor::GetProjectFile(), CompileTargetBase::GetTitle(), m_pProject, PROJECT_LAYOUT_FILE_VERSION_MAJOR, PROJECT_LAYOUT_FILE_VERSION_MINOR, ProjectFile::relativeFilename, and cbEditor::stNoSplit.
Referenced by cbProject::SaveLayout().
Member Data Documentation
m_NotebookLayout
wxString ProjectLayoutLoader::m_NotebookLayout private
Definition at line 39 of file projectlayoutloader.h.
Referenced by Open().
m_pProject
cbProject* ProjectLayoutLoader::m_pProject private
Definition at line 37 of file projectlayoutloader.h.
Referenced by Open(), and Save().
m_TopProjectFile
ProjectFile* ProjectLayoutLoader::m_TopProjectFile private
Definition at line 38 of file projectlayoutloader.h.
Referenced by Open().
The documentation for this class was generated from the following files:
projectlayoutloader.h
projectlayoutloader.cpp