Code::Blocks: cbException Class Reference
cbException Class Reference
Code::Blocks error handling unit.
#include <cbexception.h>
Public Member Functions
cbException (const wxString &msg, const wxString &file, int line)
virtual ~cbException ()
void ShowErrorMessage (bool safe=true)
Display exception error message.
Public Attributes
wxString Message
The exception's error message.
wxString File
The file where the exception was raised.
int Line
The line in the file where the exception was raised.
Detailed Description
Code::Blocks error handling unit.
Two macros are defined to help error handling in Code::Blocks: cbThrow() and cbAssert().
Note
cbAssert() does nothing in release mode. For debug mode, compile with -DcbDEBUGThe base Code::Blocks exception object.
Definition at line 23 of file cbexception.h.
Constructor & Destructor Documentation
cbException()
cbException::cbException (const wxString & msg, const wxString & file, int line)
Definition at line 21 of file cbexception.cpp.
~cbException()
cbException::~cbException () virtual
Definition at line 27 of file cbexception.cpp.
Member Function Documentation
ShowErrorMessage()
void cbException::ShowErrorMessage (bool safe = true)
Display exception error message.
Parameters
safe If true, wxSafeShowMessage will be used to display the error, else a normal message box will be used.
Definition at line 31 of file cbexception.cpp.
References _(), _T, wxString::c_str(), cbMessageBox(), File, ConfigManager::GetRevisionNumber(), Line, Message, wxString::Printf(), wxICON_ERROR, wxSafeShowMessage(), and wxT.
Referenced by PluginManager::AskPluginsForModuleMenu(), MainFrame::CreateMenubar(), MainFrame::DoAddPlugin(), PluginManager::ExecutePlugin(), Wiz::Launch(), PluginManager::LoadAllPlugins(), PluginManager::LoadPlugin(), CompilerOptionsDlg::OnAddCompilerClick(), CodeBlocksApp::OnInit(), and CodeBlocksApp::OnRun().
Member Data Documentation
File
wxString cbException::File
The file where the exception was raised.
Definition at line 37 of file cbexception.h.
Referenced by ShowErrorMessage().
Line
int cbException::Line
The line in the file where the exception was raised.
Definition at line 38 of file cbexception.h.
Referenced by ShowErrorMessage().
Message
wxString cbException::Message
The exception's error message.
Definition at line 36 of file cbexception.h.
Referenced by ShowErrorMessage().
The documentation for this class was generated from the following files:
cbexception.h
cbexception.cpp