Code::Blocks: ProjectFileOptionsDlg Class Reference
ProjectFileOptionsDlg Class Reference
#include <projectfileoptionsdlg.h>
Public Member Functions
ProjectFileOptionsDlg (wxWindow *parent, ProjectFile *pf)
ProjectFileOptionsDlg (wxWindow *parent, const wxString &fileName)
~ProjectFileOptionsDlg ()
void OnReadOnlyCheck (wxCommandEvent &event)
void OnCompilerCombo (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void FillGeneralProperties ()
void FillCompilers ()
void UpdateBuildCommand ()
void SaveBuildCommandSelection ()
bool ToggleFileReadOnly (bool setReadOnly)
Private Attributes
ProjectFile * m_ProjectFile
wxString m_FileNameStr
wxFileName m_FileName
int m_LastBuildStageCompilerSel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 14 of file projectfileoptionsdlg.h.
Constructor & Destructor Documentation
ProjectFileOptionsDlg() [1/2]
ProjectFileOptionsDlg::ProjectFileOptionsDlg (wxWindow * parent, ProjectFile * pf)
Definition at line 144 of file projectfileoptionsdlg.cpp.
References ProjectFile::AutoGeneratedBy(), ProjectFile::buildTargets, ProjectFile::compile, ProjectFile::compilerVar, ProjectFile::file, FillCompilers(), FillGeneralProperties(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), cbProject::GetCommonTopLevelPath(), CompileTargetBase::GetFilename(), ProjectFile::GetObjName(), ProjectFile::GetParentProject(), CompileTargetBase::GetTitle(), ProjectFile::link, m_FileNameStr, ProjectFile::relativeFilename, UpdateBuildCommand(), and ProjectFile::weight.
ProjectFileOptionsDlg() [2/2]
ProjectFileOptionsDlg::ProjectFileOptionsDlg (wxWindow * parent, const wxString & fileName)
Definition at line 197 of file projectfileoptionsdlg.cpp.
References FillGeneralProperties(), and m_FileNameStr.
~ProjectFileOptionsDlg()
ProjectFileOptionsDlg::~ProjectFileOptionsDlg ()
Definition at line 213 of file projectfileoptionsdlg.cpp.
Member Function Documentation
EndModal()
void ProjectFileOptionsDlg::EndModal (int retCode)
Definition at line 274 of file projectfileoptionsdlg.cpp.
References ProjectFile::AddBuildTarget(), ProjectFile::compile, ProjectFile::compilerVar, ScriptBindings::EndModal(), Manager::Get(), ProjectFile::GetParentProject(), Manager::GetProjectManager(), ProjectManager::GetUI(), ProjectFile::link, m_ProjectFile, cbProjectManagerUI::RebuildTree(), ProjectFile::RemoveBuildTarget(), SaveBuildCommandSelection(), cbProject::SetModified(), and ProjectFile::weight.
FillCompilers()
void ProjectFileOptionsDlg::FillCompilers () private
Definition at line 348 of file projectfileoptionsdlg.cpp.
References CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetCompilerIndex(), CompilerFactory::GetCompilersCount(), Compiler::GetName(), ProjectFile::GetParentProject(), m_LastBuildStageCompilerSel, and m_ProjectFile.
Referenced by ProjectFileOptionsDlg().
FillGeneralProperties()
void ProjectFileOptionsDlg::FillGeneralProperties () private
Definition at line 306 of file projectfileoptionsdlg.cpp.
References CountLines(), Manager::Get(), EditorManager::GetColourSet(), EditorColourSet::GetCommentToken(), Manager::GetEditorManager(), EditorColourSet::GetLanguageForFilename(), HL_NONE, m_FileName, and m_FileNameStr.
Referenced by ProjectFileOptionsDlg().
OnCompilerCombo()
void ProjectFileOptionsDlg::OnCompilerCombo (wxCommandEvent & event)
Definition at line 241 of file projectfileoptionsdlg.cpp.
References m_LastBuildStageCompilerSel, SaveBuildCommandSelection(), and UpdateBuildCommand().
OnReadOnlyCheck()
void ProjectFileOptionsDlg::OnReadOnlyCheck (wxCommandEvent & event)
Definition at line 217 of file projectfileoptionsdlg.cpp.
References EditorManager::CheckForExternallyModifiedFiles(), LogManager::DebugLog(), F(), Manager::Get(), Manager::GetEditorManager(), Manager::GetLogManager(), m_FileName, m_FileNameStr, and ToggleFileReadOnly().
OnUpdateUI()
void ProjectFileOptionsDlg::OnUpdateUI (wxUpdateUIEvent & event)
Definition at line 254 of file projectfileoptionsdlg.cpp.
References m_ProjectFile.
SaveBuildCommandSelection()
void ProjectFileOptionsDlg::SaveBuildCommandSelection () private
Definition at line 385 of file projectfileoptionsdlg.cpp.
References ProjectFile::customBuild, CompilerFactory::GetCompiler(), Compiler::GetID(), m_LastBuildStageCompilerSel, and m_ProjectFile.
Referenced by EndModal(), and OnCompilerCombo().
ToggleFileReadOnly()
bool ProjectFileOptionsDlg::ToggleFileReadOnly (bool setReadOnly) private
Definition at line 395 of file projectfileoptionsdlg.cpp.
References LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), m_FileName, and m_FileNameStr.
Referenced by OnReadOnlyCheck().
UpdateBuildCommand()
void ProjectFileOptionsDlg::UpdateBuildCommand () private
Definition at line 364 of file projectfileoptionsdlg.cpp.
References ctCompileObjectCmd, ctCompileResourceCmd, ProjectFile::customBuild, FileTypeOf(), ftHeader, ftResource, ftSource, Compiler::GetCommand(), CompilerFactory::GetCompiler(), Compiler::GetID(), m_ProjectFile, and ProjectFile::relativeFilename.
Referenced by OnCompilerCombo(), and ProjectFileOptionsDlg().
Member Data Documentation
m_FileName
wxFileName ProjectFileOptionsDlg::m_FileName private
Definition at line 35 of file projectfileoptionsdlg.h.
Referenced by FillGeneralProperties(), OnReadOnlyCheck(), and ToggleFileReadOnly().
m_FileNameStr
wxString ProjectFileOptionsDlg::m_FileNameStr private
Definition at line 34 of file projectfileoptionsdlg.h.
Referenced by FillGeneralProperties(), OnReadOnlyCheck(), ProjectFileOptionsDlg(), and ToggleFileReadOnly().
m_LastBuildStageCompilerSel
int ProjectFileOptionsDlg::m_LastBuildStageCompilerSel private
Definition at line 36 of file projectfileoptionsdlg.h.
Referenced by FillCompilers(), OnCompilerCombo(), and SaveBuildCommandSelection().
m_ProjectFile
ProjectFile* ProjectFileOptionsDlg::m_ProjectFile private
Definition at line 33 of file projectfileoptionsdlg.h.
Referenced by EndModal(), FillCompilers(), OnUpdateUI(), SaveBuildCommandSelection(), and UpdateBuildCommand().
The documentation for this class was generated from the following files:
projectfileoptionsdlg.h
projectfileoptionsdlg.cpp