Code::Blocks: UsrGlblMgrEditDialog Class Reference
UsrGlblMgrEditDialog Class Reference
Public Member Functions
UsrGlblMgrEditDialog (const wxString &var=wxEmptyString)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void Help (wxCommandEvent &event)
void DoClose ()
void OnOK (cb_unused wxCommandEvent &event)
void OnCancel (cb_unused wxCommandEvent &event)
void CloseHandler (cb_unused wxCloseEvent &event)
void CloneVar (wxCommandEvent &event)
void CloneSet (wxCommandEvent &event)
void NewVar (wxCommandEvent &event)
void NewSet (wxCommandEvent &event)
void DeleteVar (wxCommandEvent &event)
void DeleteSet (wxCommandEvent &event)
void OnFS (wxCommandEvent &event)
void SelectSet (wxCommandEvent &event)
void SelectVar (wxCommandEvent &event)
void Load ()
void Save ()
void UpdateChoices ()
void AddVar (const wxString &var)
void Sanitise (wxString &s)
Private Attributes
wxString m_CurrentSet
wxString m_CurrentVar
wxChoice * m_SelSet
wxListBox * m_SelVar
wxButton * m_DeleteSet
wxTextCtrl * m_Base
wxTextCtrl * m_Include
wxTextCtrl * m_Lib
wxTextCtrl * m_Obj
wxTextCtrl * m_Bin
wxTextCtrl * m_Name [7]
wxTextCtrl * m_Value [7]
ConfigManager * m_CfgMan
Friends
class UserVariableManager
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 91 of file uservarmanager.cpp.
Constructor & Destructor Documentation
UsrGlblMgrEditDialog()
UsrGlblMgrEditDialog::UsrGlblMgrEditDialog (const wxString & var = wxEmptyString)
Definition at line 457 of file uservarmanager.cpp.
References ConfigManager::Exists(), Manager::Get(), Manager::GetConfigManager(), GetUserVariableDialog::Load(), and PlaceWindow().
Member Function Documentation
AddVar()
void UsrGlblMgrEditDialog::AddVar (const wxString & var) private
Definition at line 614 of file uservarmanager.cpp.
References GetUserVariableDialog::Load().
Referenced by UserVariableManager::Arrogate(), and UserVariableManager::Replace().
CloneSet()
void UsrGlblMgrEditDialog::CloneSet (wxCommandEvent & event) private
Definition at line 538 of file uservarmanager.cpp.
References cSets(), InfoWindow::Display(), GetUserVariableDialog::Load(), and PlaceWindow().
Referenced by GetUserVariableDialog::GetSelectedVariable().
CloneVar()
void UsrGlblMgrEditDialog::CloneVar (wxCommandEvent & event) private
Definition at line 501 of file uservarmanager.cpp.
References InfoWindow::Display(), GetUserVariableDialog::Load(), and PlaceWindow().
Referenced by GetUserVariableDialog::GetSelectedVariable().
CloseHandler()
void UsrGlblMgrEditDialog::CloseHandler (cb_unused wxCloseEvent & event) inline private
Definition at line 116 of file uservarmanager.cpp.
References GetUserVariableDialog::Load().
Referenced by GetUserVariableDialog::GetSelectedVariable().
DeleteSet()
void UsrGlblMgrEditDialog::DeleteSet (wxCommandEvent & event) private
Definition at line 596 of file uservarmanager.cpp.
References cSets(), GetUserVariableDialog::Load(), PlaceWindow(), AnnoyingDialog::rtYES, and AnnoyingDialog::ShowModal().
Referenced by GetUserVariableDialog::GetSelectedVariable().
DeleteVar()
void UsrGlblMgrEditDialog::DeleteVar (wxCommandEvent & event) private
Definition at line 581 of file uservarmanager.cpp.
References cSets(), GetUserVariableDialog::Load(), PlaceWindow(), AnnoyingDialog::rtYES, and AnnoyingDialog::ShowModal().
Referenced by GetUserVariableDialog::GetSelectedVariable().
DoClose()
void UsrGlblMgrEditDialog::DoClose () private
Definition at line 494 of file uservarmanager.cpp.
References ScriptBindings::EndModal().
Help()
void UsrGlblMgrEditDialog::Help (wxCommandEvent & event) private
Definition at line 820 of file uservarmanager.cpp.
Referenced by GetUserVariableDialog::GetSelectedVariable().
Load()
void UsrGlblMgrEditDialog::Load () private
Definition at line 700 of file uservarmanager.cpp.
References builtinMembers(), cSets(), and SetValue().
NewSet()
void UsrGlblMgrEditDialog::NewSet (wxCommandEvent & event) private
Definition at line 663 of file uservarmanager.cpp.
References GetUserVariableDialog::Load(), and PlaceWindow().
Referenced by GetUserVariableDialog::GetSelectedVariable().
NewVar()
void UsrGlblMgrEditDialog::NewVar (wxCommandEvent & event) private
Definition at line 650 of file uservarmanager.cpp.
References PlaceWindow().
Referenced by GetUserVariableDialog::GetSelectedVariable().
OnCancel()
void UsrGlblMgrEditDialog::OnCancel (cb_unused wxCommandEvent & event) inline private
Definition at line 115 of file uservarmanager.cpp.
OnFS()
void UsrGlblMgrEditDialog::OnFS (wxCommandEvent & event) private
Definition at line 797 of file uservarmanager.cpp.
References cbThrow, and ChooseDirectory().
Referenced by GetUserVariableDialog::GetSelectedVariable().
OnOK()
void UsrGlblMgrEditDialog::OnOK (cb_unused wxCommandEvent & event) inline private
Definition at line 114 of file uservarmanager.cpp.
Referenced by GetUserVariableDialog::GetSelectedVariable().
Sanitise()
void UsrGlblMgrEditDialog::Sanitise (wxString & s) private
Definition at line 626 of file uservarmanager.cpp.
Save()
void UsrGlblMgrEditDialog::Save () private
Definition at line 730 of file uservarmanager.cpp.
References builtinMembers(), cbMessageBox(), and cSets().
SelectSet()
void UsrGlblMgrEditDialog::SelectSet (wxCommandEvent & event) private
Definition at line 690 of file uservarmanager.cpp.
References GetUserVariableDialog::Load().
Referenced by GetUserVariableDialog::GetSelectedVariable().
SelectVar()
void UsrGlblMgrEditDialog::SelectVar (wxCommandEvent & event) private
Definition at line 683 of file uservarmanager.cpp.
References GetUserVariableDialog::Load().
Referenced by GetUserVariableDialog::GetSelectedVariable().
UpdateChoices()
void UsrGlblMgrEditDialog::UpdateChoices () private
Definition at line 774 of file uservarmanager.cpp.
References cSets().
Friends And Related Function Documentation
UserVariableManager
friend class UserVariableManager friend
Definition at line 140 of file uservarmanager.cpp.
Member Data Documentation
m_Base
wxTextCtrl* UsrGlblMgrEditDialog::m_Base private
Definition at line 101 of file uservarmanager.cpp.
m_Bin
wxTextCtrl* UsrGlblMgrEditDialog::m_Bin private
Definition at line 105 of file uservarmanager.cpp.
m_CfgMan
ConfigManager* UsrGlblMgrEditDialog::m_CfgMan private
Definition at line 110 of file uservarmanager.cpp.
m_CurrentSet
wxString UsrGlblMgrEditDialog::m_CurrentSet private
Definition at line 93 of file uservarmanager.cpp.
m_CurrentVar
wxString UsrGlblMgrEditDialog::m_CurrentVar private
Definition at line 94 of file uservarmanager.cpp.
m_DeleteSet
wxButton* UsrGlblMgrEditDialog::m_DeleteSet private
Definition at line 99 of file uservarmanager.cpp.
m_Include
wxTextCtrl* UsrGlblMgrEditDialog::m_Include private
Definition at line 102 of file uservarmanager.cpp.
m_Lib
wxTextCtrl* UsrGlblMgrEditDialog::m_Lib private
Definition at line 103 of file uservarmanager.cpp.
m_Name
wxTextCtrl* UsrGlblMgrEditDialog::m_Name[7] private
Definition at line 107 of file uservarmanager.cpp.
m_Obj
wxTextCtrl* UsrGlblMgrEditDialog::m_Obj private
Definition at line 104 of file uservarmanager.cpp.
m_SelSet
wxChoice* UsrGlblMgrEditDialog::m_SelSet private
Definition at line 96 of file uservarmanager.cpp.
m_SelVar
wxListBox* UsrGlblMgrEditDialog::m_SelVar private
Definition at line 97 of file uservarmanager.cpp.
m_Value
wxTextCtrl* UsrGlblMgrEditDialog::m_Value[7] private
Definition at line 108 of file uservarmanager.cpp.
The documentation for this class was generated from the following file:
uservarmanager.cpp