Code::Blocks: EditorLexerLoader Class Reference
EditorLexerLoader Class Reference
#include <editorlexerloader.h>
Public Member Functions
EditorLexerLoader (EditorColourSet *target)
virtual ~EditorLexerLoader ()
void Load (LoaderBase *loader)
Protected Member Functions
void DoLexer (TiXmlElement *node)
void DoStyles (HighlightLanguage language, TiXmlElement *node)
void DoKeywords (HighlightLanguage language, TiXmlElement *node)
void DoSingleKeywordNode (HighlightLanguage language, TiXmlElement *node, const wxString &nodename)
void DoSampleCode (HighlightLanguage language, TiXmlElement *node)
void DoLangAttributes (HighlightLanguage language, TiXmlElement *node)
bool DoLangAttributesLexerStyles (TiXmlElement *attribs, const char *attributeName, std::set< int > &styles)
Protected Attributes
EditorColourSet * m_pTarget
Detailed Description
Definition at line 15 of file editorlexerloader.h.
Constructor & Destructor Documentation
EditorLexerLoader()
EditorLexerLoader::EditorLexerLoader (EditorColourSet * target)
Definition at line 25 of file editorlexerloader.cpp.
~EditorLexerLoader()
EditorLexerLoader::~EditorLexerLoader () virtual
Definition at line 31 of file editorlexerloader.cpp.
Member Function Documentation
DoKeywords()
void EditorLexerLoader::DoKeywords (HighlightLanguage language, TiXmlElement * node) protected
Definition at line 156 of file editorlexerloader.cpp.
References _T, and DoSingleKeywordNode().
Referenced by DoLexer().
DoLangAttributes()
void EditorLexerLoader::DoLangAttributes (HighlightLanguage language, TiXmlElement * node) protected
Definition at line 207 of file editorlexerloader.cpp.
References CommentToken::boxCommentEnd, CommentToken::boxCommentMid, CommentToken::boxCommentStart, DoLangAttributesLexerStyles(), CommentToken::doxygenLineComment, CommentToken::doxygenStreamCommentEnd, CommentToken::doxygenStreamCommentStart, CommentToken::lineComment, m_pTarget, EditorColourSet::SetCaseSensitivity(), EditorColourSet::SetCharacterLexerStyles(), EditorColourSet::SetCommentLexerStyles(), EditorColourSet::SetCommentToken(), EditorColourSet::SetPreprocessorLexerStyles(), EditorColourSet::SetStringLexerStyles(), CommentToken::streamCommentEnd, and CommentToken::streamCommentStart.
Referenced by DoLexer().
DoLangAttributesLexerStyles()
bool EditorLexerLoader::DoLangAttributesLexerStyles (TiXmlElement * attribs, const char * attributeName, std::set< int > & styles) protected
Definition at line 249 of file editorlexerloader.cpp.
References _T, GetArrayFromString(), and wxString::IsEmpty().
Referenced by DoLangAttributes().
DoLexer()
void EditorLexerLoader::DoLexer (TiXmlElement * node) protected
Definition at line 74 of file editorlexerloader.cpp.
References _(), EditorColourSet::AddHighlightLanguage(), DoKeywords(), DoLangAttributes(), DoSampleCode(), DoStyles(), Manager::Get(), Manager::GetLogManager(), HL_NONE, LogManager::Log(), m_pTarget, and EditorColourSet::SetFileMasks().
Referenced by Load().
DoSampleCode()
void EditorLexerLoader::DoSampleCode (HighlightLanguage language, TiXmlElement * node) protected
Definition at line 193 of file editorlexerloader.cpp.
References wxString::IsEmpty(), m_pTarget, and EditorColourSet::SetSampleCode().
Referenced by DoLexer().
DoSingleKeywordNode()
void EditorLexerLoader::DoSingleKeywordNode (HighlightLanguage language, TiXmlElement * node, const wxString & nodename) protected
Definition at line 167 of file editorlexerloader.cpp.
References _T, m_pTarget, wxString::mb_str(), wxRegEx::Replace(), and EditorColourSet::SetKeywords().
Referenced by DoKeywords().
DoStyles()
void EditorLexerLoader::DoStyles (HighlightLanguage language, TiXmlElement * node) protected
Definition at line 97 of file editorlexerloader.cpp.
References _T, EditorColourSet::AddOption(), Doxygen::B, GetArrayFromString(), wxArrayString::GetCount(), m_pTarget, wxColour::Set(), and wxNullColour.
Referenced by DoLexer().
Load()
void EditorLexerLoader::Load (LoaderBase * loader)
Definition at line 36 of file editorlexerloader.cpp.
References _(), cbC2U(), DoLexer(), LoaderBase::FileName(), Manager::Get(), LoaderBase::GetData(), Manager::GetLogManager(), and LogManager::Log().
Referenced by EditorColourSet::LoadAvailableSets().
Member Data Documentation
m_pTarget
EditorColourSet* EditorLexerLoader::m_pTarget protected
Definition at line 30 of file editorlexerloader.h.
Referenced by DoLangAttributes(), DoLexer(), DoSampleCode(), DoSingleKeywordNode(), and DoStyles().
The documentation for this class was generated from the following files:
editorlexerloader.h
editorlexerloader.cpp