Code::Blocks: FindReplaceDlg Class Reference
FindReplaceDlg Class Reference
#include <findreplacedlg.h>
Public Member Functions
FindReplaceDlg (wxWindow *parent, const wxString &initial=wxEmptyString, bool hasSelection=false, bool findMode=true, bool findReplaceInFilesOnly=false, bool findReplaceInFilesActive=false)
~FindReplaceDlg ()
wxString GetFindString () const
wxString GetReplaceString () const
bool IsFindInFiles () const
bool GetDeleteOldSearches () const
bool GetSortSearchResult () const
bool GetMatchWord () const
bool GetStartWord () const
bool GetMatchCase () const
bool GetRegEx () const
bool GetAutoWrapSearch () const
bool GetFindUsesSelectedText () const
bool GetStartFile () const
bool GetMultiLine () const
bool GetFixEOLs () const
int GetDirection () const
int GetOrigin () const
int GetScope () const
bool GetRecursive () const
bool GetHidden () const
wxString GetSearchPath () const
wxString GetSearchMask () const
int GetProject () const
int GetTarget () const
bool IsMultiLine () const
Public Member Functions inherited from FindReplaceBase
FindReplaceBase (cb_optional wxWindow *parent, cb_optional const wxString &initial, cb_optional bool hasSelection)
virtual ~FindReplaceBase ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void OnReplaceChange (wxNotebookEvent &event)
void OnRegEx (wxCommandEvent &event)
void OnActivate (wxActivateEvent &event)
void OnMultiChange (wxCommandEvent &event)
void OnLimitToChange (wxCommandEvent &event)
void OnScopeChange (wxCommandEvent &event)
void OnBrowsePath (wxCommandEvent &event)
void OnSearchProject (wxCommandEvent &event)
void OnDeferredFocus (wxCommandEvent &event)
Private Member Functions
void FillComboWithLastValues (wxComboBox *combo, const wxString &configKey)
void SaveComboValues (wxComboBox *combo, const wxString &configKey)
Private Attributes
bool m_findReplaceInFilesActive
bool m_findMode
wxWindow * m_findPage
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 16 of file findreplacedlg.h.
Constructor & Destructor Documentation
FindReplaceDlg()
FindReplaceDlg::FindReplaceDlg (wxWindow * parent, const wxString & initial = wxEmptyString, bool hasSelection = false, bool findMode = true, bool findReplaceInFilesOnly = false, bool findReplaceInFilesActive = false)
Definition at line 58 of file findreplacedlg.cpp.
References CONF_GROUP, ConfigManager::Exists(), Manager::Get(), cbProject::GetActiveBuildTarget(), ProjectManager::GetActiveProject(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), EditorManager::GetBuiltinEditor(), Manager::GetConfigManager(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), Manager::GetProjectManager(), ProjectManager::GetProjects(), CompileTargetBase::GetTitle(), OnReplaceChange(), ConfigManager::Read(), ConfigManager::ReadBool(), ConfigManager::ReadInt(), and ConfigManager::UnSet().
~FindReplaceDlg()
FindReplaceDlg::~FindReplaceDlg ()
Definition at line 271 of file findreplacedlg.cpp.
References CONF_GROUP, Manager::Get(), Manager::GetConfigManager(), IsFindInFiles(), m_findPage, m_findReplaceInFilesActive, OnReplaceChange(), SaveComboValues(), and ConfigManager::Write().
Member Function Documentation
FillComboWithLastValues()
void FindReplaceDlg::FillComboWithLastValues (wxComboBox * combo, const wxString & configKey) private
Definition at line 716 of file findreplacedlg.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Read().
GetAutoWrapSearch()
bool FindReplaceDlg::GetAutoWrapSearch () const virtual
Implements FindReplaceBase.
Definition at line 426 of file findreplacedlg.cpp.
References IsFindInFiles().
GetDeleteOldSearches()
bool FindReplaceDlg::GetDeleteOldSearches () const virtual
Implements FindReplaceBase.
Definition at line 376 of file findreplacedlg.cpp.
References IsFindInFiles().
GetDirection()
int FindReplaceDlg::GetDirection () const virtual
Implements FindReplaceBase.
Definition at line 463 of file findreplacedlg.cpp.
References IsFindInFiles().
GetFindString()
wxString FindReplaceDlg::GetFindString () const virtual
Implements FindReplaceBase.
Definition at line 341 of file findreplacedlg.cpp.
References IsFindInFiles(), and IsMultiLine().
GetFindUsesSelectedText()
bool FindReplaceDlg::GetFindUsesSelectedText () const virtual
Implements FindReplaceBase.
Definition at line 433 of file findreplacedlg.cpp.
GetFixEOLs()
bool FindReplaceDlg::GetFixEOLs () const virtual
Implements FindReplaceBase.
Definition at line 456 of file findreplacedlg.cpp.
References IsFindInFiles().
GetHidden()
bool FindReplaceDlg::GetHidden () const virtual
Implements FindReplaceBase.
Definition at line 489 of file findreplacedlg.cpp.
GetMatchCase()
bool FindReplaceDlg::GetMatchCase () const virtual
Implements FindReplaceBase.
Definition at line 412 of file findreplacedlg.cpp.
References IsFindInFiles().
GetMatchWord()
bool FindReplaceDlg::GetMatchWord () const virtual
Implements FindReplaceBase.
Definition at line 389 of file findreplacedlg.cpp.
References IsFindInFiles().
GetMultiLine()
bool FindReplaceDlg::GetMultiLine () const virtual
Implements FindReplaceBase.
Definition at line 449 of file findreplacedlg.cpp.
References IsFindInFiles().
GetOrigin()
int FindReplaceDlg::GetOrigin () const virtual
Implements FindReplaceBase.
Definition at line 470 of file findreplacedlg.cpp.
References IsFindInFiles().
GetProject()
int FindReplaceDlg::GetProject () const virtual
Implements FindReplaceBase.
Definition at line 504 of file findreplacedlg.cpp.
GetRecursive()
bool FindReplaceDlg::GetRecursive () const virtual
Implements FindReplaceBase.
Definition at line 484 of file findreplacedlg.cpp.
GetRegEx()
bool FindReplaceDlg::GetRegEx () const virtual
Implements FindReplaceBase.
Definition at line 419 of file findreplacedlg.cpp.
References IsFindInFiles().
GetReplaceString()
wxString FindReplaceDlg::GetReplaceString () const virtual
Implements FindReplaceBase.
Definition at line 355 of file findreplacedlg.cpp.
References IsFindInFiles(), and IsMultiLine().
GetScope()
int FindReplaceDlg::GetScope () const virtual
Implements FindReplaceBase.
Definition at line 477 of file findreplacedlg.cpp.
References IsFindInFiles().
GetSearchMask()
wxString FindReplaceDlg::GetSearchMask () const virtual
Implements FindReplaceBase.
Definition at line 499 of file findreplacedlg.cpp.
GetSearchPath()
wxString FindReplaceDlg::GetSearchPath () const virtual
Implements FindReplaceBase.
Definition at line 494 of file findreplacedlg.cpp.
GetSortSearchResult()
bool FindReplaceDlg::GetSortSearchResult () const virtual
Implements FindReplaceBase.
Definition at line 384 of file findreplacedlg.cpp.
GetStartFile()
bool FindReplaceDlg::GetStartFile () const virtual
Implements FindReplaceBase.
Definition at line 438 of file findreplacedlg.cpp.
References IsFindInFiles().
GetStartWord()
bool FindReplaceDlg::GetStartWord () const virtual
Implements FindReplaceBase.
Definition at line 401 of file findreplacedlg.cpp.
References IsFindInFiles().
GetTarget()
int FindReplaceDlg::GetTarget () const virtual
Implements FindReplaceBase.
Definition at line 509 of file findreplacedlg.cpp.
IsFindInFiles()
bool FindReplaceDlg::IsFindInFiles () const virtual
Implements FindReplaceBase.
Definition at line 371 of file findreplacedlg.cpp.
References m_findReplaceInFilesActive.
Referenced by GetAutoWrapSearch(), GetDeleteOldSearches(), GetDirection(), GetFindString(), GetFixEOLs(), GetMatchCase(), GetMatchWord(), GetMultiLine(), GetOrigin(), GetRegEx(), GetReplaceString(), GetScope(), GetStartFile(), GetStartWord(), IsMultiLine(), OnActivate(), OnDeferredFocus(), and ~FindReplaceDlg().
IsMultiLine()
bool FindReplaceDlg::IsMultiLine () const
Definition at line 514 of file findreplacedlg.cpp.
References IsFindInFiles().
Referenced by GetFindString(), GetReplaceString(), OnActivate(), and OnDeferredFocus().
OnActivate()
void FindReplaceDlg::OnActivate (wxActivateEvent & event) protected
Definition at line 632 of file findreplacedlg.cpp.
References IsFindInFiles(), and IsMultiLine().
OnBrowsePath()
void FindReplaceDlg::OnBrowsePath (wxCommandEvent & event) protected
Definition at line 550 of file findreplacedlg.cpp.
References ChooseDirectory().
OnDeferredFocus()
void FindReplaceDlg::OnDeferredFocus (wxCommandEvent & event) protected
Definition at line 611 of file findreplacedlg.cpp.
References IsFindInFiles(), and IsMultiLine().
OnLimitToChange()
void FindReplaceDlg::OnLimitToChange (wxCommandEvent & event) protected
Definition at line 706 of file findreplacedlg.cpp.
OnMultiChange()
void FindReplaceDlg::OnMultiChange (wxCommandEvent & event) protected
Definition at line 651 of file findreplacedlg.cpp.
References m_findMode, and m_findPage.
OnRegEx()
void FindReplaceDlg::OnRegEx (wxCommandEvent & event) protected
Definition at line 627 of file findreplacedlg.cpp.
OnReplaceChange()
void FindReplaceDlg::OnReplaceChange (wxNotebookEvent & event) protected
Definition at line 575 of file findreplacedlg.cpp.
References m_findReplaceInFilesActive.
Referenced by FindReplaceDlg(), and ~FindReplaceDlg().
OnScopeChange()
void FindReplaceDlg::OnScopeChange (wxCommandEvent & event) protected
Definition at line 523 of file findreplacedlg.cpp.
References m_findPage.
OnSearchProject()
void FindReplaceDlg::OnSearchProject (wxCommandEvent & event) protected
Definition at line 558 of file findreplacedlg.cpp.
References Manager::Get(), cbProject::GetActiveBuildTarget(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), Manager::GetProjectManager(), ProjectManager::GetProjects(), and CompileTargetBase::GetTitle().
SaveComboValues()
void FindReplaceDlg::SaveComboValues (wxComboBox * combo, const wxString & configKey) private
Definition at line 724 of file findreplacedlg.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Referenced by ~FindReplaceDlg().
Member Data Documentation
m_findMode
bool FindReplaceDlg::m_findMode private
Definition at line 65 of file findreplacedlg.h.
Referenced by OnMultiChange().
m_findPage
wxWindow* FindReplaceDlg::m_findPage private
Definition at line 66 of file findreplacedlg.h.
Referenced by OnMultiChange(), OnScopeChange(), and ~FindReplaceDlg().
m_findReplaceInFilesActive
bool FindReplaceDlg::m_findReplaceInFilesActive private
Definition at line 64 of file findreplacedlg.h.
Referenced by IsFindInFiles(), OnReplaceChange(), and ~FindReplaceDlg().
The documentation for this class was generated from the following files:
findreplacedlg.h
findreplacedlg.cpp