Code::Blocks: NativeParserHelper::ParserDirTraverser Class Reference
NativeParserHelper::ParserDirTraverser Class Reference
Public Member Functions
ParserDirTraverser (const wxString &excludePath, wxArrayString &files)
virtual wxDirTraverseResult OnFile (const wxString &filename)
virtual wxDirTraverseResult OnDir (const wxString &dirname)
Public Member Functions inherited from wxDirTraverser
virtual wxDirTraverseResult OnOpenError (const wxString &openerrorname)
Private Attributes
const wxString & m_ExcludeDir
wxArrayString & m_Files
Detailed Description
Definition at line 93 of file nativeparser.cpp.
Constructor & Destructor Documentation
ParserDirTraverser()
NativeParserHelper::ParserDirTraverser::ParserDirTraverser (const wxString & excludePath, wxArrayString & files) inline
Definition at line 96 of file nativeparser.cpp.
Member Function Documentation
OnDir()
virtual wxDirTraverseResult NativeParserHelper::ParserDirTraverser::OnDir (const wxString & dirname) inline virtual
Implements wxDirTraverser.
Definition at line 108 of file nativeparser.cpp.
References wxArrayString::Clear(), wxArrayString::GetCount(), m_ExcludeDir, m_Files, wxDIR_CONTINUE, wxDIR_IGNORE, and wxDIR_STOP.
OnFile()
virtual wxDirTraverseResult NativeParserHelper::ParserDirTraverser::OnFile (const wxString & filename) inline virtual
Implements wxDirTraverser.
Definition at line 101 of file nativeparser.cpp.
References wxArrayString::Add(), ParserCommon::FileType(), ParserCommon::ftOther, m_Files, and wxDIR_CONTINUE.
Member Data Documentation
m_ExcludeDir
const wxString& NativeParserHelper::ParserDirTraverser::m_ExcludeDir private
Definition at line 119 of file nativeparser.cpp.
Referenced by OnDir().
m_Files
wxArrayString& NativeParserHelper::ParserDirTraverser::m_Files private
Definition at line 120 of file nativeparser.cpp.
Referenced by OnDir(), and OnFile().
The documentation for this class was generated from the following file:
nativeparser.cpp