Code::Blocks: PluginRegistrant< T > Class Template Reference
PluginRegistrant< T > Class Template Reference
Plugin registration object.
#include <cbplugin.h>
Public Member Functions
PluginRegistrant (const wxString &name)
Static Public Member Functions
static cbPlugin * CreatePlugin ()
static void FreePlugin (cbPlugin *plugin)
static void SDKVersion (int *major, int *minor, int *release)
Detailed Description
template<class T>
class PluginRegistrant< T >
Plugin registration object.
Use this class to register your new plugin with Code::Blocks. All you have to do is instantiate a PluginRegistrant object.
Example code to use in one of your plugin's source files (supposedly called "MyPlugin"):
namespace
{
    PluginRegistrant<MyPlugin> registration("MyPlugin");
}
Constructor & Destructor Documentation
template<class T> PluginRegistrant< T >::PluginRegistrant (const wxString & name) inline
Parameters
name The plugin's name.
References PluginRegistrant< T >::CreatePlugin(), PluginRegistrant< T >::FreePlugin(), Manager::Get(), Manager::GetPluginManager(), PluginManager::RegisterPlugin(), and PluginRegistrant< T >::SDKVersion().
Member Function Documentation
template<class T> static cbPlugin* PluginRegistrant< T >::CreatePlugin () inline static
Referenced by PluginRegistrant< T >::PluginRegistrant().
template<class T> static void PluginRegistrant< T >::FreePlugin (cbPlugin * plugin) inline static
Referenced by PluginRegistrant< T >::PluginRegistrant().
template<class T> static void PluginRegistrant< T >::SDKVersion (int * major, int * minor, int * release) inline static
References PLUGIN_SDK_VERSION_MAJOR, PLUGIN_SDK_VERSION_MINOR, and PLUGIN_SDK_VERSION_RELEASE.
Referenced by PluginRegistrant< T >::PluginRegistrant().
The documentation for this class was generated from the following file:
cbplugin.h