Code::Blocks: wxStandardDialogLayoutAdapter Class Reference
wxStandardDialogLayoutAdapter Class Reference
#include <scrollingdialog.h>
Public Member Functions
wxStandardDialogLayoutAdapter ()
virtual bool CanDoLayoutAdaptation (wxDialogHelper *dialog)
Indicate that adaptation should be done.
virtual bool DoLayoutAdaptation (wxDialogHelper *dialog)
Do layout adaptation.
virtual wxSizer * FindButtonSizer (bool stdButtonSizer, wxDialogHelper *dialog, wxSizer *sizer, int &retBorder, int accumlatedBorder=0)
Find a standard or horizontal box sizer.
virtual bool IsOrdinaryButtonSizer (wxDialogHelper *dialog, wxBoxSizer *sizer)
Check if this sizer contains standard buttons, and so can be repositioned in the dialog.
virtual bool IsStandardButton (wxDialogHelper *dialog, wxButton *button)
Check if this is a standard button.
virtual bool FindLooseButtons (wxDialogHelper *dialog, wxStdDialogButtonSizer *buttonSizer, wxSizer *sizer, int &count)
Find 'loose' main buttons in the existing layout and add them to the standard dialog sizer.
virtual void ReparentControls (wxWindow *parent, wxWindow *reparentTo, wxSizer *buttonSizer=NULL)
Reparent the controls to the scrolled window, except those in buttonSizer.
virtual bool FitWithScrolling (wxDialog *dialog, wxScrolledWindow *scrolledWindow)
A function to fit the dialog around its contents, and then adjust for screen size.
virtual bool FitWithScrolling (wxDialog *dialog, wxWindowList &windows)
virtual int MustScroll (wxDialog *dialog, wxSize &windowSize, wxSize &displaySize)
Find whether scrolling will be necessary for the dialog, returning wxVERTICAL, wxHORIZONTAL or both.
Public Member Functions inherited from wxDialogLayoutAdapter
wxDialogLayoutAdapter ()
Detailed Description
Standard adapter. Does scrolling adaptation for paged and regular dialogs.
Definition at line 52 of file scrollingdialog.h.
Constructor & Destructor Documentation
wxStandardDialogLayoutAdapter()
wxStandardDialogLayoutAdapter::wxStandardDialogLayoutAdapter () inline
Definition at line 56 of file scrollingdialog.h.
References wxDialogLayoutAdapter::CanDoLayoutAdaptation(), wxDialogLayoutAdapter::DoLayoutAdaptation(), and NULL.
Member Function Documentation
CanDoLayoutAdaptation()
bool wxStandardDialogLayoutAdapter::CanDoLayoutAdaptation (wxDialogHelper * dialog) virtual
Indicate that adaptation should be done.
Standard adapter
Implements wxDialogLayoutAdapter.
Definition at line 79 of file scrollingdialog.cpp.
Referenced by wxDialogHelper::SetLayoutAdapter().
DoLayoutAdaptation()
bool wxStandardDialogLayoutAdapter::DoLayoutAdaptation (wxDialogHelper * dialog) virtual
Do layout adaptation.
Implements wxDialogLayoutAdapter.
Definition at line 90 of file scrollingdialog.cpp.
References wxDialogHelper::GetContentWindow(), wxDialogHelper::GetDialog(), wxDialogHelper::GetLayoutAdaptationLevel(), NULL, and wxDialogHelper::SetLayoutAdaptationDone().
FindButtonSizer()
wxSizer * wxStandardDialogLayoutAdapter::FindButtonSizer (bool stdButtonSizer, wxDialogHelper * dialog, wxSizer * sizer, int & retBorder, int accumlatedBorder = 0) virtual
Find a standard or horizontal box sizer.
Find and remove the button sizer, if any.
Definition at line 184 of file scrollingdialog.cpp.
References NULL.
FindLooseButtons()
bool wxStandardDialogLayoutAdapter::FindLooseButtons (wxDialogHelper * dialog, wxStdDialogButtonSizer * buttonSizer, wxSizer * sizer, int & count) virtual
Find 'loose' main buttons in the existing layout and add them to the standard dialog sizer.
Definition at line 255 of file scrollingdialog.cpp.
FitWithScrolling() [1/2]
bool wxStandardDialogLayoutAdapter::FitWithScrolling (wxDialog * dialog, wxScrolledWindow * scrolledWindow) virtual
A function to fit the dialog around its contents, and then adjust for screen size.
If scrolled windows are passed, scrolling is enabled in the required orientation(s).
Definition at line 395 of file scrollingdialog.cpp.
FitWithScrolling() [2/2]
bool wxStandardDialogLayoutAdapter::FitWithScrolling (wxDialog * dialog, wxWindowList & windows) virtual
Definition at line 335 of file scrollingdialog.cpp.
References wxEXTRA_DIALOG_HEIGHT.
IsOrdinaryButtonSizer()
bool wxStandardDialogLayoutAdapter::IsOrdinaryButtonSizer (wxDialogHelper * dialog, wxBoxSizer * sizer) virtual
Check if this sizer contains standard buttons, and so can be repositioned in the dialog.
Definition at line 228 of file scrollingdialog.cpp.
IsStandardButton()
bool wxStandardDialogLayoutAdapter::IsStandardButton (wxDialogHelper * dialog, wxButton * button) virtual
Check if this is a standard button.
Definition at line 246 of file scrollingdialog.cpp.
References wxDialogHelper::IsUserButtonId().
MustScroll()
int wxStandardDialogLayoutAdapter::MustScroll (wxDialog * dialog, wxSize & windowSize, wxSize & displaySize) virtual
Find whether scrolling will be necessary for the dialog, returning wxVERTICAL, wxHORIZONTAL or both.
Definition at line 305 of file scrollingdialog.cpp.
References wxEXTRA_DIALOG_HEIGHT.
ReparentControls()
void wxStandardDialogLayoutAdapter::ReparentControls (wxWindow * parent, wxWindow * reparentTo, wxSizer * buttonSizer = NULL) virtual
Reparent the controls to the scrolled window, except those in buttonSizer.
Reparent the controls to the scrolled window.
Definition at line 281 of file scrollingdialog.cpp.
The documentation for this class was generated from the following files:
scrollingdialog.h
scrollingdialog.cpp