Code::Blocks: WizCompilerPanel Class Reference
WizCompilerPanel Class Reference
#include <wizpage.h>
Public Member Functions
WizCompilerPanel (const wxString &compilerID, const wxString &validCompilerIDs, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap, bool allowCompilerChange=true, bool allowConfigChange=true)
~WizCompilerPanel ()
wxString GetCompilerID () const
bool GetWantDebug () const
wxString GetDebugName () const
wxString GetDebugOutputDir () const
wxString GetDebugObjectOutputDir () const
bool GetWantRelease () const
wxString GetReleaseName () const
wxString GetReleaseOutputDir () const
wxString GetReleaseObjectOutputDir () const
void OnPageChanging (wxWizardEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
CompilerPanel * m_pCompilerPanel
bool m_AllowConfigChange
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 134 of file wizpage.h.
Constructor & Destructor Documentation
WizCompilerPanel()
WizCompilerPanel::WizCompilerPanel (const wxString & compilerID, const wxString & validCompilerIDs, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap, bool allowCompilerChange = true, bool allowConfigChange = true)
Definition at line 492 of file wizpage.cpp.
References _T, CompilerPanel::EnableConfigurationTargets(), Wizard::FillCompilerControl(), Manager::Get(), CompilerPanel::GetCompilerCombo(), Manager::GetConfigManager(), m_AllowConfigChange, m_pCompilerPanel, ConfigManager::Read(), ConfigManager::ReadBool(), CompilerPanel::SetDebugName(), CompilerPanel::SetDebugObjectOutputDir(), CompilerPanel::SetDebugOutputDir(), CompilerPanel::SetReleaseName(), CompilerPanel::SetReleaseObjectOutputDir(), CompilerPanel::SetReleaseOutputDir(), CompilerPanel::SetWantDebug(), and CompilerPanel::SetWantRelease().
~WizCompilerPanel()
WizCompilerPanel::~WizCompilerPanel ()
Definition at line 519 of file wizpage.cpp.
Member Function Documentation
GetCompilerID()
wxString WizCompilerPanel::GetCompilerID () const
Definition at line 524 of file wizpage.cpp.
References CompilerFactory::GetCompilerByName(), CompilerPanel::GetCompilerCombo(), Compiler::GetID(), m_pCompilerPanel, and wxEmptyString.
Referenced by Wiz::GetCompilerID(), and OnPageChanging().
GetDebugName()
wxString WizCompilerPanel::GetDebugName () const
Definition at line 539 of file wizpage.cpp.
References CompilerPanel::GetDebugName(), and m_pCompilerPanel.
Referenced by Wiz::GetDebugName(), and OnPageChanging().
GetDebugObjectOutputDir()
wxString WizCompilerPanel::GetDebugObjectOutputDir () const
Definition at line 551 of file wizpage.cpp.
References AppendPathSepIfNeeded(), CompilerPanel::GetDebugObjectOutputDir(), and m_pCompilerPanel.
Referenced by Wiz::GetDebugObjectOutputDir(), and OnPageChanging().
GetDebugOutputDir()
wxString WizCompilerPanel::GetDebugOutputDir () const
Definition at line 545 of file wizpage.cpp.
References AppendPathSepIfNeeded(), CompilerPanel::GetDebugOutputDir(), and m_pCompilerPanel.
Referenced by Wiz::GetDebugOutputDir(), and OnPageChanging().
GetReleaseName()
wxString WizCompilerPanel::GetReleaseName () const
Definition at line 563 of file wizpage.cpp.
References CompilerPanel::GetReleaseName(), and m_pCompilerPanel.
Referenced by Wiz::GetReleaseName(), and OnPageChanging().
GetReleaseObjectOutputDir()
wxString WizCompilerPanel::GetReleaseObjectOutputDir () const
Definition at line 575 of file wizpage.cpp.
References AppendPathSepIfNeeded(), CompilerPanel::GetReleaseObjectOutputDir(), and m_pCompilerPanel.
Referenced by Wiz::GetReleaseObjectOutputDir(), and OnPageChanging().
GetReleaseOutputDir()
wxString WizCompilerPanel::GetReleaseOutputDir () const
Definition at line 569 of file wizpage.cpp.
References AppendPathSepIfNeeded(), CompilerPanel::GetReleaseOutputDir(), and m_pCompilerPanel.
Referenced by Wiz::GetReleaseOutputDir(), and OnPageChanging().
GetWantDebug()
bool WizCompilerPanel::GetWantDebug () const
Definition at line 533 of file wizpage.cpp.
References CompilerPanel::GetWantDebug(), and m_pCompilerPanel.
Referenced by Wiz::GetWantDebug(), and OnPageChanging().
GetWantRelease()
bool WizCompilerPanel::GetWantRelease () const
Definition at line 557 of file wizpage.cpp.
References CompilerPanel::GetWantRelease(), and m_pCompilerPanel.
Referenced by Wiz::GetWantRelease(), and OnPageChanging().
OnPageChanging()
void WizCompilerPanel::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 581 of file wizpage.cpp.
References _(), _T, cbMessageBox(), Manager::Get(), GetCompilerID(), Manager::GetConfigManager(), GetDebugName(), GetDebugObjectOutputDir(), GetDebugOutputDir(), wxWizardEvent::GetDirection(), GetReleaseName(), GetReleaseObjectOutputDir(), GetReleaseOutputDir(), GetWantDebug(), GetWantRelease(), wxString::IsEmpty(), m_AllowConfigChange, WizPageBase::OnPageChanging(), ConfigManager::Write(), and wxICON_ERROR.
Member Data Documentation
m_AllowConfigChange
bool WizCompilerPanel::m_AllowConfigChange private
Definition at line 154 of file wizpage.h.
Referenced by OnPageChanging(), and WizCompilerPanel().
m_pCompilerPanel
CompilerPanel* WizCompilerPanel::m_pCompilerPanel private
Definition at line 153 of file wizpage.h.
Referenced by GetCompilerID(), GetDebugName(), GetDebugObjectOutputDir(), GetDebugOutputDir(), GetReleaseName(), GetReleaseObjectOutputDir(), GetReleaseOutputDir(), GetWantDebug(), GetWantRelease(), and WizCompilerPanel().
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp