Code::Blocks: GdbCmd_Backtrace Class Reference
GdbCmd_Backtrace Class Reference
Command to run a backtrace.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_Backtrace (DebuggerDriver *driver)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Static Public Member Functions
static bool MatchLine (cbStackFrame &sf, bool &hasLineInfo, const wxString &line)
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to run a backtrace.
Definition at line 1195 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_Backtrace()
GdbCmd_Backtrace::GdbCmd_Backtrace (DebuggerDriver * driver) inline
Parameters
dlg The backtrace dialog.
Definition at line 1199 of file gdb_commands.h.
References _T, and DebuggerCmd::m_Cmd.
Member Function Documentation
MatchLine()
static bool GdbCmd_Backtrace::MatchLine (cbStackFrame & sf, bool & hasLineInfo, const wxString & line) inline static
Definition at line 1276 of file gdb_commands.h.
References cbDebuggerStringToAddress(), wxRegEx::GetMatch(), cbStackFrame::MakeValid(), wxRegEx::Matches(), reBT0(), reBT1(), reBT2(), reBT3(), reBT4(), reBTX(), cbStackFrame::SetAddress(), cbStackFrame::SetFile(), cbStackFrame::SetNumber(), cbStackFrame::SetSymbol(), and wxEmptyString.
Referenced by SUITE().
ParseOutput()
void GdbCmd_Backtrace::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 1204 of file gdb_commands.h.
References _T, cbDebuggerCommonConfig::AutoSwitchFrame, wxString::Format(), Manager::Get(), GetArrayFromString(), DebuggerManager::GetBacktraceDialog(), wxArrayString::GetCount(), Manager::GetDebuggerManager(), cbStackFrame::GetFilename(), cbDebuggerCommonConfig::GetFlag(), cbStackFrame::GetLine(), cbStackFrame::GetNumber(), DebuggerDriver::GetStackFrames(), DebuggerDriver::GetUserSelectedFrame(), DebuggerDriver::Log(), DebuggerCmd::m_pDriver, DebuggerDriver::QueueCommand(), cbBacktraceDlg::Reload(), DebuggerDriver::SetCurrentFrame(), DebuggerDriver::ShowFile(), and wxString::ToLong().
The documentation for this class was generated from the following file:
gdb_commands.h