Code::Blocks: ProjectPathPanel Class Reference
ProjectPathPanel Class Reference
#include <projectpathpanel.h>
Public Member Functions
ProjectPathPanel (wxWindow *parent, wxWindowID id=-1)
virtual ~ProjectPathPanel ()
void SetPath (const wxString &path)
wxString GetPath () const
wxString GetName () const
wxString GetFullFileName () const
wxString GetTitle () const
Static Public Attributes
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_TEXTCTRL3 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_BUTTON1 = wxNewId()
static const long ID_STATICTEXT3 = wxNewId()
static const long ID_TEXTCTRL2 = wxNewId()
static const long ID_STATICTEXT5 = wxNewId()
static const long ID_TEXTCTRL4 = wxNewId()
Private Member Functions
void Update ()
void UpdateFromResulting ()
void OnFullPathChanged (wxCommandEvent &event)
void OntxtFinalDirText (wxCommandEvent &event)
void OntxtPrjTitleText (wxCommandEvent &event)
Private Attributes
bool m_LockUpdates
wxTextCtrl * txtPrjTitle
wxTextCtrl * txtPrjPath
wxBoxSizer * BoxSizer2
wxBoxSizer * BoxSizer1
wxTextCtrl * txtPrjName
wxButton * btnPrjPathBrowse
wxTextCtrl * txtFinalDir
Detailed Description
Definition at line 20 of file projectpathpanel.h.
Constructor & Destructor Documentation
ProjectPathPanel()
ProjectPathPanel::ProjectPathPanel (wxWindow * parent, wxWindowID id = -1)
Definition at line 41 of file projectpathpanel.cpp.
References _(), _T, ID_TEXTCTRL1, OnFullPathChanged(), OntxtFinalDirText(), OntxtPrjTitleText(), wxALIGN_CENTER_VERTICAL, wxALIGN_LEFT, wxALL, wxBOTTOM, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxHORIZONTAL, wxLEFT, wxRIGHT, wxTAB_TRAVERSAL, wxTOP, and wxVERTICAL.
~ProjectPathPanel()
ProjectPathPanel::~ProjectPathPanel () virtual
Definition at line 86 of file projectpathpanel.cpp.
Member Function Documentation
GetFullFileName()
wxString ProjectPathPanel::GetFullFileName () const inline
Definition at line 39 of file projectpathpanel.h.
References txtFinalDir.
GetName()
wxString ProjectPathPanel::GetName () const inline
Definition at line 38 of file projectpathpanel.h.
References txtPrjTitle.
GetPath()
wxString ProjectPathPanel::GetPath () const inline
Definition at line 34 of file projectpathpanel.h.
References txtPrjPath.
GetTitle()
wxString ProjectPathPanel::GetTitle () const inline
Definition at line 40 of file projectpathpanel.h.
References txtPrjTitle.
OnFullPathChanged()
void ProjectPathPanel::OnFullPathChanged (wxCommandEvent & event) private
Definition at line 123 of file projectpathpanel.cpp.
References Update().
Referenced by ProjectPathPanel().
OntxtFinalDirText()
void ProjectPathPanel::OntxtFinalDirText (wxCommandEvent & event) private
Definition at line 128 of file projectpathpanel.cpp.
References _(), txtPrjName, and UpdateFromResulting().
Referenced by ProjectPathPanel().
OntxtPrjTitleText()
void ProjectPathPanel::OntxtPrjTitleText (wxCommandEvent & event) private
Definition at line 134 of file projectpathpanel.cpp.
References FileFilters::CODEBLOCKS_DOT_EXT, wxString::IsEmpty(), wxString::IsSameAs(), wxString::Right(), txtPrjName, txtPrjTitle, and Update().
Referenced by ProjectPathPanel().
SetPath()
void ProjectPathPanel::SetPath (const wxString & path) inline
Definition at line 27 of file projectpathpanel.h.
References txtPrjPath, and Update().
Update()
void ProjectPathPanel::Update () private
Definition at line 102 of file projectpathpanel.cpp.
References _(), m_LockUpdates, txtFinalDir, txtPrjName, txtPrjPath, and wxEmptyString.
Referenced by OnFullPathChanged(), OntxtPrjTitleText(), and SetPath().
UpdateFromResulting()
void ProjectPathPanel::UpdateFromResulting () private
Definition at line 90 of file projectpathpanel.cpp.
References wxFileName::GetName(), wxFileName::GetPath(), m_LockUpdates, txtFinalDir, txtPrjName, and txtPrjPath.
Referenced by OntxtFinalDirText().
Member Data Documentation
BoxSizer1
wxBoxSizer* ProjectPathPanel::BoxSizer1 private
Definition at line 71 of file projectpathpanel.h.
BoxSizer2
wxBoxSizer* ProjectPathPanel::BoxSizer2 private
Definition at line 70 of file projectpathpanel.h.
btnPrjPathBrowse
wxButton* ProjectPathPanel::btnPrjPathBrowse private
Definition at line 73 of file projectpathpanel.h.
ID_BUTTON1
const long ProjectPathPanel::ID_BUTTON1 = wxNewId() static
Definition at line 48 of file projectpathpanel.h.
ID_STATICTEXT1
const long ProjectPathPanel::ID_STATICTEXT1 = wxNewId() static
Definition at line 43 of file projectpathpanel.h.
ID_STATICTEXT2
const long ProjectPathPanel::ID_STATICTEXT2 = wxNewId() static
Definition at line 46 of file projectpathpanel.h.
ID_STATICTEXT3
const long ProjectPathPanel::ID_STATICTEXT3 = wxNewId() static
Definition at line 49 of file projectpathpanel.h.
ID_STATICTEXT4
const long ProjectPathPanel::ID_STATICTEXT4 = wxNewId() static
Definition at line 44 of file projectpathpanel.h.
ID_STATICTEXT5
const long ProjectPathPanel::ID_STATICTEXT5 = wxNewId() static
Definition at line 51 of file projectpathpanel.h.
ID_TEXTCTRL1
const long ProjectPathPanel::ID_TEXTCTRL1 = wxNewId() static
Definition at line 47 of file projectpathpanel.h.
ID_TEXTCTRL2
const long ProjectPathPanel::ID_TEXTCTRL2 = wxNewId() static
Definition at line 50 of file projectpathpanel.h.
ID_TEXTCTRL3
const long ProjectPathPanel::ID_TEXTCTRL3 = wxNewId() static
Definition at line 45 of file projectpathpanel.h.
ID_TEXTCTRL4
const long ProjectPathPanel::ID_TEXTCTRL4 = wxNewId() static
Definition at line 52 of file projectpathpanel.h.
m_LockUpdates
bool ProjectPathPanel::m_LockUpdates private
Definition at line 59 of file projectpathpanel.h.
Referenced by Update(), and UpdateFromResulting().
txtFinalDir
wxTextCtrl* ProjectPathPanel::txtFinalDir private
Definition at line 74 of file projectpathpanel.h.
Referenced by GetFullFileName(), Update(), and UpdateFromResulting().
txtPrjName
wxTextCtrl* ProjectPathPanel::txtPrjName private
Definition at line 72 of file projectpathpanel.h.
Referenced by OntxtFinalDirText(), OntxtPrjTitleText(), Update(), and UpdateFromResulting().
txtPrjPath
wxTextCtrl* ProjectPathPanel::txtPrjPath private
Definition at line 69 of file projectpathpanel.h.
Referenced by GetPath(), SetPath(), Update(), and UpdateFromResulting().
txtPrjTitle
wxTextCtrl* ProjectPathPanel::txtPrjTitle private
Definition at line 68 of file projectpathpanel.h.
Referenced by GetName(), GetTitle(), and OntxtPrjTitleText().
The documentation for this class was generated from the following files:
projectpathpanel.h
projectpathpanel.cpp