Code::Blocks: CodeBlocksEvent Class Reference
CodeBlocksEvent Class Reference
A generic Code::Blocks event.
#include <sdk_events.h>
Public Member Functions
CodeBlocksEvent (wxEventType commandType=wxEVT_NULL, int id=0, cbProject *project=nullptr, EditorBase *editor=nullptr, cbPlugin *plugin=nullptr, EditorBase *old_editor=nullptr)
CodeBlocksEvent (const CodeBlocksEvent &event)
virtual wxEvent * Clone () const
cbProject * GetProject () const
void SetProject (cbProject *project)
EditorBase * GetEditor () const
void SetEditor (EditorBase *editor)
EditorBase * GetOldEditor () const
void SetOldEditor (EditorBase *editor)
cbPlugin * GetPlugin () const
void SetPlugin (cbPlugin *plugin)
int GetX () const
void SetX (int x)
int GetY () const
void SetY (int y)
const wxString & GetBuildTargetName () const
void SetBuildTargetName (const wxString &target)
const wxString & GetOldBuildTargetName () const
void SetOldBuildTargetName (const wxString &target)
Protected Attributes
cbProject * m_pProject
EditorBase * m_pEditor
EditorBase * m_pOldEditor
cbPlugin * m_pPlugin
int m_X
int m_Y
wxString m_TargetName
wxString m_OldTargetName
Detailed Description
A generic Code::Blocks event.
Definition at line 20 of file sdk_events.h.
Constructor & Destructor Documentation
CodeBlocksEvent() [1/2]
CodeBlocksEvent::CodeBlocksEvent (wxEventType commandType = wxEVT_NULL, int id = 0, cbProject * project = nullptr, EditorBase * editor = nullptr, cbPlugin * plugin = nullptr, EditorBase * old_editor = nullptr) inline
Definition at line 23 of file sdk_events.h.
CodeBlocksEvent() [2/2]
CodeBlocksEvent::CodeBlocksEvent (const CodeBlocksEvent & event) inline
Definition at line 31 of file sdk_events.h.
Member Function Documentation
Clone()
virtual wxEvent* CodeBlocksEvent::Clone () const inline virtual
Definition at line 39 of file sdk_events.h.
GetBuildTargetName()
const wxString& CodeBlocksEvent::GetBuildTargetName () const inline
Definition at line 59 of file sdk_events.h.
Referenced by DebuggerGDB::OnBuildTargetSelected().
GetEditor()
EditorBase* CodeBlocksEvent::GetEditor () const inline
Definition at line 44 of file sdk_events.h.
Referenced by CCManager::OnDeactivateEd(), CodeCompletion::OnEditorActivated(), CCManager::OnEditorClose(), CodeCompletion::OnEditorClosed(), CCManager::OnEditorOpen(), CodeCompletion::OnEditorOpen(), CodeCompletion::OnEditorSave(), and MainFrame::OnEditorUpdateUI().
GetOldBuildTargetName()
const wxString& CodeBlocksEvent::GetOldBuildTargetName () const inline
Definition at line 64 of file sdk_events.h.
GetOldEditor()
EditorBase* CodeBlocksEvent::GetOldEditor () const inline
Definition at line 47 of file sdk_events.h.
GetPlugin()
cbPlugin* CodeBlocksEvent::GetPlugin () const inline
Definition at line 50 of file sdk_events.h.
Referenced by MainFrame::OnPluginInstalled(), and MainFrame::OnPluginUninstalled().
GetProject()
cbProject* CodeBlocksEvent::GetProject () const inline
Definition at line 41 of file sdk_events.h.
Referenced by DebuggerGDB::OnBuildTargetSelected(), CompilerGCC::OnProjectActivated(), cbDebuggerPlugin::OnProjectActivated(), cbDebuggerPlugin::OnProjectClosed(), CodeCompletion::OnProjectFileAdded(), CodeCompletion::OnProjectFileRemoved(), CodeCompletion::OnProjectSaved(), and CompilerGCC::OnProjectUnloaded().
GetX()
int CodeBlocksEvent::GetX () const inline
Definition at line 53 of file sdk_events.h.
Referenced by CCManager::OnEditorTooltip().
GetY()
int CodeBlocksEvent::GetY () const inline
Definition at line 56 of file sdk_events.h.
SetBuildTargetName()
void CodeBlocksEvent::SetBuildTargetName (const wxString & target) inline
Definition at line 60 of file sdk_events.h.
Referenced by CompilerCommandGenerator::Init(), and CompilerGCC::NotifyCleanProject().
SetEditor()
void CodeBlocksEvent::SetEditor (EditorBase * editor) inline
Definition at line 45 of file sdk_events.h.
Referenced by CCManager::OnMenuSelect().
SetOldBuildTargetName()
void CodeBlocksEvent::SetOldBuildTargetName (const wxString & target) inline
Definition at line 65 of file sdk_events.h.
SetOldEditor()
void CodeBlocksEvent::SetOldEditor (EditorBase * editor) inline
Definition at line 48 of file sdk_events.h.
SetPlugin()
void CodeBlocksEvent::SetPlugin (cbPlugin * plugin) inline
Definition at line 51 of file sdk_events.h.
Referenced by PluginManager::InstallPlugin().
SetProject()
void CodeBlocksEvent::SetProject (cbProject * project) inline
Definition at line 42 of file sdk_events.h.
Referenced by ProjectOptionsDlg::OnAddBuildTargetClick(), ProjectOptionsDlg::OnBuildOrderClick(), ProjectOptionsDlg::OnBuildTargetChanged(), ProjectOptionsDlg::OnCopyBuildTargetClick(), ProjectOptionsDlg::OnEditBuildTargetClick(), ProjectOptionsDlg::OnRemoveBuildTargetClick(), and ProjectManager::RemoveFileFromProject().
SetX()
void CodeBlocksEvent::SetX (int x) inline
Definition at line 54 of file sdk_events.h.
Referenced by CCManager::OnMenuSelect().
SetY()
void CodeBlocksEvent::SetY (int y) inline
Definition at line 57 of file sdk_events.h.
Referenced by CCManager::OnMenuSelect().
Member Data Documentation
m_OldTargetName
wxString CodeBlocksEvent::m_OldTargetName protected
Definition at line 76 of file sdk_events.h.
m_pEditor
EditorBase* CodeBlocksEvent::m_pEditor protected
Definition at line 68 of file sdk_events.h.
m_pOldEditor
EditorBase* CodeBlocksEvent::m_pOldEditor protected
Definition at line 69 of file sdk_events.h.
m_pPlugin
cbPlugin* CodeBlocksEvent::m_pPlugin protected
Definition at line 70 of file sdk_events.h.
m_pProject
cbProject* CodeBlocksEvent::m_pProject protected
Definition at line 67 of file sdk_events.h.
m_TargetName
wxString CodeBlocksEvent::m_TargetName protected
Definition at line 75 of file sdk_events.h.
m_X
int CodeBlocksEvent::m_X protected
Definition at line 72 of file sdk_events.h.
m_Y
int CodeBlocksEvent::m_Y protected
Definition at line 73 of file sdk_events.h.
The documentation for this class was generated from the following file:
sdk_events.h