Code::Blocks: DebuggerGDB Class Reference
DebuggerGDB Class Reference
#include <debuggergdb.h>
Public Member Functions
DebuggerGDB ()
~DebuggerGDB ()
cbConfigurationPanel * GetProjectConfigurationPanel (wxWindow *parent, cbProject *project)
void OnAttachReal ()
void OnReleaseReal (bool appShutDown)
bool SupportsFeature (cbDebuggerFeature::Flags flag)
cbDebuggerConfiguration * LoadConfig (const ConfigManagerWrapper &config)
DebuggerConfiguration & GetActiveConfigEx ()
void RunCommand (int cmd)
cb::shared_ptr< cbBreakpoint > AddBreakpoint (const wxString &filename, int line)
Request to add a breakpoint.
cb::shared_ptr< cbBreakpoint > AddDataBreakpoint (const wxString &dataExpression)
Request to add a breakpoint based on a data expression.
int GetBreakpointsCount () const
cb::shared_ptr< cbBreakpoint > GetBreakpoint (int index)
cb::shared_ptr< const cbBreakpoint > GetBreakpoint (int index) const
void UpdateBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint)
void DeleteBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint)
void DeleteAllBreakpoints ()
void ShiftBreakpoint (int index, int lines_to_shift)
void EnableBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint, bool enable)
int GetStackFrameCount () const
cb::shared_ptr< const cbStackFrame > GetStackFrame (int index) const
void SwitchToFrame (int number)
int GetActiveStackFrame () const
int GetThreadsCount () const
cb::shared_ptr< const cbThread > GetThread (int index) const
bool SwitchToThread (int thread_number)
bool Debug (bool breakOnEntry)
Start a new debugging process.
void Continue ()
Continue running the debugged program.
void Next ()
Execute the next instruction and return control to the debugger.
void NextInstruction ()
Execute the next instruction and return control to the debugger.
void StepIntoInstruction ()
Execute the next instruction and return control to the debugger, if the instruction is a function call step into it.
void Step ()
Execute the next instruction, stepping into function calls if needed, and return control to the debugger.
void StepOut ()
Execute the next instruction, stepping out of function calls if needed, and return control to the debugger.
bool RunToCursor (const wxString &filename, int line, const wxString &line_text)
Run the debugged program until it reaches the cursor at the current editor.
void SetNextStatement (const wxString &filename, int line)
Sets the position of the Program counter to the specified filename:line.
void Break ()
Break the debugging process (stop the debuggee for debugging).
void Stop ()
Stop the debugging process (exit debugging).
bool Validate (const wxString &line, const char cb)
bool IsRunning () const
Is the plugin currently debugging?
bool IsStopped () const
Is the plugin stopped on breakpoint?
bool IsBusy () const
Is the plugin processing something?
bool IsTemporaryBreak () const
int GetExitCode () const
Get the exit code of the last debug process.
cb::shared_ptr< cbWatch > AddWatch (const wxString &symbol)
void DeleteWatch (cb::shared_ptr< cbWatch > watch)
bool HasWatch (cb::shared_ptr< cbWatch > watch)
void ShowWatchProperties (cb::shared_ptr< cbWatch > watch)
bool SetWatchValue (cb::shared_ptr< cbWatch > watch, const wxString &value)
void ExpandWatch (cb::shared_ptr< cbWatch > watch)
void CollapseWatch (cb::shared_ptr< cbWatch > watch)
void UpdateWatch (cb::shared_ptr< cbWatch > watch)
void AddWatchNoUpdate (const cb::shared_ptr< GDBWatch > &watch)
void OnWatchesContextMenu (wxMenu &menu, const cbWatch &watch, wxObject *property, int &disabledMenus)
void GetCurrentPosition (wxString &filename, int &line)
void RequestUpdate (DebugWindows window)
void AttachToProcess (const wxString &pid)
void DetachFromProcess ()
bool IsAttachedToProcess () const
void SendCommand (const wxString &cmd, bool debugLog)
void DoSendCommand (const wxString &cmd)
DebuggerState & GetState ()
void OnConfigurationChange (bool isActive)
Called when the user clicks OK in Settings -> Debugger...
wxArrayString & GetSearchDirs (cbProject *prj)
RemoteDebuggingMap & GetRemoteDebuggingMap (cbProject *project=0)
void OnProjectLoadingHook (cbProject *project, TiXmlElement *elem, bool loading)
void OnValueTooltip (const wxString &token, const wxRect &evalRect)
bool ShowValueTooltip (int style)
void DebuggeeContinued ()
Public Member Functions inherited from cbDebuggerPlugin
cbDebuggerPlugin (const wxString &guiName, const wxString &settingsName)
virtual void OnAttach ()
Any descendent plugin should override this virtual method and perform any necessary initialization.
virtual void OnRelease (bool appShutDown)
virtual void BuildMenu (wxMenuBar *menuBar)
virtual void BuildModuleMenu (const ModuleType type, wxMenu *menu, const FileTreeData *data=nullptr)
virtual bool BuildToolBar (wxToolBar *toolBar)
virtual void EditorLinesAddedOrRemoved (cbEditor *editor, int startline, int lines)
Notify the debugger that lines were added or removed in an editor.
virtual bool ToolMenuEnabled () const
cbDebuggerConfiguration & GetActiveConfig ()
void SetActiveConfig (int index)
int GetIndexOfActiveConfig () const
virtual wxString GetEditorWordAtCaret (const wxPoint *mousePosition=NULL)
void ClearActiveMarkFromAllEditors ()
SyncEditorResult SyncEditor (const wxString &filename, int line, bool setMarker=true)
void BringCBToFront ()
bool DragInProgress () const
void ShowLog (bool clear)
void Log (const wxString &msg, Logger::level level=Logger::info)
void DebugLog (const wxString &msg, Logger::level level=Logger::info)
bool HasDebugLog () const
void ClearLog ()
void SetupLog (int normalIndex)
wxString GetGUIName () const
wxString GetSettingsName () const
Public Member Functions inherited from cbPlugin
cbPlugin ()
In default cbPlugin's constructor the associated PluginInfo structure is filled with default values.
virtual ~cbPlugin ()
cbPlugin destructor.
virtual PluginType GetType () const
The plugin must return its type on request.
virtual int GetConfigurationPriority () const
Return the plugin's configuration priority.
virtual int GetConfigurationGroup () const
Return the configuration group for this plugin.
virtual cbConfigurationPanel * GetConfigurationPanel (cb_optional wxWindow *parent)
Return plugin's configuration panel.
virtual cbConfigurationPanel * GetProjectConfigurationPanel (cb_optional wxWindow *parent, cb_optional cbProject *project)
Return plugin's configuration panel for projects.
virtual void BuildMenu (cb_optional wxMenuBar *menuBar)
This method is called by Code::Blocks and is used by the plugin to add any menu items it needs on Code::Blocks's menu bar.
virtual void BuildModuleMenu (cb_optional const ModuleType type, cb_optional wxMenu *menu, cb_optional const FileTreeData *data=nullptr)
This method is called by Code::Blocks core modules (EditorManager, ProjectManager etc) and is used by the plugin to add any menu items it needs in the module's popup menu.
virtual bool BuildToolBar (cb_optional wxToolBar *toolBar)
This method is called by Code::Blocks and is used by the plugin to add any toolbar items it needs on Code::Blocks's toolbar.
virtual int GetToolBarPriority ()
This method return the priority of the plugin's toolbar, the less value indicates a more preceding position when C::B starts with no configuration file.
virtual void CreateStatusField (cbStatusBar *statusBar)
This method is called by Code::Blocks and is used by the plugin to add a field on Code::Blocks's statusbar.
bool IsAttached () const
See whether this plugin is attached or not.
virtual bool CanDetach () const
See whether this plugin can be detached (unloaded) or not.
Static Public Member Functions
static void ConvertToGDBFriendly (wxString &str)
static void ConvertToGDBFile (wxString &str)
static void ConvertToGDBDirectory (wxString &str, wxString base=_T(""), bool relative=true)
static void StripQuotes (wxString &str)
Protected Member Functions
cbProject * GetProject ()
void ResetProject ()
void ConvertDirectory (wxString &str, wxString base, bool relative)
void CleanupWhenProjectClosed (cbProject *project)
bool CompilerFinished (bool compilerFailed, StartType startType)
Called when the compilation has finished.
void AddSourceDir (const wxString &dir)
Protected Member Functions inherited from cbDebuggerPlugin
void SwitchToDebuggingLayout ()
void SwitchToPreviousLayout ()
bool GetDebuggee (wxString &pathToDebuggee, wxString &workingDirectory, ProjectBuildTarget *target)
bool EnsureBuildUpToDate (StartType startType)
bool WaitingCompilerToFinish () const
int RunNixConsole (wxString &consoleTty)
void MarkAsStopped ()
Protected Member Functions inherited from cbPlugin
virtual void OnRelease (cb_optional bool appShutDown)
Any descendent plugin should override this virtual method and perform any necessary de-initialization.
virtual void NotImplemented (const wxString &log) const
This method logs a "Not implemented" message and is provided for convenience only.
Private Types
typedef std::map< cbProject *, wxArrayString > SearchDirsMap
typedef std::map< cbProject *, RemoteDebuggingMap > ProjectRemoteDebuggingMap
Private Member Functions
void ParseOutput (const wxString &output)
void DoWatches ()
void MarkAllWatchesAsUnchanged ()
int LaunchProcess (const wxString &cmd, const wxString &cwd)
int DoDebug (bool breakOnEntry)
void DoBreak (bool temporary)
void OnAddSymbolFile (wxCommandEvent &event)
void DeleteAllProjectBreakpoints (cbProject *project)
void OnBuildTargetSelected (CodeBlocksEvent &event)
void OnGDBOutput (wxCommandEvent &event)
void OnGDBError (wxCommandEvent &event)
void OnGDBTerminated (wxCommandEvent &event)
void OnIdle (wxIdleEvent &event)
void OnTimer (wxTimerEvent &event)
void OnShowFile (wxCommandEvent &event)
void OnCursorChanged (wxCommandEvent &event)
void SetupToolsMenu (wxMenu &menu)
void KillConsole ()
void CheckIfConsoleIsClosed ()
void OnInfoFrame (wxCommandEvent &event)
void OnInfoDLL (wxCommandEvent &event)
void OnInfoFiles (wxCommandEvent &event)
void OnInfoFPU (wxCommandEvent &event)
void OnInfoSignals (wxCommandEvent &event)
void OnMenuWatchDereference (wxCommandEvent &event)
void OnUpdateTools (wxUpdateUIEvent &event)
void OnPrintElements (wxCommandEvent &event)
void OnUpdateCatchThrow (wxUpdateUIEvent &event)
void OnCatchThrow (wxCommandEvent &event)
Private Attributes
DebuggerState m_State
PipedProcess * m_pProcess
bool m_LastExitCode
int m_Pid
int m_PidToAttach
wxRect m_EvalRect
wxTimer m_TimerPollDebugger
bool m_NoDebugInfo
bool m_StoppedOnSignal
cbProject * m_pProject
wxString m_ActiveBuildTarget
SearchDirsMap m_SearchDirs
ProjectRemoteDebuggingMap m_RemoteDebugging
int m_HookId
bool m_bIsConsole
bool m_stopDebuggerConsoleClosed
int m_nConsolePid
bool m_Canceled
bool m_TemporaryBreak
WatchesContainer m_watches
cb::shared_ptr< GDBWatch > m_localsWatch
cb::shared_ptr< GDBWatch > m_funcArgsWatch
wxString m_watchToDereferenceSymbol
wxObject * m_watchToDereferenceProperty
int m_printElements
Friends
struct TestIfBelongToProject
Additional Inherited Members
Public Types inherited from cbDebuggerPlugin
enum DebugWindows {
Backtrace, CPURegisters, Disassembly, ExamineMemory,
Threads, Watches
}
enum SyncEditorResult { SyncOk = 0, SyncFileNotFound, SyncFileUnknown }
Protected Types inherited from cbDebuggerPlugin
enum StartType { StartTypeUnknown = 0, StartTypeRun, StartTypeStepInto }
Protected Attributes inherited from cbPlugin
PluginType m_Type
Holds the plugin's type.
bool m_IsAttached
Holds the "attached" state.
Detailed Description
Definition at line 32 of file debuggergdb.h.
Member Typedef Documentation
ProjectRemoteDebuggingMap
typedef std::map<cbProject*, RemoteDebuggingMap> DebuggerGDB::ProjectRemoteDebuggingMap private
Definition at line 196 of file debuggergdb.h.
SearchDirsMap
typedef std::map<cbProject*, wxArrayString> DebuggerGDB::SearchDirsMap private
Definition at line 193 of file debuggergdb.h.
Constructor & Destructor Documentation
DebuggerGDB()
DebuggerGDB::DebuggerGDB ()
Definition at line 164 of file debuggergdb.cpp.
References _T, LibLoader::LoadLibrary(), Manager::LoadResource(), and NotifyMissingFile().
~DebuggerGDB()
DebuggerGDB::~DebuggerGDB ()
Definition at line 199 of file debuggergdb.cpp.
Member Function Documentation
AddBreakpoint()
cb::shared_ptr< cbBreakpoint > DebuggerGDB::AddBreakpoint (const wxString & filename, int line) virtual
Request to add a breakpoint.
Parameters
file The file to add the breakpoint based on a file/line pair.
line The line number to put the breakpoint in file.
Returns
True if succeeded, false if not.
Implements cbDebuggerPlugin.
Definition at line 1329 of file debuggergdb.cpp.
References DebuggerState::AddBreakpoint(), Continue(), DoBreak(), IsStopped(), and m_State.
AddDataBreakpoint()
cb::shared_ptr< cbBreakpoint > DebuggerGDB::AddDataBreakpoint (const wxString & dataExpression) virtual
Request to add a breakpoint based on a data expression.
Parameters
dataExpression The data expression to add the breakpoint.
Returns
True if succeeded, false if not.
Implements cbDebuggerPlugin.
Definition at line 1343 of file debuggergdb.cpp.
References DebuggerState::AddBreakpoint(), Manager::Get(), DataBreakpointDlg::GetDataExpression(), DataBreakpointDlg::GetSelection(), m_State, PlaceWindow(), wxDialog::ShowModal(), and wxID_OK.
AddSourceDir()
void DebuggerGDB::AddSourceDir (const wxString & dir) protected
Definition at line 944 of file debuggergdb.cpp.
References _(), _T, DebuggerDriver::AddDirectory(), ConvertToGDBDirectory(), Manager::Get(), DebuggerState::GetDriver(), Manager::GetMacrosManager(), DebuggerState::HasDriver(), wxString::IsEmpty(), cbDebuggerPlugin::Log(), m_State, and MacrosManager::ReplaceEnvVars().
Referenced by DoDebug(), and ResetProject().
AddWatch()
cb::shared_ptr< cbWatch > DebuggerGDB::AddWatch (const wxString & symbol) virtual
Implements cbDebuggerPlugin.
Definition at line 2062 of file debuggergdb.cpp.
References CleanStringValue(), DebuggerState::GetDriver(), m_pProcess, m_State, m_watches, and DebuggerDriver::UpdateWatch().
Referenced by GetExitCode().
AddWatchNoUpdate()
void DebuggerGDB::AddWatchNoUpdate (const cb::shared_ptr< GDBWatch > & watch)
Definition at line 2073 of file debuggergdb.cpp.
References m_watches.
Referenced by GetExitCode(), and GdbCmd_TooltipEvaluation::ParseOutput().
AttachToProcess()
void DebuggerGDB::AttachToProcess (const wxString & pid) virtual
Implements cbDebuggerPlugin.
Definition at line 2206 of file debuggergdb.cpp.
References Debug(), wxString::IsEmpty(), m_PidToAttach, and wxString::ToLong().
Referenced by GetExitCode().
Break()
void DebuggerGDB::Break () virtual
Break the debugging process (stop the debuggee for debugging).
Implements cbDebuggerPlugin.
Definition at line 1568 of file debuggergdb.cpp.
References DoBreak().
Referenced by Stop().
CheckIfConsoleIsClosed()
void DebuggerGDB::CheckIfConsoleIsClosed () private
Definition at line 1906 of file debuggergdb.cpp.
References _(), m_nConsolePid, m_stopDebuggerConsoleClosed, AnnoyingDialog::rtNO, AnnoyingDialog::ShowModal(), Stop(), wxART_QUESTION, wxKill(), and wxSIGNONE.
Referenced by OnTimer(), and ResetProject().
CleanupWhenProjectClosed()
void DebuggerGDB::CleanupWhenProjectClosed (cbProject * project) protected virtual
Implements cbDebuggerPlugin.
Definition at line 1950 of file debuggergdb.cpp.
References DeleteAllProjectBreakpoints(), Manager::Get(), DebuggerManager::GetBreakpointDialog(), Manager::GetDebuggerManager(), GetRemoteDebuggingMap(), GetSearchDirs(), and cbBreakpointsDlg::Reload().
Referenced by ResetProject().
CollapseWatch()
void DebuggerGDB::CollapseWatch (cb::shared_ptr< cbWatch > watch) virtual
Implements cbDebuggerPlugin.
Definition at line 2141 of file debuggergdb.cpp.
Referenced by GetExitCode().
CompilerFinished()
bool DebuggerGDB::CompilerFinished (bool compilerFailed, StartType startType) protected virtual
Called when the compilation has finished.
The compilation is started when EnsureBuildUpToDate is called.
Parameters
compilerFailed the compilation failed for some reason.
startType it is the same value given to the Debug method, when the debugger session was started.
Returns
True if debug session is start, false if there are any errors or the users canceled the session.
Reimplemented from cbDebuggerPlugin.
Definition at line 2227 of file debuggergdb.cpp.
References DoDebug(), cbDebuggerPlugin::StartTypeStepInto, and cbDebuggerPlugin::StartTypeUnknown.
Referenced by ResetProject().
Continue()
void DebuggerGDB::Continue () virtual
Continue running the debugged program.
Implements cbDebuggerPlugin.
Definition at line 1489 of file debuggergdb.cpp.
References CMD_CONTINUE, and RunCommand().
Referenced by AddBreakpoint(), DeleteAllBreakpoints(), DeleteBreakpoint(), EnableBreakpoint(), RunToCursor(), and UpdateBreakpoint().
ConvertDirectory()
void DebuggerGDB::ConvertDirectory (wxString & str, wxString base, bool relative) protected virtual
Implements cbDebuggerPlugin.
Definition at line 986 of file debuggergdb.cpp.
References ConvertToGDBDirectory().
Referenced by ResetProject().
ConvertToGDBDirectory()
void DebuggerGDB::ConvertToGDBDirectory (wxString & str, wxString base = _T(""), bool relative = true) static
Definition at line 993 of file debuggergdb.cpp.
References _T, wxString::AfterFirst(), wxString::BeforeFirst(), wxString::Clear(), wxString::Contains(), ConvertToGDBFriendly(), wxString::Find(), wxString::GetChar(), wxFileName::GetShortPath(), wxString::IsEmpty(), wxString::Length(), wxString::Mid(), StripQuotes(), and wxNOT_FOUND.
Referenced by AddSourceDir(), ConvertDirectory(), ConvertToGDBFile(), DoDebug(), GetState(), and OnAddSymbolFile().
ConvertToGDBFile()
void DebuggerGDB::ConvertToGDBFile (wxString & str) static
Definition at line 978 of file debuggergdb.cpp.
References ConvertToGDBDirectory(), wxFileName::GetFullName(), and wxFileName::GetPath().
Referenced by GetState().
ConvertToGDBFriendly()
void DebuggerGDB::ConvertToGDBFriendly (wxString & str) static
Definition at line 963 of file debuggergdb.cpp.
References _T, wxString::Find(), wxString::GetChar(), wxString::IsEmpty(), wxString::Replace(), and UnixFilename().
Referenced by ConvertToGDBDirectory(), and GetState().
Debug()
bool DebuggerGDB::Debug (bool breakOnEntry) virtual
Start a new debugging process.
Implements cbDebuggerPlugin.
Definition at line 625 of file debuggergdb.cpp.
References DoDebug(), cbDebuggerPlugin::EnsureBuildUpToDate(), Manager::Get(), cbProject::GetActiveBuildTarget(), ProjectManager::GetActiveProject(), Manager::GetProjectManager(), DebuggerState::HasDriver(), wxString::IsEmpty(), m_ActiveBuildTarget, m_Canceled, m_NoDebugInfo, m_PidToAttach, m_pProcess, m_pProject, m_State, cbDebuggerPlugin::StartTypeRun, cbDebuggerPlugin::StartTypeStepInto, and cbDebuggerPlugin::WaitingCompilerToFinish().
Referenced by AttachToProcess(), and RunToCursor().
DebuggeeContinued()
void DebuggerGDB::DebuggeeContinued ()
Definition at line 1990 of file debuggergdb.cpp.
References m_TemporaryBreak.
Referenced by GetState(), and DebuggerDriver::NotifyDebuggeeContinued().
DeleteAllBreakpoints()
void DebuggerGDB::DeleteAllBreakpoints () virtual
Implements cbDebuggerPlugin.
Definition at line 1449 of file debuggergdb.cpp.
References Continue(), DoBreak(), IsStopped(), m_State, and DebuggerState::RemoveAllBreakpoints().
DeleteAllProjectBreakpoints()
void DebuggerGDB::DeleteAllProjectBreakpoints (cbProject * project) private
Definition at line 1484 of file debuggergdb.cpp.
References m_State, and DebuggerState::RemoveAllProjectBreakpoints().
Referenced by CleanupWhenProjectClosed(), and ResetProject().
DeleteBreakpoint()
void DebuggerGDB::DeleteBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint) virtual
Implements cbDebuggerPlugin.
Definition at line 1437 of file debuggergdb.cpp.
References Continue(), DoBreak(), IsStopped(), m_State, and DebuggerState::RemoveBreakpoint().
DeleteWatch()
void DebuggerGDB::DeleteWatch (cb::shared_ptr< cbWatch > watch) virtual
Implements cbDebuggerPlugin.
Definition at line 2078 of file debuggergdb.cpp.
References m_watches.
Referenced by GetExitCode().
DetachFromProcess()
void DebuggerGDB::DetachFromProcess () virtual
Implements cbDebuggerPlugin.
Definition at line 2215 of file debuggergdb.cpp.
References DebuggerDriver::Detach(), DebuggerState::GetDriver(), m_PidToAttach, m_State, and DebuggerDriver::Stop().
Referenced by GetExitCode().
DoBreak()
void DebuggerGDB::DoBreak (bool temporary) private
Definition at line 1573 of file debuggergdb.cpp.
References _(), cbEVT_DEBUGGER_PAUSED, cbMessageBox(), cbDebuggerPlugin::DebugLog(), Logger::error, wxProcess::Exists(), F(), wxString::Format(), Manager::Get(), DebuggerDriver::GetChildPID(), DebuggerState::GetDriver(), Manager::GetPluginManager(), IsStopped(), cbDebuggerPlugin::Log(), m_Pid, m_pProcess, m_State, m_TemporaryBreak, PluginManager::NotifyPlugins(), NULL, DebuggerDriver::UseDebugBreakProcess(), Logger::warning, wxICON_WARNING, wxKill(), wxOK, wxSIGINT, and wxT.
Referenced by AddBreakpoint(), Break(), DeleteAllBreakpoints(), DeleteBreakpoint(), EnableBreakpoint(), ResetProject(), and UpdateBreakpoint().
DoDebug()
int DebuggerGDB::DoDebug (bool breakOnEntry) private
Definition at line 665 of file debuggergdb.cpp.
References _(), _T, DebuggerConfiguration::AddOtherProjectDirs, AddSourceDir(), DebuggerState::ApplyBreakpoints(), DebuggerDriver::Attach(), cbProject::BuildTargetValid(), cbEVT_DEBUGGER_STARTED, cbMessageBox(), DebuggerDriver::ClearDirectories(), ConvertToGDBDirectory(), cbDebuggerPlugin::DebugLog(), wxString::empty(), Logger::error, wxString::Format(), Manager::Get(), GetActiveConfigEx(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), DebuggerDriver::GetCommandLine(), cbProject::GetCommonTopLevelPath(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), cbDebuggerPlugin::GetDebuggee(), DebuggerConfiguration::GetDebuggerExecutable(), DebuggerDriver::GetDebuggersWorkingDirectory(), CompilerFactory::GetDefaultCompiler(), DebuggerState::GetDriver(), CompileTargetBase::GetExecutionParameters(), CompilerCommandGenerator::GetLinkerSearchDirs(), Manager::GetPluginManager(), Manager::GetProjectManager(), ProjectManager::GetProjects(), GetRemoteDebuggingMap(), GetSearchDirs(), GetStringFromArray(), CompileTargetBase::GetTargetType(), CompileTargetBase::GetTitle(), ProjectBuildTarget::GetUseConsoleRunner(), HandlerRoutine(), DebuggerState::HasDriver(), wxString::IsEmpty(), LaunchProcess(), wxString::Length(), cbDebuggerPlugin::Log(), m_ActiveBuildTarget, m_bIsConsole, m_Canceled, m_nConsolePid, m_PidToAttach, m_pProcess, m_pProject, m_printElements, m_State, m_stopDebuggerConsoleClosed, m_TimerPollDebugger, RemoteDebugging::MergeWith(), wxString::Mid(), PluginManager::NotifyPlugins(), DebuggerDriver::Prepare(), wxString::Printf(), DebuggerDriver::QueueCommand(), cbDebuggerPlugin::RunNixConsole(), cbProject::SelectTarget(), DebuggerDriver::SetArguments(), DebuggerDriver::SetWorkingDirectory(), RemoteDebugging::skipLDpath, wxTimer::Start(), DebuggerDriver::Start(), DebuggerState::StartDriver(), cbDebuggerPlugin::SwitchToDebuggingLayout(), wxString::Trim(), ttCommandsOnly, ttConsoleOnly, DebuggerDriver::UseDebugBreakProcess(), wxString::wx_str(), wxEmptyString, wxGetEnv(), wxICON_ERROR, wxICON_INFORMATION, wxMilliSleep(), wxSetEnv(), wxT, and Manager::Yield().
Referenced by CompilerFinished(), Debug(), and ResetProject().
DoSendCommand()
void DebuggerGDB::DoSendCommand (const wxString & cmd)
Definition at line 1093 of file debuggergdb.cpp.
References cbDebuggerPlugin::DebugLog(), cbDebuggerPlugin::HasDebugLog(), IsStopped(), m_pProcess, PipedProcess::SendString(), and wxT.
Referenced by GetExitCode(), DebuggerDriver::RunQueue(), and SendCommand().
DoWatches()
void DebuggerGDB::DoWatches () private
Definition at line 493 of file debuggergdb.cpp.
References cbWatchesDlg::AddSpecialWatch(), Manager::Get(), GetActiveConfigEx(), Manager::GetDebuggerManager(), DebuggerState::GetDriver(), DebuggerConfiguration::GetFlag(), DebuggerManager::GetWatchesDialog(), m_funcArgsWatch, m_localsWatch, m_pProcess, m_State, m_watches, DebuggerDriver::UpdateWatches(), DebuggerConfiguration::WatchFuncArgs, DebuggerConfiguration::WatchLocals, and wxT.
Referenced by OnCursorChanged(), RequestUpdate(), ResetProject(), SetWatchValue(), and ShowWatchProperties().
EnableBreakpoint()
void DebuggerGDB::EnableBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint, bool enable) virtual
Implements cbDebuggerPlugin.
Definition at line 1469 of file debuggergdb.cpp.
References Continue(), cbDebuggerPlugin::DebugLog(), DoBreak(), DebuggerBreakpoint::enabled, wxString::Format(), IsStopped(), m_State, DebuggerState::ResetBreakpoint(), and wxT.
ExpandWatch()
void DebuggerGDB::ExpandWatch (cb::shared_ptr< cbWatch > watch) virtual
Implements cbDebuggerPlugin.
Definition at line 2137 of file debuggergdb.cpp.
Referenced by GetExitCode().
GetActiveConfigEx()
DebuggerConfiguration & DebuggerGDB::GetActiveConfigEx ()
Definition at line 285 of file debuggergdb.cpp.
References cbDebuggerPlugin::GetActiveConfig().
Referenced by DoDebug(), DoWatches(), GDB_driver::GetCommandLine(), GDB_driver::InitializeScripting(), OnCatchThrow(), OnConfigurationChange(), OnUpdateCatchThrow(), GDB_driver::Prepare(), RunToCursor(), SetupToolsMenu(), ShowValueTooltip(), CDB_driver::Start(), GDB_driver::Start(), DebuggerState::StartDriver(), and SupportsFeature().
GetActiveStackFrame()
int DebuggerGDB::GetActiveStackFrame () const virtual
Implements cbDebuggerPlugin.
Definition at line 1292 of file debuggergdb.cpp.
References DebuggerDriver::GetCurrentFrame(), DebuggerState::GetDriver(), DebuggerState::HasDriver(), and m_State.
GetBreakpoint() [1/2]
cb::shared_ptr< cbBreakpoint > DebuggerGDB::GetBreakpoint (int index) virtual
Implements cbDebuggerPlugin.
Definition at line 1363 of file debuggergdb.cpp.
References cbAssert, DebuggerState::GetBreakpoints(), and m_State.
GetBreakpoint() [2/2]
cb::shared_ptr< const cbBreakpoint > DebuggerGDB::GetBreakpoint (int index) const virtual
Implements cbDebuggerPlugin.
Definition at line 1371 of file debuggergdb.cpp.
References cbAssert, DebuggerState::GetBreakpoints(), and m_State.
GetBreakpointsCount()
int DebuggerGDB::GetBreakpointsCount () const virtual
Implements cbDebuggerPlugin.
Definition at line 1358 of file debuggergdb.cpp.
References DebuggerState::GetBreakpoints(), and m_State.
GetCurrentPosition()
void DebuggerGDB::GetCurrentPosition (wxString & filename, int & line) virtual
Implements cbDebuggerPlugin.
Definition at line 1702 of file debuggergdb.cpp.
References Cursor::file, DebuggerDriver::GetCursor(), DebuggerState::GetDriver(), DebuggerState::HasDriver(), Cursor::line, m_State, and wxEmptyString.
Referenced by GetExitCode().
GetExitCode()
int DebuggerGDB::GetExitCode () const inline virtual
Get the exit code of the last debug process.
Implements cbDebuggerPlugin.
Definition at line 89 of file debuggergdb.h.
References AddWatch(), AddWatchNoUpdate(), AttachToProcess(), CollapseWatch(), DeleteWatch(), DetachFromProcess(), DoSendCommand(), ExpandWatch(), GetCurrentPosition(), HasWatch(), IsAttachedToProcess(), m_LastExitCode, OnWatchesContextMenu(), RequestUpdate(), SendCommand(), SetWatchValue(), ShowWatchProperties(), and UpdateWatch().
GetProject()
cbProject* DebuggerGDB::GetProject () inline protected virtual
Implements cbDebuggerPlugin.
Definition at line 134 of file debuggergdb.h.
References m_pProject.
GetProjectConfigurationPanel()
cbConfigurationPanel * DebuggerGDB::GetProjectConfigurationPanel (wxWindow * parent, cbProject * project)
Definition at line 290 of file debuggergdb.cpp.
GetRemoteDebuggingMap()
RemoteDebuggingMap & DebuggerGDB::GetRemoteDebuggingMap (cbProject * project = 0)
Definition at line 340 of file debuggergdb.cpp.
References m_pProject, and m_RemoteDebugging.
Referenced by CleanupWhenProjectClosed(), DoDebug(), GDB_driver::GetRemoteDebuggingInfo(), GetState(), DebuggerOptionsProjectDlg::OnApply(), and OnProjectLoadingHook().
GetSearchDirs()
wxArrayString & DebuggerGDB::GetSearchDirs (cbProject * prj)
Definition at line 331 of file debuggergdb.cpp.
References m_SearchDirs.
Referenced by CleanupWhenProjectClosed(), DoDebug(), GetState(), DebuggerOptionsProjectDlg::OnApply(), and OnProjectLoadingHook().
GetStackFrame()
cb::shared_ptr< const cbStackFrame > DebuggerGDB::GetStackFrame (int index) const virtual
Implements cbDebuggerPlugin.
Definition at line 1275 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerDriver::GetStackFrames(), and m_State.
GetStackFrameCount()
int DebuggerGDB::GetStackFrameCount () const virtual
Implements cbDebuggerPlugin.
Definition at line 1270 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerDriver::GetStackFrames(), and m_State.
GetState()
DebuggerState& DebuggerGDB::GetState () inline
Definition at line 114 of file debuggergdb.h.
References _T, ConvertToGDBDirectory(), ConvertToGDBFile(), ConvertToGDBFriendly(), DebuggeeContinued(), GetRemoteDebuggingMap(), GetSearchDirs(), m_State, OnConfigurationChange(), OnProjectLoadingHook(), OnValueTooltip(), ShowValueTooltip(), and StripQuotes().
Referenced by GDB_driver::ParseOutput().
GetThread()
cb::shared_ptr< const cbThread > DebuggerGDB::GetThread (int index) const virtual
Implements cbDebuggerPlugin.
Definition at line 1305 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerDriver::GetThreads(), and m_State.
GetThreadsCount()
int DebuggerGDB::GetThreadsCount () const virtual
Implements cbDebuggerPlugin.
Definition at line 1297 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerDriver::GetThreads(), DebuggerState::HasDriver(), and m_State.
HasWatch()
bool DebuggerGDB::HasWatch (cb::shared_ptr< cbWatch > watch) virtual
Implements cbDebuggerPlugin.
Definition at line 2085 of file debuggergdb.cpp.
References m_funcArgsWatch, m_localsWatch, and m_watches.
Referenced by GetExitCode(), SetWatchValue(), and UpdateWatch().
IsAttachedToProcess()
bool DebuggerGDB::IsAttachedToProcess () const virtual
Implements cbDebuggerPlugin.
Definition at line 2222 of file debuggergdb.cpp.
References m_PidToAttach.
Referenced by GetExitCode(), and GDB_driver::Stop().
IsBusy()
bool DebuggerGDB::IsBusy () const virtual
Is the plugin processing something?
Implements cbDebuggerPlugin.
Definition at line 619 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), DebuggerDriver::IsQueueBusy(), and m_State.
Referenced by IsRunning().
IsRunning()
bool DebuggerGDB::IsRunning () const inline virtual
Is the plugin currently debugging?
Implements cbDebuggerPlugin.
Definition at line 85 of file debuggergdb.h.
References IsBusy(), IsStopped(), and m_pProcess.
Referenced by OnUpdateTools().
IsStopped()
bool DebuggerGDB::IsStopped () const virtual
Is the plugin stopped on breakpoint?
Implements cbDebuggerPlugin.
Definition at line 614 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), DebuggerDriver::IsProgramStopped(), and m_State.
Referenced by AddBreakpoint(), DeleteAllBreakpoints(), DeleteBreakpoint(), DoBreak(), DoSendCommand(), EnableBreakpoint(), IsRunning(), OnUpdateCatchThrow(), OnUpdateTools(), SetNextStatement(), ShowValueTooltip(), Stop(), and UpdateBreakpoint().
IsTemporaryBreak()
bool DebuggerGDB::IsTemporaryBreak () const inline
Definition at line 88 of file debuggergdb.h.
References m_TemporaryBreak.
Referenced by CDB_driver::ParseOutput().
KillConsole()
void DebuggerGDB::KillConsole () private
Definition at line 1885 of file debuggergdb.cpp.
References HandlerRoutine(), m_bIsConsole, m_nConsolePid, and wxKill().
Referenced by OnGDBTerminated(), OnReleaseReal(), and ResetProject().
LaunchProcess()
int DebuggerGDB::LaunchProcess (const wxString & cmd, const wxString & cwd) private
Definition at line 531 of file debuggergdb.cpp.
References _(), wxString::BeforeFirst(), wxString::Contains(), cbDebuggerPlugin::DebugLog(), Logger::error, wxString::Format(), wxArrayString::GetCount(), wxProcess::GetErrorStream(), wxProcess::GetInputStream(), wxProcess::GetOutputStream(), wxArrayString::Item(), wxString::Length(), cbDebuggerPlugin::Log(), m_Pid, m_pProcess, wxString::Mid(), wxString::StartsWith(), wxString::ToLong(), wxString::wx_str(), wxEXEC_ASYNC, wxEXEC_SYNC, wxExecute(), and wxT.
Referenced by DoDebug(), and ResetProject().
LoadConfig()
cbDebuggerConfiguration * DebuggerGDB::LoadConfig (const ConfigManagerWrapper & config) virtual
Implements cbDebuggerPlugin.
Definition at line 280 of file debuggergdb.cpp.
MarkAllWatchesAsUnchanged()
void DebuggerGDB::MarkAllWatchesAsUnchanged () private
Definition at line 2161 of file debuggergdb.cpp.
References m_funcArgsWatch, m_localsWatch, and m_watches.
Referenced by OnCursorChanged(), and ResetProject().
Next()
void DebuggerGDB::Next () virtual
Execute the next instruction and return control to the debugger.
Implements cbDebuggerPlugin.
Definition at line 1494 of file debuggergdb.cpp.
References CMD_STEP, and RunCommand().
NextInstruction()
void DebuggerGDB::NextInstruction () virtual
Execute the next instruction and return control to the debugger.
Implements cbDebuggerPlugin.
Definition at line 1499 of file debuggergdb.cpp.
References CMD_STEP_INSTR, and RunCommand().
OnAddSymbolFile()
void DebuggerGDB::OnAddSymbolFile (wxCommandEvent & event) private
Definition at line 1718 of file debuggergdb.cpp.
References _(), _T, ConvertToGDBDirectory(), wxString::IsEmpty(), wxFD_FILE_MUST_EXIST, wxFD_OPEN, and wxFileSelector().
Referenced by ResetProject().
OnAttachReal()
void DebuggerGDB::OnAttachReal () virtual
Implements cbDebuggerPlugin.
Definition at line 207 of file debuggergdb.cpp.
References cbEVT_BUILDTARGET_SELECTED, Manager::Get(), m_HookId, m_TimerPollDebugger, OnBuildTargetSelected(), OnProjectLoadingHook(), Manager::RegisterEventSink(), ProjectLoaderHooks::RegisterHook(), and wxTimer::SetOwner().
OnBuildTargetSelected()
void DebuggerGDB::OnBuildTargetSelected (CodeBlocksEvent & event) private
Definition at line 2236 of file debuggergdb.cpp.
References CodeBlocksEvent::GetBuildTargetName(), CodeBlocksEvent::GetProject(), m_ActiveBuildTarget, and m_pProject.
Referenced by OnAttachReal(), and ResetProject().
OnCatchThrow()
void DebuggerGDB::OnCatchThrow (wxCommandEvent & event) private
Definition at line 1794 of file debuggergdb.cpp.
References DebuggerConfiguration::CatchExceptions, DebuggerDriver::EnableCatchingThrow(), GetActiveConfigEx(), DebuggerState::GetDriver(), m_State, and DebuggerConfiguration::SetFlag().
Referenced by ResetProject().
OnConfigurationChange()
void DebuggerGDB::OnConfigurationChange (bool isActive) virtual
Called when the user clicks OK in Settings -> Debugger...
Reimplemented from cbDebuggerPlugin.
Definition at line 296 of file debuggergdb.cpp.
References Manager::Get(), GetActiveConfigEx(), Manager::GetDebuggerManager(), DebuggerConfiguration::GetFlag(), DebuggerManager::GetWatchesDialog(), m_funcArgsWatch, m_localsWatch, cbWatchesDlg::RemoveWatch(), RequestUpdate(), cbDebuggerPlugin::Watches, DebuggerConfiguration::WatchFuncArgs, and DebuggerConfiguration::WatchLocals.
Referenced by GetState().
OnCursorChanged()
void DebuggerGDB::OnCursorChanged (wxCommandEvent & event) private
Definition at line 1995 of file debuggergdb.cpp.
References _(), Cursor::address, cbDebuggerCommonConfig::AutoSwitchFrame, cbDebuggerPlugin::BringCBToFront(), cbDebuggerStringToAddress(), Cursor::changed, CMD_BACKTRACE, CMD_DISASSEMBLE, CMD_MEMORYDUMP, CMD_REGISTERS, CMD_RUNNINGTHREADS, DoWatches(), Cursor::file, wxString::Format(), Cursor::function, Manager::Get(), DebuggerDriver::GetCursor(), Manager::GetDebuggerManager(), DebuggerManager::GetDisassemblyDialog(), DebuggerState::GetDriver(), cbDebuggerCommonConfig::GetFlag(), DebuggerManager::GetWatchesDialog(), cbWatchesDlg::GetWindow(), DebuggerState::HasDriver(), IsWindowReallyShown(), Cursor::line, cbDebuggerPlugin::Log(), m_State, m_TemporaryBreak, MarkAllWatchesAsUnchanged(), RunCommand(), cbDisassemblyDlg::SetActiveAddress(), cbDebuggerPlugin::SyncEditor(), DebuggerManager::UpdateBacktrace(), DebuggerManager::UpdateCPURegisters(), DebuggerManager::UpdateDisassembly(), DebuggerManager::UpdateExamineMemory(), DebuggerManager::UpdateThreads(), and wxString::wx_str().
Referenced by ResetProject().
OnGDBError()
void DebuggerGDB::OnGDBError (wxCommandEvent & event) private
Definition at line 1840 of file debuggergdb.cpp.
References wxString::IsEmpty(), and ParseOutput().
Referenced by ResetProject().
OnGDBOutput()
void DebuggerGDB::OnGDBOutput (wxCommandEvent & event) private
Definition at line 1833 of file debuggergdb.cpp.
References wxString::IsEmpty(), and ParseOutput().
Referenced by ResetProject().
OnGDBTerminated()
void DebuggerGDB::OnGDBTerminated (wxCommandEvent & event) private
killerbot : run there the post shell commands ?
Definition at line 1847 of file debuggergdb.cpp.
References _(), cbEVT_DEBUGGER_FINISHED, cbMessageBox(), cbDebuggerPlugin::ClearActiveMarkFromAllEditors(), wxString::Format(), Manager::Get(), DebuggerManager::GetBreakpointDialog(), Manager::GetDebuggerManager(), Manager::GetPluginManager(), Manager::IsAppShuttingDown(), KillConsole(), cbDebuggerPlugin::Log(), m_LastExitCode, m_NoDebugInfo, m_PidToAttach, m_State, m_TimerPollDebugger, cbDebuggerPlugin::MarkAsStopped(), PluginManager::NotifyPlugins(), cbBreakpointsDlg::Reload(), wxTimer::Stop(), DebuggerState::StopDriver(), cbDebuggerPlugin::SwitchToPreviousLayout(), and wxICON_STOP.
Referenced by ResetProject().
OnIdle()
void DebuggerGDB::OnIdle (wxIdleEvent & event) private
Definition at line 1967 of file debuggergdb.cpp.
References m_pProcess.
Referenced by ResetProject().
OnInfoDLL()
void DebuggerGDB::OnInfoDLL (wxCommandEvent & event) private
Definition at line 1807 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), DebuggerDriver::InfoDLL(), and m_State.
Referenced by ResetProject().
OnInfoFiles()
void DebuggerGDB::OnInfoFiles (wxCommandEvent & event) private
Definition at line 1815 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), DebuggerDriver::InfoFiles(), and m_State.
Referenced by ResetProject().
OnInfoFPU()
void DebuggerGDB::OnInfoFPU (wxCommandEvent & event) private
Definition at line 1821 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), DebuggerDriver::InfoFPU(), and m_State.
Referenced by ResetProject().
OnInfoFrame()
void DebuggerGDB::OnInfoFrame (wxCommandEvent & event) private
Definition at line 1801 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), DebuggerDriver::InfoFrame(), and m_State.
Referenced by ResetProject().
OnInfoSignals()
void DebuggerGDB::OnInfoSignals (wxCommandEvent & event) private
Definition at line 1827 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), DebuggerDriver::InfoSignals(), and m_State.
Referenced by ResetProject().
OnMenuWatchDereference()
void DebuggerGDB::OnMenuWatchDereference (wxCommandEvent & event) private
Definition at line 2195 of file debuggergdb.cpp.
References Manager::Get(), Manager::GetDebuggerManager(), DebuggerManager::GetWatchesDialog(), m_watchToDereferenceProperty, m_watchToDereferenceSymbol, NULL, cbWatchesDlg::RenameWatch(), wxEmptyString, and wxT.
Referenced by ResetProject().
OnPrintElements()
void DebuggerGDB::OnPrintElements (wxCommandEvent & event) private
Definition at line 1767 of file debuggergdb.cpp.
References wxString::Format(), DebuggerState::GetDriver(), m_printElements, m_State, DebuggerDriver::QueueCommand(), RequestUpdate(), cbDebuggerPlugin::Watches, and wxT.
Referenced by ResetProject().
OnProjectLoadingHook()
void DebuggerGDB::OnProjectLoadingHook (cbProject * project, TiXmlElement * elem, bool loading)
Definition at line 353 of file debuggergdb.cpp.
References _T, wxArrayString::Add(), RemoteDebugging::additionalCmds, RemoteDebugging::additionalCmdsBefore, RemoteDebugging::additionalShellCmdsAfter, RemoteDebugging::additionalShellCmdsBefore, cbC2U(), cbU2C(), wxString::Clear(), RemoteDebugging::connType, RemoteDebugging::extendedRemote, cbProject::GetBuildTarget(), wxArrayString::GetCount(), GetRemoteDebuggingMap(), GetSearchDirs(), wxArrayString::Index(), wxString::insert(), RemoteDebugging::ip, RemoteDebugging::ipPort, wxString::IsEmpty(), RemoteDebugging::serialBaud, RemoteDebugging::serialPort, RemoteDebugging::skipLDpath, and wxNOT_FOUND.
Referenced by GetState(), and OnAttachReal().
OnReleaseReal()
void DebuggerGDB::OnReleaseReal (bool appShutDown) virtual
Implements cbDebuggerPlugin.
Definition at line 219 of file debuggergdb.cpp.
References DebuggerState::CleanUp(), DebuggerState::HasDriver(), KillConsole(), m_HookId, m_State, Stop(), and ProjectLoaderHooks::UnregisterHook().
OnShowFile()
void DebuggerGDB::OnShowFile (wxCommandEvent & event) private
Definition at line 1985 of file debuggergdb.cpp.
References cbDebuggerPlugin::SyncEditor().
Referenced by ResetProject().
OnTimer()
void DebuggerGDB::OnTimer (wxTimerEvent & event) private
Definition at line 1975 of file debuggergdb.cpp.
References CheckIfConsoleIsClosed(), ParseOutput(), wxEmptyString, and wxWakeUpIdle().
Referenced by ResetProject().
OnUpdateCatchThrow()
void DebuggerGDB::OnUpdateCatchThrow (wxUpdateUIEvent & event) private
Definition at line 1787 of file debuggergdb.cpp.
References DebuggerConfiguration::CatchExceptions, GetActiveConfigEx(), DebuggerConfiguration::GetFlag(), DebuggerConfiguration::IsGDB(), and IsStopped().
Referenced by ResetProject().
OnUpdateTools()
void DebuggerGDB::OnUpdateTools (wxUpdateUIEvent & event) private
Definition at line 1756 of file debuggergdb.cpp.
References IsRunning(), IsStopped(), and m_printElements.
Referenced by ResetProject().
OnValueTooltip()
void DebuggerGDB::OnValueTooltip (const wxString & token, const wxRect & evalRect) virtual
Reimplemented from cbDebuggerPlugin.
Definition at line 1945 of file debuggergdb.cpp.
References DebuggerDriver::EvaluateSymbol(), DebuggerState::GetDriver(), and m_State.
Referenced by GetState().
OnWatchesContextMenu()
void DebuggerGDB::OnWatchesContextMenu (wxMenu & menu, const cbWatch & watch, wxObject * property, int & disabledMenus) virtual
Parameters
[out] disabledMenus A combination of WatchesDisabledMenuItems, which controls which of the default menu items are disabled
Reimplemented from cbDebuggerPlugin.
Definition at line 2172 of file debuggergdb.cpp.
References _(), cbDebuggerPlugin::WatchesDisabledMenuItems::AddDataBreak, cbDebuggerPlugin::WatchesDisabledMenuItems::Delete, cbWatch::GetParent(), cbWatch::GetSymbol(), cbWatch::GetType(), wxMenu::Insert(), wxMenu::InsertSeparator(), IsPointerType(), m_watchToDereferenceProperty, m_watchToDereferenceSymbol, cbDebuggerPlugin::WatchesDisabledMenuItems::Properties, and cbDebuggerPlugin::WatchesDisabledMenuItems::Rename.
Referenced by GetExitCode().
ParseOutput()
void DebuggerGDB::ParseOutput (const wxString & output) private
Definition at line 1694 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), wxString::IsEmpty(), m_State, and DebuggerDriver::ParseOutput().
Referenced by OnGDBError(), OnGDBOutput(), OnTimer(), and ResetProject().
RequestUpdate()
void DebuggerGDB::RequestUpdate (DebugWindows window) virtual
Implements cbDebuggerPlugin.
Definition at line 1104 of file debuggergdb.cpp.
References cbDebuggerPlugin::Backtrace, CMD_BACKTRACE, CMD_DISASSEMBLE, CMD_MEMORYDUMP, CMD_REGISTERS, CMD_RUNNINGTHREADS, cbDebuggerPlugin::CPURegisters, cbDebuggerPlugin::Disassembly, DoWatches(), cbDebuggerPlugin::ExamineMemory, Manager::Get(), IsWindowReallyShown(), RunCommand(), cbDebuggerPlugin::Threads, and cbDebuggerPlugin::Watches.
Referenced by GetExitCode(), OnConfigurationChange(), and OnPrintElements().
ResetProject()
void DebuggerGDB::ResetProject () inline protected virtual
Implements cbDebuggerPlugin.
Definition at line 135 of file debuggergdb.h.
References AddSourceDir(), CheckIfConsoleIsClosed(), CleanupWhenProjectClosed(), CompilerFinished(), ConvertDirectory(), DeleteAllProjectBreakpoints(), DoBreak(), DoDebug(), DoWatches(), KillConsole(), LaunchProcess(), m_pProcess, MarkAllWatchesAsUnchanged(), NULL, OnAddSymbolFile(), OnBuildTargetSelected(), OnCatchThrow(), OnCursorChanged(), OnGDBError(), OnGDBOutput(), OnGDBTerminated(), OnIdle(), OnInfoDLL(), OnInfoFiles(), OnInfoFPU(), OnInfoFrame(), OnInfoSignals(), OnMenuWatchDereference(), OnPrintElements(), OnShowFile(), OnTimer(), OnUpdateCatchThrow(), OnUpdateTools(), ParseOutput(), and SetupToolsMenu().
RunCommand()
void DebuggerGDB::RunCommand (int cmd)
Definition at line 1132 of file debuggergdb.cpp.
References _(), DebuggerDriver::Backtrace(), cbDebuggerPlugin::ClearActiveMarkFromAllEditors(), CMD_BACKTRACE, CMD_CONTINUE, CMD_DISASSEMBLE, CMD_MEMORYDUMP, CMD_REGISTERS, CMD_RUNNINGTHREADS, CMD_STEP, CMD_STEP_INSTR, CMD_STEP_INTO_INSTR, CMD_STEPIN, CMD_STEPOUT, CMD_STOP, DebuggerDriver::Continue(), DebuggerDriver::CPURegisters(), DebuggerDriver::Disassemble(), Manager::Get(), DebuggerState::GetDriver(), DebuggerState::HasDriver(), cbDebuggerPlugin::Log(), m_pProcess, m_State, cbDebuggerPlugin::MarkAsStopped(), DebuggerDriver::MemoryDump(), DebuggerDriver::NotifyCursorChanged(), DebuggerDriver::ResetCurrentFrame(), DebuggerDriver::RunningThreads(), DebuggerDriver::Step(), DebuggerDriver::StepIn(), DebuggerDriver::StepInstruction(), DebuggerDriver::StepIntoInstruction(), DebuggerDriver::StepOut(), and DebuggerDriver::Stop().
Referenced by Continue(), Next(), NextInstruction(), OnCursorChanged(), RequestUpdate(), Step(), StepIntoInstruction(), StepOut(), and Stop().
RunToCursor()
bool DebuggerGDB::RunToCursor (const wxString & filename, int line, const wxString & line_text) virtual
Run the debugged program until it reaches the cursor at the current editor.
Implements cbDebuggerPlugin.
Definition at line 1540 of file debuggergdb.cpp.
References DebuggerState::AddBreakpoint(), Continue(), Debug(), DebuggerConfiguration::DoNotRun, Manager::Get(), GetActiveConfigEx(), DebuggerManager::GetBreakpointDialog(), Manager::GetDebuggerManager(), m_pProcess, m_State, and cbBreakpointsDlg::Reload().
SendCommand()
void DebuggerGDB::SendCommand (const wxString & cmd, bool debugLog) virtual
Implements cbDebuggerPlugin.
Definition at line 1081 of file debuggergdb.cpp.
References _T, CleanStringValue(), DoSendCommand(), DebuggerState::GetDriver(), DebuggerState::HasDriver(), cbDebuggerPlugin::Log(), m_State, and DebuggerDriver::QueueCommand().
Referenced by GetExitCode().
SetNextStatement()
void DebuggerGDB::SetNextStatement (const wxString & filename, int line) virtual
Sets the position of the Program counter to the specified filename:line.
Implements cbDebuggerPlugin.
Definition at line 1560 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), IsStopped(), m_State, and DebuggerDriver::SetNextStatement().
SetupToolsMenu()
void DebuggerGDB::SetupToolsMenu (wxMenu & menu) private virtual
Implements cbDebuggerPlugin.
Definition at line 1733 of file debuggergdb.cpp.
References _(), wxMenu::Append(), wxMenu::AppendCheckItem(), wxMenu::AppendRadioItem(), wxMenu::AppendSeparator(), wxMenu::AppendSubMenu(), and GetActiveConfigEx().
Referenced by ResetProject().
SetWatchValue()
bool DebuggerGDB::SetWatchValue (cb::shared_ptr< cbWatch > watch, const wxString & value) virtual
Implements cbDebuggerPlugin.
Definition at line 2106 of file debuggergdb.cpp.
References cbGetRootWatch(), DoWatches(), wxString::empty(), wxString::find(), DebuggerState::GetDriver(), DebuggerState::HasDriver(), HasWatch(), m_State, wxString::npos, DebuggerDriver::SetVarValue(), and wxT.
Referenced by GetExitCode().
ShiftBreakpoint()
void DebuggerGDB::ShiftBreakpoint (int index, int lines_to_shift) virtual
Implements cbDebuggerPlugin.
Definition at line 1460 of file debuggergdb.cpp.
References DebuggerState::GetBreakpoints(), m_State, and DebuggerState::ShiftBreakpoint().
ShowValueTooltip()
bool DebuggerGDB::ShowValueTooltip (int style) virtual
Reimplemented from cbDebuggerPlugin.
Definition at line 1927 of file debuggergdb.cpp.
References DebuggerConfiguration::EvalExpression, GetActiveConfigEx(), DebuggerState::GetDriver(), DebuggerConfiguration::GetFlag(), DebuggerState::HasDriver(), DebuggerDriver::IsDebuggingStarted(), IsStopped(), m_pProcess, m_State, wxSCI_C_DEFAULT, wxSCI_C_GLOBALCLASS, wxSCI_C_IDENTIFIER, wxSCI_C_OPERATOR, and wxSCI_C_WORD2.
Referenced by GetState().
ShowWatchProperties()
void DebuggerGDB::ShowWatchProperties (cb::shared_ptr< cbWatch > watch) virtual
Implements cbDebuggerPlugin.
Definition at line 2094 of file debuggergdb.cpp.
References DoWatches(), and wxID_OK.
Referenced by GetExitCode().
Step()
void DebuggerGDB::Step () virtual
Execute the next instruction, stepping into function calls if needed, and return control to the debugger.
Implements cbDebuggerPlugin.
Definition at line 1509 of file debuggergdb.cpp.
References CMD_STEPIN, and RunCommand().
StepIntoInstruction()
void DebuggerGDB::StepIntoInstruction () virtual
Execute the next instruction and return control to the debugger, if the instruction is a function call step into it.
Implements cbDebuggerPlugin.
Definition at line 1504 of file debuggergdb.cpp.
References CMD_STEP_INTO_INSTR, and RunCommand().
StepOut()
void DebuggerGDB::StepOut () virtual
Execute the next instruction, stepping out of function calls if needed, and return control to the debugger.
Implements cbDebuggerPlugin.
Definition at line 1535 of file debuggergdb.cpp.
References CMD_STEPOUT, and RunCommand().
Stop()
void DebuggerGDB::Stop () virtual
Stop the debugging process (exit debugging).
Implements cbDebuggerPlugin.
Definition at line 1671 of file debuggergdb.cpp.
References _(), Break(), CMD_STOP, cbDebuggerPlugin::DebugLog(), DebuggerDriver::GetChildPID(), DebuggerState::GetDriver(), IsStopped(), m_Pid, m_pProcess, m_State, RunCommand(), wxKill(), and wxSIGTERM.
Referenced by CheckIfConsoleIsClosed(), and OnReleaseReal().
StripQuotes()
void DebuggerGDB::StripQuotes (wxString & str) static
Definition at line 956 of file debuggergdb.cpp.
References _T, wxString::GetChar(), wxString::Length(), and wxString::Mid().
Referenced by ConvertToGDBDirectory(), and GetState().
SupportsFeature()
bool DebuggerGDB::SupportsFeature (cbDebuggerFeature::Flags flag) virtual
Implements cbDebuggerPlugin.
Definition at line 234 of file debuggergdb.cpp.
References cbDebuggerFeature::Breakpoints, cbDebuggerFeature::Callstack, cbDebuggerFeature::CPURegisters, cbDebuggerFeature::Disassembly, cbDebuggerFeature::ExamineMemory, GetActiveConfigEx(), DebuggerConfiguration::IsGDB(), cbDebuggerFeature::RunToCursor, cbDebuggerFeature::SetNextStatement, cbDebuggerFeature::Threads, cbDebuggerFeature::ValueTooltips, and cbDebuggerFeature::Watches.
SwitchToFrame()
void DebuggerGDB::SwitchToFrame (int number) virtual
Implements cbDebuggerPlugin.
Definition at line 1280 of file debuggergdb.cpp.
References Manager::Get(), DebuggerManager::GetBacktraceDialog(), Manager::GetDebuggerManager(), DebuggerState::GetDriver(), DebuggerState::HasDriver(), m_State, cbBacktraceDlg::Reload(), DebuggerDriver::SetCurrentFrame(), and DebuggerDriver::SwitchToFrame().
SwitchToThread()
bool DebuggerGDB::SwitchToThread (int thread_number) virtual
Implements cbDebuggerPlugin.
Definition at line 1310 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerDriver::GetThreads(), DebuggerState::HasDriver(), m_State, and DebuggerDriver::SwitchThread().
UpdateBreakpoint()
void DebuggerGDB::UpdateBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint) virtual
Implements cbDebuggerPlugin.
Definition at line 1379 of file debuggergdb.cpp.
References DebuggerBreakpoint::bptCode, DebuggerBreakpoint::bptData, DebuggerBreakpoint::bptFunction, Continue(), DoBreak(), Manager::Get(), EditBreakpointDlg::GetBreakpoint(), DebuggerState::GetBreakpoints(), DataBreakpointDlg::GetDataExpression(), DataBreakpointDlg::GetSelection(), IsStopped(), m_State, PlaceWindow(), DebuggerState::ResetBreakpoint(), wxDialog::ShowModal(), and wxID_OK.
UpdateWatch()
void DebuggerGDB::UpdateWatch (cb::shared_ptr< cbWatch > watch) virtual
Implements cbDebuggerPlugin.
Definition at line 2145 of file debuggergdb.cpp.
References DebuggerState::GetDriver(), DebuggerState::HasDriver(), HasWatch(), m_funcArgsWatch, m_localsWatch, m_State, DebuggerDriver::UpdateWatch(), and DebuggerDriver::UpdateWatchLocalsArgs().
Referenced by GetExitCode().
Validate()
bool DebuggerGDB::Validate (const wxString & line, const char cb)
Definition at line 1514 of file debuggergdb.cpp.
References _T, and wxString::Find().
Friends And Related Function Documentation
TestIfBelongToProject
friend struct TestIfBelongToProject friend
Definition at line 215 of file debuggergdb.h.
Member Data Documentation
m_ActiveBuildTarget
wxString DebuggerGDB::m_ActiveBuildTarget private
Definition at line 190 of file debuggergdb.h.
Referenced by Debug(), DoDebug(), and OnBuildTargetSelected().
m_bIsConsole
bool DebuggerGDB::m_bIsConsole private
Definition at line 202 of file debuggergdb.h.
Referenced by DoDebug(), and KillConsole().
m_Canceled
bool DebuggerGDB::m_Canceled private
Definition at line 206 of file debuggergdb.h.
Referenced by Debug(), and DoDebug().
m_EvalRect
wxRect DebuggerGDB::m_EvalRect private
Definition at line 182 of file debuggergdb.h.
m_funcArgsWatch
cb::shared_ptr<GDBWatch> DebuggerGDB::m_funcArgsWatch private
Definition at line 211 of file debuggergdb.h.
Referenced by DoWatches(), HasWatch(), MarkAllWatchesAsUnchanged(), OnConfigurationChange(), and UpdateWatch().
m_HookId
int DebuggerGDB::m_HookId private
Definition at line 199 of file debuggergdb.h.
Referenced by OnAttachReal(), and OnReleaseReal().
m_LastExitCode
bool DebuggerGDB::m_LastExitCode private
Definition at line 179 of file debuggergdb.h.
Referenced by GetExitCode(), and OnGDBTerminated().
m_localsWatch
cb::shared_ptr<GDBWatch> DebuggerGDB::m_localsWatch private
Definition at line 211 of file debuggergdb.h.
Referenced by DoWatches(), HasWatch(), MarkAllWatchesAsUnchanged(), OnConfigurationChange(), and UpdateWatch().
m_nConsolePid
int DebuggerGDB::m_nConsolePid private
Definition at line 204 of file debuggergdb.h.
Referenced by CheckIfConsoleIsClosed(), DoDebug(), and KillConsole().
m_NoDebugInfo
bool DebuggerGDB::m_NoDebugInfo private
Definition at line 184 of file debuggergdb.h.
Referenced by Debug(), and OnGDBTerminated().
m_Pid
int DebuggerGDB::m_Pid private
Definition at line 180 of file debuggergdb.h.
Referenced by DoBreak(), LaunchProcess(), and Stop().
m_PidToAttach
int DebuggerGDB::m_PidToAttach private
Definition at line 181 of file debuggergdb.h.
Referenced by AttachToProcess(), Debug(), DetachFromProcess(), DoDebug(), IsAttachedToProcess(), and OnGDBTerminated().
m_pProcess
PipedProcess* DebuggerGDB::m_pProcess private
Definition at line 178 of file debuggergdb.h.
Referenced by AddWatch(), Debug(), DoBreak(), DoDebug(), DoSendCommand(), DoWatches(), IsRunning(), LaunchProcess(), OnIdle(), ResetProject(), RunCommand(), RunToCursor(), ShowValueTooltip(), and Stop().
m_pProject
cbProject* DebuggerGDB::m_pProject private
Definition at line 189 of file debuggergdb.h.
Referenced by Debug(), DoDebug(), GetProject(), GetRemoteDebuggingMap(), and OnBuildTargetSelected().
m_printElements
int DebuggerGDB::m_printElements private
Definition at line 217 of file debuggergdb.h.
Referenced by DoDebug(), OnPrintElements(), and OnUpdateTools().
m_RemoteDebugging
ProjectRemoteDebuggingMap DebuggerGDB::m_RemoteDebugging private
Definition at line 197 of file debuggergdb.h.
Referenced by GetRemoteDebuggingMap().
m_SearchDirs
SearchDirsMap DebuggerGDB::m_SearchDirs private
Definition at line 194 of file debuggergdb.h.
Referenced by GetSearchDirs().
m_State
DebuggerState DebuggerGDB::m_State private
Definition at line 34 of file debuggergdb.h.
Referenced by AddBreakpoint(), AddDataBreakpoint(), AddSourceDir(), AddWatch(), Debug(), DeleteAllBreakpoints(), DeleteAllProjectBreakpoints(), DeleteBreakpoint(), DetachFromProcess(), DoBreak(), DoDebug(), DoWatches(), EnableBreakpoint(), GetActiveStackFrame(), GetBreakpoint(), GetBreakpointsCount(), GetCurrentPosition(), GetStackFrame(), GetStackFrameCount(), GetState(), GetThread(), GetThreadsCount(), IsBusy(), IsStopped(), OnCatchThrow(), OnCursorChanged(), OnGDBTerminated(), OnInfoDLL(), OnInfoFiles(), OnInfoFPU(), OnInfoFrame(), OnInfoSignals(), OnPrintElements(), OnReleaseReal(), OnValueTooltip(), ParseOutput(), RunCommand(), RunToCursor(), SendCommand(), SetNextStatement(), SetWatchValue(), ShiftBreakpoint(), ShowValueTooltip(), Stop(), SwitchToFrame(), SwitchToThread(), UpdateBreakpoint(), and UpdateWatch().
m_stopDebuggerConsoleClosed
bool DebuggerGDB::m_stopDebuggerConsoleClosed private
Definition at line 203 of file debuggergdb.h.
Referenced by CheckIfConsoleIsClosed(), and DoDebug().
m_StoppedOnSignal
bool DebuggerGDB::m_StoppedOnSignal private
Definition at line 186 of file debuggergdb.h.
m_TemporaryBreak
bool DebuggerGDB::m_TemporaryBreak private
Definition at line 208 of file debuggergdb.h.
Referenced by DebuggeeContinued(), DoBreak(), IsTemporaryBreak(), and OnCursorChanged().
m_TimerPollDebugger
wxTimer DebuggerGDB::m_TimerPollDebugger private
Definition at line 183 of file debuggergdb.h.
Referenced by DoDebug(), OnAttachReal(), and OnGDBTerminated().
m_watches
WatchesContainer DebuggerGDB::m_watches private
Definition at line 210 of file debuggergdb.h.
Referenced by AddWatch(), AddWatchNoUpdate(), DeleteWatch(), DoWatches(), HasWatch(), and MarkAllWatchesAsUnchanged().
m_watchToDereferenceProperty
wxObject* DebuggerGDB::m_watchToDereferenceProperty private
Definition at line 213 of file debuggergdb.h.
Referenced by OnMenuWatchDereference(), and OnWatchesContextMenu().
m_watchToDereferenceSymbol
wxString DebuggerGDB::m_watchToDereferenceSymbol private
Definition at line 212 of file debuggergdb.h.
Referenced by OnMenuWatchDereference(), and OnWatchesContextMenu().
The documentation for this class was generated from the following files:
debuggergdb.h
debuggergdb.cpp