Code::Blocks: ColourManager Class Reference
ColourManager Class Reference
#include <cbcolourmanager.h>
Classes
struct ColourDef
Public Types
typedef std::map< wxString, ColourDef > ColourDefMap
Public Member Functions
void Load ()
void Save ()
void RegisterColour (const wxString &category, const wxString &name, const wxString &id, const wxColour &defaultColour)
wxColour GetColour (const wxString &id) const
void SetColour (const wxString &id, const wxColour &colour)
const ColourDefMap & GetColourDefinitions () const
Private Attributes
ColourDefMap m_colours
Friends
class Mgr< ColourManager >
class Manager
Additional Inherited Members
Static Public Member Functions inherited from Mgr< ColourManager >
static bool Valid ()
static ColourManager * Get ()
static void Free ()
Protected Member Functions inherited from Mgr< ColourManager >
Mgr ()
virtual ~Mgr ()
Detailed Description
Definition at line 14 of file cbcolourmanager.h.
Member Typedef Documentation
ColourDefMap
typedef std::map<wxString, ColourDef> ColourManager::ColourDefMap
Definition at line 36 of file cbcolourmanager.h.
Member Function Documentation
GetColour()
wxColour ColourManager::GetColour (const wxString & id) const
Definition at line 75 of file cbcolourmanager.cpp.
References m_colours, and wxBLACK.
Referenced by EditorColourSet::Apply(), CCOptionsDlg::CCOptionsDlg(), ProjectManagerUI::CheckForExternallyModifiedProjects(), EditorConfigurationDlg::EditorConfigurationDlg(), DocumentationHelper::GenerateHTML(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), ThreadsDlg::Reload(), BacktraceDlg::Reload(), StartHerePage::Reload(), setupColours(), TextCtrlLogger::UpdateSettings(), ListCtrlLogger::UpdateSettings(), and UpdateWatch().
GetColourDefinitions()
const ColourManager::ColourDefMap & ColourManager::GetColourDefinitions () const
Definition at line 88 of file cbcolourmanager.cpp.
References m_colours.
Referenced by EnvironmentSettingsDlg::FillApplicationColours(), EnvironmentSettingsDlg::OnChooseAppColourItem(), and EnvironmentSettingsDlg::OnClickAppColour().
Load()
void ColourManager::Load ()
Definition at line 21 of file cbcolourmanager.cpp.
References ConfigManager::EnumerateKeys(), Manager::Get(), Manager::GetConfigManager(), wxArrayString::GetCount(), m_colours, ConfigManager::ReadColour(), ColourManager::ColourDef::value, and wxT.
Referenced by MainFrame::CreateIDE().
RegisterColour()
void ColourManager::RegisterColour (const wxString & category, const wxString & name, const wxString & id, const wxColour & defaultColour)
Definition at line 54 of file cbcolourmanager.cpp.
References ColourManager::ColourDef::category, ColourManager::ColourDef::defaultValue, wxString::Lower(), m_colours, ColourManager::ColourDef::name, and ColourManager::ColourDef::value.
Referenced by BacktraceDlg::BacktraceDlg(), CCManager::CCManager(), DocumentationHelper::DocumentationHelper(), EditorManager::EditorManager(), LogManager::LogManager(), ProjectManagerUI::ProjectManagerUI(), StartHerePage::RegisterColours(), ThreadsDlg::ThreadsDlg(), and WatchesDlg::WatchesDlg().
Save()
void ColourManager::Save ()
Definition at line 42 of file cbcolourmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), m_colours, ConfigManager::UnSet(), ConfigManager::Write(), and wxT.
Referenced by EnvironmentSettingsDlg::EndModal(), and EditorConfigurationDlg::EndModal().
SetColour()
void ColourManager::SetColour (const wxString & id, const wxColour & colour)
Definition at line 81 of file cbcolourmanager.cpp.
References m_colours.
Referenced by EditorConfigurationDlg::EndModal(), CCOptionsDlg::OnApply(), and EnvironmentSettingsDlg::WriteApplicationColours().
Friends And Related Function Documentation
Manager
friend class Manager friend
Definition at line 17 of file cbcolourmanager.h.
Mgr< ColourManager >
friend class Mgr< ColourManager > friend
Definition at line 16 of file cbcolourmanager.h.
Member Data Documentation
m_colours
ColourDefMap ColourManager::m_colours private
Definition at line 40 of file cbcolourmanager.h.
Referenced by GetColour(), GetColourDefinitions(), Load(), RegisterColour(), Save(), and SetColour().
The documentation for this class was generated from the following files:
cbcolourmanager.h
cbcolourmanager.cpp