Code::Blocks: FilePathPanel Class Reference
FilePathPanel Class Reference
#include <filepathpanel.h>
Public Member Functions
FilePathPanel (wxWindow *parent, wxWindowID id=-1)
virtual ~FilePathPanel ()
wxString GetFilename () const
wxString GetHeaderGuard () const
bool GetAddToProject () const
void SetAddToProject (bool add)
int GetTargetIndex ()
void SetFilePathSelectionFilter (const wxString &filter)
void ShowHeaderGuard (bool show)
Static Public Attributes
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_BUTTON1 = wxNewId()
static const long ID_STATICTEXT3 = wxNewId()
static const long ID_TEXTCTRL2 = wxNewId()
static const long ID_CHECKBOX1 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_CHECKLISTBOX2 = wxNewId()
static const long ID_BUTTON2 = wxNewId()
static const long ID_BUTTON3 = wxNewId()
Private Member Functions
void OntxtFilenameText (wxCommandEvent &event)
void OnbtnBrowseClick (wxCommandEvent &event)
void OnchkAddToProjectChange (wxCommandEvent &event)
void OnbtnAllClick (wxCommandEvent &event)
void OnbtnNoneClick (wxCommandEvent &event)
void ToggleVisibility (bool on)
Private Attributes
wxButton * btnAll
wxStaticText * lblGuard
wxFlexGridSizer * FlexGridSizer1
wxBoxSizer * BoxSizer3
wxCheckListBox * clbTargets
wxBoxSizer * BoxSizer2
wxCheckBox * chkAddToProject
wxTextCtrl * txtFilename
wxButton * btnNone
wxButton * btnBrowse
wxTextCtrl * txtGuard
wxBoxSizer * BoxSizer6
wxString m_ExtFilter
int m_Selection
Detailed Description
Definition at line 22 of file filepathpanel.h.
Constructor & Destructor Documentation
FilePathPanel()
FilePathPanel::FilePathPanel (wxWindow * parent, wxWindowID id = -1)
Definition at line 44 of file filepathpanel.cpp.
References _(), _T, wxBoxSizer::Add(), wxBoxSizer::Fit(), Manager::Get(), cbProject::GetActiveBuildTarget(), ProjectManager::GetActiveProject(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), Manager::GetProjectManager(), CompileTargetBase::GetTitle(), ID_TEXTCTRL1, OnbtnAllClick(), OnbtnBrowseClick(), OnbtnNoneClick(), OnchkAddToProjectChange(), OntxtFilenameText(), wxBoxSizer::SetSizeHints(), wxALIGN_CENTER_VERTICAL, wxALIGN_LEFT, wxALIGN_TOP, wxALL, wxBOTTOM, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxFIXED_MINSIZE, wxHORIZONTAL, wxLB_HSCROLL, wxLB_SINGLE, wxLEFT, wxRIGHT, wxTAB_TRAVERSAL, wxTOP, and wxVERTICAL.
~FilePathPanel()
FilePathPanel::~FilePathPanel () virtual
Definition at line 131 of file filepathpanel.cpp.
Member Function Documentation
GetAddToProject()
bool FilePathPanel::GetAddToProject () const inline
Definition at line 31 of file filepathpanel.h.
References chkAddToProject, GetTargetIndex(), wxCheckBox::GetValue(), and SetAddToProject().
Referenced by WizFilePathPanel::OnPageChanging().
GetFilename()
wxString FilePathPanel::GetFilename () const inline
Definition at line 29 of file filepathpanel.h.
References txtFilename.
Referenced by WizFilePathPanel::OnPageChanging().
GetHeaderGuard()
wxString FilePathPanel::GetHeaderGuard () const inline
Definition at line 30 of file filepathpanel.h.
References _T, and txtGuard.
Referenced by WizFilePathPanel::OnPageChanging().
GetTargetIndex()
int FilePathPanel::GetTargetIndex ()
Definition at line 145 of file filepathpanel.cpp.
References clbTargets, wxCheckListBox::GetCount(), wxCheckListBox::IsChecked(), and m_Selection.
Referenced by GetAddToProject(), and WizFilePathPanel::GetTargetIndex().
OnbtnAllClick()
void FilePathPanel::OnbtnAllClick (wxCommandEvent & event) private
Definition at line 202 of file filepathpanel.cpp.
References wxCheckListBox::Check(), clbTargets, and wxCheckListBox::GetCount().
Referenced by FilePathPanel().
OnbtnBrowseClick()
void FilePathPanel::OnbtnBrowseClick (wxCommandEvent & event) private
Definition at line 183 of file filepathpanel.cpp.
References _(), _T, Manager::Get(), ProjectManager::GetActiveProject(), CompileTargetBase::GetBasePath(), Manager::GetProjectManager(), m_ExtFilter, PlaceWindow(), txtFilename, wxFD_OVERWRITE_PROMPT, wxFD_SAVE, and wxID_OK.
Referenced by FilePathPanel().
OnbtnNoneClick()
void FilePathPanel::OnbtnNoneClick (wxCommandEvent & event) private
Definition at line 210 of file filepathpanel.cpp.
References wxCheckListBox::Check(), clbTargets, and wxCheckListBox::GetCount().
Referenced by FilePathPanel().
OnchkAddToProjectChange()
void FilePathPanel::OnchkAddToProjectChange (wxCommandEvent & event) private
Definition at line 197 of file filepathpanel.cpp.
References SetAddToProject().
Referenced by FilePathPanel().
OntxtFilenameText()
void FilePathPanel::OntxtFilenameText (wxCommandEvent & event) private
Definition at line 167 of file filepathpanel.cpp.
References _T, wxString::MakeUpper(), wxString::Replace(), txtFilename, txtGuard, and wxFileNameFromPath().
Referenced by FilePathPanel().
SetAddToProject()
void FilePathPanel::SetAddToProject (bool add)
Definition at line 135 of file filepathpanel.cpp.
References chkAddToProject, Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetProjectManager(), wxCheckBox::SetValue(), and ToggleVisibility().
Referenced by GetAddToProject(), OnchkAddToProjectChange(), and WizFilePathPanel::WizFilePathPanel().
SetFilePathSelectionFilter()
void FilePathPanel::SetFilePathSelectionFilter (const wxString & filter) inline
Definition at line 34 of file filepathpanel.h.
References m_ExtFilter.
Referenced by WizFilePathPanel::SetFilePathSelectionFilter().
ShowHeaderGuard()
void FilePathPanel::ShowHeaderGuard (bool show) inline
Definition at line 35 of file filepathpanel.h.
References lblGuard, and txtGuard.
Referenced by WizFilePathPanel::WizFilePathPanel().
ToggleVisibility()
void FilePathPanel::ToggleVisibility (bool on) private
Definition at line 218 of file filepathpanel.cpp.
References btnAll, btnNone, and clbTargets.
Referenced by SetAddToProject().
Member Data Documentation
BoxSizer2
wxBoxSizer* FilePathPanel::BoxSizer2 private
Definition at line 71 of file filepathpanel.h.
BoxSizer3
wxBoxSizer* FilePathPanel::BoxSizer3 private
Definition at line 69 of file filepathpanel.h.
BoxSizer6
wxBoxSizer* FilePathPanel::BoxSizer6 private
Definition at line 77 of file filepathpanel.h.
btnAll
wxButton* FilePathPanel::btnAll private
Definition at line 66 of file filepathpanel.h.
Referenced by ToggleVisibility().
btnBrowse
wxButton* FilePathPanel::btnBrowse private
Definition at line 75 of file filepathpanel.h.
btnNone
wxButton* FilePathPanel::btnNone private
Definition at line 74 of file filepathpanel.h.
Referenced by ToggleVisibility().
chkAddToProject
wxCheckBox* FilePathPanel::chkAddToProject private
Definition at line 72 of file filepathpanel.h.
Referenced by GetAddToProject(), and SetAddToProject().
clbTargets
wxCheckListBox* FilePathPanel::clbTargets private
Definition at line 70 of file filepathpanel.h.
Referenced by GetTargetIndex(), OnbtnAllClick(), OnbtnNoneClick(), and ToggleVisibility().
FlexGridSizer1
wxFlexGridSizer* FilePathPanel::FlexGridSizer1 private
Definition at line 68 of file filepathpanel.h.
ID_BUTTON1
const long FilePathPanel::ID_BUTTON1 = wxNewId() static
Definition at line 45 of file filepathpanel.h.
ID_BUTTON2
const long FilePathPanel::ID_BUTTON2 = wxNewId() static
Definition at line 51 of file filepathpanel.h.
ID_BUTTON3
const long FilePathPanel::ID_BUTTON3 = wxNewId() static
Definition at line 52 of file filepathpanel.h.
ID_CHECKBOX1
const long FilePathPanel::ID_CHECKBOX1 = wxNewId() static
Definition at line 48 of file filepathpanel.h.
ID_CHECKLISTBOX2
const long FilePathPanel::ID_CHECKLISTBOX2 = wxNewId() static
Definition at line 50 of file filepathpanel.h.
ID_STATICTEXT1
const long FilePathPanel::ID_STATICTEXT1 = wxNewId() static
Definition at line 42 of file filepathpanel.h.
ID_STATICTEXT2
const long FilePathPanel::ID_STATICTEXT2 = wxNewId() static
Definition at line 43 of file filepathpanel.h.
ID_STATICTEXT3
const long FilePathPanel::ID_STATICTEXT3 = wxNewId() static
Definition at line 46 of file filepathpanel.h.
ID_STATICTEXT4
const long FilePathPanel::ID_STATICTEXT4 = wxNewId() static
Definition at line 49 of file filepathpanel.h.
ID_TEXTCTRL1
const long FilePathPanel::ID_TEXTCTRL1 = wxNewId() static
Definition at line 44 of file filepathpanel.h.
ID_TEXTCTRL2
const long FilePathPanel::ID_TEXTCTRL2 = wxNewId() static
Definition at line 47 of file filepathpanel.h.
lblGuard
wxStaticText* FilePathPanel::lblGuard private
Definition at line 67 of file filepathpanel.h.
Referenced by ShowHeaderGuard().
m_ExtFilter
wxString FilePathPanel::m_ExtFilter private
Definition at line 80 of file filepathpanel.h.
Referenced by OnbtnBrowseClick(), and SetFilePathSelectionFilter().
m_Selection
int FilePathPanel::m_Selection private
Definition at line 81 of file filepathpanel.h.
Referenced by GetTargetIndex().
txtFilename
wxTextCtrl* FilePathPanel::txtFilename private
Definition at line 73 of file filepathpanel.h.
Referenced by GetFilename(), OnbtnBrowseClick(), and OntxtFilenameText().
txtGuard
wxTextCtrl* FilePathPanel::txtGuard private
Definition at line 76 of file filepathpanel.h.
Referenced by GetHeaderGuard(), OntxtFilenameText(), and ShowHeaderGuard().
The documentation for this class was generated from the following files:
filepathpanel.h
filepathpanel.cpp