Code::Blocks: EditPairDlg Class Reference
EditPairDlg Class Reference
#include <editpairdlg.h>
Public Types
enum BrowseMode { bmDisable = 0, bmBrowseForFile, bmBrowseForDirectory }
Public Member Functions
EditPairDlg (wxWindow *parent, wxString &key, wxString &value, const wxString &title=_("Edit pair"), BrowseMode allowBrowse=bmDisable)
virtual ~EditPairDlg ()
EditPairDlg & operator= (const EditPairDlg &)
virtual void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void OnUpdateUI (wxUpdateUIEvent &event)
void OnBrowse (wxCommandEvent &event)
Protected Attributes
wxString & m_Key
wxString & m_Value
BrowseMode m_BrowseMode
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Member Enumeration Documentation
enum EditPairDlg::BrowseMode
Enumerator
bmDisable
bmBrowseForFile
bmBrowseForDirectory
Constructor & Destructor Documentation
EditPairDlg::EditPairDlg (wxWindow * parent, wxString & key, wxString & value, const wxString & title = _("Edit pair"), BrowseMode allowBrowse = bmDisable)
EditPairDlg::~EditPairDlg () virtual
Member Function Documentation
void EditPairDlg::EndModal (int retCode) virtual
References ScriptBindings::EndModal(), m_Key, and m_Value.
void EditPairDlg::OnBrowse (wxCommandEvent & event) protected
References bmBrowseForDirectory, bmBrowseForFile, bmDisable, ChooseDirectory(), FileFilters::GetFilterAll(), m_BrowseMode, and PlaceWindow().
void EditPairDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
References reKey().
EditPairDlg& EditPairDlg::operator= (const EditPairDlg &) inline
Member Data Documentation
BrowseMode EditPairDlg::m_BrowseMode protected
Referenced by OnBrowse().
wxString& EditPairDlg::m_Key protected
Referenced by EndModal().
wxString& EditPairDlg::m_Value protected
Referenced by EndModal().
The documentation for this class was generated from the following files:
editpairdlg.h
editpairdlg.cpp