Code::Blocks: cbTextInputStream Class Reference
cbTextInputStream Class Reference
Public Member Functions
cbTextInputStream (wxInputStream &s, const wxString &sep=wxT(" \), wxMBConv &conv=wxConvLocal)
~cbTextInputStream ()
wxChar NextChar ()
wxString ReadLine ()
Public Member Functions inherited from wxTextInputStream
wxTextInputStream (wxInputStream &stream, const wxString &sep=" \", const wxMBConv &conv=wxConvAuto())
~wxTextInputStream ()
const wxInputStream & GetInputStream () const
wxChar GetChar ()
wxUint16 Read16 (int base=10)
wxInt16 Read16S (int base=10)
wxUint32 Read32 (int base=10)
wxInt32 Read32S (int base=10)
wxUint8 Read8 (int base=10)
wxInt8 Read8S (int base=10)
double ReadDouble ()
wxString ReadLine ()
wxString ReadString ()
wxString ReadWord ()
void SetStringSeparators (const wxString &sep)
Protected Attributes
bool m_allowMBconversion
Detailed Description
Definition at line 20 of file pipedprocess.cpp.
Constructor & Destructor Documentation
cbTextInputStream()
cbTextInputStream::cbTextInputStream (wxInputStream & s, const wxString & sep = wxT(" \t"), wxMBConv & conv = wxConvLocal) inline
Definition at line 26 of file pipedprocess.cpp.
References HTMLTags::sep, wxT, and wxTextInputStream::wxTextInputStream().
~cbTextInputStream()
cbTextInputStream::~cbTextInputStream () inline
Definition at line 39 of file pipedprocess.cpp.
Member Function Documentation
NextChar()
wxChar cbTextInputStream::NextChar () inline
Definition at line 46 of file pipedprocess.cpp.
Referenced by ReadLine().
ReadLine()
wxString cbTextInputStream::ReadLine () inline
Definition at line 81 of file pipedprocess.cpp.
References NextChar().
Referenced by PipedProcess::HasInput().
Member Data Documentation
m_allowMBconversion
bool cbTextInputStream::m_allowMBconversion protected
Definition at line 23 of file pipedprocess.cpp.
The documentation for this class was generated from the following file:
pipedprocess.cpp