Code::Blocks: InfoPane Class Reference
InfoPane Class Reference
#include <infopane.h>
Classes
struct Page
Public Member Functions
InfoPane (wxWindow *parent)
virtual ~InfoPane ()
void Show (size_t index)
void Show (Logger *logger)
void Hide (Logger *logger)
void ShowNonLogger (wxWindow *p)
void HideNonLogger (wxWindow *p)
int GetPageIndexByWindow (wxWindow *win)
int GetCurrentPage (bool &is_logger)
Logger * GetLogger (int index)
wxWindow * GetWindow (int index)
void UpdateEffectiveTabOrder ()
void LoadTabOrder (wxString layout)
wxString SaveTabOrder ()
bool AddLogger (Logger *logger, wxWindow *p, const wxString &title, wxBitmap *icon=nullptr)
bool DeleteLogger (Logger *l)
bool AddNonLogger (wxWindow *p, const wxString &title, wxBitmap *icon=nullptr)
bool RemoveNonLogger (wxWindow *p)
bool DeleteNonLogger (wxWindow *p)
Public Member Functions inherited from cbAuiNotebook
cbAuiNotebook (wxWindow *pParent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxAUI_NB_DEFAULT_STYLE)
cbAuiNotebook constructor
virtual ~cbAuiNotebook ()
cbAuiNotebook destructor
void AdvanceSelection (bool forward=true)
Advances the selection.
wxString SavePerspective (const wxString projectTitle=wxEmptyString)
Save layout of the notebook.
bool LoadPerspective (const wxString &layout, bool mergeLayouts=false)
Loads serialized notebook layout.
int GetTabIndexFromTooltip (const wxString &text)
Get the tab index from tooltiptext.
int GetTabPositionFromIndex (int index)
Get the tab position.
void MinimizeFreeSpace ()
Minmize free horizontal page.
bool DeletePage (size_t page)
Delete Page.
bool RemovePage (size_t page)
Remove Page.
bool MovePage (wxWindow *page, size_t new_idx)
Move page.
bool AddPage (wxWindow *page, const wxString &caption, bool select=false, const wxBitmap &bitmap=wxNullBitmap)
Add Page.
bool InsertPage (size_t page_idx, wxWindow *page, const wxString &caption, bool select=false, const wxBitmap &bitmap=wxNullBitmap)
Insert Page.
void SetZoom (int zoom)
Set zoomfactor for builtin editors.
void FocusActiveTabCtrl ()
Set Focus on the tabCtrl belonging to the active tab.
wxAuiTabCtrl * GetTabCtrl (wxWindow *page)
Returns a pointer to the page's tab control or nullptr.
void GetPagesInTabCtrl (std::vector< wxWindow *> &result, wxWindow *page)
Return a vector containing all pages that are in the same tab control as the page passed as parameter.
Public Member Functions inherited from wxAuiNotebook
wxAuiNotebook ()
wxAuiNotebook (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxAUI_NB_DEFAULT_STYLE)
bool AddPage (wxWindow *page, const wxString &caption, bool select=false, const wxBitmap &bitmap=wxNullBitmap)
virtual bool AddPage (wxWindow *page, const wxString &text, bool select, int imageId)
void AdvanceSelection (bool forward=true)
virtual int ChangeSelection (size_t n)
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
virtual bool DeleteAllPages ()
wxAuiTabArt * GetArtProvider () const
wxWindow * GetCurrentPage () const
int GetHeightForPageHeight (int pageHeight)
wxWindow * GetPage (size_t page_idx) const
wxBitmap GetPageBitmap (size_t page) const
size_t GetPageCount () const
int GetPageIndex (wxWindow *page_wnd) const
wxString GetPageText (size_t page) const
wxString GetPageToolTip (size_t pageIdx) const
int GetSelection () const
int GetTabCtrlHeight () const
bool InsertPage (size_t page_idx, wxWindow *page, const wxString &caption, bool select=false, const wxBitmap &bitmap=wxNullBitmap)
virtual bool InsertPage (size_t index, wxWindow *page, const wxString &text, bool select=false, int imageId=NO_IMAGE)
void SetArtProvider (wxAuiTabArt *art)
virtual bool SetFont (const wxFont &font)
void SetMeasuringFont (const wxFont &font)
void SetNormalFont (const wxFont &font)
bool SetPageBitmap (size_t page, const wxBitmap &bitmap)
virtual bool SetPageImage (size_t n, int imageId)
bool SetPageText (size_t page, const wxString &text)
bool SetPageToolTip (size_t page, const wxString &text)
void SetSelectedFont (const wxFont &font)
size_t SetSelection (size_t new_page)
virtual void SetTabCtrlHeight (int height)
bool ShowWindowMenu ()
virtual void SetUniformBitmapSize (const wxSize &size)
virtual void Split (size_t page, int direction)
wxBookCtrlBase ()
wxBookCtrlBase (wxWindow *parent, wxWindowID winid, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name=wxEmptyString)
bool Create (wxWindow *parent, wxWindowID winid, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name=wxEmptyString)
virtual void SetPageSize (const wxSize &size)
virtual int HitTest (const wxPoint &pt, long *flags=NULL) const
virtual int GetPageImage (size_t nPage) const=0
wxWindow * GetCurrentPage () const
void AdvanceSelection (bool forward=true)
int FindPage (const wxWindow *page) const
wxWindow * GetPage (size_t page) const
wxWithImages ()
virtual ~wxWithImages ()
void AssignImageList (wxImageList *imageList)
virtual void SetImageList (wxImageList *imageList)
wxImageList * GetImageList () const
Private Types
typedef int(* CompareFunction) (Page **, Page **)
Private Member Functions
void ReorderTabs (CompareFunction cmp_f)
WX_DEFINE_ARRAY (Page *, wxArrayOfPage)
void Toggle (size_t index)
void Hide (size_t i)
void OnMenu (wxCommandEvent &event)
void OnCopy (wxCommandEvent &event)
void OnWrapMode (wxCommandEvent &event)
void OnClear (wxCommandEvent &event)
void ContextMenu (wxContextMenuEvent &event)
void OnTabContextMenu (wxAuiNotebookEvent &event)
void OnCloseClicked (wxAuiNotebookEvent &event)
void OnTabPosition (wxCommandEvent &event)
void DoShowContextMenu ()
int AddPagePrivate (wxWindow *p, const wxString &title, wxBitmap *icon=nullptr)
bool InsertPagePrivate (wxWindow *p, const wxString &title, wxBitmap *icon=nullptr, int index=-1)
Static Private Member Functions
static int CompareIndexes (Page **p1, Page **p2)
Private Attributes
wxBitmap m_DefaultBitmap
wxArrayOfPage m_Pages
Additional Inherited Members
Static Public Member Functions inherited from cbAuiNotebook
static void UseToolTips (bool use=true)
Enable or disable tabtooltips globally.
static void AllowScrolling (bool allow=true)
Enable or disable tab-scrolling with mousewheel.
static void SetModKeys (wxString keys=_T("Strg"))
Sets the modifier keys for scrolling.
static void UseModToAdvance (bool use=false)
Use modkey to advance through tabs with mousewheel.
static void InvertAdvanceDirection (bool invert=false)
Change direction of tab-advancing with mousewheel.
static void InvertMoveDirection (bool invert=false)
Change direction of tab-moving with mousewheel.
Protected Member Functions inherited from cbAuiNotebook
wxString UniqueIdFromTooltip (const wxString &text)
Create a unique id from the tooltip-text.
void MinimizeFreeSpace (wxAuiTabCtrl *tabCtrl)
Minmize free horizontal page of tabCtrl.
void OnNavigationKeyNotebook (wxNavigationKeyEvent &event)
Handle the navigation key event.
void OnIdle (cb_unused wxIdleEvent &event)
OnIdle.
void OnTabCtrlDblClick (wxMouseEvent &event)
Catch doubleclick-events from wxTabCtrl.
void OnTabCtrlMouseWheel (wxMouseEvent &event)
Catch mousewheel-events from wxTabCtrl.
void OnResize (wxSizeEvent &event)
Catch resize-events and call MinimizeFreeSpace()
void OnDragDone (wxAuiNotebookEvent &event)
Catch dragdone-events from wxTabCtrl.
void OnEnterTabCtrl (wxMouseEvent &event)
Catch mouseenter-events from wxTabCtrl.
void OnLeaveTabCtrl (wxMouseEvent &event)
Catch mouseleave-events from wxTabCtrl.
bool IsFocusStored (wxWindow *page)
Checks the old focus.
void StoreFocus ()
Save old focus.
void RestoreFocus ()
Restore old focus.
void ResetTabCtrlEvents ()
Reset tabctrl events.
void UpdateTabControlsArray ()
Updates the array, that holds the wxTabCtrls.
bool CheckKeyModifier ()
Check for pressed modifier-keys.
Protected Member Functions inherited from wxAuiNotebook
bool HasImageList () const
wxIcon GetImage (int iconIndex) const
Protected Attributes inherited from cbAuiNotebook
cbAuiTabCtrlArray m_TabCtrls
Holds the wxTabCtrls used by the notebook.
int m_LastSelected
Last selected tab.
long m_LastId
Id of last focused window.
bool m_SetZoomOnIdle
If true, zoom for all editors is set in next OnIdle-call.
bool m_MinimizeFreeSpaceOnIdle
If true, MinimizeFreeSpace is called in next OnIdle-call.
wxSize m_TabCtrlSize
Holds the size of a tabCtrl after a resize event.
Static Protected Attributes inherited from cbAuiNotebook
static bool s_UseTabTooltips
Enable or disable tab tooltips.
static bool s_AllowMousewheel = true
Enable or disable scrolling tabs with mousewheel.
static cbAuiNotebookArray s_cbAuiNotebookArray
Holds an array of all existing cbAuiNotebooks.
static wxString s_modKeys = _T("Ctrl")
Holds the modifier keys for scrolling.
static bool s_modToAdvance = false
Use modkey to advance through tabs with mousewheel.
static int s_moveDirection = 1
Mousewheel move direction: negative => invert.
static int s_advanceDirection = 1
Mouseweheel advance direction: negative => invert.
Detailed Description
Definition at line 25 of file infopane.h.
Member Typedef Documentation
CompareFunction
typedef int(* InfoPane::CompareFunction) (Page **, Page **) private
Definition at line 41 of file infopane.h.
Constructor & Destructor Documentation
InfoPane()
InfoPane::InfoPane (wxWindow * parent)
Definition at line 56 of file infopane.cpp.
References _T, cbLoadBitmap(), ConfigManager::GetDataFolder(), and wxBITMAP_TYPE_PNG.
~InfoPane()
InfoPane::~InfoPane () virtual
Definition at line 61 of file infopane.cpp.
Member Function Documentation
AddLogger()
bool InfoPane::AddLogger (Logger * logger, wxWindow * p, const wxString & title, wxBitmap * icon = nullptr)
Definition at line 443 of file infopane.cpp.
References AddPagePrivate(), InfoPane::Page::eventID, InfoPane::Page::icon, InfoPane::Page::indexInNB, InfoPane::Page::islogger, InfoPane::Page::logger, m_Pages, InfoPane::Page::title, InfoPane::Page::window, and wxNewId().
AddNonLogger()
bool InfoPane::AddNonLogger (wxWindow * p, const wxString & title, wxBitmap * icon = nullptr)
Definition at line 463 of file infopane.cpp.
References AddPagePrivate(), InfoPane::Page::eventID, InfoPane::Page::icon, InfoPane::Page::indexInNB, InfoPane::Page::islogger, m_Pages, InfoPane::Page::title, InfoPane::Page::window, and wxNewId().
AddPagePrivate()
int InfoPane::AddPagePrivate (wxWindow * p, const wxString & title, wxBitmap * icon = nullptr) private
Definition at line 147 of file infopane.cpp.
References cbAuiNotebook::AddPage(), wxAuiNotebook::GetPageCount(), and m_DefaultBitmap.
Referenced by AddLogger(), AddNonLogger(), ReorderTabs(), and Toggle().
CompareIndexes()
int InfoPane::CompareIndexes (Page ** p1, Page ** p2) static private
Definition at line 111 of file infopane.cpp.
Referenced by DoShowContextMenu(), LoadTabOrder(), and SaveTabOrder().
ContextMenu()
void InfoPane::ContextMenu (wxContextMenuEvent & event) private
Definition at line 338 of file infopane.cpp.
References DoShowContextMenu().
DeleteLogger()
bool InfoPane::DeleteLogger (Logger * l)
Definition at line 485 of file infopane.cpp.
References LogManager::DeleteLog(), cbAuiNotebook::DeletePage(), LogManager::FindIndex(), Manager::Get(), Manager::GetLogManager(), wxAuiNotebook::GetPageIndex(), and m_Pages.
DeleteNonLogger()
bool InfoPane::DeleteNonLogger (wxWindow * p)
Definition at line 528 of file infopane.cpp.
References _T, cbThrow, cbAuiNotebook::DeletePage(), wxAuiNotebook::GetPageIndex(), and m_Pages.
DoShowContextMenu()
void InfoPane::DoShowContextMenu () private
Definition at line 363 of file infopane.cpp.
References _(), _T, Logger::Feature::Additional, wxMenu::Append(), Logger::AppendAdditionalMenuItems(), wxMenu::AppendCheckItem(), wxMenu::AppendSeparator(), wxMenu::AppendSubMenu(), Logger::Feature::CanClear, Logger::Feature::CanCopy, wxMenu::Check(), CompareIndexes(), Manager::Get(), wxMenu::GetMenuItemCount(), wxAuiNotebook::GetPage(), wxAuiNotebook::GetPageCount(), GetPageIndexByWindow(), wxAuiNotebook::GetSelection(), Logger::GetWrapMode(), Logger::HasFeature(), Logger::Feature::IsWrappable, m_Pages, UpdateEffectiveTabOrder(), wxEmptyString, and wxITEM_CHECK.
Referenced by ContextMenu(), and OnTabContextMenu().
GetCurrentPage()
int InfoPane::GetCurrentPage (bool & is_logger)
Definition at line 204 of file infopane.cpp.
References wxAuiNotebook::GetPage(), GetPageIndexByWindow(), wxAuiNotebook::GetSelection(), and m_Pages.
GetLogger()
Logger * InfoPane::GetLogger (int index)
Definition at line 211 of file infopane.cpp.
References m_Pages, and NULL.
GetPageIndexByWindow()
int InfoPane::GetPageIndexByWindow (wxWindow * win)
Definition at line 194 of file infopane.cpp.
References m_Pages.
Referenced by DoShowContextMenu(), GetCurrentPage(), OnClear(), OnCloseClicked(), OnCopy(), and OnWrapMode().
GetWindow()
wxWindow * InfoPane::GetWindow (int index)
Definition at line 218 of file infopane.cpp.
References m_Pages, and NULL.
Hide() [1/2]
void InfoPane::Hide (size_t i) private
Hide() [2/2]
void InfoPane::Hide (Logger * logger)
Definition at line 236 of file infopane.cpp.
References m_Pages, and Toggle().
HideNonLogger()
void InfoPane::HideNonLogger (wxWindow * p)
Definition at line 264 of file infopane.cpp.
References m_Pages, and Toggle().
InsertPagePrivate()
bool InfoPane::InsertPagePrivate (wxWindow * p, const wxString & title, wxBitmap * icon = nullptr, int index = -1) private
Definition at line 155 of file infopane.cpp.
References cbAuiNotebook::InsertPage(), and m_DefaultBitmap.
Referenced by Toggle().
LoadTabOrder()
void InfoPane::LoadTabOrder (wxString layout)
Definition at line 83 of file infopane.cpp.
References _T, wxString::AfterFirst(), wxString::AfterLast(), wxString::BeforeFirst(), CompareIndexes(), wxString::Find(), wxStringTokenizer::GetNextToken(), wxStringTokenizer::HasMoreTokens(), m_Pages, wxString::Remove(), ReorderTabs(), wxAuiNotebook::SetSelection(), and wxString::ToLong().
OnClear()
void InfoPane::OnClear (wxCommandEvent & event) private
Definition at line 315 of file infopane.cpp.
References wxAuiNotebook::GetPage(), GetPageIndexByWindow(), wxAuiNotebook::GetSelection(), and m_Pages.
OnCloseClicked()
void InfoPane::OnCloseClicked (wxAuiNotebookEvent & event) private
Definition at line 352 of file infopane.cpp.
References wxAuiNotebook::GetPage(), GetPageIndexByWindow(), wxAuiNotebookEvent::GetSelection(), and Toggle().
OnCopy()
void InfoPane::OnCopy (wxCommandEvent & event) private
Definition at line 293 of file infopane.cpp.
References wxAuiNotebook::GetPage(), GetPageIndexByWindow(), wxAuiNotebook::GetSelection(), and m_Pages.
OnMenu()
void InfoPane::OnMenu (wxCommandEvent & event) private
Definition at line 322 of file infopane.cpp.
References m_Pages, and Toggle().
OnTabContextMenu()
void InfoPane::OnTabContextMenu (wxAuiNotebookEvent & event) private
Definition at line 343 of file infopane.cpp.
References DoShowContextMenu(), wxAuiNotebookEvent::GetSelection(), and wxAuiNotebook::SetSelection().
OnTabPosition()
void InfoPane::OnTabPosition (wxCommandEvent & event) private
Definition at line 430 of file infopane.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
OnWrapMode()
void InfoPane::OnWrapMode (wxCommandEvent & event) private
Definition at line 305 of file infopane.cpp.
References wxAuiNotebook::GetPage(), GetPageIndexByWindow(), wxAuiNotebook::GetSelection(), Logger::Feature::IsWrappable, m_Pages, and TextCtrlLogger::ToggleWrapMode().
RemoveNonLogger()
bool InfoPane::RemoveNonLogger (wxWindow * p)
Definition at line 510 of file infopane.cpp.
References _T, cbThrow, wxAuiNotebook::GetPageIndex(), m_Pages, and cbAuiNotebook::RemovePage().
ReorderTabs()
void InfoPane::ReorderTabs (CompareFunction cmp_f) private
Definition at line 118 of file infopane.cpp.
References AddPagePrivate(), wxAuiNotebook::GetPageIndex(), m_Pages, cbAuiNotebook::MovePage(), and cbAuiNotebook::RemovePage().
Referenced by LoadTabOrder().
SaveTabOrder()
wxString InfoPane::SaveTabOrder ()
Definition at line 65 of file infopane.cpp.
References _T, CompareIndexes(), wxAuiNotebook::GetSelection(), m_Pages, and UpdateEffectiveTabOrder().
Show() [1/2]
void InfoPane::Show (size_t index)
Definition at line 225 of file infopane.cpp.
References wxAuiNotebook::GetPageIndex(), m_Pages, wxAuiNotebook::SetSelection(), and Toggle().
Show() [2/2]
void InfoPane::Show (Logger * logger)
Definition at line 249 of file infopane.cpp.
References wxAuiNotebook::GetPageIndex(), m_Pages, wxAuiNotebook::SetSelection(), and Toggle().
ShowNonLogger()
void InfoPane::ShowNonLogger (wxWindow * p)
Definition at line 277 of file infopane.cpp.
References wxAuiNotebook::GetPageIndex(), m_Pages, wxAuiNotebook::SetSelection(), and Toggle().
Toggle()
void InfoPane::Toggle (size_t index) private
Definition at line 173 of file infopane.cpp.
References AddPagePrivate(), wxAuiNotebook::GetPageIndex(), InsertPagePrivate(), m_Pages, cbAuiNotebook::RemovePage(), and UpdateEffectiveTabOrder().
Referenced by Hide(), HideNonLogger(), OnCloseClicked(), OnMenu(), Show(), and ShowNonLogger().
UpdateEffectiveTabOrder()
void InfoPane::UpdateEffectiveTabOrder ()
Definition at line 162 of file infopane.cpp.
References wxAuiNotebook::GetPageIndex(), cbAuiNotebook::GetTabPositionFromIndex(), and m_Pages.
Referenced by DoShowContextMenu(), SaveTabOrder(), and Toggle().
WX_DEFINE_ARRAY()
InfoPane::WX_DEFINE_ARRAY (Page * , wxArrayOfPage) private
Member Data Documentation
m_DefaultBitmap
wxBitmap InfoPane::m_DefaultBitmap private
Definition at line 45 of file infopane.h.
Referenced by AddPagePrivate(), and InsertPagePrivate().
m_Pages
wxArrayOfPage InfoPane::m_Pages private
Definition at line 48 of file infopane.h.
Referenced by AddLogger(), AddNonLogger(), DeleteLogger(), DeleteNonLogger(), DoShowContextMenu(), GetCurrentPage(), GetLogger(), GetPageIndexByWindow(), GetWindow(), Hide(), HideNonLogger(), LoadTabOrder(), OnClear(), OnCopy(), OnMenu(), OnWrapMode(), RemoveNonLogger(), ReorderTabs(), SaveTabOrder(), Show(), ShowNonLogger(), Toggle(), and UpdateEffectiveTabOrder().
The documentation for this class was generated from the following files:
infopane.h
infopane.cpp