Code::Blocks: PrintDialog Class Reference
PrintDialog Class Reference
#include <printdlg.h>
Public Member Functions
PrintDialog (wxWindow *parent)
virtual ~PrintDialog ()
virtual void EndModal (int retCode)
PrintScope GetPrintScope () const
PrintColourMode GetPrintColourMode () const
bool GetPrintLineNumbers () const
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Detailed Description
Definition at line 12 of file printdlg.h.
Constructor & Destructor Documentation
PrintDialog()
PrintDialog::PrintDialog (wxWindow * parent)
Definition at line 27 of file printdlg.cpp.
References _T, wxXmlResource::Get(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetConfigManager(), cbEditor::GetControl(), Manager::GetEditorManager(), wxScintilla::GetSelectedText(), wxString::Length(), wxXmlResource::LoadObject(), ConfigManager::ReadBool(), and ConfigManager::ReadInt().
~PrintDialog()
PrintDialog::~PrintDialog () virtual
Definition at line 48 of file printdlg.cpp.
Member Function Documentation
EndModal()
void PrintDialog::EndModal (int retCode) virtual
Definition at line 68 of file printdlg.cpp.
References _T, ScriptBindings::EndModal(), Manager::Get(), Manager::GetConfigManager(), GetPrintLineNumbers(), ConfigManager::Write(), and wxID_OK.
GetPrintColourMode()
PrintColourMode PrintDialog::GetPrintColourMode () const
Definition at line 58 of file printdlg.cpp.
Referenced by MainFrame::OnFilePrint().
GetPrintLineNumbers()
bool PrintDialog::GetPrintLineNumbers () const
Definition at line 63 of file printdlg.cpp.
Referenced by EndModal(), and MainFrame::OnFilePrint().
GetPrintScope()
PrintScope PrintDialog::GetPrintScope () const
Definition at line 53 of file printdlg.cpp.
Referenced by MainFrame::OnFilePrint().
The documentation for this class was generated from the following files:
printdlg.h
printdlg.cpp