Code::Blocks: wxIccDirTraverser Class Reference
wxIccDirTraverser Class Reference
Public Member Functions
wxIccDirTraverser (wxArrayString &folders)
virtual wxDirTraverseResult OnFile (const wxString &WXUNUSED(filename))
virtual wxDirTraverseResult OnDir (const wxString &dirname)
Public Member Functions inherited from wxDirTraverser
virtual wxDirTraverseResult OnFile (const wxString &filename)=0
virtual wxDirTraverseResult OnOpenError (const wxString &openerrorname)
Private Attributes
wxArrayString & m_Dirs
wxChar m_SepChar
Detailed Description
Definition at line 27 of file compilerICC.cpp.
Constructor & Destructor Documentation
wxIccDirTraverser()
wxIccDirTraverser::wxIccDirTraverser (wxArrayString & folders) inline
Definition at line 30 of file compilerICC.cpp.
References _T, and m_SepChar.
Member Function Documentation
OnDir()
virtual wxDirTraverseResult wxIccDirTraverser::OnDir (const wxString & dirname) inline virtual
Implements wxDirTraverser.
Definition at line 40 of file compilerICC.cpp.
References _T, wxArrayString::Add(), wxString::AfterLast(), wxString::Contains(), wxArrayString::Index(), m_Dirs, m_SepChar, wxDIR_CONTINUE, and wxNOT_FOUND.
OnFile()
virtual wxDirTraverseResult wxIccDirTraverser::OnFile (const wxString & WXUNUSEDfilename) inline virtual
Definition at line 35 of file compilerICC.cpp.
References wxDIR_CONTINUE.
Member Data Documentation
m_Dirs
wxArrayString& wxIccDirTraverser::m_Dirs private
Definition at line 51 of file compilerICC.cpp.
Referenced by OnDir().
m_SepChar
wxChar wxIccDirTraverser::m_SepChar private
Definition at line 52 of file compilerICC.cpp.
Referenced by OnDir(), and wxIccDirTraverser().
The documentation for this class was generated from the following file:
compilerICC.cpp