Code::Blocks: ExamineMemoryDlg Class Reference
ExamineMemoryDlg Class Reference
#include <examinememorydlg.h>
Public Member Functions
ExamineMemoryDlg (wxWindow *parent)
wxWindow * GetWindow ()
void Begin ()
void End ()
void Clear ()
wxString GetBaseAddress ()
int GetBytes ()
void AddError (const wxString &err)
void AddHexByte (const wxString &addr, const wxString &hexbyte)
void EnableWindow (bool enable)
Public Member Functions inherited from cbExamineMemoryDlg
virtual ~cbExamineMemoryDlg ()
Protected Member Functions
void OnGo (wxCommandEvent &event)
Private Attributes
wxTextCtrl * m_pText
size_t m_ByteCounter
wxChar m_LineText [67]
unsigned long m_LastRowStartingAddress
Detailed Description
Definition at line 14 of file examinememorydlg.h.
Constructor & Destructor Documentation
ExamineMemoryDlg()
ExamineMemoryDlg::ExamineMemoryDlg (wxWindow * parent)
Definition at line 31 of file examinememorydlg.cpp.
References _T, wxXmlResource::Get(), wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, and wxFONTWEIGHT_NORMAL.
Member Function Documentation
AddError()
void ExamineMemoryDlg::AddError (const wxString & err) virtual
Implements cbExamineMemoryDlg.
Definition at line 76 of file examinememorydlg.cpp.
References _T, and m_pText.
Referenced by GetWindow().
AddHexByte()
void ExamineMemoryDlg::AddHexByte (const wxString & addr, const wxString & hexbyte) virtual
Implements cbExamineMemoryDlg.
Definition at line 81 of file examinememorydlg.cpp.
References _T, CHAR_OFFSET, wxString::Format(), HEX_OFFSET, m_ByteCounter, m_LastRowStartingAddress, m_LineText, m_pText, and wxString::ToULong().
Referenced by GetWindow().
Begin()
void ExamineMemoryDlg::Begin () virtual
Implements cbExamineMemoryDlg.
Definition at line 45 of file examinememorydlg.cpp.
References m_pText.
Referenced by GetWindow().
Clear()
void ExamineMemoryDlg::Clear () virtual
Implements cbExamineMemoryDlg.
Definition at line 55 of file examinememorydlg.cpp.
References _T, m_ByteCounter, m_LastRowStartingAddress, m_LineText, and m_pText.
Referenced by GetWindow().
EnableWindow()
void ExamineMemoryDlg::EnableWindow (bool enable) virtual
Implements cbExamineMemoryDlg.
Definition at line 135 of file examinememorydlg.cpp.
Referenced by GetWindow().
End()
void ExamineMemoryDlg::End () virtual
Implements cbExamineMemoryDlg.
Definition at line 50 of file examinememorydlg.cpp.
References m_pText.
Referenced by GetWindow().
GetBaseAddress()
wxString ExamineMemoryDlg::GetBaseAddress () virtual
Implements cbExamineMemoryDlg.
Definition at line 64 of file examinememorydlg.cpp.
Referenced by GetWindow().
GetBytes()
int ExamineMemoryDlg::GetBytes () virtual
Implements cbExamineMemoryDlg.
Definition at line 69 of file examinememorydlg.cpp.
Referenced by GetWindow().
GetWindow()
wxWindow* ExamineMemoryDlg::GetWindow () inline virtual
Implements cbExamineMemoryDlg.
Definition at line 19 of file examinememorydlg.h.
References AddError(), AddHexByte(), Begin(), Clear(), EnableWindow(), End(), GetBaseAddress(), GetBytes(), and OnGo().
OnGo()
void ExamineMemoryDlg::OnGo (wxCommandEvent & event) protected
Definition at line 128 of file examinememorydlg.cpp.
References cbDebuggerPlugin::ExamineMemory, Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), and cbDebuggerPlugin::RequestUpdate().
Referenced by GetWindow().
Member Data Documentation
m_ByteCounter
size_t ExamineMemoryDlg::m_ByteCounter private
Definition at line 36 of file examinememorydlg.h.
Referenced by AddHexByte(), and Clear().
m_LastRowStartingAddress
unsigned long ExamineMemoryDlg::m_LastRowStartingAddress private
Definition at line 38 of file examinememorydlg.h.
Referenced by AddHexByte(), and Clear().
m_LineText
wxChar ExamineMemoryDlg::m_LineText[67] private
Definition at line 37 of file examinememorydlg.h.
Referenced by AddHexByte(), and Clear().
m_pText
wxTextCtrl* ExamineMemoryDlg::m_pText private
Definition at line 35 of file examinememorydlg.h.
Referenced by AddError(), AddHexByte(), Begin(), Clear(), and End().
The documentation for this class was generated from the following files:
examinememorydlg.h
examinememorydlg.cpp