Code::Blocks: BlockAllocator< T, pool_size, debug > Class Template Reference
BlockAllocator< T, pool_size, debug > Class Template Reference
#include <blockallocated.h>
Classes
union LinkedBlock
Public Member Functions
BlockAllocator ()
~BlockAllocator ()
void * New ()
void Delete (void *ptr)
Private Member Functions
void AllocBlockPushBack ()
void PushFront (LinkedBlock< T > *p)
Private Attributes
std::vector< LinkedBlock< T > * > allocBlocks
LinkedBlock< T > * first
int ref_count
int max_refs
int total_refs
Class Documentation
union BlockAllocator::LinkedBlock
template<class T, unsigned int pool_size, const bool debug>
template<class U>
union BlockAllocator< T, pool_size, debug >::LinkedBlock< U >
Class Members
char data[sizeof(U)]
LinkedBlock< U > * next
Constructor & Destructor Documentation
template<class T, unsigned int pool_size, const bool debug> BlockAllocator< T, pool_size, debug >::BlockAllocator () inline
template<class T, unsigned int pool_size, const bool debug> BlockAllocator< T, pool_size, debug >::~BlockAllocator () inline
References cbC2U(), BlkAllc::DebugLog(), BlkAllc::enable_global_debug, BlockAllocator< T, pool_size, debug >::max_refs, BlockAllocator< T, pool_size, debug >::ref_count, BlockAllocator< T, pool_size, debug >::total_refs, and BlkAllc::verbose.
Member Function Documentation
template<class T, unsigned int pool_size, const bool debug> void BlockAllocator< T, pool_size, debug >::AllocBlockPushBack () inline private
References BlockAllocator< T, pool_size, debug >::LinkedBlock< U >::next, and ParserConsts::ptr().
Referenced by BlockAllocator< T, pool_size, debug >::New().
template<class T, unsigned int pool_size, const bool debug> void BlockAllocator< T, pool_size, debug >::Delete (void * ptr) inline
References BlkAllc::enable_global_debug, BlockAllocator< T, pool_size, debug >::PushFront(), and BlockAllocator< T, pool_size, debug >::ref_count.
Referenced by BlockAllocated< T, pool_size, debug >::operator delete().
template<class T, unsigned int pool_size, const bool debug> void* BlockAllocator< T, pool_size, debug >::New () inline
References BlockAllocator< T, pool_size, debug >::AllocBlockPushBack(), BlkAllc::enable_global_debug, BlockAllocator< T, pool_size, debug >::first, BlockAllocator< T, pool_size, debug >::max_refs, BlockAllocator< T, pool_size, debug >::LinkedBlock< U >::next, BlockAllocator< T, pool_size, debug >::ref_count, and BlockAllocator< T, pool_size, debug >::total_refs.
Referenced by BlockAllocated< T, pool_size, debug >::operator new().
template<class T, unsigned int pool_size, const bool debug> void BlockAllocator< T, pool_size, debug >::PushFront (LinkedBlock< T > * p) inline private
References BlockAllocator< T, pool_size, debug >::first, and BlockAllocator< T, pool_size, debug >::LinkedBlock< U >::next.
Referenced by BlockAllocator< T, pool_size, debug >::Delete().
Member Data Documentation
template<class T, unsigned int pool_size, const bool debug> std::vector<LinkedBlock<T>*> BlockAllocator< T, pool_size, debug >::allocBlocks private
template<class T, unsigned int pool_size, const bool debug> LinkedBlock<T>* BlockAllocator< T, pool_size, debug >::first private
Referenced by BlockAllocator< T, pool_size, debug >::New(), and BlockAllocator< T, pool_size, debug >::PushFront().
template<class T, unsigned int pool_size, const bool debug> int BlockAllocator< T, pool_size, debug >::max_refs private
Referenced by BlockAllocator< T, pool_size, debug >::New(), and BlockAllocator< T, pool_size, debug >::~BlockAllocator().
template<class T, unsigned int pool_size, const bool debug> int BlockAllocator< T, pool_size, debug >::ref_count private
Referenced by BlockAllocator< T, pool_size, debug >::Delete(), BlockAllocator< T, pool_size, debug >::New(), and BlockAllocator< T, pool_size, debug >::~BlockAllocator().
template<class T, unsigned int pool_size, const bool debug> int BlockAllocator< T, pool_size, debug >::total_refs private
Referenced by BlockAllocator< T, pool_size, debug >::New(), and BlockAllocator< T, pool_size, debug >::~BlockAllocator().
The documentation for this class was generated from the following file:
blockallocated.h