Code::Blocks: AnnoyingDialog Class Reference
AnnoyingDialog Class Reference
Dialog that contains a "Don't annoy me" checkbox.
#include <annoyingdialog.h>
Public Types
enum dStyle {
OK, YES_NO, YES_NO_CANCEL, OK_CANCEL,
ONE_BUTTON, TWO_BUTTONS, THREE_BUTTONS
}
enum dReturnType {
rtINVALID = -1, rtSAVE_CHOICE, rtONE, rtTWO,
rtTHREE, rtYES, rtNO, rtOK,
rtCANCEL
}
Public Member Functions
AnnoyingDialog (const wxString &caption, const wxString &message, const wxArtID icon=wxART_INFORMATION, dStyle style=YES_NO, dReturnType defaultReturn=rtYES, const wxString &b1=wxEmptyString, const wxString &b2=wxEmptyString, const wxString &b3=wxEmptyString)
AnnoyingDialog (const wxString &caption, const wxString &id, const wxString &message, const wxArtID icon, dStyle style, dReturnType defaultReturn, const wxString &b1=wxEmptyString, const wxString &b2=wxEmptyString, const wxString &b3=wxEmptyString)
virtual ~AnnoyingDialog ()
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void Init (const wxString &caption, const wxString &id, const wxString &message, const wxArtID icon, dStyle style, const wxString &b1, const wxString &b2, const wxString &b3)
void OnButton (wxCommandEvent &event)
Private Attributes
wxString m_Id
wxCheckBox * m_CheckBox
dReturnType m_DefRet
bool m_DontAnnoy
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Dialog that contains a "Don't annoy me" checkbox.
Using this dialog, the user can select not to display this dialog again. The dialog can be then re-enabled in "Settings->Environment->Dialogs"...
Definition at line 22 of file annoyingdialog.h.
Member Enumeration Documentation
dReturnType
enum AnnoyingDialog::dReturnType
Enumerator
rtINVALID
rtSAVE_CHOICE
rtONE
rtTWO
rtTHREE
rtYES
rtNO
rtOK
rtCANCEL
Definition at line 36 of file annoyingdialog.h.
dStyle
enum AnnoyingDialog::dStyle
Enumerator
OK
YES_NO
YES_NO_CANCEL
OK_CANCEL
ONE_BUTTON
TWO_BUTTONS
THREE_BUTTONS
Definition at line 25 of file annoyingdialog.h.
Constructor & Destructor Documentation
AnnoyingDialog() [1/2]
AnnoyingDialog::AnnoyingDialog (const wxString & caption, const wxString & message, const wxArtID icon = wxART_INFORMATION, dStyle style = YES_NO, dReturnType defaultReturn = rtYES, const wxString & b1 = wxEmptyString, const wxString & b2 = wxEmptyString, const wxString & b3 = wxEmptyString)
Definition at line 30 of file annoyingdialog.cpp.
AnnoyingDialog() [2/2]
AnnoyingDialog::AnnoyingDialog (const wxString & caption, const wxString & id, const wxString & message, const wxArtID icon, dStyle style, dReturnType defaultReturn, const wxString & b1 = wxEmptyString, const wxString & b2 = wxEmptyString, const wxString & b3 = wxEmptyString)
Definition at line 39 of file annoyingdialog.cpp.
References wxScrollingDialog::Init().
~AnnoyingDialog()
virtual AnnoyingDialog::~AnnoyingDialog () inline virtual
Definition at line 55 of file annoyingdialog.h.
References HTMLTags::b1, wxScrollingDialog::Init(), and wxScrollingDialog::ShowModal().
Member Function Documentation
Init()
void AnnoyingDialog::Init (const wxString & caption, const wxString & id, const wxString & message, const wxArtID icon, dStyle style, const wxString & b1, const wxString & b2, const wxString & b3) private
Definition at line 48 of file annoyingdialog.cpp.
References HTMLTags::b1, cbThrow, ConfigManager::Exists(), F(), Manager::Get(), Manager::GetConfigManager(), Manager::GetLogManager(), LogManager::Log(), m_CheckBox, m_DefRet, m_DontAnnoy, m_Id, OK, OK_CANCEL, ONE_BUTTON, ConfigManager::ReadSSet(), rtCANCEL, rtINVALID, rtNO, rtOK, rtONE, rtSAVE_CHOICE, rtTHREE, rtTWO, rtYES, THREE_BUTTONS, TWO_BUTTONS, ConfigManager::Write(), YES_NO, and YES_NO_CANCEL.
OnButton()
void AnnoyingDialog::OnButton (wxCommandEvent & event) private
Definition at line 225 of file annoyingdialog.cpp.
References cbThrow, ScriptBindings::EndModal(), F(), Manager::Get(), Manager::GetConfigManager(), m_CheckBox, m_DefRet, m_Id, ConfigManager::ReadSSet(), rtCANCEL, rtNO, rtOK, rtSAVE_CHOICE, rtYES, and ConfigManager::Write().
ShowModal()
int AnnoyingDialog::ShowModal () virtual
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Reimplemented from wxScrollingDialog.
Definition at line 261 of file annoyingdialog.cpp.
References m_DefRet, m_DontAnnoy, PlaceWindow(), and wxScrollingDialog::ShowModal().
Referenced by RecentItemsList::AskToRemoveFileFromHistory(), DebuggerGDB::CheckIfConsoleIsClosed(), UsrGlblMgrEditDialog::DeleteSet(), UsrGlblMgrEditDialog::DeleteVar(), MainFrame::DoCheckCurrentLayoutForChanges(), WorkspaceLoader::LoadLayout(), CompilerOptionsDlg::OnAdvancedClick(), CompilerGCC::OnClean(), CompilerGCC::OnCleanAll(), cbDebuggerPlugin::OnCompilerFinished(), ProjectOptionsDlg::OnExportTargetClick(), CompilerOptionsDlg::OnOptionChanged(), cbDebuggerPlugin::OnProjectClosed(), CompilerGCC::OnRebuild(), CompilerGCC::OnRebuildAll(), CompilerOptionsDlg::OnTreeSelectionChanging(), ProjectLayoutLoader::Open(), ProjectLoader::Open(), CompilerOptionsDlg::OptionsToText(), QuoteString(), and FindReplace::ReplaceInFiles().
Member Data Documentation
m_CheckBox
wxCheckBox* AnnoyingDialog::m_CheckBox private
Definition at line 63 of file annoyingdialog.h.
Referenced by Init(), and OnButton().
m_DefRet
dReturnType AnnoyingDialog::m_DefRet private
Definition at line 64 of file annoyingdialog.h.
Referenced by Init(), OnButton(), and ShowModal().
m_DontAnnoy
bool AnnoyingDialog::m_DontAnnoy private
Definition at line 65 of file annoyingdialog.h.
Referenced by Init(), and ShowModal().
m_Id
wxString AnnoyingDialog::m_Id private
Definition at line 62 of file annoyingdialog.h.
Referenced by Init(), and OnButton().
The documentation for this class was generated from the following files:
annoyingdialog.h
annoyingdialog.cpp