Code::Blocks: WatchesProperty Class Reference
WatchesProperty Class Reference
Public Member Functions
WatchesProperty (const wxString &label, const wxString &value, cb::shared_ptr< cbWatch > watch, bool readonly)
virtual const wxPGEditor * DoGetEditorClass () const
virtual wxPGEditorDialogAdapter * GetEditorDialog () const
cb::shared_ptr< cbWatch > GetWatch ()
cb::shared_ptr< const cbWatch > GetWatch () const
void SetWatch (cb::shared_ptr< cbWatch > watch)
Protected Attributes
cb::shared_ptr< cbWatch > m_watch
bool m_readonly
Private Member Functions
WatchesProperty ()
Detailed Description
Definition at line 147 of file watchesdlg.cpp.
Constructor & Destructor Documentation
WatchesProperty() [1/2]
WatchesProperty::WatchesProperty () inline private
Definition at line 151 of file watchesdlg.cpp.
WatchesProperty() [2/2]
WatchesProperty::WatchesProperty (const wxString & label, const wxString & value, cb::shared_ptr< cbWatch > watch, bool readonly) inline
Definition at line 153 of file watchesdlg.cpp.
Member Function Documentation
DoGetEditorClass()
virtual const wxPGEditor* WatchesProperty::DoGetEditorClass () const inline virtual
Definition at line 161 of file watchesdlg.cpp.
References watchesDummyEditor, and watchesPropertyEditor.
GetEditorDialog()
wxPGEditorDialogAdapter * WatchesProperty::GetEditorDialog () const virtual
Definition at line 341 of file watchesdlg.cpp.
GetWatch() [1/2]
cb::shared_ptr<cbWatch> WatchesProperty::GetWatch () inline
Definition at line 169 of file watchesdlg.cpp.
References WatchesDlg::WatchItemPredicate::m_watch.
Referenced by WatchRawDialog::Create(), WatchesDlg::DeleteProperty(), WatchRawDialogAdapter::DoShowDialog(), WatchesDlg::OnCollapse(), ValueTooltip::OnCollapse(), WatchesDlg::OnExpand(), ValueTooltip::OnExpand(), WatchesDlg::OnKeyDown(), WatchesDlg::OnMenuAddDataBreak(), WatchesDlg::OnMenuAutoUpdate(), WatchesDlg::OnMenuExamineMemory(), WatchesDlg::OnMenuProperties(), WatchesDlg::OnMenuUpdate(), WatchesDlg::OnPropertyRightClick(), WatchesDlg::RenameWatch(), WatchRawDialog::SetValue(), SetValue(), and WatchRawDialog::UpdateValue().
GetWatch() [2/2]
cb::shared_ptr<const cbWatch> WatchesProperty::GetWatch () const inline
Definition at line 170 of file watchesdlg.cpp.
References WatchesDlg::WatchItemPredicate::m_watch.
SetWatch()
void WatchesProperty::SetWatch (cb::shared_ptr< cbWatch > watch) inline
Definition at line 171 of file watchesdlg.cpp.
References WatchesDlg::WatchItemPredicate::m_watch.
Referenced by WatchesDlg::AddWatch(), and WatchesDlg::RenameWatch().
Member Data Documentation
m_readonly
bool WatchesProperty::m_readonly protected
Definition at line 175 of file watchesdlg.cpp.
m_watch
cb::shared_ptr<cbWatch> WatchesProperty::m_watch protected
Definition at line 174 of file watchesdlg.cpp.
The documentation for this class was generated from the following file:
watchesdlg.cpp