Code::Blocks: RecentItemsList Class Reference
RecentItemsList Class Reference
#include <recentitemslist.h>
Public Member Functions
RecentItemsList (const wxString &menuName, const wxString &configPath, int menuID, int firstMenuItemID)
void AddToHistory (const wxString &FileName)
void AskToRemoveFileFromHistory (size_t id, bool cannot_open=true)
wxString GetHistoryFile (size_t id) const
void ClearHistory ()
void Initialize ()
void TerminateHistory ()
const wxFileHistory * GetFileHistory () const
bool Empty () const
Private Member Functions
void BuildMenu (wxMenu *menu)
void ClearMenu (wxMenu *menu)
wxMenu * GetMenu ()
void RefreshStartHerePage ()
Private Attributes
wxFileHistory * m_list
wxString m_menuName
wxString m_configPath
int m_menuID
int m_firstMenuItemID
Detailed Description
Definition at line 10 of file recentitemslist.h.
Constructor & Destructor Documentation
RecentItemsList()
RecentItemsList::RecentItemsList (const wxString & menuName, const wxString & configPath, int menuID, int firstMenuItemID)
Definition at line 26 of file recentitemslist.cpp.
Member Function Documentation
AddToHistory()
void RecentItemsList::AddToHistory (const wxString & FileName)
Definition at line 35 of file recentitemslist.cpp.
References wxFileHistory::AddFileToHistory(), BuildMenu(), ClearMenu(), wxFileHistory::GetCount(), wxFileHistory::GetHistoryFile(), GetMenu(), wxString::Lower(), m_list, and RefreshStartHerePage().
AskToRemoveFileFromHistory()
void RecentItemsList::AskToRemoveFileFromHistory (size_t id, bool cannot_open = true)
Definition at line 76 of file recentitemslist.cpp.
References _(), _T, BuildMenu(), ClearMenu(), wxFileHistory::GetCount(), GetMenu(), m_list, PlaceWindow(), RefreshStartHerePage(), wxFileHistory::RemoveFileFromHistory(), AnnoyingDialog::rtYES, AnnoyingDialog::ShowModal(), wxART_QUESTION, and wxEmptyString.
Referenced by MainFrame::OnStartHereLink().
BuildMenu()
void RecentItemsList::BuildMenu (wxMenu * menu) private
Definition at line 158 of file recentitemslist.cpp.
References _T, wxString::Format(), wxFileHistory::GetCount(), wxFileHistory::GetHistoryFile(), wxMenu::GetMenuItemCount(), wxMenu::Insert(), wxMenu::InsertSeparator(), m_firstMenuItemID, and m_list.
Referenced by AddToHistory(), AskToRemoveFileFromHistory(), Empty(), and Initialize().
ClearHistory()
void RecentItemsList::ClearHistory ()
Definition at line 106 of file recentitemslist.cpp.
References _T, ConfigManager::DeleteSubPath(), Manager::Get(), Manager::GetConfigManager(), wxFileHistory::GetCount(), Initialize(), m_configPath, m_list, RefreshStartHerePage(), and wxFileHistory::RemoveFileFromHistory().
ClearMenu()
void RecentItemsList::ClearMenu (wxMenu * menu) private
Definition at line 172 of file recentitemslist.cpp.
References wxMenu::Delete(), wxMenu::GetMenuItemCount(), and wxMenu::GetMenuItems().
Referenced by AddToHistory(), AskToRemoveFileFromHistory(), Empty(), and TerminateHistory().
Empty()
bool RecentItemsList::Empty () const inline
Definition at line 25 of file recentitemslist.h.
References BuildMenu(), ClearMenu(), wxFileHistory::GetCount(), GetMenu(), m_list, and RefreshStartHerePage().
GetFileHistory()
const wxFileHistory* RecentItemsList::GetFileHistory () const inline
Definition at line 24 of file recentitemslist.h.
References m_list.
Referenced by StartHerePage::Reload().
GetHistoryFile()
wxString RecentItemsList::GetHistoryFile (size_t id) const
Definition at line 70 of file recentitemslist.cpp.
References wxFileHistory::GetHistoryFile(), m_list, and wxEmptyString.
Referenced by MainFrame::OnStartHereLink().
GetMenu()
wxMenu * RecentItemsList::GetMenu () private
Definition at line 178 of file recentitemslist.cpp.
References wxMenu::FindItem(), wxMenuBar::FindMenu(), Manager::Get(), Manager::GetAppFrame(), wxMenuBar::GetMenu(), m_menuID, m_menuName, and wxNOT_FOUND.
Referenced by AddToHistory(), AskToRemoveFileFromHistory(), Empty(), Initialize(), and TerminateHistory().
Initialize()
void RecentItemsList::Initialize ()
Definition at line 116 of file recentitemslist.cpp.
References _T, wxFileHistory::AddFileToHistory(), BuildMenu(), Manager::Get(), Manager::GetConfigManager(), wxArrayString::GetCount(), GetMenu(), m_configPath, m_firstMenuItemID, m_list, ConfigManager::ReadArrayString(), TerminateHistory(), and wxFileExists().
Referenced by ClearHistory().
RefreshStartHerePage()
void RecentItemsList::RefreshStartHerePage () private
Definition at line 192 of file recentitemslist.cpp.
References g_StartHereTitle, Manager::Get(), EditorManager::GetEditor(), and Manager::GetEditorManager().
Referenced by AddToHistory(), AskToRemoveFileFromHistory(), ClearHistory(), and Empty().
TerminateHistory()
void RecentItemsList::TerminateHistory ()
Definition at line 136 of file recentitemslist.cpp.
References _T, wxArrayString::Add(), ClearMenu(), Manager::Get(), Manager::GetConfigManager(), wxFileHistory::GetCount(), wxFileHistory::GetHistoryFile(), GetMenu(), Manager::IsAppShuttingDown(), m_configPath, m_list, wxFileHistory::RemoveMenu(), and ConfigManager::Write().
Referenced by Initialize().
Member Data Documentation
m_configPath
wxString RecentItemsList::m_configPath private
Definition at line 33 of file recentitemslist.h.
Referenced by ClearHistory(), Initialize(), and TerminateHistory().
m_firstMenuItemID
int RecentItemsList::m_firstMenuItemID private
Definition at line 34 of file recentitemslist.h.
Referenced by BuildMenu(), and Initialize().
m_list
wxFileHistory* RecentItemsList::m_list private
Definition at line 32 of file recentitemslist.h.
Referenced by AddToHistory(), AskToRemoveFileFromHistory(), BuildMenu(), ClearHistory(), Empty(), GetFileHistory(), GetHistoryFile(), Initialize(), and TerminateHistory().
m_menuID
int RecentItemsList::m_menuID private
Definition at line 34 of file recentitemslist.h.
Referenced by GetMenu().
m_menuName
wxString RecentItemsList::m_menuName private
Definition at line 33 of file recentitemslist.h.
Referenced by GetMenu().
The documentation for this class was generated from the following files:
recentitemslist.h
recentitemslist.cpp