Code::Blocks: MyHtmlWin Class Reference
MyHtmlWin Class Reference
Public Member Functions
MyHtmlWin (StartHerePage *parent, int id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxHW_SCROLLBAR_AUTO)
void OnLinkClicked (const wxHtmlLinkInfo &link) override
Private Attributes
StartHerePage * m_pOwner
Detailed Description
Definition at line 41 of file startherepage.cpp.
Constructor & Destructor Documentation
MyHtmlWin()
MyHtmlWin::MyHtmlWin (StartHerePage * parent, int id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxHW_SCROLLBAR_AUTO) inline
Definition at line 44 of file startherepage.cpp.
Member Function Documentation
OnLinkClicked()
void MyHtmlWin::OnLinkClicked (const wxHtmlLinkInfo & link) inline override
Definition at line 50 of file startherepage.cpp.
References wxHtmlLinkInfo::GetHref(), StartHerePage::LinkClicked(), m_pOwner, and wxLaunchDefaultBrowser().
Member Data Documentation
m_pOwner
StartHerePage* MyHtmlWin::m_pOwner private
Definition at line 59 of file startherepage.cpp.
Referenced by OnLinkClicked().
The documentation for this class was generated from the following file:
startherepage.cpp