Code::Blocks: BuildLogger Class Reference
BuildLogger Class Reference
Public Member Functions
BuildLogger ()
void UpdateSettings ()
virtual wxWindow * CreateControl (wxWindow *parent)
void AddBuildProgressBar ()
void RemoveBuildProgressBar ()
void OpenLink (long urlStart, long urlEnd)
Public Member Functions inherited from TextCtrlLogger
TextCtrlLogger (bool fixedPitchFont=false)
~TextCtrlLogger ()
virtual void CopyContentsToClipboard (bool selectionOnly=false)
virtual void Append (const wxString &msg, Logger::level lv=info)
virtual void Clear ()
virtual bool GetWrapMode () const
virtual void ToggleWrapMode ()
virtual bool HasFeature (Feature::Enum feature) const
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Public Attributes
wxGauge * progress
Private Attributes
wxPanel * panel
wxBoxSizer * sizer
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Protected Attributes inherited from TextCtrlLogger
wxTextCtrl * control
bool fixed
wxTextAttr style [num_levels]
Detailed Description
Definition at line 89 of file compilergcc.cpp.
Constructor & Destructor Documentation
BuildLogger()
BuildLogger::BuildLogger () inline
Definition at line 96 of file compilergcc.cpp.
Member Function Documentation
AddBuildProgressBar()
void BuildLogger::AddBuildProgressBar () inline
Definition at line 121 of file compilergcc.cpp.
CreateControl()
virtual wxWindow* BuildLogger::CreateControl (wxWindow * parent) inline virtual
Reimplemented from TextCtrlLogger.
Definition at line 107 of file compilergcc.cpp.
References TextCtrlLogger::CreateControl(), and idBuildLog.
OpenLink()
void BuildLogger::OpenLink (long urlStart, long urlEnd) inline
Definition at line 142 of file compilergcc.cpp.
References Manager::Get(), PluginManager::GetMIMEHandlerForFile(), Manager::GetPluginManager(), and cbMimePlugin::OpenFile().
RemoveBuildProgressBar()
void BuildLogger::RemoveBuildProgressBar () inline
Definition at line 131 of file compilergcc.cpp.
UpdateSettings()
void BuildLogger::UpdateSettings () inline virtual
Reimplemented from TextCtrlLogger.
Definition at line 98 of file compilergcc.cpp.
References TextCtrlLogger::UpdateSettings().
Member Data Documentation
panel
wxPanel* BuildLogger::panel private
Definition at line 91 of file compilergcc.cpp.
progress
wxGauge* BuildLogger::progress
Definition at line 94 of file compilergcc.cpp.
sizer
wxBoxSizer* BuildLogger::sizer private
Definition at line 92 of file compilergcc.cpp.
The documentation for this class was generated from the following file:
compilergcc.cpp