Code::Blocks: ScriptConsole Class Reference
ScriptConsole Class Reference
#include <scriptconsole.h>
Public Member Functions
ScriptConsole (wxWindow *parent, wxWindowID id=-1)
virtual ~ScriptConsole ()
void Log (const wxString &msg)
Static Public Attributes
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_COMBOBOX1 = wxNewId()
static const long ID_BITMAPBUTTON1 = wxNewId()
static const long ID_BITMAPBUTTON2 = wxNewId()
static const long ID_BITMAPBUTTON3 = wxNewId()
static const long ID_PANEL1 = wxNewId()
Protected Member Functions
void OnbtnExecuteClick (wxCommandEvent &event)
void OnbtnLoadClick (wxCommandEvent &event)
void OnbtnClearClick (wxCommandEvent &event)
Protected Attributes
wxPanel * Panel1
wxBitmapButton * btnLoad
wxComboBox * txtCommand
wxBitmapButton * btnExecute
wxBitmapButton * btnClear
wxTextCtrl * txtConsole
wxStaticText * lblCommand
Detailed Description
Definition at line 24 of file scriptconsole.h.
Constructor & Destructor Documentation
ScriptConsole()
ScriptConsole::ScriptConsole (wxWindow * parent, wxWindowID id = -1)
Definition at line 66 of file scriptconsole.cpp.
References _(), _T, wxBoxSizer::Add(), wxBoxSizer::Fit(), wxArtProvider::GetBitmap(), wxSystemSettings::GetColour(), OnbtnClearClick(), OnbtnExecuteClick(), OnbtnLoadClick(), s_OldPrintFunc, ScriptConsolePrintFunc(), wxBoxSizer::SetSizeHints(), sq_getprintfunc(), sq_setprintfunc(), wxALIGN_CENTER_VERTICAL, wxALL, wxART_BUTTON, wxBU_AUTODRAW, wxCB_DROPDOWN, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxFONTENCODING_DEFAULT, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, wxHORIZONTAL, wxHSCROLL, wxSYS_COLOUR_BTNFACE, wxTAB_TRAVERSAL, wxTE_MULTILINE, wxTE_PROCESS_ENTER, wxTE_READONLY, and wxVERTICAL.
~ScriptConsole()
ScriptConsole::~ScriptConsole () virtual
Definition at line 123 of file scriptconsole.cpp.
References s_OldPrintFunc, and sq_setprintfunc().
Member Function Documentation
Log()
void ScriptConsole::Log (const wxString & msg)
Definition at line 136 of file scriptconsole.cpp.
References _T, wxString::Last(), Manager::ProcessPendingEvents(), and txtConsole.
Referenced by OnbtnExecuteClick(), OnbtnLoadClick(), and ScriptConsolePrintFunc().
OnbtnClearClick()
void ScriptConsole::OnbtnClearClick (wxCommandEvent & event) protected
Definition at line 192 of file scriptconsole.cpp.
References txtCommand, and txtConsole.
Referenced by ScriptConsole().
OnbtnExecuteClick()
void ScriptConsole::OnbtnExecuteClick (wxCommandEvent & event) protected
Definition at line 145 of file scriptconsole.cpp.
References _T, Manager::Get(), wxString::IsEmpty(), Log(), wxString::Trim(), txtCommand, txtConsole, wxBell(), wxEmptyString, and wxNOT_FOUND.
Referenced by ScriptConsole().
OnbtnLoadClick()
void ScriptConsole::OnbtnLoadClick (wxCommandEvent & event) protected
Definition at line 168 of file scriptconsole.cpp.
References _(), _T, Manager::Get(), Manager::GetConfigManager(), wxFileDialog::GetDirectory(), wxFileDialog::GetPath(), Manager::GetScriptingManager(), ScriptingManager::LoadScript(), Log(), ConfigManager::Read(), wxFileDialog::ShowModal(), txtCommand, txtConsole, ConfigManager::Write(), wxEmptyString, wxFD_OPEN, and wxID_OK.
Referenced by ScriptConsole().
Member Data Documentation
btnClear
wxBitmapButton* ScriptConsole::btnClear protected
Definition at line 55 of file scriptconsole.h.
btnExecute
wxBitmapButton* ScriptConsole::btnExecute protected
Definition at line 54 of file scriptconsole.h.
btnLoad
wxBitmapButton* ScriptConsole::btnLoad protected
Definition at line 52 of file scriptconsole.h.
ID_BITMAPBUTTON1
const long ScriptConsole::ID_BITMAPBUTTON1 = wxNewId() static
Definition at line 37 of file scriptconsole.h.
ID_BITMAPBUTTON2
const long ScriptConsole::ID_BITMAPBUTTON2 = wxNewId() static
Definition at line 38 of file scriptconsole.h.
ID_BITMAPBUTTON3
const long ScriptConsole::ID_BITMAPBUTTON3 = wxNewId() static
Definition at line 39 of file scriptconsole.h.
ID_COMBOBOX1
const long ScriptConsole::ID_COMBOBOX1 = wxNewId() static
Definition at line 36 of file scriptconsole.h.
ID_PANEL1
const long ScriptConsole::ID_PANEL1 = wxNewId() static
Definition at line 40 of file scriptconsole.h.
ID_STATICTEXT1
const long ScriptConsole::ID_STATICTEXT1 = wxNewId() static
Definition at line 35 of file scriptconsole.h.
ID_TEXTCTRL1
const long ScriptConsole::ID_TEXTCTRL1 = wxNewId() static
Definition at line 34 of file scriptconsole.h.
lblCommand
wxStaticText* ScriptConsole::lblCommand protected
Definition at line 57 of file scriptconsole.h.
Panel1
wxPanel* ScriptConsole::Panel1 protected
Definition at line 51 of file scriptconsole.h.
txtCommand
wxComboBox* ScriptConsole::txtCommand protected
Definition at line 53 of file scriptconsole.h.
Referenced by OnbtnClearClick(), OnbtnExecuteClick(), and OnbtnLoadClick().
txtConsole
wxTextCtrl* ScriptConsole::txtConsole protected
Definition at line 56 of file scriptconsole.h.
Referenced by Log(), OnbtnClearClick(), OnbtnExecuteClick(), and OnbtnLoadClick().
The documentation for this class was generated from the following files:
scriptconsole.h
scriptconsole.cpp