Code::Blocks: WatchesDlg Class Reference
WatchesDlg Class Reference
#include <watchesdlg.h>
Classes
struct WatchItem
struct WatchItemPredicate
Public Member Functions
WatchesDlg ()
wxWindow * GetWindow ()
void UpdateWatches ()
void AddWatch (cb::shared_ptr< cbWatch > watch)
void AddSpecialWatch (cb::shared_ptr< cbWatch > watch, bool readonly)
void RemoveWatch (cb::shared_ptr< cbWatch > watch)
void RenameWatch (wxObject *prop, const wxString &newSymbol)
void RefreshUI ()
Public Member Functions inherited from cbWatchesDlg
virtual ~cbWatchesDlg ()
Private Types
typedef std::vector< WatchItem > WatchItems
Private Member Functions
void OnExpand (wxPropertyGridEvent &event)
void OnCollapse (wxPropertyGridEvent &event)
void OnPropertySelected (wxPropertyGridEvent &event)
void OnPropertyChanged (wxPropertyGridEvent &event)
void OnPropertyChanging (wxPropertyGridEvent &event)
void OnPropertyLableEditBegin (wxPropertyGridEvent &event)
void OnPropertyLableEditEnd (wxPropertyGridEvent &event)
void OnPropertyRightClick (wxPropertyGridEvent &event)
void OnIdle (wxIdleEvent &event)
void OnKeyDown (wxKeyEvent &event)
void OnMenuRename (wxCommandEvent &event)
void OnMenuProperties (wxCommandEvent &event)
void OnMenuDelete (wxCommandEvent &event)
void OnMenuDeleteAll (wxCommandEvent &event)
void OnMenuAddDataBreak (wxCommandEvent &event)
void OnMenuAutoUpdate (wxCommandEvent &event)
void OnMenuUpdate (wxCommandEvent &event)
void DeleteProperty (WatchesProperty &prop)
Private Attributes
wxPropertyGrid * m_grid
WatchItems m_watches
bool m_append_empty_watch
Detailed Description
Definition at line 22 of file watchesdlg.h.
Member Typedef Documentation
WatchItems
typedef std::vector<WatchItem> WatchesDlg::WatchItems private
Definition at line 68 of file watchesdlg.h.
Constructor & Destructor Documentation
WatchesDlg()
WatchesDlg::WatchesDlg ()
Definition at line 360 of file watchesdlg.cpp.
References _(), wxBoxSizer::Add(), wxPropertyGrid::Append(), Manager::Get(), Manager::GetColourManager(), m_grid, OnKeyDown(), ColourManager::RegisterColour(), wxPropertyGrid::RegisterEditorClass(), wxPropertyGrid::SetColumnCount(), wxPropertyGrid::SetColumnProportion(), wxPropertyGrid::SetPropertyAttribute(), watchesDummyEditor, watchesPropertyEditor, wxALL, wxDefaultPosition, wxDefaultSize, wxEmptyString, wxEVT_KEY_DOWN, wxEXPAND, wxPG_EX_DISABLE_TLP_TRACKING, wxPG_EX_HELP_AS_TOOLTIPS, wxPG_SPLITTER_AUTO_CENTER, wxRED, wxT, wxTAB_TRAVERSAL, and wxVERTICAL.
Member Function Documentation
AddSpecialWatch()
void WatchesDlg::AddSpecialWatch (cb::shared_ptr< cbWatch > watch, bool readonly) virtual
Implements cbWatchesDlg.
Definition at line 548 of file watchesdlg.cpp.
References wxPropertyGrid::Insert(), m_grid, m_watches, WatchesDlg::WatchItem::property, WatchesDlg::WatchItem::readonly, WatchesDlg::WatchItem::special, WatchesDlg::WatchItem::watch, and wxPG_ITERATE_ALL.
Referenced by GetWindow().
AddWatch()
void WatchesDlg::AddWatch (cb::shared_ptr< cbWatch > watch) virtual
Implements cbWatchesDlg.
Definition at line 514 of file watchesdlg.cpp.
References wxPropertyGrid::Append(), wxPropertyGrid::EndLabelEdit(), wxPropertyGrid::GetLabelEditor(), wxPropertyGrid::GetLastItem(), m_grid, m_watches, WatchesDlg::WatchItem::property, wxPropertyGrid::SetPropertyLabel(), wxPropertyGrid::SetPropertyName(), WatchesProperty::SetWatch(), WatchesDlg::WatchItem::watch, wxEmptyString, and wxPG_ITERATE_DEFAULT.
Referenced by GetWindow().
DeleteProperty()
void WatchesDlg::DeleteProperty (WatchesProperty & prop) private
Definition at line 659 of file watchesdlg.cpp.
References wxPropertyGrid::DeleteProperty(), cbDebuggerPlugin::DeleteWatch(), Manager::Get(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), WatchesProperty::GetWatch(), wxPGProperty::IsRoot(), m_grid, and m_watches.
Referenced by GetWindow(), OnKeyDown(), OnMenuDelete(), and RemoveWatch().
GetWindow()
wxWindow* WatchesDlg::GetWindow () inline virtual
Implements cbWatchesDlg.
Definition at line 27 of file watchesdlg.h.
References AddSpecialWatch(), AddWatch(), DeleteProperty(), OnCollapse(), OnExpand(), OnIdle(), OnKeyDown(), OnMenuAddDataBreak(), OnMenuAutoUpdate(), OnMenuDelete(), OnMenuDeleteAll(), OnMenuProperties(), OnMenuRename(), OnMenuUpdate(), OnPropertyChanged(), OnPropertyChanging(), OnPropertyLableEditBegin(), OnPropertyLableEditEnd(), OnPropertyRightClick(), OnPropertySelected(), RefreshUI(), RemoveWatch(), RenameWatch(), and UpdateWatches().
OnCollapse()
void WatchesDlg::OnCollapse (wxPropertyGridEvent & event) private
Definition at line 589 of file watchesdlg.cpp.
References cbDebuggerPlugin::CollapseWatch(), Manager::Get(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), and WatchesProperty::GetWatch().
Referenced by GetWindow().
OnExpand()
void WatchesDlg::OnExpand (wxPropertyGridEvent & event) private
Definition at line 578 of file watchesdlg.cpp.
References cbDebuggerPlugin::ExpandWatch(), Manager::Get(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), and WatchesProperty::GetWatch().
Referenced by GetWindow().
OnIdle()
void WatchesDlg::OnIdle (wxIdleEvent & event) private
Definition at line 630 of file watchesdlg.cpp.
References wxPropertyGrid::Append(), wxPropertyGrid::BeginLabelEdit(), m_append_empty_watch, m_grid, wxPropertyGrid::SelectProperty(), and wxEmptyString.
Referenced by GetWindow().
OnKeyDown()
void WatchesDlg::OnKeyDown (wxKeyEvent & event) private
Definition at line 687 of file watchesdlg.cpp.
References wxPropertyGrid::BeginLabelEdit(), DeleteProperty(), Manager::Get(), wxPGProperty::GetChildCount(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), wxKeyEvent::GetKeyCode(), wxPropertyGrid::GetLabelEditor(), wxPGProperty::GetParent(), wxPropertyGrid::GetRoot(), wxPropertyGrid::GetSelection(), WatchesProperty::GetWatch(), wxPropertyGrid::IsEditorFocused(), wxPGProperty::IsRoot(), wxPGProperty::Item(), m_grid, m_watches, wxPropertyGrid::SelectProperty(), cbDebuggerPlugin::SupportsFeature(), cbDebuggerFeature::Watches, WXK_DELETE, and WXK_INSERT.
Referenced by GetWindow(), and WatchesDlg().
OnMenuAddDataBreak()
void WatchesDlg::OnMenuAddDataBreak (wxCommandEvent & event) private
Definition at line 882 of file watchesdlg.cpp.
References cbDebuggerPlugin::AddDataBreakpoint(), wxString::empty(), Manager::Get(), DebuggerManager::GetActiveDebugger(), DebuggerManager::GetBreakpointDialog(), Manager::GetDebuggerManager(), wxPropertyGrid::GetSelection(), WatchesProperty::GetWatch(), m_grid, and cbBreakpointsDlg::Reload().
Referenced by GetWindow().
OnMenuAutoUpdate()
void WatchesDlg::OnMenuAutoUpdate (wxCommandEvent & event) private
Definition at line 900 of file watchesdlg.cpp.
References wxPropertyGrid::GetSelection(), WatchesProperty::GetWatch(), and m_grid.
Referenced by GetWindow().
OnMenuDelete()
void WatchesDlg::OnMenuDelete (wxCommandEvent & event) private
Definition at line 853 of file watchesdlg.cpp.
References DeleteProperty(), wxPropertyGrid::GetSelection(), and m_grid.
Referenced by GetWindow().
OnMenuDeleteAll()
void WatchesDlg::OnMenuDeleteAll (wxCommandEvent & event) private
Definition at line 863 of file watchesdlg.cpp.
References wxPropertyGrid::DeleteProperty(), cbDebuggerPlugin::DeleteWatch(), Manager::Get(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), m_grid, and m_watches.
Referenced by GetWindow().
OnMenuProperties()
void WatchesDlg::OnMenuProperties (wxCommandEvent & event) private
Definition at line 837 of file watchesdlg.cpp.
References Manager::Get(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), wxPropertyGrid::GetSelection(), WatchesProperty::GetWatch(), m_grid, and cbDebuggerPlugin::ShowWatchProperties().
Referenced by GetWindow().
OnMenuRename()
void WatchesDlg::OnMenuRename (wxCommandEvent & event) private
Definition at line 828 of file watchesdlg.cpp.
References wxPropertyGrid::BeginLabelEdit(), wxPropertyGrid::GetLabelEditor(), and m_grid.
Referenced by GetWindow().
OnMenuUpdate()
void WatchesDlg::OnMenuUpdate (wxCommandEvent & event) private
Definition at line 912 of file watchesdlg.cpp.
References cbGetRootWatch(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), wxPropertyGrid::GetSelection(), WatchesProperty::GetWatch(), m_grid, and cbDebuggerPlugin::UpdateWatch().
Referenced by GetWindow().
OnPropertyChanged()
void WatchesDlg::OnPropertyChanged (wxPropertyGridEvent & event) private
Definition at line 600 of file watchesdlg.cpp.
References SetValue().
Referenced by GetWindow().
OnPropertyChanging()
void WatchesDlg::OnPropertyChanging (wxPropertyGridEvent & event) private
Definition at line 606 of file watchesdlg.cpp.
References wxPGProperty::GetChildCount(), wxPropertyGridEvent::GetProperty(), and wxPropertyGridEvent::Veto().
Referenced by GetWindow().
OnPropertyLableEditBegin()
void WatchesDlg::OnPropertyLableEditBegin (wxPropertyGridEvent & event) private
Definition at line 612 of file watchesdlg.cpp.
References wxPGProperty::GetParent(), wxPGProperty::IsRoot(), and wxPropertyGridEvent::Veto().
Referenced by GetWindow().
OnPropertyLableEditEnd()
void WatchesDlg::OnPropertyLableEditEnd (wxPropertyGridEvent & event) private
Definition at line 624 of file watchesdlg.cpp.
References wxPropertyGrid::GetLabelEditor(), wxPropertyGridEvent::GetProperty(), m_grid, and RenameWatch().
Referenced by GetWindow().
OnPropertyRightClick()
void WatchesDlg::OnPropertyRightClick (wxPropertyGridEvent & event) private
Definition at line 742 of file watchesdlg.cpp.
References _(), cbDebuggerPlugin::WatchesDisabledMenuItems::AddDataBreak, wxMenu::Append(), wxMenu::AppendCheckItem(), wxMenu::AppendSeparator(), cbGetRootWatch(), wxMenu::Check(), cbDebuggerPlugin::WatchesDisabledMenuItems::Delete, cbDebuggerPlugin::WatchesDisabledMenuItems::DeleteAll, cbDebuggerPlugin::WatchesDisabledMenuItems::Empty, wxMenu::Enable(), Manager::Get(), DebuggerManager::GetActiveDebugger(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), wxPropertyGridEvent::GetProperty(), WatchesProperty::GetWatch(), m_watches, cbDebuggerPlugin::OnWatchesContextMenu(), cbDebuggerPlugin::WatchesDisabledMenuItems::Properties, cbDebuggerPlugin::WatchesDisabledMenuItems::Rename, cbDebuggerPlugin::SupportsFeature(), cbDebuggerFeature::Watches, and wxEmptyString.
Referenced by GetWindow().
OnPropertySelected()
void WatchesDlg::OnPropertySelected (wxPropertyGridEvent & event) private
Definition at line 643 of file watchesdlg.cpp.
References wxPropertyGrid::BeginLabelEdit(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), wxPropertyGrid::GetSelection(), m_grid, cbDebuggerPlugin::SupportsFeature(), cbDebuggerFeature::Watches, and wxEmptyString.
Referenced by GetWindow().
RefreshUI()
void WatchesDlg::RefreshUI () virtual
Implements cbWatchesDlg.
Definition at line 967 of file watchesdlg.cpp.
References wxPropertyGrid::DisableProperty(), wxPropertyGrid::EnableProperty(), Manager::Get(), DebuggerManager::GetActiveDebugger(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), m_grid, m_watches, ValueTooltip::OnCollapse(), ValueTooltip::OnExpand(), ValueTooltip::OnTimer(), wxPropertyGrid::RemoveProperty(), cbDebuggerPlugin::SupportsFeature(), and cbDebuggerFeature::Watches.
Referenced by GetWindow().
RemoveWatch()
void WatchesDlg::RemoveWatch (cb::shared_ptr< cbWatch > watch) virtual
Implements cbWatchesDlg.
Definition at line 569 of file watchesdlg.cpp.
References DeleteProperty(), and m_watches.
Referenced by GetWindow().
RenameWatch()
void WatchesDlg::RenameWatch (wxObject * prop, const wxString & newSymbol) virtual
Implements cbWatchesDlg.
Definition at line 926 of file watchesdlg.cpp.
References cbDebuggerPlugin::AddWatch(), cbDebuggerPlugin::DeleteWatch(), Manager::Get(), DebuggerManager::GetActiveDebugger(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), WatchesProperty::GetWatch(), m_append_empty_watch, m_grid, m_watches, WatchesDlg::WatchItem::property, WatchesProperty::SetWatch(), UpdateWatch(), WatchesDlg::WatchItem::watch, and wxEmptyString.
Referenced by GetWindow(), and OnPropertyLableEditEnd().
UpdateWatches()
void WatchesDlg::UpdateWatches () virtual
Implements cbWatchesDlg.
Definition at line 507 of file watchesdlg.cpp.
References m_grid, m_watches, and UpdateWatch().
Referenced by GetWindow().
Member Data Documentation
m_append_empty_watch
bool WatchesDlg::m_append_empty_watch private
Definition at line 74 of file watchesdlg.h.
Referenced by OnIdle(), and RenameWatch().
m_grid
wxPropertyGrid* WatchesDlg::m_grid private
Definition at line 72 of file watchesdlg.h.
Referenced by AddSpecialWatch(), AddWatch(), DeleteProperty(), OnIdle(), OnKeyDown(), OnMenuAddDataBreak(), OnMenuAutoUpdate(), OnMenuDelete(), OnMenuDeleteAll(), OnMenuProperties(), OnMenuRename(), OnMenuUpdate(), OnPropertyLableEditEnd(), OnPropertySelected(), RefreshUI(), RenameWatch(), UpdateWatches(), and WatchesDlg().
m_watches
WatchItems WatchesDlg::m_watches private
Definition at line 73 of file watchesdlg.h.
Referenced by AddSpecialWatch(), AddWatch(), DeleteProperty(), OnKeyDown(), OnMenuDeleteAll(), OnPropertyRightClick(), RefreshUI(), RemoveWatch(), RenameWatch(), and UpdateWatches().
The documentation for this class was generated from the following files:
watchesdlg.h
watchesdlg.cpp