Code::Blocks: CompilerFlagDlg Class Reference
CompilerFlagDlg Class Reference
#include <compilerflagdlg.h>
Public Member Functions
CompilerFlagDlg (wxWindow *parent, CompOption *opt, wxArrayString &categ, const wxString &selectedCategory)
virtual ~CompilerFlagDlg ()
void EndModal (int retCode)
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Private Member Functions
void OnAdvancedOption (wxCommandEvent &event)
Private Attributes
wxTextCtrl * NameText
wxTextCtrl * CompilerText
wxTextCtrl * LinkerText
wxComboBox * CategoryCombo
wxTextCtrl * AgainstText
wxTextCtrl * MessageText
wxTextCtrl * SupersedeText
wxToggleButton * ExclusiveToggle
CompOption * copt
Detailed Description
Definition at line 11 of file compilerflagdlg.h.
Constructor & Destructor Documentation
CompilerFlagDlg()
CompilerFlagDlg::CompilerFlagDlg (wxWindow * parent, CompOption * opt, wxArrayString & categ, const wxString & selectedCategory)
Definition at line 14 of file compilerflagdlg.cpp.
References _(), CompOption::additionalLibs, AgainstText, CompOption::category, CategoryCombo, CompOption::checkAgainst, CompOption::checkMessage, CompilerText, copt, wxString::empty(), wxString::EndsWith(), CompOption::exclusive, ExclusiveToggle, wxXmlResource::Get(), wxString::IsEmpty(), LinkerText, wxXmlResource::LoadObject(), MessageText, CompOption::name, NameText, OnAdvancedOption(), CompOption::option, wxToggleButton::SetValue(), CompOption::supersedes, SupersedeText, wxString::Trim(), wxEmptyString, and wxT.
~CompilerFlagDlg()
CompilerFlagDlg::~CompilerFlagDlg () virtual
Definition at line 63 of file compilerflagdlg.cpp.
Member Function Documentation
EndModal()
void CompilerFlagDlg::EndModal (int retCode)
Definition at line 77 of file compilerflagdlg.cpp.
References CompOption::additionalLibs, AgainstText, wxString::BeforeLast(), CompOption::category, CategoryCombo, CompOption::checkAgainst, CompOption::checkMessage, CompilerText, copt, ScriptBindings::EndModal(), CompOption::exclusive, ExclusiveToggle, wxToggleButton::GetValue(), wxString::IsEmpty(), LinkerText, MessageText, CompOption::name, NameText, CompOption::option, CompOption::supersedes, SupersedeText, wxString::Trim(), wxID_CANCEL, and wxT.
OnAdvancedOption()
void CompilerFlagDlg::OnAdvancedOption (wxCommandEvent & event) private
Definition at line 68 of file compilerflagdlg.cpp.
References _(), AgainstText, ExclusiveToggle, wxToggleButton::GetValue(), and MessageText.
Referenced by CompilerFlagDlg().
Member Data Documentation
AgainstText
wxTextCtrl* CompilerFlagDlg::AgainstText private
Definition at line 30 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), EndModal(), and OnAdvancedOption().
CategoryCombo
wxComboBox* CompilerFlagDlg::CategoryCombo private
Definition at line 29 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), and EndModal().
CompilerText
wxTextCtrl* CompilerFlagDlg::CompilerText private
Definition at line 27 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), and EndModal().
copt
CompOption* CompilerFlagDlg::copt private
Definition at line 35 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), and EndModal().
ExclusiveToggle
wxToggleButton* CompilerFlagDlg::ExclusiveToggle private
Definition at line 33 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), EndModal(), and OnAdvancedOption().
LinkerText
wxTextCtrl* CompilerFlagDlg::LinkerText private
Definition at line 28 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), and EndModal().
MessageText
wxTextCtrl* CompilerFlagDlg::MessageText private
Definition at line 31 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), EndModal(), and OnAdvancedOption().
NameText
wxTextCtrl* CompilerFlagDlg::NameText private
Definition at line 26 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), and EndModal().
SupersedeText
wxTextCtrl* CompilerFlagDlg::SupersedeText private
Definition at line 32 of file compilerflagdlg.h.
Referenced by CompilerFlagDlg(), and EndModal().
The documentation for this class was generated from the following files:
compilerflagdlg.h
compilerflagdlg.cpp