Code::Blocks: GdbCmd_LocalsFuncArgs Class Reference
GdbCmd_LocalsFuncArgs Class Reference
#include <gdb_commands.h>
Public Member Functions
GdbCmd_LocalsFuncArgs (DebuggerDriver *driver, cb::shared_ptr< GDBWatch > watch, bool doLocals)
void ParseOutput (const wxString &output)
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
virtual bool IsContinueCommand () const
Private Attributes
cb::shared_ptr< GDBWatch > m_watch
bool m_doLocals
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Constructor & Destructor Documentation
GdbCmd_LocalsFuncArgs::GdbCmd_LocalsFuncArgs (DebuggerDriver * driver, cb::shared_ptr< GDBWatch > watch, bool doLocals) inline
References DebuggerCmd::m_Cmd.
Member Function Documentation
void GdbCmd_LocalsFuncArgs::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
References AddChild(), ParseGDBWatchValue(), and TokenizeGDBLocals().
Member Data Documentation
bool GdbCmd_LocalsFuncArgs::m_doLocals private
cb::shared_ptr<GDBWatch> GdbCmd_LocalsFuncArgs::m_watch private
The documentation for this class was generated from the following file:
gdb_commands.h