Code::Blocks: CompilerCommandGenerator Class Reference
CompilerCommandGenerator Class Reference
Generate command-lines needed to produce a build.
#include <compilercommandgenerator.h>
Public Member Functions
CompilerCommandGenerator ()
virtual ~CompilerCommandGenerator ()
virtual void Init (cbProject *project)
Initialize for use with the specified project.
virtual void GenerateCommandLine (wxString &macro, ProjectBuildTarget *target, ProjectFile *pf, const wxString &file, const wxString &object, const wxString &flat_object, const wxString &deps)
Get the command line to compile/link the specific file.
virtual const wxArrayString & GetCompilerSearchDirs (ProjectBuildTarget *target)
Get the full include dirs used in the actual command line.
virtual const wxArrayString & GetLinkerSearchDirs (ProjectBuildTarget *target)
Get the full linker dirs used in the actual command line.
Protected Member Functions
virtual void DoBuildScripts (cbProject *project, CompileTargetBase *target, const wxString &funcName)
Apply pre-build scripts for base.
virtual wxString GetOrderedOptions (const ProjectBuildTarget *target, OptionsRelationType rel, const wxString &project_options, const wxString &target_options)
Arrange order of options.
virtual wxArrayString GetOrderedOptions (const ProjectBuildTarget *target, OptionsRelationType rel, const wxArrayString &project_options, const wxArrayString &target_options)
Arrange order of options.
virtual wxArrayString GetOrderedIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxArrayString GetOrderedLibrariesDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxArrayString GetOrderedResourceIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxString SetupOutputFilenames (Compiler *compiler, ProjectBuildTarget *target)
Setup output filename for build target.
virtual wxString SetupIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup compiler include dirs for build target.
virtual wxString SetupLibrariesDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup linker include dirs for build target.
virtual wxString SetupResourceIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup resource compiler include dirs for build target.
virtual wxString SetupCompilerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup compiler flags for build target.
virtual wxString SetupLinkerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup linker flags for build target.
virtual wxString SetupLinkLibraries (Compiler *compiler, ProjectBuildTarget *target)
Setup link libraries for build target.
virtual wxString SetupResourceCompilerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup resource compiler flags for build target.
virtual wxString FixupLinkLibraries (Compiler *compiler, const wxString &lib)
Fix library name based on advanced compiler settings.
virtual void FixPathSeparators (Compiler *compiler, wxString &inAndOut)
Static Protected Member Functions
static wxString MakeOptString (const wxArrayString &arr, const wxString &opt, wxChar separator=_T(' '))
static wxString PathSearch (const wxArrayString &arr, const wxString &filename)
Protected Attributes
OptionsMap m_Output
output filenames, per-target
OptionsMap m_StaticOutput
static output filenames, per-target
OptionsMap m_DefOutput
def output filenames, per-target
OptionsMap m_Inc
compiler 'include' dirs, per-target
OptionsMap m_Lib
linker 'include' dirs, per-target
OptionsMap m_RC
resource compiler 'include' dirs, per-target
OptionsMap m_CFlags
compiler flags, per-target
OptionsMap m_RCFlags
resource compiler flags, per-target
OptionsMap m_LDFlags
linker flags, per-target
OptionsMap m_LDAdd
link libraries, per-target
wxString m_PrjIncPath
directive to add the project's top-level path in compiler search dirs (ready for the command line)
SearchDirsMap m_CompilerSearchDirs
array of final compiler search dirs, per-target
SearchDirsMap m_LinkerSearchDirs
array of final linker search dirs, per-target
Private Member Functions
wxString GetProcessedIncludeDir (Compiler *compiler, ProjectBuildTarget *target, const wxArrayString &inc_dirs, const wxString &inc_switch)
Processes include dirs by default.
void SearchDirsFromBackticks (Compiler *compiler, ProjectBuildTarget *target, const wxString &btOutput)
Private Attributes
wxArrayString m_NotLoadedScripts
wxArrayString m_ScriptsWithErrors
Detailed Description
Generate command-lines needed to produce a build.
This pre-generates everything when Init() is called.
This is used by compilers to generate the needed command lines for a build.
Definition at line 30 of file compilercommandgenerator.h.
Constructor & Destructor Documentation
CompilerCommandGenerator()
CompilerCommandGenerator::CompilerCommandGenerator ()
Definition at line 39 of file compilercommandgenerator.cpp.
~CompilerCommandGenerator()
CompilerCommandGenerator::~CompilerCommandGenerator () virtual
Definition at line 44 of file compilercommandgenerator.cpp.
Member Function Documentation
DoBuildScripts()
void CompilerCommandGenerator::DoBuildScripts (cbProject * project, CompileTargetBase * target, const wxString & funcName) protected virtual
Apply pre-build scripts for base.
Definition at line 514 of file compilercommandgenerator.cpp.
References cbU2C(), ScriptingManager::DisplayErrors(), Manager::Get(), CompileTargetBase::GetBasePath(), CompileOptionsBase::GetBuildScripts(), Manager::GetMacrosManager(), Manager::GetScriptingManager(), ScriptingManager::LoadBuffer(), m_NotLoadedScripts, m_ScriptsWithErrors, and MacrosManager::ReplaceMacros().
Referenced by Init().
FixPathSeparators()
void CompilerCommandGenerator::FixPathSeparators (Compiler * compiler, wxString & inAndOut) protected virtual
Definition at line 555 of file compilercommandgenerator.cpp.
References CompilerSwitches::forceFwdSlashes, and Compiler::GetSwitches().
Referenced by FixupLinkLibraries(), GenerateCommandLine(), GetOrderedIncludeDirs(), GetOrderedLibrariesDirs(), GetOrderedResourceIncludeDirs(), GetProcessedIncludeDir(), and SetupOutputFilenames().
FixupLinkLibraries()
wxString CompilerCommandGenerator::FixupLinkLibraries (Compiler * compiler, const wxString & lib) protected virtual
Fix library name based on advanced compiler settings.
Definition at line 984 of file compilercommandgenerator.cpp.
References FixPathSeparators(), Compiler::GetSwitches(), CompilerSwitches::libExtension, CompilerSwitches::libPrefix, CompilerSwitches::linkerNeedsLibExtension, CompilerSwitches::linkerNeedsLibPrefix, CompilerSwitches::linkLibs, and QuoteStringIfNeeded().
Referenced by SetupLinkLibraries().
GenerateCommandLine()
void CompilerCommandGenerator::GenerateCommandLine (wxString & macro, ProjectBuildTarget * target, ProjectFile * pf, const wxString & file, const wxString & object, const wxString & flat_object, const wxString & deps) virtual
Get the command line to compile/link the specific file.
Definition at line 207 of file compilercommandgenerator.cpp.
References CompilerPrograms::C, ProjectFile::compilerVar, CompilerPrograms::CPP, LogManager::DebugLog(), FileFilters::EXECUTABLE_EXT, F(), FixPathSeparators(), Manager::Get(), GetArrayFromString(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), Compiler::GetCOnlyFlags(), Compiler::GetCPPOnlyFlags(), CompilerFactory::GetDefaultCompiler(), Manager::GetLogManager(), Manager::GetMacrosManager(), Compiler::GetPrograms(), GetStringFromArray(), Compiler::GetSwitches(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, CompilerPrograms::LD, CompilerPrograms::LIB, m_CFlags, m_DefOutput, m_Inc, m_LDAdd, m_LDFlags, m_Lib, m_Output, m_PrjIncPath, m_RC, m_RCFlags, m_StaticOutput, CompilerSwitches::objectSeparator, QuoteStringIfNeeded(), MacrosManager::ReplaceMacros(), CompileOptionsBase::SupportsCurrentPlatform(), ttDynamicLib, ttStaticLib, UnquoteStringIfNeeded(), and CompilerPrograms::WINDRES.
Referenced by DirectCommands::GetCompileFileCommand(), DirectCommands::GetCompileSingleFileCommand(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), and DirectCommands::GetTargetLinkCommands().
GetCompilerSearchDirs()
const wxArrayString & CompilerCommandGenerator::GetCompilerSearchDirs (ProjectBuildTarget * target) virtual
Get the full include dirs used in the actual command line.
These are the actual include dirs that will be used for building and might be different than target->GetIncludeDirs(). This is because it's the sum of target include dirs + project include dirs + build-script include dirs.
Note
This is only valid after Init() has been called.
Definition at line 1098 of file compilercommandgenerator.cpp.
References m_CompilerSearchDirs.
Referenced by DirectCommands::DepsSearchStart().
GetLinkerSearchDirs()
const wxArrayString & CompilerCommandGenerator::GetLinkerSearchDirs (ProjectBuildTarget * target) virtual
Get the full linker dirs used in the actual command line.
These are the actual linker dirs that will be used for building and might be different than target->GetLibDirs(). This is because it's the sum of target linker dirs + project linker dirs + build-script linker dirs.
Note
This is only valid after Init() has been called.
Definition at line 1110 of file compilercommandgenerator.cpp.
References m_LinkerSearchDirs.
Referenced by cbGetDynamicLinkerPathForTarget(), and DebuggerGDB::DoDebug().
GetOrderedIncludeDirs()
wxArrayString CompilerCommandGenerator::GetOrderedIncludeDirs (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Definition at line 718 of file compilercommandgenerator.cpp.
References LogManager::DebugLogError(), FixPathSeparators(), Manager::Get(), CompileTargetBase::GetBasePath(), Manager::GetConfigManager(), CompileOptionsBase::GetIncludeDirs(), Manager::GetLogManager(), Manager::GetMacrosManager(), GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), Compiler::GetSwitches(), m_CompilerSearchDirs, ortIncludeDirs, ConfigManager::ReadBool(), MacrosManager::ReplaceMacros(), UnquoteStringIfNeeded(), and CompilerSwitches::Use83Paths.
Referenced by SetupIncludeDirs().
GetOrderedLibrariesDirs()
wxArrayString CompilerCommandGenerator::GetOrderedLibrariesDirs (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Definition at line 767 of file compilercommandgenerator.cpp.
References LogManager::DebugLogError(), FixPathSeparators(), Manager::Get(), CompileTargetBase::GetBasePath(), CompileOptionsBase::GetLibDirs(), Manager::GetLogManager(), Manager::GetMacrosManager(), GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), Compiler::GetSwitches(), m_LinkerSearchDirs, ortLibDirs, MacrosManager::ReplaceMacros(), UnquoteStringIfNeeded(), and CompilerSwitches::Use83Paths.
Referenced by SetupLibrariesDirs(), and SetupLinkLibraries().
GetOrderedOptions() [1/2]
wxString CompilerCommandGenerator::GetOrderedOptions (const ProjectBuildTarget * target, OptionsRelationType rel, const wxString & project_options, const wxString & target_options) protected virtual
Arrange order of options.
Depending on the order defined for the build target, it concatenates project_options with target_options and returns the result.
Definition at line 1126 of file compilercommandgenerator.cpp.
References CompileTargetBase::GetOptionRelation(), orAppendToParentOptions, orPrependToParentOptions, orUseParentOptionsOnly, and orUseTargetOptionsOnly.
Referenced by GetOrderedIncludeDirs(), GetOrderedLibrariesDirs(), GetOrderedResourceIncludeDirs(), SetupCompilerOptions(), CompilerOWGenerator::SetupLibrariesDirs(), CompilerOWGenerator::SetupLinkerOptions(), SetupLinkerOptions(), CompilerOWGenerator::SetupLinkLibraries(), SetupLinkLibraries(), and SetupResourceCompilerOptions().
GetOrderedOptions() [2/2]
wxArrayString CompilerCommandGenerator::GetOrderedOptions (const ProjectBuildTarget * target, OptionsRelationType rel, const wxArrayString & project_options, const wxArrayString & target_options) protected virtual
Arrange order of options.
Depending on the order defined for the build target, it concatenates project_options with target_options and returns the result.
Definition at line 1154 of file compilercommandgenerator.cpp.
References CompileTargetBase::GetOptionRelation(), orAppendToParentOptions, orPrependToParentOptions, orUseParentOptionsOnly, and orUseTargetOptionsOnly.
GetOrderedResourceIncludeDirs()
wxArrayString CompilerCommandGenerator::GetOrderedResourceIncludeDirs (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Definition at line 820 of file compilercommandgenerator.cpp.
References LogManager::DebugLogError(), FixPathSeparators(), Manager::Get(), Manager::GetLogManager(), Manager::GetMacrosManager(), GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), CompileOptionsBase::GetResourceIncludeDirs(), Compiler::GetSwitches(), ortResDirs, MacrosManager::ReplaceMacros(), UnquoteStringIfNeeded(), and CompilerSwitches::Use83Paths.
Referenced by SetupResourceIncludeDirs().
GetProcessedIncludeDir()
wxString CompilerCommandGenerator::GetProcessedIncludeDir (Compiler * compiler, ProjectBuildTarget * target, const wxArrayString & inc_dirs, const wxString & inc_switch) private
Processes include dirs by default.
Definition at line 1187 of file compilercommandgenerator.cpp.
References FixPathSeparators(), Manager::Get(), Manager::GetMacrosManager(), Compiler::GetSwitches(), QuoteStringIfNeeded(), MacrosManager::ReplaceMacros(), UnquoteStringIfNeeded(), and CompilerSwitches::Use83Paths.
Init()
void CompilerCommandGenerator::Init (cbProject * project) virtual
Initialize for use with the specified project.
Definition at line 49 of file compilercommandgenerator.cpp.
References cbEVT_COMPILER_SET_BUILD_OPTIONS, cbMessageBox(), cbThrow, DoBuildScripts(), Manager::Get(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), cbProject::GetCommonTopLevelPath(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetDefaultCompiler(), Manager::GetLogManager(), cbProject::GetModified(), CompileTargetBase::GetTargetType(), CompileTargetBase::GetTitle(), Manager::IsBatchBuild(), LogManager::LogToStdOut(), m_CFlags, m_CompilerSearchDirs, m_DefOutput, m_Inc, m_LDAdd, m_LDFlags, m_Lib, m_LinkerSearchDirs, m_NotLoadedScripts, m_Output, m_PrjIncPath, m_RC, m_RCFlags, m_ScriptsWithErrors, m_StaticOutput, Manager::ProcessEvent(), QuoteStringIfNeeded(), CodeBlocksEvent::SetBuildTargetName(), cbProject::SetModified(), SetupCompilerOptions(), SetupIncludeDirs(), SetupLibrariesDirs(), SetupLinkerOptions(), SetupLinkLibraries(), SetupOutputFilenames(), SetupResourceCompilerOptions(), SetupResourceIncludeDirs(), CompileOptionsBase::SupportsCurrentPlatform(), and ttCommandsOnly.
Referenced by CompilerMINGW::GetCommandGenerator(), CompilerOW::GetCommandGenerator(), and Compiler::GetCommandGenerator().
MakeOptString()
wxString CompilerCommandGenerator::MakeOptString (const wxArrayString & arr, const wxString & opt, wxChar separator = _T(' ')) static protected
Definition at line 850 of file compilercommandgenerator.cpp.
References QuoteStringIfNeeded().
Referenced by SetupIncludeDirs(), SetupLibrariesDirs(), and SetupResourceIncludeDirs().
PathSearch()
wxString CompilerCommandGenerator::PathSearch (const wxArrayString & arr, const wxString & filename) static protected
Definition at line 883 of file compilercommandgenerator.cpp.
References Manager::Get(), Manager::GetLogManager(), and LogManager::Log().
Referenced by SetupLinkLibraries().
SearchDirsFromBackticks()
void CompilerCommandGenerator::SearchDirsFromBackticks (Compiler * compiler, ProjectBuildTarget * target, const wxString & btOutput) private
Definition at line 1212 of file compilercommandgenerator.cpp.
References Compiler::GetSwitches(), CompilerSwitches::includeDirs, CompilerSwitches::libDirs, m_CompilerSearchDirs, and m_LinkerSearchDirs.
Referenced by SetupCompilerOptions(), SetupLinkerOptions(), and SetupResourceCompilerOptions().
SetupCompilerOptions()
wxString CompilerCommandGenerator::SetupCompilerOptions (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup compiler flags for build target.
Definition at line 926 of file compilercommandgenerator.cpp.
References ExpandBackticks(), Manager::Get(), CompileOptionsBase::GetCompilerOptions(), Manager::GetMacrosManager(), GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), GetStringFromArray(), ortCompilerOptions, MacrosManager::ReplaceMacros(), and SearchDirsFromBackticks().
Referenced by Init().
SetupIncludeDirs()
wxString CompilerCommandGenerator::SetupIncludeDirs (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup compiler include dirs for build target.
Reimplemented in CompilerMINGWGenerator.
Definition at line 900 of file compilercommandgenerator.cpp.
References GetOrderedIncludeDirs(), Compiler::GetSwitches(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, and MakeOptString().
Referenced by Init(), and CompilerMINGWGenerator::SetupIncludeDirs().
SetupLibrariesDirs()
wxString CompilerCommandGenerator::SetupLibrariesDirs (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup linker include dirs for build target.
Reimplemented in CompilerOWGenerator.
Definition at line 908 of file compilercommandgenerator.cpp.
References GetOrderedLibrariesDirs(), Compiler::GetSwitches(), CompilerSwitches::libDirs, CompilerSwitches::libDirSeparator, CompilerSwitches::linkerNeedsPathResolved, and MakeOptString().
Referenced by Init().
SetupLinkerOptions()
wxString CompilerCommandGenerator::SetupLinkerOptions (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup linker flags for build target.
Reimplemented in CompilerOWGenerator.
Definition at line 955 of file compilercommandgenerator.cpp.
References ExpandBackticks(), Manager::Get(), CompileOptionsBase::GetLinkerOptions(), Manager::GetMacrosManager(), GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), GetStringFromArray(), ortLinkerOptions, MacrosManager::ReplaceMacros(), and SearchDirsFromBackticks().
Referenced by Init().
SetupLinkLibraries()
wxString CompilerCommandGenerator::SetupLinkLibraries (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup link libraries for build target.
Reimplemented in CompilerOWGenerator.
Definition at line 1032 of file compilercommandgenerator.cpp.
References FixupLinkLibraries(), CompileOptionsBase::GetLinkLibs(), GetOrderedLibrariesDirs(), GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), Compiler::GetSwitches(), CompilerSwitches::linkerNeedsPathResolved, CompilerSwitches::objectSeparator, ortLinkerOptions, PathSearch(), and QuoteStringIfNeeded().
Referenced by Init().
SetupOutputFilenames()
wxString CompilerCommandGenerator::SetupOutputFilenames (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup output filename for build target.
Definition at line 574 of file compilercommandgenerator.cpp.
References LogManager::DebugLog(), F(), FixPathSeparators(), Manager::Get(), CompileTargetBase::GetDynamicLibDefFilename(), CompileTargetBase::GetDynamicLibImportFilename(), Manager::GetLogManager(), Manager::GetMacrosManager(), CompileTargetBase::GetOutputFilename(), Compiler::GetSwitches(), CompileTargetBase::GetTargetFilenameGenerationPolicy(), CompileTargetBase::GetTargetType(), CompilerSwitches::libExtension, CompilerSwitches::libPrefix, m_Output, m_StaticOutput, QuoteStringIfNeeded(), MacrosManager::ReplaceMacros(), tgfpPlatformDefault, ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttExecutable, ttNative, ttStaticLib, UnixFilename(), and UnquoteStringIfNeeded().
Referenced by Init().
SetupResourceCompilerOptions()
wxString CompilerCommandGenerator::SetupResourceCompilerOptions (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup resource compiler flags for build target.
Definition at line 1070 of file compilercommandgenerator.cpp.
References ExpandBackticks(), Manager::Get(), Manager::GetMacrosManager(), GetOrderedOptions(), GetStringFromArray(), ortCompilerOptions, MacrosManager::ReplaceMacros(), and SearchDirsFromBackticks().
Referenced by Init().
SetupResourceIncludeDirs()
wxString CompilerCommandGenerator::SetupResourceIncludeDirs (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup resource compiler include dirs for build target.
Definition at line 918 of file compilercommandgenerator.cpp.
References GetOrderedResourceIncludeDirs(), Compiler::GetSwitches(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, and MakeOptString().
Referenced by Init().
Member Data Documentation
m_CFlags
OptionsMap CompilerCommandGenerator::m_CFlags protected
compiler flags, per-target
Definition at line 93 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_CompilerSearchDirs
SearchDirsMap CompilerCommandGenerator::m_CompilerSearchDirs protected
array of final compiler search dirs, per-target
Definition at line 100 of file compilercommandgenerator.h.
Referenced by GetCompilerSearchDirs(), GetOrderedIncludeDirs(), Init(), and SearchDirsFromBackticks().
m_DefOutput
OptionsMap CompilerCommandGenerator::m_DefOutput protected
def output filenames, per-target
Definition at line 89 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_Inc
OptionsMap CompilerCommandGenerator::m_Inc protected
compiler 'include' dirs, per-target
Definition at line 90 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_LDAdd
OptionsMap CompilerCommandGenerator::m_LDAdd protected
link libraries, per-target
Definition at line 96 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_LDFlags
OptionsMap CompilerCommandGenerator::m_LDFlags protected
linker flags, per-target
Definition at line 95 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_Lib
OptionsMap CompilerCommandGenerator::m_Lib protected
linker 'include' dirs, per-target
Definition at line 91 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_LinkerSearchDirs
SearchDirsMap CompilerCommandGenerator::m_LinkerSearchDirs protected
array of final linker search dirs, per-target
Definition at line 101 of file compilercommandgenerator.h.
Referenced by GetLinkerSearchDirs(), GetOrderedLibrariesDirs(), Init(), and SearchDirsFromBackticks().
m_NotLoadedScripts
wxArrayString CompilerCommandGenerator::m_NotLoadedScripts private
Definition at line 106 of file compilercommandgenerator.h.
Referenced by DoBuildScripts(), and Init().
m_Output
OptionsMap CompilerCommandGenerator::m_Output protected
output filenames, per-target
Definition at line 87 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), Init(), and SetupOutputFilenames().
m_PrjIncPath
wxString CompilerCommandGenerator::m_PrjIncPath protected
directive to add the project's top-level path in compiler search dirs (ready for the command line)
Definition at line 98 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_RC
OptionsMap CompilerCommandGenerator::m_RC protected
resource compiler 'include' dirs, per-target
Definition at line 92 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_RCFlags
OptionsMap CompilerCommandGenerator::m_RCFlags protected
resource compiler flags, per-target
Definition at line 94 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), and Init().
m_ScriptsWithErrors
wxArrayString CompilerCommandGenerator::m_ScriptsWithErrors private
Definition at line 107 of file compilercommandgenerator.h.
Referenced by DoBuildScripts(), and Init().
m_StaticOutput
OptionsMap CompilerCommandGenerator::m_StaticOutput protected
static output filenames, per-target
Definition at line 88 of file compilercommandgenerator.h.
Referenced by GenerateCommandLine(), Init(), and SetupOutputFilenames().
The documentation for this class was generated from the following files:
compilercommandgenerator.h
compilercommandgenerator.cpp