Code::Blocks: DataBreakpointDlg Class Reference
DataBreakpointDlg Class Reference
#include <databreakpointdlg.h>
Public Member Functions
DataBreakpointDlg (wxWindow *parent, const wxString &dataExpression, bool enabled, int selection)
virtual ~DataBreakpointDlg ()
bool IsBreakpointEnabled ()
int GetSelection ()
wxString GetDataExpression () const
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Static Public Attributes
static const long ID_CHK_ENABLED = wxNewId()
static const long ID_TXT_DATA_EXPRESION = wxNewId()
static const long ID_RDO_CONDITION = wxNewId()
Protected Attributes
wxRadioBox * m_condition
wxCheckBox * m_enabled
wxTextCtrl * m_dataExpression
wxStdDialogButtonSizer * StdDialogButtonSizer1
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
DataBreakpointDlg::DataBreakpointDlg (wxWindow * parent, const wxString & dataExpression, bool enabled, int selection)
DataBreakpointDlg::~DataBreakpointDlg () virtual
Member Function Documentation
wxString DataBreakpointDlg::GetDataExpression () const
References CleanStringValue(), and m_dataExpression.
Referenced by DebuggerGDB::AddDataBreakpoint(), and DebuggerGDB::UpdateBreakpoint().
int DataBreakpointDlg::GetSelection ()
References m_condition.
Referenced by DebuggerGDB::AddDataBreakpoint(), and DebuggerGDB::UpdateBreakpoint().
bool DataBreakpointDlg::IsBreakpointEnabled ()
References m_enabled.
Member Data Documentation
const long DataBreakpointDlg::ID_CHK_ENABLED = wxNewId() static
const long DataBreakpointDlg::ID_RDO_CONDITION = wxNewId() static
const long DataBreakpointDlg::ID_TXT_DATA_EXPRESION = wxNewId() static
wxRadioBox* DataBreakpointDlg::m_condition protected
Referenced by GetSelection().
wxTextCtrl* DataBreakpointDlg::m_dataExpression protected
Referenced by GetDataExpression().
wxCheckBox* DataBreakpointDlg::m_enabled protected
Referenced by IsBreakpointEnabled().
wxStdDialogButtonSizer* DataBreakpointDlg::StdDialogButtonSizer1 protected
The documentation for this class was generated from the following files:
databreakpointdlg.h
databreakpointdlg.cpp