Code::Blocks: WizGenericSelectPathPanel Class Reference
WizGenericSelectPathPanel Class Reference
#include <wizpage.h>
Public Member Functions
WizGenericSelectPathPanel (const wxString &pageId, const wxString &descr, const wxString &label, const wxString &defValue, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizGenericSelectPathPanel ()
void OnButton (wxCommandEvent &event)
virtual void OnPageChanging (wxWizardEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
GenericSelectPath * m_pGenericSelectPath
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 119 of file wizpage.h.
Constructor & Destructor Documentation
WizGenericSelectPathPanel()
WizGenericSelectPathPanel::WizGenericSelectPathPanel (const wxString & pageId, const wxString & descr, const wxString & label, const wxString & defValue, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 439 of file wizpage.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), wxString::IsEmpty(), and ConfigManager::Read().
~WizGenericSelectPathPanel()
WizGenericSelectPathPanel::~WizGenericSelectPathPanel ()
Definition at line 454 of file wizpage.cpp.
Member Function Documentation
OnButton()
void WizGenericSelectPathPanel::OnButton (wxCommandEvent & event)
Definition at line 459 of file wizpage.cpp.
References _(), ChooseDirectory(), Manager::Get(), Manager::GetMacrosManager(), wxString::IsEmpty(), MacrosManager::ReplaceMacros(), wxDirExists(), and wxEmptyString.
Referenced by WizProjectPathPanel::OnPageChanged().
OnPageChanging()
void WizGenericSelectPathPanel::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 468 of file wizpage.cpp.
References _(), _T, cbMessageBox(), Manager::Get(), Manager::GetConfigManager(), wxWizardEvent::GetDirection(), Manager::GetMacrosManager(), WizPageBase::GetPageName(), WizPageBase::OnPageChanging(), MacrosManager::ReplaceMacros(), ConfigManager::Write(), wxDirExists(), and wxICON_ERROR.
Member Data Documentation
m_pGenericSelectPath
GenericSelectPath* WizGenericSelectPathPanel::m_pGenericSelectPath private
Definition at line 129 of file wizpage.h.
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp