Code::Blocks: cbProject Class Reference
cbProject Class Reference
Represents a Code::Blocks project.
#include <cbproject.h>
Classes
struct Glob
Public Member Functions
cbProject (const wxString &filename=wxEmptyString)
Constructor.
~cbProject ()
Destructor.
bool IsLoaded () const
void ClearAllProperties ()
This resets the project to a clear state.
void CalculateCommonTopLevelPath ()
Calculates the top-level path common to all project files.
wxString GetCommonTopLevelPath () const
bool GetModified () const
void SetModified (bool modified=true)
Mark the project as modified or not.
ProjectFile * GetFile (int index)
Access a file of the project.
ProjectFile * GetFileByFilename (const wxString &filename, bool isRelative=true, bool isUnixFilename=false)
Access a file of the project.
int GetFilesCount ()
void SetMakefile (const wxString &makefile)
Set the Makefile filename used when exporting a Makefile for the project, or when using a custom Makefile to build the project.
const wxString & GetMakefile ()
void SetMakefileCustom (bool custom)
Mark if the project should use a custom Makefile for compilation.
bool IsMakefileCustom ()
void SetMakefileExecutionDir (const wxString &dir)
Allow the specification of specific execution directory if the project use a custom Makefile.
wxString GetMakefileExecutionDir ()
wxString GetExecutionDir ()
bool BuildTargetValid (const wxString &name, bool virtuals_too=true) const
Is there a build target (virtual or real) by name?
wxString GetFirstValidBuildTargetName (bool virtuals_too=true) const
const wxString & GetDefaultExecuteTarget () const
void SetDefaultExecuteTarget (const wxString &name)
Set the build target index which will be pre-selected when the "Select target" dialog appears when running the project.
int GetBuildTargetsCount ()
ProjectBuildTarget * GetBuildTarget (int index)
Access a build target.
ProjectBuildTarget * GetBuildTarget (const wxString &targetName)
Access a build target.
ProjectBuildTarget * AddBuildTarget (const wxString &targetName)
Add a new build target.
bool RenameBuildTarget (int index, const wxString &targetName)
Rename a build target.
bool RenameBuildTarget (const wxString &oldTargetName, const wxString &newTargetName)
Rename a build target.
ProjectBuildTarget * DuplicateBuildTarget (int index, const wxString &newName=wxEmptyString)
Duplicate a build target.
ProjectBuildTarget * DuplicateBuildTarget (const wxString &targetName, const wxString &newName=wxEmptyString)
Duplicate a build target.
bool ExportTargetAsProject (int index)
Export a target as a new project.
bool ExportTargetAsProject (const wxString &targetName)
Export a target as a new project.
bool RemoveBuildTarget (int index)
Remove a build target.
bool RemoveBuildTarget (const wxString &targetName)
Remove a build target.
void ReOrderTargets (const wxArrayString &nameOrder)
Reorder the list of build targets.
bool SetActiveBuildTarget (const wxString &name)
Set the active build target.
const wxString & GetActiveBuildTarget () const
PCHMode GetModeForPCH () const
void SetModeForPCH (PCHMode mode)
Set the mode to handle precompiled headers.
void SetCompilerID (const wxString &id)
! Set the flag if the host app should be run in terminal
wxTreeItemId GetProjectNode ()
void SetProjectNode (wxTreeItemId node)
Sets the root item of this item, should not be called by user's code!
bool QueryCloseAllFiles ()
Act like closing all project files, but don't do it.
bool CloseAllFiles (bool dontsave=false)
Close all project files.
bool SaveAllFiles ()
Save all project files.
bool Save ()
Save the project.
bool SaveAs ()
Save the project under a different name.
bool SaveLayout ()
Save the project's layout.
bool LoadLayout ()
Load the project's layout.
void BeginAddFiles ()
Notify that file(s) will be added shortly.
void EndAddFiles ()
Notify that file(s) addition finished.
void BeginRemoveFiles ()
Notify that file(s) will be removed shortly.
void EndRemoveFiles ()
Notify that file(s) removal finished.
ProjectFile * AddFile (const wxString &targetName, const wxString &filename, bool compile=true, bool link=true, unsigned short int weight=50)
Add a file to the project.
ProjectFile * AddFile (int targetIndex, const wxString &filename, bool compile=true, bool link=true, unsigned short int weight=50)
Add a file to the project.
bool RemoveFile (ProjectFile *pf)
Remove a file from the project.
void SetGlobs (const std::vector< Glob > &globs)
Set the globs to the project, this are directory paths do retrieve files from to be added to the project, the path can be searched recursively.
std::vector< Glob > GetGlobs () const
Retrieve the current globs from the project.
const wxArrayString & ExpandedNodes ()
Convenience function for remembering the project's tree state when refreshing it.
void AddExpandedNode (const wxString &path)
Convenience function for remembering the project's tree state when refreshing it.
void SaveTreeState (wxTreeCtrl *tree)
Convenience function for remembering the project's tree state when refreshing it.
void RestoreTreeState (wxTreeCtrl *tree)
Convenience function for remembering the project's tree state when refreshing it.
int SelectTarget (int initial=-1, bool evenIfOne=false)
Displays a target selection dialog.
ProjectBuildTarget * GetCurrentlyCompilingTarget ()
Get a pointer to the currently compiling target.
void SetCurrentlyCompilingTarget (ProjectBuildTarget *bt)
Set the currently compiling target.
bool DefineVirtualBuildTarget (const wxString &alias, const wxArrayString &targets)
Define a new virtual build target.
bool HasVirtualBuildTarget (const wxString &alias) const
Does a virtual build target exist?
bool RemoveVirtualBuildTarget (const wxString &alias)
Remove a virtual build target.
wxArrayString GetVirtualBuildTargets () const
Get a list of all defined virtual build targets.
const wxArrayString & GetVirtualBuildTargetGroup (const wxString &alias) const
Access a virtual build target's group of build targets.
wxArrayString GetExpandedVirtualBuildTargetGroup (const wxString &alias) const
Access a virtual build target's expanded group of build targets.
bool CanAddToVirtualBuildTarget (const wxString &alias, const wxString &target)
Checks if a build target (virtual or real) can be added to a virtual build target, without causing a circular-reference.
const wxArrayString & GetVirtualFolders () const
Get a list of the virtual folders.
void SetVirtualFolders (const wxArrayString &folders)
Set the virtual folders list.
bool AppendUniqueVirtualFolder (const wxString &folder)
Appends a new virtual folder to the end of the list only if it doesn't exists.
void RemoveVirtualFolders (const wxString &folder)
Remove all virtual folders starting with folder.
void ReplaceVirtualFolder (const wxString &oldFolder, const wxString &newFolder)
Replaced the oldFolder with newFolder or appends newFolder to the end of the list if oldFolder is not found.
wxDateTime GetLastModificationTime () const
Returns the last modification time for the file.
void Touch ()
Sets the last modification time for the project to 'now'.
void SetExtendedObjectNamesGeneration (bool ext)
Sets object names generation to extended/normal mode.
bool GetExtendedObjectNamesGeneration () const
Gets object names generation mode (extended/normal).
void SetNotes (const wxString &notes)
Set notes on the project.
const wxString & GetNotes () const
Get notes on the project.
void SetShowNotesOnLoad (bool show)
Set show project notes on load automatically.
bool GetShowNotesOnLoad () const
Get show project notes on load automatically.
void SetCheckForExternallyModifiedFiles (bool check)
Set check for externally modified files.
bool GetCheckForExternallyModifiedFiles () const
Get check for externally modified files.
void ShowNotes (bool nonEmptyOnly, bool editable=false)
Show project notes now.
virtual void SetTitle (const wxString &title)
Changes project title.
virtual TiXmlNode * GetExtensionsNode ()
Access the <Extensions> XML node of this project.
virtual void AddToExtensions (const wxString &stringDesc)
Convenience function (mainly for scripts) to add nodes/attributes under the <Extensions> node.
virtual void ProjectFileRenamed (ProjectFile *pf)
Internal use only.
virtual FilesList & GetFilesList ()
Provides an easy way to iterate all the files belonging in this target.
Public Member Functions inherited from CompileTargetBase
CompileTargetBase ()
virtual ~CompileTargetBase ()
virtual void SetTargetFilenameGenerationPolicy (TargetFilenameGenerationPolicy prefix, TargetFilenameGenerationPolicy extension)
A target's filename can either be auto-generated based on the running platform, or completely specified by the user.
virtual void GetTargetFilenameGenerationPolicy (TargetFilenameGenerationPolicy &prefixOut, TargetFilenameGenerationPolicy &extensionOut) const
virtual const wxString & GetFilename () const
virtual const wxString & GetTitle () const
Read the target's title.
virtual void SetOutputFilename (const wxString &filename)
Set the target's output filename.
virtual void SetImportLibraryFilename (const wxString &filename)
Set the target's import library filename.
virtual void SetDefinitionFileFilename (const wxString &filename)
Set the target's definition file filename.
virtual void SetWorkingDir (const wxString &dirname)
Set the target's working dir on execution (valid only for executable targets)
virtual void SetObjectOutput (const wxString &dirname)
Set the target's objects output dir.
virtual void SetDepsOutput (const wxString &dirname)
Set the target's dependencies output dir.
virtual OptionsRelation GetOptionRelation (OptionsRelationType type) const
Read the target's options relation for type.
virtual void SetOptionRelation (OptionsRelationType type, OptionsRelation rel)
Set the target's options relation for type to rel.
virtual wxString GetWorkingDir ()
Read the target's working dir for execution (valid only for executable targets)
virtual wxString GetObjectOutput () const
Read the target's objects output dir.
virtual wxString GetDepsOutput () const
Read the target's dependencies output dir.
virtual wxString GetOutputFilename ()
Read the target's output filename.
virtual wxString SuggestOutputFilename ()
Suggest a filename based on the target's type.
virtual wxString GetExecutableFilename () const
Read the target's executable filename (produced if target type is ttExecutable)
virtual wxString GetDynamicLibFilename ()
Read the target's dynamic library filename (produced if target type is ttDynamicLib)
virtual wxString GetDynamicLibImportFilename ()
Read the target's dynamic library import filename (produced if target type is ttDynamicLib)
virtual wxString GetDynamicLibDefFilename ()
Read the target's dynamic library definition file filename (produced if target type is ttDynamicLib)
virtual wxString GetStaticLibFilename ()
Read the target's static library filename (produced if target type is ttStaticLib)
virtual wxString GetNativeFilename ()
Read the target's native filename (produced if target type is ttNative)
virtual wxString GetBasePath () const
Read the target's base path, e.g. if GetFilename() returns "/usr/local/bin/xxx", base path will return "/usr/local/bin".
virtual void SetTargetType (TargetType pt)
Set the target's type to pt.
virtual TargetType GetTargetType () const
Read the target's type.
virtual const wxString & GetExecutionParameters () const
Read the target's execution parameters.
virtual void SetExecutionParameters (const wxString &params)
Set the target's execution parameters to params.
virtual const wxString & GetHostApplication () const
Read the target's host application.
virtual void SetHostApplication (const wxString &app)
Set the target's host application to app.
virtual bool GetRunHostApplicationInTerminal () const
Get the flag if the host app should be run in terminal.
virtual void SetRunHostApplicationInTerminal (bool in_terminal)
virtual const wxString & GetCompilerID () const
Read the target's compiler.
virtual wxString GetMakeCommandFor (MakeCommand cmd) const
Get the "make" command used for cmd.
virtual void SetMakeCommandFor (MakeCommand cmd, const wxString &make)
Set the "make" command used for cmd.
virtual bool MakeCommandsModified () const
True if any of the "make" commands is modified.
Public Member Functions inherited from CompileOptionsBase
CompileOptionsBase ()
virtual ~CompileOptionsBase ()
virtual void AddPlatform (int platform)
virtual void RemovePlatform (int platform)
virtual void SetPlatforms (int platforms)
virtual int GetPlatforms () const
virtual bool SupportsCurrentPlatform () const
virtual void SetLinkerOptions (const wxArrayString &linkerOpts)
virtual const wxArrayString & GetLinkerOptions () const
virtual void AddLinkerOption (const wxString &option)
virtual void ReplaceLinkerOption (const wxString &option, const wxString &new_option)
virtual void RemoveLinkerOption (const wxString &option)
virtual void SetLinkLibs (const wxArrayString &linkLibs)
virtual const wxArrayString & GetLinkLibs () const
virtual void AddLinkLib (const wxString &option)
virtual void ReplaceLinkLib (const wxString &option, const wxString &new_option)
virtual void RemoveLinkLib (const wxString &option)
virtual void SetCompilerOptions (const wxArrayString &compilerOpts)
virtual const wxArrayString & GetCompilerOptions () const
virtual void AddCompilerOption (const wxString &option)
virtual void ReplaceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveCompilerOption (const wxString &option)
virtual void SetResourceCompilerOptions (const wxArrayString &resourceCompilerOpts)
virtual const wxArrayString & GetResourceCompilerOptions () const
virtual void AddResourceCompilerOption (const wxString &option)
virtual void ReplaceResourceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveResourceCompilerOption (const wxString &option)
virtual void SetIncludeDirs (const wxArrayString &includeDirs)
virtual const wxArrayString & GetIncludeDirs () const
virtual void AddIncludeDir (const wxString &option)
virtual void ReplaceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveIncludeDir (const wxString &option)
virtual void SetResourceIncludeDirs (const wxArrayString &resIncludeDirs)
virtual const wxArrayString & GetResourceIncludeDirs () const
virtual void AddResourceIncludeDir (const wxString &option)
virtual void ReplaceResourceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveResourceIncludeDir (const wxString &option)
virtual void SetLibDirs (const wxArrayString &libDirs)
virtual const wxArrayString & GetLibDirs () const
virtual void AddLibDir (const wxString &option)
virtual void ReplaceLibDir (const wxString &option, const wxString &new_option)
virtual void RemoveLibDir (const wxString &option)
virtual void SetCommandsBeforeBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsBeforeBuild () const
virtual void AddCommandsBeforeBuild (const wxString &command)
virtual void RemoveCommandsBeforeBuild (const wxString &command)
virtual void SetCommandsAfterBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsAfterBuild () const
virtual void AddCommandsAfterBuild (const wxString &command)
virtual void RemoveCommandsAfterBuild (const wxString &command)
virtual void SetBuildScripts (const wxArrayString &scripts)
virtual const wxArrayString & GetBuildScripts () const
virtual void AddBuildScript (const wxString &script)
virtual void RemoveBuildScript (const wxString &script)
virtual bool GetAlwaysRunPostBuildSteps () const
virtual void SetAlwaysRunPostBuildSteps (bool always)
virtual bool SetVar (const wxString &key, const wxString &value, bool onlyIfExists=false)
virtual bool UnsetVar (const wxString &key)
virtual void UnsetAllVars ()
virtual bool HasVar (const wxString &key) const
virtual const wxString & GetVar (const wxString &key) const
virtual const StringHash & GetAllVars () const
Private Member Functions
void Open ()
void ExpandVirtualBuildTargetGroup (const wxString &alias, wxArrayString &result) const
ProjectBuildTarget * AddDefaultBuildTarget ()
int IndexOfBuildTargetName (const wxString &targetName) const
wxString CreateUniqueFilename ()
void NotifyPlugins (wxEventType type, const wxString &targetName=wxEmptyString, const wxString &oldTargetName=wxEmptyString)
Private Attributes
VirtualBuildTargetsMap m_VirtualTargets
BuildTargets m_Targets
wxString m_ActiveTarget
wxString m_LastSavedActiveTarget
wxString m_DefaultExecuteTarget
wxString m_Makefile
bool m_CustomMakefile
wxString m_MakefileExecutionDir
std::vector< Glob > m_Globs
FilesList m_Files
ProjectFileArray m_FileArray
wxArrayString m_ExpandedNodes
wxArrayString m_SelectedNodes
bool m_Loaded
wxTreeItemId m_ProjectNode
wxArrayString m_VirtualFolders
bool m_CurrentlyLoading
wxString m_CommonTopLevelPath
wxString m_BasePath
PCHMode m_PCHMode
ProjectFiles m_ProjectFilesMap
ProjectBuildTarget * m_CurrentlyCompilingTarget
wxDateTime m_LastModified
bool m_ExtendedObjectNamesGeneration
wxString m_Notes
bool m_AutoShowNotesOnLoad
bool m_CheckForExternallyModifiedFiles
TiXmlElement * m_pExtensionsElement
Additional Inherited Members
Protected Attributes inherited from CompileTargetBase
wxString m_Filename
wxString m_Title
wxString m_OutputFilename
wxString m_ImportLibraryFilename
wxString m_DefinitionFileFilename
wxString m_WorkingDir
wxString m_ObjectOutput
wxString m_DepsOutput
wxString m_ExecutionParameters
wxString m_HostApplication
OptionsRelation m_OptionsRelation [ortLast]
TargetType m_TargetType
wxString m_CompilerId
wxString m_MakeCommands [mcLast]
bool m_MakeCommandsModified
bool m_RunHostApplicationInTerminal
TargetFilenameGenerationPolicy m_PrefixGenerationPolicy
TargetFilenameGenerationPolicy m_ExtensionGenerationPolicy
Protected Attributes inherited from CompileOptionsBase
int m_Platform
wxArrayString m_LinkerOptions
wxArrayString m_LinkLibs
wxArrayString m_CompilerOptions
wxArrayString m_ResourceCompilerOptions
wxArrayString m_IncludeDirs
wxArrayString m_ResIncludeDirs
wxArrayString m_LibDirs
wxArrayString m_CmdsBefore
wxArrayString m_CmdsAfter
wxArrayString m_Scripts
bool m_Modified
bool m_AlwaysRunPostCmds
StringHash m_Vars
Detailed Description
Represents a Code::Blocks project.
A project is a collection of build targets and files. Each project can contain any number of build targets and files.
See also
ProjectBuildTarget, ProjectFile.
Definition at line 96 of file cbproject.h.
Constructor & Destructor Documentation
cbProject()
cbProject::cbProject (const wxString & filename = wxEmptyString)
Constructor.
Definition at line 55 of file cbproject.cpp.
References CreateUniqueFilename(), CompileTargetBase::GetBasePath(), CompilerFactory::GetDefaultCompilerID(), wxFileName::GetName(), wxFileName::GetPathSeparator(), wxString::IsEmpty(), m_BasePath, m_CommonTopLevelPath, m_FileArray, CompileTargetBase::m_Filename, m_Files, m_Loaded, CompileTargetBase::m_Title, Open(), realpath(), Save(), SaveAs(), SetCompilerID(), SetModified(), wxDirExists(), and wxFileExists().
~cbProject()
cbProject::~cbProject ()
Destructor.
Definition at line 111 of file cbproject.cpp.
References ClearAllProperties().
Member Function Documentation
AddBuildTarget()
ProjectBuildTarget * cbProject::AddBuildTarget (const wxString & targetName)
Add a new build target.
Parameters
targetName The build target name.
Returns
The build target that was just created.
Definition at line 1145 of file cbproject.cpp.
References _T, cbEVT_BUILDTARGET_ADDED, cbEVT_PROJECT_TARGETS_MODIFIED, F(), Manager::Get(), GetBuildTarget(), CompileTargetBase::GetCompilerID(), Manager::GetLogManager(), CompileTargetBase::GetOutputFilename(), HasVirtualBuildTarget(), LogManager::LogWarning(), CompileTargetBase::m_Filename, m_Targets, NotifyPlugins(), RemoveVirtualBuildTarget(), CompileTargetBase::SetCompilerID(), CompileTargetBase::SetDepsOutput(), SetModified(), CompileTargetBase::SetObjectOutput(), CompileTargetBase::SetOutputFilename(), CompileTargetBase::SetTitle(), CompileTargetBase::SetWorkingDir(), and wxString::wx_str().
Referenced by AddDefaultBuildTarget(), ProjectLoader::DoBuildTarget(), ProjectOptionsDlg::OnAddBuildTargetClick(), ScriptBindings::RegisterBindings(), Wiz::RunProjectWizard(), and Wiz::RunTargetWizard().
AddDefaultBuildTarget()
ProjectBuildTarget * cbProject::AddDefaultBuildTarget () private
Definition at line 1140 of file cbproject.cpp.
References _T, and AddBuildTarget().
Referenced by AddFile(), Open(), and SaveAs().
AddExpandedNode()
void cbProject::AddExpandedNode (const wxString & path) inline
Convenience function for remembering the project's tree state when refreshing it.
Adds an expanded node in this internal list.
Parameters
path The tree-path to add.
Definition at line 451 of file cbproject.h.
References RestoreTreeState(), and SaveTreeState().
AddFile() [1/2]
ProjectFile * cbProject::AddFile (const wxString & targetName, const wxString & filename, bool compile = true, bool link = true, unsigned short int weight = 50)
Add a file to the project.
This variation, takes a target name as first parameter.
Parameters
targetName The name of the build target to add this file to.
filename The file's filename. This must be a filename relative to the project's path.
compile If true this file is compiled when building the project.
link If true this file is linked when building the project.
weight A value between zero and 100 (defaults to 50). Smaller weight, makes the file compile earlier than those with larger weight.
Returns
The newly added file or NULL if something went wrong.
Definition at line 616 of file cbproject.cpp.
References _T, wxFile::Access(), ProjectFile::AddBuildTarget(), AddDefaultBuildTarget(), wxString::AfterLast(), wxFileName::Assign(), FileFilters::C_EXT, wxString::c_str(), CalculateCommonTopLevelPath(), ProjectFile::compile, ProjectFile::compilerVar, ctCompileObjectCmd, ctCompileResourceCmd, LogManager::DebugLog(), ProjectFile::file, FileTypeOf(), ftObject, ftResource, ftResourceBin, ftSource, ftStaticLib, fvsMissing, fvsReadOnly, ProjectFile::generatedFiles, CompilerTool::generatedFiles, Manager::Get(), CompileTargetBase::GetBasePath(), wxString::GetChar(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), Compiler::GetCompilerTool(), wxArrayString::GetCount(), wxFileName::GetExt(), GetFileByFilename(), wxFileName::GetFullName(), wxFileName::GetFullPath(), Manager::GetLogManager(), Manager::GetMacrosManager(), wxFileName::GetName(), wxFileName::GetPath(), wxFileName::GetVolume(), IndexOfBuildTargetName(), wxFileName::IsAbsolute(), wxString::IsSameAs(), wxString::Length(), ProjectFile::link, wxString::Lower(), m_CommonTopLevelPath, m_CurrentlyLoading, m_FileArray, CompileTargetBase::m_Filename, m_Files, m_ProjectFilesMap, m_Targets, wxFileName::MakeRelativeTo(), wxFileName::Normalize(), realpath(), ProjectFile::relativeFilename, ProjectFile::relativeToCommonTopLevelPath, wxString::Replace(), MacrosManager::ReplaceMacros(), FileFilters::RESOURCE_EXT, wxString::Right(), ProjectFile::SetAutoGeneratedBy(), ProjectFile::SetFileState(), wxFileName::SetFullName(), SetModified(), wxString::StartsWith(), UnixFilename(), wxFile::write, wxFileExists(), wxPATH_NORM_DOTS, and wxPATH_NORM_TILDE.
Referenced by ScriptBindings::cbProject_AddFile(), ProjectManager::DoAddFileToProject(), and ProjectLoader::DoUnits().
AddFile() [2/2]
ProjectFile* cbProject::AddFile (int targetIndex, const wxString & filename, bool compile = true, bool link = true, unsigned short int weight = 50)
Add a file to the project.
This variation, takes a target index as first parameter.
Parameters
targetIndex The index of the build target to add this file to.
filename The file's filename. This must be a filename relative to the project's path.
compile If true this file is compiled when building the project.
link If true this file is linked when building the project.
weight A value between zero and 100 (defaults to 50). Smaller weight, makes the file compile earlier than those with larger weight.
Returns
The newly added file or NULL if something went wrong.
AddToExtensions()
void cbProject::AddToExtensions (const wxString & stringDesc) virtual
Convenience function (mainly for scripts) to add nodes/attributes under the <Extensions> node.
It is mainly useful for scripts that can't otherwise access the XML node. For C++ code, using GetExtensionsNode() is recommended instead (which is much faster).
Parameters
stringDesc A string representation of the nodes/attributes to add/edit under <Extensions>. stringDesc is a string of the form: "node/subnode/.../+subnode:attr=val"
The ":attr=val" part is optional. The node/subnode structure will be created if not there. To set more than one attribute, call this function more than once, using the same node/subnode structure. If a node begins with the "plus" sign (+), then this forces adding a new node instead of re-using the existing one (if any).
Definition at line 1661 of file cbproject.cpp.
References _T, cbU2C(), wxString::GetChar(), GetExtensionsNode(), wxString::IsEmpty(), wxString::Length(), wxString::Mid(), wxString::Remove(), and SetModified().
Referenced by ScriptBindings::RegisterBindings().
AppendUniqueVirtualFolder()
bool cbProject::AppendUniqueVirtualFolder (const wxString & folder)
Appends a new virtual folder to the end of the list only if it doesn't exists.
Returns
True if folder has been appended, false if not.
Definition at line 908 of file cbproject.cpp.
References wxArrayString::Index(), m_VirtualFolders, and wxNOT_FOUND.
Referenced by ProjectManagerUI::BuildProjectTree(), and ProjectManagerUI::CheckForExternallyModifiedProjects().
BeginAddFiles()
void cbProject::BeginAddFiles ()
Notify that file(s) will be added shortly.
This function should be called before calling AddFile(). When done calling AddFile() as many times as needed, call EndAddFiles().
This sequence of function calls ensures proper events dispatching. This function broadcasts the cbEVT_PROJECT_BEGIN_ADD_FILES event.
Definition at line 588 of file cbproject.cpp.
References cbEVT_PROJECT_BEGIN_ADD_FILES, Manager::Get(), and Manager::ProcessEvent().
Referenced by ProjectManager::AddMultipleFilesToProject(), Wiz::CopyFiles(), ProjectLoader::DoUnits(), and Wiz::RunProjectWizard().
BeginRemoveFiles()
void cbProject::BeginRemoveFiles ()
Notify that file(s) will be removed shortly.
This function should be called before calling RemoveFile(). When done calling RemoveFile() as many times as needed, call EndRemoveFiles().
This sequence of function calls ensures proper events dispatching. This function broadcasts the cbEVT_PROJECT_BEGIN_REMOVE_FILES event.
Definition at line 602 of file cbproject.cpp.
References cbEVT_PROJECT_BEGIN_REMOVE_FILES, Manager::Get(), and Manager::ProcessEvent().
Referenced by ProjectManagerUI::OnRemoveFileFromProject().
BuildTargetValid()
bool cbProject::BuildTargetValid (const wxString & name, bool virtuals_too = true) const
Is there a build target (virtual or real) by name?
Parameters
name The build target's name.
virtuals_too Include virtual build targets in query.
Returns
True if exists a build target (virtual or real) by that name, false if not.
Definition at line 1330 of file cbproject.cpp.
References HasVirtualBuildTarget(), and IndexOfBuildTargetName().
Referenced by DebuggerGDB::DoDebug(), DebuggerManager::FindTargetsDebugger(), ScriptBindings::RegisterBindings(), and SetActiveBuildTarget().
CalculateCommonTopLevelPath()
void cbProject::CalculateCommonTopLevelPath ()
Calculates the top-level path common to all project files.
This is called automatically (no need for you to call it) and is used to find the top-level folder for building the tree.
Definition at line 315 of file cbproject.cpp.
References _T, cbC2U(), LogManager::DebugLog(), LogManager::DebugLogError(), F(), ProjectFile::file, Manager::Get(), CompileTargetBase::GetBasePath(), wxString::GetChar(), wxFileName::GetDirCount(), wxFileName::GetFullPath(), Manager::GetLogManager(), wxFileName::GetPath(), wxFileName::GetPathSeparator(), wxFileName::GetVolume(), wxString::IsSameAs(), wxString::Left(), wxString::Length(), m_BasePath, m_CommonTopLevelPath, m_Files, wxFileName::MakeRelativeTo(), wxFileName::Normalize(), ProjectFile::relativeFilename, ProjectFile::relativeToCommonTopLevelPath, HTMLTags::sep, ProjectFile::SetObjName(), wxString::StartsWith(), wxStopWatch::Time(), and wxPATH_NORM_DOTS.
Referenced by AddFile(), ProjectManagerUI::OnRemoveFileFromProject(), Open(), ProjectFile::Rename(), and SaveAs().
CanAddToVirtualBuildTarget()
bool cbProject::CanAddToVirtualBuildTarget (const wxString & alias, const wxString & target)
Checks if a build target (virtual or real) can be added to a virtual build target, without causing a circular-reference.
Parameters
alias The "parent" virtual build target to add the build target in.
target The build target to add in the alias virtual build target.
Returns
True if a circular reference is not detected, false if it is.
Definition at line 1514 of file cbproject.cpp.
References wxArrayString::GetCount(), GetVirtualBuildTargetGroup(), HasVirtualBuildTarget(), wxArrayString::Index(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ClearAllProperties()
void cbProject::ClearAllProperties ()
This resets the project to a clear state.
Like it's just been new'ed.
Definition at line 236 of file cbproject.cpp.
References cbEVT_BUILDTARGET_SELECTED, wxArrayString::Clear(), Delete(), CompileOptionsBase::m_CompilerOptions, m_FileArray, m_Files, CompileOptionsBase::m_IncludeDirs, CompileOptionsBase::m_LibDirs, CompileOptionsBase::m_LinkerOptions, m_pExtensionsElement, m_Targets, NotifyPlugins(), and SetModified().
Referenced by ~cbProject().
CloseAllFiles()
bool cbProject::CloseAllFiles (bool dontsave = false)
Close all project files.
Parameters
dontsave If true, no project file will be saved even if modified. If false, any modified file will be saved (default).
Returns
True if successful, false otherwise.
Definition at line 1089 of file cbproject.cpp.
References EditorManager::Close(), ProjectFile::file, Manager::Get(), Manager::GetEditorManager(), wxFileName::GetFullPath(), EditorManager::HideNotebook(), m_FileArray, m_Files, QueryCloseAllFiles(), and EditorManager::ShowNotebook().
Referenced by ProjectManager::CloseProject(), and ScriptBindings::RegisterBindings().
CreateUniqueFilename()
wxString cbProject::CreateUniqueFilename () private
Definition at line 203 of file cbproject.cpp.
References _(), _T, wxString::Clear(), FileFilters::CODEBLOCKS_EXT, wxString::Format(), Manager::Get(), CompileTargetBase::GetFilename(), Manager::GetProjectManager(), and ProjectManager::GetProjects().
Referenced by cbProject().
DefineVirtualBuildTarget()
bool cbProject::DefineVirtualBuildTarget (const wxString & alias, const wxArrayString & targets)
Define a new virtual build target.
A virtual build target is not really a build target itself but it is an alias for a group of other build targets, real or virtual. An example is the "All" virtual build target which means "all build targets".
Parameters
alias The virtual build target's name.
targets A list of build target names to include in this virtual build target. They can be real or other virtual build targets.
Returns
True for success, false for failure. The only reason for this function to return false is if a real build target exists with the same name as alias (or if you pass an empty targets array).
Note
Every time you call this function with the same alias parameter, the virtual build target is re-defined. In other words, it's not an error if alias is already defined.
Definition at line 1444 of file cbproject.cpp.
References _T, cbEVT_PROJECT_TARGETS_MODIFIED, F(), Manager::Get(), GetBuildTarget(), wxArrayString::GetCount(), Manager::GetLogManager(), LogManager::LogWarning(), m_VirtualTargets, NotifyPlugins(), SetModified(), and wxString::wx_str().
Referenced by ProjectLoader::DoVirtualTargets(), ProjectLoader::Open(), ScriptBindings::RegisterBindings(), and VirtualBuildTargetsDlg::SetVirtualTarget().
DuplicateBuildTarget() [1/2]
ProjectBuildTarget * cbProject::DuplicateBuildTarget (int index, const wxString & newName = wxEmptyString)
Duplicate a build target.
Parameters
index The index of the build target to duplicate.
newName The name for the new build target. If empty, it will be named like "Copy of <base_target_name>".
Returns
The new build target if index was valid, NULL if not (or something went wrong).
Definition at line 1211 of file cbproject.cpp.
References _(), ProjectFile::AddBuildTarget(), cbEVT_BUILDTARGET_ADDED, cbEVT_PROJECT_TARGETS_MODIFIED, GetBuildTarget(), ProjectBuildTarget::GetFilesList(), CompileTargetBase::GetTitle(), wxString::IsEmpty(), m_Targets, NotifyPlugins(), SetModified(), and CompileTargetBase::SetTitle().
Referenced by ScriptBindings::cbProject_DuplicateBuildTarget(), DuplicateBuildTarget(), and ProjectOptionsDlg::OnCopyBuildTargetClick().
DuplicateBuildTarget() [2/2]
ProjectBuildTarget * cbProject::DuplicateBuildTarget (const wxString & targetName, const wxString & newName = wxEmptyString)
Duplicate a build target.
Parameters
targetName The name of the build target to duplicate.
newName The name for the new build target. If empty, it will be named like "Copy of <base_target_name>".
Returns
The new build target if index was valid, NULL if not (or something went wrong).
Definition at line 1236 of file cbproject.cpp.
References DuplicateBuildTarget(), and IndexOfBuildTargetName().
EndAddFiles()
void cbProject::EndAddFiles ()
Notify that file(s) addition finished.
This function should be called when done calling AddFile() as many times as needed.
This sequence of function calls ensures proper events dispatching. This function broadcasts the cbEVT_PROJECT_END_ADD_FILES event.
See also
BeginAddFiles().
Definition at line 595 of file cbproject.cpp.
References cbEVT_PROJECT_END_ADD_FILES, Manager::Get(), and Manager::ProcessEvent().
Referenced by ProjectManager::AddMultipleFilesToProject(), Wiz::CopyFiles(), ProjectLoader::DoUnits(), and Wiz::RunProjectWizard().
EndRemoveFiles()
void cbProject::EndRemoveFiles ()
Notify that file(s) removal finished.
This function should be called when done calling RemoveFile() as many times as needed.
This sequence of function calls ensures proper events dispatching. This function broadcasts the cbEVT_PROJECT_END_REMOVE_FILES event.
See also
BeginRemoveFiles().
Definition at line 609 of file cbproject.cpp.
References cbEVT_PROJECT_END_REMOVE_FILES, Manager::Get(), and Manager::ProcessEvent().
Referenced by ProjectManagerUI::OnRemoveFileFromProject().
ExpandedNodes()
const wxArrayString& cbProject::ExpandedNodes () inline
Convenience function for remembering the project's tree state when refreshing it.
Returns
An array of strings containing the tree-path names of expanded nodes.
Definition at line 445 of file cbproject.h.
Referenced by ProjectLayoutLoader::Save().
ExpandVirtualBuildTargetGroup()
void cbProject::ExpandVirtualBuildTargetGroup (const wxString & alias, wxArrayString & result) const private
Definition at line 1543 of file cbproject.cpp.
References wxArrayString::Add(), wxArrayString::GetCount(), GetVirtualBuildTargetGroup(), wxArrayString::Index(), IndexOfBuildTargetName(), and wxNOT_FOUND.
Referenced by GetExpandedVirtualBuildTargetGroup().
ExportTargetAsProject() [1/2]
bool cbProject::ExportTargetAsProject (int index)
Export a target as a new project.
In other words, save a copy of the project containing only the specified target. The user will be prompted with a dialog to select the new project name.
Parameters
index The index of the build target to export.
Returns
True on success, false on failure (or dialog cancellation).
Note
The dialog to select the new project name is not a file dialog because the user is not allowed to save anywhere. The new project must remain "operational" (assuming the target to export, was "operational") so the new project must be saved in the same directory as the original to preserve relative paths.
Definition at line 1241 of file cbproject.cpp.
References GetBuildTarget(), and CompileTargetBase::GetTitle().
Referenced by ScriptBindings::cbProject_ExportTargetAsProject(), and ProjectOptionsDlg::OnExportTargetClick().
ExportTargetAsProject() [2/2]
bool cbProject::ExportTargetAsProject (const wxString & targetName)
Export a target as a new project.
In other words, save a copy of the project containing only the specified target. The user will be prompted with a dialog to select the new project name.
Parameters
targetName The name of the build target to export.
Returns
True on success, false on failure (or dialog cancellation).
See also
ExportTargetAsProject(int).
Definition at line 1249 of file cbproject.cpp.
References _(), cbGetTextFromUser(), ProjectLoader::ExportTargetAsProject(), GetBuildTarget(), CompileTargetBase::GetFilename(), wxFileName::GetFullPath(), GetModified(), CompileTargetBase::GetTitle(), wxString::IsEmpty(), m_pExtensionsElement, Save(), SetModified(), wxFileName::SetName(), and SetTitle().
GetActiveBuildTarget()
const wxString & cbProject::GetActiveBuildTarget () const
Returns
The active build target name. Note that this might be a virtual target.
Definition at line 1368 of file cbproject.cpp.
References m_ActiveTarget.
Referenced by NativeParser::AddProjectDefinedMacros(), CodeBlocksApp::BatchJob(), EditorManager::CollectDefines(), DebuggerGDB::Debug(), FilePathPanel::FilePathPanel(), FindReplaceDlg::FindReplaceDlg(), DebuggerManager::FindTargetsDebugger(), FindReplaceDlg::OnSearchProject(), ScriptBindings::RegisterBindings(), MacrosManager::ReplaceMacros(), and ProjectLayoutLoader::Save().
GetBuildTarget() [1/2]
ProjectBuildTarget * cbProject::GetBuildTarget (int index)
Access a build target.
Parameters
index The build target index. Must be greater or equal to zero and less than GetBuildTargetsCount().
Returns
The build target or NULL if not found.
Definition at line 1387 of file cbproject.cpp.
References m_Targets.
Referenced by ProjectFile::AddBuildTarget(), AddBuildTarget(), NativeParser::AddCompilerDirs(), NativeParser::AddProjectDefinedMacros(), ProjectManagerUI::AskForBuildTargetIndex(), ProjectManagerUI::AskForMultiBuildTargetIndex(), CodeBlocksApp::BatchJob(), ProjectOptionsDlg::BuildScriptsTree(), ScriptBindings::cbProject_GetBuildTarget(), VirtualBuildTargetsDlg::CheckTargets(), EditorManager::CollectDefines(), CompilerOptionsDlg::CompilerOptionsDlg(), ProjectLoader::ConvertVersion_Pre_1_1(), DefineVirtualBuildTarget(), ProjectManager::DoAddFileToProject(), ProjectOptionsDlg::DoBeforeTargetChange(), CompilerGCC::DoBuild(), DebuggerGDB::DoDebug(), CompilerOptionsDlg::DoFillTree(), ProjectOptionsDlg::DoTargetChange(), ProjectLoader::DoUnitOptions(), DuplicateBuildTarget(), SelectTargetDlg::EndModal(), CompilerGCC::ExpandTargets(), ProjectLoader::ExportTargetAsProject(), ExportTargetAsProject(), FilePathPanel::FilePathPanel(), ProjectOptionsDlg::FillBuildTargets(), ProjectOptionsDlg::FillScripts(), FindReplace::FindInFiles(), FindReplaceDlg::FindReplaceDlg(), DebuggerManager::FindTargetsDebugger(), GetBuildTarget(), DirectCommands::GetCleanCommands(), DirectCommands::GetCompileCommands(), NativeParser::GetCompilerStandardGCC(), DirectCommands::GetLinkCommands(), SelectTargetDlg::GetSelectionTarget(), CompilerGCC::GetTargetIndexFromName(), CompilerCommandGenerator::Init(), CompilerGCC::IsValidTarget(), DebuggerOptionsProjectDlg::LoadCurrentRemoteDebuggingRecord(), TemplateManager::NewProjectFromUserTemplate(), VirtualBuildTargetsDlg::OnAddClick(), ProjectOptionsDlg::OnAddScript(), ProjectOptionsDlg::OnBuildOrderClick(), DebuggerOptionsProjectDlg::OnBuildTargetAdded(), DebuggerOptionsProjectDlg::OnBuildTargetRemoved(), ProjectOptionsDlg::OnCheckScripts(), CompilerGCC::OnCompileFileRequest(), ProjectOptionsDlg::OnCopyBuildTargetClick(), CompilerOptionsDlg::OnCopyDirsClick(), CompilerOptionsDlg::OnCopyLibsClick(), ProjectOptionsDlg::OnCreateDefFileClick(), ProjectOptionsDlg::OnCreateImportFileClick(), ProjectOptionsDlg::OnEditBuildTargetClick(), VirtualBuildTargetsDlg::OnEditClick(), ProjectOptionsDlg::OnEditDepsClick(), ProjectOptionsDlg::OnExportTargetClick(), ProjectOptionsDlg::OnFileMarkOffClick(), ProjectOptionsDlg::OnFileMarkOnClick(), ProjectOptionsDlg::OnFileToggleMarkClick(), WizBuildTargetPanel::OnPageChanging(), CompilerGCC::OnProjectCompilerOptions(), DebuggerGDB::OnProjectLoadingHook(), ProjectOptionsDlg::OnProjectTypeChanged(), ProjectOptionsDlg::OnRemoveScript(), ProjectOptionsDlg::OnScriptMoveDown(), ProjectOptionsDlg::OnScriptMoveUp(), FindReplaceDlg::OnSearchProject(), ProjectOptionsDlg::OnTargetBuildOptionsClick(), ProjectLoader::Open(), CompilerGCC::PreprocessJob(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), MacrosManager::RecalcVars(), ProjectFile::RemoveBuildTarget(), RemoveBuildTarget(), RenameBuildTarget(), ReOrderTargets(), FindReplace::ReplaceInFiles(), MacrosManager::ReplaceMacros(), DebuggerOptionsProjectDlg::SaveCurrentRemoteDebuggingRecord(), EditorManager::SwapActiveHeaderSource(), CompilerOptionsDlg::UpdateCompilerForTargets(), ProjectFile::UpdateFileDetails(), CompilerGCC::UpdateProjectTargets(), SelectTargetDlg::UpdateSelected(), and ProjectOptionsDlg::ValidateTargetName().
GetBuildTarget() [2/2]
ProjectBuildTarget * cbProject::GetBuildTarget (const wxString & targetName)
Access a build target.
Parameters
targetName The build target name.
Returns
The build target or NULL if not found.
Definition at line 1394 of file cbproject.cpp.
References GetBuildTarget(), and IndexOfBuildTargetName().
GetBuildTargetsCount()
int cbProject::GetBuildTargetsCount () inline
Returns
The number of build targets this project contains.
Definition at line 200 of file cbproject.h.
References wxEmptyString.
Referenced by NativeParser::AddCompilerDirs(), ProjectManagerUI::AskForBuildTargetIndex(), ProjectManagerUI::AskForMultiBuildTargetIndex(), CodeBlocksApp::BatchJob(), ProjectOptionsDlg::BuildScriptsTree(), VirtualBuildTargetsDlg::CheckTargets(), CompilerOptionsDlg::CompilerOptionsDlg(), ProjectLoader::ConvertVersion_Pre_1_1(), Wiz::CopyFiles(), ProjectManager::DoAddFileToProject(), CompilerOptionsDlg::DoFillTree(), ProjectLoader::DoUnitOptions(), ProjectLoader::ExportTargetAsProject(), FilePathPanel::FilePathPanel(), ProjectOptionsDlg::FillBuildTargets(), FindReplaceDlg::FindReplaceDlg(), DirectCommands::GetCleanCommands(), DirectCommands::GetCompileCommands(), NativeParser::GetCompilerStandardGCC(), DirectCommands::GetLinkCommands(), CompilerGCC::GetTargetIndexFromName(), CompilerCommandGenerator::Init(), TemplateManager::NewProjectFromUserTemplate(), ProjectManagerUI::OnAddFilesToProjectRecursively(), ProjectManagerUI::OnAddFileToProject(), ProjectOptionsDlg::OnBuildOrderClick(), ProjectOptionsDlg::OnCheckScripts(), CompilerOptionsDlg::OnCopyDirsClick(), CompilerOptionsDlg::OnCopyLibsClick(), FindReplaceDlg::OnSearchProject(), ProjectLoader::Open(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), Wiz::RunProjectWizard(), SelectTarget(), EditorManager::SwapActiveHeaderSource(), CompilerOptionsDlg::UpdateCompilerForTargets(), ProjectFile::UpdateFileDetails(), and CompilerGCC::UpdateProjectTargets().
GetCheckForExternallyModifiedFiles()
bool cbProject::GetCheckForExternallyModifiedFiles () const
Get check for externally modified files.
Returns
True if check for externally modified files is set, false if not.
Definition at line 1623 of file cbproject.cpp.
References m_CheckForExternallyModifiedFiles.
Referenced by EditorManager::CheckForExternallyModifiedFiles(), ProjectLoader::ExportTargetAsProject(), and ScriptBindings::RegisterBindings().
GetCommonTopLevelPath()
wxString cbProject::GetCommonTopLevelPath () const
Returns
the top-level path common to all project files.
Definition at line 418 of file cbproject.cpp.
References m_CommonTopLevelPath.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects(), DebuggerGDB::DoDebug(), CompilerErrors::DoGotoError(), NativeParser::GetAllPathsByFilename(), CodeCompletion::GetSystemIncludeDirs(), CompilerCommandGenerator::Init(), SelectTargetDlg::OnHostApplicationButtonClick(), ProjectManagerUI::OnRemoveFileFromProject(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), TemplateManager::SaveUserTemplate(), and ProjectManagerUI::ShowMenu().
GetCurrentlyCompilingTarget()
ProjectBuildTarget* cbProject::GetCurrentlyCompilingTarget () inline
Get a pointer to the currently compiling target.
Returns
While the project is being built, this function returns the currently building target. For all other times, NULL is returned.
Definition at line 478 of file cbproject.h.
Referenced by cbEditor::AddToContextMenu(), ProjectManager::CloseProject(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), MainFrame::OnApplicationClose(), ProjectManagerUI::OnCloseProject(), MainFrame::OnFileMenuUpdateUI(), ProjectManagerUI::OnKeyDown(), DebuggerMenuHandler::OnUpdateUI(), DebuggerToolbarHandler::OnUpdateUI(), ProjectManagerUI::QueryCloseProject(), ScriptBindings::RegisterBindings(), MacrosManager::ReplaceMacros(), ProjectManagerUI::ShowMenu(), and cbDebuggerPlugin::ToolMenuEnabled().
GetDefaultExecuteTarget()
const wxString & cbProject::GetDefaultExecuteTarget () const
Returns
The build target index which will be pre-selected when the "Select target" dialog appears when running the project. Valid only for multi-target projects.
Definition at line 1382 of file cbproject.cpp.
References m_DefaultExecuteTarget.
Referenced by ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), and SelectTargetDlg::UpdateSelected().
GetExecutionDir()
wxString cbProject::GetExecutionDir ()
Returns
Either the execution directory for the custom Makefile or the projects base path. Defaults to the projects base path, if no custom makefile is used. Used to unify the call to the function.
Definition at line 1018 of file cbproject.cpp.
References CompileTargetBase::GetBasePath(), GetMakefileExecutionDir(), and m_CustomMakefile.
Referenced by CompilerQueue::Add(), and CompilerGCC::AddOutputLine().
GetExpandedVirtualBuildTargetGroup()
wxArrayString cbProject::GetExpandedVirtualBuildTargetGroup (const wxString & alias) const
Access a virtual build target's expanded group of build targets.
The difference from GetVirtualBuildTargetGroup() lies in that this function returns the full list of real build targets in this group (by recursively expanding virtual build targets in the group).
Parameters
alias The virtual build target's name.
Returns
The expanded list of all real build targets under the alias alias.
Definition at line 1502 of file cbproject.cpp.
References ExpandVirtualBuildTargetGroup(), and m_VirtualTargets.
Referenced by NativeParser::AddProjectDefinedMacros(), CompilerGCC::ExpandTargets(), and ScriptBindings::RegisterBindings().
GetExtendedObjectNamesGeneration()
bool cbProject::GetExtendedObjectNamesGeneration () const
Gets object names generation mode (extended/normal).
Returns
True for extended mode, false for normal mode.
See also
SetExtendedObjectNamesGeneration.
Definition at line 1581 of file cbproject.cpp.
References m_ExtendedObjectNamesGeneration.
Referenced by ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), ProjectFile::SetObjName(), and pfDetails::Update().
GetExtensionsNode()
TiXmlNode * cbProject::GetExtensionsNode () virtual
Access the <Extensions> XML node of this project.
This function is for advanced users only. Use at your own risk (and respect other plugins authors work under this node).
Returns
The <Extensions> XML node.
Note
This function will never return NULL.
Definition at line 1654 of file cbproject.cpp.
References _T, cbU2C(), and m_pExtensionsElement.
Referenced by AddToExtensions().
GetFile()
ProjectFile * cbProject::GetFile (int index)
Access a file of the project.
Parameters
index The index of the file. Must be greater or equal than zero and less than GetFilesCount().
Returns
A pointer to the file or NULL if not found.
Definition at line 1026 of file cbproject.cpp.
References m_FileArray, m_Files, and NULL.
Referenced by ScriptBindings::RegisterBindings().
GetFileByFilename()
ProjectFile * cbProject::GetFileByFilename (const wxString & filename, bool isRelative = true, bool isUnixFilename = false)
Access a file of the project.
Parameters
filename The filename of the file.
isRelative True if filename is a relative filename, false if not.
isUnixFilename True if filename is already normalized with UnixFilename(), false if not.
Returns
A pointer to the file or NULL if not found.
Definition at line 1044 of file cbproject.cpp.
References _T, CompileTargetBase::GetBasePath(), wxFileName::GetFullPath(), m_ProjectFilesMap, wxFileName::MakeRelativeTo(), realpath(), wxString::Remove(), wxString::StartsWith(), and UnixFilename().
Referenced by AddFile(), ProjectOptionsDlg::DoBeforeTargetChange(), CodeCompletion::DoCodeCompleteIncludes(), CompilerErrors::DoGotoError(), CodeRefactoring::DoRenameSymbols(), ProjectOptionsDlg::DoTargetChange(), ProjectManager::FindProjectForFile(), NativeParser::GetProjectByFilename(), EditorManager::OnAddFileToProject(), CompilerGCC::OnCompileFileRequest(), cbEditor::OnContextMenuEntry(), ProjectOptionsDlg::OnFileMarkOffClick(), ProjectOptionsDlg::OnFileMarkOnClick(), MainFrame::OnFileNewWhat(), ProjectOptionsDlg::OnFileOptionsClick(), ProjectOptionsDlg::OnFileToggleMarkClick(), CodeCompletion::OnRealtimeParsingTimer(), ProjectManagerUI::OnRemoveFileFromProject(), ProjectLayoutLoader::Open(), ScriptBindings::RegisterBindings(), Wiz::RunProjectWizard(), EditorManager::SwapActiveHeaderSource(), and cbDebuggerPlugin::SyncEditor().
GetFilesCount()
int cbProject::GetFilesCount () inline
Returns
The number of files in the project.
Definition at line 142 of file cbproject.h.
Referenced by CodeCompletion::OnProjectActivated(), ScriptBindings::RegisterBindings(), and TemplateManager::SaveUserTemplate().
GetFilesList()
virtual FilesList& cbProject::GetFilesList () inline virtual
Provides an easy way to iterate all the files belonging in this target.
Returns
A list of files belonging in this target.
Definition at line 685 of file cbproject.h.
References wxEmptyString.
Referenced by NativeParser::AddProjectToParser(), ProjectManagerUI::BuildProjectTree(), ProjectManagerUI::CheckForExternallyModifiedProjects(), EditorManager::CollectDefines(), CodeCompletion::DoCodeCompleteIncludes(), NativeParser::DoFullParsing(), CompilerErrors::DoGotoError(), MarkFileAsLocalThreadedTask::Execute(), ProjectLoader::ExportTargetAsProject(), FindReplace::FindInFiles(), CodeRefactoring::GetAllProjectFiles(), DirectCommands::GetProjectFilesSortedByWeight(), ClassBrowserBuilderThread::Init(), ProjectManagerUI::OnAddFileToProject(), ProjectManagerUI::OnGotoFile(), CodeCompletion::OnOpenIncludeFile(), MacrosManager::RecalcVars(), NativeParser::RemoveProjectFromParser(), FindReplace::ReplaceInFiles(), Wiz::RunTargetWizard(), ProjectLayoutLoader::Save(), TemplateManager::SaveUserTemplate(), CompilerMINGWGenerator::SetupIncludeDirs(), and EditorManager::SwapActiveHeaderSource().
GetFirstValidBuildTargetName()
wxString cbProject::GetFirstValidBuildTargetName (bool virtuals_too = true) const
Returns
The first valid (virtual or real) build target.
Definition at line 1340 of file cbproject.cpp.
References CompileTargetBase::GetTitle(), m_Targets, m_VirtualTargets, and wxEmptyString.
Referenced by ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), and SetActiveBuildTarget().
GetGlobs()
std::vector< cbProject::Glob > cbProject::GetGlobs () const
Retrieve the current globs from the project.
Returns
globs the globs to add to the project.
Definition at line 1745 of file cbproject.cpp.
References m_Globs.
Referenced by ProjectLoader::ExportTargetAsProject().
GetLastModificationTime()
wxDateTime cbProject::GetLastModificationTime () const inline
Returns the last modification time for the file.
Used to detect modifications outside the Program.
Definition at line 569 of file cbproject.h.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects().
GetMakefile()
const wxString & cbProject::GetMakefile ()
Returns
The filename for the Makefile.
Definition at line 983 of file cbproject.cpp.
References _T, wxFileName::Assign(), CompileTargetBase::GetBasePath(), wxFileName::GetFullPath(), wxString::IsEmpty(), CompileTargetBase::m_Filename, m_Makefile, wxFileName::MakeRelativeTo(), wxFileName::SetExt(), and wxFileName::SetName().
Referenced by ProjectLoader::ExportTargetAsProject(), CompilerGCC::GetMakeCommandFor(), MacrosManager::RecalcVars(), and ScriptBindings::RegisterBindings().
GetMakefileExecutionDir()
wxString cbProject::GetMakefileExecutionDir ()
Returns
The execution directory for the custom Makefile. Defaults to the projects base path, if no custom makefile is used.
Definition at line 1008 of file cbproject.cpp.
References CompileTargetBase::GetBasePath(), wxFileName::GetFullPath(), wxString::IsEmpty(), and m_MakefileExecutionDir.
Referenced by ProjectLoader::ExportTargetAsProject(), and GetExecutionDir().
GetModeForPCH()
PCHMode cbProject::GetModeForPCH () const inline
Returns
The mode precompiled headers are handled.
Definition at line 301 of file cbproject.h.
Referenced by ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), ProjectFile::SetObjName(), CompilerMINGWGenerator::SetupIncludeDirs(), and pfDetails::Update().
GetModified()
bool cbProject::GetModified () const virtual
Returns
True if the project is modified in any way.
Reimplemented from CompileOptionsBase.
Definition at line 162 of file cbproject.cpp.
References CompileOptionsBase::GetModified(), and m_Targets.
Referenced by CodeCompletion::DoCodeCompleteIncludes(), ExportTargetAsProject(), CompilerCommandGenerator::Init(), MainFrame::OnFileMenuUpdateUI(), MainFrame::OnProjectMenuUpdateUI(), ProjectManagerUI::QueryCloseProject(), ScriptBindings::RegisterBindings(), and ProjectManager::SaveAllProjects().
GetNotes()
const wxString & cbProject::GetNotes () const
Get notes on the project.
Returns
Simple text notes about the project.
Definition at line 1595 of file cbproject.cpp.
References m_Notes.
Referenced by ProjectManager::EndLoadingWorkspace(), ProjectLoader::ExportTargetAsProject(), and ScriptBindings::RegisterBindings().
GetProjectNode()
wxTreeItemId cbProject::GetProjectNode () inline
Returns
The root item of this project in the project manager's tree.
Definition at line 311 of file cbproject.h.
Referenced by ProjectManagerUI::BuildProjectTree(), ProjectManagerUI::CheckForExternallyModifiedProjects(), ProjectManagerUI::FinishLoadingProject(), ProjectManagerUI::FinishLoadingWorkspace(), ProjectManagerUI::MoveProjectDown(), ProjectManagerUI::MoveProjectUp(), ProjectOptionsDlg::OnCreateImportFileClick(), ProjectManagerUI::RemoveProject(), Wiz::RunProjectWizard(), and ProjectManagerUI::UpdateActiveProject().
GetShowNotesOnLoad()
bool cbProject::GetShowNotesOnLoad () const
Get show project notes on load automatically.
Returns
True if show project notes on load is set, false if not.
Definition at line 1609 of file cbproject.cpp.
References m_AutoShowNotesOnLoad.
Referenced by ProjectManager::EndLoadingProject(), ProjectManager::EndLoadingWorkspace(), ProjectLoader::ExportTargetAsProject(), and ScriptBindings::RegisterBindings().
GetVirtualBuildTargetGroup()
const wxArrayString & cbProject::GetVirtualBuildTargetGroup (const wxString & alias) const
Access a virtual build target's group of build targets.
Parameters
alias The virtual build target's name.
Returns
The list of all build targets under the alias alias.
Definition at line 1491 of file cbproject.cpp.
References m_VirtualTargets.
Referenced by CanAddToVirtualBuildTarget(), VirtualBuildTargetsDlg::CheckTargets(), ExpandVirtualBuildTargetGroup(), ProjectLoader::ExportTargetAsProject(), and ScriptBindings::RegisterBindings().
GetVirtualBuildTargets()
wxArrayString cbProject::GetVirtualBuildTargets () const
Get a list of all defined virtual build targets.
Returns
A list of all defined virtual build targets.
Definition at line 1482 of file cbproject.cpp.
References wxArrayString::Add(), and m_VirtualTargets.
Referenced by ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), and CompilerGCC::UpdateProjectTargets().
GetVirtualFolders()
const wxArrayString & cbProject::GetVirtualFolders () const
Get a list of the virtual folders.
Normally used by the project loader only.
Definition at line 903 of file cbproject.cpp.
References m_VirtualFolders.
Referenced by ProjectManagerUI::BuildProjectTree(), ProjectManagerUI::CheckForExternallyModifiedProjects(), and ProjectLoader::ExportTargetAsProject().
HasVirtualBuildTarget()
bool cbProject::HasVirtualBuildTarget (const wxString & alias) const
Does a virtual build target exist?
Parameters
alias The virtual build target's name.
Returns
True if the virtual build target exists, false if not.
Definition at line 1465 of file cbproject.cpp.
References m_VirtualTargets.
Referenced by AddBuildTarget(), BuildTargetValid(), CanAddToVirtualBuildTarget(), ProjectLoader::Open(), ScriptBindings::RegisterBindings(), and ProjectOptionsDlg::ValidateTargetName().
IndexOfBuildTargetName()
int cbProject::IndexOfBuildTargetName (const wxString & targetName) const private
Definition at line 1319 of file cbproject.cpp.
References CompileTargetBase::GetTitle(), m_Targets, and wxString::Matches().
Referenced by AddFile(), BuildTargetValid(), DuplicateBuildTarget(), ExpandVirtualBuildTargetGroup(), GetBuildTarget(), RemoveBuildTarget(), and RenameBuildTarget().
IsLoaded()
bool cbProject::IsLoaded () const inline
Returns
True if the project fully loaded, false if not.
Definition at line 105 of file cbproject.h.
References CompileOptionsBase::GetModified(), and CompileOptionsBase::SetModified().
Referenced by ProjectManager::LoadProject().
IsMakefileCustom()
bool cbProject::IsMakefileCustom () inline
Returns
True if the project is using a custom Makefile for compilation, false if not.
Definition at line 159 of file cbproject.h.
Referenced by CompilerOptionsDlg::CompilerOptionsDlg(), ProjectLoader::ExportTargetAsProject(), CompilerOptionsDlg::OnTreeSelectionChange(), ScriptBindings::RegisterBindings(), and CompilerGCC::UseMake().
LoadLayout()
bool cbProject::LoadLayout ()
Load the project's layout.
See also
SaveLayout() for info.
Returns
True if successful, false otherwise.
Definition at line 508 of file cbproject.cpp.
References _T, EditorBase::Activate(), LogManager::DebugLog(), ProjectFile::editorOpen, ProjectFile::editorTabPos, ProjectFile::file, Manager::Get(), Manager::GetConfigManager(), Manager::GetEditorManager(), Manager::GetFileManager(), wxFileName::GetFullPath(), Manager::GetLogManager(), ProjectLayoutLoader::GetTopProjectFile(), EditorManager::HideNotebook(), wxString::IsEmpty(), FileManager::Load(), ProjectLayoutLoader::LoadNotebookLayout(), CompileTargetBase::m_Filename, m_Files, ProjectLayoutLoader::Open(), EditorManager::Open(), ConfigManager::ReadBool(), ConfigManager::ReadInt(), wxFileName::SetExt(), cbEditor::SetProjectFile(), EditorManager::ShowNotebook(), and wxFileExists().
Referenced by ProjectManager::EndLoadingProject(), and ScriptBindings::RegisterBindings().
NotifyPlugins()
void cbProject::NotifyPlugins (wxEventType type, const wxString & targetName = wxEmptyString, const wxString & oldTargetName = wxEmptyString) private
Definition at line 120 of file cbproject.cpp.
References Manager::Get(), and Manager::ProcessEvent().
Referenced by AddBuildTarget(), ClearAllProperties(), DefineVirtualBuildTarget(), DuplicateBuildTarget(), RemoveBuildTarget(), RemoveVirtualBuildTarget(), RenameBuildTarget(), Save(), SaveAs(), SetActiveBuildTarget(), and SetTitle().
Open()
void cbProject::Open () private
Definition at line 260 of file cbproject.cpp.
References _(), AddDefaultBuildTarget(), wxString::c_str(), CalculateCommonTopLevelPath(), cbMessageBox(), Delete(), wxFileName::DirExists(), InfoWindow::Display(), wxFileName::FileExists(), ProjectLoader::FileModified(), FileTypeOf(), ProjectLoader::FileUpgraded(), ftCodeBlocksProject, Manager::Get(), Manager::GetLogManager(), wxFileName::GetModificationTime(), Manager::IsBatchBuild(), LogManager::Log(), m_CurrentlyLoading, CompileTargetBase::m_Filename, m_LastModified, m_Loaded, m_pExtensionsElement, m_ProjectFilesMap, m_Targets, CompileTargetBase::m_Title, ProjectLoader::Open(), wxString::Printf(), SetModified(), wxCENTRE, wxICON_ERROR, and wxOK.
Referenced by cbProject().
ProjectFileRenamed()
void cbProject::ProjectFileRenamed (ProjectFile * pf) virtual
Internal use only.
Updates the internal hashmap of project files.
Definition at line 1725 of file cbproject.cpp.
References ProjectFile::file, wxFileName::GetFullPath(), m_ProjectFilesMap, and UnixFilename().
Referenced by ProjectFile::Rename().
QueryCloseAllFiles()
bool cbProject::QueryCloseAllFiles ()
Act like closing all project files, but don't do it.
Used to check if any of the project files need saving.
Returns
True if even one project file needs to be saved, false if not.
Definition at line 1073 of file cbproject.cpp.
References ProjectFile::file, Manager::Get(), Manager::GetEditorManager(), wxFileName::GetFullPath(), cbEditor::GetModified(), EditorManager::IsBuiltinOpen(), m_Files, and EditorManager::QueryClose().
Referenced by CloseAllFiles(), and ProjectManagerUI::QueryCloseProject().
RemoveBuildTarget() [1/2]
bool cbProject::RemoveBuildTarget (int index)
Remove a build target.
Parameters
index The index of the build target to remove.
Returns
True if index was valid, false if not.
Definition at line 1279 of file cbproject.cpp.
References cbEVT_BUILDTARGET_REMOVED, cbEVT_PROJECT_TARGETS_MODIFIED, GetBuildTarget(), CompileTargetBase::GetTitle(), wxArrayString::Index(), m_Files, m_Targets, m_VirtualTargets, NotifyPlugins(), wxArrayString::RemoveAt(), ProjectFile::RemoveBuildTarget(), and SetModified().
Referenced by ScriptBindings::cbProject_RemoveBuildTarget(), ProjectOptionsDlg::OnRemoveBuildTargetClick(), and RemoveBuildTarget().
RemoveBuildTarget() [2/2]
bool cbProject::RemoveBuildTarget (const wxString & targetName)
Remove a build target.
Parameters
targetName The build target name.
Returns
True if the targetName was valid, false if not.
Definition at line 1314 of file cbproject.cpp.
References IndexOfBuildTargetName(), and RemoveBuildTarget().
RemoveFile()
bool cbProject::RemoveFile (ProjectFile * pf)
Remove a file from the project.
Parameters
pf The pointer to ProjectFile.
Returns
True if pf was a valid project file, false if not.
Definition at line 855 of file cbproject.cpp.
References _T, ProjectFile::AutoGeneratedBy(), EditorManager::Close(), LogManager::DebugLog(), ProjectFile::file, ProjectFile::generatedFiles, Manager::Get(), Manager::GetEditorManager(), wxFileName::GetFullPath(), Manager::GetLogManager(), m_FileArray, m_Files, m_ProjectFilesMap, m_Targets, ProjectFile::relativeFilename, SetModified(), and UnixFilename().
Referenced by ScriptBindings::cbProject_RemoveFile(), and ProjectManager::RemoveFileFromProject().
RemoveVirtualBuildTarget()
bool cbProject::RemoveVirtualBuildTarget (const wxString & alias)
Remove a virtual build target.
Parameters
alias The virtual build target's name.
Returns
True if the virtual build target was removed, false if not.
Definition at line 1470 of file cbproject.cpp.
References cbEVT_PROJECT_TARGETS_MODIFIED, m_VirtualTargets, NotifyPlugins(), and SetModified().
Referenced by AddBuildTarget(), VirtualBuildTargetsDlg::OnEditClick(), VirtualBuildTargetsDlg::OnRemoveClick(), and ScriptBindings::RegisterBindings().
RemoveVirtualFolders()
void cbProject::RemoveVirtualFolders (const wxString & folder)
Remove all virtual folders starting with folder.
Definition at line 919 of file cbproject.cpp.
References wxString::Clear(), wxArrayString::GetCount(), wxString::IsEmpty(), m_Files, m_VirtualFolders, wxArrayString::RemoveAt(), SetModified(), wxString::StartsWith(), and ProjectFile::virtual_path.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects().
RenameBuildTarget() [1/2]
bool cbProject::RenameBuildTarget (int index, const wxString & targetName)
Rename a build target.
Parameters
index The build target's index to rename.
targetName The new name for the build target.
Returns
True if index was valid, false if not.
Definition at line 1173 of file cbproject.cpp.
References cbEVT_BUILDTARGET_RENAMED, cbEVT_PROJECT_TARGETS_MODIFIED, GetBuildTarget(), CompileTargetBase::GetTitle(), wxArrayString::Index(), m_Files, m_VirtualTargets, NotifyPlugins(), ProjectFile::RenameBuildTarget(), SetModified(), and CompileTargetBase::SetTitle().
Referenced by ScriptBindings::cbProject_RenameBuildTarget(), ProjectOptionsDlg::OnEditBuildTargetClick(), and RenameBuildTarget().
RenameBuildTarget() [2/2]
bool cbProject::RenameBuildTarget (const wxString & oldTargetName, const wxString & newTargetName)
Rename a build target.
Parameters
oldTargetName The build target's old name.
newTargetName The new name for the build target.
Returns
True if oldTargetName was valid, false if not.
Definition at line 1206 of file cbproject.cpp.
References IndexOfBuildTargetName(), and RenameBuildTarget().
ReOrderTargets()
void cbProject::ReOrderTargets (const wxArrayString & nameOrder)
Reorder the list of build targets.
This is useful, so that when the special build target "All" is being built targets are built in the desired order.
Parameters
nameOrder An array of strings containing build target names in the order you desire. The number of array elements must be equal to GetBuildTargetsCount().
Definition at line 1400 of file cbproject.cpp.
References _T, LogManager::DebugLog(), F(), Manager::Get(), GetBuildTarget(), wxArrayString::GetCount(), Manager::GetLogManager(), wxArrayString::Index(), wxArrayString::Insert(), m_Targets, m_VirtualTargets, wxArrayString::Remove(), SetModified(), and wxNOT_FOUND.
Referenced by ProjectOptionsDlg::OnBuildOrderClick().
ReplaceVirtualFolder()
void cbProject::ReplaceVirtualFolder (const wxString & oldFolder, const wxString & newFolder)
Replaced the oldFolder with newFolder or appends newFolder to the end of the list if oldFolder is not found.
Definition at line 940 of file cbproject.cpp.
References wxArrayString::Add(), wxArrayString::Index(), wxString::IsEmpty(), m_Files, m_VirtualFolders, wxString::Replace(), SetModified(), wxString::StartsWith(), ProjectFile::virtual_path, and wxNOT_FOUND.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects().
RestoreTreeState()
void cbProject::RestoreTreeState (wxTreeCtrl * tree)
Convenience function for remembering the project's tree state when refreshing it.
Parameters
tree The tree control to restore its expanded state to a previously saved.
Definition at line 978 of file cbproject.cpp.
References m_ExpandedNodes, m_ProjectNode, and m_SelectedNodes.
Save()
bool cbProject::Save ()
Save the project.
Returns
True if successful, false otherwise.
Definition at line 477 of file cbproject.cpp.
References _(), cbEVT_PROJECT_SAVE, cbMessageBox(), wxFileName::GetModificationTime(), wxString::IsEmpty(), CompileTargetBase::m_Filename, m_LastModified, m_pExtensionsElement, NotifyPlugins(), ProjectLoader::Save(), SaveAs(), and wxICON_WARNING.
Referenced by cbProject(), ExportTargetAsProject(), MainFrame::OnFileNewWhat(), ProjectManagerUI::QueryCloseProject(), ScriptBindings::RegisterBindings(), Wiz::RunProjectWizard(), ProjectManager::SaveProject(), and TemplateManager::SaveUserTemplate().
SaveAllFiles()
bool cbProject::SaveAllFiles ()
Save all project files.
Returns
True if successful, false otherwise.
Definition at line 1112 of file cbproject.cpp.
References ProjectFile::file, Manager::Get(), Manager::GetEditorManager(), wxFileName::GetFullPath(), m_Files, and EditorManager::Save().
Referenced by CompilerGCC::DoBuild(), CompilerGCC::DoWorkspaceBuild(), MainFrame::OnFileNewWhat(), ScriptBindings::RegisterBindings(), and TemplateManager::SaveUserTemplate().
SaveAs()
bool cbProject::SaveAs ()
Save the project under a different name.
A dialog pops up for the user to choose a new filename for the project.
Returns
True if successful, false otherwise.
Definition at line 428 of file cbproject.cpp.
References _(), _T, AddDefaultBuildTarget(), wxFileName::Assign(), CalculateCommonTopLevelPath(), cbEVT_PROJECT_SAVE, cbMessageBox(), FileFilters::CODEBLOCKS_EXT, Manager::Get(), wxFileName::GetExt(), FileFilters::GetFilterString(), wxFileName::GetFullName(), wxFileName::GetModificationTime(), wxFileName::GetPath(), wxString::IsSameAs(), CompileTargetBase::m_Filename, m_LastModified, m_Loaded, m_pExtensionsElement, wxString::Matches(), NotifyPlugins(), PlaceWindow(), ProjectLoader::Save(), wxFD_OVERWRITE_PROMPT, wxFD_SAVE, wxICON_WARNING, and wxID_OK.
Referenced by cbProject(), Save(), and ProjectManager::SaveProjectAs().
SaveLayout()
bool cbProject::SaveLayout ()
Save the project's layout.
Layout is the list of open project files, which one is active, where the cursor is located on each one of those, etc.
Returns
True if successful, false otherwise.
Definition at line 494 of file cbproject.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), wxFileName::GetFullPath(), wxString::IsEmpty(), CompileTargetBase::m_Filename, ConfigManager::ReadBool(), ProjectLayoutLoader::Save(), and wxFileName::SetExt().
Referenced by ProjectManager::CloseProject(), and ScriptBindings::RegisterBindings().
SaveTreeState()
void cbProject::SaveTreeState (wxTreeCtrl * tree)
Convenience function for remembering the project's tree state when refreshing it.
Parameters
tree The tree control to save its expanded state.
Definition at line 973 of file cbproject.cpp.
References m_ExpandedNodes, m_ProjectNode, and m_SelectedNodes.
SelectTarget()
int cbProject::SelectTarget (int initial = -1, bool evenIfOne = false)
Displays a target selection dialog.
When invoked, a selection dialog is presented to the user so that he/she can select one target from the list of this project's targets.
Parameters
initial The index of the pre-selected target when the dialog is displayed. Defaults to none (-1).
evenIfOne If true, the dialog is still shown even if the project contains only one target. The default behaviour is to not show the dialog if the project has only one target.
Returns
The target's index that the user selected or -1 if the dialog was cancelled.
Definition at line 1125 of file cbproject.cpp.
References GetBuildTargetsCount(), SelectTargetDlg::GetSelection(), PlaceWindow(), wxDialog::ShowModal(), and wxID_OK.
Referenced by CodeBlocksApp::BatchJob(), DebuggerGDB::DoDebug(), ProjectManagerUI::OnExecParameters(), and ScriptBindings::RegisterBindings().
SetActiveBuildTarget()
bool cbProject::SetActiveBuildTarget (const wxString & name)
Set the active build target.
Parameters
name The build target name to set as active. If name does not exist, then the first virtual target is set or the first real target, depending which is valid.
Returns
True if name was valid, false if not.
Definition at line 1350 of file cbproject.cpp.
References BuildTargetValid(), cbEVT_BUILDTARGET_SELECTED, GetFirstValidBuildTargetName(), m_ActiveTarget, and NotifyPlugins().
Referenced by ProjectLayoutLoader::Open(), and ScriptBindings::RegisterBindings().
SetCheckForExternallyModifiedFiles()
void cbProject::SetCheckForExternallyModifiedFiles (bool check)
Set check for externally modified files.
Parameters
True if check for externally modified files is set, false if not.
Definition at line 1614 of file cbproject.cpp.
References m_CheckForExternallyModifiedFiles, and SetModified().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetCompilerID()
void cbProject::SetCompilerID (const wxString & id) virtual
! Set the flag if the host app should be run in terminal
Set the target's compiler
Reimplemented from CompileTargetBase.
Definition at line 129 of file cbproject.cpp.
References FileTypeOf(), ftResource, CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), ProjectFile::GetObjName(), Compiler::GetSwitches(), m_Files, m_Targets, CompilerSwitches::objectExtension, ProjectFile::relativeFilename, CompileTargetBase::SetCompilerID(), wxFileName::SetExt(), and ProjectFile::SetObjName().
Referenced by cbProject(), ProjectLoader::DoProjectOptions(), CompilerOptionsDlg::ProjectTargetCompilerAdjust(), and Wiz::RunProjectWizard().
SetCurrentlyCompilingTarget()
void cbProject::SetCurrentlyCompilingTarget (ProjectBuildTarget * bt)
Set the currently compiling target.
Note
This function is for internal use by compilers only. Using this function in any other place results in undefined behaviour!
Parameters
bt The build target that is currently building.
Definition at line 1439 of file cbproject.cpp.
References m_CurrentlyCompilingTarget.
Referenced by ScriptBindings::RegisterBindings().
SetDefaultExecuteTarget()
void cbProject::SetDefaultExecuteTarget (const wxString & name)
Set the build target index which will be pre-selected when the "Select target" dialog appears when running the project.
Parameters
name The build target's name.
Definition at line 1373 of file cbproject.cpp.
References m_DefaultExecuteTarget, and SetModified().
Referenced by ProjectLoader::DoProjectOptions(), SelectTargetDlg::OnCheckboxSelection(), ProjectLoader::Open(), and ScriptBindings::RegisterBindings().
SetExtendedObjectNamesGeneration()
void cbProject::SetExtendedObjectNamesGeneration (bool ext)
Sets object names generation to extended/normal mode.
In normal mode (the default), the file foo.cpp generates the foo.o object file. In extended mode, the file foo.cpp generates the foo.cpp.o object file.
This option is useful for large projects containing similarly named files (in the same directory) differing only on their extensions. Using the extended mode with said projects guarantees that each object name will be unique.
Parameters
ext Set to true to switch to extended mode, false for normal mode.
Definition at line 1560 of file cbproject.cpp.
References m_ExtendedObjectNamesGeneration, m_Files, ProjectFile::relativeToCommonTopLevelPath, SetModified(), ProjectFile::SetObjName(), and ProjectFile::UpdateFileDetails().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetGlobs()
void cbProject::SetGlobs (const std::vector< Glob > & globs)
Set the globs to the project, this are directory paths do retrieve files from to be added to the project, the path can be searched recursively.
Parameters
globs the globs to add to the project.
Definition at line 1740 of file cbproject.cpp.
References m_Globs.
Referenced by ProjectLoader::DoUnits().
SetMakefile()
void cbProject::SetMakefile (const wxString & makefile) inline
Set the Makefile filename used when exporting a Makefile for the project, or when using a custom Makefile to build the project.
Parameters
makefile The filename for the Makefile.
Definition at line 148 of file cbproject.h.
References CompileOptionsBase::SetModified().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetMakefileCustom()
void cbProject::SetMakefileCustom (bool custom)
Mark if the project should use a custom Makefile for compilation.
Parameters
custom If true, use a custom Makefile for compilation. If false, use direct C::B build mode.
Definition at line 194 of file cbproject.cpp.
References m_CustomMakefile, and SetModified().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetMakefileExecutionDir()
void cbProject::SetMakefileExecutionDir (const wxString & dir)
Allow the specification of specific execution directory if the project use a custom Makefile.
Defaults to the projects base path, if no custom makefile is used.
Parameters
dir The directory the custom Makefile should be executed from.
Definition at line 999 of file cbproject.cpp.
References m_MakefileExecutionDir, and SetModified().
Referenced by ProjectLoader::DoProjectOptions(), and ProjectOptionsDlg::EndModal().
SetModeForPCH()
void cbProject::SetModeForPCH (PCHMode mode) inline
Set the mode to handle precompiled headers.
Parameters
mode The desired PCH mode.
Definition at line 306 of file cbproject.h.
References CompileTargetBase::SetCompilerID(), and CompileOptionsBase::SetModified().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetModified()
void cbProject::SetModified (bool modified = true) virtual
Mark the project as modified or not.
Parameters
modified If true, the project is marked as modified. If false, as not-modified.
Reimplemented from CompileOptionsBase.
Definition at line 179 of file cbproject.cpp.
References m_ActiveTarget, m_LastSavedActiveTarget, m_Targets, and CompileOptionsBase::SetModified().
Referenced by AddBuildTarget(), AddFile(), AddToExtensions(), cbProject(), ProjectManagerUI::CheckForExternallyModifiedProjects(), ClearAllProperties(), DefineVirtualBuildTarget(), DuplicateBuildTarget(), ProjectFileOptionsDlg::EndModal(), ExportTargetAsProject(), CompilerCommandGenerator::Init(), Open(), ScriptBindings::RegisterBindings(), RemoveBuildTarget(), RemoveFile(), RemoveVirtualBuildTarget(), RemoveVirtualFolders(), ProjectFile::Rename(), RenameBuildTarget(), ReOrderTargets(), ReplaceVirtualFolder(), ProjectLoader::Save(), SetCheckForExternallyModifiedFiles(), SetDefaultExecuteTarget(), SetExtendedObjectNamesGeneration(), SetMakefileCustom(), SetMakefileExecutionDir(), SetNotes(), and SetShowNotesOnLoad().
SetNotes()
void cbProject::SetNotes (const wxString & notes)
Set notes on the project.
Parameters
notes Simple text notes about the project.
Definition at line 1586 of file cbproject.cpp.
References m_Notes, and SetModified().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), ScriptBindings::RegisterBindings(), and ShowNotes().
SetProjectNode()
void cbProject::SetProjectNode (wxTreeItemId node) inline
Sets the root item of this item, should not be called by user's code!
Definition at line 314 of file cbproject.h.
References ScriptBindings::IOLib::RemoveFile().
Referenced by ProjectManagerUI::BuildProjectTree().
SetShowNotesOnLoad()
void cbProject::SetShowNotesOnLoad (bool show)
Set show project notes on load automatically.
Parameters
show If true show project notes on load.
Definition at line 1600 of file cbproject.cpp.
References m_AutoShowNotesOnLoad, and SetModified().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetTitle()
void cbProject::SetTitle (const wxString & title) virtual
Changes project title.
This function overrides CompileTargetBase::SetTitle. It sends additional notification event to plugins and than calls base function.
Reimplemented from CompileTargetBase.
Definition at line 1645 of file cbproject.cpp.
References cbEVT_PROJECT_RENAMED, CompileTargetBase::GetTitle(), NotifyPlugins(), and CompileTargetBase::SetTitle().
Referenced by ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), ExportTargetAsProject(), TemplateManager::NewProjectFromUserTemplate(), ScriptBindings::RegisterBindings(), and Wiz::RunProjectWizard().
SetVirtualFolders()
void cbProject::SetVirtualFolders (const wxArrayString & folders)
Set the virtual folders list.
Normally used by the project loader only.
Definition at line 963 of file cbproject.cpp.
References _T, wxArrayString::GetCount(), and m_VirtualFolders.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects(), and ProjectLoader::DoProjectOptions().
ShowNotes()
void cbProject::ShowNotes (bool nonEmptyOnly, bool editable = false)
Show project notes now.
Parameters
nonEmptyOnly If true, show notes only if non-empty.
editable If true, the notes will be editable.
Note
If editable is true, the nonEmptyOnly parameter is ignored...
Definition at line 1628 of file cbproject.cpp.
References _(), Manager::Get(), GenericMultiLineNotesDlg::GetNotes(), wxString::IsEmpty(), m_Notes, CompileTargetBase::m_Title, PlaceWindow(), SetNotes(), wxDialog::ShowModal(), and wxID_OK.
Referenced by ProjectManager::EndLoadingProject(), ProjectManager::EndLoadingWorkspace(), and ScriptBindings::RegisterBindings().
Touch()
void cbProject::Touch ()
Sets the last modification time for the project to 'now'.
Used to detect modifications outside the Program.
Definition at line 423 of file cbproject.cpp.
References m_LastModified, and wxDateTime::Now().
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects().
Member Data Documentation
m_ActiveTarget
wxString cbProject::m_ActiveTarget private
Definition at line 698 of file cbproject.h.
Referenced by GetActiveBuildTarget(), SetActiveBuildTarget(), and SetModified().
m_AutoShowNotesOnLoad
bool cbProject::m_AutoShowNotesOnLoad private
Definition at line 729 of file cbproject.h.
Referenced by GetShowNotesOnLoad(), and SetShowNotesOnLoad().
m_BasePath
wxString cbProject::m_BasePath private
Definition at line 717 of file cbproject.h.
Referenced by CalculateCommonTopLevelPath(), and cbProject().
m_CheckForExternallyModifiedFiles
bool cbProject::m_CheckForExternallyModifiedFiles private
Definition at line 730 of file cbproject.h.
Referenced by GetCheckForExternallyModifiedFiles(), and SetCheckForExternallyModifiedFiles().
m_CommonTopLevelPath
wxString cbProject::m_CommonTopLevelPath private
Definition at line 716 of file cbproject.h.
Referenced by AddFile(), CalculateCommonTopLevelPath(), cbProject(), and GetCommonTopLevelPath().
m_CurrentlyCompilingTarget
ProjectBuildTarget* cbProject::m_CurrentlyCompilingTarget private
Definition at line 723 of file cbproject.h.
Referenced by SetCurrentlyCompilingTarget().
m_CurrentlyLoading
bool cbProject::m_CurrentlyLoading private
Definition at line 715 of file cbproject.h.
Referenced by AddFile(), and Open().
m_CustomMakefile
bool cbProject::m_CustomMakefile private
Definition at line 702 of file cbproject.h.
Referenced by GetExecutionDir(), and SetMakefileCustom().
m_DefaultExecuteTarget
wxString cbProject::m_DefaultExecuteTarget private
Definition at line 700 of file cbproject.h.
Referenced by GetDefaultExecuteTarget(), and SetDefaultExecuteTarget().
m_ExpandedNodes
wxArrayString cbProject::m_ExpandedNodes private
Definition at line 708 of file cbproject.h.
Referenced by RestoreTreeState(), and SaveTreeState().
m_ExtendedObjectNamesGeneration
bool cbProject::m_ExtendedObjectNamesGeneration private
Definition at line 727 of file cbproject.h.
Referenced by GetExtendedObjectNamesGeneration(), and SetExtendedObjectNamesGeneration().
m_FileArray
ProjectFileArray cbProject::m_FileArray private
Definition at line 707 of file cbproject.h.
Referenced by AddFile(), cbProject(), ClearAllProperties(), CloseAllFiles(), GetFile(), and RemoveFile().
m_Files
FilesList cbProject::m_Files private
Definition at line 706 of file cbproject.h.
Referenced by AddFile(), CalculateCommonTopLevelPath(), cbProject(), ClearAllProperties(), CloseAllFiles(), GetFile(), LoadLayout(), QueryCloseAllFiles(), RemoveBuildTarget(), RemoveFile(), RemoveVirtualFolders(), RenameBuildTarget(), ReplaceVirtualFolder(), SaveAllFiles(), SetCompilerID(), and SetExtendedObjectNamesGeneration().
m_Globs
std::vector<Glob> cbProject::m_Globs private
Definition at line 705 of file cbproject.h.
Referenced by GetGlobs(), and SetGlobs().
m_LastModified
wxDateTime cbProject::m_LastModified private
Definition at line 725 of file cbproject.h.
Referenced by Open(), Save(), SaveAs(), and Touch().
m_LastSavedActiveTarget
wxString cbProject::m_LastSavedActiveTarget private
Definition at line 699 of file cbproject.h.
Referenced by SetModified().
m_Loaded
bool cbProject::m_Loaded private
Definition at line 710 of file cbproject.h.
Referenced by cbProject(), Open(), and SaveAs().
m_Makefile
wxString cbProject::m_Makefile private
Definition at line 701 of file cbproject.h.
Referenced by GetMakefile().
m_MakefileExecutionDir
wxString cbProject::m_MakefileExecutionDir mutable private
Definition at line 703 of file cbproject.h.
Referenced by GetMakefileExecutionDir(), and SetMakefileExecutionDir().
m_Notes
wxString cbProject::m_Notes private
Definition at line 728 of file cbproject.h.
Referenced by GetNotes(), SetNotes(), and ShowNotes().
m_PCHMode
PCHMode cbProject::m_PCHMode private
Definition at line 719 of file cbproject.h.
m_pExtensionsElement
TiXmlElement* cbProject::m_pExtensionsElement private
Definition at line 734 of file cbproject.h.
Referenced by ClearAllProperties(), ExportTargetAsProject(), GetExtensionsNode(), Open(), Save(), and SaveAs().
m_ProjectFilesMap
ProjectFiles cbProject::m_ProjectFilesMap private
Definition at line 722 of file cbproject.h.
Referenced by AddFile(), GetFileByFilename(), Open(), ProjectFileRenamed(), and RemoveFile().
m_ProjectNode
wxTreeItemId cbProject::m_ProjectNode private
Definition at line 711 of file cbproject.h.
Referenced by RestoreTreeState(), and SaveTreeState().
m_SelectedNodes
wxArrayString cbProject::m_SelectedNodes private
Definition at line 709 of file cbproject.h.
Referenced by RestoreTreeState(), and SaveTreeState().
m_Targets
BuildTargets cbProject::m_Targets private
Definition at line 697 of file cbproject.h.
Referenced by AddBuildTarget(), AddFile(), ClearAllProperties(), DuplicateBuildTarget(), GetBuildTarget(), GetFirstValidBuildTargetName(), GetModified(), IndexOfBuildTargetName(), Open(), RemoveBuildTarget(), RemoveFile(), ReOrderTargets(), SetCompilerID(), and SetModified().
m_VirtualFolders
wxArrayString cbProject::m_VirtualFolders private
Definition at line 713 of file cbproject.h.
Referenced by AppendUniqueVirtualFolder(), GetVirtualFolders(), RemoveVirtualFolders(), ReplaceVirtualFolder(), and SetVirtualFolders().
m_VirtualTargets
VirtualBuildTargetsMap cbProject::m_VirtualTargets private
Definition at line 696 of file cbproject.h.
Referenced by DefineVirtualBuildTarget(), GetExpandedVirtualBuildTargetGroup(), GetFirstValidBuildTargetName(), GetVirtualBuildTargetGroup(), GetVirtualBuildTargets(), HasVirtualBuildTarget(), RemoveBuildTarget(), RemoveVirtualBuildTarget(), RenameBuildTarget(), and ReOrderTargets().
The documentation for this class was generated from the following files:
cbproject.h
cbproject.cpp