Code::Blocks: CompilerLCC Class Reference
CompilerLCC Class Reference
#include <compilerLCC.h>
Public Member Functions
CompilerLCC ()
virtual ~CompilerLCC ()
virtual bool IsValid ()
Check if the compiler is actually valid (installed).
virtual void Reset ()
Reset settings to defaults.
virtual AutoDetectResult AutoDetectInstallationDir ()
Try to auto-detect the compiler's installation directory.
Public Member Functions inherited from Compiler
Compiler (const wxString &name, const wxString &ID, const wxString &parentID=wxEmptyString, int weight=50)
virtual ~Compiler ()
virtual CompilerLineType CheckForWarningsAndErrors (const wxString &line)
Check if the supplied string is a compiler warning/error.
virtual wxString GetLastErrorFilename ()
Returns warning/error filename.
virtual wxString GetLastErrorLine ()
Returns warning/error line number (as a string).
virtual wxString GetLastError ()
Returns warning/error actual string.
virtual const wxString & GetName () const
Get the compiler's name.
virtual const wxString & GetMasterPath () const
Get the compiler's master path (must contain "bin", "include" and "lib")
virtual const wxArrayString & GetExtraPaths () const
Get the compiler's extra paths.
virtual const CompilerPrograms & GetPrograms () const
Get the compiler's programs.
virtual const CompilerSwitches & GetSwitches () const
Get the compiler's generic switches.
virtual const CompilerOptions & GetOptions () const
Get the compiler's options.
virtual const wxString & GetCommand (CommandType ct, const wxString &fileExtension=wxEmptyString) const
Get a command based on CommandType.
virtual const CompilerTool * GetCompilerTool (CommandType ct, const wxString &fileExtension=wxEmptyString) const
Get a compiler tool based on CommandType.
virtual CompilerToolsVector & GetCommandToolsVector (CommandType ct)
Get a command tool vector based on CommandType (used by advanced compiler dialog)
virtual const RegExArray & GetRegExArray ()
Get the array of regexes used in errors/warnings recognition.
virtual void LoadDefaultRegExArray (bool globalPrecedence=false)
Load the default (preset) array of regexes used in errors/warnings recognition.
virtual void SetName (const wxString &name)
Set the compiler's name.
virtual void SetMasterPath (const wxString &path)
Set the compiler's master path (must contain "bin", "include" and "lib")
virtual void SetExtraPaths (const wxArrayString &paths)
Set the compiler's extra paths.
virtual void SetPrograms (const CompilerPrograms &programs)
Set the compiler's programs.
virtual void SetSwitches (const CompilerSwitches &switches)
Set the compiler's generic switches.
virtual void SetOptions (const CompilerOptions &options)
Set the compiler's options.
virtual void SetRegExArray (const RegExArray &regexes)
Set the array of regexes used in errors/warnings recognition.
virtual void SaveSettings (const wxString &baseKey)
Save settings.
virtual void LoadSettings (const wxString &baseKey)
Load settings.
virtual void ReloadOptions ()
Reload option flags (for copied compilers).
const wxString & GetID () const
Get this compiler's unique ID.
const wxString & GetParentID () const
Get this compiler's parent's unique ID.
virtual void SetVersionString ()
Set the compiler version string.
const wxString GetVersionString () const
Get the compiler version string.
virtual CompilerCommandGenerator * GetCommandGenerator (cbProject *project)
This is to be overridden, if compiler needs to alter the default command line generation.
void SetCOnlyFlags (const wxString &flags)
void SetCPPOnlyFlags (const wxString &flags)
const wxString & GetCOnlyFlags ()
const wxString & GetCPPOnlyFlags ()
Public Member Functions inherited from CompileOptionsBase
CompileOptionsBase ()
virtual ~CompileOptionsBase ()
virtual void AddPlatform (int platform)
virtual void RemovePlatform (int platform)
virtual void SetPlatforms (int platforms)
virtual int GetPlatforms () const
virtual bool SupportsCurrentPlatform () const
virtual void SetLinkerOptions (const wxArrayString &linkerOpts)
virtual const wxArrayString & GetLinkerOptions () const
virtual void AddLinkerOption (const wxString &option)
virtual void ReplaceLinkerOption (const wxString &option, const wxString &new_option)
virtual void RemoveLinkerOption (const wxString &option)
virtual void SetLinkLibs (const wxArrayString &linkLibs)
virtual const wxArrayString & GetLinkLibs () const
virtual void AddLinkLib (const wxString &option)
virtual void ReplaceLinkLib (const wxString &option, const wxString &new_option)
virtual void RemoveLinkLib (const wxString &option)
virtual void SetCompilerOptions (const wxArrayString &compilerOpts)
virtual const wxArrayString & GetCompilerOptions () const
virtual void AddCompilerOption (const wxString &option)
virtual void ReplaceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveCompilerOption (const wxString &option)
virtual void SetResourceCompilerOptions (const wxArrayString &resourceCompilerOpts)
virtual const wxArrayString & GetResourceCompilerOptions () const
virtual void AddResourceCompilerOption (const wxString &option)
virtual void ReplaceResourceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveResourceCompilerOption (const wxString &option)
virtual void SetIncludeDirs (const wxArrayString &includeDirs)
virtual const wxArrayString & GetIncludeDirs () const
virtual void AddIncludeDir (const wxString &option)
virtual void ReplaceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveIncludeDir (const wxString &option)
virtual void SetResourceIncludeDirs (const wxArrayString &resIncludeDirs)
virtual const wxArrayString & GetResourceIncludeDirs () const
virtual void AddResourceIncludeDir (const wxString &option)
virtual void ReplaceResourceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveResourceIncludeDir (const wxString &option)
virtual void SetLibDirs (const wxArrayString &libDirs)
virtual const wxArrayString & GetLibDirs () const
virtual void AddLibDir (const wxString &option)
virtual void ReplaceLibDir (const wxString &option, const wxString &new_option)
virtual void RemoveLibDir (const wxString &option)
virtual void SetCommandsBeforeBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsBeforeBuild () const
virtual void AddCommandsBeforeBuild (const wxString &command)
virtual void RemoveCommandsBeforeBuild (const wxString &command)
virtual void SetCommandsAfterBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsAfterBuild () const
virtual void AddCommandsAfterBuild (const wxString &command)
virtual void RemoveCommandsAfterBuild (const wxString &command)
virtual void SetBuildScripts (const wxArrayString &scripts)
virtual const wxArrayString & GetBuildScripts () const
virtual void AddBuildScript (const wxString &script)
virtual void RemoveBuildScript (const wxString &script)
virtual bool GetModified () const
virtual void SetModified (bool modified)
virtual bool GetAlwaysRunPostBuildSteps () const
virtual void SetAlwaysRunPostBuildSteps (bool always)
virtual bool SetVar (const wxString &key, const wxString &value, bool onlyIfExists=false)
virtual bool UnsetVar (const wxString &key)
virtual void UnsetAllVars ()
virtual bool HasVar (const wxString &key) const
virtual const wxString & GetVar (const wxString &key) const
virtual const StringHash & GetAllVars () const
Protected Member Functions
virtual Compiler * CreateCopy ()
Implement this in new compilers, to return a new copy.
Protected Member Functions inherited from Compiler
Compiler (const Compiler &other)
bool IsUniqueID (const wxString &ID)
void MakeValidID ()
void LoadDefaultOptions (const wxString &name, int recursion=0)
void LoadRegExArray (const wxString &name, bool globalPrecedence=false, int recursion=0)
bool EvalXMLCondition (const wxXmlNode *node)
wxString GetExecName (const wxString &name)
void MirrorCurrentSettings ()
void CompileRegExArray ()
Private Attributes
bool m_RegistryUpdated
Additional Inherited Members
Static Public Attributes inherited from Compiler
static const wxString FilePathWithSpaces = _T("[][{}() \t#%$~[:alnum:]&_:+/\\.-]+")
static wxString CommandTypeDescriptions [ctCount]
Get the command type descriptions (used in advanced compiler options)
Protected Attributes inherited from Compiler
wxString m_Name
wxString m_MasterPath
wxArrayString m_ExtraPaths
CompilerToolsVector m_Commands [ctCount]
CompilerPrograms m_Programs
CompilerSwitches m_Switches
CompilerOptions m_Options
RegExArray m_RegExes
wxString m_ErrorFilename
wxString m_ErrorLine
wxString m_Error
wxString m_VersionString
wxString m_SortOptions [2]
int m_Weight
Protected Attributes inherited from CompileOptionsBase
int m_Platform
wxArrayString m_LinkerOptions
wxArrayString m_LinkLibs
wxArrayString m_CompilerOptions
wxArrayString m_ResourceCompilerOptions
wxArrayString m_IncludeDirs
wxArrayString m_ResIncludeDirs
wxArrayString m_LibDirs
wxArrayString m_CmdsBefore
wxArrayString m_CmdsAfter
wxArrayString m_Scripts
bool m_Modified
bool m_AlwaysRunPostCmds
StringHash m_Vars
Constructor & Destructor Documentation
CompilerLCC::CompilerLCC ()
References Compiler::m_Weight, and Reset().
Referenced by CreateCopy().
CompilerLCC::~CompilerLCC () virtual
Member Function Documentation
AutoDetectResult CompilerLCC::AutoDetectInstallationDir () virtual
Try to auto-detect the compiler's installation directory.
Implements Compiler.
References CompileOptionsBase::AddIncludeDir(), CompileOptionsBase::AddLibDir(), adrDetected, adrGuessed, CompilerPrograms::C, Compiler::m_ExtraPaths, Compiler::m_MasterPath, Compiler::m_Programs, and m_RegistryUpdated.
Compiler * CompilerLCC::CreateCopy () protected virtual
Implement this in new compilers, to return a new copy.
Implements Compiler.
References CompilerLCC().
bool CompilerLCC::IsValid () virtual
Check if the compiler is actually valid (installed).
Reimplemented from Compiler.
References CompilerPrograms::C, LogManager::DebugLog(), Manager::Get(), Manager::GetLogManager(), Compiler::IsValid(), Compiler::m_MasterPath, Compiler::m_Programs, and m_RegistryUpdated.
void CompilerLCC::Reset () virtual
Reset settings to defaults.
Put initialization code here or leave blank for standard XML loading. Call this from the default constructor.
Reimplemented from Compiler.
References CompilerOptions::ClearOptions(), Compiler::GetID(), Compiler::LoadDefaultOptions(), Compiler::LoadDefaultRegExArray(), CompileOptionsBase::m_CmdsAfter, CompileOptionsBase::m_CmdsBefore, CompileOptionsBase::m_CompilerOptions, CompileOptionsBase::m_LinkerOptions, CompileOptionsBase::m_LinkLibs, Compiler::m_Options, and m_RegistryUpdated.
Referenced by CompilerLCC().
Member Data Documentation
bool CompilerLCC::m_RegistryUpdated private
Referenced by AutoDetectInstallationDir(), IsValid(), and Reset().
The documentation for this class was generated from the following files:
compilerLCC.h
compilerLCC.cpp