Code::Blocks: cbDebuggerMenuHandler Class Reference
cbDebuggerMenuHandler Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbDebuggerMenuHandler ()
virtual void SetActiveDebugger (cbDebuggerPlugin *active)=0
virtual void MarkActiveTargetAsValid (bool valid)=0
virtual void RebuildMenus ()=0
virtual void BuildContextMenu (wxMenu &menu, const wxString &word_at_caret, bool is_running)=0
virtual bool RegisterWindowMenu (const wxString &name, const wxString &help, cbDebuggerWindowMenuItem *item)=0
virtual void UnregisterWindowMenu (const wxString &name)=0
Detailed Description
Definition at line 129 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
~cbDebuggerMenuHandler()
cbDebuggerMenuHandler::~cbDebuggerMenuHandler () virtual
Definition at line 23 of file cbdebugger_interfaces.cpp.
Member Function Documentation
BuildContextMenu()
virtual void cbDebuggerMenuHandler::BuildContextMenu (wxMenu & menu, const wxString & word_at_caret, bool is_running) pure virtual
Implemented in DebuggerMenuHandler.
Referenced by DebuggerManager::BuildContextMenu().
MarkActiveTargetAsValid()
virtual void cbDebuggerMenuHandler::MarkActiveTargetAsValid (bool valid) pure virtual
Implemented in DebuggerMenuHandler.
Referenced by DebuggerManager::FindTargetsDebugger().
RebuildMenus()
virtual void cbDebuggerMenuHandler::RebuildMenus () pure virtual
Implemented in DebuggerMenuHandler.
Referenced by DebuggerManager::GetMenu(), DebuggerManager::RebuildAllConfigs(), DebuggerManager::RefreshUI(), DebuggerManager::RegisterDebugger(), and DebuggerManager::UnregisterDebugger().
RegisterWindowMenu()
virtual bool cbDebuggerMenuHandler::RegisterWindowMenu (const wxString & name, const wxString & help, cbDebuggerWindowMenuItem * item) pure virtual
Implemented in DebuggerMenuHandler.
SetActiveDebugger()
virtual void cbDebuggerMenuHandler::SetActiveDebugger (cbDebuggerPlugin * active) pure virtual
Implemented in DebuggerMenuHandler.
Referenced by DebuggerManager::FindTargetsDebugger(), DebuggerManager::RefreshUI(), DebuggerManager::RegisterDebugger(), DebuggerManager::SetTargetsDefaultAsActiveDebugger(), and DebuggerManager::UnregisterDebugger().
UnregisterWindowMenu()
virtual void cbDebuggerMenuHandler::UnregisterWindowMenu (const wxString & name) pure virtual
Implemented in DebuggerMenuHandler.
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp