Code::Blocks: PluginsConfigurationDlg Class Reference
PluginsConfigurationDlg Class Reference
Dialog for Enabling/Disabling/Installing/Uninstalling a plug-in.
#include <pluginsconfigurationdlg.h>
Public Member Functions
PluginsConfigurationDlg (wxWindow *parent)
~PluginsConfigurationDlg ()
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Private Member Functions
void FillList ()
void OnToggle (wxCommandEvent &event)
void OnInstall (wxCommandEvent &event)
void OnUninstall (wxCommandEvent &event)
void OnExport (wxCommandEvent &event)
void OnSelect (wxListEvent &event)
void OnMouseMotion (wxMouseEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void OnLinkClicked (wxHtmlLinkEvent &event)
DECLARE_EVENT_TABLE ()
Detailed Description
Dialog for Enabling/Disabling/Installing/Uninstalling a plug-in.
Definition at line 19 of file pluginsconfigurationdlg.h.
Constructor & Destructor Documentation
PluginsConfigurationDlg()
PluginsConfigurationDlg::PluginsConfigurationDlg (wxWindow * parent)
Definition at line 64 of file pluginsconfigurationdlg.cpp.
References _(), _T, cbDirAccessCheck(), dacReadWrite, wxXmlResource::Get(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::GetFolder(), wxSystemSettings::GetFont(), wxFont::GetPointSize(), PluginManager::GetSafeMode(), wxXmlResource::LoadObject(), OnMouseMotion(), ConfigManager::ReadBool(), sdPluginsGlobal, wxEmptyString, wxEVT_LEAVE_WINDOW, wxEVT_MOTION, and wxSYS_DEFAULT_GUI_FONT.
~PluginsConfigurationDlg()
PluginsConfigurationDlg::~PluginsConfigurationDlg ()
Definition at line 171 of file pluginsconfigurationdlg.cpp.
References OnMouseMotion(), wxEVT_LEAVE_WINDOW, and wxEVT_MOTION.
Member Function Documentation
DECLARE_EVENT_TABLE()
PluginsConfigurationDlg::DECLARE_EVENT_TABLE () private
EndModal()
void PluginsConfigurationDlg::EndModal (int retCode)
Definition at line 480 of file pluginsconfigurationdlg.cpp.
References _T, ScriptBindings::EndModal(), Manager::Get(), Manager::GetCCManager(), Manager::GetConfigManager(), CCManager::NotifyPluginStatus(), and ConfigManager::Write().
FillList()
void PluginsConfigurationDlg::FillList () private
Definition at line 130 of file pluginsconfigurationdlg.cpp.
References _(), _T, wxString::AfterLast(), wxListCtrl::DeleteAllItems(), PluginElement::fileName, Manager::Get(), wxSystemSettings::GetColour(), wxListCtrl::GetColumnCount(), Manager::GetPluginManager(), PluginManager::GetPlugins(), PluginElement::info, wxListCtrl::InsertColumn(), wxListCtrl::InsertItem(), cbPlugin::IsAttached(), PluginElement::plugin, wxListCtrl::SetColumnWidth(), wxListCtrl::SetItem(), wxListCtrl::SetItemData(), wxListCtrl::SetItemTextColour(), sortByTitle(), wxListCtrl::SortItems(), PluginInfo::title, UnixFilename(), PluginInfo::version, wxLIST_AUTOSIZE, wxLIST_AUTOSIZE_USEHEADER, wxLIST_FORMAT_CENTER, wxSYS_COLOUR_GRAYTEXT, and wxSYS_COLOUR_WINDOWTEXT.
Referenced by OnInstall(), and OnUninstall().
OnExport()
void PluginsConfigurationDlg::OnExport (wxCommandEvent & event) private
Definition at line 297 of file pluginsconfigurationdlg.cpp.
References _(), _T, wxArrayString::Add(), wxString::c_str(), cbMessageBox(), PluginManager::ExportPlugin(), PluginElement::fileName, wxString::Format(), Manager::Get(), Manager::GetConfigManager(), wxFileName::GetFullPath(), wxListCtrl::GetItemData(), wxListCtrl::GetItemText(), wxFileName::GetName(), wxListCtrl::GetNextItem(), Manager::GetPluginManager(), wxListCtrl::GetSelectedItemCount(), wxArrayString::Index(), PluginElement::info, wxString::IsEmpty(), PluginElement::plugin, ConfigManager::Read(), wxString::Replace(), AnnoyingDialog::rtONE, AnnoyingDialog::rtTHREE, AnnoyingDialog::rtTWO, wxFileName::SetExt(), wxFileName::SetName(), wxFileName::SetPath(), AnnoyingDialog::THREE_BUTTONS, PluginInfo::title, PluginInfo::version, CfgMgrConsts::version, ConfigManager::Write(), wxART_QUESTION, wxDD_NEW_DIR_BUTTON, wxFileExists(), wxICON_WARNING, wxID_OK, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED, wxNOT_FOUND, wxPD_APP_MODAL, wxPD_AUTO_HIDE, wxPD_CAN_ABORT, wxPD_ELAPSED_TIME, wxPD_ESTIMATED_TIME, and wxPD_REMAINING_TIME.
Referenced by sortByTitle().
OnInstall()
void PluginsConfigurationDlg::OnInstall (wxCommandEvent & event) private
Definition at line 237 of file pluginsconfigurationdlg.cpp.
References _(), _T, cbMessageBox(), FillList(), Manager::Get(), wxArrayString::GetCount(), wxFileDialog::GetPaths(), Manager::GetPluginManager(), PluginManager::InstallPlugin(), wxString::IsEmpty(), wxFileDialog::ShowModal(), wxEmptyString, wxFD_FILE_MUST_EXIST, wxFD_MULTIPLE, wxFD_OPEN, wxICON_WARNING, and wxID_OK.
Referenced by sortByTitle().
OnLinkClicked()
void PluginsConfigurationDlg::OnLinkClicked (wxHtmlLinkEvent & event) private
Definition at line 492 of file pluginsconfigurationdlg.cpp.
References wxLaunchDefaultBrowser().
Referenced by sortByTitle().
OnMouseMotion()
void PluginsConfigurationDlg::OnMouseMotion (wxMouseEvent & event) private
Definition at line 424 of file pluginsconfigurationdlg.cpp.
References PluginElement::fileName, wxListCtrl::GetItemData(), wxMouseEvent::GetPosition(), wxListCtrl::HitTest(), wxString::IsEmpty(), wxMouseEvent::Leaving(), and wxLIST_HITTEST_ONITEM.
Referenced by PluginsConfigurationDlg(), and ~PluginsConfigurationDlg().
OnSelect()
void PluginsConfigurationDlg::OnSelect (wxListEvent & event) private
Definition at line 398 of file pluginsconfigurationdlg.cpp.
References _T, PluginInfo::description, PluginElement::fileName, wxListCtrl::GetItemData(), wxListCtrl::GetNextItem(), wxListCtrl::GetSelectedItemCount(), PluginElement::info, wxString::Replace(), PluginInfo::title, UnixFilename(), PluginInfo::version, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by sortByTitle().
OnToggle()
void PluginsConfigurationDlg::OnToggle (wxCommandEvent & event) private
Definition at line 177 of file pluginsconfigurationdlg.cpp.
References _(), _T, PluginManager::AttachPlugin(), wxString::c_str(), PluginManager::DetachPlugin(), wxString::Format(), Manager::Get(), wxSystemSettings::GetColour(), Manager::GetConfigManager(), wxListCtrl::GetItem(), wxListCtrl::GetItemData(), wxListCtrl::GetNextItem(), Manager::GetPluginManager(), wxListCtrl::GetSelectedItemCount(), PluginElement::info, cbPlugin::IsAttached(), PluginInfo::name, PluginElement::plugin, wxListItem::SetColumn(), wxListItem::SetId(), wxListCtrl::SetItem(), wxListCtrl::SetItemTextColour(), wxListItem::SetMask(), PluginInfo::title, ConfigManager::Write(), wxLIST_MASK_TEXT, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED, wxPD_APP_MODAL, wxPD_AUTO_HIDE, wxPD_CAN_ABORT, wxSYS_COLOUR_GRAYTEXT, and wxSYS_COLOUR_WINDOWTEXT.
Referenced by sortByTitle().
OnUninstall()
void PluginsConfigurationDlg::OnUninstall (wxCommandEvent & event) private
Definition at line 268 of file pluginsconfigurationdlg.cpp.
References _(), _T, cbMessageBox(), FillList(), Manager::Get(), wxListCtrl::GetItemData(), wxListCtrl::GetNextItem(), wxListCtrl::GetSelectedItemCount(), PluginElement::info, wxString::IsEmpty(), PluginElement::plugin, PluginInfo::title, wxICON_WARNING, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by sortByTitle().
OnUpdateUI()
void PluginsConfigurationDlg::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 454 of file pluginsconfigurationdlg.cpp.
References wxListCtrl::GetItemData(), wxListCtrl::GetNextItem(), wxListCtrl::GetSelectedItemCount(), cbPlugin::IsAttached(), PluginElement::plugin, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by sortByTitle().
The documentation for this class was generated from the following files:
pluginsconfigurationdlg.h
pluginsconfigurationdlg.cpp