Code::Blocks: IncrementalSelectListDlg Class Reference
IncrementalSelectListDlg Class Reference
#include <incrementalselectlistdlg.h>
Public Member Functions
IncrementalSelectListDlg (wxWindow *parent, const IncrementalSelectIterator &iterator, const wxString &caption=wxEmptyString, const wxString &message=wxEmptyString)
virtual ~IncrementalSelectListDlg ()
wxString GetStringSelection ()
wxIntPtr GetSelection ()
Public Member Functions inherited from IncrementalSelectListBase
IncrementalSelectListBase (wxWindow *parent, const IncrementalSelectIterator &iterator, const wxString &dialog, const wxString &caption=wxEmptyString, const wxString &message=wxEmptyString)
virtual ~IncrementalSelectListBase ()
void OnSearch (wxCommandEvent &event)
void OnSelect (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void GetCurrentSelection (int &selected, int &selectedMax) override
void UpdateCurrentSelection (int selected, int selectedPrevious) override
void FillData () override
refresh the list
Protected Member Functions inherited from IncrementalSelectListBase
void FilterItems ()
fetch the search key word from the text control, and filter the items
void KeyDownAction (wxKeyEvent &event, int &selected, int selectedMax)
handle user pressed some special key in the editor ctrl For example, if user press the UP key, we have to select some text before the cursor
void FillList ()
fill the m_List with filtered items
Private Member Functions
DECLARE_EVENT_TABLE ()
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from IncrementalSelectListBase
wxListBox * m_List
wxTextCtrl * m_Text
for showing the filtered items
wxArrayString m_Result
for entering search keys
wxArrayLong m_Indexes
the filtered items
bool m_Promoted
the filtered item index in the list
const IncrementalSelectIterator & m_Iterator
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 15 of file incrementalselectlistdlg.h.
Constructor & Destructor Documentation
IncrementalSelectListDlg()
IncrementalSelectListDlg::IncrementalSelectListDlg (wxWindow * parent, const IncrementalSelectIterator & iterator, const wxString & caption = wxEmptyString, const wxString & message = wxEmptyString)
Definition at line 30 of file incrementalselectlistdlg.cpp.
~IncrementalSelectListDlg()
IncrementalSelectListDlg::~IncrementalSelectListDlg () virtual
Definition at line 37 of file incrementalselectlistdlg.cpp.
Member Function Documentation
DECLARE_EVENT_TABLE()
IncrementalSelectListDlg::DECLARE_EVENT_TABLE () private
FillData()
void IncrementalSelectListDlg::FillData () override protected virtual
refresh the list
Reimplemented from IncrementalSelectListBase.
Definition at line 55 of file incrementalselectlistdlg.cpp.
References IncrementalSelectListBase::FillList(), and IncrementalSelectListBase::FilterItems().
GetCurrentSelection()
void IncrementalSelectListDlg::GetCurrentSelection (int & selected, int & selectedMax) override protected virtual
Reimplemented from IncrementalSelectListBase.
Definition at line 69 of file incrementalselectlistdlg.cpp.
References IncrementalSelectListBase::m_List.
GetSelection()
wxIntPtr IncrementalSelectListDlg::GetSelection ()
Definition at line 46 of file incrementalselectlistdlg.cpp.
References IncrementalSelectListBase::m_List.
Referenced by ProjectManagerUI::OnFindFile().
GetStringSelection()
wxString IncrementalSelectListDlg::GetStringSelection ()
Definition at line 41 of file incrementalselectlistdlg.cpp.
References IncrementalSelectListBase::m_List.
UpdateCurrentSelection()
void IncrementalSelectListDlg::UpdateCurrentSelection (int selected, int selectedPrevious) override protected virtual
Reimplemented from IncrementalSelectListBase.
Definition at line 75 of file incrementalselectlistdlg.cpp.
References IncrementalSelectListBase::m_List.
The documentation for this class was generated from the following files:
incrementalselectlistdlg.h
incrementalselectlistdlg.cpp