Code::Blocks: ConfigManagerWrapper Class Reference
ConfigManagerWrapper Class Reference
Wrapper class for reading or writing config values, without the need for the full path.
#include <configmanager.h>
Public Member Functions
ConfigManagerWrapper ()
ConfigManagerWrapper (wxString namespace_, wxString basepath)
bool IsValid () const
const wxString & GetBasepath () const
void Write (const wxString &name, const wxString &value, bool ignoreEmpty=false)
wxString Read (const wxString &key, const wxString &defaultVal=wxEmptyString)
bool Read (const wxString &key, wxString *str)
void Write (const wxString &key, const char *str)
void Write (const wxString &name, int value)
bool Read (const wxString &name, int *value)
int ReadInt (const wxString &name, int defaultVal=0)
void Write (const wxString &name, bool value)
bool Read (const wxString &name, bool *value)
bool ReadBool (const wxString &name, bool defaultVal=false)
void Write (const wxString &name, double value)
bool Read (const wxString &name, double *value)
double ReadDouble (const wxString &name, double defaultVal=0.0f)
Private Attributes
wxString m_namespace
wxString m_basepath
Detailed Description
Wrapper class for reading or writing config values, without the need for the full path.
It provides a way to sandbox a part of the code from the namespace details or the full path used to access the config values.
Definition at line 316 of file configmanager.h.
Constructor & Destructor Documentation
ConfigManagerWrapper() [1/2]
ConfigManagerWrapper::ConfigManagerWrapper () inline
Definition at line 319 of file configmanager.h.
ConfigManagerWrapper() [2/2]
ConfigManagerWrapper::ConfigManagerWrapper (wxString namespace_, wxString basepath) inline
Definition at line 320 of file configmanager.h.
Member Function Documentation
GetBasepath()
const wxString& ConfigManagerWrapper::GetBasepath () const inline
Definition at line 326 of file configmanager.h.
Referenced by DebuggerSettingsDlg::OnOK().
IsValid()
bool ConfigManagerWrapper::IsValid () const inline
Definition at line 325 of file configmanager.h.
Referenced by DebuggerSettingsDlg::OnOK().
Read() [1/5]
wxString ConfigManagerWrapper::Read (const wxString & key, const wxString & defaultVal = wxEmptyString)
Definition at line 1616 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Read().
Read() [2/5]
bool ConfigManagerWrapper::Read (const wxString & key, wxString * str)
Definition at line 1624 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Read().
Read() [3/5]
bool ConfigManagerWrapper::Read (const wxString & name, int * value)
Definition at line 1646 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Read().
Read() [4/5]
bool ConfigManagerWrapper::Read (const wxString & name, bool * value)
Definition at line 1669 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Read().
Read() [5/5]
bool ConfigManagerWrapper::Read (const wxString & name, double * value)
Definition at line 1691 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Read().
ReadBool()
bool ConfigManagerWrapper::ReadBool (const wxString & name, bool defaultVal = false)
Definition at line 1676 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::ReadBool().
ReadDouble()
double ConfigManagerWrapper::ReadDouble (const wxString & name, double defaultVal = 0.0f)
Definition at line 1698 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::ReadDouble().
ReadInt()
int ConfigManagerWrapper::ReadInt (const wxString & name, int defaultVal = 0)
Definition at line 1654 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::ReadInt().
Write() [1/5]
void ConfigManagerWrapper::Write (const wxString & name, const wxString & value, bool ignoreEmpty = false)
Definition at line 1608 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Write() [2/5]
void ConfigManagerWrapper::Write (const wxString & key, const char * str)
Definition at line 1631 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Write() [3/5]
void ConfigManagerWrapper::Write (const wxString & name, int value)
Definition at line 1639 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Write() [4/5]
void ConfigManagerWrapper::Write (const wxString & name, bool value)
Definition at line 1662 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Write() [5/5]
void ConfigManagerWrapper::Write (const wxString & name, double value)
Definition at line 1684 of file configmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Member Data Documentation
m_basepath
wxString ConfigManagerWrapper::m_basepath private
Definition at line 348 of file configmanager.h.
m_namespace
wxString ConfigManagerWrapper::m_namespace private
Definition at line 347 of file configmanager.h.
The documentation for this class was generated from the following files:
configmanager.h
configmanager.cpp