Code::Blocks: TimestampTextCtrlLogger Class Reference
TimestampTextCtrlLogger Class Reference
an extended logger from TextCtrlLogger, since it add time stamps for each log message
#include <loggers.h>
Public Member Functions
virtual void Append (const wxString &msg, Logger::level lv=info)
Public Member Functions inherited from TextCtrlLogger
TextCtrlLogger (bool fixedPitchFont=false)
~TextCtrlLogger ()
virtual void CopyContentsToClipboard (bool selectionOnly=false)
virtual void UpdateSettings ()
virtual void Clear ()
virtual wxWindow * CreateControl (wxWindow *parent)
virtual bool GetWrapMode () const
virtual void ToggleWrapMode ()
virtual bool HasFeature (Feature::Enum feature) const
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Protected Attributes inherited from TextCtrlLogger
wxTextCtrl * control
bool fixed
wxTextAttr style [num_levels]
Detailed Description
an extended logger from TextCtrlLogger, since it add time stamps for each log message
Definition at line 113 of file loggers.h.
Member Function Documentation
Append()
void TimestampTextCtrlLogger::Append (const wxString & msg, Logger::level lv = info) virtual
Reimplemented from TextCtrlLogger.
Definition at line 230 of file loggers.cpp.
References _T, wxString::c_str(), TextCtrlLogger::control, wxDateTime::GetHour(), wxDateTime::GetMillisecond(), wxDateTime::GetMinute(), wxDateTime::GetSecond(), TextCtrlLogger::style, and wxDateTime::UNow().
The documentation for this class was generated from the following files:
loggers.h
loggers.cpp