Code::Blocks: CCLogger Class Reference
CCLogger Class Reference
#include <cclogger.h>
Public Member Functions
void Init (wxEvtHandler *parent, int logId, int debugLogId, int addTokenId=-1)
void AddToken (const wxString &msg)
void Log (const wxString &msg)
void DebugLog (const wxString &msg)
Static Public Member Functions
static CCLogger * Get ()
Protected Member Functions
CCLogger ()
virtual ~CCLogger ()
CCLogger (const CCLogger &)
CCLogger & operator= (const CCLogger &)
Static Protected Attributes
static std::unique_ptr< CCLogger > s_Inst
Private Attributes
wxEvtHandler * m_Parent
int m_LogId
int m_DebugLogId
int m_AddTokenId
Friends
class std::default_delete< CCLogger >
Detailed Description
Definition at line 35 of file cclogger.h.
Constructor & Destructor Documentation
CCLogger() [1/2]
CCLogger::CCLogger () protected
Definition at line 52 of file cclogger.cpp.
~CCLogger()
virtual CCLogger::~CCLogger () inline protected virtual
Definition at line 47 of file cclogger.h.
CCLogger() [2/2]
CCLogger::CCLogger (const CCLogger &) inline protected
Definition at line 48 of file cclogger.h.
Member Function Documentation
AddToken()
void CCLogger::AddToken (const wxString & msg)
Definition at line 77 of file cclogger.cpp.
References m_AddTokenId, m_Parent, and wxPostEvent().
DebugLog()
void CCLogger::DebugLog (const wxString & msg)
Definition at line 107 of file cclogger.cpp.
References Manager::IsAppShuttingDown(), m_DebugLogId, m_Parent, and wxPostEvent().
Referenced by NativeParser::AddCompilerDirs(), NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddIncludeDirsToParser(), ClassBrowserBuilderThread::AddMembersOf(), ClassBrowserBuilderThread::AddNodes(), NativeParser::AddProjectToParser(), NativeParser::AI(), NativeParserBase::BreakUpComponents(), CodeCompletion::BuildMenu(), CodeCompletion::BuildModuleMenu(), ClassBrowserBuilderThread::BuildTree(), NativeParser::CreateParser(), NativeParser::DeleteParser(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeCompletion::DoCodeComplete(), NativeParser::DoFullParsing(), ClassBrowserBuilderThread::ExpandItem(), NativeParserBase::FindAIMatches(), NativeParserBase::FindCurrentFunctionScope(), NativeParser::FindCurrentFunctionStart(), NativeParserBase::GenerateResultSet(), NativeParser::GetAllPathsByFilename(), NativeParser::GetCompilerUsingStandardGCC(), NativeParser::GetGCCCompilerDirs(), Parser::GetPredefinedMacros(), CodeRefactoring::GetSymbolUnderCursor(), NativeParser::MarkItemsByAI(), Parser::OnAllThreadsDone(), NativeParser::OnEditorActivated(), NativeParser::OnParserEnd(), NativeParser::OnParserStart(), NativeParser::OnParsingOneByOneTimer(), CodeCompletion::OnProjectFileChanged(), CodeCompletion::OnProjectSavedTimer(), CodeCompletion::OnRealtimeParsingTimer(), CodeCompletion::OnReparsingTimer(), CodeCompletion::OnSelectedFileReparse(), CodeCompletion::OnSystemHeadersThreadFinish(), CodeCompletion::OnSystemHeadersThreadMessage(), ClassBrowser::OnThreadEvent(), ClassBrowser::OnViewScope(), NativeParser::ParseBufferForUsingNamespace(), NativeParser::ParseFunctionArguments(), CodeCompletion::ParseFunctionsAndFillToolbar(), NativeParser::ParseLocalBlock(), NativeParser::ParseUsingNamespace(), ParserThread::ReadClsNames(), ParserThread::ReadVarNames(), CCTreeCtrl::RemoveDoubles(), NativeParser::RemoveObsoleteParsers(), NativeParser::RemoveProjectFromParser(), TokenTree::RemoveToken(), Parser::Reparse(), Parser::ReparseModifiedFiles(), NativeParserBase::ResolveExpression(), ClassBrowserBuilderThread::SelectItem(), ClassBrowser::SetParser(), NativeParser::SwitchParser(), ClassBrowser::UpdateClassBrowserView(), and Parser::UpdateParsingProject().
Get()
CCLogger * CCLogger::Get () static
Definition at line 60 of file cclogger.cpp.
References s_Inst.
Referenced by NativeParser::AddCompilerDirs(), NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddIncludeDirsToParser(), ClassBrowserBuilderThread::AddMembersOf(), ClassBrowserBuilderThread::AddNodes(), NativeParser::AddProjectToParser(), NativeParser::AI(), NativeParserBase::BreakUpComponents(), CodeCompletion::BuildMenu(), CodeCompletion::BuildModuleMenu(), ClassBrowserBuilderThread::BuildTree(), CodeCompletion::CodeCompletion(), NativeParser::CreateParser(), NativeParser::DeleteParser(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeCompletion::DoCodeComplete(), NativeParser::DoFullParsing(), ClassBrowserBuilderThread::ExpandItem(), NativeParserBase::FindAIMatches(), NativeParserBase::FindCurrentFunctionScope(), NativeParser::FindCurrentFunctionStart(), NativeParserBase::GenerateResultSet(), NativeParser::GetAllPathsByFilename(), NativeParser::GetCompilerUsingStandardGCC(), NativeParser::GetGCCCompilerDirs(), Parser::GetPredefinedMacros(), CodeRefactoring::GetSymbolUnderCursor(), NativeParser::MarkItemsByAI(), Parser::OnAllThreadsDone(), NativeParser::OnEditorActivated(), NativeParser::OnParserEnd(), NativeParser::OnParserStart(), NativeParser::OnParsingOneByOneTimer(), CodeCompletion::OnProjectFileChanged(), CodeCompletion::OnProjectSavedTimer(), CodeCompletion::OnRealtimeParsingTimer(), CodeCompletion::OnReparsingTimer(), CodeCompletion::OnSelectedFileReparse(), CodeCompletion::OnSystemHeadersThreadFinish(), CodeCompletion::OnSystemHeadersThreadMessage(), ClassBrowser::OnThreadEvent(), ClassBrowser::OnViewScope(), NativeParser::ParseBufferForUsingNamespace(), NativeParser::ParseFunctionArguments(), CodeCompletion::ParseFunctionsAndFillToolbar(), NativeParser::ParseLocalBlock(), NativeParser::ParseUsingNamespace(), ParserThread::ReadClsNames(), ParserThread::ReadVarNames(), CCTreeCtrl::RemoveDoubles(), NativeParser::RemoveObsoleteParsers(), NativeParser::RemoveProjectFromParser(), TokenTree::RemoveToken(), Parser::Reparse(), Parser::ReparseModifiedFiles(), NativeParserBase::ResolveExpression(), ClassBrowserBuilderThread::SelectItem(), ClassBrowser::SetParser(), NativeParser::SwitchParser(), ClassBrowser::UpdateClassBrowserView(), and Parser::UpdateParsingProject().
Init()
void CCLogger::Init (wxEvtHandler * parent, int logId, int debugLogId, int addTokenId = -1)
Definition at line 69 of file cclogger.cpp.
References m_AddTokenId, m_DebugLogId, m_LogId, and m_Parent.
Referenced by CodeCompletion::CodeCompletion().
Log()
void CCLogger::Log (const wxString & msg)
Definition at line 90 of file cclogger.cpp.
References Manager::IsAppShuttingDown(), m_LogId, m_Parent, and wxPostEvent().
Referenced by NativeParser::AddProjectToParser(), NativeParser::CreateParser(), NativeParser::DeleteParser(), NativeParser::OnParserEnd(), NativeParser::OnParsingOneByOneTimer(), NativeParser::RemoveObsoleteParsers(), NativeParser::RemoveProjectFromParser(), and NativeParser::SwitchParser().
operator=()
CCLogger& CCLogger::operator= (const CCLogger &) inline protected
Definition at line 49 of file cclogger.h.
Friends And Related Function Documentation
std::default_delete< CCLogger >
friend class std::default_delete< CCLogger > friend
Definition at line 52 of file cclogger.h.
Member Data Documentation
m_AddTokenId
int CCLogger::m_AddTokenId private
Definition at line 59 of file cclogger.h.
Referenced by AddToken(), and Init().
m_DebugLogId
int CCLogger::m_DebugLogId private
Definition at line 58 of file cclogger.h.
Referenced by DebugLog(), and Init().
m_LogId
int CCLogger::m_LogId private
Definition at line 57 of file cclogger.h.
Referenced by Init(), and Log().
m_Parent
wxEvtHandler* CCLogger::m_Parent private
Definition at line 56 of file cclogger.h.
Referenced by AddToken(), DebugLog(), Init(), and Log().
s_Inst
std::unique_ptr< CCLogger > CCLogger::s_Inst static protected
Definition at line 53 of file cclogger.h.
Referenced by Get().
The documentation for this class was generated from the following files:
cclogger.h
cclogger.cpp