Code::Blocks: cbPlugin Class Reference
cbPlugin Class Reference
Base class for plugins This is the most basic class a plugin must descend from.
#include <cbplugin.h>
Public Member Functions
cbPlugin ()
In default cbPlugin's constructor the associated PluginInfo structure is filled with default values.
virtual ~cbPlugin ()
cbPlugin destructor.
virtual PluginType GetType () const
The plugin must return its type on request.
virtual int GetConfigurationPriority () const
Return the plugin's configuration priority.
virtual int GetConfigurationGroup () const
Return the configuration group for this plugin.
virtual cbConfigurationPanel * GetConfigurationPanel (cb_optional wxWindow *parent)
Return plugin's configuration panel.
virtual cbConfigurationPanel * GetProjectConfigurationPanel (cb_optional wxWindow *parent, cb_optional cbProject *project)
Return plugin's configuration panel for projects.
virtual void BuildMenu (cb_optional wxMenuBar *menuBar)
This method is called by Code::Blocks and is used by the plugin to add any menu items it needs on Code::Blocks's menu bar.
virtual void BuildModuleMenu (cb_optional const ModuleType type, cb_optional wxMenu *menu, cb_optional const FileTreeData *data=nullptr)
This method is called by Code::Blocks core modules (EditorManager, ProjectManager etc) and is used by the plugin to add any menu items it needs in the module's popup menu.
virtual bool BuildToolBar (cb_optional wxToolBar *toolBar)
This method is called by Code::Blocks and is used by the plugin to add any toolbar items it needs on Code::Blocks's toolbar.
virtual int GetToolBarPriority ()
This method return the priority of the plugin's toolbar, the less value indicates a more preceding position when C::B starts with no configuration file.
virtual void CreateStatusField (cbStatusBar *statusBar)
This method is called by Code::Blocks and is used by the plugin to add a field on Code::Blocks's statusbar.
bool IsAttached () const
See whether this plugin is attached or not.
virtual bool CanDetach () const
See whether this plugin can be detached (unloaded) or not.
Protected Member Functions
virtual void OnAttach ()
Any descendent plugin should override this virtual method and perform any necessary initialization.
virtual void OnRelease (cb_optional bool appShutDown)
Any descendent plugin should override this virtual method and perform any necessary de-initialization.
virtual void NotImplemented (const wxString &log) const
This method logs a "Not implemented" message and is provided for convenience only.
Protected Attributes
PluginType m_Type
Holds the plugin's type.
bool m_IsAttached
Holds the "attached" state.
Private Member Functions
void Attach ()
Attach is not a virtual function, so you can't override it.
void Release (bool appShutDown)
Release is not a virtual function, so you can't override it.
Friends
class PluginManager
Detailed Description
Base class for plugins This is the most basic class a plugin must descend from.
cbPlugin descends from wxEvtHandler, so it provides its methods as well...
It's not enough to create a new plugin. You must also provide a resource zip file containing a file named "manifest.xml". Check the manifest.xml file of existing plugins to see how to create one (it's ultra-simple).
Constructor & Destructor Documentation
cbPlugin::cbPlugin ()
In default cbPlugin's constructor the associated PluginInfo structure is filled with default values.
If you inherit from cbPlugin, you should fill the m_PluginInfo members with the appropriate values.
cbPlugin::~cbPlugin () virtual
cbPlugin destructor.
Member Function Documentation
void cbPlugin::Attach () private
Attach is not a virtual function, so you can't override it.
The default implementation hooks the plugin to Code::Block's event handling system, so that the plugin can receive (and process) events from Code::Blocks core library. Use OnAttach() for any initialization specific tasks.
See also
OnAttach()
References cbEVT_PLUGIN_ATTACHED, Manager::Get(), Manager::GetAppWindow(), m_IsAttached, OnAttach(), and Manager::ProcessEvent().
Referenced by PluginManager::AttachPlugin().
virtual void cbPlugin::BuildMenu (cb_optional wxMenuBar * menuBar) inline virtual
This method is called by Code::Blocks and is used by the plugin to add any menu items it needs on Code::Blocks's menu bar.
It is a pure virtual method that needs to be implemented by all plugins. If the plugin does not need to add items on the menu, just do nothing ;)
Note
This function may be called more than one time. This can happen, for example, when a plugin is installed or uninstalled.
Parameters
menuBar the wxMenuBar to create items in
Referenced by MainFrame::CreateMenubar(), and MainFrame::DoAddPlugin().
virtual void cbPlugin::BuildModuleMenu (cb_optional const ModuleType type, cb_optional wxMenu * menu, cb_optional const FileTreeData * data = nullptr) inline virtual
This method is called by Code::Blocks core modules (EditorManager, ProjectManager etc) and is used by the plugin to add any menu items it needs in the module's popup menu.
For example, when the user right-clicks on a project file in the project tree, ProjectManager prepares a popup menu to display with context sensitive options for that file. Before it displays this popup menu, it asks all attached plugins (by asking PluginManager to call this method), if they need to add any entries in that menu. This method is called.
If the plugin does not need to add items in the menu, just do nothing ;)
Parameters
type the module that's preparing a popup menu
menu pointer to the popup menu
data pointer to FileTreeData object (to access/modify the file tree)
Referenced by PluginManager::AskPluginsForModuleMenu().
virtual bool cbPlugin::BuildToolBar (cb_optional wxToolBar * toolBar) inline virtual
This method is called by Code::Blocks and is used by the plugin to add any toolbar items it needs on Code::Blocks's toolbar.
It is a pure virtual method that needs to be implemented by all plugins. If the plugin does not need to add items on the toolbar, just do nothing ;)
Parameters
toolBar the wxToolBar to create items on
Returns
The plugin should return true if it needed the toolbar, false if not
Referenced by MainFrame::DoAddPluginToolbar().
virtual bool cbPlugin::CanDetach () const inline virtual
See whether this plugin can be detached (unloaded) or not.
This function is called usually when the user requests to uninstall or disable a plugin. Before disabling/uninstalling it, Code::Blocks asks the plugin if it can be detached or not. In other words, it checks to see if it can be disabled/uninstalled safely...
A plugin should return true if it can be detached at this moment, false if not.
Returns
The default implementation returns true.
virtual void cbPlugin::CreateStatusField (cbStatusBar * statusBar) inline virtual
This method is called by Code::Blocks and is used by the plugin to add a field on Code::Blocks's statusbar.
If the plugin does not need to add items on the statusbar, just do nothing ;)
Parameters
statusBar the cbStatusBar to create items on
Referenced by MainFrame::DoAddPluginStatusField().
virtual int cbPlugin::GetConfigurationGroup () const inline virtual
Return the configuration group for this plugin.
Default is cgUnknown. Notice that you can logically AND more than one configuration groups, so you could set it, for example, as "cgCompiler | cgContribPlugin".
Reimplemented in CompilerGCC, and CodeCompletion.
References cgUnknown.
Referenced by PluginManager::GetConfigurationPanels().
virtual cbConfigurationPanel* cbPlugin::GetConfigurationPanel (cb_optional wxWindow * parent) inline virtual
Return plugin's configuration panel.
Parameters
parent The parent window.
Returns
A pointer to the plugin's cbConfigurationPanel. It is deleted by the caller.
Referenced by PluginManager::GetConfigurationPanels().
virtual int cbPlugin::GetConfigurationPriority () const inline virtual
Return the plugin's configuration priority.
This is a number (default is 50) that is used to sort plugins in configuration dialogs. Lower numbers mean the plugin's configuration is put higher in the list.
Reimplemented in CompilerGCC.
virtual cbConfigurationPanel* cbPlugin::GetProjectConfigurationPanel (cb_optional wxWindow * parent, cb_optional cbProject * project) inline virtual
Return plugin's configuration panel for projects.
The panel returned from this function will be added in the project's configuration dialog.
Parameters
parent The parent window.
project The project that is being edited.
Returns
A pointer to the plugin's cbConfigurationPanel. It is deleted by the caller.
Referenced by PluginManager::GetProjectConfigurationPanels().
virtual int cbPlugin::GetToolBarPriority () inline virtual
This method return the priority of the plugin's toolbar, the less value indicates a more preceding position when C::B starts with no configuration file.
Reimplemented in CodeCompletion, and CompilerGCC.
Referenced by MainFrame::DoAddPluginToolbar().
virtual PluginType cbPlugin::GetType () const inline virtual
The plugin must return its type on request.
Referenced by MainFrame::CreateMenubar(), MainFrame::DoAddPlugin(), PluginManager::ExecutePlugin(), and PluginManager::GetOffersFor().
bool cbPlugin::IsAttached () const inline
See whether this plugin is attached or not.
A plugin should not perform any of its tasks, if not attached...
Note
This function is not virtual.
Returns
Returns true if it attached, false if not.
Referenced by PluginManager::AskPluginsForModuleMenu(), PluginManager::AttachPlugin(), CodeCompletion::BuildMenu(), CompilerGCC::BuildMenu(), cbDebuggerPlugin::BuildMenu(), CodeCompletion::BuildModuleMenu(), CompilerGCC::BuildModuleMenu(), cbDebuggerPlugin::BuildModuleMenu(), CompilerGCC::BuildToolBar(), CompilerSettingsDlg::CompilerSettingsDlg(), MainFrame::CreateMenubar(), MainFrame::CreateToolbars(), cbDebuggerPlugin::DebugLog(), PluginManager::DetachPlugin(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CompilerGCC::DoRecreateTargetMenu(), CodeCompletion::EditorEventHook(), PluginsConfigurationDlg::FillList(), CodeCompletion::GetAutocompList(), CodeCompletion::GetCallTips(), PluginManager::GetConfigurationPanels(), PluginManager::GetOffersFor(), PluginManager::GetProjectConfigurationPanels(), CodeCompletion::GetTokenAt(), PluginManager::LoadAllPlugins(), cbDebuggerPlugin::Log(), CodeCompletion::OnEditorActivated(), CodeCompletion::OnEditorOpen(), CodeCompletion::OnEditorSave(), CodeCompletion::OnProjectActivated(), CodeCompletion::OnProjectClosed(), CodeCompletion::OnProjectFileAdded(), CodeCompletion::OnProjectFileChanged(), CodeCompletion::OnProjectFileRemoved(), CodeCompletion::OnProjectSavedTimer(), CodeCompletion::OnReparsingTimer(), PluginsConfigurationDlg::OnToggle(), PluginsConfigurationDlg::OnUpdateUI(), and CodeCompletion::OnWorkspaceChanged().
void cbPlugin::NotImplemented (const wxString & log) const protected virtual
This method logs a "Not implemented" message and is provided for convenience only.
References LogManager::DebugLog(), Manager::Get(), and Manager::GetLogManager().
Referenced by CompilerGCC::DistClean().
virtual void cbPlugin::OnAttach () inline protected virtual
Any descendent plugin should override this virtual method and perform any necessary initialization.
This method is called by Code::Blocks (PluginManager actually) when the plugin has been loaded and should attach in Code::Blocks. When Code::Blocks starts up, it finds and loads all plugins but does not activate (attaches) them. It then activates all plugins that the user has selected to be activated on start-up.
This means that a plugin might be loaded but not activated...
Think of this method as the actual constructor...
Reimplemented in cbSmartIndentPlugin, cbDebuggerPlugin, Wiz, CompilerGCC, and CodeCompletion.
Referenced by Attach().
virtual void cbPlugin::OnRelease (cb_optional bool appShutDown) inline protected virtual
Any descendent plugin should override this virtual method and perform any necessary de-initialization.
This method is called by Code::Blocks (PluginManager actually) when the plugin has been loaded, attached and should de-attach from Code::Blocks.
Think of this method as the actual destructor...
Parameters
appShutDown If true, the application is shutting down. In this case don't use Manager::Get()->Get...() functions or the behaviour is undefined...
Referenced by Release().
void cbPlugin::Release (bool appShutDown) private
Release is not a virtual function, so you can't override it.
The default implementation un-hooks the plugin from Code::Blocks's event handling system. Use OnRelease() for any clean-up specific tasks.
Parameters
appShutDown If true, the application is shutting down. In this case don't use Manager::Get()->Get...() functions or the behaviour is undefined...
See also
OnRelease()
References cbEVT_PLUGIN_RELEASED, Manager::Get(), Manager::GetAppWindow(), m_IsAttached, OnRelease(), and Manager::ProcessEvent().
Referenced by PluginManager::DetachPlugin().
Friends And Related Function Documentation
friend class PluginManager friend
Member Data Documentation
bool cbPlugin::m_IsAttached protected
Holds the "attached" state.
Referenced by Attach(), and Release().
PluginType cbPlugin::m_Type protected
Holds the plugin's type.
Set in the default constructor.
Referenced by cbCodeCompletionPlugin::cbCodeCompletionPlugin(), cbCompilerPlugin::cbCompilerPlugin(), cbDebuggerPlugin::cbDebuggerPlugin(), cbMimePlugin::cbMimePlugin(), cbSmartIndentPlugin::cbSmartIndentPlugin(), cbToolPlugin::cbToolPlugin(), and cbWizardPlugin::cbWizardPlugin().
The documentation for this class was generated from the following files:
cbplugin.h
cbplugin.cpp