Code::Blocks: WizProjectPathPanel Class Reference
WizProjectPathPanel Class Reference
#include <wizpage.h>
Public Member Functions
WizProjectPathPanel (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizProjectPathPanel ()
wxString GetPath () const
wxString GetName () const
wxString GetFullFileName () const
wxString GetTitle () const
void OnButton (wxCommandEvent &event)
virtual void OnPageChanging (wxWizardEvent &event)
virtual void OnPageChanged (wxWizardEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
ProjectPathPanel * m_pProjectPathPanel
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 99 of file wizpage.h.
Constructor & Destructor Documentation
WizProjectPathPanel()
WizProjectPathPanel::WizProjectPathPanel (wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 331 of file wizpage.cpp.
~WizProjectPathPanel()
WizProjectPathPanel::~WizProjectPathPanel ()
Definition at line 338 of file wizpage.cpp.
Member Function Documentation
GetFullFileName()
wxString WizProjectPathPanel::GetFullFileName () const
Definition at line 355 of file wizpage.cpp.
Referenced by Wiz::GetProjectFullFilename().
GetName()
wxString WizProjectPathPanel::GetName () const
Definition at line 349 of file wizpage.cpp.
Referenced by Wiz::GetProjectName().
GetPath()
wxString WizProjectPathPanel::GetPath () const
Definition at line 343 of file wizpage.cpp.
References AppendPathSepIfNeeded().
Referenced by Wiz::GetProjectPath().
GetTitle()
wxString WizProjectPathPanel::GetTitle () const
Definition at line 361 of file wizpage.cpp.
Referenced by Wiz::GetProjectTitle().
OnButton()
void WizProjectPathPanel::OnButton (wxCommandEvent & event)
Definition at line 367 of file wizpage.cpp.
References _(), ChooseDirectory(), wxString::IsEmpty(), wxDirExists(), and wxEmptyString.
Referenced by WizFilePathPanel::OnPageChanging().
OnPageChanged()
void WizProjectPathPanel::OnPageChanged (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 421 of file wizpage.cpp.
References Manager::Get(), ProjectManager::GetDefaultPath(), wxWizardEvent::GetDirection(), Manager::GetProjectManager(), WizGenericSelectPathPanel::OnButton(), and WizPageBase::OnPageChanged().
OnPageChanging()
void WizProjectPathPanel::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 376 of file wizpage.cpp.
References _(), cbMessageBox(), Manager::Get(), wxWizardEvent::GetDirection(), Manager::GetProjectManager(), wxString::IsEmpty(), WizPageBase::OnPageChanging(), ProjectManager::SetDefaultPath(), wxFileExists(), wxICON_ERROR, wxICON_QUESTION, wxID_YES, and wxYES_NO.
Member Data Documentation
m_pProjectPathPanel
ProjectPathPanel* WizProjectPathPanel::m_pProjectPathPanel private
Definition at line 114 of file wizpage.h.
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp