Code::Blocks: MacrosManager Class Reference
MacrosManager Class Reference
#include <macrosmanager.h>
Public Member Functions
void CreateMenu (wxMenuBar *menuBar)
void ReleaseMenu (wxMenuBar *menuBar)
void ReplaceMacros (wxString &buffer, ProjectBuildTarget *target=nullptr, bool subrequest=false)
wxString ReplaceMacros (const wxString &buffer, ProjectBuildTarget *target=nullptr)
void ReplaceEnvVars (wxString &buffer)
void RecalcVars (cbProject *project, EditorBase *editor, ProjectBuildTarget *target)
void ClearProjectKeys ()
void Reset ()
Protected Attributes
ProjectBuildTarget * m_LastTarget
cbProject * m_LastProject
wxFileName m_ProjectWxFileName
wxFileName m_WorkspaceWxFileName
wxString m_AppPath
wxString m_DataPath
wxString m_Plugins
wxString m_ActiveEditorFilename
int m_ActiveEditorLine
int m_ActiveEditorColumn
wxString m_WorkspaceFilename
wxString m_WorkspaceName
wxString m_WorkspaceDir
wxString m_ProjectFilename
wxString m_ProjectName
wxString m_ProjectDir
wxString m_ProjectTopDir
wxString m_ProjectFiles
wxString m_Makefile
wxString m_TargetOutputDir
wxString m_TargetName
wxString m_TargetOutputBaseName
wxString m_TargetOutputFilename
wxString m_TargetFilename
MacrosMap m_Macros
wxRegEx m_RE_Unix
wxRegEx m_RE_DOS
wxRegEx m_RE_If
wxRegEx m_RE_IfSp
wxRegEx m_RE_Script
wxRegEx m_RE_ToAbsolutePath
wxRegEx m_RE_To83Path
wxRegEx m_RE_RemoveQuotes
UserVariableManager * m_UserVarMan
Private Member Functions
MacrosManager ()
~MacrosManager ()
wxString EvalCondition (const wxString &cond, const wxString &true_clause, const wxString &false_clause, ProjectBuildTarget *target)
int MatchBrace (const wxString &buffer, int index)
Friends
class Manager
class Mgr< MacrosManager >
Additional Inherited Members
Static Public Member Functions inherited from Mgr< MacrosManager >
static bool Valid ()
static MacrosManager * Get ()
static void Free ()
Protected Member Functions inherited from Mgr< MacrosManager >
Mgr ()
virtual ~Mgr ()
Detailed Description
Definition at line 23 of file macrosmanager.h.
Constructor & Destructor Documentation
MacrosManager()
MacrosManager::MacrosManager () private
Definition at line 50 of file macrosmanager.cpp.
~MacrosManager()
MacrosManager::~MacrosManager () private
Definition at line 55 of file macrosmanager.cpp.
Member Function Documentation
ClearProjectKeys()
void MacrosManager::ClearProjectKeys ()
Definition at line 115 of file macrosmanager.cpp.
References Manager::Get(), cbWorkspace::GetFilename(), Manager::GetProjectManager(), cbWorkspace::GetTitle(), ProjectManager::GetWorkspace(), and UnixFilename().
CreateMenu()
void MacrosManager::CreateMenu (wxMenuBar * menuBar)
Definition at line 59 of file macrosmanager.cpp.
EvalCondition()
wxString MacrosManager::EvalCondition (const wxString & cond, const wxString & true_clause, const wxString & false_clause, ProjectBuildTarget * target) private
Definition at line 616 of file macrosmanager.cpp.
References ExpressionConsts::GT(), and ExpressionConsts::LT().
MatchBrace()
int MacrosManager::MatchBrace (const wxString & buffer, int index) private
Definition at line 668 of file macrosmanager.cpp.
RecalcVars()
void MacrosManager::RecalcVars (cbProject * project, EditorBase * editor, ProjectBuildTarget * target)
Definition at line 217 of file macrosmanager.cpp.
References CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), wxScintilla::GetColumn(), cbProject::GetCommonTopLevelPath(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), cbEditor::GetControl(), wxScintilla::GetCurrentLine(), wxScintilla::GetCurrentPos(), CompileTargetBase::GetExecutionParameters(), EditorBase::GetFilename(), CompileTargetBase::GetFilename(), cbProject::GetFilesList(), cbProject::GetMakefile(), CompileTargetBase::GetObjectOutput(), CompileTargetBase::GetOutputFilename(), GetSelectedText(), CompileTargetBase::GetTitle(), EditorBase::IsBuiltinEditor(), QuoteStringIfNeeded(), and UnixFilename().
Referenced by CompilerGCC::BuildStateManagement(), and ToolsManager::Execute().
ReleaseMenu()
void MacrosManager::ReleaseMenu (wxMenuBar * menuBar)
Definition at line 63 of file macrosmanager.cpp.
ReplaceEnvVars()
void MacrosManager::ReplaceEnvVars (wxString & buffer) inline
Definition at line 32 of file macrosmanager.h.
Referenced by DebuggerGDB::AddSourceDir(), GdbCmd_RemoteTarget::GdbCmd_RemoteTarget(), cbDebuggerPlugin::GetDebuggee(), DebuggerConfiguration::GetDebuggerExecutable(), DebuggerConfiguration::GetUserArguments(), EditPathDlg::OnBrowse(), DebuggerConfigurationPanel::OnBrowse(), CompilerGCC::OnCleanFile(), CompilerGCC::Run(), cbDebuggerPlugin::RunNixConsole(), CompilerGCC::RunSingleFile(), pfDetails::Update(), and DebuggerConfigurationPanel::ValidateExecutablePath().
ReplaceMacros() [1/2]
void MacrosManager::ReplaceMacros (wxString & buffer, ProjectBuildTarget * target = nullptr, bool subrequest = false)
Definition at line 435 of file macrosmanager.cpp.
References const_COIN(), const_RANDOM(), Manager::Get(), cbProject::GetActiveBuildTarget(), EditorManager::GetActiveEditor(), ProjectManager::GetActiveProject(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetCurrentlyCompilingTarget(), Manager::GetEditorManager(), EditorBase::GetFilename(), ProjectBuildTarget::GetParentProject(), Manager::GetProjectManager(), Manager::GetScriptingManager(), CompileTargetBase::GetTitle(), ScriptingManager::LoadBufferRedirectOutput(), toNativePath(), toUnixPath(), toWindowsPath(), and UnixFilename().
Referenced by NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), cbProject::AddFile(), NativeParser::AddGCCCompilerDirs(), NativeParser::AddIncludeDirsToParser(), NativeParser::AddProjectDefinedMacros(), DirectCommands::AreExternalDepsOutdated(), AutoDetectCompilers::AutoDetectCompilers(), CompilerICC::AutoDetectInstallationDir(), DirectCommands::DepsSearchStart(), CompilerCommandGenerator::DoBuildScripts(), CompilerGCC::DoRunQueue(), ToolsManager::Execute(), CompilerCommandGenerator::GenerateCommandLine(), CodeCompletion::GetAbsolutePath(), CompilerGCC::GetMakeCommandFor(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), CompilerCommandGenerator::GetOrderedResourceIncludeDirs(), CompilerCommandGenerator::GetProcessedIncludeDir(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), ScriptBindings::gReplaceMacros(), GDB_driver::InitializeScripting(), PluginManager::InstallPlugin(), ProjectOptionsDlg::IsScriptValid(), Compiler::IsValid(), EditorManager::New(), WizGenericSelectPathPanel::OnButton(), CompilerGCC::OnJobEnd(), WizGenericSelectPathPanel::OnPageChanging(), GDB_driver::Prepare(), CompilerGCC::Run(), CompilerCommandGenerator::SetupCompilerOptions(), CompilerGCC::SetupEnvironment(), CompilerOWGenerator::SetupLibrariesDirs(), CompilerOWGenerator::SetupLinkerOptions(), CompilerCommandGenerator::SetupLinkerOptions(), CompilerCommandGenerator::SetupOutputFilenames(), CompilerCommandGenerator::SetupResourceCompilerOptions(), CompilerMINGW::SetVersionString(), EditorManager::SwapActiveHeaderSource(), and pfDetails::Update().
ReplaceMacros() [2/2]
wxString MacrosManager::ReplaceMacros (const wxString & buffer, ProjectBuildTarget * target = nullptr)
Definition at line 67 of file macrosmanager.cpp.
Reset()
void MacrosManager::Reset ()
Definition at line 74 of file macrosmanager.cpp.
References Manager::Get(), ConfigManager::GetDataFolder(), ConfigManager::GetExecutableFolder(), ConfigManager::GetPluginsFolder(), Manager::GetUserVariableManager(), and UnixFilename().
Referenced by CompilerGCC::CompileFileWithoutProject(), CompilerGCC::Configure(), and CompilerOptionsDlg::OnApply().
Friends And Related Function Documentation
Manager
friend class Manager friend
Definition at line 26 of file macrosmanager.h.
Mgr< MacrosManager >
friend class Mgr< MacrosManager > friend
Definition at line 27 of file macrosmanager.h.
Member Data Documentation
m_ActiveEditorColumn
int MacrosManager::m_ActiveEditorColumn protected
Definition at line 48 of file macrosmanager.h.
m_ActiveEditorFilename
wxString MacrosManager::m_ActiveEditorFilename protected
Definition at line 46 of file macrosmanager.h.
m_ActiveEditorLine
int MacrosManager::m_ActiveEditorLine protected
Definition at line 47 of file macrosmanager.h.
m_AppPath
wxString MacrosManager::m_AppPath protected
Definition at line 43 of file macrosmanager.h.
m_DataPath
wxString MacrosManager::m_DataPath protected
Definition at line 44 of file macrosmanager.h.
m_LastProject
cbProject* MacrosManager::m_LastProject protected
Definition at line 38 of file macrosmanager.h.
m_LastTarget
ProjectBuildTarget* MacrosManager::m_LastTarget protected
Definition at line 37 of file macrosmanager.h.
m_Macros
MacrosMap MacrosManager::m_Macros protected
Definition at line 64 of file macrosmanager.h.
m_Makefile
wxString MacrosManager::m_Makefile protected
Definition at line 57 of file macrosmanager.h.
m_Plugins
wxString MacrosManager::m_Plugins protected
Definition at line 45 of file macrosmanager.h.
m_ProjectDir
wxString MacrosManager::m_ProjectDir protected
Definition at line 54 of file macrosmanager.h.
m_ProjectFilename
wxString MacrosManager::m_ProjectFilename protected
Definition at line 52 of file macrosmanager.h.
m_ProjectFiles
wxString MacrosManager::m_ProjectFiles protected
Definition at line 56 of file macrosmanager.h.
m_ProjectName
wxString MacrosManager::m_ProjectName protected
Definition at line 53 of file macrosmanager.h.
m_ProjectTopDir
wxString MacrosManager::m_ProjectTopDir protected
Definition at line 55 of file macrosmanager.h.
m_ProjectWxFileName
wxFileName MacrosManager::m_ProjectWxFileName protected
Definition at line 40 of file macrosmanager.h.
m_RE_DOS
wxRegEx MacrosManager::m_RE_DOS protected
Definition at line 66 of file macrosmanager.h.
m_RE_If
wxRegEx MacrosManager::m_RE_If protected
Definition at line 67 of file macrosmanager.h.
m_RE_IfSp
wxRegEx MacrosManager::m_RE_IfSp protected
Definition at line 68 of file macrosmanager.h.
m_RE_RemoveQuotes
wxRegEx MacrosManager::m_RE_RemoveQuotes protected
Definition at line 72 of file macrosmanager.h.
m_RE_Script
wxRegEx MacrosManager::m_RE_Script protected
Definition at line 69 of file macrosmanager.h.
m_RE_To83Path
wxRegEx MacrosManager::m_RE_To83Path protected
Definition at line 71 of file macrosmanager.h.
m_RE_ToAbsolutePath
wxRegEx MacrosManager::m_RE_ToAbsolutePath protected
Definition at line 70 of file macrosmanager.h.
m_RE_Unix
wxRegEx MacrosManager::m_RE_Unix protected
Definition at line 65 of file macrosmanager.h.
m_TargetFilename
wxString MacrosManager::m_TargetFilename protected
Definition at line 62 of file macrosmanager.h.
m_TargetName
wxString MacrosManager::m_TargetName protected
Definition at line 59 of file macrosmanager.h.
m_TargetOutputBaseName
wxString MacrosManager::m_TargetOutputBaseName protected
Definition at line 60 of file macrosmanager.h.
m_TargetOutputDir
wxString MacrosManager::m_TargetOutputDir protected
Definition at line 58 of file macrosmanager.h.
m_TargetOutputFilename
wxString MacrosManager::m_TargetOutputFilename protected
Definition at line 61 of file macrosmanager.h.
m_UserVarMan
UserVariableManager* MacrosManager::m_UserVarMan protected
Definition at line 73 of file macrosmanager.h.
m_WorkspaceDir
wxString MacrosManager::m_WorkspaceDir protected
Definition at line 51 of file macrosmanager.h.
m_WorkspaceFilename
wxString MacrosManager::m_WorkspaceFilename protected
Definition at line 49 of file macrosmanager.h.
m_WorkspaceName
wxString MacrosManager::m_WorkspaceName protected
Definition at line 50 of file macrosmanager.h.
m_WorkspaceWxFileName
wxFileName MacrosManager::m_WorkspaceWxFileName protected
Definition at line 41 of file macrosmanager.h.
The documentation for this class was generated from the following files:
macrosmanager.h
macrosmanager.cpp