Code::Blocks: NbStyleVC71 Class Reference
NbStyleVC71 Class Reference
#include <notebookstyles.h>
Public Member Functions
NbStyleVC71 ()
wxAuiTabArt * Clone ()
void DrawTab (wxDC &dc, wxWindow *wnd, const wxAuiNotebookPage &page, const wxRect &in_rect, int close_button_state, wxRect *out_tab_rect, wxRect *out_button_rect, int *x_extent)
int GetBestTabCtrlSize (wxWindow *wnd, const wxAuiNotebookPageArray &pages, const wxSize &required_bmp_size)
Public Member Functions inherited from wxAuiDefaultTabArt
wxAuiDefaultTabArt ()
virtual ~wxAuiDefaultTabArt ()
void SetFlags (unsigned int flags)
void SetSizingInfo (const wxSize &tabCtrlSize, size_t tabCount)
void SetNormalFont (const wxFont &font)
void SetSelectedFont (const wxFont &font)
void SetMeasuringFont (const wxFont &font)
void SetColour (const wxColour &colour)
void SetActiveColour (const wxColour &colour)
void DrawBackground (wxDC &dc, wxWindow *wnd, const wxRect &rect)
void DrawButton (wxDC &dc, wxWindow *wnd, const wxRect &inRect, int bitmapId, int buttonState, int orientation, wxRect *outRect)
int GetIndentSize ()
wxSize GetTabSize (wxDC &dc, wxWindow *wnd, const wxString &caption, const wxBitmap &bitmap, bool active, int closeButtonState, int *xExtent)
int ShowDropDown (wxWindow *wnd, const wxAuiNotebookPageArray &items, int activeIdx)
wxAuiTabArt ()
Additional Inherited Members
Protected Attributes inherited from wxAuiDefaultTabArt
wxFont m_normalFont
wxFont m_selectedFont
wxFont m_measuringFont
wxColour m_baseColour
wxPen m_baseColourPen
wxPen m_borderPen
wxBrush m_baseColourBrush
wxColour m_activeColour
wxBitmap m_activeCloseBmp
wxBitmap m_disabledCloseBmp
wxBitmap m_activeLeftBmp
wxBitmap m_disabledLeftBmp
wxBitmap m_activeRightBmp
wxBitmap m_disabledRightBmp
wxBitmap m_activeWindowListBmp
wxBitmap m_disabledWindowListBmp
int m_fixedTabWidth
int m_tabCtrlHeight
unsigned int m_flags
Detailed Description
Definition at line 27 of file notebookstyles.h.
Constructor & Destructor Documentation
NbStyleVC71()
NbStyleVC71::NbStyleVC71 ()
Definition at line 37 of file notebookstyles.cpp.
Referenced by Clone().
Member Function Documentation
Clone()
wxAuiTabArt * NbStyleVC71::Clone () virtual
Reimplemented from wxAuiDefaultTabArt.
Definition at line 41 of file notebookstyles.cpp.
References wxAuiDefaultTabArt::m_measuringFont, wxAuiDefaultTabArt::m_normalFont, wxAuiDefaultTabArt::m_selectedFont, NbStyleVC71(), wxAuiDefaultTabArt::SetMeasuringFont(), wxAuiDefaultTabArt::SetNormalFont(), and wxAuiDefaultTabArt::SetSelectedFont().
DrawTab()
void NbStyleVC71::DrawTab (wxDC & dc, wxWindow * wnd, const wxAuiNotebookPage & page, const wxRect & in_rect, int close_button_state, wxRect * out_tab_rect, wxRect * out_button_rect, int * x_extent) virtual
Reimplemented from wxAuiDefaultTabArt.
Definition at line 58 of file notebookstyles.cpp.
References wxString::empty(), wxSystemSettings::GetColour(), wxBitmap::GetHeight(), wxAuiDefaultTabArt::GetTabSize(), wxBitmap::GetWidth(), wxRect::height, wxAuiDefaultTabArt::m_activeCloseBmp, wxAuiDefaultTabArt::m_disabledCloseBmp, wxAuiDefaultTabArt::m_flags, wxAuiDefaultTabArt::m_normalFont, wxAuiDefaultTabArt::m_selectedFont, wxAuiDefaultTabArt::m_tabCtrlHeight, wxRect::width, wxAUI_BUTTON_STATE_HIDDEN, wxAUI_BUTTON_STATE_HOVER, wxAUI_BUTTON_STATE_PRESSED, wxSYS_COLOUR_3DDKSHADOW, wxSYS_COLOUR_3DFACE, wxSYS_COLOUR_3DHIGHLIGHT, wxSYS_COLOUR_3DSHADOW, wxSYS_COLOUR_BTNTEXT, wxT, wxTRANSPARENT_BRUSH, wxRect::x, wxPoint::y, and wxRect::y.
GetBestTabCtrlSize()
int NbStyleVC71::GetBestTabCtrlSize (wxWindow * wnd, const wxAuiNotebookPageArray & pages, const wxSize & required_bmp_size) virtual
Reimplemented from wxAuiDefaultTabArt.
Definition at line 223 of file notebookstyles.cpp.
References wxAuiDefaultTabArt::GetTabSize(), wxAuiDefaultTabArt::m_measuringFont, wxAUI_BUTTON_STATE_HIDDEN, wxNullBitmap, and wxT.
The documentation for this class was generated from the following files:
notebookstyles.h
notebookstyles.cpp