Code::Blocks: WatchRawDialogAdapter Class Reference
WatchRawDialogAdapter Class Reference
Public Member Functions
WatchRawDialogAdapter ()
bool DoShowDialog (wxPropertyGrid *WXUNUSED(propGrid), wxPGProperty *property) override
Detailed Description
Definition at line 183 of file watchesdlg.cpp.
Constructor & Destructor Documentation
WatchRawDialogAdapter()
WatchRawDialogAdapter::WatchRawDialogAdapter () inline
Definition at line 187 of file watchesdlg.cpp.
References IMPLEMENT_DYNAMIC_CLASS().
Member Function Documentation
DoShowDialog()
bool WatchRawDialogAdapter::DoShowDialog (wxPropertyGrid * WXUNUSEDpropGrid, wxPGProperty * property) override
Definition at line 335 of file watchesdlg.cpp.
References WatchRawDialog::Create(), and WatchesProperty::GetWatch().
The documentation for this class was generated from the following file:
watchesdlg.cpp