Code::Blocks: wxMultiColumnListCtrl Class Reference
wxMultiColumnListCtrl Class Reference
#include <switcherdlg.h>
Public Member Functions
wxMultiColumnListCtrl (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
wxMultiColumnListCtrl ()
bool Create (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void SetItems (const wxSwitcherItems &items)
const wxSwitcherItems & GetItems () const
wxSwitcherItems & GetItems ()
void SetExtraNavigationKey (int keyCode)
int GetExtraNavigationKey () const
void SetModifierKey (int modifierKey)
int GetModifierKey () const
void OnPaint (wxPaintEvent &event)
void OnMouseEvent (wxMouseEvent &event)
void OnChar (wxKeyEvent &event)
void OnKey (wxKeyEvent &event)
void OnEraseBackground (wxEraseEvent &event)
virtual wxSize DoGetBestSize () const
void CalculateLayout ()
void CalculateLayout (wxDC &dc)
void InvalidateLayout ()
void Init ()
void GenerateSelectionEvent ()
void AdvanceToNextSelectableItem (int direction)
void SendCloseEvent ()
Protected Attributes
wxPoint m_ptMouse
Mouse point initialized on Init function.
wxSwitcherItems m_items
wxSize m_overallSize
int m_extraNavigationKey
int m_modifierKey
Detailed Description
wxMultiColumnListCtrl A control for displaying several columns (not scrollable)
Definition at line 204 of file switcherdlg.h.
Constructor & Destructor Documentation
wxMultiColumnListCtrl() [1/2]
wxMultiColumnListCtrl::wxMultiColumnListCtrl (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
Definition at line 439 of file switcherdlg.cpp.
References wxSwitcherItem::Init().
wxMultiColumnListCtrl() [2/2]
wxMultiColumnListCtrl::wxMultiColumnListCtrl () inline
Definition at line 209 of file switcherdlg.h.
References wxSwitcherItem::Init(), wxDefaultPosition, and wxDefaultSize.
Member Function Documentation
AdvanceToNextSelectableItem()
void wxMultiColumnListCtrl::AdvanceToNextSelectableItem (int direction)
Definition at line 718 of file switcherdlg.cpp.
References wxSwitcherItem::GetIsGroup().
CalculateLayout() [1/2]
void wxMultiColumnListCtrl::CalculateLayout ()
Definition at line 756 of file switcherdlg.cpp.
CalculateLayout() [2/2]
void wxMultiColumnListCtrl::CalculateLayout (wxDC & dc)
Definition at line 762 of file switcherdlg.cpp.
Create()
bool wxMultiColumnListCtrl::Create (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
Definition at line 446 of file switcherdlg.cpp.
DoGetBestSize()
wxSize wxMultiColumnListCtrl::DoGetBestSize () const virtual
Definition at line 456 of file switcherdlg.cpp.
GenerateSelectionEvent()
void wxMultiColumnListCtrl::GenerateSelectionEvent ()
Definition at line 747 of file switcherdlg.cpp.
References wxSwitcherItem::GetId().
GetExtraNavigationKey()
int wxMultiColumnListCtrl::GetExtraNavigationKey () const inline
Definition at line 222 of file switcherdlg.h.
GetItems() [1/2]
const wxSwitcherItems& wxMultiColumnListCtrl::GetItems () const inline
Definition at line 216 of file switcherdlg.h.
GetItems() [2/2]
wxSwitcherItems& wxMultiColumnListCtrl::GetItems () inline
Definition at line 217 of file switcherdlg.h.
GetModifierKey()
int wxMultiColumnListCtrl::GetModifierKey () const inline
Definition at line 227 of file switcherdlg.h.
Init()
void wxMultiColumnListCtrl::Init ()
Definition at line 835 of file switcherdlg.cpp.
References wxSwitcherDialog::OnActivate(), wxSwitcherDialog::OnCloseWindow(), wxSwitcherDialog::OnPaint(), wxSwitcherDialog::OnSelectItem(), wxGetMousePosition(), wxID_ANY, and WXK_CONTROL.
InvalidateLayout()
void wxMultiColumnListCtrl::InvalidateLayout () inline
Definition at line 244 of file switcherdlg.h.
References wxSwitcherItem::Init().
OnChar()
void wxMultiColumnListCtrl::OnChar (wxKeyEvent & event)
Definition at line 564 of file switcherdlg.cpp.
Referenced by wxSwitcherItems::HitTest().
OnEraseBackground()
void wxMultiColumnListCtrl::OnEraseBackground (wxEraseEvent & event)
Definition at line 478 of file switcherdlg.cpp.
Referenced by wxSwitcherItems::HitTest().
OnKey()
void wxMultiColumnListCtrl::OnKey (wxKeyEvent & event)
Definition at line 568 of file switcherdlg.cpp.
References wxSwitcherItem::GetColPos(), wxKeyEvent::GetKeyCode(), wxSwitcherItem::GetRowPos(), wxKeyboardState::ShiftDown(), wxEVT_KEY_UP, WXK_DOWN, WXK_END, WXK_ESCAPE, WXK_HOME, WXK_LEFT, WXK_NUMPAD_DOWN, WXK_NUMPAD_END, WXK_NUMPAD_ENTER, WXK_NUMPAD_HOME, WXK_NUMPAD_LEFT, WXK_NUMPAD_RIGHT, WXK_NUMPAD_UP, WXK_RETURN, WXK_RIGHT, WXK_TAB, and WXK_UP.
Referenced by wxSwitcherItems::HitTest().
OnMouseEvent()
void wxMultiColumnListCtrl::OnMouseEvent (wxMouseEvent & event)
Definition at line 500 of file switcherdlg.cpp.
References wxMouseEvent::GetButton(), wxMouseEvent::GetPosition(), wxMouseEvent::LeftDown(), wxEVT_MOUSEWHEEL, wxMOUSE_BTN_NONE, wxNOT_FOUND, wxPoint::x, and wxPoint::y.
Referenced by wxSwitcherItems::HitTest().
OnPaint()
void wxMultiColumnListCtrl::OnPaint (wxPaintEvent & event)
Definition at line 483 of file switcherdlg.cpp.
Referenced by wxSwitcherItems::HitTest().
SendCloseEvent()
void wxMultiColumnListCtrl::SendCloseEvent ()
Definition at line 461 of file switcherdlg.cpp.
References wxCloseEvent::SetCanVeto(), and wxEVT_CLOSE_WINDOW.
SetExtraNavigationKey()
void wxMultiColumnListCtrl::SetExtraNavigationKey (int keyCode) inline
Definition at line 221 of file switcherdlg.h.
SetItems()
void wxMultiColumnListCtrl::SetItems (const wxSwitcherItems & items) inline
Definition at line 215 of file switcherdlg.h.
SetModifierKey()
void wxMultiColumnListCtrl::SetModifierKey (int modifierKey) inline
Definition at line 226 of file switcherdlg.h.
Member Data Documentation
m_extraNavigationKey
int wxMultiColumnListCtrl::m_extraNavigationKey protected
Definition at line 263 of file switcherdlg.h.
m_items
wxSwitcherItems wxMultiColumnListCtrl::m_items protected
Definition at line 261 of file switcherdlg.h.
m_modifierKey
int wxMultiColumnListCtrl::m_modifierKey protected
Definition at line 264 of file switcherdlg.h.
m_overallSize
wxSize wxMultiColumnListCtrl::m_overallSize protected
Definition at line 262 of file switcherdlg.h.
m_ptMouse
wxPoint wxMultiColumnListCtrl::m_ptMouse protected
Mouse point initialized on Init function.
Used because if the mouse is over the dialog when it's opened, it automatically select the item under the mouse pointer. Recording the mouse pointer position when the dialog is opened prevent this : select the item only if the user move the mouse.
Definition at line 260 of file switcherdlg.h.
The documentation for this class was generated from the following files:
switcherdlg.h
switcherdlg.cpp