Code::Blocks: EncodingDetector Class Reference
EncodingDetector Class Reference
Try to detect the encoding of a file on disk.
#include <encodingdetector.h>
Public Member Functions
EncodingDetector (const wxString &filename, bool useLog=true)
EncodingDetector (LoaderBase *fileLdr, bool useLog=true)
EncodingDetector (const wxByte *buffer, size_t size, bool useLog=true)
EncodingDetector (const EncodingDetector &rhs, bool useLog=true)
~EncodingDetector ()
bool IsOK () const
bool UsesBOM () const
int GetBOMSizeInBytes () const
wxFontEncoding GetFontEncoding () const
wxString GetWxStr () const
Protected Member Functions
bool DetectEncoding (const wxString &filename, bool convert_to_wxstring=true)
bool DetectEncoding (const wxByte *buffer, size_t size, bool convert_to_wxstring=true)
bool DetectEncodingEx (const wxByte *buffer, size_t len)
void Report (const char *aCharset)
Protected Attributes
bool m_IsOK
bool m_UseBOM
bool m_UseLog
int m_BOMSizeInBytes
wxFontEncoding m_Encoding
Private Member Functions
bool ConvertToWxString (const wxByte *buffer, size_t size)
Private Attributes
wxString m_MozillaResult
wxString m_ConvStr
Detailed Description
Try to detect the encoding of a file on disk.
Definition at line 17 of file encodingdetector.h.
Constructor & Destructor Documentation
EncodingDetector() [1/4]
EncodingDetector::EncodingDetector (const wxString & filename, bool useLog = true)
Definition at line 35 of file encodingdetector.cpp.
References DetectEncoding(), wxLocale::GetSystemEncoding(), m_Encoding, m_IsOK, and wxEmptyString.
EncodingDetector() [2/4]
EncodingDetector::EncodingDetector (LoaderBase * fileLdr, bool useLog = true)
Definition at line 47 of file encodingdetector.cpp.
References DetectEncoding(), LoaderBase::GetData(), LoaderBase::GetLength(), wxLocale::GetSystemEncoding(), m_Encoding, m_IsOK, and wxEmptyString.
EncodingDetector() [3/4]
EncodingDetector::EncodingDetector (const wxByte * buffer, size_t size, bool useLog = true)
Definition at line 59 of file encodingdetector.cpp.
References DetectEncoding(), wxLocale::GetSystemEncoding(), m_Encoding, m_IsOK, and wxEmptyString.
EncodingDetector() [4/4]
EncodingDetector::EncodingDetector (const EncodingDetector & rhs, bool useLog = true)
~EncodingDetector()
EncodingDetector::~EncodingDetector ()
Definition at line 71 of file encodingdetector.cpp.
Member Function Documentation
ConvertToWxString()
bool EncodingDetector::ConvertToWxString (const wxByte * buffer, size_t size) private
Definition at line 431 of file encodingdetector.cpp.
References _T, wxEncodingConverter::Convert(), LogManager::DebugLog(), wxFontMapper::Get(), Manager::Get(), Manager::GetConfigManager(), Manager::GetLogManager(), wxLocale::GetSystemEncoding(), wxEncodingConverter::Init(), wxCSConv::IsOk(), m_BOMSizeInBytes, m_ConvStr, m_Encoding, m_UseLog, makeStringNoNull(), wxString::Printf(), ConfigManager::ReadBool(), wxFONTENCODING_ISO8859_1, wxFONTENCODING_UNICODE, wxFONTENCODING_UTF16BE, wxFONTENCODING_UTF16LE, wxFONTENCODING_UTF32BE, wxFONTENCODING_UTF32LE, wxFONTENCODING_UTF7, and wxFONTENCODING_UTF8.
Referenced by DetectEncoding().
DetectEncoding() [1/2]
bool EncodingDetector::DetectEncoding (const wxString & filename, bool convert_to_wxstring = true) protected
Returns
True if succeeded, false if not (e.g. file didn't exist).
Definition at line 113 of file encodingdetector.cpp.
References wxFile::Close(), wxFile::IsOpened(), wxFile::Length(), and wxFile::Read().
Referenced by EncodingDetector().
DetectEncoding() [2/2]
bool EncodingDetector::DetectEncoding (const wxByte * buffer, size_t size, bool convert_to_wxstring = true) protected
Definition at line 147 of file encodingdetector.cpp.
References _T, wxFontMapper::CharsetToEncoding(), ConvertToWxString(), LogManager::DebugLog(), DetectEncodingEx(), F(), wxFontMapper::Get(), Manager::Get(), Manager::GetConfigManager(), wxFontMapper::GetEncodingFromName(), Manager::GetLogManager(), wxLocale::GetSystemEncodingName(), wxString::IsEmpty(), m_BOMSizeInBytes, m_Encoding, m_MozillaResult, m_UseBOM, m_UseLog, wxString::Printf(), ConfigManager::Read(), ConfigManager::ReadInt(), wxEmptyString, and wxFONTENCODING_DEFAULT.
DetectEncodingEx()
bool EncodingDetector::DetectEncodingEx (const wxByte * buffer, size_t len) protected
Definition at line 256 of file encodingdetector.cpp.
References m_BOMSizeInBytes, m_Encoding, m_UseBOM, wxFONTENCODING_DEFAULT, wxFONTENCODING_UTF16BE, wxFONTENCODING_UTF16LE, wxFONTENCODING_UTF32BE, wxFONTENCODING_UTF32LE, wxFONTENCODING_UTF7, wxFONTENCODING_UTF8, wxUINT16_SWAP_ON_BE, wxUINT16_SWAP_ON_LE, wxUINT32_SWAP_ON_BE, and wxUINT32_SWAP_ON_LE.
Referenced by DetectEncoding().
GetBOMSizeInBytes()
int EncodingDetector::GetBOMSizeInBytes () const
Returns
The BOM size in bytes. Returns zero if no BOM.
Definition at line 98 of file encodingdetector.cpp.
References m_BOMSizeInBytes.
Referenced by cbEditorInternalData::cbEditorInternalData().
GetFontEncoding()
wxFontEncoding EncodingDetector::GetFontEncoding () const
Returns
The detected encoding. Currently ISO8859-1 is returned if no BOM is present.
Definition at line 103 of file encodingdetector.cpp.
References m_Encoding.
Referenced by cbEditorInternalData::cbEditorInternalData().
GetWxStr()
wxString EncodingDetector::GetWxStr () const
Definition at line 108 of file encodingdetector.cpp.
References m_ConvStr.
Referenced by FindReplace::FindInFiles(), CodeRefactoring::SearchInFiles(), and CodeRefactoring::VerifyResult().
IsOK()
bool EncodingDetector::IsOK () const
Returns
True if file was read, false if not.
Definition at line 88 of file encodingdetector.cpp.
References m_IsOK.
Referenced by cbEditorInternalData::cbEditorInternalData(), FindReplace::FindInFiles(), CodeRefactoring::SearchInFiles(), and CodeRefactoring::VerifyResult().
Report()
void EncodingDetector::Report (const char * aCharset) protected
Definition at line 75 of file encodingdetector.cpp.
References _T, cbC2U(), wxString::Contains(), LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), m_MozillaResult, m_UseLog, wxString::wx_str(), wxEmptyString, and wxT.
UsesBOM()
bool EncodingDetector::UsesBOM () const
Returns
True if the file contains a BOM (Byte Order Mark), false if not.
Definition at line 93 of file encodingdetector.cpp.
References m_UseBOM.
Referenced by cbEditorInternalData::cbEditorInternalData().
Member Data Documentation
m_BOMSizeInBytes
int EncodingDetector::m_BOMSizeInBytes protected
Definition at line 45 of file encodingdetector.h.
Referenced by ConvertToWxString(), DetectEncoding(), DetectEncodingEx(), and GetBOMSizeInBytes().
m_ConvStr
wxString EncodingDetector::m_ConvStr private
Definition at line 51 of file encodingdetector.h.
Referenced by ConvertToWxString(), and GetWxStr().
m_Encoding
wxFontEncoding EncodingDetector::m_Encoding protected
Definition at line 46 of file encodingdetector.h.
Referenced by ConvertToWxString(), DetectEncoding(), DetectEncodingEx(), EncodingDetector(), and GetFontEncoding().
m_IsOK
bool EncodingDetector::m_IsOK protected
Definition at line 42 of file encodingdetector.h.
Referenced by EncodingDetector(), and IsOK().
m_MozillaResult
wxString EncodingDetector::m_MozillaResult private
Definition at line 50 of file encodingdetector.h.
Referenced by DetectEncoding(), and Report().
m_UseBOM
bool EncodingDetector::m_UseBOM protected
Definition at line 43 of file encodingdetector.h.
Referenced by DetectEncoding(), DetectEncodingEx(), and UsesBOM().
m_UseLog
bool EncodingDetector::m_UseLog protected
Definition at line 44 of file encodingdetector.h.
Referenced by ConvertToWxString(), DetectEncoding(), and Report().
The documentation for this class was generated from the following files:
encodingdetector.h
encodingdetector.cpp