Code::Blocks: BacktraceDlg Class Reference
BacktraceDlg Class Reference
#include <backtracedlg.h>
Public Member Functions
BacktraceDlg (wxWindow *parent)
wxWindow * GetWindow ()
void Reload ()
void EnableWindow (bool enable)
Public Member Functions inherited from cbBacktraceDlg
virtual ~cbBacktraceDlg ()
Private Member Functions
void OnListRightClick (wxListEvent &event)
void OnDoubleClick (wxListEvent &event)
void OnJump (wxCommandEvent &event)
void OnSwitchFrame (wxCommandEvent &event)
void OnSave (wxCommandEvent &event)
void OnCopyToClipboard (wxCommandEvent &event)
void OnSettingJumpDefault (wxCommandEvent &event)
void OnSettingSwitchDefault (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
bool IsSwitchFrameEnabled () const
DECLARE_EVENT_TABLE ()
Private Attributes
wxListCtrl * m_list
Detailed Description
Definition at line 19 of file backtracedlg.h.
Constructor & Destructor Documentation
BacktraceDlg()
BacktraceDlg::BacktraceDlg (wxWindow * parent)
Definition at line 55 of file backtracedlg.cpp.
References _(), wxBoxSizer::Add(), Manager::Get(), Manager::GetColourManager(), ColourManager::RegisterColour(), wxALL, wxDefaultPosition, wxDefaultSize, wxEXPAND, wxLC_HRULES, wxLC_REPORT, wxLC_SINGLE_SEL, wxLC_VRULES, wxLIST_FORMAT_LEFT, wxLIST_FORMAT_RIGHT, wxRED, wxT, wxVERTICAL, and wxWHITE.
Member Function Documentation
DECLARE_EVENT_TABLE()
BacktraceDlg::DECLARE_EVENT_TABLE () private
Referenced by GetWindow().
EnableWindow()
void BacktraceDlg::EnableWindow (bool enable) virtual
Implements cbBacktraceDlg.
Definition at line 121 of file backtracedlg.cpp.
References m_list.
Referenced by GetWindow().
GetWindow()
wxWindow* BacktraceDlg::GetWindow () inline virtual
Implements cbBacktraceDlg.
Definition at line 24 of file backtracedlg.h.
References DECLARE_EVENT_TABLE(), EnableWindow(), IsSwitchFrameEnabled(), OnCopyToClipboard(), OnDoubleClick(), OnJump(), OnListRightClick(), OnSave(), OnSettingJumpDefault(), OnSettingSwitchDefault(), OnSwitchFrame(), OnUpdateUI(), and Reload().
IsSwitchFrameEnabled()
bool BacktraceDlg::IsSwitchFrameEnabled () const private
Definition at line 290 of file backtracedlg.cpp.
References Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), cbDebuggerPlugin::IsRunning(), and cbDebuggerPlugin::IsStopped().
Referenced by GetWindow(), OnDoubleClick(), OnSwitchFrame(), and OnUpdateUI().
OnCopyToClipboard()
void BacktraceDlg::OnCopyToClipboard (wxCommandEvent & event) private
Definition at line 242 of file backtracedlg.cpp.
References _T, wxListCtrl::GetItem(), wxListCtrl::GetItemCount(), wxListCtrl::GetItemText(), m_list, wxLIST_MASK_TEXT, and wxTheClipboard.
Referenced by GetWindow().
OnDoubleClick()
void BacktraceDlg::OnDoubleClick (wxListEvent & event) private
Definition at line 198 of file backtracedlg.cpp.
References cbDebuggerCommonConfig::GetFlag(), IsSwitchFrameEnabled(), cbDebuggerCommonConfig::JumpOnDoubleClick, OnJump(), and OnSwitchFrame().
Referenced by GetWindow().
OnJump()
void BacktraceDlg::OnJump (wxCommandEvent & event) private
Definition at line 148 of file backtracedlg.cpp.
References _T, Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), wxListCtrl::GetItem(), wxListCtrl::GetNextItem(), wxListCtrl::GetSelectedItemCount(), wxString::IsEmpty(), m_list, cbDebuggerPlugin::SyncEditor(), wxString::ToLong(), wxLIST_MASK_TEXT, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by GetWindow(), and OnDoubleClick().
OnListRightClick()
void BacktraceDlg::OnListRightClick (wxListEvent & event) private
Definition at line 128 of file backtracedlg.cpp.
References _(), wxMenu::Append(), wxMenu::AppendRadioItem(), wxMenu::AppendSeparator(), wxMenu::Check(), cbDebuggerCommonConfig::GetFlag(), cbDebuggerCommonConfig::JumpOnDoubleClick, and m_list.
Referenced by GetWindow().
OnSave()
void BacktraceDlg::OnSave (wxCommandEvent & event) private
Definition at line 208 of file backtracedlg.cpp.
References _(), _T, cbMessageBox(), FileFilters::GetFilterAll(), wxListCtrl::GetItem(), wxListCtrl::GetItemCount(), wxListCtrl::GetItemText(), wxFileDialog::GetPath(), m_list, PlaceWindow(), wxFileDialog::ShowModal(), wxEmptyString, wxFD_OVERWRITE_PROMPT, wxFD_SAVE, wxICON_INFORMATION, wxID_OK, and wxLIST_MASK_TEXT.
Referenced by GetWindow().
OnSettingJumpDefault()
void BacktraceDlg::OnSettingJumpDefault (wxCommandEvent & event) private
Definition at line 273 of file backtracedlg.cpp.
References cbDebuggerCommonConfig::JumpOnDoubleClick, and cbDebuggerCommonConfig::SetFlag().
Referenced by GetWindow().
OnSettingSwitchDefault()
void BacktraceDlg::OnSettingSwitchDefault (wxCommandEvent & event) private
Definition at line 279 of file backtracedlg.cpp.
References cbDebuggerCommonConfig::JumpOnDoubleClick, and cbDebuggerCommonConfig::SetFlag().
Referenced by GetWindow().
OnSwitchFrame()
void BacktraceDlg::OnSwitchFrame (wxCommandEvent & event) private
Definition at line 175 of file backtracedlg.cpp.
References _(), cbMessageBox(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), wxListCtrl::GetItemText(), wxListCtrl::GetNextItem(), wxListCtrl::GetSelectedItemCount(), IsSwitchFrameEnabled(), m_list, cbDebuggerPlugin::SwitchToFrame(), wxString::ToLong(), wxICON_ERROR, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by GetWindow(), and OnDoubleClick().
OnUpdateUI()
void BacktraceDlg::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 285 of file backtracedlg.cpp.
References IsSwitchFrameEnabled().
Referenced by GetWindow().
Reload()
void BacktraceDlg::Reload () virtual
Implements cbBacktraceDlg.
Definition at line 77 of file backtracedlg.cpp.
References wxListCtrl::DeleteAllItems(), wxListCtrl::EnsureVisible(), Manager::Get(), DebuggerManager::GetActiveDebugger(), cbDebuggerPlugin::GetActiveStackFrame(), ColourManager::GetColour(), Manager::GetColourManager(), Manager::GetDebuggerManager(), wxListCtrl::GetItemCount(), cbDebuggerPlugin::GetStackFrame(), cbDebuggerPlugin::GetStackFrameCount(), wxListCtrl::InsertItem(), m_list, wxString::Printf(), wxListCtrl::SetColumnWidth(), wxListCtrl::SetItem(), wxListCtrl::SetItemBackgroundColour(), wxListCtrl::SetItemTextColour(), wxLIST_AUTOSIZE, and wxT.
Referenced by GetWindow().
Member Data Documentation
m_list
wxListCtrl* BacktraceDlg::m_list private
Definition at line 44 of file backtracedlg.h.
Referenced by EnableWindow(), OnCopyToClipboard(), OnJump(), OnListRightClick(), OnSave(), OnSwitchFrame(), and Reload().
The documentation for this class was generated from the following files:
backtracedlg.h
backtracedlg.cpp