Code::Blocks: CdbCmd_Backtrace Class Reference
CdbCmd_Backtrace Class Reference
Command to run a backtrace.
#include <cdb_commands.h>
Public Member Functions
CdbCmd_Backtrace (DebuggerDriver *driver, bool switchToFirst)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
bool m_SwitchToFirst
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to run a backtrace.
Definition at line 400 of file cdb_commands.h.
Constructor & Destructor Documentation
CdbCmd_Backtrace()
CdbCmd_Backtrace::CdbCmd_Backtrace (DebuggerDriver * driver, bool switchToFirst) inline
Parameters
dlg The backtrace dialog.
Definition at line 404 of file cdb_commands.h.
References _T, and DebuggerCmd::m_Cmd.
Member Function Documentation
ParseOutput()
void CdbCmd_Backtrace::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 410 of file cdb_commands.h.
References _T, Cursor::address, cbDebuggerStringToAddress(), Cursor::changed, Cursor::file, Manager::Get(), cbStackFrame::GetAddressAsString(), GetArrayFromString(), DebuggerManager::GetBacktraceDialog(), wxArrayString::GetCount(), Manager::GetDebuggerManager(), cbStackFrame::GetFilename(), cbStackFrame::GetLine(), wxRegEx::GetMatch(), DebuggerDriver::GetStackFrames(), cbStackFrame::IsValid(), Cursor::line, DebuggerCmd::m_pDriver, cbStackFrame::MakeValid(), wxRegEx::Matches(), DebuggerDriver::NotifyCursorChanged(), reBT1(), reBT2(), cbBacktraceDlg::Reload(), cbStackFrame::SetAddress(), DebuggerDriver::SetCursor(), cbStackFrame::SetFile(), cbStackFrame::SetNumber(), cbStackFrame::SetSymbol(), and wxString::ToLong().
Member Data Documentation
m_SwitchToFirst
bool CdbCmd_Backtrace::m_SwitchToFirst private
Definition at line 474 of file cdb_commands.h.
The documentation for this class was generated from the following file:
cdb_commands.h