Code::Blocks: DebuggerManager Class Reference
DebuggerManager Class Reference
#include <debuggermanager.h>
Classes
struct PluginData
Public Types
typedef std::vector< cbDebuggerConfiguration * > ConfigurationVector
typedef std::map< cbDebuggerPlugin *, PluginData > RegisteredPlugins
Public Member Functions
bool RegisterDebugger (cbDebuggerPlugin *plugin)
Called to register a debugger plugin.
bool UnregisterDebugger (cbDebuggerPlugin *plugin)
Called to unregister a debugger plugin.
ConfigManagerWrapper NewConfig (cbDebuggerPlugin *plugin, const wxString &name)
void RebuildAllConfigs ()
wxMenu * GetMenu ()
bool HasMenu () const
void BuildContextMenu (wxMenu &menu, const wxString &word_at_caret, bool is_running)
TextCtrlLogger * GetLogger (int &index)
TextCtrlLogger * GetLogger ()
void HideLogger ()
void SetInterfaceFactory (cbDebugInterfaceFactory *factory)
cbDebugInterfaceFactory * GetInterfaceFactory ()
void SetMenuHandler (cbDebuggerMenuHandler *handler)
cbDebuggerMenuHandler * GetMenuHandler ()
cbBacktraceDlg * GetBacktraceDialog ()
cbBreakpointsDlg * GetBreakpointDialog ()
Returns a pointer to the breakpoints dialog.
cbCPURegistersDlg * GetCPURegistersDialog ()
Returns a pointer to the CPU registers dialog.
cbDisassemblyDlg * GetDisassemblyDialog ()
Returns a pointer to the disassembly dialog.
cbExamineMemoryDlg * GetExamineMemoryDialog ()
Returns a pointer to the memory dialog.
cbThreadsDlg * GetThreadsDialog ()
Returns a pointer to the threads dialog.
cbWatchesDlg * GetWatchesDialog ()
Returns a pointer to the watches dialog.
bool ShowBacktraceDialog ()
bool UpdateBacktrace ()
bool UpdateCPURegisters ()
bool UpdateDisassembly ()
bool UpdateExamineMemory ()
bool UpdateThreads ()
cbDebuggerPlugin * GetDebuggerHavingWatch (cb::shared_ptr< cbWatch > watch)
bool ShowValueTooltip (const cb::shared_ptr< cbWatch > &watch, const wxRect &rect)
RegisteredPlugins const & GetAllDebuggers () const
RegisteredPlugins & GetAllDebuggers ()
cbDebuggerPlugin * GetActiveDebugger ()
void SetActiveDebugger (cbDebuggerPlugin *activeDebugger, ConfigurationVector::const_iterator config)
void SetTargetsDefaultAsActiveDebugger ()
bool IsActiveDebuggerTargetsDefault () const
bool IsDisassemblyMixedMode ()
void SetDisassemblyMixedMode (bool mixed)
Private Member Functions
DebuggerManager ()
~DebuggerManager ()
void ProcessSettings (RegisteredPlugins::iterator it)
void FindTargetsDebugger ()
void RefreshUI ()
void CreateWindows ()
void DestoryWindows ()
void OnProjectActivated (CodeBlocksEvent &event)
void OnTargetSelected (CodeBlocksEvent &event)
void OnSettingsChanged (CodeBlocksEvent &event)
void OnPluginLoadingComplete (CodeBlocksEvent &event)
Private Attributes
cbDebugInterfaceFactory * m_interfaceFactory
RegisteredPlugins m_registered
cbDebuggerPlugin * m_activeDebugger
cbDebuggerMenuHandler * m_menuHandler
cbBacktraceDlg * m_backtraceDialog
cbBreakpointsDlg * m_breakPointsDialog
cbCPURegistersDlg * m_cpuRegistersDialog
cbDisassemblyDlg * m_disassemblyDialog
cbExamineMemoryDlg * m_examineMemoryDialog
cbThreadsDlg * m_threadsDialog
cbWatchesDlg * m_watchesDialog
TextCtrlLogger * m_logger
int m_loggerIndex
bool m_isDisassemblyMixedMode
bool m_useTargetsDefault
Friends
class Mgr< DebuggerManager >
class Manager
Additional Inherited Members
Static Public Member Functions inherited from Mgr< DebuggerManager >
static bool Valid ()
static DebuggerManager * Get ()
static void Free ()
Protected Member Functions inherited from Mgr< DebuggerManager >
Mgr ()
virtual ~Mgr ()
Detailed Description
Definition at line 228 of file debuggermanager.h.
Member Typedef Documentation
ConfigurationVector
typedef std::vector<cbDebuggerConfiguration*> DebuggerManager::ConfigurationVector
Definition at line 237 of file debuggermanager.h.
RegisteredPlugins
typedef std::map<cbDebuggerPlugin*, PluginData> DebuggerManager::RegisteredPlugins
Definition at line 259 of file debuggermanager.h.
Constructor & Destructor Documentation
DebuggerManager()
DebuggerManager::DebuggerManager () private
Definition at line 695 of file debuggermanager.cpp.
References cbEVT_BUILDTARGET_SELECTED, cbEVT_PLUGIN_LOADING_COMPLETE, cbEVT_PROJECT_ACTIVATE, cbEVT_PROJECT_OPEN, cbEVT_SETTINGS_CHANGED, Manager::Get(), m_useTargetsDefault, OnPluginLoadingComplete(), OnProjectActivated(), OnSettingsChanged(), OnTargetSelected(), ReadActiveDebuggerConfig(), and Manager::RegisterEventSink().
~DebuggerManager()
DebuggerManager::~DebuggerManager () private
Definition at line 726 of file debuggermanager.cpp.
References Manager::Get(), m_interfaceFactory, m_registered, and Manager::RemoveAllEventSinksFor().
Member Function Documentation
BuildContextMenu()
void DebuggerManager::BuildContextMenu (wxMenu & menu, const wxString & word_at_caret, bool is_running)
Definition at line 935 of file debuggermanager.cpp.
References cbDebuggerMenuHandler::BuildContextMenu(), and m_menuHandler.
Referenced by cbDebuggerPlugin::BuildModuleMenu().
CreateWindows()
void DebuggerManager::CreateWindows () private
Definition at line 992 of file debuggermanager.cpp.
References cbDebugInterfaceFactory::CreateBacktrace(), cbDebugInterfaceFactory::CreateBreapoints(), cbDebugInterfaceFactory::CreateCPURegisters(), cbDebugInterfaceFactory::CreateDisassembly(), cbDebugInterfaceFactory::CreateMemory(), cbDebugInterfaceFactory::CreateThreads(), cbDebugInterfaceFactory::CreateWatches(), m_backtraceDialog, m_breakPointsDialog, m_cpuRegistersDialog, m_disassemblyDialog, m_examineMemoryDialog, m_interfaceFactory, m_threadsDialog, and m_watchesDialog.
Referenced by RegisterDebugger(), and SetInterfaceFactory().
DestoryWindows()
void DebuggerManager::DestoryWindows () private
Definition at line 1010 of file debuggermanager.cpp.
References cbDebugInterfaceFactory::DeleteBacktrace(), cbDebugInterfaceFactory::DeleteBreakpoints(), cbDebugInterfaceFactory::DeleteCPURegisters(), cbDebugInterfaceFactory::DeleteDisassembly(), cbDebugInterfaceFactory::DeleteMemory(), cbDebugInterfaceFactory::DeleteThreads(), cbDebugInterfaceFactory::DeleteWatches(), m_backtraceDialog, m_breakPointsDialog, m_cpuRegistersDialog, m_disassemblyDialog, m_examineMemoryDialog, m_interfaceFactory, m_threadsDialog, and m_watchesDialog.
Referenced by UnregisterDebugger().
FindTargetsDebugger()
void DebuggerManager::FindTargetsDebugger () private
Definition at line 1217 of file debuggermanager.cpp.
References cbProject::BuildTargetValid(), CompilerPrograms::DBGconfig, Manager::Get(), cbProject::GetActiveBuildTarget(), ProjectManager::GetActiveProject(), cbProject::GetBuildTarget(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), DebuggerManager::PluginData::GetConfigurations(), CompilerFactory::GetDefaultCompiler(), Compiler::GetID(), Manager::GetLogManager(), Compiler::GetName(), Compiler::GetPrograms(), Manager::GetProjectManager(), CompileTargetBase::GetTitle(), LogManager::LogError(), m_activeDebugger, m_menuHandler, m_registered, m_useTargetsDefault, cbDebuggerMenuHandler::MarkActiveTargetAsValid(), RefreshUI(), cbDebuggerPlugin::SetActiveConfig(), cbDebuggerMenuHandler::SetActiveDebugger(), and WriteActiveDebuggerConfig().
Referenced by OnPluginLoadingComplete(), OnProjectActivated(), OnSettingsChanged(), OnTargetSelected(), and SetTargetsDefaultAsActiveDebugger().
GetActiveDebugger()
cbDebuggerPlugin * DebuggerManager::GetActiveDebugger ()
Definition at line 1149 of file debuggermanager.cpp.
References m_activeDebugger.
Referenced by cbEditor::AddBreakpoint(), DebuggerMenuHandler::BuildContextMenu(), cbDebuggerPlugin::BuildModuleMenu(), DisassemblyDlg::Clear(), DebuggerMenuHandler::DebuggerMenuHandler(), BacktraceDlg::IsSwitchFrameEnabled(), cbEditor::OnBeforeBuildContextMenu(), BreakpointsDlg::OnBreakpointAdd(), ValueTooltip::OnCollapse(), WatchesDropTarget::OnDropText(), cbEditor::OnEditorModified(), DebugLogPanel::OnEntryCommand(), ValueTooltip::OnExpand(), ExamineMemoryDlg::OnGo(), BacktraceDlg::OnJump(), DebugLogPanel::OnLoadFile(), WatchesDlg::OnMenuAddDataBreak(), WatchesDlg::OnMenuUpdate(), DisassemblyDlg::OnMixedModeCB(), DebuggerSettingsDlg::OnOK(), WatchesDlg::OnPropertyRightClick(), WatchesDlg::OnPropertySelected(), DisassemblyDlg::OnRefresh(), DebuggerToolbarHandler::OnStop(), BacktraceDlg::OnSwitchFrame(), ThreadsDlg::OnSwitchThread(), DebuggerToolbarHandler::OnToolInfo(), DebuggerToolbarHandler::OnUpdateUI(), DebugLogPanel::OnUpdateUI(), cbEditor::RefreshBreakpointMarkers(), WatchesDlg::RefreshUI(), ThreadsDlg::Reload(), BacktraceDlg::Reload(), BreakpointsDlg::Reload(), cbEditor::RemoveBreakpoint(), WatchesDlg::RenameWatch(), CompilerGCC::StopRunningDebugger(), and cbEditor::ToggleBreakpoint().
GetAllDebuggers() [1/2]
DebuggerManager::RegisteredPlugins const & DebuggerManager::GetAllDebuggers () const
Definition at line 1141 of file debuggermanager.cpp.
References m_registered.
Referenced by DebuggerSettingsDlg::DebuggerSettingsDlg(), CompilerOptionsDlg::DoFillCompilerPrograms(), cbDebuggerPlugin::GetActiveConfig(), DebuggerMenuHandler::LogActiveConfig(), DebuggerMenuHandler::OnActiveDebuggerClick(), cbEditor::OnEditorModified(), DebuggerSettingsDlg::OnOK(), DebuggerMenuHandler::RebuildMenus(), cbEditor::RefreshBreakpointMarkers(), and BreakpointsDlg::Reload().
GetAllDebuggers() [2/2]
DebuggerManager::RegisteredPlugins & DebuggerManager::GetAllDebuggers ()
Definition at line 1145 of file debuggermanager.cpp.
References m_registered.
GetBacktraceDialog()
cbBacktraceDlg * DebuggerManager::GetBacktraceDialog ()
Definition at line 1049 of file debuggermanager.cpp.
References m_backtraceDialog.
Referenced by CdbCmd_Backtrace::ParseOutput(), CdbCmd_SwitchFrame::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), DebuggerMenuHandler::RegisterDefaultWindowItems(), DebuggerDriver::ResetCurrentFrame(), ShowBacktraceDialog(), and DebuggerGDB::SwitchToFrame().
GetBreakpointDialog()
cbBreakpointsDlg * DebuggerManager::GetBreakpointDialog ()
Returns a pointer to the breakpoints dialog.
It will return nullptr if there are no debugger plugins loaded. Debugger plugin writers can treat it as always returning non-null value.
Definition at line 1054 of file debuggermanager.cpp.
References m_breakPointsDialog.
Referenced by cbEditor::AddBreakpoint(), DebuggerGDB::CleanupWhenProjectClosed(), DebuggerMenuHandler::OnAddDataBreakpoint(), cbEditor::OnContextMenuEntry(), cbEditor::OnEditorModified(), DebuggerGDB::OnGDBTerminated(), WatchesDlg::OnMenuAddDataBreak(), DebuggerMenuHandler::OnRemoveAllBreakpoints(), GDB_driver::ParseOutput(), GdbCmd_AddBreakpoint::ParseOutput(), GdbCmd_AddDataBreakpoint::ParseOutput(), DebuggerMenuHandler::RegisterDefaultWindowItems(), cbEditor::RemoveBreakpoint(), DebuggerGDB::RunToCursor(), and cbEditor::ToggleBreakpoint().
GetCPURegistersDialog()
cbCPURegistersDlg * DebuggerManager::GetCPURegistersDialog ()
Returns a pointer to the CPU registers dialog.
It will return nullptr if there are no debugger plugins loaded. Debugger plugin writers can treat it as always returning non-null value.
Definition at line 1059 of file debuggermanager.cpp.
References m_cpuRegistersDialog.
Referenced by CdbCmd_InfoRegisters::ParseOutput(), GdbCmd_InfoRegisters::ParseOutput(), GdbCmd_InfoRegisters::ParseOutputFromOR32gdbPort(), and DebuggerMenuHandler::RegisterDefaultWindowItems().
GetDebuggerHavingWatch()
cbDebuggerPlugin * DebuggerManager::GetDebuggerHavingWatch (cb::shared_ptr< cbWatch > watch)
Definition at line 1125 of file debuggermanager.cpp.
References cbGetRootWatch(), m_registered, and NULL.
Referenced by ValueTooltip::ClearWatch(), WatchesDlg::DeleteProperty(), WatchesDlg::OnCollapse(), WatchesDlg::OnExpand(), WatchesDlg::OnKeyDown(), WatchesDlg::OnMenuDeleteAll(), WatchesDlg::OnMenuProperties(), WatchesDlg::OnPropertyRightClick(), WatchesDlg::RefreshUI(), WatchesDlg::RenameWatch(), and SetValue().
GetDisassemblyDialog()
cbDisassemblyDlg * DebuggerManager::GetDisassemblyDialog ()
Returns a pointer to the disassembly dialog.
It will return nullptr if there are no debugger plugins loaded. Debugger plugin writers can treat it as always returning non-null value.
Definition at line 1064 of file debuggermanager.cpp.
References m_disassemblyDialog.
Referenced by DebuggerGDB::OnCursorChanged(), CdbCmd_Disassembly::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_Disassembly::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_StepOrNextInstruction::ParseOutput(), DebuggerMenuHandler::RegisterDefaultWindowItems(), and GDB_driver::Start().
GetExamineMemoryDialog()
cbExamineMemoryDlg * DebuggerManager::GetExamineMemoryDialog ()
Returns a pointer to the memory dialog.
It will return nullptr if there are no debugger plugins loaded. Debugger plugin writers can treat it as always returning non-null value.
Definition at line 1069 of file debuggermanager.cpp.
References m_examineMemoryDialog.
Referenced by GdbCmd_ExamineMemory::GdbCmd_ExamineMemory(), GdbCmd_ExamineMemory::ParseOutput(), and DebuggerMenuHandler::RegisterDefaultWindowItems().
GetInterfaceFactory()
cbDebugInterfaceFactory * DebuggerManager::GetInterfaceFactory ()
Definition at line 1034 of file debuggermanager.cpp.
References m_interfaceFactory.
Referenced by cbDebuggerPlugin::CancelValueTooltip().
GetLogger() [1/2]
TextCtrlLogger * DebuggerManager::GetLogger (int & index)
Definition at line 940 of file debuggermanager.cpp.
References cbEVT_ADD_LOG_WINDOW, cbLoadBitmap(), Manager::Get(), ConfigManager::GetDataFolder(), Manager::GetLogManager(), LogSlot::icon, m_logger, m_loggerIndex, Manager::ProcessEvent(), LogManager::SetLog(), LogManager::Slot(), and LogSlot::title.
Referenced by cbDebuggerPlugin::ClearLog(), DebuggerSettingsDlg::OnOK(), and cbDebuggerPlugin::ShowLog().
GetLogger() [2/2]
TextCtrlLogger * DebuggerManager::GetLogger ()
Definition at line 963 of file debuggermanager.cpp.
Referenced by RegisterDebugger().
GetMenu()
wxMenu * DebuggerManager::GetMenu ()
Definition at line 887 of file debuggermanager.cpp.
References cbAssert, Manager::Get(), Manager::GetAppFrame(), Manager::LoadMenu(), m_menuHandler, NULL, and cbDebuggerMenuHandler::RebuildMenus().
Referenced by cbDebuggerPlugin::BuildMenu().
GetMenuHandler()
cbDebuggerMenuHandler * DebuggerManager::GetMenuHandler ()
Definition at line 1044 of file debuggermanager.cpp.
References m_menuHandler.
GetThreadsDialog()
cbThreadsDlg * DebuggerManager::GetThreadsDialog ()
Returns a pointer to the threads dialog.
It will return nullptr if there are no debugger plugins loaded. Debugger plugin writers can treat it as always returning non-null value.
Definition at line 1074 of file debuggermanager.cpp.
References m_threadsDialog.
Referenced by GdbCmd_Threads::ParseOutput(), and DebuggerMenuHandler::RegisterDefaultWindowItems().
GetWatchesDialog()
cbWatchesDlg * DebuggerManager::GetWatchesDialog ()
Returns a pointer to the watches dialog.
It will return nullptr if there are no debugger plugins loaded. Debugger plugin writers can treat it as always returning non-null value.
Definition at line 1079 of file debuggermanager.cpp.
References m_watchesDialog.
Referenced by DbgCmd_UpdateWatchesTree::Action(), DebuggerGDB::DoWatches(), DebuggerMenuHandler::OnAddWatch(), DebuggerGDB::OnConfigurationChange(), DebuggerGDB::OnCursorChanged(), WatchesDropTarget::OnDropText(), DebuggerGDB::OnMenuWatchDereference(), and DebuggerMenuHandler::RegisterDefaultWindowItems().
HasMenu()
bool DebuggerManager::HasMenu () const
Definition at line 927 of file debuggermanager.cpp.
References cbAssert, Manager::Get(), and Manager::GetAppFrame().
HideLogger()
void DebuggerManager::HideLogger ()
Definition at line 969 of file debuggermanager.cpp.
References cbEVT_REMOVE_LOG_WINDOW, Manager::Get(), m_logger, m_loggerIndex, and Manager::ProcessEvent().
Referenced by UnregisterDebugger().
IsActiveDebuggerTargetsDefault()
bool DebuggerManager::IsActiveDebuggerTargetsDefault () const
Definition at line 1205 of file debuggermanager.cpp.
References m_activeDebugger, and m_useTargetsDefault.
Referenced by DebuggerMenuHandler::RebuildMenus().
IsDisassemblyMixedMode()
bool DebuggerManager::IsDisassemblyMixedMode ()
Definition at line 1320 of file debuggermanager.cpp.
References m_isDisassemblyMixedMode.
Referenced by DisassemblyDlg::OnMixedModeCB(), GdbCmd_DisassemblyInit::ParseOutput(), and DisassemblyDlg::SetActiveAddress().
NewConfig()
ConfigManagerWrapper DebuggerManager::NewConfig (cbDebuggerPlugin * plugin, const wxString & name)
Definition at line 855 of file debuggermanager.cpp.
References ConfigManager::EnumerateSubPaths(), Manager::Get(), Manager::GetConfigManager(), and m_registered.
Referenced by DebuggerSettingsDlg::OnOK().
OnPluginLoadingComplete()
void DebuggerManager::OnPluginLoadingComplete (CodeBlocksEvent & event) private
Definition at line 1351 of file debuggermanager.cpp.
References FindTargetsDebugger(), m_activeDebugger, m_useTargetsDefault, and RefreshUI().
Referenced by DebuggerManager().
OnProjectActivated()
void DebuggerManager::OnProjectActivated (CodeBlocksEvent & event) private
Definition at line 1330 of file debuggermanager.cpp.
References FindTargetsDebugger(), and m_useTargetsDefault.
Referenced by DebuggerManager().
OnSettingsChanged()
void DebuggerManager::OnSettingsChanged (CodeBlocksEvent & event) private
Definition at line 1342 of file debuggermanager.cpp.
References cbSettingsType::Compiler, cbSettingsType::Debugger, FindTargetsDebugger(), and m_useTargetsDefault.
Referenced by DebuggerManager().
OnTargetSelected()
void DebuggerManager::OnTargetSelected (CodeBlocksEvent & event) private
Definition at line 1336 of file debuggermanager.cpp.
References FindTargetsDebugger(), and m_useTargetsDefault.
Referenced by DebuggerManager().
ProcessSettings()
void DebuggerManager::ProcessSettings (RegisteredPlugins::iterator it) private
Definition at line 821 of file debuggermanager.cpp.
References DebuggerManager::PluginData::ClearConfigurations(), ConfigManager::EnumerateSubPaths(), Manager::Get(), Manager::GetConfigManager(), DebuggerManager::PluginData::GetConfigurations(), cbDebuggerPlugin::GetSettingsName(), cbDebuggerPlugin::LoadConfig(), DebuggerManager::PluginData::m_lastConfigID, ConfigManager::Read(), cbDebuggerConfiguration::SetName(), and ConfigManager::Write().
Referenced by RebuildAllConfigs(), and RegisterDebugger().
RebuildAllConfigs()
void DebuggerManager::RebuildAllConfigs ()
Definition at line 880 of file debuggermanager.cpp.
References m_menuHandler, m_registered, ProcessSettings(), and cbDebuggerMenuHandler::RebuildMenus().
Referenced by DebuggerSettingsDlg::OnOK().
RefreshUI()
void DebuggerManager::RefreshUI () private
Definition at line 1180 of file debuggermanager.cpp.
References cbDebuggerFeature::Callstack, cbDebuggerFeature::CPURegisters, cbDebuggerFeature::Disassembly, cbBacktraceDlg::EnableWindow(), cbCPURegistersDlg::EnableWindow(), cbDisassemblyDlg::EnableWindow(), cbExamineMemoryDlg::EnableWindow(), cbThreadsDlg::EnableWindow(), cbDebuggerFeature::ExamineMemory, m_activeDebugger, m_backtraceDialog, m_breakPointsDialog, m_cpuRegistersDialog, m_disassemblyDialog, m_examineMemoryDialog, m_menuHandler, m_threadsDialog, m_watchesDialog, cbDebuggerMenuHandler::RebuildMenus(), RefreshBreakpoints(), cbWatchesDlg::RefreshUI(), cbBreakpointsDlg::Reload(), cbDebuggerMenuHandler::SetActiveDebugger(), cbDebuggerPlugin::SupportsFeature(), and cbDebuggerFeature::Threads.
Referenced by FindTargetsDebugger(), OnPluginLoadingComplete(), SetActiveDebugger(), and UnregisterDebugger().
RegisterDebugger()
bool DebuggerManager::RegisterDebugger (cbDebuggerPlugin * plugin)
Called to register a debugger plugin.
It is called by cbDebuggerPlugin::OnAttach and it should not be called by the debugger plugins explicitly in their OnAttachReal methods.
Definition at line 735 of file debuggermanager.cpp.
References cbAssert, CreateWindows(), Manager::Get(), cbDebuggerPlugin::GetGUIName(), GetLogger(), Manager::GetLogManager(), cbDebuggerPlugin::GetSettingsName(), LogManager::LogError(), m_activeDebugger, m_menuHandler, m_registered, ProcessSettings(), ReadActiveDebuggerConfig(), cbDebuggerMenuHandler::RebuildMenus(), cbDebuggerPlugin::SetActiveConfig(), cbDebuggerMenuHandler::SetActiveDebugger(), and cbDebuggerPlugin::SetupLog().
Referenced by cbDebuggerPlugin::OnAttach().
SetActiveDebugger()
void DebuggerManager::SetActiveDebugger (cbDebuggerPlugin * activeDebugger, ConfigurationVector::const_iterator config)
Definition at line 1166 of file debuggermanager.cpp.
References cbAssert, m_activeDebugger, m_registered, m_useTargetsDefault, RefreshUI(), cbDebuggerPlugin::SetActiveConfig(), and WriteActiveDebuggerConfig().
Referenced by DebuggerMenuHandler::OnActiveDebuggerClick().
SetDisassemblyMixedMode()
void DebuggerManager::SetDisassemblyMixedMode (bool mixed)
Definition at line 1325 of file debuggermanager.cpp.
References m_isDisassemblyMixedMode.
Referenced by DisassemblyDlg::OnMixedModeCB().
SetInterfaceFactory()
void DebuggerManager::SetInterfaceFactory (cbDebugInterfaceFactory * factory)
Definition at line 978 of file debuggermanager.cpp.
References cbAssert, CreateWindows(), cbBacktraceDlg::EnableWindow(), cbCPURegistersDlg::EnableWindow(), cbDisassemblyDlg::EnableWindow(), cbExamineMemoryDlg::EnableWindow(), cbThreadsDlg::EnableWindow(), m_backtraceDialog, m_cpuRegistersDialog, m_disassemblyDialog, m_examineMemoryDialog, m_interfaceFactory, and m_threadsDialog.
Referenced by MainFrame::SetupDebuggerUI().
SetMenuHandler()
void DebuggerManager::SetMenuHandler (cbDebuggerMenuHandler * handler)
Definition at line 1039 of file debuggermanager.cpp.
References m_menuHandler.
Referenced by MainFrame::CreateMenubar().
SetTargetsDefaultAsActiveDebugger()
void DebuggerManager::SetTargetsDefaultAsActiveDebugger ()
Definition at line 1210 of file debuggermanager.cpp.
References FindTargetsDebugger(), m_activeDebugger, m_menuHandler, and cbDebuggerMenuHandler::SetActiveDebugger().
Referenced by DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick().
ShowBacktraceDialog()
bool DebuggerManager::ShowBacktraceDialog ()
Definition at line 1084 of file debuggermanager.cpp.
References cbEVT_SHOW_DOCK_WINDOW, Manager::Get(), GetBacktraceDialog(), cbBacktraceDlg::GetWindow(), IsWindowReallyShown(), Manager::ProcessEvent(), and CodeBlocksDockEvent::pWindow.
Referenced by CDB_driver::ParseOutput().
ShowValueTooltip()
bool DebuggerManager::ShowValueTooltip (const cb::shared_ptr< cbWatch > & watch, const wxRect & rect)
Definition at line 1136 of file debuggermanager.cpp.
References m_interfaceFactory, and cbDebugInterfaceFactory::ShowValueTooltip().
UnregisterDebugger()
bool DebuggerManager::UnregisterDebugger (cbDebuggerPlugin * plugin)
Called to unregister a debugger plugin.
It is called by cbDebuggerPlugin::OnRelease and it should not be called by the debugger plugins explicitly in their OnReleaseReal methods.
Definition at line 788 of file debuggermanager.cpp.
References DestoryWindows(), Manager::Get(), Manager::GetDebuggerManager(), HideLogger(), Manager::IsAppShuttingDown(), m_activeDebugger, m_menuHandler, m_registered, cbDebuggerMenuHandler::RebuildMenus(), RefreshUI(), and cbDebuggerMenuHandler::SetActiveDebugger().
Referenced by cbDebuggerPlugin::OnRelease().
UpdateBacktrace()
bool DebuggerManager::UpdateBacktrace ()
Definition at line 1100 of file debuggermanager.cpp.
References cbBacktraceDlg::GetWindow(), IsWindowReallyShown(), and m_backtraceDialog.
Referenced by DebuggerGDB::OnCursorChanged().
UpdateCPURegisters()
bool DebuggerManager::UpdateCPURegisters ()
Definition at line 1105 of file debuggermanager.cpp.
References cbCPURegistersDlg::GetWindow(), IsWindowReallyShown(), and m_cpuRegistersDialog.
Referenced by DebuggerGDB::OnCursorChanged().
UpdateDisassembly()
bool DebuggerManager::UpdateDisassembly ()
Definition at line 1110 of file debuggermanager.cpp.
References cbDisassemblyDlg::GetWindow(), IsWindowReallyShown(), and m_disassemblyDialog.
Referenced by DebuggerGDB::OnCursorChanged(), and GdbCmd_StepOrNextInstruction::ParseOutput().
UpdateExamineMemory()
bool DebuggerManager::UpdateExamineMemory ()
Definition at line 1115 of file debuggermanager.cpp.
References cbExamineMemoryDlg::GetWindow(), IsWindowReallyShown(), and m_examineMemoryDialog.
Referenced by DebuggerGDB::OnCursorChanged().
UpdateThreads()
bool DebuggerManager::UpdateThreads ()
Definition at line 1120 of file debuggermanager.cpp.
References cbThreadsDlg::GetWindow(), IsWindowReallyShown(), and m_threadsDialog.
Referenced by DebuggerGDB::OnCursorChanged().
Friends And Related Function Documentation
Manager
friend class Manager friend
Definition at line 235 of file debuggermanager.h.
Mgr< DebuggerManager >
friend class Mgr< DebuggerManager > friend
Definition at line 234 of file debuggermanager.h.
Member Data Documentation
m_activeDebugger
cbDebuggerPlugin* DebuggerManager::m_activeDebugger private
Definition at line 363 of file debuggermanager.h.
Referenced by FindTargetsDebugger(), GetActiveDebugger(), IsActiveDebuggerTargetsDefault(), OnPluginLoadingComplete(), RefreshUI(), RegisterDebugger(), SetActiveDebugger(), SetTargetsDefaultAsActiveDebugger(), and UnregisterDebugger().
m_backtraceDialog
cbBacktraceDlg* DebuggerManager::m_backtraceDialog private
Definition at line 366 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetBacktraceDialog(), RefreshUI(), SetInterfaceFactory(), and UpdateBacktrace().
m_breakPointsDialog
cbBreakpointsDlg* DebuggerManager::m_breakPointsDialog private
Definition at line 367 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetBreakpointDialog(), and RefreshUI().
m_cpuRegistersDialog
cbCPURegistersDlg* DebuggerManager::m_cpuRegistersDialog private
Definition at line 368 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetCPURegistersDialog(), RefreshUI(), SetInterfaceFactory(), and UpdateCPURegisters().
m_disassemblyDialog
cbDisassemblyDlg* DebuggerManager::m_disassemblyDialog private
Definition at line 369 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetDisassemblyDialog(), RefreshUI(), SetInterfaceFactory(), and UpdateDisassembly().
m_examineMemoryDialog
cbExamineMemoryDlg* DebuggerManager::m_examineMemoryDialog private
Definition at line 370 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetExamineMemoryDialog(), RefreshUI(), SetInterfaceFactory(), and UpdateExamineMemory().
m_interfaceFactory
cbDebugInterfaceFactory* DebuggerManager::m_interfaceFactory private
Definition at line 360 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetInterfaceFactory(), SetInterfaceFactory(), ShowValueTooltip(), and ~DebuggerManager().
m_isDisassemblyMixedMode
bool DebuggerManager::m_isDisassemblyMixedMode private
Definition at line 376 of file debuggermanager.h.
Referenced by IsDisassemblyMixedMode(), and SetDisassemblyMixedMode().
m_logger
TextCtrlLogger* DebuggerManager::m_logger private
Definition at line 374 of file debuggermanager.h.
Referenced by GetLogger(), and HideLogger().
m_loggerIndex
int DebuggerManager::m_loggerIndex private
Definition at line 375 of file debuggermanager.h.
Referenced by GetLogger(), and HideLogger().
m_menuHandler
cbDebuggerMenuHandler* DebuggerManager::m_menuHandler private
Definition at line 364 of file debuggermanager.h.
Referenced by BuildContextMenu(), FindTargetsDebugger(), GetMenu(), GetMenuHandler(), RebuildAllConfigs(), RefreshUI(), RegisterDebugger(), SetMenuHandler(), SetTargetsDefaultAsActiveDebugger(), and UnregisterDebugger().
m_registered
RegisteredPlugins DebuggerManager::m_registered private
Definition at line 362 of file debuggermanager.h.
Referenced by FindTargetsDebugger(), GetAllDebuggers(), GetDebuggerHavingWatch(), NewConfig(), RebuildAllConfigs(), RegisterDebugger(), SetActiveDebugger(), UnregisterDebugger(), and ~DebuggerManager().
m_threadsDialog
cbThreadsDlg* DebuggerManager::m_threadsDialog private
Definition at line 371 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetThreadsDialog(), RefreshUI(), SetInterfaceFactory(), and UpdateThreads().
m_useTargetsDefault
bool DebuggerManager::m_useTargetsDefault private
Definition at line 377 of file debuggermanager.h.
Referenced by DebuggerManager(), FindTargetsDebugger(), IsActiveDebuggerTargetsDefault(), OnPluginLoadingComplete(), OnProjectActivated(), OnSettingsChanged(), OnTargetSelected(), and SetActiveDebugger().
m_watchesDialog
cbWatchesDlg* DebuggerManager::m_watchesDialog private
Definition at line 372 of file debuggermanager.h.
Referenced by CreateWindows(), DestoryWindows(), GetWatchesDialog(), and RefreshUI().
The documentation for this class was generated from the following files:
debuggermanager.h
debuggermanager.cpp