Code::Blocks: cbTool Class Reference
cbTool Class Reference
#include <cbtool.h>
Public Types
enum eLaunchOption { LAUNCH_NEW_CONSOLE_WINDOW, LAUNCH_HIDDEN, LAUNCH_VISIBLE, LAUNCH_VISIBLE_DETACHED }
Public Member Functions
cbTool ()
wxString GetName () const
wxString GetCommand () const
wxString GetParams () const
wxString GetWorkingDir () const
eLaunchOption GetLaunchOption () const
int GetMenuId () const
void SetName (const wxString &Name)
void SetCommand (const wxString &Command)
void SetParams (const wxString &Params)
void SetWorkingDir (const wxString &WorkingDir)
void SetLaunchOption (eLaunchOption LaunchOption)
void SetMenuId (int MenuId)
Private Attributes
wxString m_Name
wxString m_Command
wxString m_Params
wxString m_WorkingDir
eLaunchOption m_LaunchOption
int m_MenuId
Detailed Description
Definition at line 13 of file cbtool.h.
Member Enumeration Documentation
eLaunchOption
enum cbTool::eLaunchOption
Enumerator
LAUNCH_NEW_CONSOLE_WINDOW
LAUNCH_HIDDEN
LAUNCH_VISIBLE
LAUNCH_VISIBLE_DETACHED
Definition at line 16 of file cbtool.h.
Constructor & Destructor Documentation
cbTool()
cbTool::cbTool () inline
Definition at line 24 of file cbtool.h.
References LAUNCH_NEW_CONSOLE_WINDOW, m_LaunchOption, and m_MenuId.
Member Function Documentation
GetCommand()
wxString cbTool::GetCommand () const inline
Definition at line 27 of file cbtool.h.
References m_Command.
Referenced by ToolsManager::Execute(), ToolsManager::LoadTools(), and ToolsManager::SaveTools().
GetLaunchOption()
eLaunchOption cbTool::GetLaunchOption () const inline
Definition at line 30 of file cbtool.h.
References m_LaunchOption.
Referenced by ToolsManager::Execute(), and ToolsManager::SaveTools().
GetMenuId()
int cbTool::GetMenuId () const inline
Definition at line 31 of file cbtool.h.
References m_MenuId.
Referenced by ToolsManager::BuildToolsMenu(), and ToolsManager::GetToolByMenuId().
GetName()
wxString cbTool::GetName () const inline
Definition at line 26 of file cbtool.h.
References m_Name.
Referenced by ToolsManager::BuildToolsMenu(), ToolsManager::Execute(), ToolsManager::LoadTools(), ToolsManager::OnToolClick(), and ToolsManager::SaveTools().
GetParams()
wxString cbTool::GetParams () const inline
Definition at line 28 of file cbtool.h.
References m_Params.
Referenced by ToolsManager::Execute(), and ToolsManager::SaveTools().
GetWorkingDir()
wxString cbTool::GetWorkingDir () const inline
Definition at line 29 of file cbtool.h.
References m_WorkingDir.
Referenced by ToolsManager::Execute(), and ToolsManager::SaveTools().
SetCommand()
void cbTool::SetCommand (const wxString & Command) inline
Definition at line 34 of file cbtool.h.
References m_Command.
Referenced by EditToolDlg::EndModal(), ToolsManager::LoadTools(), and ConfigureToolsDlg::OnAddSeparator().
SetLaunchOption()
void cbTool::SetLaunchOption (eLaunchOption LaunchOption) inline
Definition at line 37 of file cbtool.h.
References m_LaunchOption.
Referenced by EditToolDlg::EndModal(), and ToolsManager::LoadTools().
SetMenuId()
void cbTool::SetMenuId (int MenuId) inline
Definition at line 38 of file cbtool.h.
References m_MenuId.
Referenced by ToolsManager::BuildToolsMenu().
SetName()
void cbTool::SetName (const wxString & Name) inline
Definition at line 33 of file cbtool.h.
References m_Name.
Referenced by EditToolDlg::EndModal(), ToolsManager::LoadTools(), and ConfigureToolsDlg::OnAddSeparator().
SetParams()
void cbTool::SetParams (const wxString & Params) inline
Definition at line 35 of file cbtool.h.
References m_Params.
Referenced by EditToolDlg::EndModal(), and ToolsManager::LoadTools().
SetWorkingDir()
void cbTool::SetWorkingDir (const wxString & WorkingDir) inline
Definition at line 36 of file cbtool.h.
References m_WorkingDir.
Referenced by EditToolDlg::EndModal(), and ToolsManager::LoadTools().
Member Data Documentation
m_Command
wxString cbTool::m_Command private
Definition at line 41 of file cbtool.h.
Referenced by GetCommand(), and SetCommand().
m_LaunchOption
eLaunchOption cbTool::m_LaunchOption private
Definition at line 44 of file cbtool.h.
Referenced by cbTool(), GetLaunchOption(), and SetLaunchOption().
m_MenuId
int cbTool::m_MenuId private
Definition at line 45 of file cbtool.h.
Referenced by cbTool(), GetMenuId(), and SetMenuId().
m_Name
wxString cbTool::m_Name private
Definition at line 40 of file cbtool.h.
Referenced by GetName(), and SetName().
m_Params
wxString cbTool::m_Params private
Definition at line 42 of file cbtool.h.
Referenced by GetParams(), and SetParams().
m_WorkingDir
wxString cbTool::m_WorkingDir private
Definition at line 43 of file cbtool.h.
Referenced by GetWorkingDir(), and SetWorkingDir().
The documentation for this class was generated from the following file:
cbtool.h