Code::Blocks: DebuggerConfigurationPanel Class Reference
DebuggerConfigurationPanel Class Reference
Public Member Functions
void ValidateExecutablePath ()
Private Member Functions
void OnBrowse (cb_unused wxCommandEvent &event)
void OnTextChange (cb_unused wxCommandEvent &event)
Detailed Description
Definition at line 28 of file debuggeroptionsdlg.cpp.
Member Function Documentation
OnBrowse()
void DebuggerConfigurationPanel::OnBrowse (cb_unused wxCommandEvent & event) inline private
Definition at line 51 of file debuggeroptionsdlg.cpp.
References _(), Manager::Get(), Manager::GetMacrosManager(), wxFileDialog::GetPath(), PlaceWindow(), MacrosManager::ReplaceEnvVars(), wxFileDialog::ShowModal(), wxEmptyString, wxFD_FILE_MUST_EXIST, wxFD_OPEN, wxFileSelectorDefaultWildcardStr, and wxID_OK.
Referenced by OnTextChange().
OnTextChange()
void DebuggerConfigurationPanel::OnTextChange (cb_unused wxCommandEvent & event) inline private
Definition at line 65 of file debuggeroptionsdlg.cpp.
References OnBrowse(), and ValidateExecutablePath().
ValidateExecutablePath()
void DebuggerConfigurationPanel::ValidateExecutablePath () inline
Definition at line 31 of file debuggeroptionsdlg.cpp.
References _(), Manager::Get(), Manager::GetMacrosManager(), MacrosManager::ReplaceEnvVars(), wxFileExists(), wxNullColour, wxRED, and wxWHITE.
Referenced by DebuggerConfiguration::MakePanel(), and OnTextChange().
The documentation for this class was generated from the following file:
debuggeroptionsdlg.cpp