Code::Blocks: ConfirmReplaceDlg Class Reference
ConfirmReplaceDlg Class Reference
#include <confirmreplacedlg.h>
Public Member Functions
ConfirmReplaceDlg (wxWindow *parent, bool replaceInFiles=false, const wxString &label=_("Replace this occurrence?"))
~ConfirmReplaceDlg ()
void OnYes (wxCommandEvent &event)
void OnNo (wxCommandEvent &event)
void OnAllInFile (wxCommandEvent &event)
void OnSkipFile (wxCommandEvent &event)
void OnAll (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void CalcPosition (cbStyledTextCtrl *ed)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Detailed Description
Definition at line 25 of file confirmreplacedlg.h.
Constructor & Destructor Documentation
ConfirmReplaceDlg()
ConfirmReplaceDlg::ConfirmReplaceDlg (wxWindow * parent, bool replaceInFiles = false, const wxString & label = _("Replace this occurrence?"))
Definition at line 32 of file confirmreplacedlg.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadObject().
~ConfirmReplaceDlg()
ConfirmReplaceDlg::~ConfirmReplaceDlg ()
Definition at line 42 of file confirmreplacedlg.cpp.
Member Function Documentation
CalcPosition()
void ConfirmReplaceDlg::CalcPosition (cbStyledTextCtrl * ed)
Definition at line 76 of file confirmreplacedlg.cpp.
References wxScintilla::GetCurrentLine(), wxScintilla::GetCurrentPos(), wxSystemSettings::GetMetric(), wxScintilla::PointFromPosition(), wxScintilla::TextHeight(), wxSYS_SCREEN_X, wxSYS_SCREEN_Y, wxPoint::x, and wxPoint::y.
Referenced by FindReplace::Replace(), and FindReplace::ReplaceInFiles().
OnAll()
void ConfirmReplaceDlg::OnAll (wxCommandEvent & event)
Definition at line 66 of file confirmreplacedlg.cpp.
References crAll, and ScriptBindings::EndModal().
OnAllInFile()
void ConfirmReplaceDlg::OnAllInFile (wxCommandEvent & event)
Definition at line 56 of file confirmreplacedlg.cpp.
References crAllInFile, and ScriptBindings::EndModal().
OnCancel()
void ConfirmReplaceDlg::OnCancel (wxCommandEvent & event)
Definition at line 71 of file confirmreplacedlg.cpp.
References crCancel, and ScriptBindings::EndModal().
OnNo()
void ConfirmReplaceDlg::OnNo (wxCommandEvent & event)
Definition at line 51 of file confirmreplacedlg.cpp.
References crNo, and ScriptBindings::EndModal().
OnSkipFile()
void ConfirmReplaceDlg::OnSkipFile (wxCommandEvent & event)
Definition at line 61 of file confirmreplacedlg.cpp.
References crSkipFile, and ScriptBindings::EndModal().
OnYes()
void ConfirmReplaceDlg::OnYes (wxCommandEvent & event)
Definition at line 46 of file confirmreplacedlg.cpp.
References crYes, and ScriptBindings::EndModal().
The documentation for this class was generated from the following files:
confirmreplacedlg.h
confirmreplacedlg.cpp