Code::Blocks: WizInfoPanel Class Reference
WizInfoPanel Class Reference
#include <wizpage.h>
Public Member Functions
WizInfoPanel (const wxString &pageId, const wxString &intro_msg, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizInfoPanel ()
virtual void OnPageChanging (wxWizardEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
InfoPanel * m_InfoPanel
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 68 of file wizpage.h.
Constructor & Destructor Documentation
WizInfoPanel()
WizInfoPanel::WizInfoPanel (const wxString & pageId, const wxString & intro_msg, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 246 of file wizpage.cpp.
References m_InfoPanel, and InfoPanel::SetIntroText().
~WizInfoPanel()
WizInfoPanel::~WizInfoPanel ()
Definition at line 254 of file wizpage.cpp.
Member Function Documentation
OnPageChanging()
void WizInfoPanel::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 258 of file wizpage.cpp.
References InfoPanel::chkSkip, wxWizardEvent::GetDirection(), WizPageBase::GetSkipPage(), wxCheckBox::GetValue(), m_InfoPanel, WizPageBase::OnPageChanging(), and WizPageBase::SetSkipPage().
Member Data Documentation
m_InfoPanel
InfoPanel* WizInfoPanel::m_InfoPanel private
Definition at line 76 of file wizpage.h.
Referenced by OnPageChanging(), and WizInfoPanel().
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp