Code::Blocks: MultiSelectDlg Class Reference
MultiSelectDlg Class Reference
#include <multiselectdlg.h>
Public Member Functions
MultiSelectDlg (wxWindow *parent, const wxArrayString &items, const wxString &wildcard, const wxString &label=_("Select items:"), const wxString &title=_("Multiple selection"))
MultiSelectDlg (wxWindow *parent, const wxArrayString &items, bool selectall=false, const wxString &label=_("Select items:"), const wxString &title=_("Multiple selection"))
virtual ~MultiSelectDlg ()
wxArrayString GetSelectedStrings () const
wxArrayInt GetSelectedIndices () const
void SelectWildCard (const wxString &wild, bool select=true, bool clearOld=false)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void Init (const wxArrayString &items, const wxString &wildcard)
void UpdateStatus ()
void OnWildcard (wxCommandEvent &event)
void OnToggle (wxCommandEvent &event)
void OnSelectAll (wxCommandEvent &event)
void OnDeselectAll (wxCommandEvent &event)
void OnItemToggle (wxCommandEvent &event)
Private Member Functions
DECLARE_EVENT_TABLE ()
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 14 of file multiselectdlg.h.
Constructor & Destructor Documentation
MultiSelectDlg() [1/2]
MultiSelectDlg::MultiSelectDlg (wxWindow * parent, const wxArrayString & items, const wxString & wildcard, const wxString & label = _("Select items:"), const wxString & title = _("Multiple selection"))
Definition at line 31 of file multiselectdlg.cpp.
MultiSelectDlg() [2/2]
MultiSelectDlg::MultiSelectDlg (wxWindow * parent, const wxArrayString & items, bool selectall = false, const wxString & label = _("Select items:"), const wxString & title = _("Multiple selection"))
Definition at line 46 of file multiselectdlg.cpp.
References wxScrollingDialog::Init().
~MultiSelectDlg()
MultiSelectDlg::~MultiSelectDlg () virtual
Definition at line 61 of file multiselectdlg.cpp.
Member Function Documentation
DECLARE_EVENT_TABLE()
MultiSelectDlg::DECLARE_EVENT_TABLE () private
GetSelectedIndices()
wxArrayInt MultiSelectDlg::GetSelectedIndices () const
Definition at line 101 of file multiselectdlg.cpp.
Referenced by ProjectManagerUI::AskForMultiBuildTargetIndex(), CodeCompletion::DoAllMethodsImpl(), and ProjectManagerUI::OnRemoveFileFromProject().
GetSelectedStrings()
wxArrayString MultiSelectDlg::GetSelectedStrings () const
Definition at line 89 of file multiselectdlg.cpp.
Referenced by ProjectManagerUI::OnAddFilesToProjectRecursively(), and ProjectOptionsDlg::OnPlatform().
Init()
void MultiSelectDlg::Init (const wxArrayString & items, const wxString & wildcard) protected
Definition at line 66 of file multiselectdlg.cpp.
References SelectWildCard().
OnDeselectAll()
void MultiSelectDlg::OnDeselectAll (wxCommandEvent & event) protected
Definition at line 195 of file multiselectdlg.cpp.
References UpdateStatus().
OnItemToggle()
void MultiSelectDlg::OnItemToggle (wxCommandEvent & event) protected
Definition at line 172 of file multiselectdlg.cpp.
References UpdateStatus().
OnSelectAll()
void MultiSelectDlg::OnSelectAll (wxCommandEvent & event) protected
Definition at line 186 of file multiselectdlg.cpp.
References UpdateStatus().
OnToggle()
void MultiSelectDlg::OnToggle (wxCommandEvent & event) protected
Definition at line 177 of file multiselectdlg.cpp.
References UpdateStatus().
OnWildcard()
void MultiSelectDlg::OnWildcard (wxCommandEvent & event) protected
Definition at line 143 of file multiselectdlg.cpp.
References cbGetTextFromUser(), cbMessageBox(), and SelectWildCard().
SelectWildCard()
void MultiSelectDlg::SelectWildCard (const wxString & wild, bool select = true, bool clearOld = false)
Definition at line 113 of file multiselectdlg.cpp.
References GetArrayFromString(), and UpdateStatus().
Referenced by Init(), ProjectOptionsDlg::OnPlatform(), and OnWildcard().
UpdateStatus()
void MultiSelectDlg::UpdateStatus () protected
Definition at line 75 of file multiselectdlg.cpp.
Referenced by OnDeselectAll(), OnItemToggle(), OnSelectAll(), OnToggle(), and SelectWildCard().
The documentation for this class was generated from the following files:
multiselectdlg.h
multiselectdlg.cpp