Code::Blocks: cbConfigurationDialog Class Reference
cbConfigurationDialog Class Reference
A simple dialog that wraps a cbConfigurationPanel.
#include <configurationpanel.h>
Public Member Functions
cbConfigurationDialog (wxWindow *parent, int id, const wxString &title)
void AttachConfigurationPanel (cbConfigurationPanel *panel)
~cbConfigurationDialog ()
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Attributes
cbConfigurationPanel * m_pPanel
wxButton * m_pOK
wxButton * m_pCancel
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
A simple dialog that wraps a cbConfigurationPanel.
Definition at line 58 of file configurationpanel.h.
Constructor & Destructor Documentation
cbConfigurationDialog()
cbConfigurationDialog::cbConfigurationDialog (wxWindow * parent, int id, const wxString & title)
Definition at line 16 of file configurationpanel.cpp.
~cbConfigurationDialog()
cbConfigurationDialog::~cbConfigurationDialog ()
Definition at line 50 of file configurationpanel.cpp.
Member Function Documentation
AttachConfigurationPanel()
void cbConfigurationDialog::AttachConfigurationPanel (cbConfigurationPanel * panel)
Definition at line 22 of file configurationpanel.cpp.
References m_pCancel, m_pOK, and m_pPanel.
Referenced by CompilerGCC::Configure().
EndModal()
void cbConfigurationDialog::EndModal (int retCode)
Definition at line 54 of file configurationpanel.cpp.
References ScriptBindings::EndModal(), m_pPanel, cbConfigurationPanel::OnApply(), and cbConfigurationPanel::OnCancel().
Member Data Documentation
m_pCancel
wxButton* cbConfigurationDialog::m_pCancel protected
Definition at line 69 of file configurationpanel.h.
Referenced by AttachConfigurationPanel().
m_pOK
wxButton* cbConfigurationDialog::m_pOK protected
Definition at line 68 of file configurationpanel.h.
Referenced by AttachConfigurationPanel().
m_pPanel
cbConfigurationPanel* cbConfigurationDialog::m_pPanel protected
Definition at line 67 of file configurationpanel.h.
Referenced by AttachConfigurationPanel(), and EndModal().
The documentation for this class was generated from the following files:
configurationpanel.h
configurationpanel.cpp