Code::Blocks: CodeBlocksLogEvent Class Reference
CodeBlocksLogEvent Class Reference
Event used to request from the main app to add a log.
#include <sdk_events.h>
Public Member Functions
CodeBlocksLogEvent (wxEventType commandType=wxEVT_NULL, Logger *logger=nullptr, const wxString &title=wxEmptyString, wxBitmap *icon=nullptr)
CodeBlocksLogEvent (wxEventType commandType, wxWindow *window, const wxString &title=wxEmptyString, wxBitmap *icon=nullptr)
CodeBlocksLogEvent (wxEventType commandType, int logIndex, const wxString &title=wxEmptyString, wxBitmap *icon=nullptr)
CodeBlocksLogEvent (const CodeBlocksLogEvent &rhs)
virtual wxEvent * Clone () const
Public Attributes
Logger * logger
The logger.
int logIndex
The logger's index.
wxBitmap * icon
The logger's icon. Valid only for cbEVT_ADD_LOG_WINDOW.
wxString title
The logger's title. Valid only for cbEVT_ADD_LOG_WINDOW.
wxWindow * window
A non-logger window. Needed at least by cbEVT_REMOVE_LOG_WINDOW.
Detailed Description
Event used to request from the main app to add a log.
Note
By adding a Logger*, the app takes ownership of it in cbEVT_ADD_LOG_WINDOW. By adding a wxWindow*, the ownership is not touched and you should delete the window after calling cbEVT_REMOVE_LOG_WINDOW for it.
Definition at line 182 of file sdk_events.h.
Constructor & Destructor Documentation
CodeBlocksLogEvent() [1/4]
CodeBlocksLogEvent::CodeBlocksLogEvent (wxEventType commandType = wxEVT_NULL, Logger * logger = nullptr, const wxString & title = wxEmptyString, wxBitmap * icon = nullptr)
Definition at line 28 of file sdk_events.cpp.
References cbAssert, cbEVT_ADD_LOG_WINDOW, LogManager::FindIndex(), Manager::Get(), Manager::GetLogManager(), LogSlot::icon, LogManager::invalid_log, LogManager::SetLog(), LogManager::Slot(), and LogSlot::title.
CodeBlocksLogEvent() [2/4]
CodeBlocksLogEvent::CodeBlocksLogEvent (wxEventType commandType, wxWindow * window, const wxString & title = wxEmptyString, wxBitmap * icon = nullptr)
Definition at line 55 of file sdk_events.cpp.
References wxID_ANY.
CodeBlocksLogEvent() [3/4]
CodeBlocksLogEvent::CodeBlocksLogEvent (wxEventType commandType, int logIndex, const wxString & title = wxEmptyString, wxBitmap * icon = nullptr)
Definition at line 48 of file sdk_events.cpp.
References Manager::Get(), LogSlot::GetLogger(), Manager::GetLogManager(), logger, logIndex, LogManager::Slot(), and wxID_ANY.
CodeBlocksLogEvent() [4/4]
CodeBlocksLogEvent::CodeBlocksLogEvent (const CodeBlocksLogEvent & rhs)
Definition at line 61 of file sdk_events.cpp.
References wxID_ANY.
Member Function Documentation
Clone()
virtual wxEvent* CodeBlocksLogEvent::Clone () const inline virtual
Definition at line 190 of file sdk_events.h.
Member Data Documentation
icon
wxBitmap* CodeBlocksLogEvent::icon
The logger's icon. Valid only for cbEVT_ADD_LOG_WINDOW.
Definition at line 194 of file sdk_events.h.
Referenced by MainFrame::OnAddLogWindow().
logger
Logger* CodeBlocksLogEvent::logger
The logger.
Definition at line 192 of file sdk_events.h.
Referenced by CodeBlocksLogEvent(), MainFrame::OnAddLogWindow(), MainFrame::OnHideLogWindow(), CompilerGCC::OnJobEnd(), MainFrame::OnRemoveLogWindow(), and MainFrame::OnSwitchToLogWindow().
logIndex
int CodeBlocksLogEvent::logIndex
The logger's index.
Definition at line 193 of file sdk_events.h.
Referenced by CodeBlocksLogEvent().
title
wxString CodeBlocksLogEvent::title
The logger's title. Valid only for cbEVT_ADD_LOG_WINDOW.
Definition at line 195 of file sdk_events.h.
Referenced by MainFrame::OnAddLogWindow().
window
wxWindow* CodeBlocksLogEvent::window
A non-logger window. Needed at least by cbEVT_REMOVE_LOG_WINDOW.
Definition at line 196 of file sdk_events.h.
Referenced by MainFrame::OnHideLogWindow(), MainFrame::OnRemoveLogWindow(), and MainFrame::OnSwitchToLogWindow().
The documentation for this class was generated from the following files:
sdk_events.h
sdk_events.cpp