Code::Blocks: LoaderBase Class Reference
LoaderBase Class Reference
#include <filemanager.h>
Public Member Functions
LoaderBase ()
~LoaderBase () override
void operator() () override
wxString FileName () const
bool Sync ()
char * GetData ()
size_t GetLength ()
Public Member Functions inherited from AbstractJob
AbstractJob ()
virtual ~AbstractJob ()
Protected Member Functions
void Ready ()
Protected Attributes
wxString fileName
char * data
size_t len
Private Member Functions
void WaitReady ()
Private Attributes
wxSemaphore sem
bool wait
Detailed Description
Definition at line 31 of file filemanager.h.
Constructor & Destructor Documentation
LoaderBase()
LoaderBase::LoaderBase () inline
Definition at line 56 of file filemanager.h.
~LoaderBase()
LoaderBase::~LoaderBase () override
Definition at line 30 of file filemanager.cpp.
References data, and WaitReady().
Member Function Documentation
FileName()
wxString LoaderBase::FileName () const inline
Definition at line 59 of file filemanager.h.
Referenced by EditorLexerLoader::Load(), and Tokenizer::ReadFile().
GetData()
char * LoaderBase::GetData ()
Definition at line 42 of file filemanager.cpp.
References data, and WaitReady().
Referenced by EncodingDetector::EncodingDetector(), EditorLexerLoader::Load(), CodeBlocksApp::OnInit(), cbEditor::Open(), and Tokenizer::ReadFile().
GetLength()
size_t LoaderBase::GetLength ()
Definition at line 48 of file filemanager.cpp.
References len, and WaitReady().
Referenced by EncodingDetector::EncodingDetector(), cbEditor::Open(), and Tokenizer::ReadFile().
operator()()
void LoaderBase::operator() () inline override virtual
Implements AbstractJob.
Reimplemented in EditorReuser, NullLoader, URLLoader, and FileLoader.
Definition at line 58 of file filemanager.h.
Ready()
void LoaderBase::Ready () inline protected
Definition at line 50 of file filemanager.h.
References wxSemaphore::Post().
Referenced by FileLoader::operator()(), and URLLoader::operator()().
Sync()
bool LoaderBase::Sync ()
Definition at line 36 of file filemanager.cpp.
References data, and WaitReady().
Referenced by ParserThread::~ParserThread().
WaitReady()
void LoaderBase::WaitReady () inline private
Definition at line 36 of file filemanager.h.
References wxSemaphore::Wait().
Referenced by GetData(), GetLength(), Sync(), and ~LoaderBase().
Member Data Documentation
data
char* LoaderBase::data protected
Definition at line 47 of file filemanager.h.
Referenced by GetData(), FileLoader::operator()(), URLLoader::operator()(), Sync(), and ~LoaderBase().
fileName
wxString LoaderBase::fileName protected
Definition at line 43 of file filemanager.h.
Referenced by FileLoader::operator()(), and URLLoader::operator()().
len
size_t LoaderBase::len protected
Definition at line 48 of file filemanager.h.
Referenced by GetLength(), FileLoader::operator()(), and URLLoader::operator()().
sem
wxSemaphore LoaderBase::sem private
Definition at line 33 of file filemanager.h.
wait
bool LoaderBase::wait private
Definition at line 34 of file filemanager.h.
The documentation for this class was generated from the following files:
filemanager.h
filemanager.cpp