Code::Blocks: ProjectManagerUI Class Reference
ProjectManagerUI Class Reference
#include <projectmanagerui.h>
Public Member Functions
ProjectManagerUI ()
~ProjectManagerUI ()
cbAuiNotebook * GetNotebook ()
cbTreeCtrl * GetTree ()
Retrieve a pointer to the project manager's tree (GUI).
wxTreeItemId GetTreeSelection ()
Get the selection of the project manager's tree (GUI).
void RebuildTree ()
Rebuild the project manager's tree.
void FreezeTree ()
Stop the tree control from updating.
void UnfreezeTree (bool force=false)
Le the tree control be updated again.
void UpdateActiveProject (cbProject *oldProject, cbProject *newProject, bool refresh)
void RemoveProject (cbProject *project)
void BeginLoadingWorkspace ()
void CloseWorkspace ()
void FinishLoadingProject (cbProject *project, bool newAddition, cb_unused FilesGroupsAndMasks *fgam)
void FinishLoadingWorkspace (cbProject *activeProject, const wxString &workspaceTitle)
void ShowFileInTree (ProjectFile &projectFile)
void CreateMenu (wxMenuBar *menuBar)
bool QueryCloseAllProjects ()
Checks whether all projects are saved.
bool QueryCloseProject (cbProject *project, bool dontsavefiles)
Checks whether project is saved.
bool QueryCloseWorkspace ()
Asks user to save the workspace, projects and files (Yes/No/cancel).
int AskForBuildTargetIndex (cbProject *project)
Utility function.
wxArrayInt AskForMultiBuildTargetIndex (cbProject *project)
Utility function.
void ConfigureProjectDependencies (cbProject *base)
Displays a dialog to setup project dependencies.
void CheckForExternallyModifiedProjects ()
Public Member Functions inherited from cbProjectManagerUI
virtual ~cbProjectManagerUI ()
virtual void FinishLoadingProject (cbProject *project, bool newAddition, FilesGroupsAndMasks *fileGroups)=0
Private Member Functions
void InitPane ()
void BuildTree ()
void SwitchToProjectsPage ()
Switches the management's notebook to the Projects tab.
void ShowMenu (wxTreeItemId id, const wxPoint &pt)
void CreateMenuTreeProps (wxMenu *menu, bool popup)
void DoOpenFile (ProjectFile *pf, const wxString &filename)
void DoOpenSelectedFile ()
void RemoveFilesRecursively (wxTreeItemId &sel_id)
void OpenFilesRecursively (wxTreeItemId &sel_id)
void OnTabContextMenu (wxAuiNotebookEvent &event)
void OnTabPosition (wxCommandEvent &event)
void OnProjectFileActivated (wxTreeEvent &event)
void OnExecParameters (wxCommandEvent &event)
void OnTreeItemRightClick (wxTreeEvent &event)
void OnTreeBeginDrag (wxTreeEvent &event)
void OnTreeEndDrag (wxTreeEvent &event)
void OnRightClick (wxCommandEvent &event)
void OnRenameWorkspace (wxCommandEvent &event)
void OnSaveWorkspace (wxCommandEvent &event)
void OnSaveAsWorkspace (wxCommandEvent &event)
void OnCloseWorkspace (wxCommandEvent &event)
void OnSetActiveProject (wxCommandEvent &event)
void OnAddFilesToProjectRecursively (wxCommandEvent &event)
void OnAddFileToProject (wxCommandEvent &event)
void OnRemoveFileFromProject (wxCommandEvent &event)
void OnRenameFile (wxCommandEvent &event)
void OnSaveProject (wxCommandEvent &event)
void OnCloseProject (wxCommandEvent &event)
void OnSaveFile (wxCommandEvent &event)
void OnCloseFile (wxCommandEvent &event)
void OnOpenFile (wxCommandEvent &event)
void OnOpenFolderFiles (wxCommandEvent &event)
void OnOpenWith (wxCommandEvent &event)
void OnProperties (wxCommandEvent &event)
void OnFileOptions (wxCommandEvent &event)
void OnNotes (wxCommandEvent &event)
void OnGotoFile (wxCommandEvent &event)
void OnViewCategorize (wxCommandEvent &event)
void OnViewUseFolders (wxCommandEvent &event)
void OnViewHideFolderName (wxCommandEvent &event)
void OnViewFileMasks (wxCommandEvent &event)
void OnFindFile (wxCommandEvent &event)
wxArrayString ListNodes (wxTreeItemId node) const
void OnBeginEditNode (wxTreeEvent &event)
void OnEndEditNode (wxTreeEvent &event)
void OnAddVirtualFolder (wxCommandEvent &event)
void OnDeleteVirtualFolder (wxCommandEvent &event)
void OnRenameVirtualFolder (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void OnIdle (wxIdleEvent &event)
void OnKeyDown (wxTreeEvent &event)
void MoveProjectUp (cbProject *project, bool warpAround=false)
Move a project up in the project manager tree.
void MoveProjectDown (cbProject *project, bool warpAround=false)
Move a project down in the project manager tree.
void BuildProjectTree (cbProject *project, cbTreeCtrl *tree, const wxTreeItemId &root, int ptvs, FilesGroupsAndMasks *fgam)
(Re)build the project tree.
Private Attributes
cbAuiNotebook * m_pNotebook
cbTreeCtrl * m_pTree
wxTreeItemId m_TreeRoot
wxImageList * m_pImages
int m_TreeVisualState
int m_TreeFreezeCounter
wxArrayTreeItemIds m_DraggingSelection
wxTreeItemId m_RightClickItem
bool m_isCheckingForExternallyModifiedProjects
Detailed Description
Definition at line 17 of file projectmanagerui.h.
Constructor & Destructor Documentation
ProjectManagerUI()
ProjectManagerUI::ProjectManagerUI ()
Definition at line 192 of file projectmanagerui.cpp.
References _(), _T, Manager::Get(), Manager::GetAppWindow(), wxSystemSettings::GetColour(), Manager::GetColourManager(), Manager::GetConfigManager(), ptvsCategorize, ptvsHideFolderName, ptvsNone, ptvsUseFolders, ConfigManager::ReadBool(), ColourManager::RegisterColour(), ConfigManager::Write(), wxDefaultPosition, wxDefaultSize, wxSYS_COLOUR_GRAYTEXT, and wxT.
~ProjectManagerUI()
ProjectManagerUI::~ProjectManagerUI ()
Definition at line 228 of file projectmanagerui.cpp.
References m_pImages, and m_pNotebook.
Member Function Documentation
AskForBuildTargetIndex()
int ProjectManagerUI::AskForBuildTargetIndex (cbProject * project) virtual
Utility function.
Displays a single selection list of a project's build targets to choose from.
Parameters
project The project to use. If NULL, the active project is used.
Returns
The selected build target's index, or -1 if no build target was selected.
Implements cbProjectManagerUI.
Definition at line 2499 of file projectmanagerui.cpp.
References _(), wxArrayString::Add(), cbGetSingleChoiceIndex(), Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), Manager::GetProjectManager(), CompileTargetBase::GetTitle(), and m_pTree.
Referenced by GetTree().
AskForMultiBuildTargetIndex()
wxArrayInt ProjectManagerUI::AskForMultiBuildTargetIndex (cbProject * project) virtual
Utility function.
Displays a multiple selection list of a project's build targets to choose from.
Parameters
project The project to use. If NULL, the active project is used.
Returns
An integer array containing the selected build targets indices. This array will be empty if no build targets were selected.
Implements cbProjectManagerUI.
Definition at line 2517 of file projectmanagerui.cpp.
References _(), wxArrayString::Add(), Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), Manager::GetProjectManager(), MultiSelectDlg::GetSelectedIndices(), CompileTargetBase::GetTitle(), PlaceWindow(), wxDialog::ShowModal(), and wxID_OK.
Referenced by GetTree().
BeginLoadingWorkspace()
void ProjectManagerUI::BeginLoadingWorkspace () virtual
Implements cbProjectManagerUI.
Definition at line 406 of file projectmanagerui.cpp.
References _(), wxTreeCtrl::AppendItem(), wxTreeCtrl::Expand(), FreezeTree(), wxTreeCtrl::GetRootItem(), m_pTree, and UnfreezeTree().
Referenced by GetTree().
BuildProjectTree()
void ProjectManagerUI::BuildProjectTree (cbProject * project, cbTreeCtrl * tree, const wxTreeItemId & root, int ptvs, FilesGroupsAndMasks * fgam) private
(Re)build the project tree.
Parameters
tree The wxTreeCtrl to use.
root The tree item to use as root. The project is built as a child of this item.
ptvs The visual style of the project tree
fgam If not NULL, use these file groups and masks for virtual folders.
Definition at line 3180 of file projectmanagerui.cpp.
References _(), _T, wxFile::Access(), wxTreeCtrl::AppendItem(), cbProject::AppendUniqueVirtualFolder(), ProjectFile::AutoGeneratedBy(), wxString::c_str(), cbC2U(), ProjectFile::compile, LogManager::DebugLogError(), wxTreeCtrl::Delete(), wxTreeCtrl::Expand(), F(), ProjectFile::file, cbProjectTreeImages::FolderIconIndex(), FileTreeData::ftdkFile, FileTreeData::ftdkFolder, FileTreeData::ftdkProject, FileTreeData::ftdkVirtualFolder, FileTreeData::ftdkVirtualGroup, Manager::Get(), wxTreeCtrl::GetChildrenCount(), wxArrayString::GetCount(), CompileTargetBase::GetFilename(), cbProject::GetFilesList(), ProjectFile::GetFileState(), wxFileName::GetFullName(), wxFileName::GetFullPath(), FilesGroupsAndMasks::GetGroupName(), FilesGroupsAndMasks::GetGroupsCount(), Manager::GetLogManager(), cbProject::GetProjectNode(), CompileTargetBase::GetTitle(), cbProject::GetVirtualFolders(), wxString::IsEmpty(), wxString::Last(), FilesGroupsAndMasks::MatchesMask(), cbProjectTreeImages::ProjectIconIndex(), ptvsCategorize, ptvsHideFolderName, ptvsUseFolders, ProjectFile::relativeToCommonTopLevelPath, cbTreeCtrl::SetCompareFunction(), FileTreeData::SetFileIndex(), FileTreeData::SetFolder(), FileTreeData::SetProjectFile(), cbProject::SetProjectNode(), ProjectFile::SetTreeItemId(), wxStopWatch::Time(), ProjectFile::virtual_path, cbProjectTreeImages::VirtualFolderIconIndex(), and wxFile::write.
Referenced by FinishLoadingProject(), GetTree(), and RebuildTree().
BuildTree()
void ProjectManagerUI::BuildTree () private
Definition at line 245 of file projectmanagerui.cpp.
References _T, wxImageList::Add(), cbLoadBitmap(), m_pImages, m_pNotebook, m_pTree, ConfigManager::ReadDataPath(), wxTreeCtrl::SetImageList(), wxBITMAP_TYPE_PNG, and wxEmptyString.
Referenced by GetTree(), and InitPane().
CheckForExternallyModifiedProjects()
void ProjectManagerUI::CheckForExternallyModifiedProjects ()
Definition at line 2547 of file projectmanagerui.cpp.
References _(), _T, wxArrayString::Add(), wxString::AfterLast(), wxTreeCtrl::AppendItem(), cbProject::AppendUniqueVirtualFolder(), wxString::BeforeFirst(), wxString::c_str(), cbEVT_PROJECT_OPTIONS_CHANGED, cbMessageBox(), wxString::CmpNoCase(), crAll, crCancel, crNo, crYes, wxTreeCtrl::Delete(), wxTreeCtrl::Expand(), wxString::Find(), wxString::First(), cbProjectTreeImages::FolderIconIndex(), FileTreeData::ftdkFile, FileTreeData::ftdkFolder, FileTreeData::ftdkProject, FileTreeData::ftdkVirtualFolder, Manager::Get(), wxString::GetChar(), ColourManager::GetColour(), Manager::GetColourManager(), cbProject::GetCommonTopLevelPath(), wxArrayString::GetCount(), CompileTargetBase::GetFilename(), cbProject::GetFilesList(), wxTreeCtrl::GetFirstChild(), FileTreeData::GetFolder(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetItemImage(), wxTreeCtrl::GetItemParent(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetItemTextColour(), FileTreeData::GetKind(), cbProject::GetLastModificationTime(), Manager::GetLogManager(), wxTreeCtrl::GetNextChild(), wxFileName::GetPathSeparator(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), Manager::GetProjectManager(), cbProject::GetProjectNode(), ProjectManager::GetProjects(), wxTreeCtrl::GetRootItem(), ProjectManager::GetUI(), cbProject::GetVirtualFolders(), wxArrayString::Index(), wxTreeCtrl::InsertItem(), wxString::IsEmpty(), wxTreeCtrl::IsExpanded(), wxTreeItemId::IsOk(), wxString::IsSameAs(), wxTreeCtrl::ItemHasChildren(), wxString::Last(), wxString::Left(), wxString::Length(), LogManager::Log(), m_isCheckingForExternallyModifiedProjects, wxString::Matches(), wxString::Mid(), PlaceWindow(), wxString::Prepend(), wxString::Printf(), Manager::ProcessEvent(), cbProjectManagerUI::RebuildTree(), ProjectManager::ReloadProject(), wxString::Remove(), wxString::RemoveLast(), cbProject::RemoveVirtualFolders(), wxString::Replace(), cbProject::ReplaceVirtualFolder(), wxString::Right(), HTMLTags::sep, FileTreeData::SetFolder(), wxTreeCtrl::SetItemTextColour(), FileTreeData::SetKind(), cbProject::SetModified(), FileTreeData::SetProjectFile(), cbProject::SetVirtualFolders(), wxDialog::ShowModal(), wxTreeCtrl::SortChildren(), wxString::StartsWith(), cbProject::Touch(), ProjectFile::virtual_path, cbProjectTreeImages::VirtualFolderIconIndex(), wxICON_ERROR, wxICON_WARNING, wxID_OK, wxNOT_FOUND, wxOK, and wxT.
Referenced by GetTree().
CloseWorkspace()
void ProjectManagerUI::CloseWorkspace () virtual
Implements cbProjectManagerUI.
Definition at line 414 of file projectmanagerui.cpp.
References _(), Manager::IsAppShuttingDown(), m_pTree, m_TreeRoot, RebuildTree(), and wxTreeCtrl::SetItemText().
Referenced by GetTree().
ConfigureProjectDependencies()
void ProjectManagerUI::ConfigureProjectDependencies (cbProject * base) virtual
Displays a dialog to setup project dependencies.
Parameters
base The project to setup its dependencies. Can be NULL (default) because there's a project selection combo in the dialog.
Implements cbProjectManagerUI.
Definition at line 2540 of file projectmanagerui.cpp.
References Manager::Get(), PlaceWindow(), and wxDialog::ShowModal().
Referenced by GetTree().
CreateMenu()
void ProjectManagerUI::CreateMenu (wxMenuBar * menuBar)
Definition at line 472 of file projectmanagerui.cpp.
References _(), _T, wxMenu::Append(), wxMenu::AppendSeparator(), CreateMenuTreeProps(), wxMenuBar::FindMenu(), wxMenuBar::GetMenu(), wxMenu::GetMenuItemCount(), idMenuProjectProperties, wxMenu::Insert(), and wxID_SEPARATOR.
Referenced by GetTree().
CreateMenuTreeProps()
void ProjectManagerUI::CreateMenuTreeProps (wxMenu * menu, bool popup) private
Definition at line 510 of file projectmanagerui.cpp.
References _(), _T, wxMenu::Append(), wxMenu::AppendCheckItem(), wxMenu::AppendSeparator(), wxMenu::Check(), wxMenu::Enable(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::ReadBool(), and ConfigManager::Write().
Referenced by CreateMenu(), GetTree(), and ShowMenu().
DoOpenFile()
void ProjectManagerUI::DoOpenFile (ProjectFile * pf, const wxString & filename) private
Definition at line 755 of file projectmanagerui.cpp.
References _(), EditorBase::Activate(), wxString::c_str(), cbMessageBox(), wxFileName::FileExists(), FileTypeOf(), ftHeader, ftSource, ftTemplateSource, fvsMissing, Manager::Get(), Manager::GetEditorManager(), Manager::GetLogManager(), PluginManager::GetMIMEHandlerForFile(), PluginManager::GetPluginInfo(), Manager::GetPluginManager(), EditorBase::IsBuiltinEditor(), EditorManager::IsOpen(), LogManager::LogError(), cbMimePlugin::OpenFile(), wxString::Printf(), ProjectFile::SetFileState(), and PluginInfo::title.
Referenced by DoOpenSelectedFile(), GetTree(), OnFindFile(), OnGotoFile(), and OpenFilesRecursively().
DoOpenSelectedFile()
void ProjectManagerUI::DoOpenSelectedFile () private
Definition at line 815 of file projectmanagerui.cpp.
References DoOpenFile(), wxTreeCtrl::GetItemData(), GetTreeSelection(), wxTreeItemId::IsOk(), and m_pTree.
Referenced by GetTree(), OnOpenFile(), and OnProjectFileActivated().
FinishLoadingProject()
void ProjectManagerUI::FinishLoadingProject (cbProject * project, bool newAddition, cb_unused FilesGroupsAndMasks * fgam)
Definition at line 424 of file projectmanagerui.cpp.
References BuildProjectTree(), wxTreeCtrl::Expand(), Manager::Get(), ProjectManager::GetFilesGroupsAndMasks(), Manager::GetProjectManager(), cbProject::GetProjectNode(), m_pTree, m_TreeRoot, m_TreeVisualState, and RebuildTree().
Referenced by GetTree().
FinishLoadingWorkspace()
void ProjectManagerUI::FinishLoadingWorkspace (cbProject * activeProject, const wxString & workspaceTitle) virtual
Implements cbProjectManagerUI.
Definition at line 437 of file projectmanagerui.cpp.
References wxTreeCtrl::Expand(), cbProject::GetProjectNode(), m_pTree, m_TreeRoot, RebuildTree(), wxTreeCtrl::SetItemText(), and UnfreezeTree().
Referenced by GetTree().
FreezeTree()
void ProjectManagerUI::FreezeTree () virtual
Stop the tree control from updating.
Note
This operation is accumulative. This means you have to call UnfreezeTree() as many times as you 've called FreezeTree() for the tree control to un-freeze (except if you call UnfreezeTree(true)).
Implements cbProjectManagerUI.
Definition at line 344 of file projectmanagerui.cpp.
References m_pTree, and m_TreeFreezeCounter.
Referenced by BeginLoadingWorkspace(), GetTree(), and RebuildTree().
GetNotebook()
cbAuiNotebook* ProjectManagerUI::GetNotebook () inline virtual
Implements cbProjectManagerUI.
Definition at line 23 of file projectmanagerui.h.
References m_pNotebook.
GetTree()
cbTreeCtrl* ProjectManagerUI::GetTree () inline virtual
Retrieve a pointer to the project manager's tree (GUI).
Returns
A pointer to a wxTreeCtrl window.
Implements cbProjectManagerUI.
Definition at line 28 of file projectmanagerui.h.
References AskForBuildTargetIndex(), AskForMultiBuildTargetIndex(), BeginLoadingWorkspace(), BuildProjectTree(), BuildTree(), CheckForExternallyModifiedProjects(), CloseWorkspace(), ConfigureProjectDependencies(), CreateMenu(), CreateMenuTreeProps(), DoOpenFile(), DoOpenSelectedFile(), FinishLoadingProject(), FinishLoadingWorkspace(), FreezeTree(), GetTreeSelection(), InitPane(), ListNodes(), m_pTree, MoveProjectDown(), MoveProjectUp(), OnAddFilesToProjectRecursively(), OnAddFileToProject(), OnAddVirtualFolder(), OnBeginEditNode(), OnCloseFile(), OnCloseProject(), OnCloseWorkspace(), OnDeleteVirtualFolder(), OnEndEditNode(), OnExecParameters(), OnFileOptions(), OnFindFile(), OnGotoFile(), OnIdle(), OnKeyDown(), OnNotes(), OnOpenFile(), OnOpenFolderFiles(), OnOpenWith(), OnProjectFileActivated(), OnProperties(), OnRemoveFileFromProject(), OnRenameFile(), OnRenameVirtualFolder(), OnRenameWorkspace(), OnRightClick(), OnSaveAsWorkspace(), OnSaveFile(), OnSaveProject(), OnSaveWorkspace(), OnSetActiveProject(), OnTabContextMenu(), OnTabPosition(), OnTreeBeginDrag(), OnTreeEndDrag(), OnTreeItemRightClick(), OnUpdateUI(), OnViewCategorize(), OnViewFileMasks(), OnViewHideFolderName(), OnViewUseFolders(), OpenFilesRecursively(), QueryCloseAllProjects(), QueryCloseProject(), QueryCloseWorkspace(), RebuildTree(), RemoveFilesRecursively(), RemoveProject(), ShowFileInTree(), ShowMenu(), SwitchToProjectsPage(), UnfreezeTree(), and UpdateActiveProject().
GetTreeSelection()
wxTreeItemId ProjectManagerUI::GetTreeSelection () virtual
Get the selection of the project manager's tree (GUI).
This must be used instead of tree->GetSelection() because the tree has the wxTR_MULTIPLE style. This usually returns the first item in the selection list, but if there is a right-click popup menu then the user may have selected several items and right-clicked on one, so return the right-click item instead. of the first
Returns
A wxTreeItemId of the selected tree item.
Implements cbProjectManagerUI.
Definition at line 389 of file projectmanagerui.cpp.
References wxTreeCtrl::GetSelections(), wxTreeItemId::IsOk(), m_pTree, and m_RightClickItem.
Referenced by DoOpenSelectedFile(), GetTree(), OnAddFilesToProjectRecursively(), OnAddFileToProject(), OnAddVirtualFolder(), OnCloseFile(), OnDeleteVirtualFolder(), OnFindFile(), OnOpenFolderFiles(), OnOpenWith(), OnProperties(), OnRemoveFileFromProject(), OnRenameFile(), OnRenameVirtualFolder(), OnSaveFile(), OnSaveProject(), and OnSetActiveProject().
InitPane()
void ProjectManagerUI::InitPane () private
Definition at line 235 of file projectmanagerui.cpp.
References _(), cbAuiNotebook::AddPage(), BuildTree(), Manager::IsAppShuttingDown(), m_pNotebook, and m_pTree.
Referenced by GetTree().
ListNodes()
wxArrayString ProjectManagerUI::ListNodes (wxTreeItemId node) const private
Definition at line 2002 of file projectmanagerui.cpp.
References wxArrayString::Add(), wxArrayString::GetCount(), wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetNextChild(), wxTreeItemId::IsOk(), wxTreeCtrl::ItemHasChildren(), wxArrayString::Last(), m_pTree, and wxT.
Referenced by GetTree(), and OnFindFile().
MoveProjectDown()
void ProjectManagerUI::MoveProjectDown (cbProject * project, bool warpAround = false) private
Move a project down in the project manager tree.
This effectively re-orders the projects build order.
Parameters
project The project to move down.
warpAround If true and the project is at the bottom of the list order, then it wraps and goes to the top of the list.
Definition at line 2385 of file projectmanagerui.cpp.
References cbAssert, Manager::Get(), Manager::GetProjectManager(), cbProject::GetProjectNode(), ProjectManager::GetProjects(), ProjectManager::GetWorkspace(), wxTreeItemId::IsOk(), m_pTree, RebuildTree(), wxTreeCtrl::SelectItem(), cbWorkspace::SetModified(), and wxNOT_FOUND.
Referenced by GetTree(), and OnSetActiveProject().
MoveProjectUp()
void ProjectManagerUI::MoveProjectUp (cbProject * project, bool warpAround = false) private
Move a project up in the project manager tree.
This effectively re-orders the projects build order.
Parameters
project The project to move up.
warpAround If true and the project is at the top of the list order, then it wraps and goes to the bottom of the list.
Definition at line 2355 of file projectmanagerui.cpp.
References cbAssert, Manager::Get(), Manager::GetProjectManager(), cbProject::GetProjectNode(), ProjectManager::GetProjects(), ProjectManager::GetWorkspace(), wxTreeItemId::IsOk(), m_pTree, RebuildTree(), wxTreeCtrl::SelectItem(), cbWorkspace::SetModified(), and wxNOT_FOUND.
Referenced by GetTree(), and OnSetActiveProject().
OnAddFilesToProjectRecursively()
void ProjectManagerUI::OnAddFilesToProjectRecursively (wxCommandEvent & event) private
Definition at line 1197 of file projectmanagerui.cpp.
References _(), _T, ProjectManager::AddMultipleFilesToProject(), ChooseDirectory(), Manager::Get(), ProjectManager::GetActiveProject(), wxDir::GetAllFiles(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTargetsCount(), wxArrayString::GetCount(), FilesGroupsAndMasks::GetFileMasks(), ProjectManager::GetFilesGroupsAndMasks(), FilesGroupsAndMasks::GetGroupsCount(), wxTreeCtrl::GetItemData(), Manager::GetProjectManager(), MultiSelectDlg::GetSelectedStrings(), GetTreeSelection(), wxString::IsEmpty(), wxTreeItemId::IsOk(), m_pTree, PlaceWindow(), RebuildTree(), wxArrayString::RemoveAt(), wxDialog::ShowModal(), wxDIR_DIRS, wxDIR_FILES, wxDirExists(), wxEmptyString, and wxID_OK.
Referenced by GetTree().
OnAddFileToProject()
void ProjectManagerUI::OnAddFileToProject (wxCommandEvent & event) private
Definition at line 1287 of file projectmanagerui.cpp.
References _(), wxArrayString::Add(), ProjectManager::AddMultipleFilesToProject(), FileTreeData::ftdkFile, FileTreeData::ftdkFolder, FileTreeData::ftdkProject, FileTreeData::ftdkUndefined, FileTreeData::ftdkVirtualFolder, FileTreeData::ftdkVirtualGroup, Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetAppWindow(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTargetsCount(), cbProject::GetFilesList(), FileFilters::GetFilterString(), wxTreeCtrl::GetFirstChild(), FileFilters::GetIndexForFilterAll(), wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), wxTreeCtrl::GetNextChild(), wxFileDialog::GetPaths(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), Manager::GetProjectManager(), GetTreeSelection(), wxTreeItemId::IsOk(), m_pTree, PlaceWindow(), RebuildTree(), ProjectFile::relativeFilename, wxFileDialog::SetFilterIndex(), wxFileDialog::ShowModal(), wxDirExists(), wxEmptyString, wxFD_FILE_MUST_EXIST, wxFD_MULTIPLE, wxFD_OPEN, and wxID_OK.
Referenced by GetTree().
OnAddVirtualFolder()
void ProjectManagerUI::OnAddVirtualFolder (wxCommandEvent & event) private
Definition at line 2161 of file projectmanagerui.cpp.
References _(), cbGetTextFromUser(), wxTreeCtrl::GetItemData(), FileTreeData::GetProject(), GetTreeSelection(), wxString::IsEmpty(), wxTreeItemId::IsOk(), and m_pTree.
Referenced by GetTree().
OnBeginEditNode()
void ProjectManagerUI::OnBeginEditNode (wxTreeEvent & event) private
Definition at line 2232 of file projectmanagerui.cpp.
References FileTreeData::ftdkVirtualFolder, wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), and m_pTree.
Referenced by GetTree().
OnCloseFile()
void ProjectManagerUI::OnCloseFile (wxCommandEvent & event) private
Definition at line 1549 of file projectmanagerui.cpp.
References EditorManager::Close(), Manager::Get(), Manager::GetEditorManager(), wxTreeCtrl::GetItemData(), GetTreeSelection(), wxTreeItemId::IsOk(), and m_pTree.
Referenced by GetTree().
OnCloseProject()
void ProjectManagerUI::OnCloseProject (wxCommandEvent & event) private
Definition at line 1496 of file projectmanagerui.cpp.
References ProjectManager::CloseProject(), FileTreeData::ftdkProject, Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetAppWindow(), cbProject::GetCurrentlyCompilingTarget(), wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), FileTreeData::GetProject(), Manager::GetProjectManager(), ProjectManager::GetProjects(), wxTreeCtrl::GetSelections(), ProjectManager::IsLoadingProject(), m_pTree, ProjectManager::SetProject(), and wxBell().
Referenced by GetTree().
OnCloseWorkspace()
void ProjectManagerUI::OnCloseWorkspace (wxCommandEvent & event) private
Definition at line 1134 of file projectmanagerui.cpp.
References ProjectManager::CloseWorkspace(), Manager::Get(), Manager::GetProjectManager(), and ProjectManager::GetWorkspace().
Referenced by GetTree().
OnDeleteVirtualFolder()
void ProjectManagerUI::OnDeleteVirtualFolder (wxCommandEvent & event) private
Definition at line 2183 of file projectmanagerui.cpp.
References wxTreeCtrl::GetItemData(), FileTreeData::GetProject(), GetTreeSelection(), wxTreeItemId::IsOk(), m_pTree, and RebuildTree().
Referenced by GetTree().
OnEndEditNode()
void ProjectManagerUI::OnEndEditNode (wxTreeEvent & event) private
Definition at line 2255 of file projectmanagerui.cpp.
References wxTreeEvent::GetItem(), wxTreeCtrl::GetItemData(), FileTreeData::GetProject(), and m_pTree.
Referenced by GetTree().
OnExecParameters()
void ProjectManagerUI::OnExecParameters (wxCommandEvent & event) private
Definition at line 1028 of file projectmanagerui.cpp.
References Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetProjectManager(), and cbProject::SelectTarget().
Referenced by GetTree().
OnFileOptions()
void ProjectManagerUI::OnFileOptions (wxCommandEvent & event) private
Definition at line 1719 of file projectmanagerui.cpp.
References ProjectFile::compile, FileTreeData::ftdkFile, wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), ProjectFile::GetParentProject(), FileTreeData::GetProjectFile(), wxTreeCtrl::GetSelections(), ProjectFile::link, m_pTree, and RebuildTree().
Referenced by GetTree().
OnFindFile()
void ProjectManagerUI::OnFindFile (wxCommandEvent & event) private
Definition at line 2022 of file projectmanagerui.cpp.
References _(), wxArrayString::Add(), GotoFile::AddControlBelowList(), DoOpenFile(), FileTreeData::ftdkProject, Manager::Get(), Manager::GetConfigManager(), CompileTargetBase::GetFilename(), wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetItemText(), FileTreeData::GetKind(), wxTreeCtrl::GetNextChild(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), Manager::GetProjectManager(), ProjectManager::GetProjects(), GotoFile::GetSelection(), CompileTargetBase::GetTitle(), GetTreeSelection(), ProjectManager::GetWorkspace(), wxCheckBox::IsChecked(), wxArrayString::IsEmpty(), wxTreeItemId::IsOk(), wxString::length(), wxString::Length(), ListNodes(), m_pTree, wxString::Mid(), PlaceWindow(), ConfigManager::ReadBool(), wxTreeCtrl::SelectItem(), ProjectManager::SetProject(), wxCheckBox::SetValue(), wxDialog::ShowModal(), wxString::StartsWith(), wxTreeCtrl::UnselectAll(), ConfigManager::Write(), wxID_ANY, wxID_OK, wxNOT_FOUND, and wxT.
Referenced by GetTree().
OnGotoFile()
void ProjectManagerUI::OnGotoFile (wxCommandEvent & event) private
Definition at line 1811 of file projectmanagerui.cpp.
References _(), LogManager::DebugLog(), DoOpenFile(), ProjectFile::file, Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetFilesList(), wxFileName::GetFullPath(), Manager::GetLogManager(), ProjectFile::GetParentProject(), Manager::GetProjectManager(), ProjectManager::GetProjects(), GotoFile::GetSelection(), CompileTargetBase::GetTitle(), wxString::length(), PlaceWindow(), ProjectFile::relativeFilename, wxDialog::ShowModal(), wxID_OK, and wxT.
Referenced by GetTree().
OnIdle()
void ProjectManagerUI::OnIdle (wxIdleEvent & event) private
Definition at line 2280 of file projectmanagerui.cpp.
Referenced by GetTree().
OnKeyDown()
void ProjectManagerUI::OnKeyDown (wxTreeEvent & event) private
Definition at line 2337 of file projectmanagerui.cpp.
References Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetCurrentlyCompilingTarget(), wxKeyEvent::GetKeyCode(), Manager::GetProjectManager(), m_DraggingSelection, OnRemoveFileFromProject(), WXK_DELETE, and WXK_NUMPAD_DELETE.
Referenced by GetTree().
OnNotes()
void ProjectManagerUI::OnNotes (wxCommandEvent & event) private
Definition at line 1626 of file projectmanagerui.cpp.
References Manager::Get(), and Manager::GetProjectManager().
Referenced by GetTree().
OnOpenFile()
void ProjectManagerUI::OnOpenFile (wxCommandEvent & event) private
Definition at line 1562 of file projectmanagerui.cpp.
References DoOpenSelectedFile().
Referenced by GetTree().
OnOpenFolderFiles()
void ProjectManagerUI::OnOpenFolderFiles (wxCommandEvent & event) private
Definition at line 1567 of file projectmanagerui.cpp.
References _(), cbMessageBox(), FileTreeData::ftdkFolder, FileTreeData::ftdkVirtualFolder, wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), GetTreeSelection(), m_pTree, OpenFilesRecursively(), wxICON_QUESTION, wxID_YES, wxNO_DEFAULT, and wxYES_NO.
Referenced by GetTree().
OnOpenWith()
void ProjectManagerUI::OnOpenWith (wxCommandEvent & event) private
Definition at line 1591 of file projectmanagerui.cpp.
References _(), wxString::c_str(), Manager::Get(), Manager::GetEditorManager(), wxTreeCtrl::GetItemData(), Manager::GetLogManager(), PluginManager::GetMimeOffers(), Manager::GetPluginManager(), FileTreeData::GetProjectFile(), GetTreeSelection(), wxTreeItemId::IsOk(), LogManager::LogError(), m_pTree, EditorManager::Open(), cbMimePlugin::OpenFile(), and wxString::Printf().
Referenced by GetTree().
OnProjectFileActivated()
void ProjectManagerUI::OnProjectFileActivated (wxTreeEvent & event) private
Definition at line 1002 of file projectmanagerui.cpp.
References wxTreeCtrl::Collapse(), DoOpenSelectedFile(), wxTreeCtrl::Expand(), FileTreeData::ftdkFolder, FileTreeData::ftdkProject, FileTreeData::ftdkVirtualFolder, FileTreeData::ftdkVirtualGroup, Manager::Get(), ProjectManager::GetActiveProject(), wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), FileTreeData::GetProject(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), wxTreeCtrl::IsExpanded(), m_pTree, m_TreeRoot, and ProjectManager::SetProject().
Referenced by GetTree().
OnProperties()
void ProjectManagerUI::OnProperties (wxCommandEvent & event) private
Definition at line 1632 of file projectmanagerui.cpp.
References _(), _T, wxString::EndsWith(), Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetAppWindow(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), FileTreeData::GetFileIndex(), wxTreeCtrl::GetItemData(), EditorManager::GetNotebook(), wxAuiNotebook::GetPageCount(), wxAuiNotebook::GetPageToolTip(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), Manager::GetProjectManager(), CompileTargetBase::GetTitle(), GetTreeSelection(), idMenuProjectProperties, wxTreeItemId::IsOk(), m_pTree, PlaceWindow(), wxString::Replace(), wxAuiNotebook::SetPageToolTip(), and ProjectManager::SetProject().
Referenced by GetTree().
OnRemoveFileFromProject()
void ProjectManagerUI::OnRemoveFileFromProject (wxCommandEvent & event) private
Definition at line 1376 of file projectmanagerui.cpp.
References _(), _T, cbProject::BeginRemoveFiles(), wxString::c_str(), cbProject::CalculateCommonTopLevelPath(), cbMessageBox(), LogManager::DebugLog(), wxTreeCtrl::Delete(), cbProject::EndRemoveFiles(), F(), FileTreeData::ftdkFolder, FileTreeData::ftdkVirtualFolder, Manager::Get(), cbProject::GetCommonTopLevelPath(), cbProject::GetFileByFilename(), wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), Manager::GetLogManager(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), Manager::GetProjectManager(), MultiSelectDlg::GetSelectedIndices(), CompileTargetBase::GetTitle(), GetTreeSelection(), wxTreeItemId::IsOk(), m_pTree, PlaceWindow(), wxString::Printf(), RebuildTree(), ProjectManager::RemoveFileFromProject(), RemoveFilesRecursively(), wxDialog::ShowModal(), wxArrayString::Sort(), wxICON_QUESTION, wxICON_WARNING, wxID_OK, wxID_YES, wxNO_DEFAULT, and wxYES_NO.
Referenced by GetTree(), and OnKeyDown().
OnRenameFile()
void ProjectManagerUI::OnRenameFile (wxCommandEvent & event) private
Definition at line 2285 of file projectmanagerui.cpp.
References _(), ProjectFile::AutoGeneratedBy(), cbMessageBox(), ProjectFile::file, Manager::Get(), wxFileName::GetFullName(), wxTreeCtrl::GetItemData(), wxFileName::GetPath(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), GetTreeSelection(), wxTreeItemId::IsOk(), wxString::Lower(), m_pTree, PlaceWindow(), RebuildTree(), wxDialog::ShowModal(), wxBell(), wxCANCEL, wxCENTRE, wxID_OK, wxOK, and wxRenameFile().
Referenced by GetTree().
OnRenameVirtualFolder()
void ProjectManagerUI::OnRenameVirtualFolder (wxCommandEvent & event) private
Definition at line 2201 of file projectmanagerui.cpp.
References _(), _T, wxString::EndsWith(), Manager::Get(), FileTreeData::GetFolder(), wxTreeCtrl::GetItemData(), FileTreeData::GetProject(), GetTreeSelection(), wxTreeItemId::IsOk(), m_pTree, RebuildTree(), wxString::RemoveLast(), wxDialog::ShowModal(), wxCANCEL, wxCENTRE, wxID_OK, and wxOK.
Referenced by GetTree().
OnRenameWorkspace()
void ProjectManagerUI::OnRenameWorkspace (wxCommandEvent & event) private
Definition at line 1104 of file projectmanagerui.cpp.
References _(), cbGetTextFromUser(), Manager::Get(), Manager::GetProjectManager(), cbWorkspace::GetTitle(), ProjectManager::GetWorkspace(), wxString::IsEmpty(), m_pTree, m_TreeRoot, wxTreeCtrl::SetItemText(), and cbWorkspace::SetTitle().
Referenced by GetTree().
OnRightClick()
void ProjectManagerUI::OnRightClick (wxCommandEvent & event) private
Definition at line 1034 of file projectmanagerui.cpp.
References _(), wxMenu::Append(), wxMenu::AppendCheckItem(), wxMenu::AppendSeparator(), PluginManager::AskPluginsForModuleMenu(), wxMenu::Check(), wxMenu::Enable(), Manager::Get(), wxMenu::GetMenuItemCount(), Manager::GetPluginManager(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), m_pTree, m_TreeVisualState, mtProjectManager, ptvsCategorize, ptvsHideFolderName, ptvsUseFolders, and wxGetMousePosition().
Referenced by GetTree(), and ShowMenu().
OnSaveAsWorkspace()
void ProjectManagerUI::OnSaveAsWorkspace (wxCommandEvent & event) private
Definition at line 1127 of file projectmanagerui.cpp.
References _T, Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), and ProjectManager::SaveWorkspaceAs().
Referenced by GetTree().
OnSaveFile()
void ProjectManagerUI::OnSaveFile (wxCommandEvent & event) private
Definition at line 1536 of file projectmanagerui.cpp.
References Manager::Get(), Manager::GetEditorManager(), wxTreeCtrl::GetItemData(), GetTreeSelection(), wxTreeItemId::IsOk(), m_pTree, and EditorManager::Save().
Referenced by GetTree().
OnSaveProject()
void ProjectManagerUI::OnSaveProject (wxCommandEvent & event) private
Definition at line 1475 of file projectmanagerui.cpp.
References Manager::Get(), wxTreeCtrl::GetItemData(), Manager::GetProjectManager(), GetTreeSelection(), ProjectManager::IsLoadingProject(), wxTreeItemId::IsOk(), m_pTree, ProjectManager::SaveProject(), and wxBell().
Referenced by GetTree().
OnSaveWorkspace()
void ProjectManagerUI::OnSaveWorkspace (wxCommandEvent & event) private
Definition at line 1120 of file projectmanagerui.cpp.
References Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), and ProjectManager::SaveWorkspace().
Referenced by GetTree().
OnSetActiveProject()
void ProjectManagerUI::OnSetActiveProject (wxCommandEvent & event) private
Definition at line 1141 of file projectmanagerui.cpp.
References Manager::Get(), ProjectManager::GetActiveProject(), wxTreeCtrl::GetItemData(), FileTreeData::GetProject(), Manager::GetProjectManager(), ProjectManager::GetProjects(), GetTreeSelection(), wxTreeItemId::IsOk(), m_pTree, MoveProjectDown(), MoveProjectUp(), ProjectManager::SetProject(), and wxNOT_FOUND.
Referenced by GetTree().
OnTabContextMenu()
void ProjectManagerUI::OnTabContextMenu (wxAuiNotebookEvent & event) private
Definition at line 902 of file projectmanagerui.cpp.
References _(), _T, wxMenu::Append(), Manager::Get(), Manager::GetConfigManager(), and m_pNotebook.
Referenced by GetTree().
OnTabPosition()
void ProjectManagerUI::OnTabPosition (wxCommandEvent & event) private
Definition at line 913 of file projectmanagerui.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), m_pNotebook, and ConfigManager::Write().
Referenced by GetTree().
OnTreeBeginDrag()
void ProjectManagerUI::OnTreeBeginDrag (wxTreeEvent & event) private
Definition at line 926 of file projectmanagerui.cpp.
References wxTreeCtrl::GetItemData(), FileTreeData::GetProject(), wxTreeCtrl::GetSelections(), m_DraggingSelection, and m_pTree.
Referenced by GetTree().
OnTreeEndDrag()
void ProjectManagerUI::OnTreeEndDrag (wxTreeEvent & event) private
Definition at line 957 of file projectmanagerui.cpp.
References wxTreeCtrl::GetItemData(), FileTreeData::GetProject(), wxTreeItemId::IsOk(), m_DraggingSelection, and m_pTree.
Referenced by GetTree().
OnTreeItemRightClick()
void ProjectManagerUI::OnTreeItemRightClick (wxTreeEvent & event) private
Definition at line 1086 of file projectmanagerui.cpp.
References Manager::Get(), wxTreeEvent::GetItem(), Manager::GetProjectManager(), m_pTree, m_RightClickItem, wxTreeCtrl::SelectItem(), ShowMenu(), wxTreeItemId::Unset(), and wxBell().
Referenced by GetTree().
OnUpdateUI()
void ProjectManagerUI::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 2275 of file projectmanagerui.cpp.
Referenced by GetTree().
OnViewCategorize()
void ProjectManagerUI::OnViewCategorize (wxCommandEvent & event) private
Definition at line 1927 of file projectmanagerui.cpp.
References _T, Manager::Get(), Manager::GetAppFrame(), Manager::GetConfigManager(), m_TreeVisualState, ptvsCategorize, RebuildTree(), and ConfigManager::Write().
Referenced by GetTree().
OnViewFileMasks()
void ProjectManagerUI::OnViewFileMasks (wxCommandEvent & event) private
Definition at line 1990 of file projectmanagerui.cpp.
References Manager::Get(), ProjectManager::GetFilesGroupsAndMasks(), Manager::GetProjectManager(), PlaceWindow(), RebuildTree(), FilesGroupsAndMasks::Save(), wxDialog::ShowModal(), and wxID_OK.
Referenced by GetTree().
OnViewHideFolderName()
void ProjectManagerUI::OnViewHideFolderName (wxCommandEvent & event) private
Definition at line 1966 of file projectmanagerui.cpp.
References _T, Manager::Get(), Manager::GetAppFrame(), Manager::GetConfigManager(), m_TreeVisualState, ptvsHideFolderName, ptvsUseFolders, RebuildTree(), and ConfigManager::Write().
Referenced by GetTree().
OnViewUseFolders()
void ProjectManagerUI::OnViewUseFolders (wxCommandEvent & event) private
Definition at line 1942 of file projectmanagerui.cpp.
References _T, Manager::Get(), Manager::GetAppFrame(), Manager::GetConfigManager(), m_TreeVisualState, ptvsHideFolderName, ptvsUseFolders, RebuildTree(), and ConfigManager::Write().
Referenced by GetTree().
OpenFilesRecursively()
void ProjectManagerUI::OpenFilesRecursively (wxTreeItemId & sel_id) private
Definition at line 863 of file projectmanagerui.cpp.
References DoOpenFile(), FileTreeData::ftdkFile, FileTreeData::ftdkFolder, FileTreeData::ftdkVirtualFolder, wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), wxTreeCtrl::GetNextChild(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), wxTreeItemId::IsOk(), and m_pTree.
Referenced by GetTree(), and OnOpenFolderFiles().
QueryCloseAllProjects()
bool ProjectManagerUI::QueryCloseAllProjects () virtual
Checks whether all projects are saved.
If not, asks the user to save and saves accordingly.
Returns
False if the user pressed cancel. Note: calls QueryCloseProject for all projects.
Implements cbProjectManagerUI.
Definition at line 2416 of file projectmanagerui.cpp.
References Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetProjects(), and QueryCloseProject().
Referenced by GetTree(), and QueryCloseWorkspace().
QueryCloseProject()
bool ProjectManagerUI::QueryCloseProject (cbProject * proj, bool dontsavefiles) virtual
Checks whether project is saved.
If not, asks the user to save and saves accordingly.
Returns
False if the user pressed cancel. Note: By default this asks the user if he should save any unmodified files in the project.
Implements cbProjectManagerUI.
Definition at line 2432 of file projectmanagerui.cpp.
References _(), wxString::c_str(), cbMessageBox(), cbProject::GetCurrentlyCompilingTarget(), cbProject::GetModified(), CompileTargetBase::GetTitle(), Manager::IsBatchBuild(), wxString::Printf(), cbProject::QueryCloseAllFiles(), cbProject::Save(), wxCANCEL, wxICON_QUESTION, wxID_CANCEL, wxID_NO, wxID_YES, and wxYES_NO.
Referenced by GetTree(), and QueryCloseAllProjects().
QueryCloseWorkspace()
bool ProjectManagerUI::QueryCloseWorkspace () virtual
Asks user to save the workspace, projects and files (Yes/No/cancel).
If user pressed Yes, it saves accordingly.
Returns
False if the user pressed cancel; true otherwise. After this function is called and returns true, it is safe to close the workspace, all files and projects without asking the user later.
Implements cbProjectManagerUI.
Definition at line 2462 of file projectmanagerui.cpp.
References _(), _T, wxString::c_str(), cbMessageBox(), Manager::Get(), Manager::GetConfigManager(), cbWorkspace::GetModified(), Manager::GetProjectManager(), cbWorkspace::GetTitle(), ProjectManager::GetWorkspace(), cbWorkspace::IsDefault(), wxString::Printf(), QueryCloseAllProjects(), ConfigManager::ReadBool(), cbWorkspace::SaveLayout(), ProjectManager::SaveWorkspace(), wxCANCEL, wxICON_QUESTION, wxID_CANCEL, wxID_YES, and wxYES_NO.
Referenced by GetTree().
RebuildTree()
void ProjectManagerUI::RebuildTree () virtual
Rebuild the project manager's tree.
Implements cbProjectManagerUI.
Definition at line 297 of file projectmanagerui.cpp.
References _(), wxFile::Access(), wxTreeCtrl::AddRoot(), BuildProjectTree(), wxString::c_str(), wxTreeCtrl::DeleteAllItems(), wxFile::Exists(), wxTreeCtrl::Expand(), FreezeTree(), Manager::Get(), ProjectManager::GetActiveProject(), cbWorkspace::GetFilename(), ProjectManager::GetFilesGroupsAndMasks(), Manager::GetProjectManager(), ProjectManager::GetProjects(), cbWorkspace::GetTitle(), ProjectManager::GetWorkspace(), Manager::IsAppShuttingDown(), wxString::IsEmpty(), m_pTree, m_TreeRoot, m_TreeVisualState, wxTreeCtrl::SetItemBold(), UnfreezeTree(), cbProjectTreeImages::WorkspaceIconIndex(), and wxFile::write.
Referenced by CloseWorkspace(), FinishLoadingProject(), FinishLoadingWorkspace(), GetTree(), MoveProjectDown(), MoveProjectUp(), OnAddFilesToProjectRecursively(), OnAddFileToProject(), OnDeleteVirtualFolder(), OnFileOptions(), OnRemoveFileFromProject(), OnRenameFile(), OnRenameVirtualFolder(), OnViewCategorize(), OnViewFileMasks(), OnViewHideFolderName(), OnViewUseFolders(), and UpdateActiveProject().
RemoveFilesRecursively()
void ProjectManagerUI::RemoveFilesRecursively (wxTreeItemId & sel_id) private
Definition at line 828 of file projectmanagerui.cpp.
References FileTreeData::ftdkFile, FileTreeData::ftdkFolder, FileTreeData::ftdkVirtualFolder, Manager::Get(), wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetNextChild(), Manager::GetProjectManager(), wxTreeItemId::IsOk(), m_pTree, and ProjectManager::RemoveFileFromProject().
Referenced by GetTree(), and OnRemoveFileFromProject().
RemoveProject()
void ProjectManagerUI::RemoveProject (cbProject * project) virtual
Implements cbProjectManagerUI.
Definition at line 384 of file projectmanagerui.cpp.
References wxTreeCtrl::Delete(), cbProject::GetProjectNode(), and m_pTree.
Referenced by GetTree().
ShowFileInTree()
void ProjectManagerUI::ShowFileInTree (ProjectFile & projectFile) virtual
Implements cbProjectManagerUI.
Definition at line 459 of file projectmanagerui.cpp.
References wxTreeCtrl::EnsureVisible(), ProjectFile::GetTreeItemId(), wxTreeItemId::IsOk(), m_pTree, wxTreeCtrl::SelectItem(), and wxTreeCtrl::UnselectAll().
Referenced by GetTree().
ShowMenu()
void ProjectManagerUI::ShowMenu (wxTreeItemId id, const wxPoint & pt) private
Definition at line 552 of file projectmanagerui.cpp.
References _(), wxMenu::Append(), wxMenu::AppendCheckItem(), wxMenu::AppendSeparator(), wxMenu::AppendSubMenu(), PluginManager::AskPluginsForModuleMenu(), wxString::c_str(), cbMimePlugin::CanHandleFile(), wxMenu::Check(), CreateMenuTreeProps(), wxMenu::Enable(), ProjectFile::file, wxString::Format(), FileTreeData::ftdkFile, FileTreeData::ftdkFolder, FileTreeData::ftdkProject, FileTreeData::ftdkVirtualFolder, FileTreeData::ftdkVirtualGroup, fvsNormal, Manager::Get(), EditorManager::GetActiveEditor(), ProjectManager::GetActiveProject(), cbProject::GetCommonTopLevelPath(), cbProject::GetCurrentlyCompilingTarget(), Manager::GetEditorManager(), ProjectFile::GetFileState(), FileTreeData::GetFolder(), wxFileName::GetFullPath(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetItemText(), FileTreeData::GetKind(), wxMenu::GetMenuItemCount(), PluginManager::GetMimeOffers(), PluginManager::GetPluginInfo(), Manager::GetPluginManager(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), Manager::GetProjectManager(), ProjectManager::GetProjects(), CompileTargetBase::GetTitle(), ProjectManager::GetWorkspace(), EditorManager::IsOpen(), wxString::IsSameAs(), m_pTree, wxFileName::MakeRelativeTo(), mtProjectManager, OnRightClick(), wxString::Printf(), PluginInfo::title, and wxID_ANY.
Referenced by GetTree(), and OnTreeItemRightClick().
SwitchToProjectsPage()
void ProjectManagerUI::SwitchToProjectsPage () private virtual
Switches the management's notebook to the Projects tab.
Implements cbProjectManagerUI.
Definition at line 448 of file projectmanagerui.cpp.
References cbEVT_SHOW_DOCK_WINDOW, Manager::Get(), wxAuiNotebook::GetPageIndex(), m_pNotebook, m_pTree, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxAuiNotebook::SetSelection(), and wxNOT_FOUND.
Referenced by GetTree().
UnfreezeTree()
void ProjectManagerUI::UnfreezeTree (bool force = false) virtual
Le the tree control be updated again.
Parameters
force If true the tree control is forced to un-freeze. Else it depends on freeze-unfreeze balance (see note).
Note
This operation is accumulative. This means you have to call UnfreezeTree() as many times as you 've called FreezeTree() for the tree control to un-freeze (except if you call UnfreezeTree(true)).
Implements cbProjectManagerUI.
Definition at line 353 of file projectmanagerui.cpp.
References m_pTree, and m_TreeFreezeCounter.
Referenced by BeginLoadingWorkspace(), FinishLoadingWorkspace(), GetTree(), and RebuildTree().
UpdateActiveProject()
void ProjectManagerUI::UpdateActiveProject (cbProject * oldProject, cbProject * newProject, bool refresh) virtual
Implements cbProjectManagerUI.
Definition at line 365 of file projectmanagerui.cpp.
References wxTreeCtrl::EnsureVisible(), cbProject::GetProjectNode(), m_pTree, RebuildTree(), and wxTreeCtrl::SetItemBold().
Referenced by GetTree().
Member Data Documentation
m_DraggingSelection
wxArrayTreeItemIds ProjectManagerUI::m_DraggingSelection private
Definition at line 145 of file projectmanagerui.h.
Referenced by OnKeyDown(), OnTreeBeginDrag(), and OnTreeEndDrag().
m_isCheckingForExternallyModifiedProjects
bool ProjectManagerUI::m_isCheckingForExternallyModifiedProjects private
Definition at line 147 of file projectmanagerui.h.
Referenced by CheckForExternallyModifiedProjects().
m_pImages
wxImageList* ProjectManagerUI::m_pImages private
Definition at line 142 of file projectmanagerui.h.
Referenced by BuildTree(), and ~ProjectManagerUI().
m_pNotebook
cbAuiNotebook* ProjectManagerUI::m_pNotebook private
Definition at line 139 of file projectmanagerui.h.
Referenced by BuildTree(), GetNotebook(), InitPane(), OnTabContextMenu(), OnTabPosition(), SwitchToProjectsPage(), and ~ProjectManagerUI().
m_pTree
cbTreeCtrl* ProjectManagerUI::m_pTree private
Definition at line 140 of file projectmanagerui.h.
Referenced by AskForBuildTargetIndex(), BeginLoadingWorkspace(), BuildTree(), CloseWorkspace(), DoOpenSelectedFile(), FinishLoadingProject(), FinishLoadingWorkspace(), FreezeTree(), GetTree(), GetTreeSelection(), InitPane(), ListNodes(), MoveProjectDown(), MoveProjectUp(), OnAddFilesToProjectRecursively(), OnAddFileToProject(), OnAddVirtualFolder(), OnBeginEditNode(), OnCloseFile(), OnCloseProject(), OnDeleteVirtualFolder(), OnEndEditNode(), OnFileOptions(), OnFindFile(), OnOpenFolderFiles(), OnOpenWith(), OnProjectFileActivated(), OnProperties(), OnRemoveFileFromProject(), OnRenameFile(), OnRenameVirtualFolder(), OnRenameWorkspace(), OnRightClick(), OnSaveFile(), OnSaveProject(), OnSetActiveProject(), OnTreeBeginDrag(), OnTreeEndDrag(), OnTreeItemRightClick(), OpenFilesRecursively(), RebuildTree(), RemoveFilesRecursively(), RemoveProject(), ShowFileInTree(), ShowMenu(), SwitchToProjectsPage(), UnfreezeTree(), and UpdateActiveProject().
m_RightClickItem
wxTreeItemId ProjectManagerUI::m_RightClickItem private
Definition at line 146 of file projectmanagerui.h.
Referenced by GetTreeSelection(), and OnTreeItemRightClick().
m_TreeFreezeCounter
int ProjectManagerUI::m_TreeFreezeCounter private
Definition at line 144 of file projectmanagerui.h.
Referenced by FreezeTree(), and UnfreezeTree().
m_TreeRoot
wxTreeItemId ProjectManagerUI::m_TreeRoot private
Definition at line 141 of file projectmanagerui.h.
Referenced by CloseWorkspace(), FinishLoadingProject(), FinishLoadingWorkspace(), OnProjectFileActivated(), OnRenameWorkspace(), and RebuildTree().
m_TreeVisualState
int ProjectManagerUI::m_TreeVisualState private
Definition at line 143 of file projectmanagerui.h.
Referenced by FinishLoadingProject(), OnRightClick(), OnViewCategorize(), OnViewHideFolderName(), OnViewUseFolders(), and RebuildTree().
The documentation for this class was generated from the following files:
projectmanagerui.h
projectmanagerui.cpp