Code::Blocks: cbFileDropTarget Class Reference
cbFileDropTarget Class Reference
Public Member Functions
cbFileDropTarget (MainFrame *frame)
bool OnDropFiles (wxCoord x, wxCoord y, const wxArrayString &filenames) override
Public Member Functions inherited from wxFileDropTarget
wxFileDropTarget ()
virtual bool OnDrop (wxCoord x, wxCoord y)
Public Member Functions inherited from wxDropTarget
wxDropTarget (wxDataObject *data=NULL)
virtual ~wxDropTarget ()
virtual bool GetData ()
virtual wxDragResult OnData (wxCoord x, wxCoord y, wxDragResult defResult)=0
virtual wxDragResult OnDragOver (wxCoord x, wxCoord y, wxDragResult defResult)
virtual wxDragResult OnEnter (wxCoord x, wxCoord y, wxDragResult defResult)
virtual void OnLeave ()
wxDataObject * GetDataObject () const
void SetDataObject (wxDataObject *data)
void SetDefaultAction (wxDragResult action)
wxDragResult GetDefaultAction ()
Private Attributes
MainFrame * m_frame
Detailed Description
Definition at line 74 of file main.cpp.
Constructor & Destructor Documentation
cbFileDropTarget()
cbFileDropTarget::cbFileDropTarget (MainFrame * frame) inline
Definition at line 77 of file main.cpp.
Referenced by MainFrame::CreateIDE(), MainFrame::MainFrame(), and MainFrame::SetupGUILogging().
Member Function Documentation
OnDropFiles()
bool cbFileDropTarget::OnDropFiles (wxCoord x, wxCoord y, const wxArrayString & filenames) inline override virtual
Implements wxFileDropTarget.
Definition at line 78 of file main.cpp.
References m_frame, and MainFrame::OnDropFiles().
Referenced by MainFrame::DoOnFileOpen().
Member Data Documentation
m_frame
MainFrame* cbFileDropTarget::m_frame private
Definition at line 84 of file main.cpp.
Referenced by OnDropFiles().
The documentation for this class was generated from the following file:
main.cpp