Code::Blocks: EditBreakpointDlg Class Reference
EditBreakpointDlg Class Reference
#include <editbreakpointdlg.h>
Public Member Functions
EditBreakpointDlg (const DebuggerBreakpoint &breakpoint, wxWindow *parent=0)
virtual ~EditBreakpointDlg ()
const DebuggerBreakpoint & GetBreakpoint () const
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Member Functions
void OnUpdateUI (wxUpdateUIEvent &event)
void EndModal (int retCode)
Protected Attributes
DebuggerBreakpoint m_breakpoint
Detailed Description
Definition at line 12 of file editbreakpointdlg.h.
Constructor & Destructor Documentation
EditBreakpointDlg()
EditBreakpointDlg::EditBreakpointDlg (const DebuggerBreakpoint & breakpoint, wxWindow * parent = 0)
Definition at line 29 of file editbreakpointdlg.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadObject().
~EditBreakpointDlg()
EditBreakpointDlg::~EditBreakpointDlg () virtual
Definition at line 46 of file editbreakpointdlg.cpp.
Member Function Documentation
EndModal()
void EditBreakpointDlg::EndModal (int retCode) protected
Definition at line 51 of file editbreakpointdlg.cpp.
References CleanStringValue(), DebuggerBreakpoint::condition, DebuggerBreakpoint::enabled, ScriptBindings::EndModal(), DebuggerBreakpoint::ignoreCount, m_breakpoint, DebuggerBreakpoint::useCondition, DebuggerBreakpoint::useIgnoreCount, and wxID_OK.
Referenced by GetBreakpoint().
GetBreakpoint()
const DebuggerBreakpoint& EditBreakpointDlg::GetBreakpoint () const inline
Definition at line 18 of file editbreakpointdlg.h.
References EndModal(), m_breakpoint, and OnUpdateUI().
Referenced by DebuggerGDB::UpdateBreakpoint().
OnUpdateUI()
void EditBreakpointDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 64 of file editbreakpointdlg.cpp.
Referenced by GetBreakpoint().
Member Data Documentation
m_breakpoint
DebuggerBreakpoint EditBreakpointDlg::m_breakpoint protected
Definition at line 23 of file editbreakpointdlg.h.
Referenced by EndModal(), and GetBreakpoint().
The documentation for this class was generated from the following files:
editbreakpointdlg.h
editbreakpointdlg.cpp