Code::Blocks: ScriptingSettingsDlg Class Reference
ScriptingSettingsDlg Class Reference
#include <scriptingsettingsdlg.h>
Public Member Functions
ScriptingSettingsDlg (wxWindow *parent)
~ScriptingSettingsDlg ()
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void FillScripts ()
void UpdateState ()
void FillTrusts ()
void UpdateTrustsState ()
void LoadItem (long item)
void SaveItem (long item)
void OnListSelection (wxListEvent &event)
void OnListDeselection (wxListEvent &event)
void OnAddScript (wxCommandEvent &event)
void OnRemoveScript (wxCommandEvent &event)
void OnScriptChanged (wxCommandEvent &event)
void OnScriptMenuChanged (wxCommandEvent &event)
void OnEnable (wxCommandEvent &event)
void OnRegister (wxCommandEvent &event)
void OnBrowse (wxCommandEvent &event)
void OnTrustSelection (wxListEvent &event)
void OnDeleteTrust (wxCommandEvent &event)
void OnValidateTrusts (wxCommandEvent &event)
Protected Attributes
ScriptsVector m_ScriptsVector
bool m_IgnoreTextEvents
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 40 of file scriptingsettingsdlg.h.
Constructor & Destructor Documentation
ScriptingSettingsDlg()
ScriptingSettingsDlg::ScriptingSettingsDlg (wxWindow * parent)
Definition at line 46 of file scriptingsettingsdlg.cpp.
~ScriptingSettingsDlg()
ScriptingSettingsDlg::~ScriptingSettingsDlg ()
Definition at line 68 of file scriptingsettingsdlg.cpp.
Member Function Documentation
EndModal()
void ScriptingSettingsDlg::EndModal (int retCode)
Definition at line 156 of file scriptingsettingsdlg.cpp.
References ConfigManager::DeleteSubPath(), ScriptBindings::EndModal(), Manager::Get(), Manager::GetConfigManager(), m_ScriptsVector, ScriptEntry::SerializeOut(), and ConfigManager::Write().
FillScripts()
void ScriptingSettingsDlg::FillScripts () protected
Definition at line 73 of file scriptingsettingsdlg.cpp.
References ScriptEntry::enabled, ConfigManager::EnumerateKeys(), Manager::Get(), Manager::GetConfigManager(), m_ScriptsVector, ScriptEntry::menu, ConfigManager::Read(), ScriptEntry::registered, ScriptEntry::script, ScriptEntry::SerializeIn(), and UpdateState().
FillTrusts()
void ScriptingSettingsDlg::FillTrusts () protected
Definition at line 116 of file scriptingsettingsdlg.cpp.
References ScriptingManager::TrustedScriptProps::crc, Manager::Get(), Manager::GetConfigManager(), Manager::GetScriptingManager(), ScriptingManager::GetTrustedScripts(), ScriptingManager::TrustedScriptProps::permanent, ConfigManager::ReadBool(), and UpdateTrustsState().
LoadItem()
void ScriptingSettingsDlg::LoadItem (long item) protected
Definition at line 185 of file scriptingsettingsdlg.cpp.
References ScriptEntry::enabled, m_IgnoreTextEvents, m_ScriptsVector, ScriptEntry::menu, ScriptEntry::registered, and ScriptEntry::script.
Referenced by OnListSelection(), and OnRemoveScript().
OnAddScript()
void ScriptingSettingsDlg::OnAddScript (wxCommandEvent & event) protected
Definition at line 278 of file scriptingsettingsdlg.cpp.
References ScriptEntry::enabled, m_ScriptsVector, OnBrowse(), ScriptEntry::registered, and ScriptEntry::script.
OnBrowse()
void ScriptingSettingsDlg::OnBrowse (wxCommandEvent & event) protected
Definition at line 314 of file scriptingsettingsdlg.cpp.
References FileFilters::GetFilterString(), ConfigManager::GetFolder(), PlaceWindow(), sdScriptsGlobal, sdScriptsUser, and UnixFilename().
Referenced by OnAddScript().
OnDeleteTrust()
void ScriptingSettingsDlg::OnDeleteTrust (wxCommandEvent & event) protected
Definition at line 346 of file scriptingsettingsdlg.cpp.
References Manager::Get(), Manager::GetScriptingManager(), ScriptingManager::RemoveTrust(), and UpdateTrustsState().
OnEnable()
void ScriptingSettingsDlg::OnEnable (wxCommandEvent & event) protected
Definition at line 262 of file scriptingsettingsdlg.cpp.
References SaveItem(), and UpdateState().
OnListDeselection()
void ScriptingSettingsDlg::OnListDeselection (wxListEvent & event) protected
Definition at line 231 of file scriptingsettingsdlg.cpp.
References SaveItem(), and UpdateState().
OnListSelection()
void ScriptingSettingsDlg::OnListSelection (wxListEvent & event) protected
Definition at line 220 of file scriptingsettingsdlg.cpp.
References LoadItem(), and UpdateState().
OnRegister()
void ScriptingSettingsDlg::OnRegister (wxCommandEvent & event) protected
Definition at line 270 of file scriptingsettingsdlg.cpp.
References SaveItem(), and UpdateState().
OnRemoveScript()
void ScriptingSettingsDlg::OnRemoveScript (wxCommandEvent & event) protected
Definition at line 298 of file scriptingsettingsdlg.cpp.
References LoadItem(), m_ScriptsVector, and UpdateState().
OnScriptChanged()
void ScriptingSettingsDlg::OnScriptChanged (wxCommandEvent & event) protected
Definition at line 242 of file scriptingsettingsdlg.cpp.
References m_IgnoreTextEvents, SaveItem(), and UpdateState().
OnScriptMenuChanged()
void ScriptingSettingsDlg::OnScriptMenuChanged (wxCommandEvent & event) protected
Definition at line 252 of file scriptingsettingsdlg.cpp.
References m_IgnoreTextEvents, SaveItem(), and UpdateState().
OnTrustSelection()
void ScriptingSettingsDlg::OnTrustSelection (wxListEvent & event) protected
Definition at line 341 of file scriptingsettingsdlg.cpp.
References UpdateTrustsState().
OnValidateTrusts()
void ScriptingSettingsDlg::OnValidateTrusts (wxCommandEvent & event) protected
Definition at line 358 of file scriptingsettingsdlg.cpp.
References cbMessageBox(), and Manager::Get().
SaveItem()
void ScriptingSettingsDlg::SaveItem (long item) protected
Definition at line 200 of file scriptingsettingsdlg.cpp.
References ScriptEntry::enabled, m_IgnoreTextEvents, m_ScriptsVector, ScriptEntry::menu, ScriptEntry::registered, and ScriptEntry::script.
Referenced by OnEnable(), OnListDeselection(), OnRegister(), OnScriptChanged(), and OnScriptMenuChanged().
UpdateState()
void ScriptingSettingsDlg::UpdateState () protected
Definition at line 99 of file scriptingsettingsdlg.cpp.
References ScriptEntry::enabled, m_ScriptsVector, and ScriptEntry::registered.
Referenced by FillScripts(), OnEnable(), OnListDeselection(), OnListSelection(), OnRegister(), OnRemoveScript(), OnScriptChanged(), and OnScriptMenuChanged().
UpdateTrustsState()
void ScriptingSettingsDlg::UpdateTrustsState () protected
Definition at line 145 of file scriptingsettingsdlg.cpp.
Referenced by FillTrusts(), OnDeleteTrust(), and OnTrustSelection().
Member Data Documentation
m_IgnoreTextEvents
bool ScriptingSettingsDlg::m_IgnoreTextEvents protected
Definition at line 70 of file scriptingsettingsdlg.h.
Referenced by LoadItem(), OnScriptChanged(), OnScriptMenuChanged(), and SaveItem().
m_ScriptsVector
ScriptsVector ScriptingSettingsDlg::m_ScriptsVector protected
Definition at line 69 of file scriptingsettingsdlg.h.
Referenced by EndModal(), FillScripts(), LoadItem(), OnAddScript(), OnRemoveScript(), SaveItem(), and UpdateState().
The documentation for this class was generated from the following files:
scriptingsettingsdlg.h
scriptingsettingsdlg.cpp