Code::Blocks: MainFrame Class Reference
MainFrame Class Reference
#include <main.h>
Public Member Functions
MainFrame & operator= (cb_unused const MainFrame &rhs)
MainFrame (wxWindow *parent=(wxWindow *) NULL)
CloseFullScreen event handling.
~MainFrame ()
bool Open (const wxString &filename, bool addToHistory=true)
bool OnDropFiles (wxCoord x, wxCoord y, const wxArrayString &filenames)
void ShowTips (bool forceShow=false)
wxScrollingDialog * GetBatchBuildDialog ()
wxString ShowOpenFileDialog (const wxString &caption, const wxString &filter)
bool OpenGeneric (const wxString &filename, bool addToHistory=true)
void StartupDone ()
cbProjectManagerUI * GetProjectManagerUI ()
Public Attributes
wxAcceleratorTable * m_pAccel
Protected Types
enum { Installed, Uninstalled, Unloaded }
typedef std::map< int, const wxString > MenuIDToScript
Protected Member Functions
void CreateIDE ()
void CreateMenubar ()
void CreateToolbars ()
void ScanForPlugins ()
void AddToolbarItem (int id, const wxString &title, const wxString &shortHelp, const wxString &longHelp, const wxString &image)
void RecreateMenuBar ()
void RegisterEvents ()
void SetupGUILogging ()
void SetupDebuggerUI ()
void RegisterScriptFunctions ()
void RunStartupScripts ()
void PluginsUpdated (cbPlugin *plugin, int status)
void DoAddPlugin (cbPlugin *plugin)
ToolbarInfo DoAddPluginToolbar (cbPlugin *plugin)
void DoAddPluginStatusField (cbPlugin *plugin)
void AddPluginInPluginsMenu (cbPlugin *plugin)
void AddPluginInHelpPluginsMenu (cbPlugin *plugin)
wxMenuItem * AddPluginInMenus (wxMenu *menu, cbPlugin *plugin, wxObjectEventFunction callback, int pos=-1, bool checkable=false)
void LoadViewLayout (const wxString &name, bool isTemp=false)
void SaveViewLayout (const wxString &name, const wxString &layout, const wxString &layoutMP, bool select=false)
void DoSelectLayout (const wxString &name)
void DoFixToolbarsLayout ()
bool DoCheckCurrentLayoutForChanges (bool canCancel=true)
void AddEditorInWindowMenu (const wxString &filename, const wxString &title)
void RemoveEditorFromWindowMenu (const wxString &filename)
int IsEditorInWindowMenu (const wxString &filename)
wxString GetEditorDescription (EditorBase *eb)
bool DoCloseCurrentWorkspace ()
bool DoOpenProject (const wxString &filename, bool addToHistory=true)
bool DoOpenFile (const wxString &filename, bool addToHistory=true)
void DoOnFileOpen (bool bProject=false)
void DoCreateStatusBar ()
void DoUpdateStatusBar ()
void DoUpdateAppTitle ()
void DoUpdateLayout ()
void DoUpdateLayoutColours ()
void DoUpdateEditorStyle ()
void DoUpdateEditorStyle (cbAuiNotebook *target, const wxString &prefix, long defaultStyle)
void ShowHideStartPage (bool forceHasProject=false, int forceState=0)
void ShowHideScriptConsole ()
void LoadWindowState ()
void SaveWindowState ()
void LoadWindowSize ()
void InitializeRecentFilesHistory ()
void TerminateRecentFilesHistory ()
wxStatusBar * OnCreateStatusBar (int number, long style, wxWindowID id, const wxString &name) override
Protected Attributes
RecentItemsList m_filesHistory
RecentItemsList m_projectsHistory
wxButton * m_pCloseFullScreenBtn
"Close FullScreen" button. Only shown when in FullScreen view
EditorManager * m_pEdMan
ProjectManager * m_pPrjMan
cbProjectManagerUI * m_pPrjManUI
LogManager * m_pLogMan
InfoPane * m_pInfoPane
wxToolBar * m_pToolbar
PluginToolbarsMap m_PluginsTools
PluginIDsMap m_PluginIDsMap
wxMenu * m_ToolsMenu
wxMenu * m_PluginsMenu
wxMenu * m_HelpPluginsMenu
bool m_ScanningForPlugins
bool m_SmallToolBar
bool m_StartupDone
bool m_InitiatedShutdown
int m_AutoHideLockCounter
int m_LastCtrlAltTabWindow
Last window focussed in the cycle 1 = Mgmt. panel, 2 = Editor, 3 = Logs & others.
wxString m_PreviousLayoutName
wxString m_LastLayoutName
wxString m_LastLayoutData
wxString m_LastMessagePaneLayoutData
bool m_LastLayoutIsTemp
wxWindow * m_pScriptConsole
MenuIDToScript m_MenuIDToScript
wxScrollingDialog * m_pBatchBuildDialog
wxButton * m_pHighlightButton
DebuggerMenuHandler * m_debuggerMenuHandler
DebuggerToolbarHandler * m_debuggerToolbarHandler
FindReplace m_findReplace
Private Member Functions
MainFrame (cb_unused const MainFrame &rhs)
bool LayoutDifferent (const wxString &layout1, const wxString &layout2, const wxString &delimiter=_("|"))
bool LayoutMessagePaneDifferent (const wxString &layout1, const wxString &layout2, bool checkSelection=false)
void OnEraseBackground (wxEraseEvent &event)
void OnSize (wxSizeEvent &event)
void OnApplicationClose (wxCloseEvent &event)
void OnStartHereLink (wxCommandEvent &event)
void OnMouseRightUp (wxMouseEvent &event)
void OnToolBarRightClick (wxCommandEvent &event)
void PopupToggleToolbarMenu ()
void SetChecksForViewToolbarsMenu (wxMenu &menu)
void OnFileNewWhat (wxCommandEvent &event)
void OnFileNew (wxCommandEvent &event)
void OnFileOpen (wxCommandEvent &event)
void OnFileReopenProject (wxCommandEvent &event)
void OnFileOpenRecentProjectClearHistory (wxCommandEvent &event)
void OnFileReopen (wxCommandEvent &event)
void OnFileOpenRecentClearHistory (wxCommandEvent &event)
void OnFileImportProjectDevCpp (wxCommandEvent &event)
void OnFileImportProjectMSVC (wxCommandEvent &event)
void OnFileImportProjectMSVCWksp (wxCommandEvent &event)
void OnFileImportProjectMSVS (wxCommandEvent &event)
void OnFileImportProjectMSVSWksp (wxCommandEvent &event)
void OnFileSave (wxCommandEvent &event)
void OnFileSaveAs (wxCommandEvent &event)
void OnFileSaveProject (wxCommandEvent &event)
void OnFileSaveProjectAs (wxCommandEvent &event)
void OnFileSaveProjectTemplate (wxCommandEvent &event)
void OnFileOpenDefWorkspace (wxCommandEvent &event)
void OnFileSaveWorkspace (wxCommandEvent &event)
void OnFileSaveWorkspaceAs (wxCommandEvent &event)
void OnFileSaveAll (wxCommandEvent &event)
void OnFileCloseWorkspace (wxCommandEvent &event)
void OnFileClose (wxCommandEvent &event)
void OnFileCloseAll (wxCommandEvent &event)
void OnFileCloseProject (wxCommandEvent &event)
void OnFilePrintSetup (wxCommandEvent &event)
void OnFilePrint (wxCommandEvent &event)
void OnFileQuit (wxCommandEvent &event)
void OnFileNext (wxCommandEvent &event)
void OnFilePrev (wxCommandEvent &event)
void OnEditUndo (wxCommandEvent &event)
void OnEditRedo (wxCommandEvent &event)
void OnEditClearHistory (wxCommandEvent &event)
void OnEditCopy (wxCommandEvent &event)
void OnEditCut (wxCommandEvent &event)
void OnEditPaste (wxCommandEvent &event)
void OnEditSwapHeaderSource (wxCommandEvent &event)
void OnEditGotoMatchingBrace (wxCommandEvent &event)
void OnEditHighlightMode (wxCommandEvent &event)
void OnEditFoldAll (wxCommandEvent &event)
void OnEditUnfoldAll (wxCommandEvent &event)
void OnEditToggleAllFolds (wxCommandEvent &event)
void OnEditFoldBlock (wxCommandEvent &event)
void OnEditUnfoldBlock (wxCommandEvent &event)
void OnEditToggleFoldBlock (wxCommandEvent &event)
void OnEditEOLMode (wxCommandEvent &event)
void OnEditEncoding (wxCommandEvent &event)
void OnEditParaUp (wxCommandEvent &event)
void OnEditParaUpExtend (wxCommandEvent &event)
void OnEditParaDown (wxCommandEvent &event)
void OnEditParaDownExtend (wxCommandEvent &event)
void OnEditWordPartLeft (wxCommandEvent &event)
void OnEditWordPartLeftExtend (wxCommandEvent &event)
void OnEditWordPartRight (wxCommandEvent &event)
void OnEditWordPartRightExtend (wxCommandEvent &event)
void OnEditZoomIn (wxCommandEvent &event)
void OnEditZoomOut (wxCommandEvent &event)
void OnEditZoomReset (wxCommandEvent &event)
void OnEditLineCut (wxCommandEvent &event)
void OnEditLineDelete (wxCommandEvent &event)
void OnEditLineDuplicate (wxCommandEvent &event)
void OnEditLineTranspose (wxCommandEvent &event)
void OnEditLineCopy (wxCommandEvent &event)
void OnEditLinePaste (wxCommandEvent &event)
void OnEditLineMove (wxCommandEvent &event)
void OnEditUpperCase (wxCommandEvent &event)
void OnEditLowerCase (wxCommandEvent &event)
void OnEditInsertNewLine (wxCommandEvent &event)
void OnEditGotoLineEnd (wxCommandEvent &event)
void OnEditInsertNewLineBelow (wxCommandEvent &event)
void OnEditInsertNewLineAbove (wxCommandEvent &event)
void OnEditSelectAll (wxCommandEvent &event)
void OnEditSelectNext (wxCommandEvent &event)
void OnEditSelectNextSkip (wxCommandEvent &event)
void OnEditCommentSelected (wxCommandEvent &event)
void OnEditUncommentSelected (wxCommandEvent &event)
void OnEditToggleCommentSelected (wxCommandEvent &event)
void OnEditStreamCommentSelected (wxCommandEvent &event)
void OnEditBoxCommentSelected (wxCommandEvent &event)
void OnEditShowCallTip (wxCommandEvent &event)
void OnEditCompleteCode (wxCommandEvent &event)
void OnEditBookmarksToggle (wxCommandEvent &event)
void OnEditBookmarksNext (wxCommandEvent &event)
void OnEditBookmarksPrevious (wxCommandEvent &event)
void OnEditBookmarksClearAll (wxCommandEvent &event)
void OnViewLayout (wxCommandEvent &event)
void OnViewLayoutSave (wxCommandEvent &event)
void OnViewLayoutDelete (wxCommandEvent &event)
void OnViewScriptConsole (wxCommandEvent &event)
void OnViewHideEditorTabs (wxCommandEvent &event)
void OnSearchFind (wxCommandEvent &event)
void OnSearchFindNext (wxCommandEvent &event)
void OnSearchFindNextSelected (wxCommandEvent &event)
void OnSearchReplace (wxCommandEvent &event)
void OnSearchGotoLine (wxCommandEvent &event)
void OnSearchGotoNextChanged (wxCommandEvent &event)
void OnSearchGotoPrevChanged (wxCommandEvent &event)
void OnPluginsExecuteMenu (wxCommandEvent &event)
void OnSettingsEnvironment (wxCommandEvent &event)
void OnSettingsKeyBindings (wxCommandEvent &event)
void OnGlobalUserVars (wxCommandEvent &event)
void OnSettingsEditor (wxCommandEvent &event)
void OnSettingsCompiler (wxCommandEvent &event)
void OnSettingsDebugger (wxCommandEvent &event)
void OnSettingsPlugins (wxCommandEvent &event)
void OnSettingsScripting (wxCommandEvent &event)
void OnHelpAbout (wxCommandEvent &event)
void OnHelpTips (wxCommandEvent &event)
void OnHelpPluginMenu (wxCommandEvent &event)
void OnViewToolbarsFit (wxCommandEvent &event)
void OnViewToolbarsOptimize (wxCommandEvent &event)
void OnToggleBar (wxCommandEvent &event)
void OnToggleStatusBar (wxCommandEvent &event)
void OnFocusEditor (wxCommandEvent &event)
void OnFocusManagement (wxCommandEvent &event)
void OnFocusLogsAndOthers (wxCommandEvent &event)
void OnSwitchTabs (wxCommandEvent &event)
void OnToggleFullScreen (wxCommandEvent &event)
void OnToggleStartPage (wxCommandEvent &event)
void OnPluginLoaded (CodeBlocksEvent &event)
void OnPluginUnloaded (CodeBlocksEvent &event)
void OnPluginInstalled (CodeBlocksEvent &event)
void OnPluginUninstalled (CodeBlocksEvent &event)
void OnEditorUpdateUI (CodeBlocksEvent &event)
void OnFileMenuUpdateUI (wxUpdateUIEvent &event)
void OnEditMenuUpdateUI (wxUpdateUIEvent &event)
void OnViewMenuUpdateUI (wxUpdateUIEvent &event)
void OnSearchMenuUpdateUI (wxUpdateUIEvent &event)
void OnProjectMenuUpdateUI (wxUpdateUIEvent &event)
void OnProjectActivated (CodeBlocksEvent &event)
void OnProjectOpened (CodeBlocksEvent &event)
void OnProjectClosed (CodeBlocksEvent &event)
void OnRequestDockWindow (CodeBlocksDockEvent &event)
void OnRequestUndockWindow (CodeBlocksDockEvent &event)
void OnRequestShowDockWindow (CodeBlocksDockEvent &event)
void OnRequestHideDockWindow (CodeBlocksDockEvent &event)
void OnDockWindowVisibility (CodeBlocksDockEvent &event)
void OnLayoutUpdate (CodeBlocksLayoutEvent &event)
void OnLayoutQuery (CodeBlocksLayoutEvent &event)
void OnLayoutSwitch (CodeBlocksLayoutEvent &event)
void OnAddLogWindow (CodeBlocksLogEvent &event)
void OnRemoveLogWindow (CodeBlocksLogEvent &event)
void OnHideLogWindow (CodeBlocksLogEvent &event)
void OnSwitchToLogWindow (CodeBlocksLogEvent &event)
void OnGetActiveLogWindow (CodeBlocksLogEvent &event)
void OnShowLogManager (CodeBlocksLogEvent &event)
void OnHideLogManager (CodeBlocksLogEvent &event)
void OnLockLogManager (CodeBlocksLogEvent &event)
void OnUnlockLogManager (CodeBlocksLogEvent &event)
void OnEditorOpened (CodeBlocksEvent &event)
void OnEditorActivated (CodeBlocksEvent &event)
void OnEditorClosed (CodeBlocksEvent &event)
void OnEditorSaved (CodeBlocksEvent &event)
void OnEditorModified (CodeBlocksEvent &event)
void OnPageChanged (wxNotebookEvent &event)
void OnShiftTab (wxCommandEvent &event)
void OnCtrlAltTab (wxCommandEvent &event)
void OnNotebookDoubleClick (CodeBlocksEvent &event)
void OnHighlightMenu (wxCommandEvent &event)
Private Attributes
wxAuiManager m_LayoutManager
LayoutViewsMap m_LayoutViews
LayoutViewsMap m_LayoutMessagePane
Detailed Description
Definition at line 60 of file main.h.
Member Typedef Documentation
MenuIDToScript
typedef std::map<int, const wxString> MainFrame::MenuIDToScript protected
Definition at line 396 of file main.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
Installed
Uninstalled
Unloaded
Definition at line 314 of file main.h.
Constructor & Destructor Documentation
MainFrame() [1/2]
MainFrame::MainFrame (cb_unused const MainFrame & rhs) private
MainFrame() [2/2]
MainFrame::MainFrame (wxWindow * parent = (wxWindow*)NULL)
CloseFullScreen event handling.
Shift-Tab bug workaround Used for mouse right click in the free area of MainFrame
Definition at line 555 of file main.cpp.
References _(), _T, FileFilters::AddDefaultFileFilters(), appglobals::AppName, appglobals::AppVersion, cbFileDropTarget::cbFileDropTarget(), LogManager::DebugLog(), Manager::Get(), Manager::GetCCManager(), Manager::GetConfigManager(), Manager::GetLogManager(), wxAuiPaneInfo::Hide(), idCtrlAltTab, idFileClose, idFileCloseAll, idFileNext, idFilePrev, idShiftTab, wxString::IsEmpty(), ConfigManager::Read(), ConfigManager::ReadBool(), wxAcceleratorEntry::Set(), ConfigManager::Write(), wxACCEL_ALT, wxACCEL_CTRL, wxACCEL_SHIFT, wxICON, WXK_F4, WXK_F6, and WXK_TAB.
~MainFrame()
MainFrame::~MainFrame ()
Definition at line 663 of file main.cpp.
References DeInitPrinting(), and wxNullAcceleratorTable.
Member Function Documentation
AddEditorInWindowMenu()
void MainFrame::AddEditorInWindowMenu (const wxString & filename, const wxString & title) protected
AddPluginInHelpPluginsMenu()
void MainFrame::AddPluginInHelpPluginsMenu (cbPlugin * plugin) protected
Definition at line 1266 of file main.cpp.
References OnHelpPluginMenu().
AddPluginInMenus()
wxMenuItem * MainFrame::AddPluginInMenus (wxMenu * menu, cbPlugin * plugin, wxObjectEventFunction callback, int pos = -1, bool checkable = false) protected
Definition at line 1212 of file main.cpp.
References _T, wxString::CmpNoCase(), wxMenu::FindItem(), wxMenu::FindItemByPosition(), Manager::Get(), wxMenuItem::GetItemLabelText(), wxMenu::GetMenuItemCount(), PluginManager::GetPluginInfo(), Manager::GetPluginManager(), wxMenu::Insert(), PluginInfo::name, PluginInfo::title, wxEmptyString, wxITEM_CHECK, wxITEM_NORMAL, and wxNewId().
AddPluginInPluginsMenu()
void MainFrame::AddPluginInPluginsMenu (cbPlugin * plugin) protected
Definition at line 1251 of file main.cpp.
References _T, OnPluginsExecuteMenu(), and wxID_SEPARATOR.
AddToolbarItem()
void MainFrame::AddToolbarItem (int id, const wxString & title, const wxString & shortHelp, const wxString & longHelp, const wxString & image) protected
Definition at line 1176 of file main.cpp.
References cbLoadBitmap(), and wxBITMAP_TYPE_PNG.
CreateIDE()
void MainFrame::CreateIDE () protected
Definition at line 730 of file main.cpp.
References _(), _T, wxAuiPaneInfo::Caption(), cbFileDropTarget::cbFileDropTarget(), Float, Manager::Get(), Manager::GetColourManager(), Manager::GetConfigManager(), Manager::GetEditorManager(), wxSize::GetHeight(), Manager::GetLogManager(), Manager::GetProjectManager(), idCloseFullScreen, Manager::IsBatchBuild(), wxAuiPaneInfo::Layer(), wxAuiPaneInfo::Left(), ColourManager::Load(), wxAuiPaneInfo::Name(), ConfigManager::ReadInt(), wxDefaultPosition, and wxT.
CreateMenubar()
void MainFrame::CreateMenubar () protected
Definition at line 961 of file main.cpp.
References _(), _T, wxMenu::Append(), wxMenu::AppendRadioItem(), wxMenu::Break(), cbPlugin::BuildMenu(), ToolsManager::BuildToolsMenu(), cbEVT_MENUBAR_CREATE_BEGIN, cbEVT_MENUBAR_CREATE_END, ScriptBindings::ScriptPluginWrapper::CreateMenu(), LogManager::DebugLog(), wxMenu::FindItem(), wxMenuBar::FindItem(), wxMenuBar::FindMenu(), wxString::Format(), wxXmlResource::Get(), Manager::Get(), EditorColourSet::GetAllHighlightLanguages(), EditorManager::GetColourSet(), wxArrayString::GetCount(), ConfigManager::GetDataFolder(), Manager::GetDebuggerManager(), Manager::GetEditorManager(), wxLocale::GetLanguageInfo(), Manager::GetLogManager(), wxMenuBar::GetMenu(), Manager::GetPluginManager(), PluginManager::GetPlugins(), wxMenuItem::GetSubMenu(), Manager::GetToolsManager(), cbPlugin::GetType(), idEditCompleteCode, idEditHighlightModeText, idHelpPlugins, idViewSwitchTabs, cbPlugin::IsAttached(), Manager::IsBatchBuild(), wxLanguageInfo::Language, wxXmlResource::Load(), wxXmlResource::LoadMenuBar(), OnEditHighlightMode(), Manager::ProcessEvent(), ptTool, wxMenuItem::SetItemLabel(), DebuggerManager::SetMenuHandler(), cbException::ShowErrorMessage(), wxLANGUAGE_CHINESE, wxLANGUAGE_CHINESE_TAIWAN, wxLANGUAGE_DEFAULT, wxLANGUAGE_JAPANESE, wxLANGUAGE_KOREAN, wxNewId(), wxNOT_FOUND, and wxT.
CreateToolbars()
void MainFrame::CreateToolbars () protected
Definition at line 1096 of file main.cpp.
References _(), _T, Manager::AddonToolBar(), wxAuiPaneInfo::Caption(), Manager::CreateEmptyToolbar(), LogManager::DebugLog(), wxXmlResource::Get(), Manager::Get(), ConfigManager::GetDataFolder(), Manager::GetLogManager(), Manager::GetPluginManager(), PluginManager::GetPlugins(), cbPlugin::IsAttached(), wxXmlResource::Load(), NULL, OnToolBarRightClick(), wxAuiPaneInfo::Position(), Manager::ProcessPendingEvents(), wxAuiPaneInfo::Row(), ToolbarInfo::toolbar, wxAuiPaneInfo::ToolbarPane(), wxAuiPaneInfo::Top(), wxID_ANY, and wxT.
DoAddPlugin()
void MainFrame::DoAddPlugin (cbPlugin * plugin) protected
Definition at line 1653 of file main.cpp.
References cbPlugin::BuildMenu(), cbPlugin::GetType(), wxAuiPaneInfo::IsToolbar(), NULL, OnToolBarRightClick(), ToolbarInfo::paneInfo, ptTool, cbException::ShowErrorMessage(), ToolbarInfo::toolbar, wxID_ANY, and wxPoint::x.
DoAddPluginStatusField()
void MainFrame::DoAddPluginStatusField (cbPlugin * plugin) protected
Definition at line 1600 of file main.cpp.
References cbStatusBar::AdjustFieldsSize(), and cbPlugin::CreateStatusField().
DoAddPluginToolbar()
ToolbarInfo MainFrame::DoAddPluginToolbar (cbPlugin * plugin) protected
Definition at line 1614 of file main.cpp.
References _(), _T, cbPlugin::BuildToolBar(), wxAuiPaneInfo::Caption(), cbThrow, wxMenuItem::Check(), Manager::CreateEmptyToolbar(), wxMenu::FindItem(), Manager::Get(), PluginManager::GetPluginInfo(), Manager::GetPluginManager(), cbPlugin::GetToolBarPriority(), idViewToolMain, InitToolbar(), wxAuiPaneInfo::Name(), PluginInfo::name, OnToggleBar(), ToolbarInfo::paneInfo, ToolbarInfo::priority, PluginInfo::title, and ToolbarInfo::toolbar.
DoCheckCurrentLayoutForChanges()
bool MainFrame::DoCheckCurrentLayoutForChanges (bool canCancel = true) protected
Definition at line 1532 of file main.cpp.
References _(), _T, wxString::Format(), Manager::Get(), AnnoyingDialog::rtCANCEL, AnnoyingDialog::rtSAVE_CHOICE, AnnoyingDialog::rtYES, AnnoyingDialog::ShowModal(), wxString::wx_str(), wxART_QUESTION, AnnoyingDialog::YES_NO, and AnnoyingDialog::YES_NO_CANCEL.
DoCloseCurrentWorkspace()
bool MainFrame::DoCloseCurrentWorkspace () protected
Definition at line 1875 of file main.cpp.
References ProjectManager::CloseWorkspace(), Manager::Get(), and Manager::GetProjectManager().
DoCreateStatusBar()
void MainFrame::DoCreateStatusBar () protected
Definition at line 1880 of file main.cpp.
References _(), wxStatusBar::GetFieldRect(), idHighlightButton, wxStatusBar::SetMinHeight(), wxBORDER_NONE, wxBU_EXACTFIT, wxBU_LEFT, wxDefaultPosition, wxDefaultSize, and wxT.
DoFixToolbarsLayout()
void MainFrame::DoFixToolbarsLayout () protected
Definition at line 1562 of file main.cpp.
References wxDefaultSize.
DoOnFileOpen()
void MainFrame::DoOnFileOpen (bool bProject = false) protected
Definition at line 2451 of file main.cpp.
References _(), _T, Manager::Get(), Manager::GetConfigManager(), wxFileDialog::GetDirectory(), wxFileDialog::GetFilterIndex(), FileFilters::GetFilterIndexFromName(), FileFilters::GetFilterNameFromIndex(), FileFilters::GetFilterString(), FileFilters::GetIndexForFilterAll(), wxFileDialog::GetPaths(), wxString::IsEmpty(), cbFileDropTarget::OnDropFiles(), PlaceWindow(), ConfigManager::Read(), wxFileDialog::SetFilterIndex(), wxFileDialog::ShowModal(), ConfigManager::Write(), wxEmptyString, wxFD_MULTIPLE, wxFD_OPEN, and wxID_OK.
DoOpenFile()
bool MainFrame::DoOpenFile (const wxString & filename, bool addToHistory = true) protected
Definition at line 1861 of file main.cpp.
References EditorBase::Activate(), Manager::Get(), Manager::GetEditorManager(), EditorBase::GetFilename(), and EditorManager::Open().
DoOpenProject()
bool MainFrame::DoOpenProject (const wxString & filename, bool addToHistory = true) protected
Definition at line 1840 of file main.cpp.
References _(), cbMessageBox(), Manager::Get(), CompileTargetBase::GetFilename(), Manager::GetProjectManager(), ProjectManager::LoadProject(), wxFileExists(), and wxICON_ERROR.
DoSelectLayout()
void MainFrame::DoSelectLayout (const wxString & name) protected
Definition at line 1577 of file main.cpp.
References _T, wxMenu::FindItem(), Manager::Get(), Manager::GetConfigManager(), wxMenu::GetMenuItems(), idViewLayoutSave, and ConfigManager::Write().
DoUpdateAppTitle()
void MainFrame::DoUpdateAppTitle () protected
Definition at line 2110 of file main.cpp.
References _T, wxString::Append(), appglobals::AppName, appglobals::AppVersion, Manager::Get(), EditorManager::GetActiveEditor(), ProjectManager::GetActiveProject(), Manager::GetEditorManager(), ProjectFile::GetParentProject(), Manager::GetProjectManager(), EditorBase::GetTitle(), CompileTargetBase::GetTitle(), EditorBase::IsBuiltinEditor(), and wxString::IsEmpty().
DoUpdateEditorStyle() [1/2]
void MainFrame::DoUpdateEditorStyle () protected
Definition at line 2044 of file main.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), Manager::GetEditorManager(), EditorManager::GetNotebook(), ConfigManager::ReadInt(), wxAuiNotebook::SetTabCtrlHeight(), wxCLIP_CHILDREN, and wxNO_FULL_REPAINT_ON_RESIZE.
DoUpdateEditorStyle() [2/2]
void MainFrame::DoUpdateEditorStyle (cbAuiNotebook * target, const wxString & prefix, long defaultStyle) protected
Definition at line 2000 of file main.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), ConfigManager::ReadBool(), ConfigManager::ReadInt(), wxAuiNotebook::SetArtProvider(), and wxAuiNotebook::SetTabCtrlHeight().
DoUpdateLayout()
void MainFrame::DoUpdateLayout () protected
Definition at line 2101 of file main.cpp.
DoUpdateLayoutColours()
void MainFrame::DoUpdateLayoutColours () protected
Definition at line 2076 of file main.cpp.
References _T, Manager::Get(), wxAuiDockArt::GetColour(), Manager::GetConfigManager(), wxAuiDockArt::GetMetric(), ConfigManager::ReadColour(), ConfigManager::ReadInt(), wxAuiDockArt::SetColour(), wxAuiDockArt::SetMetric(), wxAUI_DOCKART_ACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_CAPTION_SIZE, wxAUI_DOCKART_INACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_PANE_BORDER_SIZE, wxAUI_DOCKART_SASH_SIZE, wxAUI_MGR_ALLOW_ACTIVE_PANE, wxAUI_MGR_DEFAULT, wxAUI_MGR_TRANSPARENT_DRAG, wxAUI_MGR_TRANSPARENT_HINT, and wxAUI_MGR_VENETIAN_BLINDS_HINT.
DoUpdateStatusBar()
void MainFrame::DoUpdateStatusBar () protected
Definition at line 1927 of file main.cpp.
References _(), _T, appglobals::AppName, changeButtonLabel(), Manager::Get(), EditorManager::GetActiveEditor(), EditorManager::GetBuiltinActiveEditor(), EditorManager::GetColourSet(), wxScintilla::GetColumn(), cbEditor::GetControl(), wxScintilla::GetCurrentLine(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), cbEditor::GetEncodingName(), wxScintilla::GetEOLMode(), EditorBase::GetFilename(), cbEditor::GetLanguage(), EditorColourSet::GetLanguageName(), cbEditor::GetModified(), wxScintilla::GetOvertype(), wxScintilla::GetReadOnly(), Manager::IsAppShuttingDown(), wxString::Printf(), wxEmptyString, wxSCI_EOL_CR, wxSCI_EOL_CRLF, and wxSCI_EOL_LF.
Referenced by OnEditorUpdateUI().
GetBatchBuildDialog()
wxScrollingDialog* MainFrame::GetBatchBuildDialog () inline
Definition at line 86 of file main.h.
GetEditorDescription()
wxString MainFrame::GetEditorDescription (EditorBase * eb) protected
Definition at line 2254 of file main.cpp.
References _(), _T, Manager::Get(), ProjectManager::GetActiveProject(), EditorBase::GetFilename(), ProjectFile::GetParentProject(), Manager::GetProjectManager(), CompileTargetBase::GetTitle(), EditorBase::IsBuiltinEditor(), NULL, and wxEmptyString.
GetProjectManagerUI()
cbProjectManagerUI* MainFrame::GetProjectManagerUI () inline
Definition at line 95 of file main.h.
InitializeRecentFilesHistory()
void MainFrame::InitializeRecentFilesHistory () protected
Definition at line 2242 of file main.cpp.
IsEditorInWindowMenu()
int MainFrame::IsEditorInWindowMenu (const wxString & filename) protected
LayoutDifferent()
bool MainFrame::LayoutDifferent (const wxString & layout1, const wxString & layout2, const wxString & delimiter = _("|")) private
Definition at line 1454 of file main.cpp.
References _(), _T, wxArrayString::Add(), wxString::Format(), wxStringTokenizer::GetNextToken(), wxStringTokenizer::HasMoreTokens(), wxString::Len(), wxString::Right(), wxStringTokenizer::SetString(), wxArrayString::Sort(), wxString::StartsWith(), and wxString::ToULong().
LayoutMessagePaneDifferent()
bool MainFrame::LayoutMessagePaneDifferent (const wxString & layout1, const wxString & layout2, bool checkSelection = false) private
Definition at line 1503 of file main.cpp.
References _T, wxArrayString::Add(), wxString::AfterLast(), wxString::BeforeLast(), wxStringTokenizer::GetNextToken(), wxStringTokenizer::HasMoreTokens(), wxStringTokenizer::SetString(), and wxArrayString::Sort().
LoadViewLayout()
void MainFrame::LoadViewLayout (const wxString & name, bool isTemp = false) protected
Definition at line 1395 of file main.cpp.
References cbEVT_SWITCHED_VIEW_LAYOUT, gDefaultLayout, Manager::Get(), wxString::IsEmpty(), CodeBlocksLayoutEvent::layout, and Manager::ProcessEvent().
LoadWindowSize()
void MainFrame::LoadWindowSize () protected
Definition at line 1297 of file main.cpp.
References _T, Manager::Get(), wxRect::GetBottom(), wxDisplay::GetClientArea(), Manager::GetConfigManager(), wxDisplay::GetCount(), wxDisplay::GetFromWindow(), wxRect::GetHeight(), wxRect::GetLeft(), wxSystemSettings::GetMetric(), wxRect::GetRight(), wxRect::GetTop(), wxRect::GetWidth(), wxRect::height, ConfigManager::ReadBool(), ConfigManager::ReadInt(), wxRect::SetBottom(), wxRect::SetLeft(), wxRect::SetRight(), wxRect::SetTop(), wxRect::width, and wxSYS_MENU_Y.
LoadWindowState()
void MainFrame::LoadWindowState () protected
Definition at line 1272 of file main.cpp.
References _T, ConfigManager::EnumerateSubPaths(), Manager::Get(), Manager::GetConfigManager(), wxArrayString::GetCount(), and ConfigManager::Read().
OnAddLogWindow()
void MainFrame::OnAddLogWindow (CodeBlocksLogEvent & event) private
Definition at line 4997 of file main.cpp.
References Manager::Get(), Manager::GetLogManager(), CodeBlocksLogEvent::icon, Manager::IsAppShuttingDown(), CodeBlocksLogEvent::logger, LogManager::NotifyUpdate(), and CodeBlocksLogEvent::title.
Referenced by RegisterEvents().
OnApplicationClose()
void MainFrame::OnApplicationClose (wxCloseEvent & event) private
Definition at line 2716 of file main.cpp.
References _(), _T, Manager::BlockYields(), EditorManager::CanShutdown(), ProjectManager::CanShutdown(), cbAssert, cbEVT_APP_START_SHUTDOWN, cbHasRunningCompilers(), cbMessageBox(), cbStopRunningCompilers(), LogManager::DebugLog(), Manager::Get(), Manager::GetLogManager(), Manager::IsBatchBuild(), OnToolBarRightClick(), Manager::ProcessEvent(), Manager::SetAppShuttingDown(), Manager::Shutdown(), wxBell(), wxICON_QUESTION, wxID_ANY, wxID_YES, wxNO_DEFAULT, wxYES_NO, and Manager::Yield().
OnCreateStatusBar()
wxStatusBar * MainFrame::OnCreateStatusBar (int number, long style, wxWindowID id, const wxString & name) override protected
Definition at line 5131 of file main.cpp.
References wxStatusBar::SetFieldsCount().
OnCtrlAltTab()
void MainFrame::OnCtrlAltTab (wxCommandEvent & event) private
Definition at line 4883 of file main.cpp.
OnDockWindowVisibility()
void MainFrame::OnDockWindowVisibility (CodeBlocksDockEvent & event) private
Definition at line 4974 of file main.cpp.
Referenced by RegisterEvents().
OnDropFiles()
bool MainFrame::OnDropFiles (wxCoord x, wxCoord y, const wxArrayString & filenames)
Definition at line 2396 of file main.cpp.
References FileTypeOf(), ftCodeBlocksWorkspace, ftMSVC6Workspace, ftMSVC7Workspace, wxArrayString::GetCount(), and wxString::IsEmpty().
Referenced by IPC::Entry(), and cbFileDropTarget::OnDropFiles().
OnEditBookmarksClearAll()
void MainFrame::OnEditBookmarksClearAll (wxCommandEvent & event) private
Definition at line 2850 of file main.cpp.
References Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), and EditorBase::IsBuiltinEditor().
OnEditBookmarksNext()
void MainFrame::OnEditBookmarksNext (wxCommandEvent & event) private
Definition at line 2836 of file main.cpp.
References Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), and EditorBase::IsBuiltinEditor().
OnEditBookmarksPrevious()
void MainFrame::OnEditBookmarksPrevious (wxCommandEvent & event) private
Definition at line 2843 of file main.cpp.
References Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), and EditorBase::IsBuiltinEditor().
OnEditBookmarksToggle()
void MainFrame::OnEditBookmarksToggle (wxCommandEvent & event) private
Definition at line 2829 of file main.cpp.
References Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), and EditorBase::IsBuiltinEditor().
OnEditBoxCommentSelected()
void MainFrame::OnEditBoxCommentSelected (wxCommandEvent & event) private
Fix a glitch: when selecting multiple lines and the caret is at the start of the line after the last line selected, the code would, wrongly, (un)comment that line too. This fixes it.
Definition at line 3642 of file main.cpp.
References wxScintilla::BeginUndoAction(), CommentToken::boxCommentEnd, CommentToken::boxCommentMid, CommentToken::boxCommentStart, wxScintilla::EndUndoAction(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), EditorManager::GetColourSet(), wxScintilla::GetColumn(), EditorColourSet::GetCommentToken(), cbEditor::GetControl(), Manager::GetEditorManager(), wxScintilla::GetEOLMode(), GetEOLStr(), cbEditor::GetLanguage(), wxScintilla::GetLineEndPosition(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxScintilla::InsertText(), wxScintilla::LineFromPosition(), wxScintilla::LineLength(), wxScintilla::PositionFromLine(), wxScintilla::SetSelectionVoid(), CommentToken::streamCommentEnd, CommentToken::streamCommentStart, wxEmptyString, and wxSCI_INVALID_POSITION.
OnEditClearHistory()
void MainFrame::OnEditClearHistory (wxCommandEvent & event) private
Definition at line 2876 of file main.cpp.
References EditorBase::ClearHistory(), Manager::Get(), EditorManager::GetActiveEditor(), and Manager::GetEditorManager().
OnEditCommentSelected()
void MainFrame::OnEditCommentSelected (wxCommandEvent & event) private
Fix a glitch: when selecting multiple lines and the caret is at the start of the line after the last line selected, the code would, wrongly, (un)comment that line too. This fixes it.
Definition at line 3337 of file main.cpp.
References wxScintilla::BeginUndoAction(), wxScintilla::EndUndoAction(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), EditorManager::GetColourSet(), wxScintilla::GetColumn(), EditorColourSet::GetCommentToken(), cbEditor::GetControl(), Manager::GetEditorManager(), cbEditor::GetLanguage(), wxScintilla::GetLineEndPosition(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxScintilla::InsertText(), CommentToken::lineComment, wxScintilla::LineFromPosition(), wxScintilla::LineLength(), wxScintilla::PositionFromLine(), wxScintilla::SetSelectionVoid(), CommentToken::streamCommentEnd, CommentToken::streamCommentStart, wxEmptyString, and wxSCI_INVALID_POSITION.
OnEditCompleteCode()
void MainFrame::OnEditCompleteCode (wxCommandEvent & event) private
Definition at line 3714 of file main.cpp.
References cbEVT_COMPLETE_CODE, Manager::Get(), and Manager::ProcessEvent().
OnEditCopy()
void MainFrame::OnEditCopy (wxCommandEvent & event) private
Definition at line 2883 of file main.cpp.
References EditorBase::Copy(), Manager::Get(), EditorManager::GetActiveEditor(), and Manager::GetEditorManager().
OnEditCut()
void MainFrame::OnEditCut (wxCommandEvent & event) private
Definition at line 2890 of file main.cpp.
References EditorBase::Cut(), Manager::Get(), EditorManager::GetActiveEditor(), and Manager::GetEditorManager().
OnEditEncoding()
void MainFrame::OnEditEncoding (wxCommandEvent & event) private
Definition at line 3815 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), cbEditor::GetUseBom(), idEditEncodingAscii, idEditEncodingDefault, idEditEncodingUnicode, idEditEncodingUnicode16BE, idEditEncodingUnicode16LE, idEditEncodingUnicode32BE, idEditEncodingUnicode32LE, idEditEncodingUseBom, idEditEncodingUtf16, idEditEncodingUtf32, idEditEncodingUtf7, idEditEncodingUtf8, cbEditor::SetEncoding(), cbEditor::SetUseBom(), wxFONTENCODING_ISO8859_1, wxFONTENCODING_SYSTEM, wxFONTENCODING_UNICODE, wxFONTENCODING_UTF16, wxFONTENCODING_UTF16BE, wxFONTENCODING_UTF16LE, wxFONTENCODING_UTF32, wxFONTENCODING_UTF32BE, wxFONTENCODING_UTF32LE, wxFONTENCODING_UTF7, and wxFONTENCODING_UTF8.
OnEditEOLMode()
void MainFrame::OnEditEOLMode (wxCommandEvent & event) private
Definition at line 3791 of file main.cpp.
References wxScintilla::BeginUndoAction(), wxScintilla::ConvertEOLs(), wxScintilla::EndUndoAction(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), wxScintilla::GetEOLMode(), idEditEOLCR, idEditEOLCRLF, idEditEOLLF, wxScintilla::SetEOLMode(), wxSCI_EOL_CR, wxSCI_EOL_CRLF, and wxSCI_EOL_LF.
OnEditFoldAll()
void MainFrame::OnEditFoldAll (wxCommandEvent & event) private
Definition at line 3749 of file main.cpp.
References cbEditor::FoldAll(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), and Manager::GetEditorManager().
OnEditFoldBlock()
void MainFrame::OnEditFoldBlock (wxCommandEvent & event) private
Definition at line 3770 of file main.cpp.
References cbEditor::FoldBlockFromLine(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), and Manager::GetEditorManager().
OnEditGotoLineEnd()
void MainFrame::OnEditGotoLineEnd (wxCommandEvent & event) private
Definition at line 3129 of file main.cpp.
References wxScintilla::AutoCompActive(), wxScintilla::AutoCompCancel(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::LineEnd().
OnEditGotoMatchingBrace()
void MainFrame::OnEditGotoMatchingBrace (wxCommandEvent & event) private
Definition at line 2822 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::GotoMatchingBrace().
OnEditHighlightMode()
void MainFrame::OnEditHighlightMode (wxCommandEvent & event) private
Definition at line 3720 of file main.cpp.
References _T, changeButtonLabel(), wxMenu::FindItem(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetCCManager(), EditorManager::GetColourSet(), Manager::GetEditorManager(), EditorColourSet::GetHighlightLanguage(), wxMenuItem::GetItemLabelText(), EditorColourSet::GetLanguageName(), idEditHighlightModeText, CCManager::NotifyPluginStatus(), and cbEditor::SetLanguage().
Referenced by CreateMenubar().
OnEditInsertNewLine()
void MainFrame::OnEditInsertNewLine (wxCommandEvent & event) private
Definition at line 3116 of file main.cpp.
References wxScintilla::AutoCompActive(), wxScintilla::AutoCompCancel(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::NewLine().
OnEditInsertNewLineAbove()
void MainFrame::OnEditInsertNewLineAbove (wxCommandEvent & event) private
Definition at line 3174 of file main.cpp.
References InsertNewLine().
OnEditInsertNewLineBelow()
void MainFrame::OnEditInsertNewLineBelow (wxCommandEvent & event) private
Definition at line 3169 of file main.cpp.
References InsertNewLine().
OnEditLineCopy()
void MainFrame::OnEditLineCopy (wxCommandEvent & event) private
Definition at line 3009 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::LineCopy().
OnEditLineCut()
void MainFrame::OnEditLineCut (wxCommandEvent & event) private
Definition at line 2981 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::LineCut().
OnEditLineDelete()
void MainFrame::OnEditLineDelete (wxCommandEvent & event) private
Definition at line 2988 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::LineDelete().
OnEditLineDuplicate()
void MainFrame::OnEditLineDuplicate (wxCommandEvent & event) private
Definition at line 2995 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::LineDuplicate().
OnEditLineMove()
void MainFrame::OnEditLineMove (wxCommandEvent & event) private
Definition at line 3036 of file main.cpp.
References wxScintilla::BeginUndoAction(), wxScintilla::DeleteRange(), wxScintilla::EndUndoAction(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), wxScintilla::GetLineCount(), wxScintilla::GetLineEndPosition(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelections(), wxScintilla::GetSelectionStart(), wxScintilla::GetTextRange(), idEditLineUp, wxScintilla::InsertText(), wxScintilla::LineFromPosition(), wxScintilla::PositionFromLine(), and wxScintilla::SetSelectionVoid().
OnEditLinePaste()
void MainFrame::OnEditLinePaste (wxCommandEvent & event) private
Definition at line 3016 of file main.cpp.
References wxScintilla::BeginUndoAction(), wxScintilla::EndUndoAction(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), wxScintilla::GotoLine(), wxScintilla::GotoPos(), wxScintilla::LineFromPosition(), and wxScintilla::Paste().
OnEditLineTranspose()
void MainFrame::OnEditLineTranspose (wxCommandEvent & event) private
Definition at line 3002 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::LineTranspose().
OnEditLowerCase()
void MainFrame::OnEditLowerCase (wxCommandEvent & event) private
Definition at line 3109 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::LowerCase().
OnEditMenuUpdateUI()
void MainFrame::OnEditMenuUpdateUI (wxUpdateUIEvent & event) private
Definition at line 4121 of file main.cpp.
References _T, EditorBase::CanPaste(), EditorBase::CanRedo(), EditorBase::CanSelectAll(), EditorBase::CanUndo(), wxMenuBar::Check(), wxMenuBar::Enable(), wxMenuBar::FindItem(), wxMenu::FindItem(), Manager::Get(), EditorManager::GetActiveEditor(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetColourSet(), cbEditor::GetControl(), Manager::GetEditorManager(), cbEditor::GetEncoding(), wxScintilla::GetEOLMode(), cbEditor::GetLanguage(), EditorColourSet::GetLanguageName(), wxLocale::GetSystemEncoding(), cbEditor::GetUseBom(), EditorBase::HasSelection(), idEditBookmarks, idEditBoxCommentSelected, idEditClearHistory, idEditCommentSelected, idEditCompleteCode, idEditCopy, idEditCut, idEditEncoding, idEditEncodingAscii, idEditEncodingDefault, idEditEncodingUnicode, idEditEncodingUnicode16BE, idEditEncodingUnicode16LE, idEditEncodingUnicode32BE, idEditEncodingUnicode32LE, idEditEncodingUseBom, idEditEncodingUtf16, idEditEncodingUtf32, idEditEncodingUtf7, idEditEncodingUtf8, idEditEOLCR, idEditEOLCRLF, idEditEOLLF, idEditEOLMode, idEditFolding, idEditGotoMatchingBrace, idEditHighlightMode, idEditHighlightModeText, idEditPaste, idEditRedo, idEditSelectAll, idEditSelectNext, idEditSelectNextSkip, idEditShowCallTip, idEditSpecialCommands, idEditSpecialCommandsCase, idEditStreamCommentSelected, idEditSwapHeaderSource, idEditToggleCommentSelected, idEditUncommentSelected, idEditUndo, Manager::IsAppShuttingDown(), EditorBase::IsReadOnly(), NULL, wxFONTENCODING_ISO8859_1, wxFONTENCODING_SYSTEM, wxFONTENCODING_UNICODE, wxFONTENCODING_UTF16, wxFONTENCODING_UTF16BE, wxFONTENCODING_UTF16LE, wxFONTENCODING_UTF32, wxFONTENCODING_UTF32BE, wxFONTENCODING_UTF32LE, wxFONTENCODING_UTF7, wxFONTENCODING_UTF8, wxNOT_FOUND, wxSCI_EOL_CR, wxSCI_EOL_CRLF, and wxSCI_EOL_LF.
OnEditorActivated()
void MainFrame::OnEditorActivated (CodeBlocksEvent & event) private
Definition at line 4824 of file main.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), EditorBase::IsBuiltinEditor(), and ConfigManager::ReadBool().
Referenced by RegisterEvents().
OnEditorClosed()
void MainFrame::OnEditorClosed (CodeBlocksEvent & event) private
Definition at line 4844 of file main.cpp.
Referenced by RegisterEvents().
OnEditorModified()
void MainFrame::OnEditorModified (CodeBlocksEvent & event) private
Definition at line 4857 of file main.cpp.
Referenced by RegisterEvents().
OnEditorOpened()
void MainFrame::OnEditorOpened (CodeBlocksEvent & event) private
Definition at line 4818 of file main.cpp.
Referenced by RegisterEvents().
OnEditorSaved()
void MainFrame::OnEditorSaved (CodeBlocksEvent & event) private
Definition at line 4851 of file main.cpp.
Referenced by RegisterEvents().
OnEditorUpdateUI()
void MainFrame::OnEditorUpdateUI (CodeBlocksEvent & event) private
Definition at line 4319 of file main.cpp.
References DoUpdateStatusBar(), Manager::Get(), EditorManager::GetActiveEditor(), wxAuiManager::GetAllPanes(), wxAuiManager::GetArtProvider(), CodeBlocksEvent::GetEditor(), Manager::GetEditorManager(), wxAuiDockArt::GetMetric(), wxAuiManager::GetPane(), Manager::IsAppShuttingDown(), wxAuiPaneInfo::IsShown(), wxAuiPaneInfo::IsToolbar(), operator<(), wxAuiPaneInfo::Position(), wxAuiPaneInfo::Row(), wxAUI_DOCKART_GRIPPER_SIZE, and wxRect::x.
Referenced by RegisterEvents().
OnEditParaDown()
void MainFrame::OnEditParaDown (wxCommandEvent & event) private
Definition at line 2918 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::ParaDown().
OnEditParaDownExtend()
void MainFrame::OnEditParaDownExtend (wxCommandEvent & event) private
Definition at line 2925 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::ParaDownExtend().
OnEditParaUp()
void MainFrame::OnEditParaUp (wxCommandEvent & event) private
Definition at line 2904 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::ParaUp().
OnEditParaUpExtend()
void MainFrame::OnEditParaUpExtend (wxCommandEvent & event) private
Definition at line 2911 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::ParaUpExtend().
OnEditPaste()
void MainFrame::OnEditPaste (wxCommandEvent & event) private
Definition at line 2897 of file main.cpp.
References Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), and EditorBase::Paste().
OnEditRedo()
void MainFrame::OnEditRedo (wxCommandEvent & event) private
Definition at line 2869 of file main.cpp.
References Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), and EditorBase::Redo().
OnEditSelectAll()
void MainFrame::OnEditSelectAll (wxCommandEvent & event) private
Definition at line 3179 of file main.cpp.
References _(), wxScintilla::AddSelection(), InfoWindow::Display(), wxString::find_first_of(), wxScintilla::FindText(), Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), wxScintilla::GetLength(), wxScintilla::GetMainSelection(), wxScintilla::GetSelectionNAnchor(), wxScintilla::GetSelectionNCaret(), wxScintilla::GetSelections(), wxScintilla::IndicatorClearRange(), wxScintilla::LineFromPosition(), main(), cbStyledTextCtrl::MakeNearbyLinesVisible(), wxString::npos, EditorBase::SelectAll(), wxScintilla::SetAdditionalSelectionTyping(), wxScintilla::SetMultiPaste(), wxSCI_FIND_MATCHCASE, wxSCI_FIND_WHOLEWORD, wxSCI_INVALID_POSITION, and wxT.
OnEditSelectNext()
void MainFrame::OnEditSelectNext (wxCommandEvent & event) private
Definition at line 3250 of file main.cpp.
References Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), wxScintilla::GetTextRange(), EditorBase::IsBuiltinEditor(), wxScintilla::SetSelection(), wxScintilla::WordEndPosition(), and wxScintilla::WordStartPosition().
OnEditSelectNextSkip()
void MainFrame::OnEditSelectNextSkip (wxCommandEvent & event) private
Definition at line 3275 of file main.cpp.
References wxScintilla::AddSelection(), wxScintilla::ClearSelections(), Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetConfigManager(), Manager::GetEditorManager(), wxScintilla::GetSelectionNAnchor(), wxScintilla::GetSelectionNCaret(), wxScintilla::GetSelections(), wxScintilla::GetTextRange(), wxScintilla::IndicatorFillRange(), EditorBase::IsBuiltinEditor(), ConfigManager::ReadBool(), wxScintilla::SetSelectionNAnchor(), wxScintilla::SetSelectionNCaret(), and wxT.
OnEditShowCallTip()
void MainFrame::OnEditShowCallTip (wxCommandEvent & event) private
Definition at line 3708 of file main.cpp.
References cbEVT_SHOW_CALL_TIP, Manager::Get(), and Manager::ProcessEvent().
OnEditStreamCommentSelected()
void MainFrame::OnEditStreamCommentSelected (wxCommandEvent & event) private
Fix a glitch: when selecting multiple lines and the caret is at the start of the line after the last line selected, the code would, wrongly, (un)comment that line too. This fixes it.
Definition at line 3562 of file main.cpp.
References _T, wxScintilla::BeginUndoAction(), wxScintilla::EndUndoAction(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), wxScintilla::GetCharAt(), EditorManager::GetColourSet(), wxScintilla::GetColumn(), EditorColourSet::GetCommentToken(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), cbEditor::GetLanguage(), wxScintilla::GetLength(), wxScintilla::GetLineEndPosition(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxScintilla::GetTextRange(), wxScintilla::GotoPos(), wxScintilla::InsertText(), wxString::Length(), wxScintilla::LineFromPosition(), wxScintilla::PositionFromLine(), wxScintilla::ReplaceTarget(), wxScintilla::SetSelectionVoid(), wxScintilla::SetTargetEnd(), wxScintilla::SetTargetStart(), CommentToken::streamCommentEnd, CommentToken::streamCommentStart, wxScintilla::WordEndPosition(), wxScintilla::WordStartPosition(), wxEmptyString, and wxSCI_INVALID_POSITION.
OnEditSwapHeaderSource()
void MainFrame::OnEditSwapHeaderSource (wxCommandEvent & event) private
Definition at line 2816 of file main.cpp.
References Manager::Get(), Manager::GetEditorManager(), and EditorManager::SwapActiveHeaderSource().
OnEditToggleAllFolds()
void MainFrame::OnEditToggleAllFolds (wxCommandEvent & event) private
Definition at line 3763 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::ToggleAllFolds().
OnEditToggleCommentSelected()
void MainFrame::OnEditToggleCommentSelected (wxCommandEvent & event) private
Fix a glitch: when selecting multiple lines and the caret is at the start of the line after the last line selected, the code would, wrongly, (un)comment that line too. This fixes it.
Definition at line 3484 of file main.cpp.
References wxScintilla::BeginUndoAction(), wxScintilla::EndUndoAction(), wxString::Find(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), EditorManager::GetColourSet(), wxScintilla::GetColumn(), EditorColourSet::GetCommentToken(), cbEditor::GetControl(), Manager::GetEditorManager(), cbEditor::GetLanguage(), wxScintilla::GetLine(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxScintilla::InsertText(), wxString::Length(), wxScintilla::LineFromPosition(), wxScintilla::LineLength(), wxScintilla::PositionFromLine(), wxScintilla::ReplaceTarget(), wxScintilla::SetSelectionVoid(), wxScintilla::SetTargetEnd(), wxScintilla::SetTargetStart(), wxString::Strip(), wxEmptyString, and wxSCI_INVALID_POSITION.
OnEditToggleFoldBlock()
void MainFrame::OnEditToggleFoldBlock (wxCommandEvent & event) private
Definition at line 3784 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::ToggleFoldBlockFromLine().
OnEditUncommentSelected()
void MainFrame::OnEditUncommentSelected (wxCommandEvent & event) private
Fix a glitch: when selecting multiple lines and the caret is at the start of the line after the last line selected, the code would, wrongly, (un)comment that line too. This fixes it.
Definition at line 3393 of file main.cpp.
References wxScintilla::BeginUndoAction(), wxString::EndsWith(), wxScintilla::EndUndoAction(), wxString::Find(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), EditorManager::GetColourSet(), wxScintilla::GetColumn(), EditorColourSet::GetCommentToken(), cbEditor::GetControl(), Manager::GetEditorManager(), cbEditor::GetLanguage(), wxScintilla::GetLine(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxString::Length(), CommentToken::lineComment, wxScintilla::LineFromPosition(), wxScintilla::LineLength(), wxString::npos, wxScintilla::PositionFromLine(), wxScintilla::ReplaceTarget(), wxString::rfind(), wxScintilla::SetSelectionVoid(), wxScintilla::SetTargetEnd(), wxScintilla::SetTargetStart(), wxString::StartsWith(), CommentToken::streamCommentEnd, CommentToken::streamCommentStart, wxString::Strip(), wxEmptyString, and wxSCI_INVALID_POSITION.
OnEditUndo()
void MainFrame::OnEditUndo (wxCommandEvent & event) private
Definition at line 2857 of file main.cpp.
References wxScintilla::AutoCompActive(), wxScintilla::AutoCompCancel(), EditorBase::CanUndo(), Manager::Get(), EditorManager::GetActiveEditor(), EditorManager::GetBuiltinEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and EditorBase::Undo().
OnEditUnfoldAll()
void MainFrame::OnEditUnfoldAll (wxCommandEvent & event) private
Definition at line 3756 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::UnfoldAll().
OnEditUnfoldBlock()
void MainFrame::OnEditUnfoldBlock (wxCommandEvent & event) private
Definition at line 3777 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::UnfoldBlockFromLine().
OnEditUpperCase()
void MainFrame::OnEditUpperCase (wxCommandEvent & event) private
Definition at line 3102 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::UpperCase().
OnEditWordPartLeft()
void MainFrame::OnEditWordPartLeft (wxCommandEvent & event) private
Definition at line 2932 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::WordPartLeft().
OnEditWordPartLeftExtend()
void MainFrame::OnEditWordPartLeftExtend (wxCommandEvent & event) private
Definition at line 2939 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::WordPartLeftExtend().
OnEditWordPartRight()
void MainFrame::OnEditWordPartRight (wxCommandEvent & event) private
Definition at line 2946 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::WordPartRight().
OnEditWordPartRightExtend()
void MainFrame::OnEditWordPartRightExtend (wxCommandEvent & event) private
Definition at line 2953 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::WordPartRightExtend().
OnEditZoomIn()
void MainFrame::OnEditZoomIn (wxCommandEvent & event) private
Definition at line 2960 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::ZoomIn().
OnEditZoomOut()
void MainFrame::OnEditZoomOut (wxCommandEvent & event) private
Definition at line 2967 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::ZoomOut().
OnEditZoomReset()
void MainFrame::OnEditZoomReset (wxCommandEvent & event) private
Definition at line 2974 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxScintilla::SetZoom().
OnEraseBackground()
void MainFrame::OnEraseBackground (wxEraseEvent & event) private
Definition at line 2693 of file main.cpp.
OnFileClose()
void MainFrame::OnFileClose (wxCommandEvent & event) private
Definition at line 2655 of file main.cpp.
References EditorManager::CloseActive(), Manager::Get(), and Manager::GetEditorManager().
OnFileCloseAll()
void MainFrame::OnFileCloseAll (wxCommandEvent & event) private
Definition at line 2662 of file main.cpp.
References EditorManager::CloseAll(), Manager::Get(), and Manager::GetEditorManager().
OnFileCloseProject()
void MainFrame::OnFileCloseProject (wxCommandEvent & event) private
Definition at line 2587 of file main.cpp.
References EditorManager::CanShutdown(), ProjectManager::CanShutdown(), ProjectManager::CloseActiveProject(), Manager::Get(), Manager::GetProjectManager(), and wxBell().
OnFileCloseWorkspace()
void MainFrame::OnFileCloseWorkspace (wxCommandEvent & event) private
Definition at line 2650 of file main.cpp.
OnFileImportProjectDevCpp()
void MainFrame::OnFileImportProjectDevCpp (wxCommandEvent & event) private
Definition at line 2600 of file main.cpp.
References _(), _T, FileFilters::DEVCPP_EXT, and FileFilters::GetFilterString().
OnFileImportProjectMSVC()
void MainFrame::OnFileImportProjectMSVC (wxCommandEvent & event) private
Definition at line 2605 of file main.cpp.
References _(), _T, FileFilters::GetFilterString(), and FileFilters::MSVC6_EXT.
OnFileImportProjectMSVCWksp()
void MainFrame::OnFileImportProjectMSVCWksp (wxCommandEvent & event) private
Definition at line 2610 of file main.cpp.
References _(), _T, FileFilters::GetFilterString(), and FileFilters::MSVC6_WORKSPACE_EXT.
OnFileImportProjectMSVS()
void MainFrame::OnFileImportProjectMSVS (wxCommandEvent & event) private
Definition at line 2615 of file main.cpp.
References _(), _T, FileFilters::GetFilterString(), and FileFilters::MSVC7_EXT.
OnFileImportProjectMSVSWksp()
void MainFrame::OnFileImportProjectMSVSWksp (wxCommandEvent & event) private
Definition at line 2620 of file main.cpp.
References _(), _T, FileFilters::GetFilterString(), and FileFilters::MSVC7_WORKSPACE_EXT.
OnFileMenuUpdateUI()
void MainFrame::OnFileMenuUpdateUI (wxUpdateUIEvent & event) private
Definition at line 4058 of file main.cpp.
References EditorManager::CanShutdown(), ProjectManager::CanShutdown(), g_StartHereTitle, Manager::Get(), EditorManager::GetActiveEditor(), ProjectManager::GetActiveProject(), EditorManager::GetBuiltinActiveEditor(), cbProject::GetCurrentlyCompilingTarget(), EditorManager::GetEditor(), Manager::GetEditorManager(), EditorBase::GetModified(), cbWorkspace::GetModified(), cbProject::GetModified(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), idFileClose, idFileCloseAll, idFileCloseProject, idFileCloseWorkspace, idFileOpen, idFileOpenDefWorkspace, idFilePrint, idFileReopenProject, idFileSave, idFileSaveAll, idFileSaveAs, idFileSaveProject, idFileSaveProjectAs, idFileSaveProjectTemplate, idFileSaveWorkspace, idFileSaveWorkspaceAs, and Manager::IsAppShuttingDown().
OnFileNew()
void MainFrame::OnFileNew (wxCommandEvent & event) private
Definition at line 2425 of file main.cpp.
References CopyMenu(), wxMenuBar::FindItem(), and idFileNewProject.
OnFileNewWhat()
void MainFrame::OnFileNewWhat (wxCommandEvent & event) private
Definition at line 2310 of file main.cpp.
References _(), _T, ProjectManager::AddFileToProject(), cbEVT_PROJECT_NEW, cbEVT_PROJECT_OPEN, cbMessageBox(), EditorManager::CheckForExternallyModifiedFiles(), Manager::Get(), Mgr< TemplateManager >::Get(), ProjectManager::GetActiveProject(), CompileTargetBase::GetBasePath(), cbEditor::GetControl(), Manager::GetEditorManager(), cbProject::GetFileByFilename(), Manager::GetPluginManager(), Manager::GetProjectManager(), idFileNewCustom, idFileNewEmpty, idFileNewFile, idFileNewProject, idFileNewTarget, idFileNewUser, wxString::IsEmpty(), TemplateManager::New(), EditorManager::New(), PluginManager::NotifyPlugins(), cbProject::Save(), cbProject::SaveAllFiles(), wxScintilla::SetChangeCollection(), totCustom, totFiles, totProject, totTarget, totUser, wxICON_QUESTION, wxID_YES, wxSetWorkingDirectory(), and wxYES_NO.
OnFileNext()
void MainFrame::OnFileNext (wxCommandEvent & event) private
Definition at line 2668 of file main.cpp.
References EditorManager::ActivateNext(), Manager::Get(), and Manager::GetEditorManager().
OnFileOpen()
void MainFrame::OnFileOpen (wxCommandEvent & event) private
Definition at line 2498 of file main.cpp.
OnFileOpenDefWorkspace()
void MainFrame::OnFileOpenDefWorkspace (wxCommandEvent & event) private
Definition at line 2625 of file main.cpp.
References _(), cbMessageBox(), Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), cbWorkspace::IsDefault(), ProjectManager::LoadWorkspace(), and wxICON_WARNING.
OnFileOpenRecentClearHistory()
void MainFrame::OnFileOpenRecentClearHistory (wxCommandEvent & event) private
Definition at line 2524 of file main.cpp.
OnFileOpenRecentProjectClearHistory()
void MainFrame::OnFileOpenRecentProjectClearHistory (wxCommandEvent & event) private
Definition at line 2511 of file main.cpp.
OnFilePrev()
void MainFrame::OnFilePrev (wxCommandEvent & event) private
Definition at line 2674 of file main.cpp.
References EditorManager::ActivatePrevious(), Manager::Get(), and Manager::GetEditorManager().
OnFilePrint()
void MainFrame::OnFilePrint (wxCommandEvent & event) private
Definition at line 2680 of file main.cpp.
References Manager::Get(), Manager::GetEditorManager(), PrintDialog::GetPrintColourMode(), PrintDialog::GetPrintLineNumbers(), PrintDialog::GetPrintScope(), PlaceWindow(), EditorManager::Print(), wxDialog::ShowModal(), and wxID_OK.
OnFilePrintSetup()
void MainFrame::OnFilePrintSetup (wxCommandEvent & event) private
OnFileQuit()
void MainFrame::OnFileQuit (wxCommandEvent & event) private
Definition at line 2688 of file main.cpp.
OnFileReopen()
void MainFrame::OnFileReopen (wxCommandEvent & event) private
Definition at line 2516 of file main.cpp.
References wxID_CBFILE01.
OnFileReopenProject()
void MainFrame::OnFileReopenProject (wxCommandEvent & event) private
Definition at line 2503 of file main.cpp.
References wxID_CBFILE17.
OnFileSave()
void MainFrame::OnFileSave (wxCommandEvent & event) private
Definition at line 2529 of file main.cpp.
References _(), cbMessageBox(), Manager::Get(), wxString::Printf(), and wxICON_ERROR.
OnFileSaveAll()
void MainFrame::OnFileSaveAll (wxCommandEvent & event) private
Definition at line 2565 of file main.cpp.
References _T, ConfigManager::Flush(), Manager::Get(), Manager::GetConfigManager(), Manager::GetEditorManager(), cbWorkspace::GetFilename(), cbWorkspace::GetModified(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), cbWorkspace::IsDefault(), EditorManager::SaveAll(), ProjectManager::SaveAllProjects(), and ProjectManager::SaveWorkspace().
OnFileSaveAs()
void MainFrame::OnFileSaveAs (wxCommandEvent & event) private
Definition at line 2540 of file main.cpp.
References Manager::Get(), Manager::GetEditorManager(), and EditorManager::SaveActiveAs().
OnFileSaveProject()
void MainFrame::OnFileSaveProject (wxCommandEvent & event) private
Definition at line 2546 of file main.cpp.
References Manager::Get(), ProjectManager::GetActiveProject(), CompileTargetBase::GetFilename(), Manager::GetProjectManager(), and ProjectManager::SaveActiveProject().
OnFileSaveProjectAs()
void MainFrame::OnFileSaveProjectAs (wxCommandEvent & event) private
Definition at line 2556 of file main.cpp.
References Manager::Get(), ProjectManager::GetActiveProject(), CompileTargetBase::GetFilename(), Manager::GetProjectManager(), and ProjectManager::SaveActiveProjectAs().
OnFileSaveProjectTemplate()
void MainFrame::OnFileSaveProjectTemplate (wxCommandEvent & event) private
Definition at line 2582 of file main.cpp.
References Manager::Get(), Mgr< TemplateManager >::Get(), and TemplateManager::SaveUserTemplate().
OnFileSaveWorkspace()
void MainFrame::OnFileSaveWorkspace (wxCommandEvent & event) private
Definition at line 2636 of file main.cpp.
References Manager::Get(), cbWorkspace::GetFilename(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), and ProjectManager::SaveWorkspace().
OnFileSaveWorkspaceAs()
void MainFrame::OnFileSaveWorkspaceAs (wxCommandEvent & event) private
Definition at line 2643 of file main.cpp.
References _T, Manager::Get(), cbWorkspace::GetFilename(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), and ProjectManager::SaveWorkspaceAs().
OnFocusEditor()
void MainFrame::OnFocusEditor (wxCommandEvent & event) private
Definition at line 4534 of file main.cpp.
References cbAuiNotebook::FocusActiveTabCtrl(), Manager::Get(), Manager::GetEditorManager(), and EditorManager::GetNotebook().
OnFocusLogsAndOthers()
void MainFrame::OnFocusLogsAndOthers (wxCommandEvent & event) private
Definition at line 4549 of file main.cpp.
OnFocusManagement()
void MainFrame::OnFocusManagement (wxCommandEvent & event) private
Definition at line 4542 of file main.cpp.
References cbAuiNotebook::FocusActiveTabCtrl().
OnGetActiveLogWindow()
void MainFrame::OnGetActiveLogWindow (CodeBlocksLogEvent & event) private
Definition at line 5039 of file main.cpp.
Referenced by RegisterEvents().
OnGlobalUserVars()
void MainFrame::OnGlobalUserVars (wxCommandEvent & event) private
Definition at line 4739 of file main.cpp.
References UserVariableManager::Configure(), Manager::Get(), and Manager::GetUserVariableManager().
OnHelpAbout()
void MainFrame::OnHelpAbout (wxCommandEvent & event) private
Definition at line 4046 of file main.cpp.
References pdlHead, PlaceWindow(), and wxDialog::ShowModal().
OnHelpPluginMenu()
void MainFrame::OnHelpPluginMenu (wxCommandEvent & event) private
Definition at line 2291 of file main.cpp.
References _T, LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), PluginManager::GetPluginInfo(), Manager::GetPluginManager(), wxString::IsEmpty(), PlaceWindow(), and wxDialog::ShowModal().
Referenced by AddPluginInHelpPluginsMenu().
OnHelpTips()
void MainFrame::OnHelpTips (wxCommandEvent & event) private
Definition at line 4053 of file main.cpp.
OnHideLogManager()
void MainFrame::OnHideLogManager (CodeBlocksLogEvent & event) private
Definition at line 5062 of file main.cpp.
References _T, and Manager::Get().
Referenced by RegisterEvents().
OnHideLogWindow()
void MainFrame::OnHideLogWindow (CodeBlocksLogEvent & event) private
Definition at line 5023 of file main.cpp.
References CodeBlocksLogEvent::logger, and CodeBlocksLogEvent::window.
Referenced by RegisterEvents().
OnHighlightMenu()
void MainFrame::OnHighlightMenu (wxCommandEvent & event) private
Definition at line 5092 of file main.cpp.
References wxMenu::Append(), wxMenu::Break(), wxMenuItem::Check(), wxMenu::FindItem(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), EditorManager::GetColourSet(), Manager::GetEditorManager(), wxMenuItem::GetHelp(), wxMenuItem::GetId(), wxMenuItem::GetItemLabel(), wxMenuItem::GetKind(), wxMenu::GetMenuItems(), wxRect::GetPosition(), idEditHighlightModeText, wxMenuItem::IsCheckable(), and wxMenuItem::IsChecked().
OnLayoutQuery()
void MainFrame::OnLayoutQuery (CodeBlocksLayoutEvent & event) private
Definition at line 4986 of file main.cpp.
References gDefaultLayout.
Referenced by RegisterEvents().
OnLayoutSwitch()
void MainFrame::OnLayoutSwitch (CodeBlocksLayoutEvent & event) private
Definition at line 4992 of file main.cpp.
References CodeBlocksLayoutEvent::layout.
Referenced by RegisterEvents().
OnLayoutUpdate()
void MainFrame::OnLayoutUpdate (CodeBlocksLayoutEvent & event) private
Definition at line 4980 of file main.cpp.
Referenced by RegisterEvents().
OnLockLogManager()
void MainFrame::OnLockLogManager (CodeBlocksLogEvent & event) private
Definition at line 5072 of file main.cpp.
References _T, and Manager::Get().
Referenced by RegisterEvents().
OnMouseRightUp()
void MainFrame::OnMouseRightUp (wxMouseEvent & event) private
Definition at line 5140 of file main.cpp.
OnNotebookDoubleClick()
void MainFrame::OnNotebookDoubleClick (CodeBlocksEvent & event) private
Definition at line 3943 of file main.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), ConfigManager::Read(), and ConfigManager::ReadBool().
OnPageChanged()
void MainFrame::OnPageChanged (wxNotebookEvent & event) private
Definition at line 4869 of file main.cpp.
OnPluginInstalled()
void MainFrame::OnPluginInstalled (CodeBlocksEvent & event) private
Definition at line 4661 of file main.cpp.
References CodeBlocksEvent::GetPlugin().
Referenced by RegisterEvents().
OnPluginLoaded()
void MainFrame::OnPluginLoaded (CodeBlocksEvent & event) private
Definition at line 4673 of file main.cpp.
References _(), _T, LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), PluginManager::GetPluginInfo(), Manager::GetPluginManager(), PluginInfo::title, and wxString::wx_str().
Referenced by RegisterEvents().
OnPluginsExecuteMenu()
void MainFrame::OnPluginsExecuteMenu (wxCommandEvent & event) private
Definition at line 2282 of file main.cpp.
References _T, LogManager::DebugLog(), PluginManager::ExecutePlugin(), F(), Manager::Get(), Manager::GetLogManager(), Manager::GetPluginManager(), and wxString::IsEmpty().
Referenced by AddPluginInPluginsMenu().
OnPluginUninstalled()
void MainFrame::OnPluginUninstalled (CodeBlocksEvent & event) private
Definition at line 4666 of file main.cpp.
References CodeBlocksEvent::GetPlugin(), and Manager::IsAppShuttingDown().
Referenced by RegisterEvents().
OnPluginUnloaded()
void MainFrame::OnPluginUnloaded (CodeBlocksEvent & event) private
Definition at line 4685 of file main.cpp.
References cbAssert, Manager::IsAppShuttingDown(), OnToolBarRightClick(), cbStatusBar::RemoveField(), and wxID_ANY.
Referenced by RegisterEvents().
OnProjectActivated()
void MainFrame::OnProjectActivated (CodeBlocksEvent & event) private
Definition at line 4806 of file main.cpp.
Referenced by RegisterEvents().
OnProjectClosed()
void MainFrame::OnProjectClosed (CodeBlocksEvent & event) private
Definition at line 4863 of file main.cpp.
Referenced by RegisterEvents().
OnProjectMenuUpdateUI()
void MainFrame::OnProjectMenuUpdateUI (wxUpdateUIEvent & event) private
OnProjectOpened()
void MainFrame::OnProjectOpened (CodeBlocksEvent & event) private
Definition at line 4812 of file main.cpp.
Referenced by RegisterEvents().
OnRemoveLogWindow()
void MainFrame::OnRemoveLogWindow (CodeBlocksLogEvent & event) private
Definition at line 5013 of file main.cpp.
References Manager::IsAppShuttingDown(), CodeBlocksLogEvent::logger, and CodeBlocksLogEvent::window.
Referenced by RegisterEvents().
OnRequestDockWindow()
void MainFrame::OnRequestDockWindow (CodeBlocksDockEvent & event) private
Definition at line 4903 of file main.cpp.
References _T, wxAuiPaneInfo::BestSize(), wxAuiPaneInfo::Bottom(), wxAuiPaneInfo::Caption(), wxAuiPaneInfo::CloseButton(), CodeBlocksDockEvent::column, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsBottom, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::dsLeft, CodeBlocksDockEvent::dsRight, CodeBlocksDockEvent::dsTop, CodeBlocksDockEvent::dsUndefined, wxAuiPaneInfo::Float(), CodeBlocksDockEvent::floatingPos, wxAuiPaneInfo::FloatingPosition(), wxAuiPaneInfo::FloatingSize(), CodeBlocksDockEvent::floatingSize, wxString::Format(), CodeBlocksDockEvent::hideable, Manager::IsAppShuttingDown(), wxString::IsEmpty(), wxAuiPaneInfo::Layer(), wxAuiPaneInfo::Left(), CodeBlocksDockEvent::minimumSize, wxAuiPaneInfo::MinSize(), wxAuiPaneInfo::Name(), wxAuiPaneInfo::Position(), CodeBlocksDockEvent::pWindow, wxAuiPaneInfo::Right(), wxAuiPaneInfo::Row(), CodeBlocksDockEvent::row, wxAuiPaneInfo::Show(), CodeBlocksDockEvent::shown, CodeBlocksDockEvent::stretch, CodeBlocksDockEvent::title, and wxAuiPaneInfo::Top().
Referenced by RegisterEvents().
OnRequestHideDockWindow()
void MainFrame::OnRequestHideDockWindow (CodeBlocksDockEvent & event) private
Definition at line 4964 of file main.cpp.
References cbEVT_DOCK_WINDOW_VISIBILITY, Manager::Get(), Manager::ProcessEvent(), and CodeBlocksDockEvent::pWindow.
Referenced by RegisterEvents().
OnRequestShowDockWindow()
void MainFrame::OnRequestShowDockWindow (CodeBlocksDockEvent & event) private
Definition at line 4954 of file main.cpp.
References cbEVT_DOCK_WINDOW_VISIBILITY, Manager::Get(), Manager::ProcessEvent(), and CodeBlocksDockEvent::pWindow.
Referenced by RegisterEvents().
OnRequestUndockWindow()
void MainFrame::OnRequestUndockWindow (CodeBlocksDockEvent & event) private
Definition at line 4944 of file main.cpp.
References wxAuiPaneInfo::IsOk(), and CodeBlocksDockEvent::pWindow.
Referenced by RegisterEvents().
OnSearchFind()
void MainFrame::OnSearchFind (wxCommandEvent & event) private
Definition at line 3976 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and idSearchFindInFiles.
OnSearchFindNext()
void MainFrame::OnSearchFindNext (wxCommandEvent & event) private
Definition at line 3984 of file main.cpp.
References idSearchFindPrevious.
OnSearchFindNextSelected()
void MainFrame::OnSearchFindNextSelected (wxCommandEvent & event) private
Definition at line 3990 of file main.cpp.
References idSearchFindSelectedPrevious.
OnSearchGotoLine()
void MainFrame::OnSearchGotoLine (wxCommandEvent & event) private
Remarks
We use wxGetText instead of wxGetNumber because wxGetNumber must provide an initial line number...which doesn't make sense, and just keeps the user deleting the initial line number everytime he instantiates the dialog. However, this is just a temporary hack, because the default dialog used isn't that suitable either.
Definition at line 4004 of file main.cpp.
References _(), _T, cbGetTextFromUser(), wxString::Format(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), wxScintilla::GetLength(), cbEditor::GotoLine(), wxScintilla::LineFromPosition(), wxString::ToLong(), and cbEditor::UnfoldBlockFromLine().
OnSearchGotoNextChanged()
void MainFrame::OnSearchGotoNextChanged (wxCommandEvent & event) private
Definition at line 4032 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::GotoNextChanged().
OnSearchGotoPrevChanged()
void MainFrame::OnSearchGotoPrevChanged (wxCommandEvent & event) private
Definition at line 4039 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::GotoPreviousChanged().
OnSearchMenuUpdateUI()
void MainFrame::OnSearchMenuUpdateUI (wxUpdateUIEvent & event) private
Definition at line 4283 of file main.cpp.
References _T, cbEditor::CanRedo(), cbEditor::CanUndo(), wxMenuBar::Enable(), Manager::Get(), EditorManager::GetBuiltinEditor(), Manager::GetConfigManager(), Manager::GetEditorManager(), idSearchFind, idSearchFindNext, idSearchFindPrevious, idSearchFindSelectedNext, idSearchFindSelectedPrevious, idSearchGotoLine, idSearchGotoNextChanged, idSearchGotoPreviousChanged, idSearchReplace, Manager::IsAppShuttingDown(), and ConfigManager::ReadBool().
OnSearchReplace()
void MainFrame::OnSearchReplace (wxCommandEvent & event) private
Definition at line 3996 of file main.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and idSearchReplaceInFiles.
OnSettingsCompiler()
void MainFrame::OnSettingsCompiler (wxCommandEvent & event) private
Definition at line 4765 of file main.cpp.
References cbEVT_SETTINGS_CHANGED, cbSettingsType::Compiler, Manager::Get(), PlaceWindow(), Manager::ProcessEvent(), wxDialog::ShowModal(), and wxID_OK.
OnSettingsDebugger()
void MainFrame::OnSettingsDebugger (wxCommandEvent & event) private
Definition at line 4777 of file main.cpp.
References cbEVT_SETTINGS_CHANGED, cbSettingsType::Debugger, Manager::Get(), PlaceWindow(), Manager::ProcessEvent(), wxDialog::ShowModal(), and wxID_OK.
OnSettingsEditor()
void MainFrame::OnSettingsEditor (wxCommandEvent & event) private
Definition at line 4744 of file main.cpp.
References cbEVT_SETTINGS_CHANGED, cbSettingsType::Editor, Manager::Get(), Manager::GetEditorManager(), PlaceWindow(), Manager::ProcessEvent(), EditorManager::RecreateOpenEditorStyles(), wxDialog::ShowModal(), wxBeginBusyCursor(), wxEndBusyCursor(), and wxID_OK.
OnSettingsEnvironment()
void MainFrame::OnSettingsEnvironment (wxCommandEvent & event) private
Definition at line 4711 of file main.cpp.
References _(), _T, cbEVT_SETTINGS_CHANGED, cbMessageBox(), cbSettingsType::Environment, Manager::Get(), Manager::GetCCManager(), Manager::GetConfigManager(), Manager::GetEditorManager(), Manager::GetLogManager(), LogManager::NotifyUpdate(), PlaceWindow(), Manager::ProcessEvent(), ConfigManager::ReadBool(), EditorManager::RecreateOpenEditorStyles(), CCManager::UpdateEnvSettings(), wxICON_INFORMATION, and wxID_OK.
OnSettingsKeyBindings()
void MainFrame::OnSettingsKeyBindings (wxCommandEvent & event) private
OnSettingsPlugins()
void MainFrame::OnSettingsPlugins (wxCommandEvent & event) private
Definition at line 4789 of file main.cpp.
References cbEVT_SETTINGS_CHANGED, Manager::Get(), cbSettingsType::Plugins, Manager::ProcessEvent(), and wxID_OK.
OnSettingsScripting()
void MainFrame::OnSettingsScripting (wxCommandEvent & event) private
Definition at line 4799 of file main.cpp.
References wxDialog::ShowModal(), and wxID_OK.
OnShiftTab()
void MainFrame::OnShiftTab (wxCommandEvent & event) private
Definition at line 4875 of file main.cpp.
References cbEditor::DoUnIndent(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), and Manager::GetEditorManager().
OnShowLogManager()
void MainFrame::OnShowLogManager (CodeBlocksLogEvent & event) private
Definition at line 5053 of file main.cpp.
References _T, and Manager::Get().
Referenced by RegisterEvents().
OnSize()
void MainFrame::OnSize (wxSizeEvent & event) private
Definition at line 2699 of file main.cpp.
References wxRect::GetPosition(), wxRect::GetSize(), and wxRect::SetPosition().
Referenced by cbStatusBar::cbStatusBar().
OnStartHereLink()
void MainFrame::OnStartHereLink (wxCommandEvent & event) private
Definition at line 2200 of file main.cpp.
References _T, wxString::AfterLast(), RecentItemsList::AskToRemoveFileFromHistory(), wxString::empty(), RecentItemsList::GetHistoryFile(), idFileNewProject, wxString::IsSameAs(), wxString::StartsWith(), and wxString::ToULong().
OnSwitchTabs()
void MainFrame::OnSwitchTabs (wxCommandEvent & event) private
Definition at line 4555 of file main.cpp.
References _(), _T, wxSwitcherItems::AddGroup(), wxSwitcherItems::AddItem(), Manager::Get(), Manager::GetEditorManager(), wxSwitcherItem::GetId(), wxSwitcherItems::GetIndexForFocus(), wxSwitcherItems::GetItem(), wxSwitcherItems::GetItemCount(), EditorManager::GetNotebook(), wxAuiNotebook::GetPage(), wxAuiNotebook::GetPageBitmap(), wxAuiNotebook::GetPageCount(), wxAuiNotebook::GetPageIndex(), wxAuiNotebook::GetPageText(), wxSwitcherDialog::GetSelection(), wxSwitcherItem::GetWindow(), cbNotebookStack::next, NULL, wxSwitcherDialog::SetExtraNavigationKey(), wxSwitcherDialog::SetModifierKey(), wxAuiNotebook::SetSelection(), wxSwitcherItems::SetSelection(), wxDialog::ShowModal(), cbNotebookStack::window, wxGetApp(), wxID_OK, WXK_ALT, wxNOT_FOUND, and wxT.
OnSwitchToLogWindow()
void MainFrame::OnSwitchToLogWindow (CodeBlocksLogEvent & event) private
Definition at line 5031 of file main.cpp.
References CodeBlocksLogEvent::logger, and CodeBlocksLogEvent::window.
Referenced by RegisterEvents().
OnToggleBar()
void MainFrame::OnToggleBar (wxCommandEvent & event) private
Definition at line 4474 of file main.cpp.
References PluginManager::FindPluginByName(), Manager::Get(), Manager::GetPluginManager(), idViewLogManager, idViewManager, idViewToolDebugger, idViewToolMain, and wxString::IsEmpty().
Referenced by DoAddPluginToolbar(), and PluginsUpdated().
OnToggleFullScreen()
void MainFrame::OnToggleFullScreen (wxCommandEvent & event) private
Definition at line 4636 of file main.cpp.
References wxSize::GetHeight(), wxSize::GetWidth(), wxFULLSCREEN_NOBORDER, wxFULLSCREEN_NOCAPTION, and wxFULLSCREEN_NOTOOLBAR.
OnToggleStartPage()
void MainFrame::OnToggleStartPage (wxCommandEvent & event) private
Definition at line 4625 of file main.cpp.
References g_StartHereTitle, Manager::Get(), and NULL.
OnToggleStatusBar()
void MainFrame::OnToggleStatusBar (wxCommandEvent & event) private
Definition at line 4519 of file main.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), ConfigManager::ReadBool(), and ConfigManager::Write().
OnToolBarRightClick()
void MainFrame::OnToolBarRightClick (wxCommandEvent & event) private
Definition at line 5146 of file main.cpp.
Referenced by CreateToolbars(), DoAddPlugin(), OnApplicationClose(), and OnPluginUnloaded().
OnUnlockLogManager()
void MainFrame::OnUnlockLogManager (CodeBlocksLogEvent & event) private
Definition at line 5079 of file main.cpp.
References _T, and Manager::Get().
Referenced by RegisterEvents().
OnViewHideEditorTabs()
void MainFrame::OnViewHideEditorTabs (wxCommandEvent & event) private
Definition at line 3960 of file main.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), Manager::GetEditorManager(), EditorManager::GetNotebook(), wxAuiNotebook::GetTabCtrlHeight(), wxAuiNotebook::SetTabCtrlHeight(), and ConfigManager::Write().
OnViewLayout()
void MainFrame::OnViewLayout (wxCommandEvent & event) private
Definition at line 3855 of file main.cpp.
Referenced by SaveViewLayout().
OnViewLayoutDelete()
void MainFrame::OnViewLayoutDelete (wxCommandEvent & event) private
Definition at line 3876 of file main.cpp.
References _(), cbMessageBox(), wxMenu::Delete(), wxString::find(), wxMenu::FindItem(), wxString::Format(), gDefaultLayout, gDefaultLayoutData, gDefaultMessagePaneLayoutData, gMinimalLayout, gMinimalLayoutData, gMinimalMessagePaneLayoutData, idViewLayoutSave, wxString::wx_str(), wxICON_INFORMATION, wxICON_QUESTION, wxID_YES, wxNO_DEFAULT, wxNOT_FOUND, and wxYES_NO.
OnViewLayoutSave()
void MainFrame::OnViewLayoutSave (wxCommandEvent & event) private
Definition at line 3860 of file main.cpp.
References _(), _T, cbGetTextFromUser(), wxString::empty(), Manager::Get(), Manager::GetConfigManager(), wxString::IsEmpty(), and ConfigManager::Read().
OnViewMenuUpdateUI()
void MainFrame::OnViewMenuUpdateUI (wxUpdateUIEvent & event) private
Definition at line 4249 of file main.cpp.
References wxMenuBar::Check(), wxMenuBar::Enable(), wxMenu::FindItem(), g_StartHereTitle, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), idViewFocusEditor, idViewFocusLogsAndOthers, idViewFocusManagement, idViewFullScreen, idViewHideEditorTabs, idViewLogManager, idViewManager, idViewScriptConsole, idViewStartPage, idViewStatusbar, idViewToolMain, Manager::IsAppShuttingDown(), and NULL.
OnViewScriptConsole()
void MainFrame::OnViewScriptConsole (wxCommandEvent & event) private
Definition at line 3955 of file main.cpp.
OnViewToolbarsFit()
void MainFrame::OnViewToolbarsFit (wxCommandEvent & event) private
Definition at line 4462 of file main.cpp.
OnViewToolbarsOptimize()
void MainFrame::OnViewToolbarsOptimize (wxCommandEvent & event) private
Definition at line 4468 of file main.cpp.
Open()
bool MainFrame::Open (const wxString & filename, bool addToHistory = true)
Definition at line 1725 of file main.cpp.
References _T, LogManager::DebugLog(), wxString::Format(), Manager::Get(), wxFileName::GetFullPath(), Manager::GetLogManager(), LogManager::LogError(), wxFileName::Normalize(), wxString::wx_str(), and wxT.
Referenced by CodeBlocksApp::LoadDelayedFiles(), and RegisterScriptFunctions().
OpenGeneric()
bool MainFrame::OpenGeneric (const wxString & filename, bool addToHistory = true)
Definition at line 1754 of file main.cpp.
References _(), _T, cbMessageBox(), wxFileName::ClearExt(), FileTypeOf(), ftCodeBlocksProject, ftCodeBlocksWorkspace, ftHeader, ftResource, ftSource, ftTemplateSource, Manager::Get(), wxFileName::GetFullPath(), PluginManager::GetMIMEHandlerForFile(), Manager::GetPluginManager(), Manager::GetProjectManager(), wxString::IsEmpty(), ProjectManager::IsOpen(), ProjectManager::LoadWorkspace(), cbMimePlugin::OpenFile(), wxFileName::SetExt(), ProjectManager::SetProject(), and wxICON_ERROR.
operator=()
MainFrame& MainFrame::operator= (cb_unused const MainFrame & rhs) inline
Definition at line 64 of file main.h.
References _T, and cbThrow.
PluginsUpdated()
void MainFrame::PluginsUpdated (cbPlugin * plugin, int status) protected
Definition at line 900 of file main.cpp.
References wxMenuItem::Check(), wxMenu::FindItem(), Manager::Get(), PluginManager::GetPluginInfo(), Manager::GetPluginManager(), PluginManager::GetPlugins(), idViewToolMain, IsWindowReallyShown(), OnToggleBar(), PluginInfo::title, and wxNOT_FOUND.
PopupToggleToolbarMenu()
void MainFrame::PopupToggleToolbarMenu () private
Definition at line 5152 of file main.cpp.
References _(), wxMenu::Append(), wxMenu::FindItem(), wxMenu::FindItemByPosition(), wxMenuBar::FindMenu(), Manager::Get(), Manager::GetAppFrame(), wxMenuItem::GetHelp(), wxMenuItem::GetId(), wxMenuItem::GetItemLabelText(), wxMenuItem::GetKind(), wxMenuBar::GetMenu(), wxMenu::GetMenuItemCount(), and wxNOT_FOUND.
RecreateMenuBar()
void MainFrame::RecreateMenuBar () protected
Definition at line 939 of file main.cpp.
RegisterEvents()
void MainFrame::RegisterEvents () protected
Definition at line 674 of file main.cpp.
References cbEVT_ADD_DOCK_WINDOW, cbEVT_ADD_LOG_WINDOW, cbEVT_DOCK_WINDOW_VISIBILITY, cbEVT_EDITOR_ACTIVATED, cbEVT_EDITOR_CLOSE, cbEVT_EDITOR_MODIFIED, cbEVT_EDITOR_OPEN, cbEVT_EDITOR_SAVE, cbEVT_EDITOR_UPDATE_UI, cbEVT_GET_ACTIVE_LOG_WINDOW, cbEVT_HIDE_DOCK_WINDOW, cbEVT_HIDE_LOG_MANAGER, cbEVT_HIDE_LOG_WINDOW, cbEVT_LOCK_LOG_MANAGER, cbEVT_PLUGIN_ATTACHED, cbEVT_PLUGIN_INSTALLED, cbEVT_PLUGIN_RELEASED, cbEVT_PLUGIN_UNINSTALLED, cbEVT_PROJECT_ACTIVATE, cbEVT_PROJECT_CLOSE, cbEVT_PROJECT_OPEN, cbEVT_QUERY_VIEW_LAYOUT, cbEVT_REMOVE_DOCK_WINDOW, cbEVT_REMOVE_LOG_WINDOW, cbEVT_SHOW_DOCK_WINDOW, cbEVT_SHOW_LOG_MANAGER, cbEVT_SWITCH_TO_LOG_WINDOW, cbEVT_SWITCH_VIEW_LAYOUT, cbEVT_UNLOCK_LOG_MANAGER, cbEVT_UPDATE_VIEW_LAYOUT, Manager::Get(), OnAddLogWindow(), OnDockWindowVisibility(), OnEditorActivated(), OnEditorClosed(), OnEditorModified(), OnEditorOpened(), OnEditorSaved(), OnEditorUpdateUI(), OnGetActiveLogWindow(), OnHideLogManager(), OnHideLogWindow(), OnLayoutQuery(), OnLayoutSwitch(), OnLayoutUpdate(), OnLockLogManager(), OnPluginInstalled(), OnPluginLoaded(), OnPluginUninstalled(), OnPluginUnloaded(), OnProjectActivated(), OnProjectClosed(), OnProjectOpened(), OnRemoveLogWindow(), OnRequestDockWindow(), OnRequestHideDockWindow(), OnRequestShowDockWindow(), OnRequestUndockWindow(), OnShowLogManager(), OnSwitchToLogWindow(), OnUnlockLogManager(), and Manager::RegisterEventSink().
RegisterScriptFunctions()
void MainFrame::RegisterScriptFunctions () protected
Definition at line 852 of file main.cpp.
References Open().
RemoveEditorFromWindowMenu()
void MainFrame::RemoveEditorFromWindowMenu (const wxString & filename) protected
RunStartupScripts()
void MainFrame::RunStartupScripts () protected
Definition at line 860 of file main.cpp.
References _(), _T, ScriptingManager::DisplayErrors(), ScriptEntry::enabled, ConfigManager::EnumerateKeys(), F(), Manager::Get(), Manager::GetConfigManager(), wxArrayString::GetCount(), Manager::GetLogManager(), Manager::GetScriptingManager(), wxString::IsEmpty(), wxFileName::IsRelative(), ScriptingManager::LoadScript(), ConfigManager::LocateDataFile(), LogManager::LogWarning(), ScriptEntry::menu, ConfigManager::Read(), ScriptEntry::registered, ScriptingManager::RegisterScriptMenu(), ScriptEntry::script, sdScriptsGlobal, sdScriptsUser, ScriptEntry::SerializeIn(), and wxString::wx_str().
SaveViewLayout()
void MainFrame::SaveViewLayout (const wxString & name, const wxString & layout, const wxString & layoutMP, bool select = false) protected
Definition at line 1431 of file main.cpp.
References _(), wxMenu::FindItem(), wxString::Format(), wxMenu::GetMenuItemCount(), idViewLayoutSave, wxMenu::InsertCheckItem(), wxString::IsEmpty(), OnViewLayout(), wxString::wx_str(), wxNewId(), and wxNOT_FOUND.
SaveWindowState()
void MainFrame::SaveWindowState () protected
Definition at line 1349 of file main.cpp.
References _T, ConfigManager::DeleteSubPath(), ConfigManager::EnumerateSubPaths(), wxString::Format(), Manager::Get(), Manager::GetConfigManager(), wxArrayString::GetCount(), wxDisplay::GetFromWindow(), and ConfigManager::Write().
ScanForPlugins()
void MainFrame::ScanForPlugins () protected
Definition at line 1183 of file main.cpp.
References _(), cbEVT_PLUGIN_LOADING_COMPLETE, Manager::Get(), Manager::GetLogManager(), Manager::GetPluginManager(), ConfigManager::GetPluginsFolder(), PluginManager::LoadAllPlugins(), LogManager::Log(), PluginManager::NotifyPlugins(), and PluginManager::ScanForPlugins().
SetChecksForViewToolbarsMenu()
void MainFrame::SetChecksForViewToolbarsMenu (wxMenu & menu) private
Definition at line 5179 of file main.cpp.
References wxMenuItem::Check(), wxMenu::Check(), PluginManager::FindPluginByName(), Manager::Get(), wxMenuItem::GetId(), wxMenu::GetMenuItemCount(), wxMenu::GetMenuItems(), Manager::GetPluginManager(), idViewToolDebugger, idViewToolMain, and wxString::IsEmpty().
SetupDebuggerUI()
void MainFrame::SetupDebuggerUI () protected
Definition at line 828 of file main.cpp.
References DECLARE_INSTANCE_TYPE(), Manager::Get(), Manager::GetAppWindow(), Manager::GetDebuggerManager(), Manager::IsBatchBuild(), and DebuggerManager::SetInterfaceFactory().
SetupGUILogging()
void MainFrame::SetupGUILogging () protected
Definition at line 783 of file main.cpp.
References _(), _T, LogManager::app_log, cbFileDropTarget::cbFileDropTarget(), Logger::CreateControl(), LogManager::debug_log, Manager::Get(), Manager::GetConfigManager(), LogSlot::GetLogger(), Manager::GetLogManager(), wxSize::GetWidth(), LogSlot::icon, Manager::IsBatchBuild(), LogManager::max_logs, LogManager::NotifyUpdate(), ConfigManager::ReadInt(), LogManager::SetLog(), LogManager::Slot(), LogSlot::title, wxEXPAND, wxT, and wxVERTICAL.
ShowHideScriptConsole()
void MainFrame::ShowHideScriptConsole () protected
Definition at line 2190 of file main.cpp.
References cbEVT_HIDE_DOCK_WINDOW, cbEVT_SHOW_DOCK_WINDOW, Manager::Get(), Manager::IsBatchBuild(), IsWindowReallyShown(), Manager::ProcessEvent(), and CodeBlocksDockEvent::pWindow.
ShowHideStartPage()
void MainFrame::ShowHideStartPage (bool forceHasProject = false, int forceState = 0) protected
Definition at line 2146 of file main.cpp.
References _T, g_StartHereTitle, Manager::Get(), Manager::GetConfigManager(), EditorManager::GetEditor(), Manager::GetEditorManager(), Manager::GetProjectManager(), ProjectManager::GetProjects(), Manager::IsBatchBuild(), and ConfigManager::ReadBool().
ShowOpenFileDialog()
wxString MainFrame::ShowOpenFileDialog (const wxString & caption, const wxString & filter)
Definition at line 1739 of file main.cpp.
References wxFileDialog::GetPath(), PlaceWindow(), wxFileDialog::ShowModal(), wxEmptyString, wxFD_OPEN, and wxID_OK.
ShowTips()
void MainFrame::ShowTips (bool forceShow = false)
Definition at line 715 of file main.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), wxTipProvider::GetCurrentTip(), ConfigManager::GetDataFolder(), ConfigManager::ReadBool(), ConfigManager::ReadInt(), ConfigManager::Write(), wxCreateFileTipProvider(), and wxShowTip().
Referenced by CodeBlocksApp::OnInit().
StartupDone()
void MainFrame::StartupDone ()
Definition at line 5125 of file main.cpp.
Referenced by CodeBlocksApp::OnInit().
TerminateRecentFilesHistory()
void MainFrame::TerminateRecentFilesHistory () protected
Definition at line 2248 of file main.cpp.
Member Data Documentation
m_AutoHideLockCounter
int MainFrame::m_AutoHideLockCounter protected
Definition at line 385 of file main.h.
m_debuggerMenuHandler
DebuggerMenuHandler* MainFrame::m_debuggerMenuHandler protected
Definition at line 402 of file main.h.
m_debuggerToolbarHandler
DebuggerToolbarHandler* MainFrame::m_debuggerToolbarHandler protected
Definition at line 403 of file main.h.
m_filesHistory
RecentItemsList MainFrame::m_filesHistory protected
Definition at line 361 of file main.h.
m_findReplace
FindReplace MainFrame::m_findReplace protected
Definition at line 405 of file main.h.
m_HelpPluginsMenu
wxMenu* MainFrame::m_HelpPluginsMenu protected
Definition at line 378 of file main.h.
m_InitiatedShutdown
bool MainFrame::m_InitiatedShutdown protected
Definition at line 383 of file main.h.
m_LastCtrlAltTabWindow
int MainFrame::m_LastCtrlAltTabWindow protected
Last window focussed in the cycle 1 = Mgmt. panel, 2 = Editor, 3 = Logs & others.
Definition at line 386 of file main.h.
m_LastLayoutData
wxString MainFrame::m_LastLayoutData protected
Definition at line 390 of file main.h.
m_LastLayoutIsTemp
bool MainFrame::m_LastLayoutIsTemp protected
Definition at line 392 of file main.h.
m_LastLayoutName
wxString MainFrame::m_LastLayoutName protected
Definition at line 389 of file main.h.
m_LastMessagePaneLayoutData
wxString MainFrame::m_LastMessagePaneLayoutData protected
Definition at line 391 of file main.h.
m_LayoutManager
wxAuiManager MainFrame::m_LayoutManager private
Definition at line 72 of file main.h.
m_LayoutMessagePane
LayoutViewsMap MainFrame::m_LayoutMessagePane private
Definition at line 74 of file main.h.
m_LayoutViews
LayoutViewsMap MainFrame::m_LayoutViews private
Definition at line 73 of file main.h.
m_MenuIDToScript
MenuIDToScript MainFrame::m_MenuIDToScript protected
Definition at line 397 of file main.h.
m_pAccel
wxAcceleratorTable* MainFrame::m_pAccel
Definition at line 78 of file main.h.
m_pBatchBuildDialog
wxScrollingDialog* MainFrame::m_pBatchBuildDialog protected
Definition at line 399 of file main.h.
m_pCloseFullScreenBtn
wxButton* MainFrame::m_pCloseFullScreenBtn protected
"Close FullScreen" button. Only shown when in FullScreen view
Definition at line 364 of file main.h.
m_pEdMan
EditorManager* MainFrame::m_pEdMan protected
Definition at line 366 of file main.h.
m_pHighlightButton
wxButton* MainFrame::m_pHighlightButton protected
Definition at line 400 of file main.h.
m_pInfoPane
InfoPane* MainFrame::m_pInfoPane protected
Definition at line 370 of file main.h.
m_pLogMan
LogManager* MainFrame::m_pLogMan protected
Definition at line 369 of file main.h.
m_PluginIDsMap
PluginIDsMap MainFrame::m_PluginIDsMap protected
Definition at line 375 of file main.h.
m_PluginsMenu
wxMenu* MainFrame::m_PluginsMenu protected
Definition at line 377 of file main.h.
m_PluginsTools
PluginToolbarsMap MainFrame::m_PluginsTools protected
Definition at line 373 of file main.h.
m_pPrjMan
ProjectManager* MainFrame::m_pPrjMan protected
Definition at line 367 of file main.h.
m_pPrjManUI
cbProjectManagerUI* MainFrame::m_pPrjManUI protected
Definition at line 368 of file main.h.
m_PreviousLayoutName
wxString MainFrame::m_PreviousLayoutName protected
Definition at line 388 of file main.h.
m_projectsHistory
RecentItemsList MainFrame::m_projectsHistory protected
Definition at line 361 of file main.h.
m_pScriptConsole
wxWindow* MainFrame::m_pScriptConsole protected
Definition at line 394 of file main.h.
m_pToolbar
wxToolBar* MainFrame::m_pToolbar protected
Definition at line 372 of file main.h.
m_ScanningForPlugins
bool MainFrame::m_ScanningForPlugins protected
Definition at line 379 of file main.h.
m_SmallToolBar
bool MainFrame::m_SmallToolBar protected
Definition at line 381 of file main.h.
m_StartupDone
bool MainFrame::m_StartupDone protected
Definition at line 382 of file main.h.
m_ToolsMenu
wxMenu* MainFrame::m_ToolsMenu protected
Definition at line 376 of file main.h.
The documentation for this class was generated from the following files:
main.h
main.cpp