Code::Blocks: GenericSingleChoiceList Class Reference
GenericSingleChoiceList Class Reference
#include <genericsinglechoicelist.h>
Public Member Functions
GenericSingleChoiceList (wxWindow *parent, wxWindowID id=-1)
virtual ~GenericSingleChoiceList ()
void SetChoices (const wxArrayString &choices, int defChoice)
int GetChoice () const
void SetChoice (int choice)
void SetDescription (const wxString &descr)
Static Public Attributes
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_LISTBOX1 = wxNewId()
Protected Attributes
wxListBox * GenericChoiceList
wxStaticText * lblDescr
Detailed Description
Definition at line 20 of file genericsinglechoicelist.h.
Constructor & Destructor Documentation
GenericSingleChoiceList()
GenericSingleChoiceList::GenericSingleChoiceList (wxWindow * parent, wxWindowID id = -1)
Definition at line 32 of file genericsinglechoicelist.cpp.
References _(), _T, wxBoxSizer::Add(), wxBoxSizer::Fit(), wxBoxSizer::SetSizeHints(), wxALL, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEXPAND, wxFIXED_MINSIZE, wxLB_HSCROLL, wxLB_SINGLE, wxTAB_TRAVERSAL, and wxVERTICAL.
~GenericSingleChoiceList()
GenericSingleChoiceList::~GenericSingleChoiceList () virtual
Definition at line 54 of file genericsinglechoicelist.cpp.
Member Function Documentation
GetChoice()
int GenericSingleChoiceList::GetChoice () const inline
Definition at line 28 of file genericsinglechoicelist.h.
References GenericChoiceList.
Referenced by WizGenericSingleChoiceList::GetChoice(), and WizGenericSingleChoiceList::OnPageChanging().
SetChoice()
void GenericSingleChoiceList::SetChoice (int choice) inline
Definition at line 29 of file genericsinglechoicelist.h.
References GenericChoiceList.
Referenced by WizGenericSingleChoiceList::SetChoice().
SetChoices()
void GenericSingleChoiceList::SetChoices (const wxArrayString & choices, int defChoice)
Definition at line 58 of file genericsinglechoicelist.cpp.
References GenericChoiceList, and wxArrayString::GetCount().
Referenced by WizGenericSingleChoiceList::WizGenericSingleChoiceList().
SetDescription()
void GenericSingleChoiceList::SetDescription (const wxString & descr) inline
Definition at line 30 of file genericsinglechoicelist.h.
References lblDescr.
Referenced by WizGenericSingleChoiceList::WizGenericSingleChoiceList().
Member Data Documentation
GenericChoiceList
wxListBox* GenericSingleChoiceList::GenericChoiceList protected
Definition at line 49 of file genericsinglechoicelist.h.
Referenced by GetChoice(), SetChoice(), and SetChoices().
ID_LISTBOX1
const long GenericSingleChoiceList::ID_LISTBOX1 = wxNewId() static
Definition at line 40 of file genericsinglechoicelist.h.
ID_STATICTEXT1
const long GenericSingleChoiceList::ID_STATICTEXT1 = wxNewId() static
Definition at line 39 of file genericsinglechoicelist.h.
lblDescr
wxStaticText* GenericSingleChoiceList::lblDescr protected
Definition at line 50 of file genericsinglechoicelist.h.
Referenced by SetDescription().
The documentation for this class was generated from the following files:
genericsinglechoicelist.h
genericsinglechoicelist.cpp