Code::Blocks: Expression Class Reference
Expression Class Reference
#include <expression.h>
Public Member Functions
Expression ()
void AddToInfixExpression (wxString token)
void ConvertInfixToPostfix ()
bool CalcPostfix ()
long GetResult () const
bool GetStatus () const
void Clear ()
Private Types
typedef std::vector< ExpressionNode > PostfixVector
typedef std::vector< wxString > InfixVector
Private Member Functions
long Calculate (ExpressionNode::ExpressionNodeType type, long first, long second)
long CalculateUnary (ExpressionNode::ExpressionNodeType type, long value)
Private Attributes
PostfixVector m_PostfixExpression
InfixVector m_InfixExpression
bool m_Status
long m_Result
Detailed Description
Definition at line 74 of file expression.h.
Member Typedef Documentation
InfixVector
typedef std::vector<wxString> Expression::InfixVector private
Definition at line 97 of file expression.h.
PostfixVector
typedef std::vector<ExpressionNode> Expression::PostfixVector private
Definition at line 96 of file expression.h.
Constructor & Destructor Documentation
Expression()
Expression::Expression () inline
Definition at line 78 of file expression.h.
Member Function Documentation
AddToInfixExpression()
void Expression::AddToInfixExpression (wxString token)
Definition at line 232 of file expression.cpp.
References ExpressionNode::IsBinaryOperator(), and wxString::IsEmpty().
Referenced by Tokenizer::CalcConditionExpression(), and ParserThread::CalcEnumExpression().
CalcPostfix()
bool Expression::CalcPostfix ()
Definition at line 359 of file expression.cpp.
References _T, ExpressionNode::GetTokenValue(), ExpressionNode::GetType(), ExpressionNode::IsUnaryOperator(), ExpressionNode::Numeric, and TRACE.
Referenced by Tokenizer::CalcConditionExpression(), and ParserThread::CalcEnumExpression().
Calculate()
long Expression::Calculate (ExpressionNode::ExpressionNodeType type, long first, long second) private
Definition at line 431 of file expression.cpp.
References ExpressionNode::And, ExpressionNode::BitwiseAnd, ExpressionNode::BitwiseOr, ExpressionNode::Divide, ExpressionNode::Equal, ExpressionNode::GT, ExpressionNode::GTOrEqual, ExpressionNode::LParenthesis, ExpressionNode::LShift, ExpressionNode::LT, ExpressionNode::LTOrEqual, ExpressionNode::Mod, ExpressionNode::Multiply, ExpressionNode::Not, ExpressionNode::Numeric, ExpressionNode::Or, ExpressionNode::Plus, ExpressionNode::Power, ExpressionNode::RParenthesis, ExpressionNode::RShift, ExpressionNode::Subtract, ExpressionNode::Unequal, and ExpressionNode::Unknown.
CalculateUnary()
long Expression::CalculateUnary (ExpressionNode::ExpressionNodeType type, long value) private
Definition at line 482 of file expression.cpp.
References ExpressionNode::And, ExpressionNode::BitwiseAnd, ExpressionNode::BitwiseOr, ExpressionNode::Divide, ExpressionNode::Equal, ExpressionNode::GT, ExpressionNode::GTOrEqual, ExpressionNode::LParenthesis, ExpressionNode::LShift, ExpressionNode::LT, ExpressionNode::LTOrEqual, ExpressionNode::Mod, ExpressionNode::Multiply, ExpressionNode::Not, ExpressionNode::Numeric, ExpressionNode::Or, ExpressionNode::Plus, ExpressionNode::Power, ExpressionNode::RParenthesis, ExpressionNode::RShift, ExpressionNode::Subtract, ExpressionNode::Unequal, and ExpressionNode::Unknown.
Clear()
void Expression::Clear ()
Definition at line 226 of file expression.cpp.
Referenced by ParserThread::CalcEnumExpression().
ConvertInfixToPostfix()
void Expression::ConvertInfixToPostfix ()
Definition at line 250 of file expression.cpp.
References _T, ExpressionNode::GetPriority(), ExpressionNode::GetType(), ExpressionNode::Initialize(), ExpressionNode::IsUnaryNode(), ExpressionNode::LParenthesis, ExpressionNode::Numeric, ExpressionNode::RParenthesis, ExpressionNode::SetUnaryOperator(), TRACE, ExpressionNode::Unknown, and wxString::wx_str().
Referenced by Tokenizer::CalcConditionExpression(), and ParserThread::CalcEnumExpression().
GetResult()
long Expression::GetResult () const inline
Definition at line 87 of file expression.h.
Referenced by Tokenizer::CalcConditionExpression(), and ParserThread::CalcEnumExpression().
GetStatus()
bool Expression::GetStatus () const inline
Definition at line 88 of file expression.h.
Referenced by Tokenizer::CalcConditionExpression(), and ParserThread::CalcEnumExpression().
Member Data Documentation
m_InfixExpression
InfixVector Expression::m_InfixExpression private
Definition at line 100 of file expression.h.
m_PostfixExpression
PostfixVector Expression::m_PostfixExpression private
Definition at line 99 of file expression.h.
m_Result
long Expression::m_Result private
Definition at line 102 of file expression.h.
m_Status
bool Expression::m_Status private
Definition at line 101 of file expression.h.
The documentation for this class was generated from the following files:
expression.h
expression.cpp