Code::Blocks: cbCPURegistersDlg Class Reference
cbCPURegistersDlg Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbCPURegistersDlg ()
virtual wxWindow * GetWindow ()=0
virtual void Clear ()=0
virtual void SetRegisterValue (const wxString &reg_name, size_t value)=0
virtual void EnableWindow (bool enable)=0
Constructor & Destructor Documentation
cbCPURegistersDlg::~cbCPURegistersDlg () virtual
Member Function Documentation
virtual void cbCPURegistersDlg::Clear () pure virtual
Implemented in CPURegistersDlg.
virtual void cbCPURegistersDlg::EnableWindow (bool enable) pure virtual
Implemented in CPURegistersDlg.
Referenced by DebuggerManager::RefreshUI(), and DebuggerManager::SetInterfaceFactory().
virtual wxWindow* cbCPURegistersDlg::GetWindow () pure virtual
Implemented in CPURegistersDlg.
Referenced by DebugInterfaceFactory::DeleteCPURegisters(), and DebuggerManager::UpdateCPURegisters().
virtual void cbCPURegistersDlg::SetRegisterValue (const wxString & reg_name, size_t value) pure virtual
Implemented in CPURegistersDlg.
Referenced by CdbCmd_InfoRegisters::ParseOutput(), GdbCmd_InfoRegisters::ParseOutput(), and GdbCmd_InfoRegisters::ParseOutputFromOR32gdbPort().
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp