Code::Blocks: ThreadsDlg Class Reference
ThreadsDlg Class Reference
#include <threadsdlg.h>
Public Member Functions
ThreadsDlg (wxWindow *parent)
wxWindow * GetWindow ()
void Reload ()
void EnableWindow (bool enable)
Public Member Functions inherited from cbThreadsDlg
virtual ~cbThreadsDlg ()
Protected Member Functions
void OnListRightClick (wxListEvent &event)
void OnListDoubleClick (wxListEvent &event)
void OnSwitchThread (wxCommandEvent &event)
Private Member Functions
DECLARE_EVENT_TABLE ()
Private Attributes
wxListCtrl * m_list
Detailed Description
Definition at line 16 of file threadsdlg.h.
Constructor & Destructor Documentation
ThreadsDlg()
ThreadsDlg::ThreadsDlg (wxWindow * parent)
Definition at line 38 of file threadsdlg.cpp.
References _(), wxBoxSizer::Add(), Manager::Get(), Manager::GetColourManager(), ColourManager::RegisterColour(), wxALL, wxDefaultPosition, wxDefaultSize, wxEXPAND, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, wxLC_HRULES, wxLC_REPORT, wxLC_SINGLE_SEL, wxLC_VRULES, wxLIST_FORMAT_LEFT, wxLIST_FORMAT_RIGHT, wxRED, wxT, wxVERTICAL, and wxWHITE.
Member Function Documentation
DECLARE_EVENT_TABLE()
ThreadsDlg::DECLARE_EVENT_TABLE () private
Referenced by GetWindow().
EnableWindow()
void ThreadsDlg::EnableWindow (bool enable) virtual
Implements cbThreadsDlg.
Definition at line 148 of file threadsdlg.cpp.
References m_list.
Referenced by GetWindow().
GetWindow()
wxWindow* ThreadsDlg::GetWindow () inline virtual
Implements cbThreadsDlg.
Definition at line 21 of file threadsdlg.h.
References DECLARE_EVENT_TABLE(), EnableWindow(), OnListDoubleClick(), OnListRightClick(), OnSwitchThread(), and Reload().
OnListDoubleClick()
void ThreadsDlg::OnListDoubleClick (wxListEvent & event) protected
Definition at line 115 of file threadsdlg.cpp.
References OnSwitchThread().
Referenced by GetWindow().
OnListRightClick()
void ThreadsDlg::OnListRightClick (wxListEvent & event) protected
Definition at line 106 of file threadsdlg.cpp.
References _(), wxMenu::Append(), wxListCtrl::GetSelectedItemCount(), and m_list.
Referenced by GetWindow().
OnSwitchThread()
void ThreadsDlg::OnSwitchThread (wxCommandEvent & event) protected
Definition at line 121 of file threadsdlg.cpp.
References Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), wxListCtrl::GetItem(), wxListCtrl::GetNextItem(), wxListCtrl::GetSelectedItemCount(), m_list, cbDebuggerPlugin::SwitchToThread(), wxString::ToULong(), wxLIST_MASK_TEXT, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by GetWindow(), and OnListDoubleClick().
Reload()
void ThreadsDlg::Reload () virtual
Implements cbThreadsDlg.
Definition at line 59 of file threadsdlg.cpp.
References wxListCtrl::DeleteAllItems(), wxListCtrl::EnsureVisible(), wxString::Format(), Manager::Get(), DebuggerManager::GetActiveDebugger(), ColourManager::GetColour(), Manager::GetColourManager(), wxListCtrl::GetColumnCount(), Manager::GetDebuggerManager(), wxListCtrl::GetItemCount(), cbDebuggerPlugin::GetThread(), cbDebuggerPlugin::GetThreadsCount(), wxListCtrl::InsertItem(), m_list, wxListCtrl::SetColumnWidth(), wxListCtrl::SetItem(), wxListCtrl::SetItemBackgroundColour(), wxListCtrl::SetItemTextColour(), wxLIST_AUTOSIZE, and wxT.
Referenced by GetWindow().
Member Data Documentation
m_list
wxListCtrl* ThreadsDlg::m_list private
Definition at line 33 of file threadsdlg.h.
Referenced by EnableWindow(), OnListRightClick(), OnSwitchThread(), and Reload().
The documentation for this class was generated from the following files:
threadsdlg.h
threadsdlg.cpp