Code::Blocks: CPURegistersDlg Class Reference
CPURegistersDlg Class Reference
#include <cpuregistersdlg.h>
Public Member Functions
CPURegistersDlg (wxWindow *parent)
wxWindow * GetWindow ()
void Clear ()
void SetRegisterValue (const wxString &reg_name, const wxString &hexValue, const wxString &interpreted)
void EnableWindow (bool enable)
Public Member Functions inherited from cbCPURegistersDlg
virtual ~cbCPURegistersDlg ()
Protected Member Functions
int RegisterIndex (const wxString &reg_name)
void OnRefresh (wxCommandEvent &event)
Private Member Functions
DECLARE_EVENT_TABLE ()
Private Attributes
wxListCtrl * m_pList
Detailed Description
Definition at line 14 of file cpuregistersdlg.h.
Constructor & Destructor Documentation
CPURegistersDlg()
CPURegistersDlg::CPURegistersDlg (wxWindow * parent)
Definition at line 21 of file cpuregistersdlg.cpp.
References wxBoxSizer::Add(), wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, wxGROW, wxLC_REPORT, wxLC_SINGLE_SEL, and wxVERTICAL.
Member Function Documentation
Clear()
void CPURegistersDlg::Clear () virtual
Implements cbCPURegistersDlg.
Definition at line 36 of file cpuregistersdlg.cpp.
References _(), wxListCtrl::ClearAll(), wxListCtrl::DeleteAllItems(), wxListCtrl::InsertColumn(), m_pList, wxLIST_FORMAT_LEFT, and wxLIST_FORMAT_RIGHT.
Referenced by GetWindow().
DECLARE_EVENT_TABLE()
CPURegistersDlg::DECLARE_EVENT_TABLE () private
Referenced by GetWindow().
EnableWindow()
void CPURegistersDlg::EnableWindow (bool enable) virtual
Implements cbCPURegistersDlg.
Definition at line 83 of file cpuregistersdlg.cpp.
References m_pList.
Referenced by GetWindow().
GetWindow()
wxWindow* CPURegistersDlg::GetWindow () inline virtual
Implements cbCPURegistersDlg.
Definition at line 19 of file cpuregistersdlg.h.
References Clear(), DECLARE_EVENT_TABLE(), EnableWindow(), OnRefresh(), RegisterIndex(), and SetRegisterValue().
OnRefresh()
void CPURegistersDlg::OnRefresh (wxCommandEvent & event) protected
Referenced by GetWindow().
RegisterIndex()
int CPURegistersDlg::RegisterIndex (const wxString & reg_name) protected
Definition at line 47 of file cpuregistersdlg.cpp.
References wxString::CmpNoCase(), wxListCtrl::GetItemCount(), wxListCtrl::GetItemText(), and m_pList.
Referenced by GetWindow(), and SetRegisterValue().
SetRegisterValue()
void CPURegistersDlg::SetRegisterValue (const wxString & reg_name, const wxString & hexValue, const wxString & interpreted) virtual
Implements cbCPURegistersDlg.
Definition at line 57 of file cpuregistersdlg.cpp.
References wxListCtrl::GetItemCount(), wxListCtrl::InsertItem(), m_pList, RegisterIndex(), wxListCtrl::SetColumnWidth(), wxListCtrl::SetItem(), wxLIST_AUTOSIZE, and wxLIST_AUTOSIZE_USEHEADER.
Referenced by GetWindow().
Member Data Documentation
m_pList
wxListCtrl* CPURegistersDlg::m_pList private
Definition at line 31 of file cpuregistersdlg.h.
Referenced by Clear(), EnableWindow(), RegisterIndex(), and SetRegisterValue().
The documentation for this class was generated from the following files:
cpuregistersdlg.h
cpuregistersdlg.cpp