Code::Blocks: CCTreeCtrl Class Reference
CCTreeCtrl Class Reference
#include <cctreectrl.h>
Public Member Functions
CCTreeCtrl ()
CCTreeCtrl (wxWindow *parent, const wxWindowID id, const wxPoint &pos, const wxSize &size, long style)
void SetCompareFunction (const BrowserSortType type)
void RemoveDoubles (const wxTreeItemId &parent)
Public Member Functions inherited from wxTreeCtrl
wxTreeCtrl ()
wxTreeCtrl (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTR_DEFAULT_STYLE, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxTreeCtrlNameStr)
virtual ~wxTreeCtrl ()
virtual wxTreeItemId AddRoot (const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
wxTreeItemId AppendItem (const wxTreeItemId &parent, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
void AssignButtonsImageList (wxImageList *imageList)
void AssignImageList (wxImageList *imageList)
void AssignStateImageList (wxImageList *imageList)
virtual void Collapse (const wxTreeItemId &item)
void CollapseAll ()
void CollapseAllChildren (const wxTreeItemId &item)
virtual void CollapseAndReset (const wxTreeItemId &item)
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTR_DEFAULT_STYLE, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxTreeCtrlNameStr)
virtual void Delete (const wxTreeItemId &item)
virtual void DeleteAllItems ()
virtual void DeleteChildren (const wxTreeItemId &item)
virtual wxTextCtrl * EditLabel (const wxTreeItemId &item, wxClassInfo *textCtrlClass=wxCLASSINFO(wxTextCtrl))
void EnableBellOnNoMatch (bool on=true)
virtual void EndEditLabel (const wxTreeItemId &item, bool discardChanges=false)
virtual void EnsureVisible (const wxTreeItemId &item)
virtual void Expand (const wxTreeItemId &item)
void ExpandAll ()
void ExpandAllChildren (const wxTreeItemId &item)
virtual bool GetBoundingRect (const wxTreeItemId &item, wxRect &rect, bool textOnly=false) const
wxImageList * GetButtonsImageList () const
virtual size_t GetChildrenCount (const wxTreeItemId &item, bool recursively=true) const
virtual unsigned int GetCount () const
virtual wxTextCtrl * GetEditControl () const
virtual wxTreeItemId GetFirstChild (const wxTreeItemId &item, wxTreeItemIdValue &cookie) const
virtual wxTreeItemId GetFirstVisibleItem () const
virtual wxTreeItemId GetFocusedItem () const
virtual void ClearFocusedItem ()
virtual void SetFocusedItem (const wxTreeItemId &item)
wxImageList * GetImageList () const
virtual unsigned int GetIndent () const
virtual wxColour GetItemBackgroundColour (const wxTreeItemId &item) const
virtual wxTreeItemData * GetItemData (const wxTreeItemId &item) const
virtual wxFont GetItemFont (const wxTreeItemId &item) const
virtual int GetItemImage (const wxTreeItemId &item, wxTreeItemIcon which=wxTreeItemIcon_Normal) const
virtual wxTreeItemId GetItemParent (const wxTreeItemId &item) const
int GetItemState (const wxTreeItemId &item) const
virtual wxString GetItemText (const wxTreeItemId &item) const
virtual wxColour GetItemTextColour (const wxTreeItemId &item) const
virtual wxTreeItemId GetLastChild (const wxTreeItemId &item) const
virtual wxTreeItemId GetNextChild (const wxTreeItemId &item, wxTreeItemIdValue &cookie) const
virtual wxTreeItemId GetNextSibling (const wxTreeItemId &item) const
virtual wxTreeItemId GetNextVisible (const wxTreeItemId &item) const
virtual wxTreeItemId GetPrevSibling (const wxTreeItemId &item) const
virtual wxTreeItemId GetPrevVisible (const wxTreeItemId &item) const
bool GetQuickBestSize () const
virtual wxTreeItemId GetRootItem () const
virtual wxTreeItemId GetSelection () const
virtual size_t GetSelections (wxArrayTreeItemIds &selection) const
wxImageList * GetStateImageList () const
wxTreeItemId HitTest (const wxPoint &point, int &flags) const
wxTreeItemId InsertItem (const wxTreeItemId &parent, const wxTreeItemId &previous, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
wxTreeItemId InsertItem (const wxTreeItemId &parent, size_t pos, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
virtual bool IsBold (const wxTreeItemId &item) const
bool IsEmpty () const
virtual bool IsExpanded (const wxTreeItemId &item) const
virtual bool IsSelected (const wxTreeItemId &item) const
virtual bool IsVisible (const wxTreeItemId &item) const
virtual bool ItemHasChildren (const wxTreeItemId &item) const
wxTreeItemId PrependItem (const wxTreeItemId &parent, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
virtual void ScrollTo (const wxTreeItemId &item)
virtual void SelectItem (const wxTreeItemId &item, bool select=true)
void SetButtonsImageList (wxImageList *imageList)
virtual void SetImageList (wxImageList *imageList)
virtual void SetIndent (unsigned int indent)
virtual void SetItemBackgroundColour (const wxTreeItemId &item, const wxColour &col)
virtual void SetItemBold (const wxTreeItemId &item, bool bold=true)
virtual void SetItemData (const wxTreeItemId &item, wxTreeItemData *data)
virtual void SetItemDropHighlight (const wxTreeItemId &item, bool highlight=true)
virtual void SetItemFont (const wxTreeItemId &item, const wxFont &font)
virtual void SetItemHasChildren (const wxTreeItemId &item, bool hasChildren=true)
virtual void SetItemImage (const wxTreeItemId &item, int image, wxTreeItemIcon which=wxTreeItemIcon_Normal)
void SetItemState (const wxTreeItemId &item, int state)
virtual void SetItemText (const wxTreeItemId &item, const wxString &text)
virtual void SetItemTextColour (const wxTreeItemId &item, const wxColour &col)
void SetQuickBestSize (bool quickBestSize)
virtual void SetStateImageList (wxImageList *imageList)
void SetWindowStyle (long styles)
virtual void SortChildren (const wxTreeItemId &item)
virtual void Toggle (const wxTreeItemId &item)
void ToggleItemSelection (const wxTreeItemId &item)
virtual void Unselect ()
virtual void UnselectAll ()
void UnselectItem (const wxTreeItemId &item)
virtual void SelectChildren (const wxTreeItemId &parent)
Protected Member Functions
int OnCompareItems (const wxTreeItemId &item1, const wxTreeItemId &item2)
Static Protected Member Functions
static int CBAlphabetCompare (CCTreeCtrlData *lhs, CCTreeCtrlData *rhs)
static int CBKindCompare (CCTreeCtrlData *lhs, CCTreeCtrlData *rhs)
static int CBScopeCompare (CCTreeCtrlData *lhs, CCTreeCtrlData *rhs)
static int CBLineCompare (CCTreeCtrlData *lhs, CCTreeCtrlData *rhs)
static int CBNoCompare (CCTreeCtrlData *lhs, CCTreeCtrlData *rhs)
Protected Attributes
int(* Compare)(CCTreeCtrlData *lhs, CCTreeCtrlData *rhs)
Detailed Description
Definition at line 91 of file cctreectrl.h.
Constructor & Destructor Documentation
CCTreeCtrl() [1/2]
CCTreeCtrl::CCTreeCtrl ()
Definition at line 48 of file cctreectrl.cpp.
CCTreeCtrl() [2/2]
CCTreeCtrl::CCTreeCtrl (wxWindow * parent, const wxWindowID id, const wxPoint & pos, const wxSize & size, long style)
Definition at line 53 of file cctreectrl.cpp.
References CBNoCompare(), and Compare.
Member Function Documentation
CBAlphabetCompare()
int CCTreeCtrl::CBAlphabetCompare (CCTreeCtrlData * lhs, CCTreeCtrlData * rhs) static protected
Definition at line 89 of file cctreectrl.cpp.
References Token::m_Name, CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_Token, and sfToken.
Referenced by CBKindCompare(), and SetCompareFunction().
CBKindCompare()
int CCTreeCtrl::CBKindCompare (CCTreeCtrlData * lhs, CCTreeCtrlData * rhs) static protected
Definition at line 100 of file cctreectrl.cpp.
References CBAlphabetCompare(), CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_TokenKind, and sfToken.
Referenced by CBScopeCompare(), and SetCompareFunction().
CBLineCompare()
int CCTreeCtrl::CBLineCompare (CCTreeCtrlData * lhs, CCTreeCtrlData * rhs) static protected
Definition at line 125 of file cctreectrl.cpp.
References Token::m_FileIdx, Token::m_Line, CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_Token, and sfToken.
Referenced by SetCompareFunction().
CBNoCompare()
int CCTreeCtrl::CBNoCompare (CCTreeCtrlData * lhs, CCTreeCtrlData * rhs) static protected
Definition at line 143 of file cctreectrl.cpp.
Referenced by CCTreeCtrl(), and SetCompareFunction().
CBScopeCompare()
int CCTreeCtrl::CBScopeCompare (CCTreeCtrlData * lhs, CCTreeCtrlData * rhs) static protected
Definition at line 112 of file cctreectrl.cpp.
References CBKindCompare(), Token::m_Scope, CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_Token, and sfToken.
Referenced by SetCompareFunction().
OnCompareItems()
int CCTreeCtrl::OnCompareItems (const wxTreeItemId & item1, const wxTreeItemId & item2) protected virtual
Reimplemented from wxTreeCtrl.
Definition at line 84 of file cctreectrl.cpp.
References Compare, and wxTreeCtrl::GetItemData().
RemoveDoubles()
void CCTreeCtrl::RemoveDoubles (const wxTreeItemId & parent)
Definition at line 151 of file cctreectrl.cpp.
References _T, CCLogger::DebugLog(), wxTreeCtrl::Delete(), Token::DisplayName(), F(), CCLogger::Get(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetLastChild(), wxTreeCtrl::GetPrevSibling(), Manager::IsAppShuttingDown(), wxTreeItemId::IsOk(), CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_Token, sfToken, and wxStopWatch::Time().
SetCompareFunction()
void CCTreeCtrl::SetCompareFunction (const BrowserSortType type)
Definition at line 60 of file cctreectrl.cpp.
References bstAlphabet, bstKind, bstLine, bstNone, bstScope, CBAlphabetCompare(), CBKindCompare(), CBLineCompare(), CBNoCompare(), CBScopeCompare(), and Compare.
Referenced by ClassBrowserBuilderThread::BuildTree().
Member Data Documentation
Compare
int(* CCTreeCtrl::Compare) (CCTreeCtrlData *lhs, CCTreeCtrlData *rhs) protected
Definition at line 109 of file cctreectrl.h.
Referenced by CCTreeCtrl(), OnCompareItems(), and SetCompareFunction().
The documentation for this class was generated from the following files:
cctreectrl.h
cctreectrl.cpp