Code::Blocks: wxScintilla Class Reference
wxScintilla Class Reference
#include <wxscintilla.h>
Public Member Functions
wxScintilla (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name=wxSCINameStr)
wxScintilla ()
~wxScintilla ()
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name=wxSCINameStr)
void AddText (const wxString &text)
Generated method declaration section {{{.
void AddStyledText (const wxMemoryBuffer &data)
Add array of cells to document.
void InsertText (int pos, const wxString &text)
Insert string at a position.
void ChangeInsertion (int length, const wxString &text)
Change the text that is being inserted in response to wxSCI_MOD_INSERTCHECK.
void ClearAll ()
Delete all text in the document.
void DeleteRange (int start, int lengthDelete)
Delete a range of text in the document.
void ClearDocumentStyle ()
Set all style bytes to 0, remove all folding information.
int GetLength () const
Returns the number of bytes in the document.
int GetCharAt (int pos) const
Returns the character byte at the position.
int GetCurrentPos () const
Returns the position of the caret.
int GetAnchor () const
Returns the position of the opposite end of the selection to the caret.
int GetStyleAt (int pos) const
Returns the style byte at the position.
void Redo ()
Redoes the next action on the undo history.
void SetUndoCollection (bool collectUndo)
Choose between collecting actions into the undo history and discarding them.
void SetChangeCollection (bool collectChange)
Choose between collecting actions into the changes history and discarding them.
int FindChangedLine (const int fromLine, const int toLine) const
Find a changed line, if fromLine > toLine search is performed backwards.
void SelectAll ()
Select all the text in the document.
void SetSavePoint ()
Remember the current position in the undo history as the position at which the document was saved.
wxMemoryBuffer GetStyledText (int startPos, int endPos)
Retrieve a buffer of cells.
bool CanRedo () const
Are there any redoable actions in the undo history?
int MarkerLineFromHandle (int markerHandle)
Retrieve the line number at which a particular marker is located.
void MarkerDeleteHandle (int markerHandle)
Delete a marker.
bool GetUndoCollection () const
Is undo history being collected?
int GetViewWhiteSpace () const
Are white space characters currently visible? Returns one of wxSCI_WS_* constants.
void SetViewWhiteSpace (int viewWS)
Make white space characters invisible, always visible or visible outside indentation.
int GetTabDrawMode () const
Retrieve the current tab draw mode.
void SetTabDrawMode (int tabDrawMode)
Set how tabs are drawn when visible.
int PositionFromPoint (wxPoint pt) const
Find the position from a point within the window.
int PositionFromPointClose (int x, int y)
Find the position from a point within the window but return wxSCI_INVALID_POSITION if not close to text.
void GotoLine (int line)
Set caret to start of a line and ensure it is visible.
void GotoPos (int caret)
Set caret to a position and ensure it is visible.
void SetAnchor (int anchor)
Set the selection anchor to a position.
wxString GetCurLine (int *linePos=NULL)
Retrieve the text of the line containing the caret.
int GetEndStyled () const
Retrieve the position of the last correctly styled character.
void ConvertEOLs (int eolMode)
Convert all line endings in the document to one mode.
int GetEOLMode () const
Retrieve the current end of line mode - one of wxSCI_EOL_CRLF, wxSCI_EOL_CR, or wxSCI_EOL_LF.
void SetEOLMode (int eolMode)
Set the current end of line mode.
void StartStyling (int start)
Set the current styling position to start.
void SetStyling (int length, int style)
Change style from current styling position for length characters to a style and move the current styling position to after this newly styled segment.
bool GetBufferedDraw () const
Is drawing done first into a buffer or direct to the screen?
void SetBufferedDraw (bool buffered)
If drawing is buffered then each line of text is drawn into a bitmap buffer before drawing it to the screen to avoid flicker.
void SetTabWidth (int tabWidth)
Change the visible size of a tab to be a multiple of the width of a space character.
int GetTabWidth () const
Retrieve the visible size of a tab.
void ClearTabStops (int line)
Clear explicit tabstops on a line.
void AddTabStop (int line, int x)
Add an explicit tab stop for a line.
int GetNextTabStop (int line, int x)
Find the next explicit tab stop position on a line after a position.
void SetCodePage (int codePage)
Set the code page used to interpret the bytes of the document as characters.
int GetIMEInteraction () const
Is the IME displayed in a window or inline?
void SetIMEInteraction (int imeInteraction)
Choose to display the the IME in a winow or inline.
void MarkerDefine (int markerNumber, int markerSymbol, const wxColour &foreground=wxNullColour, const wxColour &background=wxNullColour)
Set the symbol used for a particular marker number, and optionally the fore and background colours.
void MarkerSetForeground (int markerNumber, const wxColour &fore)
Set the foreground colour used for a particular marker number.
void MarkerSetBackground (int markerNumber, const wxColour &back)
Set the background colour used for a particular marker number.
void MarkerSetBackgroundSelected (int markerNumber, const wxColour &back)
Set the background colour used for a particular marker number when its folding block is selected.
void MarkerEnableHighlight (bool enabled)
Enable/disable highlight for current folding bloc (smallest one that contains the caret)
int MarkerAdd (int line, int markerNumber)
Add a marker to a line, returning an ID which can be used to find or delete the marker.
void MarkerDelete (int line, int markerNumber)
Delete a marker from a line.
void MarkerDeleteAll (int markerNumber)
Delete all markers with a particular number from all lines.
int MarkerGet (int line)
Get a bit mask of all the markers set on a line.
int MarkerNext (int lineStart, int markerMask)
Find the next line at or after lineStart that includes a marker in mask.
int MarkerPrevious (int lineStart, int markerMask)
Find the previous line before lineStart that includes a marker in mask.
void MarkerDefineBitmap (int markerNumber, const wxBitmap &bmp)
Define a marker from a bitmap.
void MarkerAddSet (int line, int markerSet)
Add a set of markers to a line.
void MarkerSetAlpha (int markerNumber, int alpha)
Set the alpha used for a marker that is drawn in the text area, not the margin.
void SetMarginType (int margin, int marginType)
Set a margin to be either numeric or symbolic.
int GetMarginType (int margin) const
Retrieve the type of a margin.
void SetMarginWidth (int margin, int pixelWidth)
Set the width of a margin to a width expressed in pixels.
int GetMarginWidth (int margin) const
Retrieve the width of a margin in pixels.
void SetMarginMask (int margin, int mask)
Set a mask that determines which markers are displayed in a margin.
int GetMarginMask (int margin) const
Retrieve the marker mask of a margin.
void SetMarginSensitive (int margin, bool sensitive)
Make a margin sensitive or insensitive to mouse clicks.
bool GetMarginSensitive (int margin) const
Retrieve the mouse click sensitivity of a margin.
void SetMarginCursor (int margin, int cursor)
Set the cursor shown when the mouse is inside a margin.
int GetMarginCursor (int margin) const
Retrieve the cursor shown in a margin.
void SetMarginBackground (int margin, const wxColour &back)
Set the background colour of a margin. Only visible for wxSCI_MARGIN_COLOUR.
wxColour GetMarginBackground (int margin) const
Retrieve the background colour of a margin.
void SetMarginCount (int margins)
Allocate a non-standard number of margins.
int GetMarginCount () const
How many margins are there?.
void StyleClearAll ()
Clear all the styles and make equivalent to the global default style.
void StyleSetForeground (int style, const wxColour &fore)
Set the foreground colour of a style.
void StyleSetBackground (int style, const wxColour &back)
Set the background colour of a style.
void StyleSetBold (int style, bool bold)
Set a style to be bold or not.
void StyleSetItalic (int style, bool italic)
Set a style to be italic or not.
void StyleSetSize (int style, int sizePoints)
Set the size of characters of a style.
void StyleSetFaceName (int style, const wxString &fontName)
Set the font of a style.
void StyleSetEOLFilled (int style, bool eolFilled)
Set a style to have its end of line filled or not.
void StyleResetDefault ()
Reset the default style to its state at startup.
void StyleSetUnderline (int style, bool underline)
Set a style to be underlined or not.
wxColour StyleGetForeground (int style) const
Get the foreground colour of a style.
wxColour StyleGetBackground (int style) const
Get the background colour of a style.
bool StyleGetBold (int style) const
Get is a style bold or not.
bool StyleGetItalic (int style) const
Get is a style italic or not.
int StyleGetSize (int style) const
Get the size of characters of a style.
wxString StyleGetFaceName (int style)
Get the font facename of a style.
bool StyleGetEOLFilled (int style) const
Get is a style to have its end of line filled or not.
bool StyleGetUnderline (int style) const
Get is a style underlined or not.
int StyleGetCase (int style) const
Get is a style mixed case, or to force upper or lower case.
int StyleGetCharacterSet (int style) const
Get the character get of the font in a style.
bool StyleGetVisible (int style) const
Get is a style visible or not.
bool StyleGetChangeable (int style) const
Get is a style changeable or not (read only).
bool StyleGetHotSpot (int style) const
Get is a style a hotspot or not.
void StyleSetCase (int style, int caseVisible)
Set a style to be mixed case, or to force upper or lower case.
void StyleSetSizeFractional (int style, int sizeHundredthPoints)
Set the size of characters of a style. Size is in points multiplied by 100.
int StyleGetSizeFractional (int style) const
Get the size of characters of a style in points multiplied by 100.
void StyleSetWeight (int style, int weight)
Set the weight of characters of a style.
int StyleGetWeight (int style) const
Get the weight of characters of a style.
void StyleSetCharacterSet (int style, int characterSet)
Set the character set of the font in a style.
void StyleSetHotSpot (int style, bool hotspot)
Set a style to be a hotspot or not.
void SetSelForeground (bool useSetting, const wxColour &fore)
Set the foreground colour of the main and additional selections and whether to use this setting.
void SetSelBackground (bool useSetting, const wxColour &back)
Set the background colour of the main and additional selections and whether to use this setting.
int GetSelAlpha () const
Get the alpha of the selection.
void SetSelAlpha (int alpha)
Set the alpha of the selection.
bool GetSelEOLFilled () const
Is the selection end of line filled?
void SetSelEOLFilled (bool filled)
Set the selection to have its end of line filled or not.
void SetCaretForeground (const wxColour &fore)
Set the foreground colour of the caret.
void CmdKeyAssign (int key, int modifiers, int cmd)
When key+modifier combination keyDefinition is pressed perform sciCommand.
void CmdKeyClear (int key, int modifiers)
When key+modifier combination keyDefinition is pressed do nothing.
void CmdKeyClearAll ()
Drop all key mappings.
void SetStyleBytes (int length, char *styleBytes)
Set the styles for a segment of the document.
void StyleSetVisible (int style, bool visible)
Set a style to be visible or not.
int GetCaretPeriod () const
Get the time in milliseconds that the caret is on and off.
void SetCaretPeriod (int periodMilliseconds)
Get the time in milliseconds that the caret is on and off. 0 = steady on.
void SetWordChars (const wxString &characters)
Set the set of characters making up words for when moving or selecting by word.
wxString GetWordChars () const
Get the set of characters making up words for when moving or selecting by word.
void BeginUndoAction ()
Start a sequence of actions that is undone and redone as a unit.
void EndUndoAction ()
End a sequence of actions that is undone and redone as a unit.
void IndicatorSetStyle (int indicator, int indicatorStyle)
Set an indicator to plain, squiggle or TT.
int IndicatorGetStyle (int indicator) const
Retrieve the style of an indicator.
void IndicatorSetForeground (int indicator, const wxColour &fore)
Set the foreground colour of an indicator.
wxColour IndicatorGetForeground (int indicator) const
Retrieve the foreground colour of an indicator.
void IndicatorSetUnder (int indicator, bool under)
Set an indicator to draw under text or over(default).
bool IndicatorGetUnder (int indicator) const
Retrieve whether indicator drawn under or over text.
void IndicatorSetHoverStyle (int indicator, int indicatorStyle)
Set a hover indicator to plain, squiggle or TT.
int IndicatorGetHoverStyle (int indicator) const
Retrieve the hover style of an indicator.
void IndicatorSetHoverForeground (int indicator, const wxColour &fore)
Set the foreground hover colour of an indicator.
wxColour IndicatorGetHoverForeground (int indicator) const
Retrieve the foreground hover colour of an indicator.
void IndicatorSetFlags (int indicator, int flags)
Set the attributes of an indicator.
int IndicatorGetFlags (int indicator) const
Retrieve the attributes of an indicator.
void SetWhitespaceForeground (bool useSetting, const wxColour &fore)
Set the foreground colour of all whitespace and whether to use this setting.
void SetWhitespaceBackground (bool useSetting, const wxColour &back)
Set the background colour of all whitespace and whether to use this setting.
void SetWhitespaceSize (int size)
Set the size of the dots used to mark space characters.
int GetWhitespaceSize () const
Get the size of the dots used to mark space characters.
wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") void SetStyleBits(int bits)
Divide each styling byte into lexical class bits (default: 5) and indicator bits (default: 3).
wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") int GetStyleBits() const
Retrieve number of bits in style bytes used to hold the lexical state.
void SetLineState (int line, int state)
Used to hold extra styling information for each line.
int GetLineState (int line) const
Retrieve the extra styling information for a line.
int GetMaxLineState () const
Retrieve the last line number that has line state.
bool GetCaretLineVisible () const
Is the background of the line containing the caret in a different colour?
void SetCaretLineVisible (bool show)
Display the background of the line containing the caret in a different colour.
wxColour GetCaretLineBackground () const
Get the colour of the background of the line containing the caret.
void SetCaretLineBackground (const wxColour &back)
Set the colour of the background of the line containing the caret.
void StyleSetChangeable (int style, bool changeable)
Set a style to be changeable or not (read only).
void AutoCompShow (int lengthEntered, const wxString &itemList)
Display a auto-completion list.
void AutoCompCancel ()
Remove the auto-completion list from the screen.
bool AutoCompActive ()
Is there an auto-completion list visible?
int AutoCompPosStart ()
Retrieve the position of the caret when the auto-completion list was displayed.
void AutoCompComplete ()
User has selected an item so remove the list and insert the selection.
void AutoCompStops (const wxString &characterSet)
Define a set of character that when typed cancel the auto-completion list.
void AutoCompSetSeparator (int separatorCharacter)
Change the separator character in the string setting up an auto-completion list.
int AutoCompGetSeparator () const
Retrieve the auto-completion list separator character.
void AutoCompSelect (const wxString &select)
Select the item in the auto-completion list that starts with a string.
void AutoCompSetCancelAtStart (bool cancel)
Should the auto-completion list be cancelled if the user backspaces to a position before where the box was created.
bool AutoCompGetCancelAtStart () const
Retrieve whether auto-completion cancelled by backspacing before start.
void AutoCompSetFillUps (const wxString &characterSet)
Define a set of characters that when typed will cause the autocompletion to choose the selected item.
void AutoCompSetChooseSingle (bool chooseSingle)
Should a single item auto-completion list automatically choose the item.
bool AutoCompGetChooseSingle () const
Retrieve whether a single item auto-completion list automatically choose the item.
void AutoCompSetIgnoreCase (bool ignoreCase)
Set whether case is significant when performing auto-completion searches.
bool AutoCompGetIgnoreCase () const
Retrieve state of ignore case flag.
void UserListShow (int listType, const wxString &itemList)
Display a list of strings and send notification when user chooses one.
void AutoCompSetAutoHide (bool autoHide)
Set whether or not autocompletion is hidden automatically when nothing matches.
bool AutoCompGetAutoHide () const
Retrieve whether or not autocompletion is hidden automatically when nothing matches.
void AutoCompSetDropRestOfWord (bool dropRestOfWord)
Set whether or not autocompletion deletes any word characters after the inserted text upon completion.
bool AutoCompGetDropRestOfWord () const
Retrieve whether or not autocompletion deletes any word characters after the inserted text upon completion.
void RegisterImage (int type, const wxBitmap &bmp)
Register an image for use in autocompletion lists.
void ClearRegisteredImages ()
Clear all the registered images.
int AutoCompGetTypeSeparator () const
Retrieve the auto-completion list type-separator character.
void AutoCompSetTypeSeparator (int separatorCharacter)
Change the type-separator character in the string setting up an auto-completion list.
void AutoCompSetMaxWidth (int characterCount)
Set the maximum width, in characters, of auto-completion and user lists.
int AutoCompGetMaxWidth () const
Get the maximum width, in characters, of auto-completion and user lists.
void AutoCompSetMaxHeight (int rowCount)
Set the maximum height, in rows, of auto-completion and user lists.
int AutoCompGetMaxHeight () const
Set the maximum height, in rows, of auto-completion and user lists.
void SetIndent (int indentSize)
Set the number of spaces used for one level of indentation.
int GetIndent () const
Retrieve indentation size.
void SetUseTabs (bool useTabs)
Indentation will only use space characters if useTabs is false, otherwise it will use a combination of tabs and spaces.
bool GetUseTabs () const
Retrieve whether tabs will be used in indentation.
void SetLineIndentation (int line, int indentation)
Change the indentation of a line to a number of columns.
int GetLineIndentation (int line) const
Retrieve the number of columns that a line is indented.
int GetLineIndentPosition (int line) const
Retrieve the position before the first non indentation character on a line.
int GetColumn (int pos) const
Retrieve the column number of a position, taking tab width into account.
int CountCharacters (int start, int end)
Count characters between two positions.
void SetUseHorizontalScrollBar (bool visible)
Show or hide the horizontal scroll bar.
bool GetUseHorizontalScrollBar () const
Is the horizontal scroll bar visible?
void SetIndentationGuides (int indentView)
Show or hide indentation guides.
int GetIndentationGuides () const
Are the indentation guides visible?
void SetHighlightGuide (int column)
Set the highlighted indentation guide column.
int GetHighlightGuide () const
Get the highlighted indentation guide column.
int GetLineEndPosition (int line) const
Get the position after the last visible characters on a line.
int GetCodePage () const
Get the code page used to interpret the bytes of the document as characters.
wxColour GetCaretForeground () const
Get the foreground colour of the caret.
bool GetReadOnly () const
In read-only mode?
void SetCurrentPos (int caret)
Sets the position of the caret.
void SetSelectionStart (int anchor)
Sets the position that starts the selection - this becomes the anchor.
int GetSelectionStart () const
Returns the position at the start of the selection.
void SetSelectionEnd (int caret)
Sets the position that ends the selection - this becomes the caret.
int GetSelectionEnd () const
Returns the position at the end of the selection.
void SetEmptySelection (int caret)
Set caret to a position, while removing any existing selection.
void SetPrintMagnification (int magnification)
Sets the print magnification added to the point size of each style for printing.
int GetPrintMagnification () const
Returns the print magnification.
void SetPrintColourMode (int mode)
Modify colours when printing for clearer printed text.
int GetPrintColourMode () const
Returns the print colour mode.
int FindText (int minPos, int maxPos, const wxString &text, int flags=0, int *findEnd=NULL)
Find some text in the document.
int FormatRange (bool doDraw, int startPos, int endPos, wxDC *draw, wxDC *target, wxRect renderRect, wxRect pageRect)
On Windows, will draw the document into a display context such as a printer.
int GetFirstVisibleLine () const
Retrieve the display line at the top of the display.
wxString GetLine (int line) const
Retrieve the contents of a line.
int GetLineCount () const
Returns the number of lines in the document. There is always at least one.
void SetMarginLeft (int pixelWidth)
Sets the size in pixels of the left margin.
int GetMarginLeft () const
Returns the size in pixels of the left margin.
void SetMarginRight (int pixelWidth)
Sets the size in pixels of the right margin.
int GetMarginRight () const
Returns the size in pixels of the right margin.
bool GetModify () const
Is the document different from when it was last saved?
wxString GetSelectedText ()
Retrieve the selected text.
wxString GetTextRange (int startPos, int endPos)
Retrieve a range of text.
void HideSelection (bool hide)
Draw the selection in normal style or with selection highlighted.
wxPoint PointFromPosition (int pos)
Retrieve the point in the window where a position is displayed.
int LineFromPosition (int pos) const
Retrieve the line containing a position.
int PositionFromLine (int line) const
Retrieve the position at the start of a line.
void LineScroll (int columns, int lines)
Scroll horizontally and vertically.
void EnsureCaretVisible ()
Ensure the caret is visible.
void ScrollRange (int secondary, int primary)
Scroll the argument positions and the range between them into view giving priority to the primary position then the secondary position.
void ReplaceSelection (const wxString &text)
Replace the selected text with the argument text.
void SetReadOnly (bool readOnly)
Set to read only or read write.
bool CanPaste () const
Will a paste succeed?
bool CanUndo () const
Are there any undoable actions in the undo history?
void EmptyUndoBuffer (bool collectChangeHistory=false)
Delete the undo history.
void Undo ()
Undo one action in the undo history.
void Cut ()
Cut the selection to the clipboard.
void Copy ()
Copy the selection to the clipboard.
void Paste ()
Paste the contents of the clipboard into the document replacing the selection.
void Clear ()
Clear the selection.
void SetText (const wxString &text)
Replace the contents of the document with the argument text.
wxString GetText () const
Retrieve all the text in the document.
int GetTextLength () const
Retrieve the number of characters in the document.
void * GetDirectFunction () const
Retrieve a pointer to a function that processes messages for this Scintilla.
void * GetDirectPointer () const
Retrieve a pointer value to use as the first argument when calling the function returned by GetDirectFunction.
void SetOvertype (bool overType)
Set to overtype (true) or insert mode.
bool GetOvertype () const
Returns true if overtype mode is active otherwise false is returned.
void SetCaretWidth (int pixelWidth)
Set the width of the insert mode caret.
int GetCaretWidth () const
Returns the width of the insert mode caret.
void SetTargetStart (int start)
Sets the position that starts the target which is used for updating the document without affecting the scroll position.
int GetTargetStart () const
Get the position that starts the target.
void SetTargetEnd (int end)
Sets the position that ends the target which is used for updating the document without affecting the scroll position.
int GetTargetEnd () const
Get the position that ends the target.
void SetTargetRange (int start, int end)
Sets both the start and end of the target in one call.
wxString GetTargetText () const
Retrieve the text in the target.
void TargetFromSelection ()
Make the target range start and end be the same as the selection range start and end.
void TargetWholeDocument ()
Sets the target to the whole document.
int ReplaceTarget (const wxString &text)
Replace the target text with the argument text.
int ReplaceTargetRE (const wxString &text)
Replace the target text with the argument text after \d processing.
int SearchInTarget (const wxString &text)
Search for a counted string in the target and set the target to the found range.
void SetSearchFlags (int searchFlags)
Set the search flags used by SearchInTarget.
int GetSearchFlags () const
Get the search flags used by SearchInTarget.
void CallTipShow (int pos, const wxString &definition)
Show a call tip containing a definition near position pos.
void CallTipCancel ()
Remove the call tip from the screen.
bool CallTipActive ()
Is there an active call tip?
int CallTipPosAtStart ()
Retrieve the position where the caret was before displaying the call tip.
void CallTipSetPosAtStart (int posStart)
Set the start position in order to change when backspacing removes the calltip.
void CallTipSetHighlight (int highlightStart, int highlightEnd)
Highlight a segment of the definition.
void CallTipSetBackground (const wxColour &back)
Set the background colour for the call tip.
void CallTipSetForeground (const wxColour &fore)
Set the foreground colour for the call tip.
void CallTipSetForegroundHighlight (const wxColour &fore)
Set the foreground colour for the highlighted part of the call tip.
void CallTipUseStyle (int tabSize)
Enable use of wxSCI_STYLE_CALLTIP and set call tip tab size in pixels.
void CallTipSetPosition (bool above)
Set position of calltip, above or below text.
int VisibleFromDocLine (int docLine)
Find the display line of a document line taking hidden lines into account.
int DocLineFromVisible (int displayLine)
Find the document line of a display line taking hidden lines into account.
int WrapCount (int docLine)
The number of display lines needed to wrap a document line.
void SetFoldLevel (int line, int level)
Set the fold level of a line.
int GetFoldLevel (int line) const
Retrieve the fold level of a line.
int GetLastChild (int line, int level) const
Find the last child line of a header line.
int GetFoldParent (int line) const
Find the parent line of a child line.
void ShowLines (int lineStart, int lineEnd)
Make a range of lines visible.
void HideLines (int lineStart, int lineEnd)
Make a range of lines invisible.
bool GetLineVisible (int line) const
Is a line visible?
bool GetAllLinesVisible () const
Are all lines visible?
void SetFoldExpanded (int line, bool expanded)
Show the children of a header line.
bool GetFoldExpanded (int line) const
Is a header line expanded?
void ToggleFold (int line)
Switch a header line between expanded and contracted.
void ToggleFoldShowText (int line, const wxString &text)
Switch a header line between expanded and contracted and show some text after the line.
void FoldDisplayTextSetStyle (int style)
Set the style of fold display text.
void FoldLine (int line, int action)
Expand or contract a fold header.
void FoldChildren (int line, int action)
Expand or contract a fold header and its children.
void ExpandChildren (int line, int level)
Expand a fold header and all children. Use the level argument instead of the line's current level.
void FoldAll (int action)
Expand or contract all fold headers.
void EnsureVisible (int line)
Ensure a particular line is visible by expanding any header line hiding it.
void SetAutomaticFold (int automaticFold)
Set automatic folding behaviours.
int GetAutomaticFold () const
Get automatic folding behaviours.
void SetFoldFlags (int flags)
Set some style options for folding.
void EnsureVisibleEnforcePolicy (int line)
Ensure a particular line is visible by expanding any header line hiding it.
void SetTabIndents (bool tabIndents)
Sets whether a tab pressed when caret is within indentation indents.
bool GetTabIndents () const
Does a tab pressed when caret is within indentation indent?
void SetBackSpaceUnIndents (bool bsUnIndents)
Sets whether a backspace pressed when caret is within indentation unindents.
bool GetBackSpaceUnIndents () const
Does a backspace pressed when caret is within indentation unindent?
void SetMouseDwellTime (int periodMilliseconds)
Sets the time the mouse must sit still to generate a mouse dwell event.
int GetMouseDwellTime () const
Retrieve the time the mouse must sit still to generate a mouse dwell event.
int WordStartPosition (int pos, bool onlyWordCharacters)
Get position of start of word.
int WordEndPosition (int pos, bool onlyWordCharacters)
Get position of end of word.
bool IsRangeWord (int start, int end)
Is the range start..end considered a word?
void SetIdleStyling (int idleStyling)
Sets limits to idle styling.
int GetIdleStyling () const
Retrieve the limits to idle styling.
void SetWrapMode (int wrapMode)
Sets whether text is word wrapped.
int GetWrapMode () const
Retrieve whether text is word wrapped.
void SetWrapVisualFlags (int wrapVisualFlags)
Set the display mode of visual flags for wrapped lines.
int GetWrapVisualFlags () const
Retrive the display mode of visual flags for wrapped lines.
void SetWrapVisualFlagsLocation (int wrapVisualFlagsLocation)
Set the location of visual flags for wrapped lines.
int GetWrapVisualFlagsLocation () const
Retrive the location of visual flags for wrapped lines.
void SetWrapStartIndent (int indent)
Set the start indent for wrapped lines.
int GetWrapStartIndent () const
Retrive the start indent for wrapped lines.
void SetWrapIndentMode (int wrapIndentMode)
Sets how wrapped sublines are placed. Default is wxSCI_WRAPINDENT_FIXED.
int GetWrapIndentMode () const
Retrieve how wrapped sublines are placed. Default is wxSCI_WRAPINDENT_FIXED.
void SetLayoutCache (int cacheMode)
Sets the degree of caching of layout information.
int GetLayoutCache () const
Retrieve the degree of caching of layout information.
void SetScrollWidth (int pixelWidth)
Sets the document width assumed for scrolling.
int GetScrollWidth () const
Retrieve the document width assumed for scrolling.
void SetScrollWidthTracking (bool tracking)
Sets whether the maximum width line displayed is used to set scroll width.
bool GetScrollWidthTracking () const
Retrieve whether the scroll width tracks wide lines.
int TextWidth (int style, const wxString &text)
Measure the pixel width of some text in a particular style.
void SetEndAtLastLine (bool endAtLastLine)
Sets the scroll range so that maximum scroll position has the last line at the bottom of the view (default).
bool GetEndAtLastLine () const
Retrieve whether the maximum scroll position has the last line at the bottom of the view.
int TextHeight (int line)
Retrieve the height of a particular line of text in pixels.
void SetUseVerticalScrollBar (bool visible)
Show or hide the vertical scroll bar.
bool GetUseVerticalScrollBar () const
Is the vertical scroll bar visible?
void AppendText (const wxString &text)
Append a string to the end of the document without changing the selection.
bool GetTwoPhaseDraw () const
Is drawing done in two phases with backgrounds drawn before foregrounds?
void SetTwoPhaseDraw (bool twoPhase)
In twoPhaseDraw mode, drawing is performed in two phases, first the background and then the foreground.
int GetPhasesDraw () const
How many phases is drawing done in?
void SetPhasesDraw (int phases)
In one phase draw, text is drawn in a series of rectangular blocks with no overlap.
void SetFontQuality (int fontQuality)
Choose the quality level for text.
int GetFontQuality () const
Retrieve the quality level for text.
void SetFirstVisibleLine (int displayLine)
Scroll so that a display line is at the top of the display.
void SetMultiPaste (int multiPaste)
Change the effect of pasting when there are multiple selections.
int GetMultiPaste () const
Retrieve the effect of pasting when there are multiple selections.
wxString GetTag (int tagNumber) const
Retrieve the value of a tag from a regular expression search.
void LinesJoin ()
Join the lines in the target.
void LinesSplit (int pixelWidth)
Split the lines in the target into lines that are less wide than pixelWidth where possible.
void SetFoldMarginColour (bool useSetting, const wxColour &back)
Set one of the colours used as a chequerboard pattern in the fold margin.
void SetFoldMarginHiColour (bool useSetting, const wxColour &fore)
Set the other colour used as a chequerboard pattern in the fold margin.
void LineDown ()
Move caret down one line.
void LineDownExtend ()
Move caret down one line extending selection to new caret position.
void LineUp ()
Move caret up one line.
void LineUpExtend ()
Move caret up one line extending selection to new caret position.
void CharLeft ()
Move caret left one character.
void CharLeftExtend ()
Move caret left one character extending selection to new caret position.
void CharRight ()
Move caret right one character.
void CharRightExtend ()
Move caret right one character extending selection to new caret position.
void WordLeft ()
Move caret left one word.
void WordLeftExtend ()
Move caret left one word extending selection to new caret position.
void WordRight ()
Move caret right one word.
void WordRightExtend ()
Move caret right one word extending selection to new caret position.
void Home ()
Move caret to first position on line.
void HomeExtend ()
Move caret to first position on line extending selection to new caret position.
void LineEnd ()
Move caret to last position on line.
void LineEndExtend ()
Move caret to last position on line extending selection to new caret position.
void DocumentStart ()
Move caret to first position in document.
void DocumentStartExtend ()
Move caret to first position in document extending selection to new caret position.
void DocumentEnd ()
Move caret to last position in document.
void DocumentEndExtend ()
Move caret to last position in document extending selection to new caret position.
void PageUp ()
Move caret one page up.
void PageUpExtend ()
Move caret one page up extending selection to new caret position.
void PageDown ()
Move caret one page down.
void PageDownExtend ()
Move caret one page down extending selection to new caret position.
void EditToggleOvertype ()
Switch from insert to overtype mode or the reverse.
void Cancel ()
Cancel any modes such as call tip or auto-completion list display.
void DeleteBack ()
Delete the selection or if no selection, the character before the caret.
void Tab ()
If selection is empty or all on one line replace the selection with a tab character.
void BackTab ()
Dedent the selected lines.
void NewLine ()
Insert a new line, may use a CRLF, CR or LF depending on EOL mode.
void FormFeed ()
Insert a Form Feed character.
void VCHome ()
Move caret to before first visible character on line.
void VCHomeExtend ()
Like VCHome but extending selection to new caret position.
void ZoomIn ()
Magnify the displayed text by increasing the sizes by 1 point.
void ZoomOut ()
Make the displayed text smaller by decreasing the sizes by 1 point.
void DelWordLeft ()
Delete the word to the left of the caret.
void DelWordRight ()
Delete the word to the right of the caret.
void DelWordRightEnd ()
Delete the word to the right of the caret, but not the trailing non-word characters.
void LineCut ()
Cut the line containing the caret.
void LineDelete ()
Delete the line containing the caret.
void LineTranspose ()
Switch the current line with the previous.
void LineDuplicate ()
Duplicate the current line.
void LowerCase ()
Transform the selection to lower case.
void UpperCase ()
Transform the selection to upper case.
void LineScrollDown ()
Scroll the document down, keeping the caret visible.
void LineScrollUp ()
Scroll the document up, keeping the caret visible.
void DeleteBackNotLine ()
Delete the selection or if no selection, the character before the caret.
void HomeDisplay ()
Move caret to first position on display line.
void HomeDisplayExtend ()
Move caret to first position on display line extending selection to new caret position.
void LineEndDisplay ()
Move caret to last position on display line.
void LineEndDisplayExtend ()
Move caret to last position on display line extending selection to new caret position.
void HomeWrap ()
Like Home but when word-wrap is enabled goes first to start of display line HomeDisplay, then to start of document line Home.
void HomeWrapExtend ()
Like HomeExtend but when word-wrap is enabled extends first to start of display line HomeDisplayExtend, then to start of document line HomeExtend.
void LineEndWrap ()
Like LineEnd but when word-wrap is enabled goes first to end of display line LineEndDisplay, then to start of document line LineEnd.
void LineEndWrapExtend ()
Like LineEndExtend but when word-wrap is enabled extends first to end of display line LineEndDisplayExtend, then to start of document line LineEndExtend.
void VCHomeWrap ()
Like VCHome but when word-wrap is enabled goes first to start of display line VCHomeDisplay, then behaves like VCHome.
void VCHomeWrapExtend ()
Like VCHomeExtend but when word-wrap is enabled extends first to start of display line VCHomeDisplayExtend, then behaves like VCHomeExtend.
void LineCopy ()
Copy the line containing the caret.
void MoveCaretInsideView ()
Move the caret inside current view if it's not there already.
int LineLength (int line) const
How many characters are on a line, including end of line characters?
void BraceHighlight (int posA, int posB)
Highlight the characters at two positions.
void BraceHighlightIndicator (bool useSetting, int indicator)
Use specified indicator to highlight matching braces instead of changing their style.
void BraceBadLight (int pos)
Highlight the character at a position indicating there is no matching brace.
void BraceBadLightIndicator (bool useSetting, int indicator)
Use specified indicator to highlight non matching brace instead of changing its style.
int BraceMatch (int pos, int maxReStyle=0)
Find the position of a matching brace or wxSCI_INVALID_POSITION if no match.
bool GetViewEOL () const
Are the end of line characters visible?
void SetViewEOL (bool visible)
Make the end of line characters visible or invisible.
void * GetDocPointer ()
Retrieve a pointer to the document object.
void SetDocPointer (void *docPointer)
Change the document object used.
void SetModEventMask (int eventMask)
Set which document modification events are sent to the container.
int GetEdgeColumn () const
Retrieve the column number which text should be kept within.
void SetEdgeColumn (int column)
Set the column number of the edge.
int GetEdgeMode () const
Retrieve the edge highlight mode.
void SetEdgeMode (int edgeMode)
The edge may be displayed by a line (wxSCI_EDGE_LINE/wxSCI_EDGE_MULTILINE) or by highlighting text that goes beyond it (wxSCI_EDGE_BACKGROUND) or not displayed at all (wxSCI_EDGE_NONE).
wxColour GetEdgeColour () const
Retrieve the colour used in edge indication.
void SetEdgeColour (const wxColour &edgeColour)
Change the colour used in edge indication.
void MultiEdgeAddLine (int column, const wxColour &edgeColour)
Add a new vertical edge to the view.
void MultiEdgeClearAll ()
Clear all vertical edges.
void SearchAnchor ()
Sets the current caret position to be the search anchor.
int SearchNext (int searchFlags, const wxString &text)
Find some text starting at the search anchor.
int SearchPrev (int searchFlags, const wxString &text)
Find some text starting at the search anchor and moving backwards.
int LinesOnScreen () const
Retrieves the number of lines completely visible.
void UsePopUp (int popUpMode)
Set whether a pop up menu is displayed automatically when the user presses the wrong mouse button on certain areas.
bool SelectionIsRectangle () const
Is the selection rectangular? The alternative is the more common stream selection.
void SetZoom (int zoomInPoints)
Set the zoom level.
int GetZoom () const
Retrieve the zoom level.
void * CreateDocument ()
Create a new document object.
void AddRefDocument (void *docPointer)
Extend life of document.
void ReleaseDocument (void *docPointer)
Release a reference to the document, deleting document if it fades to black.
int GetModEventMask () const
Get which document modification events are sent to the container.
void SetSCIFocus (bool focus)
Change internal focus flag.
bool GetSCIFocus () const
Get internal focus flag.
void SetStatus (int status)
Change error status - 0 = OK.
int GetStatus () const
Get error status.
void SetMouseDownCaptures (bool captures)
Set whether the mouse is captured when its button is pressed.
bool GetMouseDownCaptures () const
Get whether mouse gets captured.
void SetMouseWheelCaptures (bool captures)
Set whether the mouse wheel can be active outside the window.
bool GetMouseWheelCaptures () const
Get whether mouse wheel can be active outside the window.
void SetSCICursor (int cursorType)
Sets the cursor to one of the wxSCI_CURSOR* values.
int GetSCICursor () const
Get cursor type.
void SetControlCharSymbol (int symbol)
Change the way control characters are displayed: If symbol is < 32, keep the drawn way, else, use the given character.
int GetControlCharSymbol () const
Get the way control characters are displayed.
void WordPartLeft ()
Move to the previous change in capitalisation.
void WordPartLeftExtend ()
Move to the previous change in capitalisation extending selection to new caret position.
void WordPartRight ()
Move to the change next in capitalisation.
void WordPartRightExtend ()
Move to the next change in capitalisation extending selection to new caret position.
void SetVisiblePolicy (int visiblePolicy, int visibleSlop)
Set the way the display area is determined when a particular line is to be moved to by Find, FindNext, GotoLine, etc.
void DelLineLeft ()
Delete back from the current position to the start of the line.
void DelLineRight ()
Delete forwards from the current position to the end of the line.
void SetXOffset (int xOffset)
Set the xOffset (ie, horizontal scroll position).
int GetXOffset () const
Get the xOffset (ie, horizontal scroll position).
void ChooseCaretX ()
Set the last x chosen value to be the caret x position.
void SetXCaretPolicy (int caretPolicy, int caretSlop)
Set the way the caret is kept visible when going sideways.
void SetYCaretPolicy (int caretPolicy, int caretSlop)
Set the way the line the caret is on is kept visible.
void SetPrintWrapMode (int wrapMode)
Set printing to line wrapped (wxSCI_WRAP_WORD) or not line wrapped (wxSCI_WRAP_NONE).
int GetPrintWrapMode () const
Is printing line wrapped?
void SetHotspotActiveForeground (bool useSetting, const wxColour &fore)
Set a fore colour for active hotspots.
wxColour GetHotspotActiveForeground () const
Get the fore colour for active hotspots.
void SetHotspotActiveBackground (bool useSetting, const wxColour &back)
Set a back colour for active hotspots.
wxColour GetHotspotActiveBackground () const
Get the back colour for active hotspots.
void SetHotspotActiveUnderline (bool underline)
Enable / Disable underlining active hotspots.
bool GetHotspotActiveUnderline () const
Get whether underlining for active hotspots.
void SetHotspotSingleLine (bool singleLine)
Limit hotspots to single line so hotspots on two lines don't merge.
bool GetHotspotSingleLine () const
Get the HotspotSingleLine property.
void ParaDown ()
Move caret down one paragraph (delimited by empty lines).
void ParaDownExtend ()
Extend selection down one paragraph (delimited by empty lines).
void ParaUp ()
Move caret up one paragraph (delimited by empty lines).
void ParaUpExtend ()
Extend selection up one paragraph (delimited by empty lines).
int PositionBefore (int pos)
Given a valid document position, return the previous position taking code page into account.
int PositionAfter (int pos)
Given a valid document position, return the next position taking code page into account.
int PositionRelative (int pos, int relative)
Given a valid document position, return a position that differs in a number of characters.
void CopyRange (int start, int end)
Copy a range of text to the clipboard. Positions are clipped into the document.
void CopyText (int length, const wxString &text)
Copy argument text to the clipboard.
void SetSelectionMode (int selectionMode)
Set the selection mode to stream (wxSCI_SEL_STREAM) or rectangular (wxSCI_SEL_RECTANGLE/wxSCI_SEL_THIN) or by lines (wxSCI_SEL_LINES).
int GetSelectionMode () const
Get the mode of the current selection.
int GetLineSelStartPosition (int line)
Retrieve the position of the start of the selection at the given line (wxSCI_INVALID_POSITION if no selection on this line).
int GetLineSelEndPosition (int line)
Retrieve the position of the end of the selection at the given line (wxSCI_INVALID_POSITION if no selection on this line).
void LineDownRectExtend ()
Move caret down one line, extending rectangular selection to new caret position.
void LineUpRectExtend ()
Move caret up one line, extending rectangular selection to new caret position.
void CharLeftRectExtend ()
Move caret left one character, extending rectangular selection to new caret position.
void CharRightRectExtend ()
Move caret right one character, extending rectangular selection to new caret position.
void HomeRectExtend ()
Move caret to first position on line, extending rectangular selection to new caret position.
void VCHomeRectExtend ()
Move caret to before first visible character on line.
void LineEndRectExtend ()
Move caret to last position on line, extending rectangular selection to new caret position.
void PageUpRectExtend ()
Move caret one page up, extending rectangular selection to new caret position.
void PageDownRectExtend ()
Move caret one page down, extending rectangular selection to new caret position.
void StutteredPageUp ()
Move caret to top of page, or one page up if already at top of page.
void StutteredPageUpExtend ()
Move caret to top of page, or one page up if already at top of page, extending selection to new caret position.
void StutteredPageDown ()
Move caret to bottom of page, or one page down if already at bottom of page.
void StutteredPageDownExtend ()
Move caret to bottom of page, or one page down if already at bottom of page, extending selection to new caret position.
void WordLeftEnd ()
Move caret left one word, position cursor at end of word.
void WordLeftEndExtend ()
Move caret left one word, position cursor at end of word, extending selection to new caret position.
void WordRightEnd ()
Move caret right one word, position cursor at end of word.
void WordRightEndExtend ()
Move caret right one word, position cursor at end of word, extending selection to new caret position.
void SetWhitespaceChars (const wxString &characters)
Set the set of characters making up whitespace for when moving or selecting by word.
wxString GetWhitespaceChars () const
Get the set of characters making up whitespace for when moving or selecting by word.
void SetPunctuationChars (const wxString &characters)
Set the set of characters making up punctuation characters Should be called after SetWordChars.
wxString GetPunctuationChars () const
Get the set of characters making up punctuation characters.
void SetCharsDefault ()
Reset the set of characters for whitespace and word characters to the defaults.
int AutoCompGetCurrent () const
Get currently selected item position in the auto-completion list.
wxString AutoCompGetCurrentText () const
Get currently selected item text in the auto-completion list.
void AutoCompSetCaseInsensitiveBehaviour (int behaviour)
Set auto-completion case insensitive behaviour to either prefer case-sensitive matches or have no preference.
int AutoCompGetCaseInsensitiveBehaviour () const
Get auto-completion case insensitive behaviour.
void AutoCompSetMulti (int multi)
Change the effect of autocompleting when there are multiple selections.
int AutoCompGetMulti () const
Retrieve the effect of autocompleting when there are multiple selections.
void AutoCompSetOrder (int order)
Set the way autocompletion lists are ordered.
int AutoCompGetOrder () const
Get the way autocompletion lists are ordered.
void Allocate (int bytes)
Enlarge the document to a particular size of text bytes.
int FindColumn (int line, int column)
Find the position of a column on a line taking into account tabs and multi-byte characters.
int GetCaretSticky () const
Can the caret preferred x position only be changed by explicit movement commands?
void SetCaretSticky (int useCaretStickyBehaviour)
Stop the caret preferred x position changing when the user types.
void ToggleCaretSticky ()
Switch between sticky and non-sticky: meant to be bound to a key.
void SetPasteConvertEndings (bool convert)
Enable/Disable convert-on-paste for line endings.
bool GetPasteConvertEndings () const
Get convert-on-paste setting.
void SelectionDuplicate ()
Duplicate the selection. If selection empty duplicate the line containing the caret.
void SetCaretLineBackAlpha (int alpha)
Set background alpha of the caret line.
int GetCaretLineBackAlpha () const
Get the background alpha of the caret line.
void SetCaretStyle (int caretStyle)
Set the style of the caret to be drawn.
int GetCaretStyle () const
Returns the current style of the caret.
void SetIndicatorCurrent (int indicator)
Set the indicator used for IndicatorFillRange and IndicatorClearRange.
int GetIndicatorCurrent () const
Get the current indicator.
void SetIndicatorValue (int value)
Set the value used for IndicatorFillRange.
int GetIndicatorValue () const
Get the current indicator value.
void IndicatorFillRange (int start, int lengthFill)
Turn a indicator on over a range.
void IndicatorClearRange (int start, int lengthClear)
Turn a indicator off over a range.
int IndicatorAllOnFor (int pos)
Are any indicators present at pos?
int IndicatorValueAt (int indicator, int pos)
What value does a particular indicator have at a position?
int IndicatorStart (int indicator, int pos)
Where does a particular indicator start?
int IndicatorEnd (int indicator, int pos)
Where does a particular indicator end?
void SetPositionCacheSize (int size)
Set number of entries in position cache.
int GetPositionCacheSize () const
How many entries are allocated to the position cache?
void CopyAllowLine ()
Copy the selection, if selection empty copy the line with the caret.
const char * GetRangePointer (int position, int rangeLength) const
Return a read-only pointer to a range of characters in the document.
int GetGapPosition () const
Return a position which, to avoid performance costs, should not be within the range of a call to GetRangePointer.
void IndicatorSetAlpha (int indicator, int alpha)
Set the alpha fill colour of the given indicator.
int IndicatorGetAlpha (int indicator) const
Get the alpha fill colour of the given indicator.
void IndicatorSetOutlineAlpha (int indicator, int alpha)
Set the alpha outline colour of the given indicator.
int IndicatorGetOutlineAlpha (int indicator) const
Get the alpha outline colour of the given indicator.
void SetExtraAscent (int extraAscent)
Set extra ascent for each line.
int GetExtraAscent () const
Get extra ascent for each line.
void SetExtraDescent (int extraDescent)
Set extra descent for each line.
int GetExtraDescent () const
Get extra descent for each line.
int GetMarkerSymbolDefined (int markerNumber)
Which symbol was defined for markerNumber with MarkerDefine.
void MarginSetText (int line, const wxString &text)
Set the text in the text margin for a line.
wxString MarginGetText (int line) const
Get the text in the text margin for a line.
void MarginSetStyle (int line, int style)
Set the style number for the text margin for a line.
int MarginGetStyle (int line) const
Get the style number for the text margin for a line.
void MarginSetStyles (int line, const wxString &styles)
Set the style in the text margin for a line.
wxString MarginGetStyles (int line) const
Get the styles in the text margin for a line.
void MarginTextClearAll ()
Clear the margin text on all lines.
void MarginSetStyleOffset (int style)
Get the start of the range of style numbers used for margin text.
int MarginGetStyleOffset () const
Get the start of the range of style numbers used for margin text.
void SetMarginOptions (int marginOptions)
Set the margin options.
int GetMarginOptions () const
Get the margin options.
void AnnotationSetText (int line, const wxString &text)
Set the annotation text for a line.
wxString AnnotationGetText (int line) const
Get the annotation text for a line.
void AnnotationSetStyle (int line, int style)
Set the style number for the annotations for a line.
int AnnotationGetStyle (int line) const
Get the style number for the annotations for a line.
void AnnotationSetStyles (int line, const wxString &styles)
Set the annotation styles for a line.
wxString AnnotationGetStyles (int line) const
Get the annotation styles for a line.
int AnnotationGetLines (int line) const
Get the number of annotation lines for a line.
void AnnotationClearAll ()
Clear the annotations from all lines.
void AnnotationSetVisible (int visible)
Set the visibility for the annotations for a view.
int AnnotationGetVisible () const
Get the visibility for the annotations for a view.
void AnnotationSetStyleOffset (int style)
Get the start of the range of style numbers used for annotations.
int AnnotationGetStyleOffset () const
Get the start of the range of style numbers used for annotations.
void ReleaseAllExtendedStyles ()
Release all extended (>255) style numbers.
int AllocateExtendedStyles (int numberStyles)
Allocate some extended (>255) style numbers and return the start of the range.
void AddUndoAction (int token, int flags)
Add a container action to the undo stack.
int CharPositionFromPoint (int x, int y)
Find the position of a character from a point within the window.
int CharPositionFromPointClose (int x, int y)
Find the position of a character from a point within the window.
void SetMouseSelectionRectangularSwitch (bool mouseSelectionRectangularSwitch)
Set whether switching to rectangular mode while selecting with the mouse is allowed.
bool GetMouseSelectionRectangularSwitch () const
Whether switching to rectangular mode while selecting with the mouse is allowed.
void SetMultipleSelection (bool multipleSelection)
Set whether multiple selections can be made.
bool GetMultipleSelection () const
Whether multiple selections can be made.
void SetAdditionalSelectionTyping (bool additionalSelectionTyping)
Set whether typing can be performed into multiple selections.
bool GetAdditionalSelectionTyping () const
Whether typing can be performed into multiple selections.
void SetAdditionalCaretsBlink (bool additionalCaretsBlink)
Set whether additional carets will blink.
bool GetAdditionalCaretsBlink () const
Whether additional carets will blink.
void SetAdditionalCaretsVisible (bool additionalCaretsVisible)
Set whether additional carets are visible.
bool GetAdditionalCaretsVisible () const
Whether additional carets are visible.
int GetSelections () const
How many selections are there?
bool GetSelectionEmpty () const
Is every selected range empty?
void ClearSelections ()
Clear selections to a single empty stream selection.
void SetSelectionVoid (int startPos, int endPos)
Select a range of text.
int SetSelectionInt (int caret, int anchor)
Set a simple selection.
int AddSelection (int caret, int anchor)
Add a selection.
void DropSelectionN (int selection)
Drop one selection.
void SetMainSelection (int selection)
Set the main selection.
int GetMainSelection () const
Which selection is the main selection.
void SetSelectionNCaret (int selection, int caret)
Set the caret position of the nth selection.
int GetSelectionNCaret (int selection) const
Return the caret position of the nth selection.
void SetSelectionNAnchor (int selection, int anchor)
Set the anchor position of the nth selection.
int GetSelectionNAnchor (int selection) const
Return the anchor position of the nth selection.
void SetSelectionNCaretVirtualSpace (int selection, int space)
Set the virtual space of the caret of the nth selection.
int GetSelectionNCaretVirtualSpace (int selection) const
Return the virtual space of the caret of the nth selection.
void SetSelectionNAnchorVirtualSpace (int selection, int space)
Set the virtual space of the anchor of the nth selection.
int GetSelectionNAnchorVirtualSpace (int selection) const
Return the virtual space of the anchor of the nth selection.
void SetSelectionNStart (int selection, int anchor)
Sets the position that starts the selection - this becomes the anchor.
int GetSelectionNStart (int selection) const
Returns the position at the start of the selection.
void SetSelectionNEnd (int selection, int caret)
Sets the position that ends the selection - this becomes the currentPosition.
int GetSelectionNEnd (int selection) const
Returns the position at the end of the selection.
void SetRectangularSelectionCaret (int caret)
Set the caret position of the rectangular selection.
int GetRectangularSelectionCaret () const
Return the caret position of the rectangular selection.
void SetRectangularSelectionAnchor (int anchor)
Set the anchor position of the rectangular selection.
int GetRectangularSelectionAnchor () const
Return the anchor position of the rectangular selection.
void SetRectangularSelectionCaretVirtualSpace (int space)
Set the virtual space of the caret of the rectangular selection.
int GetRectangularSelectionCaretVirtualSpace () const
Return the virtual space of the caret of the rectangular selection.
void SetRectangularSelectionAnchorVirtualSpace (int space)
Set the virtual space of the anchor of the rectangular selection.
int GetRectangularSelectionAnchorVirtualSpace () const
Return the virtual space of the anchor of the rectangular selection.
void SetVirtualSpaceOptions (int virtualSpaceOptions)
Set options for virtual space behaviour.
int GetVirtualSpaceOptions () const
Return options for virtual space behaviour.
void SetRectangularSelectionModifier (int modifier)
On GTK+, allow selecting the modifier key to use for mouse-based rectangular selection.
int GetRectangularSelectionModifier () const
Get the modifier key used for rectangular selection.
void SetAdditionalSelForeground (const wxColour &fore)
Set the foreground colour of additional selections.
void SetAdditionalSelBackground (const wxColour &back)
Set the background colour of additional selections.
void SetAdditionalSelAlpha (int alpha)
Set the alpha of the selection.
int GetAdditionalSelAlpha () const
Get the alpha of the selection.
void SetAdditionalCaretForeground (const wxColour &fore)
Set the foreground colour of additional carets.
wxColour GetAdditionalCaretForeground () const
Get the foreground colour of additional carets.
void RotateSelection ()
Set the main selection to the next selection.
void SwapMainAnchorCaret ()
Swap that caret and anchor of the main selection.
void MultipleSelectAddNext ()
Add the next occurrence of the main selection to the set of selections as main.
void MultipleSelectAddEach ()
Add each occurrence of the main selection in the target to the set of selections.
int ChangeLexerState (int start, int end)
Indicate that the internal state of a lexer has changed over a range and therefore there may be a need to redraw.
int ContractedFoldNext (int lineStart)
Find the next line at or after lineStart that is a contracted fold header line.
void VerticalCentreCaret ()
Centre current line in window.
void MoveSelectedLinesUp ()
Move the selected lines up one line, shifting the line above after the selection.
void MoveSelectedLinesDown ()
Move the selected lines down one line, shifting the line below before the selection.
void SetIdentifier (int identifier)
Set the identifier reported as idFrom in notification messages.
int GetIdentifier () const
Get the identifier.
void RGBAImageSetWidth (int width)
Set the width for future RGBA image data.
void RGBAImageSetHeight (int height)
Set the height for future RGBA image data.
void RGBAImageSetScale (int scalePercent)
Set the scale factor in percent for future RGBA image data.
void MarkerDefineRGBAImage (int markerNumber, const unsigned char *pixels)
Define a marker from RGBA data.
void RegisterRGBAImage (int type, const unsigned char *pixels)
Register an RGBA image for use in autocompletion lists.
void ScrollToStart ()
Scroll to start of document.
void ScrollToEnd ()
Scroll to end of document.
void SetTechnology (int technology)
Set the technology used.
int GetTechnology () const
Get the tech.
void * CreateLoader (int bytes) const
Create an ILoader*.
void VCHomeDisplay ()
Move caret to before first visible character on display line.
void VCHomeDisplayExtend ()
Like VCHomeDisplay but extending selection to new caret position.
bool GetCaretLineVisibleAlways () const
Is the caret line always visible?
void SetCaretLineVisibleAlways (bool alwaysVisible)
Sets the caret line to always visible.
void SetLineEndTypesAllowed (int lineEndBitSet)
Set the line end types that the application wants to use. May not be used if incompatible with lexer or encoding.
int GetLineEndTypesAllowed () const
Get the line end types currently allowed.
int GetLineEndTypesActive () const
Get the line end types currently recognised. May be a subset of the allowed types due to lexer limitation.
void SetRepresentation (const wxString &encodedCharacter, const wxString &representation)
Set the way a character is drawn.
wxString GetRepresentation (const wxString &encodedCharacter) const
Set the way a character is drawn.
void ClearRepresentation (const wxString &encodedCharacter)
Remove a character representation.
void StartRecord ()
Start notifying the container of all key presses and commands.
void StopRecord ()
Stop notifying the container of all key presses and commands.
void SetLexer (int lexer)
Set the lexing language of the document.
int GetLexer () const
Retrieve the lexing language of the document.
void Colourise (int start, int end)
Colourise a segment of the document using the current lexing language.
void SetProperty (const wxString &key, const wxString &value)
Set up a value that may be used by a lexer for some optional feature.
void SetKeyWords (int keyWordSet, const wxString &keyWords)
Set up the key words used by the lexer.
void SetLexerLanguage (const wxString &language)
Set the lexing language of the document based on string name.
void LoadLexerLibrary (const wxString &path)
Load a lexer library (dll / so).
wxString GetProperty (const wxString &key)
Retrieve a "property" value previously set with SetProperty.
wxString GetPropertyExpanded (const wxString &key)
Retrieve a "property" value previously set with SetProperty, with "$()" variable replacement on returned buffer.
int GetPropertyInt (const wxString &key, int defaultValue=0) const
Retrieve a "property" value previously set with SetProperty, interpreted as an int AFTER any "$()" variable replacement.
wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") int GetStyleBitsNeeded() const
Retrieve the number of bits the current lexer needs for styling.
wxString GetLexerLanguage () const
Retrieve the lexing language of the document.
void * PrivateLexerCall (int operation, void *pointer)
For private communication between an application and a known lexer.
wxString PropertyNames () const
Retrieve a '\n' separated list of properties understood by the current lexer.
int PropertyType (const wxString &name)
Retrieve the type of a property.
wxString DescribeProperty (const wxString &name) const
Describe a property.
wxString DescribeKeyWordSets () const
Retrieve a '\n' separated list of descriptions of the keyword sets understood by the current lexer.
int GetLineEndTypesSupported () const
Bit set of LineEndType enumertion for which line ends beyond the standard LF, CR, and CRLF are supported by the lexer.
int AllocateSubStyles (int styleBase, int numberStyles)
Allocate a set of sub styles for a particular base style, returning start of range.
int GetSubStylesStart (int styleBase) const
The starting style number for the sub styles associated with a base style.
int GetSubStylesLength (int styleBase) const
The number of sub styles associated with a base style.
int GetStyleFromSubStyle (int subStyle) const
For a sub style, return the base style, else return the argument.
int GetPrimaryStyleFromStyle (int style) const
For a secondary style, return the primary style, else return the argument.
void FreeSubStyles ()
Free allocated sub styles.
void SetIdentifiers (int style, const wxString &identifiers)
Set the identifiers that are shown in a particular style.
int DistanceToSecondaryStyles () const
Where styles are duplicated by a feature such as active/inactive code return the distance between the two types.
wxString GetSubStyleBases () const
Get the set of base styles that can be extended with sub styles.
int GetCurrentLine ()
Manually declared methods.
void StyleSetSpec (int styleNum, const wxString &spec)
Extract style settings from a spec-string which is composed of one or more of the following comma separated elements:
wxFont StyleGetFont (int style)
Get the font of a style.
void StyleSetFont (int styleNum, const wxFont &font)
Set style size, face, bold, italic, and underline attributes from a wxFont's attributes.
void StyleSetFontAttr (int styleNum, int size, const wxString &faceName, bool bold, bool italic, bool underline, wxFontEncoding encoding=wxFONTENCODING_DEFAULT)
Set all font style attributes at once.
void StyleSetFontEncoding (int style, wxFontEncoding encoding)
Set the font encoding to be used by a style.
void CmdKeyExecute (int cmd)
Perform one of the operations defined by the wxSCI_CMD_* constants.
void SetMargins (int left, int right)
Set the left and right margin in the edit area, measured in pixels.
void ScrollToLine (int line)
Scroll enough to make the given line visible.
void ScrollToColumn (int column)
Scroll enough to make the given column visible.
wxIntPtr SendMsg (int msg, wxUIntPtr wp=0, wxIntPtr lp=0) const
Send a message to Scintilla.
void SetVScrollBar (wxScrollBar *bar)
Set the vertical scrollbar to use instead of the one that's built-in.
void SetHScrollBar (wxScrollBar *bar)
Set the horizontal scrollbar to use instead of the one that's built-in.
bool GetLastKeydownProcessed ()
Can be used to prevent the EVT_CHAR handler from adding the char.
void SetLastKeydownProcessed (bool val)
bool SaveFile (const wxString &filename)
Write the contents of the editor to filename.
bool LoadFile (const wxString &filename)
Load the contents of filename into the editor.
wxDragResult DoDragEnter (wxCoord x, wxCoord y, wxDragResult def)
Allow for simulating a DnD DragEnter.
wxDragResult DoDragOver (wxCoord x, wxCoord y, wxDragResult def)
Allow for simulating a DnD DragOver.
void DoDragLeave ()
Allow for simulating a DnD DragLeave.
bool DoDropText (long x, long y, const wxString &data)
Allow for simulating a DnD DropText.
void SetUseAntiAliasing (bool useAA)
Specify whether anti-aliased fonts should be used.
bool GetUseAntiAliasing ()
Returns the current UseAntiAliasing setting.
void AnnotationClearLine (int line)
Clear annotations from the given line.
void AddTextRaw (const char *text, int length=-1)
The following methods are nearly equivalent to their similarly named cousins above.
void InsertTextRaw (int pos, const char *text)
Insert string at a position.
wxCharBuffer GetCurLineRaw (int *linePos=NULL)
Retrieve the text of the line containing the caret.
wxCharBuffer GetLineRaw (int line)
Retrieve the contents of a line.
wxCharBuffer GetSelectedTextRaw ()
Retrieve the selected text.
wxCharBuffer GetTargetTextRaw ()
Retrieve the target text.
wxCharBuffer GetTextRangeRaw (int startPos, int endPos)
Retrieve a range of text.
void SetTextRaw (const char *text)
Replace the contents of the document with the argument text.
wxCharBuffer GetTextRaw ()
Retrieve all the text in the document.
void AppendTextRaw (const char *text, int length=-1)
Append a string to the end of the document without changing the selection.
virtual void WriteText (const wxString &text)
implement wxTextEntryBase pure virtual methods
virtual void Remove (long from, long to)
virtual void Replace (long from, long to, const wxString &text)
virtual void SetInsertionPoint (long pos)
virtual long GetInsertionPoint () const
virtual long GetLastPosition () const
virtual void SetSelection (long from, long to)
virtual void SelectNone ()
virtual void GetSelection (long *from, long *to) const
void GetSelection (int *from, int *to)
kept for compatibility only
virtual bool IsEditable () const
virtual void SetEditable (bool editable)
void SetMouseCapture (bool on)
bool HaveMouseCapture () const
Static Public Member Functions
static wxVersionInfo GetLibraryVersionInfo ()
Protected Member Functions
wxString GetValue () const
void SetValue (const wxString &text)
virtual void DoSetValue (const wxString &value, int flags)
virtual wxString DoGetValue () const
virtual wxWindow * GetEditableWindow ()
virtual bool DoLoadFile (const wxString &file, int fileType)
virtual bool DoSaveFile (const wxString &file, int fileType)
void OnPaint (wxPaintEvent &evt)
Event handlers.
void OnScrollWin (wxScrollWinEvent &evt)
void OnScroll (wxScrollEvent &evt)
void OnSize (wxSizeEvent &evt)
void OnMouseLeftDown (wxMouseEvent &evt)
void OnMouseRightDown (wxMouseEvent &evt)
void OnMouseMove (wxMouseEvent &evt)
void OnMouseLeftUp (wxMouseEvent &evt)
void OnMouseRightUp (wxMouseEvent &evt)
void OnMouseMiddleUp (wxMouseEvent &evt)
void OnContextMenu (wxContextMenuEvent &evt)
void OnMouseWheel (wxMouseEvent &evt)
void OnChar (wxKeyEvent &evt)
void OnKeyDown (wxKeyEvent &evt)
void OnLoseFocus (wxFocusEvent &evt)
void OnGainFocus (wxFocusEvent &evt)
void OnSysColourChanged (wxSysColourChangedEvent &evt)
void OnEraseBackground (wxEraseEvent &evt)
void OnMenu (wxCommandEvent &evt)
void OnListBox (wxCommandEvent &evt)
void OnIdle (wxIdleEvent &evt)
void OnMouseCaptureLost (wxMouseCaptureLostEvent &evt)
virtual wxSize DoGetBestSize () const override
void NotifyChange ()
Turn notifications from Scintilla into events.
void NotifyParent (SCNotification *scn)
Protected Attributes
ScintillaWX * m_swx
wxStopWatch m_stopWatch
wxScrollBar * m_vScrollBar
wxScrollBar * m_hScrollBar
bool m_lastKeyDownConsumed
Private Member Functions
DECLARE_EVENT_TABLE ()
DECLARE_DYNAMIC_CLASS (wxScintilla)
Friends
class ScintillaWX
class Platform
Detailed Description
Definition at line 2865 of file wxscintilla.h.
Constructor & Destructor Documentation
wxScintilla() [1/2]
wxScintilla::wxScintilla (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0, const wxString & name = wxSCINameStr)
wxScintilla() [2/2]
wxScintilla::wxScintilla () inline
Definition at line 2883 of file wxscintilla.h.
References Associations::ClearAll(), CCManagerHelper::FindColumn(), GetSelectedText(), NULL, ParserConsts::space, wxDefaultPosition, wxDefaultSize, wxFONTENCODING_DEFAULT, wxID_ANY, wxNullColour, and wxSCINameStr.
~wxScintilla()
wxScintilla::~wxScintilla ()
Member Function Documentation
AddRefDocument()
void wxScintilla::AddRefDocument (void * docPointer)
Extend life of document.
AddSelection()
int wxScintilla::AddSelection (int caret, int anchor)
Add a selection.
Referenced by MainFrame::OnEditSelectAll(), and MainFrame::OnEditSelectNextSkip().
AddStyledText()
void wxScintilla::AddStyledText (const wxMemoryBuffer & data)
Add array of cells to document.
AddTabStop()
void wxScintilla::AddTabStop (int line, int x)
Add an explicit tab stop for a line.
AddText()
void wxScintilla::AddText (const wxString & text)
Generated method declaration section {{{.
Add text to the document at current position.
Referenced by cbStyledTextCtrl::DoSelectionBraceCompletion().
AddTextRaw()
void wxScintilla::AddTextRaw (const char * text, int length = -1)
The following methods are nearly equivalent to their similarly named cousins above.
The difference is that these methods bypass wxString and always use a char* even if used in a unicode build of wxWidgets. In that case the character data will be utf-8 encoded since that is what is used internally by Scintilla in unicode builds. Add text to the document at current position.
AddUndoAction()
void wxScintilla::AddUndoAction (int token, int flags)
Add a container action to the undo stack.
Allocate()
void wxScintilla::Allocate (int bytes)
Enlarge the document to a particular size of text bytes.
AllocateExtendedStyles()
int wxScintilla::AllocateExtendedStyles (int numberStyles)
Allocate some extended (>255) style numbers and return the start of the range.
AllocateSubStyles()
int wxScintilla::AllocateSubStyles (int styleBase, int numberStyles)
Allocate a set of sub styles for a particular base style, returning start of range.
AnnotationClearAll()
void wxScintilla::AnnotationClearAll ()
Clear the annotations from all lines.
AnnotationClearLine()
void wxScintilla::AnnotationClearLine (int line)
Clear annotations from the given line.
AnnotationGetLines()
int wxScintilla::AnnotationGetLines (int line) const
Get the number of annotation lines for a line.
AnnotationGetStyle()
int wxScintilla::AnnotationGetStyle (int line) const
Get the style number for the annotations for a line.
AnnotationGetStyleOffset()
int wxScintilla::AnnotationGetStyleOffset () const
Get the start of the range of style numbers used for annotations.
AnnotationGetStyles()
wxString wxScintilla::AnnotationGetStyles (int line) const
Get the annotation styles for a line.
AnnotationGetText()
wxString wxScintilla::AnnotationGetText (int line) const
Get the annotation text for a line.
AnnotationGetVisible()
int wxScintilla::AnnotationGetVisible () const
Get the visibility for the annotations for a view.
AnnotationSetStyle()
void wxScintilla::AnnotationSetStyle (int line, int style)
Set the style number for the annotations for a line.
AnnotationSetStyleOffset()
void wxScintilla::AnnotationSetStyleOffset (int style)
Get the start of the range of style numbers used for annotations.
AnnotationSetStyles()
void wxScintilla::AnnotationSetStyles (int line, const wxString & styles)
Set the annotation styles for a line.
AnnotationSetText()
void wxScintilla::AnnotationSetText (int line, const wxString & text)
Set the annotation text for a line.
AnnotationSetVisible()
void wxScintilla::AnnotationSetVisible (int visible)
Set the visibility for the annotations for a view.
AppendText()
void wxScintilla::AppendText (const wxString & text)
Append a string to the end of the document without changing the selection.
Referenced by DisassemblyDlg::AddAssemblerLine(), and DisassemblyDlg::AddSourceLine().
AppendTextRaw()
void wxScintilla::AppendTextRaw (const char * text, int length = -1)
Append a string to the end of the document without changing the selection.
AutoCompActive()
bool wxScintilla::AutoCompActive ()
Is there an auto-completion list visible?
Referenced by CCManager::DoBufferedCC(), InsertNewLine(), CCManager::OnCompleteCode(), MainFrame::OnEditGotoLineEnd(), MainFrame::OnEditInsertNewLine(), CCManager::OnEditorHook(), MainFrame::OnEditUndo(), cbStyledTextCtrl::OnKeyDown(), cbStyledTextCtrl::OnKillFocus(), and CCManager::OnTimer().
AutoCompCancel()
void wxScintilla::AutoCompCancel ()
Remove the auto-completion list from the screen.
Referenced by InsertNewLine(), MainFrame::OnEditGotoLineEnd(), MainFrame::OnEditInsertNewLine(), CCManager::OnEditorHook(), MainFrame::OnEditUndo(), and cbStyledTextCtrl::OnKillFocus().
AutoCompComplete()
void wxScintilla::AutoCompComplete ()
User has selected an item so remove the list and insert the selection.
AutoCompGetAutoHide()
bool wxScintilla::AutoCompGetAutoHide () const
Retrieve whether or not autocompletion is hidden automatically when nothing matches.
AutoCompGetCancelAtStart()
bool wxScintilla::AutoCompGetCancelAtStart () const
Retrieve whether auto-completion cancelled by backspacing before start.
AutoCompGetCaseInsensitiveBehaviour()
int wxScintilla::AutoCompGetCaseInsensitiveBehaviour () const
Get auto-completion case insensitive behaviour.
AutoCompGetChooseSingle()
bool wxScintilla::AutoCompGetChooseSingle () const
Retrieve whether a single item auto-completion list automatically choose the item.
AutoCompGetCurrent()
int wxScintilla::AutoCompGetCurrent () const
Get currently selected item position in the auto-completion list.
Referenced by CCManager::OnTimer().
AutoCompGetCurrentText()
wxString wxScintilla::AutoCompGetCurrentText () const
Get currently selected item text in the auto-completion list.
AutoCompGetDropRestOfWord()
bool wxScintilla::AutoCompGetDropRestOfWord () const
Retrieve whether or not autocompletion deletes any word characters after the inserted text upon completion.
AutoCompGetIgnoreCase()
bool wxScintilla::AutoCompGetIgnoreCase () const
Retrieve state of ignore case flag.
AutoCompGetMaxHeight()
int wxScintilla::AutoCompGetMaxHeight () const
Set the maximum height, in rows, of auto-completion and user lists.
Referenced by CCManager::OnAutocompleteSelect().
AutoCompGetMaxWidth()
int wxScintilla::AutoCompGetMaxWidth () const
Get the maximum width, in characters, of auto-completion and user lists.
AutoCompGetMulti()
int wxScintilla::AutoCompGetMulti () const
Retrieve the effect of autocompleting when there are multiple selections.
AutoCompGetOrder()
int wxScintilla::AutoCompGetOrder () const
Get the way autocompletion lists are ordered.
AutoCompGetSeparator()
int wxScintilla::AutoCompGetSeparator () const
Retrieve the auto-completion list separator character.
AutoCompGetTypeSeparator()
int wxScintilla::AutoCompGetTypeSeparator () const
Retrieve the auto-completion list type-separator character.
AutoCompPosStart()
int wxScintilla::AutoCompPosStart ()
Retrieve the position of the caret when the auto-completion list was displayed.
AutoCompSelect()
void wxScintilla::AutoCompSelect (const wxString & select)
Select the item in the auto-completion list that starts with a string.
Referenced by CCManager::DoBufferedCC(), and CCManager::OnCompleteCode().
AutoCompSetAutoHide()
void wxScintilla::AutoCompSetAutoHide (bool autoHide)
Set whether or not autocompletion is hidden automatically when nothing matches.
AutoCompSetCancelAtStart()
void wxScintilla::AutoCompSetCancelAtStart (bool cancel)
Should the auto-completion list be cancelled if the user backspaces to a position before where the box was created.
AutoCompSetCaseInsensitiveBehaviour()
void wxScintilla::AutoCompSetCaseInsensitiveBehaviour (int behaviour)
Set auto-completion case insensitive behaviour to either prefer case-sensitive matches or have no preference.
AutoCompSetChooseSingle()
void wxScintilla::AutoCompSetChooseSingle (bool chooseSingle)
Should a single item auto-completion list automatically choose the item.
AutoCompSetDropRestOfWord()
void wxScintilla::AutoCompSetDropRestOfWord (bool dropRestOfWord)
Set whether or not autocompletion deletes any word characters after the inserted text upon completion.
AutoCompSetFillUps()
void wxScintilla::AutoCompSetFillUps (const wxString & characterSet)
Define a set of characters that when typed will cause the autocompletion to choose the selected item.
AutoCompSetIgnoreCase()
void wxScintilla::AutoCompSetIgnoreCase (bool ignoreCase)
Set whether case is significant when performing auto-completion searches.
Referenced by CCManager::OnCompleteCode().
AutoCompSetMaxHeight()
void wxScintilla::AutoCompSetMaxHeight (int rowCount)
Set the maximum height, in rows, of auto-completion and user lists.
The default is 5 rows.
Referenced by CCManager::OnCompleteCode().
AutoCompSetMaxWidth()
void wxScintilla::AutoCompSetMaxWidth (int characterCount)
Set the maximum width, in characters, of auto-completion and user lists.
Set to 0 to autosize to fit longest item, which is the default.
AutoCompSetMulti()
void wxScintilla::AutoCompSetMulti (int multi)
Change the effect of autocompleting when there are multiple selections.
AutoCompSetOrder()
void wxScintilla::AutoCompSetOrder (int order)
Set the way autocompletion lists are ordered.
Referenced by CCManager::OnCompleteCode().
AutoCompSetSeparator()
void wxScintilla::AutoCompSetSeparator (int separatorCharacter)
Change the separator character in the string setting up an auto-completion list.
Default is space but can be changed if items contain space.
Referenced by CCManager::OnCompleteCode().
AutoCompSetTypeSeparator()
void wxScintilla::AutoCompSetTypeSeparator (int separatorCharacter)
Change the type-separator character in the string setting up an auto-completion list.
Default is '?' but can be changed if items contain '?'.
Referenced by CCManager::OnCompleteCode().
AutoCompShow()
void wxScintilla::AutoCompShow (int lengthEntered, const wxString & itemList)
Display a auto-completion list.
The lengthEntered parameter indicates how many characters before the caret should be used to provide context.
Referenced by CCManager::DoBufferedCC(), CCManager::InjectAutoCompShow(), and CCManager::OnCompleteCode().
AutoCompStops()
void wxScintilla::AutoCompStops (const wxString & characterSet)
Define a set of character that when typed cancel the auto-completion list.
BackTab()
void wxScintilla::BackTab ()
Dedent the selected lines.
BeginUndoAction()
void wxScintilla::BeginUndoAction ()
Start a sequence of actions that is undone and redone as a unit.
May be nested.
Referenced by CodeRefactoring::DoRenameSymbols(), cbStyledTextCtrl::DoSelectionBraceCompletion(), InsertNewLine(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditEOLMode(), MainFrame::OnEditLineMove(), MainFrame::OnEditLinePaste(), cbEditor::OnEditorCharAdded(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and cbEditor::Save().
BraceBadLight()
void wxScintilla::BraceBadLight (int pos)
Highlight the character at a position indicating there is no matching brace.
Referenced by cbEditor::HighlightBraces().
BraceBadLightIndicator()
void wxScintilla::BraceBadLightIndicator (bool useSetting, int indicator)
Use specified indicator to highlight non matching brace instead of changing its style.
BraceHighlight()
void wxScintilla::BraceHighlight (int posA, int posB)
Highlight the characters at two positions.
Referenced by cbEditor::HighlightBraces().
BraceHighlightIndicator()
void wxScintilla::BraceHighlightIndicator (bool useSetting, int indicator)
Use specified indicator to highlight matching braces instead of changing their style.
BraceMatch()
int wxScintilla::BraceMatch (int pos, int maxReStyle = 0)
Find the position of a matching brace or wxSCI_INVALID_POSITION if no match.
The maxReStyle must be 0 for now. It may be defined in a future release.
Referenced by cbStyledTextCtrl::DoBraceCompletion(), cbEditor::GotoMatchingBrace(), cbEditor::HighlightBraces(), and NativeParser::ParseLocalBlock().
CallTipActive()
bool wxScintilla::CallTipActive ()
Is there an active call tip?
Referenced by CCManager::DoBufferedCC(), CodeCompletion::DoCodeComplete(), CCManager::DoShowTips(), CCManager::OnCompleteCode(), CCManager::OnDeactivateApp(), CCManager::OnDeactivateEd(), CCManager::OnEditorHook(), CCManager::OnEditorTooltip(), cbStyledTextCtrl::OnKeyDown(), cbStyledTextCtrl::OnKillFocus(), CCManager::OnMenuSelect(), CCManager::ProcessArrow(), cbDebuggerPlugin::ProcessValueTooltip(), and DebugInterfaceFactory::ShowValueTooltip().
CallTipCancel()
void wxScintilla::CallTipCancel ()
Remove the call tip from the screen.
Referenced by cbStyledTextCtrl::CallTipCancel(), and cbStyledTextCtrl::GetLastSelectedText().
CallTipPosAtStart()
int wxScintilla::CallTipPosAtStart ()
Retrieve the position where the caret was before displaying the call tip.
CallTipSetBackground()
void wxScintilla::CallTipSetBackground (const wxColour & back)
Set the background colour for the call tip.
Referenced by setupColours().
CallTipSetForeground()
void wxScintilla::CallTipSetForeground (const wxColour & fore)
Set the foreground colour for the call tip.
Referenced by setupColours().
CallTipSetForegroundHighlight()
void wxScintilla::CallTipSetForegroundHighlight (const wxColour & fore)
Set the foreground colour for the highlighted part of the call tip.
Referenced by setupColours().
CallTipSetHighlight()
void wxScintilla::CallTipSetHighlight (int highlightStart, int highlightEnd)
Highlight a segment of the definition.
Referenced by CCManager::DoShowTips().
CallTipSetPosAtStart()
void wxScintilla::CallTipSetPosAtStart (int posStart)
Set the start position in order to change when backspacing removes the calltip.
CallTipSetPosition()
void wxScintilla::CallTipSetPosition (bool above)
Set position of calltip, above or below text.
CallTipShow()
void wxScintilla::CallTipShow (int pos, const wxString & definition)
Show a call tip containing a definition near position pos.
Referenced by CodeCompletion::DoCodeComplete(), and CCManager::DoShowTips().
CallTipUseStyle()
void wxScintilla::CallTipUseStyle (int tabSize)
Enable use of wxSCI_STYLE_CALLTIP and set call tip tab size in pixels.
Cancel()
void wxScintilla::Cancel ()
Cancel any modes such as call tip or auto-completion list display.
CanPaste()
bool wxScintilla::CanPaste () const
Will a paste succeed?
Referenced by cbEditor::AddToContextMenu(), and cbEditor::CanPaste().
CanRedo()
bool wxScintilla::CanRedo () const
Are there any redoable actions in the undo history?
Referenced by cbEditor::CanRedo(), and cbEditor::CreateContextSubMenu().
CanUndo()
bool wxScintilla::CanUndo () const
Are there any undoable actions in the undo history?
Referenced by cbEditor::CanUndo(), and cbEditor::CreateContextSubMenu().
ChangeInsertion()
void wxScintilla::ChangeInsertion (int length, const wxString & text)
Change the text that is being inserted in response to wxSCI_MOD_INSERTCHECK.
ChangeLexerState()
int wxScintilla::ChangeLexerState (int start, int end)
Indicate that the internal state of a lexer has changed over a range and therefore there may be a need to redraw.
CharLeft()
void wxScintilla::CharLeft ()
Move caret left one character.
CharLeftExtend()
void wxScintilla::CharLeftExtend ()
Move caret left one character extending selection to new caret position.
CharLeftRectExtend()
void wxScintilla::CharLeftRectExtend ()
Move caret left one character, extending rectangular selection to new caret position.
CharPositionFromPoint()
int wxScintilla::CharPositionFromPoint (int x, int y)
Find the position of a character from a point within the window.
CharPositionFromPointClose()
int wxScintilla::CharPositionFromPointClose (int x, int y)
Find the position of a character from a point within the window.
Return wxSCI_INVALID_POSITION if not close to text.
CharRight()
void wxScintilla::CharRight ()
Move caret right one character.
Referenced by cbStyledTextCtrl::DoBraceCompletion(), and cbStyledTextCtrl::OnKeyDown().
CharRightExtend()
void wxScintilla::CharRightExtend ()
Move caret right one character extending selection to new caret position.
CharRightRectExtend()
void wxScintilla::CharRightRectExtend ()
Move caret right one character, extending rectangular selection to new caret position.
ChooseCaretX()
void wxScintilla::ChooseCaretX ()
Set the last x chosen value to be the caret x position.
Referenced by cbEditor::GotoMatchingBrace(), and cbEditor::OnEditorCharAdded().
Clear()
void wxScintilla::Clear ()
Clear the selection.
ClearAll()
void wxScintilla::ClearAll ()
Delete all text in the document.
Referenced by DisassemblyDlg::AddAssemblerLine(), DisassemblyDlg::AddSourceLine(), DisassemblyDlg::Clear(), and cbEditor::Open().
ClearDocumentStyle()
void wxScintilla::ClearDocumentStyle ()
Set all style bytes to 0, remove all folding information.
ClearRegisteredImages()
void wxScintilla::ClearRegisteredImages ()
Clear all the registered images.
Referenced by CodeCompletion::DoCodeComplete(), CodeCompletion::DoCodeCompleteIncludes(), and CodeCompletion::DoCodeCompletePreprocessor().
ClearRepresentation()
void wxScintilla::ClearRepresentation (const wxString & encodedCharacter)
Remove a character representation.
ClearSelections()
void wxScintilla::ClearSelections ()
Clear selections to a single empty stream selection.
Referenced by MainFrame::OnEditSelectNextSkip().
ClearTabStops()
void wxScintilla::ClearTabStops (int line)
Clear explicit tabstops on a line.
CmdKeyAssign()
void wxScintilla::CmdKeyAssign (int key, int modifiers, int cmd)
When key+modifier combination keyDefinition is pressed perform sciCommand.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
CmdKeyClear()
void wxScintilla::CmdKeyClear (int key, int modifiers)
When key+modifier combination keyDefinition is pressed do nothing.
CmdKeyClearAll()
void wxScintilla::CmdKeyClearAll ()
Drop all key mappings.
CmdKeyExecute()
void wxScintilla::CmdKeyExecute (int cmd)
Perform one of the operations defined by the wxSCI_CMD_* constants.
Colourise()
void wxScintilla::Colourise (int start, int end)
Colourise a segment of the document using the current lexing language.
Referenced by EditorColourSet::Apply(), cbEditor::DoFoldAll(), cbEditor::DoFoldBlockFromLine(), cbEditor::InternalSetEditorStyleAfterFileOpen(), and CodeCompletion::UpdateEditorSyntax().
ContractedFoldNext()
int wxScintilla::ContractedFoldNext (int lineStart)
Find the next line at or after lineStart that is a contracted fold header line.
Return -1 when no more lines.
Referenced by cbEditor::UpdateProjectFile().
ConvertEOLs()
void wxScintilla::ConvertEOLs (int eolMode)
Convert all line endings in the document to one mode.
Referenced by cbEditorInternalData::EnsureConsistentLineEnds(), MainFrame::OnEditEOLMode(), FindReplace::Replace(), and FindReplace::ReplaceInFiles().
Copy()
void wxScintilla::Copy ()
Copy the selection to the clipboard.
Referenced by cbEditor::Copy(), and cbEditor::OnContextMenuEntry().
CopyAllowLine()
void wxScintilla::CopyAllowLine ()
Copy the selection, if selection empty copy the line with the caret.
CopyRange()
void wxScintilla::CopyRange (int start, int end)
Copy a range of text to the clipboard. Positions are clipped into the document.
CopyText()
void wxScintilla::CopyText (int length, const wxString & text)
Copy argument text to the clipboard.
CountCharacters()
int wxScintilla::CountCharacters (int start, int end)
Count characters between two positions.
Create()
bool wxScintilla::Create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0, const wxString & name = wxSCINameStr)
CreateDocument()
void* wxScintilla::CreateDocument ()
Create a new document object.
Starts with reference count of 1 and not selected into editor.
CreateLoader()
void* wxScintilla::CreateLoader (int bytes) const
Create an ILoader*.
Cut()
void wxScintilla::Cut ()
Cut the selection to the clipboard.
Referenced by cbEditor::Cut(), and cbEditor::OnContextMenuEntry().
DECLARE_DYNAMIC_CLASS()
wxScintilla::DECLARE_DYNAMIC_CLASS (wxScintilla) private
DECLARE_EVENT_TABLE()
wxScintilla::DECLARE_EVENT_TABLE () private
DeleteBack()
void wxScintilla::DeleteBack ()
Delete the selection or if no selection, the character before the caret.
Referenced by cbStyledTextCtrl::DoBraceCompletion(), cbStyledTextCtrl::DoSelectionBraceCompletion(), and cbStyledTextCtrl::OnKeyDown().
DeleteBackNotLine()
void wxScintilla::DeleteBackNotLine ()
Delete the selection or if no selection, the character before the caret.
Will not delete the character before at the start of a line.
DeleteRange()
void wxScintilla::DeleteRange (int start, int lengthDelete)
Delete a range of text in the document.
Referenced by MainFrame::OnEditLineMove().
DelLineLeft()
void wxScintilla::DelLineLeft ()
Delete back from the current position to the start of the line.
DelLineRight()
void wxScintilla::DelLineRight ()
Delete forwards from the current position to the end of the line.
DelWordLeft()
void wxScintilla::DelWordLeft ()
Delete the word to the left of the caret.
DelWordRight()
void wxScintilla::DelWordRight ()
Delete the word to the right of the caret.
DelWordRightEnd()
void wxScintilla::DelWordRightEnd ()
Delete the word to the right of the caret, but not the trailing non-word characters.
DescribeKeyWordSets()
wxString wxScintilla::DescribeKeyWordSets () const
Retrieve a '\n' separated list of descriptions of the keyword sets understood by the current lexer.
Referenced by EditorConfigurationDlg::OnEditKeywords().
DescribeProperty()
wxString wxScintilla::DescribeProperty (const wxString & name) const
Describe a property.
DistanceToSecondaryStyles()
int wxScintilla::DistanceToSecondaryStyles () const
Where styles are duplicated by a feature such as active/inactive code return the distance between the two types.
DocLineFromVisible()
int wxScintilla::DocLineFromVisible (int displayLine)
Find the document line of a display line taking hidden lines into account.
DocumentEnd()
void wxScintilla::DocumentEnd ()
Move caret to last position in document.
DocumentEndExtend()
void wxScintilla::DocumentEndExtend ()
Move caret to last position in document extending selection to new caret position.
DocumentStart()
void wxScintilla::DocumentStart ()
Move caret to first position in document.
DocumentStartExtend()
void wxScintilla::DocumentStartExtend ()
Move caret to first position in document extending selection to new caret position.
DoDragEnter()
wxDragResult wxScintilla::DoDragEnter (wxCoord x, wxCoord y, wxDragResult def)
Allow for simulating a DnD DragEnter.
DoDragLeave()
void wxScintilla::DoDragLeave ()
Allow for simulating a DnD DragLeave.
DoDragOver()
wxDragResult wxScintilla::DoDragOver (wxCoord x, wxCoord y, wxDragResult def)
Allow for simulating a DnD DragOver.
DoDropText()
bool wxScintilla::DoDropText (long x, long y, const wxString & data)
Allow for simulating a DnD DropText.
DoGetBestSize()
virtual wxSize wxScintilla::DoGetBestSize () const override protected virtual
DoGetValue()
virtual wxString wxScintilla::DoGetValue () const inline protected virtual
Definition at line 5350 of file wxscintilla.h.
DoLoadFile()
virtual bool wxScintilla::DoLoadFile (const wxString & file, int fileType) protected virtual
DoSaveFile()
virtual bool wxScintilla::DoSaveFile (const wxString & file, int fileType) protected virtual
DoSetValue()
virtual void wxScintilla::DoSetValue (const wxString & value, int flags) protected virtual
DropSelectionN()
void wxScintilla::DropSelectionN (int selection)
Drop one selection.
EditToggleOvertype()
void wxScintilla::EditToggleOvertype ()
Switch from insert to overtype mode or the reverse.
EmptyUndoBuffer()
void wxScintilla::EmptyUndoBuffer (bool collectChangeHistory = false)
Delete the undo history.
Referenced by cbEditor::ClearHistory(), cbEditor::OnContextMenuEntry(), and cbEditor::Open().
EndUndoAction()
void wxScintilla::EndUndoAction ()
End a sequence of actions that is undone and redone as a unit.
Referenced by CodeRefactoring::DoRenameSymbols(), cbStyledTextCtrl::DoSelectionBraceCompletion(), InsertNewLine(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditEOLMode(), MainFrame::OnEditLineMove(), MainFrame::OnEditLinePaste(), cbEditor::OnEditorCharAdded(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and cbEditor::Save().
EnsureCaretVisible()
void wxScintilla::EnsureCaretVisible ()
Ensure the caret is visible.
EnsureVisible()
void wxScintilla::EnsureVisible (int line)
Ensure a particular line is visible by expanding any header line hiding it.
Referenced by FindReplace::Find(), cbEditor::GotoLine(), FindReplace::Replace(), and FindReplace::ReplaceInFiles().
EnsureVisibleEnforcePolicy()
void wxScintilla::EnsureVisibleEnforcePolicy (int line)
Ensure a particular line is visible by expanding any header line hiding it.
Use the currently set visibility policy to determine which range to display.
Referenced by cbEditor::DoFoldBlockFromLine().
ExpandChildren()
void wxScintilla::ExpandChildren (int line, int level)
Expand a fold header and all children. Use the level argument instead of the line's current level.
FindChangedLine()
int wxScintilla::FindChangedLine (const int fromLine, const int toLine) const
Find a changed line, if fromLine > toLine search is performed backwards.
Referenced by cbEditor::GotoNextChanged(), and cbEditor::GotoPreviousChanged().
FindColumn()
int wxScintilla::FindColumn (int line, int column)
Find the position of a column on a line taking into account tabs and multi-byte characters.
If beyond end of line, return line end position.
FindText()
int wxScintilla::FindText (int minPos, int maxPos, const wxString & text, int flags = 0, int * findEnd = NULL)
Find some text in the document.
Referenced by FindReplace::Find(), CodeRefactoring::Find(), cbSmartIndentPlugin::FindBlockStart(), cbEditor::GotoTokenPosition(), MainFrame::OnEditSelectAll(), FindReplace::Replace(), and FindReplace::ReplaceInFiles().
FoldAll()
void wxScintilla::FoldAll (int action)
Expand or contract all fold headers.
FoldChildren()
void wxScintilla::FoldChildren (int line, int action)
Expand or contract a fold header and its children.
FoldDisplayTextSetStyle()
void wxScintilla::FoldDisplayTextSetStyle (int style)
Set the style of fold display text.
FoldLine()
void wxScintilla::FoldLine (int line, int action)
Expand or contract a fold header.
Referenced by cbEditor::DoFoldAll(), and cbEditor::DoFoldBlockFromLine().
FormatRange()
int wxScintilla::FormatRange (bool doDraw, int startPos, int endPos, wxDC * draw, wxDC * target, wxRect renderRect, wxRect pageRect)
On Windows, will draw the document into a display context such as a printer.
Referenced by cbEditorPrintout::GetPageInfo(), and cbEditorPrintout::OnPrintPage().
FormFeed()
void wxScintilla::FormFeed ()
Insert a Form Feed character.
FreeSubStyles()
void wxScintilla::FreeSubStyles ()
Free allocated sub styles.
GetAdditionalCaretForeground()
wxColour wxScintilla::GetAdditionalCaretForeground () const
Get the foreground colour of additional carets.
GetAdditionalCaretsBlink()
bool wxScintilla::GetAdditionalCaretsBlink () const
Whether additional carets will blink.
GetAdditionalCaretsVisible()
bool wxScintilla::GetAdditionalCaretsVisible () const
Whether additional carets are visible.
GetAdditionalSelAlpha()
int wxScintilla::GetAdditionalSelAlpha () const
Get the alpha of the selection.
GetAdditionalSelectionTyping()
bool wxScintilla::GetAdditionalSelectionTyping () const
Whether typing can be performed into multiple selections.
GetAllLinesVisible()
bool wxScintilla::GetAllLinesVisible () const
Are all lines visible?
GetAnchor()
int wxScintilla::GetAnchor () const
Returns the position of the opposite end of the selection to the caret.
Referenced by cbEditor::Save().
GetAutomaticFold()
int wxScintilla::GetAutomaticFold () const
Get automatic folding behaviours.
GetBackSpaceUnIndents()
bool wxScintilla::GetBackSpaceUnIndents () const
Does a backspace pressed when caret is within indentation unindent?
GetBufferedDraw()
bool wxScintilla::GetBufferedDraw () const
Is drawing done first into a buffer or direct to the screen?
GetCaretForeground()
wxColour wxScintilla::GetCaretForeground () const
Get the foreground colour of the caret.
Referenced by cbStyledTextCtrl::HighlightRightBrace().
GetCaretLineBackAlpha()
int wxScintilla::GetCaretLineBackAlpha () const
Get the background alpha of the caret line.
GetCaretLineBackground()
wxColour wxScintilla::GetCaretLineBackground () const
Get the colour of the background of the line containing the caret.
Referenced by cbEditor::SetLanguageDependentColours().
GetCaretLineVisible()
bool wxScintilla::GetCaretLineVisible () const
Is the background of the line containing the caret in a different colour?
GetCaretLineVisibleAlways()
bool wxScintilla::GetCaretLineVisibleAlways () const
Is the caret line always visible?
GetCaretPeriod()
int wxScintilla::GetCaretPeriod () const
Get the time in milliseconds that the caret is on and off.
GetCaretSticky()
int wxScintilla::GetCaretSticky () const
Can the caret preferred x position only be changed by explicit movement commands?
GetCaretStyle()
int wxScintilla::GetCaretStyle () const
Returns the current style of the caret.
GetCaretWidth()
int wxScintilla::GetCaretWidth () const
Returns the width of the insert mode caret.
Referenced by cbStyledTextCtrl::HighlightRightBrace().
GetCharAt()
int wxScintilla::GetCharAt (int pos) const
Returns the character byte at the position.
Referenced by CodeCompletion::DoAutocomplete(), cbStyledTextCtrl::DoBraceCompletion(), CCManager::DoUpdateCallTip(), NativeParser::FindCurrentFunctionStart(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), cbSmartIndentPlugin::GetFirstBraceInLine(), cbSmartIndentPlugin::GetLastNonCommentWord(), CodeCompletionHelper::GetLastNonWhitespaceChar(), cbSmartIndentPlugin::GetLastNonWhitespaceChars(), CodeCompletionHelper::GetNextNonWhitespaceChar(), cbSmartIndentPlugin::GetNextNonWhitespaceCharOfLine(), cbSmartIndentPlugin::GetNextNonWhitespaceCharOnLine(), cbEditorInternalData::GetUrl(), cbEditor::HighlightBraces(), cbStyledTextCtrl::HighlightRightBrace(), MainFrame::OnEditStreamCommentSelected(), cbStyledTextCtrl::OnKeyDown(), cbStyledTextCtrl::OnKeyUp(), CCManager::OnShowCallTip(), NativeParser::ParseLocalBlock(), and cbEditorInternalData::StripTrailingSpaces().
GetCodePage()
int wxScintilla::GetCodePage () const
Get the code page used to interpret the bytes of the document as characters.
GetColumn()
int wxScintilla::GetColumn (int pos) const
Retrieve the column number of a position, taking tab width into account.
Referenced by CCManager::DoShowTips(), MainFrame::DoUpdateStatusBar(), CCManagerHelper::FindColumn(), cbEditor::HighlightBraces(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), MacrosManager::RecalcVars(), and cbEditor::Save().
GetControlCharSymbol()
int wxScintilla::GetControlCharSymbol () const
Get the way control characters are displayed.
GetCurLine()
wxString wxScintilla::GetCurLine (int * linePos = NULL)
Retrieve the text of the line containing the caret.
Referenced by CodeCompletion::DoCodeCompleteIncludes(), cbEditor::GotoMatchingBrace(), and cbEditor::OnEditorCharAdded().
GetCurLineRaw()
wxCharBuffer wxScintilla::GetCurLineRaw (int * linePos = NULL)
Retrieve the text of the line containing the caret.
Returns the index of the caret on the line.
GetCurrentLine()
int wxScintilla::GetCurrentLine ()
Manually declared methods.
Returns the line number of the line with the caret.
Referenced by cbEditor::AddBreakpoint(), ConfirmReplaceDlg::CalcPosition(), DisassemblyDlg::CenterCurrentLine(), CodeCompletion::DoAutocomplete(), CodeCompletion::DoCodeCompleteIncludes(), CodeRefactoring::DoFindReferences(), MainFrame::DoUpdateStatusBar(), CodeCompletion::EditorEventHook(), cbEditor::FoldBlockFromLine(), CodeCompletion::GetAutocompList(), CodeCompletion::GotoFunctionPrevNext(), cbEditor::GotoMatchingBrace(), cbEditor::GotoNextChanged(), cbEditor::GotoPreviousChanged(), cbEditor::HasBreakpoint(), cbStyledTextCtrl::HighlightRightBrace(), cbEditor::LineHasMarker(), cbEditor::MarkerNext(), cbEditor::MarkerPrevious(), cbEditor::MarkerToggle(), DisassemblyDlg::OnAdjustLine(), CCManager::OnAutocompleteSelect(), CodeCompletion::OnGotoDeclaration(), DebuggerMenuHandler::OnRunToCursor(), DebuggerMenuHandler::OnSetNextStatement(), CodeCompletion::ParseFunctionsAndFillToolbar(), MacrosManager::RecalcVars(), cbEditor::RemoveBreakpoint(), cbEditor::ToggleBreakpoint(), cbEditor::ToggleFoldBlockFromLine(), and cbEditor::UnfoldBlockFromLine().
GetCurrentPos()
int wxScintilla::GetCurrentPos () const
Returns the position of the caret.
Referenced by NativeParser::AI(), cbStyledTextCtrl::AllowTabSmartJump(), ConfirmReplaceDlg::CalcPosition(), FindReplace::CalculateFindReplaceStartEnd(), EditorBase::DisplayContextMenu(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoAutocomplete(), cbStyledTextCtrl::DoBraceCompletion(), CodeCompletion::DoClassMethodDeclImpl(), CodeCompletion::DoCodeComplete(), cbStyledTextCtrl::DoSelectionBraceCompletion(), CCManager::DoUpdateCallTip(), MainFrame::DoUpdateStatusBar(), CodeCompletionHelper::EditorHasNameUnderCursor(), cbStyledTextCtrl::EnableTabSmartJump(), NativeParser::FindCurrentFunctionStart(), FindReplace::FindSelectedText(), NativeParser::GetCallTips(), cbDebuggerPlugin::GetEditorWordAtCaret(), cbSmartIndentPlugin::GetFirstBraceInLine(), cbSmartIndentPlugin::GetLastNonCommentWord(), cbSmartIndentPlugin::GetLastNonWhitespaceChars(), cbEditor::GetLineIndentInSpaces(), cbEditorInternalData::GetLineIndentString(), cbSmartIndentPlugin::GetNextNonWhitespaceCharOfLine(), cbSmartIndentPlugin::GetNextNonWhitespaceCharOnLine(), GetSelectedText(), CodeRefactoring::GetSymbolUnderCursor(), cbEditorInternalData::GetUrl(), cbEditor::GotoMatchingBrace(), cbEditor::GotoNextChanged(), cbEditor::GotoPreviousChanged(), cbEditor::GotoTokenPosition(), cbEditor::HighlightBraces(), cbStyledTextCtrl::HighlightRightBrace(), InsertNewLine(), CCManager::OnCompleteCode(), MainFrame::OnEditLinePaste(), cbEditor::OnEditorCharAdded(), CCManager::OnEditorHook(), MainFrame::OnEditStreamCommentSelected(), CodeCompletion::OnGotoDeclaration(), cbStyledTextCtrl::OnKeyDown(), cbStyledTextCtrl::OnKeyUp(), CCManager::OnMenuSelect(), cbStyledTextCtrl::OnMouseMiddleDown(), CCManager::OnShowCallTip(), CCManager::OnTimer(), CodeRefactoring::Parse(), NativeParser::ParseFunctionArguments(), NativeParser::ParseLocalBlock(), NativeParser::ParseUsingNamespace(), MacrosManager::RecalcVars(), cbEditor::Reload(), cbEditor::Save(), FindReplace::ShowFindDialog(), and cbEditor::UpdateProjectFile().
GetDirectFunction()
void* wxScintilla::GetDirectFunction () const
Retrieve a pointer to a function that processes messages for this Scintilla.
GetDirectPointer()
void* wxScintilla::GetDirectPointer () const
Retrieve a pointer value to use as the first argument when calling the function returned by GetDirectFunction.
GetDocPointer()
void* wxScintilla::GetDocPointer ()
Retrieve a pointer to the document object.
Referenced by cbEditor::Split().
GetEdgeColour()
wxColour wxScintilla::GetEdgeColour () const
Retrieve the colour used in edge indication.
GetEdgeColumn()
int wxScintilla::GetEdgeColumn () const
Retrieve the column number which text should be kept within.
GetEdgeMode()
int wxScintilla::GetEdgeMode () const
Retrieve the edge highlight mode.
Referenced by cbEditor::Print().
GetEditableWindow()
virtual wxWindow* wxScintilla::GetEditableWindow () inline protected virtual
Definition at line 5351 of file wxscintilla.h.
GetEndAtLastLine()
bool wxScintilla::GetEndAtLastLine () const
Retrieve whether the maximum scroll position has the last line at the bottom of the view.
GetEndStyled()
int wxScintilla::GetEndStyled () const
Retrieve the position of the last correctly styled character.
GetEOLMode()
int wxScintilla::GetEOLMode () const
Retrieve the current end of line mode - one of wxSCI_EOL_CRLF, wxSCI_EOL_CR, or wxSCI_EOL_LF.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), MainFrame::DoUpdateStatusBar(), cbEditorInternalData::EnsureConsistentLineEnds(), cbEditorInternalData::EnsureFinalLineEnd(), FindReplace::Find(), InsertNewLine(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditEOLMode(), MainFrame::OnEditMenuUpdateUI(), cbEditor::OnEditorCharAdded(), FindReplace::Replace(), and FindReplace::ReplaceInFiles().
GetExtraAscent()
int wxScintilla::GetExtraAscent () const
Get extra ascent for each line.
GetExtraDescent()
int wxScintilla::GetExtraDescent () const
Get extra descent for each line.
GetFirstVisibleLine()
int wxScintilla::GetFirstVisibleLine () const
Retrieve the display line at the top of the display.
Referenced by CCManagerHelper::IsPosVisible(), cbStyledTextCtrl::MakeNearbyLinesVisible(), DisassemblyDlg::OnAdjustLine(), DisassemblyDlg::SetActiveAddress(), and cbEditor::UpdateProjectFile().
GetFoldExpanded()
bool wxScintilla::GetFoldExpanded (int line) const
Is a header line expanded?
Referenced by cbEditor::DoFoldAll(), cbEditor::DoFoldBlockFromLine(), and cbEditor::OnEditorModified().
GetFoldLevel()
int wxScintilla::GetFoldLevel (int line) const
Retrieve the fold level of a line.
Referenced by cbEditor::DoFoldAll(), cbEditor::DoFoldBlockFromLine(), cbEditor::FixFoldState(), and cbEditor::SaveFoldState().
GetFoldParent()
int wxScintilla::GetFoldParent (int line) const
Find the parent line of a child line.
Referenced by cbEditor::DoFoldBlockFromLine(), and cbEditor::FixFoldState().
GetFontQuality()
int wxScintilla::GetFontQuality () const
Retrieve the quality level for text.
GetGapPosition()
int wxScintilla::GetGapPosition () const
Return a position which, to avoid performance costs, should not be within the range of a call to GetRangePointer.
GetHighlightGuide()
int wxScintilla::GetHighlightGuide () const
Get the highlighted indentation guide column.
GetHotspotActiveBackground()
wxColour wxScintilla::GetHotspotActiveBackground () const
Get the back colour for active hotspots.
GetHotspotActiveForeground()
wxColour wxScintilla::GetHotspotActiveForeground () const
Get the fore colour for active hotspots.
GetHotspotActiveUnderline()
bool wxScintilla::GetHotspotActiveUnderline () const
Get whether underlining for active hotspots.
GetHotspotSingleLine()
bool wxScintilla::GetHotspotSingleLine () const
Get the HotspotSingleLine property.
GetIdentifier()
int wxScintilla::GetIdentifier () const
Get the identifier.
GetIdleStyling()
int wxScintilla::GetIdleStyling () const
Retrieve the limits to idle styling.
GetIMEInteraction()
int wxScintilla::GetIMEInteraction () const
Is the IME displayed in a window or inline?
GetIndent()
int wxScintilla::GetIndent () const
Retrieve indentation size.
GetIndentationGuides()
int wxScintilla::GetIndentationGuides () const
Are the indentation guides visible?
GetIndicatorCurrent()
int wxScintilla::GetIndicatorCurrent () const
Get the current indicator.
GetIndicatorValue()
int wxScintilla::GetIndicatorValue () const
Get the current indicator value.
GetInsertionPoint()
virtual long wxScintilla::GetInsertionPoint () const inline virtual
Definition at line 5286 of file wxscintilla.h.
GetLastChild()
int wxScintilla::GetLastChild (int line, int level) const
Find the last child line of a header line.
Referenced by cbEditor::DoFoldAll(), and cbEditor::OnEditorModified().
GetLastKeydownProcessed()
bool wxScintilla::GetLastKeydownProcessed () inline
Can be used to prevent the EVT_CHAR handler from adding the char.
Definition at line 5164 of file wxscintilla.h.
GetLastPosition()
virtual long wxScintilla::GetLastPosition () const inline virtual
Definition at line 5287 of file wxscintilla.h.
GetLayoutCache()
int wxScintilla::GetLayoutCache () const
Retrieve the degree of caching of layout information.
GetLength()
int wxScintilla::GetLength () const
Returns the number of bytes in the document.
Referenced by NativeParser::AI(), FindReplace::CalculateFindReplaceStartEnd(), cbEditor::CanSelectAll(), cbEditorPrintout::cbEditorPrintout(), cbStyledTextCtrl::DoBraceCompletion(), CodeCompletion::EditorEventHook(), FindReplace::Find(), CodeRefactoring::Find(), NativeParser::FindCurrentFunctionStart(), CodeCompletionHelper::GetNextNonWhitespaceChar(), cbStyledTextCtrl::HighlightRightBrace(), CCManager::OnEditorTooltip(), MainFrame::OnEditSelectAll(), MainFrame::OnEditStreamCommentSelected(), CodeCompletion::OnRealtimeParsingTimer(), MainFrame::OnSearchGotoLine(), NativeParser::ParseFunctionArguments(), NativeParser::ParseLocalBlock(), NativeParser::ParseUsingNamespace(), and FindReplace::Replace().
GetLexer()
int wxScintilla::GetLexer () const
Retrieve the lexing language of the document.
Referenced by CodeCompletion::DoCodeCompletePreprocessor(), cbEditorInternalData::GetUrl(), cbStyledTextCtrl::IsCharacter(), cbStyledTextCtrl::IsComment(), cbStyledTextCtrl::IsPreprocessor(), cbStyledTextCtrl::IsString(), OverrideUseTabsPerLanguage(), cbEditorInternalData::StripTrailingSpaces(), and CodeCompletion::UpdateEditorSyntax().
GetLexerLanguage()
wxString wxScintilla::GetLexerLanguage () const
Retrieve the lexing language of the document.
GetLibraryVersionInfo()
static wxVersionInfo wxScintilla::GetLibraryVersionInfo () static
Referenced by dlgAbout::dlgAbout().
GetLine()
wxString wxScintilla::GetLine (int line) const
Retrieve the contents of a line.
Referenced by CodeCompletion::DoAutocomplete(), CodeCompletionHelper::EditorHasNameUnderCursor(), CodeRefactoring::Find(), FindReplace::FindInFiles(), cbEditor::GetLineIndentInSpaces(), cbEditorInternalData::GetLineIndentString(), cbEditor::GotoMatchingBrace(), cbEditor::OnEditorCharAdded(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), DebuggerMenuHandler::OnRunToCursor(), and DisassemblyDlg::SetActiveAddress().
GetLineCount()
int wxScintilla::GetLineCount () const
Returns the number of lines in the document. There is always at least one.
Referenced by cbEditorInternalData::DetectIndentStyle(), cbEditor::DoFoldAll(), cbEditorInternalData::EnsureFinalLineEnd(), cbEditor::FixFoldState(), cbEditorInternalData::GetUrl(), cbEditor::GotoMatchingBrace(), cbEditor::GotoNextChanged(), cbEditor::GotoPreviousChanged(), cbEditor::GotoTokenPosition(), cbEditor::MarkerPrevious(), MainFrame::OnEditLineMove(), cbEditor::SaveFoldState(), DisassemblyDlg::SetActiveAddress(), cbEditorInternalData::SetLineNumberColWidth(), and cbEditorInternalData::StripTrailingSpaces().
GetLineEndPosition()
int wxScintilla::GetLineEndPosition (int line) const
Get the position after the last visible characters on a line.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoAutocomplete(), CCManager::DoShowTips(), CCManagerHelper::FindColumn(), cbEditorInternalData::GetUrl(), cbStyledTextCtrl::HighlightRightBrace(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditLineMove(), MainFrame::OnEditStreamCommentSelected(), NativeParser::ParseLocalBlock(), and cbEditorInternalData::StripTrailingSpaces().
GetLineEndTypesActive()
int wxScintilla::GetLineEndTypesActive () const
Get the line end types currently recognised. May be a subset of the allowed types due to lexer limitation.
GetLineEndTypesAllowed()
int wxScintilla::GetLineEndTypesAllowed () const
Get the line end types currently allowed.
GetLineEndTypesSupported()
int wxScintilla::GetLineEndTypesSupported () const
Bit set of LineEndType enumertion for which line ends beyond the standard LF, CR, and CRLF are supported by the lexer.
GetLineIndentation()
int wxScintilla::GetLineIndentation (int line) const
Retrieve the number of columns that a line is indented.
GetLineIndentPosition()
int wxScintilla::GetLineIndentPosition (int line) const
Retrieve the position before the first non indentation character on a line.
Referenced by CodeCompletion::GetAutocompList(), and cbStyledTextCtrl::HighlightRightBrace().
GetLineRaw()
wxCharBuffer wxScintilla::GetLineRaw (int line)
Retrieve the contents of a line.
GetLineSelEndPosition()
int wxScintilla::GetLineSelEndPosition (int line)
Retrieve the position of the end of the selection at the given line (wxSCI_INVALID_POSITION if no selection on this line).
GetLineSelStartPosition()
int wxScintilla::GetLineSelStartPosition (int line)
Retrieve the position of the start of the selection at the given line (wxSCI_INVALID_POSITION if no selection on this line).
GetLineState()
int wxScintilla::GetLineState (int line) const
Retrieve the extra styling information for a line.
GetLineVisible()
bool wxScintilla::GetLineVisible (int line) const
Is a line visible?
Referenced by cbEditor::FixFoldState(), and DisassemblyDlg::SetActiveAddress().
GetMainSelection()
int wxScintilla::GetMainSelection () const
Which selection is the main selection.
Referenced by MainFrame::OnEditSelectAll().
GetMarginBackground()
wxColour wxScintilla::GetMarginBackground (int margin) const
Retrieve the background colour of a margin.
GetMarginCount()
int wxScintilla::GetMarginCount () const
How many margins are there?.
GetMarginCursor()
int wxScintilla::GetMarginCursor (int margin) const
Retrieve the cursor shown in a margin.
GetMarginLeft()
int wxScintilla::GetMarginLeft () const
Returns the size in pixels of the left margin.
GetMarginMask()
int wxScintilla::GetMarginMask (int margin) const
Retrieve the marker mask of a margin.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
GetMarginOptions()
int wxScintilla::GetMarginOptions () const
Get the margin options.
GetMarginRight()
int wxScintilla::GetMarginRight () const
Returns the size in pixels of the right margin.
GetMarginSensitive()
bool wxScintilla::GetMarginSensitive (int margin) const
Retrieve the mouse click sensitivity of a margin.
GetMarginType()
int wxScintilla::GetMarginType (int margin) const
Retrieve the type of a margin.
Referenced by cbEditor::Print().
GetMarginWidth()
int wxScintilla::GetMarginWidth (int margin) const
Retrieve the width of a margin in pixels.
Referenced by CCManager::DoShowTips(), cbEditor::OnBeforeBuildContextMenu(), cbEditor::Print(), and cbEditor::Split().
GetMarkerSymbolDefined()
int wxScintilla::GetMarkerSymbolDefined (int markerNumber)
Which symbol was defined for markerNumber with MarkerDefine.
GetMaxLineState()
int wxScintilla::GetMaxLineState () const
Retrieve the last line number that has line state.
GetModEventMask()
int wxScintilla::GetModEventMask () const
Get which document modification events are sent to the container.
GetModify()
bool wxScintilla::GetModify () const
Is the document different from when it was last saved?
Referenced by NativeParser::FindCurrentFunctionStart(), cbEditor::GetModified(), and cbEditor::OnEditorChange().
GetMouseDownCaptures()
bool wxScintilla::GetMouseDownCaptures () const
Get whether mouse gets captured.
GetMouseDwellTime()
int wxScintilla::GetMouseDwellTime () const
Retrieve the time the mouse must sit still to generate a mouse dwell event.
GetMouseSelectionRectangularSwitch()
bool wxScintilla::GetMouseSelectionRectangularSwitch () const
Whether switching to rectangular mode while selecting with the mouse is allowed.
GetMouseWheelCaptures()
bool wxScintilla::GetMouseWheelCaptures () const
Get whether mouse wheel can be active outside the window.
GetMultiPaste()
int wxScintilla::GetMultiPaste () const
Retrieve the effect of pasting when there are multiple selections.
GetMultipleSelection()
bool wxScintilla::GetMultipleSelection () const
Whether multiple selections can be made.
GetNextTabStop()
int wxScintilla::GetNextTabStop (int line, int x)
Find the next explicit tab stop position on a line after a position.
GetOvertype()
bool wxScintilla::GetOvertype () const
Returns true if overtype mode is active otherwise false is returned.
Referenced by MainFrame::DoUpdateStatusBar().
GetPasteConvertEndings()
bool wxScintilla::GetPasteConvertEndings () const
Get convert-on-paste setting.
GetPhasesDraw()
int wxScintilla::GetPhasesDraw () const
How many phases is drawing done in?
GetPositionCacheSize()
int wxScintilla::GetPositionCacheSize () const
How many entries are allocated to the position cache?
GetPrimaryStyleFromStyle()
int wxScintilla::GetPrimaryStyleFromStyle (int style) const
For a secondary style, return the primary style, else return the argument.
GetPrintColourMode()
int wxScintilla::GetPrintColourMode () const
Returns the print colour mode.
GetPrintMagnification()
int wxScintilla::GetPrintMagnification () const
Returns the print magnification.
GetPrintWrapMode()
int wxScintilla::GetPrintWrapMode () const
Is printing line wrapped?
GetProperty()
wxString wxScintilla::GetProperty (const wxString & key)
Retrieve a "property" value previously set with SetProperty.
GetPropertyExpanded()
wxString wxScintilla::GetPropertyExpanded (const wxString & key)
Retrieve a "property" value previously set with SetProperty, with "$()" variable replacement on returned buffer.
GetPropertyInt()
int wxScintilla::GetPropertyInt (const wxString & key, int defaultValue = 0) const
Retrieve a "property" value previously set with SetProperty, interpreted as an int AFTER any "$()" variable replacement.
GetPunctuationChars()
wxString wxScintilla::GetPunctuationChars () const
Get the set of characters making up punctuation characters.
GetRangePointer()
const char* wxScintilla::GetRangePointer (int position, int rangeLength) const
Return a read-only pointer to a range of characters in the document.
May move the gap so that the range is contiguous, but will only move up to rangeLength bytes.
GetReadOnly()
bool wxScintilla::GetReadOnly () const
In read-only mode?
Referenced by cbEditor::AddToContextMenu(), EditorManager::CheckForExternallyModifiedFiles(), cbEditor::CreateContextSubMenu(), MainFrame::DoUpdateStatusBar(), cbEditor::IsReadOnly(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and cbEditor::SetModified().
GetRectangularSelectionAnchor()
int wxScintilla::GetRectangularSelectionAnchor () const
Return the anchor position of the rectangular selection.
GetRectangularSelectionAnchorVirtualSpace()
int wxScintilla::GetRectangularSelectionAnchorVirtualSpace () const
Return the virtual space of the anchor of the rectangular selection.
GetRectangularSelectionCaret()
int wxScintilla::GetRectangularSelectionCaret () const
Return the caret position of the rectangular selection.
GetRectangularSelectionCaretVirtualSpace()
int wxScintilla::GetRectangularSelectionCaretVirtualSpace () const
Return the virtual space of the caret of the rectangular selection.
GetRectangularSelectionModifier()
int wxScintilla::GetRectangularSelectionModifier () const
Get the modifier key used for rectangular selection.
GetRepresentation()
wxString wxScintilla::GetRepresentation (const wxString & encodedCharacter) const
Set the way a character is drawn.
GetSCICursor()
int wxScintilla::GetSCICursor () const
Get cursor type.
GetSCIFocus()
bool wxScintilla::GetSCIFocus () const
Get internal focus flag.
GetScrollWidth()
int wxScintilla::GetScrollWidth () const
Retrieve the document width assumed for scrolling.
GetScrollWidthTracking()
bool wxScintilla::GetScrollWidthTracking () const
Retrieve whether the scroll width tracks wide lines.
GetSearchFlags()
int wxScintilla::GetSearchFlags () const
Get the search flags used by SearchInTarget.
GetSelAlpha()
int wxScintilla::GetSelAlpha () const
Get the alpha of the selection.
GetSelectedText()
wxString wxScintilla::GetSelectedText ()
Retrieve the selected text.
Referenced by cbEditorPrintout::cbEditorPrintout(), EditorBase::DisplayContextMenu(), FindReplace::FindNext(), FindReplace::FindSelectedText(), cbDebuggerPlugin::GetEditorWordAtCaret(), GetSelectedText(), cbEditorInternalData::GetUrl(), cbStyledTextCtrl::OnKeyDown(), cbStyledTextCtrl::OnMouseMiddleDown(), PrintDialog::PrintDialog(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and FindReplace::ShowFindDialog().
GetSelectedTextRaw()
wxCharBuffer wxScintilla::GetSelectedTextRaw ()
Retrieve the selected text.
GetSelection() [1/2]
virtual void wxScintilla::GetSelection (long * from, long * to) const inline virtual
Definition at line 5310 of file wxscintilla.h.
GetSelection() [2/2]
void wxScintilla::GetSelection (int * from, int * to) inline
kept for compatibility only
Definition at line 5319 of file wxscintilla.h.
GetSelectionEmpty()
bool wxScintilla::GetSelectionEmpty () const
Is every selected range empty?
Referenced by cbEditor::AddToContextMenu(), and cbEditor::CreateContextSubMenu().
GetSelectionEnd()
int wxScintilla::GetSelectionEnd () const
Returns the position at the end of the selection.
Referenced by FindReplace::CalculateFindReplaceStartEnd(), cbEditorPrintout::cbEditorPrintout(), cbDebuggerPlugin::GetEditorWordAtCaret(), cbEditor::HasSelection(), cbEditor::OnBeforeBuildContextMenu(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditLineMove(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), cbStyledTextCtrl::OnMouseMiddleDown(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and FindReplace::ShowFindDialog().
GetSelectionMode()
int wxScintilla::GetSelectionMode () const
Get the mode of the current selection.
GetSelectionNAnchor()
int wxScintilla::GetSelectionNAnchor (int selection) const
Return the anchor position of the nth selection.
Referenced by MainFrame::OnEditSelectAll(), and MainFrame::OnEditSelectNextSkip().
GetSelectionNAnchorVirtualSpace()
int wxScintilla::GetSelectionNAnchorVirtualSpace (int selection) const
Return the virtual space of the anchor of the nth selection.
GetSelectionNCaret()
int wxScintilla::GetSelectionNCaret (int selection) const
Return the caret position of the nth selection.
Referenced by MainFrame::OnEditSelectAll(), and MainFrame::OnEditSelectNextSkip().
GetSelectionNCaretVirtualSpace()
int wxScintilla::GetSelectionNCaretVirtualSpace (int selection) const
Return the virtual space of the caret of the nth selection.
GetSelectionNEnd()
int wxScintilla::GetSelectionNEnd (int selection) const
Returns the position at the end of the selection.
GetSelectionNStart()
int wxScintilla::GetSelectionNStart (int selection) const
Returns the position at the start of the selection.
GetSelections()
int wxScintilla::GetSelections () const
How many selections are there?
Referenced by cbStyledTextCtrl::DoSelectionBraceCompletion(), MainFrame::OnEditLineMove(), MainFrame::OnEditSelectAll(), and MainFrame::OnEditSelectNextSkip().
GetSelectionStart()
int wxScintilla::GetSelectionStart () const
Returns the position at the start of the selection.
Referenced by FindReplace::CalculateFindReplaceStartEnd(), cbEditorPrintout::cbEditorPrintout(), FindReplace::FindInFiles(), cbDebuggerPlugin::GetEditorWordAtCaret(), cbEditor::HasSelection(), cbEditor::OnBeforeBuildContextMenu(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditLineMove(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), cbStyledTextCtrl::OnMouseMiddleDown(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and FindReplace::ShowFindDialog().
GetSelEOLFilled()
bool wxScintilla::GetSelEOLFilled () const
Is the selection end of line filled?
GetStatus()
int wxScintilla::GetStatus () const
Get error status.
GetStyleAt()
int wxScintilla::GetStyleAt (int pos) const
Returns the style byte at the position.
Referenced by cbStyledTextCtrl::AllowTabSmartJump(), CodeCompletion::DoAutocomplete(), cbStyledTextCtrl::DoBraceCompletion(), cbStyledTextCtrl::EmulateDwellStart(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), cbSmartIndentPlugin::GetFirstBraceInLine(), cbSmartIndentPlugin::GetLastNonCommentWord(), CodeCompletionHelper::GetLastNonWhitespaceChar(), cbSmartIndentPlugin::GetLastNonWhitespaceChars(), CodeCompletionHelper::GetNextNonWhitespaceChar(), CodeRefactoring::GetSymbolUnderCursor(), CodeCompletion::GetTokenAt(), cbEditorInternalData::GetUrl(), cbStyledTextCtrl::HighlightRightBrace(), cbEditor::OnEditorDwellStart(), CCManager::OnMenuSelect(), CCManager::OnShowCallTip(), NativeParser::ParseLocalBlock(), and CodeRefactoring::VerifyResult().
GetStyledText()
wxMemoryBuffer wxScintilla::GetStyledText (int startPos, int endPos)
Retrieve a buffer of cells.
GetStyleFromSubStyle()
int wxScintilla::GetStyleFromSubStyle (int subStyle) const
For a sub style, return the base style, else return the argument.
GetSubStyleBases()
wxString wxScintilla::GetSubStyleBases () const
Get the set of base styles that can be extended with sub styles.
GetSubStylesLength()
int wxScintilla::GetSubStylesLength (int styleBase) const
The number of sub styles associated with a base style.
GetSubStylesStart()
int wxScintilla::GetSubStylesStart (int styleBase) const
The starting style number for the sub styles associated with a base style.
GetTabDrawMode()
int wxScintilla::GetTabDrawMode () const
Retrieve the current tab draw mode.
Returns one of wxSCI_TD_* constants.
GetTabIndents()
bool wxScintilla::GetTabIndents () const
Does a tab pressed when caret is within indentation indent?
GetTabWidth()
int wxScintilla::GetTabWidth () const
Retrieve the visible size of a tab.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), cbSmartIndentPlugin::GetFirstBraceInLine(), cbEditor::GetLineIndentInSpaces(), and cbSmartIndentPlugin::Indent().
GetTag()
wxString wxScintilla::GetTag (int tagNumber) const
Retrieve the value of a tag from a regular expression search.
GetTargetEnd()
int wxScintilla::GetTargetEnd () const
Get the position that ends the target.
GetTargetStart()
int wxScintilla::GetTargetStart () const
Get the position that starts the target.
GetTargetText()
wxString wxScintilla::GetTargetText () const
Retrieve the text in the target.
GetTargetTextRaw()
wxCharBuffer wxScintilla::GetTargetTextRaw ()
Retrieve the target text.
GetTechnology()
int wxScintilla::GetTechnology () const
Get the tech.
GetText()
wxString wxScintilla::GetText () const
Retrieve all the text in the document.
Referenced by CrashHandlerSaveEditorFiles(), FindReplace::FindInFiles(), FileManager::Load(), CodeCompletion::OnGotoFunction(), DisassemblyDlg::OnSave(), CodeCompletion::ParseFunctionsAndFillToolbar(), cbEditor::Save(), cbEditor::SaveFoldState(), CodeRefactoring::SearchInFiles(), and CodeRefactoring::VerifyResult().
GetTextLength()
int wxScintilla::GetTextLength () const
Retrieve the number of characters in the document.
GetTextRange()
wxString wxScintilla::GetTextRange (int startPos, int endPos)
Retrieve a range of text.
Referenced by NativeParser::AI(), EditorBase::DisplayContextMenu(), CodeCompletion::DoCodeCompletePreprocessor(), CCManager::DoUpdateCallTip(), CodeCompletionHelper::EditorHasNameUnderCursor(), FindReplace::Find(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), cbDebuggerPlugin::GetEditorWordAtCaret(), cbSmartIndentPlugin::GetLastNonCommentWord(), cbSmartIndentPlugin::GetLastNonWhitespaceChars(), GetSelectedText(), CodeRefactoring::GetSymbolUnderCursor(), cbEditorInternalData::GetUrl(), CCManager::OnCompleteCode(), MainFrame::OnEditLineMove(), CCManager::OnEditorTooltip(), MainFrame::OnEditSelectNext(), MainFrame::OnEditSelectNextSkip(), MainFrame::OnEditStreamCommentSelected(), CodeCompletion::OnGotoDeclaration(), CCManager::OnShowCallTip(), NativeParser::ParseLocalBlock(), NativeParser::ParseUsingNamespace(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and FindReplace::ShowFindDialog().
GetTextRangeRaw()
wxCharBuffer wxScintilla::GetTextRangeRaw (int startPos, int endPos)
Retrieve a range of text.
GetTextRaw()
wxCharBuffer wxScintilla::GetTextRaw ()
Retrieve all the text in the document.
GetTwoPhaseDraw()
bool wxScintilla::GetTwoPhaseDraw () const
Is drawing done in two phases with backgrounds drawn before foregrounds?
GetUndoCollection()
bool wxScintilla::GetUndoCollection () const
Is undo history being collected?
GetUseAntiAliasing()
bool wxScintilla::GetUseAntiAliasing ()
Returns the current UseAntiAliasing setting.
GetUseHorizontalScrollBar()
bool wxScintilla::GetUseHorizontalScrollBar () const
Is the horizontal scroll bar visible?
GetUseTabs()
bool wxScintilla::GetUseTabs () const
Retrieve whether tabs will be used in indentation.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), cbSmartIndentPlugin::GetFirstBraceInLine(), and cbSmartIndentPlugin::Indent().
GetUseVerticalScrollBar()
bool wxScintilla::GetUseVerticalScrollBar () const
Is the vertical scroll bar visible?
GetValue()
wxString wxScintilla::GetValue () const inline protected
Definition at line 5346 of file wxscintilla.h.
GetViewEOL()
bool wxScintilla::GetViewEOL () const
Are the end of line characters visible?
GetViewWhiteSpace()
int wxScintilla::GetViewWhiteSpace () const
Are white space characters currently visible? Returns one of wxSCI_WS_* constants.
GetVirtualSpaceOptions()
int wxScintilla::GetVirtualSpaceOptions () const
Return options for virtual space behaviour.
GetWhitespaceChars()
wxString wxScintilla::GetWhitespaceChars () const
Get the set of characters making up whitespace for when moving or selecting by word.
GetWhitespaceSize()
int wxScintilla::GetWhitespaceSize () const
Get the size of the dots used to mark space characters.
GetWordChars()
wxString wxScintilla::GetWordChars () const
Get the set of characters making up words for when moving or selecting by word.
GetWrapIndentMode()
int wxScintilla::GetWrapIndentMode () const
Retrieve how wrapped sublines are placed. Default is wxSCI_WRAPINDENT_FIXED.
GetWrapMode()
int wxScintilla::GetWrapMode () const
Retrieve whether text is word wrapped.
GetWrapStartIndent()
int wxScintilla::GetWrapStartIndent () const
Retrive the start indent for wrapped lines.
GetWrapVisualFlags()
int wxScintilla::GetWrapVisualFlags () const
Retrive the display mode of visual flags for wrapped lines.
GetWrapVisualFlagsLocation()
int wxScintilla::GetWrapVisualFlagsLocation () const
Retrive the location of visual flags for wrapped lines.
GetXOffset()
int wxScintilla::GetXOffset () const
Get the xOffset (ie, horizontal scroll position).
GetZoom()
int wxScintilla::GetZoom () const
Retrieve the zoom level.
Referenced by cbEditor::OnZoom(), cbEditorInternalData::SetFoldingColWidth(), cbEditor::SetZoom(), cbEditor::Split(), and cbEditor::UpdateProjectFile().
GotoLine()
void wxScintilla::GotoLine (int line)
Set caret to start of a line and ensure it is visible.
Referenced by FindReplace::Find(), cbEditor::GotoLine(), cbEditor::GotoNextChanged(), cbEditor::GotoPreviousChanged(), MainFrame::OnEditLinePaste(), and DisassemblyDlg::SetActiveAddress().
GotoPos()
void wxScintilla::GotoPos (int caret)
Set caret to a position and ensure it is visible.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), cbEditor::GotoMatchingBrace(), cbEditor::GotoTokenPosition(), cbEditor::OnBeforeBuildContextMenu(), MainFrame::OnEditLinePaste(), cbEditor::OnEditorCharAdded(), MainFrame::OnEditStreamCommentSelected(), cbStyledTextCtrl::OnKeyDown(), cbEditor::Reload(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), cbEditor::SetProjectFile(), and CodeRefactoring::VerifyResult().
HaveMouseCapture()
bool wxScintilla::HaveMouseCapture () const
Referenced by cbStyledTextCtrl::OnContextMenu().
HideLines()
void wxScintilla::HideLines (int lineStart, int lineEnd)
Make a range of lines invisible.
Referenced by cbEditor::DoFoldAll().
HideSelection()
void wxScintilla::HideSelection (bool hide)
Draw the selection in normal style or with selection highlighted.
Home()
void wxScintilla::Home ()
Move caret to first position on line.
HomeDisplay()
void wxScintilla::HomeDisplay ()
Move caret to first position on display line.
Referenced by InsertNewLine().
HomeDisplayExtend()
void wxScintilla::HomeDisplayExtend ()
Move caret to first position on display line extending selection to new caret position.
HomeExtend()
void wxScintilla::HomeExtend ()
Move caret to first position on line extending selection to new caret position.
HomeRectExtend()
void wxScintilla::HomeRectExtend ()
Move caret to first position on line, extending rectangular selection to new caret position.
HomeWrap()
void wxScintilla::HomeWrap ()
Like Home but when word-wrap is enabled goes first to start of display line HomeDisplay, then to start of document line Home.
HomeWrapExtend()
void wxScintilla::HomeWrapExtend ()
Like HomeExtend but when word-wrap is enabled extends first to start of display line HomeDisplayExtend, then to start of document line HomeExtend.
IndicatorAllOnFor()
int wxScintilla::IndicatorAllOnFor (int pos)
Are any indicators present at pos?
IndicatorClearRange()
void wxScintilla::IndicatorClearRange (int start, int lengthClear)
Turn a indicator off over a range.
Referenced by cbStyledTextCtrl::HighlightRightBrace(), and MainFrame::OnEditSelectAll().
IndicatorEnd()
int wxScintilla::IndicatorEnd (int indicator, int pos)
Where does a particular indicator end?
IndicatorFillRange()
void wxScintilla::IndicatorFillRange (int start, int lengthFill)
Turn a indicator on over a range.
Referenced by cbStyledTextCtrl::HighlightRightBrace(), and MainFrame::OnEditSelectNextSkip().
IndicatorGetAlpha()
int wxScintilla::IndicatorGetAlpha (int indicator) const
Get the alpha fill colour of the given indicator.
IndicatorGetFlags()
int wxScintilla::IndicatorGetFlags (int indicator) const
Retrieve the attributes of an indicator.
IndicatorGetForeground()
wxColour wxScintilla::IndicatorGetForeground (int indicator) const
Retrieve the foreground colour of an indicator.
Referenced by cbEditor::Split().
IndicatorGetHoverForeground()
wxColour wxScintilla::IndicatorGetHoverForeground (int indicator) const
Retrieve the foreground hover colour of an indicator.
IndicatorGetHoverStyle()
int wxScintilla::IndicatorGetHoverStyle (int indicator) const
Retrieve the hover style of an indicator.
IndicatorGetOutlineAlpha()
int wxScintilla::IndicatorGetOutlineAlpha (int indicator) const
Get the alpha outline colour of the given indicator.
IndicatorGetStyle()
int wxScintilla::IndicatorGetStyle (int indicator) const
Retrieve the style of an indicator.
Referenced by cbEditor::Split().
IndicatorGetUnder()
bool wxScintilla::IndicatorGetUnder (int indicator) const
Retrieve whether indicator drawn under or over text.
Referenced by cbEditor::Split().
IndicatorSetAlpha()
void wxScintilla::IndicatorSetAlpha (int indicator, int alpha)
Set the alpha fill colour of the given indicator.
IndicatorSetFlags()
void wxScintilla::IndicatorSetFlags (int indicator, int flags)
Set the attributes of an indicator.
IndicatorSetForeground()
void wxScintilla::IndicatorSetForeground (int indicator, const wxColour & fore)
Set the foreground colour of an indicator.
Referenced by cbStyledTextCtrl::HighlightRightBrace(), and cbEditor::Split().
IndicatorSetHoverForeground()
void wxScintilla::IndicatorSetHoverForeground (int indicator, const wxColour & fore)
Set the foreground hover colour of an indicator.
IndicatorSetHoverStyle()
void wxScintilla::IndicatorSetHoverStyle (int indicator, int indicatorStyle)
Set a hover indicator to plain, squiggle or TT.
IndicatorSetOutlineAlpha()
void wxScintilla::IndicatorSetOutlineAlpha (int indicator, int alpha)
Set the alpha outline colour of the given indicator.
IndicatorSetStyle()
void wxScintilla::IndicatorSetStyle (int indicator, int indicatorStyle)
Set an indicator to plain, squiggle or TT.
Referenced by cbStyledTextCtrl::HighlightRightBrace(), and cbEditor::Split().
IndicatorSetUnder()
void wxScintilla::IndicatorSetUnder (int indicator, bool under)
Set an indicator to draw under text or over(default).
Referenced by cbStyledTextCtrl::HighlightRightBrace(), and cbEditor::Split().
IndicatorStart()
int wxScintilla::IndicatorStart (int indicator, int pos)
Where does a particular indicator start?
IndicatorValueAt()
int wxScintilla::IndicatorValueAt (int indicator, int pos)
What value does a particular indicator have at a position?
InsertText()
void wxScintilla::InsertText (int pos, const wxString & text)
Insert string at a position.
Referenced by cbStyledTextCtrl::DoBraceCompletion(), cbStyledTextCtrl::DoSelectionBraceCompletion(), cbEditorInternalData::EnsureFinalLineEnd(), InsertNewLine(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditLineMove(), cbEditor::OnEditorCharAdded(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), cbStyledTextCtrl::OnMouseMiddleDown(), and cbEditor::Open().
InsertTextRaw()
void wxScintilla::InsertTextRaw (int pos, const char * text)
Insert string at a position.
IsEditable()
virtual bool wxScintilla::IsEditable () const inline virtual
Definition at line 5330 of file wxscintilla.h.
IsRangeWord()
bool wxScintilla::IsRangeWord (int start, int end)
Is the range start..end considered a word?
LineCopy()
void wxScintilla::LineCopy ()
Copy the line containing the caret.
Referenced by MainFrame::OnEditLineCopy().
LineCut()
void wxScintilla::LineCut ()
Cut the line containing the caret.
Referenced by MainFrame::OnEditLineCut().
LineDelete()
void wxScintilla::LineDelete ()
Delete the line containing the caret.
Referenced by MainFrame::OnEditLineDelete().
LineDown()
void wxScintilla::LineDown ()
Move caret down one line.
Referenced by InsertNewLine().
LineDownExtend()
void wxScintilla::LineDownExtend ()
Move caret down one line extending selection to new caret position.
LineDownRectExtend()
void wxScintilla::LineDownRectExtend ()
Move caret down one line, extending rectangular selection to new caret position.
LineDuplicate()
void wxScintilla::LineDuplicate ()
Duplicate the current line.
Referenced by MainFrame::OnEditLineDuplicate().
LineEnd()
void wxScintilla::LineEnd ()
Move caret to last position on line.
Referenced by MainFrame::OnEditGotoLineEnd().
LineEndDisplay()
void wxScintilla::LineEndDisplay ()
Move caret to last position on display line.
Referenced by InsertNewLine().
LineEndDisplayExtend()
void wxScintilla::LineEndDisplayExtend ()
Move caret to last position on display line extending selection to new caret position.
LineEndExtend()
void wxScintilla::LineEndExtend ()
Move caret to last position on line extending selection to new caret position.
LineEndRectExtend()
void wxScintilla::LineEndRectExtend ()
Move caret to last position on line, extending rectangular selection to new caret position.
LineEndWrap()
void wxScintilla::LineEndWrap ()
Like LineEnd but when word-wrap is enabled goes first to end of display line LineEndDisplay, then to start of document line LineEnd.
LineEndWrapExtend()
void wxScintilla::LineEndWrapExtend ()
Like LineEndExtend but when word-wrap is enabled extends first to end of display line LineEndDisplayExtend, then to start of document line LineEndExtend.
LineFromPosition()
int wxScintilla::LineFromPosition (int pos) const
Retrieve the line containing a position.
Referenced by NativeParser::AI(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CCManager::DoShowTips(), CCManager::DoUpdateCallTip(), CodeCompletionHelper::EditorHasNameUnderCursor(), FindReplace::Find(), CodeRefactoring::Find(), NativeParser::FindCurrentFunctionStart(), FindReplace::FindInFiles(), cbEditor::GetLineIndentInSpaces(), cbEditorInternalData::GetLineIndentString(), cbEditor::GotoNextChanged(), cbEditor::GotoPreviousChanged(), cbStyledTextCtrl::HighlightRightBrace(), CCManagerHelper::IsPosVisible(), cbEditor::OnBeforeBuildContextMenu(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditLineMove(), MainFrame::OnEditLinePaste(), cbEditor::OnEditorCharAdded(), cbEditor::OnEditorModified(), CCManager::OnEditorTooltip(), MainFrame::OnEditSelectAll(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), cbEditor::OnMarginClick(), MainFrame::OnSearchGotoLine(), CCManager::OnShowCallTip(), NativeParser::ParseFunctionArguments(), NativeParser::ParseLocalBlock(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and FindReplace::ShowFindDialog().
LineLength()
int wxScintilla::LineLength (int line) const
How many characters are on a line, including end of line characters?
Referenced by cbEditor::GotoTokenPosition(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditToggleCommentSelected(), and MainFrame::OnEditUncommentSelected().
LineScroll()
void wxScintilla::LineScroll (int columns, int lines)
Scroll horizontally and vertically.
Referenced by cbStyledTextCtrl::MakeNearbyLinesVisible().
LineScrollDown()
void wxScintilla::LineScrollDown ()
Scroll the document down, keeping the caret visible.
LineScrollUp()
void wxScintilla::LineScrollUp ()
Scroll the document up, keeping the caret visible.
LinesJoin()
void wxScintilla::LinesJoin ()
Join the lines in the target.
LinesOnScreen()
int wxScintilla::LinesOnScreen () const
Retrieves the number of lines completely visible.
Referenced by DisassemblyDlg::CenterLine(), CCManager::DoShowTips(), FindReplace::Find(), CCManagerHelper::IsPosVisible(), cbStyledTextCtrl::MakeNearbyLinesVisible(), DisassemblyDlg::OnAdjustLine(), and DisassemblyDlg::SetActiveAddress().
LinesSplit()
void wxScintilla::LinesSplit (int pixelWidth)
Split the lines in the target into lines that are less wide than pixelWidth where possible.
LineTranspose()
void wxScintilla::LineTranspose ()
Switch the current line with the previous.
Referenced by MainFrame::OnEditLineTranspose().
LineUp()
void wxScintilla::LineUp ()
Move caret up one line.
LineUpExtend()
void wxScintilla::LineUpExtend ()
Move caret up one line extending selection to new caret position.
LineUpRectExtend()
void wxScintilla::LineUpRectExtend ()
Move caret up one line, extending rectangular selection to new caret position.
LoadFile()
bool wxScintilla::LoadFile (const wxString & filename)
Load the contents of filename into the editor.
Referenced by EditorConfigurationDlg::CreateColoursSample().
LoadLexerLibrary()
void wxScintilla::LoadLexerLibrary (const wxString & path)
Load a lexer library (dll / so).
LowerCase()
void wxScintilla::LowerCase ()
Transform the selection to lower case.
Referenced by cbEditor::OnContextMenuEntry(), and MainFrame::OnEditLowerCase().
MarginGetStyle()
int wxScintilla::MarginGetStyle (int line) const
Get the style number for the text margin for a line.
MarginGetStyleOffset()
int wxScintilla::MarginGetStyleOffset () const
Get the start of the range of style numbers used for margin text.
MarginGetStyles()
wxString wxScintilla::MarginGetStyles (int line) const
Get the styles in the text margin for a line.
MarginGetText()
wxString wxScintilla::MarginGetText (int line) const
Get the text in the text margin for a line.
MarginSetStyle()
void wxScintilla::MarginSetStyle (int line, int style)
Set the style number for the text margin for a line.
MarginSetStyleOffset()
void wxScintilla::MarginSetStyleOffset (int style)
Get the start of the range of style numbers used for margin text.
MarginSetStyles()
void wxScintilla::MarginSetStyles (int line, const wxString & styles)
Set the style in the text margin for a line.
MarginSetText()
void wxScintilla::MarginSetText (int line, const wxString & text)
Set the text in the text margin for a line.
MarginTextClearAll()
void wxScintilla::MarginTextClearAll ()
Clear the margin text on all lines.
MarkerAdd()
int wxScintilla::MarkerAdd (int line, int markerNumber)
Add a marker to a line, returning an ID which can be used to find or delete the marker.
Referenced by cbEditor::BreakpointMarkerToggle(), EditorConfigurationDlg::CreateColoursSample(), cbEditor::MarkerToggle(), cbEditor::MarkLine(), cbEditor::OnContextMenuEntry(), and DisassemblyDlg::SetActiveAddress().
MarkerAddSet()
void wxScintilla::MarkerAddSet (int line, int markerSet)
Add a set of markers to a line.
MarkerDefine()
void wxScintilla::MarkerDefine (int markerNumber, int markerSymbol, const wxColour & foreground = wxNullColour, const wxColour & background = wxNullColour)
Set the symbol used for a particular marker number, and optionally the fore and background colours.
Referenced by cbEditor::CreateEditor(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::SetMarkerStyle().
MarkerDefineBitmap()
void wxScintilla::MarkerDefineBitmap (int markerNumber, const wxBitmap & bmp)
Define a marker from a bitmap.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
MarkerDefineRGBAImage()
void wxScintilla::MarkerDefineRGBAImage (int markerNumber, const unsigned char * pixels)
Define a marker from RGBA data.
It has the width and height from RGBAImageSetWidth/Height
MarkerDelete()
void wxScintilla::MarkerDelete (int line, int markerNumber)
Delete a marker from a line.
Referenced by cbEditor::BreakpointMarkerToggle(), cbEditor::MarkerToggle(), and cbEditor::OnContextMenuEntry().
MarkerDeleteAll()
void wxScintilla::MarkerDeleteAll (int markerNumber)
Delete all markers with a particular number from all lines.
Referenced by DisassemblyDlg::Clear(), cbEditor::ClearAllBookmarks(), EditorConfigurationDlg::CreateColoursSample(), cbEditor::MarkLine(), cbEditor::OnContextMenuEntry(), and DisassemblyDlg::SetActiveAddress().
MarkerDeleteHandle()
void wxScintilla::MarkerDeleteHandle (int markerHandle)
Delete a marker.
MarkerEnableHighlight()
void wxScintilla::MarkerEnableHighlight (bool enabled)
Enable/disable highlight for current folding bloc (smallest one that contains the caret)
MarkerGet()
int wxScintilla::MarkerGet (int line)
Get a bit mask of all the markers set on a line.
Referenced by cbEditor::BreakpointMarkerToggle(), and cbEditor::LineHasMarker().
MarkerLineFromHandle()
int wxScintilla::MarkerLineFromHandle (int markerHandle)
Retrieve the line number at which a particular marker is located.
MarkerNext()
int wxScintilla::MarkerNext (int lineStart, int markerMask)
Find the next line at or after lineStart that includes a marker in mask.
Return -1 when no more lines.
Referenced by cbEditor::MarkerNext(), and cbEditor::RefreshBreakpointMarkers().
MarkerPrevious()
int wxScintilla::MarkerPrevious (int lineStart, int markerMask)
Find the previous line before lineStart that includes a marker in mask.
Referenced by cbEditor::MarkerPrevious().
MarkerSetAlpha()
void wxScintilla::MarkerSetAlpha (int markerNumber, int alpha)
Set the alpha used for a marker that is drawn in the text area, not the margin.
MarkerSetBackground()
void wxScintilla::MarkerSetBackground (int markerNumber, const wxColour & back)
Set the background colour used for a particular marker number.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), cbEditor::SetLanguageDependentColours(), and cbEditor::SetMarkerStyle().
MarkerSetBackgroundSelected()
void wxScintilla::MarkerSetBackgroundSelected (int markerNumber, const wxColour & back)
Set the background colour used for a particular marker number when its folding block is selected.
MarkerSetForeground()
void wxScintilla::MarkerSetForeground (int markerNumber, const wxColour & fore)
Set the foreground colour used for a particular marker number.
Referenced by cbEditor::SetMarkerStyle().
MoveCaretInsideView()
void wxScintilla::MoveCaretInsideView ()
Move the caret inside current view if it's not there already.
MoveSelectedLinesDown()
void wxScintilla::MoveSelectedLinesDown ()
Move the selected lines down one line, shifting the line below before the selection.
MoveSelectedLinesUp()
void wxScintilla::MoveSelectedLinesUp ()
Move the selected lines up one line, shifting the line above after the selection.
MultiEdgeAddLine()
void wxScintilla::MultiEdgeAddLine (int column, const wxColour & edgeColour)
Add a new vertical edge to the view.
MultiEdgeClearAll()
void wxScintilla::MultiEdgeClearAll ()
Clear all vertical edges.
MultipleSelectAddEach()
void wxScintilla::MultipleSelectAddEach ()
Add each occurrence of the main selection in the target to the set of selections.
If the current selection is empty then select word around caret.
MultipleSelectAddNext()
void wxScintilla::MultipleSelectAddNext ()
Add the next occurrence of the main selection to the set of selections as main.
If the current selection is empty then select word around caret.
NewLine()
void wxScintilla::NewLine ()
Insert a new line, may use a CRLF, CR or LF depending on EOL mode.
Referenced by MainFrame::OnEditInsertNewLine().
NotifyChange()
void wxScintilla::NotifyChange () protected
Turn notifications from Scintilla into events.
NotifyParent()
void wxScintilla::NotifyParent (SCNotification * scn) protected
OnChar()
void wxScintilla::OnChar (wxKeyEvent & evt) protected
OnContextMenu()
void wxScintilla::OnContextMenu (wxContextMenuEvent & evt) protected
Referenced by cbStyledTextCtrl::GetLastSelectedText().
OnEraseBackground()
void wxScintilla::OnEraseBackground (wxEraseEvent & evt) protected
OnGainFocus()
void wxScintilla::OnGainFocus (wxFocusEvent & evt) protected
OnIdle()
void wxScintilla::OnIdle (wxIdleEvent & evt) protected
OnKeyDown()
void wxScintilla::OnKeyDown (wxKeyEvent & evt) protected
Referenced by cbStyledTextCtrl::GetLastSelectedText().
OnListBox()
void wxScintilla::OnListBox (wxCommandEvent & evt) protected
OnLoseFocus()
void wxScintilla::OnLoseFocus (wxFocusEvent & evt) protected
OnMenu()
void wxScintilla::OnMenu (wxCommandEvent & evt) protected
OnMouseCaptureLost()
void wxScintilla::OnMouseCaptureLost (wxMouseCaptureLostEvent & evt) protected
OnMouseLeftDown()
void wxScintilla::OnMouseLeftDown (wxMouseEvent & evt) protected
OnMouseLeftUp()
void wxScintilla::OnMouseLeftUp (wxMouseEvent & evt) protected
Referenced by cbStyledTextCtrl::GetLastSelectedText().
OnMouseMiddleUp()
void wxScintilla::OnMouseMiddleUp (wxMouseEvent & evt) protected
OnMouseMove()
void wxScintilla::OnMouseMove (wxMouseEvent & evt) protected
OnMouseRightDown()
void wxScintilla::OnMouseRightDown (wxMouseEvent & evt) protected
OnMouseRightUp()
void wxScintilla::OnMouseRightUp (wxMouseEvent & evt) protected
OnMouseWheel()
void wxScintilla::OnMouseWheel (wxMouseEvent & evt) protected
OnPaint()
void wxScintilla::OnPaint (wxPaintEvent & evt) protected
Event handlers.
OnScroll()
void wxScintilla::OnScroll (wxScrollEvent & evt) protected
OnScrollWin()
void wxScintilla::OnScrollWin (wxScrollWinEvent & evt) protected
OnSize()
void wxScintilla::OnSize (wxSizeEvent & evt) protected
OnSysColourChanged()
void wxScintilla::OnSysColourChanged (wxSysColourChangedEvent & evt) protected
PageDown()
void wxScintilla::PageDown ()
Move caret one page down.
PageDownExtend()
void wxScintilla::PageDownExtend ()
Move caret one page down extending selection to new caret position.
PageDownRectExtend()
void wxScintilla::PageDownRectExtend ()
Move caret one page down, extending rectangular selection to new caret position.
PageUp()
void wxScintilla::PageUp ()
Move caret one page up.
PageUpExtend()
void wxScintilla::PageUpExtend ()
Move caret one page up extending selection to new caret position.
PageUpRectExtend()
void wxScintilla::PageUpRectExtend ()
Move caret one page up, extending rectangular selection to new caret position.
ParaDown()
void wxScintilla::ParaDown ()
Move caret down one paragraph (delimited by empty lines).
Referenced by MainFrame::OnEditParaDown().
ParaDownExtend()
void wxScintilla::ParaDownExtend ()
Extend selection down one paragraph (delimited by empty lines).
Referenced by MainFrame::OnEditParaDownExtend().
ParaUp()
void wxScintilla::ParaUp ()
Move caret up one paragraph (delimited by empty lines).
Referenced by MainFrame::OnEditParaUp().
ParaUpExtend()
void wxScintilla::ParaUpExtend ()
Extend selection up one paragraph (delimited by empty lines).
Referenced by MainFrame::OnEditParaUpExtend().
Paste()
void wxScintilla::Paste ()
Paste the contents of the clipboard into the document replacing the selection.
Referenced by cbEditor::OnContextMenuEntry(), MainFrame::OnEditLinePaste(), and cbEditor::Paste().
PointFromPosition()
wxPoint wxScintilla::PointFromPosition (int pos)
Retrieve the point in the window where a position is displayed.
Referenced by ConfirmReplaceDlg::CalcPosition(), EditorBase::DisplayContextMenu(), CCManager::DoShowTips(), and CCManager::OnMenuSelect().
PositionAfter()
int wxScintilla::PositionAfter (int pos)
Given a valid document position, return the next position taking code page into account.
Maximum value returned is the last position in the document.
PositionBefore()
int wxScintilla::PositionBefore (int pos)
Given a valid document position, return the previous position taking code page into account.
Returns 0 if passed 0.
PositionFromLine()
int wxScintilla::PositionFromLine (int line) const
Retrieve the position at the start of a line.
Referenced by NativeParser::AI(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeCompletion::DoCodeCompleteIncludes(), CCManager::DoShowTips(), CCManager::DoUpdateCallTip(), cbEditorInternalData::EnsureFinalLineEnd(), CCManagerHelper::FindColumn(), NativeParser::FindCurrentFunctionStart(), cbEditor::GotoMatchingBrace(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditLineMove(), CCManager::OnEditorTooltip(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), CCManager::OnShowCallTip(), NativeParser::ParseFunctionArguments(), and cbEditorInternalData::StripTrailingSpaces().
PositionFromPoint()
int wxScintilla::PositionFromPoint (wxPoint pt) const
Find the position from a point within the window.
Referenced by CCManager::DoShowTips(), cbStyledTextCtrl::EmulateDwellStart(), cbDebuggerPlugin::GetEditorWordAtCaret(), cbEditor::OnBeforeBuildContextMenu(), cbEditor::OnEditorDwellStart(), and cbStyledTextCtrl::OnMouseMiddleDown().
PositionFromPointClose()
int wxScintilla::PositionFromPointClose (int x, int y)
Find the position from a point within the window but return wxSCI_INVALID_POSITION if not close to text.
Referenced by cbDebuggerPlugin::GetEditorWordAtCaret(), and CCManager::OnEditorTooltip().
PositionRelative()
int wxScintilla::PositionRelative (int pos, int relative)
Given a valid document position, return a position that differs in a number of characters.
Returned value is always between 0 and last position in document.
PrivateLexerCall()
void* wxScintilla::PrivateLexerCall (int operation, void * pointer)
For private communication between an application and a known lexer.
PropertyNames()
wxString wxScintilla::PropertyNames () const
Retrieve a '\n' separated list of properties understood by the current lexer.
PropertyType()
int wxScintilla::PropertyType (const wxString & name)
Retrieve the type of a property.
Redo()
void wxScintilla::Redo ()
Redoes the next action on the undo history.
Referenced by cbEditor::OnContextMenuEntry(), and cbEditor::Redo().
RegisterImage()
void wxScintilla::RegisterImage (int type, const wxBitmap & bmp)
Register an image for use in autocompletion lists.
Referenced by CodeCompletion::DoCodeComplete(), CodeCompletion::DoCodeCompleteIncludes(), and CodeCompletion::DoCodeCompletePreprocessor().
RegisterRGBAImage()
void wxScintilla::RegisterRGBAImage (int type, const unsigned char * pixels)
Register an RGBA image for use in autocompletion lists.
It has the width and height from RGBAImageSetWidth/Height
ReleaseAllExtendedStyles()
void wxScintilla::ReleaseAllExtendedStyles ()
Release all extended (>255) style numbers.
ReleaseDocument()
void wxScintilla::ReleaseDocument (void * docPointer)
Release a reference to the document, deleting document if it fades to black.
Remove()
virtual void wxScintilla::Remove (long from, long to) inline virtual
Definition at line 5256 of file wxscintilla.h.
References wxT.
Replace()
virtual void wxScintilla::Replace (long from, long to, const wxString & text) inline virtual
Definition at line 5260 of file wxscintilla.h.
ReplaceSelection()
void wxScintilla::ReplaceSelection (const wxString & text)
Replace the selected text with the argument text.
Referenced by cbEditor::OnContextMenuEntry(), FindReplace::Replace(), and FindReplace::ReplaceInFiles().
ReplaceTarget()
int wxScintilla::ReplaceTarget (const wxString & text)
Replace the target text with the argument text.
Text is counted so it can contain NULs. Returns the length of the replacement text.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeRefactoring::DoRenameSymbols(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), and cbEditorInternalData::StripTrailingSpaces().
ReplaceTargetRE()
int wxScintilla::ReplaceTargetRE (const wxString & text)
Replace the target text with the argument text after \d processing.
Text is counted so it can contain NULs. Looks for \d where d is between 1 and 9 and replaces these with the strings matched in the last search operation which were surrounded by \(and \). Returns the length of the replacement text including any change caused by processing the \d patterns.
Referenced by FindReplace::Replace(), and FindReplace::ReplaceInFiles().
RGBAImageSetHeight()
void wxScintilla::RGBAImageSetHeight (int height)
Set the height for future RGBA image data.
RGBAImageSetScale()
void wxScintilla::RGBAImageSetScale (int scalePercent)
Set the scale factor in percent for future RGBA image data.
RGBAImageSetWidth()
void wxScintilla::RGBAImageSetWidth (int width)
Set the width for future RGBA image data.
RotateSelection()
void wxScintilla::RotateSelection ()
Set the main selection to the next selection.
SaveFile()
bool wxScintilla::SaveFile (const wxString & filename)
Write the contents of the editor to filename.
ScrollRange()
void wxScintilla::ScrollRange (int secondary, int primary)
Scroll the argument positions and the range between them into view giving priority to the primary position then the secondary position.
This may be used to make a search match visible.
ScrollToColumn()
void wxScintilla::ScrollToColumn (int column)
Scroll enough to make the given column visible.
Referenced by cbEditor::SetProjectFile().
ScrollToEnd()
void wxScintilla::ScrollToEnd ()
Scroll to end of document.
ScrollToLine()
void wxScintilla::ScrollToLine (int line)
Scroll enough to make the given line visible.
Referenced by cbEditor::SetProjectFile().
ScrollToStart()
void wxScintilla::ScrollToStart ()
Scroll to start of document.
SearchAnchor()
void wxScintilla::SearchAnchor ()
Sets the current caret position to be the search anchor.
SearchInTarget()
int wxScintilla::SearchInTarget (const wxString & text)
Search for a counted string in the target and set the target to the found range.
Text is counted so it can contain NULs. Returns length of range or -1 for failure in which case target is not moved.
SearchNext()
int wxScintilla::SearchNext (int searchFlags, const wxString & text)
Find some text starting at the search anchor.
Does not ensure the selection is visible.
SearchPrev()
int wxScintilla::SearchPrev (int searchFlags, const wxString & text)
Find some text starting at the search anchor and moving backwards.
Does not ensure the selection is visible.
SelectAll()
void wxScintilla::SelectAll ()
Select all the text in the document.
Referenced by cbEditor::OnContextMenuEntry(), and cbEditor::SelectAll().
SelectionDuplicate()
void wxScintilla::SelectionDuplicate ()
Duplicate the selection. If selection empty duplicate the line containing the caret.
SelectionIsRectangle()
bool wxScintilla::SelectionIsRectangle () const
Is the selection rectangular? The alternative is the more common stream selection.
SelectNone()
virtual void wxScintilla::SelectNone () inline virtual
Definition at line 5302 of file wxscintilla.h.
SendMsg()
wxIntPtr wxScintilla::SendMsg (int msg, wxUIntPtr wp = 0, wxIntPtr lp = 0) const
Send a message to Scintilla.
NB: this method is not really const as it can modify the control but it has to be declared as such as it's called from both const and non-const methods and we can't distinguish between the two
Referenced by cbEditor::DoIndent(), and cbEditor::DoUnIndent().
SetAdditionalCaretForeground()
void wxScintilla::SetAdditionalCaretForeground (const wxColour & fore)
Set the foreground colour of additional carets.
SetAdditionalCaretsBlink()
void wxScintilla::SetAdditionalCaretsBlink (bool additionalCaretsBlink)
Set whether additional carets will blink.
SetAdditionalCaretsVisible()
void wxScintilla::SetAdditionalCaretsVisible (bool additionalCaretsVisible)
Set whether additional carets are visible.
SetAdditionalSelAlpha()
void wxScintilla::SetAdditionalSelAlpha (int alpha)
Set the alpha of the selection.
SetAdditionalSelBackground()
void wxScintilla::SetAdditionalSelBackground (const wxColour & back)
Set the background colour of additional selections.
Must have previously called SetSelBack with non-zero first argument for this to have an effect.
SetAdditionalSelectionTyping()
void wxScintilla::SetAdditionalSelectionTyping (bool additionalSelectionTyping)
Set whether typing can be performed into multiple selections.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), and MainFrame::OnEditSelectAll().
SetAdditionalSelForeground()
void wxScintilla::SetAdditionalSelForeground (const wxColour & fore)
Set the foreground colour of additional selections.
Must have previously called SetSelFore with non-zero first argument for this to have an effect.
SetAnchor()
void wxScintilla::SetAnchor (int anchor)
Set the selection anchor to a position.
The anchor is the opposite end of the selection from the caret.
SetAutomaticFold()
void wxScintilla::SetAutomaticFold (int automaticFold)
Set automatic folding behaviours.
SetBackSpaceUnIndents()
void wxScintilla::SetBackSpaceUnIndents (bool bsUnIndents)
Sets whether a backspace pressed when caret is within indentation unindents.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetBufferedDraw()
void wxScintilla::SetBufferedDraw (bool buffered)
If drawing is buffered then each line of text is drawn into a bitmap buffer before drawing it to the screen to avoid flicker.
SetCaretForeground()
void wxScintilla::SetCaretForeground (const wxColour & fore)
Set the foreground colour of the caret.
Referenced by cbStyledTextCtrl::HighlightRightBrace(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetCaretLineBackAlpha()
void wxScintilla::SetCaretLineBackAlpha (int alpha)
Set background alpha of the caret line.
SetCaretLineBackground()
void wxScintilla::SetCaretLineBackground (const wxColour & back)
Set the colour of the background of the line containing the caret.
Referenced by EditorColourSet::Apply().
SetCaretLineVisible()
void wxScintilla::SetCaretLineVisible (bool show)
Display the background of the line containing the caret in a different colour.
Referenced by EditorConfigurationDlg::CreateColoursSample(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetCaretLineVisibleAlways()
void wxScintilla::SetCaretLineVisibleAlways (bool alwaysVisible)
Sets the caret line to always visible.
SetCaretPeriod()
void wxScintilla::SetCaretPeriod (int periodMilliseconds)
Get the time in milliseconds that the caret is on and off. 0 = steady on.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetCaretSticky()
void wxScintilla::SetCaretSticky (int useCaretStickyBehaviour)
Stop the caret preferred x position changing when the user types.
SetCaretStyle()
void wxScintilla::SetCaretStyle (int caretStyle)
Set the style of the caret to be drawn.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetCaretWidth()
void wxScintilla::SetCaretWidth (int pixelWidth)
Set the width of the insert mode caret.
Referenced by cbStyledTextCtrl::HighlightRightBrace(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetChangeCollection()
void wxScintilla::SetChangeCollection (bool collectChange)
Choose between collecting actions into the changes history and discarding them.
Referenced by MainFrame::OnFileNewWhat(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and cbEditor::SetChangeCollection().
SetCharsDefault()
void wxScintilla::SetCharsDefault ()
Reset the set of characters for whitespace and word characters to the defaults.
SetCodePage()
void wxScintilla::SetCodePage (int codePage)
Set the code page used to interpret the bytes of the document as characters.
SetControlCharSymbol()
void wxScintilla::SetControlCharSymbol (int symbol)
Change the way control characters are displayed: If symbol is < 32, keep the drawn way, else, use the given character.
SetCurrentPos()
void wxScintilla::SetCurrentPos (int caret)
Sets the position of the caret.
SetDocPointer()
void wxScintilla::SetDocPointer (void * docPointer)
Change the document object used.
Referenced by cbEditor::Split().
SetEdgeColour()
void wxScintilla::SetEdgeColour (const wxColour & edgeColour)
Change the colour used in edge indication.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetEdgeColumn()
void wxScintilla::SetEdgeColumn (int column)
Set the column number of the edge.
If text goes past the edge then it is highlighted.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetEdgeMode()
void wxScintilla::SetEdgeMode (int edgeMode)
The edge may be displayed by a line (wxSCI_EDGE_LINE/wxSCI_EDGE_MULTILINE) or by highlighting text that goes beyond it (wxSCI_EDGE_BACKGROUND) or not displayed at all (wxSCI_EDGE_NONE).
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::Print().
SetEditable()
virtual void wxScintilla::SetEditable (bool editable) inline virtual
Definition at line 5331 of file wxscintilla.h.
SetEmptySelection()
void wxScintilla::SetEmptySelection (int caret)
Set caret to a position, while removing any existing selection.
SetEndAtLastLine()
void wxScintilla::SetEndAtLastLine (bool endAtLastLine)
Sets the scroll range so that maximum scroll position has the last line at the bottom of the view (default).
Setting this to false allows scrolling one page below the last line.
SetEOLMode()
void wxScintilla::SetEOLMode (int eolMode)
Set the current end of line mode.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen(), and MainFrame::OnEditEOLMode().
SetExtraAscent()
void wxScintilla::SetExtraAscent (int extraAscent)
Set extra ascent for each line.
SetExtraDescent()
void wxScintilla::SetExtraDescent (int extraDescent)
Set extra descent for each line.
SetFirstVisibleLine()
void wxScintilla::SetFirstVisibleLine (int displayLine)
Scroll so that a display line is at the top of the display.
Referenced by DisassemblyDlg::CenterLine().
SetFoldExpanded()
void wxScintilla::SetFoldExpanded (int line, bool expanded)
Show the children of a header line.
Referenced by cbEditor::DoFoldAll(), cbEditor::FixFoldState(), and cbEditor::OnEditorModified().
SetFoldFlags()
void wxScintilla::SetFoldFlags (int flags)
Set some style options for folding.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen(), and cbEditor::UnderlineFoldedLines().
SetFoldLevel()
void wxScintilla::SetFoldLevel (int line, int level)
Set the fold level of a line.
This encodes an integer level along with flags indicating whether the line is a header and whether it is effectively white space.
Referenced by cbEditor::SaveFoldState().
SetFoldMarginColour()
void wxScintilla::SetFoldMarginColour (bool useSetting, const wxColour & back)
Set one of the colours used as a chequerboard pattern in the fold margin.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetFoldMarginHiColour()
void wxScintilla::SetFoldMarginHiColour (bool useSetting, const wxColour & fore)
Set the other colour used as a chequerboard pattern in the fold margin.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetFontQuality()
void wxScintilla::SetFontQuality (int fontQuality)
Choose the quality level for text.
SetHighlightGuide()
void wxScintilla::SetHighlightGuide (int column)
Set the highlighted indentation guide column.
0 = no highlighted guide.
Referenced by cbEditor::HighlightBraces().
SetHotspotActiveBackground()
void wxScintilla::SetHotspotActiveBackground (bool useSetting, const wxColour & back)
Set a back colour for active hotspots.
SetHotspotActiveForeground()
void wxScintilla::SetHotspotActiveForeground (bool useSetting, const wxColour & fore)
Set a fore colour for active hotspots.
SetHotspotActiveUnderline()
void wxScintilla::SetHotspotActiveUnderline (bool underline)
Enable / Disable underlining active hotspots.
SetHotspotSingleLine()
void wxScintilla::SetHotspotSingleLine (bool singleLine)
Limit hotspots to single line so hotspots on two lines don't merge.
SetHScrollBar()
void wxScintilla::SetHScrollBar (wxScrollBar * bar)
Set the horizontal scrollbar to use instead of the one that's built-in.
SetIdentifier()
void wxScintilla::SetIdentifier (int identifier)
Set the identifier reported as idFrom in notification messages.
SetIdentifiers()
void wxScintilla::SetIdentifiers (int style, const wxString & identifiers)
Set the identifiers that are shown in a particular style.
SetIdleStyling()
void wxScintilla::SetIdleStyling (int idleStyling)
Sets limits to idle styling.
SetIMEInteraction()
void wxScintilla::SetIMEInteraction (int imeInteraction)
Choose to display the the IME in a winow or inline.
SetIndent()
void wxScintilla::SetIndent (int indentSize)
Set the number of spaces used for one level of indentation.
SetIndentationGuides()
void wxScintilla::SetIndentationGuides (int indentView)
Show or hide indentation guides.
Referenced by EditorConfigurationDlg::CreateColoursSample(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetIndicatorCurrent()
void wxScintilla::SetIndicatorCurrent (int indicator)
Set the indicator used for IndicatorFillRange and IndicatorClearRange.
Referenced by cbStyledTextCtrl::HighlightRightBrace().
SetIndicatorValue()
void wxScintilla::SetIndicatorValue (int value)
Set the value used for IndicatorFillRange.
SetInsertionPoint()
virtual void wxScintilla::SetInsertionPoint (long pos) inline virtual
Definition at line 5282 of file wxscintilla.h.
SetKeyWords()
void wxScintilla::SetKeyWords (int keyWordSet, const wxString & keyWords)
Set up the key words used by the lexer.
Referenced by EditorColourSet::Apply(), EditorManager::CollectDefines(), and CodeCompletion::UpdateEditorSyntax().
SetLastKeydownProcessed()
void wxScintilla::SetLastKeydownProcessed (bool val) inline
Definition at line 5165 of file wxscintilla.h.
References NULL.
SetLayoutCache()
void wxScintilla::SetLayoutCache (int cacheMode)
Sets the degree of caching of layout information.
SetLexer()
void wxScintilla::SetLexer (int lexer)
Set the lexing language of the document.
Referenced by EditorColourSet::Apply().
SetLexerLanguage()
void wxScintilla::SetLexerLanguage (const wxString & language)
Set the lexing language of the document based on string name.
SetLineEndTypesAllowed()
void wxScintilla::SetLineEndTypesAllowed (int lineEndBitSet)
Set the line end types that the application wants to use. May not be used if incompatible with lexer or encoding.
SetLineIndentation()
void wxScintilla::SetLineIndentation (int line, int indentation)
Change the indentation of a line to a number of columns.
SetLineState()
void wxScintilla::SetLineState (int line, int state)
Used to hold extra styling information for each line.
SetMainSelection()
void wxScintilla::SetMainSelection (int selection)
Set the main selection.
SetMarginBackground()
void wxScintilla::SetMarginBackground (int margin, const wxColour & back)
Set the background colour of a margin. Only visible for wxSCI_MARGIN_COLOUR.
SetMarginCount()
void wxScintilla::SetMarginCount (int margins)
Allocate a non-standard number of margins.
SetMarginCursor()
void wxScintilla::SetMarginCursor (int margin, int cursor)
Set the cursor shown when the mouse is inside a margin.
SetMarginLeft()
void wxScintilla::SetMarginLeft (int pixelWidth)
Sets the size in pixels of the left margin.
SetMarginMask()
void wxScintilla::SetMarginMask (int margin, int mask)
Set a mask that determines which markers are displayed in a margin.
Referenced by cbEditor::DoInitializations(), cbEditor::InternalSetEditorStyleAfterFileOpen(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetMarginOptions()
void wxScintilla::SetMarginOptions (int marginOptions)
Set the margin options.
SetMarginRight()
void wxScintilla::SetMarginRight (int pixelWidth)
Sets the size in pixels of the right margin.
SetMargins()
void wxScintilla::SetMargins (int left, int right)
Set the left and right margin in the edit area, measured in pixels.
SetMarginSensitive()
void wxScintilla::SetMarginSensitive (int margin, bool sensitive)
Make a margin sensitive or insensitive to mouse clicks.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetMarginType()
void wxScintilla::SetMarginType (int margin, int marginType)
Set a margin to be either numeric or symbolic.
Referenced by EditorConfigurationDlg::CreateColoursSample(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), and cbEditor::Print().
SetMarginWidth()
void wxScintilla::SetMarginWidth (int margin, int pixelWidth)
Set the width of a margin to a width expressed in pixels.
Referenced by EditorConfigurationDlg::CreateColoursSample(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), cbEditor::Print(), cbEditorInternalData::SetFoldingColWidth(), cbEditorInternalData::SetLineNumberColWidth(), and cbEditor::Split().
SetModEventMask()
void wxScintilla::SetModEventMask (int eventMask)
Set which document modification events are sent to the container.
Referenced by cbEditor::Open().
SetMouseCapture()
void wxScintilla::SetMouseCapture (bool on)
Referenced by cbStyledTextCtrl::OnContextMenu().
SetMouseDownCaptures()
void wxScintilla::SetMouseDownCaptures (bool captures)
Set whether the mouse is captured when its button is pressed.
SetMouseDwellTime()
void wxScintilla::SetMouseDwellTime (int periodMilliseconds)
Sets the time the mouse must sit still to generate a mouse dwell event.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetMouseSelectionRectangularSwitch()
void wxScintilla::SetMouseSelectionRectangularSwitch (bool mouseSelectionRectangularSwitch)
Set whether switching to rectangular mode while selecting with the mouse is allowed.
SetMouseWheelCaptures()
void wxScintilla::SetMouseWheelCaptures (bool captures)
Set whether the mouse wheel can be active outside the window.
SetMultiPaste()
void wxScintilla::SetMultiPaste (int multiPaste)
Change the effect of pasting when there are multiple selections.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen(), and MainFrame::OnEditSelectAll().
SetMultipleSelection()
void wxScintilla::SetMultipleSelection (bool multipleSelection)
Set whether multiple selections can be made.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetOvertype()
void wxScintilla::SetOvertype (bool overType)
Set to overtype (true) or insert mode.
SetPasteConvertEndings()
void wxScintilla::SetPasteConvertEndings (bool convert)
Enable/Disable convert-on-paste for line endings.
SetPhasesDraw()
void wxScintilla::SetPhasesDraw (int phases)
In one phase draw, text is drawn in a series of rectangular blocks with no overlap.
In two phase draw, text is drawn in a series of lines allowing runs to overlap horizontally. In multiple phase draw, each element is drawn over the whole drawing area, allowing text to overlap from one line to the next.
SetPositionCacheSize()
void wxScintilla::SetPositionCacheSize (int size)
Set number of entries in position cache.
SetPrintColourMode()
void wxScintilla::SetPrintColourMode (int mode)
Modify colours when printing for clearer printed text.
Referenced by cbEditor::Print().
SetPrintMagnification()
void wxScintilla::SetPrintMagnification (int magnification)
Sets the print magnification added to the point size of each style for printing.
Referenced by cbEditor::Print().
SetPrintWrapMode()
void wxScintilla::SetPrintWrapMode (int wrapMode)
Set printing to line wrapped (wxSCI_WRAP_WORD) or not line wrapped (wxSCI_WRAP_NONE).
SetProperty()
void wxScintilla::SetProperty (const wxString & key, const wxString & value)
Set up a value that may be used by a lexer for some optional feature.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen().
SetPunctuationChars()
void wxScintilla::SetPunctuationChars (const wxString & characters)
Set the set of characters making up punctuation characters Should be called after SetWordChars.
SetReadOnly()
void wxScintilla::SetReadOnly (bool readOnly)
Set to read only or read write.
Referenced by DisassemblyDlg::AddAssemblerLine(), DisassemblyDlg::AddSourceLine(), DisassemblyDlg::Clear(), and cbEditor::SetReadOnly().
SetRectangularSelectionAnchor()
void wxScintilla::SetRectangularSelectionAnchor (int anchor)
Set the anchor position of the rectangular selection.
SetRectangularSelectionAnchorVirtualSpace()
void wxScintilla::SetRectangularSelectionAnchorVirtualSpace (int space)
Set the virtual space of the anchor of the rectangular selection.
SetRectangularSelectionCaret()
void wxScintilla::SetRectangularSelectionCaret (int caret)
Set the caret position of the rectangular selection.
SetRectangularSelectionCaretVirtualSpace()
void wxScintilla::SetRectangularSelectionCaretVirtualSpace (int space)
Set the virtual space of the caret of the rectangular selection.
SetRectangularSelectionModifier()
void wxScintilla::SetRectangularSelectionModifier (int modifier)
On GTK+, allow selecting the modifier key to use for mouse-based rectangular selection.
Often the window manager requires Alt+Mouse Drag for moving windows. Valid values are wxSCI_KEYMOD_CTRL (default), wxSCI_KEYMOD_ALT, or wxSCI_KEYMOD_SUPER.
SetRepresentation()
void wxScintilla::SetRepresentation (const wxString & encodedCharacter, const wxString & representation)
Set the way a character is drawn.
SetSavePoint()
void wxScintilla::SetSavePoint ()
Remember the current position in the undo history as the position at which the document was saved.
Referenced by cbEditor::Save(), and cbEditor::SetModified().
SetSCICursor()
void wxScintilla::SetSCICursor (int cursorType)
Sets the cursor to one of the wxSCI_CURSOR* values.
SetSCIFocus()
void wxScintilla::SetSCIFocus (bool focus)
Change internal focus flag.
Referenced by FindReplace::Find(), FindReplace::FindInFiles(), and FindReplace::Replace().
SetScrollWidth()
void wxScintilla::SetScrollWidth (int pixelWidth)
Sets the document width assumed for scrolling.
SetScrollWidthTracking()
void wxScintilla::SetScrollWidthTracking (bool tracking)
Sets whether the maximum width line displayed is used to set scroll width.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetSearchFlags()
void wxScintilla::SetSearchFlags (int searchFlags)
Set the search flags used by SearchInTarget.
SetSelAlpha()
void wxScintilla::SetSelAlpha (int alpha)
Set the alpha of the selection.
SetSelBackground()
void wxScintilla::SetSelBackground (bool useSetting, const wxColour & back)
Set the background colour of the main and additional selections and whether to use this setting.
Referenced by EditorColourSet::Apply().
SetSelection()
virtual void wxScintilla::SetSelection (long from, long to) inline virtual
Definition at line 5289 of file wxscintilla.h.
Referenced by MainFrame::OnEditSelectNext().
SetSelectionEnd()
void wxScintilla::SetSelectionEnd (int caret)
Sets the position that ends the selection - this becomes the caret.
Referenced by FindReplace::FindSelectedText().
SetSelectionInt()
int wxScintilla::SetSelectionInt (int caret, int anchor)
Set a simple selection.
Referenced by cbEditor::GotoTokenPosition().
SetSelectionMode()
void wxScintilla::SetSelectionMode (int selectionMode)
Set the selection mode to stream (wxSCI_SEL_STREAM) or rectangular (wxSCI_SEL_RECTANGLE/wxSCI_SEL_THIN) or by lines (wxSCI_SEL_LINES).
SetSelectionNAnchor()
void wxScintilla::SetSelectionNAnchor (int selection, int anchor)
Set the anchor position of the nth selection.
Referenced by MainFrame::OnEditSelectNextSkip().
SetSelectionNAnchorVirtualSpace()
void wxScintilla::SetSelectionNAnchorVirtualSpace (int selection, int space)
Set the virtual space of the anchor of the nth selection.
Referenced by cbEditor::Save().
SetSelectionNCaret()
void wxScintilla::SetSelectionNCaret (int selection, int caret)
Set the caret position of the nth selection.
Referenced by MainFrame::OnEditSelectNextSkip().
SetSelectionNCaretVirtualSpace()
void wxScintilla::SetSelectionNCaretVirtualSpace (int selection, int space)
Set the virtual space of the caret of the nth selection.
Referenced by cbEditor::Save().
SetSelectionNEnd()
void wxScintilla::SetSelectionNEnd (int selection, int caret)
Sets the position that ends the selection - this becomes the currentPosition.
SetSelectionNStart()
void wxScintilla::SetSelectionNStart (int selection, int anchor)
Sets the position that starts the selection - this becomes the anchor.
SetSelectionStart()
void wxScintilla::SetSelectionStart (int anchor)
Sets the position that starts the selection - this becomes the anchor.
Referenced by FindReplace::FindSelectedText().
SetSelectionVoid()
void wxScintilla::SetSelectionVoid (int startPos, int endPos)
Select a range of text.
Referenced by FindReplace::Find(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditLineMove(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), cbStyledTextCtrl::OnMouseMiddleDown(), FindReplace::Replace(), and FindReplace::ReplaceInFiles().
SetSelEOLFilled()
void wxScintilla::SetSelEOLFilled (bool filled)
Set the selection to have its end of line filled or not.
SetSelForeground()
void wxScintilla::SetSelForeground (bool useSetting, const wxColour & fore)
Set the foreground colour of the main and additional selections and whether to use this setting.
Referenced by EditorColourSet::Apply().
SetStatus()
void wxScintilla::SetStatus (int status)
Change error status - 0 = OK.
SetStyleBytes()
void wxScintilla::SetStyleBytes (int length, char * styleBytes)
Set the styles for a segment of the document.
SetStyling()
void wxScintilla::SetStyling (int length, int style)
Change style from current styling position for length characters to a style and move the current styling position to after this newly styled segment.
SetTabDrawMode()
void wxScintilla::SetTabDrawMode (int tabDrawMode)
Set how tabs are drawn when visible.
SetTabIndents()
void wxScintilla::SetTabIndents (bool tabIndents)
Sets whether a tab pressed when caret is within indentation indents.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetTabWidth()
void wxScintilla::SetTabWidth (int tabWidth)
Change the visible size of a tab to be a multiple of the width of a space character.
Referenced by EditorConfigurationDlg::CreateColoursSample(), cbEditor::InternalSetEditorStyleAfterFileOpen(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetTargetEnd()
void wxScintilla::SetTargetEnd (int end)
Sets the position that ends the target which is used for updating the document without affecting the scroll position.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeRefactoring::DoRenameSymbols(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and cbEditorInternalData::StripTrailingSpaces().
SetTargetRange()
void wxScintilla::SetTargetRange (int start, int end)
Sets both the start and end of the target in one call.
SetTargetStart()
void wxScintilla::SetTargetStart (int start)
Sets the position that starts the target which is used for updating the document without affecting the scroll position.
Referenced by CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeRefactoring::DoRenameSymbols(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), and cbEditorInternalData::StripTrailingSpaces().
SetTechnology()
void wxScintilla::SetTechnology (int technology)
Set the technology used.
SetText()
void wxScintilla::SetText (const wxString & text)
Replace the contents of the document with the argument text.
Referenced by ScriptBindings::cbEditor_SetText(), DisassemblyDlg::Clear(), FindReplace::FindInFiles(), EditorManager::New(), cbEditor::SaveFoldState(), CodeRefactoring::SearchInFiles(), and CodeRefactoring::VerifyResult().
SetTextRaw()
void wxScintilla::SetTextRaw (const char * text)
Replace the contents of the document with the argument text.
SetTwoPhaseDraw()
void wxScintilla::SetTwoPhaseDraw (bool twoPhase)
In twoPhaseDraw mode, drawing is performed in two phases, first the background and then the foreground.
This avoids chopping off characters that overlap the next run.
SetUndoCollection()
void wxScintilla::SetUndoCollection (bool collectUndo)
Choose between collecting actions into the undo history and discarding them.
SetUseAntiAliasing()
void wxScintilla::SetUseAntiAliasing (bool useAA)
Specify whether anti-aliased fonts should be used.
Will have no effect on some platforms, but on some (wxMac for example) can greatly improve performance.
SetUseHorizontalScrollBar()
void wxScintilla::SetUseHorizontalScrollBar (bool visible)
Show or hide the horizontal scroll bar.
SetUseTabs()
void wxScintilla::SetUseTabs (bool useTabs)
Indentation will only use space characters if useTabs is false, otherwise it will use a combination of tabs and spaces.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), and OverrideUseTabsPerLanguage().
SetUseVerticalScrollBar()
void wxScintilla::SetUseVerticalScrollBar (bool visible)
Show or hide the vertical scroll bar.
SetValue()
void wxScintilla::SetValue (const wxString & text) inline protected
Definition at line 5347 of file wxscintilla.h.
SetViewEOL()
void wxScintilla::SetViewEOL (bool visible)
Make the end of line characters visible or invisible.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetViewWhiteSpace()
void wxScintilla::SetViewWhiteSpace (int viewWS)
Make white space characters invisible, always visible or visible outside indentation.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetVirtualSpaceOptions()
void wxScintilla::SetVirtualSpaceOptions (int virtualSpaceOptions)
Set options for virtual space behaviour.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetVisiblePolicy()
void wxScintilla::SetVisiblePolicy (int visiblePolicy, int visibleSlop)
Set the way the display area is determined when a particular line is to be moved to by Find, FindNext, GotoLine, etc.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetVScrollBar()
void wxScintilla::SetVScrollBar (wxScrollBar * bar)
Set the vertical scrollbar to use instead of the one that's built-in.
SetWhitespaceBackground()
void wxScintilla::SetWhitespaceBackground (bool useSetting, const wxColour & back)
Set the background colour of all whitespace and whether to use this setting.
SetWhitespaceChars()
void wxScintilla::SetWhitespaceChars (const wxString & characters)
Set the set of characters making up whitespace for when moving or selecting by word.
Should be called after SetWordChars.
SetWhitespaceForeground()
void wxScintilla::SetWhitespaceForeground (bool useSetting, const wxColour & fore)
Set the foreground colour of all whitespace and whether to use this setting.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetWhitespaceSize()
void wxScintilla::SetWhitespaceSize (int size)
Set the size of the dots used to mark space characters.
SetWordChars()
void wxScintilla::SetWordChars (const wxString & characters)
Set the set of characters making up words for when moving or selecting by word.
First sets defaults like SetCharsDefault.
SetWrapIndentMode()
void wxScintilla::SetWrapIndentMode (int wrapIndentMode)
Sets how wrapped sublines are placed. Default is wxSCI_WRAPINDENT_FIXED.
SetWrapMode()
void wxScintilla::SetWrapMode (int wrapMode)
Sets whether text is word wrapped.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetWrapStartIndent()
void wxScintilla::SetWrapStartIndent (int indent)
Set the start indent for wrapped lines.
SetWrapVisualFlags()
void wxScintilla::SetWrapVisualFlags (int wrapVisualFlags)
Set the display mode of visual flags for wrapped lines.
SetWrapVisualFlagsLocation()
void wxScintilla::SetWrapVisualFlagsLocation (int wrapVisualFlagsLocation)
Set the location of visual flags for wrapped lines.
SetXCaretPolicy()
void wxScintilla::SetXCaretPolicy (int caretPolicy, int caretSlop)
Set the way the caret is kept visible when going sideways.
The exclusion zone is given in pixels.
SetXOffset()
void wxScintilla::SetXOffset (int xOffset)
Set the xOffset (ie, horizontal scroll position).
SetYCaretPolicy()
void wxScintilla::SetYCaretPolicy (int caretPolicy, int caretSlop)
Set the way the line the caret is on is kept visible.
The exclusion zone is given in lines.
Referenced by cbEditor::InternalSetEditorStyleBeforeFileOpen().
SetZoom()
void wxScintilla::SetZoom (int zoomInPoints)
Set the zoom level.
This number of points is added to the size of all fonts. It may be positive to magnify or negative to reduce.
Referenced by MainFrame::OnEditZoomReset(), cbEditor::SetProjectFile(), cbEditor::SetZoom(), and cbEditor::Split().
ShowLines()
void wxScintilla::ShowLines (int lineStart, int lineEnd)
Make a range of lines visible.
Referenced by cbEditor::DoFoldAll(), cbEditor::FixFoldState(), and cbEditor::OnEditorModified().
StartRecord()
void wxScintilla::StartRecord ()
Start notifying the container of all key presses and commands.
StartStyling()
void wxScintilla::StartStyling (int start)
Set the current styling position to start.
StopRecord()
void wxScintilla::StopRecord ()
Stop notifying the container of all key presses and commands.
StutteredPageDown()
void wxScintilla::StutteredPageDown ()
Move caret to bottom of page, or one page down if already at bottom of page.
StutteredPageDownExtend()
void wxScintilla::StutteredPageDownExtend ()
Move caret to bottom of page, or one page down if already at bottom of page, extending selection to new caret position.
StutteredPageUp()
void wxScintilla::StutteredPageUp ()
Move caret to top of page, or one page up if already at top of page.
StutteredPageUpExtend()
void wxScintilla::StutteredPageUpExtend ()
Move caret to top of page, or one page up if already at top of page, extending selection to new caret position.
StyleClearAll()
void wxScintilla::StyleClearAll ()
Clear all the styles and make equivalent to the global default style.
Referenced by EditorColourSet::Apply(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
StyleGetBackground()
wxColour wxScintilla::StyleGetBackground (int style) const
Get the background colour of a style.
StyleGetBold()
bool wxScintilla::StyleGetBold (int style) const
Get is a style bold or not.
StyleGetCase()
int wxScintilla::StyleGetCase (int style) const
Get is a style mixed case, or to force upper or lower case.
StyleGetChangeable()
bool wxScintilla::StyleGetChangeable (int style) const
Get is a style changeable or not (read only).
Experimental feature, currently buggy.
StyleGetCharacterSet()
int wxScintilla::StyleGetCharacterSet (int style) const
Get the character get of the font in a style.
StyleGetEOLFilled()
bool wxScintilla::StyleGetEOLFilled (int style) const
Get is a style to have its end of line filled or not.
StyleGetFaceName()
wxString wxScintilla::StyleGetFaceName (int style)
Get the font facename of a style.
StyleGetFont()
wxFont wxScintilla::StyleGetFont (int style)
Get the font of a style.
Referenced by cbEditorInternalData::SetFoldingColWidth().
StyleGetForeground()
wxColour wxScintilla::StyleGetForeground (int style) const
Get the foreground colour of a style.
StyleGetHotSpot()
bool wxScintilla::StyleGetHotSpot (int style) const
Get is a style a hotspot or not.
StyleGetItalic()
bool wxScintilla::StyleGetItalic (int style) const
Get is a style italic or not.
StyleGetSize()
int wxScintilla::StyleGetSize (int style) const
Get the size of characters of a style.
StyleGetSizeFractional()
int wxScintilla::StyleGetSizeFractional (int style) const
Get the size of characters of a style in points multiplied by 100.
StyleGetUnderline()
bool wxScintilla::StyleGetUnderline (int style) const
Get is a style underlined or not.
StyleGetVisible()
bool wxScintilla::StyleGetVisible (int style) const
Get is a style visible or not.
StyleGetWeight()
int wxScintilla::StyleGetWeight (int style) const
Get the weight of characters of a style.
StyleResetDefault()
void wxScintilla::StyleResetDefault ()
Reset the default style to its state at startup.
StyleSetBackground()
void wxScintilla::StyleSetBackground (int style, const wxColour & back)
Set the background colour of a style.
Referenced by EditorColourSet::Apply(), and EditorColourSet::DoApplyStyle().
StyleSetBold()
void wxScintilla::StyleSetBold (int style, bool bold)
Set a style to be bold or not.
Referenced by EditorColourSet::DoApplyStyle().
StyleSetCase()
void wxScintilla::StyleSetCase (int style, int caseVisible)
Set a style to be mixed case, or to force upper or lower case.
StyleSetChangeable()
void wxScintilla::StyleSetChangeable (int style, bool changeable)
Set a style to be changeable or not (read only).
Experimental feature, currently buggy.
StyleSetCharacterSet()
void wxScintilla::StyleSetCharacterSet (int style, int characterSet)
Set the character set of the font in a style.
StyleSetEOLFilled()
void wxScintilla::StyleSetEOLFilled (int style, bool eolFilled)
Set a style to have its end of line filled or not.
StyleSetFaceName()
void wxScintilla::StyleSetFaceName (int style, const wxString & fontName)
Set the font of a style.
StyleSetFont()
void wxScintilla::StyleSetFont (int styleNum, const wxFont & font)
Set style size, face, bold, italic, and underline attributes from a wxFont's attributes.
Referenced by EditorConfigurationDlg::ApplyColours(), and cbEditor::InternalSetEditorStyleBeforeFileOpen().
StyleSetFontAttr()
void wxScintilla::StyleSetFontAttr (int styleNum, int size, const wxString & faceName, bool bold, bool italic, bool underline, wxFontEncoding encoding = wxFONTENCODING_DEFAULT)
Set all font style attributes at once.
StyleSetFontEncoding()
void wxScintilla::StyleSetFontEncoding (int style, wxFontEncoding encoding)
Set the font encoding to be used by a style.
StyleSetForeground()
void wxScintilla::StyleSetForeground (int style, const wxColour & fore)
Set the foreground colour of a style.
Referenced by EditorColourSet::Apply(), and EditorColourSet::DoApplyStyle().
StyleSetHotSpot()
void wxScintilla::StyleSetHotSpot (int style, bool hotspot)
Set a style to be a hotspot or not.
StyleSetItalic()
void wxScintilla::StyleSetItalic (int style, bool italic)
Set a style to be italic or not.
Referenced by EditorColourSet::DoApplyStyle().
StyleSetSize()
void wxScintilla::StyleSetSize (int style, int sizePoints)
Set the size of characters of a style.
StyleSetSizeFractional()
void wxScintilla::StyleSetSizeFractional (int style, int sizeHundredthPoints)
Set the size of characters of a style. Size is in points multiplied by 100.
StyleSetSpec()
void wxScintilla::StyleSetSpec (int styleNum, const wxString & spec)
Extract style settings from a spec-string which is composed of one or more of the following comma separated elements:
bold turns on bold italic turns on italics fore:[name or #RRGGBB] sets the foreground colour back:[name or #RRGGBB] sets the background colour face:[facename] sets the font face name to use size:[num] sets the font size in points eol turns on eol filling underline turns on underlining
StyleSetUnderline()
void wxScintilla::StyleSetUnderline (int style, bool underline)
Set a style to be underlined or not.
Referenced by EditorColourSet::DoApplyStyle().
StyleSetVisible()
void wxScintilla::StyleSetVisible (int style, bool visible)
Set a style to be visible or not.
StyleSetWeight()
void wxScintilla::StyleSetWeight (int style, int weight)
Set the weight of characters of a style.
SwapMainAnchorCaret()
void wxScintilla::SwapMainAnchorCaret ()
Swap that caret and anchor of the main selection.
Tab()
void wxScintilla::Tab ()
If selection is empty or all on one line replace the selection with a tab character.
If more than one line selected, indent the lines.
TargetFromSelection()
void wxScintilla::TargetFromSelection ()
Make the target range start and end be the same as the selection range start and end.
TargetWholeDocument()
void wxScintilla::TargetWholeDocument ()
Sets the target to the whole document.
TextHeight()
int wxScintilla::TextHeight (int line)
Retrieve the height of a particular line of text in pixels.
Referenced by ConfirmReplaceDlg::CalcPosition(), and CCManager::OnAutocompleteSelect().
TextWidth()
int wxScintilla::TextWidth (int style, const wxString & text)
Measure the pixel width of some text in a particular style.
Does not handle tab or control characters.
Referenced by CCManager::DoShowTips(), and cbEditorInternalData::SetLineNumberColWidth().
ToggleCaretSticky()
void wxScintilla::ToggleCaretSticky ()
Switch between sticky and non-sticky: meant to be bound to a key.
ToggleFold()
void wxScintilla::ToggleFold (int line)
Switch a header line between expanded and contracted.
Referenced by cbEditor::FixFoldState(), cbEditor::OnMarginClick(), and cbEditor::SetProjectFile().
ToggleFoldShowText()
void wxScintilla::ToggleFoldShowText (int line, const wxString & text)
Switch a header line between expanded and contracted and show some text after the line.
Undo()
void wxScintilla::Undo ()
Undo one action in the undo history.
Referenced by cbEditor::OnContextMenuEntry(), and cbEditor::Undo().
UpperCase()
void wxScintilla::UpperCase ()
Transform the selection to upper case.
Referenced by cbEditor::OnContextMenuEntry(), and MainFrame::OnEditUpperCase().
UsePopUp()
void wxScintilla::UsePopUp (int popUpMode)
Set whether a pop up menu is displayed automatically when the user presses the wrong mouse button on certain areas.
Referenced by cbEditor::CreateEditor().
UserListShow()
void wxScintilla::UserListShow (int listType, const wxString & itemList)
Display a list of strings and send notification when user chooses one.
VCHome()
void wxScintilla::VCHome ()
Move caret to before first visible character on line.
If already there move to first character on line.
VCHomeDisplay()
void wxScintilla::VCHomeDisplay ()
Move caret to before first visible character on display line.
If already there move to first character on display line.
VCHomeDisplayExtend()
void wxScintilla::VCHomeDisplayExtend ()
Like VCHomeDisplay but extending selection to new caret position.
VCHomeExtend()
void wxScintilla::VCHomeExtend ()
Like VCHome but extending selection to new caret position.
VCHomeRectExtend()
void wxScintilla::VCHomeRectExtend ()
Move caret to before first visible character on line.
If already there move to first character on line. In either case, extend rectangular selection to new caret position.
VCHomeWrap()
void wxScintilla::VCHomeWrap ()
Like VCHome but when word-wrap is enabled goes first to start of display line VCHomeDisplay, then behaves like VCHome.
VCHomeWrapExtend()
void wxScintilla::VCHomeWrapExtend ()
Like VCHomeExtend but when word-wrap is enabled extends first to start of display line VCHomeDisplayExtend, then behaves like VCHomeExtend.
VerticalCentreCaret()
void wxScintilla::VerticalCentreCaret ()
Centre current line in window.
VisibleFromDocLine()
int wxScintilla::VisibleFromDocLine (int docLine)
Find the display line of a document line taking hidden lines into account.
Referenced by CCManagerHelper::IsPosVisible(), and cbStyledTextCtrl::MakeNearbyLinesVisible().
WordEndPosition()
int wxScintilla::WordEndPosition (int pos, bool onlyWordCharacters)
Get position of end of word.
Referenced by EditorBase::DisplayContextMenu(), CodeCompletionHelper::EditorHasNameUnderCursor(), FindReplace::FindSelectedText(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), cbDebuggerPlugin::GetEditorWordAtCaret(), cbSmartIndentPlugin::GetLastNonCommentWord(), GetSelectedText(), CodeRefactoring::GetSymbolUnderCursor(), CodeCompletion::GetTokenAt(), CCManager::OnCompleteCode(), CCManager::OnEditorTooltip(), MainFrame::OnEditSelectNext(), MainFrame::OnEditStreamCommentSelected(), CodeCompletion::OnGotoDeclaration(), CodeRefactoring::Parse(), NativeParser::ParseLocalBlock(), and FindReplace::ShowFindDialog().
WordLeft()
void wxScintilla::WordLeft ()
Move caret left one word.
WordLeftEnd()
void wxScintilla::WordLeftEnd ()
Move caret left one word, position cursor at end of word.
WordLeftEndExtend()
void wxScintilla::WordLeftEndExtend ()
Move caret left one word, position cursor at end of word, extending selection to new caret position.
WordLeftExtend()
void wxScintilla::WordLeftExtend ()
Move caret left one word extending selection to new caret position.
WordPartLeft()
void wxScintilla::WordPartLeft ()
Move to the previous change in capitalisation.
Referenced by MainFrame::OnEditWordPartLeft().
WordPartLeftExtend()
void wxScintilla::WordPartLeftExtend ()
Move to the previous change in capitalisation extending selection to new caret position.
Referenced by MainFrame::OnEditWordPartLeftExtend().
WordPartRight()
void wxScintilla::WordPartRight ()
Move to the change next in capitalisation.
Referenced by MainFrame::OnEditWordPartRight().
WordPartRightExtend()
void wxScintilla::WordPartRightExtend ()
Move to the next change in capitalisation extending selection to new caret position.
Referenced by MainFrame::OnEditWordPartRightExtend().
WordRight()
void wxScintilla::WordRight ()
Move caret right one word.
WordRightEnd()
void wxScintilla::WordRightEnd ()
Move caret right one word, position cursor at end of word.
WordRightEndExtend()
void wxScintilla::WordRightEndExtend ()
Move caret right one word, position cursor at end of word, extending selection to new caret position.
WordRightExtend()
void wxScintilla::WordRightExtend ()
Move caret right one word extending selection to new caret position.
WordStartPosition()
int wxScintilla::WordStartPosition (int pos, bool onlyWordCharacters)
Get position of start of word.
Referenced by EditorBase::DisplayContextMenu(), CodeCompletion::DoAutocomplete(), CCManager::DoShowTips(), CCManager::DoUpdateCallTip(), CodeCompletionHelper::EditorHasNameUnderCursor(), FindReplace::FindSelectedText(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), cbDebuggerPlugin::GetEditorWordAtCaret(), cbSmartIndentPlugin::GetLastNonCommentWord(), GetSelectedText(), CodeRefactoring::GetSymbolUnderCursor(), CCManager::OnCompleteCode(), CCManager::OnEditorHook(), CCManager::OnEditorTooltip(), MainFrame::OnEditSelectNext(), MainFrame::OnEditStreamCommentSelected(), CodeCompletion::OnGotoDeclaration(), CCManager::OnShowCallTip(), NativeParser::ParseLocalBlock(), and FindReplace::ShowFindDialog().
WrapCount()
int wxScintilla::WrapCount (int docLine)
The number of display lines needed to wrap a document line.
WriteText()
virtual void wxScintilla::WriteText (const wxString & text) inline virtual
implement wxTextEntryBase pure virtual methods
Definition at line 5251 of file wxscintilla.h.
wxDEPRECATED_MSG() [1/3]
wxScintilla::wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.")
Divide each styling byte into lexical class bits (default: 5) and indicator bits (default: 3).
If a lexer requires more than 32 lexical states, then this is used to expand the possible states.
wxDEPRECATED_MSG() [2/3]
wxScintilla::wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") const
Retrieve number of bits in style bytes used to hold the lexical state.
wxDEPRECATED_MSG() [3/3]
wxScintilla::wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") const
Retrieve the number of bits the current lexer needs for styling.
ZoomIn()
void wxScintilla::ZoomIn ()
Magnify the displayed text by increasing the sizes by 1 point.
Referenced by MainFrame::OnEditZoomIn().
ZoomOut()
void wxScintilla::ZoomOut ()
Make the displayed text smaller by decreasing the sizes by 1 point.
Referenced by MainFrame::OnEditZoomOut().
Friends And Related Function Documentation
Platform
friend class Platform friend
Definition at line 5401 of file wxscintilla.h.
ScintillaWX
friend class ScintillaWX friend
Definition at line 5400 of file wxscintilla.h.
Member Data Documentation
m_hScrollBar
wxScrollBar* wxScintilla::m_hScrollBar protected
Definition at line 5396 of file wxscintilla.h.
m_lastKeyDownConsumed
bool wxScintilla::m_lastKeyDownConsumed protected
Definition at line 5398 of file wxscintilla.h.
m_stopWatch
wxStopWatch wxScintilla::m_stopWatch protected
Definition at line 5394 of file wxscintilla.h.
m_swx
ScintillaWX* wxScintilla::m_swx protected
Definition at line 5393 of file wxscintilla.h.
m_vScrollBar
wxScrollBar* wxScintilla::m_vScrollBar protected
Definition at line 5395 of file wxscintilla.h.
The documentation for this class was generated from the following file:
wxscintilla.h