Code::Blocks: Logger Class Reference
Logger Class Reference abstract
The base class for all kinds of loggers, see loggers.h for its derived classes.
#include <logger.h>
Classes
struct Feature
Public Types
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Public Member Functions
Logger ()
virtual ~Logger ()
virtual void Append (const wxString &msg, Logger::level lv=info)=0
virtual void Clear ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual void UpdateSettings ()
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool GetWrapMode () const
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Detailed Description
The base class for all kinds of loggers, see loggers.h for its derived classes.
Definition at line 23 of file logger.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
num_levels
Definition at line 38 of file logger.h.
level
enum Logger::level
Enumerator
caption
info
warning
success
error
critical
failure
pagetitle
spacer
asterisk
Definition at line 37 of file logger.h.
Constructor & Destructor Documentation
Logger()
Logger::Logger () inline
Definition at line 51 of file logger.h.
~Logger()
virtual Logger::~Logger () inline virtual
Definition at line 52 of file logger.h.
Member Function Documentation
Append()
virtual void Logger::Append (const wxString & msg, Logger::level lv = info) pure virtual
Implemented in ListCtrlLogger, TimestampTextCtrlLogger, TextCtrlLogger, HTMLFileLogger, and StdoutLogger.
AppendAdditionalMenuItems()
virtual void Logger::AppendAdditionalMenuItems (cb_optional wxMenu & menu) inline virtual
Definition at line 71 of file logger.h.
Referenced by InfoPane::DoShowContextMenu().
Clear()
virtual void Logger::Clear () inline virtual
Reimplemented in ListCtrlLogger, and TextCtrlLogger.
Definition at line 63 of file logger.h.
CopyContentsToClipboard()
virtual void Logger::CopyContentsToClipboard (cb_optional bool selectionOnly = false) inline virtual
Definition at line 64 of file logger.h.
CreateControl()
virtual wxWindow* Logger::CreateControl (cb_optional wxWindow * parent) inline virtual
Definition at line 67 of file logger.h.
Referenced by MainFrame::SetupGUILogging().
GetWrapMode()
virtual bool Logger::GetWrapMode () const inline virtual
Reimplemented in TextCtrlLogger.
Definition at line 69 of file logger.h.
Referenced by InfoPane::DoShowContextMenu().
HasFeature()
virtual bool Logger::HasFeature (cb_optional Feature::Enum feature) const inline virtual
Definition at line 70 of file logger.h.
Referenced by InfoPane::DoShowContextMenu().
UpdateSettings()
virtual void Logger::UpdateSettings () inline virtual
Reimplemented in ListCtrlLogger, TextCtrlLogger, and BuildLogger.
Definition at line 66 of file logger.h.
The documentation for this class was generated from the following file:
logger.h