Code::Blocks: Wiz Class Reference
Wiz Class Reference
#include <wiz.h>
Public Member Functions
Wiz ()
~Wiz ()
Wiz & operator= (cb_unused const Wiz &rhs)
int GetCount () const
TemplateOutputType GetOutputType (int index) const
wxString GetTitle (int index) const
wxString GetDescription (int index) const
wxString GetCategory (int index) const
const wxBitmap & GetBitmap (int index) const
wxString GetScriptFilename (int index) const
CompileTargetBase * Launch (int index, wxString *pFilename=0)
When this is called, the wizard must get to work ;).
CompileTargetBase * RunProjectWizard (wxString *pFilename)
CompileTargetBase * RunTargetWizard (wxString *pFilename)
CompileTargetBase * RunFilesWizard (wxString *pFilename)
CompileTargetBase * RunCustomWizard (wxString *pFilename)
void AddWizard (TemplateOutputType otype, const wxString &title, const wxString &cat, const wxString &script, const wxString &templatePNG, const wxString &wizardPNG, const wxString &xrc)
TemplateOutputType GetWizardType ()
void EnableWindow (const wxString &name, bool enable)
void CheckCheckbox (const wxString &name, bool check)
bool IsCheckboxChecked (const wxString &name)
void FillComboboxWithCompilers (const wxString &name)
wxString GetCompilerFromCombobox (const wxString &name)
void FillContainerWithCompilers (const wxString &name, const wxString &compilerID, const wxString &validCompilerIDs)
wxString GetComboboxStringSelection (const wxString &name)
int GetComboboxSelection (const wxString &name)
void SetComboboxSelection (const wxString &name, int sel)
void SetComboboxValue (const wxString &name, const wxString &value)
wxString GetComboboxValue (const wxString &name)
int GetRadioboxSelection (const wxString &name)
void SetRadioboxSelection (const wxString &name, int sel)
int GetListboxSelection (const wxString &name)
wxString GetListboxSelections (const wxString &name)
wxString GetListboxStringSelections (const wxString &name)
void SetListboxSelection (const wxString &name, int sel)
wxString GetCheckListboxChecked (const wxString &name)
wxString GetCheckListboxStringChecked (const wxString &name)
bool IsCheckListboxItemChecked (const wxString &name, unsigned int item)
void CheckCheckListboxItem (const wxString &name, unsigned int item, bool check)
void SetTextControlValue (const wxString &name, const wxString &value)
wxString GetTextControlValue (const wxString &name)
void SetSpinControlValue (const wxString &name, int value)
int GetSpinControlValue (const wxString &name)
wxString GetProjectPath ()
wxString GetProjectName ()
wxString GetProjectFullFilename ()
wxString GetProjectTitle ()
wxString GetCompilerID ()
bool GetWantDebug ()
wxString GetDebugName ()
wxString GetDebugOutputDir ()
wxString GetDebugObjectOutputDir ()
bool GetWantRelease ()
wxString GetReleaseName ()
wxString GetReleaseOutputDir ()
wxString GetReleaseObjectOutputDir ()
wxString GetTargetCompilerID ()
bool GetTargetEnableDebug ()
wxString GetTargetName ()
wxString GetTargetOutputDir ()
wxString GetTargetObjectOutputDir ()
wxString GetFileName ()
wxString GetFileHeaderGuard ()
bool GetFileAddToProject ()
int GetFileTargetIndex ()
void SetFilePathSelectionFilter (const wxString &filter)
void SetCompilerDefault (const wxString &defCompilerID)
void SetDebugTargetDefaults (bool wantDebug, const wxString &debugName, const wxString &debugOut, const wxString &debugObjOut)
void SetReleaseTargetDefaults (bool wantRelease, const wxString &releaseName, const wxString &releaseOut, const wxString &releaseObjOut)
void AddInfoPage (const wxString &pageId, const wxString &intro_msg)
void AddFilePathPage (bool showHeaderGuard)
void AddProjectPathPage ()
void AddCompilerPage (const wxString &compilerID, const wxString &validCompilerIDs, bool allowCompilerChange=true, bool allowConfigChange=true)
void AddBuildTargetPage (const wxString &targetName, bool isDebug, bool showCompiler=false, const wxString &compilerID=wxEmptyString, const wxString &validCompilerIDs=_T("*"), bool allowCompilerChange=true)
void AddGenericSingleChoiceListPage (const wxString &pageName, const wxString &descr, const wxString &choices, int defChoice)
void AddGenericSelectPathPage (const wxString &pageId, const wxString &descr, const wxString &label, const wxString &defValue)
void AddPage (const wxString &panelName)
void Finalize ()
void RegisterWizard ()
wxString FindTemplateFile (const wxString &filename)
Public Member Functions inherited from cbWizardPlugin
cbWizardPlugin ()
Public Member Functions inherited from cbPlugin
cbPlugin ()
In default cbPlugin's constructor the associated PluginInfo structure is filled with default values.
virtual ~cbPlugin ()
cbPlugin destructor.
virtual PluginType GetType () const
The plugin must return its type on request.
virtual int GetConfigurationPriority () const
Return the plugin's configuration priority.
virtual int GetConfigurationGroup () const
Return the configuration group for this plugin.
virtual cbConfigurationPanel * GetConfigurationPanel (cb_optional wxWindow *parent)
Return plugin's configuration panel.
virtual cbConfigurationPanel * GetProjectConfigurationPanel (cb_optional wxWindow *parent, cb_optional cbProject *project)
Return plugin's configuration panel for projects.
virtual void BuildMenu (cb_optional wxMenuBar *menuBar)
This method is called by Code::Blocks and is used by the plugin to add any menu items it needs on Code::Blocks's menu bar.
virtual void BuildModuleMenu (cb_optional const ModuleType type, cb_optional wxMenu *menu, cb_optional const FileTreeData *data=nullptr)
This method is called by Code::Blocks core modules (EditorManager, ProjectManager etc) and is used by the plugin to add any menu items it needs in the module's popup menu.
virtual bool BuildToolBar (cb_optional wxToolBar *toolBar)
This method is called by Code::Blocks and is used by the plugin to add any toolbar items it needs on Code::Blocks's toolbar.
virtual int GetToolBarPriority ()
This method return the priority of the plugin's toolbar, the less value indicates a more preceding position when C::B starts with no configuration file.
virtual void CreateStatusField (cbStatusBar *statusBar)
This method is called by Code::Blocks and is used by the plugin to add a field on Code::Blocks's statusbar.
bool IsAttached () const
See whether this plugin is attached or not.
virtual bool CanDetach () const
See whether this plugin can be detached (unloaded) or not.
Protected Member Functions
void OnAttach ()
Any descendent plugin should override this virtual method and perform any necessary initialization.
void Clear ()
void CopyFiles (cbProject *theproject, const wxString &prjdir, const wxString &srcdir)
wxString GenerateFile (const wxString &basePath, const wxString &filename, const wxString &contents)
Protected Member Functions inherited from cbPlugin
virtual void OnRelease (cb_optional bool appShutDown)
Any descendent plugin should override this virtual method and perform any necessary de-initialization.
virtual void NotImplemented (const wxString &log) const
This method logs a "Not implemented" message and is provided for convenience only.
Protected Attributes
Wizards m_Wizards
wxWizard * m_pWizard
WizPages m_Pages
WizProjectPathPanel * m_pWizProjectPathPanel
WizFilePathPanel * m_pWizFilePathPanel
WizCompilerPanel * m_pWizCompilerPanel
WizBuildTargetPanel * m_pWizBuildTargetPanel
int m_LaunchIndex
wxString m_LastXRC
wxString m_DefCompilerID
bool m_WantDebug
wxString m_DebugName
wxString m_DebugOutputDir
wxString m_DebugObjOutputDir
bool m_WantRelease
wxString m_ReleaseName
wxString m_ReleaseOutputDir
wxString m_ReleaseObjOutputDir
Protected Attributes inherited from cbPlugin
PluginType m_Type
Holds the plugin's type.
bool m_IsAttached
Holds the "attached" state.
Private Member Functions
Wiz (cb_unused const Wiz &rhs)
Detailed Description
Definition at line 38 of file wiz.h.
Constructor & Destructor Documentation
Wiz() [1/2]
Wiz::Wiz ()
Definition at line 58 of file wiz.cpp.
~Wiz()
Wiz::~Wiz ()
Definition at line 69 of file wiz.cpp.
Wiz() [2/2]
Wiz::Wiz (cb_unused const Wiz & rhs) private
Member Function Documentation
AddBuildTargetPage()
void Wiz::AddBuildTargetPage (const wxString & targetName, bool isDebug, bool showCompiler = false, const wxString & compilerID = wxEmptyString, const wxString & validCompilerIDs = _T("*"), bool allowCompilerChange = true)
Definition at line 1255 of file wiz.cpp.
References m_LaunchIndex, m_Pages, m_pWizard, m_pWizBuildTargetPanel, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddCompilerPage()
void Wiz::AddCompilerPage (const wxString & compilerID, const wxString & validCompilerIDs, bool allowCompilerChange = true, bool allowConfigChange = true)
Definition at line 1241 of file wiz.cpp.
References m_LaunchIndex, m_Pages, m_pWizard, m_pWizCompilerPanel, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddFilePathPage()
void Wiz::AddFilePathPage (bool showHeaderGuard)
Definition at line 1213 of file wiz.cpp.
References m_LaunchIndex, m_Pages, m_pWizard, m_pWizFilePathPanel, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddGenericSelectPathPage()
void Wiz::AddGenericSelectPathPage (const wxString & pageId, const wxString & descr, const wxString & label, const wxString & defValue)
Definition at line 1279 of file wiz.cpp.
References m_LaunchIndex, m_Pages, m_pWizard, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddGenericSingleChoiceListPage()
void Wiz::AddGenericSingleChoiceListPage (const wxString & pageName, const wxString & descr, const wxString & choices, int defChoice)
Definition at line 1269 of file wiz.cpp.
References _T, GetArrayFromString(), m_LaunchIndex, m_Pages, m_pWizard, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddInfoPage()
void Wiz::AddInfoPage (const wxString & pageId, const wxString & intro_msg)
Definition at line 1203 of file wiz.cpp.
References m_LaunchIndex, m_Pages, m_pWizard, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddPage()
void Wiz::AddPage (const wxString & panelName)
Definition at line 1289 of file wiz.cpp.
References m_LaunchIndex, m_Pages, m_pWizard, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddProjectPathPage()
void Wiz::AddProjectPathPage ()
Definition at line 1227 of file wiz.cpp.
References m_LaunchIndex, m_Pages, m_pWizard, m_pWizProjectPathPanel, m_Wizards, and WizPageBase::SkipPage().
Referenced by RegisterWizard().
AddWizard()
void Wiz::AddWizard (TemplateOutputType otype, const wxString & title, const wxString & cat, const wxString & script, const wxString & templatePNG, const wxString & wizardPNG, const wxString & xrc)
Definition at line 1311 of file wiz.cpp.
References _(), _T, WizardInfo::cat, cbLoadBitmap(), wxBitmap::ConvertToImage(), LogManager::DebugLog(), F(), Manager::Get(), ConfigManager::GetFolder(), wxBitmap::GetHeight(), Manager::GetLogManager(), wxBitmap::GetWidth(), LogManager::LogWarning(), m_Wizards, WizardInfo::output_type, wxImage::Resize(), WizardInfo::script, sdDataGlobal, sdDataUser, WizardInfo::templatePNG, WizardInfo::title, totCustom, totFiles, totProject, totTarget, totUser, WizardInfo::wizardPNG, wxString::wx_str(), wxBITMAP_TYPE_PNG, wxFileExists(), and WizardInfo::xrc.
Referenced by RegisterWizard().
CheckCheckbox()
void Wiz::CheckCheckbox (const wxString & name, bool check)
Definition at line 1134 of file wiz.cpp.
References wxWizard::GetCurrentPage(), m_pWizard, and wxCheckBox::SetValue().
Referenced by RegisterWizard().
CheckCheckListboxItem()
void Wiz::CheckCheckListboxItem (const wxString & name, unsigned int item, bool check)
Definition at line 1123 of file wiz.cpp.
References wxCheckListBox::Check(), wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
Clear()
void Wiz::Clear () protected
Definition at line 195 of file wiz.cpp.
References wxXmlResource::Get(), wxString::IsEmpty(), m_LastXRC, m_Pages, m_pWizard, m_pWizBuildTargetPanel, m_pWizCompilerPanel, m_pWizFilePathPanel, m_pWizProjectPathPanel, and wxXmlResource::Unload().
Referenced by Launch(), RunCustomWizard(), RunFilesWizard(), RunProjectWizard(), and RunTargetWizard().
CopyFiles()
void Wiz::CopyFiles (cbProject * theproject, const wxString & prjdir, const wxString & srcdir) protected
Definition at line 785 of file wiz.cpp.
References _T, ProjectManager::AddFileToProject(), cbProject::BeginAddFiles(), cbMessageBox(), CreateDirRecursively(), cbProject::EndAddFiles(), wxFileName::FileExists(), Manager::Get(), wxDir::GetAllFiles(), cbProject::GetBuildTargetsCount(), wxArrayString::GetCount(), ConfigManager::GetFolder(), wxFileName::GetFullPath(), wxFileName::GetPath(), Manager::GetProjectManager(), wxFileName::MakeRelativeTo(), wxString::Printf(), wxString::Replace(), sdDataGlobal, sdDataUser, wxCopyFile(), wxDirExists(), wxICON_QUESTION, wxID_YES, wxNO_DEFAULT, and wxYES_NO.
Referenced by RunProjectWizard().
EnableWindow()
void Wiz::EnableWindow (const wxString & name, bool enable)
Definition at line 901 of file wiz.cpp.
References wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
FillComboboxWithCompilers()
void Wiz::FillComboboxWithCompilers (const wxString & name)
Definition at line 867 of file wiz.cpp.
References CompilerFactory::GetCompiler(), CompilerFactory::GetCompilersCount(), wxWizard::GetCurrentPage(), CompilerFactory::GetDefaultCompiler(), Compiler::GetName(), and m_pWizard.
Referenced by RegisterWizard().
FillContainerWithCompilers()
void Wiz::FillContainerWithCompilers (const wxString & name, const wxString & compilerID, const wxString & validCompilerIDs)
Definition at line 888 of file wiz.cpp.
References Wizard::FillCompilerControl(), wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
Finalize()
void Wiz::Finalize ()
Definition at line 1298 of file wiz.cpp.
References wxWizardPageSimple::Chain(), wxWizard::GetPageAreaSizer(), m_Pages, and m_pWizard.
Referenced by Launch().
FindTemplateFile()
wxString Wiz::FindTemplateFile (const wxString & filename)
Definition at line 853 of file wiz.cpp.
References _T, ConfigManager::GetFolder(), sdDataGlobal, sdDataUser, and wxFileExists().
Referenced by RegisterWizard().
GenerateFile()
wxString Wiz::GenerateFile (const wxString & basePath, const wxString & filename, const wxString & contents) protected
Definition at line 713 of file wiz.cpp.
References _T, cbMessageBox(), cbWrite(), LogManager::DebugLog(), F(), wxFileName::FileExists(), FileTypeOf(), ftCodeBlocksProject, ftCodeBlocksWorkspace, ftDynamicLib, ftExecutable, ftObject, ftResourceBin, ftStaticLib, Manager::Get(), wxFileName::GetDirs(), GetEOLStr(), wxFileName::GetFullName(), wxFileName::GetFullPath(), Manager::GetLogManager(), wxFileName::GetPath(), wxFileName::IsRelative(), wxFileName::MakeRelativeTo(), wxFileName::Mkdir(), wxString::Printf(), wxFile::write, wxString::wx_str(), wxEmptyString, wxFONTENCODING_UTF8, wxICON_QUESTION, wxID_NO, wxNO_DEFAULT, and wxYES_NO.
Referenced by RunProjectWizard().
GetBitmap()
const wxBitmap & Wiz::GetBitmap (int index) const virtual
Parameters
index the wizard index.
Returns
the template's bitmap
Implements cbWizardPlugin.
Definition at line 180 of file wiz.cpp.
References cbAssert, GetCount(), and m_Wizards.
GetCategory()
wxString Wiz::GetCategory (int index) const virtual
Parameters
index the wizard index.
Returns
the template's category (GUI, Console, etc; free-form text). Try to adhere to standard category names...
Implements cbWizardPlugin.
Definition at line 171 of file wiz.cpp.
References cbAssert, GetCount(), and m_Wizards.
GetCheckListboxChecked()
wxString Wiz::GetCheckListboxChecked (const wxString & name)
Definition at line 1069 of file wiz.cpp.
References _T, wxString::Append(), wxString::Format(), wxCheckListBox::GetCount(), wxWizard::GetCurrentPage(), wxCheckListBox::IsChecked(), m_pWizard, and wxEmptyString.
Referenced by RegisterWizard().
GetCheckListboxStringChecked()
wxString Wiz::GetCheckListboxStringChecked (const wxString & name)
Definition at line 1090 of file wiz.cpp.
References _T, wxString::Append(), wxString::Format(), wxCheckListBox::GetCount(), wxWizard::GetCurrentPage(), wxCheckListBox::GetString(), wxCheckListBox::IsChecked(), m_pWizard, wxString::wx_str(), and wxEmptyString.
Referenced by RegisterWizard().
GetComboboxSelection()
int Wiz::GetComboboxSelection (const wxString & name)
Definition at line 968 of file wiz.cpp.
References wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by GetCompilerFromCombobox(), and RegisterWizard().
GetComboboxStringSelection()
wxString Wiz::GetComboboxStringSelection (const wxString & name)
Definition at line 956 of file wiz.cpp.
References wxWizard::GetCurrentPage(), m_pWizard, and wxEmptyString.
Referenced by RegisterWizard().
GetComboboxValue()
wxString Wiz::GetComboboxValue (const wxString & name)
Definition at line 934 of file wiz.cpp.
References wxWizard::GetCurrentPage(), m_pWizard, and wxEmptyString.
Referenced by RegisterWizard().
GetCompilerFromCombobox()
wxString Wiz::GetCompilerFromCombobox (const wxString & name)
Definition at line 947 of file wiz.cpp.
References GetComboboxSelection(), CompilerFactory::GetCompiler(), Compiler::GetID(), and wxEmptyString.
Referenced by RegisterWizard().
GetCompilerID()
wxString Wiz::GetCompilerID ()
Definition at line 1406 of file wiz.cpp.
References WizCompilerPanel::GetCompilerID(), WizBuildTargetPanel::GetCompilerID(), GetWizardType(), m_DefCompilerID, m_pWizBuildTargetPanel, m_pWizCompilerPanel, totProject, and totTarget.
Referenced by RegisterWizard(), and RunProjectWizard().
GetCount()
int Wiz::GetCount () const virtual
Returns
the number of template wizards this plugin contains
Implements cbWizardPlugin.
Definition at line 140 of file wiz.cpp.
References m_Wizards.
Referenced by GetBitmap(), GetCategory(), GetDescription(), GetOutputType(), GetScriptFilename(), GetTitle(), GetWizardType(), and Launch().
GetDebugName()
wxString Wiz::GetDebugName ()
Definition at line 1422 of file wiz.cpp.
References WizCompilerPanel::GetDebugName(), m_DebugName, and m_pWizCompilerPanel.
Referenced by RegisterWizard(), and RunProjectWizard().
GetDebugObjectOutputDir()
wxString Wiz::GetDebugObjectOutputDir ()
Definition at line 1436 of file wiz.cpp.
References WizCompilerPanel::GetDebugObjectOutputDir(), m_DebugObjOutputDir, and m_pWizCompilerPanel.
Referenced by RegisterWizard(), and RunProjectWizard().
GetDebugOutputDir()
wxString Wiz::GetDebugOutputDir ()
Definition at line 1429 of file wiz.cpp.
References WizCompilerPanel::GetDebugOutputDir(), m_DebugOutputDir, and m_pWizCompilerPanel.
Referenced by RegisterWizard().
GetDescription()
wxString Wiz::GetDescription (int index) const virtual
Parameters
index the wizard index.
Returns
the template's description
Implements cbWizardPlugin.
Definition at line 163 of file wiz.cpp.
References _(), cbAssert, and GetCount().
GetFileAddToProject()
bool Wiz::GetFileAddToProject ()
Definition at line 1520 of file wiz.cpp.
References WizFilePathPanel::GetAddToProject(), and m_pWizFilePathPanel.
Referenced by RegisterWizard().
GetFileHeaderGuard()
wxString Wiz::GetFileHeaderGuard ()
Definition at line 1513 of file wiz.cpp.
References WizFilePathPanel::GetHeaderGuard(), m_pWizFilePathPanel, and wxEmptyString.
Referenced by RegisterWizard().
GetFileName()
wxString Wiz::GetFileName ()
Definition at line 1506 of file wiz.cpp.
References WizFilePathPanel::GetFilename(), m_pWizFilePathPanel, and wxEmptyString.
Referenced by RegisterWizard().
GetFileTargetIndex()
int Wiz::GetFileTargetIndex ()
Definition at line 1527 of file wiz.cpp.
References WizFilePathPanel::GetTargetIndex(), and m_pWizFilePathPanel.
Referenced by RegisterWizard().
GetListboxSelection()
int Wiz::GetListboxSelection (const wxString & name)
Definition at line 1003 of file wiz.cpp.
References wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
GetListboxSelections()
wxString Wiz::GetListboxSelections (const wxString & name)
Definition at line 1016 of file wiz.cpp.
References _T, wxString::Append(), wxString::Format(), wxWizard::GetCurrentPage(), m_pWizard, and wxEmptyString.
Referenced by RegisterWizard().
GetListboxStringSelections()
wxString Wiz::GetListboxStringSelections (const wxString & name)
Definition at line 1037 of file wiz.cpp.
References _T, wxString::Append(), wxWizard::GetCurrentPage(), m_pWizard, and wxEmptyString.
Referenced by RegisterWizard().
GetOutputType()
TemplateOutputType Wiz::GetOutputType (int index) const virtual
Parameters
index the wizard index.
Returns
the output type of the specified wizard at index
Implements cbWizardPlugin.
Definition at line 146 of file wiz.cpp.
References cbAssert, GetCount(), and m_Wizards.
GetProjectFullFilename()
wxString Wiz::GetProjectFullFilename ()
Definition at line 1392 of file wiz.cpp.
References WizProjectPathPanel::GetFullFileName(), m_pWizProjectPathPanel, and wxEmptyString.
Referenced by RegisterWizard(), and RunProjectWizard().
GetProjectName()
wxString Wiz::GetProjectName ()
Definition at line 1385 of file wiz.cpp.
References WizProjectPathPanel::GetName(), m_pWizProjectPathPanel, and wxEmptyString.
Referenced by RegisterWizard().
GetProjectPath()
wxString Wiz::GetProjectPath ()
Definition at line 1378 of file wiz.cpp.
References WizProjectPathPanel::GetPath(), m_pWizProjectPathPanel, and wxEmptyString.
Referenced by RegisterWizard().
GetProjectTitle()
wxString Wiz::GetProjectTitle ()
Definition at line 1399 of file wiz.cpp.
References WizProjectPathPanel::GetTitle(), m_pWizProjectPathPanel, and wxEmptyString.
Referenced by RegisterWizard(), and RunProjectWizard().
GetRadioboxSelection()
int Wiz::GetRadioboxSelection (const wxString & name)
Definition at line 980 of file wiz.cpp.
References wxWizard::GetCurrentPage(), wxRadioBox::GetSelection(), and m_pWizard.
Referenced by RegisterWizard().
GetReleaseName()
wxString Wiz::GetReleaseName ()
Definition at line 1450 of file wiz.cpp.
References WizCompilerPanel::GetReleaseName(), m_pWizCompilerPanel, and m_ReleaseName.
Referenced by RegisterWizard(), and RunProjectWizard().
GetReleaseObjectOutputDir()
wxString Wiz::GetReleaseObjectOutputDir ()
Definition at line 1464 of file wiz.cpp.
References WizCompilerPanel::GetReleaseObjectOutputDir(), m_pWizCompilerPanel, and m_ReleaseObjOutputDir.
Referenced by RegisterWizard(), and RunProjectWizard().
GetReleaseOutputDir()
wxString Wiz::GetReleaseOutputDir ()
Definition at line 1457 of file wiz.cpp.
References WizCompilerPanel::GetReleaseOutputDir(), m_pWizCompilerPanel, and m_ReleaseOutputDir.
Referenced by RegisterWizard().
GetScriptFilename()
wxString Wiz::GetScriptFilename (int index) const virtual
Parameters
index the wizard index.
Returns
this wizard's script filename (if this wizard is scripted).
Implements cbWizardPlugin.
Definition at line 188 of file wiz.cpp.
References cbAssert, GetCount(), and m_Wizards.
GetSpinControlValue()
int Wiz::GetSpinControlValue (const wxString & name)
Definition at line 1191 of file wiz.cpp.
References wxWizard::GetCurrentPage(), wxSpinCtrl::GetValue(), and m_pWizard.
Referenced by RegisterWizard().
GetTargetCompilerID()
wxString Wiz::GetTargetCompilerID ()
Definition at line 1471 of file wiz.cpp.
References WizBuildTargetPanel::GetCompilerID(), m_pWizBuildTargetPanel, and wxEmptyString.
Referenced by RegisterWizard(), and RunTargetWizard().
GetTargetEnableDebug()
bool Wiz::GetTargetEnableDebug ()
Definition at line 1478 of file wiz.cpp.
References WizBuildTargetPanel::GetEnableDebug(), and m_pWizBuildTargetPanel.
Referenced by RegisterWizard(), and RunTargetWizard().
GetTargetName()
wxString Wiz::GetTargetName ()
Definition at line 1485 of file wiz.cpp.
References WizBuildTargetPanel::GetTargetName(), m_pWizBuildTargetPanel, and wxEmptyString.
Referenced by RegisterWizard(), and RunTargetWizard().
GetTargetObjectOutputDir()
wxString Wiz::GetTargetObjectOutputDir ()
Definition at line 1499 of file wiz.cpp.
References WizBuildTargetPanel::GetTargetObjectOutputDir(), m_pWizBuildTargetPanel, and wxEmptyString.
Referenced by RegisterWizard(), and RunTargetWizard().
GetTargetOutputDir()
wxString Wiz::GetTargetOutputDir ()
Definition at line 1492 of file wiz.cpp.
References WizBuildTargetPanel::GetTargetOutputDir(), m_pWizBuildTargetPanel, and wxEmptyString.
Referenced by RegisterWizard(), and RunTargetWizard().
GetTextControlValue()
wxString Wiz::GetTextControlValue (const wxString & name)
Definition at line 1168 of file wiz.cpp.
References wxWizard::GetCurrentPage(), m_pWizard, and wxEmptyString.
Referenced by RegisterWizard().
GetTitle()
wxString Wiz::GetTitle (int index) const virtual
Parameters
index the wizard index.
Returns
the template's title
Implements cbWizardPlugin.
Definition at line 154 of file wiz.cpp.
References cbAssert, GetCount(), and m_Wizards.
GetWantDebug()
bool Wiz::GetWantDebug ()
Definition at line 1415 of file wiz.cpp.
References WizCompilerPanel::GetWantDebug(), m_pWizCompilerPanel, and m_WantDebug.
Referenced by RegisterWizard(), and RunProjectWizard().
GetWantRelease()
bool Wiz::GetWantRelease ()
Definition at line 1443 of file wiz.cpp.
References WizCompilerPanel::GetWantRelease(), m_pWizCompilerPanel, and m_WantRelease.
Referenced by RegisterWizard(), and RunProjectWizard().
GetWizardType()
TemplateOutputType Wiz::GetWizardType ()
Definition at line 861 of file wiz.cpp.
References cbAssert, GetCount(), m_LaunchIndex, and m_Wizards.
Referenced by GetCompilerID(), and RegisterWizard().
IsCheckboxChecked()
bool Wiz::IsCheckboxChecked (const wxString & name)
Definition at line 1145 of file wiz.cpp.
References wxWizard::GetCurrentPage(), wxCheckBox::IsChecked(), and m_pWizard.
Referenced by RegisterWizard().
IsCheckListboxItemChecked()
bool Wiz::IsCheckListboxItemChecked (const wxString & name, unsigned int item)
Definition at line 1111 of file wiz.cpp.
References wxWizard::GetCurrentPage(), wxCheckListBox::IsChecked(), and m_pWizard.
Referenced by RegisterWizard().
Launch()
CompileTargetBase * Wiz::Launch (int index, wxString * createdFilename = 0) virtual
When this is called, the wizard must get to work ;).
Parameters
index the wizard index.
createdFilename if provided, on return it should contain the main filename this wizard created. If the user created a project, that would be the project's filename. If the wizard created a build target, that would be an empty string. If the wizard created a file, that would be the file's name.
Returns
a pointer to the generated cbProject or ProjectBuildTarget. NULL for everything else (failure too). You should dynamic-cast this to the correct type based on GetOutputType() 's value.
Implements cbWizardPlugin.
Definition at line 214 of file wiz.cpp.
References _(), _T, cbAssert, cbMessageBox(), wxString::Clear(), Clear(), wxWizard::Create(), InfoWindow::Display(), ScriptingManager::DisplayErrors(), Finalize(), wxXmlResource::Get(), Manager::Get(), GetCount(), ConfigManager::GetFolder(), Manager::GetScriptingManager(), ScriptingManager::LoadBuffer(), m_LastXRC, m_LaunchIndex, m_Pages, m_pWizard, m_pWizProjectPathPanel, m_Wizards, RunCustomWizard(), RunFilesWizard(), RunProjectWizard(), RunTargetWizard(), wxWizard::RunWizard(), sdDataGlobal, sdDataUser, cbException::ShowErrorMessage(), totCustom, totFiles, totProject, totTarget, wxDEFAULT_DIALOG_STYLE, wxDefaultPosition, wxFileExists(), wxICON_ERROR, wxID_ANY, and wxRESIZE_BORDER.
OnAttach()
void Wiz::OnAttach () protected virtual
Any descendent plugin should override this virtual method and perform any necessary initialization.
This method is called by Code::Blocks (PluginManager actually) when the plugin has been loaded and should attach in Code::Blocks. When Code::Blocks starts up, it finds and loads all plugins but does not activate (attaches) them. It then activates all plugins that the user has selected to be activated on start-up.
This means that a plugin might be loaded but not activated...
Think of this method as the actual constructor...
Reimplemented from cbPlugin.
Definition at line 74 of file wiz.cpp.
References _(), _T, cbMessageBox(), ScriptingManager::DisplayErrors(), Manager::Get(), CompilerFactory::GetDefaultCompilerID(), ConfigManager::GetFolder(), Manager::GetScriptingManager(), ScriptingManager::LoadScript(), m_DebugName, m_DebugObjOutputDir, m_DebugOutputDir, m_DefCompilerID, m_ReleaseName, m_ReleaseObjOutputDir, m_ReleaseOutputDir, m_WantDebug, m_WantRelease, RegisterWizard(), sdDataGlobal, sdDataUser, HTMLTags::sep, wxFileExists(), and wxICON_ERROR.
operator=()
Wiz& Wiz::operator= (cb_unused const Wiz & rhs) inline
Definition at line 44 of file wiz.h.
References _T, WizardInfo::cat, cbThrow, WizardInfo::script, WizardInfo::templatePNG, WizardInfo::title, WizardInfo::wizardPNG, wxEmptyString, and WizardInfo::xrc.
RegisterWizard()
void Wiz::RegisterWizard ()
Definition at line 1570 of file wiz.cpp.
References AddBuildTargetPage(), AddCompilerPage(), AddFilePathPage(), AddGenericSelectPathPage(), AddGenericSingleChoiceListPage(), AddInfoPage(), AddPage(), AddProjectPathPage(), AddWizard(), CheckCheckbox(), CheckCheckListboxItem(), EnableWindow(), FillComboboxWithCompilers(), FillContainerWithCompilers(), FindTemplateFile(), GetCheckListboxChecked(), GetCheckListboxStringChecked(), GetComboboxSelection(), GetComboboxStringSelection(), GetComboboxValue(), GetCompilerFromCombobox(), GetCompilerID(), GetDebugName(), GetDebugObjectOutputDir(), GetDebugOutputDir(), GetFileAddToProject(), GetFileHeaderGuard(), GetFileName(), GetFileTargetIndex(), GetListboxSelection(), GetListboxSelections(), GetListboxStringSelections(), GetProjectFullFilename(), GetProjectName(), GetProjectPath(), GetProjectTitle(), GetRadioboxSelection(), GetReleaseName(), GetReleaseObjectOutputDir(), GetReleaseOutputDir(), GetSpinControlValue(), GetTargetCompilerID(), GetTargetEnableDebug(), GetTargetName(), GetTargetObjectOutputDir(), GetTargetOutputDir(), GetTextControlValue(), GetWantDebug(), GetWantRelease(), GetWizardType(), IsCheckboxChecked(), IsCheckListboxItemChecked(), SetComboboxSelection(), SetComboboxValue(), SetCompilerDefault(), SetDebugTargetDefaults(), SetFilePathSelectionFilter(), SetListboxSelection(), SetRadioboxSelection(), SetReleaseTargetDefaults(), SetSpinControlValue(), and SetTextControlValue().
Referenced by OnAttach().
RunCustomWizard()
CompileTargetBase * Wiz::RunCustomWizard (wxString * pFilename)
Definition at line 697 of file wiz.cpp.
References _(), cbMessageBox(), Clear(), ScriptingManager::DisplayErrors(), Manager::Get(), Manager::GetScriptingManager(), and wxICON_ERROR.
Referenced by Launch().
RunFilesWizard()
CompileTargetBase * Wiz::RunFilesWizard (wxString * pFilename)
Definition at line 671 of file wiz.cpp.
References _(), _T, wxString::BeforeFirst(), cbMessageBox(), Clear(), ScriptingManager::DisplayErrors(), Manager::Get(), EditorManager::GetEditor(), Manager::GetEditorManager(), Manager::GetScriptingManager(), EditorBase::IsBuiltinEditor(), wxString::IsEmpty(), and wxICON_ERROR.
Referenced by Launch().
RunProjectWizard()
CompileTargetBase * Wiz::RunProjectWizard (wxString * pFilename)
Definition at line 340 of file wiz.cpp.
References _(), _T, wxArrayString::Add(), cbProject::AddBuildTarget(), ProjectManager::AddFileToProject(), wxString::AfterFirst(), wxString::BeforeFirst(), cbProject::BeginAddFiles(), wxString::c_str(), cbMessageBox(), Clear(), CopyFiles(), CreateDirRecursively(), LogManager::DebugLog(), ScriptingManager::DisplayErrors(), cbProject::EndAddFiles(), wxTreeCtrl::Expand(), F(), wxString::Format(), GenerateFile(), Manager::Get(), GetArrayFromString(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTargetsCount(), GetCompilerID(), wxArrayString::GetCount(), GetDebugName(), GetDebugObjectOutputDir(), CompilerFactory::GetDefaultCompilerID(), cbProject::GetFileByFilename(), CompileTargetBase::GetFilename(), Manager::GetLogManager(), wxFileName::GetPath(), GetProjectFullFilename(), Manager::GetProjectManager(), cbProject::GetProjectNode(), GetProjectTitle(), GetReleaseName(), GetReleaseObjectOutputDir(), Manager::GetScriptingManager(), cbProjectManagerUI::GetTree(), ProjectManager::GetUI(), GetWantDebug(), GetWantRelease(), wxString::IsEmpty(), ProjectManager::NewProject(), NULL, cbProjectManagerUI::RebuildTree(), cbProject::Save(), CompileTargetBase::SetCompilerID(), cbProject::SetCompilerID(), CompilerFactory::SetDefaultCompiler(), ProjectBuildTarget::SetIncludeInTargetAll(), CompileTargetBase::SetObjectOutput(), cbProject::SetTitle(), wxString::Trim(), wxString::wx_str(), and wxICON_ERROR.
Referenced by Launch().
RunTargetWizard()
CompileTargetBase * Wiz::RunTargetWizard (wxString * pFilename)
Definition at line 541 of file wiz.cpp.
References _(), ProjectFile::AddBuildTarget(), cbProject::AddBuildTarget(), cbMessageBox(), Clear(), ScriptingManager::DisplayErrors(), Manager::Get(), ProjectManager::GetActiveProject(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetDefaultCompilerID(), cbProject::GetFilesList(), Manager::GetProjectManager(), Manager::GetScriptingManager(), GetTargetCompilerID(), GetTargetEnableDebug(), GetTargetName(), GetTargetObjectOutputDir(), GetTargetOutputDir(), m_pWizBuildTargetPanel, CompileTargetBase::SetCompilerID(), ProjectBuildTarget::SetIncludeInTargetAll(), CompileTargetBase::SetObjectOutput(), CompileTargetBase::SetWorkingDir(), wxEmptyString, wxICON_ERROR, wxICON_INFORMATION, and wxOK.
Referenced by Launch().
SetComboboxSelection()
void Wiz::SetComboboxSelection (const wxString & name, int sel)
Definition at line 912 of file wiz.cpp.
References wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
SetComboboxValue()
void Wiz::SetComboboxValue (const wxString & name, const wxString & value)
Definition at line 923 of file wiz.cpp.
References wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
SetCompilerDefault()
void Wiz::SetCompilerDefault (const wxString & defCompilerID)
Definition at line 1540 of file wiz.cpp.
References CompilerFactory::GetDefaultCompilerID(), and m_DefCompilerID.
Referenced by RegisterWizard().
SetDebugTargetDefaults()
void Wiz::SetDebugTargetDefaults (bool wantDebug, const wxString & debugName, const wxString & debugOut, const wxString & debugObjOut)
Definition at line 1546 of file wiz.cpp.
References m_DebugName, m_DebugObjOutputDir, m_DebugOutputDir, and m_WantDebug.
Referenced by RegisterWizard().
SetFilePathSelectionFilter()
void Wiz::SetFilePathSelectionFilter (const wxString & filter)
Definition at line 1534 of file wiz.cpp.
References m_pWizFilePathPanel, and WizFilePathPanel::SetFilePathSelectionFilter().
Referenced by RegisterWizard().
SetListboxSelection()
void Wiz::SetListboxSelection (const wxString & name, int sel)
Definition at line 1058 of file wiz.cpp.
References wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
SetRadioboxSelection()
void Wiz::SetRadioboxSelection (const wxString & name, int sel)
Definition at line 992 of file wiz.cpp.
References wxWizard::GetCurrentPage(), m_pWizard, and wxRadioBox::SetSelection().
Referenced by RegisterWizard().
SetReleaseTargetDefaults()
void Wiz::SetReleaseTargetDefaults (bool wantRelease, const wxString & releaseName, const wxString & releaseOut, const wxString & releaseObjOut)
Definition at line 1558 of file wiz.cpp.
References m_ReleaseName, m_ReleaseObjOutputDir, m_ReleaseOutputDir, and m_WantRelease.
Referenced by RegisterWizard().
SetSpinControlValue()
void Wiz::SetSpinControlValue (const wxString & name, int value)
Definition at line 1180 of file wiz.cpp.
References wxWizard::GetCurrentPage(), m_pWizard, and wxSpinCtrl::SetValue().
Referenced by RegisterWizard().
SetTextControlValue()
void Wiz::SetTextControlValue (const wxString & name, const wxString & value)
Definition at line 1157 of file wiz.cpp.
References wxWizard::GetCurrentPage(), and m_pWizard.
Referenced by RegisterWizard().
Member Data Documentation
m_DebugName
wxString Wiz::m_DebugName protected
Definition at line 186 of file wiz.h.
Referenced by GetDebugName(), OnAttach(), and SetDebugTargetDefaults().
m_DebugObjOutputDir
wxString Wiz::m_DebugObjOutputDir protected
Definition at line 188 of file wiz.h.
Referenced by GetDebugObjectOutputDir(), OnAttach(), and SetDebugTargetDefaults().
m_DebugOutputDir
wxString Wiz::m_DebugOutputDir protected
Definition at line 187 of file wiz.h.
Referenced by GetDebugOutputDir(), OnAttach(), and SetDebugTargetDefaults().
m_DefCompilerID
wxString Wiz::m_DefCompilerID protected
Definition at line 184 of file wiz.h.
Referenced by GetCompilerID(), OnAttach(), and SetCompilerDefault().
m_LastXRC
wxString Wiz::m_LastXRC protected
Definition at line 181 of file wiz.h.
Referenced by Clear(), and Launch().
m_LaunchIndex
int Wiz::m_LaunchIndex protected
Definition at line 180 of file wiz.h.
Referenced by AddBuildTargetPage(), AddCompilerPage(), AddFilePathPage(), AddGenericSelectPathPage(), AddGenericSingleChoiceListPage(), AddInfoPage(), AddPage(), AddProjectPathPage(), GetWizardType(), and Launch().
m_Pages
WizPages Wiz::m_Pages protected
Definition at line 175 of file wiz.h.
Referenced by AddBuildTargetPage(), AddCompilerPage(), AddFilePathPage(), AddGenericSelectPathPage(), AddGenericSingleChoiceListPage(), AddInfoPage(), AddPage(), AddProjectPathPage(), Clear(), Finalize(), and Launch().
m_pWizard
wxWizard* Wiz::m_pWizard protected
Definition at line 174 of file wiz.h.
Referenced by AddBuildTargetPage(), AddCompilerPage(), AddFilePathPage(), AddGenericSelectPathPage(), AddGenericSingleChoiceListPage(), AddInfoPage(), AddPage(), AddProjectPathPage(), CheckCheckbox(), CheckCheckListboxItem(), Clear(), EnableWindow(), FillComboboxWithCompilers(), FillContainerWithCompilers(), Finalize(), GetCheckListboxChecked(), GetCheckListboxStringChecked(), GetComboboxSelection(), GetComboboxStringSelection(), GetComboboxValue(), GetListboxSelection(), GetListboxSelections(), GetListboxStringSelections(), GetRadioboxSelection(), GetSpinControlValue(), GetTextControlValue(), IsCheckboxChecked(), IsCheckListboxItemChecked(), Launch(), SetComboboxSelection(), SetComboboxValue(), SetListboxSelection(), SetRadioboxSelection(), SetSpinControlValue(), and SetTextControlValue().
m_pWizBuildTargetPanel
WizBuildTargetPanel* Wiz::m_pWizBuildTargetPanel protected
Definition at line 179 of file wiz.h.
Referenced by AddBuildTargetPage(), Clear(), GetCompilerID(), GetTargetCompilerID(), GetTargetEnableDebug(), GetTargetName(), GetTargetObjectOutputDir(), GetTargetOutputDir(), and RunTargetWizard().
m_pWizCompilerPanel
WizCompilerPanel* Wiz::m_pWizCompilerPanel protected
Definition at line 178 of file wiz.h.
Referenced by AddCompilerPage(), Clear(), GetCompilerID(), GetDebugName(), GetDebugObjectOutputDir(), GetDebugOutputDir(), GetReleaseName(), GetReleaseObjectOutputDir(), GetReleaseOutputDir(), GetWantDebug(), and GetWantRelease().
m_pWizFilePathPanel
WizFilePathPanel* Wiz::m_pWizFilePathPanel protected
Definition at line 177 of file wiz.h.
Referenced by AddFilePathPage(), Clear(), GetFileAddToProject(), GetFileHeaderGuard(), GetFileName(), GetFileTargetIndex(), and SetFilePathSelectionFilter().
m_pWizProjectPathPanel
WizProjectPathPanel* Wiz::m_pWizProjectPathPanel protected
Definition at line 176 of file wiz.h.
Referenced by AddProjectPathPage(), Clear(), GetProjectFullFilename(), GetProjectName(), GetProjectPath(), GetProjectTitle(), and Launch().
m_ReleaseName
wxString Wiz::m_ReleaseName protected
Definition at line 190 of file wiz.h.
Referenced by GetReleaseName(), OnAttach(), and SetReleaseTargetDefaults().
m_ReleaseObjOutputDir
wxString Wiz::m_ReleaseObjOutputDir protected
Definition at line 192 of file wiz.h.
Referenced by GetReleaseObjectOutputDir(), OnAttach(), and SetReleaseTargetDefaults().
m_ReleaseOutputDir
wxString Wiz::m_ReleaseOutputDir protected
Definition at line 191 of file wiz.h.
Referenced by GetReleaseOutputDir(), OnAttach(), and SetReleaseTargetDefaults().
m_WantDebug
bool Wiz::m_WantDebug protected
Definition at line 185 of file wiz.h.
Referenced by GetWantDebug(), OnAttach(), and SetDebugTargetDefaults().
m_WantRelease
bool Wiz::m_WantRelease protected
Definition at line 189 of file wiz.h.
Referenced by GetWantRelease(), OnAttach(), and SetReleaseTargetDefaults().
m_Wizards
Wizards Wiz::m_Wizards protected
Definition at line 173 of file wiz.h.
Referenced by AddBuildTargetPage(), AddCompilerPage(), AddFilePathPage(), AddGenericSelectPathPage(), AddGenericSingleChoiceListPage(), AddInfoPage(), AddPage(), AddProjectPathPage(), AddWizard(), GetBitmap(), GetCategory(), GetCount(), GetOutputType(), GetScriptFilename(), GetTitle(), GetWizardType(), and Launch().
The documentation for this class was generated from the following files:
wiz.h
wiz.cpp