Code::Blocks: SQCompiler Class Reference
SQCompiler Class Reference
Public Member Functions
SQCompiler (SQVM *v, SQLEXREADFUNC rg, SQUserPointer up, const SQChar *sourcename, bool raiseerror, bool lineinfo)
void Error (const SQChar *s,...)
void Lex ()
void PushExpState ()
bool IsDerefToken (SQInteger tok)
ExpState PopExpState ()
SQObject Expect (SQInteger tok)
bool IsEndOfStatement ()
void OptionalSemicolon ()
void MoveIfCurrentTargetIsLocal ()
bool Compile (SQObjectPtr &o)
void Statements ()
void Statement ()
void EmitDerefOp (SQOpcode op)
void Emit2ArgsOP (SQOpcode op, SQInteger p3=0)
void EmitCompoundArith (SQInteger tok, bool deref)
void CommaExpr ()
ExpState Expression (bool funcarg=false)
void BIN_EXP (SQOpcode op, void(SQCompiler::*f)(void), SQInteger op3=0)
void LogicalOrExp ()
void LogicalAndExp ()
void BitwiseOrExp ()
void BitwiseXorExp ()
void BitwiseAndExp ()
void CompExp ()
void ShiftExp ()
void PlusExp ()
void MultExp ()
void PrefixedExpr ()
SQInteger Factor ()
void UnaryOP (SQOpcode op)
bool NeedGet ()
void FunctionCallArgs ()
void ParseTableOrClass (SQInteger separator, SQInteger terminator= '}')
void LocalDeclStatement ()
void IfStatement ()
void WhileStatement ()
void DoWhileStatement ()
void ForStatement ()
void ForEachStatement ()
void SwitchStatement ()
void FunctionStatement ()
void ClassStatement ()
SQObject ExpectScalar ()
void EnumStatement ()
void TryCatchStatement ()
void FunctionExp (SQInteger ftype)
void ClassExp ()
void DelegateExpr ()
void DeleteExpr ()
void PrefixIncDec (SQInteger token)
void CreateFunction (SQObject &name)
void CleanStack (SQInteger stacksize)
void ResolveBreaks (SQFuncState *funcstate, SQInteger ntoresolve)
void ResolveContinues (SQFuncState *funcstate, SQInteger ntoresolve, SQInteger targetpos)
Static Public Member Functions
static void ThrowError (void *ud, const SQChar *s)
Private Attributes
SQInteger _token
SQFuncState * _fs
SQObjectPtr _sourcename
SQLexer _lex
bool _lineinfo
bool _raiseerror
SQInteger _debugline
SQInteger _debugop
ExpStateVec _expstates
SQChar * compilererror
jmp_buf _errorjmp
SQVM * _vm
Constructor & Destructor Documentation
SQCompiler::SQCompiler (SQVM * v, SQLEXREADFUNC rg, SQUserPointer up, const SQChar * sourcename, bool raiseerror, bool lineinfo) inline
References _lex, _lineinfo, _raiseerror, _sourcename, _vm, compilererror, NULL, and ThrowError().
Member Function Documentation
void SQCompiler::BIN_EXP (SQOpcode op, void(SQCompiler::*)(void) f, SQInteger op3 = 0) inline
References _fs, and Lex().
Referenced by BitwiseAndExp(), BitwiseOrExp(), BitwiseXorExp(), CompExp(), LogicalAndExp(), MultExp(), PlusExp(), and ShiftExp().
void SQCompiler::BitwiseAndExp () inline
References _token, BIN_EXP(), and CompExp().
Referenced by BitwiseXorExp().
void SQCompiler::BitwiseOrExp () inline
References _token, BIN_EXP(), and BitwiseXorExp().
Referenced by LogicalAndExp().
void SQCompiler::BitwiseXorExp () inline
References _token, BIN_EXP(), and BitwiseAndExp().
Referenced by BitwiseOrExp().
void SQCompiler::ClassExp () inline
References _fs, _token, Expect(), Expression(), Lex(), and ParseTableOrClass().
Referenced by ClassStatement(), and Factor().
void SQCompiler::ClassStatement () inline
References ExpState::_deref, _exst, _fs, ClassExp(), DEREF_FIELD, DEREF_NO_DEREF, EmitDerefOp(), Error(), Lex(), PopExpState(), PrefixedExpr(), and PushExpState().
Referenced by Statement().
void SQCompiler::CleanStack (SQInteger stacksize) inline
References _fs.
Referenced by Compile(), DoWhileStatement(), ForEachStatement(), ForStatement(), IfStatement(), TryCatchStatement(), and WhileStatement().
void SQCompiler::CommaExpr () inline
References _fs, _token, Expression(), and Lex().
Referenced by DelegateExpr(), DoWhileStatement(), Factor(), ForStatement(), IfStatement(), ParseTableOrClass(), Statement(), SwitchStatement(), and WhileStatement().
void SQCompiler::CompExp () inline
References _token, BIN_EXP(), and ShiftExp().
Referenced by BitwiseAndExp().
bool SQCompiler::Compile (SQObjectPtr & o) inline
References _debugline, _debugop, _errorjmp, _fs, _lex, _lineinfo, _raiseerror, _sourcename, _token, _vm, CleanStack(), compilererror, Lex(), NULL, OptionalSemicolon(), Statement(), and ThrowError().
Referenced by Compile().
void SQCompiler::CreateFunction (SQObject & name) inline
References _fs, _lex, _lineinfo, _sourcename, _token, _vm, Error(), Expect(), Expression(), Lex(), and Statement().
Referenced by FunctionExp(), FunctionStatement(), and ParseTableOrClass().
void SQCompiler::DelegateExpr () inline
References _fs, CommaExpr(), Expect(), and Lex().
Referenced by Factor().
void SQCompiler::DeleteExpr () inline
References ExpState::_deref, _exst, DEREF_FIELD, DEREF_NO_DEREF, Emit2ArgsOP(), Error(), Lex(), PopExpState(), PrefixedExpr(), and PushExpState().
Referenced by Factor().
void SQCompiler::DoWhileStatement () inline
References _fs, BEGIN_BREAKBLE_BLOCK, CleanStack(), CommaExpr(), END_BREAKBLE_BLOCK, Expect(), Lex(), and Statement().
Referenced by Statement().
void SQCompiler::Emit2ArgsOP (SQOpcode op, SQInteger p3 = 0) inline
References _fs.
Referenced by DeleteExpr(), EmitCompoundArith(), Factor(), FunctionStatement(), PrefixedExpr(), and PrefixIncDec().
void SQCompiler::EmitCompoundArith (SQInteger tok, bool deref) inline
References _fs, and Emit2ArgsOP().
Referenced by Expression().
void SQCompiler::EmitDerefOp (SQOpcode op) inline
References _fs.
Referenced by ClassStatement(), Expression(), and FunctionStatement().
void SQCompiler::EnumStatement () inline
References _fs, _token, _vm, Expect(), ExpectScalar(), and Lex().
Referenced by Statement().
void SQCompiler::Error (const SQChar * s, ...) inline
References _errorjmp, and compilererror.
Referenced by ClassStatement(), CreateFunction(), DeleteExpr(), Expect(), ExpectScalar(), Expression(), Factor(), FunctionCallArgs(), OptionalSemicolon(), PrefixedExpr(), Statement(), and ThrowError().
SQObject SQCompiler::Expect (SQInteger tok) inline
References _fs, _lex, _token, Error(), and Lex().
Referenced by ClassExp(), CreateFunction(), DelegateExpr(), DoWhileStatement(), EnumStatement(), Expression(), Factor(), ForEachStatement(), ForStatement(), FunctionExp(), FunctionStatement(), IfStatement(), LocalDeclStatement(), ParseTableOrClass(), PrefixedExpr(), Statement(), SwitchStatement(), TryCatchStatement(), and WhileStatement().
SQObject SQCompiler::ExpectScalar () inline
References _fs, _lex, _token, Error(), and Lex().
Referenced by EnumStatement(), and Statement().
ExpState SQCompiler::Expression (bool funcarg = false) inline
References _exst, _fs, _token, DEREF_FIELD, DEREF_NO_DEREF, EmitCompoundArith(), EmitDerefOp(), Error(), Expect(), Lex(), LogicalOrExp(), PopExpState(), and PushExpState().
Referenced by ClassExp(), CommaExpr(), CreateFunction(), Factor(), ForEachStatement(), FunctionCallArgs(), LocalDeclStatement(), ParseTableOrClass(), PrefixedExpr(), and SwitchStatement().
SQInteger SQCompiler::Factor () inline
References _exst, _fs, _lex, _token, ClassExp(), CommaExpr(), DelegateExpr(), DeleteExpr(), DEREF_FIELD, DEREF_NO_DEREF, Emit2ArgsOP(), Error(), Expect(), Expression(), FunctionExp(), Lex(), NeedGet(), ParseTableOrClass(), PrefixIncDec(), and UnaryOP().
Referenced by PrefixedExpr().
void SQCompiler::ForEachStatement () inline
References _fs, _token, BEGIN_BREAKBLE_BLOCK, CleanStack(), END_BREAKBLE_BLOCK, Expect(), Expression(), Lex(), and Statement().
Referenced by Statement().
void SQCompiler::ForStatement () inline
References _fs, _token, BEGIN_BREAKBLE_BLOCK, CleanStack(), CommaExpr(), END_BREAKBLE_BLOCK, Expect(), Lex(), LocalDeclStatement(), and Statement().
Referenced by Statement().
void SQCompiler::FunctionCallArgs () inline
References _fs, _token, Error(), Expression(), Lex(), and MoveIfCurrentTargetIsLocal().
Referenced by PrefixedExpr().
void SQCompiler::FunctionExp (SQInteger ftype) inline
References _fs, _null_, CreateFunction(), Expect(), and Lex().
Referenced by Factor().
void SQCompiler::FunctionStatement () inline
References _fs, _token, CreateFunction(), Emit2ArgsOP(), EmitDerefOp(), Expect(), and Lex().
Referenced by Statement().
void SQCompiler::IfStatement () inline
References _fs, _token, CleanStack(), CommaExpr(), Expect(), Lex(), OptionalSemicolon(), and Statement().
Referenced by Statement().
bool SQCompiler::IsDerefToken (SQInteger tok) inline
bool SQCompiler::IsEndOfStatement () inline
References _lex, and _token.
Referenced by OptionalSemicolon(), PrefixedExpr(), and Statement().
void SQCompiler::Lex () inline
References _lex, and _token.
Referenced by BIN_EXP(), ClassExp(), ClassStatement(), CommaExpr(), Compile(), CreateFunction(), DelegateExpr(), DeleteExpr(), DoWhileStatement(), EnumStatement(), Expect(), ExpectScalar(), Expression(), Factor(), ForEachStatement(), ForStatement(), FunctionCallArgs(), FunctionExp(), FunctionStatement(), IfStatement(), LocalDeclStatement(), LogicalAndExp(), LogicalOrExp(), OptionalSemicolon(), ParseTableOrClass(), PrefixedExpr(), PrefixIncDec(), Statement(), SwitchStatement(), TryCatchStatement(), UnaryOP(), and WhileStatement().
void SQCompiler::LocalDeclStatement () inline
References _fs, _token, Expect(), Expression(), and Lex().
Referenced by ForStatement(), and Statement().
void SQCompiler::LogicalAndExp () inline
References _fs, _token, BIN_EXP(), BitwiseOrExp(), and Lex().
Referenced by LogicalOrExp().
void SQCompiler::LogicalOrExp () inline
References _fs, _token, Lex(), and LogicalAndExp().
Referenced by Expression().
void SQCompiler::MoveIfCurrentTargetIsLocal () inline
References _fs.
Referenced by FunctionCallArgs().
void SQCompiler::MultExp () inline
References _token, BIN_EXP(), and PrefixedExpr().
Referenced by PlusExp().
bool SQCompiler::NeedGet () inline
References _exst, and _token.
Referenced by Factor(), and PrefixedExpr().
void SQCompiler::OptionalSemicolon () inline
References _token, Error(), IsEndOfStatement(), and Lex().
Referenced by Compile(), IfStatement(), Statement(), and Statements().
void SQCompiler::ParseTableOrClass (SQInteger separator, SQInteger terminator = '}') inline
References _fs, _token, CommaExpr(), CreateFunction(), Expect(), Expression(), and Lex().
Referenced by ClassExp(), and Factor().
void SQCompiler::PlusExp () inline
References _token, BIN_EXP(), and MultExp().
Referenced by ShiftExp().
ExpState SQCompiler::PopExpState () inline
References _expstates.
Referenced by ClassStatement(), DeleteExpr(), Expression(), and PrefixIncDec().
void SQCompiler::PrefixedExpr () inline
References _exst, _fs, _lex, _token, DEREF_FIELD, DEREF_NO_DEREF, Emit2ArgsOP(), Error(), Expect(), Expression(), Factor(), FunctionCallArgs(), IsEndOfStatement(), Lex(), and NeedGet().
Referenced by ClassStatement(), DeleteExpr(), MultExp(), PrefixIncDec(), and UnaryOP().
void SQCompiler::PrefixIncDec (SQInteger token) inline
References ExpState::_deref, _exst, _fs, DEREF_FIELD, Emit2ArgsOP(), Lex(), PopExpState(), PrefixedExpr(), and PushExpState().
Referenced by Factor().
void SQCompiler::PushExpState () inline
References _expstates.
Referenced by ClassStatement(), DeleteExpr(), Expression(), and PrefixIncDec().
void SQCompiler::ResolveBreaks (SQFuncState * funcstate, SQInteger ntoresolve) inline
Referenced by SwitchStatement().
void SQCompiler::ResolveContinues (SQFuncState * funcstate, SQInteger ntoresolve, SQInteger targetpos) inline
void SQCompiler::ShiftExp () inline
References _token, BIN_EXP(), and PlusExp().
Referenced by CompExp().
void SQCompiler::Statement () inline
References _fs, _lex, _lineinfo, _token, _vm, ClassStatement(), CommaExpr(), DoWhileStatement(), EnumStatement(), Error(), Expect(), ExpectScalar(), ForEachStatement(), ForStatement(), FunctionStatement(), IfStatement(), IsEndOfStatement(), Lex(), LocalDeclStatement(), OptionalSemicolon(), Statements(), SwitchStatement(), TryCatchStatement(), and WhileStatement().
Referenced by Compile(), CreateFunction(), DoWhileStatement(), ForEachStatement(), ForStatement(), IfStatement(), Statements(), TryCatchStatement(), and WhileStatement().
void SQCompiler::Statements () inline
References _lex, _token, OptionalSemicolon(), and Statement().
Referenced by Statement(), and SwitchStatement().
void SQCompiler::SwitchStatement () inline
References _fs, _token, CommaExpr(), Expect(), Expression(), Lex(), ResolveBreaks(), and Statements().
Referenced by Statement().
static void SQCompiler::ThrowError (void * ud, const SQChar * s) inline static
References Error().
Referenced by Compile(), and SQCompiler().
void SQCompiler::TryCatchStatement () inline
References _fs, CleanStack(), Expect(), Lex(), and Statement().
Referenced by Statement().
void SQCompiler::UnaryOP (SQOpcode op) inline
References _fs, Lex(), and PrefixedExpr().
Referenced by Factor().
void SQCompiler::WhileStatement () inline
References _fs, BEGIN_BREAKBLE_BLOCK, CleanStack(), CommaExpr(), END_BREAKBLE_BLOCK, Expect(), Lex(), and Statement().
Referenced by Statement().
Member Data Documentation
SQInteger SQCompiler::_debugline private
Referenced by Compile().
SQInteger SQCompiler::_debugop private
Referenced by Compile().
jmp_buf SQCompiler::_errorjmp private
Referenced by Compile(), and Error().
ExpStateVec SQCompiler::_expstates private
Referenced by PopExpState(), and PushExpState().
SQFuncState* SQCompiler::_fs private
Referenced by BIN_EXP(), ClassExp(), ClassStatement(), CleanStack(), CommaExpr(), Compile(), CreateFunction(), DelegateExpr(), DoWhileStatement(), Emit2ArgsOP(), EmitCompoundArith(), EmitDerefOp(), EnumStatement(), Expect(), ExpectScalar(), Expression(), Factor(), ForEachStatement(), ForStatement(), FunctionCallArgs(), FunctionExp(), FunctionStatement(), IfStatement(), LocalDeclStatement(), LogicalAndExp(), LogicalOrExp(), MoveIfCurrentTargetIsLocal(), ParseTableOrClass(), PrefixedExpr(), PrefixIncDec(), Statement(), SwitchStatement(), TryCatchStatement(), UnaryOP(), and WhileStatement().
SQLexer SQCompiler::_lex private
Referenced by Compile(), CreateFunction(), Expect(), ExpectScalar(), Factor(), IsEndOfStatement(), Lex(), PrefixedExpr(), SQCompiler(), Statement(), and Statements().
bool SQCompiler::_lineinfo private
Referenced by Compile(), CreateFunction(), SQCompiler(), and Statement().
bool SQCompiler::_raiseerror private
Referenced by Compile(), and SQCompiler().
SQObjectPtr SQCompiler::_sourcename private
Referenced by Compile(), CreateFunction(), and SQCompiler().
SQInteger SQCompiler::_token private
Referenced by BitwiseAndExp(), BitwiseOrExp(), BitwiseXorExp(), ClassExp(), CommaExpr(), CompExp(), Compile(), CreateFunction(), EnumStatement(), Expect(), ExpectScalar(), Expression(), Factor(), ForEachStatement(), ForStatement(), FunctionCallArgs(), FunctionStatement(), IfStatement(), IsEndOfStatement(), Lex(), LocalDeclStatement(), LogicalAndExp(), LogicalOrExp(), MultExp(), NeedGet(), OptionalSemicolon(), ParseTableOrClass(), PlusExp(), PrefixedExpr(), ShiftExp(), Statement(), Statements(), and SwitchStatement().
SQVM* SQCompiler::_vm private
Referenced by Compile(), CreateFunction(), EnumStatement(), SQCompiler(), and Statement().
SQChar* SQCompiler::compilererror private
Referenced by Compile(), Error(), and SQCompiler().
The documentation for this class was generated from the following file:
sqcompiler.cpp