Code::Blocks: GdbCmd_TooltipEvaluation Class Reference
GdbCmd_TooltipEvaluation Class Reference
Command to display a tooltip about a variables value.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_TooltipEvaluation (DebuggerDriver *driver, const wxString &what, const wxRect &tiprect, const wxString &w_type=wxEmptyString, const wxString &address=wxEmptyString)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
wxRect m_WinRect
wxString m_What
wxString m_Type
wxString m_Address
wxString m_ParseFunc
bool m_autoDereferenced
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to display a tooltip about a variables value.
Definition at line 930 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_TooltipEvaluation()
GdbCmd_TooltipEvaluation::GdbCmd_TooltipEvaluation (DebuggerDriver * driver, const wxString & what, const wxRect & tiprect, const wxString & w_type = wxEmptyString, const wxString & address = wxEmptyString) inline
Parameters
what The variable to evaluate.
win A pointer to the tip window pointer.
tiprect The tip window's rect.
Definition at line 943 of file gdb_commands.h.
References cbC2U(), cbU2C(), DebuggerDriver::DebugLog(), IsPointerType(), DebuggerCmd::m_Cmd, and DebuggerCmd::m_pDriver.
Member Function Documentation
ParseOutput()
void GdbCmd_TooltipEvaluation::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 989 of file gdb_commands.h.
References DebuggerGDB::AddWatchNoUpdate(), cbC2U(), cbU2C(), DebuggerDriver::DebugLog(), Manager::Get(), DebuggerDriver::GetDebugger(), DebuggerCmd::m_pDriver, and ParseGDBWatchValue().
Member Data Documentation
m_Address
wxString GdbCmd_TooltipEvaluation::m_Address private
Definition at line 935 of file gdb_commands.h.
m_autoDereferenced
bool GdbCmd_TooltipEvaluation::m_autoDereferenced private
Definition at line 937 of file gdb_commands.h.
m_ParseFunc
wxString GdbCmd_TooltipEvaluation::m_ParseFunc private
Definition at line 936 of file gdb_commands.h.
m_Type
wxString GdbCmd_TooltipEvaluation::m_Type private
Definition at line 934 of file gdb_commands.h.
m_What
wxString GdbCmd_TooltipEvaluation::m_What private
Definition at line 933 of file gdb_commands.h.
m_WinRect
wxRect GdbCmd_TooltipEvaluation::m_WinRect private
Definition at line 932 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h