Code::Blocks: CdbCmd_AddBreakpoint Class Reference
CdbCmd_AddBreakpoint Class Reference
Command to add a breakpoint.
#include <cdb_commands.h>
Public Member Functions
CdbCmd_AddBreakpoint (DebuggerDriver *driver, cb::shared_ptr< DebuggerBreakpoint > bp)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Public Attributes
cb::shared_ptr< DebuggerBreakpoint > m_BP
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Static Private Attributes
static int m_lastIndex = 1
Additional Inherited Members
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to add a breakpoint.
Definition at line 244 of file cdb_commands.h.
Constructor & Destructor Documentation
CdbCmd_AddBreakpoint()
CdbCmd_AddBreakpoint::CdbCmd_AddBreakpoint (DebuggerDriver * driver, cb::shared_ptr< DebuggerBreakpoint > bp) inline
Parameters
bp The breakpoint to set.
Definition at line 249 of file cdb_commands.h.
References _T, wxString::Format(), DebuggerCmd::m_Cmd, and QuoteStringIfNeeded().
Member Function Documentation
ParseOutput()
void CdbCmd_AddBreakpoint::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 272 of file cdb_commands.h.
References _T, GetArrayFromString(), wxArrayString::GetCount(), DebuggerDriver::Log(), and DebuggerCmd::m_pDriver.
Member Data Documentation
m_BP
cb::shared_ptr<DebuggerBreakpoint> CdbCmd_AddBreakpoint::m_BP
Definition at line 287 of file cdb_commands.h.
m_lastIndex
int CdbCmd_AddBreakpoint::m_lastIndex = 1 static private
Definition at line 246 of file cdb_commands.h.
The documentation for this class was generated from the following file:
cdb_commands.h