Code::Blocks: CodeBlocksApp Class Reference
CodeBlocksApp Class Reference
#include <app.h>
Public Member Functions
virtual bool OnInit ()
virtual int OnExit ()
virtual int OnRun ()
wxString GetAppPath () const
int ParseCmdLine (MainFrame *handlerFrame, const wxString &CmdLine=wxEmptyString)
void OnAppActivate (wxActivateEvent &event)
bool OnCmdLineParsed (wxCmdLineParser &parser)
void OnFatalException ()
void LoadDelayedFiles (MainFrame *frame)
void SetAutoFile (wxString &file)
void AttachDebugger ()
void AddFileToOpenDelayed (const wxString &filename)
Public Member Functions inherited from wxApp
wxApp ()
virtual ~wxApp ()
virtual wxVideoMode GetDisplayMode () const
bool GetExitOnFrameDelete () const
virtual wxLayoutDirection GetLayoutDirection () const
bool GetUseBestVisual () const
virtual wxWindow * GetTopWindow () const
virtual bool IsActive () const
virtual bool SafeYield (wxWindow *win, bool onlyIfNeeded)
virtual bool SafeYieldFor (wxWindow *win, long eventsToProcess)
bool ProcessMessage (WXMSG *msg)
virtual bool SetDisplayMode (const wxVideoMode &info)
void SetExitOnFrameDelete (bool flag)
virtual bool SetNativeTheme (const wxString &theme)
void SetTopWindow (wxWindow *window)
void SetUseBestVisual (bool flag, bool forceTrueColour=false)
virtual void MacNewFile ()
virtual void MacOpenFiles (const wxArrayString &fileNames)
virtual void MacOpenFile (const wxString &fileName)
virtual void MacOpenURL (const wxString &url)
virtual void MacPrintFile (const wxString &fileName)
virtual void MacReopenApp ()
virtual bool OSXIsGUIApplication ()
virtual ~wxAppConsole ()
bool Yield (bool onlyIfNeeded=false)
void SetCLocale ()
virtual int MainLoop ()
virtual void ExitMainLoop ()
virtual int FilterEvent (wxEvent &event)
wxEventLoopBase * GetMainLoop () const
virtual void HandleEvent (wxEvtHandler *handler, wxEventFunction func, wxEvent &event) const
virtual bool UsesEventLoop () const
virtual void ProcessPendingEvents ()
void DeletePendingEvents ()
bool HasPendingEvents () const
void SuspendProcessingOfPendingEvents ()
void ResumeProcessingOfPendingEvents ()
void ScheduleForDestruction (wxObject *object)
bool IsScheduledForDestruction (wxObject *object) const
virtual void OnAssertFailure (const wxChar *file, int line, const wxChar *func, const wxChar *cond, const wxChar *msg)
virtual bool OnCmdLineError (wxCmdLineParser &parser)
virtual bool OnCmdLineHelp (wxCmdLineParser &parser)
virtual void OnEventLoopEnter (wxEventLoopBase *loop)
virtual void OnEventLoopExit (wxEventLoopBase *loop)
virtual bool OnExceptionInMainLoop ()
virtual void OnInitCmdLine (wxCmdLineParser &parser)
virtual void OnUnhandledException ()
wxString GetAppDisplayName () const
wxString GetAppName () const
wxString GetClassName () const
wxAppTraits * GetTraits ()
const wxString & GetVendorDisplayName () const
const wxString & GetVendorName () const
void SetAppDisplayName (const wxString &name)
void SetAppName (const wxString &name)
void SetClassName (const wxString &name)
void SetVendorDisplayName (const wxString &name)
void SetVendorName (const wxString &name)
virtual void QueueEvent (wxEvent *event)
virtual void AddPendingEvent (const wxEvent &event)
virtual bool ProcessEvent (wxEvent &event)
virtual void SetNextHandler (wxEvtHandler *handler)
virtual void SetPreviousHandler (wxEvtHandler *handler)
wxEventFilter ()
virtual ~wxEventFilter ()
Protected Member Functions
void OnBatchBuildDone (CodeBlocksEvent &event)
void OnTBIconLeftDown (wxTaskBarIconEvent &event)
bool LoadConfig ()
void InitDebugConsole ()
void InitExceptionHandler ()
bool InitXRCStuff ()
MainFrame * InitFrame ()
void CheckVersion ()
void InitLocale ()
int BatchJob ()
Protected Member Functions inherited from wxApp
virtual wxAppTraits * CreateTraits ()
Protected Attributes
wxLocale m_locale
wxArrayString m_DelayedFilesToOpen
Private Member Functions
void SetupPersonality (const wxString &personality)
void InitAssociations ()
Private Attributes
wxString m_Prefix
wxString m_UserDataDir
wxString m_BatchTarget
wxString m_Script
wxString m_AutoFile
wxString m_DebuggerAttach
wxString m_DebuggerConfig
wxScrollingDialog * m_pBatchBuildDialog
MainFrame * m_Frame
wxSingleInstanceChecker * m_pSingleInstance
bool m_Batch
bool m_BatchNotify
bool m_BatchWindowAutoClose
bool m_Build
bool m_ReBuild
bool m_Clean
bool m_HasProject
bool m_HasWorkSpace
bool m_Splash
bool m_HasDebugLog
bool m_CrashHandler
bool m_SafeMode
bool m_DDE
bool m_Assocs
int m_BatchExitCode
Additional Inherited Members
Static Public Member Functions inherited from wxApp
static void SetInstance (wxAppConsole *app)
static wxAppConsole * GetInstance ()
static bool IsMainLoopRunning ()
Public Attributes inherited from wxApp
int argc
wxChar ** argv
Detailed Description
Definition at line 107 of file app.h.
Member Function Documentation
AddFileToOpenDelayed()
void CodeBlocksApp::AddFileToOpenDelayed (const wxString & filename)
Definition at line 1460 of file app.cpp.
Referenced by GetResourcesDir().
AttachDebugger()
void CodeBlocksApp::AttachDebugger ()
Definition at line 1289 of file app.cpp.
References _(), cbDebuggerPlugin::AttachToProcess(), wxString::empty(), wxString::find(), wxString::Format(), Manager::Get(), DebuggerManager::GetAllDebuggers(), DebuggerManager::PluginData::GetConfigurations(), Manager::GetDebuggerManager(), cbDebuggerPlugin::GetGUIName(), Manager::GetLogManager(), cbDebuggerPlugin::GetSettingsName(), LogManager::Log(), LogManager::LogError(), wxApp::MacOpenFile(), wxApp::MacPrintFile(), wxString::npos, cbDebuggerPlugin::SetActiveConfig(), wxString::substr(), wxString::wx_str(), and wxT.
Referenced by GetResourcesDir().
BatchJob()
int CodeBlocksApp::BatchJob () protected
Definition at line 914 of file app.cpp.
References _(), _T, cbCompilerPlugin::Build(), cbCompilerPlugin::BuildWorkspace(), cbCompilerPlugin::Clean(), cbCompilerPlugin::CleanWorkspace(), Manager::Get(), cbProject::GetActiveBuildTarget(), ProjectManager::GetActiveProject(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), PluginManager::GetFirstCompiler(), Manager::GetPluginManager(), Manager::GetProjectManager(), CompileTargetBase::GetTitle(), wxString::Matches(), PlaceWindow(), cbCompilerPlugin::Rebuild(), cbCompilerPlugin::RebuildWorkspace(), wxTaskBarIcon::RemoveIcon(), cbProject::SelectTarget(), wxTaskBarIcon::SetIcon(), wxFileNameFromPath(), wxICON, and wxID_OK.
CheckVersion()
void CodeBlocksApp::CheckVersion () protected
Definition at line 515 of file app.cpp.
References _T, appglobals::AppActualVersion, Manager::Get(), Manager::GetConfigManager(), ConfigManager::Read(), and ConfigManager::Write().
GetAppPath()
wxString CodeBlocksApp::GetAppPath () const
Definition at line 1065 of file app.cpp.
References _T, wxFileName::GetPath(), and wxString::IsEmpty().
InitAssociations()
void CodeBlocksApp::InitAssociations () private
Definition at line 425 of file app.cpp.
References _T, ASC_ASSOC_DLG_NO_DONT_ASK, ASC_ASSOC_DLG_NO_ONLY_NOW, ASC_ASSOC_DLG_YES_ALL_FILES, ASC_ASSOC_DLG_YES_C_FILES, Associations::Check(), Manager::Get(), Manager::GetConfigManager(), PlaceWindow(), ConfigManager::ReadBool(), Associations::SetAll(), Associations::SetCore(), wxDialog::ShowModal(), and ConfigManager::Write().
InitDebugConsole()
void CodeBlocksApp::InitDebugConsole () protected
Definition at line 457 of file app.cpp.
InitExceptionHandler()
void CodeBlocksApp::InitExceptionHandler () protected
Definition at line 472 of file app.cpp.
InitFrame()
MainFrame * CodeBlocksApp::InitFrame () protected
Definition at line 501 of file app.cpp.
References wxUpdateUIEvent::SetUpdateInterval().
InitLocale()
void CodeBlocksApp::InitLocale () protected
Definition at line 524 of file app.cpp.
References _T, wxLocale::AddCatalogLookupPathPrefix(), wxString::Alloc(), wxString::Append(), wxLanguageInfo::CanonicalName, wxLocale::FindLanguageInfo(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::GetDataFolder(), wxDir::GetFirst(), wxLocale::GetLanguageInfo(), wxDir::GetNext(), wxDir::IsOpened(), wxLanguageInfo::Language, wxString::length(), ConfigManager::Read(), ConfigManager::ReadBool(), wxDIR_FILES, wxDirExists(), and wxLANGUAGE_DEFAULT.
InitXRCStuff()
bool CodeBlocksApp::InitXRCStuff () protected
Definition at line 479 of file app.cpp.
References _T, appglobals::AppName, cbMessageBox(), Manager::LoadResource(), wxString::Printf(), and ConfigManager::ReadDataPath().
LoadConfig()
bool CodeBlocksApp::LoadConfig () protected
Referenced by IMPLEMENT_APP().
LoadDelayedFiles()
void CodeBlocksApp::LoadDelayedFiles (MainFrame * frame)
Definition at line 1240 of file app.cpp.
References _T, wxString::empty(), wxString::Find(), Manager::Get(), EditorManager::GetEditor(), Manager::GetEditorManager(), wxFileName::GetFullPath(), EditorBase::GotoLine(), wxString::Mid(), wxFileName::Normalize(), wxString::npos, MainFrame::Open(), wxString::Remove(), wxString::ToLong(), and wxNOT_FOUND.
Referenced by GetResourcesDir().
OnAppActivate()
void CodeBlocksApp::OnAppActivate (wxActivateEvent & event)
Definition at line 1409 of file app.cpp.
References _T, cbEVT_APP_ACTIVATED, cbEVT_APP_DEACTIVATED, Manager::Get(), wxActivateEvent::GetActive(), EditorManager::GetBuiltinActiveEditor(), Manager::GetConfigManager(), cbEditor::GetControl(), Manager::GetEditorManager(), EditorManager::GetNotebook(), idEditorManagerCheckFiles, Manager::IsAppShuttingDown(), Manager::ProcessEvent(), ConfigManager::ReadBool(), and wxPostEvent().
OnBatchBuildDone()
void CodeBlocksApp::OnBatchBuildDone (CodeBlocksEvent & event) protected
Definition at line 1018 of file app.cpp.
References _(), appglobals::AppName, cbMessageBox(), wxString::Format(), cbCompilerPlugin::GetExitCode(), wxBell(), wxICON_INFORMATION, wxICON_WARNING, and wxID_OK.
Referenced by OnInit().
OnCmdLineParsed()
bool CodeBlocksApp::OnCmdLineParsed (wxCmdLineParser & parser) virtual
Reimplemented from wxApp.
Definition at line 894 of file app.cpp.
References wxApp::OnCmdLineParsed().
OnExit()
int CodeBlocksApp::OnExit () virtual
Reimplemented from wxApp.
Definition at line 820 of file app.cpp.
References Manager::Free(), and wxTheClipboard.
OnFatalException()
void CodeBlocksApp::OnFatalException () virtual
Reimplemented from wxApp.
Definition at line 899 of file app.cpp.
References _(), wxDebugReport::AddAll(), appglobals::AppName, cbMessageBox(), wxString::Format(), wxDebugReport::Process(), and wxDebugReportPreviewStd::Show().
OnInit()
bool CodeBlocksApp::OnInit () virtual
Reimplemented from wxApp.
Definition at line 572 of file app.cpp.
References _(), _T, wxFileSystem::AddHandler(), appglobals::AppActualVersionVerb, appglobals::AppBuildTimestamp, appglobals::AppName, cbC2U(), cbEVT_APP_STARTUP_DONE, cbEVT_COMPILER_FINISHED, cbMessageBox(), DDE_SERVICE, DDE_TOPIC, ScriptingManager::DisplayErrors(), wxLog::EnableLogging(), F(), wxString::Format(), wxCmdLineParser::Found(), wxXmlResource::Get(), Manager::Get(), Manager::GetCmdLineParser(), Manager::GetConfigManager(), LoaderBase::GetData(), Manager::GetFileManager(), Manager::GetLogManager(), Manager::GetProjectManager(), Manager::GetScriptingManager(), ConfigManager::GetTempFolder(), wxXmlResource::InitAllHandlers(), wxXmlResource::InsertHandler(), wxString::IsEmpty(), FileManager::Load(), ScriptingManager::LoadBuffer(), ScriptingManager::LoadScript(), ProjectManager::LoadWorkspace(), ConfigManager::LocateDataFile(), LogManager::Log(), OnBatchBuildDone(), Manager::ProcessEvent(), Manager::ProcessPendingEvents(), ConfigManager::ReadBool(), Manager::RegisterEventSink(), wxString::Replace(), sdScriptsGlobal, sdScriptsUser, wxMessageOutput::Set(), Manager::SetAppStartedUp(), Manager::SetBatchBuild(), wxCmdLineParser::SetDesc(), PluginManager::SetSafeMode(), cbException::ShowErrorMessage(), MainFrame::ShowTips(), MainFrame::StartupDone(), wxCmdLineParser::Usage(), ProjectManager::WorkspaceChanged(), wxGetUserId(), wxHandleFatalExceptions(), wxICON_ERROR, wxInitAllImageHandlers(), wxOK, wxSafeShowMessage(), wxT, and wxTheClipboard.
OnRun()
int CodeBlocksApp::OnRun () virtual
Reimplemented from wxApp.
Definition at line 865 of file app.cpp.
References _(), cbC2U(), ScriptingManager::DisplayErrors(), EnableLFH(), Manager::Get(), Manager::GetScriptingManager(), wxApp::OnRun(), cbException::ShowErrorMessage(), and wxSafeShowMessage().
OnTBIconLeftDown()
void CodeBlocksApp::OnTBIconLeftDown (wxTaskBarIconEvent & event) protected
Definition at line 1055 of file app.cpp.
ParseCmdLine()
int CodeBlocksApp::ParseCmdLine (MainFrame * handlerFrame, const wxString & CmdLine = wxEmptyString)
Definition at line 1107 of file app.cpp.
References _T, LogManager::app_log, LogManager::debug_log, wxLog::EnableLogging(), wxFile::Exists(), FileTypeOf(), wxCmdLineParser::Found(), ftCodeBlocksProject, ftCodeBlocksWorkspace, Manager::Get(), Manager::GetCmdLineParser(), Manager::GetLogManager(), wxCmdLineParser::GetParam(), wxCmdLineParser::GetParamCount(), wxString::IsEmpty(), wxFileName::Normalize(), wxCmdLineParser::Parse(), wxCmdLineParser::SetCmdLine(), and LogManager::SetLog().
Referenced by GetResourcesDir().
SetAutoFile()
void CodeBlocksApp::SetAutoFile (wxString & file)
Definition at line 1102 of file app.cpp.
Referenced by GetResourcesDir().
SetupPersonality()
void CodeBlocksApp::SetupPersonality (const wxString & personality) private
Definition at line 1223 of file app.cpp.
References _(), _T, wxString::CmpNoCase(), Manager::Get(), Manager::GetPersonalityManager(), wxSingleChoiceDialog::GetStringSelection(), PersonalityManager::SetPersonality(), wxSingleChoiceDialog::ShowModal(), and wxID_OK.
Member Data Documentation
m_Assocs
bool CodeBlocksApp::m_Assocs private
Definition at line 174 of file app.h.
m_AutoFile
wxString CodeBlocksApp::m_AutoFile private
Definition at line 149 of file app.h.
m_Batch
bool CodeBlocksApp::m_Batch private
Definition at line 157 of file app.h.
m_BatchExitCode
int CodeBlocksApp::m_BatchExitCode private
Definition at line 176 of file app.h.
m_BatchNotify
bool CodeBlocksApp::m_BatchNotify private
Definition at line 158 of file app.h.
m_BatchTarget
wxString CodeBlocksApp::m_BatchTarget private
Definition at line 147 of file app.h.
m_BatchWindowAutoClose
bool CodeBlocksApp::m_BatchWindowAutoClose private
Definition at line 159 of file app.h.
m_Build
bool CodeBlocksApp::m_Build private
Definition at line 160 of file app.h.
m_Clean
bool CodeBlocksApp::m_Clean private
Definition at line 162 of file app.h.
m_CrashHandler
bool CodeBlocksApp::m_CrashHandler private
Definition at line 167 of file app.h.
m_DDE
bool CodeBlocksApp::m_DDE private
Definition at line 172 of file app.h.
m_DebuggerAttach
wxString CodeBlocksApp::m_DebuggerAttach private
Definition at line 150 of file app.h.
m_DebuggerConfig
wxString CodeBlocksApp::m_DebuggerConfig private
Definition at line 151 of file app.h.
m_DelayedFilesToOpen
wxArrayString CodeBlocksApp::m_DelayedFilesToOpen protected
Definition at line 140 of file app.h.
m_Frame
MainFrame* CodeBlocksApp::m_Frame private
Definition at line 154 of file app.h.
m_HasDebugLog
bool CodeBlocksApp::m_HasDebugLog private
Definition at line 166 of file app.h.
m_HasProject
bool CodeBlocksApp::m_HasProject private
Definition at line 163 of file app.h.
m_HasWorkSpace
bool CodeBlocksApp::m_HasWorkSpace private
Definition at line 164 of file app.h.
m_locale
wxLocale CodeBlocksApp::m_locale protected
Definition at line 139 of file app.h.
m_pBatchBuildDialog
wxScrollingDialog* CodeBlocksApp::m_pBatchBuildDialog private
Definition at line 153 of file app.h.
m_Prefix
wxString CodeBlocksApp::m_Prefix private
Definition at line 145 of file app.h.
m_pSingleInstance
wxSingleInstanceChecker* CodeBlocksApp::m_pSingleInstance private
Definition at line 155 of file app.h.
m_ReBuild
bool CodeBlocksApp::m_ReBuild private
Definition at line 161 of file app.h.
m_SafeMode
bool CodeBlocksApp::m_SafeMode private
Definition at line 168 of file app.h.
m_Script
wxString CodeBlocksApp::m_Script private
Definition at line 148 of file app.h.
m_Splash
bool CodeBlocksApp::m_Splash private
Definition at line 165 of file app.h.
m_UserDataDir
wxString CodeBlocksApp::m_UserDataDir private
Definition at line 146 of file app.h.
The documentation for this class was generated from the following files:
app.h
app.cpp