Code::Blocks: UserVariableManager Class Reference
UserVariableManager Class Reference
#include <uservarmanager.h>
Public Member Functions
UserVariableManager ()
wxString Replace (const wxString &variable)
wxString GetVariable (wxString old=wxEmptyString)
void Preempt (const wxString &variable)
void Arrogate ()
bool Exists (const wxString &variable) const
void Configure ()
void Migrate ()
UserVariableManager & operator= (cb_unused const UserVariableManager &rhs)
Private Member Functions
UserVariableManager (cb_unused const UserVariableManager &rhs)
Private Attributes
ConfigManager * m_CfgMan
wxString m_ActiveSet
wxArrayString m_Preempted
Friends
class Manager
class Mgr< UserVariableManager >
class MacrosManager
Additional Inherited Members
Static Public Member Functions inherited from Mgr< UserVariableManager >
static bool Valid ()
static UserVariableManager * Get ()
static void Free ()
Protected Member Functions inherited from Mgr< UserVariableManager >
Mgr ()
virtual ~Mgr ()
Detailed Description
Definition at line 17 of file uservarmanager.h.
Constructor & Destructor Documentation
UserVariableManager() [1/2]
UserVariableManager::UserVariableManager ()
Definition at line 268 of file uservarmanager.cpp.
References Manager::Get(), and Manager::GetConfigManager().
UserVariableManager() [2/2]
UserVariableManager::UserVariableManager (cb_unused const UserVariableManager & rhs) private
Member Function Documentation
Arrogate()
void UserVariableManager::Arrogate ()
Definition at line 234 of file uservarmanager.cpp.
References UsrGlblMgrEditDialog::AddVar(), InfoWindow::Display(), PlaceWindow(), and wxScrollingDialog::ShowModal().
Referenced by ProjectManager::EndLoadingProject(), and ProjectManager::EndLoadingWorkspace().
Configure()
void UserVariableManager::Configure ()
Definition at line 143 of file uservarmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), m_ActiveSet, PlaceWindow(), ConfigManager::Read(), and wxScrollingDialog::ShowModal().
Referenced by GetUserVariableDialog::OnConfig(), and MainFrame::OnGlobalUserVars().
Exists()
bool UserVariableManager::Exists (const wxString & variable) const
Definition at line 225 of file uservarmanager.cpp.
References cSets().
Referenced by ScriptBindings::RegisterBindings().
GetVariable()
wxString UserVariableManager::GetVariable (wxString old = wxEmptyString)
Definition at line 308 of file uservarmanager.cpp.
References GetUserVariableDialog::GetVariable(), GetUserVariableDialog::OnActivated(), GetUserVariableDialog::OnCancel(), GetUserVariableDialog::OnConfig(), GetUserVariableDialog::OnOK(), and wxScrollingDialog::ShowModal().
Referenced by EditPathDlg::OnOther().
Migrate()
void UserVariableManager::Migrate ()
Definition at line 274 of file uservarmanager.cpp.
References ConfigManager::Delete(), ConfigManager::EnumerateKeys(), ConfigManager::EnumerateSubPaths(), ConfigManager::Exists(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::Read(), and ConfigManager::Write().
operator=()
UserVariableManager& UserVariableManager::operator= (cb_unused const UserVariableManager & rhs) inline
Definition at line 41 of file uservarmanager.h.
References cbThrow.
Preempt()
void UserVariableManager::Preempt (const wxString & variable)
Definition at line 211 of file uservarmanager.cpp.
References cSets().
Replace()
wxString UserVariableManager::Replace (const wxString & variable)
Definition at line 152 of file uservarmanager.cpp.
References UsrGlblMgrEditDialog::AddVar(), cBase(), cBin(), cInclude(), cLib(), cObj(), cSets(), InfoWindow::Display(), Manager::Get(), Manager::GetProjectManager(), ProjectManager::IsLoading(), PlaceWindow(), and wxScrollingDialog::ShowModal().
Friends And Related Function Documentation
MacrosManager
friend class MacrosManager friend
Definition at line 21 of file uservarmanager.h.
Manager
friend class Manager friend
Definition at line 19 of file uservarmanager.h.
Mgr< UserVariableManager >
friend class Mgr< UserVariableManager > friend
Definition at line 20 of file uservarmanager.h.
Member Data Documentation
m_ActiveSet
wxString UserVariableManager::m_ActiveSet private
Definition at line 24 of file uservarmanager.h.
Referenced by Configure().
m_CfgMan
ConfigManager* UserVariableManager::m_CfgMan private
Definition at line 23 of file uservarmanager.h.
m_Preempted
wxArrayString UserVariableManager::m_Preempted private
Definition at line 25 of file uservarmanager.h.
The documentation for this class was generated from the following files:
uservarmanager.h
uservarmanager.cpp