Code::Blocks: PluginManager Class Reference
PluginManager Class Reference
PluginManager manages plugins.
#include <pluginmanager.h>
Classes
struct PluginRegistration
Public Types
typedef std::vector< cbCompilerPlugin * > CompilerPlugins
Public Member Functions
void CreateMenu (wxMenuBar *menuBar)
void ReleaseMenu (wxMenuBar *menuBar)
void RegisterPlugin (const wxString &name, CreatePluginProc createProc, FreePluginProc freeProc, PluginSDKVersionProc versionProc)
int ScanForPlugins (const wxString &path)
bool LoadPlugin (const wxString &pluginName)
void LoadAllPlugins ()
void UnloadAllPlugins ()
void UnloadPlugin (cbPlugin *plugin)
int ExecutePlugin (const wxString &pluginName)
bool AttachPlugin (cbPlugin *plugin, bool ignoreSafeMode=false)
bool DetachPlugin (cbPlugin *plugin)
bool InstallPlugin (const wxString &pluginName, bool forAllUsers=true, bool askForConfirmation=true)
bool UninstallPlugin (cbPlugin *plugin, bool removeFiles=true)
bool ExportPlugin (cbPlugin *plugin, const wxString &filename)
const PluginInfo * GetPluginInfo (const wxString &pluginName)
const PluginInfo * GetPluginInfo (cbPlugin *plugin)
const PluginElementsArray & GetPlugins () const
PluginElement * FindElementByName (const wxString &pluginName)
cbPlugin * FindPluginByName (const wxString &pluginName)
cbPlugin * FindPluginByFileName (const wxString &pluginFileName)
const CompilerPlugins & GetCompilerPlugins () const
cbCompilerPlugin * GetFirstCompiler () const
PluginsArray GetToolOffers ()
PluginsArray GetMimeOffers ()
PluginsArray GetDebuggerOffers ()
PluginsArray GetCodeCompletionOffers ()
PluginsArray GetSmartIndentOffers ()
PluginsArray GetOffersFor (PluginType type)
void AskPluginsForModuleMenu (const ModuleType type, wxMenu *menu, const FileTreeData *data=nullptr)
void ResetModuleMenu ()
Called by the code creating the context menu for the editor.
void RegisterFindMenuItems (bool before, int count)
Can be called by plugins' BuildModuleMenu when building the EditorManager's context menu.
int GetFindMenuItemCount () const
Returns the number of items in the find group already added to the menu.
int GetFindMenuItemFirst () const
Returns the position of the first menu item in the find group.
void RegisterLastNonPluginMenuItem (int id)
Called by the editor code which adds the non-plugin related menu items to store the id of the last fixed menu item.
int FindSortedMenuItemPosition (wxMenu &popup, const wxString &label) const
Called by plugins when they want to add menu items to the editor's context menu.
cbMimePlugin * GetMIMEHandlerForFile (const wxString &filename)
void GetConfigurationPanels (int group, wxWindow *parent, ConfigurationPanelsArray &arrayToFill)
void GetProjectConfigurationPanels (wxWindow *parent, cbProject *project, ConfigurationPanelsArray &arrayToFill)
int Configure ()
void SetupLocaleDomain (const wxString &DomainName)
void NotifyPlugins (CodeBlocksEvent &event)
void NotifyPlugins (CodeBlocksDockEvent &event)
void NotifyPlugins (CodeBlocksLayoutEvent &event)
Static Public Member Functions
static void SetSafeMode (bool on)
static bool GetSafeMode ()
Static Public Member Functions inherited from Mgr< PluginManager >
static bool Valid ()
static PluginManager * Get ()
static void Free ()
Private Member Functions
PluginManager ()
~PluginManager () override
void OnScriptMenu (wxCommandEvent &event)
void OnScriptModuleMenu (wxCommandEvent &event)
bool ReadManifestFile (const wxString &pluginFilename, const wxString &pluginName=wxEmptyString, PluginInfo *infoOut=nullptr)
void ReadExtraFilesFromManifestFile (const wxString &pluginFilename, wxArrayString &extraFiles)
bool ExtractFile (const wxString &bundlename, const wxString &src_filename, const wxString &dst_filename, bool isMandatory=true)
Private Attributes
PluginElementsArray m_Plugins
wxString m_CurrentlyLoadingFilename
wxDynamicLibrary * m_pCurrentlyLoadingLib
TiXmlDocument * m_pCurrentlyLoadingManifestDoc
std::vector< PluginRegistration > m_RegisteredPlugins
CompilerPlugins m_CompilerPlugins
int m_FindMenuItemCount = 0
int m_FindMenuItemFirst = 0
int m_LastNonPluginMenuId = 0
Static Private Attributes
static bool s_SafeMode = false
Friends
class Mgr< PluginManager >
class Manager
Additional Inherited Members
Protected Member Functions inherited from Mgr< PluginManager >
Mgr ()
virtual ~Mgr ()
Detailed Description
PluginManager manages plugins.
There are two plugin types: binary and scripted.
Binary plugins are dynamically loaded shared libraries (dll/so) which can do pretty much anything with the SDK.
Script plugins are more lightweight and are very convenient for smaller scale/functionality plugins.
Definition at line 76 of file pluginmanager.h.
Member Typedef Documentation
CompilerPlugins
typedef std::vector<cbCompilerPlugin*> PluginManager::CompilerPlugins
Definition at line 79 of file pluginmanager.h.
Constructor & Destructor Documentation
PluginManager()
PluginManager::PluginManager () private
Definition at line 168 of file pluginmanager.cpp.
References Manager::Get(), and Manager::GetAppWindow().
~PluginManager()
PluginManager::~PluginManager () override private
Definition at line 176 of file pluginmanager.cpp.
Member Function Documentation
AskPluginsForModuleMenu()
void PluginManager::AskPluginsForModuleMenu (const ModuleType type, wxMenu * menu, const FileTreeData * data = nullptr)
Definition at line 1374 of file pluginmanager.cpp.
References cbPlugin::BuildModuleMenu(), ScriptBindings::ScriptPluginWrapper::CreateModuleMenu(), cbPlugin::IsAttached(), OnScriptModuleMenu(), and cbException::ShowErrorMessage().
Referenced by EditorBase::DisplayContextMenu(), EditorManager::OnPageContextMenu(), ProjectManagerUI::OnRightClick(), and ProjectManagerUI::ShowMenu().
AttachPlugin()
bool PluginManager::AttachPlugin (cbPlugin * plugin, bool ignoreSafeMode = false)
Definition at line 189 of file pluginmanager.cpp.
References cbPlugin::Attach(), and cbPlugin::IsAttached().
Referenced by PluginsConfigurationDlg::OnToggle().
Configure()
int PluginManager::Configure ()
Definition at line 1495 of file pluginmanager.cpp.
References Manager::Get(), PlaceWindow(), and wxDialog::ShowModal().
CreateMenu()
void PluginManager::CreateMenu (wxMenuBar * menuBar)
Definition at line 181 of file pluginmanager.cpp.
DetachPlugin()
bool PluginManager::DetachPlugin (cbPlugin * plugin)
Definition at line 201 of file pluginmanager.cpp.
References Manager::Get(), Manager::IsAppShuttingDown(), cbPlugin::IsAttached(), cbPlugin::Release(), and Manager::RemoveAllEventSinksFor().
Referenced by PluginsConfigurationDlg::OnToggle().
ExecutePlugin()
int PluginManager::ExecutePlugin (const wxString & pluginName)
Definition at line 1235 of file pluginmanager.cpp.
References _T, ScriptBindings::IOLib::Execute(), F(), Manager::Get(), Manager::GetLogManager(), cbPlugin::GetType(), PluginElement::info, LogManager::LogError(), PluginInfo::name, PluginElement::plugin, ptTool, cbException::ShowErrorMessage(), and wxString::wx_str().
Referenced by ScriptBindings::ExecutePlugin(), and MainFrame::OnPluginsExecuteMenu().
ExportPlugin()
bool PluginManager::ExportPlugin (cbPlugin * plugin, const wxString & filename)
Definition at line 497 of file pluginmanager.cpp.
References _(), _T, wxFile::Access(), wxArrayString::Add(), wxFileName::Assign(), wxString::c_str(), cbMessageBox(), PluginElement::fileName, wxString::Format(), wxArrayString::GetCount(), wxFileName::GetName(), wxArrayString::IsEmpty(), wxString::IsEmpty(), ConfigManager::LocateDataFile(), PluginElement::plugin, wxString::Prepend(), wxZipOutputStream::PutNextEntry(), wxString::Remove(), sdDataGlobal, sdDataUser, wxZipOutputStream::SetComment(), wxString::StartsWith(), wxFile::write, wxFileExists(), and wxICON_WARNING.
Referenced by PluginsConfigurationDlg::OnExport().
ExtractFile()
bool PluginManager::ExtractFile (const wxString & bundlename, const wxString & src_filename, const wxString & dst_filename, bool isMandatory = true) private
Definition at line 597 of file pluginmanager.cpp.
References _(), _T, wxFile::Access(), wxString::c_str(), cbMessageBox(), CreateDirRecursively(), wxString::Format(), wxFSFile::GetStream(), wxFile::IsOpened(), wxFileSystem::OpenFile(), wxFile::write, wxFile::Write(), wxFileExists(), wxICON_ERROR, and wxICON_WARNING.
FindElementByName()
PluginElement * PluginManager::FindElementByName (const wxString & pluginName)
Definition at line 1178 of file pluginmanager.cpp.
References PluginElement::info, and PluginInfo::name.
FindPluginByFileName()
cbPlugin * PluginManager::FindPluginByFileName (const wxString & pluginFileName)
Definition at line 1202 of file pluginmanager.cpp.
References PluginElement::fileName, and PluginElement::plugin.
FindPluginByName()
cbPlugin * PluginManager::FindPluginByName (const wxString & pluginName)
Definition at line 1190 of file pluginmanager.cpp.
References PluginElement::info, PluginInfo::name, and PluginElement::plugin.
Referenced by MainFrame::OnToggleBar(), and MainFrame::SetChecksForViewToolbarsMenu().
FindSortedMenuItemPosition()
int PluginManager::FindSortedMenuItemPosition (wxMenu & popup, const wxString & label) const
Called by plugins when they want to add menu items to the editor's context menu.
Using this method will produce a menu which is sorted alphabetically (case insensitive). The menu items are added at the bottom of the menu.
Parameters
popup The context menu passed to BuildModuleMenu.
label The label of the new menu item. It will be used to find the correct position.
Returns
The position where to insert the item.
Definition at line 1437 of file pluginmanager.cpp.
References wxString::begin(), wxString::CmpNoCase(), wxString::end(), wxString::erase(), wxMenu::GetMenuItems(), and wxITEM_SEPARATOR.
GetCodeCompletionOffers()
PluginsArray PluginManager::GetCodeCompletionOffers ()
Definition at line 1331 of file pluginmanager.cpp.
References ptCodeCompletion.
Referenced by CCManager::GetProviderFor().
GetCompilerPlugins()
const CompilerPlugins& PluginManager::GetCompilerPlugins () const inline
Definition at line 115 of file pluginmanager.h.
Referenced by cbHasRunningCompilers(), cbStopRunningCompilers(), and cbDebuggerPlugin::EnsureBuildUpToDate().
GetConfigurationPanels()
void PluginManager::GetConfigurationPanels (int group, wxWindow * parent, ConfigurationPanelsArray & arrayToFill)
Definition at line 1269 of file pluginmanager.cpp.
References cbPlugin::GetConfigurationGroup(), cbPlugin::GetConfigurationPanel(), cbPlugin::IsAttached(), and SortByConfigurationPriority().
Referenced by CompilerSettingsDlg::AddPluginPanels(), EnvironmentSettingsDlg::AddPluginPanels(), and EditorConfigurationDlg::AddPluginPanels().
GetDebuggerOffers()
PluginsArray PluginManager::GetDebuggerOffers ()
Definition at line 1326 of file pluginmanager.cpp.
References ptDebugger.
GetFindMenuItemCount()
int PluginManager::GetFindMenuItemCount () const
Returns the number of items in the find group already added to the menu.
Definition at line 1422 of file pluginmanager.cpp.
Referenced by DebuggerMenuHandler::BuildContextMenu(), and EditorBase::DisplayContextMenu().
GetFindMenuItemFirst()
int PluginManager::GetFindMenuItemFirst () const
Returns the position of the first menu item in the find group.
Definition at line 1427 of file pluginmanager.cpp.
Referenced by DebuggerMenuHandler::BuildContextMenu(), CodeCompletion::BuildModuleMenu(), and EditorBase::DisplayContextMenu().
GetFirstCompiler()
cbCompilerPlugin * PluginManager::GetFirstCompiler () const
Definition at line 1309 of file pluginmanager.cpp.
Referenced by CodeBlocksApp::BatchJob(), and ProjectOptionsDlg::ProjectOptionsDlg().
GetMIMEHandlerForFile()
cbMimePlugin * PluginManager::GetMIMEHandlerForFile (const wxString & filename)
Definition at line 1483 of file pluginmanager.cpp.
References cbMimePlugin::CanHandleFile().
Referenced by ProjectManagerUI::DoOpenFile(), ProjectManager::LoadProject(), MainFrame::OpenGeneric(), and BuildLogger::OpenLink().
GetMimeOffers()
PluginsArray PluginManager::GetMimeOffers ()
Definition at line 1321 of file pluginmanager.cpp.
References ptMime.
Referenced by ProjectManagerUI::OnOpenWith(), and ProjectManagerUI::ShowMenu().
GetOffersFor()
PluginsArray PluginManager::GetOffersFor (PluginType type)
Definition at line 1341 of file pluginmanager.cpp.
References cbPlugin::GetType(), cbPlugin::IsAttached(), and ptMime.
Referenced by NewFromTemplateDlg::NewFromTemplateDlg().
GetPluginInfo() [1/2]
const PluginInfo * PluginManager::GetPluginInfo (const wxString & pluginName)
Definition at line 1214 of file pluginmanager.cpp.
References PluginElement::info, and PluginInfo::name.
Referenced by MainFrame::AddPluginInMenus(), MainFrame::DoAddPluginToolbar(), ProjectManagerUI::DoOpenFile(), MainFrame::OnHelpPluginMenu(), MainFrame::OnPluginLoaded(), MainFrame::PluginsUpdated(), and ProjectManagerUI::ShowMenu().
GetPluginInfo() [2/2]
const PluginInfo * PluginManager::GetPluginInfo (cbPlugin * plugin)
Definition at line 1223 of file pluginmanager.cpp.
References PluginElement::info, and PluginElement::plugin.
GetPlugins()
const PluginElementsArray& PluginManager::GetPlugins () const inline
Definition at line 109 of file pluginmanager.h.
Referenced by CompilerSettingsDlg::CompilerSettingsDlg(), MainFrame::CreateMenubar(), MainFrame::CreateToolbars(), CompilerSettingsDlg::EndModal(), PluginsConfigurationDlg::FillList(), and MainFrame::PluginsUpdated().
GetProjectConfigurationPanels()
void PluginManager::GetProjectConfigurationPanels (wxWindow * parent, cbProject * project, ConfigurationPanelsArray & arrayToFill)
Definition at line 1295 of file pluginmanager.cpp.
References cbPlugin::GetProjectConfigurationPanel(), and cbPlugin::IsAttached().
Referenced by ProjectOptionsDlg::AddPluginPanels().
GetSafeMode()
static bool PluginManager::GetSafeMode () inline static
Definition at line 164 of file pluginmanager.h.
References ScriptBindings::ScriptPluginWrapper::OnScriptMenu(), ScriptBindings::ScriptPluginWrapper::OnScriptModuleMenu(), and wxEmptyString.
Referenced by cbSplashScreen::DrawReleaseInfo(), GetInitialInfo(), and StartHerePage::StartHerePage().
GetSmartIndentOffers()
PluginsArray PluginManager::GetSmartIndentOffers ()
Definition at line 1336 of file pluginmanager.cpp.
References ptSmartIndent.
GetToolOffers()
PluginsArray PluginManager::GetToolOffers ()
Definition at line 1316 of file pluginmanager.cpp.
References ptTool.
InstallPlugin()
bool PluginManager::InstallPlugin (const wxString & pluginName, bool forAllUsers = true, bool askForConfirmation = true)
Definition at line 213 of file pluginmanager.cpp.
References _(), _T, wxString::AfterFirst(), wxString::BeforeFirst(), cbEVT_PLUGIN_INSTALLED, cbMessageBox(), CompareVersions(), wxString::Contains(), LogManager::DebugLog(), FileFilters::DYNAMICLIB_DOT_EXT, Manager::Get(), wxArrayString::GetCount(), ConfigManager::GetFolder(), Manager::GetLogManager(), Manager::GetMacrosManager(), wxFileName::GetName(), wxString::IsEmpty(), Manager::ProcessEvent(), wxString::Remove(), MacrosManager::ReplaceMacros(), sdDataGlobal, sdDataUser, sdPluginsGlobal, sdPluginsUser, CodeBlocksEvent::SetPlugin(), wxString::StartsWith(), UnixFilename(), wxGenericProgressDialog::Update(), PluginInfo::version, CfgMgrConsts::version, wxICON_QUESTION, wxID_NO, and wxYES_NO.
Referenced by ScriptBindings::InstallPlugin(), and PluginsConfigurationDlg::OnInstall().
LoadAllPlugins()
void PluginManager::LoadAllPlugins ()
Definition at line 1067 of file pluginmanager.cpp.
References _(), _T, wxString::c_str(), cbMessageBox(), Manager::Get(), Manager::GetConfigManager(), Manager::GetLogManager(), PluginElement::info, cbPlugin::IsAttached(), wxString::IsEmpty(), LogManager::Log(), PluginInfo::name, PluginElement::plugin, wxString::Printf(), ConfigManager::Read(), ConfigManager::ReadBool(), cbException::ShowErrorMessage(), PluginInfo::title, ConfigManager::Write(), wxEmptyString, wxICON_WARNING, wxID_NO, wxID_YES, and wxYES_NO.
Referenced by MainFrame::ScanForPlugins().
LoadPlugin()
bool PluginManager::LoadPlugin (const wxString & pluginName)
Definition at line 1004 of file pluginmanager.cpp.
References _T, PluginManager::PluginRegistration::createProc, LogManager::DebugLog(), F(), PluginElement::fileName, PluginElement::freeProc, PluginManager::PluginRegistration::freeProc, Manager::Get(), Manager::GetLogManager(), cbPlugin::GetType(), PluginElement::info, PluginManager::PluginRegistration::info, PluginElement::library, LibLoader::LoadLibrary(), LogManager::LogError(), PluginManager::PluginRegistration::name, PluginElement::plugin, ptCompiler, LibLoader::RemoveLibrary(), cbException::ShowErrorMessage(), and wxString::wx_str().
NotifyPlugins() [1/3]
void PluginManager::NotifyPlugins (CodeBlocksEvent & event)
Definition at line 1520 of file pluginmanager.cpp.
References Manager::Get(), and Manager::ProcessEvent().
Referenced by ProjectManager::AddFileToProject(), ProjectManager::AddMultipleFilesToProject(), ProjectManager::CloseProject(), ProjectManager::CloseWorkspace(), DebuggerGDB::DoBreak(), DebuggerGDB::DoDebug(), cbStyledTextCtrl::EmulateDwellStart(), ProjectManager::EndLoadingWorkspace(), ProjectManager::LoadWorkspace(), EditorManager::New(), cbEditor::NotifyPlugins(), ProjectOptionsDlg::OnAddBuildTargetClick(), ProjectOptionsDlg::OnBuildOrderClick(), ProjectOptionsDlg::OnBuildTargetChanged(), ProjectOptionsDlg::OnCopyBuildTargetClick(), ProjectOptionsDlg::OnEditBuildTargetClick(), MainFrame::OnFileNewWhat(), DebuggerGDB::OnGDBTerminated(), EditorManager::OnPageChanged(), EditorManager::OnPageChanging(), EditorManager::OnPageClose(), ProjectOptionsDlg::OnRemoveBuildTargetClick(), ProjectManager::RemoveFileFromProject(), MainFrame::ScanForPlugins(), EditorManager::SetActiveEditor(), ProjectManager::SetProject(), ProjectManager::WorkspaceChanged(), and EditorBase::~EditorBase().
NotifyPlugins() [2/3]
void PluginManager::NotifyPlugins (CodeBlocksDockEvent & event)
Definition at line 1525 of file pluginmanager.cpp.
References Manager::Get(), and Manager::ProcessEvent().
NotifyPlugins() [3/3]
void PluginManager::NotifyPlugins (CodeBlocksLayoutEvent & event)
Definition at line 1530 of file pluginmanager.cpp.
References Manager::Get(), and Manager::ProcessEvent().
OnScriptMenu()
void PluginManager::OnScriptMenu (wxCommandEvent & event) private
Definition at line 1473 of file pluginmanager.cpp.
References ScriptBindings::ScriptPluginWrapper::OnScriptMenu().
OnScriptModuleMenu()
void PluginManager::OnScriptModuleMenu (wxCommandEvent & event) private
Definition at line 1478 of file pluginmanager.cpp.
References ScriptBindings::ScriptPluginWrapper::OnScriptModuleMenu().
Referenced by AskPluginsForModuleMenu().
ReadExtraFilesFromManifestFile()
void PluginManager::ReadExtraFilesFromManifestFile (const wxString & pluginFilename, wxArrayString & extraFiles) private
Definition at line 863 of file pluginmanager.cpp.
References _T, wxArrayString::Add(), cbC2U(), cbU2C(), wxArrayString::Clear(), Manager::Get(), wxFileName::GetFullName(), Manager::GetLogManager(), wxFSFile::GetStream(), wxString::IsEmpty(), ConfigManager::LocateDataFile(), LogManager::LogError(), wxFileSystem::OpenFile(), wxString::Remove(), sdDataGlobal, sdDataUser, sdPluginsGlobal, sdPluginsUser, wxFileName::SetExt(), and wxString::StartsWith().
ReadManifestFile()
bool PluginManager::ReadManifestFile (const wxString & pluginFilename, const wxString & pluginName = wxEmptyString, PluginInfo * infoOut = nullptr) private
Returns
True if the plugin should be loaded, false if not.
Definition at line 722 of file pluginmanager.cpp.
References _T, PluginInfo::author, PluginInfo::authorEmail, PluginInfo::authorWebsite, cbC2U(), cbU2C(), PluginInfo::description, Manager::Get(), wxFileName::GetFullName(), Manager::GetLogManager(), wxFSFile::GetStream(), wxString::IsEmpty(), PluginInfo::license, ConfigManager::LocateDataFile(), LogManager::LogError(), PluginInfo::name, wxFileSystem::OpenFile(), wxString::Remove(), sdDataGlobal, sdDataUser, sdPluginsGlobal, sdPluginsUser, wxFileName::SetExt(), wxString::StartsWith(), PluginInfo::thanksTo, PluginInfo::title, PluginInfo::version, and CfgMgrConsts::version.
RegisterFindMenuItems()
void PluginManager::RegisterFindMenuItems (bool before, int count)
Can be called by plugins' BuildModuleMenu when building the EditorManager's context menu.
This method has two purposes:
to control the number of find related items in the menu
to control the number of items that are placed before the find related items.
Parameters
before Pass true when you're adding items before the find group and false when adding in the find group.
count The number of items you're adding to the menu.
Definition at line 1414 of file pluginmanager.cpp.
Referenced by cbEditor::AddToContextMenu(), DebuggerMenuHandler::BuildContextMenu(), and CodeCompletion::BuildModuleMenu().
RegisterLastNonPluginMenuItem()
void PluginManager::RegisterLastNonPluginMenuItem (int id)
Called by the editor code which adds the non-plugin related menu items to store the id of the last fixed menu item.
Must not be called by plugins.
Definition at line 1432 of file pluginmanager.cpp.
Referenced by cbEditor::AddToContextMenu().
RegisterPlugin()
void PluginManager::RegisterPlugin (const wxString & name, CreatePluginProc createProc, FreePluginProc freeProc, PluginSDKVersionProc versionProc)
Definition at line 665 of file pluginmanager.cpp.
References _(), _T, wxString::c_str(), PluginManager::PluginRegistration::createProc, PluginManager::PluginRegistration::freeProc, Manager::Get(), Manager::GetLogManager(), PluginManager::PluginRegistration::info, wxString::IsEmpty(), LogManager::LogError(), PluginInfo::name, PluginManager::PluginRegistration::name, PLUGIN_SDK_VERSION_MAJOR, PLUGIN_SDK_VERSION_MINOR, PLUGIN_SDK_VERSION_RELEASE, wxString::Printf(), and PluginManager::PluginRegistration::versionProc.
Referenced by PluginRegistrant< T >::PluginRegistrant().
ReleaseMenu()
void PluginManager::ReleaseMenu (wxMenuBar * menuBar)
Definition at line 185 of file pluginmanager.cpp.
ResetModuleMenu()
void PluginManager::ResetModuleMenu ()
Called by the code creating the context menu for the editor.
Must not be called by plugins.
Definition at line 1407 of file pluginmanager.cpp.
Referenced by EditorBase::DisplayContextMenu().
ScanForPlugins()
int PluginManager::ScanForPlugins (const wxString & path)
Definition at line 931 of file pluginmanager.cpp.
References _(), _T, cbReadBatchBuildPlugins(), InfoWindow::Display(), F(), Manager::Get(), wxArrayString::GetCount(), wxDir::GetFirst(), Manager::GetLogManager(), wxDir::GetNext(), Manager::IsBatchBuild(), wxString::IsEmpty(), wxDir::IsOpened(), LogManager::Log(), wxDIR_FILES, and wxDirExists().
Referenced by MainFrame::ScanForPlugins().
SetSafeMode()
static void PluginManager::SetSafeMode (bool on) inline static
Definition at line 163 of file pluginmanager.h.
Referenced by CodeBlocksApp::OnInit().
SetupLocaleDomain()
void PluginManager::SetupLocaleDomain (const wxString & DomainName)
Definition at line 1502 of file pluginmanager.cpp.
References _T, wxString::Cmp(), wxString::Format(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::Read(), ConfigManager::ReadInt(), ConfigManager::Write(), and wxEmptyString.
UninstallPlugin()
bool PluginManager::UninstallPlugin (cbPlugin * plugin, bool removeFiles = true)
Definition at line 361 of file pluginmanager.cpp.
References _(), _T, wxFile::Access(), wxString::c_str(), cbEVT_PLUGIN_UNINSTALLED, cbMessageBox(), PluginElement::fileName, wxString::Format(), Manager::Get(), wxArrayString::GetCount(), Manager::GetLogManager(), wxFileName::GetName(), PluginElement::info, wxString::IsEmpty(), ConfigManager::LocateDataFile(), LogManager::LogWarning(), PluginElement::plugin, Manager::ProcessEvent(), wxString::Remove(), sdDataGlobal, sdDataUser, wxString::StartsWith(), PluginInfo::title, wxGenericProgressDialog::Update(), wxFile::write, wxFileExists(), wxICON_WARNING, and wxRemoveFile().
UnloadAllPlugins()
void PluginManager::UnloadAllPlugins ()
Definition at line 1127 of file pluginmanager.cpp.
References LibLoader::Cleanup().
UnloadPlugin()
void PluginManager::UnloadPlugin (cbPlugin * plugin)
Definition at line 1140 of file pluginmanager.cpp.
References PluginElement::freeProc, cbPlugin::GetType(), PluginElement::library, PluginElement::plugin, ptCompiler, and LibLoader::RemoveLibrary().
Friends And Related Function Documentation
Manager
friend class Manager friend
Definition at line 83 of file pluginmanager.h.
Mgr< PluginManager >
friend class Mgr< PluginManager > friend
Definition at line 82 of file pluginmanager.h.
Member Data Documentation
m_CompilerPlugins
CompilerPlugins PluginManager::m_CompilerPlugins private
Definition at line 213 of file pluginmanager.h.
m_CurrentlyLoadingFilename
wxString PluginManager::m_CurrentlyLoadingFilename private
Definition at line 184 of file pluginmanager.h.
m_FindMenuItemCount
int PluginManager::m_FindMenuItemCount = 0 private
Definition at line 215 of file pluginmanager.h.
m_FindMenuItemFirst
int PluginManager::m_FindMenuItemFirst = 0 private
Definition at line 216 of file pluginmanager.h.
m_LastNonPluginMenuId
int PluginManager::m_LastNonPluginMenuId = 0 private
Definition at line 217 of file pluginmanager.h.
m_pCurrentlyLoadingLib
wxDynamicLibrary* PluginManager::m_pCurrentlyLoadingLib private
Definition at line 185 of file pluginmanager.h.
m_pCurrentlyLoadingManifestDoc
TiXmlDocument* PluginManager::m_pCurrentlyLoadingManifestDoc private
Definition at line 186 of file pluginmanager.h.
m_Plugins
PluginElementsArray PluginManager::m_Plugins private
Definition at line 183 of file pluginmanager.h.
m_RegisteredPlugins
std::vector<PluginRegistration> PluginManager::m_RegisteredPlugins private
Definition at line 212 of file pluginmanager.h.
s_SafeMode
bool PluginManager::s_SafeMode = false static private
Definition at line 219 of file pluginmanager.h.
Referenced by LibLoader::Cleanup().
The documentation for this class was generated from the following files:
pluginmanager.h
pluginmanager.cpp