Code::Blocks: DebugLogPanel Class Reference
DebugLogPanel Class Reference
Public Member Functions
DebugLogPanel (wxWindow *parent, DebugTextCtrlLogger *text_control_logger, bool debug_log)
void OnEntryCommand (cb_unused wxCommandEvent &event)
void OnClearLog (cb_unused wxCommandEvent &event)
void OnLoadFile (cb_unused wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Private Attributes
DebugTextCtrlLogger * m_text_control_logger
wxComboBox * m_command_entry
bool m_debug_log
Detailed Description
Definition at line 522 of file debuggermanager.cpp.
Constructor & Destructor Documentation
DebugLogPanel()
DebugLogPanel::DebugLogPanel (wxWindow * parent, DebugTextCtrlLogger * text_control_logger, bool debug_log) inline
Definition at line 525 of file debuggermanager.cpp.
References _(), _T, wxBoxSizer::Add(), DebugTextCtrlLogger::CreateTextCtrl(), wxArtProvider::GetBitmap(), OnClearLog(), OnEntryCommand(), OnLoadFile(), OnUpdateUI(), wxBitmapButton::SetDefault(), wxALIGN_CENTER_VERTICAL, wxALL, wxART_BUTTON, wxBU_AUTODRAW, wxCB_DROPDOWN, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEVT_UPDATE_UI, wxEXPAND, wxHORIZONTAL, wxID_ANY, wxNewId(), wxST_NO_AUTORESIZE, wxTE_PROCESS_ENTER, and wxVERTICAL.
Member Function Documentation
OnClearLog()
void DebugLogPanel::OnClearLog (cb_unused wxCommandEvent & event) inline
Definition at line 630 of file debuggermanager.cpp.
Referenced by DebugLogPanel().
OnEntryCommand()
void DebugLogPanel::OnEntryCommand (cb_unused wxCommandEvent & event) inline
Definition at line 606 of file debuggermanager.cpp.
References Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), wxString::IsEmpty(), cbDebuggerPlugin::SendCommand(), wxString::Trim(), wxEmptyString, and wxNOT_FOUND.
Referenced by DebugLogPanel().
OnLoadFile()
void DebugLogPanel::OnLoadFile (cb_unused wxCommandEvent & event) inline
Definition at line 638 of file debuggermanager.cpp.
References _(), _T, Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetConfigManager(), Manager::GetDebuggerManager(), wxFileDialog::GetDirectory(), wxFileDialog::GetPath(), ConfigManager::Read(), cbDebuggerPlugin::SendCommand(), wxFileDialog::ShowModal(), ConfigManager::Write(), wxEmptyString, wxFD_OPEN, and wxID_OK.
Referenced by DebugLogPanel().
OnUpdateUI()
void DebugLogPanel::OnUpdateUI (wxUpdateUIEvent & event) inline
Definition at line 658 of file debuggermanager.cpp.
References Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), cbDebuggerPlugin::IsRunning(), and cbDebuggerPlugin::IsStopped().
Referenced by DebugLogPanel().
Member Data Documentation
m_command_entry
wxComboBox* DebugLogPanel::m_command_entry private
Definition at line 665 of file debuggermanager.cpp.
m_debug_log
bool DebugLogPanel::m_debug_log private
Definition at line 666 of file debuggermanager.cpp.
m_text_control_logger
DebugTextCtrlLogger* DebugLogPanel::m_text_control_logger private
Definition at line 664 of file debuggermanager.cpp.
The documentation for this class was generated from the following file:
debuggermanager.cpp