Code::Blocks: CompilerQueue Class Reference
CompilerQueue Class Reference
#include <compiler_defs.h>
Public Member Functions
CompilerQueue ()
~CompilerQueue ()
void Clear ()
Clear the queue.
size_t GetCount () const
Get the commands count.
bool LastCommandWasRun () const
void Add (CompilerCommand *cmd)
Queue a command.
void Add (CompilerQueue *queue)
Queue all commands from another CompilerQueue.
CompilerCommand * Next ()
Get the next command in queue.
CompilerCommand * Peek ()
Protected Attributes
CompilerCommands m_Commands
bool m_LastWasRun
Constructor & Destructor Documentation
CompilerQueue::CompilerQueue ()
CompilerQueue::~CompilerQueue ()
References Clear().
Member Function Documentation
void CompilerQueue::Add (CompilerCommand * cmd)
Queue a command.
References CompilerCommand::dir, cbProject::GetExecutionDir(), m_Commands, and CompilerCommand::project.
Referenced by Add(), CompilerGCC::AddToCommandQueue(), CompilerGCC::DistClean(), CompilerGCC::Run(), and CompilerGCC::RunSingleFile().
void CompilerQueue::Add (CompilerQueue * queue)
Queue all commands from another CompilerQueue.
References Add(), and m_Commands.
void CompilerQueue::Clear ()
Clear the queue.
References m_Commands.
Referenced by CompilerGCC::DoRunQueue(), CompilerGCC::InitBuildState(), CompilerGCC::KillProcess(), CompilerGCC::OnJobEnd(), CompilerGCC::ResetBuildState(), and ~CompilerQueue().
size_t CompilerQueue::GetCount () const
Get the commands count.
References m_Commands.
Referenced by CompilerGCC::DoPrepareQueue(), CompilerGCC::IsRunning(), CompilerGCC::NotifyCleanProject(), CompilerGCC::NotifyCleanWorkspace(), and CompilerGCC::OnJobEnd().
bool CompilerQueue::LastCommandWasRun () const
References m_LastWasRun.
Referenced by CompilerGCC::DoRunQueue(), CompilerGCC::KillProcess(), and CompilerGCC::OnJobEnd().
CompilerCommand * CompilerQueue::Next ()
Get the next command in queue.
If from is NULL, returns the top command. If from is not NULL, the command following from is returned. if remove is true (default), the command is removed from the list. This means that the caller must delete it.
References CompilerCommand::isRun, m_Commands, and m_LastWasRun.
Referenced by CompilerGCC::DoRunQueue().
CompilerCommand * CompilerQueue::Peek ()
References m_Commands.
Referenced by CompilerGCC::DoRunQueue().
Member Data Documentation
CompilerCommands CompilerQueue::m_Commands protected
Referenced by Add(), Clear(), GetCount(), Next(), and Peek().
bool CompilerQueue::m_LastWasRun protected
Referenced by LastCommandWasRun(), and Next().
The documentation for this class was generated from the following files:
compiler_defs.h
compiler_defs.cpp