Code::Blocks: FileTreeData Class Reference
FileTreeData Class Reference
#include <cbproject.h>
Public Types
enum FileTreeDataKind {
ftdkUndefined = 0, ftdkProject, ftdkFolder, ftdkFile,
ftdkVirtualGroup, ftdkVirtualFolder
}
The kind of tree node.
Public Member Functions
FileTreeData (cbProject *project, FileTreeDataKind kind=ftdkUndefined)
FileTreeDataKind GetKind () const
cbProject * GetProject () const
int GetFileIndex () const
ProjectFile * GetProjectFile () const
const wxString & GetFolder () const
void SetKind (FileTreeDataKind kind)
void SetProject (cbProject *project)
void SetFileIndex (int index)
void SetProjectFile (ProjectFile *file)
void SetFolder (const wxString &folder)
Public Member Functions inherited from MiscTreeItemData
MiscTreeItemData ()
wxEvtHandler * GetOwner ()
virtual ~MiscTreeItemData ()
Public Member Functions inherited from wxTreeItemData
wxTreeItemData ()
virtual ~wxTreeItemData ()
const wxTreeItemId & GetId () const
void SetId (const wxTreeItemId &id)
Public Member Functions inherited from wxClientData
wxClientData ()
virtual ~wxClientData ()
Private Attributes
int m_Index
cbProject * m_Project
ProjectFile * m_file
wxString m_folder
FileTreeDataKind m_kind
Additional Inherited Members
Static Public Member Functions inherited from MiscTreeItemData
static bool OwnerCheck (wxTreeEvent &event, wxTreeCtrl *tree, wxEvtHandler *handler, bool strict=false)
Protected Member Functions inherited from MiscTreeItemData
void SetOwner (wxEvtHandler *owner)
Detailed Description
Definition at line 37 of file cbproject.h.
Member Enumeration Documentation
FileTreeDataKind
enum FileTreeData::FileTreeDataKind
The kind of tree node.
Enumerator
ftdkUndefined
ftdkProject
ftdkFolder
ftdkFile
ftdkVirtualGroup
ftdkVirtualFolder
Definition at line 41 of file cbproject.h.
Constructor & Destructor Documentation
FileTreeData()
FileTreeData::FileTreeData (cbProject * project, FileTreeDataKind kind = ftdkUndefined) inline
Definition at line 51 of file cbproject.h.
Member Function Documentation
GetFileIndex()
int FileTreeData::GetFileIndex () const inline
Definition at line 60 of file cbproject.h.
Referenced by ProjectManagerUI::OnProperties(), and ScriptBindings::RegisterBindings().
GetFolder()
const wxString& FileTreeData::GetFolder () const inline
Definition at line 62 of file cbproject.h.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects(), ProjectManagerUI::OnRenameVirtualFolder(), ScriptBindings::RegisterBindings(), and ProjectManagerUI::ShowMenu().
GetKind()
FileTreeDataKind FileTreeData::GetKind () const inline
Definition at line 58 of file cbproject.h.
Referenced by CompilerGCC::BuildModuleMenu(), CodeCompletion::BuildModuleMenu(), ProjectManagerUI::CheckForExternallyModifiedProjects(), ProjectManagerUI::OnAddFileToProject(), ProjectManagerUI::OnBeginEditNode(), ProjectManagerUI::OnCloseProject(), ProjectManagerUI::OnFileOptions(), ProjectManagerUI::OnFindFile(), ProjectManagerUI::OnOpenFolderFiles(), ProjectManagerUI::OnProjectFileActivated(), ProjectManagerUI::OnRemoveFileFromProject(), CodeCompletion::OnSelectedFileReparse(), ProjectManagerUI::OpenFilesRecursively(), ScriptBindings::RegisterBindings(), NativeParser::ReparseSelectedProject(), and ProjectManagerUI::ShowMenu().
GetProject()
cbProject* FileTreeData::GetProject () const inline
Definition at line 59 of file cbproject.h.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects(), CompilerGCC::DoSwitchProjectTemporarily(), ProjectManagerUI::OnAddFileToProject(), ProjectManagerUI::OnAddVirtualFolder(), ProjectManagerUI::OnCloseProject(), ProjectManagerUI::OnDeleteVirtualFolder(), ProjectManagerUI::OnEndEditNode(), ProjectManagerUI::OnFindFile(), CompilerGCC::OnProjectCompilerOptions(), ProjectManagerUI::OnProjectFileActivated(), ProjectManagerUI::OnProperties(), ProjectManagerUI::OnRemoveFileFromProject(), ProjectManagerUI::OnRenameFile(), ProjectManagerUI::OnRenameVirtualFolder(), CodeCompletion::OnSelectedFileReparse(), ProjectManagerUI::OnSetActiveProject(), ProjectManagerUI::OnTreeBeginDrag(), ProjectManagerUI::OnTreeEndDrag(), ProjectManagerUI::OpenFilesRecursively(), ScriptBindings::RegisterBindings(), NativeParser::ReparseSelectedProject(), and ProjectManagerUI::ShowMenu().
GetProjectFile()
ProjectFile* FileTreeData::GetProjectFile () const inline
Definition at line 61 of file cbproject.h.
Referenced by CompilerGCC::BuildModuleMenu(), ProjectManagerUI::CheckForExternallyModifiedProjects(), ProjectManagerUI::OnAddFileToProject(), CompilerGCC::OnCleanFile(), ProjectManagerUI::OnFileOptions(), ProjectManagerUI::OnFindFile(), ProjectManagerUI::OnOpenWith(), ProjectManagerUI::OnProperties(), ProjectManagerUI::OnRemoveFileFromProject(), ProjectManagerUI::OnRenameFile(), CodeCompletion::OnSelectedFileReparse(), ProjectManagerUI::OpenFilesRecursively(), CompilerGCC::PrepareCompileFilePM(), ScriptBindings::RegisterBindings(), and ProjectManagerUI::ShowMenu().
SetFileIndex()
void FileTreeData::SetFileIndex (int index) inline
Definition at line 67 of file cbproject.h.
Referenced by ProjectManagerUI::BuildProjectTree(), and ScriptBindings::RegisterBindings().
SetFolder()
void FileTreeData::SetFolder (const wxString & folder) inline
Definition at line 70 of file cbproject.h.
Referenced by ProjectManagerUI::BuildProjectTree(), ProjectManagerUI::CheckForExternallyModifiedProjects(), EditorBase::DisplayContextMenu(), and ScriptBindings::RegisterBindings().
SetKind()
void FileTreeData::SetKind (FileTreeDataKind kind) inline
Definition at line 64 of file cbproject.h.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects(), and ScriptBindings::RegisterBindings().
SetProject()
void FileTreeData::SetProject (cbProject * project) inline
Definition at line 65 of file cbproject.h.
Referenced by ScriptBindings::RegisterBindings().
SetProjectFile()
void FileTreeData::SetProjectFile (ProjectFile * file) inline
Definition at line 68 of file cbproject.h.
Referenced by ProjectManagerUI::BuildProjectTree(), ProjectManagerUI::CheckForExternallyModifiedProjects(), and ScriptBindings::RegisterBindings().
Member Data Documentation
m_file
ProjectFile* FileTreeData::m_file private
Definition at line 74 of file cbproject.h.
m_folder
wxString FileTreeData::m_folder private
Definition at line 75 of file cbproject.h.
m_Index
int FileTreeData::m_Index private
Definition at line 72 of file cbproject.h.
m_kind
FileTreeDataKind FileTreeData::m_kind private
Definition at line 76 of file cbproject.h.
m_Project
cbProject* FileTreeData::m_Project private
Definition at line 73 of file cbproject.h.
The documentation for this class was generated from the following file:
cbproject.h