Code::Blocks: FindReplaceBase Class Reference
FindReplaceBase Class Reference abstract
#include <findreplacebase.h>
Public Member Functions
FindReplaceBase (cb_optional wxWindow *parent, cb_optional const wxString &initial, cb_optional bool hasSelection)
virtual ~FindReplaceBase ()
virtual wxString GetFindString () const =0
virtual wxString GetReplaceString () const =0
virtual bool IsFindInFiles () const =0
virtual bool GetDeleteOldSearches () const =0
virtual bool GetSortSearchResult () const =0
virtual bool GetMatchWord () const =0
virtual bool GetStartWord () const =0
virtual bool GetStartFile () const =0
virtual bool GetMatchCase () const =0
virtual bool GetMultiLine () const =0
virtual bool GetFixEOLs () const =0
virtual bool GetRegEx () const =0
virtual bool GetAutoWrapSearch () const =0
virtual bool GetFindUsesSelectedText () const =0
virtual int GetDirection () const =0
virtual int GetOrigin () const =0
virtual int GetScope () const =0
virtual bool GetRecursive () const =0
virtual bool GetHidden () const =0
virtual wxString GetSearchPath () const =0
virtual wxString GetSearchMask () const =0
virtual int GetProject () const =0
virtual int GetTarget () const =0
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 14 of file findreplacebase.h.
Constructor & Destructor Documentation
FindReplaceBase()
FindReplaceBase::FindReplaceBase (cb_optional wxWindow * parent, cb_optional const wxString & initial, cb_optional bool hasSelection) inline
Definition at line 17 of file findreplacebase.h.
~FindReplaceBase()
virtual FindReplaceBase::~FindReplaceBase () inline virtual
Definition at line 18 of file findreplacebase.h.
References GetAutoWrapSearch(), GetDeleteOldSearches(), GetDirection(), GetFindString(), GetFindUsesSelectedText(), GetFixEOLs(), GetHidden(), GetMatchCase(), GetMatchWord(), GetMultiLine(), GetOrigin(), GetProject(), GetRecursive(), GetRegEx(), GetReplaceString(), GetScope(), GetSearchMask(), GetSearchPath(), GetSortSearchResult(), GetStartFile(), GetStartWord(), GetTarget(), and IsFindInFiles().
Member Function Documentation
GetAutoWrapSearch()
virtual bool FindReplaceBase::GetAutoWrapSearch () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetDeleteOldSearches()
virtual bool FindReplaceBase::GetDeleteOldSearches () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetDirection()
virtual int FindReplaceBase::GetDirection () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetFindString()
virtual wxString FindReplaceBase::GetFindString () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetFindUsesSelectedText()
virtual bool FindReplaceBase::GetFindUsesSelectedText () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetFixEOLs()
virtual bool FindReplaceBase::GetFixEOLs () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetHidden()
virtual bool FindReplaceBase::GetHidden () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetMatchCase()
virtual bool FindReplaceBase::GetMatchCase () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetMatchWord()
virtual bool FindReplaceBase::GetMatchWord () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetMultiLine()
virtual bool FindReplaceBase::GetMultiLine () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetOrigin()
virtual int FindReplaceBase::GetOrigin () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetProject()
virtual int FindReplaceBase::GetProject () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetRecursive()
virtual bool FindReplaceBase::GetRecursive () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetRegEx()
virtual bool FindReplaceBase::GetRegEx () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetReplaceString()
virtual wxString FindReplaceBase::GetReplaceString () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetScope()
virtual int FindReplaceBase::GetScope () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetSearchMask()
virtual wxString FindReplaceBase::GetSearchMask () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetSearchPath()
virtual wxString FindReplaceBase::GetSearchPath () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetSortSearchResult()
virtual bool FindReplaceBase::GetSortSearchResult () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetStartFile()
virtual bool FindReplaceBase::GetStartFile () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetStartWord()
virtual bool FindReplaceBase::GetStartWord () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
GetTarget()
virtual int FindReplaceBase::GetTarget () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
IsFindInFiles()
virtual bool FindReplaceBase::IsFindInFiles () const pure virtual
Implemented in FindReplaceDlg.
Referenced by FindReplace::ShowFindDialog(), and ~FindReplaceBase().
The documentation for this class was generated from the following file:
findreplacebase.h