Code::Blocks: CompilerOptions Class Reference
CompilerOptions Class Reference
#include <compileroptions.h>
Public Member Functions
CompilerOptions ()
CompilerOptions (const CompilerOptions &other)
CompilerOptions & operator= (const CompilerOptions &other)
~CompilerOptions ()
void ClearOptions ()
void AddOption (CompOption *coption, int index=-1)
void AddOption (const wxString &name, const wxString &option, const wxString &category=_("General"), const wxString &additionalLibs=wxEmptyString, const wxString &checkAgainst=wxEmptyString, const wxString &checkMessage=wxEmptyString, const wxString &supersedes=wxEmptyString, bool exclusive=false, int index=-1)
void RemoveOption (int index)
unsigned int GetCount () const
CompOption * GetOption (int index)
CompOption * GetOptionByName (const wxString &name)
CompOption * GetOptionByOption (const wxString &option)
CompOption * GetOptionByAdditionalLibs (const wxString &libs)
Private Attributes
OptionsArray m_Options
Detailed Description
Definition at line 30 of file compileroptions.h.
Constructor & Destructor Documentation
CompilerOptions() [1/2]
CompilerOptions::CompilerOptions ()
Definition at line 13 of file compileroptions.cpp.
CompilerOptions() [2/2]
CompilerOptions::CompilerOptions (const CompilerOptions & other)
Definition at line 17 of file compileroptions.cpp.
~CompilerOptions()
CompilerOptions::~CompilerOptions ()
Definition at line 34 of file compileroptions.cpp.
References ClearOptions().
Member Function Documentation
AddOption() [1/2]
void CompilerOptions::AddOption (CompOption * coption, int index = -1)
Definition at line 49 of file compileroptions.cpp.
References m_Options.
Referenced by AddOption(), Compiler::LoadDefaultOptions(), CompilerOptionsDlg::OnFlagsPopup(), and operator=().
AddOption() [2/2]
void CompilerOptions::AddOption (const wxString & name, const wxString & option, const wxString & category = _("General"), const wxString & additionalLibs = wxEmptyString, const wxString & checkAgainst = wxEmptyString, const wxString & checkMessage = wxEmptyString, const wxString & supersedes = wxEmptyString, bool exclusive = false, int index = -1)
Definition at line 57 of file compileroptions.cpp.
References _T, CompOption::additionalLibs, AddOption(), CompOption::category, CompOption::checkAgainst, CompOption::checkMessage, CompOption::enabled, CompOption::exclusive, wxString::IsEmpty(), CompOption::name, CompOption::option, and CompOption::supersedes.
ClearOptions()
void CompilerOptions::ClearOptions ()
Definition at line 39 of file compileroptions.cpp.
References m_Options.
Referenced by operator=(), Compiler::ReloadOptions(), CompilerLCC::Reset(), Compiler::Reset(), and ~CompilerOptions().
GetCount()
unsigned int CompilerOptions::GetCount () const inline
Definition at line 49 of file compileroptions.h.
Referenced by CompilerOptionsDlg::DoFillOptions(), CompilerOptionsDlg::DoSaveCompilerDefinition(), CompilerOptionsDlg::OnFlagsPopup(), CompilerOptionsDlg::OnOptionChanged(), CompilerOptionsDlg::OptionsToText(), and CompilerOptionsDlg::TextToOptions().
GetOption()
CompOption* CompilerOptions::GetOption (int index) inline
Definition at line 50 of file compileroptions.h.
Referenced by CompilerOptionsDlg::DoFillOptions(), CompilerOptionsDlg::DoSaveCompilerDefinition(), CompilerOptionsDlg::OnFlagsPopup(), CompilerOptionsDlg::OnOptionChanged(), CompilerOptionsDlg::OptionsToText(), and CompilerOptionsDlg::TextToOptions().
GetOptionByAdditionalLibs()
CompOption * CompilerOptions::GetOptionByAdditionalLibs (const wxString & libs)
Definition at line 121 of file compileroptions.cpp.
References CompOption::additionalLibs, wxString::IsEmpty(), and m_Options.
Referenced by CompilerOptionsDlg::OnOptionChanged(), and CompilerOptionsDlg::TextToOptions().
GetOptionByName()
CompOption * CompilerOptions::GetOptionByName (const wxString & name)
Definition at line 97 of file compileroptions.cpp.
References m_Options, and CompOption::name.
Referenced by CompilerOptionsDlg::OnFlagsPopup(), and CompilerOptionsDlg::OnOptionChanged().
GetOptionByOption()
CompOption * CompilerOptions::GetOptionByOption (const wxString & option)
Definition at line 108 of file compileroptions.cpp.
References wxString::IsEmpty(), m_Options, and CompOption::option.
Referenced by CompilerOptionsDlg::OnOptionChanged(), and CompilerOptionsDlg::TextToOptions().
operator=()
CompilerOptions & CompilerOptions::operator= (const CompilerOptions & other)
Definition at line 23 of file compileroptions.cpp.
References AddOption(), ClearOptions(), and m_Options.
RemoveOption()
void CompilerOptions::RemoveOption (int index)
Definition at line 90 of file compileroptions.cpp.
References m_Options.
Referenced by CompilerOptionsDlg::OnFlagsPopup().
Member Data Documentation
m_Options
OptionsArray CompilerOptions::m_Options private
Definition at line 56 of file compileroptions.h.
Referenced by AddOption(), ClearOptions(), GetOptionByAdditionalLibs(), GetOptionByName(), GetOptionByOption(), operator=(), and RemoveOption().
The documentation for this class was generated from the following files:
compileroptions.h
compileroptions.cpp