Code::Blocks: CompileOptionsBase Class Reference
CompileOptionsBase Class Reference
This is a base class for all classes needing compilation parameters.
#include <compileoptionsbase.h>
Public Member Functions
CompileOptionsBase ()
virtual ~CompileOptionsBase ()
virtual void AddPlatform (int platform)
virtual void RemovePlatform (int platform)
virtual void SetPlatforms (int platforms)
virtual int GetPlatforms () const
virtual bool SupportsCurrentPlatform () const
virtual void SetLinkerOptions (const wxArrayString &linkerOpts)
virtual const wxArrayString & GetLinkerOptions () const
virtual void AddLinkerOption (const wxString &option)
virtual void ReplaceLinkerOption (const wxString &option, const wxString &new_option)
virtual void RemoveLinkerOption (const wxString &option)
virtual void SetLinkLibs (const wxArrayString &linkLibs)
virtual const wxArrayString & GetLinkLibs () const
virtual void AddLinkLib (const wxString &option)
virtual void ReplaceLinkLib (const wxString &option, const wxString &new_option)
virtual void RemoveLinkLib (const wxString &option)
virtual void SetCompilerOptions (const wxArrayString &compilerOpts)
virtual const wxArrayString & GetCompilerOptions () const
virtual void AddCompilerOption (const wxString &option)
virtual void ReplaceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveCompilerOption (const wxString &option)
virtual void SetResourceCompilerOptions (const wxArrayString &resourceCompilerOpts)
virtual const wxArrayString & GetResourceCompilerOptions () const
virtual void AddResourceCompilerOption (const wxString &option)
virtual void ReplaceResourceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveResourceCompilerOption (const wxString &option)
virtual void SetIncludeDirs (const wxArrayString &includeDirs)
virtual const wxArrayString & GetIncludeDirs () const
virtual void AddIncludeDir (const wxString &option)
virtual void ReplaceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveIncludeDir (const wxString &option)
virtual void SetResourceIncludeDirs (const wxArrayString &resIncludeDirs)
virtual const wxArrayString & GetResourceIncludeDirs () const
virtual void AddResourceIncludeDir (const wxString &option)
virtual void ReplaceResourceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveResourceIncludeDir (const wxString &option)
virtual void SetLibDirs (const wxArrayString &libDirs)
virtual const wxArrayString & GetLibDirs () const
virtual void AddLibDir (const wxString &option)
virtual void ReplaceLibDir (const wxString &option, const wxString &new_option)
virtual void RemoveLibDir (const wxString &option)
virtual void SetCommandsBeforeBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsBeforeBuild () const
virtual void AddCommandsBeforeBuild (const wxString &command)
virtual void RemoveCommandsBeforeBuild (const wxString &command)
virtual void SetCommandsAfterBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsAfterBuild () const
virtual void AddCommandsAfterBuild (const wxString &command)
virtual void RemoveCommandsAfterBuild (const wxString &command)
virtual void SetBuildScripts (const wxArrayString &scripts)
virtual const wxArrayString & GetBuildScripts () const
virtual void AddBuildScript (const wxString &script)
virtual void RemoveBuildScript (const wxString &script)
virtual bool GetModified () const
virtual void SetModified (bool modified)
virtual bool GetAlwaysRunPostBuildSteps () const
virtual void SetAlwaysRunPostBuildSteps (bool always)
virtual bool SetVar (const wxString &key, const wxString &value, bool onlyIfExists=false)
virtual bool UnsetVar (const wxString &key)
virtual void UnsetAllVars ()
virtual bool HasVar (const wxString &key) const
virtual const wxString & GetVar (const wxString &key) const
virtual const StringHash & GetAllVars () const
Protected Attributes
int m_Platform
wxArrayString m_LinkerOptions
wxArrayString m_LinkLibs
wxArrayString m_CompilerOptions
wxArrayString m_ResourceCompilerOptions
wxArrayString m_IncludeDirs
wxArrayString m_ResIncludeDirs
wxArrayString m_LibDirs
wxArrayString m_CmdsBefore
wxArrayString m_CmdsAfter
wxArrayString m_Scripts
bool m_Modified
bool m_AlwaysRunPostCmds
StringHash m_Vars
Detailed Description
This is a base class for all classes needing compilation parameters.
It offers functions to get/set the following:
Compiler options
Linker options
Compiler include dirs
Resource compiler include dirs
Linker include dirs
Custom commands to be executed before/after build
The settings modification status
These settings are used by the compiler plugins to construct the necessary compilation commands.
Definition at line 28 of file compileoptionsbase.h.
Constructor & Destructor Documentation
CompileOptionsBase()
CompileOptionsBase::CompileOptionsBase ()
Definition at line 21 of file compileoptionsbase.cpp.
~CompileOptionsBase()
CompileOptionsBase::~CompileOptionsBase () virtual
Definition at line 29 of file compileoptionsbase.cpp.
Member Function Documentation
AddBuildScript()
void CompileOptionsBase::AddBuildScript (const wxString & script) virtual
Definition at line 346 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_Scripts, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by ProjectLoader::DoBuild(), ProjectLoader::DoBuildTargetOptions(), ProjectOptionsDlg::OnAddScript(), and ScriptBindings::RegisterBindings().
AddCommandsAfterBuild()
void CompileOptionsBase::AddCommandsAfterBuild (const wxString & command) virtual
Definition at line 340 of file compileoptionsbase.cpp.
References wxArrayString::Add(), m_CmdsAfter, and SetModified().
Referenced by ProjectLoader::DoExtraCommands(), and ScriptBindings::RegisterBindings().
AddCommandsBeforeBuild()
void CompileOptionsBase::AddCommandsBeforeBuild (const wxString & command) virtual
Definition at line 334 of file compileoptionsbase.cpp.
References wxArrayString::Add(), m_CmdsBefore, and SetModified().
Referenced by ProjectLoader::DoExtraCommands(), and ScriptBindings::RegisterBindings().
AddCompilerOption()
void CompileOptionsBase::AddCompilerOption (const wxString & option) virtual
Definition at line 286 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_CompilerOptions, SetModified(), and wxNOT_FOUND.
Referenced by CompilerXML::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), ProjectLoader::DoCompilerOptions(), and ScriptBindings::RegisterBindings().
AddIncludeDir()
void CompileOptionsBase::AddIncludeDir (const wxString & option) virtual
Definition at line 304 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_IncludeDirs, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by CompilerXML::AddPath(), CompilerLCC::AutoDetectInstallationDir(), CompilerGNUARM::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerKeilC51::AutoDetectInstallationDir(), CompilerOW::AutoDetectInstallationDir(), CompilerGDC::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), CompilerMSVC::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), ProjectLoader::DoCompilerOptions(), ProjectLoader::DoIncludesOptions(), CompilerOptionsDlg::OnCopyDirsClick(), and ScriptBindings::RegisterBindings().
AddLibDir()
void CompileOptionsBase::AddLibDir (const wxString & option) virtual
Definition at line 324 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_LibDirs, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by CompilerXML::AddPath(), CompilerLCC::AutoDetectInstallationDir(), CompilerGNUARM::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerKeilC51::AutoDetectInstallationDir(), CompilerOW::AutoDetectInstallationDir(), CompilerGDC::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), CompilerMSVC::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), ProjectLoader::DoLibsOptions(), ProjectLoader::DoLinkerOptions(), CompilerOptionsDlg::OnCopyDirsClick(), and ScriptBindings::RegisterBindings().
AddLinkerOption()
void CompileOptionsBase::AddLinkerOption (const wxString & option) virtual
Definition at line 268 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_LinkerOptions, SetModified(), and wxNOT_FOUND.
Referenced by CompilerXML::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), ProjectLoader::DoLinkerOptions(), and ScriptBindings::RegisterBindings().
AddLinkLib()
void CompileOptionsBase::AddLinkLib (const wxString & option) virtual
Definition at line 277 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_LinkLibs, SetModified(), and wxNOT_FOUND.
Referenced by CompilerXML::AutoDetectInstallationDir(), ProjectLoader::DoLinkerOptions(), CompilerOptionsDlg::OnCopyLibsClick(), and ScriptBindings::RegisterBindings().
AddPlatform()
void CompileOptionsBase::AddPlatform (int platform) virtual
Definition at line 34 of file compileoptionsbase.cpp.
References m_Platform, and SetModified().
Referenced by ScriptBindings::RegisterBindings().
AddResourceCompilerOption()
void CompileOptionsBase::AddResourceCompilerOption (const wxString & option) virtual
Definition at line 295 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_ResourceCompilerOptions, SetModified(), and wxNOT_FOUND.
Referenced by ProjectLoader::DoResourceCompilerOptions(), and ScriptBindings::RegisterBindings().
AddResourceIncludeDir()
void CompileOptionsBase::AddResourceIncludeDir (const wxString & option) virtual
Definition at line 314 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Index(), m_ResIncludeDirs, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by CompilerXML::AddPath(), CompilerOW::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), ProjectLoader::DoResourceCompilerOptions(), CompilerOptionsDlg::OnCopyDirsClick(), and ScriptBindings::RegisterBindings().
GetAllVars()
const StringHash & CompileOptionsBase::GetAllVars () const virtual
Definition at line 574 of file compileoptionsbase.cpp.
References m_Vars.
Referenced by CompilerOptionsDlg::DoFillVars(), ProjectLoader::SaveEnvironment(), and Compiler::SaveSettings().
GetAlwaysRunPostBuildSteps()
bool CompileOptionsBase::GetAlwaysRunPostBuildSteps () const virtual
Definition at line 245 of file compileoptionsbase.cpp.
References m_AlwaysRunPostCmds.
Referenced by CompilerGCC::BuildStateManagement(), CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), and ScriptBindings::RegisterBindings().
GetBuildScripts()
const wxArrayString & CompileOptionsBase::GetBuildScripts () const virtual
Definition at line 214 of file compileoptionsbase.cpp.
References m_Scripts.
Referenced by CompilerOptionsDlg::CompilerOptionsDlg(), CompilerCommandGenerator::DoBuildScripts(), ProjectOptionsDlg::DoCheckScripts(), ProjectLoader::ExportTargetAsProject(), ProjectOptionsDlg::FillScripts(), ProjectOptionsDlg::OnScriptMoveDown(), ProjectOptionsDlg::OnScriptMoveUp(), and ScriptBindings::RegisterBindings().
GetCommandsAfterBuild()
const wxArrayString & CompileOptionsBase::GetCommandsAfterBuild () const virtual
Definition at line 240 of file compileoptionsbase.cpp.
References m_CmdsAfter.
Referenced by CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), DirectCommands::GetPostBuildCommands(), and ScriptBindings::RegisterBindings().
GetCommandsBeforeBuild()
const wxArrayString & CompileOptionsBase::GetCommandsBeforeBuild () const virtual
Definition at line 227 of file compileoptionsbase.cpp.
References m_CmdsBefore.
Referenced by CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), DirectCommands::GetPreBuildCommands(), and ScriptBindings::RegisterBindings().
GetCompilerOptions()
const wxArrayString & CompileOptionsBase::GetCompilerOptions () const virtual
Definition at line 109 of file compileoptionsbase.cpp.
References m_CompilerOptions.
Referenced by NativeParser::AddProjectDefinedMacros(), EditorManager::CollectDefines(), CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), NativeParser::GetCompilerStandardGCC(), ScriptBindings::RegisterBindings(), CompilerCommandGenerator::SetupCompilerOptions(), and CompilerOWGenerator::SetupLinkerOptions().
GetIncludeDirs()
const wxArrayString & CompileOptionsBase::GetIncludeDirs () const virtual
Definition at line 145 of file compileoptionsbase.cpp.
References m_IncludeDirs.
Referenced by NativeParser::AddCompilerDirs(), NativeParser::AddCompilerIncludeDirsToParser(), CompilerICC::AutoDetectInstallationDir(), CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), CompilerCommandGenerator::GetOrderedIncludeDirs(), ScriptBindings::RegisterBindings(), and EditorManager::SwapActiveHeaderSource().
GetLibDirs()
const wxArrayString & CompileOptionsBase::GetLibDirs () const virtual
Definition at line 191 of file compileoptionsbase.cpp.
References m_LibDirs.
Referenced by DirectCommands::AreExternalDepsOutdated(), CompilerICC::AutoDetectInstallationDir(), CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), ScriptBindings::RegisterBindings(), and CompilerOWGenerator::SetupLibrariesDirs().
GetLinkerOptions()
const wxArrayString & CompileOptionsBase::GetLinkerOptions () const virtual
Definition at line 83 of file compileoptionsbase.cpp.
References m_LinkerOptions.
Referenced by CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), CompilerOWGenerator::SetupLinkerOptions(), and CompilerCommandGenerator::SetupLinkerOptions().
GetLinkLibs()
const wxArrayString & CompileOptionsBase::GetLinkLibs () const virtual
Definition at line 96 of file compileoptionsbase.cpp.
References m_LinkLibs.
Referenced by DirectCommands::AreExternalDepsOutdated(), CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), CompilerOWGenerator::SetupLinkLibraries(), and CompilerCommandGenerator::SetupLinkLibraries().
GetModified()
bool CompileOptionsBase::GetModified () const virtual
Reimplemented in cbProject.
Definition at line 258 of file compileoptionsbase.cpp.
References m_Modified.
Referenced by cbProject::GetModified(), cbProject::IsLoaded(), and ScriptBindings::RegisterBindings().
GetPlatforms()
int CompileOptionsBase::GetPlatforms () const virtual
Definition at line 58 of file compileoptionsbase.cpp.
References m_Platform.
Referenced by ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), ProjectOptionsDlg::OnCreateDefFileClick(), ProjectOptionsDlg::OnCreateImportFileClick(), and ScriptBindings::RegisterBindings().
GetResourceCompilerOptions()
const wxArrayString & CompileOptionsBase::GetResourceCompilerOptions () const virtual
Definition at line 122 of file compileoptionsbase.cpp.
References m_ResourceCompilerOptions.
Referenced by CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), and ScriptBindings::RegisterBindings().
GetResourceIncludeDirs()
const wxArrayString & CompileOptionsBase::GetResourceIncludeDirs () const virtual
Definition at line 168 of file compileoptionsbase.cpp.
References m_ResIncludeDirs.
Referenced by CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), CompilerCommandGenerator::GetOrderedResourceIncludeDirs(), and ScriptBindings::RegisterBindings().
GetVar()
const wxString & CompileOptionsBase::GetVar (const wxString & key) const virtual
Definition at line 564 of file compileoptionsbase.cpp.
References m_Vars, and wxEmptyString.
Referenced by ScriptBindings::RegisterBindings().
HasVar()
bool CompileOptionsBase::HasVar (const wxString & key) const virtual
Definition at line 555 of file compileoptionsbase.cpp.
References m_Vars.
RemoveBuildScript()
void CompileOptionsBase::RemoveBuildScript (const wxString & script) virtual
Definition at line 511 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_Scripts, wxArrayString::RemoveAt(), SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by ProjectOptionsDlg::OnRemoveScript(), and ScriptBindings::RegisterBindings().
RemoveCommandsAfterBuild()
void CompileOptionsBase::RemoveCommandsAfterBuild (const wxString & command) virtual
Definition at line 505 of file compileoptionsbase.cpp.
References m_CmdsAfter, wxArrayString::Remove(), and SetModified().
Referenced by ScriptBindings::RegisterBindings().
RemoveCommandsBeforeBuild()
void CompileOptionsBase::RemoveCommandsBeforeBuild (const wxString & command) virtual
Definition at line 499 of file compileoptionsbase.cpp.
References m_CmdsBefore, wxArrayString::Remove(), and SetModified().
Referenced by ScriptBindings::RegisterBindings().
RemoveCompilerOption()
void CompileOptionsBase::RemoveCompilerOption (const wxString & option) virtual
Definition at line 446 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_CompilerOptions, wxArrayString::RemoveAt(), SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
RemoveIncludeDir()
void CompileOptionsBase::RemoveIncludeDir (const wxString & option) virtual
Definition at line 466 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_IncludeDirs, wxArrayString::RemoveAt(), SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
RemoveLibDir()
void CompileOptionsBase::RemoveLibDir (const wxString & option) virtual
Definition at line 488 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_LibDirs, wxArrayString::RemoveAt(), SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
RemoveLinkerOption()
void CompileOptionsBase::RemoveLinkerOption (const wxString & option) virtual
Definition at line 426 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_LinkerOptions, wxArrayString::RemoveAt(), SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
RemoveLinkLib()
void CompileOptionsBase::RemoveLinkLib (const wxString & option) virtual
Definition at line 436 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_LinkLibs, wxArrayString::RemoveAt(), SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
RemovePlatform()
void CompileOptionsBase::RemovePlatform (int platform) virtual
Definition at line 42 of file compileoptionsbase.cpp.
References m_Platform, and SetModified().
Referenced by ScriptBindings::RegisterBindings().
RemoveResourceCompilerOption()
void CompileOptionsBase::RemoveResourceCompilerOption (const wxString & option) virtual
Definition at line 456 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_ResourceCompilerOptions, wxArrayString::RemoveAt(), SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
RemoveResourceIncludeDir()
void CompileOptionsBase::RemoveResourceIncludeDir (const wxString & option) virtual
Definition at line 477 of file compileoptionsbase.cpp.
References wxArrayString::Index(), m_ResIncludeDirs, wxArrayString::RemoveAt(), SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ReplaceCompilerOption()
void CompileOptionsBase::ReplaceCompilerOption (const wxString & option, const wxString & new_option) virtual
Definition at line 376 of file compileoptionsbase.cpp.
References wxArrayString::Index(), wxArrayString::Item(), m_CompilerOptions, SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ReplaceIncludeDir()
void CompileOptionsBase::ReplaceIncludeDir (const wxString & option, const wxString & new_option) virtual
Definition at line 396 of file compileoptionsbase.cpp.
References wxArrayString::Index(), wxArrayString::Item(), m_IncludeDirs, SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ReplaceLibDir()
void CompileOptionsBase::ReplaceLibDir (const wxString & option, const wxString & new_option) virtual
Definition at line 416 of file compileoptionsbase.cpp.
References wxArrayString::Index(), wxArrayString::Item(), m_LibDirs, SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ReplaceLinkerOption()
void CompileOptionsBase::ReplaceLinkerOption (const wxString & option, const wxString & new_option) virtual
Definition at line 356 of file compileoptionsbase.cpp.
References wxArrayString::Index(), wxArrayString::Item(), m_LinkerOptions, SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ReplaceLinkLib()
void CompileOptionsBase::ReplaceLinkLib (const wxString & option, const wxString & new_option) virtual
Definition at line 366 of file compileoptionsbase.cpp.
References wxArrayString::Index(), wxArrayString::Item(), m_LinkLibs, SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ReplaceResourceCompilerOption()
void CompileOptionsBase::ReplaceResourceCompilerOption (const wxString & option, const wxString & new_option) virtual
Definition at line 386 of file compileoptionsbase.cpp.
References wxArrayString::Index(), wxArrayString::Item(), m_ResourceCompilerOptions, SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
ReplaceResourceIncludeDir()
void CompileOptionsBase::ReplaceResourceIncludeDir (const wxString & option, const wxString & new_option) virtual
Definition at line 406 of file compileoptionsbase.cpp.
References wxArrayString::Index(), wxArrayString::Item(), m_ResIncludeDirs, SetModified(), and wxNOT_FOUND.
Referenced by ScriptBindings::RegisterBindings().
SetAlwaysRunPostBuildSteps()
void CompileOptionsBase::SetAlwaysRunPostBuildSteps (bool always) virtual
Definition at line 250 of file compileoptionsbase.cpp.
References m_AlwaysRunPostCmds, and SetModified().
Referenced by ProjectLoader::DoExtraCommands(), CompilerOptionsDlg::DoSaveOptions(), and ScriptBindings::RegisterBindings().
SetBuildScripts()
void CompileOptionsBase::SetBuildScripts (const wxArrayString & scripts) virtual
Definition at line 196 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Clear(), wxArrayString::GetCount(), wxArrayString::Index(), m_Scripts, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by ProjectOptionsDlg::OnScriptMoveDown(), ProjectOptionsDlg::OnScriptMoveUp(), and ScriptBindings::RegisterBindings().
SetCommandsAfterBuild()
void CompileOptionsBase::SetCommandsAfterBuild (const wxArrayString & commands) virtual
Definition at line 232 of file compileoptionsbase.cpp.
References m_CmdsAfter, and SetModified().
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetCommandsBeforeBuild()
void CompileOptionsBase::SetCommandsBeforeBuild (const wxArrayString & commands) virtual
Definition at line 219 of file compileoptionsbase.cpp.
References m_CmdsBefore, and SetModified().
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetCompilerOptions()
void CompileOptionsBase::SetCompilerOptions (const wxArrayString & compilerOpts) virtual
Definition at line 101 of file compileoptionsbase.cpp.
References m_CompilerOptions, and SetModified().
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetIncludeDirs()
void CompileOptionsBase::SetIncludeDirs (const wxArrayString & includeDirs) virtual
Definition at line 127 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Clear(), wxArrayString::GetCount(), wxArrayString::Index(), m_IncludeDirs, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetLibDirs()
void CompileOptionsBase::SetLibDirs (const wxArrayString & libDirs) virtual
Definition at line 173 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Clear(), wxArrayString::GetCount(), wxArrayString::Index(), m_LibDirs, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetLinkerOptions()
void CompileOptionsBase::SetLinkerOptions (const wxArrayString & linkerOpts) virtual
Definition at line 75 of file compileoptionsbase.cpp.
References m_LinkerOptions, and SetModified().
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetLinkLibs()
void CompileOptionsBase::SetLinkLibs (const wxArrayString & linkLibs) virtual
Definition at line 88 of file compileoptionsbase.cpp.
References m_LinkLibs, and SetModified().
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetModified()
void CompileOptionsBase::SetModified (bool modified) virtual
Reimplemented in cbProject.
Definition at line 263 of file compileoptionsbase.cpp.
References m_Modified.
Referenced by AddBuildScript(), AddCommandsAfterBuild(), AddCommandsBeforeBuild(), AddCompilerOption(), AddIncludeDir(), AddLibDir(), AddLinkerOption(), AddLinkLib(), AddPlatform(), AddResourceCompilerOption(), AddResourceIncludeDir(), cbProject::IsLoaded(), ScriptBindings::RegisterBindings(), RemoveBuildScript(), RemoveCommandsAfterBuild(), RemoveCommandsBeforeBuild(), RemoveCompilerOption(), RemoveIncludeDir(), RemoveLibDir(), RemoveLinkerOption(), RemoveLinkLib(), RemovePlatform(), RemoveResourceCompilerOption(), RemoveResourceIncludeDir(), ReplaceCompilerOption(), ReplaceIncludeDir(), ReplaceLibDir(), ReplaceLinkerOption(), ReplaceLinkLib(), ReplaceResourceCompilerOption(), ReplaceResourceIncludeDir(), ProjectBuildTarget::SetAdditionalOutputFiles(), SetAlwaysRunPostBuildSteps(), SetBuildScripts(), SetCommandsAfterBuild(), SetCommandsBeforeBuild(), CompileTargetBase::SetCompilerID(), SetCompilerOptions(), ProjectBuildTarget::SetCreateDefFile(), ProjectBuildTarget::SetCreateStaticLib(), CompileTargetBase::SetDefinitionFileFilename(), CompileTargetBase::SetDepsOutput(), CompileTargetBase::SetExecutionParameters(), ProjectBuildTarget::SetExternalDeps(), CompileTargetBase::SetHostApplication(), CompileTargetBase::SetImportLibraryFilename(), SetIncludeDirs(), ProjectBuildTarget::SetIncludeInTargetAll(), SetLibDirs(), SetLinkerOptions(), SetLinkLibs(), CompileTargetBase::SetMakeCommandFor(), cbProject::SetMakefile(), cbProject::SetModeForPCH(), cbProject::SetModified(), CompileTargetBase::SetObjectOutput(), CompileTargetBase::SetOptionRelation(), CompileTargetBase::SetOutputFilename(), SetPlatforms(), SetResourceCompilerOptions(), SetResourceIncludeDirs(), CompileTargetBase::SetRunHostApplicationInTerminal(), CompileTargetBase::SetTargetFilenameGenerationPolicy(), CompileTargetBase::SetTargetType(), CompileTargetBase::SetTitle(), ProjectBuildTarget::SetUseConsoleRunner(), SetVar(), CompileTargetBase::SetWorkingDir(), and UnsetVar().
SetPlatforms()
void CompileOptionsBase::SetPlatforms (int platforms) virtual
Definition at line 50 of file compileoptionsbase.cpp.
References m_Platform, and SetModified().
Referenced by ProjectOptionsDlg::DoBeforeTargetChange(), ProjectLoader::DoBuildTargetOptions(), ProjectLoader::DoProjectOptions(), ProjectOptionsDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetResourceCompilerOptions()
void CompileOptionsBase::SetResourceCompilerOptions (const wxArrayString & resourceCompilerOpts) virtual
Definition at line 114 of file compileoptionsbase.cpp.
References m_ResourceCompilerOptions, and SetModified().
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetResourceIncludeDirs()
void CompileOptionsBase::SetResourceIncludeDirs (const wxArrayString & resIncludeDirs) virtual
Definition at line 150 of file compileoptionsbase.cpp.
References wxArrayString::Add(), wxArrayString::Clear(), wxArrayString::GetCount(), wxArrayString::Index(), m_ResIncludeDirs, SetModified(), UnixFilename(), and wxNOT_FOUND.
Referenced by CompilerOptionsDlg::DoSaveOptions(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SetVar()
bool CompileOptionsBase::SetVar (const wxString & key, const wxString & value, bool onlyIfExists = false) virtual
Definition at line 522 of file compileoptionsbase.cpp.
References m_Vars, and SetModified().
Referenced by ProjectLoader::DoEnvironment(), CompilerOptionsDlg::DoSaveVars(), Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
SupportsCurrentPlatform()
bool CompileOptionsBase::SupportsCurrentPlatform () const virtual
Definition at line 63 of file compileoptionsbase.cpp.
References m_Platform, spMac, spUnix, and spWindows.
Referenced by NativeParser::AddCompilerDirs(), NativeParser::AddCompilerIncludeDirsToParser(), NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), NativeParser::AddProjectDefinedMacros(), CompilerOptionsDlg::CompilerOptionsDlg(), NativeParser::DoFullParsing(), CompilerCommandGenerator::GenerateCommandLine(), CompilerCommandGenerator::Init(), Compiler::IsValid(), CompilerGCC::IsValidTarget(), Compiler::MakeInvalidCompilerMessages(), CompilerOptionsDlg::OnTreeSelectionChange(), CompilerGCC::PreprocessJob(), ScriptBindings::RegisterBindings(), and CompilerGCC::UpdateProjectTargets().
UnsetAllVars()
void CompileOptionsBase::UnsetAllVars () virtual
Definition at line 550 of file compileoptionsbase.cpp.
References m_Vars.
Referenced by Compiler::LoadSettings(), and ScriptBindings::RegisterBindings().
UnsetVar()
bool CompileOptionsBase::UnsetVar (const wxString & key) virtual
Definition at line 538 of file compileoptionsbase.cpp.
References m_Vars, and SetModified().
Referenced by CompilerOptionsDlg::DoSaveVars(), and ScriptBindings::RegisterBindings().
Member Data Documentation
m_AlwaysRunPostCmds
bool CompileOptionsBase::m_AlwaysRunPostCmds protected
Definition at line 122 of file compileoptionsbase.h.
Referenced by GetAlwaysRunPostBuildSteps(), and SetAlwaysRunPostBuildSteps().
m_CmdsAfter
wxArrayString CompileOptionsBase::m_CmdsAfter protected
Definition at line 119 of file compileoptionsbase.h.
Referenced by AddCommandsAfterBuild(), Compiler::Compiler(), GetCommandsAfterBuild(), Compiler::MirrorCurrentSettings(), RemoveCommandsAfterBuild(), CompilerLCC::Reset(), Compiler::Reset(), Compiler::SaveSettings(), and SetCommandsAfterBuild().
m_CmdsBefore
wxArrayString CompileOptionsBase::m_CmdsBefore protected
Definition at line 118 of file compileoptionsbase.h.
Referenced by AddCommandsBeforeBuild(), Compiler::Compiler(), GetCommandsBeforeBuild(), Compiler::MirrorCurrentSettings(), RemoveCommandsBeforeBuild(), CompilerLCC::Reset(), Compiler::Reset(), Compiler::SaveSettings(), and SetCommandsBeforeBuild().
m_CompilerOptions
wxArrayString CompileOptionsBase::m_CompilerOptions protected
Definition at line 113 of file compileoptionsbase.h.
Referenced by AddCompilerOption(), cbProject::ClearAllProperties(), Compiler::Compiler(), GetCompilerOptions(), Compiler::MirrorCurrentSettings(), RemoveCompilerOption(), ReplaceCompilerOption(), CompilerLCC::Reset(), Compiler::Reset(), Compiler::SaveSettings(), and SetCompilerOptions().
m_IncludeDirs
wxArrayString CompileOptionsBase::m_IncludeDirs protected
Definition at line 115 of file compileoptionsbase.h.
Referenced by AddIncludeDir(), CompilerXML::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), cbProject::ClearAllProperties(), Compiler::Compiler(), GetIncludeDirs(), Compiler::MirrorCurrentSettings(), RemoveIncludeDir(), ReplaceIncludeDir(), Compiler::SaveSettings(), and SetIncludeDirs().
m_LibDirs
wxArrayString CompileOptionsBase::m_LibDirs protected
Definition at line 117 of file compileoptionsbase.h.
Referenced by AddLibDir(), CompilerXML::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), cbProject::ClearAllProperties(), Compiler::Compiler(), GetLibDirs(), Compiler::MirrorCurrentSettings(), RemoveLibDir(), ReplaceLibDir(), Compiler::SaveSettings(), and SetLibDirs().
m_LinkerOptions
wxArrayString CompileOptionsBase::m_LinkerOptions protected
Definition at line 111 of file compileoptionsbase.h.
Referenced by AddLinkerOption(), cbProject::ClearAllProperties(), Compiler::Compiler(), GetLinkerOptions(), Compiler::MirrorCurrentSettings(), RemoveLinkerOption(), ReplaceLinkerOption(), CompilerLCC::Reset(), Compiler::Reset(), Compiler::SaveSettings(), and SetLinkerOptions().
m_LinkLibs
wxArrayString CompileOptionsBase::m_LinkLibs protected
Definition at line 112 of file compileoptionsbase.h.
Referenced by AddLinkLib(), Compiler::Compiler(), GetLinkLibs(), Compiler::MirrorCurrentSettings(), RemoveLinkLib(), ReplaceLinkLib(), CompilerLCC::Reset(), Compiler::Reset(), Compiler::SaveSettings(), and SetLinkLibs().
m_Modified
bool CompileOptionsBase::m_Modified protected
Definition at line 121 of file compileoptionsbase.h.
Referenced by GetModified(), and SetModified().
m_Platform
int CompileOptionsBase::m_Platform protected
Definition at line 110 of file compileoptionsbase.h.
Referenced by AddPlatform(), GetPlatforms(), RemovePlatform(), SetPlatforms(), and SupportsCurrentPlatform().
m_ResIncludeDirs
wxArrayString CompileOptionsBase::m_ResIncludeDirs protected
Definition at line 116 of file compileoptionsbase.h.
Referenced by AddResourceIncludeDir(), CompilerXML::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), Compiler::Compiler(), GetResourceIncludeDirs(), Compiler::MirrorCurrentSettings(), RemoveResourceIncludeDir(), ReplaceResourceIncludeDir(), Compiler::SaveSettings(), and SetResourceIncludeDirs().
m_ResourceCompilerOptions
wxArrayString CompileOptionsBase::m_ResourceCompilerOptions protected
Definition at line 114 of file compileoptionsbase.h.
Referenced by AddResourceCompilerOption(), GetResourceCompilerOptions(), RemoveResourceCompilerOption(), ReplaceResourceCompilerOption(), Compiler::SaveSettings(), and SetResourceCompilerOptions().
m_Scripts
wxArrayString CompileOptionsBase::m_Scripts protected
Definition at line 120 of file compileoptionsbase.h.
Referenced by AddBuildScript(), GetBuildScripts(), RemoveBuildScript(), and SetBuildScripts().
m_Vars
StringHash CompileOptionsBase::m_Vars protected
Definition at line 123 of file compileoptionsbase.h.
Referenced by GetAllVars(), GetVar(), HasVar(), SetVar(), UnsetAllVars(), and UnsetVar().
The documentation for this class was generated from the following files:
compileoptionsbase.h
compileoptionsbase.cpp