Code::Blocks: DebugInterfaceFactory Class Reference
DebugInterfaceFactory Class Reference
#include <debugger_interface_creator.h>
Public Member Functions
DebugInterfaceFactory ()
~DebugInterfaceFactory ()
virtual cbBacktraceDlg * CreateBacktrace ()
virtual void DeleteBacktrace (cbBacktraceDlg *dialog)
virtual cbBreakpointsDlg * CreateBreapoints ()
virtual void DeleteBreakpoints (cbBreakpointsDlg *dialog)
virtual cbCPURegistersDlg * CreateCPURegisters ()
virtual void DeleteCPURegisters (cbCPURegistersDlg *dialog)
virtual cbDisassemblyDlg * CreateDisassembly ()
virtual void DeleteDisassembly (cbDisassemblyDlg *dialog)
virtual cbExamineMemoryDlg * CreateMemory ()
virtual void DeleteMemory (cbExamineMemoryDlg *dialog)
virtual cbThreadsDlg * CreateThreads ()
virtual void DeleteThreads (cbThreadsDlg *dialog)
virtual cbWatchesDlg * CreateWatches ()
virtual void DeleteWatches (cbWatchesDlg *dialog)
virtual bool ShowValueTooltip (const cb::shared_ptr< cbWatch > &watch, const wxRect &rect)
Show new value tooltip.
virtual void HideValueTooltip ()
virtual bool IsValueTooltipShown ()
virtual void UpdateValueTooltip ()
Public Member Functions inherited from cbDebugInterfaceFactory
cbDebugInterfaceFactory ()
virtual ~cbDebugInterfaceFactory ()
Private Member Functions
void OnEditorDeactivate (CodeBlocksEvent &event)
Private Attributes
ValueTooltip * m_tooltip
Detailed Description
Definition at line 13 of file debugger_interface_creator.h.
Constructor & Destructor Documentation
DebugInterfaceFactory()
DebugInterfaceFactory::DebugInterfaceFactory ()
Definition at line 36 of file debugger_interface_creator.cpp.
References cbEVT_EDITOR_DEACTIVATED, Manager::Get(), OnEditorDeactivate(), and Manager::RegisterEventSink().
~DebugInterfaceFactory()
DebugInterfaceFactory::~DebugInterfaceFactory ()
Definition at line 43 of file debugger_interface_creator.cpp.
References Manager::Get(), and Manager::RemoveAllEventSinksFor().
Member Function Documentation
CreateBacktrace()
cbBacktraceDlg * DebugInterfaceFactory::CreateBacktrace () virtual
Implements cbDebugInterfaceFactory.
Definition at line 48 of file debugger_interface_creator.cpp.
References _(), _T, cbEVT_ADD_DOCK_WINDOW, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::floatingSize, Manager::Get(), CodeBlocksDockEvent::minimumSize, CodeBlocksDockEvent::name, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxSize::Set(), and CodeBlocksDockEvent::title.
CreateBreapoints()
cbBreakpointsDlg * DebugInterfaceFactory::CreateBreapoints () virtual
Implements cbDebugInterfaceFactory.
Definition at line 69 of file debugger_interface_creator.cpp.
References _(), _T, cbEVT_ADD_DOCK_WINDOW, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::floatingSize, Manager::Get(), CodeBlocksDockEvent::minimumSize, CodeBlocksDockEvent::name, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxSize::Set(), and CodeBlocksDockEvent::title.
CreateCPURegisters()
cbCPURegistersDlg * DebugInterfaceFactory::CreateCPURegisters () virtual
Implements cbDebugInterfaceFactory.
Definition at line 91 of file debugger_interface_creator.cpp.
References _(), _T, cbEVT_ADD_DOCK_WINDOW, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::floatingSize, Manager::Get(), CodeBlocksDockEvent::minimumSize, CodeBlocksDockEvent::name, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxSize::Set(), and CodeBlocksDockEvent::title.
CreateDisassembly()
cbDisassemblyDlg * DebugInterfaceFactory::CreateDisassembly () virtual
Implements cbDebugInterfaceFactory.
Definition at line 113 of file debugger_interface_creator.cpp.
References _(), _T, cbEVT_ADD_DOCK_WINDOW, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::floatingSize, Manager::Get(), CodeBlocksDockEvent::minimumSize, CodeBlocksDockEvent::name, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxSize::Set(), and CodeBlocksDockEvent::title.
CreateMemory()
cbExamineMemoryDlg * DebugInterfaceFactory::CreateMemory () virtual
Implements cbDebugInterfaceFactory.
Definition at line 135 of file debugger_interface_creator.cpp.
References _(), _T, cbEVT_ADD_DOCK_WINDOW, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::floatingSize, Manager::Get(), CodeBlocksDockEvent::minimumSize, CodeBlocksDockEvent::name, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxSize::Set(), and CodeBlocksDockEvent::title.
CreateThreads()
cbThreadsDlg * DebugInterfaceFactory::CreateThreads () virtual
Implements cbDebugInterfaceFactory.
Definition at line 156 of file debugger_interface_creator.cpp.
References _(), _T, cbEVT_ADD_DOCK_WINDOW, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::floatingSize, Manager::Get(), CodeBlocksDockEvent::minimumSize, CodeBlocksDockEvent::name, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxSize::Set(), and CodeBlocksDockEvent::title.
CreateWatches()
cbWatchesDlg * DebugInterfaceFactory::CreateWatches () virtual
Implements cbDebugInterfaceFactory.
Definition at line 178 of file debugger_interface_creator.cpp.
References _(), _T, cbEVT_ADD_DOCK_WINDOW, CodeBlocksDockEvent::desiredSize, CodeBlocksDockEvent::dockSide, CodeBlocksDockEvent::dsFloating, CodeBlocksDockEvent::floatingSize, Manager::Get(), CodeBlocksDockEvent::minimumSize, CodeBlocksDockEvent::name, Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, wxSize::Set(), and CodeBlocksDockEvent::title.
DeleteBacktrace()
void DebugInterfaceFactory::DeleteBacktrace (cbBacktraceDlg * dialog) virtual
Implements cbDebugInterfaceFactory.
Definition at line 63 of file debugger_interface_creator.cpp.
References cbBacktraceDlg::GetWindow(), and RemoveDockWindow().
DeleteBreakpoints()
void DebugInterfaceFactory::DeleteBreakpoints (cbBreakpointsDlg * dialog) virtual
Implements cbDebugInterfaceFactory.
Definition at line 85 of file debugger_interface_creator.cpp.
References cbBreakpointsDlg::GetWindow(), and RemoveDockWindow().
DeleteCPURegisters()
void DebugInterfaceFactory::DeleteCPURegisters (cbCPURegistersDlg * dialog) virtual
Implements cbDebugInterfaceFactory.
Definition at line 107 of file debugger_interface_creator.cpp.
References cbCPURegistersDlg::GetWindow(), and RemoveDockWindow().
DeleteDisassembly()
void DebugInterfaceFactory::DeleteDisassembly (cbDisassemblyDlg * dialog) virtual
Implements cbDebugInterfaceFactory.
Definition at line 129 of file debugger_interface_creator.cpp.
References cbDisassemblyDlg::GetWindow(), and RemoveDockWindow().
DeleteMemory()
void DebugInterfaceFactory::DeleteMemory (cbExamineMemoryDlg * dialog) virtual
Implements cbDebugInterfaceFactory.
Definition at line 150 of file debugger_interface_creator.cpp.
References cbExamineMemoryDlg::GetWindow(), and RemoveDockWindow().
DeleteThreads()
void DebugInterfaceFactory::DeleteThreads (cbThreadsDlg * dialog) virtual
Implements cbDebugInterfaceFactory.
Definition at line 172 of file debugger_interface_creator.cpp.
References cbThreadsDlg::GetWindow(), and RemoveDockWindow().
DeleteWatches()
void DebugInterfaceFactory::DeleteWatches (cbWatchesDlg * dialog) virtual
Implements cbDebugInterfaceFactory.
Definition at line 193 of file debugger_interface_creator.cpp.
References cbWatchesDlg::GetWindow(), and RemoveDockWindow().
HideValueTooltip()
void DebugInterfaceFactory::HideValueTooltip () virtual
Implements cbDebugInterfaceFactory.
Definition at line 224 of file debugger_interface_creator.cpp.
References ValueTooltip::Dismiss(), and m_tooltip.
Referenced by OnEditorDeactivate().
IsValueTooltipShown()
bool DebugInterfaceFactory::IsValueTooltipShown () virtual
Implements cbDebugInterfaceFactory.
Definition at line 236 of file debugger_interface_creator.cpp.
References m_tooltip.
OnEditorDeactivate()
void DebugInterfaceFactory::OnEditorDeactivate (CodeBlocksEvent & event) private
Definition at line 241 of file debugger_interface_creator.cpp.
References HideValueTooltip().
Referenced by DebugInterfaceFactory().
ShowValueTooltip()
bool DebugInterfaceFactory::ShowValueTooltip (const cb::shared_ptr< cbWatch > & watch, const wxRect & rect) virtual
Show new value tooltip.
Returns
Return True only if new tooltip was shown, else return False.
Implements cbDebugInterfaceFactory.
Definition at line 199 of file debugger_interface_creator.cpp.
References wxScintilla::CallTipActive(), cbStyledTextCtrl::CallTipCancel(), wxRect::Contains(), Manager::Get(), EditorManager::GetActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), EditorBase::IsBuiltinEditor(), m_tooltip, and wxGetMousePosition().
UpdateValueTooltip()
void DebugInterfaceFactory::UpdateValueTooltip () virtual
Implements cbDebugInterfaceFactory.
Definition at line 230 of file debugger_interface_creator.cpp.
References m_tooltip, and ValueTooltip::UpdateWatch().
Member Data Documentation
m_tooltip
ValueTooltip* DebugInterfaceFactory::m_tooltip private
Definition at line 48 of file debugger_interface_creator.h.
Referenced by HideValueTooltip(), IsValueTooltipShown(), ShowValueTooltip(), and UpdateValueTooltip().
The documentation for this class was generated from the following files:
debugger_interface_creator.h
debugger_interface_creator.cpp