Code::Blocks: wxScrollingDialog Class Reference
wxScrollingDialog Class Reference
#include <scrollingdialog.h>
Inherits wxDialog, and wxDialogHelper.
Inherited by AdvancedCompilerOptionsDlg, AnnoyingDialog, AskAssocDialog, AutoDetectCompilers, BatchLogWindow, cbConfigurationDialog, CCDebugInfo, CompilerSettingsDlg, ConfigureToolsDlg, ConfirmReplaceDlg, DataBreakpointDlg, DebuggerInfoWindow, DebuggerSettingsDlg, dlgAbout, dlgAboutPlugin, EditArrayFileDlg, EditArrayOrderDlg, EditArrayStringDlg, EditBreakpointDlg, EditKeywordsDlg, EditorConfigurationDlg, EditPairDlg, EditPathDlg, EditToolDlg, EditWatchDlg, EnvironmentSettingsDlg, ExternalDepsDlg, FindReplaceBase, GenericMultiLineNotesDlg, IncrementalSelectListDlg, InsertClassMethodDlg, ManageAssocsDialog, MultiSelectDlg, NewFromTemplateDlg, PluginsConfigurationDlg, PrintDialog, ProjectDepsDlg, ProjectFileOptionsDlg, ProjectOptionsDlg, ProjectsFileMasksDlg, ScriptBindings::XrcDialog, ScriptingSettingsDlg, ScriptSecurityWarningDlg, SelectIncludeFile, SelectTargetDlg, UsrGlblMgrEditDialog, VirtualBuildTargetsDlg, WatchRawDialog, and wxSwitcherDialog.
Public Member Functions
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
A class that makes its content scroll if necessary
Constructor & Destructor Documentation
wxScrollingDialog::wxScrollingDialog () inline
References Init().
wxScrollingDialog::wxScrollingDialog (wxWindow * parent, int id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE, const wxString & name = _("dialogBox")) inline
References Create(), and Init().
Member Function Documentation
bool wxScrollingDialog::Create (wxWindow * parent, int id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE, const wxString & name = _("dialogBox"))
Referenced by wxSwitcherDialog::Create(), and wxScrollingDialog().
void wxScrollingDialog::Init ()
wxScrollingDialog
References wxDialogHelper::SetDialog().
Referenced by AnnoyingDialog::AnnoyingDialog(), MultiSelectDlg::MultiSelectDlg(), and wxScrollingDialog().
bool wxScrollingDialog::Show (bool show = true) virtual
Override Show to rejig the control and sizer hierarchy if necessary.
References wxDialogHelper::CanDoLayoutAdaptation(), and wxDialogHelper::DoLayoutAdaptation().
Referenced by CodeBlocksApp::BatchJob(), and WatchRawDialogAdapter::DoShowDialog().
int wxScrollingDialog::ShowModal () virtual
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Reimplemented in AnnoyingDialog.
References wxDialogHelper::CanDoLayoutAdaptation(), and wxDialogHelper::DoLayoutAdaptation().
Referenced by DebuggerGDB::AddDataBreakpoint(), UserVariableManager::Arrogate(), ProjectManagerUI::AskForMultiBuildTargetIndex(), CodeBlocksApp::BatchJob(), EditorManager::CheckForExternallyModifiedFiles(), ProjectManagerUI::CheckForExternallyModifiedProjects(), UserVariableManager::Configure(), ToolsManager::Configure(), PluginManager::Configure(), CompilerGCC::Configure(), ProjectManagerUI::ConfigureProjectDependencies(), ScriptingManager::DisplayErrors(), CodeCompletion::DoAllMethodsImpl(), ConfigureToolsDlg::DoEditTool(), CodeBlocksApp::InitAssociations(), CompilerFactory::LoadSettings(), TemplateManager::New(), CompilerOptionsDlg::OnAddExtraPathClick(), ProjectManagerUI::OnAddFilesToProjectRecursively(), CCOptionsDlg::OnAddRepl(), CompilerOptionsDlg::OnAddVarClick(), CompilerOptionsDlg::OnAdvancedClick(), ProjectOptionsDlg::OnBuildOrderClick(), cbEditor::OnContextMenuEntry(), ProjectOptionsDlg::OnEditDepsClick(), CompilerOptionsDlg::OnEditExtraPathClick(), CCOptionsDlg::OnEditRepl(), CompilerOptionsDlg::OnEditVarClick(), MainFrame::OnFilePrint(), ProjectManagerUI::OnFindFile(), CodeCompletion::OnGotoDeclaration(), CodeCompletion::OnGotoFunction(), MainFrame::OnHelpAbout(), MainFrame::OnHelpPluginMenu(), EnvironmentSettingsDlg::OnManageAssocs(), CodeCompletion::OnOpenIncludeFile(), ProjectOptionsDlg::OnPlatform(), EditorManager::OnProperties(), ProjectManagerUI::OnRemoveFileFromProject(), MainFrame::OnSettingsCompiler(), MainFrame::OnSettingsDebugger(), MainFrame::OnSettingsEditor(), MainFrame::OnSettingsScripting(), MainFrame::OnSwitchTabs(), ClassBrowser::OnTreeItemDoubleClick(), ProjectManagerUI::OnViewFileMasks(), ProjectOptionsDlg::OnVirtualTargets(), DebuggerInfoCmd::ParseOutput(), FindReplace::Replace(), UserVariableManager::Replace(), FindReplace::ReplaceInFiles(), ScriptBindings::IOLib::SecurityAllows(), cbProject::SelectTarget(), ScriptBindings::ShowDialog(), FindReplace::ShowFindDialog(), AnnoyingDialog::ShowModal(), ScriptBindings::ShowModalForDialogs(), cbProject::ShowNotes(), ProjectFile::ShowOptions(), and DebuggerGDB::UpdateBreakpoint().
The documentation for this class was generated from the following files:
scrollingdialog.h
scrollingdialog.cpp