Code::Blocks: WatchesDropTarget Class Reference
WatchesDropTarget Class Reference
Public Member Functions
virtual bool OnDropText (wxCoord WXUNUSED(x), wxCoord WXUNUSED(y), const wxString &text)
virtual wxDragResult OnDragOver (wxCoord WXUNUSED(x), wxCoord WXUNUSED(y), wxDragResult WXUNUSED(def))
Public Member Functions inherited from wxTextDropTarget
wxTextDropTarget ()
virtual bool OnDrop (wxCoord x, wxCoord y)
virtual bool OnDropText (wxCoord x, wxCoord y, const wxString &data)=0
Public Member Functions inherited from wxDropTarget
wxDropTarget (wxDataObject *data=NULL)
virtual ~wxDropTarget ()
virtual bool GetData ()
virtual wxDragResult OnData (wxCoord x, wxCoord y, wxDragResult defResult)=0
virtual wxDragResult OnDragOver (wxCoord x, wxCoord y, wxDragResult defResult)
virtual wxDragResult OnEnter (wxCoord x, wxCoord y, wxDragResult defResult)
virtual void OnLeave ()
wxDataObject * GetDataObject () const
void SetDataObject (wxDataObject *data)
void SetDefaultAction (wxDragResult action)
wxDragResult GetDefaultAction ()
Detailed Description
Definition at line 338 of file watchesdlg.cpp.
Member Function Documentation
OnDragOver()
virtual wxDragResult WatchesDropTarget::OnDragOver (wxCoord WXUNUSEDx, wxCoord WXUNUSEDy, wxDragResult WXUNUSEDdef) inline virtual
Definition at line 353 of file watchesdlg.cpp.
References wxDragCopy.
OnDropText()
virtual bool WatchesDropTarget::OnDropText (wxCoord WXUNUSEDx, wxCoord WXUNUSEDy, const wxString & text) inline virtual
Definition at line 341 of file watchesdlg.cpp.
References cbWatchesDlg::AddWatch(), cbDebuggerPlugin::AddWatch(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), DebuggerManager::GetWatchesDialog(), cbDebuggerPlugin::SupportsFeature(), and cbDebuggerFeature::Watches.
The documentation for this class was generated from the following file:
watchesdlg.cpp