Code::Blocks: CdbCmd_Watch Class Reference
CdbCmd_Watch Class Reference
#include <cdb_commands.h>
Public Member Functions
CdbCmd_Watch (DebuggerDriver *driver, cb::shared_ptr< GDBWatch > const &watch)
void ParseOutput (const wxString &output)
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
virtual bool IsContinueCommand () const
Private Attributes
cb::shared_ptr< GDBWatch > m_watch
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to get info about a watched variable.
Constructor & Destructor Documentation
CdbCmd_Watch::CdbCmd_Watch (DebuggerDriver * driver, cb::shared_ptr< GDBWatch > const & watch) inline
References DebuggerCmd::m_Cmd.
Member Function Documentation
void CdbCmd_Watch::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
References Manager::Get(), Manager::GetLogManager(), LogManager::LogError(), and ParseCDBWatchValue().
Member Data Documentation
cb::shared_ptr<GDBWatch> CdbCmd_Watch::m_watch private
The documentation for this class was generated from the following file:
cdb_commands.h