Code::Blocks: ScopeTreeData Class Reference
ScopeTreeData Class Reference
Public Member Functions
ScopeTreeData (cbProject *project, ProjectBuildTarget *target)
cbProject * GetProject ()
ProjectBuildTarget * GetTarget ()
Public Member Functions inherited from wxTreeItemData
wxTreeItemData ()
virtual ~wxTreeItemData ()
const wxTreeItemId & GetId () const
void SetId (const wxTreeItemId &id)
Public Member Functions inherited from wxClientData
wxClientData ()
virtual ~wxClientData ()
Private Attributes
cbProject * m_Project
ProjectBuildTarget * m_Target
Detailed Description
Definition at line 191 of file compileroptionsdlg.cpp.
Constructor & Destructor Documentation
ScopeTreeData()
ScopeTreeData::ScopeTreeData (cbProject * project, ProjectBuildTarget * target) inline
Definition at line 194 of file compileroptionsdlg.cpp.
Member Function Documentation
GetProject()
cbProject* ScopeTreeData::GetProject () inline
Definition at line 195 of file compileroptionsdlg.cpp.
Referenced by CompilerOptionsDlg::OnTreeSelectionChange().
GetTarget()
ProjectBuildTarget* ScopeTreeData::GetTarget () inline
Definition at line 196 of file compileroptionsdlg.cpp.
Referenced by CompilerOptionsDlg::OnTreeSelectionChange(), and CompilerOptionsDlg::OnUpdateUI().
Member Data Documentation
m_Project
cbProject* ScopeTreeData::m_Project private
Definition at line 198 of file compileroptionsdlg.cpp.
m_Target
ProjectBuildTarget* ScopeTreeData::m_Target private
Definition at line 199 of file compileroptionsdlg.cpp.
The documentation for this class was generated from the following file:
compileroptionsdlg.cpp