Code::Blocks: Manager Class Reference
Manager Class Reference
#include <manager.h>
Public Member Functions
bool ProcessEvent (CodeBlocksEvent &event)
bool ProcessEvent (CodeBlocksDockEvent &event)
bool ProcessEvent (CodeBlocksLayoutEvent &event)
bool ProcessEvent (CodeBlocksLogEvent &event)
wxFrame * GetAppFrame () const
wxWindow * GetAppWindow () const
ProjectManager * GetProjectManager () const
Functions returning pointers to the respective sub-manager instances.
EditorManager * GetEditorManager () const
LogManager * GetLogManager () const
PluginManager * GetPluginManager () const
ToolsManager * GetToolsManager () const
MacrosManager * GetMacrosManager () const
PersonalityManager * GetPersonalityManager () const
UserVariableManager * GetUserVariableManager () const
ScriptingManager * GetScriptingManager () const
ConfigManager * GetConfigManager (const wxString &name_space) const
FileManager * GetFileManager () const
DebuggerManager * GetDebuggerManager () const
ColourManager * GetColourManager () const
CCManager * GetCCManager () const
wxToolBar * CreateEmptyToolbar ()
void RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksEvent > *functor)
void RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksDockEvent > *functor)
void RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksLayoutEvent > *functor)
void RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksLogEvent > *functor)
void RemoveAllEventSinksFor (void *owner)
cbSearchResultsLog * GetSearchResultLogger () const
Returns pointer to the search result logger, might be nullptr or hidden.
void SetSearchResultLogger (cbSearchResultsLog *log)
Sets the pointer to the search result logger, users must not call this method.
Static Public Member Functions
static void SetAppStartedUp (bool app_started_up)
static void SetAppShuttingDown (bool app_shutting_down)
static void SetBatchBuild (bool is_batch)
static bool IsBatchBuild ()
static void BlockYields (bool block)
Blocks/unblocks Manager::Yield(). Be careful when using it. Actually, do not use it ;)
static void Yield ()
Whenever you need to call wxYield(), call Manager::Yield(). It's safer.
static void ProcessPendingEvents ()
static void Shutdown ()
static Manager * Get ()
Use Manager::Get() to get a pointer to its instance Manager::Get() is guaranteed to never return an invalid pointer.
static void Free ()
Never, EVER, call this function! It is the last function called on shutdown....
static bool IsAppShuttingDown ()
static bool IsAppStartedUp ()
static void InitXRC (bool force=false)
XML Resource functions /////// Inits XML Resource system.
static void LoadXRC (wxString relpath)
Loads XRC file(s) using data_path.
static bool LoadResource (const wxString &file)
static wxMenuBar * LoadMenuBar (wxString resid, bool createonfailure=false)
Loads Menubar from XRC.
static wxMenu * LoadMenu (wxString menu_id, bool createonfailure=false)
Loads Menu from XRC.
static wxToolBar * LoadToolBar (wxFrame *parent, wxString resid, bool defaultsmall=true)
Loads ToolBar from XRC.
static Manager * Get (wxFrame *appWindow)
static void AddonToolBar (wxToolBar *toolBar, wxString resid)
static bool isToolBar16x16 (wxToolBar *toolBar)
static wxCmdLineParser * GetCmdLineParser ()
Private Types
typedef std::vector< IEventFunctorBase< CodeBlocksEvent > *> EventSinksArray
typedef std::map< wxEventType, EventSinksArray > EventSinksMap
typedef std::vector< IEventFunctorBase< CodeBlocksDockEvent > *> DockEventSinksArray
typedef std::map< wxEventType, DockEventSinksArray > DockEventSinksMap
typedef std::vector< IEventFunctorBase< CodeBlocksLayoutEvent > *> LayoutEventSinksArray
typedef std::map< wxEventType, LayoutEventSinksArray > LayoutEventSinksMap
typedef std::vector< IEventFunctorBase< CodeBlocksLogEvent > *> LogEventSinksArray
typedef std::map< wxEventType, LogEventSinksArray > LogEventSinksMap
Private Member Functions
Manager ()
~Manager ()
void OnMenu (wxCommandEvent &event)
Private Attributes
wxFrame * m_pAppWindow
EventSinksMap m_EventSinks
DockEventSinksMap m_DockEventSinks
LayoutEventSinksMap m_LayoutEventSinks
LogEventSinksMap m_LogEventSinks
cbSearchResultsLog * m_SearchResultLog
Static Private Attributes
static bool m_AppShuttingDown = false
static bool m_AppStartedUp = false
static bool m_BlockYields = false
static bool m_IsBatch = false
static wxCmdLineParser m_CmdLineParser
Detailed Description
Definition at line 48 of file manager.h.
Member Typedef Documentation
DockEventSinksArray
typedef std::vector< IEventFunctorBase<CodeBlocksDockEvent>* > Manager::DockEventSinksArray private
Definition at line 169 of file manager.h.
DockEventSinksMap
typedef std::map< wxEventType, DockEventSinksArray > Manager::DockEventSinksMap private
Definition at line 170 of file manager.h.
EventSinksArray
typedef std::vector< IEventFunctorBase<CodeBlocksEvent>* > Manager::EventSinksArray private
Definition at line 167 of file manager.h.
EventSinksMap
typedef std::map< wxEventType, EventSinksArray > Manager::EventSinksMap private
Definition at line 168 of file manager.h.
LayoutEventSinksArray
typedef std::vector< IEventFunctorBase<CodeBlocksLayoutEvent>* > Manager::LayoutEventSinksArray private
Definition at line 171 of file manager.h.
LayoutEventSinksMap
typedef std::map< wxEventType, LayoutEventSinksArray > Manager::LayoutEventSinksMap private
Definition at line 172 of file manager.h.
LogEventSinksArray
typedef std::vector< IEventFunctorBase<CodeBlocksLogEvent>* > Manager::LogEventSinksArray private
Definition at line 173 of file manager.h.
LogEventSinksMap
typedef std::map< wxEventType, LogEventSinksArray > Manager::LogEventSinksMap private
Definition at line 174 of file manager.h.
Constructor & Destructor Documentation
Manager()
Manager::Manager () private
Definition at line 121 of file manager.cpp.
Referenced by Get().
~Manager()
Manager::~Manager () private
Definition at line 125 of file manager.cpp.
References m_DockEventSinks, m_EventSinks, m_LayoutEventSinks, and m_LogEventSinks.
Member Function Documentation
AddonToolBar()
void Manager::AddonToolBar (wxToolBar * toolBar, wxString resid) static
Definition at line 405 of file manager.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadObject().
Referenced by CompilerGCC::BuildToolBar(), CodeCompletion::BuildToolBar(), MainFrame::CreateToolbars(), and DebuggerToolbarHandler::GetToolbar().
BlockYields()
void Manager::BlockYields (bool block) static
Blocks/unblocks Manager::Yield(). Be careful when using it. Actually, do not use it ;)
Definition at line 210 of file manager.cpp.
References m_BlockYields.
Referenced by MainFrame::OnApplicationClose().
CreateEmptyToolbar()
wxToolBar * Manager::CreateEmptyToolbar ()
Definition at line 394 of file manager.cpp.
References _T, Get(), GetAppFrame(), GetConfigManager(), ConfigManager::ReadBool(), wxToolBar::SetToolBitmapSize(), wxDefaultPosition, wxTB_FLAT, and wxTB_NODIVIDER.
Referenced by MainFrame::CreateToolbars(), MainFrame::DoAddPluginToolbar(), and DebuggerToolbarHandler::GetToolbar().
Free()
void Manager::Free () static
Never, EVER, call this function! It is the last function called on shutdown....
Definition at line 189 of file manager.cpp.
References s_ManagerInstance.
Referenced by CodeBlocksApp::OnExit().
Get() [1/2]
Manager * Manager::Get () static
Use Manager::Get() to get a pointer to its instance Manager::Get() is guaranteed to never return an invalid pointer.
Definition at line 182 of file manager.cpp.
References Manager(), and s_ManagerInstance.
Referenced by DbgCmd_UpdateWatchesTree::Action(), EditorBase::Activate(), DebuggerState::AddBreakpoint(), cbEditor::AddBreakpoint(), cbProject::AddBuildTarget(), NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), DebuggerGDB::AddDataBreakpoint(), cbProject::AddFile(), ProjectManager::AddFileToProject(), NativeParser::AddGCCCompilerDirs(), NativeParser::AddIncludeDirsToParser(), ProjectManager::AddMultipleFilesToProject(), CompilerGCC::AddOutputLine(), MainFrame::AddPluginInMenus(), CompilerSettingsDlg::AddPluginPanels(), EnvironmentSettingsDlg::AddPluginPanels(), EditorConfigurationDlg::AddPluginPanels(), ProjectOptionsDlg::AddPluginPanels(), NativeParser::AddProjectDefinedMacros(), ProjectManager::AddProjectDependency(), NativeParser::AddProjectToParser(), DebuggerGDB::AddSourceDir(), cbEditor::AddToContextMenu(), Wiz::AddWizard(), CompilerGCC::AllocProcesses(), EditorColourSet::Apply(), DirectCommands::AreExternalDepsOutdated(), CompilerGCC::AskForActiveProject(), ProjectManagerUI::AskForBuildTargetIndex(), ProjectManagerUI::AskForMultiBuildTargetIndex(), cbPlugin::Attach(), CodeBlocksApp::AttachDebugger(), cbEditor::AutoComplete(), AutoDetectCompilers::AutoDetectCompilers(), CompilerGDC::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), cbSmartIndentPlugin::AutoIndentEnabled(), BacktraceDlg::BacktraceDlg(), CodeBlocksApp::BatchJob(), BatchLogWindow::BatchLogWindow(), cbProject::BeginAddFiles(), ProjectManager::BeginLoadingProject(), cbProject::BeginRemoveFiles(), cbSmartIndentPlugin::BraceCompletionEnabled(), cbSmartIndentPlugin::BraceSmartIndentEnabled(), BreakpointsDlg::BreakpointProperties(), cbDebuggerPlugin::BringCBToFront(), GotoFunctionDlg::BuildContent(), DebuggerMenuHandler::BuildContextMenu(), CompilerGCC::BuildMenu(), cbDebuggerPlugin::BuildMenu(), CompilerGCC::BuildModuleMenu(), CodeCompletion::BuildModuleMenu(), cbDebuggerPlugin::BuildModuleMenu(), ProjectManagerUI::BuildProjectTree(), CompilerGCC::BuildStateManagement(), CompilerGCC::BuildToolBar(), CodeCompletion::BuildToolBar(), cbProject::CalculateCommonTopLevelPath(), CompilerGCC::CalculateProjectDependencies(), CompilerGCC::CalculateWorkspaceDependencies(), EditorHooks::CallHooks(), ScriptBindings::CallMenu(), CCManager::CallSmartIndentCCDone(), cbDebuggerPlugin::CancelValueTooltip(), cbAuiNotebook::cbAuiNotebook(), cbEditorInternalData::cbEditorInternalData(), cbGetMultiChoiceDialog(), cbGetSingleChoiceIndex(), cbGetTextFromUser(), cbMessageBox(), cbReadBatchBuildPlugins(), cbSaveToFile(), cbWriteBatchBuildPlugins(), CCManager::CCManager(), CCOptionsDlg::CCOptionsDlg(), CfgMgrBldr::CfgMgrBldr(), EditorConfigurationDlg::ChangeTheme(), EditorManager::CheckForExternallyModifiedFiles(), ProjectManagerUI::CheckForExternallyModifiedProjects(), CodeBlocksApp::CheckVersion(), ScriptBindings::IOLib::ChooseDir(), ScriptBindings::IOLib::ChooseFile(), ClassBrowser::ClassBrowser(), DebuggerGDB::CleanupWhenProjectClosed(), DisassemblyDlg::Clear(), cbDebuggerPlugin::ClearActiveMarkFromAllEditors(), cbProject::ClearAllProperties(), RecentItemsList::ClearHistory(), cbEditor::ClearHistory(), CompilerGCC::ClearLog(), cbDebuggerPlugin::ClearLog(), ProjectManager::ClearProjectDependencies(), MacrosManager::ClearProjectKeys(), ValueTooltip::ClearWatch(), cbProject::CloseAllFiles(), ProjectManager::CloseProject(), ProjectManager::CloseWorkspace(), CodeBlocksLogEvent::CodeBlocksLogEvent(), EditorManager::CollectDefines(), DirectCommands::CompileFile(), CompilerGCC::CompileFileWithoutProject(), Compiler::Compiler(), CompilerFactory::CompilerInheritsFrom(), CompilerMessages::CompilerMessages(), CompilerSettingsDlg::CompilerSettingsDlg(), ScriptBindings::ConfigManager_Read(), ScriptBindings::ConfigManager_Write(), UserVariableManager::Configure(), ToolsManager::Configure(), CompilerGCC::Configure(), PluginManager::Configure(), ProjectManagerUI::ConfigureProjectDependencies(), EncodingDetector::ConvertToWxString(), ScriptBindings::IOLib::CopyFile(), Wiz::CopyFiles(), CrashHandlerSaveEditorFiles(), DebugInterfaceFactory::CreateBacktrace(), DebugInterfaceFactory::CreateBreapoints(), NativeParser::CreateClassBrowser(), CompilerFactory::CreateCompilerCopy(), EditorBase::CreateContextSubMenu(), cbSearchResultsLog::CreateControl(), CompilerMessages::CreateControl(), DebugInterfaceFactory::CreateCPURegisters(), ScriptBindings::IOLib::CreateDirRecursively(), DebugInterfaceFactory::CreateDisassembly(), cbEditor::CreateEditor(), CreateEmptyToolbar(), MenuItemsManager::CreateFromString(), MainFrame::CreateIDE(), DebugInterfaceFactory::CreateMemory(), MainFrame::CreateMenubar(), ProjectManagerUI::CreateMenuTreeProps(), FindReplace::CreateSearchLog(), DebugInterfaceFactory::CreateThreads(), MainFrame::CreateToolbars(), EditorBase::CreateUniqueFilename(), cbProject::CreateUniqueFilename(), DebugInterfaceFactory::CreateWatches(), DebuggerGDB::Debug(), DebuggerManager::DebuggerManager(), DebuggerMenuHandler::DebuggerMenuHandler(), DebuggerOptionsProjectDlg::DebuggerOptionsProjectDlg(), DebuggerSettingsDlg::DebuggerSettingsDlg(), DebugInterfaceFactory::DebugInterfaceFactory(), cbDebuggerPlugin::DebugLog(), cbProject::DefineVirtualBuildTarget(), InfoPane::DeleteLogger(), WatchesDlg::DeleteProperty(), DirectCommands::DepsSearchStart(), CompilerMessages::DestroyControls(), PluginManager::DetachPlugin(), EncodingDetector::DetectEncoding(), DirectCommands::DirectCommands(), ScriptBindings::IOLib::DirectoryExists(), DisassemblyDlg::DisassemblyDlg(), CompilerGCC::Dispatcher(), EditorBase::DisplayContextMenu(), ScriptingManager::DisplayErrors(), CompilerGCC::DistClean(), MainFrame::DoAddPluginToolbar(), CodeCompletion::DoAllMethodsImpl(), CDB_driver::DoBacktrace(), DebuggerGDB::DoBreak(), CompilerGCC::DoBuild(), CompilerCommandGenerator::DoBuildScripts(), ProjectLoader::DoBuildTarget(), MainFrame::DoCheckCurrentLayoutForChanges(), CodeCompletion::DoClassMethodDeclImpl(), Associations::DoClearAssociation(), CompilerErrors::DoClearErrorMarkFromAllEditors(), MainFrame::DoCloseCurrentWorkspace(), DocumentationHelper::DocumentationHelper(), DebuggerGDB::DoDebug(), CompilerOptionsDlg::DoFillCompilerPrograms(), ConfigureToolsDlg::DoFillList(), CompilerOptionsDlg::DoFillOthers(), CodeRefactoring::DoFindReferences(), CompilerErrors::DoGotoError(), CompilerGCC::DoGotoNextError(), CompilerGCC::DoGotoPreviousError(), cbEditor::DoInitializations(), EditorLexerLoader::DoLexer(), MainFrame::DoOnFileOpen(), ProjectManagerUI::DoOpenFile(), MainFrame::DoOpenFile(), MainFrame::DoOpenProject(), CodeCompletion::DoParseOpenedProjectAndActiveEditor(), CompilerGCC::DoPrepareQueue(), CompilerGCC::DoRecreateTargetMenu(), CompilerGCC::DoRegisterCompilers(), CodeRefactoring::DoRenameSymbols(), CompilerGCC::DoRunQueue(), MainFrame::DoSelectLayout(), Associations::DoSetAssociation(), InfoPane::DoShowContextMenu(), CCManager::DoShowDocumentation(), CompilerGCC::DoSwitchProjectTemporarily(), ProjectLoader::DoUnits(), MainFrame::DoUpdateAppTitle(), MainFrame::DoUpdateEditorStyle(), MainFrame::DoUpdateLayoutColours(), MainFrame::DoUpdateStatusBar(), DebuggerGDB::DoWatches(), CompilerGCC::DoWorkspaceBuild(), EditorBase::EditorBase(), EditorConfigurationDlg::EditorConfigurationDlg(), CodeCompletionHelper::EditorHasNameUnderCursor(), EditorManager::EditorManager(), ScriptBindings::EditorManager_Close(), ScriptBindings::EditorManager_GetBuiltinEditor(), ScriptBindings::EditorManager_Open(), ScriptBindings::EditorManager_Save(), NewFromTemplateDlg::EditScript(), cbStyledTextCtrl::EmulateDwellStart(), BreakpointsDlg::EnableBreakpoint(), cbProject::EndAddFiles(), ProjectManager::EndLoadingProject(), ProjectManager::EndLoadingWorkspace(), PrintDialog::EndModal(), CompilerSettingsDlg::EndModal(), EnvironmentSettingsDlg::EndModal(), ProjectFileOptionsDlg::EndModal(), BatchLogWindow::EndModal(), PluginsConfigurationDlg::EndModal(), NewFromTemplateDlg::EndModal(), ScriptingSettingsDlg::EndModal(), EditorConfigurationDlg::EndModal(), cbProject::EndRemoveFiles(), cbDebuggerPlugin::EnsureBuildUpToDate(), IPC::Entry(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), Compiler::EvalXMLCondition(), ExamineMemoryDlg::ExamineMemoryDlg(), ToolsManager::Execute(), ScriptBindings::ExecutePlugin(), PluginManager::ExecutePlugin(), ExpandBackticks(), ScriptBindings::IOLib::FileExists(), FilePathPanel::FilePathPanel(), ParserCommon::FileType(), EnvironmentSettingsDlg::FillApplicationColours(), FindReplaceDlg::FillComboWithLastValues(), ProjectFileOptionsDlg::FillGeneralProperties(), ProjectDepsDlg::FillList(), PluginsConfigurationDlg::FillList(), ScriptingSettingsDlg::FillScripts(), ScriptingSettingsDlg::FillTrusts(), FindReplace::Find(), FindReplace::FindInFiles(), FindReplace::FindNext(), FindReplaceDlg::FindReplaceDlg(), FindReplace::FindSelectedText(), DebuggerManager::FindTargetsDebugger(), ProjectManagerUI::FinishLoadingProject(), cbEditor::FixFoldState(), ScriptBindings::gBuildLog(), GdbCmd_ExamineMemory::GdbCmd_ExamineMemory(), GdbCmd_RemoteTarget::GdbCmd_RemoteTarget(), ScriptBindings::gDebugLog(), CompilerCommandGenerator::GenerateCommandLine(), Wiz::GenerateFile(), DocumentationHelper::GenerateHTML(), CompileTargetBase::GenerateTargetFilename(), ScriptBindings::gErrorLog(), Get(), CodeCompletion::GetAbsolutePath(), cbDebuggerPlugin::GetActiveConfig(), ScriptBindings::getCM(), DirectCommands::GetCompileFileCommand(), NativeParser::GetCurrentProject(), cbDebuggerPlugin::GetDebuggee(), DebuggerConfiguration::GetDebuggerExecutable(), ProjectManager::GetDefaultPath(), CompileTargetBase::GetDynamicLibDefFilename(), CompileTargetBase::GetDynamicLibFilename(), CompileTargetBase::GetDynamicLibImportFilename(), MainFrame::GetEditorDescription(), cbDebuggerPlugin::GetEditorWordAtCaret(), ScriptBindings::getEM(), GetEOLStr(), cbDebuggerCommonConfig::GetFlag(), DebuggerManager::GetLogger(), CompilerGCC::GetMakeCommandFor(), RecentItemsList::GetMenu(), DebuggerManager::GetMenu(), WizPageBase::GetNext(), CodeRefactoring::GetOpenedFiles(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), CompilerCommandGenerator::GetOrderedResourceIncludeDirs(), NativeParser::GetParserInfoByCurrentEditor(), cbDebuggerCommonConfig::GetPerspective(), ScriptBindings::getPM(), GetpMan(), GetpMsg(), WizPageBase::GetPrev(), CompilerCommandGenerator::GetProcessedIncludeDir(), NativeParser::GetProjectByFilename(), CCManager::GetProviderFor(), ConfigManager::GetProxy(), GetResourcesDir(), GetSelectedText(), GetSettingsIconsStyle(), GetShellString(), ScriptBindings::getSM(), CompileTargetBase::GetStaticLibFilename(), CodeRefactoring::GetSymbolUnderCursor(), FindReplaceDlg::GetTarget(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), DebuggerToolbarHandler::GetToolbar(), DebuggerConfiguration::GetUserArguments(), GetUserVariableDialog::GetUserVariableDialog(), ScriptBindings::getUVM(), ProjectLoader::GetValidCompilerID(), cbDebuggerCommonConfig::GetValueTooltipFont(), ScriptBindings::gLog(), CodeCompletion::GotoFunctionPrevNext(), ScriptBindings::gReplaceMacros(), ScriptBindings::gWarningLog(), handleConfigError(), DebuggerManager::HasMenu(), DebuggerManager::HideLogger(), IMPLEMENT_APP(), InfoWindow::InfoWindow(), CompilerCommandGenerator::Init(), AnnoyingDialog::Init(), CodeBlocksApp::InitAssociations(), CompilerGCC::InitBuildLog(), RecentItemsList::Initialize(), CodeBlocksApp::InitLocale(), InitPrinting(), CCManager::InjectAutoCompShow(), InsertNewLine(), ScriptBindings::InstallPlugin(), PluginManager::InstallPlugin(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), ProjectManager::IsBusy(), DirectCommands::IsObjectOutdated(), cbCodeCompletionPlugin::IsProviderFor(), ProjectOptionsDlg::IsScriptValid(), BacktraceDlg::IsSwitchFrameEnabled(), CompilerLCC::IsValid(), Compiler::IsValid(), CompilerGCC::IsValidTarget(), CompilerGCC::KillProcess(), Wiz::Launch(), StartHerePage::LinkClicked(), ColourManager::Load(), EditorLexerLoader::Load(), FilesGroupsAndMasks::Load(), GetUserVariableDialog::Load(), FileManager::Load(), cbWorkspace::Load(), EditorColourSet::Load(), PluginManager::LoadAllPlugins(), EditorColourSet::LoadAvailableSets(), ScriptingManager::LoadBuffer(), Compiler::LoadDefaultOptions(), CodeBlocksApp::LoadDelayedFiles(), WorkspaceLoader::LoadLayout(), cbWorkspace::LoadLayout(), cbProject::LoadLayout(), ProjectLayoutLoader::LoadNotebookLayout(), PluginManager::LoadPlugin(), ProjectManager::LoadProject(), Compiler::LoadRegExArray(), LoadResource(), ScriptingManager::LoadScript(), CompilerFactory::LoadSettings(), Compiler::LoadSettings(), EditorConfigurationDlg::LoadThemes(), ToolsManager::LoadTools(), TemplateManager::LoadUserTemplates(), MainFrame::LoadViewLayout(), MainFrame::LoadWindowSize(), MainFrame::LoadWindowState(), ProjectManager::LoadWorkspace(), ProfileTimer::Log(), cbDebuggerPlugin::Log(), DebuggerMenuHandler::LogActiveConfig(), LogManager::LogManager(), CompilerGCC::LogMessage(), MainFrame::MainFrame(), Compiler::MakeInvalidCompilerMessages(), cbDebuggerPlugin::MarkAsStopped(), NativeParser::MarkItemsByAI(), UserVariableManager::Migrate(), ProjectManagerUI::MoveProjectDown(), ProjectManagerUI::MoveProjectUp(), NativeParser::NativeParser(), EditorManager::New(), DebuggerManager::NewConfig(), NewFromTemplateDlg::NewFromTemplateDlg(), TemplateManager::NewProjectFromUserTemplate(), CompilerGCC::NotifyCleanProject(), CompilerGCC::NotifyCleanWorkspace(), CCManager::NotifyDocumentation(), CompilerGCC::NotifyJobDone(), PluginManager::NotifyPlugins(), cbEditor::NotifyPlugins(), cbProject::NotifyPlugins(), cbPlugin::NotImplemented(), DebuggerMenuHandler::OnActiveDebuggerClick(), DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick(), ConfigureToolsDlg::OnAdd(), ProjectOptionsDlg::OnAddBuildTargetClick(), DebuggerMenuHandler::OnAddDataBreakpoint(), ProjectManagerUI::OnAddFilesToProjectRecursively(), ProjectManagerUI::OnAddFileToProject(), EditorManager::OnAddFileToProject(), MainFrame::OnAddLogWindow(), ConfigureToolsDlg::OnAddSeparator(), DebuggerMenuHandler::OnAddWatch(), CodeBlocksApp::OnAppActivate(), MainFrame::OnApplicationClose(), CCOptionsDlg::OnApply(), CompilerOptionsDlg::OnApply(), CodeCompletion::OnAttach(), CompilerGCC::OnAttach(), Wiz::OnAttach(), cbDebuggerPlugin::OnAttach(), cbSmartIndentPlugin::OnAttach(), DebuggerGDB::OnAttachReal(), CCManager::OnAutocompleteSelect(), CompilerMessages::OnAutoFit(), cbEditor::OnBeforeBuildContextMenu(), cbEditorPrintout::OnBeginDocument(), BreakpointsDlg::OnBreakpointAdd(), BreakpointsDlg::OnBreakpointEdit(), EditPathDlg::OnBrowse(), DebuggerConfigurationPanel::OnBrowse(), FilePathPanel::OnbtnBrowseClick(), ScriptConsole::OnbtnExecuteClick(), ScriptConsole::OnbtnLoadClick(), ProjectOptionsDlg::OnBuildOrderClick(), ProjectOptionsDlg::OnBuildTargetChanged(), ScriptBindings::XrcDialog::OnButton(), AnnoyingDialog::OnButton(), WizPage::OnButton(), WizGenericSelectPathPanel::OnButton(), CodeCompletion::OnCCDebugLogger(), CodeCompletion::OnCCLogger(), EnvironmentSettingsDlg::OnChooseAppColourItem(), CompilerGCC::OnCleanFile(), EnvironmentSettingsDlg::OnClickAppColour(), cbEditor::OnClose(), ProjectManagerUI::OnCloseFile(), ProjectManagerUI::OnCloseProject(), ProjectManagerUI::OnCloseWorkspace(), WatchesDlg::OnCollapse(), ValueTooltip::OnCollapse(), CompilerGCC::OnCompileFileRequest(), cbDebuggerPlugin::OnCompilerFinished(), CCManager::OnCompleteCode(), GetUserVariableDialog::OnConfig(), DebuggerGDB::OnConfigurationChange(), EditorBase::OnContextMenuEntry(), cbEditor::OnContextMenuEntry(), ProjectOptionsDlg::OnCopyBuildTargetClick(), CompilerOptionsDlg::OnCopyDirsClick(), CompilerOptionsDlg::OnCopyLibsClick(), ProjectOptionsDlg::OnCreateImportFileClick(), DebuggerGDB::OnCursorChanged(), CCManager::OnDeactivateApp(), CCManager::OnDeactivateEd(), DebuggerToolbarHandler::OnDebugWindows(), CCManager::OnDeferredCallTipCancel(), CCManager::OnDeferredCallTipShow(), EditorConfigurationDlg::OnDeleteColourTheme(), ScriptingSettingsDlg::OnDeleteTrust(), DocumentationHelper::OnDocumentationLink(), ConfigureToolsDlg::OnDown(), WatchesDropTarget::OnDropText(), ConfigureToolsDlg::OnEdit(), MainFrame::OnEditBookmarksClearAll(), MainFrame::OnEditBookmarksNext(), MainFrame::OnEditBookmarksPrevious(), MainFrame::OnEditBookmarksToggle(), MainFrame::OnEditBoxCommentSelected(), ProjectOptionsDlg::OnEditBuildTargetClick(), MainFrame::OnEditClearHistory(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditCompleteCode(), MainFrame::OnEditCopy(), MainFrame::OnEditCut(), MainFrame::OnEditEncoding(), MainFrame::OnEditEOLMode(), MainFrame::OnEditFoldAll(), MainFrame::OnEditFoldBlock(), MainFrame::OnEditGotoLineEnd(), MainFrame::OnEditGotoMatchingBrace(), MainFrame::OnEditHighlightMode(), MainFrame::OnEditInsertNewLine(), MainFrame::OnEditLineCopy(), MainFrame::OnEditLineCut(), MainFrame::OnEditLineDelete(), MainFrame::OnEditLineDuplicate(), MainFrame::OnEditLineMove(), MainFrame::OnEditLinePaste(), MainFrame::OnEditLineTranspose(), MainFrame::OnEditLowerCase(), MainFrame::OnEditMenuUpdateUI(), CodeCompletion::OnEditorActivated(), MainFrame::OnEditorActivated(), NativeParser::OnEditorActivated(), CodeCompletion::OnEditorActivatedTimer(), cbEditor::OnEditorCharAdded(), CCManager::OnEditorClose(), CodeCompletion::OnEditorClosed(), CCManager::OnEditorHook(), cbEditor::OnEditorModified(), CCManager::OnEditorOpen(), CodeCompletion::OnEditorOpen(), CCManager::OnEditorTooltip(), MainFrame::OnEditorUpdateUI(), cbEditor::OnEditorUpdateUI(), MainFrame::OnEditParaDown(), MainFrame::OnEditParaDownExtend(), MainFrame::OnEditParaUp(), MainFrame::OnEditParaUpExtend(), MainFrame::OnEditPaste(), MainFrame::OnEditRedo(), MainFrame::OnEditSelectAll(), MainFrame::OnEditSelectNext(), MainFrame::OnEditSelectNextSkip(), MainFrame::OnEditShowCallTip(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditSwapHeaderSource(), MainFrame::OnEditToggleAllFolds(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditToggleFoldBlock(), MainFrame::OnEditUncommentSelected(), MainFrame::OnEditUndo(), MainFrame::OnEditUnfoldAll(), MainFrame::OnEditUnfoldBlock(), MainFrame::OnEditUpperCase(), MainFrame::OnEditWordPartLeft(), MainFrame::OnEditWordPartLeftExtend(), MainFrame::OnEditWordPartRight(), MainFrame::OnEditWordPartRightExtend(), MainFrame::OnEditZoomIn(), MainFrame::OnEditZoomOut(), MainFrame::OnEditZoomReset(), BreakpointsDlg::OnEnable(), DebugLogPanel::OnEntryCommand(), ProjectManagerUI::OnExecParameters(), WatchesDlg::OnExpand(), ValueTooltip::OnExpand(), PluginsConfigurationDlg::OnExport(), MainFrame::OnFileClose(), MainFrame::OnFileCloseAll(), MainFrame::OnFileCloseProject(), MainFrame::OnFileMenuUpdateUI(), MainFrame::OnFileNewWhat(), MainFrame::OnFileNext(), MainFrame::OnFileOpenDefWorkspace(), MainFrame::OnFilePrev(), MainFrame::OnFilePrint(), MainFrame::OnFileSave(), MainFrame::OnFileSaveAll(), MainFrame::OnFileSaveAs(), MainFrame::OnFileSaveProject(), MainFrame::OnFileSaveProjectAs(), MainFrame::OnFileSaveProjectTemplate(), MainFrame::OnFileSaveWorkspace(), MainFrame::OnFileSaveWorkspaceAs(), ProjectManagerUI::OnFindFile(), MainFrame::OnFocusEditor(), CodeCompletion::OnFunction(), DebuggerGDB::OnGDBTerminated(), MainFrame::OnGlobalUserVars(), ExamineMemoryDlg::OnGo(), CCDebugInfo::OnGoDeclClick(), CCDebugInfo::OnGoImplClick(), CodeCompletion::OnGotoDeclaration(), ProjectManagerUI::OnGotoFile(), CodeCompletion::OnGotoFunction(), MainFrame::OnHelpPluginMenu(), MainFrame::OnHideLogManager(), MainFrame::OnHighlightMenu(), cbAuiNotebook::OnIdle(), CodeBlocksApp::OnInit(), PluginsConfigurationDlg::OnInstall(), CompilerGCC::OnJobEnd(), BacktraceDlg::OnJump(), ClassBrowser::OnJumpTo(), WatchesDlg::OnKeyDown(), ProjectOptionsDlg::OnKeyDown(), cbStyledTextCtrl::OnKeyDown(), ProjectManagerUI::OnKeyDown(), DebugLogPanel::OnLoadFile(), MainFrame::OnLockLogManager(), WatchesDlg::OnMenuAddDataBreak(), WatchesDlg::OnMenuDeleteAll(), WatchesDlg::OnMenuExamineMemory(), WatchesDlg::OnMenuProperties(), CCManager::OnMenuSelect(), WatchesDlg::OnMenuUpdate(), DebuggerGDB::OnMenuWatchDereference(), DisassemblyDlg::OnMixedModeCB(), GotoFunctionDlg::OnModeClick(), MainFrame::OnNotebookDoubleClick(), ProjectManagerUI::OnNotes(), DebuggerSettingsDlg::OnOK(), BreakpointsDlg::OnOpen(), CodeCompletion::OnOpenIncludeFile(), ProjectManagerUI::OnOpenWith(), EditPathDlg::OnOther(), WizPageBase::OnPageChanged(), WizProjectPathPanel::OnPageChanged(), EditorManager::OnPageChanged(), WizPageBase::OnPageChanging(), WizFilePathPanel::OnPageChanging(), WizProjectPathPanel::OnPageChanging(), WizGenericSelectPathPanel::OnPageChanging(), WizCompilerPanel::OnPageChanging(), EditorManager::OnPageChanging(), WizBuildTargetPanel::OnPageChanging(), WizGenericSingleChoiceList::OnPageChanging(), EditorManager::OnPageClose(), EditorManager::OnPageContextMenu(), CodeCompletion::OnParserEnd(), CodeCompletion::OnParserStart(), NativeParser::OnParsingOneByOneTimer(), MainFrame::OnPluginLoaded(), MainFrame::OnPluginsExecuteMenu(), cbEditorPrintout::OnPrintPage(), CompilerGCC::OnProjectActivated(), cbDebuggerPlugin::OnProjectActivated(), cbDebuggerPlugin::OnProjectClosed(), CompilerGCC::OnProjectCompilerOptions(), ProjectOptionsDlg::OnProjectDepsClick(), ProjectManagerUI::OnProjectFileActivated(), CodeCompletion::OnProjectSavedTimer(), ProjectManagerUI::OnProperties(), EditorManager::OnProperties(), WatchesDlg::OnPropertyRightClick(), WatchesDlg::OnPropertySelected(), ProjectFileOptionsDlg::OnReadOnlyCheck(), CodeCompletion::OnRealtimeParsingTimer(), DisassemblyDlg::OnRefresh(), CodeCompletion::OnRelease(), CompilerGCC::OnRelease(), cbDebuggerPlugin::OnRelease(), ConfigureToolsDlg::OnRemove(), BreakpointsDlg::OnRemove(), DebuggerMenuHandler::OnRemoveAllBreakpoints(), ProjectOptionsDlg::OnRemoveBuildTargetClick(), ProjectManagerUI::OnRemoveFileFromProject(), EditorManager::OnRemoveFileFromProject(), EditorConfigurationDlg::OnRenameColourTheme(), ProjectManagerUI::OnRenameFile(), ProjectManagerUI::OnRenameVirtualFolder(), ProjectManagerUI::OnRenameWorkspace(), CodeCompletion::OnReparsingTimer(), MainFrame::OnRequestHideDockWindow(), MainFrame::OnRequestShowDockWindow(), ProjectManagerUI::OnRightClick(), CodeBlocksApp::OnRun(), DebuggerMenuHandler::OnRunToCursor(), DisassemblyDlg::OnSave(), CCDebugInfo::OnSave(), ProjectManagerUI::OnSaveAsWorkspace(), ProjectManagerUI::OnSaveFile(), ProjectManagerUI::OnSaveProject(), ProjectManagerUI::OnSaveWorkspace(), ScriptingManager::OnScriptMenu(), ClassBrowser::OnSearch(), MainFrame::OnSearchFind(), MainFrame::OnSearchGotoLine(), MainFrame::OnSearchGotoNextChanged(), MainFrame::OnSearchGotoPrevChanged(), MainFrame::OnSearchMenuUpdateUI(), FindReplaceDlg::OnSearchProject(), MainFrame::OnSearchReplace(), CodeCompletion::OnSelectedFileReparse(), FindReplaceDlg::OnSelectTarget(), CompilerGCC::OnSelectTarget(), ProjectManagerUI::OnSetActiveProject(), DebuggerMenuHandler::OnSetNextStatement(), ClassBrowser::OnSetSortType(), MainFrame::OnSettingsCompiler(), MainFrame::OnSettingsDebugger(), MainFrame::OnSettingsEditor(), MainFrame::OnSettingsEnvironment(), MainFrame::OnSettingsPlugins(), MainFrame::OnShiftTab(), CCManager::OnShowCallTip(), EditorManager::OnShowFileInTree(), MainFrame::OnShowLogManager(), DebuggerMenuHandler::OnStart(), DebuggerMenuHandler::OnStep(), DebuggerToolbarHandler::OnStop(), BacktraceDlg::OnSwitchFrame(), MainFrame::OnSwitchTabs(), ThreadsDlg::OnSwitchThread(), ProjectManagerUI::OnTabContextMenu(), InfoPane::OnTabPosition(), ProjectManagerUI::OnTabPosition(), EditorManager::OnTabPosition(), CCManager::OnTimer(), PluginsConfigurationDlg::OnToggle(), MainFrame::OnToggleBar(), DebuggerMenuHandler::OnToggleBreakpoint(), MainFrame::OnToggleStartPage(), MainFrame::OnToggleStatusBar(), ToolsManager::OnToolErrOutput(), DebuggerToolbarHandler::OnToolInfo(), ToolsManager::OnToolStdOutput(), ToolsManager::OnToolTerminated(), ClassBrowser::OnTreeItemDoubleClick(), ProjectManagerUI::OnTreeItemRightClick(), PluginsConfigurationDlg::OnUninstall(), MainFrame::OnUnlockLogManager(), ConfigureToolsDlg::OnUp(), ConfigureToolsDlg::OnUpdateUI(), DebuggerMenuHandler::OnUpdateUI(), CCOptionsDlg::OnUpdateUI(), DebuggerToolbarHandler::OnUpdateUI(), ProjectManagerUI::OnUpdateUI(), CompilerGCC::OnUpdateUI(), CodeCompletion::OnUpdateUI(), EditorManager::OnUpdateUI(), DebugLogPanel::OnUpdateUI(), ScriptingSettingsDlg::OnValidateTrusts(), ProjectManagerUI::OnViewCategorize(), CodeCompletion::OnViewClassBrowser(), ProjectManagerUI::OnViewFileMasks(), MainFrame::OnViewHideEditorTabs(), ProjectManagerUI::OnViewHideFolderName(), MainFrame::OnViewLayoutSave(), MainFrame::OnViewMenuUpdateUI(), ClassBrowser::OnViewScope(), ProjectManagerUI::OnViewUseFolders(), CodeCompletion::OnWorkspaceChanged(), cbEditor::OnZoom(), WorkspaceLoader::Open(), ProjectLayoutLoader::Open(), ProjectTemplateLoader::Open(), ProjectLoader::Open(), MainFrame::Open(), EditorManager::Open(), cbEditor::Open(), cbProject::Open(), EditorManager::OpenContainingFolder(), OpenContainingFolderData::OpenContainingFolderData(), MainFrame::OpenGeneric(), BuildLogger::OpenLink(), CodeRefactoring::Parse(), Parser::Parse(), CodeBlocksApp::ParseCmdLine(), CodeCompletion::ParseFunctionsAndFillToolbar(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), DebuggerInfoCmd::ParseOutput(), CdbCmd_Watch::ParseOutput(), CdbCmd_TooltipEvaluation::ParseOutput(), GdbCmd_AddBreakpointCondition::ParseOutput(), CdbCmd_Backtrace::ParseOutput(), GdbCmd_AddBreakpoint::ParseOutput(), CdbCmd_SwitchFrame::ParseOutput(), CdbCmd_InfoRegisters::ParseOutput(), GdbCmd_AddDataBreakpoint::ParseOutput(), CdbCmd_Disassembly::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_Threads::ParseOutput(), GdbCmd_Watch::ParseOutput(), GdbCmd_TooltipEvaluation::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), GdbCmd_InfoRegisters::ParseOutput(), GdbCmd_Disassembly::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_ExamineMemory::ParseOutput(), GdbCmd_StepOrNextInstruction::ParseOutput(), GdbCmd_InfoRegisters::ParseOutputFromOR32gdbPort(), CompilerCommandGenerator::PathSearch(), PlaceWindow(), PluginManager::PluginManager(), PluginRegistrant< T >::PluginRegistrant(), PluginsConfigurationDlg::PluginsConfigurationDlg(), MainFrame::PluginsUpdated(), MainFrame::PopupToggleToolbarMenu(), GDB_driver::Prepare(), CompilerGCC::PrepareCompileFile(), CompilerGCC::PreprocessJob(), cbEditor::Print(), CompilerGCC::PrintBanner(), PrintDialog::PrintDialog(), CompilerGCC::PrintInvalidCompiler(), CCManager::ProcessArrow(), ProcessEvent(), DebuggerManager::ProcessSettings(), cbDebuggerPlugin::ProcessValueTooltip(), ProjectDepsDlg::ProjectDepsDlg(), ProjectManager::ProjectManager(), ScriptBindings::ProjectManager_AddFileToProject(), ProjectManagerUI::ProjectManagerUI(), ProjectOptionsDlg::ProjectOptionsDlg(), cbProject::QueryCloseAllFiles(), ProjectManagerUI::QueryCloseAllProjects(), ProjectManagerUI::QueryCloseWorkspace(), ConfigManagerWrapper::Read(), ReadActiveDebuggerConfig(), ConfigManagerWrapper::ReadBool(), ConfigManagerWrapper::ReadDouble(), PluginManager::ReadExtraFilesFromManifestFile(), ScriptBindings::IOLib::ReadFileContents(), ConfigManagerWrapper::ReadInt(), PluginManager::ReadManifestFile(), Parser::ReadOptions(), CompilerGCC::Rebuild(), DebuggerMenuHandler::RebuildMenus(), ProjectManagerUI::RebuildTree(), CompilerGCC::RebuildWorkspace(), cbEditor::RefreshBreakpointMarkers(), RefreshBreakpoints(), RecentItemsList::RefreshStartHerePage(), ScriptingManager::RefreshTrusts(), WatchesDlg::RefreshUI(), StartHerePage::RegisterColours(), DebuggerManager::RegisterDebugger(), DebuggerMenuHandler::RegisterDefaultWindowItems(), MainFrame::RegisterEvents(), PluginManager::RegisterPlugin(), ScriptBindings::ScriptPluginWrapper::RegisterPlugin(), ScriptingManager::RegisterScriptMenu(), ScriptingManager::RegisterScriptPlugin(), CompilerFactory::RegisterUserCompilers(), cbDebuggerPlugin::RegisterValueTooltip(), DebuggerMenuHandler::RegisterWindowMenu(), cbPlugin::Release(), ThreadsDlg::Reload(), BacktraceDlg::Reload(), StartHerePage::Reload(), BreakpointsDlg::Reload(), BreakpointsDlg::RemoveAllBreakpoints(), cbEditor::RemoveBreakpoint(), NativeParser::RemoveClassBrowser(), CompilerFactory::RemoveCompiler(), ScriptBindings::IOLib::RemoveDir(), RemoveDockWindow(), ScriptBindings::IOLib::RemoveFile(), cbProject::RemoveFile(), ProjectManager::RemoveFileFromProject(), ProjectManagerUI::RemoveFilesRecursively(), NativeParser::RemoveObsoleteParsers(), ProjectManager::RemoveProjectDependency(), ProjectManager::RemoveProjectFromAllDependencies(), ScriptBindings::IOLib::RenameFile(), CodeRefactoring::RenameSymbols(), WatchesDlg::RenameWatch(), cbProject::ReOrderTargets(), NativeParser::ReparseSelectedProject(), FindReplace::Replace(), UserVariableManager::Replace(), FindReplace::ReplaceInFiles(), MacrosManager::ReplaceMacros(), EncodingDetector::Report(), DebuggerGDB::RequestUpdate(), DocumentationHelper::RereadOptions(), CodeCompletion::RereadOptions(), NativeParser::RereadParserOptions(), MacrosManager::Reset(), EditorColourSet::Reset(), CompilerGCC::ResetBuildState(), DebuggerDriver::ResetCurrentFrame(), CompilerGCC::Run(), DebuggerGDB::RunCommand(), Wiz::RunCustomWizard(), Wiz::RunFilesWizard(), GDB_driver::RunningThreads(), cbDebuggerPlugin::RunNixConsole(), Wiz::RunProjectWizard(), CompilerGCC::RunSingleFile(), MainFrame::RunStartupScripts(), Wiz::RunTargetWizard(), DebuggerGDB::RunToCursor(), ColourManager::Save(), WorkspaceLoader::Save(), ProjectLayoutLoader::Save(), FilesGroupsAndMasks::Save(), cbWorkspace::Save(), EditorColourSet::Save(), cbProject::SaveAllFiles(), cbWorkspace::SaveAs(), cbEditor::SaveAs(), cbProject::SaveAs(), CompilerGCC::SaveBuildLog(), CCDebugInfoHelper::SaveCCDebugInfo(), FindReplaceDlg::SaveComboValues(), TinyXML::SaveDocument(), WorkspaceLoader::SaveLayout(), cbWorkspace::SaveLayout(), cbProject::SaveLayout(), ProjectDepsDlg::SaveList(), CompilerFactory::SaveSettings(), Compiler::SaveSettings(), ToolsManager::SaveTools(), TemplateManager::SaveUserTemplate(), MainFrame::SaveWindowState(), PluginManager::ScanForPlugins(), MainFrame::ScanForPlugins(), ScriptConsolePrintFunc(), CodeRefactoring::SearchInFiles(), ScriptBindings::IOLib::SecurityAllows(), cbSmartIndentPlugin::SelectionBraceCompletionEnabled(), DisassemblyDlg::SetActiveAddress(), EditorManager::SetActiveEditor(), FilePathPanel::SetAddToProject(), ExamineMemoryDlg::SetBaseAddress(), MainFrame::SetChecksForViewToolbarsMenu(), ProjectManager::SetDefaultPath(), DebuggerManager::SetDisassemblyMixedMode(), cbEditor::SetEditorStyleAfterFileOpen(), cbEditor::SetEditorStyleBeforeFileOpen(), ProjectFile::SetFileState(), cbDebuggerCommonConfig::SetFlag(), cbEditorInternalData::SetLineNumberColWidth(), cbDebuggerCommonConfig::SetPerspective(), ProjectManager::SetProject(), cbEditor::SetProjectFile(), EditorBase::SetTitle(), CompilerCommandGenerator::SetupCompilerOptions(), MainFrame::SetupDebuggerUI(), CompilerGCC::SetupEnvironment(), MainFrame::SetupGUILogging(), CompilerOWGenerator::SetupLibrariesDirs(), CompilerOWGenerator::SetupLinkerOptions(), CompilerCommandGenerator::SetupLinkerOptions(), PluginManager::SetupLocaleDomain(), CompilerCommandGenerator::SetupOutputFilenames(), CodeBlocksApp::SetupPersonality(), CompilerCommandGenerator::SetupResourceCompilerOptions(), SetValue(), cbDebuggerCommonConfig::SetValueTooltipFont(), CompilerMINGW::SetVersionString(), DebuggerManager::ShowBacktraceDialog(), ScriptBindings::ShowDialog(), FindReplace::ShowFindDialog(), MainFrame::ShowHideScriptConsole(), MainFrame::ShowHideStartPage(), cbDebuggerPlugin::ShowLog(), ProjectManagerUI::ShowMenu(), cbProject::ShowNotes(), MainFrame::ShowTips(), DebugInterfaceFactory::ShowValueTooltip(), cbSmartIndentPlugin::SmartIndentEnabled(), cbEditor::Split(), GDB_driver::Start(), CompilerGCC::StartCompileFile(), CompilerGCC::StopRunningDebugger(), EditorManager::SwapActiveHeaderSource(), GDB_driver::SwitchThread(), cbDebuggerPlugin::SwitchToDebuggingLayout(), DebuggerGDB::SwitchToFrame(), cbDebuggerPlugin::SwitchToPreviousLayout(), ProjectManagerUI::SwitchToProjectsPage(), CfgMgrBldr::SwitchToR(), cbSearchResultsLog::SyncEditor(), cbDebuggerPlugin::SyncEditor(), TemplateManager::TemplateManager(), RecentItemsList::TerminateHistory(), EditorBase::ThereAreOthers(), ThreadsDlg::ThreadsDlg(), cbEditor::ToggleBreakpoint(), ProjectFileOptionsDlg::ToggleFileReadOnly(), cbDebuggerPlugin::ToolMenuEnabled(), ToolsManager::ToolsManager(), PluginManager::UninstallPlugin(), cbAuiNotebook::UniqueIdFromTooltip(), DebuggerManager::UnregisterDebugger(), ScriptingManager::UnRegisterScriptMenu(), pfDetails::Update(), DebuggerGDB::UpdateBreakpoint(), ClassBrowser::UpdateClassBrowserView(), CodeCompletion::UpdateEditorSyntax(), CCManager::UpdateEnvSettings(), CompilerSettingsDlg::UpdateListbookImages(), EditorConfigurationDlg::UpdateListbookImages(), ClassBrowser::UpdateSash(), TextCtrlLogger::UpdateSettings(), ListCtrlLogger::UpdateSettings(), CodeCompletion::UpdateToolBar(), UpdateWatch(), UserVariableManager::UserVariableManager(), UsrGlblMgrEditDialog::UsrGlblMgrEditDialog(), DebuggerConfigurationPanel::ValidateExecutablePath(), CodeRefactoring::VerifyResult(), WatchesDlg::WatchesDlg(), WizCompilerPanel::WizCompilerPanel(), WizFilePathPanel::WizFilePathPanel(), WizGenericSelectPathPanel::WizGenericSelectPathPanel(), WizGenericSingleChoiceList::WizGenericSingleChoiceList(), WizPageBase::WizPageBase(), ProjectManager::WorkspaceChanged(), ConfigManagerWrapper::Write(), WriteActiveDebuggerConfig(), EnvironmentSettingsDlg::WriteApplicationColours(), ScriptBindings::IOLib::WriteFileContents(), DocumentationHelper::WriteOptions(), Parser::WriteOptions(), ScriptBindings::wx_GetColourFromUser(), CCManager::~CCManager(), ClassBrowser::~ClassBrowser(), DebuggerManager::~DebuggerManager(), DebuggerOptionsProjectDlg::~DebuggerOptionsProjectDlg(), DebugInterfaceFactory::~DebugInterfaceFactory(), DirectCommands::~DirectCommands(), EditorBase::~EditorBase(), EditorManager::~EditorManager(), FindReplaceDlg::~FindReplaceDlg(), and ScriptingManager::~ScriptingManager().
Get() [2/2]
Manager * Manager::Get (wxFrame * appWindow) static
Definition at line 166 of file manager.cpp.
References _(), _T, cbThrow, Get(), GetLogManager(), LoadResource(), LogManager::Log(), and m_pAppWindow.
GetAppFrame()
wxFrame * Manager::GetAppFrame () const
Definition at line 419 of file manager.cpp.
References m_pAppWindow.
Referenced by ProjectManager::AddMultipleFilesToProject(), ScriptBindings::CallMenu(), CCManager::CCManager(), CreateEmptyToolbar(), MenuItemsManager::CreateFromString(), CompilerGCC::DoRecreateTargetMenu(), IPC::Entry(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), RecentItemsList::GetMenu(), DebuggerManager::GetMenu(), DebuggerManager::HasMenu(), DebuggerMenuHandler::OnUpdateUI(), CompilerGCC::OnUpdateUI(), ProjectManagerUI::OnViewCategorize(), ProjectManagerUI::OnViewHideFolderName(), ProjectManagerUI::OnViewUseFolders(), MainFrame::PopupToggleToolbarMenu(), ScriptingManager::RegisterScriptMenu(), and CCManager::~CCManager().
GetAppWindow()
wxWindow * Manager::GetAppWindow () const
Definition at line 424 of file manager.cpp.
References m_pAppWindow.
Referenced by cbPlugin::Attach(), cbDebuggerPlugin::BringCBToFront(), cbGetMultiChoiceDialog(), cbGetSingleChoiceIndex(), cbGetTextFromUser(), cbMessageBox(), cbSearchResultsLog::CreateControl(), CompilerMessages::CreateControl(), CompilerMessages::DestroyControls(), EditorManager::EditorManager(), FindReplace::FindInFiles(), ProjectManagerUI::OnAddFileToProject(), ProjectManagerUI::OnCloseProject(), DebuggerToolbarHandler::OnDebugWindows(), ProjectManagerUI::OnProperties(), DebuggerToolbarHandler::OnStop(), DebuggerToolbarHandler::OnToolInfo(), PlaceWindow(), PluginManager::PluginManager(), ProjectManager::ProjectManager(), ProjectManagerUI::ProjectManagerUI(), ScriptingManager::RegisterScriptMenu(), ScriptingManager::RegisterScriptPlugin(), cbPlugin::Release(), FindReplace::ReplaceInFiles(), CodeRefactoring::SearchInFiles(), MainFrame::SetupDebuggerUI(), TemplateManager::TemplateManager(), and ToolsManager::ToolsManager().
GetCCManager()
CCManager * Manager::GetCCManager () const
Definition at line 494 of file manager.cpp.
References Mgr< CCManager >::Get().
Referenced by PluginsConfigurationDlg::EndModal(), MainFrame::MainFrame(), MainFrame::OnEditHighlightMode(), cbStyledTextCtrl::OnKeyDown(), and MainFrame::OnSettingsEnvironment().
GetCmdLineParser()
wxCmdLineParser * Manager::GetCmdLineParser () static
Definition at line 545 of file manager.cpp.
References m_CmdLineParser.
Referenced by CodeBlocksApp::OnInit(), and CodeBlocksApp::ParseCmdLine().
GetColourManager()
ColourManager * Manager::GetColourManager () const
Definition at line 489 of file manager.cpp.
References Mgr< ColourManager >::Get().
Referenced by EditorColourSet::Apply(), BacktraceDlg::BacktraceDlg(), CCManager::CCManager(), CCOptionsDlg::CCOptionsDlg(), ProjectManagerUI::CheckForExternallyModifiedProjects(), MainFrame::CreateIDE(), DocumentationHelper::DocumentationHelper(), EditorConfigurationDlg::EditorConfigurationDlg(), EditorManager::EditorManager(), EnvironmentSettingsDlg::EndModal(), EditorConfigurationDlg::EndModal(), EnvironmentSettingsDlg::FillApplicationColours(), DocumentationHelper::GenerateHTML(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), LogManager::LogManager(), CCOptionsDlg::OnApply(), EnvironmentSettingsDlg::OnChooseAppColourItem(), EnvironmentSettingsDlg::OnClickAppColour(), ProjectManagerUI::ProjectManagerUI(), StartHerePage::RegisterColours(), ThreadsDlg::Reload(), BacktraceDlg::Reload(), StartHerePage::Reload(), ThreadsDlg::ThreadsDlg(), CCManager::UpdateEnvSettings(), TextCtrlLogger::UpdateSettings(), ListCtrlLogger::UpdateSettings(), UpdateWatch(), WatchesDlg::WatchesDlg(), and EnvironmentSettingsDlg::WriteApplicationColours().
GetConfigManager()
ConfigManager * Manager::GetConfigManager (const wxString & name_space) const
Definition at line 474 of file manager.cpp.
References CfgMgrBldr::GetConfigManager().
Referenced by CompilerGCC::AddOutputLine(), CompilerGCC::AllocProcesses(), EditorColourSet::Apply(), AutoDetectCompilers::AutoDetectCompilers(), cbSmartIndentPlugin::AutoIndentEnabled(), cbSmartIndentPlugin::BraceCompletionEnabled(), cbSmartIndentPlugin::BraceSmartIndentEnabled(), cbAuiNotebook::cbAuiNotebook(), cbReadBatchBuildPlugins(), cbWriteBatchBuildPlugins(), CCOptionsDlg::CCOptionsDlg(), EditorConfigurationDlg::ChangeTheme(), CodeBlocksApp::CheckVersion(), ClassBrowser::ClassBrowser(), RecentItemsList::ClearHistory(), EditorManager::CollectDefines(), CompilerMessages::CompilerMessages(), ScriptBindings::ConfigManager_Read(), ScriptBindings::ConfigManager_Write(), UserVariableManager::Configure(), CompilerGCC::Configure(), EncodingDetector::ConvertToWxString(), NativeParser::CreateClassBrowser(), cbEditor::CreateEditor(), CreateEmptyToolbar(), MainFrame::CreateIDE(), ProjectManagerUI::CreateMenuTreeProps(), DebuggerManager::DebuggerManager(), EncodingDetector::DetectEncoding(), DisassemblyDlg::DisassemblyDlg(), CodeCompletion::DoAllMethodsImpl(), Associations::DoClearAssociation(), CompilerOptionsDlg::DoFillOthers(), MainFrame::DoOnFileOpen(), CompilerGCC::DoRegisterCompilers(), CompilerGCC::DoRunQueue(), MainFrame::DoSelectLayout(), Associations::DoSetAssociation(), MainFrame::DoUpdateEditorStyle(), MainFrame::DoUpdateLayoutColours(), EditorConfigurationDlg::EditorConfigurationDlg(), EditorManager::EditorManager(), PrintDialog::EndModal(), CompilerSettingsDlg::EndModal(), EnvironmentSettingsDlg::EndModal(), BatchLogWindow::EndModal(), PluginsConfigurationDlg::EndModal(), NewFromTemplateDlg::EndModal(), ScriptingSettingsDlg::EndModal(), EditorConfigurationDlg::EndModal(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), Compiler::EvalXMLCondition(), ExamineMemoryDlg::ExamineMemoryDlg(), ToolsManager::Execute(), ParserCommon::FileType(), FindReplaceDlg::FillComboWithLastValues(), ScriptingSettingsDlg::FillScripts(), ScriptingSettingsDlg::FillTrusts(), FindReplace::Find(), FindReplaceDlg::FindReplaceDlg(), cbEditor::FixFoldState(), ScriptBindings::getCM(), ProjectManager::GetDefaultPath(), GetEOLStr(), cbDebuggerCommonConfig::GetFlag(), CompilerCommandGenerator::GetOrderedIncludeDirs(), cbDebuggerCommonConfig::GetPerspective(), ConfigManager::GetProxy(), GetShellString(), cbDebuggerCommonConfig::GetValueTooltipFont(), IMPLEMENT_APP(), AnnoyingDialog::Init(), CodeBlocksApp::InitAssociations(), RecentItemsList::Initialize(), CodeBlocksApp::InitLocale(), InitPrinting(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), DirectCommands::IsObjectOutdated(), ColourManager::Load(), FilesGroupsAndMasks::Load(), GetUserVariableDialog::Load(), EditorColourSet::Load(), PluginManager::LoadAllPlugins(), Compiler::LoadDefaultOptions(), cbProject::LoadLayout(), Compiler::LoadSettings(), EditorConfigurationDlg::LoadThemes(), ToolsManager::LoadTools(), MainFrame::LoadWindowSize(), MainFrame::LoadWindowState(), MainFrame::MainFrame(), UserVariableManager::Migrate(), NativeParser::NativeParser(), EditorManager::New(), DebuggerManager::NewConfig(), TemplateManager::NewProjectFromUserTemplate(), CodeBlocksApp::OnAppActivate(), CCOptionsDlg::OnApply(), CompilerOptionsDlg::OnApply(), CompilerGCC::OnAttach(), CompilerMessages::OnAutoFit(), ScriptConsole::OnbtnLoadClick(), AnnoyingDialog::OnButton(), CCManager::OnCompleteCode(), EditorConfigurationDlg::OnDeleteColourTheme(), MainFrame::OnEditorActivated(), cbEditor::OnEditorCharAdded(), CCManager::OnEditorHook(), CCManager::OnEditorTooltip(), MainFrame::OnEditSelectNextSkip(), PluginsConfigurationDlg::OnExport(), MainFrame::OnFileSaveAll(), ProjectManagerUI::OnFindFile(), ExamineMemoryDlg::OnGo(), CodeBlocksApp::OnInit(), CompilerGCC::OnJobEnd(), DebugLogPanel::OnLoadFile(), GotoFunctionDlg::OnModeClick(), MainFrame::OnNotebookDoubleClick(), DebuggerSettingsDlg::OnOK(), WizPageBase::OnPageChanging(), WizFilePathPanel::OnPageChanging(), WizGenericSelectPathPanel::OnPageChanging(), WizCompilerPanel::OnPageChanging(), WizGenericSingleChoiceList::OnPageChanging(), CompilerGCC::OnRelease(), EditorConfigurationDlg::OnRenameColourTheme(), MainFrame::OnSearchMenuUpdateUI(), ClassBrowser::OnSetSortType(), MainFrame::OnSettingsEnvironment(), CCManager::OnShowCallTip(), ProjectManagerUI::OnTabContextMenu(), InfoPane::OnTabPosition(), ProjectManagerUI::OnTabPosition(), EditorManager::OnTabPosition(), PluginsConfigurationDlg::OnToggle(), MainFrame::OnToggleStatusBar(), CCOptionsDlg::OnUpdateUI(), ProjectManagerUI::OnViewCategorize(), MainFrame::OnViewHideEditorTabs(), ProjectManagerUI::OnViewHideFolderName(), MainFrame::OnViewLayoutSave(), ClassBrowser::OnViewScope(), ProjectManagerUI::OnViewUseFolders(), cbEditor::OnZoom(), cbEditor::Open(), EditorManager::OpenContainingFolder(), PlaceWindow(), PluginsConfigurationDlg::PluginsConfigurationDlg(), cbEditor::Print(), PrintDialog::PrintDialog(), DebuggerManager::ProcessSettings(), ProjectManagerUI::ProjectManagerUI(), ProjectManagerUI::QueryCloseWorkspace(), ConfigManagerWrapper::Read(), ReadActiveDebuggerConfig(), ConfigManagerWrapper::ReadBool(), ConfigManagerWrapper::ReadDouble(), ConfigManagerWrapper::ReadInt(), Parser::ReadOptions(), CompilerGCC::Rebuild(), CompilerGCC::RebuildWorkspace(), ScriptingManager::RefreshTrusts(), CompilerFactory::RegisterUserCompilers(), CompilerFactory::RemoveCompiler(), NativeParser::RemoveObsoleteParsers(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), DocumentationHelper::RereadOptions(), CodeCompletion::RereadOptions(), NativeParser::RereadParserOptions(), EditorColourSet::Reset(), CompilerGCC::Run(), cbDebuggerPlugin::RunNixConsole(), CompilerGCC::RunSingleFile(), MainFrame::RunStartupScripts(), ColourManager::Save(), FilesGroupsAndMasks::Save(), EditorColourSet::Save(), cbEditor::SaveAs(), FindReplaceDlg::SaveComboValues(), cbProject::SaveLayout(), CompilerFactory::SaveSettings(), Compiler::SaveSettings(), ToolsManager::SaveTools(), MainFrame::SaveWindowState(), ScriptBindings::IOLib::SecurityAllows(), cbSmartIndentPlugin::SelectionBraceCompletionEnabled(), ProjectManager::SetDefaultPath(), DebuggerManager::SetDisassemblyMixedMode(), cbEditor::SetEditorStyleAfterFileOpen(), cbEditor::SetEditorStyleBeforeFileOpen(), cbDebuggerCommonConfig::SetFlag(), cbEditorInternalData::SetLineNumberColWidth(), cbDebuggerCommonConfig::SetPerspective(), MainFrame::SetupGUILogging(), PluginManager::SetupLocaleDomain(), cbDebuggerCommonConfig::SetValueTooltipFont(), CompilerMINGW::SetVersionString(), MainFrame::ShowHideStartPage(), MainFrame::ShowTips(), cbSmartIndentPlugin::SmartIndentEnabled(), cbEditor::Split(), RecentItemsList::TerminateHistory(), ClassBrowser::UpdateSash(), TextCtrlLogger::UpdateSettings(), ListCtrlLogger::UpdateSettings(), CodeCompletion::UpdateToolBar(), UserVariableManager::UserVariableManager(), UsrGlblMgrEditDialog::UsrGlblMgrEditDialog(), WizCompilerPanel::WizCompilerPanel(), WizFilePathPanel::WizFilePathPanel(), WizGenericSelectPathPanel::WizGenericSelectPathPanel(), WizGenericSingleChoiceList::WizGenericSingleChoiceList(), WizPageBase::WizPageBase(), ConfigManagerWrapper::Write(), WriteActiveDebuggerConfig(), DocumentationHelper::WriteOptions(), Parser::WriteOptions(), ClassBrowser::~ClassBrowser(), EditorManager::~EditorManager(), FindReplaceDlg::~FindReplaceDlg(), and ScriptingManager::~ScriptingManager().
GetDebuggerManager()
DebuggerManager * Manager::GetDebuggerManager () const
Definition at line 484 of file manager.cpp.
References Mgr< DebuggerManager >::Get().
Referenced by DbgCmd_UpdateWatchesTree::Action(), cbEditor::AddBreakpoint(), CodeBlocksApp::AttachDebugger(), DebuggerMenuHandler::BuildContextMenu(), cbDebuggerPlugin::BuildMenu(), cbDebuggerPlugin::BuildModuleMenu(), cbDebuggerPlugin::CancelValueTooltip(), DebuggerGDB::CleanupWhenProjectClosed(), DisassemblyDlg::Clear(), cbDebuggerPlugin::ClearLog(), ValueTooltip::ClearWatch(), MainFrame::CreateMenubar(), DebuggerMenuHandler::DebuggerMenuHandler(), DebuggerSettingsDlg::DebuggerSettingsDlg(), WatchesDlg::DeleteProperty(), CompilerOptionsDlg::DoFillCompilerPrograms(), DebuggerGDB::DoWatches(), GdbCmd_ExamineMemory::GdbCmd_ExamineMemory(), cbDebuggerPlugin::GetActiveConfig(), BacktraceDlg::IsSwitchFrameEnabled(), DebuggerMenuHandler::LogActiveConfig(), DebuggerMenuHandler::OnActiveDebuggerClick(), DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick(), DebuggerMenuHandler::OnAddDataBreakpoint(), DebuggerMenuHandler::OnAddWatch(), cbDebuggerPlugin::OnAttach(), cbEditor::OnBeforeBuildContextMenu(), BreakpointsDlg::OnBreakpointAdd(), WatchesDlg::OnCollapse(), ValueTooltip::OnCollapse(), DebuggerGDB::OnConfigurationChange(), cbEditor::OnContextMenuEntry(), DebuggerGDB::OnCursorChanged(), WatchesDropTarget::OnDropText(), cbEditor::OnEditorModified(), DebugLogPanel::OnEntryCommand(), WatchesDlg::OnExpand(), ValueTooltip::OnExpand(), DebuggerGDB::OnGDBTerminated(), ExamineMemoryDlg::OnGo(), BacktraceDlg::OnJump(), WatchesDlg::OnKeyDown(), DebugLogPanel::OnLoadFile(), WatchesDlg::OnMenuAddDataBreak(), WatchesDlg::OnMenuDeleteAll(), WatchesDlg::OnMenuExamineMemory(), WatchesDlg::OnMenuProperties(), WatchesDlg::OnMenuUpdate(), DebuggerGDB::OnMenuWatchDereference(), DisassemblyDlg::OnMixedModeCB(), DebuggerSettingsDlg::OnOK(), WatchesDlg::OnPropertyRightClick(), WatchesDlg::OnPropertySelected(), DisassemblyDlg::OnRefresh(), cbDebuggerPlugin::OnRelease(), DebuggerMenuHandler::OnRemoveAllBreakpoints(), DebuggerToolbarHandler::OnStop(), BacktraceDlg::OnSwitchFrame(), ThreadsDlg::OnSwitchThread(), DebuggerToolbarHandler::OnToolInfo(), DebuggerToolbarHandler::OnUpdateUI(), DebugLogPanel::OnUpdateUI(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), CdbCmd_Backtrace::ParseOutput(), GdbCmd_AddBreakpoint::ParseOutput(), CdbCmd_SwitchFrame::ParseOutput(), CdbCmd_InfoRegisters::ParseOutput(), GdbCmd_AddDataBreakpoint::ParseOutput(), CdbCmd_Disassembly::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_Threads::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), GdbCmd_InfoRegisters::ParseOutput(), GdbCmd_Disassembly::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_ExamineMemory::ParseOutput(), GdbCmd_StepOrNextInstruction::ParseOutput(), GdbCmd_InfoRegisters::ParseOutputFromOR32gdbPort(), DebuggerMenuHandler::RebuildMenus(), cbEditor::RefreshBreakpointMarkers(), WatchesDlg::RefreshUI(), DebuggerMenuHandler::RegisterDefaultWindowItems(), ThreadsDlg::Reload(), BacktraceDlg::Reload(), BreakpointsDlg::Reload(), cbEditor::RemoveBreakpoint(), WatchesDlg::RenameWatch(), DebuggerDriver::ResetCurrentFrame(), DebuggerGDB::RunToCursor(), DisassemblyDlg::SetActiveAddress(), ExamineMemoryDlg::SetBaseAddress(), MainFrame::SetupDebuggerUI(), SetValue(), cbDebuggerPlugin::ShowLog(), GDB_driver::Start(), CompilerGCC::StopRunningDebugger(), DebuggerGDB::SwitchToFrame(), cbEditor::ToggleBreakpoint(), and DebuggerManager::UnregisterDebugger().
GetEditorManager()
EditorManager * Manager::GetEditorManager () const
Definition at line 434 of file manager.cpp.
References Mgr< EditorManager >::Get().
Referenced by EditorBase::Activate(), NativeParser::AddProjectToParser(), BreakpointsDlg::BreakpointProperties(), EditorConfigurationDlg::ChangeTheme(), cbDebuggerPlugin::ClearActiveMarkFromAllEditors(), cbProject::CloseAllFiles(), ProjectManager::CloseProject(), CompilerGCC::CompileFileWithoutProject(), CrashHandlerSaveEditorFiles(), EditorBase::CreateContextSubMenu(), MainFrame::CreateIDE(), MainFrame::CreateMenubar(), DisassemblyDlg::DisassemblyDlg(), EditorBase::DisplayContextMenu(), CodeCompletion::DoAllMethodsImpl(), CompilerGCC::DoBuild(), CodeCompletion::DoClassMethodDeclImpl(), CompilerErrors::DoClearErrorMarkFromAllEditors(), CodeRefactoring::DoFindReferences(), CompilerErrors::DoGotoError(), ProjectManagerUI::DoOpenFile(), MainFrame::DoOpenFile(), CodeCompletion::DoParseOpenedProjectAndActiveEditor(), CodeRefactoring::DoRenameSymbols(), MainFrame::DoUpdateAppTitle(), MainFrame::DoUpdateEditorStyle(), MainFrame::DoUpdateStatusBar(), EditorBase::EditorBase(), ScriptBindings::EditorManager_Close(), ScriptBindings::EditorManager_GetBuiltinEditor(), ScriptBindings::EditorManager_Open(), ScriptBindings::EditorManager_Save(), NewFromTemplateDlg::EditScript(), BreakpointsDlg::EnableBreakpoint(), EnvironmentSettingsDlg::EndModal(), EditorConfigurationDlg::EndModal(), ProjectFileOptionsDlg::FillGeneralProperties(), FindReplace::FindInFiles(), FindReplace::FindNext(), FindReplaceDlg::FindReplaceDlg(), FindReplace::FindSelectedText(), NativeParser::GetCurrentProject(), cbDebuggerPlugin::GetEditorWordAtCaret(), ScriptBindings::getEM(), CodeRefactoring::GetOpenedFiles(), NativeParser::GetParserInfoByCurrentEditor(), CCManager::GetProviderFor(), GetSelectedText(), CodeRefactoring::GetSymbolUnderCursor(), CodeCompletion::GotoFunctionPrevNext(), CCManager::InjectAutoCompShow(), InsertNewLine(), FileManager::Load(), CodeBlocksApp::LoadDelayedFiles(), WorkspaceLoader::LoadLayout(), cbProject::LoadLayout(), ProjectLayoutLoader::LoadNotebookLayout(), NativeParser::MarkItemsByAI(), CCManager::NotifyDocumentation(), CodeBlocksApp::OnAppActivate(), CCManager::OnAutocompleteSelect(), BreakpointsDlg::OnBreakpointEdit(), cbEditor::OnClose(), ProjectManagerUI::OnCloseFile(), CCManager::OnCompleteCode(), EditorBase::OnContextMenuEntry(), cbEditor::OnContextMenuEntry(), CCManager::OnDeactivateApp(), CCManager::OnDeactivateEd(), CCManager::OnDeferredCallTipCancel(), DocumentationHelper::OnDocumentationLink(), MainFrame::OnEditBookmarksClearAll(), MainFrame::OnEditBookmarksNext(), MainFrame::OnEditBookmarksPrevious(), MainFrame::OnEditBookmarksToggle(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditClearHistory(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditCopy(), MainFrame::OnEditCut(), MainFrame::OnEditEncoding(), MainFrame::OnEditEOLMode(), MainFrame::OnEditFoldAll(), MainFrame::OnEditFoldBlock(), MainFrame::OnEditGotoLineEnd(), MainFrame::OnEditGotoMatchingBrace(), MainFrame::OnEditHighlightMode(), MainFrame::OnEditInsertNewLine(), MainFrame::OnEditLineCopy(), MainFrame::OnEditLineCut(), MainFrame::OnEditLineDelete(), MainFrame::OnEditLineDuplicate(), MainFrame::OnEditLineMove(), MainFrame::OnEditLinePaste(), MainFrame::OnEditLineTranspose(), MainFrame::OnEditLowerCase(), MainFrame::OnEditMenuUpdateUI(), CodeCompletion::OnEditorActivated(), NativeParser::OnEditorActivated(), CodeCompletion::OnEditorActivatedTimer(), CCManager::OnEditorClose(), CodeCompletion::OnEditorClosed(), CCManager::OnEditorOpen(), CodeCompletion::OnEditorOpen(), MainFrame::OnEditorUpdateUI(), MainFrame::OnEditParaDown(), MainFrame::OnEditParaDownExtend(), MainFrame::OnEditParaUp(), MainFrame::OnEditParaUpExtend(), MainFrame::OnEditPaste(), MainFrame::OnEditRedo(), MainFrame::OnEditSelectAll(), MainFrame::OnEditSelectNext(), MainFrame::OnEditSelectNextSkip(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditSwapHeaderSource(), MainFrame::OnEditToggleAllFolds(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditToggleFoldBlock(), MainFrame::OnEditUncommentSelected(), MainFrame::OnEditUndo(), MainFrame::OnEditUnfoldAll(), MainFrame::OnEditUnfoldBlock(), MainFrame::OnEditUpperCase(), MainFrame::OnEditWordPartLeft(), MainFrame::OnEditWordPartLeftExtend(), MainFrame::OnEditWordPartRight(), MainFrame::OnEditWordPartRightExtend(), MainFrame::OnEditZoomIn(), MainFrame::OnEditZoomOut(), MainFrame::OnEditZoomReset(), BreakpointsDlg::OnEnable(), MainFrame::OnFileClose(), MainFrame::OnFileCloseAll(), MainFrame::OnFileMenuUpdateUI(), MainFrame::OnFileNewWhat(), MainFrame::OnFileNext(), MainFrame::OnFilePrev(), MainFrame::OnFilePrint(), MainFrame::OnFileSaveAll(), MainFrame::OnFileSaveAs(), MainFrame::OnFocusEditor(), CodeCompletion::OnFunction(), CCDebugInfo::OnGoDeclClick(), CCDebugInfo::OnGoImplClick(), CodeCompletion::OnGotoDeclaration(), CodeCompletion::OnGotoFunction(), MainFrame::OnHighlightMenu(), cbAuiNotebook::OnIdle(), CompilerGCC::OnJobEnd(), ClassBrowser::OnJumpTo(), CCManager::OnMenuSelect(), BreakpointsDlg::OnOpen(), CodeCompletion::OnOpenIncludeFile(), ProjectManagerUI::OnOpenWith(), CodeCompletion::OnParserEnd(), CodeCompletion::OnParserStart(), NativeParser::OnParsingOneByOneTimer(), ProjectManagerUI::OnProperties(), ProjectFileOptionsDlg::OnReadOnlyCheck(), CodeCompletion::OnRealtimeParsingTimer(), BreakpointsDlg::OnRemove(), CodeCompletion::OnReparsingTimer(), DebuggerMenuHandler::OnRunToCursor(), ProjectManagerUI::OnSaveFile(), ScriptingManager::OnScriptMenu(), MainFrame::OnSearchFind(), MainFrame::OnSearchGotoLine(), MainFrame::OnSearchGotoNextChanged(), MainFrame::OnSearchGotoPrevChanged(), MainFrame::OnSearchMenuUpdateUI(), MainFrame::OnSearchReplace(), DebuggerMenuHandler::OnSetNextStatement(), MainFrame::OnSettingsEditor(), MainFrame::OnSettingsEnvironment(), MainFrame::OnShiftTab(), CCManager::OnShowCallTip(), MainFrame::OnSwitchTabs(), CCManager::OnTimer(), DebuggerMenuHandler::OnToggleBreakpoint(), ClassBrowser::OnTreeItemDoubleClick(), DebuggerMenuHandler::OnUpdateUI(), DebuggerToolbarHandler::OnUpdateUI(), ProjectManagerUI::OnUpdateUI(), CompilerGCC::OnUpdateUI(), CodeCompletion::OnUpdateUI(), MainFrame::OnViewHideEditorTabs(), MainFrame::OnViewMenuUpdateUI(), cbEditor::OnZoom(), CodeRefactoring::Parse(), CodeCompletion::ParseFunctionsAndFillToolbar(), GdbCmd_AddBreakpointCondition::ParseOutput(), CompilerGCC::PrepareCompileFile(), PrintDialog::PrintDialog(), CCManager::ProcessArrow(), cbProject::QueryCloseAllFiles(), RefreshBreakpoints(), RecentItemsList::RefreshStartHerePage(), BreakpointsDlg::RemoveAllBreakpoints(), cbProject::RemoveFile(), FindReplace::ReplaceInFiles(), MacrosManager::ReplaceMacros(), Wiz::RunFilesWizard(), ProjectLayoutLoader::Save(), cbProject::SaveAllFiles(), CodeRefactoring::SearchInFiles(), EditorBase::SetTitle(), FindReplace::ShowFindDialog(), MainFrame::ShowHideStartPage(), ProjectManagerUI::ShowMenu(), DebugInterfaceFactory::ShowValueTooltip(), cbSearchResultsLog::SyncEditor(), cbDebuggerPlugin::SyncEditor(), ClassBrowser::UpdateClassBrowserView(), CodeCompletion::UpdateEditorSyntax(), CCManager::UpdateEnvSettings(), CodeRefactoring::VerifyResult(), ProjectManager::WorkspaceChanged(), and EditorBase::~EditorBase().
GetFileManager()
FileManager * Manager::GetFileManager () const
Definition at line 479 of file manager.cpp.
References Mgr< FileManager >::Get().
Referenced by cbSaveToFile(), cbProject::LoadLayout(), CodeBlocksApp::OnInit(), EditorManager::Open(), cbEditor::Open(), Parser::Parse(), and TinyXML::SaveDocument().
GetLogManager()
LogManager * Manager::GetLogManager () const
Definition at line 439 of file manager.cpp.
References Mgr< LogManager >::Get().
Referenced by cbProject::AddBuildTarget(), cbProject::AddFile(), CompilerGCC::AddOutputLine(), ProjectManager::AddProjectDependency(), Wiz::AddWizard(), DirectCommands::AreExternalDepsOutdated(), CodeBlocksApp::AttachDebugger(), cbEditor::AutoComplete(), CompilerGDC::AutoDetectInstallationDir(), ProjectManagerUI::BuildProjectTree(), cbProject::CalculateCommonTopLevelPath(), CompilerGCC::CalculateProjectDependencies(), EditorHooks::CallHooks(), cbEditorInternalData::cbEditorInternalData(), ProjectManagerUI::CheckForExternallyModifiedProjects(), ProjectManager::ClearProjectDependencies(), CodeBlocksLogEvent::CodeBlocksLogEvent(), DirectCommands::CompileFile(), Compiler::Compiler(), CompilerFactory::CompilerInheritsFrom(), EncodingDetector::ConvertToWxString(), CompilerFactory::CreateCompilerCopy(), MainFrame::CreateIDE(), MainFrame::CreateMenubar(), MainFrame::CreateToolbars(), cbDebuggerPlugin::DebugLog(), cbProject::DefineVirtualBuildTarget(), InfoPane::DeleteLogger(), EncodingDetector::DetectEncoding(), DirectCommands::DirectCommands(), CompilerGCC::DistClean(), CompilerGCC::DoBuild(), ProjectLoader::DoBuildTarget(), EditorLexerLoader::DoLexer(), ProjectManagerUI::DoOpenFile(), CompilerGCC::DoRegisterCompilers(), ProjectLoader::DoUnits(), CompilerGCC::DoWorkspaceBuild(), EditorManager::EditorManager(), ToolsManager::Execute(), PluginManager::ExecutePlugin(), ExpandBackticks(), DebuggerManager::FindTargetsDebugger(), ScriptBindings::gBuildLog(), ScriptBindings::gDebugLog(), CompilerCommandGenerator::GenerateCommandLine(), Wiz::GenerateFile(), CompileTargetBase::GenerateTargetFilename(), ScriptBindings::gErrorLog(), Get(), DirectCommands::GetCompileFileCommand(), CompileTargetBase::GetDynamicLibDefFilename(), CompileTargetBase::GetDynamicLibFilename(), CompileTargetBase::GetDynamicLibImportFilename(), DebuggerManager::GetLogger(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), CompilerCommandGenerator::GetOrderedResourceIncludeDirs(), GetpMsg(), CompileTargetBase::GetStaticLibFilename(), GetUserVariableDialog::GetUserVariableDialog(), ScriptBindings::gLog(), ScriptBindings::gWarningLog(), CompilerCommandGenerator::Init(), AnnoyingDialog::Init(), PluginManager::InstallPlugin(), CompilerLCC::IsValid(), CompilerGCC::KillProcess(), EditorLexerLoader::Load(), cbWorkspace::Load(), PluginManager::LoadAllPlugins(), EditorColourSet::LoadAvailableSets(), ScriptingManager::LoadBuffer(), Compiler::LoadDefaultOptions(), WorkspaceLoader::LoadLayout(), cbWorkspace::LoadLayout(), cbProject::LoadLayout(), PluginManager::LoadPlugin(), Compiler::LoadRegExArray(), LoadResource(), ScriptingManager::LoadScript(), CompilerFactory::LoadSettings(), ToolsManager::LoadTools(), TemplateManager::LoadUserTemplates(), ProfileTimer::Log(), cbDebuggerPlugin::Log(), CompilerGCC::LogMessage(), MainFrame::MainFrame(), TemplateManager::NewProjectFromUserTemplate(), cbPlugin::NotImplemented(), MainFrame::OnAddLogWindow(), MainFrame::OnApplicationClose(), CompilerGCC::OnAttach(), cbEditorPrintout::OnBeginDocument(), WizPage::OnButton(), CodeCompletion::OnCCDebugLogger(), CodeCompletion::OnCCLogger(), CompilerGCC::OnCleanFile(), CompilerGCC::OnCompileFileRequest(), CompilerOptionsDlg::OnCopyDirsClick(), CompilerOptionsDlg::OnCopyLibsClick(), ProjectManagerUI::OnGotoFile(), MainFrame::OnHelpPluginMenu(), CodeBlocksApp::OnInit(), CompilerGCC::OnJobEnd(), ProjectManagerUI::OnOpenWith(), MainFrame::OnPluginLoaded(), MainFrame::OnPluginsExecuteMenu(), cbEditorPrintout::OnPrintPage(), ProjectFileOptionsDlg::OnReadOnlyCheck(), ProjectOptionsDlg::OnRemoveBuildTargetClick(), ProjectManagerUI::OnRemoveFileFromProject(), MainFrame::OnSettingsEnvironment(), ToolsManager::OnToolErrOutput(), ToolsManager::OnToolStdOutput(), ToolsManager::OnToolTerminated(), ProjectLayoutLoader::Open(), ProjectTemplateLoader::Open(), ProjectLoader::Open(), MainFrame::Open(), EditorManager::Open(), cbEditor::Open(), cbProject::Open(), EditorManager::OpenContainingFolder(), OpenContainingFolderData::OpenContainingFolderData(), CodeBlocksApp::ParseCmdLine(), CdbCmd_Watch::ParseOutput(), GdbCmd_Watch::ParseOutput(), CompilerCommandGenerator::PathSearch(), CompilerGCC::PreprocessJob(), CompilerGCC::PrintInvalidCompiler(), ProcessEvent(), PluginManager::ReadExtraFilesFromManifestFile(), PluginManager::ReadManifestFile(), DebuggerManager::RegisterDebugger(), PluginManager::RegisterPlugin(), ScriptBindings::ScriptPluginWrapper::RegisterPlugin(), ScriptingManager::RegisterScriptMenu(), DebuggerMenuHandler::RegisterWindowMenu(), CompilerFactory::RemoveCompiler(), cbProject::RemoveFile(), ProjectManager::RemoveFileFromProject(), ProjectManager::RemoveProjectDependency(), ProjectManager::RemoveProjectFromAllDependencies(), cbProject::ReOrderTargets(), EncodingDetector::Report(), CompilerGCC::Run(), Wiz::RunProjectWizard(), CompilerGCC::RunSingleFile(), MainFrame::RunStartupScripts(), cbWorkspace::Save(), cbEditor::SaveAs(), CompilerGCC::SaveBuildLog(), cbWorkspace::SaveLayout(), TemplateManager::SaveUserTemplate(), PluginManager::ScanForPlugins(), MainFrame::ScanForPlugins(), cbEditor::SetProjectFile(), CompilerGCC::SetupEnvironment(), MainFrame::SetupGUILogging(), CompilerCommandGenerator::SetupOutputFilenames(), ScriptBindings::ShowDialog(), CompilerGCC::StartCompileFile(), CompilerGCC::StopRunningDebugger(), cbDebuggerPlugin::SwitchToDebuggingLayout(), cbDebuggerPlugin::SwitchToPreviousLayout(), CfgMgrBldr::SwitchToR(), ProjectFileOptionsDlg::ToggleFileReadOnly(), PluginManager::UninstallPlugin(), ScriptingManager::UnRegisterScriptMenu(), and DirectCommands::~DirectCommands().
GetMacrosManager()
MacrosManager * Manager::GetMacrosManager () const
Definition at line 454 of file manager.cpp.
References Mgr< MacrosManager >::Get().
Referenced by NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), cbProject::AddFile(), NativeParser::AddGCCCompilerDirs(), NativeParser::AddIncludeDirsToParser(), NativeParser::AddProjectDefinedMacros(), DebuggerGDB::AddSourceDir(), DirectCommands::AreExternalDepsOutdated(), AutoDetectCompilers::AutoDetectCompilers(), CompilerICC::AutoDetectInstallationDir(), CompilerGCC::BuildStateManagement(), cbProject::ClearAllProperties(), CompilerGCC::CompileFileWithoutProject(), CompilerGCC::Configure(), DirectCommands::DepsSearchStart(), CompilerCommandGenerator::DoBuildScripts(), CompilerGCC::DoRunQueue(), ToolsManager::Execute(), GdbCmd_RemoteTarget::GdbCmd_RemoteTarget(), CompilerCommandGenerator::GenerateCommandLine(), CodeCompletion::GetAbsolutePath(), cbDebuggerPlugin::GetDebuggee(), DebuggerConfiguration::GetDebuggerExecutable(), CompilerGCC::GetMakeCommandFor(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), CompilerCommandGenerator::GetOrderedResourceIncludeDirs(), CompilerCommandGenerator::GetProcessedIncludeDir(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), DebuggerConfiguration::GetUserArguments(), ScriptBindings::gReplaceMacros(), PluginManager::InstallPlugin(), ProjectOptionsDlg::IsScriptValid(), Compiler::IsValid(), Compiler::MakeInvalidCompilerMessages(), EditorManager::New(), CompilerOptionsDlg::OnApply(), EditPathDlg::OnBrowse(), DebuggerConfigurationPanel::OnBrowse(), WizGenericSelectPathPanel::OnButton(), CompilerGCC::OnCleanFile(), CompilerGCC::OnJobEnd(), ProjectOptionsDlg::OnKeyDown(), WizGenericSelectPathPanel::OnPageChanging(), GDB_driver::Prepare(), CompilerGCC::Run(), cbDebuggerPlugin::RunNixConsole(), CompilerGCC::RunSingleFile(), CompilerCommandGenerator::SetupCompilerOptions(), CompilerGCC::SetupEnvironment(), CompilerOWGenerator::SetupLibrariesDirs(), CompilerOWGenerator::SetupLinkerOptions(), CompilerCommandGenerator::SetupLinkerOptions(), CompilerCommandGenerator::SetupOutputFilenames(), CompilerCommandGenerator::SetupResourceCompilerOptions(), CompilerMINGW::SetVersionString(), EditorManager::SwapActiveHeaderSource(), pfDetails::Update(), and DebuggerConfigurationPanel::ValidateExecutablePath().
GetPersonalityManager()
PersonalityManager * Manager::GetPersonalityManager () const
Definition at line 459 of file manager.cpp.
References Mgr< PersonalityManager >::Get().
Referenced by CodeBlocksApp::SetupPersonality().
GetPluginManager()
PluginManager * Manager::GetPluginManager () const
Definition at line 444 of file manager.cpp.
References Mgr< PluginManager >::Get().
Referenced by ProjectManager::AddFileToProject(), ProjectManager::AddMultipleFilesToProject(), MainFrame::AddPluginInMenus(), CompilerSettingsDlg::AddPluginPanels(), EnvironmentSettingsDlg::AddPluginPanels(), EditorConfigurationDlg::AddPluginPanels(), ProjectOptionsDlg::AddPluginPanels(), cbEditor::AddToContextMenu(), CodeBlocksApp::BatchJob(), DebuggerMenuHandler::BuildContextMenu(), CodeCompletion::BuildModuleMenu(), ProjectManager::CloseProject(), ProjectManager::CloseWorkspace(), CompilerSettingsDlg::CompilerSettingsDlg(), MainFrame::CreateMenubar(), MainFrame::CreateToolbars(), EditorBase::DisplayContextMenu(), MainFrame::DoAddPluginToolbar(), DebuggerGDB::DoBreak(), DebuggerGDB::DoDebug(), ProjectManagerUI::DoOpenFile(), cbStyledTextCtrl::EmulateDwellStart(), ProjectManager::EndLoadingWorkspace(), CompilerSettingsDlg::EndModal(), cbDebuggerPlugin::EnsureBuildUpToDate(), ScriptBindings::ExecutePlugin(), PluginsConfigurationDlg::FillList(), CCManager::GetProviderFor(), ScriptBindings::InstallPlugin(), ProjectManager::LoadProject(), ProjectManager::LoadWorkspace(), EditorManager::New(), NewFromTemplateDlg::NewFromTemplateDlg(), cbEditor::NotifyPlugins(), ProjectOptionsDlg::OnAddBuildTargetClick(), ProjectOptionsDlg::OnBuildOrderClick(), ProjectOptionsDlg::OnBuildTargetChanged(), ProjectOptionsDlg::OnCopyBuildTargetClick(), ProjectOptionsDlg::OnEditBuildTargetClick(), PluginsConfigurationDlg::OnExport(), MainFrame::OnFileNewWhat(), DebuggerGDB::OnGDBTerminated(), MainFrame::OnHelpPluginMenu(), PluginsConfigurationDlg::OnInstall(), ProjectManagerUI::OnOpenWith(), EditorManager::OnPageChanged(), EditorManager::OnPageChanging(), EditorManager::OnPageClose(), EditorManager::OnPageContextMenu(), MainFrame::OnPluginLoaded(), MainFrame::OnPluginsExecuteMenu(), ProjectOptionsDlg::OnRemoveBuildTargetClick(), ProjectManagerUI::OnRightClick(), PluginsConfigurationDlg::OnToggle(), MainFrame::OnToggleBar(), MainFrame::OpenGeneric(), BuildLogger::OpenLink(), PluginRegistrant< T >::PluginRegistrant(), MainFrame::PluginsUpdated(), ProjectOptionsDlg::ProjectOptionsDlg(), ProjectManager::RemoveFileFromProject(), MainFrame::ScanForPlugins(), EditorManager::SetActiveEditor(), MainFrame::SetChecksForViewToolbarsMenu(), ProjectManager::SetProject(), ProjectManagerUI::ShowMenu(), ProjectManager::WorkspaceChanged(), and EditorBase::~EditorBase().
GetProjectManager()
ProjectManager * Manager::GetProjectManager () const
Functions returning pointers to the respective sub-manager instances.
During application startup as well as during runtime, these functions will always return a valid pointer. During application shutdown, these functions will continue to return a valid pointer until the requested manager shuts down. From that point, the below functions will return null. If there is any chance that your code might execute during application shutdown, you MUST check for a null pointer. The one notable exception to this rule is ConfigManager, which has the same lifetime as Manager itself.
The order of destruction is:
ToolsManager, TemplateManager, PluginManager, ScriptingManager, ProjectManager, EditorManager, PersonalityManager, MacrosManager, UserVariableManager, LogManager The ConfigManager is destroyed immediately before the application terminates, so it can be considered being omnipresent.
For plugin developers, this means that most managers (except for the ones you probably don't use anyway) will be available throughout the entire lifetime of your plugins.
Definition at line 429 of file manager.cpp.
References Mgr< ProjectManager >::Get().
Referenced by DebuggerState::AddBreakpoint(), CompilerGCC::AskForActiveProject(), ProjectManagerUI::AskForBuildTargetIndex(), ProjectManagerUI::AskForMultiBuildTargetIndex(), CodeBlocksApp::BatchJob(), CompilerGCC::BuildModuleMenu(), CompilerGCC::CalculateProjectDependencies(), CompilerGCC::CalculateWorkspaceDependencies(), EditorManager::CheckForExternallyModifiedFiles(), ProjectManagerUI::CheckForExternallyModifiedProjects(), MacrosManager::ClearProjectKeys(), EditorManager::CollectDefines(), Wiz::CopyFiles(), NativeParser::CreateClassBrowser(), MainFrame::CreateIDE(), cbProject::CreateUniqueFilename(), DebuggerGDB::Debug(), MainFrame::DoCloseCurrentWorkspace(), DebuggerGDB::DoDebug(), CompilerErrors::DoGotoError(), cbEditor::DoInitializations(), MainFrame::DoOpenProject(), CodeCompletion::DoParseOpenedProjectAndActiveEditor(), CompilerGCC::DoRecreateTargetMenu(), CompilerGCC::DoSwitchProjectTemporarily(), MainFrame::DoUpdateAppTitle(), CompilerGCC::DoWorkspaceBuild(), ProjectFileOptionsDlg::EndModal(), FilePathPanel::FilePathPanel(), ProjectDepsDlg::FillList(), FindReplace::FindInFiles(), FindReplaceDlg::FindReplaceDlg(), DebuggerManager::FindTargetsDebugger(), ProjectManagerUI::FinishLoadingProject(), NativeParser::GetCurrentProject(), MainFrame::GetEditorDescription(), ScriptBindings::getPM(), GetpMan(), NativeParser::GetProjectByFilename(), FindReplaceDlg::GetTarget(), CompilerGCC::InitBuildLog(), ProjectManager::IsBusy(), CompilerGCC::IsValidTarget(), CompilerGCC::KillProcess(), cbDebuggerPlugin::MarkAsStopped(), ProjectManagerUI::MoveProjectDown(), ProjectManagerUI::MoveProjectUp(), TemplateManager::NewProjectFromUserTemplate(), CompilerGCC::NotifyJobDone(), ProjectManagerUI::OnAddFilesToProjectRecursively(), ProjectManagerUI::OnAddFileToProject(), EditorManager::OnAddFileToProject(), FilePathPanel::OnbtnBrowseClick(), ProjectManagerUI::OnCloseProject(), ProjectManagerUI::OnCloseWorkspace(), cbDebuggerPlugin::OnCompilerFinished(), cbEditor::OnContextMenuEntry(), ProjectOptionsDlg::OnCreateImportFileClick(), ProjectManagerUI::OnExecParameters(), MainFrame::OnFileCloseProject(), MainFrame::OnFileMenuUpdateUI(), MainFrame::OnFileNewWhat(), MainFrame::OnFileOpenDefWorkspace(), MainFrame::OnFileSaveAll(), MainFrame::OnFileSaveProject(), MainFrame::OnFileSaveProjectAs(), MainFrame::OnFileSaveWorkspace(), MainFrame::OnFileSaveWorkspaceAs(), ProjectManagerUI::OnFindFile(), ProjectManagerUI::OnGotoFile(), CodeBlocksApp::OnInit(), ProjectManagerUI::OnKeyDown(), ProjectManagerUI::OnNotes(), WizProjectPathPanel::OnPageChanged(), WizProjectPathPanel::OnPageChanging(), WizBuildTargetPanel::OnPageChanging(), NativeParser::OnParsingOneByOneTimer(), CompilerGCC::OnProjectActivated(), cbDebuggerPlugin::OnProjectActivated(), CompilerGCC::OnProjectCompilerOptions(), ProjectOptionsDlg::OnProjectDepsClick(), ProjectManagerUI::OnProjectFileActivated(), CodeCompletion::OnProjectSavedTimer(), ProjectManagerUI::OnProperties(), ProjectManagerUI::OnRemoveFileFromProject(), EditorManager::OnRemoveFileFromProject(), ProjectManagerUI::OnRenameWorkspace(), ProjectManagerUI::OnRightClick(), DebuggerMenuHandler::OnRunToCursor(), DisassemblyDlg::OnSave(), ProjectManagerUI::OnSaveAsWorkspace(), ProjectManagerUI::OnSaveProject(), ProjectManagerUI::OnSaveWorkspace(), FindReplaceDlg::OnSearchProject(), CodeCompletion::OnSelectedFileReparse(), FindReplaceDlg::OnSelectTarget(), CompilerGCC::OnSelectTarget(), ProjectManagerUI::OnSetActiveProject(), EditorManager::OnShowFileInTree(), DebuggerMenuHandler::OnStart(), DebuggerMenuHandler::OnStep(), ProjectManagerUI::OnTreeItemRightClick(), DebuggerMenuHandler::OnUpdateUI(), DebuggerToolbarHandler::OnUpdateUI(), ProjectManagerUI::OnUpdateUI(), CompilerGCC::OnUpdateUI(), ProjectManagerUI::OnViewFileMasks(), CodeCompletion::OnWorkspaceChanged(), WorkspaceLoader::Open(), ProjectLayoutLoader::Open(), EditorManager::Open(), MainFrame::OpenGeneric(), CompilerGCC::PrepareCompileFile(), CompilerGCC::PreprocessJob(), ProjectDepsDlg::ProjectDepsDlg(), ProjectManagerUI::QueryCloseAllProjects(), ProjectManagerUI::QueryCloseWorkspace(), ProjectManagerUI::RebuildTree(), NativeParser::RemoveClassBrowser(), ProjectManagerUI::RemoveFilesRecursively(), NativeParser::ReparseSelectedProject(), UserVariableManager::Replace(), FindReplace::ReplaceInFiles(), MacrosManager::ReplaceMacros(), CompilerGCC::ResetBuildState(), CompilerGCC::Run(), Wiz::RunProjectWizard(), Wiz::RunTargetWizard(), WorkspaceLoader::Save(), WorkspaceLoader::SaveLayout(), ProjectDepsDlg::SaveList(), FilePathPanel::SetAddToProject(), ProjectFile::SetFileState(), EditorBase::SetTitle(), MainFrame::ShowHideStartPage(), ProjectManagerUI::ShowMenu(), EditorManager::SwapActiveHeaderSource(), cbDebuggerPlugin::SyncEditor(), cbDebuggerPlugin::ToolMenuEnabled(), and cbAuiNotebook::UniqueIdFromTooltip().
GetScriptingManager()
ScriptingManager * Manager::GetScriptingManager () const
Definition at line 469 of file manager.cpp.
References Mgr< ScriptingManager >::Get().
Referenced by CompilerCommandGenerator::DoBuildScripts(), CompilerGCC::DoRunQueue(), ScriptingSettingsDlg::FillTrusts(), WizPageBase::GetNext(), WizPageBase::GetPrev(), ScriptBindings::getSM(), ProjectOptionsDlg::IsScriptValid(), Wiz::Launch(), CompilerGCC::OnAttach(), Wiz::OnAttach(), ScriptConsole::OnbtnLoadClick(), ScriptBindings::XrcDialog::OnButton(), WizPage::OnButton(), ScriptingSettingsDlg::OnDeleteTrust(), CodeBlocksApp::OnInit(), WizPageBase::OnPageChanged(), WizPageBase::OnPageChanging(), CodeBlocksApp::OnRun(), ScriptBindings::ScriptPluginWrapper::RegisterPlugin(), MacrosManager::ReplaceMacros(), Wiz::RunCustomWizard(), Wiz::RunFilesWizard(), Wiz::RunProjectWizard(), CompilerGCC::RunSingleFile(), MainFrame::RunStartupScripts(), Wiz::RunTargetWizard(), ScriptConsolePrintFunc(), and ScriptBindings::IOLib::SecurityAllows().
GetSearchResultLogger()
cbSearchResultsLog* Manager::GetSearchResultLogger () const inline
Returns pointer to the search result logger, might be nullptr or hidden.
Definition at line 161 of file manager.h.
Referenced by CodeRefactoring::DoFindReferences().
GetToolsManager()
ToolsManager * Manager::GetToolsManager () const
Definition at line 449 of file manager.cpp.
References Mgr< ToolsManager >::Get().
Referenced by MainFrame::CreateMenubar(), ConfigureToolsDlg::DoFillList(), ConfigureToolsDlg::OnAdd(), ConfigureToolsDlg::OnAddSeparator(), ConfigureToolsDlg::OnDown(), ConfigureToolsDlg::OnEdit(), ConfigureToolsDlg::OnRemove(), ConfigureToolsDlg::OnUp(), and ConfigureToolsDlg::OnUpdateUI().
GetUserVariableManager()
UserVariableManager * Manager::GetUserVariableManager () const
Definition at line 464 of file manager.cpp.
References Mgr< UserVariableManager >::Get().
Referenced by ProjectManager::EndLoadingProject(), ProjectManager::EndLoadingWorkspace(), ScriptBindings::getUVM(), GetUserVariableDialog::OnConfig(), MainFrame::OnGlobalUserVars(), EditPathDlg::OnOther(), and MacrosManager::Reset().
InitXRC()
void Manager::InitXRC (bool force = false) static
XML Resource functions /////// Inits XML Resource system.
Definition at line 343 of file manager.cpp.
References wxFileSystem::AddHandler(), wxXmlResource::Get(), wxXmlResource::InitAllHandlers(), and wxXmlResource::InsertHandler().
IsAppShuttingDown()
bool Manager::IsAppShuttingDown () static
Definition at line 333 of file manager.cpp.
References m_AppShuttingDown.
Referenced by NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), cbSyncExecute(), LibLoader::Cleanup(), ProjectManager::CloseAllProjects(), ProjectManagerUI::CloseWorkspace(), CCLogger::DebugLog(), PluginManager::DetachPlugin(), MainFrame::DoUpdateStatusBar(), ClassBrowserBuilderThread::Entry(), NativeParser::GetGCCCompilerDirs(), ProjectManagerUI::InitPane(), ProjectManager::IsBusy(), CCLogger::Log(), MainFrame::OnAddLogWindow(), Parser::OnAllThreadsDone(), CodeBlocksApp::OnAppActivate(), Parser::OnBatchTimer(), CodeCompletion::OnCCDebugLogger(), CodeCompletion::OnCCLogger(), MainFrame::OnEditMenuUpdateUI(), CodeCompletion::OnEditorOpen(), MainFrame::OnEditorUpdateUI(), MainFrame::OnFileMenuUpdateUI(), DebuggerGDB::OnGDBTerminated(), MainFrame::OnPluginUninstalled(), MainFrame::OnPluginUnloaded(), MainFrame::OnRemoveLogWindow(), MainFrame::OnRequestDockWindow(), MainFrame::OnSearchMenuUpdateUI(), MainFrame::OnViewMenuUpdateUI(), WorkspaceLoader::Open(), ProcessEvent(), ProjectManagerUI::RebuildTree(), CCTreeCtrl::RemoveDoubles(), EditorManager::RemoveEditorBase(), LibLoader::RemoveLibrary(), ClassBrowserBuilderThread::SelectItemRequired(), RecentItemsList::TerminateHistory(), ClassBrowser::ThreadedBuildTree(), DebuggerManager::UnregisterDebugger(), NativeParser::UpdateClassBrowser(), and ClassBrowser::UpdateClassBrowserView().
IsAppStartedUp()
bool Manager::IsAppStartedUp () static
Definition at line 338 of file manager.cpp.
References m_AppStartedUp.
IsBatchBuild()
static bool Manager::IsBatchBuild () inline static
Definition at line 66 of file manager.h.
Referenced by ProjectManager::CloseWorkspace(), MainFrame::CreateIDE(), MainFrame::CreateMenubar(), FindReplace::CreateSearchLog(), CompilerGCC::DoRunQueue(), CompilerCommandGenerator::Init(), EditorColourSet::Load(), EditorColourSet::LoadAvailableSets(), WorkspaceLoader::LoadLayout(), MainFrame::OnApplicationClose(), CompilerGCC::OnAttach(), CompilerGCC::OnJobEnd(), CompilerGCC::OnRelease(), ProjectLayoutLoader::Open(), ProjectLoader::Open(), cbProject::Open(), ProjectManagerUI::QueryCloseProject(), EditorColourSet::Reset(), EditorColourSet::Save(), PluginManager::ScanForPlugins(), MainFrame::SetupDebuggerUI(), MainFrame::SetupGUILogging(), MainFrame::ShowHideScriptConsole(), and MainFrame::ShowHideStartPage().
isToolBar16x16()
bool Manager::isToolBar16x16 (wxToolBar * toolBar) static
Definition at line 412 of file manager.cpp.
References wxSize::GetHeight(), wxToolBar::GetToolBitmapSize(), and wxSize::GetWidth().
Referenced by CompilerGCC::BuildToolBar(), and DebuggerToolbarHandler::GetToolbar().
LoadMenu()
wxMenu * Manager::LoadMenu (wxString menu_id, bool createonfailure = false) static
Loads Menu from XRC.
Definition at line 368 of file manager.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadMenu().
Referenced by CompilerGCC::BuildMenu(), and DebuggerManager::GetMenu().
LoadMenuBar()
wxMenuBar * Manager::LoadMenuBar (wxString resid, bool createonfailure = false) static
Loads Menubar from XRC.
Definition at line 361 of file manager.cpp.
References wxXmlResource::Get(), and wxXmlResource::LoadMenuBar().
LoadResource()
bool Manager::LoadResource (const wxString & file) static
Definition at line 499 of file manager.cpp.
References _(), _T, wxFile::Access(), wxMemoryFSHandler::AddFile(), wxXmlResource::Get(), Get(), GetLogManager(), wxFile::Length(), ConfigManager::LocateDataFile(), LogManager::LogError(), wxFile::Read(), wxFile::read, sdDataGlobal, and sdDataUser.
Referenced by CodeCompletion::CodeCompletion(), CompilerGCC::CompilerGCC(), DebuggerGDB::DebuggerGDB(), Get(), CodeBlocksApp::InitXRCStuff(), and LoadXRC().
LoadToolBar()
wxToolBar * Manager::LoadToolBar (wxFrame * parent, wxString resid, bool defaultsmall = true) static
Loads ToolBar from XRC.
Definition at line 375 of file manager.cpp.
References wxXmlResource::Get(), wxXmlResource::LoadToolBar(), wxToolBar::SetToolBitmapSize(), platform::WindowsVersion(), platform::winver_WindowsXP, wxID_ANY, wxTB_FLAT, and wxTB_HORIZONTAL.
LoadXRC()
void Manager::LoadXRC (wxString relpath) static
Loads XRC file(s) using data_path.
Definition at line 356 of file manager.cpp.
References LoadResource().
OnMenu()
void Manager::OnMenu (wxCommandEvent & event) private
ProcessEvent() [1/4]
bool Manager::ProcessEvent (CodeBlocksEvent & event)
Definition at line 246 of file manager.cpp.
References _(), LogManager::DebugLog(), F(), wxString::FromUTF8(), Get(), GetLogManager(), IsAppShuttingDown(), m_EventSinks, wxStopWatch::Time(), and wxString::wx_str().
Referenced by cbPlugin::Attach(), cbProject::BeginAddFiles(), cbProject::BeginRemoveFiles(), CCManager::CallSmartIndentCCDone(), ProjectManagerUI::CheckForExternallyModifiedProjects(), CompilerGCC::ClearLog(), ToolsManager::Configure(), DebugInterfaceFactory::CreateBacktrace(), DebugInterfaceFactory::CreateBreapoints(), NativeParser::CreateClassBrowser(), DebugInterfaceFactory::CreateCPURegisters(), DebugInterfaceFactory::CreateDisassembly(), DebugInterfaceFactory::CreateMemory(), MainFrame::CreateMenubar(), FindReplace::CreateSearchLog(), DebugInterfaceFactory::CreateThreads(), DebugInterfaceFactory::CreateWatches(), DebuggerMenuHandler::DebuggerMenuHandler(), CodeRefactoring::DoFindReferences(), CompilerGCC::DoGotoNextError(), CompilerGCC::DoGotoPreviousError(), CompilerGCC::DoPrepareQueue(), cbProject::EndAddFiles(), ProjectManager::EndLoadingProject(), cbProject::EndRemoveFiles(), ToolsManager::Execute(), FindReplace::FindInFiles(), DebuggerManager::GetLogger(), GetResourcesDir(), DebuggerManager::HideLogger(), CompilerCommandGenerator::Init(), PluginManager::InstallPlugin(), CompilerFactory::LoadSettings(), MainFrame::LoadViewLayout(), TemplateManager::NewProjectFromUserTemplate(), CompilerGCC::NotifyCleanProject(), CompilerGCC::NotifyCleanWorkspace(), CompilerGCC::NotifyJobDone(), PluginManager::NotifyPlugins(), cbProject::NotifyPlugins(), DebuggerMenuHandler::OnAddWatch(), CodeBlocksApp::OnAppActivate(), MainFrame::OnApplicationClose(), CompilerGCC::OnAttach(), CCManager::OnDeferredCallTipShow(), MainFrame::OnEditCompleteCode(), CCManager::OnEditorHook(), MainFrame::OnEditShowCallTip(), CodeBlocksApp::OnInit(), CompilerGCC::OnJobEnd(), WatchesDlg::OnMenuExamineMemory(), CCManager::OnMenuSelect(), CompilerGCC::OnRelease(), MainFrame::OnRequestHideDockWindow(), MainFrame::OnRequestShowDockWindow(), MainFrame::OnSettingsCompiler(), MainFrame::OnSettingsDebugger(), MainFrame::OnSettingsEditor(), MainFrame::OnSettingsEnvironment(), MainFrame::OnSettingsPlugins(), CCManager::OnTimer(), CodeCompletion::OnViewClassBrowser(), CompilerGCC::PrintBanner(), DebuggerMenuHandler::RegisterDefaultWindowItems(), cbPlugin::Release(), NativeParser::RemoveClassBrowser(), RemoveDockWindow(), CodeCompletion::RereadOptions(), CompilerFactory::SaveSettings(), DebuggerManager::ShowBacktraceDialog(), MainFrame::ShowHideScriptConsole(), cbDebuggerPlugin::ShowLog(), CompilerGCC::StartCompileFile(), cbDebuggerPlugin::SwitchToDebuggingLayout(), cbDebuggerPlugin::SwitchToPreviousLayout(), ProjectManagerUI::SwitchToProjectsPage(), and PluginManager::UninstallPlugin().
ProcessEvent() [2/4]
bool Manager::ProcessEvent (CodeBlocksDockEvent & event)
Definition at line 291 of file manager.cpp.
References IsAppShuttingDown(), and m_DockEventSinks.
ProcessEvent() [3/4]
bool Manager::ProcessEvent (CodeBlocksLayoutEvent & event)
Definition at line 305 of file manager.cpp.
References IsAppShuttingDown(), and m_LayoutEventSinks.
ProcessEvent() [4/4]
bool Manager::ProcessEvent (CodeBlocksLogEvent & event)
Definition at line 319 of file manager.cpp.
References IsAppShuttingDown(), and m_LogEventSinks.
ProcessPendingEvents()
void Manager::ProcessPendingEvents () static
Definition at line 215 of file manager.cpp.
References m_AppShuttingDown, m_BlockYields, wxApp::ProcessPendingEvents(), and wxTheApp.
Referenced by MainFrame::CreateToolbars(), ScriptConsole::Log(), and CodeBlocksApp::OnInit().
RegisterEventSink() [1/4]
void Manager::RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksEvent > * functor)
Definition at line 550 of file manager.cpp.
References m_EventSinks.
Referenced by CCManager::CCManager(), DebuggerManager::DebuggerManager(), DebuggerOptionsProjectDlg::DebuggerOptionsProjectDlg(), DebugInterfaceFactory::DebugInterfaceFactory(), EditorManager::EditorManager(), CodeCompletion::OnAttach(), CompilerGCC::OnAttach(), cbDebuggerPlugin::OnAttach(), cbSmartIndentPlugin::OnAttach(), DebuggerGDB::OnAttachReal(), CodeBlocksApp::OnInit(), ProjectManager::ProjectManager(), MainFrame::RegisterEvents(), and cbDebuggerPlugin::RegisterValueTooltip().
RegisterEventSink() [2/4]
void Manager::RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksDockEvent > * functor)
Definition at line 555 of file manager.cpp.
References m_DockEventSinks.
RegisterEventSink() [3/4]
void Manager::RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksLayoutEvent > * functor)
Definition at line 560 of file manager.cpp.
References m_LayoutEventSinks.
RegisterEventSink() [4/4]
void Manager::RegisterEventSink (wxEventType eventType, IEventFunctorBase< CodeBlocksLogEvent > * functor)
Definition at line 565 of file manager.cpp.
References m_LogEventSinks.
RemoveAllEventSinksFor()
void Manager::RemoveAllEventSinksFor (void * owner)
Definition at line 570 of file manager.cpp.
References m_AppShuttingDown, m_AppStartedUp, m_BlockYields, m_CmdLineParser, m_DockEventSinks, m_EventSinks, m_IsBatch, m_LayoutEventSinks, and m_LogEventSinks.
Referenced by PluginManager::DetachPlugin(), CodeCompletion::OnRelease(), cbDebuggerPlugin::OnRelease(), CCManager::~CCManager(), DebuggerManager::~DebuggerManager(), DebuggerOptionsProjectDlg::~DebuggerOptionsProjectDlg(), and DebugInterfaceFactory::~DebugInterfaceFactory().
SetAppShuttingDown()
void Manager::SetAppShuttingDown (bool app_shutting_down) static
Definition at line 200 of file manager.cpp.
References m_AppShuttingDown.
Referenced by MainFrame::OnApplicationClose().
SetAppStartedUp()
void Manager::SetAppStartedUp (bool app_started_up) static
Definition at line 195 of file manager.cpp.
References m_AppStartedUp.
Referenced by CodeBlocksApp::OnInit().
SetBatchBuild()
void Manager::SetBatchBuild (bool is_batch) static
Definition at line 205 of file manager.cpp.
References m_IsBatch.
Referenced by CodeBlocksApp::OnInit().
SetSearchResultLogger()
void Manager::SetSearchResultLogger (cbSearchResultsLog * log) inline
Sets the pointer to the search result logger, users must not call this method.
Definition at line 163 of file manager.h.
Referenced by FindReplace::CreateSearchLog().
Shutdown()
void Manager::Shutdown () static
Definition at line 227 of file manager.cpp.
References Mgr< ToolsManager >::Free(), Mgr< CfgMgrBldr >::Free(), Mgr< LogManager >::Free(), Mgr< UserVariableManager >::Free(), Mgr< MacrosManager >::Free(), Mgr< PersonalityManager >::Free(), Mgr< EditorManager >::Free(), Mgr< CCManager >::Free(), Mgr< ScriptingManager >::Free(), Mgr< DebuggerManager >::Free(), Mgr< PluginManager >::Free(), Mgr< ProjectManager >::Free(), Mgr< TemplateManager >::Free(), and m_AppShuttingDown.
Referenced by MainFrame::OnApplicationClose().
Yield()
void Manager::Yield () static
Whenever you need to call wxYield(), call Manager::Yield(). It's safer.
Definition at line 221 of file manager.cpp.
References m_AppShuttingDown, m_BlockYields, wxTheApp, and wxApp::Yield().
Referenced by CompilerGCC::BuildStateManagement(), cbStopRunningCompilers(), cbSyncExecute(), DebuggerGDB::DoDebug(), CompilerGCC::DoPrepareQueue(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), DirectCommands::GetTargetCompileCommands(), CompilerGCC::NotifyCleanProject(), CompilerGCC::NotifyCleanWorkspace(), MainFrame::OnApplicationClose(), cbDebuggerPlugin::RunNixConsole(), and cbEditor::Split().
Member Data Documentation
m_AppShuttingDown
bool Manager::m_AppShuttingDown = false static private
Definition at line 51 of file manager.h.
Referenced by IsAppShuttingDown(), ProcessPendingEvents(), RemoveAllEventSinksFor(), SetAppShuttingDown(), Shutdown(), and Yield().
m_AppStartedUp
bool Manager::m_AppStartedUp = false static private
Definition at line 52 of file manager.h.
Referenced by IsAppStartedUp(), RemoveAllEventSinksFor(), and SetAppStartedUp().
m_BlockYields
bool Manager::m_BlockYields = false static private
Definition at line 53 of file manager.h.
Referenced by BlockYields(), ProcessPendingEvents(), RemoveAllEventSinksFor(), and Yield().
m_CmdLineParser
wxCmdLineParser Manager::m_CmdLineParser static private
Definition at line 55 of file manager.h.
Referenced by GetCmdLineParser(), and RemoveAllEventSinksFor().
m_DockEventSinks
DockEventSinksMap Manager::m_DockEventSinks private
Definition at line 177 of file manager.h.
Referenced by ProcessEvent(), RegisterEventSink(), RemoveAllEventSinksFor(), and ~Manager().
m_EventSinks
EventSinksMap Manager::m_EventSinks private
Definition at line 176 of file manager.h.
Referenced by ProcessEvent(), RegisterEventSink(), RemoveAllEventSinksFor(), and ~Manager().
m_IsBatch
bool Manager::m_IsBatch = false static private
Definition at line 54 of file manager.h.
Referenced by RemoveAllEventSinksFor(), and SetBatchBuild().
m_LayoutEventSinks
LayoutEventSinksMap Manager::m_LayoutEventSinks private
Definition at line 178 of file manager.h.
Referenced by ProcessEvent(), RegisterEventSink(), RemoveAllEventSinksFor(), and ~Manager().
m_LogEventSinks
LogEventSinksMap Manager::m_LogEventSinks private
Definition at line 179 of file manager.h.
Referenced by ProcessEvent(), RegisterEventSink(), RemoveAllEventSinksFor(), and ~Manager().
m_pAppWindow
wxFrame* Manager::m_pAppWindow private
Definition at line 50 of file manager.h.
Referenced by Get(), GetAppFrame(), and GetAppWindow().
m_SearchResultLog
cbSearchResultsLog* Manager::m_SearchResultLog private
Definition at line 180 of file manager.h.
The documentation for this class was generated from the following files:
manager.h
manager.cpp