Code::Blocks: CompilerGCC Class Reference
CompilerGCC Class Reference
#include <compilergcc.h>
Classes
struct BuildJobTarget
struct CompilerProcess
Public Member Functions
CompilerGCC ()
virtual ~CompilerGCC ()
virtual void OnAttach ()
Any descendent plugin should override this virtual method and perform any necessary initialization.
virtual void OnRelease (bool appShutDown)
virtual void BuildMenu (wxMenuBar *menuBar)
virtual void BuildModuleMenu (const ModuleType type, wxMenu *menu, const FileTreeData *data=0)
virtual bool BuildToolBar (wxToolBar *toolBar)
virtual int GetToolBarPriority ()
This method return the priority of the plugin's toolbar, the less value indicates a more preceding position when C::B starts with no configuration file.
virtual int Run (ProjectBuildTarget *target=0L)
Run the project/target.
virtual int Run (const wxString &target)
Same as Run(ProjectBuildTarget*) but with a wxString argument.
virtual int RunSingleFile (const wxString &filename)
virtual int Clean (const wxString &target)
Same as Clean(ProjectBuildTarget*) but with a wxString argument.
virtual int Clean (ProjectBuildTarget *target=0L)
Clean the project/target.
virtual int DistClean (ProjectBuildTarget *target=0L)
DistClean the project/target.
virtual int DistClean (const wxString &target)
Same as DistClean(ProjectBuildTarget*) but with a wxString argument.
virtual int Build (ProjectBuildTarget *target=0L)
Build the project/target.
virtual int Build (const wxString &target)
Same as Build(ProjectBuildTarget*) but with a wxString argument.
virtual int Rebuild (ProjectBuildTarget *target=0L)
Rebuild the project/target.
virtual int Rebuild (const wxString &target)
Same as Rebuild(ProjectBuildTarget*) but with a wxString argument.
virtual int CleanWorkspace (const wxString &target=wxEmptyString)
Clean all open projects.
virtual int BuildWorkspace (const wxString &target=wxEmptyString)
Build all open projects.
virtual int RebuildWorkspace (const wxString &target=wxEmptyString)
Rebuild all open projects.
virtual int CompileFile (const wxString &file)
Compile a specific file.
virtual int CompileFileWithoutProject (const wxString &file)
virtual int CompileFileDefault (cbProject *project, ProjectFile *pf, ProjectBuildTarget *bt)
virtual int KillProcess ()
Abort the current build process.
virtual bool IsRunning () const
Is the plugin currently compiling?
virtual int GetExitCode () const
Get the exit code of the last build process.
virtual int Configure (cbProject *project, ProjectBuildTarget *target=0L)
Display configuration dialog.
int GetConfigurationPriority () const
Return the plugin's configuration priority.
int GetConfigurationGroup () const
Return the configuration group for this plugin.
cbConfigurationPanel * GetConfigurationPanel (wxWindow *parent)
bool IsValidTarget (const wxString &target) const
void SwitchCompiler (const wxString &id)
const wxString & GetCurrentCompilerID ()
void OnIdle (wxIdleEvent &event)
void OnTimer (wxTimerEvent &event)
void OnCompile (wxCommandEvent &event)
void OnCompileFile (wxCommandEvent &event)
void OnCleanFile (wxCommandEvent &event)
void OnRebuild (wxCommandEvent &event)
void OnCompileAll (wxCommandEvent &event)
void OnRebuildAll (wxCommandEvent &event)
void OnCleanAll (wxCommandEvent &event)
void OnClean (wxCommandEvent &event)
void OnRun (wxCommandEvent &event)
void OnProjectCompilerOptions (wxCommandEvent &event)
void OnTargetCompilerOptions (wxCommandEvent &event)
void OnCompileAndRun (wxCommandEvent &event)
void OnKillProcess (wxCommandEvent &event)
void OnSelectTarget (wxCommandEvent &event)
void OnNextError (wxCommandEvent &event)
void OnPreviousError (wxCommandEvent &event)
void OnClearErrors (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void OnConfig (wxCommandEvent &event)
Public Member Functions inherited from cbCompilerPlugin
cbCompilerPlugin ()
Public Member Functions inherited from cbPlugin
cbPlugin ()
In default cbPlugin's constructor the associated PluginInfo structure is filled with default values.
virtual ~cbPlugin ()
cbPlugin destructor.
virtual PluginType GetType () const
The plugin must return its type on request.
virtual cbConfigurationPanel * GetConfigurationPanel (cb_optional wxWindow *parent)
Return plugin's configuration panel.
virtual cbConfigurationPanel * GetProjectConfigurationPanel (cb_optional wxWindow *parent, cb_optional cbProject *project)
Return plugin's configuration panel for projects.
virtual void BuildMenu (cb_optional wxMenuBar *menuBar)
This method is called by Code::Blocks and is used by the plugin to add any menu items it needs on Code::Blocks's menu bar.
virtual void BuildModuleMenu (cb_optional const ModuleType type, cb_optional wxMenu *menu, cb_optional const FileTreeData *data=nullptr)
This method is called by Code::Blocks core modules (EditorManager, ProjectManager etc) and is used by the plugin to add any menu items it needs in the module's popup menu.
virtual bool BuildToolBar (cb_optional wxToolBar *toolBar)
This method is called by Code::Blocks and is used by the plugin to add any toolbar items it needs on Code::Blocks's toolbar.
bool IsAttached () const
See whether this plugin is attached or not.
virtual bool CanDetach () const
See whether this plugin can be detached (unloaded) or not.
Private Types
typedef std::queue< BuildJobTarget > BuildJobTargetsList
typedef std::vector< CompilerProcess > CompilerProcessList
Private Member Functions
void Dispatcher (wxCommandEvent &event)
void TextURL (wxTextUrlEvent &event)
bool StopRunningDebugger ()
bool ReAllocProcesses ()
void AllocProcesses ()
void FreeProcesses ()
bool IsProcessRunning (int idx=-1) const
int GetNextAvailableProcessIndex () const
int GetActiveProcessCount () const
void SetupEnvironment ()
void OnProjectActivated (CodeBlocksEvent &event)
void OnProjectLoaded (CodeBlocksEvent &event)
void OnProjectUnloaded (CodeBlocksEvent &event)
void OnCompileFileRequest (CodeBlocksEvent &event)
void OnGCCOutput (CodeBlocksEvent &event)
void OnGCCError (CodeBlocksEvent &event)
void OnGCCTerminated (CodeBlocksEvent &event)
void OnJobEnd (size_t procIndex, int exitCode)
void SaveOptions ()
void LoadOptions ()
void DoRegisterCompilers ()
void DoPrepareQueue (bool clearLog)
void NotifyCleanProject (const wxString &target)
void NotifyCleanWorkspace ()
int DoRunQueue ()
void DoClearTargetMenu ()
void DoRecreateTargetMenu ()
void DoUpdateTargetMenu (int targetIndex)
FileTreeData * DoSwitchProjectTemporarily ()
ProjectBuildTarget * DoAskForTarget ()
int DoGUIAskForTarget ()
void ClearLog ()
void PrepareCompileFile (wxFileName &file)
void PrepareCompileFilePM (wxFileName &file)
bool CheckProject ()
void AskForActiveProject ()
void StartCompileFile (wxFileName file)
void DoGotoNextError ()
void DoGotoPreviousError ()
void DoClearErrors ()
wxString ProjectMakefile ()
void AddOutputLine (const wxString &output, bool forceErrorColour=false)
void LogWarningOrError (CompilerLineType lt, cbProject *prj, const wxString &filename, const wxString &line, const wxString &msg)
void LogMessage (const wxString &message, CompilerLineType lt=cltNormal, LogTarget log=ltAll, bool forceErrorColour=false, bool isTitle=false, bool updateProgress=false)
void SaveBuildLog ()
void InitBuildLog (bool workspaceBuild)
void PrintBanner (BuildAction action, cbProject *prj=0, ProjectBuildTarget *target=0)
bool UseMake (cbProject *project=0)
bool CompilerValid (ProjectBuildTarget *target=0)
ProjectBuildTarget * GetBuildTargetForFile (ProjectFile *pf)
wxString GetMakeCommandFor (MakeCommand cmd, cbProject *project, ProjectBuildTarget *target)
int DoBuild (bool clean, bool build)
int DoBuild (const wxString &target, bool clean, bool build, bool clearLog=true)
int DoWorkspaceBuild (const wxString &target, bool clean, bool build, bool clearLog=true)
void CalculateWorkspaceDependencies (wxArrayInt &deps)
void CalculateProjectDependencies (cbProject *prj, wxArrayInt &deps)
void InitBuildState (BuildJob job, const wxString &target)
void ResetBuildState ()
void BuildStateManagement ()
This uses m_BuildJob.
BuildState GetNextStateBasedOnJob ()
void NotifyJobDone (bool showNothingToBeDone=false)
void AddToCommandQueue (const wxArrayString &commands)
int GetTargetIndexFromName (cbProject *prj, const wxString &name)
void UpdateProjectTargets (cbProject *project)
wxString GetTargetString (int index=-1)
void DoClean (const wxArrayString &commands)
bool DoCleanWithMake (ProjectBuildTarget *bt)
wxString GetCurrentCompilerID (ProjectBuildTarget *target)
wxString GetErrWarnStr ()
wxString GetMinSecStr ()
void ExpandTargets (cbProject *project, const wxString &targetName, wxArrayString &result)
void PreprocessJob (cbProject *project, const wxString &targetName)
BuildJobTarget GetNextJob ()
const BuildJobTarget & PeekNextJob ()
Private Attributes
BuildJobTargetsList m_BuildJobTargetsList
CompilerProcessList m_CompilerProcessList
wxArrayString m_Targets
int m_RealTargetsStartIndex
int m_RealTargetIndex
CompilerQueue m_CommandQueue
wxString m_CompilerId
int m_PageIndex
int m_ListPageIndex
wxMenu * m_Menu
wxMenu * m_TargetMenu
int m_TargetIndex
wxMenu * m_pErrorsMenu
cbProject * m_pProject
wxToolBar * m_pTbar
wxTimer m_timerIdleWakeUp
BuildLogger * m_pLog
CompilerMessages * m_pListLog
wxChoice * m_pToolTarget
bool m_RunAfterCompile
wxString m_CdRun
wxString m_RunCmd
int m_LastExitCode
CompilerErrors m_Errors
wxString m_LastTargetName
bool m_NotifiedMaxErrors
wxLongLong m_StartTime
cbProject * m_pBuildingProject
wxString m_BuildingTargetName
BuildJob m_BuildJob
BuildState m_BuildState
BuildState m_NextBuildState
cbProject * m_pLastBuildingProject
ProjectBuildTarget * m_pLastBuildingTarget
bool m_Clean
bool m_Build
bool m_LastBuildStep
bool m_RunTargetPostBuild
bool m_RunProjectPostBuild
bool m_IsWorkspaceOperation
wxString m_BuildLogFilename
wxString m_BuildLogTitle
wxString m_BuildLogContents
wxDateTime m_BuildStartTime
size_t m_MaxProgress
size_t m_CurrentProgress
bool m_LogBuildProgressPercentage
Friends
class CompilerOptionsDlg
Additional Inherited Members
Protected Member Functions inherited from cbPlugin
virtual void OnRelease (cb_optional bool appShutDown)
Any descendent plugin should override this virtual method and perform any necessary de-initialization.
virtual void NotImplemented (const wxString &log) const
This method logs a "Not implemented" message and is provided for convenience only.
Protected Attributes inherited from cbPlugin
PluginType m_Type
Holds the plugin's type.
bool m_IsAttached
Holds the "attached" state.
Class Documentation
struct CompilerGCC::CompilerProcess
Class Members
wxString OutputFile
long int PID
PipedProcess * pProcess
Member Typedef Documentation
typedef std::queue<BuildJobTarget> CompilerGCC::BuildJobTargetsList private
typedef std::vector<CompilerProcess> CompilerGCC::CompilerProcessList private
Constructor & Destructor Documentation
CompilerGCC::CompilerGCC ()
References Manager::LoadResource(), and NotifyMissingFile().
CompilerGCC::~CompilerGCC () virtual
Member Function Documentation
void CompilerGCC::AddOutputLine (const wxString & output, bool forceErrorColour = false) private
References AskForActiveProject(), Compiler::CheckForWarningsAndErrors(), cltError, cltNormal, LogManager::DebugLog(), F(), Manager::Get(), CompileTargetBase::GetBasePath(), CompilerFactory::GetCompiler(), Manager::GetConfigManager(), CompilerErrors::GetCount(), cbProject::GetExecutionDir(), Compiler::GetLastError(), Compiler::GetLastErrorFilename(), Compiler::GetLastErrorLine(), Manager::GetLogManager(), ProjectBuildTarget::GetParentProject(), LogMessage(), LogWarningOrError(), ltAll, ltFile, m_CompilerId, m_Errors, m_NotifiedMaxErrors, m_pBuildingProject, m_pLastBuildingTarget, m_pProject, ConfigManager::ReadArrayString(), ConfigManager::ReadInt(), UseMake(), and Compiler::WithMultiLineMsg().
Referenced by OnGCCError(), and OnGCCOutput().
void CompilerGCC::AddToCommandQueue (const wxArrayString & commands) private
References CompilerQueue::Add(), COMPILER_SIMPLE_LOG, COMPILER_TARGET_CHANGE, COMPILER_WAIT, COMPILER_WAIT_LINK, cbProject::GetBuildTarget(), GetTargetIndexFromName(), CompilerCommand::isLink, m_BuildingTargetName, m_CommandQueue, m_CurrentProgress, m_MaxProgress, m_pBuildingProject, m_pLog, CompilerCommand::mustWait, and BuildLogger::progress.
Referenced by BuildStateManagement(), CompileFileDefault(), and CompileFileWithoutProject().
void CompilerGCC::AllocProcesses () private
References Manager::Get(), Manager::GetConfigManager(), m_CompilerProcessList, and ConfigManager::ReadInt().
Referenced by OnAttach(), and ReAllocProcesses().
void CompilerGCC::AskForActiveProject () private
References Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetProjectManager(), m_pBuildingProject, and m_pProject.
Referenced by AddOutputLine(), CheckProject(), DoSwitchProjectTemporarily(), and ProjectMakefile().
int CompilerGCC::Build (ProjectBuildTarget * target = 0L) virtual
Build the project/target.
Parameters
target The specific build target to build. If NULL, it builds all the targets of the current project.
Implements cbCompilerPlugin.
References CompileTargetBase::GetTitle().
Referenced by OnCompile(), OnCompileAndRun(), Run(), and RunSingleFile().
int CompilerGCC::Build (const wxString & target) virtual
Same as Build(ProjectBuildTarget*) but with a wxString argument.
Implements cbCompilerPlugin.
References DoBuild(), and m_LastBuildStep.
void CompilerGCC::BuildMenu (wxMenuBar * menuBar) virtual
References DoRecreateTargetMenu(), Manager::Get(), cbPlugin::IsAttached(), Manager::LoadMenu(), m_Menu, m_TargetMenu, and NULL.
void CompilerGCC::BuildModuleMenu (const ModuleType type, wxMenu * menu, const FileTreeData * data = 0) virtual
References CheckProject(), FileTypeOf(), FileTreeData::ftdkFile, FileTreeData::ftdkProject, FileTreeData::ftdkUndefined, ftHeader, ftSource, ftTemplateSource, Manager::Get(), ProjectManager::GetIsRunning(), FileTreeData::GetKind(), FileTreeData::GetProjectFile(), Manager::GetProjectManager(), cbPlugin::IsAttached(), IsRunning(), mtProjectManager, and ProjectFile::relativeFilename.
void CompilerGCC::BuildStateManagement () private
This uses m_BuildJob.
References AddToCommandQueue(), baBuild, baClean, bsNone, bsProjectDone, bsProjectPostBuild, bsProjectPreBuild, bsTargetBuild, bsTargetClean, bsTargetDone, bsTargetPostBuild, bsTargetPreBuild, clogFull, clogNone, clogSimple, cltError, cltNormal, COMPILER_ERROR_LOG, COMPILER_SIMPLE_LOG, DoClean(), DoCleanWithMake(), F(), Manager::Get(), CompileOptionsBase::GetAlwaysRunPostBuildSteps(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), getBuildTargetName(), DirectCommands::GetCleanCommands(), DirectCommands::GetCompileCommands(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), cbProject::GetExecutionDir(), Manager::GetMacrosManager(), GetMakeCommandFor(), cbProject::GetMakefile(), GetNextStateBasedOnJob(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), Compiler::GetSwitches(), GetTargetIndexFromName(), CompileTargetBase::GetTitle(), IsProcessRunning(), CompilerSwitches::logging, LogMessage(), m_Build, m_BuildingTargetName, m_BuildState, DirectCommands::m_doYield, m_NextBuildState, m_PageIndex, m_pBuildingProject, m_pLastBuildingProject, m_pLastBuildingTarget, m_RunProjectPostBuild, m_RunTargetPostBuild, mcAskRebuildNeeded, mcBuild, mcSilentBuild, PrintBanner(), MacrosManager::RecalcVars(), ResetBuildState(), cbProject::SetCurrentlyCompilingTarget(), SwitchCompiler(), UseMake(), and Manager::Yield().
Referenced by DoBuild(), DoRunQueue(), and OnJobEnd().
bool CompilerGCC::BuildToolBar (wxToolBar * toolBar) virtual
References Manager::AddonToolBar(), DoRecreateTargetMenu(), Manager::Get(), cbPlugin::IsAttached(), Manager::isToolBar16x16(), m_pTbar, and m_pToolTarget.
int CompilerGCC::BuildWorkspace (const wxString & target = wxEmptyString) virtual
Build all open projects.
Parameters
target If not empty, the target to build in each project. Else all targets.
Implements cbCompilerPlugin.
References DoWorkspaceBuild().
Referenced by OnCompileAll().
void CompilerGCC::CalculateProjectDependencies (cbProject * prj, wxArrayInt & deps) private
References F(), Manager::Get(), ProjectManager::GetDependenciesForProject(), Manager::GetLogManager(), Manager::GetProjectManager(), ProjectManager::GetProjects(), CompileTargetBase::GetTitle(), LogManager::Log(), m_PageIndex, and Logger::warning.
Referenced by CalculateWorkspaceDependencies(), and PreprocessJob().
void CompilerGCC::CalculateWorkspaceDependencies (wxArrayInt & deps) private
References CalculateProjectDependencies(), Manager::Get(), Manager::GetProjectManager(), and ProjectManager::GetProjects().
Referenced by PreprocessJob().
bool CompilerGCC::CheckProject () private
References AskForActiveProject(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetDefaultCompilerID(), m_CompilerId, m_pProject, and SwitchCompiler().
Referenced by BuildModuleMenu(), CompileFile(), DistClean(), DoAskForTarget(), DoBuild(), DoGUIAskForTarget(), DoRecreateTargetMenu(), OnClean(), OnCleanFile(), OnRebuild(), PrepareCompileFile(), PrepareCompileFilePM(), and Run().
int CompilerGCC::Clean (const wxString & target) virtual
Same as Clean(ProjectBuildTarget*) but with a wxString argument.
Implements cbCompilerPlugin.
References DoBuild(), and m_LastBuildStep.
Referenced by Clean(), and OnClean().
int CompilerGCC::Clean (ProjectBuildTarget * target = 0L) virtual
Clean the project/target.
Cleaning a project means deleting any files created by building it. This includes any object files, the binary output file, etc.
Parameters
target The specific build target to "clean". If NULL, it cleans all the build targets of the current project.
Implements cbCompilerPlugin.
References Clean(), and CompileTargetBase::GetTitle().
int CompilerGCC::CleanWorkspace (const wxString & target = wxEmptyString) virtual
Clean all open projects.
Parameters
target If not empty, the target to clean in each project. Else all targets.
Implements cbCompilerPlugin.
References DoWorkspaceBuild().
Referenced by OnCleanAll().
void CompilerGCC::ClearLog () private
References cbEVT_SWITCH_TO_LOG_WINDOW, TextCtrlLogger::Clear(), Manager::Get(), IsProcessRunning(), m_IsWorkspaceOperation, m_pLog, and Manager::ProcessEvent().
Referenced by DoPrepareQueue().
int CompilerGCC::CompileFile (const wxString & file) virtual
Compile a specific file.
Parameters
file The file to compile (must be a project file!)
Implements cbCompilerPlugin.
References baBuildFile, CheckProject(), cltError, CompileFileDefault(), CompileFileWithoutProject(), CompilerValid(), DoClearErrors(), DoPrepareQueue(), CompileTargetBase::GetBasePath(), GetBuildTargetForFile(), cbProject::GetFileByFilename(), LogMessage(), LogWarningOrError(), m_pProject, PrintBanner(), and ProjectFile::relativeToCommonTopLevelPath.
Referenced by DoBuild(), and StartCompileFile().
int CompilerGCC::CompileFileDefault (cbProject * project, ProjectFile * pf, ProjectBuildTarget * bt) virtual
References AddToCommandQueue(), cltError, DirectCommands::CompileFile(), DoRunQueue(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompileTargetBase::GetTitle(), LogMessage(), LogWarningOrError(), m_PageIndex, and ProjectFile::relativeToCommonTopLevelPath.
Referenced by CompileFile(), and OnCompileFileRequest().
int CompilerGCC::CompileFileWithoutProject (const wxString & file) virtual
References AddToCommandQueue(), DoRunQueue(), Manager::Get(), DirectCommands::GetCompileSingleFileCommand(), CompilerFactory::GetDefaultCompiler(), CompilerFactory::GetDefaultCompilerID(), Manager::GetEditorManager(), Manager::GetMacrosManager(), m_PageIndex, MacrosManager::Reset(), EditorManager::Save(), and SwitchCompiler().
Referenced by CompileFile().
bool CompilerGCC::CompilerValid (ProjectBuildTarget * target = 0) private
References CompilerFactory::GetCompiler(), GetCurrentCompilerID(), CompilerFactory::GetDefaultCompiler(), and Compiler::IsValid().
Referenced by CompileFile(), DistClean(), DoBuild(), PreprocessJob(), PrintBanner(), and Run().
int CompilerGCC::Configure (cbProject * project, ProjectBuildTarget * target = 0L) virtual
Display configuration dialog.
Parameters
project The selected project (can be NULL).
target The selected target (can be NULL).
Implements cbCompilerPlugin.
References BuildLogger::AddBuildProgressBar(), cbConfigurationDialog::AttachConfigurationPanel(), CompilerOptionsDlg, Manager::Get(), Manager::GetConfigManager(), Manager::GetMacrosManager(), m_pLog, PlaceWindow(), ConfigManager::ReadBool(), BuildLogger::RemoveBuildProgressBar(), MacrosManager::Reset(), SaveOptions(), cbConfigurationPanel::SetParentDialog(), and wxScrollingDialog::ShowModal().
Referenced by OnConfig(), OnProjectCompilerOptions(), and OnTargetCompilerOptions().
void CompilerGCC::Dispatcher (wxCommandEvent & event) private
References Manager::Get(), cbEditor::GetControl(), OnClean(), OnCleanAll(), OnCleanFile(), OnClearErrors(), OnCompile(), OnCompileAll(), OnCompileAndRun(), OnCompileFile(), OnConfig(), OnKillProcess(), OnNextError(), OnPreviousError(), OnProjectCompilerOptions(), OnRebuild(), OnRebuildAll(), OnRun(), and OnTargetCompilerOptions().
int CompilerGCC::DistClean (ProjectBuildTarget * target = 0L) virtual
DistClean the project/target.
DistClean will typically remove any config files and anything else that got created as part of building a software package.
Parameters
target The specific build target to "distclean". If NULL, it cleans all the build targets of the current project.
Implements cbCompilerPlugin.
References CompilerQueue::Add(), CompilerValid(), DoPrepareQueue(), DoRunQueue(), Manager::Get(), CompileTargetBase::GetBasePath(), Manager::GetLogManager(), GetMakeCommandFor(), LogManager::Log(), m_CommandQueue, m_IsWorkspaceOperation, m_pProject, mcDistClean, cbPlugin::NotImplemented(), cbProject::SaveAllFiles(), and UseMake().
Referenced by DistClean().
int CompilerGCC::DistClean (const wxString & target) virtual
Same as DistClean(ProjectBuildTarget*) but with a wxString argument.
Implements cbCompilerPlugin.
References CheckProject(), DistClean(), cbProject::GetBuildTarget(), m_LastTargetName, and m_pProject.
ProjectBuildTarget * CompilerGCC::DoAskForTarget () private
References CheckProject(), cbProject::GetBuildTarget(), m_pProject, and m_RealTargetIndex.
Referenced by Run().
int CompilerGCC::DoBuild (bool clean, bool build) private
References BuildStateManagement(), CompilerValid(), Manager::Get(), cbProject::GetBuildTarget(), Manager::GetLogManager(), GetNextJob(), LogManager::Log(), m_Build, m_BuildingTargetName, m_Clean, m_pBuildingProject, CompilerGCC::BuildJobTarget::project, cbProject::SaveAllFiles(), and CompilerGCC::BuildJobTarget::targetName.
Referenced by Build(), Clean(), DoBuild(), DoWorkspaceBuild(), GetNextStateBasedOnJob(), and Rebuild().
int CompilerGCC::DoBuild (const wxString & target, bool clean, bool build, bool clearLog = true) private
References bjProject, CheckProject(), CompileFile(), DoBuild(), DoClearErrors(), DoPrepareQueue(), DoRunQueue(), Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), EditorBase::GetFilename(), GetTargetString(), InitBuildLog(), InitBuildState(), m_BuildJobTargetsList, m_IsWorkspaceOperation, m_pProject, NotifyCleanProject(), PreprocessJob(), and StopRunningDebugger().
void CompilerGCC::DoClean (const wxArrayString & commands) private
Referenced by BuildStateManagement().
bool CompilerGCC::DoCleanWithMake (ProjectBuildTarget * bt) private
References clogFull, cltError, cltNormal, COMPILER_ERROR_LOG, ExpandBackticks(), F(), getBuildTargetName(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), cbProject::GetExecutionDir(), GetMakeCommandFor(), Compiler::GetSwitches(), CompilerSwitches::logging, LogMessage(), m_pBuildingProject, and mcClean.
Referenced by BuildStateManagement().
void CompilerGCC::DoClearErrors () private
References CompilerErrors::Clear(), ListCtrlLogger::Clear(), m_Errors, m_NotifiedMaxErrors, and m_pListLog.
Referenced by CompileFile(), DoBuild(), DoPrepareQueue(), and OnClearErrors().
void CompilerGCC::DoClearTargetMenu () private
References m_TargetMenu.
Referenced by DoRecreateTargetMenu(), and OnRelease().
void CompilerGCC::DoGotoNextError () private
References CompilerMessages::FocusError(), CompilerErrors::GetFocusedError(), m_Errors, m_pListLog, and CompilerErrors::Next().
Referenced by OnNextError().
void CompilerGCC::DoGotoPreviousError () private
References CompilerMessages::FocusError(), CompilerErrors::GetFocusedError(), m_Errors, m_pListLog, and CompilerErrors::Previous().
Referenced by OnPreviousError().
int CompilerGCC::DoGUIAskForTarget () private
References CheckProject(), m_pProject, m_RealTargetIndex, and cbProject::SelectTarget().
Referenced by GetBuildTargetForFile(), OnTargetCompilerOptions(), and Run().
void CompilerGCC::DoPrepareQueue (bool clearLog) private
References cbEVT_COMPILER_STARTED, ClearLog(), DoClearErrors(), Manager::Get(), CompilerQueue::GetCount(), m_CommandQueue, m_pProject, m_StartTime, Manager::ProcessEvent(), and Manager::Yield().
Referenced by CompileFile(), DistClean(), DoBuild(), DoWorkspaceBuild(), and Run().
void CompilerGCC::DoRecreateTargetMenu () private
References CheckProject(), DoClearTargetMenu(), DoUpdateTargetMenu(), Manager::Get(), cbProject::GetActiveBuildTarget(), Manager::GetAppFrame(), CompileTargetBase::GetCompilerID(), cbProject::GetFirstValidBuildTargetName(), Manager::GetProjectManager(), GetTargetString(), ProjectManager::GetWorkspace(), cbPlugin::IsAttached(), IsValidTarget(), m_pProject, m_pToolTarget, m_RealTargetIndex, m_RealTargetsStartIndex, m_TargetIndex, m_TargetMenu, m_Targets, MAX_TARGETS, OnSelectTarget(), and SwitchCompiler().
Referenced by BuildMenu(), BuildToolBar(), and UpdateProjectTargets().
void CompilerGCC::DoRegisterCompilers () private
References Manager::Get(), Manager::GetConfigManager(), ConfigManager::GetFolder(), Manager::GetLogManager(), LogManager::Log(), ConfigManager::ReadBool(), CompilerFactory::RegisterCompiler(), CompilerFactory::RegisterUserCompilers(), sdDataGlobal, and sdDataUser.
Referenced by CompilerOptionsDlg::OnApply(), and OnAttach().
int CompilerGCC::DoRunQueue () private
References CompilerMessages::AutoFitColumns(), bsNone, BuildStateManagement(), cbGetDynamicLinkerPathForTarget(), cbMergeLibPaths(), CompilerQueue::Clear(), cltError, cltNormal, CompilerCommand::command, DEFAULT_CONSOLE_SHELL, Delete(), CompilerCommand::dir, ExpandBackticks(), Manager::Get(), Manager::GetConfigManager(), GetErrWarnStr(), Manager::GetMacrosManager(), GetMinSecStr(), GetNextAvailableProcessIndex(), CompileTargetBase::GetOutputFilename(), Manager::GetScriptingManager(), Manager::IsBatchBuild(), CompilerCommand::isLink, IsProcessRunning(), CompilerCommand::isRun, CompilerQueue::LastCommandWasRun(), ScriptingManager::LoadScript(), LogMessage(), LogWarningOrError(), ltAll, ltFile, ltMessages, m_BuildState, m_CdRun, m_CommandQueue, m_CompilerProcessList, m_NextBuildState, m_pListLog, m_pLog, m_pProject, m_RunAfterCompile, m_timerIdleWakeUp, CompilerCommand::message, CompilerCommand::mustWait, CompilerQueue::Next(), NotifyJobDone(), CompilerQueue::Peek(), BuildLogger::progress, ConfigManager::Read(), ConfigManager::ReadBool(), MacrosManager::ReplaceMacros(), ResetBuildState(), Run(), SaveBuildLog(), and CompilerCommand::target.
Referenced by CompileFileDefault(), CompileFileWithoutProject(), DistClean(), DoBuild(), DoWorkspaceBuild(), OnJobEnd(), and OnRun().
FileTreeData * CompilerGCC::DoSwitchProjectTemporarily () private
References AskForActiveProject(), Manager::Get(), FileTreeData::GetProject(), Manager::GetProjectManager(), cbProjectManagerUI::GetTree(), cbProjectManagerUI::GetTreeSelection(), ProjectManager::GetUI(), and ProjectManager::SetProject().
Referenced by OnClean(), OnCleanFile(), OnCompile(), OnRebuild(), OnTargetCompilerOptions(), and PrepareCompileFilePM().
void CompilerGCC::DoUpdateTargetMenu (int targetIndex) private
References GetTargetString(), m_pProject, m_RealTargetIndex, m_RealTargetsStartIndex, m_TargetIndex, m_TargetMenu, MAX_TARGETS, and cbProject::SetActiveBuildTarget().
Referenced by DoRecreateTargetMenu(), and OnSelectTarget().
int CompilerGCC::DoWorkspaceBuild (const wxString & target, bool clean, bool build, bool clearLog = true) private
References bjWorkspace, DoBuild(), DoPrepareQueue(), DoRunQueue(), F(), Manager::Get(), Manager::GetLogManager(), Manager::GetProjectManager(), ProjectManager::GetProjects(), GetTargetString(), CompileTargetBase::GetTitle(), InitBuildLog(), InitBuildState(), LogManager::Log(), m_BuildJobTargetsList, m_IsWorkspaceOperation, m_PageIndex, NotifyCleanWorkspace(), PreprocessJob(), cbProject::SaveAllFiles(), and StopRunningDebugger().
Referenced by BuildWorkspace(), CleanWorkspace(), and RebuildWorkspace().
void CompilerGCC::ExpandTargets (cbProject * project, const wxString & targetName, wxArrayString & result) private
References cbProject::GetBuildTarget(), and cbProject::GetExpandedVirtualBuildTargetGroup().
Referenced by PreprocessJob().
void CompilerGCC::FreeProcesses () private
References Delete(), and m_CompilerProcessList.
Referenced by OnRelease(), and ReAllocProcesses().
int CompilerGCC::GetActiveProcessCount () const private
References m_CompilerProcessList.
ProjectBuildTarget * CompilerGCC::GetBuildTargetForFile (ProjectFile * pf) private
References ProjectFile::buildTargets, cbMessageBox(), DoGUIAskForTarget(), cbProject::GetBuildTarget(), m_pProject, m_RealTargetIndex, m_TargetIndex, and m_Targets.
Referenced by CompileFile(), and OnCleanFile().
int CompilerGCC::GetConfigurationGroup () const inline virtual
Return the configuration group for this plugin.
Default is cgUnknown. Notice that you can logically AND more than one configuration groups, so you could set it, for example, as "cgCompiler | cgContribPlugin".
Reimplemented from cbPlugin.
References cgCompiler.
cbConfigurationPanel * CompilerGCC::GetConfigurationPanel (wxWindow * parent)
References CompilerOptionsDlg.
int CompilerGCC::GetConfigurationPriority () const inline virtual
Return the plugin's configuration priority.
This is a number (default is 50) that is used to sort plugins in configuration dialogs. Lower numbers mean the plugin's configuration is put higher in the list.
Reimplemented from cbPlugin.
const wxString & CompilerGCC::GetCurrentCompilerID ()
References CompilerFactory::GetCompiler(), and m_CompilerId.
Referenced by CompilerValid(), PreprocessJob(), and PrintBanner().
wxString CompilerGCC::GetCurrentCompilerID (ProjectBuildTarget * target) private
References CompileTargetBase::GetCompilerID(), m_pBuildingProject, and m_pProject.
wxString CompilerGCC::GetErrWarnStr () private
References cltError, cltWarning, CompilerErrors::GetCount(), and m_Errors.
Referenced by DoRunQueue(), and OnJobEnd().
virtual int CompilerGCC::GetExitCode () const inline virtual
Get the exit code of the last build process.
Implements cbCompilerPlugin.
References m_LastExitCode.
wxString CompilerGCC::GetMakeCommandFor (MakeCommand cmd, cbProject * project, ProjectBuildTarget * target) private
References Manager::Get(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetDefaultCompilerID(), Manager::GetMacrosManager(), CompileTargetBase::GetMakeCommandFor(), cbProject::GetMakefile(), Compiler::GetPrograms(), CompileTargetBase::GetTitle(), CompilerFactory::IsValidCompilerID(), CompilerPrograms::MAKE, and MacrosManager::ReplaceMacros().
Referenced by BuildStateManagement(), DistClean(), and DoCleanWithMake().
wxString CompilerGCC::GetMinSecStr () private
References m_StartTime.
Referenced by DoRunQueue(), and OnJobEnd().
int CompilerGCC::GetNextAvailableProcessIndex () const private
References m_CompilerProcessList.
Referenced by DoRunQueue().
CompilerGCC::BuildJobTarget CompilerGCC::GetNextJob () private
References m_BuildJobTargetsList.
Referenced by DoBuild(), and GetNextStateBasedOnJob().
BuildState CompilerGCC::GetNextStateBasedOnJob () private
References bjTarget, bsNone, bsProjectDone, bsProjectPostBuild, bsProjectPreBuild, bsTargetBuild, bsTargetClean, bsTargetDone, bsTargetPostBuild, bsTargetPreBuild, DoBuild(), GetNextJob(), m_Build, m_BuildingTargetName, m_BuildJob, m_BuildState, m_Clean, m_NextBuildState, m_pBuildingProject, PeekNextJob(), CompilerGCC::BuildJobTarget::project, cbProject::SetCurrentlyCompilingTarget(), and CompilerGCC::BuildJobTarget::targetName.
Referenced by BuildStateManagement().
int CompilerGCC::GetTargetIndexFromName (cbProject * prj, const wxString & name) private
References cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), and CompileTargetBase::GetTitle().
Referenced by AddToCommandQueue(), and BuildStateManagement().
wxString CompilerGCC::GetTargetString (int index = -1) private
References m_TargetIndex, and m_Targets.
Referenced by DoBuild(), DoRecreateTargetMenu(), DoUpdateTargetMenu(), DoWorkspaceBuild(), and OnSelectTarget().
virtual int CompilerGCC::GetToolBarPriority () inline virtual
This method return the priority of the plugin's toolbar, the less value indicates a more preceding position when C::B starts with no configuration file.
Reimplemented from cbPlugin.
void CompilerGCC::InitBuildLog (bool workspaceBuild) private
References Manager::Get(), CompileTargetBase::GetBasePath(), cbWorkspace::GetFilename(), CompileTargetBase::GetFilename(), Manager::GetProjectManager(), cbWorkspace::GetTitle(), CompileTargetBase::GetTitle(), ProjectManager::GetWorkspace(), m_BuildLogContents, m_BuildLogFilename, m_BuildLogTitle, m_BuildStartTime, m_CurrentProgress, m_MaxProgress, and m_pProject.
Referenced by DoBuild(), and DoWorkspaceBuild().
void CompilerGCC::InitBuildState (BuildJob job, const wxString & target) private
References bsNone, bsProjectPreBuild, CompilerQueue::Clear(), m_BuildingTargetName, m_BuildJob, m_BuildState, m_CommandQueue, m_NextBuildState, m_pBuildingProject, m_pLastBuildingProject, and m_pLastBuildingTarget.
Referenced by DoBuild(), and DoWorkspaceBuild().
bool CompilerGCC::IsProcessRunning (int idx = -1) const private
References m_CompilerProcessList.
Referenced by BuildStateManagement(), ClearLog(), DoRunQueue(), IsRunning(), KillProcess(), NotifyJobDone(), OnIdle(), and OnJobEnd().
bool CompilerGCC::IsRunning () const virtual
Is the plugin currently compiling?
Implements cbCompilerPlugin.
References bjIdle, CompilerQueue::GetCount(), IsProcessRunning(), m_BuildJob, and m_CommandQueue.
Referenced by BuildModuleMenu(), CompilerOptionsDlg::OnApply(), and OnUpdateUI().
bool CompilerGCC::IsValidTarget (const wxString & target) const
References Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetBuildTarget(), Manager::GetProjectManager(), m_Targets, and CompileOptionsBase::SupportsCurrentPlatform().
Referenced by DoRecreateTargetMenu().
int CompilerGCC::KillProcess () virtual
Abort the current build process.
Implements cbCompilerPlugin.
References CompilerQueue::Clear(), cltInfo, F(), Manager::Get(), ProjectManager::GetIsRunning(), Manager::GetLogManager(), Manager::GetProjectManager(), IsProcessRunning(), CompilerQueue::LastCommandWasRun(), LogManager::Log(), LogMessage(), ltMessages, m_CommandQueue, m_CompilerProcessList, m_PageIndex, m_RunAfterCompile, NULL, ResetBuildState(), and ProjectManager::SetIsRunning().
Referenced by OnKillProcess().
void CompilerGCC::LoadOptions () private
References CompilerFactory::LoadSettings().
Referenced by CompilerOptionsDlg::OnApply(), and OnAttach().
void CompilerGCC::LogMessage (const wxString & message, CompilerLineType lt = cltNormal, LogTarget log = ltAll, bool forceErrorColour = false, bool isTitle = false, bool updateProgress = false) private
References Logger::caption, cltError, cltWarning, COMPILER_ERROR_ID_LOG, COMPILER_NOTE_ID_LOG, COMPILER_SIMPLE_LOG, COMPILER_WARNING_ID_LOG, Logger::critical, Logger::error, Manager::Get(), Manager::GetLogManager(), Logger::info, LogManager::Log(), LogManager::LogToStdOut(), LogWarningOrError(), ltFile, ltMessages, m_BuildLogContents, m_CurrentProgress, m_LogBuildProgressPercentage, m_MaxProgress, m_PageIndex, m_pLog, BuildLogger::progress, and Logger::warning.
Referenced by AddOutputLine(), BuildStateManagement(), CompileFile(), CompileFileDefault(), DoCleanWithMake(), DoRunQueue(), KillProcess(), NotifyJobDone(), OnJobEnd(), and PrintBanner().
void CompilerGCC::LogWarningOrError (CompilerLineType lt, cbProject * prj, const wxString & filename, const wxString & line, const wxString & msg) private
References CompilerErrors::AddError(), ListCtrlLogger::Append(), cltError, cltWarning, Logger::error, Logger::info, m_Errors, m_pListLog, and Logger::warning.
Referenced by AddOutputLine(), CompileFile(), CompileFileDefault(), DoRunQueue(), LogMessage(), OnJobEnd(), and PrintBanner().
void CompilerGCC::NotifyCleanProject (const wxString & target) private
References cbEVT_CLEAN_PROJECT_STARTED, Manager::Get(), CompilerQueue::GetCount(), m_CommandQueue, m_pProject, Manager::ProcessEvent(), CodeBlocksEvent::SetBuildTargetName(), and Manager::Yield().
Referenced by DoBuild().
void CompilerGCC::NotifyCleanWorkspace () private
References cbEVT_CLEAN_WORKSPACE_STARTED, Manager::Get(), CompilerQueue::GetCount(), m_CommandQueue, Manager::ProcessEvent(), and Manager::Yield().
Referenced by DoWorkspaceBuild().
void CompilerGCC::NotifyJobDone (bool showNothingToBeDone = false) private
References bjIdle, cbEVT_COMPILER_FINISHED, cbEVT_HIDE_LOG_MANAGER, cltError, Manager::Get(), CompilerErrors::GetCount(), ProjectManager::GetIsRunning(), Manager::GetProjectManager(), IsProcessRunning(), LogMessage(), m_BuildJob, m_Clean, m_Errors, m_LastBuildStep, m_LastExitCode, m_pProject, NULL, Manager::ProcessEvent(), and ProjectManager::SetIsRunning().
Referenced by DoRunQueue(), OnJobEnd(), and PreprocessJob().
void CompilerGCC::OnAttach () virtual
Any descendent plugin should override this virtual method and perform any necessary initialization.
This method is called by Code::Blocks (PluginManager actually) when the plugin has been loaded and should attach in Code::Blocks. When Code::Blocks starts up, it finds and loads all plugins but does not activate (attaches) them. It then activates all plugins that the user has selected to be activated on start-up.
This means that a plugin might be loaded but not activated...
Think of this method as the actual constructor...
Reimplemented from cbPlugin.
References BuildLogger::AddBuildProgressBar(), AllocProcesses(), bjIdle, bsNone, cbEVT_ADD_LOG_WINDOW, cbEVT_COMPILE_FILE_REQUEST, cbEVT_PROJECT_ACTIVATE, cbEVT_PROJECT_CLOSE, cbEVT_PROJECT_OPEN, cbEVT_PROJECT_TARGETS_MODIFIED, cbLoadBitmap(), DoRegisterCompilers(), ScriptBindings::gBuildLog(), ScriptBindings::gBuildLogId, Manager::Get(), Manager::GetConfigManager(), ConfigManager::GetDataFolder(), Manager::GetLogManager(), Manager::GetScriptingManager(), LogSlot::icon, Manager::IsBatchBuild(), LoadOptions(), m_Build, m_BuildJob, m_Clean, m_Errors, m_IsWorkspaceOperation, m_LastBuildStep, m_LastExitCode, m_ListPageIndex, m_LogBuildProgressPercentage, m_Menu, m_NextBuildState, m_NotifiedMaxErrors, m_PageIndex, m_pBuildingProject, m_pErrorsMenu, m_pLastBuildingProject, m_pLastBuildingTarget, m_pListLog, m_pLog, m_pProject, m_pTbar, m_pToolTarget, m_RealTargetIndex, m_RealTargetsStartIndex, m_RunAfterCompile, m_RunProjectPostBuild, m_RunTargetPostBuild, m_TargetIndex, m_TargetMenu, m_timerIdleWakeUp, MAX_TARGETS, OnCompileFileRequest(), OnProjectActivated(), OnProjectLoaded(), OnProjectUnloaded(), Manager::ProcessEvent(), ConfigManager::ReadBool(), Manager::RegisterEventSink(), CompilerMessages::SetCompilerErrors(), CompilerFactory::SetDefaultCompiler(), LogManager::SetLog(), LogManager::Slot(), and LogSlot::title.
void CompilerGCC::OnClean (wxCommandEvent & event)
References CheckProject(), Clean(), DoSwitchProjectTemporarily(), idMenuCleanFromProjectManager, m_pProject, m_RealTargetIndex, AnnoyingDialog::rtNO, and AnnoyingDialog::ShowModal().
Referenced by Dispatcher().
void CompilerGCC::OnCleanAll (wxCommandEvent & event)
References CleanWorkspace(), AnnoyingDialog::rtNO, and AnnoyingDialog::ShowModal().
Referenced by Dispatcher().
void CompilerGCC::OnCleanFile (wxCommandEvent & event)
References CheckProject(), LogManager::DebugLog(), DoSwitchProjectTemporarily(), F(), Manager::Get(), CompileTargetBase::GetBasePath(), GetBuildTargetForFile(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), Manager::GetLogManager(), Manager::GetMacrosManager(), CompileTargetBase::GetObjectOutput(), ProjectFile::GetObjName(), FileTreeData::GetProjectFile(), Compiler::GetSwitches(), idMenuCleanFileFromProjectManager, m_pProject, MacrosManager::ReplaceEnvVars(), and CompilerSwitches::UseFlatObjects.
Referenced by Dispatcher().
void CompilerGCC::OnClearErrors (wxCommandEvent & event)
References DoClearErrors().
Referenced by Dispatcher().
void CompilerGCC::OnCompile (wxCommandEvent & event)
References Build(), DoSwitchProjectTemporarily(), idMenuCompileFromProjectManager, and m_RealTargetIndex.
Referenced by Dispatcher().
void CompilerGCC::OnCompileAll (wxCommandEvent & event)
References BuildWorkspace().
Referenced by Dispatcher().
void CompilerGCC::OnCompileAndRun (wxCommandEvent & event)
References Build(), and m_RunAfterCompile.
Referenced by Dispatcher().
void CompilerGCC::OnCompileFile (wxCommandEvent & event)
References idMenuCompileFileFromProjectManager, PrepareCompileFile(), PrepareCompileFilePM(), and StartCompileFile().
Referenced by Dispatcher().
void CompilerGCC::OnCompileFileRequest (CodeBlocksEvent & event) private
References ProjectFile::buildTargets, CompileFileDefault(), LogManager::DebugLog(), F(), Manager::Get(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetFileByFilename(), EditorBase::GetFilename(), Manager::GetLogManager(), m_RealTargetIndex, and UnixFilename().
Referenced by OnAttach().
void CompilerGCC::OnConfig (wxCommandEvent & event)
References Configure(), and NULL.
Referenced by Dispatcher().
void CompilerGCC::OnGCCError (CodeBlocksEvent & event) private
References AddOutputLine().
void CompilerGCC::OnGCCOutput (CodeBlocksEvent & event) private
References AddOutputLine().
void CompilerGCC::OnGCCTerminated (CodeBlocksEvent & event) private
References idGCCProcess1, and OnJobEnd().
void CompilerGCC::OnIdle (wxIdleEvent & event)
References IsProcessRunning(), and m_CompilerProcessList.
void CompilerGCC::OnJobEnd (size_t procIndex, int exitCode) private
References CompilerMessages::AutoFitColumns(), bsNone, BuildStateManagement(), cbEVT_GET_ACTIVE_LOG_WINDOW, cbEVT_HIDE_LOG_MANAGER, cbEVT_SHOW_LOG_MANAGER, cbEVT_SWITCH_TO_LOG_WINDOW, CompilerQueue::Clear(), cltError, cltNormal, cltWarning, DoRunQueue(), CompilerMessages::FocusError(), Manager::Get(), EditorManager::GetBuiltinEditor(), CompilerFactory::GetCompiler(), Manager::GetConfigManager(), cbEditor::GetControl(), CompilerErrors::GetCount(), CompilerQueue::GetCount(), Manager::GetEditorManager(), GetErrWarnStr(), CompilerErrors::GetFirstError(), Manager::GetLogManager(), Manager::GetMacrosManager(), GetMinSecStr(), Manager::IsBatchBuild(), IsProcessRunning(), CompilerQueue::LastCommandWasRun(), LogManager::Log(), CodeBlocksLogEvent::logger, LogMessage(), LogWarningOrError(), ltAll, m_BuildJobTargetsList, m_BuildState, m_CommandQueue, m_CompilerId, m_CompilerProcessList, m_Errors, m_LastExitCode, m_NextBuildState, m_PageIndex, m_pListLog, m_pLog, m_RunAfterCompile, m_timerIdleWakeUp, NotifyJobDone(), Manager::ProcessEvent(), BuildLogger::progress, ConfigManager::ReadBool(), MacrosManager::ReplaceMacros(), ResetBuildState(), Run(), SaveBuildLog(), and UnixFilename().
Referenced by OnGCCTerminated().
void CompilerGCC::OnKillProcess (wxCommandEvent & event)
References KillProcess().
Referenced by Dispatcher().
void CompilerGCC::OnNextError (wxCommandEvent & event)
References DoGotoNextError().
Referenced by Dispatcher().
void CompilerGCC::OnPreviousError (wxCommandEvent & event)
References DoGotoPreviousError().
Referenced by Dispatcher().
void CompilerGCC::OnProjectActivated (CodeBlocksEvent & event) private
References Manager::Get(), ProjectManager::GetActiveProject(), CodeBlocksEvent::GetProject(), Manager::GetProjectManager(), and UpdateProjectTargets().
Referenced by OnAttach().
void CompilerGCC::OnProjectCompilerOptions (wxCommandEvent & event)
References Configure(), Manager::Get(), cbProject::GetBuildTarget(), FileTreeData::GetProject(), Manager::GetProjectManager(), CompileTargetBase::GetTitle(), cbProjectManagerUI::GetTree(), cbProjectManagerUI::GetTreeSelection(), ProjectManager::GetUI(), m_pProject, and m_RealTargetIndex.
Referenced by Dispatcher().
void CompilerGCC::OnProjectLoaded (CodeBlocksEvent & event) private
Referenced by OnAttach().
void CompilerGCC::OnProjectUnloaded (CodeBlocksEvent & event) private
References CodeBlocksEvent::GetProject(), and m_pProject.
Referenced by OnAttach().
void CompilerGCC::OnRebuild (wxCommandEvent & event)
References CheckProject(), DoSwitchProjectTemporarily(), idMenuRebuildFromProjectManager, m_pProject, m_RealTargetIndex, Rebuild(), AnnoyingDialog::rtNO, and AnnoyingDialog::ShowModal().
Referenced by Dispatcher().
void CompilerGCC::OnRebuildAll (wxCommandEvent & event)
References RebuildWorkspace(), AnnoyingDialog::rtNO, and AnnoyingDialog::ShowModal().
Referenced by Dispatcher().
void CompilerGCC::OnRelease (bool appShutDown) virtual
References cbEVT_REMOVE_LOG_WINDOW, CompilerMessages::DestroyControls(), DoClearTargetMenu(), FreeProcesses(), ScriptBindings::gBuildLogId, Manager::Get(), Manager::GetConfigManager(), CompilerFactory::GetDefaultCompilerID(), Manager::IsBatchBuild(), m_pListLog, m_pLog, m_timerIdleWakeUp, Manager::ProcessEvent(), SaveOptions(), CompilerFactory::UnregisterCompilers(), and ConfigManager::Write().
void CompilerGCC::OnRun (wxCommandEvent & event)
References DoRunQueue(), and Run().
Referenced by Dispatcher().
void CompilerGCC::OnSelectTarget (wxCommandEvent & event)
References DoUpdateTargetMenu(), Manager::Get(), Manager::GetProjectManager(), GetTargetString(), ProjectManager::GetWorkspace(), idToolTarget, m_pToolTarget, and cbWorkspace::SetPreferredTarget().
Referenced by DoRecreateTargetMenu().
void CompilerGCC::OnTargetCompilerOptions (wxCommandEvent & event)
References Configure(), DoGUIAskForTarget(), DoSwitchProjectTemporarily(), m_pProject, and m_RealTargetIndex.
Referenced by Dispatcher().
void CompilerGCC::OnTimer (wxTimerEvent & event)
void CompilerGCC::OnUpdateUI (wxUpdateUIEvent & event)
References Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetAppFrame(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), ProjectManager::GetIsRunning(), Manager::GetProjectManager(), CompilerErrors::HasNextError(), CompilerErrors::HasPreviousError(), IsRunning(), m_Errors, m_pTbar, and m_pToolTarget.
const CompilerGCC::BuildJobTarget & CompilerGCC::PeekNextJob () private
References m_BuildJobTargetsList.
Referenced by GetNextStateBasedOnJob().
void CompilerGCC::PrepareCompileFile (wxFileName & file) private
References CheckProject(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), EditorBase::GetFilename(), ProjectFile::GetParentProject(), cbEditor::GetProjectFile(), Manager::GetProjectManager(), cbEditor::Save(), and ProjectManager::SetProject().
Referenced by OnCompileFile().
void CompilerGCC::PrepareCompileFilePM (wxFileName & file) private
References CheckProject(), DoSwitchProjectTemporarily(), ProjectFile::file, and FileTreeData::GetProjectFile().
Referenced by OnCompileFile().
void CompilerGCC::PreprocessJob (cbProject * project, const wxString & targetName) private
References CalculateProjectDependencies(), CalculateWorkspaceDependencies(), CompilerValid(), ExpandTargets(), F(), Manager::Get(), cbProject::GetBuildTarget(), CompilerFactory::GetCompiler(), GetCurrentCompilerID(), Manager::GetLogManager(), Compiler::GetName(), Manager::GetProjectManager(), ProjectManager::GetProjects(), CompileTargetBase::GetTitle(), LogManager::LogWarning(), m_BuildJobTargetsList, m_IsWorkspaceOperation, m_PageIndex, NotifyJobDone(), CompilerGCC::BuildJobTarget::project, CompileOptionsBase::SupportsCurrentPlatform(), and CompilerGCC::BuildJobTarget::targetName.
Referenced by DoBuild(), and DoWorkspaceBuild().
void CompilerGCC::PrintBanner (BuildAction action, cbProject * prj = 0, ProjectBuildTarget * target = 0) private
References CompilerMessages::AutoFitColumns(), baBuild, baBuildFile, baClean, baRun, cbEVT_SHOW_LOG_MANAGER, cltNormal, CompilerValid(), Manager::Get(), CompilerFactory::GetCompiler(), GetCurrentCompilerID(), Compiler::GetName(), CompileTargetBase::GetTitle(), LogMessage(), LogWarningOrError(), ltAll, m_pListLog, m_pProject, and Manager::ProcessEvent().
Referenced by BuildStateManagement(), CompileFile(), and Run().
wxString CompilerGCC::ProjectMakefile () private
References AskForActiveProject(), cbProject::GetMakefile(), and m_pProject.
bool CompilerGCC::ReAllocProcesses () private
References AllocProcesses(), and FreeProcesses().
Referenced by CompilerOptionsDlg::OnApply().
int CompilerGCC::Rebuild (ProjectBuildTarget * target = 0L) virtual
Rebuild the project/target.
Rebuilding a project is equal to calling Clean() and then Build(). This makes sure that all compilable files in the project will be compiled again.
Parameters
target The specific build target to rebuild. If NULL, it rebuilds all the build targets of the current project.
Implements cbCompilerPlugin.
References CompileTargetBase::GetTitle().
Referenced by OnRebuild().
int CompilerGCC::Rebuild (const wxString & target) virtual
Same as Rebuild(ProjectBuildTarget*) but with a wxString argument.
Implements cbCompilerPlugin.
References DoBuild(), Manager::Get(), Manager::GetConfigManager(), m_LastBuildStep, and ConfigManager::ReadBool().
int CompilerGCC::RebuildWorkspace (const wxString & target = wxEmptyString) virtual
Rebuild all open projects.
Parameters
target If not empty, the target to rebuild in each project. Else all targets.
Implements cbCompilerPlugin.
References DoWorkspaceBuild(), Manager::Get(), Manager::GetConfigManager(), m_LastBuildStep, and ConfigManager::ReadBool().
Referenced by OnRebuildAll().
void CompilerGCC::ResetBuildState () private
References bjIdle, bsNone, CompilerQueue::Clear(), Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetProjects(), m_BuildingTargetName, m_BuildJob, m_BuildState, m_CommandQueue, m_NextBuildState, m_pBuildingProject, m_pLastBuildingProject, m_pLastBuildingTarget, m_pProject, and cbProject::SetCurrentlyCompilingTarget().
Referenced by BuildStateManagement(), DoRunQueue(), KillProcess(), and OnJobEnd().
int CompilerGCC::Run (ProjectBuildTarget * target = 0L) virtual
Run the project/target.
Running a project means executing its build output. Of course this depends on the selected build target and its type.
Parameters
target The specific build target to "run". If NULL, the plugin should ask the user which target to "run" (except maybe if there is only one build target in the project).
Implements cbCompilerPlugin.
References CompilerQueue::Add(), baRun, Build(), cbGetDynamicLinkerPathForTarget(), cbMessageBox(), CheckProject(), CompilerValid(), DEFAULT_CONSOLE_SHELL, DEFAULT_CONSOLE_TERM, DoAskForTarget(), DoGUIAskForTarget(), DoPrepareQueue(), EscapeSpaces(), F(), Manager::Get(), cbProject::GetActiveBuildTarget(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompileTargetBase::GetCompilerID(), Manager::GetConfigManager(), ConfigManager::GetExecutableFolder(), CompileTargetBase::GetExecutionParameters(), CompileTargetBase::GetHostApplication(), Manager::GetLogManager(), Manager::GetMacrosManager(), CompileTargetBase::GetOutputFilename(), Manager::GetProjectManager(), CompileTargetBase::GetRunHostApplicationInTerminal(), CompileTargetBase::GetTargetType(), CompileTargetBase::GetTitle(), ProjectBuildTarget::GetUseConsoleRunner(), CompileTargetBase::GetWorkingDir(), LogManager::Log(), LogManager::LogWarning(), m_CdRun, m_CommandQueue, m_PageIndex, m_pProject, m_RealTargetIndex, m_RunAfterCompile, PrintBanner(), QuoteStringIfNeeded(), ConfigManager::Read(), MacrosManager::ReplaceEnvVars(), MacrosManager::ReplaceMacros(), RunSingleFile(), cbProject::SetCurrentlyCompilingTarget(), ProjectManager::SetIsRunning(), ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttStaticLib, and UnixFilename().
Referenced by DoRunQueue(), OnJobEnd(), OnRun(), and Run().
int CompilerGCC::Run (const wxString & target) virtual
Same as Run(ProjectBuildTarget*) but with a wxString argument.
Implements cbCompilerPlugin.
References CheckProject(), cbProject::GetBuildTarget(), m_LastTargetName, m_pProject, and Run().
int CompilerGCC::RunSingleFile (const wxString & filename) virtual
References CompilerQueue::Add(), Build(), cbMessageBox(), DEFAULT_CONSOLE_TERM, FileFilters::EXECUTABLE_EXT, F(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::GetExecutableFolder(), Manager::GetLogManager(), Manager::GetMacrosManager(), Manager::GetScriptingManager(), ScriptingManager::LoadScript(), LogManager::Log(), m_CdRun, m_CommandQueue, m_PageIndex, m_RunAfterCompile, ConfigManager::Read(), and MacrosManager::ReplaceEnvVars().
Referenced by Run().
void CompilerGCC::SaveBuildLog () private
References F(), Manager::Get(), Manager::GetLogManager(), LogManager::Log(), m_BuildLogContents, m_BuildLogFilename, m_BuildLogTitle, m_BuildStartTime, m_PageIndex, and Logger::warning.
Referenced by DoRunQueue(), and OnJobEnd().
void CompilerGCC::SaveOptions () private
References CompilerFactory::SaveSettings().
Referenced by Configure(), CompilerOptionsDlg::OnApply(), and OnRelease().
void CompilerGCC::SetupEnvironment () private
References CompilerPrograms::C, LogManager::DebugLog(), LogManager::DebugLogError(), InfoWindow::Display(), F(), Manager::Get(), CompilerFactory::GetCompiler(), Compiler::GetExtraPaths(), Manager::GetLogManager(), Manager::GetMacrosManager(), Compiler::GetMasterPath(), Compiler::GetName(), Compiler::GetPrograms(), m_CompilerId, and MacrosManager::ReplaceMacros().
Referenced by CompilerOptionsDlg::OnApply(), and SwitchCompiler().
void CompilerGCC::StartCompileFile (wxFileName file) private
References cbEVT_SWITCH_TO_LOG_WINDOW, CompileFile(), Manager::Get(), CompileTargetBase::GetBasePath(), Manager::GetLogManager(), LogManager::Log(), m_pLog, m_pProject, Manager::ProcessEvent(), cbProject::SaveAllFiles(), and UnixFilename().
Referenced by OnCompileFile().
bool CompilerGCC::StopRunningDebugger () private
References cbMessageBox(), TextCtrlLogger::Clear(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), Manager::GetLogManager(), cbDebuggerPlugin::IsRunning(), LogManager::Log(), m_PageIndex, m_pLog, and cbDebuggerPlugin::Stop().
Referenced by DoBuild(), and DoWorkspaceBuild().
void CompilerGCC::SwitchCompiler (const wxString & id)
References CompilerFactory::GetCompiler(), m_CompilerId, and SetupEnvironment().
Referenced by BuildStateManagement(), CheckProject(), CompileFileWithoutProject(), and DoRecreateTargetMenu().
void CompilerGCC::TextURL (wxTextUrlEvent & event) private
References idBuildLog, m_pLog, and BuildLogger::OpenLink().
void CompilerGCC::UpdateProjectTargets (cbProject * project) private
References DoRecreateTargetMenu(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompileTargetBase::GetTitle(), cbProject::GetVirtualBuildTargets(), m_RealTargetsStartIndex, m_Targets, and CompileOptionsBase::SupportsCurrentPlatform().
Referenced by OnProjectActivated().
bool CompilerGCC::UseMake (cbProject * project = 0) private
References CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), cbProject::IsMakefileCustom(), and m_pProject.
Referenced by AddOutputLine(), BuildStateManagement(), and DistClean().
Friends And Related Function Documentation
friend class CompilerOptionsDlg friend
Referenced by Configure(), and GetConfigurationPanel().
Member Data Documentation
bool CompilerGCC::m_Build private
Referenced by BuildStateManagement(), DoBuild(), GetNextStateBasedOnJob(), and OnAttach().
wxString CompilerGCC::m_BuildingTargetName private
Referenced by AddToCommandQueue(), BuildStateManagement(), DoBuild(), GetNextStateBasedOnJob(), InitBuildState(), and ResetBuildState().
BuildJob CompilerGCC::m_BuildJob private
Referenced by GetNextStateBasedOnJob(), InitBuildState(), IsRunning(), NotifyJobDone(), OnAttach(), and ResetBuildState().
BuildJobTargetsList CompilerGCC::m_BuildJobTargetsList private
Referenced by DoBuild(), DoWorkspaceBuild(), GetNextJob(), OnJobEnd(), PeekNextJob(), and PreprocessJob().
wxString CompilerGCC::m_BuildLogContents private
Referenced by InitBuildLog(), LogMessage(), and SaveBuildLog().
wxString CompilerGCC::m_BuildLogFilename private
Referenced by InitBuildLog(), and SaveBuildLog().
wxString CompilerGCC::m_BuildLogTitle private
Referenced by InitBuildLog(), and SaveBuildLog().
wxDateTime CompilerGCC::m_BuildStartTime private
Referenced by InitBuildLog(), and SaveBuildLog().
BuildState CompilerGCC::m_BuildState private
Referenced by BuildStateManagement(), DoRunQueue(), GetNextStateBasedOnJob(), InitBuildState(), OnJobEnd(), and ResetBuildState().
wxString CompilerGCC::m_CdRun private
Referenced by DoRunQueue(), Run(), and RunSingleFile().
bool CompilerGCC::m_Clean private
Referenced by DoBuild(), GetNextStateBasedOnJob(), NotifyJobDone(), and OnAttach().
CompilerQueue CompilerGCC::m_CommandQueue private
Referenced by AddToCommandQueue(), DistClean(), DoPrepareQueue(), DoRunQueue(), InitBuildState(), IsRunning(), KillProcess(), NotifyCleanProject(), NotifyCleanWorkspace(), OnJobEnd(), ResetBuildState(), Run(), and RunSingleFile().
wxString CompilerGCC::m_CompilerId private
Referenced by AddOutputLine(), CheckProject(), GetCurrentCompilerID(), OnJobEnd(), SetupEnvironment(), and SwitchCompiler().
CompilerProcessList CompilerGCC::m_CompilerProcessList private
Referenced by AllocProcesses(), DoRunQueue(), FreeProcesses(), GetActiveProcessCount(), GetNextAvailableProcessIndex(), IsProcessRunning(), KillProcess(), OnIdle(), and OnJobEnd().
size_t CompilerGCC::m_CurrentProgress private
Referenced by AddToCommandQueue(), InitBuildLog(), and LogMessage().
CompilerErrors CompilerGCC::m_Errors private
Referenced by AddOutputLine(), DoClearErrors(), DoGotoNextError(), DoGotoPreviousError(), GetErrWarnStr(), LogWarningOrError(), NotifyJobDone(), OnAttach(), OnJobEnd(), and OnUpdateUI().
bool CompilerGCC::m_IsWorkspaceOperation private
Referenced by ClearLog(), DistClean(), DoBuild(), DoWorkspaceBuild(), OnAttach(), and PreprocessJob().
bool CompilerGCC::m_LastBuildStep private
Referenced by Build(), Clean(), NotifyJobDone(), OnAttach(), Rebuild(), and RebuildWorkspace().
int CompilerGCC::m_LastExitCode private
Referenced by GetExitCode(), NotifyJobDone(), OnAttach(), and OnJobEnd().
wxString CompilerGCC::m_LastTargetName private
Referenced by DistClean(), and Run().
int CompilerGCC::m_ListPageIndex private
Referenced by OnAttach().
bool CompilerGCC::m_LogBuildProgressPercentage private
Referenced by LogMessage(), CompilerOptionsDlg::OnApply(), and OnAttach().
size_t CompilerGCC::m_MaxProgress private
Referenced by AddToCommandQueue(), InitBuildLog(), and LogMessage().
wxMenu* CompilerGCC::m_Menu private
Referenced by BuildMenu(), and OnAttach().
BuildState CompilerGCC::m_NextBuildState private
Referenced by BuildStateManagement(), DoRunQueue(), GetNextStateBasedOnJob(), InitBuildState(), OnAttach(), OnJobEnd(), and ResetBuildState().
bool CompilerGCC::m_NotifiedMaxErrors private
Referenced by AddOutputLine(), DoClearErrors(), and OnAttach().
int CompilerGCC::m_PageIndex private
Referenced by BuildStateManagement(), CalculateProjectDependencies(), CompileFileDefault(), CompileFileWithoutProject(), DoWorkspaceBuild(), KillProcess(), LogMessage(), OnAttach(), OnJobEnd(), PreprocessJob(), Run(), RunSingleFile(), SaveBuildLog(), and StopRunningDebugger().
cbProject* CompilerGCC::m_pBuildingProject private
Referenced by AddOutputLine(), AddToCommandQueue(), AskForActiveProject(), BuildStateManagement(), DoBuild(), DoCleanWithMake(), GetCurrentCompilerID(), GetNextStateBasedOnJob(), InitBuildState(), OnAttach(), and ResetBuildState().
wxMenu* CompilerGCC::m_pErrorsMenu private
Referenced by OnAttach().
cbProject* CompilerGCC::m_pLastBuildingProject private
Referenced by BuildStateManagement(), InitBuildState(), OnAttach(), and ResetBuildState().
ProjectBuildTarget* CompilerGCC::m_pLastBuildingTarget private
Referenced by AddOutputLine(), BuildStateManagement(), InitBuildState(), OnAttach(), and ResetBuildState().
CompilerMessages* CompilerGCC::m_pListLog private
Referenced by DoClearErrors(), DoGotoNextError(), DoGotoPreviousError(), DoRunQueue(), LogWarningOrError(), OnAttach(), OnJobEnd(), OnRelease(), and PrintBanner().
BuildLogger* CompilerGCC::m_pLog private
Referenced by AddToCommandQueue(), ClearLog(), Configure(), DoRunQueue(), LogMessage(), OnAttach(), OnJobEnd(), OnRelease(), StartCompileFile(), StopRunningDebugger(), and TextURL().
cbProject* CompilerGCC::m_pProject private
Referenced by AddOutputLine(), AskForActiveProject(), CheckProject(), CompileFile(), DistClean(), DoAskForTarget(), DoBuild(), DoGUIAskForTarget(), DoPrepareQueue(), DoRecreateTargetMenu(), DoRunQueue(), DoUpdateTargetMenu(), GetBuildTargetForFile(), GetCurrentCompilerID(), InitBuildLog(), NotifyCleanProject(), NotifyJobDone(), OnAttach(), OnClean(), OnCleanFile(), OnProjectCompilerOptions(), OnProjectUnloaded(), OnRebuild(), OnTargetCompilerOptions(), PrintBanner(), ProjectMakefile(), ResetBuildState(), Run(), StartCompileFile(), and UseMake().
wxToolBar* CompilerGCC::m_pTbar private
Referenced by BuildToolBar(), OnAttach(), and OnUpdateUI().
wxChoice* CompilerGCC::m_pToolTarget private
Referenced by BuildToolBar(), DoRecreateTargetMenu(), OnAttach(), OnSelectTarget(), and OnUpdateUI().
int CompilerGCC::m_RealTargetIndex private
Referenced by DoAskForTarget(), DoGUIAskForTarget(), DoRecreateTargetMenu(), DoUpdateTargetMenu(), GetBuildTargetForFile(), OnAttach(), OnClean(), OnCompile(), OnCompileFileRequest(), OnProjectCompilerOptions(), OnRebuild(), OnTargetCompilerOptions(), and Run().
int CompilerGCC::m_RealTargetsStartIndex private
Referenced by DoRecreateTargetMenu(), DoUpdateTargetMenu(), OnAttach(), and UpdateProjectTargets().
bool CompilerGCC::m_RunAfterCompile private
Referenced by DoRunQueue(), KillProcess(), OnAttach(), OnCompileAndRun(), OnJobEnd(), Run(), and RunSingleFile().
wxString CompilerGCC::m_RunCmd private
bool CompilerGCC::m_RunProjectPostBuild private
Referenced by BuildStateManagement(), and OnAttach().
bool CompilerGCC::m_RunTargetPostBuild private
Referenced by BuildStateManagement(), and OnAttach().
wxLongLong CompilerGCC::m_StartTime private
Referenced by DoPrepareQueue(), and GetMinSecStr().
int CompilerGCC::m_TargetIndex private
Referenced by DoRecreateTargetMenu(), DoUpdateTargetMenu(), GetBuildTargetForFile(), GetTargetString(), and OnAttach().
wxMenu* CompilerGCC::m_TargetMenu private
Referenced by BuildMenu(), DoClearTargetMenu(), DoRecreateTargetMenu(), DoUpdateTargetMenu(), and OnAttach().
wxArrayString CompilerGCC::m_Targets private
Referenced by DoRecreateTargetMenu(), GetBuildTargetForFile(), GetTargetString(), IsValidTarget(), and UpdateProjectTargets().
wxTimer CompilerGCC::m_timerIdleWakeUp private
Referenced by DoRunQueue(), OnAttach(), OnJobEnd(), and OnRelease().
The documentation for this class was generated from the following files:
compilergcc.h
compilergcc.cpp