Code::Blocks: CompilerFactory Class Reference
CompilerFactory Class Reference
#include <compilerfactory.h>
Static Public Member Functions
static size_t GetCompilersCount ()
static Compiler * GetCompiler (size_t index)
static Compiler * GetCompiler (const wxString &id)
static Compiler * GetCompilerByName (const wxString &title)
static int GetCompilerIndex (const wxString &id)
static int GetCompilerIndex (Compiler *compiler)
static bool IsValidCompilerID (const wxString &id)
static bool CompilerInheritsFrom (const wxString &id, const wxString &from_id)
static bool CompilerInheritsFrom (Compiler *compiler, const wxString &from_id)
static void RegisterCompiler (Compiler *compiler)
Register a supported (builtin) compiler.
static void RegisterUserCompilers ()
Register all user-defined compiler copies.
static Compiler * CreateCompilerCopy (Compiler *compiler, const wxString &newName)
Create a copy of a compiler.
static void RemoveCompiler (Compiler *compiler)
Remove a compiler.
static void UnregisterCompilers ()
Unregister all compilers.
static wxString GetCompilerVersionString (const wxString &Id)
get the version number as string for the compiler with the specified index
static void SaveSettings ()
static void LoadSettings ()
static const wxString & GetDefaultCompilerID ()
static Compiler * GetDefaultCompiler ()
static void SetDefaultCompiler (size_t index)
static void SetDefaultCompiler (const wxString &id)
static void SetDefaultCompiler (Compiler *compiler)
static Compiler * SelectCompilerUI (const wxString &message=_("Select compiler"), const wxString &preselectedID=wxEmptyString)
Static Private Attributes
static CompilersArray Compilers
static Compiler * s_DefaultCompiler = nullptr
Detailed Description
Definition at line 22 of file compilerfactory.h.
Member Function Documentation
CompilerInheritsFrom() [1/2]
bool CompilerFactory::CompilerInheritsFrom (const wxString & id, const wxString & from_id) static
Returns
true if compiler ID id inherits, directly or indirectly, from compiler ID from_id.
Definition at line 100 of file compilerfactory.cpp.
References GetCompiler().
Referenced by Wiz::AppendContainerWithSelectCompilers(), Wizard::FillCompilerControl(), Wiz::FillContainerWithSelectCompilers(), and ScriptBindings::RegisterBindings().
CompilerInheritsFrom() [2/2]
bool CompilerFactory::CompilerInheritsFrom (Compiler * compiler, const wxString & from_id) static
Returns
true if compiler inherits, directly or indirectly, from compiler ID from_id.
Definition at line 105 of file compilerfactory.cpp.
References _T, LogManager::DebugLog(), Manager::Get(), GetCompiler(), Compiler::GetID(), Manager::GetLogManager(), and Compiler::GetParentID().
CreateCompilerCopy()
Compiler * CompilerFactory::CreateCompilerCopy (Compiler * compiler, const wxString & newName) static
Create a copy of a compiler.
Definition at line 163 of file compilerfactory.cpp.
References _T, Compilers, Compiler::CreateCopy(), LogManager::DebugLog(), F(), Manager::Get(), Compiler::GetID(), Manager::GetLogManager(), Compiler::GetName(), wxString::IsEmpty(), Compiler::LoadSettings(), Compiler::m_CompilerIDs, Compiler::m_ID, Compiler::MakeValidID(), RegisterCompiler(), Compiler::ReloadOptions(), wxArrayString::Remove(), Compiler::SetName(), and wxString::wx_str().
Referenced by CompilerOptionsDlg::OnAddCompilerClick(), and RegisterUserCompilers().
GetCompiler() [1/2]
Compiler * CompilerFactory::GetCompiler (size_t index) static
Returns
the compiler by an index.
Definition at line 32 of file compilerfactory.cpp.
References Compilers.
Referenced by NativeParser::AddCompilerDirs(), NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), cbProject::AddFile(), CompilerGCC::AddOutputLine(), Wiz::AppendContainerWithSelectCompilers(), DirectCommands::AreExternalDepsOutdated(), CompilerOptionsDlg::AutoDetectCompiler(), AutoDetectCompilers::AutoDetectCompilers(), CompilerICC::AutoDetectInstallationDir(), CompilerGCC::BuildStateManagement(), cbGetDynamicLinkerPathForTarget(), EditorManager::CollectDefines(), CompilerGCC::CompileFileDefault(), CompilerOptionsDlg::CompilerChanged(), CompilerInheritsFrom(), CompilerOptionsDlg::CompilerOptionsDlg(), CompilerGCC::CompilerValid(), ProjectLoader::ConvertLibraries(), CompilerGCC::DoCleanWithMake(), DebuggerGDB::DoDebug(), CompilerOptionsDlg::DoFillCompilerPrograms(), CompilerOptionsDlg::DoFillCompilerSets(), CompilerOptionsDlg::DoLoadOptions(), CompilerOptionsDlg::DoSaveCompilerDefinition(), CompilerOptionsDlg::DoSaveCompilerPrograms(), CompilerOptionsDlg::DoSaveOptions(), AdvancedCompilerOptionsDlg::EndModal(), ProjectLoader::ExportTargetAsProject(), Wiz::FillComboboxWithCompilers(), Wizard::FillCompilerControl(), ProjectFileOptionsDlg::FillCompilers(), Wiz::FillContainerWithSelectCompilers(), DebuggerManager::FindTargetsDebugger(), CompilerCommandGenerator::GenerateCommandLine(), CompileTargetBase::GenerateTargetFilename(), DirectCommands::GetCompileFileCommand(), Wiz::GetCompilerFromCombobox(), GetCompilerVersionString(), CompilerGCC::GetCurrentCompilerID(), CompilerGCC::GetMakeCommandFor(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), CompileTargetBase::GetStaticLibFilename(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), ProjectLoader::GetValidCompilerID(), CompilerOptionsDlg::GetVarsOwner(), CompilerCommandGenerator::Init(), DirectCommands::IsObjectOutdated(), TemplateManager::NewProjectFromUserTemplate(), CompilerOptionsDlg::OnAddCompilerClick(), CompilerOptionsDlg::OnAdvancedClick(), CompilerGCC::OnCleanFile(), CompilerOptionsDlg::OnEditCompilerClick(), CompilerOptionsDlg::OnFlagsPopup(), CompilerGCC::OnJobEnd(), AutoDetectCompilers::OnMouseMotion(), ProjectOptionsDlg::OnProjectTypeChanged(), AdvancedCompilerOptionsDlg::OnRegexDefaults(), AdvancedCompilerOptionsDlg::OnRegexTest(), CompilerOptionsDlg::OnRemoveCompilerClick(), CompilerOptionsDlg::OnResetCompilerClick(), CompilerOptionsDlg::OnTreeSelectionChange(), CompilerOptionsDlg::OnUpdateUI(), CompilerOptionsDlg::OptionsToText(), CompilerGCC::PreprocessJob(), CompilerGCC::PrintBanner(), ProjectOptionsDlg::ProjectOptionsDlg(), AdvancedCompilerOptionsDlg::ReadCompilerOptions(), MacrosManager::RecalcVars(), RegisterUserCompilers(), ProjectFileOptionsDlg::SaveBuildCommandSelection(), cbProject::SetCompilerID(), SetDefaultCompiler(), ProjectFile::SetObjName(), CompilerGCC::SetupEnvironment(), CompilerGCC::SwitchCompiler(), CompilerOptionsDlg::TextToOptions(), pfDetails::Update(), ProjectFileOptionsDlg::UpdateBuildCommand(), CompilerOptionsDlg::UpdateCompilerForTargets(), CompilerGCC::UseMake(), and AdvancedCompilerOptionsDlg::WriteCompilerOptions().
GetCompiler() [2/2]
Compiler * CompilerFactory::GetCompiler (const wxString & id) static
Returns
the compiler by a name (ID). Not the compiler's title...
Definition at line 42 of file compilerfactory.cpp.
References Compilers, wxString::IsSameAs(), wxString::Lower(), wxString::Replace(), wxEmptyString, and wxT.
GetCompilerByName()
Compiler * CompilerFactory::GetCompilerByName (const wxString & title) static
Returns
the compiler by title.
Definition at line 61 of file compilerfactory.cpp.
References Compilers.
Referenced by ScriptBindings::CompilerFactory_GetCompilerIDByName(), WizCompilerPanel::GetCompilerID(), and WizBuildTargetPanel::GetCompilerID().
GetCompilerIndex() [1/2]
int CompilerFactory::GetCompilerIndex (const wxString & id) static
Returns
the compiler's index from its id. Returns -1 if it doesn't exist.
Definition at line 71 of file compilerfactory.cpp.
References Compilers, wxString::IsSameAs(), wxString::Lower(), wxString::Replace(), wxEmptyString, and wxT.
Referenced by ScriptBindings::CompilerFactory_GetCompilerIndex(), CompilerOptionsDlg::CompilerOptionsDlg(), ProjectFileOptionsDlg::FillCompilers(), Compiler::LoadDefaultOptions(), Compiler::LoadSettings(), CompilerOptionsDlg::OnAddCompilerClick(), CompilerOptionsDlg::OnTreeSelectionChange(), CompilerOptionsDlg::OnUpdateUI(), and Compiler::SaveSettings().
GetCompilerIndex() [2/2]
int CompilerFactory::GetCompilerIndex (Compiler * compiler) static
Returns
the compiler's index. Returns -1 if it doesn't exist.
Definition at line 90 of file compilerfactory.cpp.
References Compilers.
GetCompilersCount()
size_t CompilerFactory::GetCompilersCount () static
Returns
the number of registered compilers.
Definition at line 27 of file compilerfactory.cpp.
References Compilers.
Referenced by Wiz::AppendContainerWithSelectCompilers(), AutoDetectCompilers::AutoDetectCompilers(), CompilerOptionsDlg::DoFillCompilerSets(), Wiz::FillComboboxWithCompilers(), Wizard::FillCompilerControl(), ProjectFileOptionsDlg::FillCompilers(), and Wiz::FillContainerWithSelectCompilers().
GetCompilerVersionString()
wxString CompilerFactory::GetCompilerVersionString (const wxString & Id) static
get the version number as string for the compiler with the specified index
Definition at line 335 of file compilerfactory.cpp.
References GetCompiler().
Referenced by ScriptBindings::RegisterBindings().
GetDefaultCompiler()
Compiler * CompilerFactory::GetDefaultCompiler () static
Definition at line 225 of file compilerfactory.cpp.
References s_DefaultCompiler.
Referenced by NativeParser::AddCompilerDirs(), AutoDetectCompilers::AutoDetectCompilers(), CompilerGCC::CompileFileWithoutProject(), CompilerGCC::CompilerValid(), DebuggerGDB::DoDebug(), Wiz::FillComboboxWithCompilers(), Wiz::FillContainerWithSelectCompilers(), DebuggerManager::FindTargetsDebugger(), CompilerCommandGenerator::GenerateCommandLine(), DirectCommands::GetCompileSingleFileCommand(), CompilerCommandGenerator::Init(), AutoDetectCompilers::OnDefaultClick(), CompilerOptionsDlg::OnSetDefaultCompilerClick(), CompilerOptionsDlg::OnUpdateUI(), and pfDetails::Update().
GetDefaultCompilerID()
const wxString & CompilerFactory::GetDefaultCompilerID () static
Definition at line 216 of file compilerfactory.cpp.
References ParserConsts::empty, Compiler::GetID(), s_DefaultCompiler, and wxEmptyString.
Referenced by NativeParser::AddCompilerPredefinedMacros(), cbProject::cbProject(), CompilerGCC::CheckProject(), CompilerGCC::CompileFileWithoutProject(), CompilerOptionsDlg::CompilerOptionsDlg(), Wizard::FillCompilerControl(), CompilerGCC::GetMakeCommandFor(), Wiz::OnAttach(), CompilerGCC::OnRelease(), ScriptBindings::RegisterBindings(), Wiz::RunProjectWizard(), Wiz::RunTargetWizard(), and Wiz::SetCompilerDefault().
IsValidCompilerID()
static bool CompilerFactory::IsValidCompilerID (const wxString & id) inline static
Returns
true if the specified compiler ID is valid, false if not.
Definition at line 40 of file compilerfactory.h.
References _(), and wxEmptyString.
Referenced by CompilerGCC::GetMakeCommandFor(), and ScriptBindings::RegisterBindings().
LoadSettings()
void CompilerFactory::LoadSettings () static
Definition at line 267 of file compilerfactory.cpp.
References _T, cbEVT_COMPILER_SETTINGS_CHANGED, Compilers, LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), PlaceWindow(), Manager::ProcessEvent(), and wxDialog::ShowModal().
Referenced by CompilerGCC::LoadOptions().
RegisterCompiler()
void CompilerFactory::RegisterCompiler (Compiler * compiler) static
Register a supported (builtin) compiler.
Definition at line 132 of file compilerfactory.cpp.
References Compilers, Compiler::m_Weight, and s_DefaultCompiler.
Referenced by CreateCompilerCopy(), and CompilerGCC::DoRegisterCompilers().
RegisterUserCompilers()
void CompilerFactory::RegisterUserCompilers () static
Register all user-defined compiler copies.
Definition at line 146 of file compilerfactory.cpp.
References _T, CreateCompilerCopy(), ConfigManager::EnumerateSubPaths(), Manager::Get(), GetCompiler(), Manager::GetConfigManager(), wxArrayString::GetCount(), wxString::IsEmpty(), ConfigManager::Read(), and wxEmptyString.
Referenced by CompilerGCC::DoRegisterCompilers().
RemoveCompiler()
void CompilerFactory::RemoveCompiler (Compiler * compiler) static
Remove a compiler.
Definition at line 192 of file compilerfactory.cpp.
References _T, Compilers, LogManager::DebugLog(), ConfigManager::DeleteSubPath(), F(), Manager::Get(), Manager::GetConfigManager(), Compiler::GetID(), Manager::GetLogManager(), Compiler::GetName(), wxString::IsEmpty(), Compiler::m_CompilerIDs, Compiler::m_ParentID, wxArrayString::Remove(), SaveSettings(), and wxString::wx_str().
Referenced by CompilerOptionsDlg::OnRemoveCompilerClick().
SaveSettings()
void CompilerFactory::SaveSettings () static
Definition at line 248 of file compilerfactory.cpp.
References _T, cbEVT_COMPILER_SETTINGS_CHANGED, Compilers, ConfigManager::DeleteSubPath(), Manager::Get(), Manager::GetConfigManager(), and Manager::ProcessEvent().
Referenced by CompilerOptionsDlg::OnApply(), CompilerOptionsDlg::OnResetCompilerClick(), RemoveCompiler(), and CompilerGCC::SaveOptions().
SelectCompilerUI()
Compiler * CompilerFactory::SelectCompilerUI (const wxString & message = _("Select compiler"), const wxString & preselectedID = wxEmptyString) static
Definition at line 298 of file compilerfactory.cpp.
References _(), Compilers, wxSingleChoiceDialog::GetSelection(), wxString::IsEmpty(), wxString::Lower(), PlaceWindow(), s_DefaultCompiler, wxSingleChoiceDialog::SetSelection(), wxSingleChoiceDialog::ShowModal(), and wxID_OK.
Referenced by CompilerOptionsDlg::CompilerOptionsDlg(), ProjectLoader::GetValidCompilerID(), and CompilerOptionsDlg::OnTreeSelectionChange().
SetDefaultCompiler() [1/3]
void CompilerFactory::SetDefaultCompiler (size_t index) static
Definition at line 230 of file compilerfactory.cpp.
References Compilers, and s_DefaultCompiler.
Referenced by CompilerGCC::OnAttach(), AutoDetectCompilers::OnDefaultClick(), CompilerOptionsDlg::OnSetDefaultCompilerClick(), Wiz::RunProjectWizard(), and SetDefaultCompiler().
SetDefaultCompiler() [2/3]
void CompilerFactory::SetDefaultCompiler (const wxString & id) static
Definition at line 236 of file compilerfactory.cpp.
References GetCompiler(), and SetDefaultCompiler().
SetDefaultCompiler() [3/3]
void CompilerFactory::SetDefaultCompiler (Compiler * compiler) static
Definition at line 242 of file compilerfactory.cpp.
References s_DefaultCompiler.
UnregisterCompilers()
void CompilerFactory::UnregisterCompilers () static
Unregister all compilers.
Definition at line 207 of file compilerfactory.cpp.
References Compilers, wxArrayString::Empty(), Compiler::m_CompilerIDs, s_DefaultCompiler, and WX_CLEAR_ARRAY.
Referenced by CompilerOptionsDlg::OnApply(), and CompilerGCC::OnRelease().
Member Data Documentation
Compilers
CompilersArray CompilerFactory::Compilers static private
Definition at line 71 of file compilerfactory.h.
Referenced by CreateCompilerCopy(), GetCompiler(), GetCompilerByName(), GetCompilerIndex(), GetCompilersCount(), LoadSettings(), RegisterCompiler(), RemoveCompiler(), SaveSettings(), SelectCompilerUI(), SetDefaultCompiler(), and UnregisterCompilers().
s_DefaultCompiler
Compiler * CompilerFactory::s_DefaultCompiler = nullptr static private
Definition at line 72 of file compilerfactory.h.
Referenced by GetDefaultCompiler(), GetDefaultCompilerID(), RegisterCompiler(), SelectCompilerUI(), SetDefaultCompiler(), and UnregisterCompilers().
The documentation for this class was generated from the following files:
compilerfactory.h
compilerfactory.cpp