Code::Blocks: CCOptionsDlg Class Reference
CCOptionsDlg Class Reference
#include <ccoptionsdlg.h>
Public Member Functions
CCOptionsDlg (wxWindow *parent, NativeParser *np, CodeCompletion *cc, DocumentationHelper *dh)
virtual ~CCOptionsDlg ()
virtual wxString GetTitle () const
virtual wxString GetBitmapBaseName () const
virtual void OnApply ()
Called when the user chooses to apply the configuration.
virtual void OnCancel ()
Called when the user chooses to cancel the configuration.
Public Member Functions inherited from cbConfigurationPanel
cbConfigurationPanel ()
~cbConfigurationPanel () override
void SetParentDialog (wxWindow *dialog)
Sets the panel's parent dialog.
wxWindow * SetParentDialog ()
Gets the panel's parent dialog.
int cbMessageBox (const wxString &message, const wxString &caption=wxEmptyString, int style=wxOK, wxWindow *parent=NULL, int x=-1, int y=-1)
Call global cbMessageBox with m_parentDialog as parent window when no parent window specified.
Protected Member Functions
void OnChooseColour (wxCommandEvent &event)
void OnCCDelayScroll (wxScrollEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Private Member Functions
void UpdateCCDelayLabel ()
bool ValidateReplacementToken (wxString &from, wxString &to)
Private Attributes
NativeParser * m_NativeParser
CodeCompletion * m_CodeCompletion
ParserBase & m_Parser
DocumentationHelper * m_Documentation
Detailed Description
Definition at line 18 of file ccoptionsdlg.h.
Constructor & Destructor Documentation
CCOptionsDlg()
CCOptionsDlg::CCOptionsDlg (wxWindow * parent, NativeParser * np, CodeCompletion * cc, DocumentationHelper * dh)
Definition at line 89 of file ccoptionsdlg.cpp.
References _T, wxXmlResource::Get(), Manager::Get(), ColourManager::GetColour(), Manager::GetColourManager(), Manager::GetConfigManager(), wxCheckBox::GetValue(), wxXmlResource::LoadPanel(), ConfigManager::Read(), ConfigManager::ReadBool(), ConfigManager::ReadInt(), wxCheckBox::SetValue(), wxSpinCtrl::SetValue(), wxEmptyString, and wxT.
~CCOptionsDlg()
CCOptionsDlg::~CCOptionsDlg () virtual
Definition at line 192 of file ccoptionsdlg.cpp.
Member Function Documentation
GetBitmapBaseName()
virtual wxString CCOptionsDlg::GetBitmapBaseName () const inline virtual
Returns
the panel's bitmap base name. You must supply two bitmaps: <basename>.png and <basename>-off.png...
Implements cbConfigurationPanel.
Definition at line 25 of file ccoptionsdlg.h.
References _T, and OnApply().
GetTitle()
virtual wxString CCOptionsDlg::GetTitle () const inline virtual
Returns
the panel's title.
Implements cbConfigurationPanel.
Definition at line 24 of file ccoptionsdlg.h.
References _().
OnApply()
void CCOptionsDlg::OnApply () virtual
Called when the user chooses to apply the configuration.
Implements cbConfigurationPanel.
Definition at line 196 of file ccoptionsdlg.cpp.
References _T, ParserBase::ClassBrowserOptions(), BrowserOptions::expandNS, ParserOptions::followGlobalIncludes, ParserOptions::followLocalIncludes, Manager::Get(), Manager::GetColourManager(), Manager::GetConfigManager(), m_CodeCompletion, m_Documentation, m_NativeParser, m_Parser, ParserBase::Options(), ParserOptions::parseComplexMacros, ParserOptions::platformCheck, ParserBase::ReadOptions(), DocumentationHelper::RereadOptions(), CodeCompletion::RereadOptions(), NativeParser::RereadParserOptions(), ColourManager::SetColour(), DocumentationHelper::SetEnabled(), BrowserOptions::showInheritance, ParserOptions::storeDocumentation, BrowserOptions::treeMembers, ParserOptions::useSmartSense, ParserOptions::wantPreprocessor, ParserOptions::whileTyping, ConfigManager::Write(), DocumentationHelper::WriteOptions(), ParserBase::WriteOptions(), and wxT.
Referenced by GetBitmapBaseName().
OnCancel()
virtual void CCOptionsDlg::OnCancel () inline virtual
Called when the user chooses to cancel the configuration.
Implements cbConfigurationPanel.
Definition at line 27 of file ccoptionsdlg.h.
References OnCCDelayScroll(), OnChooseColour(), OnUpdateUI(), UpdateCCDelayLabel(), and ValidateReplacementToken().
OnCCDelayScroll()
void CCOptionsDlg::OnCCDelayScroll (wxScrollEvent & event) protected
Definition at line 320 of file ccoptionsdlg.cpp.
References UpdateCCDelayLabel().
Referenced by OnCancel().
OnChooseColour()
void CCOptionsDlg::OnChooseColour (wxCommandEvent & event) protected
Definition at line 305 of file ccoptionsdlg.cpp.
References wxColourData::GetColour(), wxColourDialog::GetColourData(), PlaceWindow(), wxColourData::SetColour(), wxColourDialog::ShowModal(), and wxID_OK.
Referenced by OnCancel().
OnUpdateUI()
void CCOptionsDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 325 of file ccoptionsdlg.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), wxCheckBox::GetValue(), and ConfigManager::ReadBool().
Referenced by OnCancel().
UpdateCCDelayLabel()
void CCOptionsDlg::UpdateCCDelayLabel () private
Definition at line 395 of file ccoptionsdlg.cpp.
References _(), and wxString::Printf().
Referenced by OnCancel(), and OnCCDelayScroll().
ValidateReplacementToken()
bool CCOptionsDlg::ValidateReplacementToken (wxString & from, wxString & to) private
Definition at line 406 of file ccoptionsdlg.cpp.
References _(), _T, cbConfigurationPanel::cbMessageBox(), wxString::Contains(), wxString::IsEmpty(), wxRegEx::Matches(), wxString::Trim(), wxICON_ERROR, wxICON_QUESTION, wxID_YES, and wxYES_NO.
Referenced by OnCancel().
Member Data Documentation
m_CodeCompletion
CodeCompletion* CCOptionsDlg::m_CodeCompletion private
Definition at line 40 of file ccoptionsdlg.h.
Referenced by OnApply().
m_Documentation
DocumentationHelper* CCOptionsDlg::m_Documentation private
Definition at line 42 of file ccoptionsdlg.h.
Referenced by OnApply().
m_NativeParser
NativeParser* CCOptionsDlg::m_NativeParser private
Definition at line 39 of file ccoptionsdlg.h.
Referenced by OnApply().
m_Parser
ParserBase& CCOptionsDlg::m_Parser private
Definition at line 41 of file ccoptionsdlg.h.
Referenced by OnApply().
The documentation for this class was generated from the following files:
ccoptionsdlg.h
ccoptionsdlg.cpp