Code::Blocks: ID Class Reference
ID Class Reference
#include <id.h>
Public Member Functions
ID ()
ID (const wxString &id)
ID (const ID &cpy)
wxString id () const
void set_id (const wxString &s)
bool operator== (const ID &other) const
bool operator== (const wxString &other) const
Private Attributes
wxString p__id
Detailed Description
Definition at line 15 of file id.h.
Constructor & Destructor Documentation
ID() [1/3]
ID::ID () inline
Definition at line 20 of file id.h.
ID() [2/3]
ID::ID (const wxString & id) inline
Definition at line 21 of file id.h.
ID() [3/3]
ID::ID (const ID & cpy) inline explicit
Definition at line 22 of file id.h.
Member Function Documentation
id()
wxString ID::id () const inline
Definition at line 24 of file id.h.
References p__id.
Referenced by operator==().
operator==() [1/2]
bool ID::operator== (const ID & other) const inline
Definition at line 34 of file id.h.
References id().
operator==() [2/2]
bool ID::operator== (const wxString & other) const inline
Definition at line 39 of file id.h.
References id().
set_id()
void ID::set_id (const wxString & s) inline
Definition at line 29 of file id.h.
Member Data Documentation
p__id
wxString ID::p__id private
Definition at line 17 of file id.h.
Referenced by id().
The documentation for this class was generated from the following file:
id.h