Code::Blocks: TextCtrlLogger Class Reference
TextCtrlLogger Class Reference
a logger which prints messages to a wxTextCtrl
#include <loggers.h>
Public Member Functions
TextCtrlLogger (bool fixedPitchFont=false)
~TextCtrlLogger ()
virtual void CopyContentsToClipboard (bool selectionOnly=false)
virtual void UpdateSettings ()
virtual void Append (const wxString &msg, Logger::level lv=info)
virtual void Clear ()
virtual wxWindow * CreateControl (wxWindow *parent)
virtual bool GetWrapMode () const
virtual void ToggleWrapMode ()
virtual bool HasFeature (Feature::Enum feature) const
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Protected Attributes
wxTextCtrl * control
bool fixed
wxTextAttr style [num_levels]
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Detailed Description
a logger which prints messages to a wxTextCtrl
Definition at line 90 of file loggers.h.
Constructor & Destructor Documentation
TextCtrlLogger()
TextCtrlLogger::TextCtrlLogger (bool fixedPitchFont = false)
Definition at line 50 of file loggers.cpp.
~TextCtrlLogger()
TextCtrlLogger::~TextCtrlLogger ()
Definition at line 55 of file loggers.cpp.
References control.
Member Function Documentation
Append()
void TextCtrlLogger::Append (const wxString & msg, Logger::level lv = info) virtual
Implements Logger.
Reimplemented in TimestampTextCtrlLogger.
Definition at line 131 of file loggers.cpp.
References Logger::caption, control, Logger::info, Logger::spacer, and style.
Clear()
void TextCtrlLogger::Clear () virtual
Reimplemented from Logger.
Definition at line 157 of file loggers.cpp.
References control.
Referenced by cbDebuggerPlugin::ClearLog(), and cbDebuggerPlugin::ShowLog().
CopyContentsToClipboard()
void TextCtrlLogger::CopyContentsToClipboard (bool selectionOnly = false) virtual
Definition at line 60 of file loggers.cpp.
References control.
CreateControl()
wxWindow * TextCtrlLogger::CreateControl (wxWindow * parent) virtual
Reimplemented in DebugTextCtrlLogger, and BuildLogger.
Definition at line 163 of file loggers.cpp.
References control.
Referenced by BuildLogger::CreateControl(), and DebugTextCtrlLogger::CreateTextCtrl().
GetWrapMode()
bool TextCtrlLogger::GetWrapMode () const virtual
Reimplemented from Logger.
Definition at line 185 of file loggers.cpp.
References control.
HasFeature()
bool TextCtrlLogger::HasFeature (Feature::Enum feature) const virtual
Definition at line 171 of file loggers.cpp.
References Logger::Feature::CanClear, Logger::Feature::CanCopy, control, and Logger::Feature::IsWrappable.
Referenced by ToggleWrapMode().
ToggleWrapMode()
void TextCtrlLogger::ToggleWrapMode () virtual
Definition at line 194 of file loggers.cpp.
References control, HasFeature(), and Logger::Feature::IsWrappable.
Referenced by InfoPane::OnWrapMode().
UpdateSettings()
void TextCtrlLogger::UpdateSettings () virtual
Reimplemented from Logger.
Reimplemented in BuildLogger.
Definition at line 69 of file loggers.cpp.
References Logger::caption, control, Logger::critical, Logger::error, fixed, Manager::Get(), ColourManager::GetColour(), Manager::GetColourManager(), Manager::GetConfigManager(), Logger::num_levels, ConfigManager::ReadInt(), Logger::spacer, style, Logger::success, and Logger::warning.
Referenced by BuildLogger::UpdateSettings().
Member Data Documentation
control
wxTextCtrl* TextCtrlLogger::control protected
Definition at line 94 of file loggers.h.
Referenced by Append(), TimestampTextCtrlLogger::Append(), Clear(), CopyContentsToClipboard(), CreateControl(), GetWrapMode(), HasFeature(), ToggleWrapMode(), UpdateSettings(), and ~TextCtrlLogger().
fixed
bool TextCtrlLogger::fixed protected
Definition at line 95 of file loggers.h.
Referenced by UpdateSettings().
style
wxTextAttr TextCtrlLogger::style[num_levels] protected
Definition at line 96 of file loggers.h.
Referenced by Append(), TimestampTextCtrlLogger::Append(), and UpdateSettings().
The documentation for this class was generated from the following files:
loggers.h
loggers.cpp