Code::Blocks: CompilerMINGWGenerator Class Reference
CompilerMINGWGenerator Class Reference
#include <compilerMINGWgenerator.h>
Public Member Functions
CompilerMINGWGenerator ()
virtual ~CompilerMINGWGenerator ()
Public Member Functions inherited from CompilerCommandGenerator
CompilerCommandGenerator ()
virtual ~CompilerCommandGenerator ()
virtual void Init (cbProject *project)
Initialize for use with the specified project.
virtual void GenerateCommandLine (wxString &macro, ProjectBuildTarget *target, ProjectFile *pf, const wxString &file, const wxString &object, const wxString &flat_object, const wxString &deps)
Get the command line to compile/link the specific file.
virtual const wxArrayString & GetCompilerSearchDirs (ProjectBuildTarget *target)
Get the full include dirs used in the actual command line.
virtual const wxArrayString & GetLinkerSearchDirs (ProjectBuildTarget *target)
Get the full linker dirs used in the actual command line.
Protected Member Functions
virtual wxString SetupIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup compiler include dirs for build target.
Protected Member Functions inherited from CompilerCommandGenerator
virtual void DoBuildScripts (cbProject *project, CompileTargetBase *target, const wxString &funcName)
Apply pre-build scripts for base.
virtual wxString GetOrderedOptions (const ProjectBuildTarget *target, OptionsRelationType rel, const wxString &project_options, const wxString &target_options)
Arrange order of options.
virtual wxArrayString GetOrderedOptions (const ProjectBuildTarget *target, OptionsRelationType rel, const wxArrayString &project_options, const wxArrayString &target_options)
Arrange order of options.
virtual wxArrayString GetOrderedIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxArrayString GetOrderedLibrariesDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxArrayString GetOrderedResourceIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxString SetupOutputFilenames (Compiler *compiler, ProjectBuildTarget *target)
Setup output filename for build target.
virtual wxString SetupLibrariesDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup linker include dirs for build target.
virtual wxString SetupResourceIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup resource compiler include dirs for build target.
virtual wxString SetupCompilerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup compiler flags for build target.
virtual wxString SetupLinkerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup linker flags for build target.
virtual wxString SetupLinkLibraries (Compiler *compiler, ProjectBuildTarget *target)
Setup link libraries for build target.
virtual wxString SetupResourceCompilerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup resource compiler flags for build target.
virtual wxString FixupLinkLibraries (Compiler *compiler, const wxString &lib)
Fix library name based on advanced compiler settings.
virtual void FixPathSeparators (Compiler *compiler, wxString &inAndOut)
Private Attributes
wxString m_VerStr
Additional Inherited Members
Static Protected Member Functions inherited from CompilerCommandGenerator
static wxString MakeOptString (const wxArrayString &arr, const wxString &opt, wxChar separator=_T(' '))
static wxString PathSearch (const wxArrayString &arr, const wxString &filename)
Protected Attributes inherited from CompilerCommandGenerator
OptionsMap m_Output
output filenames, per-target
OptionsMap m_StaticOutput
static output filenames, per-target
OptionsMap m_DefOutput
def output filenames, per-target
OptionsMap m_Inc
compiler 'include' dirs, per-target
OptionsMap m_Lib
linker 'include' dirs, per-target
OptionsMap m_RC
resource compiler 'include' dirs, per-target
OptionsMap m_CFlags
compiler flags, per-target
OptionsMap m_RCFlags
resource compiler flags, per-target
OptionsMap m_LDFlags
linker flags, per-target
OptionsMap m_LDAdd
link libraries, per-target
wxString m_PrjIncPath
directive to add the project's top-level path in compiler search dirs (ready for the command line)
SearchDirsMap m_CompilerSearchDirs
array of final compiler search dirs, per-target
SearchDirsMap m_LinkerSearchDirs
array of final linker search dirs, per-target
Constructor & Destructor Documentation
CompilerMINGWGenerator::CompilerMINGWGenerator ()
References m_VerStr.
CompilerMINGWGenerator::~CompilerMINGWGenerator () virtual
Member Function Documentation
wxString CompilerMINGWGenerator::SetupIncludeDirs (Compiler * compiler, ProjectBuildTarget * target) protected virtual
Setup compiler include dirs for build target.
Reimplemented from CompilerCommandGenerator.
References ProjectFile::compile, FileTypeOf(), ftHeader, cbProject::GetFilesList(), cbProject::GetModeForPCH(), CompileTargetBase::GetObjectOutput(), ProjectFile::GetObjName(), ProjectBuildTarget::GetParentProject(), Compiler::GetSwitches(), Compiler::GetVersionString(), CompilerSwitches::includeDirs, m_VerStr, pchObjectDir, QuoteStringIfNeeded(), ProjectFile::relativeFilename, HTMLTags::sep, CompilerCommandGenerator::SetupIncludeDirs(), and CompilerSwitches::UseFlatObjects.
Member Data Documentation
wxString CompilerMINGWGenerator::m_VerStr private
Referenced by CompilerMINGWGenerator(), and SetupIncludeDirs().
The documentation for this class was generated from the following files:
compilerMINGWgenerator.h
compilerMINGWgenerator.cpp