Code::Blocks: EditArrayFileDlg Class Reference
EditArrayFileDlg Class Reference
#include <editarrayfiledlg.h>
Public Member Functions
EditArrayFileDlg (wxWindow *parent, wxArrayString &array, bool useRelativePaths=false, const wxString &basePath=_T(""))
virtual ~EditArrayFileDlg ()
EditArrayFileDlg & operator= (const EditArrayFileDlg &)
virtual void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void OnAdd (wxCommandEvent &event)
void OnEdit (wxCommandEvent &event)
void OnDelete (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Protected Attributes
wxArrayString & m_Array
bool m_UseRelativePaths
wxString m_BasePath
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 13 of file editarrayfiledlg.h.
Constructor & Destructor Documentation
EditArrayFileDlg()
EditArrayFileDlg::EditArrayFileDlg (wxWindow * parent, wxArrayString & array, bool useRelativePaths = false, const wxString & basePath = _T(""))
Definition at line 33 of file editarrayfiledlg.cpp.
~EditArrayFileDlg()
EditArrayFileDlg::~EditArrayFileDlg () virtual
Definition at line 57 of file editarrayfiledlg.cpp.
Member Function Documentation
EndModal()
void EditArrayFileDlg::EndModal (int retCode) virtual
Definition at line 62 of file editarrayfiledlg.cpp.
References ScriptBindings::EndModal(), and m_Array.
OnAdd()
void EditArrayFileDlg::OnAdd (wxCommandEvent & event) protected
Definition at line 78 of file editarrayfiledlg.cpp.
References FileFilters::GetFilterAll(), m_BasePath, m_UseRelativePaths, and PlaceWindow().
OnDelete()
void EditArrayFileDlg::OnDelete (wxCommandEvent & event) protected
Definition at line 115 of file editarrayfiledlg.cpp.
References cbMessageBox().
OnEdit()
void EditArrayFileDlg::OnEdit (wxCommandEvent & event) protected
Definition at line 96 of file editarrayfiledlg.cpp.
References FileFilters::GetFilterAll(), m_BasePath, m_UseRelativePaths, and PlaceWindow().
OnUpdateUI()
void EditArrayFileDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 124 of file editarrayfiledlg.cpp.
operator=()
EditArrayFileDlg& EditArrayFileDlg::operator= (const EditArrayFileDlg &) inline
Definition at line 18 of file editarrayfiledlg.h.
References ScriptBindings::EndModal().
Member Data Documentation
m_Array
wxArrayString& EditArrayFileDlg::m_Array protected
Definition at line 25 of file editarrayfiledlg.h.
Referenced by EndModal().
m_BasePath
wxString EditArrayFileDlg::m_BasePath protected
Definition at line 27 of file editarrayfiledlg.h.
Referenced by OnAdd(), and OnEdit().
m_UseRelativePaths
bool EditArrayFileDlg::m_UseRelativePaths protected
Definition at line 26 of file editarrayfiledlg.h.
Referenced by OnAdd(), and OnEdit().
The documentation for this class was generated from the following files:
editarrayfiledlg.h
editarrayfiledlg.cpp