Code::Blocks: EditToolDlg Class Reference
EditToolDlg Class Reference
#include <edittooldlg.h>
Public Member Functions
EditToolDlg (wxWindow *parent, cbTool *tool)
~EditToolDlg ()
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void OnUpdateUI (wxUpdateUIEvent &event)
void OnBrowseCommand (wxCommandEvent &event)
void OnBrowseDir (wxCommandEvent &event)
Private Attributes
cbTool * m_Tool
the tool we are editing (setting up)
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
EditToolDlg::EditToolDlg (wxWindow * parent, cbTool * tool)
References cbThrow.
EditToolDlg::~EditToolDlg ()
Member Function Documentation
void EditToolDlg::EndModal (int retCode)
References ScriptBindings::EndModal(), m_Tool, cbTool::SetCommand(), cbTool::SetLaunchOption(), cbTool::SetName(), cbTool::SetParams(), and cbTool::SetWorkingDir().
void EditToolDlg::OnBrowseCommand (wxCommandEvent & event) private
void EditToolDlg::OnBrowseDir (wxCommandEvent & event) private
References ChooseDirectory().
void EditToolDlg::OnUpdateUI (wxUpdateUIEvent & event) private
Member Data Documentation
cbTool* EditToolDlg::m_Tool private
the tool we are editing (setting up)
Referenced by EndModal().
The documentation for this class was generated from the following files:
edittooldlg.h
edittooldlg.cpp