Code::Blocks: ConfigManager Class Reference
ConfigManager Class Reference
#include <configmanager.h>
Public Member Functions
wxString GetPath () const
void SetPath (const wxString &strPath)
wxArrayString EnumerateSubPaths (const wxString &path)
wxArrayString EnumerateKeys (const wxString &path)
void DeleteSubPath (const wxString &strPath)
void Clear ()
void Delete ()
void DeleteAll ()
void Flush ()
void Write (const wxString &name, const wxString &value, bool ignoreEmpty=false)
wxString Read (const wxString &key, const wxString &defaultVal=wxEmptyString)
bool Read (const wxString &key, wxString *str)
void Write (const wxString &key, const char *str)
void Write (const wxString &name, int value)
bool Read (const wxString &name, int *value)
int ReadInt (const wxString &name, int defaultVal=0)
void Write (const wxString &name, bool value)
bool Read (const wxString &name, bool *value)
bool ReadBool (const wxString &name, bool defaultVal=false)
void Write (const wxString &name, double value)
bool Read (const wxString &name, double *value)
double ReadDouble (const wxString &name, double defaultVal=0.0f)
bool Exists (const wxString &name)
void Set (const wxString &name)
void UnSet (const wxString &name)
void Write (const wxString &name, const wxArrayString &as)
void Read (const wxString &name, wxArrayString *as)
wxArrayString ReadArrayString (const wxString &name)
void WriteBinary (const wxString &name, const wxString &source)
void WriteBinary (const wxString &name, void *ptr, size_t len)
wxString ReadBinary (const wxString &name)
void Write (const wxString &name, const wxColour &c)
bool Read (const wxString &name, wxColour *value)
wxColour ReadColour (const wxString &name, const wxColour &defaultVal= *wxBLACK)
void Write (const wxString &name, const ISerializable &object)
bool Read (const wxString &name, ISerializable *object)
void Write (const wxString &name, const ConfigManagerContainer::StringToStringMap &map)
void Read (const wxString &name, ConfigManagerContainer::StringToStringMap *map)
ConfigManagerContainer::StringToStringMap ReadSSMap (const wxString &name)
void Write (const wxString &name, const ConfigManagerContainer::IntToStringMap &map)
void Read (const wxString &name, ConfigManagerContainer::IntToStringMap *map)
ConfigManagerContainer::IntToStringMap ReadISMap (const wxString &name)
void Write (const wxString &name, const ConfigManagerContainer::StringSet &set)
void Read (const wxString &name, ConfigManagerContainer::StringSet *map)
ConfigManagerContainer::StringSet ReadSSet (const wxString &name)
void Write (const wxString &name, const ConfigManagerContainer::SerializableObjectMap *map)
template<typename T >
void Read (const wxString &name, std::map< wxString, T *> *map)
Static Public Member Functions
static wxString LocateDataFile (const wxString &filename, int search_dirs=sdAllKnown)
Locate a file in an installation- and platform-independent way.
static wxString GetFolder (SearchDirs dir)
Access one of Code::Blocks' folders.
static wxString GetHomeFolder ()
static wxString GetConfigFolder ()
static wxString GetPluginsFolder (bool global=true)
static wxString GetScriptsFolder (bool global=true)
static wxString GetDataFolder (bool global=true)
static wxString GetExecutableFolder ()
static wxString GetTempFolder ()
static wxString GetProxy ()
static wxString GetRevisionString ()
static unsigned int GetRevisionNumber ()
static wxString GetSvnDate ()
static wxString ReadDataPath ()
static wxString ReadAppPath ()
Static Protected Member Functions
static bool SetUserDataFolder (const wxString &user_data_path)
static wxString GetUserDataFolder ()
Private Member Functions
ConfigManager (TiXmlElement *r)
TiXmlElement * AssertPath (wxString &path)
TiXmlElement * GetUniqElement (TiXmlElement *p, const wxString &q)
void SetNodeText (TiXmlElement *n, const TiXmlText &t)
void Collapse (wxString &str) const
wxString InvalidNameMessage (const wxString &what, const wxString &sub, TiXmlElement *localPath) const
Static Private Member Functions
static void InitPaths ()
static void MigrateFolders ()
Private Attributes
TiXmlDocument * doc
TiXmlElement * root
TiXmlElement * pathNode
Static Private Attributes
static wxString config_folder
static wxString home_folder
static wxString data_path_user
static wxString data_path_global
static wxString app_path
static wxString temp_folder
static wxString alternate_user_data_path
static bool has_alternate_user_data_path =false
Friends
class CfgMgrBldr
class CodeBlocksApp
Detailed Description
Definition at line 94 of file configmanager.h.
Constructor & Destructor Documentation
ConfigManager()
ConfigManager::ConfigManager (TiXmlElement * r) private
Definition at line 624 of file configmanager.cpp.
Member Function Documentation
AssertPath()
TiXmlElement * ConfigManager::AssertPath (wxString & path) private
Definition at line 674 of file configmanager.cpp.
References _T, wxString::AfterFirst(), wxString::BeforeFirst(), cbThrow, cbU2C(), Collapse(), CfgMgrConsts::dotDot, wxString::find(), wxString::find_first_of(), wxString::GetChar(), InvalidNameMessage(), wxString::IsEmpty(), wxString::IsSameAs(), wxString::Mid(), wxString::npos, pathNode, root, to_lower(), and to_upper().
Referenced by EnumerateKeys(), EnumerateSubPaths(), Exists(), Read(), ReadBinary(), Set(), SetPath(), UnSet(), Write(), and WriteBinary().
Clear()
void ConfigManager::Clear ()
Definition at line 731 of file configmanager.cpp.
References root.
Collapse()
void ConfigManager::Collapse (wxString & str) const inline private
Definition at line 140 of file configmanager.cpp.
References _T, wxString::c_str(), and wxString::Truncate().
Referenced by AssertPath(), and DeleteSubPath().
Delete()
void ConfigManager::Delete ()
Definition at line 736 of file configmanager.cpp.
References cbC2U(), CfgMgrBldr::cs, doc, Mgr< CfgMgrBldr >::Get(), CfgMgrBldr::namespaces, and root.
Referenced by UserVariableManager::Migrate().
DeleteAll()
void ConfigManager::DeleteAll ()
Definition at line 752 of file configmanager.cpp.
References _T, cbC2U(), cbThrow, CfgMgrBldr::cs, doc, Mgr< CfgMgrBldr >::Get(), wxString::IsSameAs(), CfgMgrBldr::namespaces, and root.
DeleteSubPath()
void ConfigManager::DeleteSubPath (const wxString & strPath)
Definition at line 1194 of file configmanager.cpp.
References _T, wxString::AfterFirst(), wxString::BeforeFirst(), cbC2U(), cbMessageBox(), cbU2C(), Collapse(), doc, wxString::find(), wxString::find_first_of(), wxString::IsEmpty(), wxString::IsSameAs(), wxString::Last(), wxString::npos, pathNode, wxString::RemoveLast(), root, and to_lower().
Referenced by RecentItemsList::ClearHistory(), ScriptingSettingsDlg::EndModal(), EditorColourSet::Load(), EditorConfigurationDlg::OnDeleteColourTheme(), DebuggerSettingsDlg::OnOK(), EditorConfigurationDlg::OnRenameColourTheme(), CompilerFactory::RemoveCompiler(), EditorColourSet::Reset(), FilesGroupsAndMasks::Save(), EditorColourSet::Save(), CompilerFactory::SaveSettings(), Compiler::SaveSettings(), ToolsManager::SaveTools(), and MainFrame::SaveWindowState().
EnumerateKeys()
wxArrayString ConfigManager::EnumerateKeys (const wxString & path)
Definition at line 1257 of file configmanager.cpp.
References _T, wxArrayString::Add(), AssertPath(), and cbC2U().
Referenced by ScriptingSettingsDlg::FillScripts(), ColourManager::Load(), GetUserVariableDialog::Load(), Compiler::LoadSettings(), UserVariableManager::Migrate(), and MainFrame::RunStartupScripts().
EnumerateSubPaths()
wxArrayString ConfigManager::EnumerateSubPaths (const wxString & path)
Definition at line 1171 of file configmanager.cpp.
References _T, wxArrayString::Add(), AssertPath(), and cbC2U().
Referenced by FilesGroupsAndMasks::Load(), GetUserVariableDialog::Load(), Compiler::LoadSettings(), EditorConfigurationDlg::LoadThemes(), ToolsManager::LoadTools(), MainFrame::LoadWindowState(), UserVariableManager::Migrate(), DebuggerManager::NewConfig(), DebuggerManager::ProcessSettings(), CompilerFactory::RegisterUserCompilers(), ToolsManager::SaveTools(), and MainFrame::SaveWindowState().
Exists()
bool ConfigManager::Exists (const wxString & name)
Definition at line 1066 of file configmanager.cpp.
References AssertPath(), and cbU2C().
Referenced by AutoDetectCompilers::AutoDetectCompilers(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), Compiler::EvalXMLCondition(), FindReplaceDlg::FindReplaceDlg(), AnnoyingDialog::Init(), EditorColourSet::Load(), Compiler::LoadDefaultOptions(), Compiler::LoadSettings(), UserVariableManager::Migrate(), and UsrGlblMgrEditDialog::UsrGlblMgrEditDialog().
Flush()
void ConfigManager::Flush ()
Definition at line 768 of file configmanager.cpp.
References CfgMgrBldr::cs, CfgMgrBldr::Flush(), and Mgr< CfgMgrBldr >::Get().
Referenced by MainFrame::OnFileSaveAll().
GetConfigFolder()
static wxString ConfigManager::GetConfigFolder () inline static
Definition at line 172 of file configmanager.h.
References sdConfig.
Referenced by cbWorkspace::cbWorkspace(), CfgMgrBldr::CfgMgrBldr(), PersonalityManager::GetPersonalitiesList(), TemplateManager::LoadUserTemplates(), TemplateManager::NewProjectFromUserTemplate(), and TemplateManager::SaveUserTemplate().
GetDataFolder()
static wxString ConfigManager::GetDataFolder (bool global = true) inline static
Definition at line 175 of file configmanager.h.
References sdDataGlobal, and sdDataUser.
Referenced by BreakpointsDlg::BreakpointsDlg(), MainFrame::CreateMenubar(), FindReplace::CreateSearchLog(), MainFrame::CreateToolbars(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), DebuggerManager::GetLogger(), InfoPane::InfoPane(), CodeBlocksApp::InitLocale(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), EnvironmentSettingsDlg::LoadListbookImages(), EditorConfigurationDlg::LoadListbookImages(), EditorManager::MarkReadOnly(), NativeParser::NativeParser(), CompilerGCC::OnAttach(), CompilerOptionsDlg::OnResetCompilerClick(), MacrosManager::Reset(), ScopeDialog::ScopeDialog(), and MainFrame::ShowTips().
GetExecutableFolder()
static wxString ConfigManager::GetExecutableFolder () inline static
Definition at line 176 of file configmanager.h.
References sdBase.
Referenced by CompilerGDC::AutoDetectInstallationDir(), CompilerGNUFortran::AutoDetectInstallationDir(), CompilerG95::AutoDetectInstallationDir(), CompilerMINGW::AutoDetectInstallationDir(), cbDetectDebuggerExecutable(), ToolsManager::Execute(), MacrosManager::Reset(), CompilerGCC::Run(), and CompilerGCC::RunSingleFile().
GetFolder()
wxString ConfigManager::GetFolder (SearchDirs dir) static
Access one of Code::Blocks' folders.
Parameters
dir The directory to return.
Definition at line 487 of file configmanager.cpp.
References _T, app_path, config_folder, data_path_global, data_path_user, home_folder, sdAllGlobal, sdAllKnown, sdAllUser, sdBase, sdConfig, sdCurrent, sdDataGlobal, sdDataUser, sdHome, sdPath, sdPluginsGlobal, sdPluginsUser, sdScriptsGlobal, sdScriptsUser, sdTemp, temp_folder, wxEmptyString, and wxGetCwd().
Referenced by Wiz::AddWizard(), NewFromTemplateDlg::BuildListFor(), Wiz::CopyFiles(), CompilerGCC::DoRegisterCompilers(), CompilerOptionsDlg::DoSaveCompilerDefinition(), NewFromTemplateDlg::EditScript(), Wiz::FindTemplateFile(), EditorColourSet::GetSampleCode(), PluginManager::InstallPlugin(), Wiz::Launch(), EditorColourSet::LoadAvailableSets(), Wiz::OnAttach(), ScriptingSettingsDlg::OnBrowse(), NewFromTemplateDlg::OnDiscardScript(), NewFromTemplateDlg::OnHelp(), NewFromTemplateDlg::OnListRightClick(), PluginsConfigurationDlg::PluginsConfigurationDlg(), and ScriptBindings::Register_Globals().
GetHomeFolder()
static wxString ConfigManager::GetHomeFolder () inline static
Definition at line 171 of file configmanager.h.
References sdHome.
Referenced by CrashHandlerSaveEditorFiles().
GetPath()
wxString ConfigManager::GetPath () const
Definition at line 639 of file configmanager.cpp.
References _T, wxString::Alloc(), cbC2U(), pathNode, wxString::Prepend(), and root.
GetPluginsFolder()
static wxString ConfigManager::GetPluginsFolder (bool global = true) inline static
Definition at line 173 of file configmanager.h.
References sdPluginsGlobal, and sdPluginsUser.
Referenced by MacrosManager::Reset(), and MainFrame::ScanForPlugins().
GetProxy()
wxString ConfigManager::GetProxy () static
Definition at line 481 of file configmanager.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), and Read().
Referenced by URLLoader::operator()(), and CfgMgrBldr::SwitchToR().
GetRevisionNumber()
unsigned int ConfigManager::GetRevisionNumber () static
Definition at line 31 of file configmanager-revision.cpp.
Referenced by cbException::ShowErrorMessage(), and CfgMgrBldr::SwitchTo().
GetRevisionString()
wxString ConfigManager::GetRevisionString () static
Definition at line 24 of file configmanager-revision.cpp.
Referenced by cbSplashScreen::DrawReleaseInfo().
GetScriptsFolder()
static wxString ConfigManager::GetScriptsFolder (bool global = true) inline static
Definition at line 174 of file configmanager.h.
References sdScriptsGlobal, and sdScriptsUser.
GetSvnDate()
wxString ConfigManager::GetSvnDate () static
Definition at line 36 of file configmanager-revision.cpp.
Referenced by StartHerePage::StartHerePage().
GetTempFolder()
static wxString ConfigManager::GetTempFolder () inline static
Definition at line 177 of file configmanager.h.
References sdTemp.
Referenced by CodeBlocksApp::OnInit().
GetUniqElement()
TiXmlElement * ConfigManager::GetUniqElement (TiXmlElement * p, const wxString & q) private
Definition at line 779 of file configmanager.cpp.
References cbU2C().
Referenced by Set(), UnSet(), Write(), and WriteBinary().
GetUserDataFolder()
wxString ConfigManager::GetUserDataFolder () inline static protected
Definition at line 545 of file configmanager.cpp.
References _T, wxString::Format(), wxString::FromUTF8(), has_alternate_user_data_path, and NULL.
Referenced by CfgMgrBldr::FindConfigFile(), and InitPaths().
InitPaths()
void ConfigManager::InitPaths () static private
Definition at line 1483 of file configmanager.cpp.
References _(), _T, app_path, wxString::append(), CreateDir(), CreateDirRecursively(), data_path_global, wxString::FromUTF8(), wxStandardPaths::Get(), GetUserDataFolder(), has_alternate_user_data_path, wxString::IsEmpty(), NULL, UnixFilename(), wxDirExists(), wxGetUserId(), and wxIsPlatform64Bit().
InvalidNameMessage()
wxString ConfigManager::InvalidNameMessage (const wxString & what, const wxString & sub, TiXmlElement * localPath) const private
Definition at line 661 of file configmanager.cpp.
References _T, wxString::c_str(), cbC2U(), wxString::Printf(), and root.
Referenced by AssertPath().
LocateDataFile()
wxString ConfigManager::LocateDataFile (const wxString & filename, int search_dirs = sdAllKnown) static
Locate a file in an installation- and platform-independent way.
You should always use this function if you are looking for "some arbitrary file that belongs to Code::Blocks", as it works across platforms without any additional effort from your side, and it has some builtin redundancy.
So, code that looked like this in the old days:
wxString some_file = ConfigManager::GetScriptsFolder() + wxFILE_SEP_PATH + _T("startup.script");
should be converted to this:
wxString some_file = ConfigManager::LocateDataFile(_T("startup.script"), sdScriptsUser | sdScriptsGlobal);
This would try to locate the file named "startup.script" in the global and also in the user's scripts folders.
Note
User's dirs always have precedence over global dirs.
Parameters
filename name of the file to search for
search_dirs A bit-mask of the folders to include in the search.
Definition at line 579 of file configmanager.cpp.
References _T, wxPathList::Add(), wxPathList::AddEnvList(), wxPathList::FindValidPath(), sdBase, sdConfig, sdCurrent, sdDataGlobal, sdDataUser, sdHome, sdPath, sdPluginsGlobal, sdPluginsUser, sdScriptsGlobal, sdScriptsUser, sdTemp, and wxGetCwd().
Referenced by CompilerSettingsDlg::AddPluginPanels(), EnvironmentSettingsDlg::AddPluginPanels(), EditorConfigurationDlg::AddPluginPanels(), PluginManager::ExportPlugin(), GDB_driver::InitializeScripting(), Compiler::LoadDefaultOptions(), Compiler::LoadRegExArray(), Manager::LoadResource(), ScriptingManager::LoadScript(), CodeBlocksApp::OnInit(), ScriptingManager::OnScriptMenu(), PluginManager::ReadExtraFilesFromManifestFile(), PluginManager::ReadManifestFile(), ScriptBindings::Register_Globals(), Compiler::ReloadOptions(), MainFrame::RunStartupScripts(), ScriptBindings::ShowDialog(), and PluginManager::UninstallPlugin().
MigrateFolders()
void ConfigManager::MigrateFolders () static private
Definition at line 1546 of file configmanager.cpp.
References _(), _T, cbMessageBox(), CreateDirRecursively(), F(), wxString::FromUTF8(), wxStandardPaths::Get(), wxStandardPaths::GetUserDataDir(), NULL, wxString::wx_str(), wxDirExists(), wxICON_ERROR, wxICON_INFORMATION, wxRenameFile(), and wxRmdir().
Referenced by CfgMgrBldr::CfgMgrBldr().
Read() [1/12]
wxString ConfigManager::Read (const wxString & key, const wxString & defaultVal = wxEmptyString)
Definition at line 841 of file configmanager.cpp.
References CfgMgrConsts::app_path, app_path, CfgMgrConsts::data_path, data_path_global, and wxString::IsSameAs().
Referenced by cbAuiNotebook::cbAuiNotebook(), CCOptionsDlg::CCOptionsDlg(), EditorConfigurationDlg::ChangeTheme(), CodeBlocksApp::CheckVersion(), ScriptBindings::ConfigManager_Read(), UserVariableManager::Configure(), EncodingDetector::DetectEncoding(), DisassemblyDlg::DisassemblyDlg(), Associations::DoClearAssociation(), MainFrame::DoOnFileOpen(), CompilerGCC::DoRunQueue(), Associations::DoSetAssociation(), EditorConfigurationDlg::EditorConfigurationDlg(), CompilerSettingsDlg::EndModal(), EnvironmentSettingsDlg::EndModal(), EditorConfigurationDlg::EndModal(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), Compiler::EvalXMLCondition(), ToolsManager::Execute(), ParserCommon::FileType(), FindReplaceDlg::FillComboWithLastValues(), ScriptingSettingsDlg::FillScripts(), FindReplaceDlg::FindReplaceDlg(), ProjectManager::GetDefaultPath(), GetProxy(), cbDebuggerCommonConfig::GetValueTooltipFont(), CodeBlocksApp::InitLocale(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), FilesGroupsAndMasks::Load(), GetUserVariableDialog::Load(), EditorColourSet::Load(), PluginManager::LoadAllPlugins(), Compiler::LoadDefaultOptions(), Compiler::LoadSettings(), EditorConfigurationDlg::LoadThemes(), ToolsManager::LoadTools(), MainFrame::LoadWindowState(), MainFrame::MainFrame(), UserVariableManager::Migrate(), EditorManager::New(), TemplateManager::NewProjectFromUserTemplate(), ScriptConsole::OnbtnLoadClick(), PluginsConfigurationDlg::OnExport(), DebugLogPanel::OnLoadFile(), MainFrame::OnNotebookDoubleClick(), MainFrame::OnViewLayoutSave(), EditorManager::OpenContainingFolder(), OpenContainingFolderData::OpenContainingFolderData(), DebuggerManager::ProcessSettings(), ConfigManagerWrapper::Read(), ReadActiveDebuggerConfig(), ReadArrayString(), ReadBool(), ReadColour(), ReadDouble(), ReadInt(), ReadISMap(), ReadSSet(), ReadSSMap(), ScriptingManager::RefreshTrusts(), CompilerFactory::RegisterUserCompilers(), FindReplace::ReplaceInFiles(), CodeCompletion::RereadOptions(), CompilerGCC::Run(), cbDebuggerPlugin::RunNixConsole(), CompilerGCC::RunSingleFile(), MainFrame::RunStartupScripts(), cbEditor::SaveAs(), PluginManager::SetupLocaleDomain(), CompilerMINGW::SetVersionString(), WizCompilerPanel::WizCompilerPanel(), and WizGenericSelectPathPanel::WizGenericSelectPathPanel().
Read() [2/12]
bool ConfigManager::Read (const wxString & key, wxString * str)
Definition at line 856 of file configmanager.cpp.
References CfgMgrConsts::app_path, app_path, AssertPath(), wxString::assign(), cbC2U(), cbU2C(), CfgMgrConsts::data_path, data_path_global, and wxString::IsSameAs().
Read() [3/12]
bool ConfigManager::Read (const wxString & name, int * value)
Definition at line 967 of file configmanager.cpp.
References AssertPath(), and cbU2C().
Read() [4/12]
bool ConfigManager::Read (const wxString & name, bool * value)
Definition at line 1000 of file configmanager.cpp.
References AssertPath(), and cbU2C().
Read() [5/12]
bool ConfigManager::Read (const wxString & name, double * value)
Definition at line 1036 of file configmanager.cpp.
References AssertPath(), and cbU2C().
Read() [6/12]
void ConfigManager::Read (const wxString & name, wxArrayString * as)
Definition at line 1103 of file configmanager.cpp.
References wxArrayString::Add(), AssertPath(), cbC2U(), and cbU2C().
Read() [7/12]
bool ConfigManager::Read (const wxString & name, wxColour * value)
Definition at line 916 of file configmanager.cpp.
References AssertPath(), cbU2C(), wxColour::Set(), and wxNullColour.
Read() [8/12]
bool ConfigManager::Read (const wxString & name, ISerializable * object)
Definition at line 1291 of file configmanager.cpp.
References AssertPath(), wxString::assign(), cbC2U(), cbU2C(), wxBase64::Decode(), and wxEmptyString.
Read() [9/12]
void ConfigManager::Read (const wxString & name, ConfigManagerContainer::StringToStringMap * map)
Definition at line 1332 of file configmanager.cpp.
References AssertPath(), cbC2U(), and cbU2C().
Read() [10/12]
void ConfigManager::Read (const wxString & name, ConfigManagerContainer::IntToStringMap * map)
Definition at line 1381 of file configmanager.cpp.
References AssertPath(), cbC2U(), cbU2C(), and wxString::ToLong().
Read() [11/12]
void ConfigManager::Read (const wxString & name, ConfigManagerContainer::StringSet * map)
Definition at line 1438 of file configmanager.cpp.
References AssertPath(), cbC2U(), and cbU2C().
Read() [12/12]
template<typename T > void ConfigManager::Read (const wxString & name, std::map< wxString, T *> * map) inline
Definition at line 297 of file configmanager.h.
References cbC2U(), wxBase64::Decode(), and wxString::mb_str().
ReadAppPath()
static wxString ConfigManager::ReadAppPath () inline static
Definition at line 192 of file configmanager.h.
References Delete(), ParserConsts::ptr, wxBLACK, and wxEmptyString.
ReadArrayString()
wxArrayString ConfigManager::ReadArrayString (const wxString & name)
Definition at line 1119 of file configmanager.cpp.
References Read().
Referenced by CompilerGCC::AddOutputLine(), cbReadBatchBuildPlugins(), CompilerOptionsDlg::DoFillOthers(), RecentItemsList::Initialize(), and Compiler::LoadSettings().
ReadBinary()
wxString ConfigManager::ReadBinary (const wxString & name)
Definition at line 1144 of file configmanager.cpp.
References AssertPath(), wxString::assign(), cbC2U(), cbU2C(), wxBase64::Decode(), wxCrc32::FromString(), and wxEmptyString.
ReadBool()
bool ConfigManager::ReadBool (const wxString & name, bool defaultVal = false)
Definition at line 990 of file configmanager.cpp.
References Read().
Referenced by EditorColourSet::Apply(), cbSmartIndentPlugin::AutoIndentEnabled(), cbSmartIndentPlugin::BraceCompletionEnabled(), cbSmartIndentPlugin::BraceSmartIndentEnabled(), cbAuiNotebook::cbAuiNotebook(), CCOptionsDlg::CCOptionsDlg(), CompilerMessages::CompilerMessages(), ScriptBindings::ConfigManager_Read(), CompilerGCC::Configure(), EncodingDetector::ConvertToWxString(), NativeParser::CreateClassBrowser(), Manager::CreateEmptyToolbar(), ProjectManagerUI::CreateMenuTreeProps(), DebuggerManager::DebuggerManager(), CodeCompletion::DoAllMethodsImpl(), CompilerGCC::DoRegisterCompilers(), CompilerGCC::DoRunQueue(), MainFrame::DoUpdateEditorStyle(), EditorConfigurationDlg::EditorConfigurationDlg(), EnvironmentSettingsDlg::EndModal(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), ParserCommon::FileType(), ScriptingSettingsDlg::FillTrusts(), FindReplace::Find(), FindReplaceDlg::FindReplaceDlg(), cbEditor::FixFoldState(), cbDebuggerCommonConfig::GetFlag(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CodeBlocksApp::InitAssociations(), CodeBlocksApp::InitLocale(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), DirectCommands::IsObjectOutdated(), EditorColourSet::Load(), PluginManager::LoadAllPlugins(), cbProject::LoadLayout(), Compiler::LoadSettings(), MainFrame::LoadWindowSize(), MainFrame::MainFrame(), NativeParser::NativeParser(), CodeBlocksApp::OnAppActivate(), CompilerOptionsDlg::OnApply(), CompilerGCC::OnAttach(), CCManager::OnCompleteCode(), MainFrame::OnEditorActivated(), cbEditor::OnEditorCharAdded(), MainFrame::OnEditSelectNextSkip(), ProjectManagerUI::OnFindFile(), CodeBlocksApp::OnInit(), CompilerGCC::OnJobEnd(), MainFrame::OnNotebookDoubleClick(), MainFrame::OnSearchMenuUpdateUI(), MainFrame::OnSettingsEnvironment(), MainFrame::OnToggleStatusBar(), CCOptionsDlg::OnUpdateUI(), cbEditor::OnZoom(), cbEditor::Open(), PlaceWindow(), PluginsConfigurationDlg::PluginsConfigurationDlg(), PrintDialog::PrintDialog(), ProjectManagerUI::ProjectManagerUI(), ProjectManagerUI::QueryCloseWorkspace(), ConfigManagerWrapper::ReadBool(), Parser::ReadOptions(), CompilerGCC::Rebuild(), CompilerGCC::RebuildWorkspace(), FindReplace::Replace(), FindReplace::ReplaceInFiles(), DocumentationHelper::RereadOptions(), CodeCompletion::RereadOptions(), NativeParser::RereadParserOptions(), cbProject::SaveLayout(), cbSmartIndentPlugin::SelectionBraceCompletionEnabled(), cbEditor::SetEditorStyleAfterFileOpen(), cbEditor::SetEditorStyleBeforeFileOpen(), cbEditorInternalData::SetLineNumberColWidth(), MainFrame::ShowHideStartPage(), MainFrame::ShowTips(), cbSmartIndentPlugin::SmartIndentEnabled(), cbEditor::Split(), CodeCompletion::UpdateToolBar(), WizCompilerPanel::WizCompilerPanel(), WizFilePathPanel::WizFilePathPanel(), and WizPageBase::WizPageBase().
ReadColour()
wxColour ConfigManager::ReadColour (const wxString & name, const wxColour & defaultVal = *wxBLACK)
Definition at line 906 of file configmanager.cpp.
References Read().
Referenced by MainFrame::DoUpdateLayoutColours(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), cbEditor::GetOptionColour(), ColourManager::Load(), and EditorColourSet::Load().
ReadDataPath()
static wxString ConfigManager::ReadDataPath () inline static
Definition at line 191 of file configmanager.h.
Referenced by ProjectManagerUI::BuildTree(), dlgAbout::dlgAbout(), CodeBlocksApp::InitXRCStuff(), cbProjectTreeImages::MakeImageList(), and StartHerePage::StartHerePage().
ReadDouble()
double ConfigManager::ReadDouble (const wxString & name, double defaultVal = 0.0f)
Definition at line 1026 of file configmanager.cpp.
References Read().
Referenced by ScriptBindings::ConfigManager_Read(), and ConfigManagerWrapper::ReadDouble().
ReadInt()
int ConfigManager::ReadInt (const wxString & name, int defaultVal = 0)
Definition at line 957 of file configmanager.cpp.
References Read().
Referenced by CompilerGCC::AddOutputLine(), CompilerGCC::AllocProcesses(), CCOptionsDlg::CCOptionsDlg(), ClassBrowser::ClassBrowser(), ScriptBindings::ConfigManager_Read(), MainFrame::CreateIDE(), EncodingDetector::DetectEncoding(), MainFrame::DoUpdateEditorStyle(), MainFrame::DoUpdateLayoutColours(), EditorConfigurationDlg::EditorConfigurationDlg(), EditorManager::EditorManager(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), ExamineMemoryDlg::ExamineMemoryDlg(), FindReplaceDlg::FindReplaceDlg(), GetEOLStr(), cbDebuggerCommonConfig::GetPerspective(), InitPrinting(), cbEditor::InternalSetEditorStyleAfterFileOpen(), cbEditor::InternalSetEditorStyleBeforeFileOpen(), cbProject::LoadLayout(), Compiler::LoadSettings(), ToolsManager::LoadTools(), MainFrame::LoadWindowSize(), CompilerOptionsDlg::OnApply(), CCManager::OnEditorHook(), CCManager::OnEditorTooltip(), CCManager::OnShowCallTip(), PlaceWindow(), PrintDialog::PrintDialog(), ReadActiveDebuggerConfig(), ConfigManagerWrapper::ReadInt(), Parser::ReadOptions(), NativeParser::RemoveObsoleteParsers(), CodeCompletion::RereadOptions(), cbEditor::SetEditorStyleBeforeFileOpen(), cbEditorInternalData::SetLineNumberColWidth(), MainFrame::SetupGUILogging(), PluginManager::SetupLocaleDomain(), MainFrame::ShowTips(), cbEditor::Split(), ClassBrowser::UpdateSash(), TextCtrlLogger::UpdateSettings(), ListCtrlLogger::UpdateSettings(), and WizGenericSingleChoiceList::WizGenericSingleChoiceList().
ReadISMap()
ConfigManagerContainer::IntToStringMap ConfigManager::ReadISMap (const wxString & name)
Definition at line 1401 of file configmanager.cpp.
References Read().
ReadSSet()
ConfigManagerContainer::StringSet ConfigManager::ReadSSet (const wxString & name)
Definition at line 1454 of file configmanager.cpp.
References Read().
Referenced by EnvironmentSettingsDlg::EndModal(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), AnnoyingDialog::Init(), and AnnoyingDialog::OnButton().
ReadSSMap()
ConfigManagerContainer::StringToStringMap ConfigManager::ReadSSMap (const wxString & name)
Definition at line 1348 of file configmanager.cpp.
References Read().
Set()
void ConfigManager::Set (const wxString & name)
Definition at line 1050 of file configmanager.cpp.
References AssertPath(), and GetUniqElement().
SetNodeText()
void ConfigManager::SetNodeText (TiXmlElement * n, const TiXmlText & t) private
Definition at line 788 of file configmanager.cpp.
Referenced by Write(), and WriteBinary().
SetPath()
void ConfigManager::SetPath (const wxString & strPath)
Definition at line 655 of file configmanager.cpp.
References _T, AssertPath(), and pathNode.
SetUserDataFolder()
bool ConfigManager::SetUserDataFolder (const wxString & user_data_path) static protected
Definition at line 565 of file configmanager.cpp.
References _(), wxString::c_str(), cbMessageBox(), CreateDirRecursively(), wxFileName::DirName(), wxString::Format(), and wxFileName::GetFullPath().
Referenced by CfgMgrBldr::FindConfigFile(), and IMPLEMENT_APP().
UnSet()
void ConfigManager::UnSet (const wxString & name)
Definition at line 1057 of file configmanager.cpp.
References AssertPath(), and GetUniqElement().
Referenced by FindReplaceDlg::FindReplaceDlg(), ColourManager::Save(), and Write().
Write() [1/12]
void ConfigManager::Write (const wxString & name, const wxString & value, bool ignoreEmpty = false)
Definition at line 805 of file configmanager.cpp.
References _T, CfgMgrConsts::app_path, AssertPath(), CfgMgrConsts::data_path, data_path_global, GetUniqElement(), wxString::IsEmpty(), wxString::IsSameAs(), wxString::mb_str(), SetNodeText(), and UnSet().
Referenced by EditorColourSet::Apply(), cbWriteBatchBuildPlugins(), CodeBlocksApp::CheckVersion(), EditorManager::CollectDefines(), ScriptBindings::ConfigManager_Write(), ProjectManagerUI::CreateMenuTreeProps(), MainFrame::DoOnFileOpen(), MainFrame::DoSelectLayout(), PrintDialog::EndModal(), CompilerSettingsDlg::EndModal(), EnvironmentSettingsDlg::EndModal(), BatchLogWindow::EndModal(), PluginsConfigurationDlg::EndModal(), NewFromTemplateDlg::EndModal(), ScriptingSettingsDlg::EndModal(), EditorConfigurationDlg::EndModal(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), IMPLEMENT_APP(), AnnoyingDialog::Init(), CodeBlocksApp::InitAssociations(), PluginManager::LoadAllPlugins(), MainFrame::MainFrame(), UserVariableManager::Migrate(), CCOptionsDlg::OnApply(), CompilerOptionsDlg::OnApply(), CompilerMessages::OnAutoFit(), ScriptConsole::OnbtnLoadClick(), AnnoyingDialog::OnButton(), PluginsConfigurationDlg::OnExport(), ProjectManagerUI::OnFindFile(), ExamineMemoryDlg::OnGo(), DebugLogPanel::OnLoadFile(), GotoFunctionDlg::OnModeClick(), DebuggerSettingsDlg::OnOK(), WizPageBase::OnPageChanging(), WizFilePathPanel::OnPageChanging(), WizGenericSelectPathPanel::OnPageChanging(), WizCompilerPanel::OnPageChanging(), WizGenericSingleChoiceList::OnPageChanging(), CompilerGCC::OnRelease(), ClassBrowser::OnSetSortType(), InfoPane::OnTabPosition(), ProjectManagerUI::OnTabPosition(), EditorManager::OnTabPosition(), PluginsConfigurationDlg::OnToggle(), MainFrame::OnToggleStatusBar(), ProjectManagerUI::OnViewCategorize(), MainFrame::OnViewHideEditorTabs(), ProjectManagerUI::OnViewHideFolderName(), ClassBrowser::OnViewScope(), ProjectManagerUI::OnViewUseFolders(), cbEditor::Print(), DebuggerManager::ProcessSettings(), ProjectManagerUI::ProjectManagerUI(), Parser::ReadOptions(), ColourManager::Save(), FilesGroupsAndMasks::Save(), EditorColourSet::Save(), cbEditor::SaveAs(), FindReplaceDlg::SaveComboValues(), Compiler::SaveSettings(), ToolsManager::SaveTools(), MainFrame::SaveWindowState(), ScriptBindings::IOLib::SecurityAllows(), ProjectManager::SetDefaultPath(), DebuggerManager::SetDisassemblyMixedMode(), cbDebuggerCommonConfig::SetFlag(), cbDebuggerCommonConfig::SetPerspective(), PluginManager::SetupLocaleDomain(), cbDebuggerCommonConfig::SetValueTooltipFont(), MainFrame::ShowTips(), RecentItemsList::TerminateHistory(), Write(), ConfigManagerWrapper::Write(), WriteActiveDebuggerConfig(), DocumentationHelper::WriteOptions(), Parser::WriteOptions(), ClassBrowser::~ClassBrowser(), EditorManager::~EditorManager(), FindReplaceDlg::~FindReplaceDlg(), and ScriptingManager::~ScriptingManager().
Write() [2/12]
void ConfigManager::Write (const wxString & key, const char * str)
Definition at line 834 of file configmanager.cpp.
References cbC2U(), and Write().
Write() [3/12]
void ConfigManager::Write (const wxString & name, int value)
Definition at line 948 of file configmanager.cpp.
References AssertPath(), and GetUniqElement().
Write() [4/12]
void ConfigManager::Write (const wxString & name, bool value)
Definition at line 981 of file configmanager.cpp.
References AssertPath(), and GetUniqElement().
Write() [5/12]
void ConfigManager::Write (const wxString & name, double value)
Definition at line 1017 of file configmanager.cpp.
References AssertPath(), and GetUniqElement().
Write() [6/12]
void ConfigManager::Write (const wxString & name, const wxArrayString & as)
Definition at line 1079 of file configmanager.cpp.
References _T, AssertPath(), wxArrayString::GetCount(), and GetUniqElement().
Write() [7/12]
void ConfigManager::Write (const wxString & name, const wxColour & c)
Definition at line 883 of file configmanager.cpp.
References _T, AssertPath(), wxColour::Blue(), GetUniqElement(), wxColour::Green(), wxColour::Red(), and wxNullColour.
Write() [8/12]
void ConfigManager::Write (const wxString & name, const ISerializable & object)
Definition at line 1280 of file configmanager.cpp.
References _T, AssertPath(), cbU2C(), wxBase64::Encode(), GetUniqElement(), and SetNodeText().
Write() [9/12]
void ConfigManager::Write (const wxString & name, const ConfigManagerContainer::StringToStringMap & map)
Definition at line 1308 of file configmanager.cpp.
References _T, AssertPath(), cbU2C(), and GetUniqElement().
Write() [10/12]
void ConfigManager::Write (const wxString & name, const ConfigManagerContainer::IntToStringMap & map)
Definition at line 1355 of file configmanager.cpp.
References _T, AssertPath(), cbU2C(), GetUniqElement(), wxString::mb_str(), and wxString::Printf().
Write() [11/12]
void ConfigManager::Write (const wxString & name, const ConfigManagerContainer::StringSet & set)
Definition at line 1413 of file configmanager.cpp.
References _T, AssertPath(), cbU2C(), and GetUniqElement().
Write() [12/12]
void ConfigManager::Write (const wxString & name, const ConfigManagerContainer::SerializableObjectMap * map)
Definition at line 1462 of file configmanager.cpp.
References _T, AssertPath(), cbU2C(), wxBase64::Encode(), and GetUniqElement().
WriteBinary() [1/2]
void ConfigManager::WriteBinary (const wxString & name, const wxString & source)
Definition at line 1126 of file configmanager.cpp.
References _T, AssertPath(), wxBase64::Encode(), wxCrc32::FromString(), GetUniqElement(), and SetNodeText().
Referenced by WriteBinary().
WriteBinary() [2/2]
void ConfigManager::WriteBinary (const wxString & name, void * ptr, size_t len)
Definition at line 1138 of file configmanager.cpp.
References WriteBinary().
Friends And Related Function Documentation
CfgMgrBldr
friend class CfgMgrBldr friend
Definition at line 96 of file configmanager.h.
CodeBlocksApp
friend class CodeBlocksApp friend
Definition at line 97 of file configmanager.h.
Member Data Documentation
alternate_user_data_path
wxString ConfigManager::alternate_user_data_path static private
Definition at line 122 of file configmanager.h.
app_path
wxString ConfigManager::app_path static private
Definition at line 120 of file configmanager.h.
Referenced by GetFolder(), InitPaths(), and Read().
config_folder
wxString ConfigManager::config_folder static private
Definition at line 112 of file configmanager.h.
Referenced by GetFolder().
data_path_global
wxString ConfigManager::data_path_global static private
Definition at line 115 of file configmanager.h.
Referenced by GetFolder(), InitPaths(), Read(), and Write().
data_path_user
wxString ConfigManager::data_path_user static private
Definition at line 114 of file configmanager.h.
Referenced by GetFolder().
doc
TiXmlDocument* ConfigManager::doc private
Definition at line 99 of file configmanager.h.
Referenced by Delete(), DeleteAll(), and DeleteSubPath().
has_alternate_user_data_path
bool ConfigManager::has_alternate_user_data_path =false static private
Definition at line 123 of file configmanager.h.
Referenced by CfgMgrBldr::FindConfigFile(), GetUserDataFolder(), and InitPaths().
home_folder
wxString ConfigManager::home_folder static private
Definition at line 113 of file configmanager.h.
Referenced by GetFolder().
pathNode
TiXmlElement* ConfigManager::pathNode private
Definition at line 101 of file configmanager.h.
Referenced by AssertPath(), DeleteSubPath(), GetPath(), and SetPath().
root
TiXmlElement* ConfigManager::root private
Definition at line 100 of file configmanager.h.
Referenced by AssertPath(), Clear(), Delete(), DeleteAll(), DeleteSubPath(), GetPath(), and InvalidNameMessage().
temp_folder
wxString ConfigManager::temp_folder static private
Definition at line 121 of file configmanager.h.
Referenced by GetFolder().
The documentation for this class was generated from the following files:
configmanager.h
configmanager-revision.cpp
configmanager.cpp