Code::Blocks: EditKeywordsDlg Class Reference
EditKeywordsDlg Class Reference
#include <editkeywordsdlg.h>
Public Member Functions
EditKeywordsDlg (wxWindow *parent, EditorColourSet *theme, HighlightLanguage lang, const wxArrayString &descr)
~EditKeywordsDlg ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Public Attributes
EditorColourSet * m_pTheme
HighlightLanguage m_Lang
wxTextCtrl * txtKeywords
int m_LastSet
Protected Member Functions
void OnSetChange (wxSpinEvent &event)
Protected Attributes
wxSpinCtrl * spnSet
Private Member Functions
void UpdateDlg ()
Private Attributes
const wxArrayString & descriptions
Detailed Description
Definition at line 16 of file editkeywordsdlg.h.
Constructor & Destructor Documentation
EditKeywordsDlg()
EditKeywordsDlg::EditKeywordsDlg (wxWindow * parent, EditorColourSet * theme, HighlightLanguage lang, const wxArrayString & descr)
Definition at line 29 of file editkeywordsdlg.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadObject().
~EditKeywordsDlg()
EditKeywordsDlg::~EditKeywordsDlg ()
Definition at line 43 of file editkeywordsdlg.cpp.
Member Function Documentation
OnSetChange()
void EditKeywordsDlg::OnSetChange (wxSpinEvent & event) protected
Definition at line 48 of file editkeywordsdlg.cpp.
References m_Lang, m_LastSet, m_pTheme, EditorColourSet::SetKeywords(), txtKeywords, and UpdateDlg().
UpdateDlg()
void EditKeywordsDlg::UpdateDlg () private
Definition at line 54 of file editkeywordsdlg.cpp.
References descriptions, wxArrayString::GetCount(), EditorColourSet::GetKeywords(), wxSpinCtrl::GetValue(), m_Lang, m_LastSet, m_pTheme, spnSet, txtKeywords, and wxT.
Referenced by OnSetChange().
Member Data Documentation
descriptions
const wxArrayString& EditKeywordsDlg::descriptions private
Definition at line 32 of file editkeywordsdlg.h.
Referenced by UpdateDlg().
m_Lang
HighlightLanguage EditKeywordsDlg::m_Lang
Definition at line 27 of file editkeywordsdlg.h.
Referenced by OnSetChange(), and UpdateDlg().
m_LastSet
int EditKeywordsDlg::m_LastSet
Definition at line 29 of file editkeywordsdlg.h.
Referenced by OnSetChange(), and UpdateDlg().
m_pTheme
EditorColourSet* EditKeywordsDlg::m_pTheme
Definition at line 26 of file editkeywordsdlg.h.
Referenced by OnSetChange(), and UpdateDlg().
spnSet
wxSpinCtrl* EditKeywordsDlg::spnSet protected
Definition at line 24 of file editkeywordsdlg.h.
Referenced by UpdateDlg().
txtKeywords
wxTextCtrl* EditKeywordsDlg::txtKeywords
Definition at line 28 of file editkeywordsdlg.h.
Referenced by OnSetChange(), and UpdateDlg().
The documentation for this class was generated from the following files:
editkeywordsdlg.h
editkeywordsdlg.cpp