Code::Blocks: cbStyledTextCtrl Class Reference
cbStyledTextCtrl Class Reference
#include <cbstyledtextctrl.h>
Public Member Functions
cbStyledTextCtrl (wxWindow *pParent, int id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
~cbStyledTextCtrl () override
void operator= (const cbStyledTextCtrl &)
Don't use this.
wxDateTime GetLastFocusTime () const
wxString GetLastSelectedText () const
void EnableTabSmartJump (bool enable=true)
bool IsCharacter (int style)
Is style classified as character for current language?
bool IsString (int style)
Is style classified as string for current language?
bool IsPreprocessor (int style)
Is style classified as preprocessor for current language?
bool IsComment (int style)
Is style classified as comment for current language?
void CallTipCancel ()
Cancel calltip only if not jumping braces via tab.
bool IsBraceShortcutActive ()
void DoBraceCompletion (const wxChar &ch)
Automated braces/quotes completion.
bool DoSelectionBraceCompletion (const wxChar &ch)
Put braces/quotes around the current selection in the editor.
void MakeNearbyLinesVisible (int line)
Scroll minimum amount such that 2 lines above and below line are shown.
Public Member Functions inherited from wxScintilla
wxScintilla (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name=wxSCINameStr)
wxScintilla ()
~wxScintilla ()
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name=wxSCINameStr)
void AddText (const wxString &text)
Generated method declaration section {{{.
void AddStyledText (const wxMemoryBuffer &data)
Add array of cells to document.
void InsertText (int pos, const wxString &text)
Insert string at a position.
void ChangeInsertion (int length, const wxString &text)
Change the text that is being inserted in response to wxSCI_MOD_INSERTCHECK.
void ClearAll ()
Delete all text in the document.
void DeleteRange (int start, int lengthDelete)
Delete a range of text in the document.
void ClearDocumentStyle ()
Set all style bytes to 0, remove all folding information.
int GetLength () const
Returns the number of bytes in the document.
int GetCharAt (int pos) const
Returns the character byte at the position.
int GetCurrentPos () const
Returns the position of the caret.
int GetAnchor () const
Returns the position of the opposite end of the selection to the caret.
int GetStyleAt (int pos) const
Returns the style byte at the position.
void Redo ()
Redoes the next action on the undo history.
void SetUndoCollection (bool collectUndo)
Choose between collecting actions into the undo history and discarding them.
void SetChangeCollection (bool collectChange)
Choose between collecting actions into the changes history and discarding them.
int FindChangedLine (const int fromLine, const int toLine) const
Find a changed line, if fromLine > toLine search is performed backwards.
void SelectAll ()
Select all the text in the document.
void SetSavePoint ()
Remember the current position in the undo history as the position at which the document was saved.
wxMemoryBuffer GetStyledText (int startPos, int endPos)
Retrieve a buffer of cells.
bool CanRedo () const
Are there any redoable actions in the undo history?
int MarkerLineFromHandle (int markerHandle)
Retrieve the line number at which a particular marker is located.
void MarkerDeleteHandle (int markerHandle)
Delete a marker.
bool GetUndoCollection () const
Is undo history being collected?
int GetViewWhiteSpace () const
Are white space characters currently visible? Returns one of wxSCI_WS_* constants.
void SetViewWhiteSpace (int viewWS)
Make white space characters invisible, always visible or visible outside indentation.
int GetTabDrawMode () const
Retrieve the current tab draw mode.
void SetTabDrawMode (int tabDrawMode)
Set how tabs are drawn when visible.
int PositionFromPoint (wxPoint pt) const
Find the position from a point within the window.
int PositionFromPointClose (int x, int y)
Find the position from a point within the window but return wxSCI_INVALID_POSITION if not close to text.
void GotoLine (int line)
Set caret to start of a line and ensure it is visible.
void GotoPos (int caret)
Set caret to a position and ensure it is visible.
void SetAnchor (int anchor)
Set the selection anchor to a position.
wxString GetCurLine (int *linePos=NULL)
Retrieve the text of the line containing the caret.
int GetEndStyled () const
Retrieve the position of the last correctly styled character.
void ConvertEOLs (int eolMode)
Convert all line endings in the document to one mode.
int GetEOLMode () const
Retrieve the current end of line mode - one of wxSCI_EOL_CRLF, wxSCI_EOL_CR, or wxSCI_EOL_LF.
void SetEOLMode (int eolMode)
Set the current end of line mode.
void StartStyling (int start)
Set the current styling position to start.
void SetStyling (int length, int style)
Change style from current styling position for length characters to a style and move the current styling position to after this newly styled segment.
bool GetBufferedDraw () const
Is drawing done first into a buffer or direct to the screen?
void SetBufferedDraw (bool buffered)
If drawing is buffered then each line of text is drawn into a bitmap buffer before drawing it to the screen to avoid flicker.
void SetTabWidth (int tabWidth)
Change the visible size of a tab to be a multiple of the width of a space character.
int GetTabWidth () const
Retrieve the visible size of a tab.
void ClearTabStops (int line)
Clear explicit tabstops on a line.
void AddTabStop (int line, int x)
Add an explicit tab stop for a line.
int GetNextTabStop (int line, int x)
Find the next explicit tab stop position on a line after a position.
void SetCodePage (int codePage)
Set the code page used to interpret the bytes of the document as characters.
int GetIMEInteraction () const
Is the IME displayed in a window or inline?
void SetIMEInteraction (int imeInteraction)
Choose to display the the IME in a winow or inline.
void MarkerDefine (int markerNumber, int markerSymbol, const wxColour &foreground=wxNullColour, const wxColour &background=wxNullColour)
Set the symbol used for a particular marker number, and optionally the fore and background colours.
void MarkerSetForeground (int markerNumber, const wxColour &fore)
Set the foreground colour used for a particular marker number.
void MarkerSetBackground (int markerNumber, const wxColour &back)
Set the background colour used for a particular marker number.
void MarkerSetBackgroundSelected (int markerNumber, const wxColour &back)
Set the background colour used for a particular marker number when its folding block is selected.
void MarkerEnableHighlight (bool enabled)
Enable/disable highlight for current folding bloc (smallest one that contains the caret)
int MarkerAdd (int line, int markerNumber)
Add a marker to a line, returning an ID which can be used to find or delete the marker.
void MarkerDelete (int line, int markerNumber)
Delete a marker from a line.
void MarkerDeleteAll (int markerNumber)
Delete all markers with a particular number from all lines.
int MarkerGet (int line)
Get a bit mask of all the markers set on a line.
int MarkerNext (int lineStart, int markerMask)
Find the next line at or after lineStart that includes a marker in mask.
int MarkerPrevious (int lineStart, int markerMask)
Find the previous line before lineStart that includes a marker in mask.
void MarkerDefineBitmap (int markerNumber, const wxBitmap &bmp)
Define a marker from a bitmap.
void MarkerAddSet (int line, int markerSet)
Add a set of markers to a line.
void MarkerSetAlpha (int markerNumber, int alpha)
Set the alpha used for a marker that is drawn in the text area, not the margin.
void SetMarginType (int margin, int marginType)
Set a margin to be either numeric or symbolic.
int GetMarginType (int margin) const
Retrieve the type of a margin.
void SetMarginWidth (int margin, int pixelWidth)
Set the width of a margin to a width expressed in pixels.
int GetMarginWidth (int margin) const
Retrieve the width of a margin in pixels.
void SetMarginMask (int margin, int mask)
Set a mask that determines which markers are displayed in a margin.
int GetMarginMask (int margin) const
Retrieve the marker mask of a margin.
void SetMarginSensitive (int margin, bool sensitive)
Make a margin sensitive or insensitive to mouse clicks.
bool GetMarginSensitive (int margin) const
Retrieve the mouse click sensitivity of a margin.
void SetMarginCursor (int margin, int cursor)
Set the cursor shown when the mouse is inside a margin.
int GetMarginCursor (int margin) const
Retrieve the cursor shown in a margin.
void SetMarginBackground (int margin, const wxColour &back)
Set the background colour of a margin. Only visible for wxSCI_MARGIN_COLOUR.
wxColour GetMarginBackground (int margin) const
Retrieve the background colour of a margin.
void SetMarginCount (int margins)
Allocate a non-standard number of margins.
int GetMarginCount () const
How many margins are there?.
void StyleClearAll ()
Clear all the styles and make equivalent to the global default style.
void StyleSetForeground (int style, const wxColour &fore)
Set the foreground colour of a style.
void StyleSetBackground (int style, const wxColour &back)
Set the background colour of a style.
void StyleSetBold (int style, bool bold)
Set a style to be bold or not.
void StyleSetItalic (int style, bool italic)
Set a style to be italic or not.
void StyleSetSize (int style, int sizePoints)
Set the size of characters of a style.
void StyleSetFaceName (int style, const wxString &fontName)
Set the font of a style.
void StyleSetEOLFilled (int style, bool eolFilled)
Set a style to have its end of line filled or not.
void StyleResetDefault ()
Reset the default style to its state at startup.
void StyleSetUnderline (int style, bool underline)
Set a style to be underlined or not.
wxColour StyleGetForeground (int style) const
Get the foreground colour of a style.
wxColour StyleGetBackground (int style) const
Get the background colour of a style.
bool StyleGetBold (int style) const
Get is a style bold or not.
bool StyleGetItalic (int style) const
Get is a style italic or not.
int StyleGetSize (int style) const
Get the size of characters of a style.
wxString StyleGetFaceName (int style)
Get the font facename of a style.
bool StyleGetEOLFilled (int style) const
Get is a style to have its end of line filled or not.
bool StyleGetUnderline (int style) const
Get is a style underlined or not.
int StyleGetCase (int style) const
Get is a style mixed case, or to force upper or lower case.
int StyleGetCharacterSet (int style) const
Get the character get of the font in a style.
bool StyleGetVisible (int style) const
Get is a style visible or not.
bool StyleGetChangeable (int style) const
Get is a style changeable or not (read only).
bool StyleGetHotSpot (int style) const
Get is a style a hotspot or not.
void StyleSetCase (int style, int caseVisible)
Set a style to be mixed case, or to force upper or lower case.
void StyleSetSizeFractional (int style, int sizeHundredthPoints)
Set the size of characters of a style. Size is in points multiplied by 100.
int StyleGetSizeFractional (int style) const
Get the size of characters of a style in points multiplied by 100.
void StyleSetWeight (int style, int weight)
Set the weight of characters of a style.
int StyleGetWeight (int style) const
Get the weight of characters of a style.
void StyleSetCharacterSet (int style, int characterSet)
Set the character set of the font in a style.
void StyleSetHotSpot (int style, bool hotspot)
Set a style to be a hotspot or not.
void SetSelForeground (bool useSetting, const wxColour &fore)
Set the foreground colour of the main and additional selections and whether to use this setting.
void SetSelBackground (bool useSetting, const wxColour &back)
Set the background colour of the main and additional selections and whether to use this setting.
int GetSelAlpha () const
Get the alpha of the selection.
void SetSelAlpha (int alpha)
Set the alpha of the selection.
bool GetSelEOLFilled () const
Is the selection end of line filled?
void SetSelEOLFilled (bool filled)
Set the selection to have its end of line filled or not.
void SetCaretForeground (const wxColour &fore)
Set the foreground colour of the caret.
void CmdKeyAssign (int key, int modifiers, int cmd)
When key+modifier combination keyDefinition is pressed perform sciCommand.
void CmdKeyClear (int key, int modifiers)
When key+modifier combination keyDefinition is pressed do nothing.
void CmdKeyClearAll ()
Drop all key mappings.
void SetStyleBytes (int length, char *styleBytes)
Set the styles for a segment of the document.
void StyleSetVisible (int style, bool visible)
Set a style to be visible or not.
int GetCaretPeriod () const
Get the time in milliseconds that the caret is on and off.
void SetCaretPeriod (int periodMilliseconds)
Get the time in milliseconds that the caret is on and off. 0 = steady on.
void SetWordChars (const wxString &characters)
Set the set of characters making up words for when moving or selecting by word.
wxString GetWordChars () const
Get the set of characters making up words for when moving or selecting by word.
void BeginUndoAction ()
Start a sequence of actions that is undone and redone as a unit.
void EndUndoAction ()
End a sequence of actions that is undone and redone as a unit.
void IndicatorSetStyle (int indicator, int indicatorStyle)
Set an indicator to plain, squiggle or TT.
int IndicatorGetStyle (int indicator) const
Retrieve the style of an indicator.
void IndicatorSetForeground (int indicator, const wxColour &fore)
Set the foreground colour of an indicator.
wxColour IndicatorGetForeground (int indicator) const
Retrieve the foreground colour of an indicator.
void IndicatorSetUnder (int indicator, bool under)
Set an indicator to draw under text or over(default).
bool IndicatorGetUnder (int indicator) const
Retrieve whether indicator drawn under or over text.
void IndicatorSetHoverStyle (int indicator, int indicatorStyle)
Set a hover indicator to plain, squiggle or TT.
int IndicatorGetHoverStyle (int indicator) const
Retrieve the hover style of an indicator.
void IndicatorSetHoverForeground (int indicator, const wxColour &fore)
Set the foreground hover colour of an indicator.
wxColour IndicatorGetHoverForeground (int indicator) const
Retrieve the foreground hover colour of an indicator.
void IndicatorSetFlags (int indicator, int flags)
Set the attributes of an indicator.
int IndicatorGetFlags (int indicator) const
Retrieve the attributes of an indicator.
void SetWhitespaceForeground (bool useSetting, const wxColour &fore)
Set the foreground colour of all whitespace and whether to use this setting.
void SetWhitespaceBackground (bool useSetting, const wxColour &back)
Set the background colour of all whitespace and whether to use this setting.
void SetWhitespaceSize (int size)
Set the size of the dots used to mark space characters.
int GetWhitespaceSize () const
Get the size of the dots used to mark space characters.
wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") void SetStyleBits(int bits)
Divide each styling byte into lexical class bits (default: 5) and indicator bits (default: 3).
wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") int GetStyleBits() const
Retrieve number of bits in style bytes used to hold the lexical state.
void SetLineState (int line, int state)
Used to hold extra styling information for each line.
int GetLineState (int line) const
Retrieve the extra styling information for a line.
int GetMaxLineState () const
Retrieve the last line number that has line state.
bool GetCaretLineVisible () const
Is the background of the line containing the caret in a different colour?
void SetCaretLineVisible (bool show)
Display the background of the line containing the caret in a different colour.
wxColour GetCaretLineBackground () const
Get the colour of the background of the line containing the caret.
void SetCaretLineBackground (const wxColour &back)
Set the colour of the background of the line containing the caret.
void StyleSetChangeable (int style, bool changeable)
Set a style to be changeable or not (read only).
void AutoCompShow (int lengthEntered, const wxString &itemList)
Display a auto-completion list.
void AutoCompCancel ()
Remove the auto-completion list from the screen.
bool AutoCompActive ()
Is there an auto-completion list visible?
int AutoCompPosStart ()
Retrieve the position of the caret when the auto-completion list was displayed.
void AutoCompComplete ()
User has selected an item so remove the list and insert the selection.
void AutoCompStops (const wxString &characterSet)
Define a set of character that when typed cancel the auto-completion list.
void AutoCompSetSeparator (int separatorCharacter)
Change the separator character in the string setting up an auto-completion list.
int AutoCompGetSeparator () const
Retrieve the auto-completion list separator character.
void AutoCompSelect (const wxString &select)
Select the item in the auto-completion list that starts with a string.
void AutoCompSetCancelAtStart (bool cancel)
Should the auto-completion list be cancelled if the user backspaces to a position before where the box was created.
bool AutoCompGetCancelAtStart () const
Retrieve whether auto-completion cancelled by backspacing before start.
void AutoCompSetFillUps (const wxString &characterSet)
Define a set of characters that when typed will cause the autocompletion to choose the selected item.
void AutoCompSetChooseSingle (bool chooseSingle)
Should a single item auto-completion list automatically choose the item.
bool AutoCompGetChooseSingle () const
Retrieve whether a single item auto-completion list automatically choose the item.
void AutoCompSetIgnoreCase (bool ignoreCase)
Set whether case is significant when performing auto-completion searches.
bool AutoCompGetIgnoreCase () const
Retrieve state of ignore case flag.
void UserListShow (int listType, const wxString &itemList)
Display a list of strings and send notification when user chooses one.
void AutoCompSetAutoHide (bool autoHide)
Set whether or not autocompletion is hidden automatically when nothing matches.
bool AutoCompGetAutoHide () const
Retrieve whether or not autocompletion is hidden automatically when nothing matches.
void AutoCompSetDropRestOfWord (bool dropRestOfWord)
Set whether or not autocompletion deletes any word characters after the inserted text upon completion.
bool AutoCompGetDropRestOfWord () const
Retrieve whether or not autocompletion deletes any word characters after the inserted text upon completion.
void RegisterImage (int type, const wxBitmap &bmp)
Register an image for use in autocompletion lists.
void ClearRegisteredImages ()
Clear all the registered images.
int AutoCompGetTypeSeparator () const
Retrieve the auto-completion list type-separator character.
void AutoCompSetTypeSeparator (int separatorCharacter)
Change the type-separator character in the string setting up an auto-completion list.
void AutoCompSetMaxWidth (int characterCount)
Set the maximum width, in characters, of auto-completion and user lists.
int AutoCompGetMaxWidth () const
Get the maximum width, in characters, of auto-completion and user lists.
void AutoCompSetMaxHeight (int rowCount)
Set the maximum height, in rows, of auto-completion and user lists.
int AutoCompGetMaxHeight () const
Set the maximum height, in rows, of auto-completion and user lists.
void SetIndent (int indentSize)
Set the number of spaces used for one level of indentation.
int GetIndent () const
Retrieve indentation size.
void SetUseTabs (bool useTabs)
Indentation will only use space characters if useTabs is false, otherwise it will use a combination of tabs and spaces.
bool GetUseTabs () const
Retrieve whether tabs will be used in indentation.
void SetLineIndentation (int line, int indentation)
Change the indentation of a line to a number of columns.
int GetLineIndentation (int line) const
Retrieve the number of columns that a line is indented.
int GetLineIndentPosition (int line) const
Retrieve the position before the first non indentation character on a line.
int GetColumn (int pos) const
Retrieve the column number of a position, taking tab width into account.
int CountCharacters (int start, int end)
Count characters between two positions.
void SetUseHorizontalScrollBar (bool visible)
Show or hide the horizontal scroll bar.
bool GetUseHorizontalScrollBar () const
Is the horizontal scroll bar visible?
void SetIndentationGuides (int indentView)
Show or hide indentation guides.
int GetIndentationGuides () const
Are the indentation guides visible?
void SetHighlightGuide (int column)
Set the highlighted indentation guide column.
int GetHighlightGuide () const
Get the highlighted indentation guide column.
int GetLineEndPosition (int line) const
Get the position after the last visible characters on a line.
int GetCodePage () const
Get the code page used to interpret the bytes of the document as characters.
wxColour GetCaretForeground () const
Get the foreground colour of the caret.
bool GetReadOnly () const
In read-only mode?
void SetCurrentPos (int caret)
Sets the position of the caret.
void SetSelectionStart (int anchor)
Sets the position that starts the selection - this becomes the anchor.
int GetSelectionStart () const
Returns the position at the start of the selection.
void SetSelectionEnd (int caret)
Sets the position that ends the selection - this becomes the caret.
int GetSelectionEnd () const
Returns the position at the end of the selection.
void SetEmptySelection (int caret)
Set caret to a position, while removing any existing selection.
void SetPrintMagnification (int magnification)
Sets the print magnification added to the point size of each style for printing.
int GetPrintMagnification () const
Returns the print magnification.
void SetPrintColourMode (int mode)
Modify colours when printing for clearer printed text.
int GetPrintColourMode () const
Returns the print colour mode.
int FindText (int minPos, int maxPos, const wxString &text, int flags=0, int *findEnd=NULL)
Find some text in the document.
int FormatRange (bool doDraw, int startPos, int endPos, wxDC *draw, wxDC *target, wxRect renderRect, wxRect pageRect)
On Windows, will draw the document into a display context such as a printer.
int GetFirstVisibleLine () const
Retrieve the display line at the top of the display.
wxString GetLine (int line) const
Retrieve the contents of a line.
int GetLineCount () const
Returns the number of lines in the document. There is always at least one.
void SetMarginLeft (int pixelWidth)
Sets the size in pixels of the left margin.
int GetMarginLeft () const
Returns the size in pixels of the left margin.
void SetMarginRight (int pixelWidth)
Sets the size in pixels of the right margin.
int GetMarginRight () const
Returns the size in pixels of the right margin.
bool GetModify () const
Is the document different from when it was last saved?
wxString GetSelectedText ()
Retrieve the selected text.
wxString GetTextRange (int startPos, int endPos)
Retrieve a range of text.
void HideSelection (bool hide)
Draw the selection in normal style or with selection highlighted.
wxPoint PointFromPosition (int pos)
Retrieve the point in the window where a position is displayed.
int LineFromPosition (int pos) const
Retrieve the line containing a position.
int PositionFromLine (int line) const
Retrieve the position at the start of a line.
void LineScroll (int columns, int lines)
Scroll horizontally and vertically.
void EnsureCaretVisible ()
Ensure the caret is visible.
void ScrollRange (int secondary, int primary)
Scroll the argument positions and the range between them into view giving priority to the primary position then the secondary position.
void ReplaceSelection (const wxString &text)
Replace the selected text with the argument text.
void SetReadOnly (bool readOnly)
Set to read only or read write.
bool CanPaste () const
Will a paste succeed?
bool CanUndo () const
Are there any undoable actions in the undo history?
void EmptyUndoBuffer (bool collectChangeHistory=false)
Delete the undo history.
void Undo ()
Undo one action in the undo history.
void Cut ()
Cut the selection to the clipboard.
void Copy ()
Copy the selection to the clipboard.
void Paste ()
Paste the contents of the clipboard into the document replacing the selection.
void Clear ()
Clear the selection.
void SetText (const wxString &text)
Replace the contents of the document with the argument text.
wxString GetText () const
Retrieve all the text in the document.
int GetTextLength () const
Retrieve the number of characters in the document.
void * GetDirectFunction () const
Retrieve a pointer to a function that processes messages for this Scintilla.
void * GetDirectPointer () const
Retrieve a pointer value to use as the first argument when calling the function returned by GetDirectFunction.
void SetOvertype (bool overType)
Set to overtype (true) or insert mode.
bool GetOvertype () const
Returns true if overtype mode is active otherwise false is returned.
void SetCaretWidth (int pixelWidth)
Set the width of the insert mode caret.
int GetCaretWidth () const
Returns the width of the insert mode caret.
void SetTargetStart (int start)
Sets the position that starts the target which is used for updating the document without affecting the scroll position.
int GetTargetStart () const
Get the position that starts the target.
void SetTargetEnd (int end)
Sets the position that ends the target which is used for updating the document without affecting the scroll position.
int GetTargetEnd () const
Get the position that ends the target.
void SetTargetRange (int start, int end)
Sets both the start and end of the target in one call.
wxString GetTargetText () const
Retrieve the text in the target.
void TargetFromSelection ()
Make the target range start and end be the same as the selection range start and end.
void TargetWholeDocument ()
Sets the target to the whole document.
int ReplaceTarget (const wxString &text)
Replace the target text with the argument text.
int ReplaceTargetRE (const wxString &text)
Replace the target text with the argument text after \d processing.
int SearchInTarget (const wxString &text)
Search for a counted string in the target and set the target to the found range.
void SetSearchFlags (int searchFlags)
Set the search flags used by SearchInTarget.
int GetSearchFlags () const
Get the search flags used by SearchInTarget.
void CallTipShow (int pos, const wxString &definition)
Show a call tip containing a definition near position pos.
void CallTipCancel ()
Remove the call tip from the screen.
bool CallTipActive ()
Is there an active call tip?
int CallTipPosAtStart ()
Retrieve the position where the caret was before displaying the call tip.
void CallTipSetPosAtStart (int posStart)
Set the start position in order to change when backspacing removes the calltip.
void CallTipSetHighlight (int highlightStart, int highlightEnd)
Highlight a segment of the definition.
void CallTipSetBackground (const wxColour &back)
Set the background colour for the call tip.
void CallTipSetForeground (const wxColour &fore)
Set the foreground colour for the call tip.
void CallTipSetForegroundHighlight (const wxColour &fore)
Set the foreground colour for the highlighted part of the call tip.
void CallTipUseStyle (int tabSize)
Enable use of wxSCI_STYLE_CALLTIP and set call tip tab size in pixels.
void CallTipSetPosition (bool above)
Set position of calltip, above or below text.
int VisibleFromDocLine (int docLine)
Find the display line of a document line taking hidden lines into account.
int DocLineFromVisible (int displayLine)
Find the document line of a display line taking hidden lines into account.
int WrapCount (int docLine)
The number of display lines needed to wrap a document line.
void SetFoldLevel (int line, int level)
Set the fold level of a line.
int GetFoldLevel (int line) const
Retrieve the fold level of a line.
int GetLastChild (int line, int level) const
Find the last child line of a header line.
int GetFoldParent (int line) const
Find the parent line of a child line.
void ShowLines (int lineStart, int lineEnd)
Make a range of lines visible.
void HideLines (int lineStart, int lineEnd)
Make a range of lines invisible.
bool GetLineVisible (int line) const
Is a line visible?
bool GetAllLinesVisible () const
Are all lines visible?
void SetFoldExpanded (int line, bool expanded)
Show the children of a header line.
bool GetFoldExpanded (int line) const
Is a header line expanded?
void ToggleFold (int line)
Switch a header line between expanded and contracted.
void ToggleFoldShowText (int line, const wxString &text)
Switch a header line between expanded and contracted and show some text after the line.
void FoldDisplayTextSetStyle (int style)
Set the style of fold display text.
void FoldLine (int line, int action)
Expand or contract a fold header.
void FoldChildren (int line, int action)
Expand or contract a fold header and its children.
void ExpandChildren (int line, int level)
Expand a fold header and all children. Use the level argument instead of the line's current level.
void FoldAll (int action)
Expand or contract all fold headers.
void EnsureVisible (int line)
Ensure a particular line is visible by expanding any header line hiding it.
void SetAutomaticFold (int automaticFold)
Set automatic folding behaviours.
int GetAutomaticFold () const
Get automatic folding behaviours.
void SetFoldFlags (int flags)
Set some style options for folding.
void EnsureVisibleEnforcePolicy (int line)
Ensure a particular line is visible by expanding any header line hiding it.
void SetTabIndents (bool tabIndents)
Sets whether a tab pressed when caret is within indentation indents.
bool GetTabIndents () const
Does a tab pressed when caret is within indentation indent?
void SetBackSpaceUnIndents (bool bsUnIndents)
Sets whether a backspace pressed when caret is within indentation unindents.
bool GetBackSpaceUnIndents () const
Does a backspace pressed when caret is within indentation unindent?
void SetMouseDwellTime (int periodMilliseconds)
Sets the time the mouse must sit still to generate a mouse dwell event.
int GetMouseDwellTime () const
Retrieve the time the mouse must sit still to generate a mouse dwell event.
int WordStartPosition (int pos, bool onlyWordCharacters)
Get position of start of word.
int WordEndPosition (int pos, bool onlyWordCharacters)
Get position of end of word.
bool IsRangeWord (int start, int end)
Is the range start..end considered a word?
void SetIdleStyling (int idleStyling)
Sets limits to idle styling.
int GetIdleStyling () const
Retrieve the limits to idle styling.
void SetWrapMode (int wrapMode)
Sets whether text is word wrapped.
int GetWrapMode () const
Retrieve whether text is word wrapped.
void SetWrapVisualFlags (int wrapVisualFlags)
Set the display mode of visual flags for wrapped lines.
int GetWrapVisualFlags () const
Retrive the display mode of visual flags for wrapped lines.
void SetWrapVisualFlagsLocation (int wrapVisualFlagsLocation)
Set the location of visual flags for wrapped lines.
int GetWrapVisualFlagsLocation () const
Retrive the location of visual flags for wrapped lines.
void SetWrapStartIndent (int indent)
Set the start indent for wrapped lines.
int GetWrapStartIndent () const
Retrive the start indent for wrapped lines.
void SetWrapIndentMode (int wrapIndentMode)
Sets how wrapped sublines are placed. Default is wxSCI_WRAPINDENT_FIXED.
int GetWrapIndentMode () const
Retrieve how wrapped sublines are placed. Default is wxSCI_WRAPINDENT_FIXED.
void SetLayoutCache (int cacheMode)
Sets the degree of caching of layout information.
int GetLayoutCache () const
Retrieve the degree of caching of layout information.
void SetScrollWidth (int pixelWidth)
Sets the document width assumed for scrolling.
int GetScrollWidth () const
Retrieve the document width assumed for scrolling.
void SetScrollWidthTracking (bool tracking)
Sets whether the maximum width line displayed is used to set scroll width.
bool GetScrollWidthTracking () const
Retrieve whether the scroll width tracks wide lines.
int TextWidth (int style, const wxString &text)
Measure the pixel width of some text in a particular style.
void SetEndAtLastLine (bool endAtLastLine)
Sets the scroll range so that maximum scroll position has the last line at the bottom of the view (default).
bool GetEndAtLastLine () const
Retrieve whether the maximum scroll position has the last line at the bottom of the view.
int TextHeight (int line)
Retrieve the height of a particular line of text in pixels.
void SetUseVerticalScrollBar (bool visible)
Show or hide the vertical scroll bar.
bool GetUseVerticalScrollBar () const
Is the vertical scroll bar visible?
void AppendText (const wxString &text)
Append a string to the end of the document without changing the selection.
bool GetTwoPhaseDraw () const
Is drawing done in two phases with backgrounds drawn before foregrounds?
void SetTwoPhaseDraw (bool twoPhase)
In twoPhaseDraw mode, drawing is performed in two phases, first the background and then the foreground.
int GetPhasesDraw () const
How many phases is drawing done in?
void SetPhasesDraw (int phases)
In one phase draw, text is drawn in a series of rectangular blocks with no overlap.
void SetFontQuality (int fontQuality)
Choose the quality level for text.
int GetFontQuality () const
Retrieve the quality level for text.
void SetFirstVisibleLine (int displayLine)
Scroll so that a display line is at the top of the display.
void SetMultiPaste (int multiPaste)
Change the effect of pasting when there are multiple selections.
int GetMultiPaste () const
Retrieve the effect of pasting when there are multiple selections.
wxString GetTag (int tagNumber) const
Retrieve the value of a tag from a regular expression search.
void LinesJoin ()
Join the lines in the target.
void LinesSplit (int pixelWidth)
Split the lines in the target into lines that are less wide than pixelWidth where possible.
void SetFoldMarginColour (bool useSetting, const wxColour &back)
Set one of the colours used as a chequerboard pattern in the fold margin.
void SetFoldMarginHiColour (bool useSetting, const wxColour &fore)
Set the other colour used as a chequerboard pattern in the fold margin.
void LineDown ()
Move caret down one line.
void LineDownExtend ()
Move caret down one line extending selection to new caret position.
void LineUp ()
Move caret up one line.
void LineUpExtend ()
Move caret up one line extending selection to new caret position.
void CharLeft ()
Move caret left one character.
void CharLeftExtend ()
Move caret left one character extending selection to new caret position.
void CharRight ()
Move caret right one character.
void CharRightExtend ()
Move caret right one character extending selection to new caret position.
void WordLeft ()
Move caret left one word.
void WordLeftExtend ()
Move caret left one word extending selection to new caret position.
void WordRight ()
Move caret right one word.
void WordRightExtend ()
Move caret right one word extending selection to new caret position.
void Home ()
Move caret to first position on line.
void HomeExtend ()
Move caret to first position on line extending selection to new caret position.
void LineEnd ()
Move caret to last position on line.
void LineEndExtend ()
Move caret to last position on line extending selection to new caret position.
void DocumentStart ()
Move caret to first position in document.
void DocumentStartExtend ()
Move caret to first position in document extending selection to new caret position.
void DocumentEnd ()
Move caret to last position in document.
void DocumentEndExtend ()
Move caret to last position in document extending selection to new caret position.
void PageUp ()
Move caret one page up.
void PageUpExtend ()
Move caret one page up extending selection to new caret position.
void PageDown ()
Move caret one page down.
void PageDownExtend ()
Move caret one page down extending selection to new caret position.
void EditToggleOvertype ()
Switch from insert to overtype mode or the reverse.
void Cancel ()
Cancel any modes such as call tip or auto-completion list display.
void DeleteBack ()
Delete the selection or if no selection, the character before the caret.
void Tab ()
If selection is empty or all on one line replace the selection with a tab character.
void BackTab ()
Dedent the selected lines.
void NewLine ()
Insert a new line, may use a CRLF, CR or LF depending on EOL mode.
void FormFeed ()
Insert a Form Feed character.
void VCHome ()
Move caret to before first visible character on line.
void VCHomeExtend ()
Like VCHome but extending selection to new caret position.
void ZoomIn ()
Magnify the displayed text by increasing the sizes by 1 point.
void ZoomOut ()
Make the displayed text smaller by decreasing the sizes by 1 point.
void DelWordLeft ()
Delete the word to the left of the caret.
void DelWordRight ()
Delete the word to the right of the caret.
void DelWordRightEnd ()
Delete the word to the right of the caret, but not the trailing non-word characters.
void LineCut ()
Cut the line containing the caret.
void LineDelete ()
Delete the line containing the caret.
void LineTranspose ()
Switch the current line with the previous.
void LineDuplicate ()
Duplicate the current line.
void LowerCase ()
Transform the selection to lower case.
void UpperCase ()
Transform the selection to upper case.
void LineScrollDown ()
Scroll the document down, keeping the caret visible.
void LineScrollUp ()
Scroll the document up, keeping the caret visible.
void DeleteBackNotLine ()
Delete the selection or if no selection, the character before the caret.
void HomeDisplay ()
Move caret to first position on display line.
void HomeDisplayExtend ()
Move caret to first position on display line extending selection to new caret position.
void LineEndDisplay ()
Move caret to last position on display line.
void LineEndDisplayExtend ()
Move caret to last position on display line extending selection to new caret position.
void HomeWrap ()
Like Home but when word-wrap is enabled goes first to start of display line HomeDisplay, then to start of document line Home.
void HomeWrapExtend ()
Like HomeExtend but when word-wrap is enabled extends first to start of display line HomeDisplayExtend, then to start of document line HomeExtend.
void LineEndWrap ()
Like LineEnd but when word-wrap is enabled goes first to end of display line LineEndDisplay, then to start of document line LineEnd.
void LineEndWrapExtend ()
Like LineEndExtend but when word-wrap is enabled extends first to end of display line LineEndDisplayExtend, then to start of document line LineEndExtend.
void VCHomeWrap ()
Like VCHome but when word-wrap is enabled goes first to start of display line VCHomeDisplay, then behaves like VCHome.
void VCHomeWrapExtend ()
Like VCHomeExtend but when word-wrap is enabled extends first to start of display line VCHomeDisplayExtend, then behaves like VCHomeExtend.
void LineCopy ()
Copy the line containing the caret.
void MoveCaretInsideView ()
Move the caret inside current view if it's not there already.
int LineLength (int line) const
How many characters are on a line, including end of line characters?
void BraceHighlight (int posA, int posB)
Highlight the characters at two positions.
void BraceHighlightIndicator (bool useSetting, int indicator)
Use specified indicator to highlight matching braces instead of changing their style.
void BraceBadLight (int pos)
Highlight the character at a position indicating there is no matching brace.
void BraceBadLightIndicator (bool useSetting, int indicator)
Use specified indicator to highlight non matching brace instead of changing its style.
int BraceMatch (int pos, int maxReStyle=0)
Find the position of a matching brace or wxSCI_INVALID_POSITION if no match.
bool GetViewEOL () const
Are the end of line characters visible?
void SetViewEOL (bool visible)
Make the end of line characters visible or invisible.
void * GetDocPointer ()
Retrieve a pointer to the document object.
void SetDocPointer (void *docPointer)
Change the document object used.
void SetModEventMask (int eventMask)
Set which document modification events are sent to the container.
int GetEdgeColumn () const
Retrieve the column number which text should be kept within.
void SetEdgeColumn (int column)
Set the column number of the edge.
int GetEdgeMode () const
Retrieve the edge highlight mode.
void SetEdgeMode (int edgeMode)
The edge may be displayed by a line (wxSCI_EDGE_LINE/wxSCI_EDGE_MULTILINE) or by highlighting text that goes beyond it (wxSCI_EDGE_BACKGROUND) or not displayed at all (wxSCI_EDGE_NONE).
wxColour GetEdgeColour () const
Retrieve the colour used in edge indication.
void SetEdgeColour (const wxColour &edgeColour)
Change the colour used in edge indication.
void MultiEdgeAddLine (int column, const wxColour &edgeColour)
Add a new vertical edge to the view.
void MultiEdgeClearAll ()
Clear all vertical edges.
void SearchAnchor ()
Sets the current caret position to be the search anchor.
int SearchNext (int searchFlags, const wxString &text)
Find some text starting at the search anchor.
int SearchPrev (int searchFlags, const wxString &text)
Find some text starting at the search anchor and moving backwards.
int LinesOnScreen () const
Retrieves the number of lines completely visible.
void UsePopUp (int popUpMode)
Set whether a pop up menu is displayed automatically when the user presses the wrong mouse button on certain areas.
bool SelectionIsRectangle () const
Is the selection rectangular? The alternative is the more common stream selection.
void SetZoom (int zoomInPoints)
Set the zoom level.
int GetZoom () const
Retrieve the zoom level.
void * CreateDocument ()
Create a new document object.
void AddRefDocument (void *docPointer)
Extend life of document.
void ReleaseDocument (void *docPointer)
Release a reference to the document, deleting document if it fades to black.
int GetModEventMask () const
Get which document modification events are sent to the container.
void SetSCIFocus (bool focus)
Change internal focus flag.
bool GetSCIFocus () const
Get internal focus flag.
void SetStatus (int status)
Change error status - 0 = OK.
int GetStatus () const
Get error status.
void SetMouseDownCaptures (bool captures)
Set whether the mouse is captured when its button is pressed.
bool GetMouseDownCaptures () const
Get whether mouse gets captured.
void SetMouseWheelCaptures (bool captures)
Set whether the mouse wheel can be active outside the window.
bool GetMouseWheelCaptures () const
Get whether mouse wheel can be active outside the window.
void SetSCICursor (int cursorType)
Sets the cursor to one of the wxSCI_CURSOR* values.
int GetSCICursor () const
Get cursor type.
void SetControlCharSymbol (int symbol)
Change the way control characters are displayed: If symbol is < 32, keep the drawn way, else, use the given character.
int GetControlCharSymbol () const
Get the way control characters are displayed.
void WordPartLeft ()
Move to the previous change in capitalisation.
void WordPartLeftExtend ()
Move to the previous change in capitalisation extending selection to new caret position.
void WordPartRight ()
Move to the change next in capitalisation.
void WordPartRightExtend ()
Move to the next change in capitalisation extending selection to new caret position.
void SetVisiblePolicy (int visiblePolicy, int visibleSlop)
Set the way the display area is determined when a particular line is to be moved to by Find, FindNext, GotoLine, etc.
void DelLineLeft ()
Delete back from the current position to the start of the line.
void DelLineRight ()
Delete forwards from the current position to the end of the line.
void SetXOffset (int xOffset)
Set the xOffset (ie, horizontal scroll position).
int GetXOffset () const
Get the xOffset (ie, horizontal scroll position).
void ChooseCaretX ()
Set the last x chosen value to be the caret x position.
void SetXCaretPolicy (int caretPolicy, int caretSlop)
Set the way the caret is kept visible when going sideways.
void SetYCaretPolicy (int caretPolicy, int caretSlop)
Set the way the line the caret is on is kept visible.
void SetPrintWrapMode (int wrapMode)
Set printing to line wrapped (wxSCI_WRAP_WORD) or not line wrapped (wxSCI_WRAP_NONE).
int GetPrintWrapMode () const
Is printing line wrapped?
void SetHotspotActiveForeground (bool useSetting, const wxColour &fore)
Set a fore colour for active hotspots.
wxColour GetHotspotActiveForeground () const
Get the fore colour for active hotspots.
void SetHotspotActiveBackground (bool useSetting, const wxColour &back)
Set a back colour for active hotspots.
wxColour GetHotspotActiveBackground () const
Get the back colour for active hotspots.
void SetHotspotActiveUnderline (bool underline)
Enable / Disable underlining active hotspots.
bool GetHotspotActiveUnderline () const
Get whether underlining for active hotspots.
void SetHotspotSingleLine (bool singleLine)
Limit hotspots to single line so hotspots on two lines don't merge.
bool GetHotspotSingleLine () const
Get the HotspotSingleLine property.
void ParaDown ()
Move caret down one paragraph (delimited by empty lines).
void ParaDownExtend ()
Extend selection down one paragraph (delimited by empty lines).
void ParaUp ()
Move caret up one paragraph (delimited by empty lines).
void ParaUpExtend ()
Extend selection up one paragraph (delimited by empty lines).
int PositionBefore (int pos)
Given a valid document position, return the previous position taking code page into account.
int PositionAfter (int pos)
Given a valid document position, return the next position taking code page into account.
int PositionRelative (int pos, int relative)
Given a valid document position, return a position that differs in a number of characters.
void CopyRange (int start, int end)
Copy a range of text to the clipboard. Positions are clipped into the document.
void CopyText (int length, const wxString &text)
Copy argument text to the clipboard.
void SetSelectionMode (int selectionMode)
Set the selection mode to stream (wxSCI_SEL_STREAM) or rectangular (wxSCI_SEL_RECTANGLE/wxSCI_SEL_THIN) or by lines (wxSCI_SEL_LINES).
int GetSelectionMode () const
Get the mode of the current selection.
int GetLineSelStartPosition (int line)
Retrieve the position of the start of the selection at the given line (wxSCI_INVALID_POSITION if no selection on this line).
int GetLineSelEndPosition (int line)
Retrieve the position of the end of the selection at the given line (wxSCI_INVALID_POSITION if no selection on this line).
void LineDownRectExtend ()
Move caret down one line, extending rectangular selection to new caret position.
void LineUpRectExtend ()
Move caret up one line, extending rectangular selection to new caret position.
void CharLeftRectExtend ()
Move caret left one character, extending rectangular selection to new caret position.
void CharRightRectExtend ()
Move caret right one character, extending rectangular selection to new caret position.
void HomeRectExtend ()
Move caret to first position on line, extending rectangular selection to new caret position.
void VCHomeRectExtend ()
Move caret to before first visible character on line.
void LineEndRectExtend ()
Move caret to last position on line, extending rectangular selection to new caret position.
void PageUpRectExtend ()
Move caret one page up, extending rectangular selection to new caret position.
void PageDownRectExtend ()
Move caret one page down, extending rectangular selection to new caret position.
void StutteredPageUp ()
Move caret to top of page, or one page up if already at top of page.
void StutteredPageUpExtend ()
Move caret to top of page, or one page up if already at top of page, extending selection to new caret position.
void StutteredPageDown ()
Move caret to bottom of page, or one page down if already at bottom of page.
void StutteredPageDownExtend ()
Move caret to bottom of page, or one page down if already at bottom of page, extending selection to new caret position.
void WordLeftEnd ()
Move caret left one word, position cursor at end of word.
void WordLeftEndExtend ()
Move caret left one word, position cursor at end of word, extending selection to new caret position.
void WordRightEnd ()
Move caret right one word, position cursor at end of word.
void WordRightEndExtend ()
Move caret right one word, position cursor at end of word, extending selection to new caret position.
void SetWhitespaceChars (const wxString &characters)
Set the set of characters making up whitespace for when moving or selecting by word.
wxString GetWhitespaceChars () const
Get the set of characters making up whitespace for when moving or selecting by word.
void SetPunctuationChars (const wxString &characters)
Set the set of characters making up punctuation characters Should be called after SetWordChars.
wxString GetPunctuationChars () const
Get the set of characters making up punctuation characters.
void SetCharsDefault ()
Reset the set of characters for whitespace and word characters to the defaults.
int AutoCompGetCurrent () const
Get currently selected item position in the auto-completion list.
wxString AutoCompGetCurrentText () const
Get currently selected item text in the auto-completion list.
void AutoCompSetCaseInsensitiveBehaviour (int behaviour)
Set auto-completion case insensitive behaviour to either prefer case-sensitive matches or have no preference.
int AutoCompGetCaseInsensitiveBehaviour () const
Get auto-completion case insensitive behaviour.
void AutoCompSetMulti (int multi)
Change the effect of autocompleting when there are multiple selections.
int AutoCompGetMulti () const
Retrieve the effect of autocompleting when there are multiple selections.
void AutoCompSetOrder (int order)
Set the way autocompletion lists are ordered.
int AutoCompGetOrder () const
Get the way autocompletion lists are ordered.
void Allocate (int bytes)
Enlarge the document to a particular size of text bytes.
int FindColumn (int line, int column)
Find the position of a column on a line taking into account tabs and multi-byte characters.
int GetCaretSticky () const
Can the caret preferred x position only be changed by explicit movement commands?
void SetCaretSticky (int useCaretStickyBehaviour)
Stop the caret preferred x position changing when the user types.
void ToggleCaretSticky ()
Switch between sticky and non-sticky: meant to be bound to a key.
void SetPasteConvertEndings (bool convert)
Enable/Disable convert-on-paste for line endings.
bool GetPasteConvertEndings () const
Get convert-on-paste setting.
void SelectionDuplicate ()
Duplicate the selection. If selection empty duplicate the line containing the caret.
void SetCaretLineBackAlpha (int alpha)
Set background alpha of the caret line.
int GetCaretLineBackAlpha () const
Get the background alpha of the caret line.
void SetCaretStyle (int caretStyle)
Set the style of the caret to be drawn.
int GetCaretStyle () const
Returns the current style of the caret.
void SetIndicatorCurrent (int indicator)
Set the indicator used for IndicatorFillRange and IndicatorClearRange.
int GetIndicatorCurrent () const
Get the current indicator.
void SetIndicatorValue (int value)
Set the value used for IndicatorFillRange.
int GetIndicatorValue () const
Get the current indicator value.
void IndicatorFillRange (int start, int lengthFill)
Turn a indicator on over a range.
void IndicatorClearRange (int start, int lengthClear)
Turn a indicator off over a range.
int IndicatorAllOnFor (int pos)
Are any indicators present at pos?
int IndicatorValueAt (int indicator, int pos)
What value does a particular indicator have at a position?
int IndicatorStart (int indicator, int pos)
Where does a particular indicator start?
int IndicatorEnd (int indicator, int pos)
Where does a particular indicator end?
void SetPositionCacheSize (int size)
Set number of entries in position cache.
int GetPositionCacheSize () const
How many entries are allocated to the position cache?
void CopyAllowLine ()
Copy the selection, if selection empty copy the line with the caret.
const char * GetRangePointer (int position, int rangeLength) const
Return a read-only pointer to a range of characters in the document.
int GetGapPosition () const
Return a position which, to avoid performance costs, should not be within the range of a call to GetRangePointer.
void IndicatorSetAlpha (int indicator, int alpha)
Set the alpha fill colour of the given indicator.
int IndicatorGetAlpha (int indicator) const
Get the alpha fill colour of the given indicator.
void IndicatorSetOutlineAlpha (int indicator, int alpha)
Set the alpha outline colour of the given indicator.
int IndicatorGetOutlineAlpha (int indicator) const
Get the alpha outline colour of the given indicator.
void SetExtraAscent (int extraAscent)
Set extra ascent for each line.
int GetExtraAscent () const
Get extra ascent for each line.
void SetExtraDescent (int extraDescent)
Set extra descent for each line.
int GetExtraDescent () const
Get extra descent for each line.
int GetMarkerSymbolDefined (int markerNumber)
Which symbol was defined for markerNumber with MarkerDefine.
void MarginSetText (int line, const wxString &text)
Set the text in the text margin for a line.
wxString MarginGetText (int line) const
Get the text in the text margin for a line.
void MarginSetStyle (int line, int style)
Set the style number for the text margin for a line.
int MarginGetStyle (int line) const
Get the style number for the text margin for a line.
void MarginSetStyles (int line, const wxString &styles)
Set the style in the text margin for a line.
wxString MarginGetStyles (int line) const
Get the styles in the text margin for a line.
void MarginTextClearAll ()
Clear the margin text on all lines.
void MarginSetStyleOffset (int style)
Get the start of the range of style numbers used for margin text.
int MarginGetStyleOffset () const
Get the start of the range of style numbers used for margin text.
void SetMarginOptions (int marginOptions)
Set the margin options.
int GetMarginOptions () const
Get the margin options.
void AnnotationSetText (int line, const wxString &text)
Set the annotation text for a line.
wxString AnnotationGetText (int line) const
Get the annotation text for a line.
void AnnotationSetStyle (int line, int style)
Set the style number for the annotations for a line.
int AnnotationGetStyle (int line) const
Get the style number for the annotations for a line.
void AnnotationSetStyles (int line, const wxString &styles)
Set the annotation styles for a line.
wxString AnnotationGetStyles (int line) const
Get the annotation styles for a line.
int AnnotationGetLines (int line) const
Get the number of annotation lines for a line.
void AnnotationClearAll ()
Clear the annotations from all lines.
void AnnotationSetVisible (int visible)
Set the visibility for the annotations for a view.
int AnnotationGetVisible () const
Get the visibility for the annotations for a view.
void AnnotationSetStyleOffset (int style)
Get the start of the range of style numbers used for annotations.
int AnnotationGetStyleOffset () const
Get the start of the range of style numbers used for annotations.
void ReleaseAllExtendedStyles ()
Release all extended (>255) style numbers.
int AllocateExtendedStyles (int numberStyles)
Allocate some extended (>255) style numbers and return the start of the range.
void AddUndoAction (int token, int flags)
Add a container action to the undo stack.
int CharPositionFromPoint (int x, int y)
Find the position of a character from a point within the window.
int CharPositionFromPointClose (int x, int y)
Find the position of a character from a point within the window.
void SetMouseSelectionRectangularSwitch (bool mouseSelectionRectangularSwitch)
Set whether switching to rectangular mode while selecting with the mouse is allowed.
bool GetMouseSelectionRectangularSwitch () const
Whether switching to rectangular mode while selecting with the mouse is allowed.
void SetMultipleSelection (bool multipleSelection)
Set whether multiple selections can be made.
bool GetMultipleSelection () const
Whether multiple selections can be made.
void SetAdditionalSelectionTyping (bool additionalSelectionTyping)
Set whether typing can be performed into multiple selections.
bool GetAdditionalSelectionTyping () const
Whether typing can be performed into multiple selections.
void SetAdditionalCaretsBlink (bool additionalCaretsBlink)
Set whether additional carets will blink.
bool GetAdditionalCaretsBlink () const
Whether additional carets will blink.
void SetAdditionalCaretsVisible (bool additionalCaretsVisible)
Set whether additional carets are visible.
bool GetAdditionalCaretsVisible () const
Whether additional carets are visible.
int GetSelections () const
How many selections are there?
bool GetSelectionEmpty () const
Is every selected range empty?
void ClearSelections ()
Clear selections to a single empty stream selection.
void SetSelectionVoid (int startPos, int endPos)
Select a range of text.
int SetSelectionInt (int caret, int anchor)
Set a simple selection.
int AddSelection (int caret, int anchor)
Add a selection.
void DropSelectionN (int selection)
Drop one selection.
void SetMainSelection (int selection)
Set the main selection.
int GetMainSelection () const
Which selection is the main selection.
void SetSelectionNCaret (int selection, int caret)
Set the caret position of the nth selection.
int GetSelectionNCaret (int selection) const
Return the caret position of the nth selection.
void SetSelectionNAnchor (int selection, int anchor)
Set the anchor position of the nth selection.
int GetSelectionNAnchor (int selection) const
Return the anchor position of the nth selection.
void SetSelectionNCaretVirtualSpace (int selection, int space)
Set the virtual space of the caret of the nth selection.
int GetSelectionNCaretVirtualSpace (int selection) const
Return the virtual space of the caret of the nth selection.
void SetSelectionNAnchorVirtualSpace (int selection, int space)
Set the virtual space of the anchor of the nth selection.
int GetSelectionNAnchorVirtualSpace (int selection) const
Return the virtual space of the anchor of the nth selection.
void SetSelectionNStart (int selection, int anchor)
Sets the position that starts the selection - this becomes the anchor.
int GetSelectionNStart (int selection) const
Returns the position at the start of the selection.
void SetSelectionNEnd (int selection, int caret)
Sets the position that ends the selection - this becomes the currentPosition.
int GetSelectionNEnd (int selection) const
Returns the position at the end of the selection.
void SetRectangularSelectionCaret (int caret)
Set the caret position of the rectangular selection.
int GetRectangularSelectionCaret () const
Return the caret position of the rectangular selection.
void SetRectangularSelectionAnchor (int anchor)
Set the anchor position of the rectangular selection.
int GetRectangularSelectionAnchor () const
Return the anchor position of the rectangular selection.
void SetRectangularSelectionCaretVirtualSpace (int space)
Set the virtual space of the caret of the rectangular selection.
int GetRectangularSelectionCaretVirtualSpace () const
Return the virtual space of the caret of the rectangular selection.
void SetRectangularSelectionAnchorVirtualSpace (int space)
Set the virtual space of the anchor of the rectangular selection.
int GetRectangularSelectionAnchorVirtualSpace () const
Return the virtual space of the anchor of the rectangular selection.
void SetVirtualSpaceOptions (int virtualSpaceOptions)
Set options for virtual space behaviour.
int GetVirtualSpaceOptions () const
Return options for virtual space behaviour.
void SetRectangularSelectionModifier (int modifier)
On GTK+, allow selecting the modifier key to use for mouse-based rectangular selection.
int GetRectangularSelectionModifier () const
Get the modifier key used for rectangular selection.
void SetAdditionalSelForeground (const wxColour &fore)
Set the foreground colour of additional selections.
void SetAdditionalSelBackground (const wxColour &back)
Set the background colour of additional selections.
void SetAdditionalSelAlpha (int alpha)
Set the alpha of the selection.
int GetAdditionalSelAlpha () const
Get the alpha of the selection.
void SetAdditionalCaretForeground (const wxColour &fore)
Set the foreground colour of additional carets.
wxColour GetAdditionalCaretForeground () const
Get the foreground colour of additional carets.
void RotateSelection ()
Set the main selection to the next selection.
void SwapMainAnchorCaret ()
Swap that caret and anchor of the main selection.
void MultipleSelectAddNext ()
Add the next occurrence of the main selection to the set of selections as main.
void MultipleSelectAddEach ()
Add each occurrence of the main selection in the target to the set of selections.
int ChangeLexerState (int start, int end)
Indicate that the internal state of a lexer has changed over a range and therefore there may be a need to redraw.
int ContractedFoldNext (int lineStart)
Find the next line at or after lineStart that is a contracted fold header line.
void VerticalCentreCaret ()
Centre current line in window.
void MoveSelectedLinesUp ()
Move the selected lines up one line, shifting the line above after the selection.
void MoveSelectedLinesDown ()
Move the selected lines down one line, shifting the line below before the selection.
void SetIdentifier (int identifier)
Set the identifier reported as idFrom in notification messages.
int GetIdentifier () const
Get the identifier.
void RGBAImageSetWidth (int width)
Set the width for future RGBA image data.
void RGBAImageSetHeight (int height)
Set the height for future RGBA image data.
void RGBAImageSetScale (int scalePercent)
Set the scale factor in percent for future RGBA image data.
void MarkerDefineRGBAImage (int markerNumber, const unsigned char *pixels)
Define a marker from RGBA data.
void RegisterRGBAImage (int type, const unsigned char *pixels)
Register an RGBA image for use in autocompletion lists.
void ScrollToStart ()
Scroll to start of document.
void ScrollToEnd ()
Scroll to end of document.
void SetTechnology (int technology)
Set the technology used.
int GetTechnology () const
Get the tech.
void * CreateLoader (int bytes) const
Create an ILoader*.
void VCHomeDisplay ()
Move caret to before first visible character on display line.
void VCHomeDisplayExtend ()
Like VCHomeDisplay but extending selection to new caret position.
bool GetCaretLineVisibleAlways () const
Is the caret line always visible?
void SetCaretLineVisibleAlways (bool alwaysVisible)
Sets the caret line to always visible.
void SetLineEndTypesAllowed (int lineEndBitSet)
Set the line end types that the application wants to use. May not be used if incompatible with lexer or encoding.
int GetLineEndTypesAllowed () const
Get the line end types currently allowed.
int GetLineEndTypesActive () const
Get the line end types currently recognised. May be a subset of the allowed types due to lexer limitation.
void SetRepresentation (const wxString &encodedCharacter, const wxString &representation)
Set the way a character is drawn.
wxString GetRepresentation (const wxString &encodedCharacter) const
Set the way a character is drawn.
void ClearRepresentation (const wxString &encodedCharacter)
Remove a character representation.
void StartRecord ()
Start notifying the container of all key presses and commands.
void StopRecord ()
Stop notifying the container of all key presses and commands.
void SetLexer (int lexer)
Set the lexing language of the document.
int GetLexer () const
Retrieve the lexing language of the document.
void Colourise (int start, int end)
Colourise a segment of the document using the current lexing language.
void SetProperty (const wxString &key, const wxString &value)
Set up a value that may be used by a lexer for some optional feature.
void SetKeyWords (int keyWordSet, const wxString &keyWords)
Set up the key words used by the lexer.
void SetLexerLanguage (const wxString &language)
Set the lexing language of the document based on string name.
void LoadLexerLibrary (const wxString &path)
Load a lexer library (dll / so).
wxString GetProperty (const wxString &key)
Retrieve a "property" value previously set with SetProperty.
wxString GetPropertyExpanded (const wxString &key)
Retrieve a "property" value previously set with SetProperty, with "$()" variable replacement on returned buffer.
int GetPropertyInt (const wxString &key, int defaultValue=0) const
Retrieve a "property" value previously set with SetProperty, interpreted as an int AFTER any "$()" variable replacement.
wxDEPRECATED_MSG ("This method uses a function deprecated in the Scintilla library.") int GetStyleBitsNeeded() const
Retrieve the number of bits the current lexer needs for styling.
wxString GetLexerLanguage () const
Retrieve the lexing language of the document.
void * PrivateLexerCall (int operation, void *pointer)
For private communication between an application and a known lexer.
wxString PropertyNames () const
Retrieve a '\n' separated list of properties understood by the current lexer.
int PropertyType (const wxString &name)
Retrieve the type of a property.
wxString DescribeProperty (const wxString &name) const
Describe a property.
wxString DescribeKeyWordSets () const
Retrieve a '\n' separated list of descriptions of the keyword sets understood by the current lexer.
int GetLineEndTypesSupported () const
Bit set of LineEndType enumertion for which line ends beyond the standard LF, CR, and CRLF are supported by the lexer.
int AllocateSubStyles (int styleBase, int numberStyles)
Allocate a set of sub styles for a particular base style, returning start of range.
int GetSubStylesStart (int styleBase) const
The starting style number for the sub styles associated with a base style.
int GetSubStylesLength (int styleBase) const
The number of sub styles associated with a base style.
int GetStyleFromSubStyle (int subStyle) const
For a sub style, return the base style, else return the argument.
int GetPrimaryStyleFromStyle (int style) const
For a secondary style, return the primary style, else return the argument.
void FreeSubStyles ()
Free allocated sub styles.
void SetIdentifiers (int style, const wxString &identifiers)
Set the identifiers that are shown in a particular style.
int DistanceToSecondaryStyles () const
Where styles are duplicated by a feature such as active/inactive code return the distance between the two types.
wxString GetSubStyleBases () const
Get the set of base styles that can be extended with sub styles.
int GetCurrentLine ()
Manually declared methods.
void StyleSetSpec (int styleNum, const wxString &spec)
Extract style settings from a spec-string which is composed of one or more of the following comma separated elements:
wxFont StyleGetFont (int style)
Get the font of a style.
void StyleSetFont (int styleNum, const wxFont &font)
Set style size, face, bold, italic, and underline attributes from a wxFont's attributes.
void StyleSetFontAttr (int styleNum, int size, const wxString &faceName, bool bold, bool italic, bool underline, wxFontEncoding encoding=wxFONTENCODING_DEFAULT)
Set all font style attributes at once.
void StyleSetFontEncoding (int style, wxFontEncoding encoding)
Set the font encoding to be used by a style.
void CmdKeyExecute (int cmd)
Perform one of the operations defined by the wxSCI_CMD_* constants.
void SetMargins (int left, int right)
Set the left and right margin in the edit area, measured in pixels.
void ScrollToLine (int line)
Scroll enough to make the given line visible.
void ScrollToColumn (int column)
Scroll enough to make the given column visible.
wxIntPtr SendMsg (int msg, wxUIntPtr wp=0, wxIntPtr lp=0) const
Send a message to Scintilla.
void SetVScrollBar (wxScrollBar *bar)
Set the vertical scrollbar to use instead of the one that's built-in.
void SetHScrollBar (wxScrollBar *bar)
Set the horizontal scrollbar to use instead of the one that's built-in.
bool GetLastKeydownProcessed ()
Can be used to prevent the EVT_CHAR handler from adding the char.
void SetLastKeydownProcessed (bool val)
bool SaveFile (const wxString &filename)
Write the contents of the editor to filename.
bool LoadFile (const wxString &filename)
Load the contents of filename into the editor.
wxDragResult DoDragEnter (wxCoord x, wxCoord y, wxDragResult def)
Allow for simulating a DnD DragEnter.
wxDragResult DoDragOver (wxCoord x, wxCoord y, wxDragResult def)
Allow for simulating a DnD DragOver.
void DoDragLeave ()
Allow for simulating a DnD DragLeave.
bool DoDropText (long x, long y, const wxString &data)
Allow for simulating a DnD DropText.
void SetUseAntiAliasing (bool useAA)
Specify whether anti-aliased fonts should be used.
bool GetUseAntiAliasing ()
Returns the current UseAntiAliasing setting.
void AnnotationClearLine (int line)
Clear annotations from the given line.
void AddTextRaw (const char *text, int length=-1)
The following methods are nearly equivalent to their similarly named cousins above.
void InsertTextRaw (int pos, const char *text)
Insert string at a position.
wxCharBuffer GetCurLineRaw (int *linePos=NULL)
Retrieve the text of the line containing the caret.
wxCharBuffer GetLineRaw (int line)
Retrieve the contents of a line.
wxCharBuffer GetSelectedTextRaw ()
Retrieve the selected text.
wxCharBuffer GetTargetTextRaw ()
Retrieve the target text.
wxCharBuffer GetTextRangeRaw (int startPos, int endPos)
Retrieve a range of text.
void SetTextRaw (const char *text)
Replace the contents of the document with the argument text.
wxCharBuffer GetTextRaw ()
Retrieve all the text in the document.
void AppendTextRaw (const char *text, int length=-1)
Append a string to the end of the document without changing the selection.
virtual void WriteText (const wxString &text)
implement wxTextEntryBase pure virtual methods
virtual void Remove (long from, long to)
virtual void Replace (long from, long to, const wxString &text)
virtual void SetInsertionPoint (long pos)
virtual long GetInsertionPoint () const
virtual long GetLastPosition () const
virtual void SetSelection (long from, long to)
virtual void SelectNone ()
virtual void GetSelection (long *from, long *to) const
void GetSelection (int *from, int *to)
kept for compatibility only
virtual bool IsEditable () const
virtual void SetEditable (bool editable)
void SetMouseCapture (bool on)
bool HaveMouseCapture () const
Static Public Member Functions
static std::map< int, std::set< int > > & GetCharacterLexerStyles ()
static std::map< int, std::set< int > > & GetStringLexerStyles ()
static std::map< int, std::set< int > > & GetPreprocessorLexerStyles ()
static std::map< int, std::set< int > > & GetCommentLexerStyles ()
Static Public Member Functions inherited from wxScintilla
static wxVersionInfo GetLibraryVersionInfo ()
Private Member Functions
void OnContextMenu (wxContextMenuEvent &event)
void OnKillFocus (wxFocusEvent &event)
void OnSetFocus (wxFocusEvent &event)
void OnMouseMiddleDown (wxMouseEvent &event)
void OnKeyDown (wxKeyEvent &event)
void OnKeyUp (wxKeyEvent &event)
void OnMouseLeftUp (wxMouseEvent &event)
bool AllowTabSmartJump ()
void HighlightRightBrace ()
void EmulateDwellStart ()
Private Attributes
wxWindow * m_pParent
wxLongLong m_lastFocusTime
int m_bracePosition
int m_lastPosition
bool m_tabSmartJump
wxString m_lastSelectedText
bool m_braceShortcutState
Static Private Attributes
static std::map< int, std::set< int > > CharacterLexerStyles
static std::map< int, std::set< int > > StringLexerStyles
static std::map< int, std::set< int > > PreprocessorLexerStyles
static std::map< int, std::set< int > > CommentLexerStyles
Additional Inherited Members
Protected Member Functions inherited from wxScintilla
wxString GetValue () const
void SetValue (const wxString &text)
virtual void DoSetValue (const wxString &value, int flags)
virtual wxString DoGetValue () const
virtual wxWindow * GetEditableWindow ()
virtual bool DoLoadFile (const wxString &file, int fileType)
virtual bool DoSaveFile (const wxString &file, int fileType)
void OnPaint (wxPaintEvent &evt)
Event handlers.
void OnScrollWin (wxScrollWinEvent &evt)
void OnScroll (wxScrollEvent &evt)
void OnSize (wxSizeEvent &evt)
void OnMouseLeftDown (wxMouseEvent &evt)
void OnMouseRightDown (wxMouseEvent &evt)
void OnMouseMove (wxMouseEvent &evt)
void OnMouseLeftUp (wxMouseEvent &evt)
void OnMouseRightUp (wxMouseEvent &evt)
void OnMouseMiddleUp (wxMouseEvent &evt)
void OnContextMenu (wxContextMenuEvent &evt)
void OnMouseWheel (wxMouseEvent &evt)
void OnChar (wxKeyEvent &evt)
void OnKeyDown (wxKeyEvent &evt)
void OnLoseFocus (wxFocusEvent &evt)
void OnGainFocus (wxFocusEvent &evt)
void OnSysColourChanged (wxSysColourChangedEvent &evt)
void OnEraseBackground (wxEraseEvent &evt)
void OnMenu (wxCommandEvent &evt)
void OnListBox (wxCommandEvent &evt)
void OnIdle (wxIdleEvent &evt)
void OnMouseCaptureLost (wxMouseCaptureLostEvent &evt)
virtual wxSize DoGetBestSize () const override
void NotifyChange ()
Turn notifications from Scintilla into events.
void NotifyParent (SCNotification *scn)
Protected Attributes inherited from wxScintilla
ScintillaWX * m_swx
wxStopWatch m_stopWatch
wxScrollBar * m_vScrollBar
wxScrollBar * m_hScrollBar
bool m_lastKeyDownConsumed
Detailed Description
Definition at line 21 of file cbstyledtextctrl.h.
Constructor & Destructor Documentation
cbStyledTextCtrl()
cbStyledTextCtrl::cbStyledTextCtrl (wxWindow * pParent, int id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
Definition at line 45 of file cbstyledtextctrl.cpp.
~cbStyledTextCtrl()
cbStyledTextCtrl::~cbStyledTextCtrl () override
Definition at line 57 of file cbstyledtextctrl.cpp.
Member Function Documentation
AllowTabSmartJump()
bool cbStyledTextCtrl::AllowTabSmartJump () private
Definition at line 402 of file cbstyledtextctrl.cpp.
References wxScintilla::GetCurrentPos(), wxScintilla::GetStyleAt(), IsCharacter(), IsComment(), IsPreprocessor(), IsString(), m_tabSmartJump, and wxSCI_INVALID_POSITION.
Referenced by OnKeyUp().
CallTipCancel()
void cbStyledTextCtrl::CallTipCancel ()
Cancel calltip only if not jumping braces via tab.
Definition at line 323 of file cbstyledtextctrl.cpp.
References wxScintilla::CallTipCancel(), and m_tabSmartJump.
Referenced by CCManager::DoShowTips(), CCManager::OnDeactivateEd(), OnKeyDown(), OnKillFocus(), cbDebuggerPlugin::ProcessValueTooltip(), and DebugInterfaceFactory::ShowValueTooltip().
DoBraceCompletion()
void cbStyledTextCtrl::DoBraceCompletion (const wxChar & ch)
Automated braces/quotes completion.
Add a close brace when an open brace is typed, but there is not already a following close brace. Allow typing a brace/quote to overwrite if it is already the next character in the editor.
Parameters
ch The last character typed.
Definition at line 336 of file cbstyledtextctrl.cpp.
References wxScintilla::BraceMatch(), wxScintilla::CharRight(), wxScintilla::DeleteBack(), wxString::Find(), wxScintilla::GetCharAt(), wxScintilla::GetCurrentPos(), wxScintilla::GetLength(), wxScintilla::GetStyleAt(), wxScintilla::InsertText(), IsCharacter(), IsComment(), IsString(), wxIsspace(), wxNOT_FOUND, and wxT.
Referenced by cbEditor::OnEditorCharAdded().
DoSelectionBraceCompletion()
bool cbStyledTextCtrl::DoSelectionBraceCompletion (const wxChar & ch)
Put braces/quotes around the current selection in the editor.
Parameters
ch The last character typed.
Returns
True if selection brace completion was applicable and edited the text.
Definition at line 381 of file cbstyledtextctrl.cpp.
References wxScintilla::AddText(), wxScintilla::BeginUndoAction(), wxScintilla::DeleteBack(), wxScintilla::EndUndoAction(), wxString::Find(), wxScintilla::GetCurrentPos(), GetLastSelectedText(), wxScintilla::GetSelections(), wxScintilla::InsertText(), wxString::Length(), wxNOT_FOUND, and wxT.
Referenced by cbEditor::OnEditorCharAdded().
EmulateDwellStart()
void cbStyledTextCtrl::EmulateDwellStart () private
Definition at line 482 of file cbstyledtextctrl.cpp.
References cbEVT_EDITOR_TOOLTIP, Manager::Get(), Manager::GetPluginManager(), wxScintilla::GetStyleAt(), m_pParent, PluginManager::NotifyPlugins(), wxScintilla::PositionFromPoint(), wxGetMousePosition(), wxPoint::x, and wxPoint::y.
Referenced by OnKeyDown().
EnableTabSmartJump()
void cbStyledTextCtrl::EnableTabSmartJump (bool enable = true)
Definition at line 498 of file cbstyledtextctrl.cpp.
References wxScintilla::GetCurrentPos(), HighlightRightBrace(), m_bracePosition, and m_tabSmartJump.
GetCharacterLexerStyles()
std::map< int, std::set< int > > & cbStyledTextCtrl::GetCharacterLexerStyles () static
Definition at line 505 of file cbstyledtextctrl.cpp.
References CharacterLexerStyles.
Referenced by EditorColourSet::SetCharacterLexerStyles().
GetCommentLexerStyles()
std::map< int, std::set< int > > & cbStyledTextCtrl::GetCommentLexerStyles () static
Definition at line 520 of file cbstyledtextctrl.cpp.
References CommentLexerStyles.
Referenced by EditorColourSet::SetCommentLexerStyles().
GetLastFocusTime()
wxDateTime cbStyledTextCtrl::GetLastFocusTime () const inline
Definition at line 30 of file cbstyledtextctrl.h.
Referenced by cbEditor::GetControl().
GetLastSelectedText()
wxString cbStyledTextCtrl::GetLastSelectedText () const inline
Definition at line 31 of file cbstyledtextctrl.h.
References wxScintilla::CallTipCancel(), wxScintilla::OnContextMenu(), wxScintilla::OnKeyDown(), and wxScintilla::OnMouseLeftUp().
Referenced by DoSelectionBraceCompletion().
GetPreprocessorLexerStyles()
std::map< int, std::set< int > > & cbStyledTextCtrl::GetPreprocessorLexerStyles () static
Definition at line 515 of file cbstyledtextctrl.cpp.
References PreprocessorLexerStyles.
Referenced by EditorColourSet::SetPreprocessorLexerStyles().
GetStringLexerStyles()
std::map< int, std::set< int > > & cbStyledTextCtrl::GetStringLexerStyles () static
Definition at line 510 of file cbstyledtextctrl.cpp.
References StringLexerStyles.
Referenced by EditorColourSet::SetStringLexerStyles().
HighlightRightBrace()
void cbStyledTextCtrl::HighlightRightBrace () private
Definition at line 414 of file cbstyledtextctrl.cpp.
References _T, wxString::Contains(), wxScintilla::GetCaretForeground(), wxScintilla::GetCaretWidth(), wxScintilla::GetCharAt(), wxScintilla::GetCurrentLine(), wxScintilla::GetCurrentPos(), wxScintilla::GetLength(), wxScintilla::GetLineEndPosition(), wxScintilla::GetLineIndentPosition(), wxScintilla::GetStyleAt(), wxScintilla::IndicatorClearRange(), wxScintilla::IndicatorFillRange(), wxScintilla::IndicatorSetForeground(), wxScintilla::IndicatorSetStyle(), wxScintilla::IndicatorSetUnder(), IsCharacter(), IsComment(), IsString(), wxScintilla::LineFromPosition(), m_bracePosition, m_lastPosition, m_tabSmartJump, s_indicHighlight(), s_rightBrace, wxScintilla::SetCaretForeground(), wxScintilla::SetCaretWidth(), wxScintilla::SetIndicatorCurrent(), wxSCI_INDIC_ROUNDBOX, and wxSCI_INVALID_POSITION.
Referenced by EnableTabSmartJump(), OnKeyDown(), OnKeyUp(), and OnMouseLeftUp().
IsBraceShortcutActive()
bool cbStyledTextCtrl::IsBraceShortcutActive ()
Todo:
Remove? This is undocumented and unexpected by users.
Definition at line 329 of file cbstyledtextctrl.cpp.
References m_braceShortcutState.
Referenced by cbEditor::OnEditorCharAdded().
IsCharacter()
bool cbStyledTextCtrl::IsCharacter (int style)
Is style classified as character for current language?
Definition at line 303 of file cbstyledtextctrl.cpp.
References CharacterLexerStyles, and wxScintilla::GetLexer().
Referenced by AllowTabSmartJump(), DoBraceCompletion(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), CodeCompletion::GetTokenAt(), HighlightRightBrace(), CCManager::OnEditorTooltip(), and NativeParser::ParseLocalBlock().
IsComment()
bool cbStyledTextCtrl::IsComment (int style)
Is style classified as comment for current language?
Definition at line 318 of file cbstyledtextctrl.cpp.
References CommentLexerStyles, and wxScintilla::GetLexer().
Referenced by AllowTabSmartJump(), CodeCompletion::DoAutocomplete(), DoBraceCompletion(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), cbSmartIndentPlugin::GetLastNonCommentWord(), CodeCompletionHelper::GetLastNonWhitespaceChar(), cbSmartIndentPlugin::GetLastNonWhitespaceChars(), CodeCompletionHelper::GetNextNonWhitespaceChar(), CodeRefactoring::GetSymbolUnderCursor(), CodeCompletion::GetTokenAt(), HighlightRightBrace(), CCManager::OnEditorTooltip(), NativeParser::ParseLocalBlock(), and CodeRefactoring::VerifyResult().
IsPreprocessor()
bool cbStyledTextCtrl::IsPreprocessor (int style)
Is style classified as preprocessor for current language?
Definition at line 313 of file cbstyledtextctrl.cpp.
References wxScintilla::GetLexer(), and PreprocessorLexerStyles.
Referenced by AllowTabSmartJump(), CodeCompletion::DoAutocomplete(), CodeCompletion::GetAutocompList(), CodeCompletion::GetTokenAt(), and CCManager::OnEditorTooltip().
IsString()
bool cbStyledTextCtrl::IsString (int style)
Is style classified as string for current language?
Definition at line 308 of file cbstyledtextctrl.cpp.
References wxScintilla::GetLexer(), and StringLexerStyles.
Referenced by AllowTabSmartJump(), DoBraceCompletion(), CodeCompletion::GetAutocompList(), NativeParser::GetCallTips(), CodeRefactoring::GetSymbolUnderCursor(), CodeCompletion::GetTokenAt(), HighlightRightBrace(), CCManager::OnEditorTooltip(), NativeParser::ParseLocalBlock(), and CodeRefactoring::VerifyResult().
MakeNearbyLinesVisible()
void cbStyledTextCtrl::MakeNearbyLinesVisible (int line)
Scroll minimum amount such that 2 lines above and below line are shown.
Parameters
line The line to scroll focus around.
Definition at line 525 of file cbstyledtextctrl.cpp.
References wxScintilla::GetFirstVisibleLine(), wxScintilla::LineScroll(), wxScintilla::LinesOnScreen(), and wxScintilla::VisibleFromDocLine().
Referenced by cbEditor::GotoMatchingBrace(), cbEditor::GotoNextChanged(), cbEditor::GotoPreviousChanged(), and MainFrame::OnEditSelectAll().
OnContextMenu()
void cbStyledTextCtrl::OnContextMenu (wxContextMenuEvent & event) private
Definition at line 97 of file cbstyledtextctrl.cpp.
References wxContextMenuEvent::GetPosition(), wxScintilla::HaveMouseCapture(), m_pParent, mtEditorManager, wxScintilla::SetMouseCapture(), and wxDefaultPosition.
OnKeyDown()
void cbStyledTextCtrl::OnKeyDown (wxKeyEvent & event) private
Definition at line 141 of file cbstyledtextctrl.cpp.
References _T, wxScintilla::AutoCompActive(), wxScintilla::CallTipActive(), CallTipCancel(), wxScintilla::CharRight(), wxKeyboardState::ControlDown(), wxScintilla::DeleteBack(), EmulateDwellStart(), wxString::Find(), Manager::Get(), Manager::GetCCManager(), wxString::GetChar(), wxScintilla::GetCharAt(), wxScintilla::GetCurrentPos(), wxKeyEvent::GetKeyCode(), wxKeyboardState::GetModifiers(), wxScintilla::GetSelectedText(), wxScintilla::GotoPos(), HighlightRightBrace(), m_bracePosition, m_braceShortcutState, m_lastPosition, m_lastSelectedText, m_tabSmartJump, CCManager::ProcessArrow(), s_leftBrace(), s_rightBrace, WXK_BACK, WXK_CONTROL, WXK_DOWN, WXK_ESCAPE, WXK_NUMPAD_ENTER, WXK_RETURN, WXK_TAB, WXK_UP, wxMOD_ALT, wxMOD_NONE, wxNOT_FOUND, and wxSCI_INVALID_POSITION.
OnKeyUp()
void cbStyledTextCtrl::OnKeyUp (wxKeyEvent & event) private
Definition at line 234 of file cbstyledtextctrl.cpp.
References _T, AllowTabSmartJump(), wxString::Find(), wxString::GetChar(), wxScintilla::GetCharAt(), wxScintilla::GetCurrentPos(), HighlightRightBrace(), m_bracePosition, m_tabSmartJump, s_leftBrace(), s_rightBrace, wxKeyboardState::ShiftDown(), wxNOT_FOUND, and wxSCI_INVALID_POSITION.
OnKillFocus()
void cbStyledTextCtrl::OnKillFocus (wxFocusEvent & event) private
Definition at line 77 of file cbstyledtextctrl.cpp.
References wxScintilla::AutoCompActive(), wxScintilla::AutoCompCancel(), wxScintilla::CallTipActive(), and CallTipCancel().
OnMouseLeftUp()
void cbStyledTextCtrl::OnMouseLeftUp (wxMouseEvent & event) private
Definition at line 297 of file cbstyledtextctrl.cpp.
References HighlightRightBrace().
OnMouseMiddleDown()
void cbStyledTextCtrl::OnMouseMiddleDown (wxMouseEvent & event) private
Definition at line 116 of file cbstyledtextctrl.cpp.
References wxScintilla::GetCurrentPos(), wxScintilla::GetSelectedText(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxMouseEvent::GetX(), wxScintilla::InsertText(), wxString::length(), wxScintilla::PositionFromPoint(), wxScintilla::SetSelectionVoid(), and wxSCI_INVALID_POSITION.
OnSetFocus()
void cbStyledTextCtrl::OnSetFocus (wxFocusEvent & event) private
Definition at line 89 of file cbstyledtextctrl.cpp.
References m_lastFocusTime, and wxGetLocalTimeMillis().
operator=()
void cbStyledTextCtrl::operator= (const cbStyledTextCtrl &)
Don't use this.
It throws an exception if you do.
Definition at line 70 of file cbstyledtextctrl.cpp.
References _T, and cbThrow.
Member Data Documentation
CharacterLexerStyles
std::map< int, std::set< int > > cbStyledTextCtrl::CharacterLexerStyles static private
Definition at line 100 of file cbstyledtextctrl.h.
Referenced by GetCharacterLexerStyles(), and IsCharacter().
CommentLexerStyles
std::map< int, std::set< int > > cbStyledTextCtrl::CommentLexerStyles static private
Definition at line 103 of file cbstyledtextctrl.h.
Referenced by GetCommentLexerStyles(), and IsComment().
m_bracePosition
int cbStyledTextCtrl::m_bracePosition private
Definition at line 94 of file cbstyledtextctrl.h.
Referenced by EnableTabSmartJump(), HighlightRightBrace(), OnKeyDown(), and OnKeyUp().
m_braceShortcutState
bool cbStyledTextCtrl::m_braceShortcutState private
Definition at line 98 of file cbstyledtextctrl.h.
Referenced by IsBraceShortcutActive(), and OnKeyDown().
m_lastFocusTime
wxLongLong cbStyledTextCtrl::m_lastFocusTime private
Definition at line 93 of file cbstyledtextctrl.h.
Referenced by OnSetFocus().
m_lastPosition
int cbStyledTextCtrl::m_lastPosition private
Definition at line 95 of file cbstyledtextctrl.h.
Referenced by HighlightRightBrace(), and OnKeyDown().
m_lastSelectedText
wxString cbStyledTextCtrl::m_lastSelectedText private
Definition at line 97 of file cbstyledtextctrl.h.
Referenced by OnKeyDown().
m_pParent
wxWindow* cbStyledTextCtrl::m_pParent private
Definition at line 92 of file cbstyledtextctrl.h.
Referenced by EmulateDwellStart(), and OnContextMenu().
m_tabSmartJump
bool cbStyledTextCtrl::m_tabSmartJump private
Definition at line 96 of file cbstyledtextctrl.h.
Referenced by AllowTabSmartJump(), CallTipCancel(), EnableTabSmartJump(), HighlightRightBrace(), OnKeyDown(), and OnKeyUp().
PreprocessorLexerStyles
std::map< int, std::set< int > > cbStyledTextCtrl::PreprocessorLexerStyles static private
Definition at line 102 of file cbstyledtextctrl.h.
Referenced by GetPreprocessorLexerStyles(), and IsPreprocessor().
StringLexerStyles
std::map< int, std::set< int > > cbStyledTextCtrl::StringLexerStyles static private
Definition at line 101 of file cbstyledtextctrl.h.
Referenced by GetStringLexerStyles(), and IsString().
The documentation for this class was generated from the following files:
cbstyledtextctrl.h
cbstyledtextctrl.cpp