Code::Blocks: ClassBrowserBuilderThread Class Reference
ClassBrowserBuilderThread Class Reference
worker thread to build the symbol browser tree controls(both the top tree and the bottom tree) When the thread is started, it is waiting for the semaphore, and once the GUI post the semaphore the builder will do the dirty job, once finished, it will wait again.
#include <classbrowserbuilderthread.h>
Public Types
enum EThreadEvent { selectItemRequired, buildTreeStart, buildTreeEnd }
the builder threads' event sent to the GUI(class browser window)
Public Types inherited from wxThread
typedef void * ExitCode
Public Member Functions
ClassBrowserBuilderThread (wxEvtHandler *evtHandler, wxSemaphore &sem)
constructor
virtual ~ClassBrowserBuilderThread ()
destructor
void Init (NativeParser *np, CCTreeCtrl *treeTop, CCTreeCtrl *treeBottom, const wxString &active_filename, void *user_data, const BrowserOptions &bo, TokenTree *tt, int idThreadEvent)
void ExpandItem (wxTreeItemId item)
construct the children of the tree item Called from external, BuildTree():
void CollapseItem (wxTreeItemId item)
remove the children of the tree item Called from external, BuildTree(), RemoveInvalidNodes():
void SelectItem (wxTreeItemId item)
void SelectItemRequired ()
void RequestTermination (bool terminate=true)
ask the worker thread to die Called from external: when the class browser window get destroyed
Public Member Functions inherited from wxThread
wxThread (wxThreadKind kind=wxTHREAD_DETACHED)
virtual ~wxThread ()
wxThreadError Create (unsigned int stackSize=0)
wxThreadError Delete (ExitCode *rc=NULL, wxThreadWait waitMode=wxTHREAD_WAIT_BLOCK)
wxThreadIdType GetId () const
wxThreadKind GetKind () const
unsigned int GetPriority () const
bool IsAlive () const
bool IsDetached () const
bool IsPaused () const
bool IsRunning () const
wxThreadError Kill ()
wxThreadError Pause ()
wxThreadError Resume ()
wxThreadError Run ()
void SetPriority (unsigned int priority)
virtual bool TestDestroy ()
ExitCode Wait (wxThreadWait flags=wxTHREAD_WAIT_BLOCK)
Protected Member Functions
virtual void * Entry ()
void BuildTree ()
void RemoveInvalidNodes (CCTreeCtrl *tree, wxTreeItemId parent)
void ExpandNamespaces (wxTreeItemId node, TokenKind tokenKind, int level)
recursively construct the children of node's children, which matches tokenKind Called from BuildTree():
bool CreateSpecialFolders (CCTreeCtrl *tree, wxTreeItemId parent)
wxTreeItemId AddNodeIfNotThere (CCTreeCtrl *tree, wxTreeItemId parent, const wxString &name, int imgIndex=-1, CCTreeCtrlData *data=0)
bool AddChildrenOf (CCTreeCtrl *tree, wxTreeItemId parent, int parentTokenIdx, short int tokenKindMask=0xffff, int tokenScopeMask=0)
bool AddAncestorsOf (CCTreeCtrl *tree, wxTreeItemId parent, int tokenIdx)
bool AddDescendantsOf (CCTreeCtrl *tree, wxTreeItemId parent, int tokenIdx, bool allowInheritance=true)
void AddMembersOf (CCTreeCtrl *tree, wxTreeItemId node)
Protected Member Functions inherited from wxThread
void Exit (ExitCode exitcode=0)
Protected Attributes
wxEvtHandler * m_Parent
wxSemaphore & m_ClassBrowserSemaphore
wxMutex m_ClassBrowserBuilderThreadMutex
Some member functions of ClassBrowserBuilderThread such as ExpandItem() can either be called from the main GUI thread(in ClassBrowser::OnTreeItemExpanding(wxTreeEvent& event)), or be called in the worker thread(in BuildTree() which is called in ClassBrowserBuilderThread::Entry()), to protect the member variables of the class(especially the wxTreeCtrl, we use the Mutex so that only one thread can access to those member variables.
NativeParser * m_NativeParser
CCTreeCtrl * m_CCTreeCtrlTop
pointer to the top wxTreeCtrl
CCTreeCtrl * m_CCTreeCtrlBottom
pointer to the bottom wxTreeCtrl
wxString m_ActiveFilename
void * m_UserData
BrowserOptions m_BrowserOptions
TokenTree * m_TokenTree
TokenFileSet m_CurrentFileSet
symbol tree contains the tokens from those files, e.g.
TokenIdxSet m_CurrentTokenSet
tokens belong to the files in m_CurrentFileSet
TokenIdxSet m_CurrentGlobalTokensSet
special global scope tokens to the files in m_CurrentFileSet
Private Member Functions
bool AddNodes (CCTreeCtrl *tree, wxTreeItemId parent, const TokenIdxSet *tokens, short int tokenKindMask=0xffff, int tokenScopeMask=0, bool allowGlobals=false)
bool TokenMatchesFilter (const Token *token, bool locked=false)
bool TokenContainsChildrenOfKind (const Token *token, int kind)
void SaveExpandedItems (CCTreeCtrl *tree, wxTreeItemId parent, int level)
void ExpandSavedItems (CCTreeCtrl *tree, wxTreeItemId parent, int level)
void SaveSelectedItem ()
void SelectSavedItem ()
Private Attributes
ExpandedItemVect m_ExpandedVect
SelectedItemPath m_SelectedPath
bool m_InitDone
bool m_TerminationRequested
if this variable is true, the Entry() function should return
int m_idThreadEvent
wxTreeItemId m_SelectItemRequired
Additional Inherited Members
Static Public Member Functions inherited from wxThread
static int GetCPUCount ()
static wxThreadIdType GetCurrentId ()
static wxThreadIdType GetMainId ()
static bool IsMain ()
static bool SetConcurrency (size_t level)
static void Sleep (unsigned long milliseconds)
static wxThread * This ()
static void Yield ()
Detailed Description
worker thread to build the symbol browser tree controls(both the top tree and the bottom tree) When the thread is started, it is waiting for the semaphore, and once the GUI post the semaphore the builder will do the dirty job, once finished, it will wait again.
Definition at line 21 of file classbrowserbuilderthread.h.
Member Enumeration Documentation
EThreadEvent
enum ClassBrowserBuilderThread::EThreadEvent
the builder threads' event sent to the GUI(class browser window)
Enumerator
selectItemRequired
buildTreeStart
an item is selected
buildTreeEnd
the thread is starting to (re)build the tree
finishing (re)build the tree
Definition at line 25 of file classbrowserbuilderthread.h.
Constructor & Destructor Documentation
ClassBrowserBuilderThread()
ClassBrowserBuilderThread::ClassBrowserBuilderThread (wxEvtHandler * evtHandler, wxSemaphore & sem)
constructor
Parameters
evtHandler parent window notification events will sent to
sem a semaphore reference which is used synchronize the GUI and the builder thread
Definition at line 66 of file classbrowserbuilderthread.cpp.
References wxID_NONE, and wxTHREAD_JOINABLE.
~ClassBrowserBuilderThread()
ClassBrowserBuilderThread::~ClassBrowserBuilderThread () virtual
destructor
Definition at line 84 of file classbrowserbuilderthread.cpp.
Member Function Documentation
AddAncestorsOf()
bool ClassBrowserBuilderThread::AddAncestorsOf (CCTreeCtrl * tree, wxTreeItemId parent, int tokenIdx) protected
Definition at line 824 of file classbrowserbuilderthread.cpp.
References _T, AddNodes(), TokenTree::at(), CBBT_SANITY_CHECK, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, Token::m_DirectAncestors, m_TokenTree, TokenTree::RecalcInheritanceChain(), s_TokenTreeMutex, tkClass, tkTypedef, and TRACE.
Referenced by ExpandItem(), and RequestTermination().
AddChildrenOf()
bool ClassBrowserBuilderThread::AddChildrenOf (CCTreeCtrl * tree, wxTreeItemId parent, int parentTokenIdx, short int tokenKindMask = 0xffff, int tokenScopeMask = 0) protected
Definition at line 783 of file classbrowserbuilderthread.cpp.
References _T, AddNodes(), TokenTree::at(), bdfEverything, bdfWorkspace, CBBT_SANITY_CHECK, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, BrowserOptions::displayFilter, TokenTree::GetGlobalNameSpaces(), m_BrowserOptions, Token::m_Children, m_CurrentGlobalTokensSet, m_TokenTree, s_TokenTreeMutex, and TRACE.
Referenced by AddMembersOf(), ExpandItem(), and RequestTermination().
AddDescendantsOf()
bool ClassBrowserBuilderThread::AddDescendantsOf (CCTreeCtrl * tree, wxTreeItemId parent, int tokenIdx, bool allowInheritance = true) protected
Definition at line 845 of file classbrowserbuilderthread.cpp.
References _T, AddNodes(), TokenTree::at(), CBBT_SANITY_CHECK, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, m_BrowserOptions, Token::m_Descendants, m_TokenTree, TokenTree::RecalcInheritanceChain(), s_TokenTreeMutex, BrowserOptions::showInheritance, tkClass, tkTypedef, and TRACE.
Referenced by ExpandItem(), and RequestTermination().
AddMembersOf()
void ClassBrowserBuilderThread::AddMembersOf (CCTreeCtrl * tree, wxTreeItemId node) protected
Definition at line 872 of file classbrowserbuilderthread.cpp.
References _(), _T, AddChildrenOf(), wxTreeCtrl::AddRoot(), wxTreeCtrl::AppendItem(), bstKind, bstScope, CBBT_SANITY_CHECK, CCLogger::DebugLog(), wxTreeCtrl::Delete(), wxTreeCtrl::DeleteAllItems(), wxTreeCtrl::EnsureVisible(), wxTreeCtrl::ExpandAll(), F(), CCLogger::Get(), wxTreeCtrl::GetChildrenCount(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetLastChild(), wxTreeCtrl::GetPrevSibling(), wxTreeCtrl::GetRootItem(), wxTreeItemId::IsOk(), m_BrowserOptions, m_CCTreeCtrlBottom, m_CCTreeCtrlTop, Token::m_Index, CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_Token, Token::m_TokenKind, PARSER_IMG_CLASS_FOLDER, PARSER_IMG_FUNCS_FOLDER, PARSER_IMG_MACRO_USE_FOLDER, PARSER_IMG_OTHERS_FOLDER, PARSER_IMG_VARS_FOLDER, wxTreeCtrl::ScrollTo(), wxTreeCtrl::SetItemBold(), sfBase, sfDerived, sfGFuncs, sfGVars, sfMacro, sfPreproc, sfRoot, sfToken, sfTypedef, BrowserOptions::sortType, wxStopWatch::Start(), wxStopWatch::Time(), tkAnyFunction, tkClass, tkConstructor, tkDestructor, tkEnum, tkFunction, tkMacroDef, tkMacroUse, tkNamespace, tkTypedef, tkVariable, TRACE, tsPrivate, tsProtected, and tsPublic.
Referenced by ExpandItem(), RequestTermination(), and SelectItem().
AddNodeIfNotThere()
wxTreeItemId ClassBrowserBuilderThread::AddNodeIfNotThere (CCTreeCtrl * tree, wxTreeItemId parent, const wxString & name, int imgIndex = -1, CCTreeCtrlData * data = 0) protected
Definition at line 756 of file classbrowserbuilderthread.cpp.
References _T, wxTreeCtrl::AppendItem(), wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetNextChild(), wxTreeCtrl::SetItemData(), wxTreeCtrl::SetItemImage(), TRACE, wxTreeItemIcon_Normal, and wxTreeItemIcon_Selected.
Referenced by CreateSpecialFolders(), and RequestTermination().
AddNodes()
bool ClassBrowserBuilderThread::AddNodes (CCTreeCtrl * tree, wxTreeItemId parent, const TokenIdxSet * tokens, short int tokenKindMask = 0xffff, int tokenScopeMask = 0, bool allowGlobals = false) private
Definition at line 1005 of file classbrowserbuilderthread.cpp.
References _T, wxTreeCtrl::AppendItem(), TokenTree::at(), CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, CCLogger::DebugLog(), F(), CCLogger::Get(), wxTreeCtrl::GetFirstChild(), Token::GetFormattedArgs(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetNextSibling(), Token::GetTicket(), NativeParser::GetTokenKindImage(), wxString::IsEmpty(), wxTreeItemId::IsOk(), m_BrowserOptions, m_CCTreeCtrlTop, Token::m_FullType, Token::m_IsLocal, Token::m_Name, m_NativeParser, Token::m_Scope, Token::m_TemplateArgument, CCTreeCtrlData::m_Ticket, Token::m_TokenKind, m_TokenTree, s_TokenTreeMutex, wxTreeCtrl::SetItemHasChildren(), sfToken, BrowserOptions::showInheritance, wxTreeCtrl::SortChildren(), tkClass, tkConstructor, tkDestructor, tkEnum, tkEnumerator, tkFunction, tkMacroUse, tkNamespace, tkTypedef, tkVariable, TokenContainsChildrenOfKind(), TokenMatchesFilter(), TRACE, and BrowserOptions::treeMembers.
Referenced by AddAncestorsOf(), AddChildrenOf(), AddDescendantsOf(), and RequestTermination().
BuildTree()
void ClassBrowserBuilderThread::BuildTree () protected
Definition at line 415 of file classbrowserbuilderthread.cpp.
References _(), _T, wxTreeCtrl::AddRoot(), buildTreeEnd, buildTreeStart, CBBT_SANITY_CHECK, CollapseItem(), CCLogger::DebugLog(), wxTreeCtrl::Expand(), ExpandItem(), ExpandNamespaces(), ExpandSavedItems(), F(), CCLogger::Get(), NativeParser::GetImageList(), wxTreeCtrl::GetRootItem(), wxTreeItemId::IsOk(), m_BrowserOptions, m_CCTreeCtrlBottom, m_CCTreeCtrlTop, m_ExpandedVect, m_idThreadEvent, m_InitDone, m_NativeParser, m_Parent, PARSER_IMG_SYMBOLS_FOLDER, RemoveInvalidNodes(), SaveExpandedItems(), SaveSelectedItem(), SelectSavedItem(), CCTreeCtrl::SetCompareFunction(), wxTreeCtrl::SetImageList(), wxTreeCtrl::SetItemHasChildren(), sfRoot, BrowserOptions::sortType, wxStopWatch::Start(), wxStopWatch::Time(), tkClass, tkNamespace, BrowserOptions::treeMembers, and wxEVT_COMMAND_ENTER.
Referenced by Entry(), and RequestTermination().
CollapseItem()
void ClassBrowserBuilderThread::CollapseItem (wxTreeItemId item)
remove the children of the tree item Called from external, BuildTree(), RemoveInvalidNodes():
Definition at line 350 of file classbrowserbuilderthread.cpp.
References _T, CBBT_SANITY_CHECK, CC_LOCKER_TRACK_CBBT_MTX_LOCK, CC_LOCKER_TRACK_CBBT_MTX_UNLOCK, wxTreeCtrl::CollapseAndReset(), wxTreeCtrl::DeleteChildren(), wxTreeItemId::IsOk(), m_CCTreeCtrlTop, m_ClassBrowserBuilderThreadMutex, m_InitDone, wxTreeCtrl::SetItemHasChildren(), and TRACE.
Referenced by BuildTree(), ClassBrowser::OnTreeItemCollapsing(), and RemoveInvalidNodes().
CreateSpecialFolders()
bool ClassBrowserBuilderThread::CreateSpecialFolders (CCTreeCtrl * tree, wxTreeItemId parent) protected
Definition at line 687 of file classbrowserbuilderthread.cpp.
References _(), _T, AddNodeIfNotThere(), TokenTree::at(), CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, wxSystemSettings::GetColour(), TokenTree::GetGlobalNameSpaces(), NativeParser::GetParser(), ParserBase::GetTokenTree(), m_BrowserOptions, m_CCTreeCtrlTop, Token::m_IsLocal, m_NativeParser, Token::m_TokenKind, PARSER_IMG_FUNCS_FOLDER, PARSER_IMG_MACRO_DEF_FOLDER, PARSER_IMG_MACRO_USE_FOLDER, PARSER_IMG_TYPEDEF_FOLDER, PARSER_IMG_VARS_FOLDER, s_TokenTreeMutex, wxTreeCtrl::SetItemHasChildren(), wxTreeCtrl::SetItemTextColour(), sfGFuncs, sfGVars, sfMacro, sfPreproc, sfTypedef, tkFunction, tkMacroDef, tkMacroUse, tkTypedef, tkVariable, TokenMatchesFilter(), TRACE, BrowserOptions::treeMembers, wxSYS_COLOUR_GRAYTEXT, and wxSYS_COLOUR_WINDOWTEXT.
Referenced by ExpandItem(), and RequestTermination().
Entry()
void * ClassBrowserBuilderThread::Entry () protected virtual
Implements wxThread.
Definition at line 194 of file classbrowserbuilderthread.cpp.
References BuildTree(), Manager::IsAppShuttingDown(), m_CCTreeCtrlBottom, m_CCTreeCtrlTop, m_ClassBrowserSemaphore, m_NativeParser, m_TerminationRequested, wxSemaphore::Wait(), wxIsMainThread(), wxMutexGuiEnter(), and wxMutexGuiLeave().
Referenced by RequestTermination().
ExpandItem()
void ClassBrowserBuilderThread::ExpandItem (wxTreeItemId item)
construct the children of the tree item Called from external, BuildTree():
Definition at line 243 of file classbrowserbuilderthread.cpp.
References _(), _T, AddAncestorsOf(), AddChildrenOf(), AddDescendantsOf(), AddMembersOf(), wxTreeCtrl::AppendItem(), bdfFile, CBBT_SANITY_CHECK, CC_LOCKER_TRACK_CBBT_MTX_LOCK, CC_LOCKER_TRACK_CBBT_MTX_UNLOCK, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, CreateSpecialFolders(), CCLogger::DebugLog(), BrowserOptions::displayFilter, F(), CCLogger::Get(), wxTreeCtrl::GetCount(), wxTreeCtrl::GetItemData(), wxString::IsEmpty(), wxTreeItemId::IsOk(), m_ActiveFilename, m_BrowserOptions, m_CCTreeCtrlTop, m_ClassBrowserBuilderThreadMutex, Token::m_Descendants, Token::m_DirectAncestors, Token::m_Index, m_InitDone, m_NativeParser, CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_Token, Token::m_TokenKind, m_TokenTree, PARSER_IMG_CLASS_FOLDER, TokenTree::RecalcInheritanceChain(), s_TokenTreeMutex, wxTreeCtrl::SetItemHasChildren(), sfBase, sfDerived, sfGFuncs, sfGVars, sfMacro, sfPreproc, sfRoot, sfToken, sfTypedef, BrowserOptions::showInheritance, wxStopWatch::Time(), tkAnyContainer, tkAnyFunction, tkClass, tkConstructor, tkDestructor, tkEnum, tkEnumerator, tkFunction, tkMacroDef, tkMacroUse, tkNamespace, tkTypedef, tkUndefined, tkVariable, TRACE, and BrowserOptions::treeMembers.
Referenced by BuildTree(), and ClassBrowser::OnTreeItemExpanding().
ExpandNamespaces()
void ClassBrowserBuilderThread::ExpandNamespaces (wxTreeItemId node, TokenKind tokenKind, int level) protected
recursively construct the children of node's children, which matches tokenKind Called from BuildTree():
Parameters
level the recursive level
Definition at line 661 of file classbrowserbuilderthread.cpp.
References _T, CBBT_SANITY_CHECK, wxTreeCtrl::Expand(), BrowserOptions::expandNS, F(), wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetNextSibling(), wxTreeItemId::IsOk(), m_BrowserOptions, m_CCTreeCtrlTop, Token::m_Name, CCTreeCtrlData::m_Token, Token::m_TokenKind, and TRACE.
Referenced by BuildTree(), and RequestTermination().
ExpandSavedItems()
void ClassBrowserBuilderThread::ExpandSavedItems (CCTreeCtrl * tree, wxTreeItemId parent, int level) private
Definition at line 1179 of file classbrowserbuilderthread.cpp.
References _T, CBBT_SANITY_CHECK, wxTreeCtrl::Expand(), CCTreeCtrlExpandedItemData::GetData(), wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), CCTreeCtrlExpandedItemData::GetLevel(), wxTreeCtrl::GetNextSibling(), wxTreeItemId::IsOk(), m_ExpandedVect, CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_TokenKind, CCTreeCtrlData::m_TokenName, and TRACE.
Referenced by BuildTree(), and RequestTermination().
Init()
void ClassBrowserBuilderThread::Init (NativeParser * np, CCTreeCtrl * treeTop, CCTreeCtrl * treeBottom, const wxString & active_filename, void * user_data, const BrowserOptions & bo, TokenTree * tt, int idThreadEvent)
Definition at line 88 of file classbrowserbuilderthread.cpp.
References _T, TokenTree::at(), bdfFile, bdfProject, CC_LOCKER_TRACK_CBBT_MTX_LOCK, CC_LOCKER_TRACK_CBBT_MTX_UNLOCK, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, BrowserOptions::displayFilter, ProjectFile::file, NativeParser::GetAllPathsByFilename(), wxArrayString::GetCount(), TokenTree::GetFileIndex(), TokenTree::GetFileMatches(), cbProject::GetFilesList(), wxFileName::GetFullPath(), NativeParser::GetParser(), TokenTree::GetTokensBelongToFile(), ParserBase::GetTokenTree(), idThreadEvent, wxString::IsEmpty(), m_ActiveFilename, m_BrowserOptions, m_CCTreeCtrlBottom, m_CCTreeCtrlTop, m_ClassBrowserBuilderThreadMutex, m_CurrentFileSet, m_CurrentGlobalTokensSet, m_CurrentTokenSet, m_idThreadEvent, m_NativeParser, Token::m_ParentIndex, m_TokenTree, m_UserData, s_TokenTreeMutex, and TRACE.
Referenced by ClassBrowser::ThreadedBuildTree().
RemoveInvalidNodes()
void ClassBrowserBuilderThread::RemoveInvalidNodes (CCTreeCtrl * tree, wxTreeItemId parent) protected
Definition at line 590 of file classbrowserbuilderthread.cpp.
References _T, TokenTree::at(), CBBT_SANITY_CHECK, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, CollapseItem(), wxTreeCtrl::Delete(), wxTreeCtrl::DeleteChildren(), wxTreeCtrl::GetChildrenCount(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetLastChild(), wxTreeCtrl::GetPrevSibling(), Token::GetTicket(), wxTreeItemId::IsOk(), wxTreeCtrl::ItemHasChildren(), m_CCTreeCtrlBottom, m_CCTreeCtrlTop, CCTreeCtrlData::m_Ticket, CCTreeCtrlData::m_Token, CCTreeCtrlData::m_TokenIndex, m_TokenTree, s_TokenTreeMutex, TokenMatchesFilter(), and TRACE.
Referenced by BuildTree(), and RequestTermination().
RequestTermination()
void ClassBrowserBuilderThread::RequestTermination (bool terminate = true) inline
ask the worker thread to die Called from external: when the class browser window get destroyed
Definition at line 68 of file classbrowserbuilderthread.h.
References AddAncestorsOf(), AddChildrenOf(), AddDescendantsOf(), AddMembersOf(), AddNodeIfNotThere(), AddNodes(), BuildTree(), CreateSpecialFolders(), Entry(), ExpandNamespaces(), ExpandSavedItems(), m_TerminationRequested, RemoveInvalidNodes(), SaveExpandedItems(), SaveSelectedItem(), SelectSavedItem(), TokenContainsChildrenOfKind(), and TokenMatchesFilter().
Referenced by ClassBrowser::~ClassBrowser().
SaveExpandedItems()
void ClassBrowserBuilderThread::SaveExpandedItems (CCTreeCtrl * tree, wxTreeItemId parent, int level) private
Definition at line 1156 of file classbrowserbuilderthread.cpp.
References _T, CBBT_SANITY_CHECK, wxTreeCtrl::GetChildrenCount(), wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetNextSibling(), wxTreeItemId::IsOk(), m_ExpandedVect, and TRACE.
Referenced by BuildTree(), and RequestTermination().
SaveSelectedItem()
void ClassBrowserBuilderThread::SaveSelectedItem () private
Definition at line 1221 of file classbrowserbuilderthread.cpp.
References _T, CBBT_SANITY_CHECK, wxTreeCtrl::GetItemData(), wxTreeCtrl::GetItemParent(), wxTreeCtrl::GetRootItem(), wxTreeCtrl::GetSelection(), wxTreeItemId::IsOk(), m_CCTreeCtrlTop, m_SelectedPath, and TRACE.
Referenced by BuildTree(), and RequestTermination().
SelectItem()
void ClassBrowserBuilderThread::SelectItem (wxTreeItemId item)
Definition at line 376 of file classbrowserbuilderthread.cpp.
References _T, AddMembersOf(), bdfFile, CBBT_SANITY_CHECK, CC_LOCKER_TRACK_CBBT_MTX_LOCK, CC_LOCKER_TRACK_CBBT_MTX_UNLOCK, CCLogger::DebugLog(), BrowserOptions::displayFilter, F(), CCLogger::Get(), wxString::IsEmpty(), wxTreeItemId::IsOk(), m_ActiveFilename, m_BrowserOptions, m_CCTreeCtrlBottom, m_CCTreeCtrlTop, m_ClassBrowserBuilderThreadMutex, TRACE, and BrowserOptions::treeMembers.
Referenced by ClassBrowser::OnTreeSelChanged().
SelectItemRequired()
void ClassBrowserBuilderThread::SelectItemRequired ()
Definition at line 401 of file classbrowserbuilderthread.cpp.
References wxTreeCtrl::EnsureVisible(), Manager::IsAppShuttingDown(), wxTreeItemId::IsOk(), m_CCTreeCtrlTop, m_SelectItemRequired, and wxTreeCtrl::SelectItem().
Referenced by ClassBrowser::OnThreadEvent().
SelectSavedItem()
void ClassBrowserBuilderThread::SelectSavedItem () private
Definition at line 1240 of file classbrowserbuilderthread.cpp.
References _T, CBBT_SANITY_CHECK, wxTreeCtrl::GetFirstChild(), wxTreeCtrl::GetItemData(), wxTreeCtrl::GetNextSibling(), wxTreeCtrl::GetRootItem(), wxTreeItemId::IsOk(), m_CCTreeCtrlTop, m_idThreadEvent, m_Parent, m_SelectedPath, m_SelectItemRequired, CCTreeCtrlData::m_SpecialFolder, CCTreeCtrlData::m_TokenKind, CCTreeCtrlData::m_TokenName, selectItemRequired, TRACE, and wxEVT_COMMAND_ENTER.
Referenced by BuildTree(), and RequestTermination().
TokenContainsChildrenOfKind()
bool ClassBrowserBuilderThread::TokenContainsChildrenOfKind (const Token * token, int kind) private
Definition at line 1129 of file classbrowserbuilderthread.cpp.
References _T, TokenTree::at(), CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, Token::GetTree(), Token::m_Children, Token::m_TokenKind, s_TokenTreeMutex, and TRACE.
Referenced by AddNodes(), and RequestTermination().
TokenMatchesFilter()
bool ClassBrowserBuilderThread::TokenMatchesFilter (const Token * token, bool locked = false) private
Definition at line 1088 of file classbrowserbuilderthread.cpp.
References _T, TokenTree::at(), bdfEverything, bdfFile, bdfProject, bdfWorkspace, CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, BrowserOptions::displayFilter, m_BrowserOptions, Token::m_Children, m_CurrentTokenSet, Token::m_Index, Token::m_IsLocal, Token::m_IsTemp, m_TokenTree, m_UserData, Token::m_UserData, s_TokenTreeMutex, and TRACE.
Referenced by AddNodes(), CreateSpecialFolders(), RemoveInvalidNodes(), and RequestTermination().
Member Data Documentation
m_ActiveFilename
wxString ClassBrowserBuilderThread::m_ActiveFilename protected
Definition at line 135 of file classbrowserbuilderthread.h.
Referenced by ExpandItem(), Init(), and SelectItem().
m_BrowserOptions
BrowserOptions ClassBrowserBuilderThread::m_BrowserOptions protected
Definition at line 137 of file classbrowserbuilderthread.h.
Referenced by AddChildrenOf(), AddDescendantsOf(), AddMembersOf(), AddNodes(), BuildTree(), CreateSpecialFolders(), ExpandItem(), ExpandNamespaces(), Init(), SelectItem(), and TokenMatchesFilter().
m_CCTreeCtrlBottom
CCTreeCtrl* ClassBrowserBuilderThread::m_CCTreeCtrlBottom protected
pointer to the bottom wxTreeCtrl
Definition at line 133 of file classbrowserbuilderthread.h.
Referenced by AddMembersOf(), BuildTree(), Entry(), Init(), RemoveInvalidNodes(), and SelectItem().
m_CCTreeCtrlTop
CCTreeCtrl* ClassBrowserBuilderThread::m_CCTreeCtrlTop protected
pointer to the top wxTreeCtrl
Definition at line 131 of file classbrowserbuilderthread.h.
Referenced by AddMembersOf(), AddNodes(), BuildTree(), CollapseItem(), CreateSpecialFolders(), Entry(), ExpandItem(), ExpandNamespaces(), Init(), RemoveInvalidNodes(), SaveSelectedItem(), SelectItem(), SelectItemRequired(), and SelectSavedItem().
m_ClassBrowserBuilderThreadMutex
wxMutex ClassBrowserBuilderThread::m_ClassBrowserBuilderThreadMutex protected
Some member functions of ClassBrowserBuilderThread such as ExpandItem() can either be called from the main GUI thread(in ClassBrowser::OnTreeItemExpanding(wxTreeEvent& event)), or be called in the worker thread(in BuildTree() which is called in ClassBrowserBuilderThread::Entry()), to protect the member variables of the class(especially the wxTreeCtrl, we use the Mutex so that only one thread can access to those member variables.
Definition at line 127 of file classbrowserbuilderthread.h.
Referenced by CollapseItem(), ExpandItem(), Init(), and SelectItem().
m_ClassBrowserSemaphore
wxSemaphore& ClassBrowserBuilderThread::m_ClassBrowserSemaphore protected
Definition at line 119 of file classbrowserbuilderthread.h.
Referenced by Entry().
m_CurrentFileSet
TokenFileSet ClassBrowserBuilderThread::m_CurrentFileSet protected
symbol tree contains the tokens from those files, e.g.
if we specify only show tokens from a.cpp, then m_CurrentFileSet could maybe contains two files: a.cpp and a.h
Definition at line 144 of file classbrowserbuilderthread.h.
Referenced by Init().
m_CurrentGlobalTokensSet
TokenIdxSet ClassBrowserBuilderThread::m_CurrentGlobalTokensSet protected
special global scope tokens to the files in m_CurrentFileSet
Definition at line 148 of file classbrowserbuilderthread.h.
Referenced by AddChildrenOf(), and Init().
m_CurrentTokenSet
TokenIdxSet ClassBrowserBuilderThread::m_CurrentTokenSet protected
tokens belong to the files in m_CurrentFileSet
Definition at line 146 of file classbrowserbuilderthread.h.
Referenced by Init(), and TokenMatchesFilter().
m_ExpandedVect
ExpandedItemVect ClassBrowserBuilderThread::m_ExpandedVect private
Definition at line 151 of file classbrowserbuilderthread.h.
Referenced by BuildTree(), ExpandSavedItems(), and SaveExpandedItems().
m_idThreadEvent
int ClassBrowserBuilderThread::m_idThreadEvent private
Definition at line 157 of file classbrowserbuilderthread.h.
Referenced by BuildTree(), Init(), and SelectSavedItem().
m_InitDone
bool ClassBrowserBuilderThread::m_InitDone private
Definition at line 153 of file classbrowserbuilderthread.h.
Referenced by BuildTree(), CollapseItem(), and ExpandItem().
m_NativeParser
NativeParser* ClassBrowserBuilderThread::m_NativeParser protected
Definition at line 128 of file classbrowserbuilderthread.h.
Referenced by AddNodes(), BuildTree(), CreateSpecialFolders(), Entry(), ExpandItem(), and Init().
m_Parent
wxEvtHandler* ClassBrowserBuilderThread::m_Parent protected
Definition at line 118 of file classbrowserbuilderthread.h.
Referenced by BuildTree(), and SelectSavedItem().
m_SelectedPath
SelectedItemPath ClassBrowserBuilderThread::m_SelectedPath private
Definition at line 152 of file classbrowserbuilderthread.h.
Referenced by SaveSelectedItem(), and SelectSavedItem().
m_SelectItemRequired
wxTreeItemId ClassBrowserBuilderThread::m_SelectItemRequired private
Definition at line 158 of file classbrowserbuilderthread.h.
Referenced by SelectItemRequired(), and SelectSavedItem().
m_TerminationRequested
bool ClassBrowserBuilderThread::m_TerminationRequested private
if this variable is true, the Entry() function should return
Definition at line 156 of file classbrowserbuilderthread.h.
Referenced by Entry(), and RequestTermination().
m_TokenTree
TokenTree* ClassBrowserBuilderThread::m_TokenTree protected
Definition at line 138 of file classbrowserbuilderthread.h.
Referenced by AddAncestorsOf(), AddChildrenOf(), AddDescendantsOf(), AddNodes(), ExpandItem(), Init(), RemoveInvalidNodes(), and TokenMatchesFilter().
m_UserData
void* ClassBrowserBuilderThread::m_UserData protected
Definition at line 136 of file classbrowserbuilderthread.h.
Referenced by Init(), and TokenMatchesFilter().
The documentation for this class was generated from the following files:
classbrowserbuilderthread.h
classbrowserbuilderthread.cpp