Code::Blocks: GdbCmd_RemoteTarget Class Reference
GdbCmd_RemoteTarget Class Reference
#include <gdb_commands.h>
Public Member Functions
GdbCmd_RemoteTarget (DebuggerDriver *driver, RemoteDebugging *rd)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Definition at line 1742 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_RemoteTarget()
GdbCmd_RemoteTarget::GdbCmd_RemoteTarget (DebuggerDriver * driver, RemoteDebugging * rd) inline
Definition at line 1745 of file gdb_commands.h.
References _(), _T, RemoteDebugging::connType, RemoteDebugging::extendedRemote, Manager::Get(), Manager::GetMacrosManager(), RemoteDebugging::ip, RemoteDebugging::ipPort, wxString::IsEmpty(), DebuggerDriver::Log(), DebuggerCmd::m_Cmd, DebuggerCmd::m_pDriver, MacrosManager::ReplaceEnvVars(), RemoteDebugging::Serial, RemoteDebugging::serialPort, RemoteDebugging::TCP, and RemoteDebugging::UDP.
Member Function Documentation
ParseOutput()
void GdbCmd_RemoteTarget::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 1782 of file gdb_commands.h.
References _(), _T, wxString::Contains(), InfoWindow::Display(), wxString::IsEmpty(), DebuggerDriver::Log(), and DebuggerCmd::m_pDriver.
The documentation for this class was generated from the following file:
gdb_commands.h