Code::Blocks: cbDebuggerConfiguration Class Reference
cbDebuggerConfiguration Class Reference abstract
#include <debuggermanager.h>
Public Member Functions
cbDebuggerConfiguration (const ConfigManagerWrapper &config)
virtual ~cbDebuggerConfiguration ()
virtual cbDebuggerConfiguration * Clone () const =0
virtual wxPanel * MakePanel (wxWindow *parent)=0
virtual bool SaveChanges (wxPanel *panel)=0
void SetName (const wxString &name)
const wxString & GetName () const
const ConfigManagerWrapper & GetConfig () const
void SetConfig (const ConfigManagerWrapper &config)
void SetMenuId (long id)
long GetMenuId () const
Protected Member Functions
cbDebuggerConfiguration (const cbDebuggerConfiguration &o)
cbDebuggerConfiguration & operator= (const cbDebuggerConfiguration &)
Protected Attributes
ConfigManagerWrapper m_config
Private Attributes
wxString m_name
long m_menuId
Detailed Description
Definition at line 152 of file debuggermanager.h.
Constructor & Destructor Documentation
cbDebuggerConfiguration() [1/2]
cbDebuggerConfiguration::cbDebuggerConfiguration (const cbDebuggerConfiguration & o) protected
Definition at line 319 of file debuggermanager.cpp.
cbDebuggerConfiguration() [2/2]
cbDebuggerConfiguration::cbDebuggerConfiguration (const ConfigManagerWrapper & config)
Definition at line 313 of file debuggermanager.cpp.
~cbDebuggerConfiguration()
virtual cbDebuggerConfiguration::~cbDebuggerConfiguration () inline virtual
Definition at line 160 of file debuggermanager.h.
Member Function Documentation
Clone()
virtual cbDebuggerConfiguration* cbDebuggerConfiguration::Clone () const pure virtual
Implemented in DebuggerConfiguration.
Referenced by DebuggerSettingsDlg::DebuggerSettingsDlg().
GetConfig()
const ConfigManagerWrapper & cbDebuggerConfiguration::GetConfig () const
Definition at line 334 of file debuggermanager.cpp.
References m_config.
Referenced by DebuggerSettingsDlg::OnOK().
GetMenuId()
long cbDebuggerConfiguration::GetMenuId () const
Definition at line 349 of file debuggermanager.cpp.
References m_menuId.
GetName()
const wxString & cbDebuggerConfiguration::GetName () const
Definition at line 329 of file debuggermanager.cpp.
References m_name.
Referenced by DebuggerSettingsDlg::CreateConfig(), DebuggerMenuHandler::LogActiveConfig(), DebuggerSettingsDlg::OnOK(), and cbDebuggerPlugin::SwitchToDebuggingLayout().
MakePanel()
virtual wxPanel* cbDebuggerConfiguration::MakePanel (wxWindow * parent) pure virtual
Implemented in DebuggerConfiguration.
Referenced by DebuggerSettingsDlg::CreateConfig().
operator=()
cbDebuggerConfiguration& cbDebuggerConfiguration::operator= (const cbDebuggerConfiguration &) protected
SaveChanges()
virtual bool cbDebuggerConfiguration::SaveChanges (wxPanel * panel) pure virtual
Implemented in DebuggerConfiguration.
Referenced by DebuggerSettingsDlg::OnOK().
SetConfig()
void cbDebuggerConfiguration::SetConfig (const ConfigManagerWrapper & config)
Definition at line 339 of file debuggermanager.cpp.
References m_config.
Referenced by DebuggerSettingsDlg::OnOK().
SetMenuId()
void cbDebuggerConfiguration::SetMenuId (long id)
Definition at line 344 of file debuggermanager.cpp.
References m_menuId.
SetName()
void cbDebuggerConfiguration::SetName (const wxString & name)
Definition at line 325 of file debuggermanager.cpp.
References m_name.
Referenced by DebuggerSettingsDlg::CreateConfig(), and DebuggerManager::ProcessSettings().
Member Data Documentation
m_config
ConfigManagerWrapper cbDebuggerConfiguration::m_config protected
Definition at line 177 of file debuggermanager.h.
Referenced by GetConfig(), and SetConfig().
m_menuId
long cbDebuggerConfiguration::m_menuId private
Definition at line 180 of file debuggermanager.h.
Referenced by GetMenuId(), and SetMenuId().
m_name
wxString cbDebuggerConfiguration::m_name private
Definition at line 179 of file debuggermanager.h.
Referenced by GetName(), and SetName().
The documentation for this class was generated from the following files:
debuggermanager.h
debuggermanager.cpp