Code::Blocks: DebuggerToolbarHandler Class Reference
DebuggerToolbarHandler Class Reference
#include <debuggermenu.h>
Public Member Functions
DebuggerToolbarHandler (DebuggerMenuHandler *menuHandler)
wxToolBar * GetToolbar (bool create=true)
Private Member Functions
void OnUpdateUI (wxUpdateUIEvent &event)
void OnToolInfo (wxCommandEvent &event)
void OnDebugWindows (wxCommandEvent &event)
void OnStop (wxCommandEvent &event)
DECLARE_EVENT_TABLE ()
Private Attributes
wxToolBar * m_Toolbar
DebuggerMenuHandler * m_menuHandler
Friends
class DebuggerManager
Detailed Description
Definition at line 77 of file debuggermenu.h.
Constructor & Destructor Documentation
DebuggerToolbarHandler()
DebuggerToolbarHandler::DebuggerToolbarHandler (DebuggerMenuHandler * menuHandler)
Definition at line 775 of file debuggermenu.cpp.
Member Function Documentation
DECLARE_EVENT_TABLE()
DebuggerToolbarHandler::DECLARE_EVENT_TABLE () private
GetToolbar()
wxToolBar * DebuggerToolbarHandler::GetToolbar (bool create = true)
Definition at line 781 of file debuggermenu.cpp.
References _T, Manager::AddonToolBar(), Manager::CreateEmptyToolbar(), Manager::Get(), and Manager::isToolBar16x16().
OnDebugWindows()
void DebuggerToolbarHandler::OnDebugWindows (wxCommandEvent & event) private
Definition at line 850 of file debuggermenu.cpp.
References Manager::Get(), and Manager::GetAppWindow().
Referenced by DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick().
OnStop()
void DebuggerToolbarHandler::OnStop (wxCommandEvent & event) private
Definition at line 857 of file debuggermenu.cpp.
References _(), wxMenu::Append(), wxMenuItem::Enable(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetAppWindow(), Manager::GetDebuggerManager(), cbDebuggerPlugin::IsAttachedToProcess(), and cbDebuggerPlugin::IsStopped().
Referenced by DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick().
OnToolInfo()
void DebuggerToolbarHandler::OnToolInfo (wxCommandEvent & event) private
Definition at line 839 of file debuggermenu.cpp.
References Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetAppWindow(), Manager::GetDebuggerManager(), and cbDebuggerPlugin::SetupToolsMenu().
Referenced by DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick().
OnUpdateUI()
void DebuggerToolbarHandler::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 798 of file debuggermenu.cpp.
References Manager::Get(), DebuggerManager::GetActiveDebugger(), ProjectManager::GetActiveProject(), EditorManager::GetBuiltinActiveEditor(), cbProject::GetCurrentlyCompilingTarget(), Manager::GetDebuggerManager(), Manager::GetEditorManager(), ProjectManager::GetIsRunning(), Manager::GetProjectManager(), cbDebuggerPlugin::IsAttachedToProcess(), cbDebuggerPlugin::IsRunning(), cbDebuggerPlugin::IsStopped(), NULL, and cbDebuggerPlugin::ToolMenuEnabled().
Referenced by DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick().
Friends And Related Function Documentation
DebuggerManager
friend class DebuggerManager friend
Definition at line 79 of file debuggermenu.h.
Member Data Documentation
m_menuHandler
DebuggerMenuHandler* DebuggerToolbarHandler::m_menuHandler private
Definition at line 90 of file debuggermenu.h.
m_Toolbar
wxToolBar* DebuggerToolbarHandler::m_Toolbar private
Definition at line 89 of file debuggermenu.h.
The documentation for this class was generated from the following files:
debuggermenu.h
debuggermenu.cpp