Code::Blocks: cbConfigurationPanel Class Reference
cbConfigurationPanel Class Reference abstract
Base class for plugin configuration panels.
#include <configurationpanel.h>
Public Member Functions
cbConfigurationPanel ()
virtual ~cbConfigurationPanel ()
virtual wxString GetTitle () const =0
virtual wxString GetBitmapBaseName () const =0
virtual void OnApply ()=0
Called when the user chooses to apply the configuration.
virtual void OnCancel ()=0
Called when the user chooses to cancel the configuration.
void SetParentDialog (wxWindow *dialog)
Sets the panel's parent dialog.
wxWindow * SetParentDialog ()
Gets the panel's parent dialog.
int cbMessageBox (const wxString &message, const wxString &caption=wxEmptyString, int style=wxOK, wxWindow *parent=NULL, int x=-1, int y=-1)
Call global cbMessageBox with m_parentDialog as parent window when no parent window specified.
Private Attributes
wxWindow * m_parentDialog
Detailed Description
Base class for plugin configuration panels.
Definition at line 19 of file configurationpanel.h.
Constructor & Destructor Documentation
cbConfigurationPanel()
cbConfigurationPanel::cbConfigurationPanel () inline
Definition at line 22 of file configurationpanel.h.
~cbConfigurationPanel()
virtual cbConfigurationPanel::~cbConfigurationPanel () inline virtual
Definition at line 23 of file configurationpanel.h.
Member Function Documentation
cbMessageBox()
int cbConfigurationPanel::cbMessageBox (const wxString & message, const wxString & caption = wxEmptyString, int style = wxOK, wxWindow * parent = NULL, int x = -1, int y = -1) inline
Call global cbMessageBox with m_parentDialog as parent window when no parent window specified.
Definition at line 46 of file configurationpanel.h.
References cbMessageBox().
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), CompilerOptionsDlg::OnAddCompilerClick(), CompilerOptionsDlg::OnAddExtraPathClick(), CCOptionsProjectDlg::OnApply(), CompilerOptionsDlg::OnApply(), CompilerOptionsDlg::OnClearDirClick(), CompilerOptionsDlg::OnClearExtraPathClick(), CompilerOptionsDlg::OnClearLibClick(), CompilerOptionsDlg::OnClearVarClick(), CompilerOptionsDlg::OnCompilerChanged(), CompilerOptionsDlg::OnEditDirClick(), CompilerOptionsDlg::OnEditExtraPathClick(), CompilerOptionsDlg::OnEditLibClick(), CompilerOptionsDlg::OnRemoveCompilerClick(), CompilerOptionsDlg::OnRemoveDirClick(), CompilerOptionsDlg::OnRemoveLibClick(), CompilerOptionsDlg::OnRemoveVarClick(), CompilerOptionsDlg::OnResetCompilerClick(), CompilerOptionsDlg::OnSetDefaultCompilerClick(), CompilerOptionsDlg::ProjectTargetCompilerAdjust(), CompilerOptionsDlg::UpdateCompilerForTargets(), and CCOptionsDlg::ValidateReplacementToken().
GetBitmapBaseName()
virtual wxString cbConfigurationPanel::GetBitmapBaseName () const pure virtual
Returns
the panel's bitmap base name. You must supply two bitmaps: <basename>.png and <basename>-off.png...
Implemented in CompilerOptionsDlg, DebuggerOptionsProjectDlg, CCOptionsDlg, and CCOptionsProjectDlg.
Referenced by CompilerSettingsDlg::AddPluginPanels(), EnvironmentSettingsDlg::AddPluginPanels(), and EditorConfigurationDlg::AddPluginPanels().
GetTitle()
virtual wxString cbConfigurationPanel::GetTitle () const pure virtual
Returns
the panel's title.
Implemented in CompilerOptionsDlg, DebuggerOptionsProjectDlg, CCOptionsDlg, and CCOptionsProjectDlg.
Referenced by CompilerSettingsDlg::AddPluginPanels(), EnvironmentSettingsDlg::AddPluginPanels(), EditorConfigurationDlg::AddPluginPanels(), and ProjectOptionsDlg::AddPluginPanels().
OnApply()
virtual void cbConfigurationPanel::OnApply () pure virtual
Called when the user chooses to apply the configuration.
Implemented in CompilerOptionsDlg, DebuggerOptionsProjectDlg, CCOptionsDlg, and CCOptionsProjectDlg.
Referenced by CompilerSettingsDlg::EndModal(), EnvironmentSettingsDlg::EndModal(), ProjectOptionsDlg::EndModal(), EditorConfigurationDlg::EndModal(), and cbConfigurationDialog::EndModal().
OnCancel()
virtual void cbConfigurationPanel::OnCancel () pure virtual
Called when the user chooses to cancel the configuration.
Implemented in CompilerOptionsDlg, DebuggerOptionsProjectDlg, CCOptionsDlg, and CCOptionsProjectDlg.
Referenced by CompilerSettingsDlg::EndModal(), EnvironmentSettingsDlg::EndModal(), ProjectOptionsDlg::EndModal(), EditorConfigurationDlg::EndModal(), and cbConfigurationDialog::EndModal().
SetParentDialog() [1/2]
void cbConfigurationPanel::SetParentDialog (wxWindow * dialog) inline
Sets the panel's parent dialog.
Definition at line 35 of file configurationpanel.h.
Referenced by CompilerSettingsDlg::AddPluginPanels(), EnvironmentSettingsDlg::AddPluginPanels(), EditorConfigurationDlg::AddPluginPanels(), ProjectOptionsDlg::AddPluginPanels(), and CompilerGCC::Configure().
SetParentDialog() [2/2]
wxWindow* cbConfigurationPanel::SetParentDialog () inline
Gets the panel's parent dialog.
Definition at line 40 of file configurationpanel.h.
Member Data Documentation
m_parentDialog
wxWindow* cbConfigurationPanel::m_parentDialog private
Definition at line 54 of file configurationpanel.h.
The documentation for this class was generated from the following file:
configurationpanel.h