Code::Blocks: ConfigureToolsDlg Class Reference
ConfigureToolsDlg Class Reference
#include <configuretoolsdlg.h>
Public Member Functions
ConfigureToolsDlg (wxWindow *parent)
~ConfigureToolsDlg ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void DoFillList ()
bool DoEditTool (cbTool *tool)
void OnAdd (wxCommandEvent &event)
void OnEdit (wxCommandEvent &event)
void OnRemove (wxCommandEvent &event)
void OnAddSeparator (wxCommandEvent &event)
void OnUp (wxCommandEvent &event)
void OnDown (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 16 of file configuretoolsdlg.h.
Constructor & Destructor Documentation
ConfigureToolsDlg()
ConfigureToolsDlg::ConfigureToolsDlg (wxWindow * parent)
Definition at line 38 of file configuretoolsdlg.cpp.
~ConfigureToolsDlg()
ConfigureToolsDlg::~ConfigureToolsDlg ()
Definition at line 45 of file configuretoolsdlg.cpp.
Member Function Documentation
DoEditTool()
bool ConfigureToolsDlg::DoEditTool (cbTool * tool) private
Definition at line 64 of file configuretoolsdlg.cpp.
References PlaceWindow(), and wxScrollingDialog::ShowModal().
Referenced by OnAdd(), and OnEdit().
DoFillList()
void ConfigureToolsDlg::DoFillList () private
Definition at line 49 of file configuretoolsdlg.cpp.
References Manager::Get(), ToolsManager::GetToolByIndex(), ToolsManager::GetToolsCount(), and Manager::GetToolsManager().
Referenced by OnAdd(), OnAddSeparator(), OnDown(), OnEdit(), OnRemove(), and OnUp().
OnAdd()
void ConfigureToolsDlg::OnAdd (wxCommandEvent & event) private
Definition at line 92 of file configuretoolsdlg.cpp.
References ToolsManager::AddTool(), DoEditTool(), DoFillList(), Manager::Get(), and Manager::GetToolsManager().
OnAddSeparator()
void ConfigureToolsDlg::OnAddSeparator (wxCommandEvent & event) private
Definition at line 124 of file configuretoolsdlg.cpp.
References ToolsManager::AddTool(), CB_TOOLS_SEPARATOR, DoFillList(), Manager::Get(), Manager::GetToolsManager(), cbTool::SetCommand(), and cbTool::SetName().
OnDown()
void ConfigureToolsDlg::OnDown (wxCommandEvent & event) private
Definition at line 145 of file configuretoolsdlg.cpp.
References DoFillList(), Manager::Get(), Manager::GetToolsManager(), ToolsManager::InsertTool(), and ToolsManager::RemoveToolByIndex().
OnEdit()
void ConfigureToolsDlg::OnEdit (wxCommandEvent & event) private
Definition at line 102 of file configuretoolsdlg.cpp.
References DoEditTool(), DoFillList(), Manager::Get(), ToolsManager::GetToolByIndex(), and Manager::GetToolsManager().
OnRemove()
void ConfigureToolsDlg::OnRemove (wxCommandEvent & event) private
Definition at line 110 of file configuretoolsdlg.cpp.
References CB_TOOLS_SEPARATOR, cbMessageBox(), DoFillList(), Manager::Get(), Manager::GetToolsManager(), and ToolsManager::RemoveToolByIndex().
OnUp()
void ConfigureToolsDlg::OnUp (wxCommandEvent & event) private
Definition at line 133 of file configuretoolsdlg.cpp.
References DoFillList(), Manager::Get(), Manager::GetToolsManager(), ToolsManager::InsertTool(), and ToolsManager::RemoveToolByIndex().
OnUpdateUI()
void ConfigureToolsDlg::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 75 of file configuretoolsdlg.cpp.
References CB_TOOLS_SEPARATOR, Manager::Get(), ToolsManager::GetToolByIndex(), and Manager::GetToolsManager().
The documentation for this class was generated from the following files:
configuretoolsdlg.h
configuretoolsdlg.cpp