Code::Blocks: BuildTargetPanel Class Reference
BuildTargetPanel Class Reference
#include <buildtargetpanel.h>
Public Member Functions
BuildTargetPanel (wxWindow *parent, wxWindowID id=-1)
virtual ~BuildTargetPanel ()
void ShowCompiler (bool show)
void SetTargetName (const wxString &name)
void SetEnableDebug (bool debug)
wxComboBox * GetCompilerCombo ()
bool GetEnableDebug () const
wxString GetTargetName () const
wxString GetOutputDir () const
wxString GetObjectOutputDir () const
Static Public Attributes
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_STATICTEXT3 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_COMBOBOX1 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_TEXTCTRL2 = wxNewId()
static const long ID_STATICTEXT5 = wxNewId()
static const long ID_TEXTCTRL3 = wxNewId()
static const long ID_CHECKBOX1 = wxNewId()
Private Member Functions
void OntxtNameText (wxCommandEvent &event)
Private Attributes
wxComboBox * cmbCompiler
wxTextCtrl * txtName
wxStaticText * lblCompiler
wxTextCtrl * txtOut
wxStaticText * StaticText3
wxCheckBox * chkEnableDebug
wxBoxSizer * BoxSizer1
wxTextCtrl * txtObjOut
Detailed Description
Definition at line 21 of file buildtargetpanel.h.
Constructor & Destructor Documentation
BuildTargetPanel()
BuildTargetPanel::BuildTargetPanel (wxWindow * parent, wxWindowID id = -1)
Definition at line 39 of file buildtargetpanel.cpp.
References _(), _T, wxBoxSizer::Add(), wxFlexGridSizer::AddGrowableCol(), ID_TEXTCTRL1, OntxtNameText(), wxALIGN_LEFT, wxALL, wxBOTTOM, wxCB_READONLY, wxCB_SIMPLE, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxLEFT, wxRIGHT, wxTAB_TRAVERSAL, wxTOP, and wxVERTICAL.
~BuildTargetPanel()
BuildTargetPanel::~BuildTargetPanel () virtual
Definition at line 84 of file buildtargetpanel.cpp.
Member Function Documentation
GetCompilerCombo()
wxComboBox* BuildTargetPanel::GetCompilerCombo () inline
Definition at line 42 of file buildtargetpanel.h.
References cmbCompiler.
Referenced by WizBuildTargetPanel::GetCompilerID(), WizBuildTargetPanel::OnPageChanging(), and WizBuildTargetPanel::WizBuildTargetPanel().
GetEnableDebug()
bool BuildTargetPanel::GetEnableDebug () const inline
Definition at line 43 of file buildtargetpanel.h.
References chkEnableDebug, and wxCheckBox::IsChecked().
Referenced by WizBuildTargetPanel::GetEnableDebug().
GetObjectOutputDir()
wxString BuildTargetPanel::GetObjectOutputDir () const inline
Definition at line 46 of file buildtargetpanel.h.
References txtObjOut.
Referenced by WizBuildTargetPanel::GetTargetObjectOutputDir().
GetOutputDir()
wxString BuildTargetPanel::GetOutputDir () const inline
Definition at line 45 of file buildtargetpanel.h.
References txtOut.
Referenced by WizBuildTargetPanel::GetTargetOutputDir().
GetTargetName()
wxString BuildTargetPanel::GetTargetName () const inline
Definition at line 44 of file buildtargetpanel.h.
References txtName.
Referenced by WizBuildTargetPanel::GetTargetName(), and WizBuildTargetPanel::OnPageChanging().
OntxtNameText()
void BuildTargetPanel::OntxtNameText (wxCommandEvent & event) private
Definition at line 89 of file buildtargetpanel.cpp.
References _T, txtName, txtObjOut, and txtOut.
Referenced by BuildTargetPanel().
SetEnableDebug()
void BuildTargetPanel::SetEnableDebug (bool debug) inline
Definition at line 37 of file buildtargetpanel.h.
References chkEnableDebug, and wxCheckBox::SetValue().
Referenced by WizBuildTargetPanel::WizBuildTargetPanel().
SetTargetName()
void BuildTargetPanel::SetTargetName (const wxString & name) inline
Definition at line 33 of file buildtargetpanel.h.
References txtName.
Referenced by WizBuildTargetPanel::WizBuildTargetPanel().
ShowCompiler()
void BuildTargetPanel::ShowCompiler (bool show) inline
Definition at line 28 of file buildtargetpanel.h.
References cmbCompiler, and lblCompiler.
Referenced by WizBuildTargetPanel::WizBuildTargetPanel().
Member Data Documentation
BoxSizer1
wxBoxSizer* BuildTargetPanel::BoxSizer1 private
Definition at line 75 of file buildtargetpanel.h.
chkEnableDebug
wxCheckBox* BuildTargetPanel::chkEnableDebug private
Definition at line 74 of file buildtargetpanel.h.
Referenced by GetEnableDebug(), and SetEnableDebug().
cmbCompiler
wxComboBox* BuildTargetPanel::cmbCompiler private
Definition at line 69 of file buildtargetpanel.h.
Referenced by GetCompilerCombo(), and ShowCompiler().
ID_CHECKBOX1
const long BuildTargetPanel::ID_CHECKBOX1 = wxNewId() static
Definition at line 59 of file buildtargetpanel.h.
ID_COMBOBOX1
const long BuildTargetPanel::ID_COMBOBOX1 = wxNewId() static
Definition at line 54 of file buildtargetpanel.h.
ID_STATICTEXT1
const long BuildTargetPanel::ID_STATICTEXT1 = wxNewId() static
Definition at line 50 of file buildtargetpanel.h.
ID_STATICTEXT2
const long BuildTargetPanel::ID_STATICTEXT2 = wxNewId() static
Definition at line 53 of file buildtargetpanel.h.
ID_STATICTEXT3
const long BuildTargetPanel::ID_STATICTEXT3 = wxNewId() static
Definition at line 51 of file buildtargetpanel.h.
ID_STATICTEXT4
const long BuildTargetPanel::ID_STATICTEXT4 = wxNewId() static
Definition at line 55 of file buildtargetpanel.h.
ID_STATICTEXT5
const long BuildTargetPanel::ID_STATICTEXT5 = wxNewId() static
Definition at line 57 of file buildtargetpanel.h.
ID_TEXTCTRL1
const long BuildTargetPanel::ID_TEXTCTRL1 = wxNewId() static
Definition at line 52 of file buildtargetpanel.h.
ID_TEXTCTRL2
const long BuildTargetPanel::ID_TEXTCTRL2 = wxNewId() static
Definition at line 56 of file buildtargetpanel.h.
ID_TEXTCTRL3
const long BuildTargetPanel::ID_TEXTCTRL3 = wxNewId() static
Definition at line 58 of file buildtargetpanel.h.
lblCompiler
wxStaticText* BuildTargetPanel::lblCompiler private
Definition at line 71 of file buildtargetpanel.h.
Referenced by ShowCompiler().
StaticText3
wxStaticText* BuildTargetPanel::StaticText3 private
Definition at line 73 of file buildtargetpanel.h.
txtName
wxTextCtrl* BuildTargetPanel::txtName private
Definition at line 70 of file buildtargetpanel.h.
Referenced by GetTargetName(), OntxtNameText(), and SetTargetName().
txtObjOut
wxTextCtrl* BuildTargetPanel::txtObjOut private
Definition at line 76 of file buildtargetpanel.h.
Referenced by GetObjectOutputDir(), and OntxtNameText().
txtOut
wxTextCtrl* BuildTargetPanel::txtOut private
Definition at line 72 of file buildtargetpanel.h.
Referenced by GetOutputDir(), and OntxtNameText().
The documentation for this class was generated from the following files:
buildtargetpanel.h
buildtargetpanel.cpp