Code::Blocks: GetUserVariableDialog Class Reference
GetUserVariableDialog Class Reference
Public Member Functions
GetUserVariableDialog (wxString old)
wxString GetVariable ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void OnOK (cb_unused wxCommandEvent &event)
void OnCancel (cb_unused wxCommandEvent &event)
void OnConfig (cb_unused wxCommandEvent &event)
void OnActivated (wxTreeEvent &event)
void Load ()
wxString GetSelectedVariable ()
Private Attributes
wxTreeCtrl * m_treectrl
wxString m_SelectedVar
wxString m_old
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 68 of file uservarmanager.cpp.
Constructor & Destructor Documentation
GetUserVariableDialog()
GetUserVariableDialog::GetUserVariableDialog (wxString old)
Definition at line 322 of file uservarmanager.cpp.
References Manager::Get(), Manager::GetLogManager(), Load(), LogManager::LogError(), m_old, m_treectrl, and SetMinSize().
Member Function Documentation
GetSelectedVariable()
wxString GetUserVariableDialog::GetSelectedVariable () private
Definition at line 419 of file uservarmanager.cpp.
References UsrGlblMgrEditDialog::CloneSet(), UsrGlblMgrEditDialog::CloneVar(), UsrGlblMgrEditDialog::CloseHandler(), UsrGlblMgrEditDialog::DeleteSet(), UsrGlblMgrEditDialog::DeleteVar(), UsrGlblMgrEditDialog::Help(), m_treectrl, UsrGlblMgrEditDialog::NewSet(), UsrGlblMgrEditDialog::NewVar(), UsrGlblMgrEditDialog::OnFS(), UsrGlblMgrEditDialog::OnOK(), UsrGlblMgrEditDialog::SelectSet(), and UsrGlblMgrEditDialog::SelectVar().
Referenced by OnActivated(), and OnOK().
GetVariable()
wxString GetUserVariableDialog::GetVariable () inline
Definition at line 85 of file uservarmanager.cpp.
References m_SelectedVar.
Referenced by UserVariableManager::GetVariable().
Load()
void GetUserVariableDialog::Load () private
Definition at line 371 of file uservarmanager.cpp.
References cSets(), ConfigManager::EnumerateKeys(), ConfigManager::EnumerateSubPaths(), Manager::Get(), Manager::GetConfigManager(), m_treectrl, and ConfigManager::Read().
Referenced by UsrGlblMgrEditDialog::AddVar(), UsrGlblMgrEditDialog::CloneSet(), UsrGlblMgrEditDialog::CloneVar(), UsrGlblMgrEditDialog::CloseHandler(), UsrGlblMgrEditDialog::DeleteSet(), UsrGlblMgrEditDialog::DeleteVar(), GetUserVariableDialog(), UsrGlblMgrEditDialog::NewSet(), OnConfig(), UsrGlblMgrEditDialog::SelectSet(), UsrGlblMgrEditDialog::SelectVar(), and UsrGlblMgrEditDialog::UsrGlblMgrEditDialog().
OnActivated()
void GetUserVariableDialog::OnActivated (wxTreeEvent & event) private
Definition at line 401 of file uservarmanager.cpp.
References ScriptBindings::EndModal(), GetSelectedVariable(), and m_SelectedVar.
Referenced by UserVariableManager::GetVariable().
OnCancel()
void GetUserVariableDialog::OnCancel (cb_unused wxCommandEvent & event) private
Definition at line 407 of file uservarmanager.cpp.
References ScriptBindings::EndModal(), and m_SelectedVar.
Referenced by UserVariableManager::GetVariable().
OnConfig()
void GetUserVariableDialog::OnConfig (cb_unused wxCommandEvent & event) private
Definition at line 413 of file uservarmanager.cpp.
References UserVariableManager::Configure(), Manager::Get(), Manager::GetUserVariableManager(), and Load().
Referenced by UserVariableManager::GetVariable().
OnOK()
void GetUserVariableDialog::OnOK (cb_unused wxCommandEvent & event) private
Definition at line 395 of file uservarmanager.cpp.
References ScriptBindings::EndModal(), GetSelectedVariable(), and m_SelectedVar.
Referenced by UserVariableManager::GetVariable().
Member Data Documentation
m_old
wxString GetUserVariableDialog::m_old private
Definition at line 72 of file uservarmanager.cpp.
Referenced by GetUserVariableDialog().
m_SelectedVar
wxString GetUserVariableDialog::m_SelectedVar private
Definition at line 71 of file uservarmanager.cpp.
Referenced by GetVariable(), OnActivated(), OnCancel(), and OnOK().
m_treectrl
wxTreeCtrl* GetUserVariableDialog::m_treectrl private
Definition at line 70 of file uservarmanager.cpp.
Referenced by GetSelectedVariable(), GetUserVariableDialog(), and Load().
The documentation for this class was generated from the following file:
uservarmanager.cpp