Code::Blocks: FileLoader Class Reference
FileLoader Class Reference
#include <filemanager.h>
Public Member Functions
FileLoader (const wxString &name)
void operator() ()
Public Member Functions inherited from LoaderBase
LoaderBase ()
~LoaderBase ()
wxString FileName () const
bool Sync ()
char * GetData ()
size_t GetLength ()
Public Member Functions inherited from AbstractJob
AbstractJob ()
virtual ~AbstractJob ()
Additional Inherited Members
Protected Member Functions inherited from LoaderBase
void Ready ()
Protected Attributes inherited from LoaderBase
wxString fileName
char * data
size_t len
Detailed Description
Definition at line 67 of file filemanager.h.
Constructor & Destructor Documentation
FileLoader()
FileLoader::FileLoader (const wxString & name) inline
Definition at line 70 of file filemanager.h.
Member Function Documentation
operator()()
void FileLoader::operator() () virtual
Reimplemented from LoaderBase.
Definition at line 55 of file filemanager.cpp.
References wxFile::Access(), LoaderBase::data, wxFileName::DirExists(), LoaderBase::fileName, LoaderBase::len, wxFile::Length(), wxFile::Read(), wxFile::read, LoaderBase::Ready(), and wxInvalidOffset.
The documentation for this class was generated from the following files:
filemanager.h
filemanager.cpp