Code::Blocks: wxDialogHelper Class Reference
wxDialogHelper Class Reference
#include <scrollingdialog.h>
Public Member Functions
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Static Public Member Functions
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
A base class for dialogs that have adaptation. In wxWidgets 3.0, this will not be needed since the new functionality will be implemented in wxDialogBase.
Definition at line 97 of file scrollingdialog.h.
Constructor & Destructor Documentation
wxDialogHelper()
wxDialogHelper::wxDialogHelper (wxDialog * dialog = NULL) inline
Definition at line 101 of file scrollingdialog.h.
~wxDialogHelper()
virtual wxDialogHelper::~wxDialogHelper () inline virtual
Definition at line 102 of file scrollingdialog.h.
Member Function Documentation
AddButtonId()
void wxDialogHelper::AddButtonId (wxWindowID id) inline
Add an id to the list of custom button identifiers that should be in the button sizer.
Definition at line 119 of file scrollingdialog.h.
CanDoLayoutAdaptation()
bool wxDialogHelper::CanDoLayoutAdaptation () virtual
Can we do the adaptation?
Definition at line 59 of file scrollingdialog.cpp.
References GetLayoutAdaptation(), GetLayoutAdaptationLevel(), GetLayoutAdapter(), m_layoutLayoutAdaptationDone, and NULL.
Referenced by wxScrollingDialog::Show(), wxScrollingPropertySheetDialog::Show(), wxScrollingDialog::ShowModal(), and wxScrollingPropertySheetDialog::ShowModal().
DoLayoutAdaptation()
bool wxDialogHelper::DoLayoutAdaptation () virtual
Do the adaptation.
Definition at line 50 of file scrollingdialog.cpp.
References wxDialogLayoutAdapter::DoLayoutAdaptation(), and GetLayoutAdapter().
Referenced by wxScrollingDialog::Show(), wxScrollingPropertySheetDialog::Show(), wxScrollingDialog::ShowModal(), and wxScrollingPropertySheetDialog::ShowModal().
GetButtonIds()
wxArrayInt& wxDialogHelper::GetButtonIds () inline
Definition at line 120 of file scrollingdialog.h.
GetContentWindow()
virtual wxWindow* wxDialogHelper::GetContentWindow () const inline virtual
Returns a content window if there is one.
Reimplemented in wxScrollingPropertySheetDialog.
Definition at line 116 of file scrollingdialog.h.
References NULL.
Referenced by wxStandardDialogLayoutAdapter::DoLayoutAdaptation().
GetDialog()
wxDialog* wxDialogHelper::GetDialog () const inline
Definition at line 107 of file scrollingdialog.h.
References wxDialogLayoutAdapter::CanDoLayoutAdaptation(), and wxDialogLayoutAdapter::DoLayoutAdaptation().
Referenced by wxStandardDialogLayoutAdapter::DoLayoutAdaptation(), and SetLayoutAdapter().
GetLayoutAdaptation()
static bool wxDialogHelper::GetLayoutAdaptation () inline static
Global switch for layout adaptation.
Definition at line 145 of file scrollingdialog.h.
Referenced by CanDoLayoutAdaptation().
GetLayoutAdaptationDone()
bool wxDialogHelper::GetLayoutAdaptationDone () const inline
Definition at line 138 of file scrollingdialog.h.
GetLayoutAdaptationLevel()
int wxDialogHelper::GetLayoutAdaptationLevel () const inline
Get level of adaptation.
Definition at line 134 of file scrollingdialog.h.
Referenced by CanDoLayoutAdaptation(), and wxStandardDialogLayoutAdapter::DoLayoutAdaptation().
GetLayoutAdapter()
static wxDialogLayoutAdapter* wxDialogHelper::GetLayoutAdapter () inline static
Definition at line 142 of file scrollingdialog.h.
Referenced by CanDoLayoutAdaptation(), and DoLayoutAdaptation().
Init()
void wxDialogHelper::Init ()
Definition at line 43 of file scrollingdialog.cpp.
References m_layoutAdaptationLevel, and m_layoutLayoutAdaptationDone.
IsUserButtonId()
bool wxDialogHelper::IsUserButtonId (wxWindowID id) inline
Is this id in the custom button id array?
Definition at line 123 of file scrollingdialog.h.
Referenced by wxStandardDialogLayoutAdapter::IsStandardButton().
SetDialog()
void wxDialogHelper::SetDialog (wxDialog * dialog) inline
Definition at line 106 of file scrollingdialog.h.
Referenced by wxScrollingDialog::Init(), and wxScrollingPropertySheetDialog::Init().
SetLayoutAdaptation()
static void wxDialogHelper::SetLayoutAdaptation (bool enable) inline static
Definition at line 146 of file scrollingdialog.h.
SetLayoutAdaptationDone()
void wxDialogHelper::SetLayoutAdaptationDone (bool adaptationDone) inline
Returns true if the adaptation has been done.
Definition at line 137 of file scrollingdialog.h.
Referenced by wxStandardDialogLayoutAdapter::DoLayoutAdaptation().
SetLayoutAdaptationLevel()
void wxDialogHelper::SetLayoutAdaptationLevel (int level) inline
Level of adaptation, from none (Level 0) to full (Level 3).
To disable adaptation, set level 0, for example in your dialog constructor. You might do this if you know that you are displaying on a large screen and you don't want the dialog changed.
Definition at line 131 of file scrollingdialog.h.
SetLayoutAdapter()
wxDialogLayoutAdapter * wxDialogHelper::SetLayoutAdapter (wxDialogLayoutAdapter * adapter) static
Set layout adapter class, returning old adapter.
Set scrolling adapter class, returning old adapter.
Definition at line 65 of file scrollingdialog.cpp.
References wxStandardDialogLayoutAdapter::CanDoLayoutAdaptation(), GetDialog(), and sm_layoutAdapter.
Referenced by wxDialogLayoutAdapterModule::OnExit(), and wxDialogLayoutAdapterModule::OnInit().
Member Data Documentation
m_buttonIds
wxArrayInt wxDialogHelper::m_buttonIds protected
Definition at line 152 of file scrollingdialog.h.
m_dialog
wxDialog* wxDialogHelper::m_dialog protected
Definition at line 150 of file scrollingdialog.h.
m_layoutAdaptationLevel
int wxDialogHelper::m_layoutAdaptationLevel protected
Definition at line 153 of file scrollingdialog.h.
Referenced by Init().
m_layoutLayoutAdaptationDone
bool wxDialogHelper::m_layoutLayoutAdaptationDone protected
Definition at line 151 of file scrollingdialog.h.
Referenced by CanDoLayoutAdaptation(), and Init().
sm_layoutAdaptation
bool wxDialogHelper::sm_layoutAdaptation = true static protected
Definition at line 155 of file scrollingdialog.h.
sm_layoutAdapter
wxDialogLayoutAdapter * wxDialogHelper::sm_layoutAdapter = NULL static protected
Dialog helper. This contains the extra members that in wxWidgets 3.0 will be in wxDialogBase.
Definition at line 154 of file scrollingdialog.h.
Referenced by SetLayoutAdapter().
The documentation for this class was generated from the following files:
scrollingdialog.h
scrollingdialog.cpp