Code::Blocks: WizBuildTargetPanel Class Reference
WizBuildTargetPanel Class Reference
#include <wizpage.h>
Public Member Functions
WizBuildTargetPanel (const wxString &targetName, bool isDebug, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap, bool showCompiler=false, const wxString &compilerID=wxEmptyString, const wxString &validCompilerIDs=_T("*"), bool allowCompilerChange=true)
~WizBuildTargetPanel ()
wxString GetCompilerID () const
bool GetEnableDebug () const
wxString GetTargetName () const
wxString GetTargetOutputDir () const
wxString GetTargetObjectOutputDir () const
void OnPageChanging (wxWizardEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
BuildTargetPanel * m_pBuildTargetPanel
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 157 of file wizpage.h.
Constructor & Destructor Documentation
WizBuildTargetPanel()
WizBuildTargetPanel::WizBuildTargetPanel (const wxString & targetName, bool isDebug, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap, bool showCompiler = false, const wxString & compilerID = wxEmptyString, const wxString & validCompilerIDs = _T("*"), bool allowCompilerChange = true)
Definition at line 620 of file wizpage.cpp.
References _T, Wizard::FillCompilerControl(), BuildTargetPanel::GetCompilerCombo(), m_pBuildTargetPanel, BuildTargetPanel::SetEnableDebug(), BuildTargetPanel::SetTargetName(), and BuildTargetPanel::ShowCompiler().
~WizBuildTargetPanel()
WizBuildTargetPanel::~WizBuildTargetPanel ()
Definition at line 641 of file wizpage.cpp.
Member Function Documentation
GetCompilerID()
wxString WizBuildTargetPanel::GetCompilerID () const
Definition at line 646 of file wizpage.cpp.
References CompilerFactory::GetCompilerByName(), BuildTargetPanel::GetCompilerCombo(), Compiler::GetID(), m_pBuildTargetPanel, and wxEmptyString.
Referenced by Wiz::GetCompilerID(), Wiz::GetTargetCompilerID(), and OnPageChanging().
GetEnableDebug()
bool WizBuildTargetPanel::GetEnableDebug () const
Definition at line 658 of file wizpage.cpp.
References BuildTargetPanel::GetEnableDebug(), and m_pBuildTargetPanel.
Referenced by Wiz::GetTargetEnableDebug().
GetTargetName()
wxString WizBuildTargetPanel::GetTargetName () const
Definition at line 664 of file wizpage.cpp.
References BuildTargetPanel::GetTargetName(), and m_pBuildTargetPanel.
Referenced by Wiz::GetTargetName().
GetTargetObjectOutputDir()
wxString WizBuildTargetPanel::GetTargetObjectOutputDir () const
Definition at line 676 of file wizpage.cpp.
References AppendPathSepIfNeeded(), BuildTargetPanel::GetObjectOutputDir(), and m_pBuildTargetPanel.
Referenced by Wiz::GetTargetObjectOutputDir().
GetTargetOutputDir()
wxString WizBuildTargetPanel::GetTargetOutputDir () const
Definition at line 670 of file wizpage.cpp.
References AppendPathSepIfNeeded(), BuildTargetPanel::GetOutputDir(), and m_pBuildTargetPanel.
Referenced by Wiz::GetTargetOutputDir().
OnPageChanging()
void WizBuildTargetPanel::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 682 of file wizpage.cpp.
References _(), cbMessageBox(), Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetBuildTarget(), BuildTargetPanel::GetCompilerCombo(), GetCompilerID(), wxWizardEvent::GetDirection(), Manager::GetProjectManager(), BuildTargetPanel::GetTargetName(), wxString::IsEmpty(), m_pBuildTargetPanel, WizPageBase::OnPageChanging(), and wxICON_ERROR.
Member Data Documentation
m_pBuildTargetPanel
BuildTargetPanel* WizBuildTargetPanel::m_pBuildTargetPanel private
Definition at line 175 of file wizpage.h.
Referenced by GetCompilerID(), GetEnableDebug(), GetTargetName(), GetTargetObjectOutputDir(), GetTargetOutputDir(), OnPageChanging(), and WizBuildTargetPanel().
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp