Code::Blocks: GdbCmd_FindWatchType Class Reference
GdbCmd_FindWatchType Class Reference
Command to get a watched variable's type.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_FindWatchType (DebuggerDriver *driver, cb::shared_ptr< GDBWatch > watch, bool firstTry=true)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
cb::shared_ptr< GDBWatch > m_watch
bool m_firstTry
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to get a watched variable's type.
Definition at line 854 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_FindWatchType()
GdbCmd_FindWatchType::GdbCmd_FindWatchType (DebuggerDriver * driver, cb::shared_ptr< GDBWatch > watch, bool firstTry = true) inline
Definition at line 859 of file gdb_commands.h.
References DebuggerCmd::m_Cmd, and wxT.
Member Function Documentation
ParseOutput()
void GdbCmd_FindWatchType::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 872 of file gdb_commands.h.
References _(), _T, wxString::AfterFirst(), wxString::empty(), wxString::EndsWith(), DebuggerDriver::High, wxString::length(), DebuggerCmd::m_pDriver, DebuggerDriver::QueueCommand(), wxString::StartsWith(), wxString::substr(), wxEmptyString, and wxT.
Member Data Documentation
m_firstTry
bool GdbCmd_FindWatchType::m_firstTry private
Definition at line 857 of file gdb_commands.h.
m_watch
cb::shared_ptr<GDBWatch> GdbCmd_FindWatchType::m_watch private
Definition at line 856 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h