Code::Blocks: BreakpointsDlg Class Reference
BreakpointsDlg Class Reference
#include <breakpointsdlg.h>
Classes
struct Item
Public Member Functions
BreakpointsDlg ()
wxWindow * GetWindow ()
bool AddBreakpoint (cbDebuggerPlugin *plugin, const wxString &filename, int line)
bool RemoveBreakpoint (cbDebuggerPlugin *plugin, const wxString &filename, int line)
void RemoveAllBreakpoints ()
void EditBreakpoint (const wxString &filename, int line)
void EnableBreakpoint (const wxString &filename, int line, bool enable)
void Reload ()
Public Member Functions inherited from cbBreakpointsDlg
virtual ~cbBreakpointsDlg ()
Private Types
enum Columns {
Type = 0, FilenameAddress, Line, Info,
Debugger
}
typedef std::vector< Item > Items
Private Member Functions
void OnRemove (wxCommandEvent &event)
void OnRemoveAll (wxCommandEvent &event)
void OnProperties (wxCommandEvent &event)
void OnOpen (wxCommandEvent &event)
void OnEnable (wxCommandEvent &event)
void OnShowTemp (wxCommandEvent &event)
void OnRightClick (wxListEvent &event)
void OnDoubleClick (wxListEvent &event)
void OnBreakpointAdd (CodeBlocksEvent &event)
void OnBreakpointEdit (CodeBlocksEvent &event)
void OnKeyUp (wxKeyEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Items::iterator FindBreakpoint (const wxString &filename, int line)
void BreakpointProperties (const Item &item)
Private Attributes
wxListCtrl * m_pList
Items m_breakpoints
wxImageList m_icons
Friends
struct FindBreakpointPred
Detailed Description
Definition at line 24 of file breakpointsdlg.h.
Member Typedef Documentation
Items
typedef std::vector<Item> BreakpointsDlg::Items private
Definition at line 77 of file breakpointsdlg.h.
Member Enumeration Documentation
Columns
enum BreakpointsDlg::Columns private
Enumerator
Type
FilenameAddress
Line
Info
Debugger
Definition at line 53 of file breakpointsdlg.h.
Constructor & Destructor Documentation
BreakpointsDlg()
BreakpointsDlg::BreakpointsDlg ()
Definition at line 69 of file breakpointsdlg.cpp.
References cbLoadBitmap(), ConfigManager::GetDataFolder(), OnDoubleClick(), and OnRightClick().
Member Function Documentation
AddBreakpoint()
bool BreakpointsDlg::AddBreakpoint (cbDebuggerPlugin * plugin, const wxString & filename, int line) virtual
Implements cbBreakpointsDlg.
Definition at line 171 of file breakpointsdlg.cpp.
References cbDebuggerPlugin::AddBreakpoint(), and Reload().
Referenced by GetWindow().
BreakpointProperties()
void BreakpointsDlg::BreakpointProperties (const Item & item) private
Definition at line 312 of file breakpointsdlg.cpp.
References BreakpointsDlg::Item::breakpoint, Manager::Get(), Manager::GetEditorManager(), EditorManager::IsBuiltinOpen(), BreakpointsDlg::Item::plugin, cbEditor::RefreshBreakpointMarkers(), Reload(), and cbDebuggerPlugin::UpdateBreakpoint().
Referenced by EditBreakpoint(), and OnProperties().
EditBreakpoint()
void BreakpointsDlg::EditBreakpoint (const wxString & filename, int line) virtual
Implements cbBreakpointsDlg.
Definition at line 248 of file breakpointsdlg.cpp.
References BreakpointProperties(), FindBreakpoint(), and m_breakpoints.
Referenced by GetWindow().
EnableBreakpoint()
void BreakpointsDlg::EnableBreakpoint (const wxString & filename, int line, bool enable) virtual
Implements cbBreakpointsDlg.
Definition at line 255 of file breakpointsdlg.cpp.
References FindBreakpoint(), Manager::Get(), Manager::GetEditorManager(), EditorManager::IsBuiltinOpen(), m_breakpoints, cbEditor::RefreshBreakpointMarkers(), and Reload().
Referenced by GetWindow().
FindBreakpoint()
BreakpointsDlg::Items::iterator BreakpointsDlg::FindBreakpoint (const wxString & filename, int line) private
Definition at line 158 of file breakpointsdlg.cpp.
References m_breakpoints.
Referenced by EditBreakpoint(), and EnableBreakpoint().
GetWindow()
wxWindow* BreakpointsDlg::GetWindow () inline virtual
Implements cbBreakpointsDlg.
Definition at line 29 of file breakpointsdlg.h.
References AddBreakpoint(), EditBreakpoint(), EnableBreakpoint(), OnBreakpointAdd(), OnBreakpointEdit(), OnDoubleClick(), OnEnable(), OnKeyUp(), OnOpen(), OnProperties(), OnRemove(), OnRemoveAll(), OnRightClick(), OnShowTemp(), OnUpdateUI(), Reload(), RemoveAllBreakpoints(), and RemoveBreakpoint().
OnBreakpointAdd()
void BreakpointsDlg::OnBreakpointAdd (CodeBlocksEvent & event) private
Definition at line 401 of file breakpointsdlg.cpp.
References cbDebuggerPlugin::AddBreakpoint(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), and Reload().
Referenced by GetWindow().
OnBreakpointEdit()
void BreakpointsDlg::OnBreakpointEdit (CodeBlocksEvent & event) private
Definition at line 411 of file breakpointsdlg.cpp.
References Manager::Get(), EditorManager::GetEditor(), Manager::GetEditorManager(), EditorBase::IsBuiltinEditor(), m_breakpoints, and Reload().
Referenced by GetWindow().
OnDoubleClick()
void BreakpointsDlg::OnDoubleClick (wxListEvent & event) private
Definition at line 386 of file breakpointsdlg.cpp.
References OnOpen().
Referenced by BreakpointsDlg(), and GetWindow().
OnEnable()
void BreakpointsDlg::OnEnable (wxCommandEvent & event) private
Definition at line 446 of file breakpointsdlg.cpp.
References BreakpointsDlg::Item::breakpoint, cbDebuggerPlugin::EnableBreakpoint(), Manager::Get(), Manager::GetEditorManager(), EditorManager::IsBuiltinOpen(), m_breakpoints, m_pList, BreakpointsDlg::Item::plugin, and Reload().
Referenced by GetWindow().
OnKeyUp()
void BreakpointsDlg::OnKeyUp (wxKeyEvent & event) private
Definition at line 392 of file breakpointsdlg.cpp.
References OnRemove().
Referenced by GetWindow().
OnOpen()
void BreakpointsDlg::OnOpen (wxCommandEvent & event) private
Definition at line 324 of file breakpointsdlg.cpp.
References EditorBase::Activate(), BreakpointsDlg::Item::breakpoint, Manager::Get(), Manager::GetEditorManager(), cbEditor::GotoLine(), m_breakpoints, m_pList, and EditorManager::Open().
Referenced by GetWindow(), and OnDoubleClick().
OnProperties()
void BreakpointsDlg::OnProperties (wxCommandEvent & event) private
Definition at line 304 of file breakpointsdlg.cpp.
References BreakpointProperties(), m_breakpoints, and m_pList.
Referenced by GetWindow().
OnRemove()
void BreakpointsDlg::OnRemove (wxCommandEvent & event) private
Definition at line 271 of file breakpointsdlg.cpp.
References BreakpointsDlg::Item::breakpoint, cbDebuggerPlugin::DeleteBreakpoint(), Manager::Get(), Manager::GetEditorManager(), EditorManager::IsBuiltinOpen(), m_breakpoints, m_pList, BreakpointsDlg::Item::plugin, and Reload().
Referenced by GetWindow(), and OnKeyUp().
OnRemoveAll()
void BreakpointsDlg::OnRemoveAll (wxCommandEvent & event) private
Definition at line 299 of file breakpointsdlg.cpp.
References RemoveAllBreakpoints().
Referenced by GetWindow().
OnRightClick()
void BreakpointsDlg::OnRightClick (wxListEvent & event) private
Definition at line 343 of file breakpointsdlg.cpp.
References idProperties, m_breakpoints, and m_pList.
Referenced by BreakpointsDlg(), and GetWindow().
OnShowTemp()
void BreakpointsDlg::OnShowTemp (wxCommandEvent & event) private
Definition at line 433 of file breakpointsdlg.cpp.
References cbDebuggerCommonConfig::GetFlag(), Reload(), cbDebuggerCommonConfig::SetFlag(), and cbDebuggerCommonConfig::ShowTemporaryBreakpoints.
Referenced by GetWindow().
OnUpdateUI()
void BreakpointsDlg::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 440 of file breakpointsdlg.cpp.
References cbDebuggerCommonConfig::GetFlag(), and cbDebuggerCommonConfig::ShowTemporaryBreakpoints.
Referenced by GetWindow().
Reload()
void BreakpointsDlg::Reload () virtual
Implements cbBreakpointsDlg.
Definition at line 110 of file breakpointsdlg.cpp.
References Debugger, FilenameAddress, Manager::Get(), DebuggerManager::GetActiveDebugger(), DebuggerManager::GetAllDebuggers(), Manager::GetDebuggerManager(), cbDebuggerCommonConfig::GetFlag(), Info, Line, m_breakpoints, m_pList, cbDebuggerCommonConfig::ShowTemporaryBreakpoints, and Type.
Referenced by AddBreakpoint(), BreakpointProperties(), EnableBreakpoint(), GetWindow(), OnBreakpointAdd(), OnBreakpointEdit(), OnEnable(), OnRemove(), OnShowTemp(), RemoveAllBreakpoints(), and RemoveBreakpoint().
RemoveAllBreakpoints()
void BreakpointsDlg::RemoveAllBreakpoints () virtual
Implements cbBreakpointsDlg.
Definition at line 218 of file breakpointsdlg.cpp.
References Manager::Get(), Manager::GetEditorManager(), cbBreakpoint::GetLocation(), EditorManager::IsBuiltinOpen(), cbBreakpoint::IsVisibleInEditor(), m_breakpoints, and Reload().
Referenced by GetWindow(), and OnRemoveAll().
RemoveBreakpoint()
bool BreakpointsDlg::RemoveBreakpoint (cbDebuggerPlugin * plugin, const wxString & filename, int line) virtual
Implements cbBreakpointsDlg.
Definition at line 202 of file breakpointsdlg.cpp.
References FindBreakpointPred, m_breakpoints, and Reload().
Referenced by GetWindow().
Friends And Related Function Documentation
FindBreakpointPred
friend struct FindBreakpointPred friend
Definition at line 62 of file breakpointsdlg.h.
Referenced by RemoveBreakpoint().
Member Data Documentation
m_breakpoints
Items BreakpointsDlg::m_breakpoints private
Definition at line 84 of file breakpointsdlg.h.
Referenced by EditBreakpoint(), EnableBreakpoint(), FindBreakpoint(), OnBreakpointEdit(), OnEnable(), OnOpen(), OnProperties(), OnRemove(), OnRightClick(), Reload(), RemoveAllBreakpoints(), and RemoveBreakpoint().
m_icons
wxImageList BreakpointsDlg::m_icons private
Definition at line 85 of file breakpointsdlg.h.
m_pList
wxListCtrl* BreakpointsDlg::m_pList private
Definition at line 83 of file breakpointsdlg.h.
Referenced by OnEnable(), OnOpen(), OnProperties(), OnRemove(), OnRightClick(), and Reload().
The documentation for this class was generated from the following files:
breakpointsdlg.h
breakpointsdlg.cpp