Code::Blocks: UnfocusablePopupWindow Class Reference
UnfocusablePopupWindow Class Reference
Public Types
typedef wxPopupWindow BaseClass
Public Member Functions
UnfocusablePopupWindow (wxWindow *parent, int style=wxBORDER_NONE)
bool Destroy ()
void OnFocus (wxFocusEvent &event)
void ActivateParent ()
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
virtual bool Show (bool show=true)
Detailed Description
Definition at line 149 of file ccmanager.cpp.
Member Typedef Documentation
BaseClass
typedef wxPopupWindow UnfocusablePopupWindow::BaseClass
Definition at line 158 of file ccmanager.cpp.
Constructor & Destructor Documentation
UnfocusablePopupWindow()
UnfocusablePopupWindow::UnfocusablePopupWindow (wxWindow * parent, int style = wxBORDER_NONE) inline
Definition at line 160 of file ccmanager.cpp.
References wxDefaultPosition, wxDefaultSize, wxEmptyString, wxFRAME_FLOAT_ON_PARENT, wxFRAME_NO_TASKBAR, wxFRAME_SHAPED, wxID_ANY, wxNO_BORDER, wxPOPUP_WINDOW, and wxSIZE_AUTO.
Member Function Documentation
ActivateParent()
void UnfocusablePopupWindow::ActivateParent ()
Definition at line 214 of file ccmanager.cpp.
References wxDynamicCast, and wxGetTopLevelParent().
Destroy()
bool UnfocusablePopupWindow::Destroy ()
Definition at line 192 of file ccmanager.cpp.
References wxRect::GetHeight(), and wxRect::SetHeight().
DoSetSize()
void UnfocusablePopupWindow::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) virtual
Definition at line 224 of file ccmanager.cpp.
References NULL, and wxDefaultCoord.
OnFocus()
void UnfocusablePopupWindow::OnFocus (wxFocusEvent & event)
Definition at line 207 of file ccmanager.cpp.
Referenced by Show().
Show()
bool UnfocusablePopupWindow::Show (bool show = true) virtual
Definition at line 238 of file ccmanager.cpp.
References OnFocus().
The documentation for this class was generated from the following file:
ccmanager.cpp