Code::Blocks: GdbCmd_AddBreakpointCondition Class Reference
GdbCmd_AddBreakpointCondition Class Reference
Utility command to set a breakpoint condition.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_AddBreakpointCondition (DebuggerDriver *driver, cb::shared_ptr< DebuggerBreakpoint > bp)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
cb::shared_ptr< DebuggerBreakpoint > m_BP
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Utility command to set a breakpoint condition.
Catches errors when setting an invalid condition and responds.
(called by GdbCmd_AddBreakpoint)
Definition at line 387 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_AddBreakpointCondition()
GdbCmd_AddBreakpointCondition::GdbCmd_AddBreakpointCondition (DebuggerDriver * driver, cb::shared_ptr< DebuggerBreakpoint > bp) inline
Parameters
bp The breakpoint to set its condition.
Definition at line 392 of file gdb_commands.h.
References _T, wxString::Format(), and DebuggerCmd::m_Cmd.
Member Function Documentation
ParseOutput()
void GdbCmd_AddBreakpointCondition::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 400 of file gdb_commands.h.
References _(), _T, wxString::c_str(), cbMessageBox(), DebuggerDriver::Continue(), wxString::Format(), Manager::Get(), EditorManager::GetActiveEditor(), Manager::GetEditorManager(), DebuggerDriver::High, DebuggerCmd::m_pDriver, DebuggerDriver::QueueCommand(), DebuggerDriver::RemoveBreakpoint(), wxString::StartsWith(), wxICON_WARNING, wxID_YES, and wxYES_NO.
Member Data Documentation
m_BP
cb::shared_ptr<DebuggerBreakpoint> GdbCmd_AddBreakpointCondition::m_BP private
Definition at line 389 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h