Code::Blocks: EnvironmentSettingsDlg Class Reference
EnvironmentSettingsDlg Class Reference
#include <environmentsettingsdlg.h>
Public Member Functions
EnvironmentSettingsDlg (wxWindow *parent, wxAuiDockArt *art)
virtual ~EnvironmentSettingsDlg ()
virtual void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Member Functions
void OnPageChanging (wxListbookEvent &event)
void OnPageChanged (wxListbookEvent &event)
void OnSetAssocs (wxCommandEvent &event)
void OnManageAssocs (wxCommandEvent &event)
void OnChooseColour (wxCommandEvent &event)
void OnResetDefaultColours (wxCommandEvent &event)
void OnUseIpcCheck (wxCommandEvent &event)
void OnPlaceCheck (wxCommandEvent &event)
void OnHeadCheck (wxCommandEvent &event)
void OnAutoHide (wxCommandEvent &event)
void OnI18NCheck (wxCommandEvent &event)
void OnSettingsIconsSize (wxCommandEvent &event)
void OnDblClickMaximizes (wxCommandEvent &event)
void OnMousewheelModifier (wxKeyEvent &event)
void OnUseTabMousewheel (wxCommandEvent &event)
void OnChooseAppColourCategory (wxCommandEvent &event)
void OnChooseAppColourItem (wxCommandEvent &event)
void OnClickAppColour (wxCommandEvent &event)
Private Member Functions
void AddPluginPanels ()
void LoadListbookImages ()
void UpdateListbookImages ()
void FillApplicationColours ()
void WriteApplicationColours ()
wxString AnnoyingDlgReturnToString (const wxString &caption)
wxString StringToAnnoyingDlgReturn (const wxString &caption)
Private Attributes
wxAuiDockArt * m_pArt
ConfigurationPanelsArray m_PluginPanels
std::map< wxString, wxColour > m_ChangedAppColours
std::map< wxString, wxString > m_AnnoyingDlgReturnMap
wxImageList * m_pImageList
Detailed Description
Definition at line 16 of file environmentsettingsdlg.h.
Constructor & Destructor Documentation
EnvironmentSettingsDlg()
EnvironmentSettingsDlg::EnvironmentSettingsDlg (wxWindow * parent, wxAuiDockArt * art)
Definition at line 99 of file environmentsettingsdlg.cpp.
References _(), _T, cbDEFAULT_OPEN_FOLDER_CMD, DEFAULT_CONSOLE_SHELL, DEFAULT_CONSOLE_TERM, wxLanguageInfo::Description, ConfigManager::Exists(), F(), wxMenu::FindItem(), wxLocale::FindLanguageInfo(), wxXmlResource::Get(), Manager::Get(), Manager::GetAppFrame(), Manager::GetConfigManager(), ConfigManager::GetDataFolder(), wxDir::GetFirst(), wxMenu::GetMenuItems(), wxDir::GetNext(), wxDir::IsOpened(), wxXmlResource::LoadObject(), OnMousewheelModifier(), OnPageChanged(), OnPageChanging(), pdlHead, ConfigManager::Read(), ConfigManager::ReadBool(), ConfigManager::ReadColour(), ConfigManager::ReadInt(), ConfigManager::ReadSSet(), AnnoyingDialog::rtCANCEL, AnnoyingDialog::rtNO, AnnoyingDialog::rtOK, AnnoyingDialog::rtYES, ConfigManager::Write(), wxAUI_DOCKART_ACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_CAPTION_SIZE, wxAUI_DOCKART_INACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_PANE_BORDER_SIZE, wxAUI_DOCKART_SASH_SIZE, wxDirExists(), wxEVT_KEY_DOWN, wxNOT_FOUND, and wxT.
~EnvironmentSettingsDlg()
EnvironmentSettingsDlg::~EnvironmentSettingsDlg () virtual
Definition at line 319 of file environmentsettingsdlg.cpp.
References m_pImageList.
Member Function Documentation
AddPluginPanels()
void EnvironmentSettingsDlg::AddPluginPanels () private
Definition at line 325 of file environmentsettingsdlg.cpp.
References _T, wxImageList::Add(), wxBookCtrlBase::AddPage(), cbLoadBitmap(), cgCompiler, cgEditor, Manager::Get(), cbConfigurationPanel::GetBitmapBaseName(), PluginManager::GetConfigurationPanels(), wxImageList::GetImageCount(), wxBookCtrlBase::GetPageCount(), Manager::GetPluginManager(), cbConfigurationPanel::GetTitle(), wxString::IsEmpty(), ConfigManager::LocateDataFile(), m_pImageList, m_PluginPanels, sdDataGlobal, sdDataUser, wxBookCtrlBase::SetPageImage(), cbConfigurationPanel::SetParentDialog(), and UpdateListbookImages().
AnnoyingDlgReturnToString()
wxString EnvironmentSettingsDlg::AnnoyingDlgReturnToString (const wxString & caption) private
Definition at line 823 of file environmentsettingsdlg.cpp.
References wxString::AfterLast(), wxString::BeforeLast(), m_AnnoyingDlgReturnMap, and wxT.
EndModal()
void EnvironmentSettingsDlg::EndModal (int retCode) virtual
Definition at line 529 of file environmentsettingsdlg.cpp.
References _T, cbAuiNotebook::AllowScrolling(), wxLanguageInfo::CanonicalName, EditorManager::DeleteNotebookStack(), ScriptBindings::EndModal(), wxLocale::FindLanguageInfo(), Manager::Get(), Manager::GetColourManager(), Manager::GetConfigManager(), wxCheckListBox::GetCount(), Manager::GetEditorManager(), wxCheckListBox::GetString(), cbAuiNotebook::InvertAdvanceDirection(), cbAuiNotebook::InvertMoveDirection(), wxCheckListBox::IsChecked(), wxString::IsEmpty(), m_pArt, m_PluginPanels, cbConfigurationPanel::OnApply(), cbConfigurationPanel::OnCancel(), pdlCentre, pdlHead, ConfigManager::Read(), ConfigManager::ReadBool(), ConfigManager::ReadSSet(), EditorManager::RebuildNotebookStack(), ColourManager::Save(), wxAuiDockArt::SetColour(), wxAuiDockArt::SetMetric(), cbAuiNotebook::SetModKeys(), StringToAnnoyingDlgReturn(), cbAuiNotebook::UseModToAdvance(), ConfigManager::Write(), WriteApplicationColours(), wxAUI_DOCKART_ACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_CAPTION_SIZE, wxAUI_DOCKART_INACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_PANE_BORDER_SIZE, wxAUI_DOCKART_SASH_SIZE, wxEmptyString, and wxID_OK.
FillApplicationColours()
void EnvironmentSettingsDlg::FillApplicationColours () private
Definition at line 681 of file environmentsettingsdlg.cpp.
References _(), wxString::empty(), Manager::Get(), ColourManager::GetColourDefinitions(), Manager::GetColourManager(), wxChoice::GetCount(), wxChoice::GetSelection(), OnChooseAppColourItem(), wxEmptyString, and wxT.
Referenced by OnChooseAppColourCategory().
LoadListbookImages()
void EnvironmentSettingsDlg::LoadListbookImages () private
Definition at line 355 of file environmentsettingsdlg.cpp.
References _T, wxImageList::Add(), cbLoadBitmap(), ConfigManager::GetDataFolder(), IMAGES_COUNT, and m_pImageList.
OnAutoHide()
void EnvironmentSettingsDlg::OnAutoHide (wxCommandEvent & event) protected
Definition at line 459 of file environmentsettingsdlg.cpp.
OnChooseAppColourCategory()
void EnvironmentSettingsDlg::OnChooseAppColourCategory (wxCommandEvent & event) protected
Definition at line 719 of file environmentsettingsdlg.cpp.
References FillApplicationColours().
OnChooseAppColourItem()
void EnvironmentSettingsDlg::OnChooseAppColourItem (wxCommandEvent & event) protected
Definition at line 724 of file environmentsettingsdlg.cpp.
References Manager::Get(), wxSystemSettings::GetColour(), ColourManager::GetColourDefinitions(), Manager::GetColourManager(), m_ChangedAppColours, and wxSYS_COLOUR_BTNFACE.
Referenced by FillApplicationColours().
OnChooseColour()
void EnvironmentSettingsDlg::OnChooseColour (wxCommandEvent & event) protected
Definition at line 427 of file environmentsettingsdlg.cpp.
References wxColourData::GetColour(), wxColourDialog::GetColourData(), PlaceWindow(), wxColourData::SetColour(), wxColourDialog::ShowModal(), and wxID_OK.
OnClickAppColour()
void EnvironmentSettingsDlg::OnClickAppColour (wxCommandEvent & event) protected
Definition at line 762 of file environmentsettingsdlg.cpp.
References Manager::Get(), wxColourData::GetColour(), wxColourDialog::GetColourData(), ColourManager::GetColourDefinitions(), Manager::GetColourManager(), m_ChangedAppColours, wxColourData::SetColour(), wxColourDialog::ShowModal(), wxID_OK, and wxNOT_FOUND.
OnDblClickMaximizes()
void EnvironmentSettingsDlg::OnDblClickMaximizes (wxCommandEvent & event) protected
Definition at line 472 of file environmentsettingsdlg.cpp.
OnHeadCheck()
void EnvironmentSettingsDlg::OnHeadCheck (wxCommandEvent & event) protected
Definition at line 513 of file environmentsettingsdlg.cpp.
References pdlCentre, pdlHead, and PlaceWindow().
OnI18NCheck()
void EnvironmentSettingsDlg::OnI18NCheck (wxCommandEvent & event) protected
Definition at line 518 of file environmentsettingsdlg.cpp.
OnManageAssocs()
void EnvironmentSettingsDlg::OnManageAssocs (wxCommandEvent & event) protected
Definition at line 418 of file environmentsettingsdlg.cpp.
References PlaceWindow(), and wxDialog::ShowModal().
OnMousewheelModifier()
void EnvironmentSettingsDlg::OnMousewheelModifier (wxKeyEvent & event) protected
Definition at line 477 of file environmentsettingsdlg.cpp.
References wxString::IsEmpty(), wxGetKeyState(), WXK_ALT, WXK_COMMAND, WXK_CONTROL, WXK_SHIFT, and wxT.
Referenced by EnvironmentSettingsDlg().
OnPageChanged()
void EnvironmentSettingsDlg::OnPageChanged (wxListbookEvent & event) protected
Definition at line 402 of file environmentsettingsdlg.cpp.
References UpdateListbookImages().
Referenced by EnvironmentSettingsDlg().
OnPageChanging()
void EnvironmentSettingsDlg::OnPageChanging (wxListbookEvent & event) protected
Definition at line 398 of file environmentsettingsdlg.cpp.
Referenced by EnvironmentSettingsDlg().
OnPlaceCheck()
void EnvironmentSettingsDlg::OnPlaceCheck (wxCommandEvent & event) protected
Definition at line 508 of file environmentsettingsdlg.cpp.
OnResetDefaultColours()
void EnvironmentSettingsDlg::OnResetDefaultColours (wxCommandEvent & event) protected
Definition at line 442 of file environmentsettingsdlg.cpp.
References wxAuiDockArt::GetColour(), wxAuiDockArt::GetMetric(), wxAUI_DOCKART_ACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_ACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_CAPTION_SIZE, wxAUI_DOCKART_INACTIVE_CAPTION_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_GRADIENT_COLOUR, wxAUI_DOCKART_INACTIVE_CAPTION_TEXT_COLOUR, wxAUI_DOCKART_PANE_BORDER_SIZE, and wxAUI_DOCKART_SASH_SIZE.
OnSetAssocs()
void EnvironmentSettingsDlg::OnSetAssocs (wxCommandEvent & event) protected
Definition at line 410 of file environmentsettingsdlg.cpp.
References Associations::SetCore().
OnSettingsIconsSize()
void EnvironmentSettingsDlg::OnSettingsIconsSize (wxCommandEvent & event) protected
Definition at line 523 of file environmentsettingsdlg.cpp.
References UpdateListbookImages().
OnUseIpcCheck()
void EnvironmentSettingsDlg::OnUseIpcCheck (wxCommandEvent & event) protected
Definition at line 467 of file environmentsettingsdlg.cpp.
OnUseTabMousewheel()
void EnvironmentSettingsDlg::OnUseTabMousewheel (wxCommandEvent & event) protected
Definition at line 499 of file environmentsettingsdlg.cpp.
StringToAnnoyingDlgReturn()
wxString EnvironmentSettingsDlg::StringToAnnoyingDlgReturn (const wxString & caption) private
Definition at line 831 of file environmentsettingsdlg.cpp.
References wxString::AfterLast(), wxString::BeforeLast(), m_AnnoyingDlgReturnMap, and wxT.
Referenced by EndModal().
UpdateListbookImages()
void EnvironmentSettingsDlg::UpdateListbookImages () private
Definition at line 370 of file environmentsettingsdlg.cpp.
References _T, wxListbook::GetListView(), wxBookCtrlBase::GetPageText(), wxBookCtrlBase::GetSelection(), IMAGES_COUNT, m_pImageList, m_PluginPanels, wxBookCtrlBase::SetPageImage(), SetSettingsIconsStyle(), sisLargeIcons, and sisNoIcons.
Referenced by AddPluginPanels(), OnPageChanged(), and OnSettingsIconsSize().
WriteApplicationColours()
void EnvironmentSettingsDlg::WriteApplicationColours () private
Definition at line 801 of file environmentsettingsdlg.cpp.
References Manager::Get(), Manager::GetColourManager(), m_ChangedAppColours, and ColourManager::SetColour().
Referenced by EndModal().
Member Data Documentation
m_AnnoyingDlgReturnMap
std::map<wxString, wxString> EnvironmentSettingsDlg::m_AnnoyingDlgReturnMap private
Definition at line 55 of file environmentsettingsdlg.h.
Referenced by AnnoyingDlgReturnToString(), and StringToAnnoyingDlgReturn().
m_ChangedAppColours
std::map<wxString, wxColour> EnvironmentSettingsDlg::m_ChangedAppColours private
Definition at line 54 of file environmentsettingsdlg.h.
Referenced by OnChooseAppColourItem(), OnClickAppColour(), and WriteApplicationColours().
m_pArt
wxAuiDockArt* EnvironmentSettingsDlg::m_pArt private
Definition at line 52 of file environmentsettingsdlg.h.
Referenced by EndModal().
m_pImageList
wxImageList* EnvironmentSettingsDlg::m_pImageList private
Definition at line 56 of file environmentsettingsdlg.h.
Referenced by AddPluginPanels(), LoadListbookImages(), UpdateListbookImages(), and ~EnvironmentSettingsDlg().
m_PluginPanels
ConfigurationPanelsArray EnvironmentSettingsDlg::m_PluginPanels private
Definition at line 53 of file environmentsettingsdlg.h.
Referenced by AddPluginPanels(), EndModal(), and UpdateListbookImages().
The documentation for this class was generated from the following files:
environmentsettingsdlg.h
environmentsettingsdlg.cpp