Code::Blocks: DbgCmd_UpdateWatchesTree Class Reference
DbgCmd_UpdateWatchesTree Class Reference
Action-only debugger command to signal the watches tree to update.
#include <debugger_defs.h>
Public Member Functions
DbgCmd_UpdateWatchesTree (DebuggerDriver *driver)
virtual ~DbgCmd_UpdateWatchesTree ()
virtual void Action ()
Executes an action.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void ParseOutput (const wxString &output)
Parses the command's output.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Action-only debugger command to signal the watches tree to update.
Definition at line 115 of file debugger_defs.h.
Constructor & Destructor Documentation
DbgCmd_UpdateWatchesTree()
DbgCmd_UpdateWatchesTree::DbgCmd_UpdateWatchesTree (DebuggerDriver * driver)
Definition at line 43 of file debugger_defs.cpp.
~DbgCmd_UpdateWatchesTree()
virtual DbgCmd_UpdateWatchesTree::~DbgCmd_UpdateWatchesTree () inline virtual
Definition at line 119 of file debugger_defs.h.
Member Function Documentation
Action()
void DbgCmd_UpdateWatchesTree::Action () virtual
Executes an action.
This allows for "dummy" debugger commands to enter the commands queue. You can, for example, leave m_Cmd empty and just have Action() do something GUI-related (like the watches command does). Action() is called when the debugger command becomes current in the commands queue. It is called after sending m_Cmd to the debugger (if not empty).
Reimplemented from DebuggerCmd.
Definition at line 48 of file debugger_defs.cpp.
References Manager::Get(), Manager::GetDebuggerManager(), DebuggerManager::GetWatchesDialog(), and cbWatchesDlg::UpdateWatches().
The documentation for this class was generated from the following files:
debugger_defs.h
debugger_defs.cpp