Code::Blocks: GotoFile Class Reference
GotoFile Class Reference
#include <goto_file.h>
Public Member Functions
GotoFile (wxWindow *parent, IncrementalSelectIterator *iterator, const wxString &title, const wxString &message)
~GotoFile () override
int GetSelection ()
void AddControlBelowList (wxControl *control)
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Member Functions
void BuildContent (wxWindow *parent, IncrementalSelectIterator *iterator, const wxString &title, const wxString &message)
Private Member Functions
void FilterItems ()
Private Attributes
IncrementalSelectHandler m_handler
GotoFileListCtrl * m_ResultList
wxBoxSizer * m_sizer
wxTextCtrl * m_Text
Static Private Attributes
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_RESULT_LIST = wxNewId()
Detailed Description
Definition at line 20 of file goto_file.h.
Constructor & Destructor Documentation
GotoFile()
GotoFile::GotoFile (wxWindow * parent, IncrementalSelectIterator * iterator, const wxString & title, const wxString & message)
Definition at line 60 of file goto_file.cpp.
~GotoFile()
GotoFile::~GotoFile () override
Definition at line 102 of file goto_file.cpp.
Member Function Documentation
AddControlBelowList()
void GotoFile::AddControlBelowList (wxControl * control)
Definition at line 115 of file goto_file.cpp.
References SetMinSize(), wxALIGN_RIGHT, wxBOTTOM, wxLEFT, and wxRIGHT.
Referenced by ProjectManagerUI::OnFindFile().
BuildContent()
void GotoFile::BuildContent (wxWindow * parent, IncrementalSelectIterator * iterator, const wxString & title, const wxString & message) protected
Definition at line 69 of file goto_file.cpp.
References _(), _T, wxListCtrl::Create(), GotoFileListCtrl::GotoFileListCtrl(), wxListItem::SetId(), wxListItem::SetText(), wxListItem::SetWidth(), wxALL, wxCLOSE_BOX, wxDEFAULT_DIALOG_STYLE, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxHSCROLL, wxID_ANY, wxLC_NO_HEADER, wxLC_REPORT, wxLC_SINGLE_SEL, wxLC_VIRTUAL, wxLEFT, wxMAXIMIZE_BOX, wxRESIZE_BORDER, wxRIGHT, wxTOP, wxVERTICAL, and wxVSCROLL.
FilterItems()
void GotoFile::FilterItems () private
GetSelection()
int GotoFile::GetSelection ()
Definition at line 110 of file goto_file.cpp.
Referenced by ProjectManagerUI::OnFindFile(), and ProjectManagerUI::OnGotoFile().
Member Data Documentation
ID_RESULT_LIST
const long GotoFile::ID_RESULT_LIST = wxNewId() static private
Definition at line 44 of file goto_file.h.
ID_TEXTCTRL1
const long GotoFile::ID_TEXTCTRL1 = wxNewId() static private
Definition at line 43 of file goto_file.h.
m_handler
IncrementalSelectHandler GotoFile::m_handler private
Definition at line 33 of file goto_file.h.
m_ResultList
GotoFileListCtrl* GotoFile::m_ResultList private
Definition at line 37 of file goto_file.h.
m_sizer
wxBoxSizer* GotoFile::m_sizer private
Definition at line 38 of file goto_file.h.
m_Text
wxTextCtrl* GotoFile::m_Text private
Definition at line 39 of file goto_file.h.
The documentation for this class was generated from the following files:
goto_file.h
goto_file.cpp