Code::Blocks: cbThreadPool Class Reference
cbThreadPool Class Reference
A Thread Pool implementation.
#include <cbthreadpool.h>
Classes
struct cbThreadedTaskElement
All tasks are added to one of these. It'll also save the autodelete value.
class cbWorkerThread
A Worker Thread class.
class CountedPtr
Josuttis' implementation of CountedPtr.
Public Member Functions
cbThreadPool (wxEvtHandler *owner, int id=-1, int concurrentThreads=-1, unsigned int stackSize=0)
cbThreadPool ctor
~cbThreadPool ()
cbThreadPool dtor
void SetConcurrentThreads (int concurrentThreads)
Changes the number of threads in the pool.
int GetConcurrentThreads () const
Gets the current number of threads in the pool.
int GetId () const
return the pool ID
void AddTask (cbThreadedTask *task, bool autodelete=true)
Adds a new task to the pool.
void AbortAllTasks ()
Aborts all running and pending tasks.
bool Done () const
Tells if the pool has finished its job.
void BatchBegin ()
Begin a batch process.
void BatchEnd ()
End a batch process.
Protected Member Functions
cbThreadedTaskElement GetNextTask ()
Returns the next task to run.
void WorkingThread ()
Mechanism for the threads to tell the Pool they're running, a thread is switch from the idle mode to working mode.
bool WaitingThread ()
Mechanism for the threads to tell the Pool they're done and will go to idle, so we can assign another task to this thread.
void TaskDone (cbWorkerThread *thread)
Called by a Worker Thread to inform a single task has finished, this will send a cbEVT_THREADTASK_ENDED event.
Private Types
typedef std::vector< cbWorkerThread * > WorkerThreadsArray
typedef std::list< cbThreadedTaskElement > TasksQueue
Private Member Functions
void _SetConcurrentThreads (int concurrentThreads)
void Broadcast ()
void AwakeNeeded ()
Private Attributes
wxEvtHandler * m_pOwner
int m_ID
bool m_batching
int m_concurrentThreads
unsigned int m_stackSize
int m_concurrentThreadsSchedule
WorkerThreadsArray m_threads
TasksQueue m_tasksQueue
bool m_taskAdded
int m_workingThreads
wxMutex m_Mutex
CountedPtr< wxSemaphore > m_semaphore
Friends
class cbWorkerThread
Detailed Description
A Thread Pool implementation.
Member Typedef Documentation
typedef std::list<cbThreadedTaskElement> cbThreadPool::TasksQueue private
typedef std::vector<cbWorkerThread *> cbThreadPool::WorkerThreadsArray private
Constructor & Destructor Documentation
cbThreadPool::cbThreadPool (wxEvtHandler * owner, int id = -1, int concurrentThreads = -1, unsigned int stackSize = 0) inline
cbThreadPool ctor
Parameters
owner Event handler to receive cbEVT_THREADTASK_ENDED and cbEVT_THREADTASK_ALLDONE events
id Used with the events
concurrentThreads Number of threads in the pool. -1 means current CPU count
References SetConcurrentThreads().
cbThreadPool::~cbThreadPool ()
cbThreadPool dtor
References cbThreadPool::cbWorkerThread::Abort(), Broadcast(), cbThreadPool::cbThreadedTaskElement::Delete(), m_Mutex, m_tasksQueue, and m_threads.
Member Function Documentation
void cbThreadPool::_SetConcurrentThreads (int concurrentThreads) private
References cbThreadPool::cbWorkerThread::Abort(), Broadcast(), cbWorkerThread, m_concurrentThreads, m_concurrentThreadsSchedule, m_semaphore, m_stackSize, m_threads, and m_workingThreads.
Referenced by SetConcurrentThreads(), and WaitingThread().
void cbThreadPool::AbortAllTasks ()
Aborts all running and pending tasks.
Note
Calls cbThreadedTask::Abort for all running tasks and just removes the pending ones.
References cbThreadPool::cbWorkerThread::AbortTask(), cbThreadPool::cbThreadedTaskElement::Delete(), m_Mutex, m_tasksQueue, and m_threads.
Referenced by Parser::TerminateAllThreads().
void cbThreadPool::AddTask (cbThreadedTask * task, bool autodelete = true)
Adds a new task to the pool.
Parameters
task The task to execute
autodelete If true, the task will be deleted when it finish or be aborted
References AwakeNeeded(), m_batching, m_concurrentThreads, m_Mutex, m_taskAdded, m_tasksQueue, and m_workingThreads.
Referenced by Parser::OnAllThreadsDone(), Parser::OnBatchTimer(), and Parser::Parse().
void cbThreadPool::AwakeNeeded () inline private
References m_concurrentThreads, m_semaphore, m_tasksQueue, and m_workingThreads.
Referenced by AddTask(), and BatchEnd().
void cbThreadPool::BatchBegin () inline
Begin a batch process.
Note
EVIL: Call it if you want to add all tasks first and get none executed yet. If you DON'T call it, tasks will be executed as you add them (in fact it's what one would expect).
References m_batching, and m_Mutex.
void cbThreadPool::BatchEnd ()
End a batch process.
Note
EVIL: Call it when you have finished adding tasks and want them to execute. BEWARE: if you call BatchBegin but DON'T call BatchEnd, the tasks WON'T execute.
References AwakeNeeded(), m_batching, and m_Mutex.
void cbThreadPool::Broadcast () inline private
References m_concurrentThreads, m_semaphore, and m_workingThreads.
Referenced by _SetConcurrentThreads(), and ~cbThreadPool().
bool cbThreadPool::Done () const inline
Tells if the pool has finished its job.
Returns
true if it has nothing to do, false if it's executing tasks
References m_Mutex, and m_workingThreads.
Referenced by Parser::Done(), Parser::NotDoneReason(), and Parser::TerminateAllThreads().
int cbThreadPool::GetConcurrentThreads () const inline
Gets the current number of threads in the pool.
Returns
Number of threads in the pool
Note
If a call to SetConcurrentThreads hasn't been applied, it'll return the number of threads that will be set by it when all tasks be done.
References m_concurrentThreads, m_concurrentThreadsSchedule, and m_Mutex.
Referenced by Parser::GetMaxThreads().
int cbThreadPool::GetId () const inline
return the pool ID
Referenced by Parser::ConnectEvents(), Parser::DisconnectEvents(), and Parser::OnAllThreadsDone().
cbThreadPool::cbThreadedTaskElement cbThreadPool::GetNextTask () protected
Returns the next task to run.
Returns
Next task to run, or a NULL task (set in .task) if none
References m_Mutex, and m_tasksQueue.
void cbThreadPool::SetConcurrentThreads (int concurrentThreads)
Changes the number of threads in the pool.
Parameters
concurrentThreads New number of threads. -1 or 0 means current CPU count
Note
If tasks are running, it'll delay it until they're all done.
References _SetConcurrentThreads(), m_concurrentThreads, m_concurrentThreadsSchedule, and m_Mutex.
Referenced by cbThreadPool(), and Parser::SetMaxThreads().
void cbThreadPool::TaskDone (cbWorkerThread * thread) protected
Called by a Worker Thread to inform a single task has finished, this will send a cbEVT_THREADTASK_ENDED event.
Parameters
thread The Worker Thread
References cbEVT_THREADTASK_ENDED, m_ID, and m_pOwner.
bool cbThreadPool::WaitingThread () protected
Mechanism for the threads to tell the Pool they're done and will go to idle, so we can assign another task to this thread.
Returns
true if everything is OK, false if we should abort, this usually happens we need to set a scheduled m_concurrentThreads value.
References _SetConcurrentThreads(), cbEVT_THREADTASK_ALLDONE, m_concurrentThreadsSchedule, m_ID, m_Mutex, m_pOwner, m_semaphore, m_taskAdded, m_tasksQueue, and m_workingThreads.
void cbThreadPool::WorkingThread () protected
Mechanism for the threads to tell the Pool they're running, a thread is switch from the idle mode to working mode.
This is triggered by semaphore released somewhere
References m_Mutex, and m_workingThreads.
Friends And Related Function Documentation
friend class cbWorkerThread friend
Referenced by _SetConcurrentThreads().
Member Data Documentation
bool cbThreadPool::m_batching private
Referenced by AddTask(), BatchBegin(), and BatchEnd().
int cbThreadPool::m_concurrentThreads private
Referenced by _SetConcurrentThreads(), AddTask(), AwakeNeeded(), Broadcast(), GetConcurrentThreads(), and SetConcurrentThreads().
int cbThreadPool::m_concurrentThreadsSchedule private
Referenced by _SetConcurrentThreads(), GetConcurrentThreads(), SetConcurrentThreads(), and WaitingThread().
int cbThreadPool::m_ID private
Referenced by TaskDone(), and WaitingThread().
wxMutex cbThreadPool::m_Mutex mutable private
Referenced by AbortAllTasks(), AddTask(), BatchBegin(), BatchEnd(), Done(), GetConcurrentThreads(), GetNextTask(), SetConcurrentThreads(), WaitingThread(), WorkingThread(), and ~cbThreadPool().
wxEvtHandler* cbThreadPool::m_pOwner private
Referenced by TaskDone(), and WaitingThread().
CountedPtr<wxSemaphore> cbThreadPool::m_semaphore private
Referenced by _SetConcurrentThreads(), AwakeNeeded(), Broadcast(), cbThreadPool::cbWorkerThread::Entry(), and WaitingThread().
unsigned int cbThreadPool::m_stackSize private
Referenced by _SetConcurrentThreads().
bool cbThreadPool::m_taskAdded private
Referenced by AddTask(), and WaitingThread().
TasksQueue cbThreadPool::m_tasksQueue private
Referenced by AbortAllTasks(), AddTask(), AwakeNeeded(), GetNextTask(), WaitingThread(), and ~cbThreadPool().
WorkerThreadsArray cbThreadPool::m_threads private
Referenced by _SetConcurrentThreads(), AbortAllTasks(), and ~cbThreadPool().
int cbThreadPool::m_workingThreads private
Referenced by _SetConcurrentThreads(), AddTask(), AwakeNeeded(), Broadcast(), Done(), WaitingThread(), and WorkingThread().
The documentation for this class was generated from the following files:
cbthreadpool.h
cbthreadpool.cpp