Code::Blocks: WizFilePathPanel Class Reference
WizFilePathPanel Class Reference
#include <wizpage.h>
Public Member Functions
WizFilePathPanel (bool showHeaderGuard, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizFilePathPanel ()
wxString GetFilename () const
wxString GetHeaderGuard () const
bool GetAddToProject () const
int GetTargetIndex () const
void SetFilePathSelectionFilter (const wxString &filter)
void OnPageChanging (wxWizardEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
FilePathPanel * m_pFilePathPanel
wxString m_Filename
wxString m_HeaderGuard
bool m_AddToProject
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 79 of file wizpage.h.
Constructor & Destructor Documentation
WizFilePathPanel()
WizFilePathPanel::WizFilePathPanel (bool showHeaderGuard, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 272 of file wizpage.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), m_pFilePathPanel, ConfigManager::ReadBool(), FilePathPanel::SetAddToProject(), and FilePathPanel::ShowHeaderGuard().
~WizFilePathPanel()
WizFilePathPanel::~WizFilePathPanel ()
Definition at line 284 of file wizpage.cpp.
Member Function Documentation
GetAddToProject()
bool WizFilePathPanel::GetAddToProject () const inline
Definition at line 87 of file wizpage.h.
Referenced by Wiz::GetFileAddToProject().
GetFilename()
wxString WizFilePathPanel::GetFilename () const inline
Definition at line 85 of file wizpage.h.
Referenced by Wiz::GetFileName().
GetHeaderGuard()
wxString WizFilePathPanel::GetHeaderGuard () const inline
Definition at line 86 of file wizpage.h.
Referenced by Wiz::GetFileHeaderGuard().
GetTargetIndex()
int WizFilePathPanel::GetTargetIndex () const
Definition at line 288 of file wizpage.cpp.
References FilePathPanel::GetTargetIndex(), and m_pFilePathPanel.
Referenced by Wiz::GetFileTargetIndex().
OnPageChanging()
void WizFilePathPanel::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented from WizPageBase.
Definition at line 302 of file wizpage.cpp.
References _(), _T, cbMessageBox(), Manager::Get(), FilePathPanel::GetAddToProject(), Manager::GetConfigManager(), wxWizardEvent::GetDirection(), FilePathPanel::GetFilename(), FilePathPanel::GetHeaderGuard(), wxString::IsEmpty(), m_AddToProject, m_Filename, m_HeaderGuard, m_pFilePathPanel, WizProjectPathPanel::OnButton(), WizPageBase::OnPageChanging(), ConfigManager::Write(), wxDirExists(), wxICON_ERROR, and wxPathOnly().
SetFilePathSelectionFilter()
void WizFilePathPanel::SetFilePathSelectionFilter (const wxString & filter)
Definition at line 297 of file wizpage.cpp.
References m_pFilePathPanel, and FilePathPanel::SetFilePathSelectionFilter().
Referenced by Wiz::SetFilePathSelectionFilter().
Member Data Documentation
m_AddToProject
bool WizFilePathPanel::m_AddToProject private
Definition at line 96 of file wizpage.h.
Referenced by OnPageChanging().
m_Filename
wxString WizFilePathPanel::m_Filename private
Definition at line 94 of file wizpage.h.
Referenced by OnPageChanging().
m_HeaderGuard
wxString WizFilePathPanel::m_HeaderGuard private
Definition at line 95 of file wizpage.h.
Referenced by OnPageChanging().
m_pFilePathPanel
FilePathPanel* WizFilePathPanel::m_pFilePathPanel private
Definition at line 93 of file wizpage.h.
Referenced by GetTargetIndex(), OnPageChanging(), SetFilePathSelectionFilter(), and WizFilePathPanel().
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp