Code::Blocks: EditWatchDlg Class Reference
EditWatchDlg Class Reference
#include <editwatchdlg.h>
Public Member Functions
EditWatchDlg (cb::shared_ptr< GDBWatch > w, wxWindow *parent)
virtual ~EditWatchDlg ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Member Functions
void EndModal (int retCode)
Protected Attributes
cb::shared_ptr< GDBWatch > m_watch
Detailed Description
Definition at line 13 of file editwatchdlg.h.
Constructor & Destructor Documentation
EditWatchDlg()
EditWatchDlg::EditWatchDlg (cb::shared_ptr< GDBWatch > w, wxWindow * parent)
Definition at line 27 of file editwatchdlg.cpp.
References _T, wxXmlResource::Get(), wxXmlResource::LoadObject(), and m_watch.
~EditWatchDlg()
EditWatchDlg::~EditWatchDlg () virtual
Definition at line 48 of file editwatchdlg.cpp.
Member Function Documentation
EndModal()
void EditWatchDlg::EndModal (int retCode) protected
Definition at line 53 of file editwatchdlg.cpp.
References CleanStringValue(), ScriptBindings::EndModal(), m_watch, and wxID_OK.
Member Data Documentation
m_watch
cb::shared_ptr<GDBWatch> EditWatchDlg::m_watch protected
Definition at line 22 of file editwatchdlg.h.
Referenced by EditWatchDlg(), and EndModal().
The documentation for this class was generated from the following files:
editwatchdlg.h
editwatchdlg.cpp