Code::Blocks: wxSwitcherItems Class Reference
wxSwitcherItems Class Reference
#include <switcherdlg.h>
Public Member Functions
wxSwitcherItems ()
wxSwitcherItems (const wxSwitcherItems &items)
bool operator== (const wxSwitcherItems &items) const
void operator= (const wxSwitcherItems &items)
void Init ()
void Copy (const wxSwitcherItems &items)
wxSwitcherItem & AddItem (const wxString &title, const wxString &name, int id=0, const wxBitmap &bitmap=wxNullBitmap)
wxSwitcherItem & AddItem (const wxString &title, const wxString &name, const wxString &descr, int id=0, const wxBitmap &bitmap=wxNullBitmap)
wxSwitcherItem & AddItem (const wxSwitcherItem &item)
wxSwitcherItem & AddGroup (const wxString &title, const wxString &name, int id=0, const wxBitmap &bitmap=wxNullBitmap)
void Clear ()
int FindItemByName (const wxString &name) const
int FindItemById (int id) const
void SetSelection (int sel)
void SetSelection (const wxString &name)
int GetSelection () const
int GetIndexForFocus () const
int HitTest (const wxPoint &pt) const
const wxSwitcherItem & GetItem (int i) const
wxSwitcherItem & GetItem (int i)
int GetItemCount () const
void SetRowCount (int rows)
int GetRowCount () const
void SetColumnCount (int cols)
int GetColumnCount () const
void SetBackgroundColour (const wxColour &colour)
const wxColour & GetBackgroundColour () const
void SetTextColour (const wxColour &colour)
const wxColour & GetTextColour () const
void SetSelectionColour (const wxColour &colour)
const wxColour & GetSelectionColour () const
void SetSelectionOutlineColour (const wxColour &colour)
const wxColour & GetSelectionOutlineColour () const
void SetSelectionTextColour (const wxColour &colour)
const wxColour & GetSelectionTextColour () const
void SetItemFont (const wxFont &font)
const wxFont & GetItemFont () const
void PaintItems (wxDC &dc, wxWindow *win)
wxSize CalculateItemSize (wxDC &dc)
Protected Attributes
wxSwitcherItemArray m_items
int m_selection
int m_rowCount
int m_columnCount
wxColour m_backgroundColour
wxColour m_textColour
wxColour m_selectionColour
wxColour m_selectionOutlineColour
wxColour m_selectionTextColour
wxFont m_itemFont
Detailed Description
wxSwitcherItems An object containing switcher items
Definition at line 107 of file switcherdlg.h.
Constructor & Destructor Documentation
wxSwitcherItems() [1/2]
wxSwitcherItems::wxSwitcherItems () inline
Definition at line 111 of file switcherdlg.h.
References wxSwitcherItem::Init().
wxSwitcherItems() [2/2]
wxSwitcherItems::wxSwitcherItems (const wxSwitcherItems & items) inline
Definition at line 112 of file switcherdlg.h.
References wxSwitcherItem::Copy(), wxSwitcherItem::Init(), and wxSwitcherItem::operator==().
Member Function Documentation
AddGroup()
wxSwitcherItem & wxSwitcherItems::AddGroup (const wxString & title, const wxString & name, int id = 0, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 181 of file switcherdlg.cpp.
References wxSwitcherItem::SetIsGroup().
Referenced by MainFrame::OnSwitchTabs().
AddItem() [1/3]
wxSwitcherItem & wxSwitcherItems::AddItem (const wxString & title, const wxString & name, int id = 0, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 152 of file switcherdlg.cpp.
References wxSwitcherItem::SetBitmap(), wxSwitcherItem::SetId(), wxSwitcherItem::SetName(), and wxSwitcherItem::SetTitle().
Referenced by MainFrame::OnSwitchTabs().
AddItem() [2/3]
wxSwitcherItem & wxSwitcherItems::AddItem (const wxString & title, const wxString & name, const wxString & descr, int id = 0, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 163 of file switcherdlg.cpp.
References wxSwitcherItem::SetBitmap(), wxSwitcherItem::SetDescription(), wxSwitcherItem::SetId(), wxSwitcherItem::SetName(), and wxSwitcherItem::SetTitle().
AddItem() [3/3]
wxSwitcherItem & wxSwitcherItems::AddItem (const wxSwitcherItem & item)
Definition at line 175 of file switcherdlg.cpp.
CalculateItemSize()
wxSize wxSwitcherItems::CalculateItemSize (wxDC & dc)
Definition at line 342 of file switcherdlg.cpp.
References wxSwitcherItem::GetFont(), wxSwitcherItem::GetIsGroup(), wxSwitcherItem::GetTitle(), wxSwitcherItem::SetFont(), wxSWITCHER_TEXT_MARGIN_X, and wxSWITCHER_TEXT_MARGIN_Y.
Clear()
void wxSwitcherItems::Clear ()
Definition at line 189 of file switcherdlg.cpp.
Copy()
void wxSwitcherItems::Copy (const wxSwitcherItems & items)
Definition at line 130 of file switcherdlg.cpp.
References m_backgroundColour, m_columnCount, m_itemFont, m_items, m_rowCount, m_selection, m_selectionColour, m_selectionOutlineColour, m_selectionTextColour, wxSwitcherItem::m_textColour, and m_textColour.
FindItemById()
int wxSwitcherItems::FindItemById (int id) const
Definition at line 206 of file switcherdlg.cpp.
References wxSwitcherItem::GetId().
FindItemByName()
int wxSwitcherItems::FindItemByName (const wxString & name) const
Definition at line 194 of file switcherdlg.cpp.
References wxSwitcherItem::GetName().
GetBackgroundColour()
const wxColour& wxSwitcherItems::GetBackgroundColour () const inline
Definition at line 160 of file switcherdlg.h.
GetColumnCount()
int wxSwitcherItems::GetColumnCount () const inline
Definition at line 157 of file switcherdlg.h.
GetIndexForFocus()
int wxSwitcherItems::GetIndexForFocus () const
Definition at line 396 of file switcherdlg.cpp.
References wxSwitcherItem::GetWindow().
Referenced by MainFrame::OnSwitchTabs().
GetItem() [1/2]
const wxSwitcherItem & wxSwitcherItems::GetItem (int i) const
Definition at line 230 of file switcherdlg.cpp.
Referenced by MainFrame::OnSwitchTabs().
GetItem() [2/2]
wxSwitcherItem & wxSwitcherItems::GetItem (int i)
Definition at line 235 of file switcherdlg.cpp.
GetItemCount()
int wxSwitcherItems::GetItemCount () const inline
Definition at line 151 of file switcherdlg.h.
Referenced by MainFrame::OnSwitchTabs().
GetItemFont()
const wxFont& wxSwitcherItems::GetItemFont () const inline
Definition at line 175 of file switcherdlg.h.
GetRowCount()
int wxSwitcherItems::GetRowCount () const inline
Definition at line 154 of file switcherdlg.h.
GetSelection()
int wxSwitcherItems::GetSelection () const inline
Definition at line 140 of file switcherdlg.h.
GetSelectionColour()
const wxColour& wxSwitcherItems::GetSelectionColour () const inline
Definition at line 166 of file switcherdlg.h.
GetSelectionOutlineColour()
const wxColour& wxSwitcherItems::GetSelectionOutlineColour () const inline
Definition at line 169 of file switcherdlg.h.
GetSelectionTextColour()
const wxColour& wxSwitcherItems::GetSelectionTextColour () const inline
Definition at line 172 of file switcherdlg.h.
GetTextColour()
const wxColour& wxSwitcherItems::GetTextColour () const inline
Definition at line 163 of file switcherdlg.h.
References wxSwitcherItem::m_textColour.
HitTest()
int wxSwitcherItems::HitTest (const wxPoint & pt) const
Definition at line 412 of file switcherdlg.cpp.
References wxSwitcherItem::GetIsGroup(), wxSwitcherItem::GetRect(), wxMultiColumnListCtrl::OnChar(), wxMultiColumnListCtrl::OnEraseBackground(), wxMultiColumnListCtrl::OnKey(), wxMultiColumnListCtrl::OnMouseEvent(), and wxMultiColumnListCtrl::OnPaint().
Init()
void wxSwitcherItems::Init ()
Definition at line 112 of file switcherdlg.cpp.
operator=()
void wxSwitcherItems::operator= (const wxSwitcherItems & items) inline
Definition at line 120 of file switcherdlg.h.
References wxSwitcherItem::Copy(), and wxSwitcherItem::Init().
operator==()
bool wxSwitcherItems::operator== (const wxSwitcherItems & items) const
wxSwitcherItems An object containing switcher items
Definition at line 89 of file switcherdlg.cpp.
References wxSwitcherItem::m_textColour.
PaintItems()
void wxSwitcherItems::PaintItems (wxDC & dc, wxWindow * win)
Definition at line 240 of file switcherdlg.cpp.
References wxSwitcherItem::GetBitmap(), wxSwitcherItem::GetFont(), wxSwitcherItem::GetIsGroup(), wxSwitcherItem::GetRect(), wxSwitcherItem::GetTextColour(), wxSwitcherItem::GetTitle(), wxSwitcherItem::SetFont(), and wxSWITCHER_TEXT_MARGIN_X.
SetBackgroundColour()
void wxSwitcherItems::SetBackgroundColour (const wxColour & colour) inline
Definition at line 159 of file switcherdlg.h.
SetColumnCount()
void wxSwitcherItems::SetColumnCount (int cols) inline
Definition at line 156 of file switcherdlg.h.
SetItemFont()
void wxSwitcherItems::SetItemFont (const wxFont & font) inline
Definition at line 174 of file switcherdlg.h.
SetRowCount()
void wxSwitcherItems::SetRowCount (int rows) inline
Definition at line 153 of file switcherdlg.h.
SetSelection() [1/2]
void wxSwitcherItems::SetSelection (int sel)
Definition at line 218 of file switcherdlg.cpp.
Referenced by MainFrame::OnSwitchTabs().
SetSelection() [2/2]
void wxSwitcherItems::SetSelection (const wxString & name)
Definition at line 223 of file switcherdlg.cpp.
SetSelectionColour()
void wxSwitcherItems::SetSelectionColour (const wxColour & colour) inline
Definition at line 165 of file switcherdlg.h.
SetSelectionOutlineColour()
void wxSwitcherItems::SetSelectionOutlineColour (const wxColour & colour) inline
Definition at line 168 of file switcherdlg.h.
SetSelectionTextColour()
void wxSwitcherItems::SetSelectionTextColour (const wxColour & colour) inline
Definition at line 171 of file switcherdlg.h.
SetTextColour()
void wxSwitcherItems::SetTextColour (const wxColour & colour) inline
Definition at line 162 of file switcherdlg.h.
References wxSwitcherItem::m_textColour.
Member Data Documentation
m_backgroundColour
wxColour wxSwitcherItems::m_backgroundColour protected
Definition at line 189 of file switcherdlg.h.
Referenced by Copy().
m_columnCount
int wxSwitcherItems::m_columnCount protected
Definition at line 187 of file switcherdlg.h.
Referenced by Copy().
m_itemFont
wxFont wxSwitcherItems::m_itemFont protected
Definition at line 195 of file switcherdlg.h.
Referenced by Copy().
m_items
wxSwitcherItemArray wxSwitcherItems::m_items protected
Definition at line 184 of file switcherdlg.h.
Referenced by Copy().
m_rowCount
int wxSwitcherItems::m_rowCount protected
Definition at line 186 of file switcherdlg.h.
Referenced by Copy().
m_selection
int wxSwitcherItems::m_selection protected
Definition at line 185 of file switcherdlg.h.
Referenced by Copy().
m_selectionColour
wxColour wxSwitcherItems::m_selectionColour protected
Definition at line 191 of file switcherdlg.h.
Referenced by Copy().
m_selectionOutlineColour
wxColour wxSwitcherItems::m_selectionOutlineColour protected
Definition at line 192 of file switcherdlg.h.
Referenced by Copy().
m_selectionTextColour
wxColour wxSwitcherItems::m_selectionTextColour protected
Definition at line 193 of file switcherdlg.h.
Referenced by Copy().
m_textColour
wxColour wxSwitcherItems::m_textColour protected
Definition at line 190 of file switcherdlg.h.
Referenced by Copy().
The documentation for this class was generated from the following files:
switcherdlg.h
switcherdlg.cpp