Code::Blocks: SelectIncludeFile Class Reference
SelectIncludeFile Class Reference
#include <selectincludefile.h>
Public Member Functions
SelectIncludeFile (wxWindow *parent, wxWindowID id=-1)
virtual ~SelectIncludeFile ()
void AddListEntries (const wxArrayString &IncludeFile)
wxString GetIncludeFile () const
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void OnOk (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
Private Attributes
wxListBox * LstIncludeFiles
wxString m_SelectedIncludeFile
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 21 of file selectincludefile.h.
Constructor & Destructor Documentation
SelectIncludeFile()
SelectIncludeFile::SelectIncludeFile (wxWindow * parent, wxWindowID id = -1)
Definition at line 22 of file selectincludefile.cpp.
~SelectIncludeFile()
SelectIncludeFile::~SelectIncludeFile () virtual
Definition at line 28 of file selectincludefile.cpp.
Member Function Documentation
AddListEntries()
void SelectIncludeFile::AddListEntries (const wxArrayString & IncludeFile)
Definition at line 48 of file selectincludefile.cpp.
References LstIncludeFiles.
Referenced by CodeCompletion::OnOpenIncludeFile().
GetIncludeFile()
wxString SelectIncludeFile::GetIncludeFile () const inline
Definition at line 28 of file selectincludefile.h.
References m_SelectedIncludeFile, OnCancel(), and OnOk().
Referenced by CodeCompletion::OnOpenIncludeFile().
OnCancel()
void SelectIncludeFile::OnCancel (wxCommandEvent & event) private
Definition at line 43 of file selectincludefile.cpp.
References ScriptBindings::EndModal().
Referenced by GetIncludeFile().
OnOk()
void SelectIncludeFile::OnOk (wxCommandEvent & event) private
Definition at line 32 of file selectincludefile.cpp.
References ScriptBindings::EndModal(), LstIncludeFiles, and m_SelectedIncludeFile.
Referenced by GetIncludeFile().
Member Data Documentation
LstIncludeFiles
wxListBox* SelectIncludeFile::LstIncludeFiles private
Definition at line 34 of file selectincludefile.h.
Referenced by AddListEntries(), and OnOk().
m_SelectedIncludeFile
wxString SelectIncludeFile::m_SelectedIncludeFile private
Definition at line 36 of file selectincludefile.h.
Referenced by GetIncludeFile(), and OnOk().
The documentation for this class was generated from the following files:
selectincludefile.h
selectincludefile.cpp