Code::Blocks: ProjectFile Class Reference
ProjectFile Class Reference
Represents a file in a Code::Blocks project.
#include <projectfile.h>
Public Member Functions
ProjectFile (cbProject *prj)
Constructor.
~ProjectFile ()
Destructor.
void Rename (const wxString &new_name)
Change filename of the file.
void AddBuildTarget (const wxString &targetName)
Make this file belong to an additional build target.
void RenameBuildTarget (const wxString &oldTargetName, const wxString &newTargetName)
Rename a build target this file belongs in.
void RemoveBuildTarget (const wxString &targetName)
Remove this file from the specified build target.
const wxArrayString & GetBuildTargets () const
bool ShowOptions (wxWindow *parent)
Show the file properties dialog.
wxString GetBaseName () const
const wxString & GetObjName ()
void SetObjName (const wxString &name)
Set the generated object filename.
cbProject * GetParentProject ()
void UpdateFileDetails (ProjectBuildTarget *target=nullptr)
This is called automatically when adding/removing build targets.
const pfDetails & GetFileDetails (ProjectBuildTarget *target)
Access the file details for this project file for the specified target.
void SetFileState (FileVisualState state)
Set the visual state (modified, read-only, etc).
FileVisualState GetFileState () const
void SetUseCustomBuildCommand (const wxString &compilerId, bool useCustomBuildCommand)
Modify 'Use custom command to build this file' for a compilerId.
void SetCustomBuildCommand (const wxString &compilerId, const wxString &newBuildCommand)
Modify customBuild command for a compilerId.
bool GetUseCustomBuildCommand (const wxString &compilerId)
Read 'Use custom command to build this file' for a compilerId.
wxString GetCustomBuildCommand (const wxString &compilerId)
Read customBuild command for a compilerId.
ProjectFile * AutoGeneratedBy () const
If this is an auto-generated file, which file is generating it?
void SetAutoGeneratedBy (ProjectFile *TheFile)
If this is an auto-generated file, set the file which is generating it?
const wxTreeItemId & GetTreeItemId () const
Returns the wxTreeItemId for the file.
void SetTreeItemId (wxTreeItemId id)
Sets the tree item id for the file.
Static Public Member Functions
static int CompareProjectFiles (ProjectFile *item1, ProjectFile *item2)
Compare relative names of projectfiles.
Public Attributes
wxFileName file
The full filename of this file.
wxString relativeFilename
The relative (to the project) filename of this file.
wxString relativeToCommonTopLevelPath
The relative filename to the common top-level path.
bool compile
Compile flag.
bool link
Link flag.
unsigned short int weight
The weight.
bool editorOpen
If true, the file is open inside an editor.
int editorSplit
Split type of the editor as int.
int editorSplitActive
Last active splitview (1 or 2).
int editorSplitPos
Last splitter position.
int editorPos
The last known caret position in an editor for this file (left/top control if split).
int editorTopLine
The last known caret line in an editor for this file (left/top control if split).
int editorZoom
The zoom-factor of the editor for this file (left/top control if split).
int editorPos_2
The last known caret position in an editor for this file (right/bottom control if split).
int editorTopLine_2
The last known caret line in an editor for this file(right/bottom control if split).
int editorZoom_2
The zoom-factor of the editor for this file(right/bottom control if split).
int editorTabPos
The position of the editor-tab for this file.
wxArrayInt editorFoldLinesArray
Fold lines.
pfCustomBuildMap customBuild
A map for custom builds.
wxString compilerVar
The compiler variable used for this file (e.g CPP, CC, etc).
wxArrayString buildTargets
An array of strings, containing the names of all the build targets this file belongs to.
wxString virtual_path
A string that represents the virtual folder this file will appear in.
ProjectFile * autoGeneratedBy
If this is an auto-generated file, which file is generating it?
ProjectFilesVector generatedFiles
Auto-generated files when compiling this file.
Protected Member Functions
void DoUpdateFileDetails (ProjectBuildTarget *target)
Protected Attributes
cbProject * project
FileVisualState m_VisualState
wxTreeItemId m_TreeItemId
wxString m_ObjName
PFDMap m_PFDMap
Friends
class cbProject
Detailed Description
Represents a file in a Code::Blocks project.
Definition at line 39 of file projectfile.h.
Constructor & Destructor Documentation
ProjectFile()
ProjectFile::ProjectFile (cbProject * prj)
Constructor.
Definition at line 26 of file projectfile.cpp.
~ProjectFile()
ProjectFile::~ProjectFile ()
Destructor.
Definition at line 47 of file projectfile.cpp.
References m_PFDMap.
Member Function Documentation
AddBuildTarget()
void ProjectFile::AddBuildTarget (const wxString & targetName)
Make this file belong to an additional build target.
Parameters
targetName The build target to add this file to.
Definition at line 78 of file projectfile.cpp.
References buildTargets, generatedFiles, cbProject::GetBuildTarget(), ProjectBuildTarget::m_FileArray, ProjectBuildTarget::m_Files, and project.
Referenced by cbProject::AddFile(), ProjectManager::DoAddFileToProject(), ProjectOptionsDlg::DoBeforeTargetChange(), ProjectLoader::DoUnitOptions(), cbProject::DuplicateBuildTarget(), ProjectFileOptionsDlg::EndModal(), ProjectOptionsDlg::OnFileMarkOnClick(), ProjectOptionsDlg::OnFileToggleMarkClick(), ScriptBindings::RegisterBindings(), and Wiz::RunTargetWizard().
AutoGeneratedBy()
ProjectFile* ProjectFile::AutoGeneratedBy () const inline
If this is an auto-generated file, which file is generating it?
Definition at line 201 of file projectfile.h.
Referenced by ProjectManagerUI::BuildProjectTree(), ProjectLoader::ExportTargetAsProject(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetCompileCommands(), ProjectManagerUI::OnRenameFile(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), cbProject::RemoveFile(), ProjectManager::RemoveFileFromProject(), and EditorManager::SwapActiveHeaderSource().
CompareProjectFiles()
int ProjectFile::CompareProjectFiles (ProjectFile * item1, ProjectFile * item2) static
Compare relative names of projectfiles.
Static helper function to sort array of projectfiles. Needed because the order of files in a hashset is not guaranteed.
Parameters
item1 first projectfile.
item2 second projectfile.
Returns
A negative value, 0, or positive value if the relative filename of item1 is less than, equal to or greater than the one of item2.
Definition at line 334 of file projectfile.cpp.
References relativeFilename.
Referenced by ProjectLoader::ExportTargetAsProject().
DoUpdateFileDetails()
void ProjectFile::DoUpdateFileDetails (ProjectBuildTarget * target) protected
Definition at line 268 of file projectfile.cpp.
References buildTargets, CompileTargetBase::GetTitle(), m_PFDMap, and pfDetails::Update().
Referenced by GetFileDetails(), and UpdateFileDetails().
GetBaseName()
wxString ProjectFile::GetBaseName () const
Returns
The relative (to the project) filename without extension.
Definition at line 153 of file projectfile.cpp.
References relativeFilename.
Referenced by ScriptBindings::RegisterBindings().
GetBuildTargets()
const wxArrayString & ProjectFile::GetBuildTargets () const
Returns
An array of strings, containing the names of all the build targets this file belongs to.
Definition at line 141 of file projectfile.cpp.
References buildTargets.
Referenced by DirectCommands::CompileFile(), and ScriptBindings::RegisterBindings().
GetCustomBuildCommand()
wxString ProjectFile::GetCustomBuildCommand (const wxString & compilerId)
Read customBuild command for a compilerId.
Definition at line 329 of file projectfile.cpp.
References customBuild.
Referenced by ScriptBindings::RegisterBindings().
GetFileDetails()
const pfDetails & ProjectFile::GetFileDetails (ProjectBuildTarget * target)
Access the file details for this project file for the specified target.
Parameters
target A pointer to the build target whose file details should be updated.
Returns
The details for this project file for the specified build target.
Definition at line 284 of file projectfile.cpp.
References DoUpdateFileDetails(), and m_PFDMap.
Referenced by DirectCommands::CompileFile(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetCompileCommands(), and DirectCommands::GetTargetLinkCommands().
GetFileState()
FileVisualState ProjectFile::GetFileState () const
Returns
The visual state (modified, read-only, etc).
Definition at line 295 of file projectfile.cpp.
References m_VisualState.
Referenced by ProjectManagerUI::BuildProjectTree(), EditorManager::CheckForExternallyModifiedFiles(), and ProjectManagerUI::ShowMenu().
GetObjName()
const wxString & ProjectFile::GetObjName ()
Returns
The generated object filename.
Definition at line 160 of file projectfile.cpp.
References generatedFiles, m_ObjName, relativeToCommonTopLevelPath, and SetObjName().
Referenced by CompilerGCC::OnCleanFile(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), ScriptBindings::RegisterBindings(), cbProject::SetCompilerID(), CompilerMINGWGenerator::SetupIncludeDirs(), and pfDetails::Update().
GetParentProject()
cbProject* ProjectFile::GetParentProject () inline
Returns
The parent project.
Definition at line 93 of file projectfile.h.
References pfCustomBuild::useCustomBuildCommand.
Referenced by EditorManager::CheckForExternallyModifiedFiles(), MainFrame::DoUpdateAppTitle(), ProjectFileOptionsDlg::EndModal(), ProjectFileOptionsDlg::FillCompilers(), MainFrame::GetEditorDescription(), NativeParser::GetProjectByEditor(), cbEditor::NotifyPlugins(), cbEditor::OnContextMenuEntry(), ProjectManagerUI::OnFileOptions(), EditorManager::OnRemoveFileFromProject(), ProjectFileRelativePathCmp::operator()(), CompilerGCC::PrepareCompileFile(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), ScriptBindings::RegisterBindings(), ProjectManager::RemoveFileFromProject(), EditorManager::SwapActiveHeaderSource(), pfDetails::Update(), and EditorManager::UpdateProjectFiles().
GetTreeItemId()
const wxTreeItemId& ProjectFile::GetTreeItemId () const inline
Returns the wxTreeItemId for the file.
Definition at line 210 of file projectfile.h.
Referenced by ProjectManagerUI::ShowFileInTree().
GetUseCustomBuildCommand()
bool ProjectFile::GetUseCustomBuildCommand (const wxString & compilerId)
Read 'Use custom command to build this file' for a compilerId.
Definition at line 324 of file projectfile.cpp.
References customBuild.
Referenced by ScriptBindings::RegisterBindings().
RemoveBuildTarget()
void ProjectFile::RemoveBuildTarget (const wxString & targetName)
Remove this file from the specified build target.
Parameters
targetName The build target's name to remove this file from.
Definition at line 113 of file projectfile.cpp.
References buildTargets, generatedFiles, cbProject::GetBuildTarget(), ProjectBuildTarget::m_FileArray, ProjectBuildTarget::m_Files, and project.
Referenced by ProjectOptionsDlg::DoBeforeTargetChange(), ProjectFileOptionsDlg::EndModal(), ProjectOptionsDlg::OnFileMarkOffClick(), ProjectOptionsDlg::OnFileToggleMarkClick(), ScriptBindings::RegisterBindings(), and cbProject::RemoveBuildTarget().
Rename()
void ProjectFile::Rename (const wxString & new_name)
Change filename of the file.
Note that this does only update the internal variables. It does NOT rename the file on disk... It updates file, relativeFilename, relativeToCommonTopLevelPath and finally marks the parent project as modified.
Note
This allows renaming only the LAST part of the filename (the name and extension)
Definition at line 57 of file projectfile.cpp.
References cbProject::CalculateCommonTopLevelPath(), file, project, cbProject::ProjectFileRenamed(), relativeFilename, cbProject::SetModified(), and UpdateFileDetails().
RenameBuildTarget()
void ProjectFile::RenameBuildTarget (const wxString & oldTargetName, const wxString & newTargetName)
Rename a build target this file belongs in.
Parameters
oldTargetName The build target's old name.
newTargetName The build target's new name.
Note
This does not change the build target's name, just the reference in the project file. This is actually used by cbProject::RenameBuildTarget().
Definition at line 102 of file projectfile.cpp.
References buildTargets, and generatedFiles.
Referenced by ScriptBindings::RegisterBindings(), and cbProject::RenameBuildTarget().
SetAutoGeneratedBy()
void ProjectFile::SetAutoGeneratedBy (ProjectFile * TheFile) inline
If this is an auto-generated file, set the file which is generating it?
Definition at line 204 of file projectfile.h.
Referenced by cbProject::AddFile().
SetCustomBuildCommand()
void ProjectFile::SetCustomBuildCommand (const wxString & compilerId, const wxString & newBuildCommand)
Modify customBuild command for a compilerId.
Definition at line 319 of file projectfile.cpp.
References customBuild.
Referenced by ProjectLoader::DoUnitOptions(), and ScriptBindings::RegisterBindings().
SetFileState()
void ProjectFile::SetFileState (FileVisualState state)
Set the visual state (modified, read-only, etc).
Parameters
state The new visual state.
Definition at line 300 of file projectfile.cpp.
References Manager::Get(), Manager::GetProjectManager(), cbProjectManagerUI::GetTree(), ProjectManager::GetUI(), m_TreeItemId, and m_VisualState.
Referenced by cbProject::AddFile(), EditorManager::CheckForExternallyModifiedFiles(), ProjectManagerUI::DoOpenFile(), cbEditor::Open(), cbEditor::SetModified(), and cbEditor::SetProjectFile().
SetObjName()
void ProjectFile::SetObjName (const wxString & name)
Set the generated object filename.
Parameters
name The filename for the generated object.
Definition at line 174 of file projectfile.cpp.
References FileTypeOf(), ftHeader, ftResource, ftResourceBin, CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), cbProject::GetExtendedObjectNamesGeneration(), cbProject::GetModeForPCH(), Compiler::GetSwitches(), m_ObjName, CompilerSwitches::objectExtension, CompilerSwitches::PCHExtension, pchSourceFile, project, relativeFilename, FileFilters::RESOURCEBIN_DOT_EXT, FileFilters::RESOURCEBIN_EXT, Compiler::SetName(), and CompilerSwitches::supportsPCH.
Referenced by cbProject::CalculateCommonTopLevelPath(), GetObjName(), ScriptBindings::RegisterBindings(), cbProject::SetCompilerID(), cbProject::SetExtendedObjectNamesGeneration(), and UpdateFileDetails().
SetTreeItemId()
void ProjectFile::SetTreeItemId (wxTreeItemId id) inline
Sets the tree item id for the file.
Should not be called by users!
Definition at line 213 of file projectfile.h.
Referenced by ProjectManagerUI::BuildProjectTree().
SetUseCustomBuildCommand()
void ProjectFile::SetUseCustomBuildCommand (const wxString & compilerId, bool useCustomBuildCommand)
Modify 'Use custom command to build this file' for a compilerId.
Definition at line 314 of file projectfile.cpp.
References customBuild.
Referenced by ProjectLoader::DoUnitOptions(), and ScriptBindings::RegisterBindings().
ShowOptions()
bool ProjectFile::ShowOptions (wxWindow * parent)
Show the file properties dialog.
Parameters
parent The parent window for the dialog (can be NULL).
Returns
True if the user closed the dialog with "OK", false if closed it with "Cancel".
Definition at line 146 of file projectfile.cpp.
References PlaceWindow(), and wxScrollingDialog::ShowModal().
Referenced by cbEditor::OnContextMenuEntry(), ProjectOptionsDlg::OnFileOptionsClick(), and EditorManager::OnProperties().
UpdateFileDetails()
void ProjectFile::UpdateFileDetails (ProjectBuildTarget * target = nullptr)
This is called automatically when adding/removing build targets.
Parameters
target A pointer to the build target whose file details should be updated.
Definition at line 243 of file projectfile.cpp.
References compile, DoUpdateFileDetails(), FileTypeOf(), ftHeader, cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), link, project, relativeFilename, relativeToCommonTopLevelPath, and SetObjName().
Referenced by Rename(), and cbProject::SetExtendedObjectNamesGeneration().
Friends And Related Function Documentation
cbProject
friend class cbProject friend
Definition at line 224 of file projectfile.h.
Member Data Documentation
autoGeneratedBy
ProjectFile* ProjectFile::autoGeneratedBy
If this is an auto-generated file, which file is generating it?
Definition at line 198 of file projectfile.h.
buildTargets
wxArrayString ProjectFile::buildTargets
An array of strings, containing the names of all the build targets this file belongs to.
Definition at line 190 of file projectfile.h.
Referenced by AddBuildTarget(), CodeCompletion::DoCodeCompleteIncludes(), ProjectOptionsDlg::DoTargetChange(), DoUpdateFileDetails(), ProjectLoader::ExportTargetAsProject(), FindReplace::FindInFiles(), CompilerGCC::GetBuildTargetForFile(), GetBuildTargets(), DirectCommands::GetProjectFilesSortedByWeight(), CompilerGCC::OnCompileFileRequest(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), ScriptBindings::RegisterBindings(), RemoveBuildTarget(), RenameBuildTarget(), and FindReplace::ReplaceInFiles().
compile
bool ProjectFile::compile
Compile flag.
If it's true, the file is compiled (generates object file) else it is not.
Definition at line 138 of file projectfile.h.
Referenced by cbProject::AddFile(), ProjectManagerUI::BuildProjectTree(), DirectCommands::CompileFile(), ProjectLoader::DoUnitOptions(), ProjectFileOptionsDlg::EndModal(), ProjectLoader::ExportTargetAsProject(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetProjectFilesSortedByWeight(), ProjectManagerUI::OnFileOptions(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), ScriptBindings::RegisterBindings(), CompilerMINGWGenerator::SetupIncludeDirs(), and UpdateFileDetails().
compilerVar
wxString ProjectFile::compilerVar
The compiler variable used for this file (e.g CPP, CC, etc).
Definition at line 187 of file projectfile.h.
Referenced by cbProject::AddFile(), DirectCommands::CompileFile(), ProjectLoader::DoUnitOptions(), ProjectFileOptionsDlg::EndModal(), ProjectLoader::ExportTargetAsProject(), CompilerCommandGenerator::GenerateCommandLine(), DirectCommands::GetCompileFileCommand(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), and ScriptBindings::RegisterBindings().
customBuild
pfCustomBuildMap ProjectFile::customBuild
A map for custom builds.
Key is compiler ID, value is pfCustomBuild struct.
Definition at line 184 of file projectfile.h.
Referenced by ProjectLoader::ExportTargetAsProject(), DirectCommands::GetCompileFileCommand(), GetCustomBuildCommand(), GetUseCustomBuildCommand(), ProjectFileOptionsDlg::SaveBuildCommandSelection(), SetCustomBuildCommand(), SetUseCustomBuildCommand(), and ProjectFileOptionsDlg::UpdateBuildCommand().
editorFoldLinesArray
wxArrayInt ProjectFile::editorFoldLinesArray
Fold lines.
Definition at line 181 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorOpen
bool ProjectFile::editorOpen
If true, the file is open inside an editor.
Definition at line 148 of file projectfile.h.
Referenced by cbProject::LoadLayout(), ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), cbEditor::UpdateProjectFile(), and cbEditor::~cbEditor().
editorPos
int ProjectFile::editorPos
The last known caret position in an editor for this file (left/top control if split).
Definition at line 160 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorPos_2
int ProjectFile::editorPos_2
The last known caret position in an editor for this file (right/bottom control if split).
Definition at line 169 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorSplit
int ProjectFile::editorSplit
Split type of the editor as int.
Definition at line 151 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorSplitActive
int ProjectFile::editorSplitActive
Last active splitview (1 or 2).
Definition at line 154 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), and cbEditor::UpdateProjectFile().
editorSplitPos
int ProjectFile::editorSplitPos
Last splitter position.
Definition at line 157 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorTabPos
int ProjectFile::editorTabPos
The position of the editor-tab for this file.
Definition at line 178 of file projectfile.h.
Referenced by cbProject::LoadLayout(), ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), and EditorManager::UpdateProjectFiles().
editorTopLine
int ProjectFile::editorTopLine
The last known caret line in an editor for this file (left/top control if split).
Definition at line 163 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorTopLine_2
int ProjectFile::editorTopLine_2
The last known caret line in an editor for this file(right/bottom control if split).
Definition at line 172 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorZoom
int ProjectFile::editorZoom
The zoom-factor of the editor for this file (left/top control if split).
Definition at line 166 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
editorZoom_2
int ProjectFile::editorZoom_2
The zoom-factor of the editor for this file(right/bottom control if split).
Definition at line 175 of file projectfile.h.
Referenced by ProjectLayoutLoader::Open(), ProjectLayoutLoader::Save(), cbEditor::SetProjectFile(), and cbEditor::UpdateProjectFile().
file
wxFileName ProjectFile::file
The full filename of this file.
Usually you need to read from it and never write to it.
Note
Use Rename() if you want to change this or else bad things will happen
Definition at line 126 of file projectfile.h.
Referenced by cbProject::AddFile(), NativeParser::AddProjectToParser(), ProjectManagerUI::BuildProjectTree(), cbProject::CalculateCommonTopLevelPath(), cbProject::CloseAllFiles(), CodeCompletion::DoCodeCompleteIncludes(), NativeParser::DoFullParsing(), CompilerErrors::DoGotoError(), MarkFileAsLocalThreadedTask::Execute(), cbTreeCtrl::filesSort(), cbTreeCtrl::filesSortNameOnly(), FindReplace::FindInFiles(), CodeRefactoring::GetAllProjectFiles(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetTargetCleanCommands(), ClassBrowserBuilderThread::Init(), cbProject::LoadLayout(), CodeCompletion::OnOpenIncludeFile(), ProjectManagerUI::OnRenameFile(), CodeCompletion::OnSelectedFileReparse(), EditorManager::Open(), ProjectFileAbsolutePathCmp::operator()(), ProjectFileAbsolutePathEqual::operator()(), CompilerGCC::PrepareCompileFilePM(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), cbProject::ProjectFileRenamed(), cbProject::QueryCloseAllFiles(), ScriptBindings::RegisterBindings(), cbProject::RemoveFile(), ProjectManager::RemoveFileFromProject(), NativeParser::RemoveProjectFromParser(), Rename(), FindReplace::ReplaceInFiles(), cbProject::SaveAllFiles(), cbEditor::SetEditorStyleBeforeFileOpen(), cbEditor::SetProjectFile(), ProjectManagerUI::ShowMenu(), EditorManager::SwapActiveHeaderSource(), and pfDetails::Update().
generatedFiles
ProjectFilesVector ProjectFile::generatedFiles
Auto-generated files when compiling this file.
Definition at line 207 of file projectfile.h.
Referenced by AddBuildTarget(), cbProject::AddFile(), ProjectLoader::DoUnitOptions(), DirectCommands::GetCompileFileCommand(), GetObjName(), RemoveBuildTarget(), cbProject::RemoveFile(), RenameBuildTarget(), EditorManager::SwapActiveHeaderSource(), and pfDetails::Update().
link
bool ProjectFile::link
Link flag.
If it's true, the (generated object) file is linked else it is not.
Definition at line 141 of file projectfile.h.
Referenced by cbProject::AddFile(), ProjectLoader::DoUnitOptions(), ProjectFileOptionsDlg::EndModal(), ProjectLoader::ExportTargetAsProject(), DirectCommands::GetProjectFilesSortedByWeight(), ProjectManagerUI::OnFileOptions(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), ScriptBindings::RegisterBindings(), and UpdateFileDetails().
m_ObjName
wxString ProjectFile::m_ObjName protected
Definition at line 230 of file projectfile.h.
Referenced by GetObjName(), and SetObjName().
m_PFDMap
PFDMap ProjectFile::m_PFDMap protected
Definition at line 231 of file projectfile.h.
Referenced by DoUpdateFileDetails(), GetFileDetails(), and ~ProjectFile().
m_TreeItemId
wxTreeItemId ProjectFile::m_TreeItemId protected
Definition at line 229 of file projectfile.h.
Referenced by SetFileState().
m_VisualState
FileVisualState ProjectFile::m_VisualState protected
Definition at line 228 of file projectfile.h.
Referenced by GetFileState(), and SetFileState().
project
cbProject* ProjectFile::project protected
Definition at line 227 of file projectfile.h.
Referenced by AddBuildTarget(), RemoveBuildTarget(), Rename(), SetObjName(), cbEditor::SetProjectFile(), and UpdateFileDetails().
relativeFilename
wxString ProjectFile::relativeFilename
The relative (to the project) filename of this file.
Usually you need to read from it and never write to it.
Note
Use Rename() if you want to change this or else bad things will happen
Definition at line 131 of file projectfile.h.
Referenced by cbProject::AddFile(), NativeParser::AddProjectToParser(), CompilerGCC::BuildModuleMenu(), cbProject::CalculateCommonTopLevelPath(), CompareProjectFiles(), CodeCompletion::DoCodeCompleteIncludes(), NativeParser::DoFullParsing(), MarkFileAsLocalThreadedTask::Execute(), ProjectLoader::ExportTargetAsProject(), CodeRefactoring::GetAllProjectFiles(), GetBaseName(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetTargetLinkCommands(), ProjectManagerUI::OnAddFileToProject(), ProjectFileRelativePathCmp::operator()(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), ScriptBindings::RegisterBindings(), cbProject::RemoveFile(), NativeParser::RemoveProjectFromParser(), Rename(), ProjectLayoutLoader::Save(), cbProject::SetCompilerID(), SetObjName(), cbEditor::SetProjectFile(), CompilerMINGWGenerator::SetupIncludeDirs(), cbAuiNotebook::UniqueIdFromTooltip(), pfDetails::Update(), ProjectFileOptionsDlg::UpdateBuildCommand(), and UpdateFileDetails().
relativeToCommonTopLevelPath
wxString ProjectFile::relativeToCommonTopLevelPath
The relative filename to the common top-level path.
This is used mainly for the tree, as this is guaranteed to not contain '..'
Definition at line 135 of file projectfile.h.
Referenced by cbProject::AddFile(), ProjectManagerUI::BuildProjectTree(), cbProject::CalculateCommonTopLevelPath(), CompilerGCC::CompileFile(), CompilerGCC::CompileFileDefault(), GetObjName(), ScriptBindings::RegisterBindings(), cbEditor::SetEditorStyleBeforeFileOpen(), cbProject::SetExtendedObjectNamesGeneration(), cbEditor::SetProjectFile(), pfDetails::Update(), and UpdateFileDetails().
virtual_path
wxString ProjectFile::virtual_path
A string that represents the virtual folder this file will appear in.
This is a relative path which doesn't have to exist in the filesystem hierarchy.
Definition at line 195 of file projectfile.h.
Referenced by ProjectManagerUI::BuildProjectTree(), ProjectManagerUI::CheckForExternallyModifiedProjects(), ProjectLoader::DoUnitOptions(), ProjectLoader::ExportTargetAsProject(), cbProject::RemoveVirtualFolders(), and cbProject::ReplaceVirtualFolder().
weight
unsigned short int ProjectFile::weight
The weight.
This is a number between 0 and 100 (defaults to 50). Files with smaller weights are compiled earlier than those with larger weights.
Definition at line 145 of file projectfile.h.
Referenced by ProjectLoader::DoUnitOptions(), ProjectFileOptionsDlg::EndModal(), ProjectLoader::ExportTargetAsProject(), DirectCommands::GetTargetCompileCommands(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), and ScriptBindings::RegisterBindings().
The documentation for this class was generated from the following files:
projectfile.h
projectfile.cpp