Code::Blocks: GotoFunctionDlg Class Reference
GotoFunctionDlg Class Reference
the goto function dialog allow user to type a function name, and filter out the functions
#include <gotofunctiondlg.h>
Public Member Functions
GotoFunctionDlg (wxWindow *parent, const IncrementalSelectIterator &iterator)
virtual ~GotoFunctionDlg ()
wxIntPtr GetSelection ()
wxListCtrl * GetListCtrl ()
Public Member Functions inherited from IncrementalSelectListBase
IncrementalSelectListBase (wxWindow *parent, const IncrementalSelectIterator &iterator, const wxString &dialog, const wxString &caption=wxEmptyString, const wxString &message=wxEmptyString)
virtual ~IncrementalSelectListBase ()
void OnSearch (wxCommandEvent &event)
void OnSelect (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void SetupMode ()
void FillData () override
refresh the list
void FillColumn ()
for functions like int f(), we need three columns to display the "int", "f", and "()".
void GetCurrentSelection (int &selected, int &selectedMax) override
void UpdateCurrentSelection (int selected, int selectedPrevious) override
void OnColumnSelect (cb_unused wxListEvent &event)
void OnModeChange (cb_unused wxCommandEvent &event)
Protected Member Functions inherited from IncrementalSelectListBase
void FilterItems ()
fetch the search key word from the text control, and filter the items
void KeyDownAction (wxKeyEvent &event, int &selected, int selectedMax)
handle user pressed some special key in the editor ctrl For example, if user press the UP key, we have to select some text before the cursor
void FillList ()
fill the m_List with filtered items
Protected Attributes
wxListCtrl * m_ListColumn
the control show filtered functions
wxCheckBox * m_Mode
a check box to switch different mode of list ctrl
Protected Attributes inherited from IncrementalSelectListBase
wxListBox * m_List
wxTextCtrl * m_Text
for showing the filtered items
wxArrayString m_Result
for entering search keys
wxArrayLong m_Indexes
the filtered items
bool m_Promoted
the filtered item index in the list
const IncrementalSelectIterator & m_Iterator
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Private Member Functions
DECLARE_EVENT_TABLE ()
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
the goto function dialog allow user to type a function name, and filter out the functions
For example, you have three functions in a cpp file
int fa1();
int fa2();
int fb1();
When user type "fa" in the text ctrl, only "fa1" and "fa2" will shown in the list. The mode option defines how the list is shown. If user want to show the function return type, function name and function parameters in different columns, then the check box should be selected
Definition at line 31 of file gotofunctiondlg.h.
Constructor & Destructor Documentation
GotoFunctionDlg()
GotoFunctionDlg::GotoFunctionDlg (wxWindow * parent, const IncrementalSelectIterator & iterator)
Definition at line 29 of file gotofunctiondlg.cpp.
References Manager::Get(), and IncrementalSelectListBase::OnKeyDown().
~GotoFunctionDlg()
GotoFunctionDlg::~GotoFunctionDlg () virtual
Definition at line 53 of file gotofunctiondlg.cpp.
References m_ListColumn, and IncrementalSelectListBase::OnKeyDown().
Member Function Documentation
DECLARE_EVENT_TABLE()
GotoFunctionDlg::DECLARE_EVENT_TABLE () private
FillColumn()
void GotoFunctionDlg::FillColumn () protected
for functions like int f(), we need three columns to display the "int", "f", and "()".
Definition at line 140 of file gotofunctiondlg.cpp.
References IncrementalSelectListBase::m_Indexes, m_ListColumn, IncrementalSelectListBase::m_Promoted, IncrementalSelectListBase::m_Result, and SortAscending().
Referenced by FillData().
FillData()
void GotoFunctionDlg::FillData () override protected virtual
refresh the list
Reimplemented from IncrementalSelectListBase.
Definition at line 221 of file gotofunctiondlg.cpp.
References FillColumn(), IncrementalSelectListBase::FillList(), IncrementalSelectListBase::FilterItems(), and m_Mode.
Referenced by SetupMode().
GetCurrentSelection()
void GotoFunctionDlg::GetCurrentSelection (int & selected, int & selectedMax) override protected virtual
Reimplemented from IncrementalSelectListBase.
Definition at line 239 of file gotofunctiondlg.cpp.
References IncrementalSelectListBase::m_List, m_ListColumn, and m_Mode.
GetListCtrl()
wxListCtrl * GotoFunctionDlg::GetListCtrl ()
Definition at line 84 of file gotofunctiondlg.cpp.
References m_ListColumn.
Referenced by SortAscending().
GetSelection()
wxIntPtr GotoFunctionDlg::GetSelection ()
Definition at line 89 of file gotofunctiondlg.cpp.
References IncrementalSelectListBase::m_List, m_ListColumn, and m_Mode.
Referenced by CodeCompletion::OnGotoFunction().
OnColumnSelect()
void GotoFunctionDlg::OnColumnSelect (cb_unused wxListEvent & event) protected
Definition at line 274 of file gotofunctiondlg.cpp.
References ScriptBindings::EndModal().
OnModeChange()
void GotoFunctionDlg::OnModeChange (cb_unused wxCommandEvent & event) protected
Definition at line 279 of file gotofunctiondlg.cpp.
References Manager::Get(), Manager::GetConfigManager(), m_Mode, SetupMode(), and ConfigManager::Write().
SetupMode()
void GotoFunctionDlg::SetupMode () protected
Definition at line 61 of file gotofunctiondlg.cpp.
References FillData(), IncrementalSelectListBase::m_List, m_ListColumn, m_Mode, and IncrementalSelectListBase::m_Text.
Referenced by OnModeChange().
UpdateCurrentSelection()
void GotoFunctionDlg::UpdateCurrentSelection (int selected, int selectedPrevious) override protected virtual
Reimplemented from IncrementalSelectListBase.
Definition at line 256 of file gotofunctiondlg.cpp.
References IncrementalSelectListBase::m_List, m_ListColumn, and m_Mode.
Member Data Documentation
m_ListColumn
wxListCtrl* GotoFunctionDlg::m_ListColumn protected
the control show filtered functions
Definition at line 53 of file gotofunctiondlg.h.
Referenced by FillColumn(), GetCurrentSelection(), GetListCtrl(), GetSelection(), SetupMode(), UpdateCurrentSelection(), and ~GotoFunctionDlg().
m_Mode
wxCheckBox* GotoFunctionDlg::m_Mode protected
a check box to switch different mode of list ctrl
Definition at line 55 of file gotofunctiondlg.h.
Referenced by FillData(), GetCurrentSelection(), GetSelection(), OnModeChange(), SetupMode(), and UpdateCurrentSelection().
The documentation for this class was generated from the following files:
gotofunctiondlg.h
gotofunctiondlg.cpp