Code::Blocks: InsertClassMethodDlg Class Reference
InsertClassMethodDlg Class Reference
#include <insertclassmethoddlg.h>
Public Member Functions
InsertClassMethodDlg (wxWindow *parent, ParserBase *parser, const wxString &filename)
virtual ~InsertClassMethodDlg ()
wxArrayString GetCode () const
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void FillClasses ()
void FillMethods ()
void OnClassesChange (wxCommandEvent &event)
void OnCodeChange (wxCommandEvent &event)
void OnFilterChange (wxCommandEvent &event)
DECLARE_EVENT_TABLE ()
Private Attributes
ParserBase * m_Parser
bool m_Decl
wxString m_Filename
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
InsertClassMethodDlg::InsertClassMethodDlg (wxWindow * parent, ParserBase * parser, const wxString & filename)
InsertClassMethodDlg::~InsertClassMethodDlg () virtual
Member Function Documentation
InsertClassMethodDlg::DECLARE_EVENT_TABLE () private
void InsertClassMethodDlg::FillClasses () private
References TokenTree::at(), FillMethods(), ParserBase::GetTokenTree(), Token::m_Name, m_Parser, Token::m_TokenKind, TokenTree::size(), tkClass, and tkTypedef.
void InsertClassMethodDlg::FillMethods () private
References InsertClassMethodDlgHelper::DoFillMethodsFor(), and Token::m_Name.
Referenced by FillClasses(), OnClassesChange(), and OnFilterChange().
wxArrayString InsertClassMethodDlg::GetCode () const
References m_Decl.
void InsertClassMethodDlg::OnClassesChange (wxCommandEvent & event) private
References FillMethods().
void InsertClassMethodDlg::OnCodeChange (wxCommandEvent & event) private
References m_Decl.
void InsertClassMethodDlg::OnFilterChange (wxCommandEvent & event) private
References FillMethods().
Member Data Documentation
bool InsertClassMethodDlg::m_Decl private
Referenced by GetCode(), and OnCodeChange().
wxString InsertClassMethodDlg::m_Filename private
ParserBase* InsertClassMethodDlg::m_Parser private
Referenced by FillClasses().
The documentation for this class was generated from the following files:
insertclassmethoddlg.h
insertclassmethoddlg.cpp