Code::Blocks: classbrowser.cpp File Reference
classbrowser.cpp File Reference
#include <sdk.h>
#include <wx/tokenzr.h>
#include <cbstyledtextctrl.h>
#include "classbrowser.h"
#include "nativeparser.h"
#include "parser/ccdebuginfo.h"
Macros
#define CC_CLASS_BROWSER_DEBUG_OUTPUT 0
#define TRACE(format, args...)
#define TRACE2(format, args...)
Variables
int idMenuJumpToDeclaration = wxNewId()
int idMenuJumpToImplementation = wxNewId()
int idMenuRefreshTree = wxNewId()
int idCBViewInheritance = wxNewId()
int idCBExpandNS = wxNewId()
int idMenuForceReparse = wxNewId()
int idMenuDebugSmartSense = wxNewId()
int idCBNoSort = wxNewId()
int idCBSortByAlpabet = wxNewId()
int idCBSortByKind = wxNewId()
int idCBSortByScope = wxNewId()
int idCBSortByLine = wxNewId()
int idCBBottomTree = wxNewId()
int idThreadEvent = wxNewId()
the event ID which will be sent from worker thread to ClassBrowser
Macro Definition Documentation
CC_CLASS_BROWSER_DEBUG_OUTPUT
#define CC_CLASS_BROWSER_DEBUG_OUTPUT 0
Definition at line 48 of file classbrowser.cpp.
TRACE
#define TRACE (format, args...)
Definition at line 75 of file classbrowser.cpp.
Referenced by ClassBrowser::ThreadedBuildTree(), and ClassBrowser::UpdateClassBrowserView().
TRACE2
#define TRACE2 (format, args...)
Definition at line 76 of file classbrowser.cpp.
Variable Documentation
idCBBottomTree
int idCBBottomTree = wxNewId()
Definition at line 91 of file classbrowser.cpp.
Referenced by ClassBrowser::OnCBViewMode(), and ClassBrowser::ShowMenu().
idCBExpandNS
int idCBExpandNS = wxNewId()
Definition at line 83 of file classbrowser.cpp.
Referenced by ClassBrowser::OnCBExpandNS(), ClassBrowser::OnCBViewMode(), and ClassBrowser::ShowMenu().
idCBNoSort
int idCBNoSort = wxNewId()
Definition at line 86 of file classbrowser.cpp.
Referenced by ClassBrowser::ShowMenu().
idCBSortByAlpabet
int idCBSortByAlpabet = wxNewId()
Definition at line 87 of file classbrowser.cpp.
Referenced by ClassBrowser::OnSetSortType(), and ClassBrowser::ShowMenu().
idCBSortByKind
int idCBSortByKind = wxNewId()
Definition at line 88 of file classbrowser.cpp.
Referenced by ClassBrowser::OnSetSortType(), and ClassBrowser::ShowMenu().
idCBSortByLine
int idCBSortByLine = wxNewId()
Definition at line 90 of file classbrowser.cpp.
Referenced by ClassBrowser::OnSetSortType(), and ClassBrowser::ShowMenu().
idCBSortByScope
int idCBSortByScope = wxNewId()
Definition at line 89 of file classbrowser.cpp.
Referenced by ClassBrowser::OnSetSortType(), and ClassBrowser::ShowMenu().
idCBViewInheritance
int idCBViewInheritance = wxNewId()
Definition at line 82 of file classbrowser.cpp.
Referenced by ClassBrowser::OnCBViewMode(), and ClassBrowser::ShowMenu().
idMenuDebugSmartSense
int idMenuDebugSmartSense = wxNewId()
Definition at line 85 of file classbrowser.cpp.
Referenced by ClassBrowser::ShowMenu().
idMenuForceReparse
int idMenuForceReparse = wxNewId()
Definition at line 84 of file classbrowser.cpp.
Referenced by ClassBrowser::ShowMenu().
idMenuJumpToDeclaration
int idMenuJumpToDeclaration = wxNewId()
Definition at line 79 of file classbrowser.cpp.
Referenced by ClassBrowser::ShowMenu().
idMenuJumpToImplementation
int idMenuJumpToImplementation = wxNewId()
Definition at line 80 of file classbrowser.cpp.
Referenced by ClassBrowser::OnJumpTo(), and ClassBrowser::ShowMenu().
idMenuRefreshTree
int idMenuRefreshTree = wxNewId()
Definition at line 81 of file classbrowser.cpp.
Referenced by ClassBrowser::ShowMenu().
idThreadEvent
int idThreadEvent = wxNewId()
the event ID which will be sent from worker thread to ClassBrowser
Definition at line 94 of file classbrowser.cpp.
Referenced by ClassBrowserBuilderThread::Init(), and ClassBrowser::ThreadedBuildTree().