Code::Blocks: wxSwitcherDialog Class Reference
wxSwitcherDialog Class Reference
#include <switcherdlg.h>
Public Member Functions
wxSwitcherDialog ()
wxSwitcherDialog (const wxSwitcherItems &items, wxWindow *parent, wxWindowID id=-1, const wxString &title=_("Pane Switcher"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxSTAY_ON_TOP|wxDIALOG_NO_PARENT|wxBORDER_SIMPLE)
bool Create (const wxSwitcherItems &items, wxWindow *parent, wxWindowID id=-1, const wxString &title=_("Pane Switcher"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxSTAY_ON_TOP|wxDIALOG_NO_PARENT|wxBORDER_SIMPLE)
void Init ()
void OnCloseWindow (wxCloseEvent &event)
void OnActivate (wxActivateEvent &event)
void OnSelectItem (wxCommandEvent &event)
void OnPaint (wxPaintEvent &event)
int GetSelection () const
void ShowDescription (int i)
void SetBorderColour (const wxColour &colour)
void SetExtraNavigationKey (int keyCode)
int GetExtraNavigationKey () const
void SetModifierKey (int modifierKey)
int GetModifierKey () const
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Attributes
wxMultiColumnListCtrl * m_listCtrl
wxHtmlWindow * m_descriptionCtrl
bool m_closing
long m_switcherBorderStyle
wxColour m_borderColour
int m_extraNavigationKey
int m_modifierKey
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
wxSwitcherDialog shows a wxMultiColumnListCtrl with a list of panes and tabs for the user to choose. Ctrl+Tab cycles through them.
Constructor & Destructor Documentation
wxSwitcherDialog::wxSwitcherDialog () inline
References Init().
wxSwitcherDialog::wxSwitcherDialog (const wxSwitcherItems & items, wxWindow * parent, wxWindowID id = -1, const wxString & title = _("Pane Switcher"), const wxPoint & position = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxSTAY_ON_TOP|wxDIALOG_NO_PARENT|wxBORDER_SIMPLE)
wxSwitcherDialog shows a wxMultiColumnListCtrl with a list of panes and tabs for the user to choose. Ctrl+Tab cycles through them.
Member Function Documentation
bool wxSwitcherDialog::Create (const wxSwitcherItems & items, wxWindow * parent, wxWindowID id = -1, const wxString & title = _("Pane Switcher"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxSTAY_ON_TOP|wxDIALOG_NO_PARENT|wxBORDER_SIMPLE)
References wxMultiColumnListCtrl::AdvanceToNextSelectableItem(), wxMultiColumnListCtrl::CalculateLayout(), wxScrollingDialog::Create(), wxMultiColumnListCtrl::Create(), wxMultiColumnListCtrl::GetItems(), wxSwitcherItems::GetSelection(), m_descriptionCtrl, m_extraNavigationKey, m_listCtrl, m_modifierKey, m_switcherBorderStyle, wxMultiColumnListCtrl::SetExtraNavigationKey(), wxMultiColumnListCtrl::SetItems(), wxMultiColumnListCtrl::SetModifierKey(), wxSwitcherItems::SetSelection(), and ShowDescription().
int wxSwitcherDialog::GetExtraNavigationKey () const inline
References m_extraNavigationKey.
int wxSwitcherDialog::GetModifierKey () const inline
References m_modifierKey.
int wxSwitcherDialog::GetSelection () const
References wxMultiColumnListCtrl::GetItems(), wxSwitcherItems::GetSelection(), and m_listCtrl.
Referenced by OnCloseWindow(), and MainFrame::OnSwitchTabs().
void wxSwitcherDialog::Init ()
References m_borderColour, m_closing, m_descriptionCtrl, m_extraNavigationKey, m_listCtrl, m_modifierKey, m_switcherBorderStyle, and NULL.
Referenced by wxSwitcherDialog().
void wxSwitcherDialog::OnActivate (wxActivateEvent & event)
References ScriptBindings::EndModal(), and m_closing.
void wxSwitcherDialog::OnCloseWindow (wxCloseEvent & event)
References ScriptBindings::EndModal(), GetSelection(), and m_closing.
void wxSwitcherDialog::OnPaint (wxPaintEvent & event)
References m_borderColour, m_descriptionCtrl, and m_switcherBorderStyle.
void wxSwitcherDialog::OnSelectItem (wxCommandEvent & event)
References ShowDescription().
void wxSwitcherDialog::SetBorderColour (const wxColour & colour) inline
References m_borderColour.
void wxSwitcherDialog::SetExtraNavigationKey (int keyCode)
References m_extraNavigationKey, m_listCtrl, and wxMultiColumnListCtrl::SetExtraNavigationKey().
Referenced by MainFrame::OnSwitchTabs().
void wxSwitcherDialog::SetModifierKey (int modifierKey)
References m_listCtrl, m_modifierKey, and wxMultiColumnListCtrl::SetModifierKey().
Referenced by MainFrame::OnSwitchTabs().
void wxSwitcherDialog::ShowDescription (int i)
References ColourToHexString(), wxSwitcherItems::GetBackgroundColour(), wxSwitcherItem::GetDescription(), wxSwitcherItems::GetItem(), wxMultiColumnListCtrl::GetItems(), wxSwitcherItem::GetTitle(), m_descriptionCtrl, and m_listCtrl.
Referenced by Create(), and OnSelectItem().
Member Data Documentation
wxColour wxSwitcherDialog::m_borderColour private
Referenced by Init(), OnPaint(), and SetBorderColour().
bool wxSwitcherDialog::m_closing private
Referenced by Init(), OnActivate(), and OnCloseWindow().
wxHtmlWindow* wxSwitcherDialog::m_descriptionCtrl private
Referenced by Create(), Init(), OnPaint(), and ShowDescription().
int wxSwitcherDialog::m_extraNavigationKey private
Referenced by Create(), GetExtraNavigationKey(), Init(), and SetExtraNavigationKey().
wxMultiColumnListCtrl* wxSwitcherDialog::m_listCtrl private
Referenced by Create(), GetSelection(), Init(), SetExtraNavigationKey(), SetModifierKey(), and ShowDescription().
int wxSwitcherDialog::m_modifierKey private
Referenced by Create(), GetModifierKey(), Init(), and SetModifierKey().
long wxSwitcherDialog::m_switcherBorderStyle private
Referenced by Create(), Init(), and OnPaint().
The documentation for this class was generated from the following files:
switcherdlg.h
switcherdlg.cpp