Code::Blocks: EditPathDlg Class Reference
EditPathDlg Class Reference
#include <editpathdlg.h>
Public Member Functions
EditPathDlg (wxWindow *parent, const wxString &path, const wxString &basepath, const wxString &title=_("Edit Path"), const wxString &message=_T(""), const bool wantDir=true, const bool allowMultiSel=false, const wxString &filter=_("All files(*)|*"))
virtual ~EditPathDlg ()
EditPathDlg & operator= (const EditPathDlg &)
const wxString & GetPath ()
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void OnBrowse (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Protected Attributes
wxString m_Path
wxString m_Message
wxString m_Basepath
wxString m_Filter
bool m_WantDir
bool m_AllowMultiSel
bool m_AskMakeRelative
bool m_ShowCreateDirButton
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Private Member Functions
DECLARE_EVENT_TABLE ()
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
EditPathDlg::EditPathDlg (wxWindow * parent, const wxString & path, const wxString & basepath, const wxString & title = _("Edit Path"), const wxString & message = _T(""), const bool wantDir = true, const bool allowMultiSel = false, const wxString & filter = _("All files(*)|*"))
EditPathDlg::~EditPathDlg () virtual
Member Function Documentation
EditPathDlg::DECLARE_EVENT_TABLE () private
void EditPathDlg::EndModal (int retCode)
References ScriptBindings::EndModal(), and m_Path.
const wxString& EditPathDlg::GetPath () inline
Referenced by CompilerOptionsDlg::OnAddExtraPathClick(), CompilerOptionsDlg::OnEditExtraPathClick(), and ScriptBindings::Register_UtilDialogs().
void EditPathDlg::OnBrowse (wxCommandEvent & event) protected
References cbMessageBox(), ChooseDirectory(), DEFAULT_ARRAY_SEP, Manager::Get(), Manager::GetMacrosManager(), GetStringFromArray(), m_AllowMultiSel, m_AskMakeRelative, m_Basepath, m_Filter, m_Message, m_Path, m_ShowCreateDirButton, m_WantDir, PlaceWindow(), MacrosManager::ReplaceEnvVars(), and s_LastPath.
void EditPathDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
EditPathDlg& EditPathDlg::operator= (const EditPathDlg &) inline
Member Data Documentation
bool EditPathDlg::m_AllowMultiSel protected
Referenced by OnBrowse().
bool EditPathDlg::m_AskMakeRelative protected
Referenced by OnBrowse().
wxString EditPathDlg::m_Basepath protected
Referenced by OnBrowse().
wxString EditPathDlg::m_Filter protected
Referenced by OnBrowse().
wxString EditPathDlg::m_Message protected
Referenced by OnBrowse().
wxString EditPathDlg::m_Path protected
Referenced by EndModal(), and OnBrowse().
bool EditPathDlg::m_ShowCreateDirButton protected
Referenced by OnBrowse().
bool EditPathDlg::m_WantDir protected
Referenced by OnBrowse().
The documentation for this class was generated from the following files:
editpathdlg.h
editpathdlg.cpp