Code::Blocks: BackgroundThreadPool Class Reference
BackgroundThreadPool Class Reference
#include <backgroundthread.h>
Public Member Functions
BackgroundThreadPool (size_t num_threads=4)
~BackgroundThreadPool ()
void AddThread (BackgroundThread *t)
void Queue (AbstractJob *j)
Private Types
typedef std::list< BackgroundThread * > ThreadList
Private Attributes
JobQueue queue
wxSemaphore semaphore
ThreadList threadList
Member Typedef Documentation
typedef std::list<BackgroundThread*> BackgroundThreadPool::ThreadList private
Constructor & Destructor Documentation
BackgroundThreadPool::BackgroundThreadPool (size_t num_threads = 4) inline
References AddThread().
BackgroundThreadPool::~BackgroundThreadPool () inline
References Delete().
Member Function Documentation
void BackgroundThreadPool::AddThread (BackgroundThread * t) inline
Referenced by BackgroundThreadPool().
void BackgroundThreadPool::Queue (AbstractJob * j) inline
References JobQueue::Push().
Member Data Documentation
JobQueue BackgroundThreadPool::queue private
wxSemaphore BackgroundThreadPool::semaphore private
ThreadList BackgroundThreadPool::threadList private
The documentation for this class was generated from the following file:
backgroundthread.h