Code::Blocks: IncrementalSelectDialog Class Reference
IncrementalSelectDialog Class Reference
Simple incremental select dialog that shows a single column and doesn't have much ui elements, except the text and list controls.
#include <incremental_select_helper.h>
Public Member Functions
IncrementalSelectDialog (wxWindow *parent, IncrementalSelectIterator *iterator, const wxString &title, const wxString &message)
~IncrementalSelectDialog () override
int GetSelection ()
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Member Functions
void BuildContent (wxWindow *parent, IncrementalSelectIterator *iterator, const wxString &title, const wxString &message)
Private Attributes
IncrementalSelectHandler m_handler
IncrementalListCtrl * m_resultList
wxTextCtrl * m_text
Detailed Description
Simple incremental select dialog that shows a single column and doesn't have much ui elements, except the text and list controls.
Definition at line 114 of file incremental_select_helper.h.
Constructor & Destructor Documentation
IncrementalSelectDialog()
IncrementalSelectDialog::IncrementalSelectDialog (wxWindow * parent, IncrementalSelectIterator * iterator, const wxString & title, const wxString & message)
Definition at line 362 of file incremental_select_helper.cpp.
~IncrementalSelectDialog()
IncrementalSelectDialog::~IncrementalSelectDialog () override
Definition at line 371 of file incremental_select_helper.cpp.
Member Function Documentation
BuildContent()
void IncrementalSelectDialog::BuildContent (wxWindow * parent, IncrementalSelectIterator * iterator, const wxString & title, const wxString & message) protected
Definition at line 376 of file incremental_select_helper.cpp.
References _(), _T, wxBoxSizer::Add(), wxBoxSizer::Fit(), ID_RESULT_LIST, ID_TEXTCTRL1, wxListItem::SetId(), wxBoxSizer::SetSizeHints(), wxListItem::SetText(), wxListItem::SetWidth(), wxALL, wxCLOSE_BOX, wxDEFAULT_DIALOG_STYLE, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxHSCROLL, wxID_ANY, wxLC_NO_HEADER, wxLC_REPORT, wxLC_SINGLE_SEL, wxLC_VIRTUAL, wxLEFT, wxMAXIMIZE_BOX, wxRESIZE_BORDER, wxRIGHT, wxTE_PROCESS_ENTER, wxTOP, wxVERTICAL, and wxVSCROLL.
GetSelection()
int IncrementalSelectDialog::GetSelection ()
Definition at line 407 of file incremental_select_helper.cpp.
Referenced by FindReplaceDlg::OnSelectTarget(), and CompilerGCC::OnSelectTarget().
Member Data Documentation
m_handler
IncrementalSelectHandler IncrementalSelectDialog::m_handler private
Definition at line 123 of file incremental_select_helper.h.
m_resultList
IncrementalListCtrl* IncrementalSelectDialog::m_resultList private
Definition at line 125 of file incremental_select_helper.h.
m_text
wxTextCtrl* IncrementalSelectDialog::m_text private
Definition at line 126 of file incremental_select_helper.h.
The documentation for this class was generated from the following files:
incremental_select_helper.h
incremental_select_helper.cpp