Code::Blocks: GdbCmd_ExamineMemory Class Reference
GdbCmd_ExamineMemory Class Reference
#include <gdb_commands.h>
Public Member Functions
GdbCmd_ExamineMemory (DebuggerDriver *driver)
void ParseOutput (const wxString &output)
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
virtual bool IsContinueCommand () const
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to examine a memory region.
Constructor & Destructor Documentation
GdbCmd_ExamineMemory::GdbCmd_ExamineMemory (DebuggerDriver * driver) inline
Parameters
dlg The memory dialog.
References CleanStringValue(), Manager::Get(), cbExamineMemoryDlg::GetBaseAddress(), cbExamineMemoryDlg::GetBytes(), Manager::GetDebuggerManager(), DebuggerManager::GetExamineMemoryDialog(), and DebuggerCmd::m_Cmd.
Member Function Documentation
void GdbCmd_ExamineMemory::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
References cbExamineMemoryDlg::AddError(), cbExamineMemoryDlg::AddHexByte(), cbExamineMemoryDlg::Begin(), cbExamineMemoryDlg::Clear(), cbExamineMemoryDlg::End(), Manager::Get(), GetArrayFromString(), Manager::GetDebuggerManager(), DebuggerManager::GetExamineMemoryDialog(), and reExamineMemoryLine().
The documentation for this class was generated from the following file:
gdb_commands.h