Code::Blocks: WizPageBase Class Reference
WizPageBase Class Reference
#include <wizpage.h>
Public Member Functions
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanging (wxWizardEvent &event)
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Private Attributes
wxString m_PageName
bool m_SkipPage
Static Private Attributes
static PagesByName s_PagesByName
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 33 of file wizpage.h.
Constructor & Destructor Documentation
WizPageBase()
WizPageBase::WizPageBase (const wxString & pageName, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 92 of file wizpage.cpp.
References _T, cbThrow, Manager::Get(), Manager::GetConfigManager(), and ConfigManager::ReadBool().
~WizPageBase()
WizPageBase::~WizPageBase ()
Definition at line 108 of file wizpage.cpp.
Member Function Documentation
GetNext()
wxWizardPage * WizPageBase::GetNext () const virtual
Implements wxWizardPage.
Definition at line 138 of file wizpage.cpp.
References _T, cbU2C(), ScriptingManager::DisplayErrors(), Manager::Get(), wxWizardPage::GetNext(), Manager::GetScriptingManager(), and wxString::IsEmpty().
GetPageName()
wxString WizPageBase::GetPageName () const inline
Definition at line 46 of file wizpage.h.
Referenced by WizGenericSelectPathPanel::OnPageChanging(), and WizGenericSingleChoiceList::OnPageChanging().
GetPrev()
wxWizardPage * WizPageBase::GetPrev () const virtual
Implements wxWizardPage.
Definition at line 116 of file wizpage.cpp.
References _T, cbU2C(), ScriptingManager::DisplayErrors(), Manager::Get(), wxWizardPage::GetPrev(), Manager::GetScriptingManager(), and wxString::IsEmpty().
GetSkipPage()
bool WizPageBase::GetSkipPage () const inline
Definition at line 47 of file wizpage.h.
Referenced by WizInfoPanel::OnPageChanging().
OnPageChanged()
void WizPageBase::OnPageChanged (wxWizardEvent & event) virtual
Reimplemented in WizProjectPathPanel.
Definition at line 179 of file wizpage.cpp.
References _T, cbU2C(), ScriptingManager::DisplayErrors(), Manager::Get(), wxWizardEvent::GetDirection(), Manager::GetScriptingManager(), and WizPage::OnButton().
Referenced by AppendPathSepIfNeeded(), and WizProjectPathPanel::OnPageChanged().
OnPageChanging()
void WizPageBase::OnPageChanging (wxWizardEvent & event) virtual
Reimplemented in WizGenericSingleChoiceList, WizBuildTargetPanel, WizCompilerPanel, WizGenericSelectPathPanel, WizProjectPathPanel, WizFilePathPanel, and WizInfoPanel.
Definition at line 158 of file wizpage.cpp.
References _T, cbU2C(), ScriptingManager::DisplayErrors(), Manager::Get(), Manager::GetConfigManager(), wxWizardEvent::GetDirection(), Manager::GetScriptingManager(), and ConfigManager::Write().
Referenced by AppendPathSepIfNeeded(), WizInfoPanel::OnPageChanging(), WizFilePathPanel::OnPageChanging(), WizProjectPathPanel::OnPageChanging(), WizGenericSelectPathPanel::OnPageChanging(), WizCompilerPanel::OnPageChanging(), WizBuildTargetPanel::OnPageChanging(), and WizGenericSingleChoiceList::OnPageChanging().
SetSkipPage()
void WizPageBase::SetSkipPage (bool skip) inline
Definition at line 48 of file wizpage.h.
Referenced by WizInfoPanel::OnPageChanging().
SkipPage()
virtual bool WizPageBase::SkipPage () const inline virtual
Definition at line 39 of file wizpage.h.
Referenced by Wiz::AddBuildTargetPage(), Wiz::AddCompilerPage(), Wiz::AddFilePathPage(), Wiz::AddGenericSelectPathPage(), Wiz::AddGenericSingleChoiceListPage(), Wiz::AddInfoPage(), Wiz::AddPage(), and Wiz::AddProjectPathPage().
Member Data Documentation
m_PageName
wxString WizPageBase::m_PageName private
Definition at line 52 of file wizpage.h.
m_SkipPage
bool WizPageBase::m_SkipPage private
Definition at line 53 of file wizpage.h.
s_PagesByName
PagesByName WizPageBase::s_PagesByName static private
Definition at line 51 of file wizpage.h.
Referenced by AppendPathSepIfNeeded().
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp