Code::Blocks: HTMLFileLogger Class Reference
HTMLFileLogger Class Reference
#include <loggers.h>
Public Member Functions
HTMLFileLogger (const wxString &filename)
void SetCSS (const CSS &in_css)
virtual void Append (const wxString &msg, Logger::level lv)
virtual void Open (const wxString &filename)
virtual void Close ()
Public Member Functions inherited from FileLogger
FileLogger (const wxString &filename)
FileLogger ()
virtual void Append (const wxString &msg, cb_unused Logger::level lv)
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void Clear ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual void UpdateSettings ()
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool GetWrapMode () const
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Private Attributes
CSS css
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Protected Attributes inherited from FileLogger
wxFFile f
Detailed Description
a logger which prints messages to an HTML file
Constructor & Destructor Documentation
HTMLFileLogger::HTMLFileLogger (const wxString & filename)
References Open().
Member Function Documentation
void HTMLFileLogger::Append (const wxString & msg, Logger::level lv) virtual
Implements Logger.
References FileLogger::f.
void HTMLFileLogger::Close () virtual
Reimplemented from FileLogger.
References FileLogger::Close(), and FileLogger::f.
void HTMLFileLogger::Open (const wxString & filename) virtual
Reimplemented from FileLogger.
References CSS::asterisk, CSS::caption, CSS::critical, css, CSS::error, FileLogger::f, CSS::failure, CSS::info, FileLogger::Open(), CSS::pagetitle, CSS::success, and CSS::warning.
Referenced by HTMLFileLogger().
void HTMLFileLogger::SetCSS (const CSS & in_css) inline
Member Data Documentation
CSS HTMLFileLogger::css private
Referenced by Open().
The documentation for this class was generated from the following files:
loggers.h
loggers.cpp