Code::Blocks: GdbCmd_DisassemblyInit Class Reference
GdbCmd_DisassemblyInit Class Reference
Command to initialize a disassembly.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_DisassemblyInit (DebuggerDriver *driver, wxString disassemblyFlavor=wxEmptyString, wxString hexAddrStr=wxT(""))
void ParseOutput (const wxString &p_output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Static Public Member Functions
static void Clear ()
Private Attributes
wxString m_disassemblyFlavor
wxString m_hexAddrStr
Static Private Attributes
static wxString LastAddr
static wxString LastSymbol
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to initialize a disassembly.
Use this instead of GdbCmd_Disassembly, which is chain-called by this.
Definition at line 1484 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_DisassemblyInit()
GdbCmd_DisassemblyInit::GdbCmd_DisassemblyInit (DebuggerDriver * driver, wxString disassemblyFlavor = wxEmptyString, wxString hexAddrStr = wxT("")) inline
Definition at line 1493 of file gdb_commands.h.
References _T, Cursor::address, wxString::empty(), DebuggerDriver::GetCursor(), DebuggerCmd::m_Cmd, and wxT.
Member Function Documentation
Clear()
static void GdbCmd_DisassemblyInit::Clear () inline static
Definition at line 1585 of file gdb_commands.h.
References wxString::Clear(), LastAddr, and LastSymbol.
Referenced by GDB_driver::Start().
ParseOutput()
void GdbCmd_DisassemblyInit::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 1516 of file gdb_commands.h.
References _T, Cursor::address, cbDebuggerStringToAddress(), cbDisassemblyDlg::Clear(), wxString::empty(), wxString::find(), Manager::Get(), GetArrayFromString(), DebuggerDriver::GetCursor(), Manager::GetDebuggerManager(), DebuggerManager::GetDisassemblyDialog(), wxRegEx::GetMatch(), DebuggerManager::IsDisassemblyMixedMode(), wxString::length(), DebuggerDriver::Log(), DebuggerCmd::m_pDriver, cbStackFrame::MakeValid(), wxRegEx::Matches(), wxString::npos, DebuggerDriver::QueueCommand(), reDisassemblyCurPC(), reDisassemblyInit(), reDisassemblyInitFunc(), reDisassemblyInitSymbol(), cbDisassemblyDlg::SetActiveAddress(), cbStackFrame::SetAddress(), DebuggerDriver::SetCursor(), cbStackFrame::SetSymbol(), and wxString::substr().
Member Data Documentation
LastAddr
wxString GdbCmd_DisassemblyInit::LastAddr static private
Definition at line 1489 of file gdb_commands.h.
Referenced by Clear().
LastSymbol
wxString GdbCmd_DisassemblyInit::LastSymbol static private
Definition at line 1490 of file gdb_commands.h.
Referenced by Clear().
m_disassemblyFlavor
wxString GdbCmd_DisassemblyInit::m_disassemblyFlavor private
Definition at line 1486 of file gdb_commands.h.
m_hexAddrStr
wxString GdbCmd_DisassemblyInit::m_hexAddrStr private
Definition at line 1487 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h