Code::Blocks: AutoDetectCompilers Class Reference
AutoDetectCompilers Class Reference
#include <autodetectcompilers.h>
Public Member Functions
AutoDetectCompilers (wxWindow *parent)
virtual ~AutoDetectCompilers ()
void OnDefaultClick (wxCommandEvent &event)
void OnMouseMotion (wxMouseEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Detailed Description
Definition at line 14 of file autodetectcompilers.h.
Constructor & Destructor Documentation
AutoDetectCompilers()
AutoDetectCompilers::AutoDetectCompilers (wxWindow * parent)
Definition at line 37 of file autodetectcompilers.cpp.
References _(), _T, adrDetected, Compiler::AutoDetectInstallationDir(), wxListCtrl::ClearAll(), wxFileName::DirExists(), ConfigManager::Exists(), wxXmlResource::Get(), Manager::Get(), CompilerFactory::GetCompiler(), CompilerFactory::GetCompilersCount(), Manager::GetConfigManager(), CompilerFactory::GetDefaultCompiler(), Compiler::GetID(), wxListCtrl::GetItemCount(), Manager::GetMacrosManager(), Compiler::GetMasterPath(), Compiler::GetName(), Compiler::GetParentID(), wxListCtrl::InsertColumn(), wxListCtrl::InsertItem(), wxString::IsEmpty(), wxXmlResource::LoadObject(), OnMouseMotion(), MacrosManager::ReplaceMacros(), wxListCtrl::SetColumnWidth(), wxListCtrl::SetItem(), wxListCtrl::SetItemBackgroundColour(), wxListCtrl::SetItemTextColour(), Compiler::SetMasterPath(), wxEVT_MOTION, wxLIGHT_GREY, wxLIST_AUTOSIZE, wxLIST_FORMAT_LEFT, wxRED, and wxT.
~AutoDetectCompilers()
AutoDetectCompilers::~AutoDetectCompilers () virtual
Definition at line 133 of file autodetectcompilers.cpp.
Member Function Documentation
OnDefaultClick()
void AutoDetectCompilers::OnDefaultClick (wxCommandEvent & event)
Definition at line 138 of file autodetectcompilers.cpp.
References CompilerFactory::GetDefaultCompiler(), wxListCtrl::GetNextItem(), CompilerFactory::SetDefaultCompiler(), wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
OnMouseMotion()
void AutoDetectCompilers::OnMouseMotion (wxMouseEvent & event)
Definition at line 149 of file autodetectcompilers.cpp.
References CompilerFactory::GetCompiler(), wxListCtrl::GetItem(), Compiler::GetMasterPath(), wxMouseEvent::GetPosition(), wxListCtrl::HitTest(), wxString::IsEmpty(), wxEmptyString, wxLIST_MASK_TEXT, wxNOT_FOUND, and wxT.
Referenced by AutoDetectCompilers().
OnUpdateUI()
void AutoDetectCompilers::OnUpdateUI (wxUpdateUIEvent & event)
Definition at line 179 of file autodetectcompilers.cpp.
References wxListCtrl::GetNextItem(), wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
The documentation for this class was generated from the following files:
autodetectcompilers.h
autodetectcompilers.cpp