Code::Blocks: InfoWindow Class Reference
InfoWindow Class Reference
#include <infowindow.h>
Static Public Member Functions
static void Display (const wxString &title, const wxString &message, unsigned int delay=5000, unsigned int hysteresis=1)
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Private Member Functions
InfoWindow (const wxString &title, const wxString &message, unsigned int delay, unsigned int hysteresis)
virtual ~InfoWindow ()
void OnTimer (wxTimerEvent &e)
void OnMove (wxMouseEvent &e)
void OnClick (wxMouseEvent &e)
Private Attributes
wxTimer * m_timer
int left
int top
int hMin
int pos
unsigned int status
unsigned int m_delay
unsigned int ks
std::list< wxString >::iterator my_message_iterator
Additional Inherited Members
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 39 of file infowindow.h.
Constructor & Destructor Documentation
InfoWindow()
InfoWindow::InfoWindow (const wxString & title, const wxString & message, unsigned int delay, unsigned int hysteresis) private
Definition at line 158 of file infowindow.cpp.
References Manager::Get(), iBitmap, textBackground(), textForeground(), and titleBackground().
~InfoWindow()
InfoWindow::~InfoWindow () private virtual
Definition at line 237 of file infowindow.cpp.
Member Function Documentation
Display()
void InfoWindow::Display (const wxString & title, const wxString & message, unsigned int delay = 5000, unsigned int hysteresis = 1) static
Definition at line 294 of file infowindow.cpp.
Referenced by UserVariableManager::Arrogate(), UsrGlblMgrEditDialog::CloneSet(), UsrGlblMgrEditDialog::CloneVar(), DetectLineEnds(), FindReplace::Find(), Wiz::Launch(), cbEditor::MarkerNext(), cbEditor::MarkerPrevious(), MainFrame::OnEditSelectAll(), cbProject::Open(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), GdbCmd_RemoteTarget::ParseOutput(), ScriptBindings::Register_Globals(), FindReplace::Replace(), UserVariableManager::Replace(), FindReplace::ReplaceInFiles(), PluginManager::ScanForPlugins(), CompilerGCC::SetupEnvironment(), cbDebuggerPlugin::SyncEditor(), and FileManager::WriteWxStringToFile().
OnClick()
void InfoWindow::OnClick (wxMouseEvent & e) private
Definition at line 286 of file infowindow.cpp.
OnMove()
void InfoWindow::OnMove (wxMouseEvent & e) private
Definition at line 280 of file infowindow.cpp.
OnTimer()
void InfoWindow::OnTimer (wxTimerEvent & e) private
Definition at line 245 of file infowindow.cpp.
Member Data Documentation
hMin
int InfoWindow::hMin private
Definition at line 54 of file infowindow.h.
ks
unsigned int InfoWindow::ks private
Definition at line 58 of file infowindow.h.
left
int InfoWindow::left private
Definition at line 52 of file infowindow.h.
m_delay
unsigned int InfoWindow::m_delay private
Definition at line 57 of file infowindow.h.
m_timer
wxTimer* InfoWindow::m_timer private
Definition at line 51 of file infowindow.h.
my_message_iterator
std::list<wxString>::iterator InfoWindow::my_message_iterator private
Definition at line 59 of file infowindow.h.
pos
int InfoWindow::pos private
Definition at line 55 of file infowindow.h.
status
unsigned int InfoWindow::status private
Definition at line 56 of file infowindow.h.
top
int InfoWindow::top private
Definition at line 53 of file infowindow.h.
The documentation for this class was generated from the following files:
infowindow.h
infowindow.cpp