Code::Blocks: wxDialogLayoutAdapter Class Reference
wxDialogLayoutAdapter Class Reference abstract
#include <scrollingdialog.h>
Public Member Functions
wxDialogLayoutAdapter ()
virtual bool CanDoLayoutAdaptation (wxDialogHelper *dialog)=0
Override this function to indicate that adaptation should be done.
virtual bool DoLayoutAdaptation (wxDialogHelper *dialog)=0
Override this function to do the adaptation.
Detailed Description
Definition at line 34 of file scrollingdialog.h.
Constructor & Destructor Documentation
wxDialogLayoutAdapter()
wxDialogLayoutAdapter::wxDialogLayoutAdapter () inline
Definition at line 38 of file scrollingdialog.h.
References CanDoLayoutAdaptation(), and DoLayoutAdaptation().
Member Function Documentation
CanDoLayoutAdaptation()
virtual bool wxDialogLayoutAdapter::CanDoLayoutAdaptation (wxDialogHelper * dialog) pure virtual
Override this function to indicate that adaptation should be done.
Implemented in wxStandardDialogLayoutAdapter.
Referenced by wxDialogHelper::GetDialog(), wxDialogLayoutAdapter(), and wxStandardDialogLayoutAdapter::wxStandardDialogLayoutAdapter().
DoLayoutAdaptation()
virtual bool wxDialogLayoutAdapter::DoLayoutAdaptation (wxDialogHelper * dialog) pure virtual
Override this function to do the adaptation.
Implemented in wxStandardDialogLayoutAdapter.
Referenced by wxDialogHelper::DoLayoutAdaptation(), wxDialogHelper::GetDialog(), wxDialogLayoutAdapter(), and wxStandardDialogLayoutAdapter::wxStandardDialogLayoutAdapter().
The documentation for this class was generated from the following file:
scrollingdialog.h