Code::Blocks: cbEditorPrintout Class Reference
cbEditorPrintout Class Reference
#include <cbeditorprintout.h>
Public Member Functions
cbEditorPrintout (const wxString &title, cbStyledTextCtrl *control, bool selectionOnly)
~cbEditorPrintout ()
bool OnPrintPage (int page)
bool HasPage (int page)
void GetPageInfo (int *minPage, int *maxPage, int *selPageFrom, int *selPageTo)
bool OnBeginDocument (int startPage, int endPage)
Protected Member Functions
bool ScaleDC (wxDC *dc)
Protected Attributes
cbStyledTextCtrl * m_TextControl
wxRect m_pageRect
wxRect m_printRect
int m_printed
int m_SelStart
int m_SelEnd
wxArrayInt * m_pPageSelStart
Detailed Description
Definition at line 13 of file cbeditorprintout.h.
Constructor & Destructor Documentation
cbEditorPrintout()
cbEditorPrintout::cbEditorPrintout (const wxString & title, cbStyledTextCtrl * control, bool selectionOnly)
Definition at line 25 of file cbeditorprintout.cpp.
References wxScintilla::GetLength(), wxScintilla::GetSelectedText(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxString::IsEmpty(), m_pPageSelStart, m_SelEnd, and m_SelStart.
~cbEditorPrintout()
cbEditorPrintout::~cbEditorPrintout ()
Definition at line 40 of file cbeditorprintout.cpp.
References m_pPageSelStart.
Member Function Documentation
GetPageInfo()
void cbEditorPrintout::GetPageInfo (int * minPage, int * maxPage, int * selPageFrom, int * selPageTo)
Definition at line 78 of file cbeditorprintout.cpp.
References wxScintilla::FormatRange(), g_printer, wxPrintData::GetOrientation(), wxPrintData::GetPaperId(), wxPrintDialogData::GetPrintData(), wxPrinter::GetPrintDialogData(), HasPage(), m_pageRect, m_pPageSelStart, m_printed, m_printRect, m_SelEnd, m_SelStart, m_TextControl, ScaleDC(), and wxLANDSCAPE.
HasPage()
bool cbEditorPrintout::HasPage (int page)
Definition at line 73 of file cbeditorprintout.cpp.
References m_printed, and m_SelEnd.
Referenced by GetPageInfo().
OnBeginDocument()
bool cbEditorPrintout::OnBeginDocument (int startPage, int endPage)
Definition at line 162 of file cbeditorprintout.cpp.
References _T, LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), and m_pPageSelStart.
OnPrintPage()
bool cbEditorPrintout::OnPrintPage (int page)
Definition at line 47 of file cbeditorprintout.cpp.
References _T, LogManager::DebugLog(), F(), wxScintilla::FormatRange(), Manager::Get(), Manager::GetLogManager(), m_pageRect, m_pPageSelStart, m_printed, m_printRect, m_SelEnd, m_TextControl, and ScaleDC().
ScaleDC()
bool cbEditorPrintout::ScaleDC (wxDC * dc) protected
Definition at line 177 of file cbeditorprintout.cpp.
Referenced by GetPageInfo(), and OnPrintPage().
Member Data Documentation
m_pageRect
wxRect cbEditorPrintout::m_pageRect protected
Definition at line 25 of file cbeditorprintout.h.
Referenced by GetPageInfo(), and OnPrintPage().
m_pPageSelStart
wxArrayInt* cbEditorPrintout::m_pPageSelStart protected
Definition at line 30 of file cbeditorprintout.h.
Referenced by cbEditorPrintout(), GetPageInfo(), OnBeginDocument(), OnPrintPage(), and ~cbEditorPrintout().
m_printed
int cbEditorPrintout::m_printed protected
Definition at line 27 of file cbeditorprintout.h.
Referenced by GetPageInfo(), HasPage(), and OnPrintPage().
m_printRect
wxRect cbEditorPrintout::m_printRect protected
Definition at line 26 of file cbeditorprintout.h.
Referenced by GetPageInfo(), and OnPrintPage().
m_SelEnd
int cbEditorPrintout::m_SelEnd protected
Definition at line 29 of file cbeditorprintout.h.
Referenced by cbEditorPrintout(), GetPageInfo(), HasPage(), and OnPrintPage().
m_SelStart
int cbEditorPrintout::m_SelStart protected
Definition at line 28 of file cbeditorprintout.h.
Referenced by cbEditorPrintout(), and GetPageInfo().
m_TextControl
cbStyledTextCtrl* cbEditorPrintout::m_TextControl protected
Definition at line 24 of file cbeditorprintout.h.
Referenced by GetPageInfo(), and OnPrintPage().
The documentation for this class was generated from the following files:
cbeditorprintout.h
cbeditorprintout.cpp