Code::Blocks: DebuggerSettingsDlg Class Reference
DebuggerSettingsDlg Class Reference
#include <debuggersettingsdlg.h>
Classes
struct Config
Public Member Functions
DebuggerSettingsDlg (wxWindow *parent)
virtual ~DebuggerSettingsDlg ()
bool CreateConfig (wxWindow *panel, cbDebuggerPlugin *plugin, const wxString &name)
void DeleteConfig (wxWindow *panel, cbDebuggerPlugin *plugin)
void ResetConfig (wxWindow *panel, cbDebuggerPlugin *plugin)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Types
typedef std::map< wxWindow *, Config > MapPanelToConfiguration
Private Member Functions
void OnPageChanged (wxNotebookEvent &event)
void OnOK (wxCommandEvent &event)
Private Attributes
wxTreebook * m_treebook
wxStaticText * m_activeInfo
MapPanelToConfiguration m_mapPanelToConfig
DebuggerSettingsCommonPanel * m_commonPanel
Static Private Attributes
static const long ID_LABEL_ACTIVE_INFO = wxNewId()
static const long ID_TREEBOOK = wxNewId()
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 23 of file debuggersettingsdlg.h.
Class Documentation
DebuggerSettingsDlg::Config
struct DebuggerSettingsDlg::Config
Definition at line 53 of file debuggersettingsdlg.h.
Class Members
cbDebuggerConfiguration * config
cbDebuggerPlugin * plugin
wxString pluginGUIName
Member Typedef Documentation
MapPanelToConfiguration
typedef std::map<wxWindow*, Config> DebuggerSettingsDlg::MapPanelToConfiguration private
Definition at line 60 of file debuggersettingsdlg.h.
Constructor & Destructor Documentation
DebuggerSettingsDlg()
DebuggerSettingsDlg::DebuggerSettingsDlg (wxWindow * parent)
Definition at line 35 of file debuggersettingsdlg.cpp.
References cbDebuggerConfiguration::Clone(), DebuggerSettingsDlg::Config::config, Manager::Get(), DebuggerManager::GetAllDebuggers(), DebuggerManager::PluginData::GetConfigurations(), Manager::GetDebuggerManager(), OnPageChanged(), DebuggerSettingsDlg::Config::plugin, and DebuggerSettingsDlg::Config::pluginGUIName.
~DebuggerSettingsDlg()
DebuggerSettingsDlg::~DebuggerSettingsDlg () virtual
Definition at line 107 of file debuggersettingsdlg.cpp.
References m_mapPanelToConfig.
Member Function Documentation
CreateConfig()
bool DebuggerSettingsDlg::CreateConfig (wxWindow * panel, cbDebuggerPlugin * plugin, const wxString & name)
Definition at line 189 of file debuggersettingsdlg.cpp.
References DebuggerSettingsDlg::Config::config, FindPageIndex(), cbDebuggerPlugin::GetGUIName(), cbDebuggerConfiguration::GetName(), cbDebuggerPlugin::LoadConfig(), m_mapPanelToConfig, m_treebook, cbDebuggerConfiguration::MakePanel(), DebuggerSettingsDlg::Config::plugin, DebuggerSettingsDlg::Config::pluginGUIName, and cbDebuggerConfiguration::SetName().
Referenced by DebuggerSettingsPanel::OnButtonCreate(), and ResetConfig().
DeleteConfig()
void DebuggerSettingsDlg::DeleteConfig (wxWindow * panel, cbDebuggerPlugin * plugin)
Definition at line 217 of file debuggersettingsdlg.cpp.
References cbAssert, cbMessageBox(), FindPageIndex(), m_mapPanelToConfig, m_treebook, and PlaceWindow().
Referenced by DebuggerSettingsPanel::OnButtonDelete().
OnOK()
void DebuggerSettingsDlg::OnOK (wxCommandEvent & event) private
Definition at line 117 of file debuggersettingsdlg.cpp.
References ConfigManager::DeleteSubPath(), ScriptBindings::EndModal(), Manager::Get(), DebuggerManager::GetActiveDebugger(), DebuggerManager::GetAllDebuggers(), ConfigManagerWrapper::GetBasepath(), cbDebuggerConfiguration::GetConfig(), Manager::GetConfigManager(), Manager::GetDebuggerManager(), DebuggerManager::GetLogger(), cbDebuggerConfiguration::GetName(), ConfigManagerWrapper::IsValid(), m_commonPanel, m_mapPanelToConfig, m_treebook, DebuggerManager::NewConfig(), DebuggerManager::RebuildAllConfigs(), DebuggerSettingsCommonPanel::SaveChanges(), cbDebuggerConfiguration::SaveChanges(), cbDebuggerConfiguration::SetConfig(), cbDebuggerPlugin::SetupLog(), and ConfigManager::Write().
OnPageChanged()
void DebuggerSettingsDlg::OnPageChanged (wxNotebookEvent & event) private
Definition at line 287 of file debuggersettingsdlg.cpp.
References m_activeInfo, and m_treebook.
Referenced by DebuggerSettingsDlg().
ResetConfig()
void DebuggerSettingsDlg::ResetConfig (wxWindow * panel, cbDebuggerPlugin * plugin)
Definition at line 263 of file debuggersettingsdlg.cpp.
References cbAssert, CreateConfig(), FindPageIndex(), m_mapPanelToConfig, and m_treebook.
Referenced by DebuggerSettingsPanel::OnButtonReset().
Member Data Documentation
ID_LABEL_ACTIVE_INFO
const long DebuggerSettingsDlg::ID_LABEL_ACTIVE_INFO = wxNewId() static private
Definition at line 48 of file debuggersettingsdlg.h.
ID_TREEBOOK
const long DebuggerSettingsDlg::ID_TREEBOOK = wxNewId() static private
Definition at line 49 of file debuggersettingsdlg.h.
m_activeInfo
wxStaticText* DebuggerSettingsDlg::m_activeInfo private
Definition at line 44 of file debuggersettingsdlg.h.
Referenced by OnPageChanged().
m_commonPanel
DebuggerSettingsCommonPanel* DebuggerSettingsDlg::m_commonPanel private
Definition at line 63 of file debuggersettingsdlg.h.
Referenced by OnOK().
m_mapPanelToConfig
MapPanelToConfiguration DebuggerSettingsDlg::m_mapPanelToConfig private
Definition at line 62 of file debuggersettingsdlg.h.
Referenced by CreateConfig(), DeleteConfig(), OnOK(), ResetConfig(), and ~DebuggerSettingsDlg().
m_treebook
wxTreebook* DebuggerSettingsDlg::m_treebook private
Definition at line 43 of file debuggersettingsdlg.h.
Referenced by CreateConfig(), DeleteConfig(), OnOK(), OnPageChanged(), and ResetConfig().
The documentation for this class was generated from the following files:
debuggersettingsdlg.h
debuggersettingsdlg.cpp