Code::Blocks: DebuggerConfiguration Class Reference
DebuggerConfiguration Class Reference
#include <debuggeroptionsdlg.h>
Public Types
enum Flags {
DisableInit, WatchFuncArgs, WatchLocals, WatchScriptPrinters,
CatchExceptions, EvalExpression, AddOtherProjectDirs, DoNotRun
}
Public Member Functions
DebuggerConfiguration (const ConfigManagerWrapper &config)
virtual cbDebuggerConfiguration * Clone () const
virtual wxPanel * MakePanel (wxWindow *parent)
virtual bool SaveChanges (wxPanel *panel)
bool GetFlag (Flags flag)
void SetFlag (Flags flag, bool value)
bool IsGDB ()
wxString GetDebuggerExecutable (bool expandMacro=true)
wxString GetUserArguments (bool expandMacro=true)
wxString GetDisassemblyFlavorCommand ()
wxString GetInitCommands ()
Public Member Functions inherited from cbDebuggerConfiguration
cbDebuggerConfiguration (const ConfigManagerWrapper &config)
virtual ~cbDebuggerConfiguration ()
void SetName (const wxString &name)
const wxString & GetName () const
const ConfigManagerWrapper & GetConfig () const
void SetConfig (const ConfigManagerWrapper &config)
void SetMenuId (long id)
long GetMenuId () const
Additional Inherited Members
Protected Member Functions inherited from cbDebuggerConfiguration
cbDebuggerConfiguration (const cbDebuggerConfiguration &o)
cbDebuggerConfiguration & operator= (const cbDebuggerConfiguration &)
Protected Attributes inherited from cbDebuggerConfiguration
ConfigManagerWrapper m_config
Member Enumeration Documentation
enum DebuggerConfiguration::Flags
Enumerator
DisableInit
WatchFuncArgs
WatchLocals
WatchScriptPrinters
CatchExceptions
EvalExpression
AddOtherProjectDirs
DoNotRun
Constructor & Destructor Documentation
DebuggerConfiguration::DebuggerConfiguration (const ConfigManagerWrapper & config) explicit
Referenced by Clone().
Member Function Documentation
cbDebuggerConfiguration * DebuggerConfiguration::Clone () const virtual
Implements cbDebuggerConfiguration.
References DebuggerConfiguration().
wxString DebuggerConfiguration::GetDebuggerExecutable (bool expandMacro = true)
References cbDetectDebuggerExecutable(), Manager::Get(), Manager::GetMacrosManager(), cbDebuggerConfiguration::m_config, ConfigManagerWrapper::Read(), and MacrosManager::ReplaceEnvVars().
Referenced by DebuggerGDB::DoDebug(), and MakePanel().
wxString DebuggerConfiguration::GetDisassemblyFlavorCommand ()
References cbDebuggerConfiguration::m_config, ConfigManagerWrapper::Read(), and ConfigManagerWrapper::ReadInt().
Referenced by GDB_driver::Prepare().
bool DebuggerConfiguration::GetFlag (Flags flag)
References AddOtherProjectDirs, CatchExceptions, DisableInit, DoNotRun, EvalExpression, cbDebuggerConfiguration::m_config, ConfigManagerWrapper::ReadBool(), WatchFuncArgs, WatchLocals, and WatchScriptPrinters.
Referenced by DebuggerGDB::DoWatches(), GDB_driver::GetCommandLine(), GDB_driver::InitializeScripting(), MakePanel(), DebuggerGDB::OnConfigurationChange(), DebuggerGDB::OnUpdateCatchThrow(), GDB_driver::Prepare(), DebuggerGDB::ShowValueTooltip(), CDB_driver::Start(), and GDB_driver::Start().
wxString DebuggerConfiguration::GetInitCommands ()
References cbDebuggerConfiguration::m_config, and ConfigManagerWrapper::Read().
Referenced by MakePanel(), and GDB_driver::Prepare().
wxString DebuggerConfiguration::GetUserArguments (bool expandMacro = true)
References Manager::Get(), Manager::GetMacrosManager(), cbDebuggerConfiguration::m_config, ConfigManagerWrapper::Read(), and MacrosManager::ReplaceEnvVars().
Referenced by MakePanel().
bool DebuggerConfiguration::IsGDB ()
References cbDebuggerConfiguration::m_config, and ConfigManagerWrapper::ReadInt().
Referenced by MakePanel(), DebuggerGDB::OnUpdateCatchThrow(), DebuggerState::StartDriver(), and DebuggerGDB::SupportsFeature().
wxPanel * DebuggerConfiguration::MakePanel (wxWindow * parent) virtual
Implements cbDebuggerConfiguration.
References AddOtherProjectDirs, CatchExceptions, DisableInit, DoNotRun, EvalExpression, GetDebuggerExecutable(), GetFlag(), GetInitCommands(), GetUserArguments(), IsGDB(), cbDebuggerConfiguration::m_config, ConfigManagerWrapper::Read(), ConfigManagerWrapper::ReadInt(), DebuggerConfigurationPanel::ValidateExecutablePath(), WatchFuncArgs, WatchLocals, and WatchScriptPrinters.
bool DebuggerConfiguration::SaveChanges (wxPanel * panel) virtual
Implements cbDebuggerConfiguration.
References cbDebuggerConfiguration::m_config, and ConfigManagerWrapper::Write().
void DebuggerConfiguration::SetFlag (Flags flag, bool value)
References AddOtherProjectDirs, CatchExceptions, DisableInit, DoNotRun, EvalExpression, cbDebuggerConfiguration::m_config, WatchFuncArgs, WatchLocals, WatchScriptPrinters, and ConfigManagerWrapper::Write().
Referenced by DebuggerGDB::OnCatchThrow().
The documentation for this class was generated from the following files:
debuggeroptionsdlg.h
debuggeroptionsdlg.cpp