Code::Blocks: IncrementalSelectIteratorIndexed Class Reference
IncrementalSelectIteratorIndexed Class Reference
#include <incremental_select_helper.h>
Public Member Functions
virtual ~IncrementalSelectIteratorIndexed ()
int GetFilteredCount () const override
void Reset () override
void AddIndex (int index) override
int GetUnfilteredIndex (int index) const override
Public Member Functions inherited from IncrementalSelectIterator
virtual ~IncrementalSelectIterator ()
virtual int GetTotalCount () const =0
virtual const wxString & GetItemFilterString (int index) const =0
virtual wxString GetDisplayText (int index, int column) const =0
virtual int GetColumnWidth (int column) const
virtual void CalcColumnWidth (wxListCtrl &list)
Protected Attributes
std::vector< int > m_indices
Detailed Description
Definition at line 42 of file incremental_select_helper.h.
Constructor & Destructor Documentation
~IncrementalSelectIteratorIndexed()
virtual IncrementalSelectIteratorIndexed::~IncrementalSelectIteratorIndexed () inline virtual
Definition at line 45 of file incremental_select_helper.h.
References IncrementalSelectIterator::AddIndex(), IncrementalSelectIterator::GetFilteredCount(), IncrementalSelectIterator::GetUnfilteredIndex(), and IncrementalSelectIterator::Reset().
Member Function Documentation
AddIndex()
void IncrementalSelectIteratorIndexed::AddIndex (int index) override virtual
Implements IncrementalSelectIterator.
Definition at line 40 of file incremental_select_helper.cpp.
GetFilteredCount()
int IncrementalSelectIteratorIndexed::GetFilteredCount () const override virtual
Implements IncrementalSelectIterator.
Definition at line 30 of file incremental_select_helper.cpp.
GetUnfilteredIndex()
int IncrementalSelectIteratorIndexed::GetUnfilteredIndex (int index) const override virtual
Implements IncrementalSelectIterator.
Definition at line 45 of file incremental_select_helper.cpp.
References wxNOT_FOUND.
Reset()
void IncrementalSelectIteratorIndexed::Reset () override virtual
Implements IncrementalSelectIterator.
Definition at line 35 of file incremental_select_helper.cpp.
Member Data Documentation
m_indices
std::vector<int> IncrementalSelectIteratorIndexed::m_indices protected
Definition at line 52 of file incremental_select_helper.h.
Referenced by GotoFunctionDlg::Iterator::GetDisplayText().
The documentation for this class was generated from the following files:
incremental_select_helper.h
incremental_select_helper.cpp