Code::Blocks: VirtualBuildTargetsDlg Class Reference
VirtualBuildTargetsDlg Class Reference
#include <virtualbuildtargetsdlg.h>
Public Member Functions
VirtualBuildTargetsDlg (wxWindow *parent, wxWindowID id, cbProject *project)
virtual ~VirtualBuildTargetsDlg ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void OnAddClick (wxCommandEvent &event)
void OnEditClick (wxCommandEvent &event)
void OnRemoveClick (wxCommandEvent &event)
void OnAliasesSelect (wxCommandEvent &event)
void OnTargetsToggled (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void SetVirtualTarget (const wxString &targetName)
void CheckTargets ()
Protected Attributes
wxCheckListBox * lstTargets
wxButton * btnEdit
wxButton * btnRemove
wxButton * btnAdd
wxListBox * lstAliases
cbProject * m_pProject
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 24 of file virtualbuildtargetsdlg.h.
Constructor & Destructor Documentation
VirtualBuildTargetsDlg()
VirtualBuildTargetsDlg::VirtualBuildTargetsDlg (wxWindow * parent, wxWindowID id, cbProject * project)
Definition at line 33 of file virtualbuildtargetsdlg.cpp.
References OnAddClick(), OnAliasesSelect(), OnEditClick(), OnRemoveClick(), and OnTargetsToggled().
~VirtualBuildTargetsDlg()
VirtualBuildTargetsDlg::~VirtualBuildTargetsDlg () virtual
Definition at line 65 of file virtualbuildtargetsdlg.cpp.
Member Function Documentation
CheckTargets()
void VirtualBuildTargetsDlg::CheckTargets () protected
Definition at line 97 of file virtualbuildtargetsdlg.cpp.
References cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompileTargetBase::GetTitle(), cbProject::GetVirtualBuildTargetGroup(), lstAliases, lstTargets, and m_pProject.
Referenced by OnAddClick(), OnAliasesSelect(), and OnRemoveClick().
OnAddClick()
void VirtualBuildTargetsDlg::OnAddClick (wxCommandEvent & event) protected
Definition at line 116 of file virtualbuildtargetsdlg.cpp.
References cbGetTextFromUser(), cbMessageBox(), CheckTargets(), cbProject::GetBuildTarget(), lstAliases, and m_pProject.
Referenced by VirtualBuildTargetsDlg().
OnAliasesSelect()
void VirtualBuildTargetsDlg::OnAliasesSelect (wxCommandEvent & event) protected
Definition at line 186 of file virtualbuildtargetsdlg.cpp.
References CheckTargets().
Referenced by VirtualBuildTargetsDlg().
OnEditClick()
void VirtualBuildTargetsDlg::OnEditClick (wxCommandEvent & event) protected
Definition at line 145 of file virtualbuildtargetsdlg.cpp.
References cbGetTextFromUser(), cbMessageBox(), cbProject::GetBuildTarget(), lstAliases, m_pProject, cbProject::RemoveVirtualBuildTarget(), and SetVirtualTarget().
Referenced by VirtualBuildTargetsDlg().
OnRemoveClick()
void VirtualBuildTargetsDlg::OnRemoveClick (wxCommandEvent & event) protected
Definition at line 176 of file virtualbuildtargetsdlg.cpp.
References cbMessageBox(), CheckTargets(), lstAliases, m_pProject, and cbProject::RemoveVirtualBuildTarget().
Referenced by VirtualBuildTargetsDlg().
OnTargetsToggled()
void VirtualBuildTargetsDlg::OnTargetsToggled (wxCommandEvent & event) protected
Definition at line 191 of file virtualbuildtargetsdlg.cpp.
References lstAliases, and SetVirtualTarget().
Referenced by VirtualBuildTargetsDlg().
OnUpdateUI()
void VirtualBuildTargetsDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 108 of file virtualbuildtargetsdlg.cpp.
References btnEdit, btnRemove, lstAliases, and lstTargets.
SetVirtualTarget()
void VirtualBuildTargetsDlg::SetVirtualTarget (const wxString & targetName) protected
Definition at line 71 of file virtualbuildtargetsdlg.cpp.
References cbMessageBox(), cbProject::DefineVirtualBuildTarget(), lstTargets, and m_pProject.
Referenced by OnEditClick(), and OnTargetsToggled().
Member Data Documentation
btnAdd
wxButton* VirtualBuildTargetsDlg::btnAdd protected
Definition at line 50 of file virtualbuildtargetsdlg.h.
btnEdit
wxButton* VirtualBuildTargetsDlg::btnEdit protected
Definition at line 48 of file virtualbuildtargetsdlg.h.
Referenced by OnUpdateUI().
btnRemove
wxButton* VirtualBuildTargetsDlg::btnRemove protected
Definition at line 49 of file virtualbuildtargetsdlg.h.
Referenced by OnUpdateUI().
lstAliases
wxListBox* VirtualBuildTargetsDlg::lstAliases protected
Definition at line 51 of file virtualbuildtargetsdlg.h.
Referenced by CheckTargets(), OnAddClick(), OnEditClick(), OnRemoveClick(), OnTargetsToggled(), and OnUpdateUI().
lstTargets
wxCheckListBox* VirtualBuildTargetsDlg::lstTargets protected
Definition at line 47 of file virtualbuildtargetsdlg.h.
Referenced by CheckTargets(), OnUpdateUI(), and SetVirtualTarget().
m_pProject
cbProject* VirtualBuildTargetsDlg::m_pProject protected
Definition at line 56 of file virtualbuildtargetsdlg.h.
Referenced by CheckTargets(), OnAddClick(), OnEditClick(), OnRemoveClick(), and SetVirtualTarget().
The documentation for this class was generated from the following files:
virtualbuildtargetsdlg.h
virtualbuildtargetsdlg.cpp