Code::Blocks: ScriptSecurityWarningDlg Class Reference
ScriptSecurityWarningDlg Class Reference
#include <scriptsecuritywarningdlg.h>
Public Member Functions
ScriptSecurityWarningDlg (wxWindow *parent, const wxString &operation, const wxString &command)
~ScriptSecurityWarningDlg () override
ScriptSecurityResponse GetResponse ()
void EndModal (int retCode) override
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Detailed Description
Definition at line 20 of file scriptsecuritywarningdlg.h.
Constructor & Destructor Documentation
ScriptSecurityWarningDlg()
ScriptSecurityWarningDlg::ScriptSecurityWarningDlg (wxWindow * parent, const wxString & operation, const wxString & command)
Definition at line 23 of file scriptsecuritywarningdlg.cpp.
References _(), _T, wxXmlResource::Get(), wxSystemSettings::GetColour(), wxXmlResource::LoadObject(), and wxSYS_COLOUR_BTNFACE.
~ScriptSecurityWarningDlg()
ScriptSecurityWarningDlg::~ScriptSecurityWarningDlg () override
Definition at line 36 of file scriptsecuritywarningdlg.cpp.
Member Function Documentation
EndModal()
void ScriptSecurityWarningDlg::EndModal (int retCode) override
Definition at line 46 of file scriptsecuritywarningdlg.cpp.
References ScriptBindings::EndModal().
GetResponse()
ScriptSecurityResponse ScriptSecurityWarningDlg::GetResponse ()
Definition at line 41 of file scriptsecuritywarningdlg.cpp.
Referenced by ScriptBindings::IOLib::SecurityAllows().
The documentation for this class was generated from the following files:
scriptsecuritywarningdlg.h
scriptsecuritywarningdlg.cpp