Code::Blocks: DebuggerSettingsCommonPanel Class Reference
DebuggerSettingsCommonPanel Class Reference
#include <debuggersettingscommonpanel.h>
Public Member Functions
DebuggerSettingsCommonPanel (wxWindow *parent)
virtual ~DebuggerSettingsCommonPanel ()
void SaveChanges ()
Private Member Functions
void UpdateValueTooltipFont ()
void OnChooseFontClick (wxCommandEvent &event)
Private Attributes
wxStaticText * m_valueTooltipLabel
wxCheckBox * m_autoBuild
wxChoice * m_perspective
wxCheckBox * m_requireCtrlForTooltips
wxCheckBox * m_jumpOnDoubleClick
wxCheckBox * m_autoSwitch
wxCheckBox * m_debuggersLog
wxString m_valueTooltipFontInfo
Static Private Attributes
static const long ID_AUTOBUILD = wxNewId()
static const long ID_AUTOSWITCH = wxNewId()
static const long ID_DEBUGGERS_LOG = wxNewId()
static const long ID_JUMP_ON_DOUBLE_CLICK = wxNewId()
static const long ID_REQUIRE_CTRL_FOR_TOOLTIPS = wxNewId()
static const long ID_VALUE_TOOLTIP_LABEL = wxNewId()
static const long ID_BUTTON_CHOOSE_FONT = wxNewId()
static const long ID_CHOICE_PERSPECTIVE = wxNewId()
Detailed Description
Definition at line 17 of file debuggersettingscommonpanel.h.
Constructor & Destructor Documentation
DebuggerSettingsCommonPanel()
DebuggerSettingsCommonPanel::DebuggerSettingsCommonPanel (wxWindow * parent)
Definition at line 36 of file debuggersettingscommonpanel.cpp.
References _(), _T, wxBoxSizer::Add(), cbDebuggerCommonConfig::AutoBuild, cbDebuggerCommonConfig::AutoSwitchFrame, wxBoxSizer::Fit(), cbDebuggerCommonConfig::GetFlag(), cbDebuggerCommonConfig::GetPerspective(), cbDebuggerCommonConfig::GetValueTooltipFont(), cbDebuggerCommonConfig::JumpOnDoubleClick, OnChooseFontClick(), cbDebuggerCommonConfig::RequireCtrlForTooltips, wxBoxSizer::SetSizeHints(), cbDebuggerCommonConfig::ShowDebuggersLog, wxALIGN_CENTER_VERTICAL, wxALIGN_LEFT, wxALIGN_TOP, wxALL, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEXPAND, wxHORIZONTAL, wxID_ANY, wxLEFT, wxRIGHT, wxTAB_TRAVERSAL, wxTOP, and wxVERTICAL.
~DebuggerSettingsCommonPanel()
DebuggerSettingsCommonPanel::~DebuggerSettingsCommonPanel () virtual
Definition at line 107 of file debuggersettingscommonpanel.cpp.
Member Function Documentation
OnChooseFontClick()
void DebuggerSettingsCommonPanel::OnChooseFontClick (wxCommandEvent & event) private
Definition at line 125 of file debuggersettingscommonpanel.cpp.
References wxNativeFontInfo::FromString(), wxFontData::GetChosenFont(), wxFontDialog::GetFontData(), wxFont::GetNativeFontInfo(), m_valueTooltipFontInfo, PlaceWindow(), wxFontData::SetInitialFont(), wxFontDialog::ShowModal(), wxNativeFontInfo::ToString(), UpdateValueTooltipFont(), and wxID_OK.
Referenced by DebuggerSettingsCommonPanel().
SaveChanges()
void DebuggerSettingsCommonPanel::SaveChanges ()
Definition at line 113 of file debuggersettingscommonpanel.cpp.
References cbDebuggerCommonConfig::AutoBuild, cbDebuggerCommonConfig::AutoSwitchFrame, wxChoice::GetSelection(), wxCheckBox::GetValue(), cbDebuggerCommonConfig::JumpOnDoubleClick, m_autoBuild, m_autoSwitch, m_debuggersLog, m_jumpOnDoubleClick, m_perspective, m_requireCtrlForTooltips, m_valueTooltipFontInfo, cbDebuggerCommonConfig::RequireCtrlForTooltips, cbDebuggerCommonConfig::SetFlag(), cbDebuggerCommonConfig::SetPerspective(), cbDebuggerCommonConfig::SetValueTooltipFont(), and cbDebuggerCommonConfig::ShowDebuggersLog.
Referenced by DebuggerSettingsDlg::OnOK().
UpdateValueTooltipFont()
void DebuggerSettingsCommonPanel::UpdateValueTooltipFont () private
Definition at line 141 of file debuggersettingscommonpanel.cpp.
References wxNativeFontInfo::FromString(), m_valueTooltipFontInfo, and m_valueTooltipLabel.
Referenced by OnChooseFontClick().
Member Data Documentation
ID_AUTOBUILD
const long DebuggerSettingsCommonPanel::ID_AUTOBUILD = wxNewId() static private
Definition at line 44 of file debuggersettingscommonpanel.h.
ID_AUTOSWITCH
const long DebuggerSettingsCommonPanel::ID_AUTOSWITCH = wxNewId() static private
Definition at line 45 of file debuggersettingscommonpanel.h.
ID_BUTTON_CHOOSE_FONT
const long DebuggerSettingsCommonPanel::ID_BUTTON_CHOOSE_FONT = wxNewId() static private
Definition at line 50 of file debuggersettingscommonpanel.h.
ID_CHOICE_PERSPECTIVE
const long DebuggerSettingsCommonPanel::ID_CHOICE_PERSPECTIVE = wxNewId() static private
Definition at line 51 of file debuggersettingscommonpanel.h.
ID_DEBUGGERS_LOG
const long DebuggerSettingsCommonPanel::ID_DEBUGGERS_LOG = wxNewId() static private
Definition at line 46 of file debuggersettingscommonpanel.h.
ID_JUMP_ON_DOUBLE_CLICK
const long DebuggerSettingsCommonPanel::ID_JUMP_ON_DOUBLE_CLICK = wxNewId() static private
Definition at line 47 of file debuggersettingscommonpanel.h.
ID_REQUIRE_CTRL_FOR_TOOLTIPS
const long DebuggerSettingsCommonPanel::ID_REQUIRE_CTRL_FOR_TOOLTIPS = wxNewId() static private
Definition at line 48 of file debuggersettingscommonpanel.h.
ID_VALUE_TOOLTIP_LABEL
const long DebuggerSettingsCommonPanel::ID_VALUE_TOOLTIP_LABEL = wxNewId() static private
Definition at line 49 of file debuggersettingscommonpanel.h.
m_autoBuild
wxCheckBox* DebuggerSettingsCommonPanel::m_autoBuild private
Definition at line 32 of file debuggersettingscommonpanel.h.
Referenced by SaveChanges().
m_autoSwitch
wxCheckBox* DebuggerSettingsCommonPanel::m_autoSwitch private
Definition at line 36 of file debuggersettingscommonpanel.h.
Referenced by SaveChanges().
m_debuggersLog
wxCheckBox* DebuggerSettingsCommonPanel::m_debuggersLog private
Definition at line 37 of file debuggersettingscommonpanel.h.
Referenced by SaveChanges().
m_jumpOnDoubleClick
wxCheckBox* DebuggerSettingsCommonPanel::m_jumpOnDoubleClick private
Definition at line 35 of file debuggersettingscommonpanel.h.
Referenced by SaveChanges().
m_perspective
wxChoice* DebuggerSettingsCommonPanel::m_perspective private
Definition at line 33 of file debuggersettingscommonpanel.h.
Referenced by SaveChanges().
m_requireCtrlForTooltips
wxCheckBox* DebuggerSettingsCommonPanel::m_requireCtrlForTooltips private
Definition at line 34 of file debuggersettingscommonpanel.h.
Referenced by SaveChanges().
m_valueTooltipFontInfo
wxString DebuggerSettingsCommonPanel::m_valueTooltipFontInfo private
Definition at line 40 of file debuggersettingscommonpanel.h.
Referenced by OnChooseFontClick(), SaveChanges(), and UpdateValueTooltipFont().
m_valueTooltipLabel
wxStaticText* DebuggerSettingsCommonPanel::m_valueTooltipLabel private
Definition at line 31 of file debuggersettingscommonpanel.h.
Referenced by UpdateValueTooltipFont().
The documentation for this class was generated from the following files:
debuggersettingscommonpanel.h
debuggersettingscommonpanel.cpp