Code::Blocks: BlockAllocated< T, pool_size, debug > Class Template Reference
BlockAllocated< T, pool_size, debug > Class Template Reference
#include <blockallocated.h>
Public Member Functions
void * operator new (cb_unused size_t size)
void operator delete (void *ptr)
Static Private Attributes
static BlockAllocator< T,
pool_size, debug > allocator
Member Function Documentation
template<class T , unsigned int pool_size, const bool debug = 0> void BlockAllocated< T, pool_size, debug >::operator delete (void * ptr) inline
References BlockAllocator< T, pool_size, debug >::Delete(), and ParserConsts::ptr().
template<class T , unsigned int pool_size, const bool debug = 0> void* BlockAllocated< T, pool_size, debug >::operator new (cb_unused size_t size) inline
References BlockAllocator< T, pool_size, debug >::New().
Member Data Documentation
template<class T , unsigned int pool_size, const bool debug = 0> BlockAllocator< T, pool_size, debug > BlockAllocated< T, pool_size, debug >::allocator static private
The documentation for this class was generated from the following file:
blockallocated.h