Code::Blocks: Compiler Class Reference
Compiler Class Reference abstract
Abstract base class for compilers.
#include <compiler.h>
Classes
struct MirrorSettings
Public Member Functions
Compiler (const wxString &name, const wxString &ID, const wxString &parentID=wxEmptyString, int weight=50)
virtual ~Compiler ()
virtual bool IsValid ()
Check if the compiler is actually valid (installed).
virtual CompilerLineType CheckForWarningsAndErrors (const wxString &line)
Check if the supplied string is a compiler warning/error.
virtual wxString GetLastErrorFilename ()
Returns warning/error filename.
virtual wxString GetLastErrorLine ()
Returns warning/error line number (as a string).
virtual wxString GetLastError ()
Returns warning/error actual string.
virtual const wxString & GetName () const
Get the compiler's name.
virtual const wxString & GetMasterPath () const
Get the compiler's master path (must contain "bin", "include" and "lib")
virtual const wxArrayString & GetExtraPaths () const
Get the compiler's extra paths.
virtual const CompilerPrograms & GetPrograms () const
Get the compiler's programs.
virtual const CompilerSwitches & GetSwitches () const
Get the compiler's generic switches.
virtual const CompilerOptions & GetOptions () const
Get the compiler's options.
virtual const wxString & GetCommand (CommandType ct, const wxString &fileExtension=wxEmptyString) const
Get a command based on CommandType.
virtual const CompilerTool * GetCompilerTool (CommandType ct, const wxString &fileExtension=wxEmptyString) const
Get a compiler tool based on CommandType.
virtual CompilerToolsVector & GetCommandToolsVector (CommandType ct)
Get a command tool vector based on CommandType (used by advanced compiler dialog)
virtual const RegExArray & GetRegExArray ()
Get the array of regexes used in errors/warnings recognition.
virtual void LoadDefaultRegExArray (bool globalPrecedence=false)
Load the default (preset) array of regexes used in errors/warnings recognition.
virtual void SetName (const wxString &name)
Set the compiler's name.
virtual void SetMasterPath (const wxString &path)
Set the compiler's master path (must contain "bin", "include" and "lib")
virtual void SetExtraPaths (const wxArrayString &paths)
Set the compiler's extra paths.
virtual void SetPrograms (const CompilerPrograms &programs)
Set the compiler's programs.
virtual void SetSwitches (const CompilerSwitches &switches)
Set the compiler's generic switches.
virtual void SetOptions (const CompilerOptions &options)
Set the compiler's options.
virtual void SetRegExArray (const RegExArray &regexes)
Set the array of regexes used in errors/warnings recognition.
virtual void SaveSettings (const wxString &baseKey)
Save settings.
virtual void LoadSettings (const wxString &baseKey)
Load settings.
virtual void Reset ()
Reset settings to defaults.
virtual void ReloadOptions ()
Reload option flags (for copied compilers).
virtual AutoDetectResult AutoDetectInstallationDir ()=0
Try to auto-detect the compiler's installation directory.
const wxString & GetID () const
Get this compiler's unique ID.
const wxString & GetParentID () const
Get this compiler's parent's unique ID.
virtual void SetVersionString ()
Set the compiler version string.
const wxString GetVersionString () const
Get the compiler version string.
virtual CompilerCommandGenerator * GetCommandGenerator (cbProject *project)
This is to be overridden, if compiler needs to alter the default command line generation.
void SetCOnlyFlags (const wxString &flags)
void SetCPPOnlyFlags (const wxString &flags)
const wxString & GetCOnlyFlags ()
const wxString & GetCPPOnlyFlags ()
bool WithMultiLineMsg ()
Do compiler writes multi-line messages?
Public Member Functions inherited from CompileOptionsBase
CompileOptionsBase ()
virtual ~CompileOptionsBase ()
virtual void AddPlatform (int platform)
virtual void RemovePlatform (int platform)
virtual void SetPlatforms (int platforms)
virtual int GetPlatforms () const
virtual bool SupportsCurrentPlatform () const
virtual void SetLinkerOptions (const wxArrayString &linkerOpts)
virtual const wxArrayString & GetLinkerOptions () const
virtual void AddLinkerOption (const wxString &option)
virtual void ReplaceLinkerOption (const wxString &option, const wxString &new_option)
virtual void RemoveLinkerOption (const wxString &option)
virtual void SetLinkLibs (const wxArrayString &linkLibs)
virtual const wxArrayString & GetLinkLibs () const
virtual void AddLinkLib (const wxString &option)
virtual void ReplaceLinkLib (const wxString &option, const wxString &new_option)
virtual void RemoveLinkLib (const wxString &option)
virtual void SetCompilerOptions (const wxArrayString &compilerOpts)
virtual const wxArrayString & GetCompilerOptions () const
virtual void AddCompilerOption (const wxString &option)
virtual void ReplaceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveCompilerOption (const wxString &option)
virtual void SetResourceCompilerOptions (const wxArrayString &resourceCompilerOpts)
virtual const wxArrayString & GetResourceCompilerOptions () const
virtual void AddResourceCompilerOption (const wxString &option)
virtual void ReplaceResourceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveResourceCompilerOption (const wxString &option)
virtual void SetIncludeDirs (const wxArrayString &includeDirs)
virtual const wxArrayString & GetIncludeDirs () const
virtual void AddIncludeDir (const wxString &option)
virtual void ReplaceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveIncludeDir (const wxString &option)
virtual void SetResourceIncludeDirs (const wxArrayString &resIncludeDirs)
virtual const wxArrayString & GetResourceIncludeDirs () const
virtual void AddResourceIncludeDir (const wxString &option)
virtual void ReplaceResourceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveResourceIncludeDir (const wxString &option)
virtual void SetLibDirs (const wxArrayString &libDirs)
virtual const wxArrayString & GetLibDirs () const
virtual void AddLibDir (const wxString &option)
virtual void ReplaceLibDir (const wxString &option, const wxString &new_option)
virtual void RemoveLibDir (const wxString &option)
virtual void SetCommandsBeforeBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsBeforeBuild () const
virtual void AddCommandsBeforeBuild (const wxString &command)
virtual void RemoveCommandsBeforeBuild (const wxString &command)
virtual void SetCommandsAfterBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsAfterBuild () const
virtual void AddCommandsAfterBuild (const wxString &command)
virtual void RemoveCommandsAfterBuild (const wxString &command)
virtual void SetBuildScripts (const wxArrayString &scripts)
virtual const wxArrayString & GetBuildScripts () const
virtual void AddBuildScript (const wxString &script)
virtual void RemoveBuildScript (const wxString &script)
virtual bool GetModified () const
virtual void SetModified (bool modified)
virtual bool GetAlwaysRunPostBuildSteps () const
virtual void SetAlwaysRunPostBuildSteps (bool always)
virtual bool SetVar (const wxString &key, const wxString &value, bool onlyIfExists=false)
virtual bool UnsetVar (const wxString &key)
virtual void UnsetAllVars ()
virtual bool HasVar (const wxString &key) const
virtual const wxString & GetVar (const wxString &key) const
virtual const StringHash & GetAllVars () const
Static Public Attributes
static const wxString FilePathWithSpaces = _T("[][{}() \t#%$~[:alnum:]&_:+/\\.-]+")
static wxString CommandTypeDescriptions [ctCount]
Get the command type descriptions (used in advanced compiler options)
Protected Member Functions
Compiler (const Compiler &other)
virtual Compiler * CreateCopy ()=0
Implement this in new compilers, to return a new copy.
bool IsUniqueID (const wxString &ID)
void MakeValidID ()
void LoadDefaultOptions (const wxString &name, int recursion=0)
void LoadRegExArray (const wxString &name, bool globalPrecedence=false, int recursion=0)
bool EvalXMLCondition (const wxXmlNode *node)
wxString GetExecName (const wxString &name)
void MirrorCurrentSettings ()
Protected Attributes
wxString m_Name
wxString m_MasterPath
wxArrayString m_ExtraPaths
CompilerToolsVector m_Commands [ctCount]
CompilerPrograms m_Programs
CompilerSwitches m_Switches
CompilerOptions m_Options
RegExArray m_RegExes
wxString m_ErrorFilename
wxString m_ErrorLine
wxString m_Error
wxString m_VersionString
wxString m_SortOptions [2]
int m_Weight
bool m_MultiLineMessages
Protected Attributes inherited from CompileOptionsBase
int m_Platform
wxArrayString m_LinkerOptions
wxArrayString m_LinkLibs
wxArrayString m_CompilerOptions
wxArrayString m_ResourceCompilerOptions
wxArrayString m_IncludeDirs
wxArrayString m_ResIncludeDirs
wxArrayString m_LibDirs
wxArrayString m_CmdsBefore
wxArrayString m_CmdsAfter
wxArrayString m_Scripts
bool m_Modified
bool m_AlwaysRunPostCmds
StringHash m_Vars
Private Attributes
wxString m_ID
wxString m_ParentID
bool m_Valid
bool m_NeedValidityCheck
MirrorSettings m_Mirror
bool m_Mirrored
Static Private Attributes
static wxArrayString m_CompilerIDs
Friends
class CompilerFactory
Detailed Description
Abstract base class for compilers.
Create a derived class and add it in compilerfactory.cpp
Definition at line 274 of file compiler.h.
Class Documentation
Compiler::MirrorSettings
struct Compiler::MirrorSettings
Definition at line 429 of file compiler.h.
Class Members
wxArrayString CmdsAfter
wxArrayString CmdsBefore
CompilerToolsVector Commands[ctCount]
wxArrayString CompilerOptions_
wxArrayString ExtraPaths
wxArrayString IncludeDirs
wxArrayString LibDirs
wxArrayString LinkerOptions
wxArrayString LinkLibs
wxString MasterPath
wxString Name
CompilerOptions Options
CompilerPrograms Programs
RegExArray RegExes
wxArrayString ResIncludeDirs
wxArrayString ResourceCompilerOptions
wxString SortOptions[2]
CompilerSwitches Switches
Constructor & Destructor Documentation
Compiler() [1/2]
Compiler::Compiler (const wxString & name, const wxString & ID, const wxString & parentID = wxEmptyString, int weight = 50)
Definition at line 91 of file compiler.cpp.
References LogManager::DebugLog(), F(), CompilerSwitches::forceFwdSlashes, Manager::Get(), Manager::GetLogManager(), m_Name, m_RegExes, m_Switches, m_VersionString, m_Weight, MakeValidID(), and CompilerSwitches::supportsPCH.
~Compiler()
Compiler::~Compiler () virtual
Definition at line 152 of file compiler.cpp.
Compiler() [2/2]
Compiler::Compiler (const Compiler & other) protected
Definition at line 111 of file compiler.cpp.
References ctCount, CompileOptionsBase::m_CmdsAfter, CompileOptionsBase::m_CmdsBefore, m_Commands, CompileOptionsBase::m_CompilerOptions, m_ExtraPaths, m_ID, CompileOptionsBase::m_IncludeDirs, CompileOptionsBase::m_LibDirs, CompileOptionsBase::m_LinkerOptions, CompileOptionsBase::m_LinkLibs, m_MasterPath, m_MultiLineMessages, m_Name, m_NeedValidityCheck, m_Options, m_Programs, m_RegExes, CompileOptionsBase::m_ResIncludeDirs, m_SortOptions, m_Switches, m_Valid, m_VersionString, m_Weight, MakeUniqueArray(), and MakeValidID().
Member Function Documentation
AutoDetectInstallationDir()
virtual AutoDetectResult Compiler::AutoDetectInstallationDir () pure virtual
Try to auto-detect the compiler's installation directory.
Implemented in CompilerICC, CompilerMINGW, CompilerG95, CompilerCYGWIN, CompilerGDC, CompilerGNUARM, CompilerGNUFortran, CompilerIAR, CompilerKeilC51, CompilerMSVC, CompilerMSVC10, CompilerMSVC8, CompilerOW, CompilerLCC, and CompilerXML.
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), and AutoDetectCompilers::AutoDetectCompilers().
CheckForWarningsAndErrors()
CompilerLineType Compiler::CheckForWarningsAndErrors (const wxString & line) virtual
Check if the supplied string is a compiler warning/error.
Definition at line 741 of file compiler.cpp.
References cltNormal, RegExStruct::filename, RegExStruct::GetRegEx(), RegExStruct::HasRegEx(), RegExStruct::line, RegExStruct::lt, m_Error, m_ErrorFilename, m_ErrorLine, m_MultiLineMessages, m_RegExes, RegExStruct::msg, and UnixFilename().
Referenced by CompilerGCC::AddOutputLine(), and AdvancedCompilerOptionsDlg::OnRegexTest().
CreateCopy()
virtual Compiler* Compiler::CreateCopy () protected pure virtual
Implement this in new compilers, to return a new copy.
Implemented in CompilerKeilCX51, CompilerICC, CompilerMINGW, CompilerOW, CompilerG95, CompilerKeilC51, CompilerMSVC10, CompilerCYGWIN, CompilerGDC, CompilerGNUARM, CompilerGNUFortran, CompilerIAR, CompilerMSVC, CompilerMSVC8, CompilerLCC, and CompilerXML.
Referenced by CompilerFactory::CreateCompilerCopy().
EvalXMLCondition()
bool Compiler::EvalXMLCondition (const wxXmlNode * node) protected
Definition at line 1147 of file compiler.cpp.
References ConfigManager::Exists(), Manager::Get(), GetArrayFromString(), Manager::GetConfigManager(), GetExecName(), GetStringFromArray(), m_ID, m_ParentID, MakeUniqueArray(), and ConfigManager::Read().
Referenced by CompilerXML::AutoDetectInstallationDir(), LoadDefaultOptions(), and LoadRegExArray().
GetCommand()
const wxString & Compiler::GetCommand (CommandType ct, const wxString & fileExtension = wxEmptyString) const virtual
Get a command based on CommandType.
Parameters
ct The command type to process
fileExtension the file's extension (no leading dot)
Definition at line 273 of file compiler.cpp.
References EmptyString, and m_Commands.
Referenced by DirectCommands::GetCompileSingleFileCommand(), DirectCommands::GetTargetLinkCommands(), and ProjectFileOptionsDlg::UpdateBuildCommand().
GetCommandGenerator()
CompilerCommandGenerator * Compiler::GetCommandGenerator (cbProject * project) virtual
This is to be overridden, if compiler needs to alter the default command line generation.
Reimplemented in CompilerMINGW, and CompilerOW.
Definition at line 266 of file compiler.cpp.
References CompilerCommandGenerator::Init().
Referenced by NativeParser::AddCompilerDirs(), cbGetDynamicLinkerPathForTarget(), and DirectCommands::DirectCommands().
GetCommandToolsVector()
virtual CompilerToolsVector& Compiler::GetCommandToolsVector (CommandType ct) inline virtual
Get a command tool vector based on CommandType (used by advanced compiler dialog)
Definition at line 312 of file compiler.h.
Referenced by CompilerOptionsDlg::DoSaveCompilerDefinition(), AdvancedCompilerOptionsDlg::ReadCompilerOptions(), and AdvancedCompilerOptionsDlg::WriteCompilerOptions().
GetCompilerTool()
const CompilerTool * Compiler::GetCompilerTool (CommandType ct, const wxString & fileExtension = wxEmptyString) const virtual
Get a compiler tool based on CommandType.
Definition at line 302 of file compiler.cpp.
References m_Commands.
Referenced by cbProject::AddFile(), and DirectCommands::GetCompileFileCommand().
GetCOnlyFlags()
const wxString& Compiler::GetCOnlyFlags () inline
Definition at line 375 of file compiler.h.
Referenced by CompilerOptionsDlg::DoSaveCompilerDefinition(), CompilerCommandGenerator::GenerateCommandLine(), LoadDefaultOptions(), CompilerOptionsDlg::OnFlagsPopup(), and SaveSettings().
GetCPPOnlyFlags()
const wxString& Compiler::GetCPPOnlyFlags () inline
Definition at line 376 of file compiler.h.
Referenced by CompilerOptionsDlg::DoSaveCompilerDefinition(), CompilerCommandGenerator::GenerateCommandLine(), LoadDefaultOptions(), CompilerOptionsDlg::OnFlagsPopup(), and SaveSettings().
GetExecName()
wxString Compiler::GetExecName (const wxString & name) protected
Definition at line 1238 of file compiler.cpp.
References CompilerPrograms::C, CompilerPrograms::CPP, CompilerPrograms::LD, CompilerPrograms::LIB, m_Programs, CompilerPrograms::MAKE, and CompilerPrograms::WINDRES.
Referenced by CompilerXML::AutoDetectInstallationDir(), and EvalXMLCondition().
GetExtraPaths()
virtual const wxArrayString& Compiler::GetExtraPaths () const inline virtual
Get the compiler's extra paths.
Definition at line 297 of file compiler.h.
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), CompilerICC::AutoDetectInstallationDir(), CompilerOptionsDlg::DoFillCompilerPrograms(), and CompilerGCC::SetupEnvironment().
GetID()
const wxString& Compiler::GetID () const inline
Get this compiler's unique ID.
Definition at line 351 of file compiler.h.
Referenced by NativeParser::AddCompilerIncludeDirsToParser(), AutoDetectCompilers::AutoDetectCompilers(), CompilerXML::AutoDetectInstallationDir(), CompilerOptionsDlg::CompilerChanged(), ScriptBindings::CompilerFactory_GetCompilerIDByName(), CompilerFactory::CompilerInheritsFrom(), CompilerFactory::CreateCompilerCopy(), CompilerOptionsDlg::DoSaveCompilerDefinition(), Wizard::FillCompilerControl(), DebuggerManager::FindTargetsDebugger(), DirectCommands::GetCompileFileCommand(), Wiz::GetCompilerFromCombobox(), WizCompilerPanel::GetCompilerID(), WizBuildTargetPanel::GetCompilerID(), CompilerFactory::GetDefaultCompilerID(), LoadDefaultRegExArray(), CompilerOptionsDlg::OnResetCompilerClick(), ReloadOptions(), CompilerFactory::RemoveCompiler(), CompilerLCC::Reset(), Reset(), ProjectFileOptionsDlg::SaveBuildCommandSelection(), CompilerMINGW::SetVersionString(), ProjectFileOptionsDlg::UpdateBuildCommand(), and CompilerOptionsDlg::UpdateCompilerForTargets().
GetLastError()
virtual wxString Compiler::GetLastError () inline virtual
Returns warning/error actual string.
Use it after a call to CheckForWarningsAndErrors()
Definition at line 291 of file compiler.h.
Referenced by CompilerGCC::AddOutputLine(), and AdvancedCompilerOptionsDlg::OnRegexTest().
GetLastErrorFilename()
virtual wxString Compiler::GetLastErrorFilename () inline virtual
Returns warning/error filename.
Use it after a call to CheckForWarningsAndErrors()
Definition at line 287 of file compiler.h.
Referenced by CompilerGCC::AddOutputLine(), and AdvancedCompilerOptionsDlg::OnRegexTest().
GetLastErrorLine()
virtual wxString Compiler::GetLastErrorLine () inline virtual
Returns warning/error line number (as a string).
Use it after a call to CheckForWarningsAndErrors()
Definition at line 289 of file compiler.h.
Referenced by CompilerGCC::AddOutputLine(), and AdvancedCompilerOptionsDlg::OnRegexTest().
GetMasterPath()
virtual const wxString& Compiler::GetMasterPath () const inline virtual
Get the compiler's master path (must contain "bin", "include" and "lib")
Definition at line 295 of file compiler.h.
Referenced by NativeParser::AddCompilerIncludeDirsToParser(), NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), CompilerOptionsDlg::AutoDetectCompiler(), AutoDetectCompilers::AutoDetectCompilers(), CompilerICC::AutoDetectInstallationDir(), CompilerOptionsDlg::DoFillCompilerPrograms(), AutoDetectCompilers::OnMouseMotion(), and CompilerGCC::SetupEnvironment().
GetName()
virtual const wxString& Compiler::GetName () const inline virtual
Get the compiler's name.
Definition at line 293 of file compiler.h.
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), AutoDetectCompilers::AutoDetectCompilers(), CompilerFactory::CreateCompilerCopy(), Wiz::FillComboboxWithCompilers(), Wizard::FillCompilerControl(), ProjectFileOptionsDlg::FillCompilers(), DebuggerManager::FindTargetsDebugger(), CompilerOptionsDlg::OnSetDefaultCompilerClick(), CompilerGCC::PreprocessJob(), CompilerGCC::PrintBanner(), CompilerFactory::RemoveCompiler(), and CompilerGCC::SetupEnvironment().
GetOptions()
virtual const CompilerOptions& Compiler::GetOptions () const inline virtual
Get the compiler's options.
Definition at line 303 of file compiler.h.
Referenced by CompilerOptionsDlg::CompilerChanged(), CompilerOptionsDlg::CompilerOptionsDlg(), and CompilerOptionsDlg::OnTreeSelectionChange().
GetParentID()
const wxString& Compiler::GetParentID () const inline
Get this compiler's parent's unique ID.
Definition at line 353 of file compiler.h.
Referenced by AutoDetectCompilers::AutoDetectCompilers(), CompilerFactory::CompilerInheritsFrom(), LoadDefaultOptions(), CompilerOptionsDlg::OnUpdateUI(), and CompilerMINGW::SetVersionString().
GetPrograms()
virtual const CompilerPrograms& Compiler::GetPrograms () const inline virtual
Get the compiler's programs.
Definition at line 299 of file compiler.h.
Referenced by NativeParser::AddCompilerIncludeDirsToParser(), NativeParser::AddCompilerPredefinedMacrosGCC(), NativeParser::AddCompilerPredefinedMacrosVC(), CompilerICC::AutoDetectInstallationDir(), CompilerOptionsDlg::DoFillCompilerPrograms(), CompilerOptionsDlg::DoSaveCompilerDefinition(), DebuggerManager::FindTargetsDebugger(), CompilerCommandGenerator::GenerateCommandLine(), CompilerGCC::GetMakeCommandFor(), and CompilerGCC::SetupEnvironment().
GetRegExArray()
virtual const RegExArray& Compiler::GetRegExArray () inline virtual
Get the array of regexes used in errors/warnings recognition.
Definition at line 314 of file compiler.h.
Referenced by CompilerOptionsDlg::DoSaveCompilerDefinition(), AdvancedCompilerOptionsDlg::OnRegexDefaults(), and AdvancedCompilerOptionsDlg::ReadCompilerOptions().
GetSwitches()
virtual const CompilerSwitches& Compiler::GetSwitches () const inline virtual
Get the compiler's generic switches.
Definition at line 301 of file compiler.h.
Referenced by DirectCommands::AreExternalDepsOutdated(), CompilerGCC::BuildStateManagement(), ProjectLoader::ConvertLibraries(), CompilerGCC::DoCleanWithMake(), CompilerOptionsDlg::DoLoadOptions(), CompilerOptionsDlg::DoSaveCompilerDefinition(), CompilerOptionsDlg::DoSaveOptions(), ProjectLoader::ExportTargetAsProject(), CompilerCommandGenerator::FixPathSeparators(), CompilerCommandGenerator::FixupLinkLibraries(), CompilerCommandGenerator::GenerateCommandLine(), CompileTargetBase::GenerateTargetFilename(), DirectCommands::GetCleanSingleFileCommand(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetCompileSingleFileCommand(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), CompilerCommandGenerator::GetOrderedResourceIncludeDirs(), CompilerCommandGenerator::GetProcessedIncludeDir(), CompileTargetBase::GetStaticLibFilename(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), DirectCommands::IsObjectOutdated(), TemplateManager::NewProjectFromUserTemplate(), CompilerGCC::OnCleanFile(), ProjectOptionsDlg::OnProjectTypeChanged(), CompilerOptionsDlg::OptionsToText(), ProjectOptionsDlg::ProjectOptionsDlg(), AdvancedCompilerOptionsDlg::ReadCompilerOptions(), CompilerCommandGenerator::SearchDirsFromBackticks(), cbProject::SetCompilerID(), ProjectFile::SetObjName(), CompilerMINGWGenerator::SetupIncludeDirs(), CompilerCommandGenerator::SetupIncludeDirs(), CompilerOWGenerator::SetupLibrariesDirs(), CompilerCommandGenerator::SetupLibrariesDirs(), CompilerCommandGenerator::SetupLinkLibraries(), CompilerCommandGenerator::SetupOutputFilenames(), CompilerCommandGenerator::SetupResourceIncludeDirs(), CompilerOptionsDlg::TextToOptions(), and pfDetails::Update().
GetVersionString()
const wxString Compiler::GetVersionString () const inline
Get the compiler version string.
Definition at line 365 of file compiler.h.
Referenced by CompilerMINGWGenerator::SetupIncludeDirs().
IsUniqueID()
bool Compiler::IsUniqueID (const wxString & ID) inline protected
Definition at line 389 of file compiler.h.
Referenced by MakeValidID().
IsValid()
bool Compiler::IsValid () virtual
Check if the compiler is actually valid (installed).
Reimplemented in CompilerLCC.
Definition at line 189 of file compiler.cpp.
References CompilerPrograms::C, Manager::Get(), Manager::GetMacrosManager(), m_ExtraPaths, m_MasterPath, m_NeedValidityCheck, m_Programs, m_Valid, MacrosManager::ReplaceMacros(), and CompileOptionsBase::SupportsCurrentPlatform().
Referenced by CompilerGCC::CompilerValid(), CompilerLCC::IsValid(), and LoadSettings().
LoadDefaultOptions()
void Compiler::LoadDefaultOptions (const wxString & name, int recursion = 0) protected
Definition at line 777 of file compiler.cpp.
References CompilerOptions::AddOption(), CompilerPrograms::C, cbMessageBox(), clogFull, clogNone, clogSimple, CompilerPrograms::CPP, ctCompileObjectCmd, ctCompileResourceCmd, ctCount, ctGenDependenciesCmd, ctLinkConsoleExeCmd, ctLinkDynamicCmd, ctLinkExeCmd, ctLinkNativeCmd, ctLinkStaticCmd, CompilerPrograms::DBGconfig, CompilerSwitches::defaultLogging, CompilerSwitches::defines, EvalXMLCondition(), ConfigManager::Exists(), CompilerSwitches::forceCompilerUseQuotes, CompilerSwitches::forceFwdSlashes, CompilerSwitches::forceLinkerUseQuotes, CompilerSwitches::genericSwitch, Manager::Get(), CompilerFactory::GetCompilerIndex(), Manager::GetConfigManager(), GetCOnlyFlags(), GetCPPOnlyFlags(), Manager::GetLogManager(), GetParentID(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, CompilerPrograms::LD, CompilerPrograms::LIB, CompilerSwitches::libDirs, CompilerSwitches::libDirSeparator, CompilerSwitches::libExtension, CompilerSwitches::libPrefix, CompilerSwitches::linkerNeedsLibExtension, CompilerSwitches::linkerNeedsLibPrefix, CompilerSwitches::linkerNeedsPathResolved, CompilerSwitches::linkLibs, ConfigManager::LocateDataFile(), LogManager::Log(), CompilerSwitches::logging, LogManager::LogWarning(), m_Commands, m_ID, m_Mirror, m_Options, m_Programs, m_Switches, CompilerPrograms::MAKE, MakeUniqueString(), CompilerSwitches::needDependencies, CompilerSwitches::objectExtension, CompilerSwitches::objectSeparator, CompilerSwitches::PCHExtension, Compiler::MirrorSettings::Programs, ConfigManager::Read(), sdDataGlobal, sdDataUser, SetCOnlyFlags(), SetCPPOnlyFlags(), CompilerSwitches::statusSuccess, CompilerSwitches::supportsPCH, CompilerSwitches::Use83Paths, CompilerSwitches::UseFlatObjects, CompilerSwitches::UseFullSourcePaths, and CompilerPrograms::WINDRES.
Referenced by ReloadOptions(), CompilerLCC::Reset(), and Reset().
LoadDefaultRegExArray()
void Compiler::LoadDefaultRegExArray (bool globalPrecedence = false) virtual
Load the default (preset) array of regexes used in errors/warnings recognition.
Definition at line 183 of file compiler.cpp.
References GetID(), LoadRegExArray(), and m_RegExes.
Referenced by AdvancedCompilerOptionsDlg::OnRegexDefaults(), ReloadOptions(), CompilerLCC::Reset(), and Reset().
LoadRegExArray()
void Compiler::LoadRegExArray (const wxString & name, bool globalPrecedence = false, int recursion = 0) protected
Definition at line 1064 of file compiler.cpp.
References cltError, cltInfo, cltNormal, cltWarning, EvalXMLCondition(), Manager::Get(), GetArrayFromString(), Manager::GetLogManager(), ConfigManager::LocateDataFile(), LogManager::Log(), LogManager::LogWarning(), m_RegExes, sdDataGlobal, and sdDataUser.
Referenced by LoadDefaultRegExArray().
LoadSettings()
void Compiler::LoadSettings (const wxString & baseKey) virtual
Load settings.
Reimplemented in CompilerOW.
Definition at line 552 of file compiler.cpp.
References CompilerPrograms::C, cbMessageBox(), CompilerTool::command, Compiler::MirrorSettings::Commands, CommandTypeDescriptions, CompilerSettingsVersion, CompilerPrograms::CPP, ctCount, CompilerPrograms::DBGconfig, CompilerSwitches::defines, ConfigManager::EnumerateKeys(), ConfigManager::EnumerateSubPaths(), ConfigManager::Exists(), CompilerTool::extensions, CompilerSwitches::forceCompilerUseQuotes, CompilerSwitches::forceFwdSlashes, CompilerSwitches::forceLinkerUseQuotes, CompilerTool::generatedFiles, CompilerSwitches::genericSwitch, Manager::Get(), GetArrayFromString(), CompilerFactory::GetCompilerIndex(), Manager::GetConfigManager(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, IsValid(), CompilerPrograms::LD, CompilerPrograms::LIB, CompilerSwitches::libDirs, CompilerSwitches::libDirSeparator, CompilerSwitches::libExtension, CompilerSwitches::libPrefix, CompilerSwitches::linkerNeedsLibExtension, CompilerSwitches::linkerNeedsLibPrefix, CompilerSwitches::linkerNeedsPathResolved, CompilerSwitches::linkLibs, CompilerSwitches::logging, m_Commands, m_ExtraPaths, m_ID, m_MasterPath, m_Mirror, m_Name, m_Options, m_Programs, m_RegExes, m_SortOptions, m_Switches, CompilerPrograms::MAKE, MakeUniqueArray(), MirrorCurrentSettings(), CompilerSwitches::needDependencies, CompilerSwitches::objectExtension, CompilerSwitches::objectSeparator, Compiler::MirrorSettings::Options, CompilerSwitches::PCHExtension, ConfigManager::Read(), ConfigManager::ReadArrayString(), ConfigManager::ReadBool(), ConfigManager::ReadInt(), Compiler::MirrorSettings::RegExes, HTMLTags::sep, CompileOptionsBase::SetCommandsAfterBuild(), CompileOptionsBase::SetCommandsBeforeBuild(), CompileOptionsBase::SetCompilerOptions(), CompileOptionsBase::SetIncludeDirs(), CompileOptionsBase::SetLibDirs(), CompileOptionsBase::SetLinkerOptions(), CompileOptionsBase::SetLinkLibs(), CompileOptionsBase::SetResourceCompilerOptions(), CompileOptionsBase::SetResourceIncludeDirs(), CompileOptionsBase::SetVar(), SetVersionString(), CompilerSwitches::statusSuccess, CompilerSwitches::supportsPCH, Compiler::MirrorSettings::Switches, CompileOptionsBase::UnsetAllVars(), CompilerSwitches::Use83Paths, CompilerSwitches::UseFlatObjects, CompilerSwitches::UseFullSourcePaths, CfgMgrConsts::version, and CompilerPrograms::WINDRES.
Referenced by CompilerFactory::CreateCompilerCopy(), and CompilerOW::LoadSettings().
MakeValidID()
void Compiler::MakeValidID () protected
Definition at line 229 of file compiler.cpp.
References cbThrow, IsUniqueID(), m_CompilerIDs, m_ID, and m_Name.
Referenced by Compiler(), and CompilerFactory::CreateCompilerCopy().
MirrorCurrentSettings()
void Compiler::MirrorCurrentSettings () protected
Definition at line 328 of file compiler.cpp.
References Compiler::MirrorSettings::CmdsAfter, Compiler::MirrorSettings::CmdsBefore, Compiler::MirrorSettings::Commands, Compiler::MirrorSettings::CompilerOptions_, ctCount, Compiler::MirrorSettings::ExtraPaths, Compiler::MirrorSettings::IncludeDirs, Compiler::MirrorSettings::LibDirs, Compiler::MirrorSettings::LinkerOptions, Compiler::MirrorSettings::LinkLibs, CompileOptionsBase::m_CmdsAfter, CompileOptionsBase::m_CmdsBefore, m_Commands, CompileOptionsBase::m_CompilerOptions, m_ExtraPaths, CompileOptionsBase::m_IncludeDirs, CompileOptionsBase::m_LibDirs, CompileOptionsBase::m_LinkerOptions, CompileOptionsBase::m_LinkLibs, m_MasterPath, m_Mirror, m_Mirrored, m_Name, m_Options, m_Programs, m_RegExes, CompileOptionsBase::m_ResIncludeDirs, m_SortOptions, m_Switches, MakeUniqueArray(), Compiler::MirrorSettings::MasterPath, Compiler::MirrorSettings::Name, Compiler::MirrorSettings::Options, Compiler::MirrorSettings::Programs, Compiler::MirrorSettings::RegExes, Compiler::MirrorSettings::ResIncludeDirs, Compiler::MirrorSettings::SortOptions, and Compiler::MirrorSettings::Switches.
Referenced by LoadSettings().
ReloadOptions()
void Compiler::ReloadOptions () virtual
Reload option flags (for copied compilers).
Override if not using standard XML loading.
Definition at line 174 of file compiler.cpp.
References CompilerOptions::ClearOptions(), GetID(), LoadDefaultOptions(), LoadDefaultRegExArray(), ConfigManager::LocateDataFile(), m_Options, sdDataGlobal, and sdDataUser.
Referenced by CompilerFactory::CreateCompilerCopy().
Reset()
void Compiler::Reset () virtual
Reset settings to defaults.
Put initialization code here or leave blank for standard XML loading. Call this from the default constructor.
Reimplemented in CompilerLCC.
Definition at line 157 of file compiler.cpp.
References CompilerOptions::ClearOptions(), ctCount, GetID(), LoadDefaultOptions(), LoadDefaultRegExArray(), CompileOptionsBase::m_CmdsAfter, CompileOptionsBase::m_CmdsBefore, m_Commands, CompileOptionsBase::m_CompilerOptions, CompileOptionsBase::m_LinkerOptions, CompileOptionsBase::m_LinkLibs, m_Options, and SetVersionString().
Referenced by CompilerCYGWIN::CompilerCYGWIN(), CompilerG95::CompilerG95(), CompilerGDC::CompilerGDC(), CompilerGNUARM::CompilerGNUARM(), CompilerGNUFortran::CompilerGNUFortran(), CompilerIAR::CompilerIAR(), CompilerICC::CompilerICC(), CompilerKeilC51::CompilerKeilC51(), CompilerMINGW::CompilerMINGW(), CompilerMSVC::CompilerMSVC(), CompilerMSVC10::CompilerMSVC10(), CompilerMSVC8::CompilerMSVC8(), CompilerOW::CompilerOW(), CompilerXML::CompilerXML(), and CompilerOptionsDlg::OnResetCompilerClick().
SaveSettings()
void Compiler::SaveSettings (const wxString & baseKey) virtual
Save settings.
Definition at line 363 of file compiler.cpp.
References CompilerPrograms::C, Compiler::MirrorSettings::CmdsAfter, Compiler::MirrorSettings::CmdsBefore, Compiler::MirrorSettings::Commands, CommandTypeDescriptions, Compiler::MirrorSettings::CompilerOptions_, CompilerSettingsVersion, CompilerPrograms::CPP, ctCount, CompilerPrograms::DBGconfig, CompilerSwitches::defines, ConfigManager::DeleteSubPath(), RegExStruct::desc, Compiler::MirrorSettings::ExtraPaths, RegExStruct::filename, CompilerSwitches::forceCompilerUseQuotes, CompilerSwitches::forceFwdSlashes, CompilerSwitches::forceLinkerUseQuotes, CompilerSwitches::genericSwitch, Manager::Get(), CompileOptionsBase::GetAllVars(), CompilerFactory::GetCompilerIndex(), Manager::GetConfigManager(), GetCOnlyFlags(), GetCPPOnlyFlags(), RegExStruct::GetRegExString(), GetStringFromArray(), CompilerSwitches::includeDirs, Compiler::MirrorSettings::IncludeDirs, CompilerSwitches::includeDirSeparator, CompilerPrograms::LD, CompilerPrograms::LIB, CompilerSwitches::libDirs, Compiler::MirrorSettings::LibDirs, CompilerSwitches::libDirSeparator, CompilerSwitches::libExtension, CompilerSwitches::libPrefix, RegExStruct::line, CompilerSwitches::linkerNeedsLibExtension, CompilerSwitches::linkerNeedsLibPrefix, CompilerSwitches::linkerNeedsPathResolved, Compiler::MirrorSettings::LinkerOptions, CompilerSwitches::linkLibs, Compiler::MirrorSettings::LinkLibs, CompilerSwitches::logging, RegExStruct::lt, CompileOptionsBase::m_CmdsAfter, CompileOptionsBase::m_CmdsBefore, m_Commands, CompileOptionsBase::m_CompilerOptions, m_ExtraPaths, m_ID, CompileOptionsBase::m_IncludeDirs, CompileOptionsBase::m_LibDirs, CompileOptionsBase::m_LinkerOptions, CompileOptionsBase::m_LinkLibs, m_MasterPath, m_Mirror, m_Name, m_ParentID, m_Programs, m_RegExes, CompileOptionsBase::m_ResIncludeDirs, CompileOptionsBase::m_ResourceCompilerOptions, m_Switches, CompilerPrograms::MAKE, MakeUniqueArray(), Compiler::MirrorSettings::MasterPath, RegExStruct::msg, CompilerSwitches::needDependencies, CompilerSwitches::objectExtension, CompilerSwitches::objectSeparator, CompilerSwitches::PCHExtension, Compiler::MirrorSettings::Programs, Compiler::MirrorSettings::RegExes, Compiler::MirrorSettings::ResIncludeDirs, Compiler::MirrorSettings::ResourceCompilerOptions, Compiler::MirrorSettings::SortOptions, CompilerSwitches::statusSuccess, CompilerSwitches::supportsPCH, Compiler::MirrorSettings::Switches, CompilerSwitches::Use83Paths, CompilerSwitches::UseFlatObjects, CompilerSwitches::UseFullSourcePaths, CompilerPrograms::WINDRES, and ConfigManager::Write().
SetCOnlyFlags()
void Compiler::SetCOnlyFlags (const wxString & flags) inline
Definition at line 372 of file compiler.h.
Referenced by LoadDefaultOptions(), and CompilerOptionsDlg::OnFlagsPopup().
SetCPPOnlyFlags()
void Compiler::SetCPPOnlyFlags (const wxString & flags) inline
Definition at line 373 of file compiler.h.
Referenced by LoadDefaultOptions(), and CompilerOptionsDlg::OnFlagsPopup().
SetExtraPaths()
virtual void Compiler::SetExtraPaths (const wxArrayString & paths) inline virtual
Set the compiler's extra paths.
Definition at line 323 of file compiler.h.
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), and CompilerOptionsDlg::DoSaveCompilerPrograms().
SetMasterPath()
virtual void Compiler::SetMasterPath (const wxString & path) inline virtual
Set the compiler's master path (must contain "bin", "include" and "lib")
Reimplemented in CompilerOW.
Definition at line 321 of file compiler.h.
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), AutoDetectCompilers::AutoDetectCompilers(), CompilerOptionsDlg::DoSaveCompilerPrograms(), and CompilerOW::SetMasterPath().
SetName()
virtual void Compiler::SetName (const wxString & name) inline virtual
Set the compiler's name.
Definition at line 319 of file compiler.h.
Referenced by CompilerFactory::CreateCompilerCopy(), TemplateManager::NewProjectFromUserTemplate(), CompilerOptionsDlg::OnEditCompilerClick(), and ProjectFile::SetObjName().
SetOptions()
virtual void Compiler::SetOptions (const CompilerOptions & options) inline virtual
Set the compiler's options.
Definition at line 329 of file compiler.h.
Referenced by CompilerOptionsDlg::DoSaveCompilerDefinition().
SetPrograms()
virtual void Compiler::SetPrograms (const CompilerPrograms & programs) inline virtual
Set the compiler's programs.
Definition at line 325 of file compiler.h.
Referenced by CompilerOptionsDlg::DoSaveCompilerPrograms().
SetRegExArray()
virtual void Compiler::SetRegExArray (const RegExArray & regexes) inline virtual
Set the array of regexes used in errors/warnings recognition.
Definition at line 331 of file compiler.h.
Referenced by AdvancedCompilerOptionsDlg::EndModal(), and AdvancedCompilerOptionsDlg::OnRegexTest().
SetSwitches()
virtual void Compiler::SetSwitches (const CompilerSwitches & switches) inline virtual
Set the compiler's generic switches.
Definition at line 327 of file compiler.h.
Referenced by CompilerOptionsDlg::DoSaveOptions(), and AdvancedCompilerOptionsDlg::WriteCompilerOptions().
SetVersionString()
virtual void Compiler::SetVersionString () inline virtual
Set the compiler version string.
Please override this virtual function with your own compiler-version detection code if you want to use this.
By default this function does nothing.
Reimplemented in CompilerMINGW.
Definition at line 362 of file compiler.h.
Referenced by CompilerG95::AutoDetectInstallationDir(), LoadSettings(), and Reset().
WithMultiLineMsg()
bool Compiler::WithMultiLineMsg () inline
Do compiler writes multi-line messages?
Definition at line 379 of file compiler.h.
Referenced by CompilerGCC::AddOutputLine().
Friends And Related Function Documentation
CompilerFactory
friend class CompilerFactory friend
Definition at line 379 of file compiler.h.
Member Data Documentation
CommandTypeDescriptions
wxString Compiler::CommandTypeDescriptions static
Initial value:
=
{
    _("Compile single file to object file"),
    _("Generate dependencies for file"),
    _("Compile Win32 resource file"),
    _("Link object files to executable"),
    _("Link object files to console executable"),
    _("Link object files to dynamic library"),
    _("Link object files to static library"),
    _("Link object files to native executable")
}
Get the command type descriptions (used in advanced compiler options)
Definition at line 356 of file compiler.h.
Referenced by CompilerSwitches::CompilerSwitches(), LoadSettings(), AdvancedCompilerOptionsDlg::ReadCompilerOptions(), and SaveSettings().
FilePathWithSpaces
const wxString Compiler::FilePathWithSpaces = _T("[][{}() \t#%$~[:alnum:]&_:+/\\.-]+") static
Definition at line 277 of file compiler.h.
m_Commands
CompilerToolsVector Compiler::m_Commands[ctCount] protected
Definition at line 408 of file compiler.h.
Referenced by Compiler(), GetCommand(), GetCompilerTool(), LoadDefaultOptions(), LoadSettings(), MirrorCurrentSettings(), Reset(), and SaveSettings().
m_CompilerIDs
wxArrayString Compiler::m_CompilerIDs static private
Definition at line 424 of file compiler.h.
Referenced by CompilerFactory::CreateCompilerCopy(), MakeValidID(), CompilerFactory::RemoveCompiler(), and CompilerFactory::UnregisterCompilers().
m_Error
wxString Compiler::m_Error protected
Definition at line 415 of file compiler.h.
Referenced by CheckForWarningsAndErrors().
m_ErrorFilename
wxString Compiler::m_ErrorFilename protected
Definition at line 413 of file compiler.h.
Referenced by CheckForWarningsAndErrors().
m_ErrorLine
wxString Compiler::m_ErrorLine protected
Definition at line 414 of file compiler.h.
Referenced by CheckForWarningsAndErrors().
m_ExtraPaths
wxArrayString Compiler::m_ExtraPaths protected
Definition at line 407 of file compiler.h.
Referenced by CompilerXML::AddPath(), CompilerXML::AutoDetectInstallationDir(), CompilerLCC::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), CompilerKeilC51::AutoDetectInstallationDir(), CompilerMSVC::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerOW::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), Compiler(), IsValid(), LoadSettings(), MirrorCurrentSettings(), and SaveSettings().
m_ID
wxString Compiler::m_ID private
Definition at line 422 of file compiler.h.
Referenced by Compiler(), CompilerFactory::CreateCompilerCopy(), EvalXMLCondition(), LoadDefaultOptions(), LoadSettings(), MakeValidID(), and SaveSettings().
m_MasterPath
wxString Compiler::m_MasterPath protected
Definition at line 406 of file compiler.h.
Referenced by CompilerXML::AddPath(), CompilerXML::AutoDetectInstallationDir(), CompilerLCC::AutoDetectInstallationDir(), CompilerGDC::AutoDetectInstallationDir(), CompilerGNUARM::AutoDetectInstallationDir(), CompilerOW::AutoDetectInstallationDir(), CompilerMSVC::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerGNUFortran::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), CompilerCYGWIN::AutoDetectInstallationDir(), CompilerKeilC51::AutoDetectInstallationDir(), CompilerG95::AutoDetectInstallationDir(), CompilerMINGW::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), Compiler(), CompilerLCC::IsValid(), IsValid(), CompilerOW::LoadSettings(), LoadSettings(), MirrorCurrentSettings(), SaveSettings(), CompilerOW::SetMasterPath(), and CompilerMINGW::SetVersionString().
m_Mirror
MirrorSettings Compiler::m_Mirror private
Definition at line 455 of file compiler.h.
Referenced by LoadDefaultOptions(), LoadSettings(), MirrorCurrentSettings(), and SaveSettings().
m_Mirrored
bool Compiler::m_Mirrored private
Definition at line 456 of file compiler.h.
Referenced by MirrorCurrentSettings().
m_MultiLineMessages
bool Compiler::m_MultiLineMessages protected
Definition at line 420 of file compiler.h.
Referenced by CheckForWarningsAndErrors(), Compiler(), CompilerGNUFortran::CompilerGNUFortran(), and CompilerXML::CompilerXML().
m_Name
wxString Compiler::m_Name protected
Definition at line 405 of file compiler.h.
Referenced by Compiler(), LoadSettings(), MakeValidID(), MirrorCurrentSettings(), and SaveSettings().
m_NeedValidityCheck
bool Compiler::m_NeedValidityCheck private
Definition at line 426 of file compiler.h.
Referenced by Compiler(), and IsValid().
m_Options
CompilerOptions Compiler::m_Options protected
Definition at line 411 of file compiler.h.
Referenced by Compiler(), LoadDefaultOptions(), LoadSettings(), MirrorCurrentSettings(), ReloadOptions(), CompilerLCC::Reset(), and Reset().
m_ParentID
wxString Compiler::m_ParentID private
Definition at line 423 of file compiler.h.
Referenced by EvalXMLCondition(), CompilerFactory::RemoveCompiler(), and SaveSettings().
m_Programs
CompilerPrograms Compiler::m_Programs protected
Definition at line 409 of file compiler.h.
Referenced by CompilerXML::AutoDetectInstallationDir(), CompilerLCC::AutoDetectInstallationDir(), CompilerOW::AutoDetectInstallationDir(), CompilerCYGWIN::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerGDC::AutoDetectInstallationDir(), CompilerGNUARM::AutoDetectInstallationDir(), CompilerMSVC::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerGNUFortran::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), CompilerKeilC51::AutoDetectInstallationDir(), CompilerG95::AutoDetectInstallationDir(), CompilerMINGW::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), Compiler(), GetExecName(), CompilerLCC::IsValid(), IsValid(), LoadDefaultOptions(), LoadSettings(), MirrorCurrentSettings(), SaveSettings(), and CompilerMINGW::SetVersionString().
m_RegExes
RegExArray Compiler::m_RegExes protected
Definition at line 412 of file compiler.h.
Referenced by CheckForWarningsAndErrors(), Compiler(), LoadDefaultRegExArray(), LoadRegExArray(), LoadSettings(), MirrorCurrentSettings(), and SaveSettings().
m_SortOptions
wxString Compiler::m_SortOptions[2] protected
Definition at line 417 of file compiler.h.
Referenced by Compiler(), LoadSettings(), and MirrorCurrentSettings().
m_Switches
CompilerSwitches Compiler::m_Switches protected
Definition at line 410 of file compiler.h.
Referenced by Compiler(), LoadDefaultOptions(), LoadSettings(), MirrorCurrentSettings(), and SaveSettings().
m_Valid
bool Compiler::m_Valid private
Definition at line 425 of file compiler.h.
Referenced by Compiler(), and IsValid().
m_VersionString
wxString Compiler::m_VersionString protected
Definition at line 416 of file compiler.h.
Referenced by Compiler(), and CompilerMINGW::SetVersionString().
m_Weight
int Compiler::m_Weight protected
Definition at line 419 of file compiler.h.
Referenced by Compiler(), CompilerCYGWIN::CompilerCYGWIN(), CompilerG95::CompilerG95(), CompilerGDC::CompilerGDC(), CompilerGNUARM::CompilerGNUARM(), CompilerGNUFortran::CompilerGNUFortran(), CompilerIAR::CompilerIAR(), CompilerICC::CompilerICC(), CompilerKeilC51::CompilerKeilC51(), CompilerKeilCX51::CompilerKeilCX51(), CompilerLCC::CompilerLCC(), CompilerMINGW::CompilerMINGW(), CompilerMSVC::CompilerMSVC(), CompilerMSVC10::CompilerMSVC10(), CompilerMSVC8::CompilerMSVC8(), CompilerOW::CompilerOW(), CompilerXML::CompilerXML(), and CompilerFactory::RegisterCompiler().
The documentation for this class was generated from the following files:
compiler.h
compiler.cpp