Code::Blocks: EditorBase Class Reference
EditorBase Class Reference
Base class that all "editors" should inherit from.
#include <editorbase.h>
Public Member Functions
EditorBase (wxWindow *parent, const wxString &filename)
~EditorBase () override
void operator= (cb_optional const EditorBase &rhs)
Don't use this.
virtual const wxString & GetFilename () const
Get the editor's filename (if applicable).
virtual void SetFilename (const wxString &filename)
Sets the editor's filename.
virtual const wxString & GetShortName () const
Returns the editor's short name.
virtual bool GetModified () const
Is it modified?
virtual void SetModified (bool=true)
Set the modification status.
virtual const wxString & GetTitle ()
The editor's title.
virtual void SetTitle (const wxString &newTitle)
Set the editor's title.
virtual void Activate ()
Activate this editor.
virtual bool QueryClose ()
Can this be closed (destroyed)?
virtual bool Close ()
Close this editor.
virtual bool Save ()
Save contents.
virtual bool SaveAs ()
Save editor contents under a different filename.
virtual bool IsBuiltinEditor () const
Is this a built-in editor?
virtual bool ThereAreOthers () const
Are there other editors besides this?
virtual void DisplayContextMenu (const wxPoint &position, ModuleType type=mtUnknown)
Display context menu.
virtual bool VisibleToTree () const
Should this kind of editor be visible in the open files tree?
virtual void GotoLine (int, bool=true)
Move the caret at the specified line.
virtual void Undo ()
Undo changes.
virtual void Redo ()
Redo changes.
virtual void ClearHistory ()
Clear Undo- (and Changebar-) history.
virtual void GotoNextChanged ()
Goto next changed line.
virtual void GotoPreviousChanged ()
Goto previous changed line.
virtual void SetChangeCollection (cb_optional bool collectChange)
Enable or disable changebar.
virtual void Cut ()
Cut selected text/object to clipboard.
virtual void Copy ()
Copy selected text/object to clipboard.
virtual void Paste ()
Paste selected text/object from clipboard.
virtual bool CanUndo () const
Is there something to undo?
virtual bool CanRedo () const
Is there something to redo?
virtual bool HasSelection () const
Is there a selection?
virtual bool CanPaste () const
Is there something to paste?
virtual bool IsReadOnly () const
Is the editor read-only?
virtual void SetReadOnly (bool=true)
Set the editor read-only.
virtual bool CanSelectAll () const
Can the editor select everything?
virtual void SelectAll ()
Select everything in the editor.
virtual bool IsContextMenuOpened () const
Is there a context (right click) menu open.
Protected Member Functions
virtual void InitFilename (const wxString &filename)
Initializes filename data.
virtual wxMenu * CreateContextSubMenu (long id)
Creates context submenus.
virtual void AddToContextMenu (cb_optional wxMenu *popup, cb_optional ModuleType type, cb_optional bool pluginsdone)
Creates context menu items, both before and after creating plugins menu items.
virtual wxString CreateUniqueFilename ()
Creates unique filename when asking to save the file.
virtual bool OnBeforeBuildContextMenu (cb_optional const wxPoint &position, cb_optional ModuleType type)
Informs the editor we 're just about to create a context menu.
virtual void OnAfterBuildContextMenu (cb_optional ModuleType type)
Informs the editor we 're done creating the context menu (just about to display it).
Protected Attributes
bool m_IsBuiltinEditor
wxString m_Shortname
wxString m_Filename
EditorBaseInternalData * m_pData
Use this to add new vars/functions w/out breaking the ABI.
Private Member Functions
EditorBase (cb_unused const EditorBase &rhs)
void OnContextMenuEntry (wxCommandEvent &event)
one event handler for all popup menu entries
void BasicAddToContextMenu (wxMenu *popup, ModuleType type)
Private Attributes
SwitchToMap m_SwitchTo
wxString m_WinTitle
wxString lastWord
Detailed Description
Base class that all "editors" should inherit from.
Note
This class descends from wxPanel, so it provides all wxPanel methods as well...
Definition at line 30 of file editorbase.h.
Constructor & Destructor Documentation
EditorBase() [1/2]
EditorBase::EditorBase (wxWindow * parent, const wxString & filename)
Definition at line 115 of file editorbase.cpp.
References _T, EditorManager::AddCustomEditor(), Manager::Get(), Manager::GetEditorManager(), InitFilename(), m_pData, m_Shortname, and SetTitle().
~EditorBase()
EditorBase::~EditorBase () override
Definition at line 129 of file editorbase.cpp.
References cbEVT_EDITOR_CLOSE, Manager::Get(), Manager::GetEditorManager(), Manager::GetPluginManager(), m_Filename, m_pData, PluginManager::NotifyPlugins(), and EditorManager::RemoveCustomEditor().
EditorBase() [2/2]
EditorBase::EditorBase (cb_unused const EditorBase & rhs) private
Member Function Documentation
Activate()
void EditorBase::Activate () virtual
Activate this editor.
Causes this editor to be activated, i.e. brought to front.
Definition at line 175 of file editorbase.cpp.
References Manager::Get(), Manager::GetEditorManager(), and EditorManager::SetActiveEditor().
Referenced by CompilerErrors::DoGotoError(), ProjectManagerUI::DoOpenFile(), MainFrame::DoOpenFile(), cbProject::LoadLayout(), CCDebugInfo::OnGoDeclClick(), CCDebugInfo::OnGoImplClick(), BreakpointsDlg::OnOpen(), ScriptBindings::RegisterBindings(), and cbSearchResultsLog::SyncEditor().
AddToContextMenu()
virtual void EditorBase::AddToContextMenu (cb_optional wxMenu * popup, cb_optional ModuleType type, cb_optional bool pluginsdone) inline protected virtual
Creates context menu items, both before and after creating plugins menu items.
Parameters
popup The popup menu.
type The module's type.
pluginsdone True if plugin menus have been created, false if not.
Definition at line 257 of file editorbase.h.
Referenced by DisplayContextMenu(), and cbEditor::GetLastModificationTime().
BasicAddToContextMenu()
void EditorBase::BasicAddToContextMenu (wxMenu * popup, ModuleType type) private
Definition at line 245 of file editorbase.cpp.
References _(), wxMenu::Append(), wxMenu::AppendSeparator(), CreateContextSubMenu(), wxMenu::Enable(), GetModified(), idCloseAll, idCloseAllOthers, idCloseMe, idSaveAll, idSaveMe, idSwitchTo, mtEditorManager, mtOpenFilesList, and ThereAreOthers().
Referenced by DisplayContextMenu().
CanPaste()
virtual bool EditorBase::CanPaste () const inline virtual
Is there something to paste?
Returns
True if there is something to paste, false if not.
Reimplemented in cbEditor.
Definition at line 211 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditMenuUpdateUI(), and ScriptBindings::RegisterBindings().
CanRedo()
virtual bool EditorBase::CanRedo () const inline virtual
Is there something to redo?
Returns
True if there is something to redo, false if not.
Reimplemented in cbEditor.
Definition at line 199 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditMenuUpdateUI(), and ScriptBindings::RegisterBindings().
CanSelectAll()
virtual bool EditorBase::CanSelectAll () const inline virtual
Can the editor select everything?
Returns
True if the editor can select all content, false if not.
Reimplemented in cbEditor.
Definition at line 229 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), and MainFrame::OnEditMenuUpdateUI().
CanUndo()
virtual bool EditorBase::CanUndo () const inline virtual
Is there something to undo?
Returns
True if there is something to undo, false if not.
Reimplemented in cbEditor.
Definition at line 193 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditMenuUpdateUI(), MainFrame::OnEditUndo(), and ScriptBindings::RegisterBindings().
ClearHistory()
virtual void EditorBase::ClearHistory () inline virtual
Clear Undo- (and Changebar-) history.
Reimplemented in cbEditor.
Definition at line 169 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), and MainFrame::OnEditClearHistory().
Close()
bool EditorBase::Close () virtual
Close this editor.
The default implementation closes (destroys) the editor and returns true.
Returns
True if editor closed successfully
Definition at line 203 of file editorbase.cpp.
Referenced by EditorManager::CheckForExternallyModifiedFiles(), and ScriptBindings::RegisterBindings().
Copy()
virtual void EditorBase::Copy () inline virtual
Copy selected text/object to clipboard.
Reimplemented in cbEditor.
Definition at line 184 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditCopy(), and ScriptBindings::RegisterBindings().
CreateContextSubMenu()
wxMenu * EditorBase::CreateContextSubMenu (long id) protected virtual
Creates context submenus.
See cbEditor code for details.
Parameters
id An event handler's ID.
Returns
The created submenu or NULL if not applicable.
Reimplemented in cbEditor.
Definition at line 219 of file editorbase.cpp.
References wxMenu::Append(), EditorMaxSwitchTo, Manager::Get(), EditorManager::GetEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), wxMenu::GetMenuItemCount(), GetModified(), GetShortName(), idSwitchFile1, idSwitchTo, m_SwitchTo, wxEmptyString, and wxT.
Referenced by BasicAddToContextMenu(), cbEditor::CreateContextSubMenu(), DisplayContextMenu(), and cbEditor::GetLastModificationTime().
CreateUniqueFilename()
wxString EditorBase::CreateUniqueFilename () protected virtual
Creates unique filename when asking to save the file.
Returns
A unique filename suggestion.
Definition at line 96 of file editorbase.cpp.
References _(), _T, wxString::Clear(), wxString::Format(), Manager::Get(), wxFileExists(), and wxGetCwd().
Cut()
virtual void EditorBase::Cut () inline virtual
Cut selected text/object to clipboard.
Reimplemented in cbEditor.
Definition at line 181 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditCut(), and ScriptBindings::RegisterBindings().
DisplayContextMenu()
void EditorBase::DisplayContextMenu (const wxPoint & position, ModuleType type = mtUnknown) virtual
Display context menu.
Displays the editor's context menu. This is called automatically if the user right-clicks in the editor area.
Parameters
position The position to popup the context menu.
type The module's type.
Definition at line 271 of file editorbase.cpp.
References _(), _T, AddToContextMenu(), wxMenu::Append(), wxMenu::AppendSeparator(), PluginManager::AskPluginsForModuleMenu(), BasicAddToContextMenu(), EditorManager::Close(), CreateContextSubMenu(), FileTreeData::ftdkUndefined, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), PluginManager::GetFindMenuItemCount(), PluginManager::GetFindMenuItemFirst(), wxMenu::GetMenuItemCount(), wxMenu::GetMenuItems(), Manager::GetPluginManager(), wxScintilla::GetSelectedText(), wxScintilla::GetTextRange(), idCodeProject, idCPlusPlusCom, idGoogle, idMsdn, idStackOverflow, idSwitchTo, wxMenu::Insert(), wxString::IsEmpty(), wxMenuItem::IsSeparator(), lastWord, EditorBaseInternalData::m_CloseMe, EditorBaseInternalData::m_DisplayingPopupMenu, m_Filename, m_pData, mtEditorManager, OnAfterBuildContextMenu(), OnBeforeBuildContextMenu(), wxScintilla::PointFromPosition(), wxMenu::Remove(), PluginManager::ResetModuleMenu(), FileTreeData::SetFolder(), wxScintilla::WordEndPosition(), wxScintilla::WordStartPosition(), wxDefaultPosition, wxEmptyString, wxGetKeyState(), wxID_SEPARATOR, WXK_ALT, and WXK_CONTROL.
GetFilename()
virtual const wxString& EditorBase::GetFilename () const inline virtual
Get the editor's filename (if applicable).
Returns
The editor's filename.
Definition at line 45 of file editorbase.h.
Referenced by NativeParser::AddProjectToParser(), EditorColourSet::Apply(), EditorManager::CheckForExternallyModifiedFiles(), CrashHandlerSaveEditorFiles(), CodeCompletion::DoAllMethodsImpl(), CompilerGCC::DoBuild(), CodeCompletion::DoClassMethodDeclImpl(), CodeCompletion::DoCodeComplete(), CodeCompletion::DoCodeCompleteIncludes(), CodeRefactoring::DoFindReferences(), MainFrame::DoOpenFile(), MainFrame::DoUpdateStatusBar(), cbDebuggerPlugin::EditorLinesAddedOrRemoved(), FindReplace::FindInFiles(), NativeParser::GetCallTips(), MainFrame::GetEditorDescription(), CodeRefactoring::GetOpenedFiles(), NativeParser::GetProjectByEditor(), CodeCompletion::GetProviderStatusFor(), EditorManager::IsOpen(), FileManager::Load(), NativeParser::MarkItemsByAI(), EditorManager::New(), CompilerGCC::OnCompileFileRequest(), cbEditor::OnContextMenuEntry(), NativeParser::OnEditorActivated(), CodeCompletion::OnEditorActivatedTimer(), CodeCompletion::OnEditorClosed(), NativeParser::OnEditorClosed(), CodeCompletion::OnEditorOpen(), cbDebuggerPlugin::OnEditorOpened(), CodeCompletion::OnOpenIncludeFile(), CodeCompletion::OnReparsingTimer(), DebuggerMenuHandler::OnRunToCursor(), DebuggerMenuHandler::OnSetNextStatement(), EditorManager::Open(), EditorManager::OpenContainingFolder(), CodeRefactoring::Parse(), CodeCompletion::ParseFunctionsAndFillToolbar(), CompilerGCC::PrepareCompileFile(), QueryClose(), MacrosManager::RecalcVars(), cbEditor::RefreshBreakpointMarkers(), ScriptBindings::RegisterBindings(), FindReplace::ReplaceInFiles(), MacrosManager::ReplaceMacros(), cbEditor::Save(), EditorManager::SaveAll(), cbEditor::SetProjectFile(), SetTitle(), EditorManager::SwapActiveHeaderSource(), ClassBrowser::UpdateClassBrowserView(), and CodeCompletion::UpdateEditorSyntax().
GetModified()
virtual bool EditorBase::GetModified () const inline virtual
Is it modified?
Returns
true If editor is modified, false otherwise.
Note
This function should always be overriden by implementations because the default implementation in EditorBase always returns false.
Reimplemented in cbEditor.
Definition at line 67 of file editorbase.h.
Referenced by BasicAddToContextMenu(), CreateContextSubMenu(), cbEditor::IsOK(), MainFrame::OnFileMenuUpdateUI(), EditorManager::OnPageContextMenu(), QueryClose(), ScriptBindings::RegisterBindings(), and EditorManager::SaveAll().
GetShortName()
virtual const wxString& EditorBase::GetShortName () const inline virtual
Returns the editor's short name.
This is the name displayed on the editor's tab...
Synonym to GetTitle().
Definition at line 58 of file editorbase.h.
Referenced by CreateContextSubMenu(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeCompletion::DoCodeComplete(), CodeCompletion::DoCodeCompleteIncludes(), CodeCompletion::DoCodeCompletePreprocessor(), EditorManager::OnPageContextMenu(), ScriptBindings::RegisterBindings(), and cbEditor::SetProjectFile().
GetTitle()
const wxString & EditorBase::GetTitle () virtual
The editor's title.
Returns
The editor's title.
Definition at line 144 of file editorbase.cpp.
References m_WinTitle.
Referenced by EditorManager::AddEditorBase(), MainFrame::DoUpdateAppTitle(), and ScriptBindings::RegisterBindings().
GotoLine()
virtual void EditorBase::GotoLine (int , bool = true) inline virtual
Move the caret at the specified line.
Parameters
line The line to move the caret to.
centerOnScreen If true, the line in question will be in the center of the editor's area (if possible). If false, it will be just made visible.
Reimplemented in cbEditor.
Definition at line 160 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), CodeBlocksApp::LoadDelayedFiles(), and ScriptBindings::RegisterBindings().
GotoNextChanged()
virtual void EditorBase::GotoNextChanged () inline virtual
Goto next changed line.
Reimplemented in cbEditor.
Definition at line 172 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime().
GotoPreviousChanged()
virtual void EditorBase::GotoPreviousChanged () inline virtual
Goto previous changed line.
Reimplemented in cbEditor.
Definition at line 175 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime().
HasSelection()
virtual bool EditorBase::HasSelection () const inline virtual
Is there a selection?
Returns
True if there is text/object selected, false if not.
Reimplemented in cbEditor.
Definition at line 205 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditMenuUpdateUI(), and ScriptBindings::RegisterBindings().
InitFilename()
void EditorBase::InitFilename (const wxString & filename) protected virtual
Initializes filename data.
Parameters
filename The editor's filename for initialization.
Definition at line 84 of file editorbase.cpp.
References wxFileName::Assign(), wxFileName::GetFullName(), and realpath().
Referenced by cbEditor::DoInitializations(), and EditorBase().
IsBuiltinEditor()
bool EditorBase::IsBuiltinEditor () const virtual
Is this a built-in editor?
Query if this is a built-in editor (a.k.a cbEditor).
Returns
True if it is a cbEditor, false otherwise.
Definition at line 209 of file editorbase.cpp.
References m_IsBuiltinEditor.
Referenced by ProjectManagerUI::DoOpenFile(), MainFrame::DoUpdateAppTitle(), EditorManager::GetBuiltinEditor(), MainFrame::GetEditorDescription(), EditorManager::InternalGetBuiltinEditor(), BreakpointsDlg::OnBreakpointEdit(), cbSmartIndentPlugin::OnCCDoneEvent(), MainFrame::OnEditBookmarksClearAll(), MainFrame::OnEditBookmarksNext(), MainFrame::OnEditBookmarksPrevious(), MainFrame::OnEditBookmarksToggle(), MainFrame::OnEditorActivated(), CodeCompletion::OnEditorClosed(), cbDebuggerPlugin::OnEditorOpened(), CCManager::OnEditorTooltip(), MainFrame::OnEditSelectNext(), MainFrame::OnEditSelectNextSkip(), EditorManager::Open(), cbDebuggerPlugin::ProcessValueTooltip(), MacrosManager::RecalcVars(), RefreshBreakpoints(), ScriptBindings::RegisterBindings(), Wiz::RunFilesWizard(), EditorManager::SetActiveEditor(), and DebugInterfaceFactory::ShowValueTooltip().
IsContextMenuOpened()
bool EditorBase::IsContextMenuOpened () const virtual
Is there a context (right click) menu open.
Returns
True if a context menu is open, false if not.
Definition at line 441 of file editorbase.cpp.
References EditorBaseInternalData::m_DisplayingPopupMenu, and m_pData.
Referenced by CCManager::OnEditorTooltip(), and cbDebuggerPlugin::ProcessValueTooltip().
IsReadOnly()
virtual bool EditorBase::IsReadOnly () const inline virtual
Is the editor read-only?
Returns
True if the editor is read-only, false if not.
Reimplemented in cbEditor.
Definition at line 217 of file editorbase.h.
Referenced by EditorManager::CheckForExternallyModifiedFiles(), cbEditor::GetLastModificationTime(), MainFrame::OnEditMenuUpdateUI(), ScriptBindings::RegisterBindings(), and SetTitle().
OnAfterBuildContextMenu()
virtual void EditorBase::OnAfterBuildContextMenu (cb_optional ModuleType type) inline protected virtual
Informs the editor we 're done creating the context menu (just about to display it).
Default implementation does nothing.
Parameters
type specifies the "ModuleType" context popup menu.
Definition at line 276 of file editorbase.h.
Referenced by DisplayContextMenu().
OnBeforeBuildContextMenu()
virtual bool EditorBase::OnBeforeBuildContextMenu (cb_optional const wxPoint & position, cb_optional ModuleType type) inline protected virtual
Informs the editor we 're just about to create a context menu.
Default implementation, just returns true.
Parameters
position specifies the position of the popup menu.
type specifies the "ModuleType" popup menu.
Returns
If the editor returns false, the context menu creation is aborted.
Definition at line 270 of file editorbase.h.
Referenced by DisplayContextMenu(), and cbEditor::OnBeforeBuildContextMenu().
OnContextMenuEntry()
void EditorBase::OnContextMenuEntry (wxCommandEvent & event) private
one event handler for all popup menu entries
Definition at line 379 of file editorbase.cpp.
References _T, EditorManager::Close(), EditorManager::CloseAllInTabCtrl(), EditorManager::CloseAllInTabCtrlExcept(), Manager::Get(), Manager::GetEditorManager(), idCloseAll, idCloseAllOthers, idCloseMe, idCodeProject, idCPlusPlusCom, idGoogle, idMsdn, idSaveAll, idSaveMe, idStackOverflow, idSwitchFile1, idSwitchFileMax, lastWord, EditorBaseInternalData::m_CloseMe, EditorBaseInternalData::m_DisplayingPopupMenu, m_pData, m_SwitchTo, Save(), EditorManager::SaveAll(), EditorManager::SetActiveEditor(), URLEncode(), and wxLaunchDefaultBrowser().
operator=()
void EditorBase::operator= (cb_optional const EditorBase & rhs) inline
Don't use this.
It throws an exception if you do.
Definition at line 39 of file editorbase.h.
References _T, and cbThrow.
Paste()
virtual void EditorBase::Paste () inline virtual
Paste selected text/object from clipboard.
Reimplemented in cbEditor.
Definition at line 187 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditPaste(), and ScriptBindings::RegisterBindings().
QueryClose()
bool EditorBase::QueryClose () virtual
Can this be closed (destroyed)?
This is used internally and queries the editor if it is safe to close it (i.e. it is not modified).
Returns
True if this editor can be closed.
Definition at line 180 of file editorbase.cpp.
References _(), cbMessageBox(), GetFilename(), GetModified(), wxString::Printf(), Save(), SetModified(), wxCANCEL, wxICON_QUESTION, wxID_CANCEL, wxID_NO, wxID_YES, and wxYES_NO.
Referenced by EditorManager::QueryClose().
Redo()
virtual void EditorBase::Redo () inline virtual
Redo changes.
Reimplemented in cbEditor.
Definition at line 166 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditRedo(), and ScriptBindings::RegisterBindings().
Save()
virtual bool EditorBase::Save () inline virtual
Save contents.
Save the editor's contents. The default implementation does nothing and returns true.
Returns
True on success, false otherwise.
Reimplemented in cbEditor.
Definition at line 113 of file editorbase.h.
Referenced by EditorManager::CheckForExternallyModifiedFiles(), cbEditor::GetProjectFile(), OnContextMenuEntry(), QueryClose(), ScriptBindings::RegisterBindings(), EditorManager::Save(), EditorManager::SaveActive(), and EditorManager::SaveAll().
SaveAs()
virtual bool EditorBase::SaveAs () inline virtual
Save editor contents under a different filename.
Save editor contents under a different filename. The default implementation does nothing and returns true.
Returns
True on success, false otherwise.
Reimplemented in cbEditor.
Definition at line 120 of file editorbase.h.
References mtUnknown.
Referenced by cbEditor::GetProjectFile(), EditorManager::SaveActiveAs(), and EditorManager::SaveAs().
SelectAll()
virtual void EditorBase::SelectAll () inline virtual
Select everything in the editor.
Reimplemented in cbEditor.
Definition at line 233 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), and MainFrame::OnEditSelectAll().
SetChangeCollection()
virtual void EditorBase::SetChangeCollection (cb_optional bool collectChange) inline virtual
Enable or disable changebar.
Definition at line 178 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime().
SetFilename()
virtual void EditorBase::SetFilename (const wxString & filename) inline virtual
Sets the editor's filename.
Parameters
filename The filename to set.
Definition at line 50 of file editorbase.h.
Referenced by NewFromTemplateDlg::EditScript(), and ScriptBindings::RegisterBindings().
SetModified()
virtual void EditorBase::SetModified (bool = true) inline virtual
Set the modification status.
Parameters
modified If true, mark as modified. If false, mark as clean (unmodified).
Reimplemented in cbEditor.
Definition at line 73 of file editorbase.h.
Referenced by EditorManager::CheckForExternallyModifiedFiles(), cbEditor::IsOK(), QueryClose(), and ScriptBindings::RegisterBindings().
SetReadOnly()
virtual void EditorBase::SetReadOnly (bool = true) inline virtual
Set the editor read-only.
Parameters
readonly If true, mark as readonly. If false, mark as read-write.
Reimplemented in cbEditor.
Definition at line 223 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime().
SetTitle()
void EditorBase::SetTitle (const wxString & newTitle) virtual
Set the editor's title.
Parameters
newTitle The new title to set.
Definition at line 149 of file editorbase.cpp.
References _(), wxFile::Access(), wxFileName::FileExists(), EditorManager::FindPageFromEditor(), ProjectManager::FindProjectForFile(), Manager::Get(), Manager::GetEditorManager(), GetFilename(), wxFileName::GetFullPath(), EditorManager::GetNotebook(), wxAuiNotebook::GetPageIndex(), Manager::GetProjectManager(), IsReadOnly(), m_WinTitle, EditorManager::MarkReadOnly(), NormalizePath(), realpath(), wxAuiNotebook::SetPageText(), wxAuiNotebook::SetPageToolTip(), UnixFilename(), wxFile::write, and wxEmptyString.
Referenced by EditorBase(), ScriptBindings::RegisterBindings(), and cbEditor::SetEditorTitle().
ThereAreOthers()
bool EditorBase::ThereAreOthers () const virtual
Are there other editors besides this?
Returns
True if there are more editors open, false otherwise.
Definition at line 214 of file editorbase.cpp.
References Manager::Get().
Referenced by BasicAddToContextMenu(), and ScriptBindings::RegisterBindings().
Undo()
virtual void EditorBase::Undo () inline virtual
Undo changes.
Reimplemented in cbEditor.
Definition at line 163 of file editorbase.h.
Referenced by cbEditor::GetLastModificationTime(), MainFrame::OnEditUndo(), and ScriptBindings::RegisterBindings().
VisibleToTree()
virtual bool EditorBase::VisibleToTree () const inline virtual
Should this kind of editor be visible in the open files tree?
There are rare cases where an editor should not be visible in the open files tree. One such example is the "Start here" page...
Returns
True if it should be visible in the open files tree, false if not.
Reimplemented in StartHerePage.
Definition at line 151 of file editorbase.h.
Member Data Documentation
lastWord
wxString EditorBase::lastWord private
Definition at line 290 of file editorbase.h.
Referenced by DisplayContextMenu(), and OnContextMenuEntry().
m_Filename
wxString EditorBase::m_Filename protected
Definition at line 280 of file editorbase.h.
Referenced by cbEditor::AddBreakpoint(), DisplayContextMenu(), cbEditor::DoInitializations(), cbEditor::OnContextMenuEntry(), cbEditor::Open(), cbEditor::Print(), cbEditor::RemoveBreakpoint(), cbEditor::Save(), cbEditor::SaveAs(), cbEditor::SetProjectFile(), cbEditor::ToggleBreakpoint(), and ~EditorBase().
m_IsBuiltinEditor
bool EditorBase::m_IsBuiltinEditor protected
Definition at line 278 of file editorbase.h.
Referenced by cbEditor::DoInitializations(), and IsBuiltinEditor().
m_pData
EditorBaseInternalData* EditorBase::m_pData protected
Use this to add new vars/functions w/out breaking the ABI.
Definition at line 281 of file editorbase.h.
Referenced by DisplayContextMenu(), EditorBase(), IsContextMenuOpened(), OnContextMenuEntry(), and ~EditorBase().
m_Shortname
wxString EditorBase::m_Shortname protected
Definition at line 279 of file editorbase.h.
Referenced by EditorBase(), cbEditor::SaveAs(), cbEditor::SetEditorStyleBeforeFileOpen(), cbEditor::SetModified(), and cbEditor::SetProjectFile().
m_SwitchTo
SwitchToMap EditorBase::m_SwitchTo private
Definition at line 288 of file editorbase.h.
Referenced by CreateContextSubMenu(), and OnContextMenuEntry().
m_WinTitle
wxString EditorBase::m_WinTitle private
Definition at line 289 of file editorbase.h.
Referenced by GetTitle(), and SetTitle().
The documentation for this class was generated from the following files:
editorbase.h
editorbase.cpp