Code::Blocks: ProjectOptionsDlg Class Reference
ProjectOptionsDlg Class Reference
#include <projectoptionsdlg.h>
Public Member Functions
ProjectOptionsDlg (wxWindow *parent, cbProject *project)
~ProjectOptionsDlg ()
void EndModal (int retCode)
void OnFileOptionsClick (wxCommandEvent &event)
void OnFileToggleMarkClick (wxCommandEvent &event)
void OnFileMarkOnClick (wxCommandEvent &event)
void OnFileMarkOffClick (wxCommandEvent &event)
void OnProjectTypeChanged (wxCommandEvent &event)
void OnBuildTargetChanged (wxCommandEvent &event)
void OnAddBuildTargetClick (wxCommandEvent &event)
void OnEditBuildTargetClick (wxCommandEvent &event)
void OnCopyBuildTargetClick (wxCommandEvent &event)
void OnRemoveBuildTargetClick (wxCommandEvent &event)
void OnBrowseOutputFilenameClick (wxCommandEvent &event)
void OnBrowseImportLibraryFilenameClick (wxCommandEvent &event)
void OnBrowseDefinitionFileFilenameClick (wxCommandEvent &event)
void OnBrowseDirClick (wxCommandEvent &event)
void OnVirtualTargets (wxCommandEvent &event)
void OnEditDepsClick (wxCommandEvent &event)
void OnExportTargetClick (wxCommandEvent &event)
void OnBuildOrderClick (wxCommandEvent &event)
void OnProjectBuildOptionsClick (wxCommandEvent &event)
void OnProjectDepsClick (wxCommandEvent &event)
void OnTargetBuildOptionsClick (wxCommandEvent &event)
void OnPlatform (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void OnOK (wxCommandEvent &event)
void OnCreateDefFileClick (wxCommandEvent &event)
void OnCreateImportFileClick (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
void OnScriptsOverviewSelChanged (wxTreeEvent &event)
void OnCheckScripts (wxCommandEvent &event)
void OnAddScript (wxCommandEvent &event)
void OnRemoveScript (wxCommandEvent &event)
void OnScriptMoveUp (wxSpinEvent &event)
void OnScriptMoveDown (wxSpinEvent &event)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Private Member Functions
void BuildScriptsTree ()
void AddPluginPanels ()
void FillScripts ()
void FillBuildTargets ()
void DoTargetChange (bool saveOld=true)
void DoBeforeTargetChange (bool force=false)
bool DoCheckScripts (CompileTargetBase *base)
bool IsScriptValid (ProjectBuildTarget *target, const wxString &script)
bool ValidateTargetName (const wxString &name)
void UpdateTargetControls ()
Private Attributes
cbProject * m_Project
int m_Current_Sel
cbCompilerPlugin * m_pCompiler
ConfigurationPanelsArray m_PluginPanels
Detailed Description
Definition at line 20 of file projectoptionsdlg.h.
Constructor & Destructor Documentation
ProjectOptionsDlg()
ProjectOptionsDlg::ProjectOptionsDlg (wxWindow * parent, cbProject * project)
Definition at line 100 of file projectoptionsdlg.cpp.
References _T, wxXmlResource::Get(), Manager::Get(), CompilerFactory::GetCompiler(), PluginManager::GetCompilerOffers(), Manager::GetPluginManager(), GetStringFromPlatforms(), Compiler::GetSwitches(), wxXmlResource::LoadObject(), OnKeyDown(), wxCheckListBox::SetSelection(), CompilerSwitches::supportsPCH, and wxEVT_KEY_DOWN.
~ProjectOptionsDlg()
ProjectOptionsDlg::~ProjectOptionsDlg ()
Definition at line 162 of file projectoptionsdlg.cpp.
References OnKeyDown(), and wxEVT_KEY_DOWN.
Member Function Documentation
AddPluginPanels()
void ProjectOptionsDlg::AddPluginPanels () private
Definition at line 198 of file projectoptionsdlg.cpp.
References wxBookCtrlBase::AddPage(), Manager::Get(), Manager::GetPluginManager(), PluginManager::GetProjectConfigurationPanels(), cbConfigurationPanel::GetTitle(), m_PluginPanels, m_Project, and cbConfigurationPanel::SetParentDialog().
BuildScriptsTree()
void ProjectOptionsDlg::BuildScriptsTree () private
Definition at line 182 of file projectoptionsdlg.cpp.
References wxTreeCtrl::AddRoot(), wxTreeCtrl::AppendItem(), wxTreeCtrl::DeleteAllItems(), wxTreeCtrl::Expand(), FillScripts(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompileTargetBase::GetTitle(), m_Project, and wxTreeCtrl::SelectItem().
Referenced by OnAddBuildTargetClick(), OnCopyBuildTargetClick(), OnEditBuildTargetClick(), and OnRemoveBuildTargetClick().
DoBeforeTargetChange()
void ProjectOptionsDlg::DoBeforeTargetChange (bool force = false) private
Definition at line 359 of file projectoptionsdlg.cpp.
References ProjectFile::AddBuildTarget(), wxFileName::Assign(), cbProject::GetBuildTarget(), wxCheckListBox::GetCount(), cbProject::GetFileByFilename(), wxFileName::GetFullPath(), GetPlatformsFromString(), wxCheckListBox::GetString(), CompileTargetBase::GetTitle(), wxCheckListBox::IsChecked(), m_Current_Sel, m_Project, ProjectFile::RemoveBuildTarget(), ProjectBuildTarget::SetCreateDefFile(), ProjectBuildTarget::SetCreateStaticLib(), CompileTargetBase::SetDefinitionFileFilename(), CompileTargetBase::SetImportLibraryFilename(), CompileTargetBase::SetObjectOutput(), CompileTargetBase::SetOutputFilename(), CompileOptionsBase::SetPlatforms(), CompileTargetBase::SetTargetFilenameGenerationPolicy(), ProjectBuildTarget::SetTargetType(), ProjectBuildTarget::SetUseConsoleRunner(), CompileTargetBase::SetWorkingDir(), tgfpNone, and tgfpPlatformDefault.
Referenced by DoTargetChange(), EndModal(), and OnBuildOrderClick().
DoCheckScripts()
bool ProjectOptionsDlg::DoCheckScripts (CompileTargetBase * base) private
Definition at line 1022 of file projectoptionsdlg.cpp.
References _(), _T, cbMessageBox(), CompileOptionsBase::GetBuildScripts(), wxArrayString::GetCount(), CompileTargetBase::GetTitle(), IsScriptValid(), and wxICON_ERROR.
Referenced by OnCheckScripts().
DoTargetChange()
void ProjectOptionsDlg::DoTargetChange (bool saveOld = true) private
Definition at line 237 of file projectoptionsdlg.cpp.
References _T, ProjectFile::buildTargets, wxCheckListBox::Check(), DoBeforeTargetChange(), cbProject::GetBuildTarget(), wxCheckListBox::GetCount(), ProjectBuildTarget::GetCreateDefFile(), ProjectBuildTarget::GetCreateStaticLib(), CompileTargetBase::GetDynamicLibDefFilename(), CompileTargetBase::GetDynamicLibImportFilename(), cbProject::GetFileByFilename(), CompileTargetBase::GetObjectOutput(), CompileTargetBase::GetOutputFilename(), CompileOptionsBase::GetPlatforms(), wxCheckListBox::GetString(), GetStringFromPlatforms(), CompileTargetBase::GetTargetFilenameGenerationPolicy(), CompileTargetBase::GetTargetType(), CompileTargetBase::GetTitle(), ProjectBuildTarget::GetUseConsoleRunner(), CompileTargetBase::GetWorkingDir(), wxArrayString::Index(), wxCheckBox::IsChecked(), m_Current_Sel, m_Project, wxCheckBox::SetValue(), tgfpPlatformDefault, ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttExecutable, ttNative, and ttStaticLib.
Referenced by FillBuildTargets(), OnAddBuildTargetClick(), OnBuildOrderClick(), OnBuildTargetChanged(), OnCopyBuildTargetClick(), and OnRemoveBuildTargetClick().
EndModal()
void ProjectOptionsDlg::EndModal (int retCode)
Definition at line 1325 of file projectoptionsdlg.cpp.
References DoBeforeTargetChange(), ScriptBindings::EndModal(), GetPlatformsFromString(), m_Current_Sel, m_PluginPanels, m_Project, cbConfigurationPanel::OnApply(), cbConfigurationPanel::OnCancel(), cbProject::SetCheckForExternallyModifiedFiles(), cbProject::SetExtendedObjectNamesGeneration(), cbProject::SetMakefile(), cbProject::SetMakefileCustom(), cbProject::SetMakefileExecutionDir(), cbProject::SetModeForPCH(), cbProject::SetNotes(), CompileOptionsBase::SetPlatforms(), cbProject::SetShowNotesOnLoad(), CompileTargetBase::SetTargetType(), cbProject::SetTitle(), and wxID_OK.
FillBuildTargets()
void ProjectOptionsDlg::FillBuildTargets () private
Definition at line 226 of file projectoptionsdlg.cpp.
References DoTargetChange(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompileTargetBase::GetTitle(), and m_Project.
Referenced by OnBuildOrderClick().
FillScripts()
void ProjectOptionsDlg::FillScripts () private
Definition at line 212 of file projectoptionsdlg.cpp.
References CompileOptionsBase::GetBuildScripts(), cbProject::GetBuildTarget(), wxArrayString::GetCount(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetRootItem(), wxTreeCtrl::GetSelection(), wxArrayString::Item(), and m_Project.
Referenced by BuildScriptsTree(), and OnScriptsOverviewSelChanged().
IsScriptValid()
bool ProjectOptionsDlg::IsScriptValid (ProjectBuildTarget * target, const wxString & script) private
Definition at line 968 of file projectoptionsdlg.cpp.
References _T, ScriptingManager::DisplayErrors(), Manager::Get(), CompileTargetBase::GetBasePath(), Manager::GetMacrosManager(), Manager::GetScriptingManager(), wxFileName::IsAbsolute(), ScriptingManager::LoadBuffer(), ScriptingManager::LoadScript(), m_Project, and MacrosManager::ReplaceMacros().
Referenced by DoCheckScripts().
OnAddBuildTargetClick()
void ProjectOptionsDlg::OnAddBuildTargetClick (wxCommandEvent & event)
Definition at line 633 of file projectoptionsdlg.cpp.
References _(), cbProject::AddBuildTarget(), BuildScriptsTree(), cbEVT_PROJECT_TARGETS_MODIFIED, cbGetTextFromUser(), cbMessageBox(), DoTargetChange(), Manager::Get(), Manager::GetPluginManager(), m_Project, PluginManager::NotifyPlugins(), CodeBlocksEvent::SetProject(), ValidateTargetName(), wxICON_ERROR, and wxOK.
OnAddScript()
void ProjectOptionsDlg::OnAddScript (wxCommandEvent & event)
Definition at line 1054 of file projectoptionsdlg.cpp.
References _(), CompileOptionsBase::AddBuildScript(), wxFileName::Assign(), GetArrayFromString(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), wxArrayString::GetCount(), wxFileName::GetFullName(), wxFileName::GetFullPath(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetRootItem(), wxTreeCtrl::GetSelection(), m_Project, wxFileName::MakeRelativeTo(), wxFileName::Normalize(), PlaceWindow(), wxEmptyString, wxID_OK, wxPATH_NORM_ALL, and wxPATH_NORM_CASE.
OnBrowseDefinitionFileFilenameClick()
void ProjectOptionsDlg::OnBrowseDefinitionFileFilenameClick (wxCommandEvent & event)
Definition at line 860 of file projectoptionsdlg.cpp.
References _(), wxFileName::Assign(), CompileTargetBase::GetBasePath(), FileFilters::GetFilterAll(), wxFileName::GetFullName(), wxFileName::GetFullPath(), wxFileName::GetPath(), m_Project, wxFileName::MakeRelativeTo(), wxFileName::Normalize(), PlaceWindow(), wxFD_OVERWRITE_PROMPT, wxFD_SAVE, wxID_OK, wxPATH_NORM_ALL, and wxPATH_NORM_CASE.
OnBrowseDirClick()
void ProjectOptionsDlg::OnBrowseDirClick (wxCommandEvent & event)
Definition at line 792 of file projectoptionsdlg.cpp.
References _(), ChooseDirectory(), CompileTargetBase::GetBasePath(), wxFileName::GetPathSeparator(), wxString::IsEmpty(), m_Project, wxFileName::Normalize(), wxPATH_NORM_ALL, and wxPATH_NORM_CASE.
OnBrowseImportLibraryFilenameClick()
void ProjectOptionsDlg::OnBrowseImportLibraryFilenameClick (wxCommandEvent & event)
Definition at line 840 of file projectoptionsdlg.cpp.
References _(), wxFileName::Assign(), CompileTargetBase::GetBasePath(), FileFilters::GetFilterAll(), wxFileName::GetFullName(), wxFileName::GetFullPath(), wxFileName::GetPath(), m_Project, wxFileName::MakeRelativeTo(), wxFileName::Normalize(), PlaceWindow(), wxFD_OVERWRITE_PROMPT, wxFD_SAVE, wxID_OK, wxPATH_NORM_ALL, and wxPATH_NORM_CASE.
OnBrowseOutputFilenameClick()
void ProjectOptionsDlg::OnBrowseOutputFilenameClick (wxCommandEvent & event)
Definition at line 820 of file projectoptionsdlg.cpp.
References _(), wxFileName::Assign(), CompileTargetBase::GetBasePath(), FileFilters::GetFilterAll(), wxFileName::GetFullName(), wxFileName::GetFullPath(), wxFileName::GetPath(), m_Project, wxFileName::MakeRelativeTo(), wxFileName::Normalize(), PlaceWindow(), wxFD_OVERWRITE_PROMPT, wxFD_SAVE, wxID_OK, wxPATH_NORM_ALL, and wxPATH_NORM_CASE.
OnBuildOrderClick()
void ProjectOptionsDlg::OnBuildOrderClick (wxCommandEvent & event)
Definition at line 578 of file projectoptionsdlg.cpp.
References wxArrayString::Add(), cbEVT_PROJECT_TARGETS_MODIFIED, DoBeforeTargetChange(), DoTargetChange(), FillBuildTargets(), Manager::Get(), EditArrayOrderDlg::GetArray(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), Manager::GetPluginManager(), CompileTargetBase::GetTitle(), wxString::IsEmpty(), m_Project, PluginManager::NotifyPlugins(), PlaceWindow(), cbProject::ReOrderTargets(), CodeBlocksEvent::SetProject(), wxDialog::ShowModal(), wxID_OK, and wxNOT_FOUND.
OnBuildTargetChanged()
void ProjectOptionsDlg::OnBuildTargetChanged (wxCommandEvent & event)
Definition at line 570 of file projectoptionsdlg.cpp.
References cbEVT_PROJECT_TARGETS_MODIFIED, DoTargetChange(), Manager::Get(), Manager::GetPluginManager(), m_Project, PluginManager::NotifyPlugins(), and CodeBlocksEvent::SetProject().
OnCheckScripts()
void ProjectOptionsDlg::OnCheckScripts (wxCommandEvent & event)
Definition at line 1040 of file projectoptionsdlg.cpp.
References _(), cbMessageBox(), DoCheckScripts(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), m_Project, and wxICON_INFORMATION.
OnCopyBuildTargetClick()
void ProjectOptionsDlg::OnCopyBuildTargetClick (wxCommandEvent & event)
Definition at line 688 of file projectoptionsdlg.cpp.
References _(), BuildScriptsTree(), cbEVT_PROJECT_TARGETS_MODIFIED, cbGetTextFromUser(), cbMessageBox(), DoTargetChange(), cbProject::DuplicateBuildTarget(), Manager::Get(), cbProject::GetBuildTarget(), Manager::GetPluginManager(), CompileTargetBase::GetTitle(), m_Project, PluginManager::NotifyPlugins(), CodeBlocksEvent::SetProject(), ValidateTargetName(), wxICON_ERROR, and wxOK.
OnCreateDefFileClick()
void ProjectOptionsDlg::OnCreateDefFileClick (wxCommandEvent & event)
Definition at line 1259 of file projectoptionsdlg.cpp.
References cbProject::GetBuildTarget(), CompileOptionsBase::GetPlatforms(), GetStringFromPlatforms(), wxCheckBox::IsChecked(), m_Project, and ttDynamicLib.
OnCreateImportFileClick()
void ProjectOptionsDlg::OnCreateImportFileClick (wxCommandEvent & event)
Definition at line 1286 of file projectoptionsdlg.cpp.
References Manager::Get(), cbProject::GetBuildTarget(), CompileOptionsBase::GetPlatforms(), Manager::GetProjectManager(), cbProject::GetProjectNode(), GetStringFromPlatforms(), CompileTargetBase::GetTitle(), cbProjectManagerUI::GetTree(), ProjectManager::GetUI(), wxCheckBox::IsChecked(), m_Project, wxTreeCtrl::SetItemText(), and ttDynamicLib.
OnEditBuildTargetClick()
void ProjectOptionsDlg::OnEditBuildTargetClick (wxCommandEvent & event)
Definition at line 659 of file projectoptionsdlg.cpp.
References _(), BuildScriptsTree(), cbEVT_PROJECT_TARGETS_MODIFIED, cbGetTextFromUser(), cbMessageBox(), Manager::Get(), cbProject::GetBuildTarget(), Manager::GetPluginManager(), CompileTargetBase::GetTitle(), m_Project, PluginManager::NotifyPlugins(), cbProject::RenameBuildTarget(), CodeBlocksEvent::SetProject(), ValidateTargetName(), wxICON_ERROR, and wxOK.
OnEditDepsClick()
void ProjectOptionsDlg::OnEditDepsClick (wxCommandEvent & event)
Definition at line 761 of file projectoptionsdlg.cpp.
References cbProject::GetBuildTarget(), m_Project, PlaceWindow(), and wxDialog::ShowModal().
OnExportTargetClick()
void ProjectOptionsDlg::OnExportTargetClick (wxCommandEvent & event)
Definition at line 773 of file projectoptionsdlg.cpp.
References _(), cbMessageBox(), cbProject::ExportTargetAsProject(), cbProject::GetBuildTarget(), CompileTargetBase::GetTitle(), m_Project, AnnoyingDialog::rtYES, AnnoyingDialog::ShowModal(), wxART_QUESTION, and wxICON_INFORMATION.
OnFileMarkOffClick()
void ProjectOptionsDlg::OnFileMarkOffClick (wxCommandEvent & event)
Definition at line 939 of file projectoptionsdlg.cpp.
References _(), _T, cbGetTextFromUser(), wxCheckListBox::Check(), cbProject::GetBuildTarget(), wxCheckListBox::GetCount(), cbProject::GetFileByFilename(), wxCheckListBox::GetString(), CompileTargetBase::GetTitle(), wxString::IsEmpty(), m_Project, ProjectFile::RemoveBuildTarget(), and wxMatchWild().
OnFileMarkOnClick()
void ProjectOptionsDlg::OnFileMarkOnClick (wxCommandEvent & event)
Definition at line 915 of file projectoptionsdlg.cpp.
References _(), _T, ProjectFile::AddBuildTarget(), cbGetTextFromUser(), wxCheckListBox::Check(), cbProject::GetBuildTarget(), wxCheckListBox::GetCount(), cbProject::GetFileByFilename(), wxCheckListBox::GetString(), CompileTargetBase::GetTitle(), wxString::IsEmpty(), m_Project, and wxMatchWild().
OnFileOptionsClick()
void ProjectOptionsDlg::OnFileOptionsClick (wxCommandEvent & event)
Definition at line 880 of file projectoptionsdlg.cpp.
References cbProject::GetFileByFilename(), wxCheckListBox::GetSelection(), wxCheckListBox::GetString(), m_Project, and ProjectFile::ShowOptions().
OnFileToggleMarkClick()
void ProjectOptionsDlg::OnFileToggleMarkClick (wxCommandEvent & event)
Definition at line 892 of file projectoptionsdlg.cpp.
References ProjectFile::AddBuildTarget(), wxCheckListBox::Check(), cbProject::GetBuildTarget(), wxCheckListBox::GetCount(), cbProject::GetFileByFilename(), wxCheckListBox::GetString(), CompileTargetBase::GetTitle(), wxCheckListBox::IsChecked(), m_Project, and ProjectFile::RemoveBuildTarget().
OnKeyDown()
void ProjectOptionsDlg::OnKeyDown (wxKeyEvent & event)
Definition at line 168 of file projectoptionsdlg.cpp.
References wxKeyboardState::ControlDown(), Manager::Get(), wxKeyEvent::GetKeyCode(), Manager::GetMacrosManager(), and MacrosManager::ReplaceMacros().
Referenced by ProjectOptionsDlg(), and ~ProjectOptionsDlg().
OnOK()
void ProjectOptionsDlg::OnOK (wxCommandEvent & event)
Definition at line 1248 of file projectoptionsdlg.cpp.
References _(), cbMessageBox(), wxCENTRE, wxICON_ERROR, and wxOK.
OnPlatform()
void ProjectOptionsDlg::OnPlatform (wxCommandEvent & event)
Definition at line 1118 of file projectoptionsdlg.cpp.
References _(), GetArrayFromString(), wxArrayString::GetCount(), MultiSelectDlg::GetSelectedStrings(), GetStringFromArray(), GetStringFromPlatforms(), MultiSelectDlg::SelectWildCard(), wxDialog::ShowModal(), spAll, and wxID_OK.
OnProjectBuildOptionsClick()
void ProjectOptionsDlg::OnProjectBuildOptionsClick (wxCommandEvent & event)
Definition at line 614 of file projectoptionsdlg.cpp.
References cbCompilerPlugin::Configure(), m_pCompiler, and m_Project.
OnProjectDepsClick()
void ProjectOptionsDlg::OnProjectDepsClick (wxCommandEvent & event)
Definition at line 609 of file projectoptionsdlg.cpp.
References cbProjectManagerUI::ConfigureProjectDependencies(), Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetUI(), and m_Project.
OnProjectTypeChanged()
void ProjectOptionsDlg::OnProjectTypeChanged (wxCommandEvent & event)
Definition at line 423 of file projectoptionsdlg.cpp.
References _T, FileFilters::DYNAMICLIB_EXT, FileFilters::EXECUTABLE_EXT, cbProject::GetBuildTarget(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompileTargetBase::GetDynamicLibDefFilename(), CompileTargetBase::GetDynamicLibImportFilename(), wxFileName::GetFullPath(), wxFileName::GetName(), CompileTargetBase::GetObjectOutput(), CompileTargetBase::GetOutputFilename(), Compiler::GetSwitches(), CompileTargetBase::GetWorkingDir(), wxCheckBox::IsChecked(), wxString::IsEmpty(), wxString::Length(), CompilerSwitches::libExtension, CompilerSwitches::libPrefix, m_Current_Sel, m_Project, FileFilters::NATIVE_EXT, wxString::Prepend(), wxString::Remove(), wxFileName::SetExt(), wxFileName::SetName(), wxString::StartsWith(), FileFilters::STATICLIB_EXT, ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttExecutable, ttNative, and ttStaticLib.
OnRemoveBuildTargetClick()
void ProjectOptionsDlg::OnRemoveBuildTargetClick (wxCommandEvent & event)
Definition at line 722 of file projectoptionsdlg.cpp.
References _(), BuildScriptsTree(), cbEVT_PROJECT_TARGETS_MODIFIED, cbMessageBox(), DoTargetChange(), Manager::Get(), Manager::GetLogManager(), Manager::GetPluginManager(), LogManager::Log(), m_Current_Sel, m_Project, PluginManager::NotifyPlugins(), wxString::Printf(), cbProject::RemoveBuildTarget(), CodeBlocksEvent::SetProject(), wxICON_QUESTION, wxID_NO, wxNO_DEFAULT, wxNOT_FOUND, and wxYES_NO.
OnRemoveScript()
void ProjectOptionsDlg::OnRemoveScript (wxCommandEvent & event)
Definition at line 1097 of file projectoptionsdlg.cpp.
References cbProject::GetBuildTarget(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetRootItem(), wxTreeCtrl::GetSelection(), wxString::IsEmpty(), m_Project, and CompileOptionsBase::RemoveBuildScript().
OnScriptMoveDown()
void ProjectOptionsDlg::OnScriptMoveDown (wxSpinEvent & event)
Definition at line 1173 of file projectoptionsdlg.cpp.
References CompileOptionsBase::GetBuildScripts(), cbProject::GetBuildTarget(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetRootItem(), wxTreeCtrl::GetSelection(), wxArrayString::Insert(), m_Project, wxArrayString::RemoveAt(), and CompileOptionsBase::SetBuildScripts().
OnScriptMoveUp()
void ProjectOptionsDlg::OnScriptMoveUp (wxSpinEvent & event)
Definition at line 1149 of file projectoptionsdlg.cpp.
References CompileOptionsBase::GetBuildScripts(), cbProject::GetBuildTarget(), wxTreeCtrl::GetItemText(), wxTreeCtrl::GetRootItem(), wxTreeCtrl::GetSelection(), wxArrayString::Insert(), m_Project, wxArrayString::RemoveAt(), and CompileOptionsBase::SetBuildScripts().
OnScriptsOverviewSelChanged()
void ProjectOptionsDlg::OnScriptsOverviewSelChanged (wxTreeEvent & event)
Definition at line 963 of file projectoptionsdlg.cpp.
References FillScripts().
OnTargetBuildOptionsClick()
void ProjectOptionsDlg::OnTargetBuildOptionsClick (wxCommandEvent & event)
Definition at line 620 of file projectoptionsdlg.cpp.
References cbCompilerPlugin::Configure(), cbProject::GetBuildTarget(), m_pCompiler, and m_Project.
OnUpdateUI()
void ProjectOptionsDlg::OnUpdateUI (wxUpdateUIEvent & event)
Definition at line 1197 of file projectoptionsdlg.cpp.
References wxCheckListBox::GetSelection(), wxTreeCtrl::GetSelection(), wxTreeItemId::IsOk(), and m_pCompiler.
OnVirtualTargets()
void ProjectOptionsDlg::OnVirtualTargets (wxCommandEvent & event)
Definition at line 755 of file projectoptionsdlg.cpp.
References m_Project, and wxDialog::ShowModal().
UpdateTargetControls()
void ProjectOptionsDlg::UpdateTargetControls () private
ValidateTargetName()
bool ProjectOptionsDlg::ValidateTargetName (const wxString & name) private
Definition at line 992 of file projectoptionsdlg.cpp.
References _(), _T, cbMessageBox(), wxString::find_first_of(), cbProject::GetBuildTarget(), cbProject::HasVirtualBuildTarget(), wxString::IsEmpty(), m_Project, wxString::npos, wxCENTRE, wxICON_ERROR, and wxOK.
Referenced by OnAddBuildTargetClick(), OnCopyBuildTargetClick(), and OnEditBuildTargetClick().
Member Data Documentation
m_Current_Sel
int ProjectOptionsDlg::m_Current_Sel private
Definition at line 76 of file projectoptionsdlg.h.
Referenced by DoBeforeTargetChange(), DoTargetChange(), EndModal(), OnProjectTypeChanged(), and OnRemoveBuildTargetClick().
m_pCompiler
cbCompilerPlugin* ProjectOptionsDlg::m_pCompiler private
Definition at line 77 of file projectoptionsdlg.h.
Referenced by OnProjectBuildOptionsClick(), OnTargetBuildOptionsClick(), and OnUpdateUI().
m_PluginPanels
ConfigurationPanelsArray ProjectOptionsDlg::m_PluginPanels private
Definition at line 78 of file projectoptionsdlg.h.
Referenced by AddPluginPanels(), and EndModal().
m_Project
cbProject* ProjectOptionsDlg::m_Project private
Definition at line 75 of file projectoptionsdlg.h.
Referenced by AddPluginPanels(), BuildScriptsTree(), DoBeforeTargetChange(), DoTargetChange(), EndModal(), FillBuildTargets(), FillScripts(), IsScriptValid(), OnAddBuildTargetClick(), OnAddScript(), OnBrowseDefinitionFileFilenameClick(), OnBrowseDirClick(), OnBrowseImportLibraryFilenameClick(), OnBrowseOutputFilenameClick(), OnBuildOrderClick(), OnBuildTargetChanged(), OnCheckScripts(), OnCopyBuildTargetClick(), OnCreateDefFileClick(), OnCreateImportFileClick(), OnEditBuildTargetClick(), OnEditDepsClick(), OnExportTargetClick(), OnFileMarkOffClick(), OnFileMarkOnClick(), OnFileOptionsClick(), OnFileToggleMarkClick(), OnProjectBuildOptionsClick(), OnProjectDepsClick(), OnProjectTypeChanged(), OnRemoveBuildTargetClick(), OnRemoveScript(), OnScriptMoveDown(), OnScriptMoveUp(), OnTargetBuildOptionsClick(), OnVirtualTargets(), and ValidateTargetName().
The documentation for this class was generated from the following files:
projectoptionsdlg.h
projectoptionsdlg.cpp