Code::Blocks: IncrementalSelectListBase Class Reference
IncrementalSelectListBase Class Reference
#include <incrementalselectlistbase.h>
Public Member Functions
IncrementalSelectListBase (wxWindow *parent, const IncrementalSelectIterator &iterator, const wxString &dialog, const wxString &caption=wxEmptyString, const wxString &message=wxEmptyString)
virtual ~IncrementalSelectListBase ()
void OnSearch (wxCommandEvent &event)
void OnSelect (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void FilterItems ()
fetch the search key word from the text control, and filter the items
void KeyDownAction (wxKeyEvent &event, int &selected, int selectedMax)
handle user pressed some special key in the editor ctrl For example, if user press the UP key, we have to select some text before the cursor
void FillList ()
fill the m_List with filtered items
virtual void FillData ()
refresh the list
virtual void GetCurrentSelection (int &selected, int &selectedMax)
virtual void UpdateCurrentSelection (int selected, int selectedPrevious)
Protected Attributes
wxListBox * m_List
wxTextCtrl * m_Text
for showing the filtered items
wxArrayString m_Result
for entering search keys
wxArrayLong m_Indexes
the filtered items
bool m_Promoted
the filtered item index in the list
const IncrementalSelectIterator & m_Iterator
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Private Member Functions
DECLARE_EVENT_TABLE ()
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 17 of file incrementalselectlistbase.h.
Constructor & Destructor Documentation
IncrementalSelectListBase()
IncrementalSelectListBase::IncrementalSelectListBase (wxWindow * parent, const IncrementalSelectIterator & iterator, const wxString & dialog, const wxString & caption = wxEmptyString, const wxString & message = wxEmptyString)
Definition at line 29 of file incrementalselectlistbase.cpp.
References OnKeyDown().
~IncrementalSelectListBase()
IncrementalSelectListBase::~IncrementalSelectListBase () virtual
Definition at line 55 of file incrementalselectlistbase.cpp.
References m_List, m_Text, and OnKeyDown().
Member Function Documentation
DECLARE_EVENT_TABLE()
IncrementalSelectListBase::DECLARE_EVENT_TABLE () private
FillData()
virtual void IncrementalSelectListBase::FillData () inline protected virtual
refresh the list
Reimplemented in GotoFunctionDlg, and IncrementalSelectListDlg.
Definition at line 42 of file incrementalselectlistbase.h.
Referenced by OnSearch().
FillList()
void IncrementalSelectListBase::FillList (void) protected
fill the m_List with filtered items
Definition at line 145 of file incrementalselectlistbase.cpp.
References m_Indexes, m_List, and m_Result.
Referenced by IncrementalSelectListDlg::FillData(), and GotoFunctionDlg::FillData().
FilterItems()
void IncrementalSelectListBase::FilterItems () protected
fetch the search key word from the text control, and filter the items
Definition at line 67 of file incrementalselectlistbase.cpp.
References IncrementalSelectIterator::GetCount(), IncrementalSelectIterator::GetDisplayItem(), IncrementalSelectIterator::GetItem(), m_Indexes, m_Iterator, m_Promoted, m_Result, and m_Text.
Referenced by IncrementalSelectListDlg::FillData(), and GotoFunctionDlg::FillData().
GetCurrentSelection()
virtual void IncrementalSelectListBase::GetCurrentSelection (int & selected, int & selectedMax) inline protected virtual
Reimplemented in GotoFunctionDlg, and IncrementalSelectListDlg.
Definition at line 43 of file incrementalselectlistbase.h.
Referenced by OnKeyDown().
KeyDownAction()
void IncrementalSelectListBase::KeyDownAction (wxKeyEvent & event, int & selected, int selectedMax) protected
handle user pressed some special key in the editor ctrl For example, if user press the UP key, we have to select some text before the cursor
Definition at line 168 of file incrementalselectlistbase.cpp.
References ScriptBindings::EndModal().
Referenced by OnKeyDown().
OnKeyDown()
void IncrementalSelectListBase::OnKeyDown (wxKeyEvent & event)
Definition at line 234 of file incrementalselectlistbase.cpp.
References GetCurrentSelection(), KeyDownAction(), and UpdateCurrentSelection().
Referenced by GotoFunctionDlg::GotoFunctionDlg(), IncrementalSelectListBase(), GotoFunctionDlg::~GotoFunctionDlg(), and ~IncrementalSelectListBase().
OnSearch()
void IncrementalSelectListBase::OnSearch (wxCommandEvent & event)
Definition at line 158 of file incrementalselectlistbase.cpp.
References FillData().
OnSelect()
void IncrementalSelectListBase::OnSelect (wxCommandEvent & event)
Definition at line 163 of file incrementalselectlistbase.cpp.
References ScriptBindings::EndModal().
UpdateCurrentSelection()
virtual void IncrementalSelectListBase::UpdateCurrentSelection (int selected, int selectedPrevious) inline protected virtual
Reimplemented in GotoFunctionDlg, and IncrementalSelectListDlg.
Definition at line 44 of file incrementalselectlistbase.h.
Referenced by OnKeyDown().
Member Data Documentation
m_Indexes
wxArrayLong IncrementalSelectListBase::m_Indexes protected
the filtered items
Definition at line 51 of file incrementalselectlistbase.h.
Referenced by GotoFunctionDlg::FillColumn(), FillList(), and FilterItems().
m_Iterator
const IncrementalSelectIterator& IncrementalSelectListBase::m_Iterator protected
Definition at line 53 of file incrementalselectlistbase.h.
Referenced by FilterItems().
m_List
wxListBox* IncrementalSelectListBase::m_List protected
Definition at line 47 of file incrementalselectlistbase.h.
Referenced by FillList(), IncrementalSelectListDlg::GetCurrentSelection(), GotoFunctionDlg::GetCurrentSelection(), IncrementalSelectListDlg::GetSelection(), GotoFunctionDlg::GetSelection(), IncrementalSelectListDlg::GetStringSelection(), GotoFunctionDlg::SetupMode(), IncrementalSelectListDlg::UpdateCurrentSelection(), GotoFunctionDlg::UpdateCurrentSelection(), and ~IncrementalSelectListBase().
m_Promoted
bool IncrementalSelectListBase::m_Promoted protected
the filtered item index in the list
Definition at line 52 of file incrementalselectlistbase.h.
Referenced by GotoFunctionDlg::FillColumn(), and FilterItems().
m_Result
wxArrayString IncrementalSelectListBase::m_Result protected
for entering search keys
Definition at line 50 of file incrementalselectlistbase.h.
Referenced by GotoFunctionDlg::FillColumn(), FillList(), and FilterItems().
m_Text
wxTextCtrl* IncrementalSelectListBase::m_Text protected
for showing the filtered items
Definition at line 48 of file incrementalselectlistbase.h.
Referenced by FilterItems(), GotoFunctionDlg::SetupMode(), and ~IncrementalSelectListBase().
The documentation for this class was generated from the following files:
incrementalselectlistbase.h
incrementalselectlistbase.cpp