Code::Blocks: IncrementalSelectHandler Class Reference
IncrementalSelectHandler Class Reference
#include <incremental_select_helper.h>
Public Member Functions
IncrementalSelectHandler (wxDialog *parent, IncrementalSelectIterator *iterator)
~IncrementalSelectHandler () override
void Init (wxListCtrl *list, wxTextCtrl *text)
void DeInit (wxWindow *window)
void FilterItems ()
int GetSelection ()
Private Member Functions
void OnKeyDown (wxKeyEvent &event)
void OnTextChanged (wxCommandEvent &event)
void OnItemActivated (wxListEvent &event)
Private Attributes
wxDialog * m_parent
wxListCtrl * m_list
wxTextCtrl * m_text
IncrementalSelectIterator * m_iterator
Detailed Description
Definition at line 58 of file incremental_select_helper.h.
Constructor & Destructor Documentation
IncrementalSelectHandler()
IncrementalSelectHandler::IncrementalSelectHandler (wxDialog * parent, IncrementalSelectIterator * iterator)
Definition at line 54 of file incremental_select_helper.cpp.
References m_parent.
~IncrementalSelectHandler()
IncrementalSelectHandler::~IncrementalSelectHandler () override
Definition at line 64 of file incremental_select_helper.cpp.
Member Function Documentation
DeInit()
void IncrementalSelectHandler::DeInit (wxWindow * window)
Definition at line 84 of file incremental_select_helper.cpp.
References m_list, m_text, OnItemActivated(), OnKeyDown(), OnTextChanged(), and wxEVT_KEY_DOWN.
Referenced by GotoFile::~GotoFile(), and GotoFunctionDlg::~GotoFunctionDlg().
FilterItems()
void IncrementalSelectHandler::FilterItems ()
Definition at line 119 of file incremental_select_helper.cpp.
References IncrementalSelectIterator::AddIndex(), wxString::c_str(), wxString::empty(), FilterItemsFinalize(), wxString::find(), IncrementalSelectIterator::GetItemFilterString(), IncrementalSelectIterator::GetTotalCount(), wxString::Lower(), m_iterator, m_list, m_text, wxString::Matches(), wxString::npos, IncrementalSelectIterator::Reset(), wxIsalpha(), and wxT.
Referenced by Init(), GotoFunctionDlg::OnModeClick(), and OnTextChanged().
GetSelection()
int IncrementalSelectHandler::GetSelection ()
Definition at line 283 of file incremental_select_helper.cpp.
References wxListCtrl::GetNextItem(), IncrementalSelectIterator::GetUnfilteredIndex(), m_iterator, m_list, wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED, and wxNOT_FOUND.
Referenced by GotoFile::GetSelection(), and GotoFunctionDlg::GetSelection().
Init()
void IncrementalSelectHandler::Init (wxListCtrl * list, wxTextCtrl * text)
Definition at line 68 of file incremental_select_helper.cpp.
References IncrementalSelectIterator::CalcColumnWidth(), FilterItems(), m_iterator, m_list, m_text, OnItemActivated(), OnKeyDown(), OnTextChanged(), and wxEVT_KEY_DOWN.
Referenced by GotoFile::BuildContent(), and GotoFunctionDlg::BuildContent().
OnItemActivated()
void IncrementalSelectHandler::OnItemActivated (wxListEvent & event) private
Definition at line 278 of file incremental_select_helper.cpp.
References m_parent, and wxID_OK.
Referenced by DeInit(), and Init().
OnKeyDown()
void IncrementalSelectHandler::OnKeyDown (wxKeyEvent & event) private
Definition at line 263 of file incremental_select_helper.cpp.
References wxListCtrl::EnsureVisible(), wxListCtrl::GetItemCount(), wxListCtrl::GetNextItem(), KeyDownAction(), m_list, m_parent, wxListCtrl::SetItemState(), wxID_LOWEST, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by DeInit(), and Init().
OnTextChanged()
void IncrementalSelectHandler::OnTextChanged (wxCommandEvent & event) private
Definition at line 97 of file incremental_select_helper.cpp.
References FilterItems().
Referenced by DeInit(), and Init().
Member Data Documentation
m_iterator
IncrementalSelectIterator* IncrementalSelectHandler::m_iterator private
Definition at line 78 of file incremental_select_helper.h.
Referenced by FilterItems(), GetSelection(), and Init().
m_list
wxListCtrl* IncrementalSelectHandler::m_list private
Definition at line 76 of file incremental_select_helper.h.
Referenced by DeInit(), FilterItems(), GetSelection(), Init(), and OnKeyDown().
m_parent
wxDialog* IncrementalSelectHandler::m_parent private
Definition at line 75 of file incremental_select_helper.h.
Referenced by IncrementalSelectHandler(), OnItemActivated(), and OnKeyDown().
m_text
wxTextCtrl* IncrementalSelectHandler::m_text private
Definition at line 77 of file incremental_select_helper.h.
Referenced by DeInit(), FilterItems(), and Init().
The documentation for this class was generated from the following files:
incremental_select_helper.h
incremental_select_helper.cpp