Code::Blocks: StartHerePage Class Reference
StartHerePage Class Reference
#include <startherepage.h>
Public Member Functions
StartHerePage (wxEvtHandler *owner, const RecentItemsList &projects, const RecentItemsList &files, wxWindow *parent)
virtual ~StartHerePage ()
bool LinkClicked (const wxHtmlLinkInfo &link)
virtual bool VisibleToTree () const
Should this kind of editor be visible in the open files tree?
void Reload ()
Public Member Functions inherited from EditorBase
EditorBase (wxWindow *parent, const wxString &filename)
virtual ~EditorBase ()
void operator= (cb_optional const EditorBase &rhs)
Don't use this.
virtual const wxString & GetFilename () const
Get the editor's filename (if applicable).
virtual void SetFilename (const wxString &filename)
Sets the editor's filename.
virtual const wxString & GetShortName () const
Returns the editor's short name.
virtual bool GetModified () const
Is it modified?
virtual void SetModified (bool=true)
Set the modification status.
virtual const wxString & GetTitle ()
The editor's title.
virtual void SetTitle (const wxString &newTitle)
Set the editor's title.
virtual void Activate ()
Activate this editor.
virtual bool QueryClose ()
Can this be closed (destroyed)?
virtual bool Close ()
Close this editor.
virtual bool Save ()
Save contents.
virtual bool SaveAs ()
Save editor contents under a different filename.
virtual bool IsBuiltinEditor () const
Is this a built-in editor?
virtual bool ThereAreOthers () const
Are there other editors besides this?
virtual void DisplayContextMenu (const wxPoint &position, ModuleType type=mtUnknown)
Display context menu.
virtual void GotoLine (int, bool=true)
Move the caret at the specified line.
virtual void Undo ()
Undo changes.
virtual void Redo ()
Redo changes.
virtual void ClearHistory ()
Clear Undo- (and Changebar-) history.
virtual void GotoNextChanged ()
Goto next changed line.
virtual void GotoPreviousChanged ()
Goto previous changed line.
virtual void SetChangeCollection (cb_optional bool collectChange)
Enable or disable changebar.
virtual void Cut ()
Cut selected text/object to clipboard.
virtual void Copy ()
Copy selected text/object to clipboard.
virtual void Paste ()
Paste selected text/object from clipboard.
virtual bool CanUndo () const
Is there something to undo?
virtual bool CanRedo () const
Is there something to redo?
virtual bool HasSelection () const
Is there a selection?
virtual bool CanPaste () const
Is there something to paste?
virtual bool IsReadOnly () const
Is the editor read-only?
virtual void SetReadOnly (bool=true)
Set the editor read-only.
virtual bool CanSelectAll () const
Can the editor select everything?
virtual void SelectAll ()
Select everything in the editor.
virtual bool IsContextMenuOpened () const
Is there a context (right click) menu open.
Protected Attributes
wxEvtHandler * m_pOwner
wxHtmlWindow * m_pWin
wxString m_OriginalPageContent
const RecentItemsList & m_projects
const RecentItemsList & m_files
Protected Attributes inherited from EditorBase
bool m_IsBuiltinEditor
wxString m_Shortname
wxString m_Filename
EditorBaseInternalData * m_pData
Use this to add new vars/functions w/out breaking the ABI.
Private Member Functions
void RegisterColours ()
Private Attributes
wxString revInfo
Additional Inherited Members
Protected Member Functions inherited from EditorBase
virtual void InitFilename (const wxString &filename)
Initializes filename data.
virtual wxMenu * CreateContextSubMenu (long id)
Creates context submenus.
virtual void AddToContextMenu (cb_optional wxMenu *popup, cb_optional ModuleType type, cb_optional bool pluginsdone)
Creates context menu items, both before and after creating plugins menu items.
virtual wxString CreateUniqueFilename ()
Creates unique filename when asking to save the file.
virtual bool OnBeforeBuildContextMenu (cb_optional const wxPoint &position, cb_optional ModuleType type)
Informs the editor we 're just about to create a context menu.
virtual void OnAfterBuildContextMenu (cb_optional ModuleType type)
Informs the editor we 're done creating the context menu (just about to display it).
Detailed Description
Definition at line 19 of file startherepage.h.
Constructor & Destructor Documentation
StartHerePage()
StartHerePage::StartHerePage (wxEvtHandler * owner, const RecentItemsList & projects, const RecentItemsList & files, wxWindow * parent)
Definition at line 140 of file startherepage.cpp.
References _(), _T, wxBoxSizer::Add(), appglobals::AppActualVersion, appglobals::AppActualVersionVerb, appglobals::AppPlatform, appglobals::AppWXAnsiUnicode, appglobals::bit_type, cbC2U(), wxSystemSettings::GetFont(), wxFont::GetPointSize(), PluginManager::GetSafeMode(), wxFSFile::GetStream(), ConfigManager::GetSvnDate(), idWin, m_OriginalPageContent, m_pWin, wxFileSystem::OpenFile(), wxString::Printf(), ConfigManager::ReadDataPath(), RegisterColours(), Reload(), wxString::Replace(), revInfo, wxEmptyString, wxEXPAND, wxSYS_DEFAULT_GUI_FONT, and wxVERTICAL.
~StartHerePage()
StartHerePage::~StartHerePage () virtual
Definition at line 228 of file startherepage.cpp.
Member Function Documentation
LinkClicked()
bool StartHerePage::LinkClicked (const wxHtmlLinkInfo & link)
Definition at line 271 of file startherepage.cpp.
References _T, Manager::Get(), wxHtmlLinkInfo::GetHref(), idStartHerePageLink, wxString::IsSameAs(), m_pOwner, revInfo, wxString::StartsWith(), wxPostEvent(), and wxTheClipboard.
Referenced by MyHtmlWin::OnLinkClicked().
RegisterColours()
void StartHerePage::RegisterColours () private
Definition at line 234 of file startherepage.cpp.
References _(), Manager::Get(), wxSystemSettings::GetColour(), Manager::GetColourManager(), ColourManager::RegisterColour(), wxBLUE, wxSYS_COLOUR_WINDOW, wxSYS_COLOUR_WINDOWTEXT, and wxT.
Referenced by StartHerePage(), and VisibleToTree().
Reload()
void StartHerePage::Reload ()
Definition at line 249 of file startherepage.cpp.
References Manager::Get(), wxColour::GetAsString(), ColourManager::GetColour(), Manager::GetColourManager(), RecentItemsList::GetFileHistory(), m_files, m_OriginalPageContent, m_projects, m_pWin, wxString::Replace(), wxC2S_HTML_SYNTAX, and wxT.
Referenced by StartHerePage(), and VisibleToTree().
VisibleToTree()
virtual bool StartHerePage::VisibleToTree () const inline virtual
Should this kind of editor be visible in the open files tree?
There are rare cases where an editor should not be visible in the open files tree. One such example is the "Start here" page...
Returns
True if it should be visible in the open files tree, false if not.
Reimplemented from EditorBase.
Definition at line 29 of file startherepage.h.
References RegisterColours(), and Reload().
Member Data Documentation
m_files
const RecentItemsList& StartHerePage::m_files protected
Definition at line 38 of file startherepage.h.
Referenced by Reload().
m_OriginalPageContent
wxString StartHerePage::m_OriginalPageContent protected
Definition at line 36 of file startherepage.h.
Referenced by Reload(), and StartHerePage().
m_pOwner
wxEvtHandler* StartHerePage::m_pOwner protected
Definition at line 34 of file startherepage.h.
Referenced by LinkClicked().
m_projects
const RecentItemsList& StartHerePage::m_projects protected
Definition at line 37 of file startherepage.h.
Referenced by Reload().
m_pWin
wxHtmlWindow* StartHerePage::m_pWin protected
Definition at line 35 of file startherepage.h.
Referenced by Reload(), and StartHerePage().
revInfo
wxString StartHerePage::revInfo private
Definition at line 21 of file startherepage.h.
Referenced by LinkClicked(), and StartHerePage().
The documentation for this class was generated from the following files:
startherepage.h
startherepage.cpp