Code::Blocks: cbDebugInterfaceFactory Class Reference
cbDebugInterfaceFactory Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
cbDebugInterfaceFactory ()
virtual ~cbDebugInterfaceFactory ()
virtual cbBacktraceDlg * CreateBacktrace ()=0
virtual void DeleteBacktrace (cbBacktraceDlg *dialog)=0
virtual cbBreakpointsDlg * CreateBreapoints ()=0
virtual void DeleteBreakpoints (cbBreakpointsDlg *dialog)=0
virtual cbCPURegistersDlg * CreateCPURegisters ()=0
virtual void DeleteCPURegisters (cbCPURegistersDlg *dialog)=0
virtual cbDisassemblyDlg * CreateDisassembly ()=0
virtual void DeleteDisassembly (cbDisassemblyDlg *dialog)=0
virtual cbExamineMemoryDlg * CreateMemory ()=0
virtual void DeleteMemory (cbExamineMemoryDlg *dialog)=0
virtual cbThreadsDlg * CreateThreads ()=0
virtual void DeleteThreads (cbThreadsDlg *dialog)=0
virtual cbWatchesDlg * CreateWatches ()=0
virtual void DeleteWatches (cbWatchesDlg *dialog)=0
virtual bool ShowValueTooltip (const cb::shared_ptr< cbWatch > &watch, const wxRect &rect)=0
Show new value tooltip.
virtual void HideValueTooltip ()=0
virtual bool IsValueTooltipShown ()=0
virtual void UpdateValueTooltip ()=0
Private Member Functions
cbDebugInterfaceFactory (cbDebugInterfaceFactory &)
cbDebugInterfaceFactory & operator= (cbDebugInterfaceFactory &)
Detailed Description
Definition at line 143 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
cbDebugInterfaceFactory() [1/2]
cbDebugInterfaceFactory::cbDebugInterfaceFactory (cbDebugInterfaceFactory &) private
cbDebugInterfaceFactory() [2/2]
cbDebugInterfaceFactory::cbDebugInterfaceFactory ()
Definition at line 25 of file cbdebugger_interfaces.cpp.
~cbDebugInterfaceFactory()
cbDebugInterfaceFactory::~cbDebugInterfaceFactory () virtual
Definition at line 26 of file cbdebugger_interfaces.cpp.
Member Function Documentation
CreateBacktrace()
virtual cbBacktraceDlg* cbDebugInterfaceFactory::CreateBacktrace () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::CreateWindows().
CreateBreapoints()
virtual cbBreakpointsDlg* cbDebugInterfaceFactory::CreateBreapoints () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::CreateWindows().
CreateCPURegisters()
virtual cbCPURegistersDlg* cbDebugInterfaceFactory::CreateCPURegisters () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::CreateWindows().
CreateDisassembly()
virtual cbDisassemblyDlg* cbDebugInterfaceFactory::CreateDisassembly () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::CreateWindows().
CreateMemory()
virtual cbExamineMemoryDlg* cbDebugInterfaceFactory::CreateMemory () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::CreateWindows().
CreateThreads()
virtual cbThreadsDlg* cbDebugInterfaceFactory::CreateThreads () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::CreateWindows().
CreateWatches()
virtual cbWatchesDlg* cbDebugInterfaceFactory::CreateWatches () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::CreateWindows().
DeleteBacktrace()
virtual void cbDebugInterfaceFactory::DeleteBacktrace (cbBacktraceDlg * dialog) pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::DestoryWindows().
DeleteBreakpoints()
virtual void cbDebugInterfaceFactory::DeleteBreakpoints (cbBreakpointsDlg * dialog) pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::DestoryWindows().
DeleteCPURegisters()
virtual void cbDebugInterfaceFactory::DeleteCPURegisters (cbCPURegistersDlg * dialog) pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::DestoryWindows().
DeleteDisassembly()
virtual void cbDebugInterfaceFactory::DeleteDisassembly (cbDisassemblyDlg * dialog) pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::DestoryWindows().
DeleteMemory()
virtual void cbDebugInterfaceFactory::DeleteMemory (cbExamineMemoryDlg * dialog) pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::DestoryWindows().
DeleteThreads()
virtual void cbDebugInterfaceFactory::DeleteThreads (cbThreadsDlg * dialog) pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::DestoryWindows().
DeleteWatches()
virtual void cbDebugInterfaceFactory::DeleteWatches (cbWatchesDlg * dialog) pure virtual
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::DestoryWindows().
HideValueTooltip()
virtual void cbDebugInterfaceFactory::HideValueTooltip () pure virtual
Implemented in DebugInterfaceFactory.
Referenced by cbDebuggerPlugin::CancelValueTooltip().
IsValueTooltipShown()
virtual bool cbDebugInterfaceFactory::IsValueTooltipShown () pure virtual
Implemented in DebugInterfaceFactory.
operator=()
cbDebugInterfaceFactory& cbDebugInterfaceFactory::operator= (cbDebugInterfaceFactory &) private
ShowValueTooltip()
virtual bool cbDebugInterfaceFactory::ShowValueTooltip (const cb::shared_ptr< cbWatch > & watch, const wxRect & rect) pure virtual
Show new value tooltip.
Returns
Return True only if new tooltip was shown, else return False.
Implemented in DebugInterfaceFactory.
Referenced by DebuggerManager::ShowValueTooltip().
UpdateValueTooltip()
virtual void cbDebugInterfaceFactory::UpdateValueTooltip () pure virtual
Implemented in DebugInterfaceFactory.
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp