Code::Blocks: GdbCmd_StepOrNextInstruction Class Reference
GdbCmd_StepOrNextInstruction Class Reference
#include <gdb_commands.h>
Public Member Functions
GdbCmd_StepOrNextInstruction (GDB_driver *driver, const wxChar *command)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerContinueBaseCmd
DebuggerContinueBaseCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Constructor & Destructor Documentation
GdbCmd_StepOrNextInstruction::GdbCmd_StepOrNextInstruction (GDB_driver * driver, const wxChar * command) inline
References DebuggerCmd::m_Cmd.
Member Function Documentation
void GdbCmd_StepOrNextInstruction::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
References cbDebuggerStringToAddress(), cbDisassemblyDlg::Clear(), Manager::Get(), Manager::GetDebuggerManager(), DebuggerManager::GetDisassemblyDialog(), DebuggerDriver::Log(), DebuggerCmd::m_pDriver, DebuggerDriver::QueueCommand(), reStepI(), reStepI2(), reStepI3(), reStepI4(), cbDisassemblyDlg::SetActiveAddress(), and DebuggerManager::UpdateDisassembly().
The documentation for this class was generated from the following file:
gdb_commands.h