Code::Blocks: CCOptionsProjectDlg Class Reference
CCOptionsProjectDlg Class Reference
#include <ccoptionsprjdlg.h>
Public Member Functions
CCOptionsProjectDlg (wxWindow *parent, cbProject *project, NativeParser *np)
virtual ~CCOptionsProjectDlg ()
virtual wxString GetTitle () const
virtual wxString GetBitmapBaseName () const
virtual void OnApply ()
Called when the user chooses to apply the configuration.
virtual void OnCancel ()
Called when the user chooses to cancel the configuration.
Public Member Functions inherited from cbConfigurationPanel
cbConfigurationPanel ()
virtual ~cbConfigurationPanel ()
void SetParentDialog (wxWindow *dialog)
Sets the panel's parent dialog.
wxWindow * SetParentDialog ()
Gets the panel's parent dialog.
int cbMessageBox (const wxString &message, const wxString &caption=wxEmptyString, int style=wxOK, wxWindow *parent=NULL, int x=-1, int y=-1)
Call global cbMessageBox with m_parentDialog as parent window when no parent window specified.
Protected Member Functions
void OnAdd (wxCommandEvent &event)
void OnEdit (wxCommandEvent &event)
void OnDelete (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Private Attributes
cbProject * m_Project
NativeParser * m_NativeParser
ParserBase * m_Parser
wxArrayString m_OldPaths
Detailed Description
Definition at line 17 of file ccoptionsprjdlg.h.
Constructor & Destructor Documentation
CCOptionsProjectDlg()
CCOptionsProjectDlg::CCOptionsProjectDlg (wxWindow * parent, cbProject * project, NativeParser * np)
Definition at line 36 of file ccoptionsprjdlg.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadPanel().
~CCOptionsProjectDlg()
CCOptionsProjectDlg::~CCOptionsProjectDlg () virtual
Definition at line 50 of file ccoptionsprjdlg.cpp.
Member Function Documentation
GetBitmapBaseName()
virtual wxString CCOptionsProjectDlg::GetBitmapBaseName () const inline virtual
Returns
the panel's bitmap base name. You must supply two bitmaps: <basename>.png and <basename>-off.png...
Implements cbConfigurationPanel.
Definition at line 24 of file ccoptionsprjdlg.h.
References _T, and OnApply().
GetTitle()
virtual wxString CCOptionsProjectDlg::GetTitle () const inline virtual
Returns
the panel's title.
Implements cbConfigurationPanel.
Definition at line 23 of file ccoptionsprjdlg.h.
References _().
OnAdd()
void CCOptionsProjectDlg::OnAdd (wxCommandEvent & event) protected
Definition at line 54 of file ccoptionsprjdlg.cpp.
References _(), _T, CompileTargetBase::GetBasePath(), m_Project, PlaceWindow(), and wxID_OK.
Referenced by OnCancel().
OnApply()
void CCOptionsProjectDlg::OnApply () virtual
Called when the user chooses to apply the configuration.
Implements cbConfigurationPanel.
Definition at line 110 of file ccoptionsprjdlg.cpp.
References _(), wxArrayString::Add(), ParserBase::AddIncludeDir(), cbConfigurationPanel::cbMessageBox(), wxArrayString::GetCount(), NativeParser::GetProjectSearchDirs(), m_NativeParser, m_OldPaths, m_Parser, m_Project, and wxICON_INFORMATION.
Referenced by GetBitmapBaseName().
OnCancel()
virtual void CCOptionsProjectDlg::OnCancel () inline virtual
Called when the user chooses to cancel the configuration.
Implements cbConfigurationPanel.
Definition at line 26 of file ccoptionsprjdlg.h.
References OnAdd(), OnDelete(), OnEdit(), and OnUpdateUI().
OnDelete()
void CCOptionsProjectDlg::OnDelete (wxCommandEvent & event) protected
Definition at line 91 of file ccoptionsprjdlg.cpp.
Referenced by OnCancel().
OnEdit()
void CCOptionsProjectDlg::OnEdit (wxCommandEvent & event) protected
Definition at line 71 of file ccoptionsprjdlg.cpp.
References _(), _T, CompileTargetBase::GetBasePath(), m_Project, PlaceWindow(), and wxID_OK.
Referenced by OnCancel().
OnUpdateUI()
void CCOptionsProjectDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 101 of file ccoptionsprjdlg.cpp.
Referenced by OnCancel().
Member Data Documentation
m_NativeParser
NativeParser* CCOptionsProjectDlg::m_NativeParser private
Definition at line 36 of file ccoptionsprjdlg.h.
Referenced by OnApply().
m_OldPaths
wxArrayString CCOptionsProjectDlg::m_OldPaths private
Definition at line 38 of file ccoptionsprjdlg.h.
Referenced by OnApply().
m_Parser
ParserBase* CCOptionsProjectDlg::m_Parser private
Definition at line 37 of file ccoptionsprjdlg.h.
Referenced by OnApply().
m_Project
cbProject* CCOptionsProjectDlg::m_Project private
Definition at line 35 of file ccoptionsprjdlg.h.
Referenced by OnAdd(), OnApply(), and OnEdit().
The documentation for this class was generated from the following files:
ccoptionsprjdlg.h
ccoptionsprjdlg.cpp