Code::Blocks: wxDialogLayoutAdapterModule Class Reference
wxDialogLayoutAdapterModule Class Reference
Public Member Functions
wxDialogLayoutAdapterModule ()
virtual void OnExit ()
virtual bool OnInit ()
Detailed Description
Module to initialise standard adapter
Definition at line 406 of file scrollingdialog.cpp.
Constructor & Destructor Documentation
wxDialogLayoutAdapterModule()
wxDialogLayoutAdapterModule::wxDialogLayoutAdapterModule () inline
Definition at line 410 of file scrollingdialog.cpp.
Member Function Documentation
OnExit()
virtual void wxDialogLayoutAdapterModule::OnExit () inline virtual
Definition at line 411 of file scrollingdialog.cpp.
References NULL, and wxDialogHelper::SetLayoutAdapter().
OnInit()
virtual bool wxDialogLayoutAdapterModule::OnInit () inline virtual
Definition at line 412 of file scrollingdialog.cpp.
References IMPLEMENT_DYNAMIC_CLASS(), and wxDialogHelper::SetLayoutAdapter().
The documentation for this class was generated from the following file:
scrollingdialog.cpp