Code::Blocks: EditorConfigurationDlg Class Reference
EditorConfigurationDlg Class Reference
#include <editorconfigurationdlg.h>
Classes
struct MenuItemLanguageOptionID
Public Member Functions
EditorConfigurationDlg (wxWindow *parent)
~EditorConfigurationDlg ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Private Types
typedef std::map< long, MenuItemLanguageOptionID > MenuIDToLanguageOption
Private Member Functions
void OnChooseFont (wxCommandEvent &event)
void OnChooseColour (wxCommandEvent &event)
void OnSetDefaultColour (wxCommandEvent &event)
void OnBoldItalicUline (wxCommandEvent &event)
void OnColourTheme (wxCommandEvent &event)
void OnAddColourTheme (wxCommandEvent &event)
void OnDeleteColourTheme (wxCommandEvent &event)
void OnRenameColourTheme (wxCommandEvent &event)
void OnColourComponent (wxCommandEvent &event)
void OnColoursReset (wxCommandEvent &event)
void OnColoursCopyFrom (wxCommandEvent &event)
void OnMenuColoursCopyFrom (wxCommandEvent &event)
void OnColoursCopyAllFrom (wxCommandEvent &event)
void OnMenuColoursCopyAllFrom (wxCommandEvent &event)
void OnEditKeywords (wxCommandEvent &event)
void OnEditFilemasks (wxCommandEvent &event)
void OnChangeLang (wxCommandEvent &event)
void OnChangeDefCodeFileType (wxCommandEvent &event)
void OnDynamicCheck (wxCommandEvent &event)
void OnHighlightOccurrences (wxCommandEvent &event)
void OnMultipleSelections (wxCommandEvent &event)
void UpdateSampleFont (bool askForNewFont)
void OnCaretStyle (wxCommandEvent &event)
void EndModal (int retCode)
void OnPageChanged (wxListbookEvent &event)
void AddPluginPanels ()
void LoadListbookImages ()
void UpdateListbookImages ()
void CreateColoursSample ()
void ApplyColours ()
void FillColourComponents ()
void ReadColours ()
void WriteColours ()
void LoadThemes ()
void ChangeTheme ()
bool AskToSaveTheme ()
void UpdateColourControls (const OptionColour *opt)
Private Attributes
cbStyledTextCtrl * m_TextColourControl
EditorColourSet * m_Theme
HighlightLanguage m_Lang
int m_DefCodeFileType
wxArrayString m_DefaultCode
will store the default code during configuration for each type
bool m_ThemeModified
ConfigurationPanelsArray m_PluginPanels
wxString m_FontString
bool m_EnableChangebar
bool m_EnableScrollWidthTracking
MenuIDToLanguageOption m_MenuIDToLanguageOption
wxImageList * m_pImageList
Detailed Description
Definition at line 19 of file editorconfigurationdlg.h.
Class Documentation
EditorConfigurationDlg::MenuItemLanguageOptionID
struct EditorConfigurationDlg::MenuItemLanguageOptionID
Definition at line 66 of file editorconfigurationdlg.h.
Class Members
int index
wxString langID
Member Typedef Documentation
MenuIDToLanguageOption
typedef std::map<long, MenuItemLanguageOptionID> EditorConfigurationDlg::MenuIDToLanguageOption private
Definition at line 71 of file editorconfigurationdlg.h.
Constructor & Destructor Documentation
EditorConfigurationDlg()
EditorConfigurationDlg::EditorConfigurationDlg (wxWindow * parent)
Definition at line 98 of file editorconfigurationdlg.cpp.
References _(), _T, wxString::CmpNoCase(), wxXmlResource::Get(), Manager::Get(), ColourManager::GetColour(), Manager::GetColourManager(), Manager::GetConfigManager(), wxFontMapper::GetEncoding(), wxFontMapper::GetEncodingName(), wxFontMapper::GetSupportedEncodingsCount(), wxLocale::GetSystemEncodingName(), IdxToFileType, wxXmlResource::LoadObject(), wxString::Printf(), ConfigManager::Read(), ConfigManager::ReadBool(), ConfigManager::ReadInt(), wxChoice::SetSelection(), wxEmptyString, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, wxSCI_CARETSTYLE_LINE, wxSCI_EOL_CRLF, wxSCI_EOL_LF, and wxT.
~EditorConfigurationDlg()
EditorConfigurationDlg::~EditorConfigurationDlg ()
Definition at line 278 of file editorconfigurationdlg.cpp.
References m_pImageList, m_TextColourControl, and m_Theme.
Member Function Documentation
AddPluginPanels()
void EditorConfigurationDlg::AddPluginPanels () private
Definition at line 289 of file editorconfigurationdlg.cpp.
References _T, wxImageList::Add(), wxBookCtrlBase::AddPage(), cbLoadBitmap(), cgEditor, Manager::Get(), cbConfigurationPanel::GetBitmapBaseName(), PluginManager::GetConfigurationPanels(), wxImageList::GetImageCount(), wxBookCtrlBase::GetPageCount(), Manager::GetPluginManager(), cbConfigurationPanel::GetTitle(), wxString::IsEmpty(), ConfigManager::LocateDataFile(), m_pImageList, m_PluginPanels, sdDataGlobal, sdDataUser, wxBookCtrlBase::SetPageImage(), cbConfigurationPanel::SetParentDialog(), and UpdateListbookImages().
ApplyColours()
void EditorConfigurationDlg::ApplyColours () private
Definition at line 422 of file editorconfigurationdlg.cpp.
References EditorColourSet::Apply(), m_Lang, m_TextColourControl, m_Theme, wxScintilla::StyleSetFont(), and wxSCI_STYLE_DEFAULT.
Referenced by CreateColoursSample(), OnColoursReset(), OnMenuColoursCopyAllFrom(), OnMenuColoursCopyFrom(), UpdateSampleFont(), and WriteColours().
AskToSaveTheme()
bool EditorConfigurationDlg::AskToSaveTheme () private
Definition at line 573 of file editorconfigurationdlg.cpp.
References _(), wxString::c_str(), cbMessageBox(), wxChoice::FindString(), EditorColourSet::GetName(), m_Theme, m_ThemeModified, wxString::Printf(), EditorColourSet::Save(), wxChoice::SetSelection(), wxCANCEL, wxID_CANCEL, wxID_YES, and wxYES_NO.
Referenced by OnColourTheme().
ChangeTheme()
void EditorConfigurationDlg::ChangeTheme () private
Definition at line 596 of file editorconfigurationdlg.cpp.
References _T, COLORSET_DEFAULT, CreateColoursSample(), wxChoice::FindString(), Manager::Get(), EditorColourSet::GetAllHighlightLanguages(), EditorManager::GetColourSet(), Manager::GetConfigManager(), wxArrayString::GetCount(), Manager::GetEditorManager(), EditorColourSet::GetHighlightLanguage(), EditorColourSet::GetName(), wxChoice::GetSelection(), m_Lang, m_Theme, m_ThemeModified, ConfigManager::Read(), wxChoice::SetSelection(), and wxNOT_FOUND.
Referenced by LoadThemes(), OnAddColourTheme(), OnColourTheme(), OnDeleteColourTheme(), and OnRenameColourTheme().
CreateColoursSample()
void EditorConfigurationDlg::CreateColoursSample () private
Definition at line 370 of file editorconfigurationdlg.cpp.
References _T, ApplyColours(), wxXmlResource::AttachUnknownControl(), FillColourComponents(), wxXmlResource::Get(), EditorColourSet::GetSampleCode(), wxString::IsEmpty(), wxScintilla::LoadFile(), m_Lang, m_TextColourControl, m_Theme, wxScintilla::MarkerAdd(), wxScintilla::MarkerDeleteAll(), wxScintilla::SetCaretWidth(), wxScintilla::SetMarginType(), wxScintilla::SetMarginWidth(), wxScintilla::SetReadOnly(), wxScintilla::SetTabWidth(), wxID_ANY, and wxSCI_MARGIN_NUMBER.
Referenced by ChangeTheme(), and OnChangeLang().
EndModal()
void EditorConfigurationDlg::EndModal (int retCode) private
Definition at line 985 of file editorconfigurationdlg.cpp.
References _T, wxArrayString::Add(), cbEditor::ClearHistory(), ScriptBindings::EndModal(), Manager::Get(), EditorManager::GetBuiltinEditor(), Manager::GetColourManager(), Manager::GetConfigManager(), EditorManager::GetEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), EditorColourSet::GetName(), EditorManager::GetNotebook(), EditorManager::GetZoom(), IdxToFileType, m_DefaultCode, m_EnableChangebar, m_PluginPanels, m_Theme, cbConfigurationPanel::OnApply(), cbConfigurationPanel::OnCancel(), wxString::Printf(), ConfigManager::Read(), ColourManager::Save(), EditorColourSet::Save(), cbEditor::SetChangeCollection(), ColourManager::SetColour(), EditorManager::SetColourSet(), EditorManager::SetZoom(), cbAuiNotebook::SetZoom(), cbEditor::UnfoldAll(), ConfigManager::Write(), wxEmptyString, wxID_OK, and wxT.
FillColourComponents()
void EditorConfigurationDlg::FillColourComponents () private
Definition at line 408 of file editorconfigurationdlg.cpp.
References EditorColourSet::GetOptionByIndex(), EditorColourSet::GetOptionCount(), m_Lang, m_Theme, OptionColour::name, and ReadColours().
Referenced by CreateColoursSample(), and OnChangeLang().
LoadListbookImages()
void EditorConfigurationDlg::LoadListbookImages () private
Definition at line 320 of file editorconfigurationdlg.cpp.
References _T, wxImageList::Add(), cbLoadBitmap(), ConfigManager::GetDataFolder(), IMAGES_COUNT, and m_pImageList.
LoadThemes()
void EditorConfigurationDlg::LoadThemes () private
Definition at line 552 of file editorconfigurationdlg.cpp.
References _T, ChangeTheme(), COLORSET_DEFAULT, ConfigManager::EnumerateSubPaths(), wxChoice::FindString(), Manager::Get(), Manager::GetConfigManager(), wxChoice::GetCount(), wxArrayString::GetCount(), ConfigManager::Read(), wxChoice::SetSelection(), wxArrayString::Sort(), and wxNOT_FOUND.
OnAddColourTheme()
void EditorConfigurationDlg::OnAddColourTheme (wxCommandEvent & event) private
Definition at line 679 of file editorconfigurationdlg.cpp.
References _(), ChangeTheme(), wxChoice::GetCount(), PlaceWindow(), wxChoice::SetSelection(), wxDialog::ShowModal(), and wxID_OK.
OnBoldItalicUline()
void EditorConfigurationDlg::OnBoldItalicUline (wxCommandEvent & event) private
Definition at line 975 of file editorconfigurationdlg.cpp.
References WriteColours().
OnCaretStyle()
void EditorConfigurationDlg::OnCaretStyle (wxCommandEvent & event) private
Definition at line 547 of file editorconfigurationdlg.cpp.
References wxSCI_CARETSTYLE_LINE.
OnChangeDefCodeFileType()
void EditorConfigurationDlg::OnChangeDefCodeFileType (wxCommandEvent & event) private
Definition at line 920 of file editorconfigurationdlg.cpp.
References m_DefaultCode, and m_DefCodeFileType.
OnChangeLang()
void EditorConfigurationDlg::OnChangeLang (wxCommandEvent & event) private
Definition at line 909 of file editorconfigurationdlg.cpp.
References CreateColoursSample(), FillColourComponents(), EditorColourSet::GetHighlightLanguage(), m_Lang, and m_Theme.
OnChooseColour()
void EditorConfigurationDlg::OnChooseColour (wxCommandEvent & event) private
Definition at line 931 of file editorconfigurationdlg.cpp.
References wxColourData::GetColour(), wxColourDialog::GetColourData(), PlaceWindow(), wxColourData::SetColour(), wxColourDialog::ShowModal(), WriteColours(), wxEmptyString, and wxID_OK.
OnChooseFont()
void EditorConfigurationDlg::OnChooseFont (wxCommandEvent & event) private
Definition at line 965 of file editorconfigurationdlg.cpp.
References UpdateSampleFont().
OnColourComponent()
void EditorConfigurationDlg::OnColourComponent (wxCommandEvent & event) private
Definition at line 970 of file editorconfigurationdlg.cpp.
References ReadColours().
OnColoursCopyAllFrom()
void EditorConfigurationDlg::OnColoursCopyAllFrom (wxCommandEvent & event) private
Definition at line 846 of file editorconfigurationdlg.cpp.
References wxMenu::Append(), EditorColourSet::GetAllHighlightLanguages(), wxArrayString::GetCount(), EditorColourSet::GetHighlightLanguage(), EditorConfigurationDlg::MenuItemLanguageOptionID::index, m_MenuIDToLanguageOption, m_Theme, OnMenuColoursCopyAllFrom(), and wxNewId().
OnColoursCopyFrom()
void EditorConfigurationDlg::OnColoursCopyFrom (wxCommandEvent & event) private
Definition at line 778 of file editorconfigurationdlg.cpp.
References wxMenu::Append(), wxMenu::AppendSubMenu(), wxMenu::FindItem(), EditorColourSet::GetAllHighlightLanguages(), wxArrayString::GetCount(), EditorColourSet::GetHighlightLanguage(), EditorColourSet::GetOptionByIndex(), EditorColourSet::GetOptionCount(), EditorConfigurationDlg::MenuItemLanguageOptionID::index, m_MenuIDToLanguageOption, m_Theme, OptionColour::name, OnMenuColoursCopyFrom(), wxNewId(), and wxNOT_FOUND.
OnColoursReset()
void EditorConfigurationDlg::OnColoursReset (wxCommandEvent & event) private
Definition at line 761 of file editorconfigurationdlg.cpp.
References _(), ApplyColours(), wxString::c_str(), cbMessageBox(), EditorColourSet::GetLanguageName(), HL_NONE, m_Lang, m_Theme, m_ThemeModified, wxString::Printf(), ReadColours(), EditorColourSet::Reset(), wxICON_QUESTION, wxID_YES, and wxYES_NO.
OnColourTheme()
void EditorConfigurationDlg::OnColourTheme (wxCommandEvent & event) private
Definition at line 647 of file editorconfigurationdlg.cpp.
References _(), AskToSaveTheme(), cbMessageBox(), ChangeTheme(), EditorColourSet::GetName(), m_Theme, wxRegEx::Matches(), wxOK, and wxT.
OnDeleteColourTheme()
void EditorConfigurationDlg::OnDeleteColourTheme (wxCommandEvent & event) private
Definition at line 696 of file editorconfigurationdlg.cpp.
References _(), _T, cbMessageBox(), ChangeTheme(), ConfigManager::DeleteSubPath(), wxChoice::FindString(), Manager::Get(), Manager::GetConfigManager(), EditorColourSet::GetName(), m_Theme, wxChoice::SetSelection(), wxID_YES, wxNOT_FOUND, and wxYES_NO.
OnDynamicCheck()
void EditorConfigurationDlg::OnDynamicCheck (wxCommandEvent & event) private
Definition at line 980 of file editorconfigurationdlg.cpp.
OnEditFilemasks()
void EditorConfigurationDlg::OnEditFilemasks (wxCommandEvent & event) private
Definition at line 749 of file editorconfigurationdlg.cpp.
References _(), _T, cbGetTextFromUser(), EditorColourSet::GetFileMasks(), EditorColourSet::GetLanguageName(), GetStringFromArray(), HL_NONE, wxString::IsEmpty(), m_Lang, m_Theme, and EditorColourSet::SetFileMasks().
OnEditKeywords()
void EditorConfigurationDlg::OnEditKeywords (wxCommandEvent & event) private
Definition at line 734 of file editorconfigurationdlg.cpp.
References wxScintilla::DescribeKeyWordSets(), GetArrayFromString(), HL_NONE, m_Lang, m_TextColourControl, m_Theme, PlaceWindow(), and wxT.
OnHighlightOccurrences()
void EditorConfigurationDlg::OnHighlightOccurrences (wxCommandEvent & event) private
OnMenuColoursCopyAllFrom()
void EditorConfigurationDlg::OnMenuColoursCopyAllFrom (wxCommandEvent & event) private
Definition at line 877 of file editorconfigurationdlg.cpp.
References ApplyColours(), OptionColour::back, OptionColour::bold, OptionColour::fore, EditorColourSet::GetOptionByIndex(), EditorColourSet::GetOptionByName(), EditorColourSet::GetOptionCount(), OptionColour::italics, m_Lang, m_MenuIDToLanguageOption, m_Theme, OptionColour::name, ReadColours(), OptionColour::underlined, and wxT.
Referenced by OnColoursCopyAllFrom().
OnMenuColoursCopyFrom()
void EditorConfigurationDlg::OnMenuColoursCopyFrom (wxCommandEvent & event) private
Definition at line 819 of file editorconfigurationdlg.cpp.
References ApplyColours(), OptionColour::back, OptionColour::bold, OptionColour::fore, EditorColourSet::GetOptionByIndex(), EditorColourSet::GetOptionByName(), EditorConfigurationDlg::MenuItemLanguageOptionID::index, OptionColour::italics, EditorConfigurationDlg::MenuItemLanguageOptionID::langID, m_Lang, m_MenuIDToLanguageOption, m_Theme, OptionColour::underlined, and UpdateColourControls().
Referenced by OnColoursCopyFrom().
OnMultipleSelections()
void EditorConfigurationDlg::OnMultipleSelections (wxCommandEvent & event) private
Definition at line 1184 of file editorconfigurationdlg.cpp.
OnPageChanged()
void EditorConfigurationDlg::OnPageChanged (wxListbookEvent & event) private
Definition at line 363 of file editorconfigurationdlg.cpp.
References UpdateListbookImages().
OnRenameColourTheme()
void EditorConfigurationDlg::OnRenameColourTheme (wxCommandEvent & event) private
Definition at line 710 of file editorconfigurationdlg.cpp.
References _(), _T, ChangeTheme(), ConfigManager::DeleteSubPath(), wxChoice::FindString(), Manager::Get(), Manager::GetConfigManager(), EditorColourSet::GetName(), wxChoice::GetSelection(), m_Theme, PlaceWindow(), EditorColourSet::Save(), EditorColourSet::SetName(), wxChoice::SetSelection(), wxChoice::SetString(), wxID_OK, and wxNOT_FOUND.
OnSetDefaultColour()
void EditorConfigurationDlg::OnSetDefaultColour (wxCommandEvent & event) private
Definition at line 951 of file editorconfigurationdlg.cpp.
References _(), wxSystemSettings::GetColour(), WriteColours(), and wxSYS_COLOUR_BTNFACE.
ReadColours()
void EditorConfigurationDlg::ReadColours () private
Definition at line 435 of file editorconfigurationdlg.cpp.
References EditorColourSet::GetOptionByName(), m_Lang, m_Theme, and UpdateColourControls().
Referenced by FillColourComponents(), OnColourComponent(), OnColoursReset(), and OnMenuColoursCopyAllFrom().
UpdateColourControls()
void EditorConfigurationDlg::UpdateColourControls (const OptionColour * opt) private
Definition at line 446 of file editorconfigurationdlg.cpp.
References _(), _T, OptionColour::back, OptionColour::bold, OptionColour::fore, wxSystemSettings::GetColour(), OptionColour::isStyle, OptionColour::italics, OptionColour::name, OptionColour::underlined, wxNullColour, and wxSYS_COLOUR_BTNFACE.
Referenced by OnMenuColoursCopyFrom(), and ReadColours().
UpdateListbookImages()
void EditorConfigurationDlg::UpdateListbookImages () private
Definition at line 335 of file editorconfigurationdlg.cpp.
References _T, Manager::Get(), wxListbook::GetListView(), wxBookCtrlBase::GetPageText(), wxBookCtrlBase::GetSelection(), IMAGES_COUNT, m_pImageList, m_PluginPanels, wxBookCtrlBase::SetPageImage(), SetSettingsIconsStyle(), sisLargeIcons, and sisNoIcons.
Referenced by AddPluginPanels(), and OnPageChanged().
UpdateSampleFont()
void EditorConfigurationDlg::UpdateSampleFont (bool askForNewFont) private
Definition at line 517 of file editorconfigurationdlg.cpp.
References ApplyColours(), wxNativeFontInfo::FromString(), wxFontData::GetChosenFont(), wxFontDialog::GetFontData(), wxFont::GetNativeFontInfoDesc(), wxString::IsEmpty(), m_FontString, PlaceWindow(), wxFontData::SetInitialFont(), wxFont::SetNativeFontInfo(), wxFontDialog::ShowModal(), wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, and wxID_OK.
Referenced by OnChooseFont().
WriteColours()
void EditorConfigurationDlg::WriteColours () private
Definition at line 488 of file editorconfigurationdlg.cpp.
References ApplyColours(), OptionColour::back, OptionColour::bold, OptionColour::fore, wxSystemSettings::GetColour(), EditorColourSet::GetOptionByName(), OptionColour::italics, m_Lang, m_Theme, m_ThemeModified, OptionColour::underlined, EditorColourSet::UpdateOptionsWithSameName(), wxNullColour, and wxSYS_COLOUR_BTNFACE.
Referenced by OnBoldItalicUline(), OnChooseColour(), and OnSetDefaultColour().
Member Data Documentation
m_DefaultCode
wxArrayString EditorConfigurationDlg::m_DefaultCode private
will store the default code during configuration for each type
Definition at line 77 of file editorconfigurationdlg.h.
Referenced by EndModal(), and OnChangeDefCodeFileType().
m_DefCodeFileType
int EditorConfigurationDlg::m_DefCodeFileType private
Definition at line 76 of file editorconfigurationdlg.h.
Referenced by OnChangeDefCodeFileType().
m_EnableChangebar
bool EditorConfigurationDlg::m_EnableChangebar private
Definition at line 81 of file editorconfigurationdlg.h.
Referenced by EndModal().
m_EnableScrollWidthTracking
bool EditorConfigurationDlg::m_EnableScrollWidthTracking private
Definition at line 82 of file editorconfigurationdlg.h.
m_FontString
wxString EditorConfigurationDlg::m_FontString private
Definition at line 80 of file editorconfigurationdlg.h.
Referenced by UpdateSampleFont().
m_Lang
HighlightLanguage EditorConfigurationDlg::m_Lang private
Definition at line 75 of file editorconfigurationdlg.h.
Referenced by ApplyColours(), ChangeTheme(), CreateColoursSample(), FillColourComponents(), OnChangeLang(), OnColoursReset(), OnEditFilemasks(), OnEditKeywords(), OnMenuColoursCopyAllFrom(), OnMenuColoursCopyFrom(), ReadColours(), and WriteColours().
m_MenuIDToLanguageOption
MenuIDToLanguageOption EditorConfigurationDlg::m_MenuIDToLanguageOption private
Definition at line 83 of file editorconfigurationdlg.h.
Referenced by OnColoursCopyAllFrom(), OnColoursCopyFrom(), OnMenuColoursCopyAllFrom(), and OnMenuColoursCopyFrom().
m_pImageList
wxImageList* EditorConfigurationDlg::m_pImageList private
Definition at line 84 of file editorconfigurationdlg.h.
Referenced by AddPluginPanels(), LoadListbookImages(), UpdateListbookImages(), and ~EditorConfigurationDlg().
m_PluginPanels
ConfigurationPanelsArray EditorConfigurationDlg::m_PluginPanels private
Definition at line 79 of file editorconfigurationdlg.h.
Referenced by AddPluginPanels(), EndModal(), and UpdateListbookImages().
m_TextColourControl
cbStyledTextCtrl* EditorConfigurationDlg::m_TextColourControl private
Definition at line 73 of file editorconfigurationdlg.h.
Referenced by ApplyColours(), CreateColoursSample(), OnEditKeywords(), and ~EditorConfigurationDlg().
m_Theme
EditorColourSet* EditorConfigurationDlg::m_Theme private
Definition at line 74 of file editorconfigurationdlg.h.
Referenced by ApplyColours(), AskToSaveTheme(), ChangeTheme(), CreateColoursSample(), EndModal(), FillColourComponents(), OnChangeLang(), OnColoursCopyAllFrom(), OnColoursCopyFrom(), OnColoursReset(), OnColourTheme(), OnDeleteColourTheme(), OnEditFilemasks(), OnEditKeywords(), OnMenuColoursCopyAllFrom(), OnMenuColoursCopyFrom(), OnRenameColourTheme(), ReadColours(), WriteColours(), and ~EditorConfigurationDlg().
m_ThemeModified
bool EditorConfigurationDlg::m_ThemeModified private
Definition at line 78 of file editorconfigurationdlg.h.
Referenced by AskToSaveTheme(), ChangeTheme(), OnColoursReset(), and WriteColours().
The documentation for this class was generated from the following files:
editorconfigurationdlg.h
editorconfigurationdlg.cpp