Code::Blocks: cbExamineMemoryDlg Class Reference
cbExamineMemoryDlg Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbExamineMemoryDlg ()
virtual wxWindow * GetWindow ()=0
virtual void Begin ()=0
virtual void End ()=0
virtual void Clear ()=0
virtual wxString GetBaseAddress ()=0
virtual int GetBytes ()=0
virtual void AddError (const wxString &err)=0
virtual void AddHexByte (const wxString &addr, const wxString &hexbyte)=0
virtual void EnableWindow (bool enable)=0
Detailed Description
Definition at line 74 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
~cbExamineMemoryDlg()
cbExamineMemoryDlg::~cbExamineMemoryDlg () virtual
Definition at line 17 of file cbdebugger_interfaces.cpp.
Member Function Documentation
AddError()
virtual void cbExamineMemoryDlg::AddError (const wxString & err) pure virtual
Implemented in ExamineMemoryDlg.
Referenced by GdbCmd_ExamineMemory::ParseOutput().
AddHexByte()
virtual void cbExamineMemoryDlg::AddHexByte (const wxString & addr, const wxString & hexbyte) pure virtual
Implemented in ExamineMemoryDlg.
Referenced by GdbCmd_ExamineMemory::ParseOutput().
Begin()
virtual void cbExamineMemoryDlg::Begin () pure virtual
Implemented in ExamineMemoryDlg.
Referenced by GdbCmd_ExamineMemory::ParseOutput().
Clear()
virtual void cbExamineMemoryDlg::Clear () pure virtual
Implemented in ExamineMemoryDlg.
Referenced by GdbCmd_ExamineMemory::ParseOutput().
EnableWindow()
virtual void cbExamineMemoryDlg::EnableWindow (bool enable) pure virtual
Implemented in ExamineMemoryDlg.
Referenced by DebuggerManager::RefreshUI(), and DebuggerManager::SetInterfaceFactory().
End()
virtual void cbExamineMemoryDlg::End () pure virtual
Implemented in ExamineMemoryDlg.
Referenced by GdbCmd_ExamineMemory::ParseOutput().
GetBaseAddress()
virtual wxString cbExamineMemoryDlg::GetBaseAddress () pure virtual
Implemented in ExamineMemoryDlg.
Referenced by GdbCmd_ExamineMemory::GdbCmd_ExamineMemory().
GetBytes()
virtual int cbExamineMemoryDlg::GetBytes () pure virtual
Implemented in ExamineMemoryDlg.
Referenced by GdbCmd_ExamineMemory::GdbCmd_ExamineMemory().
GetWindow()
virtual wxWindow* cbExamineMemoryDlg::GetWindow () pure virtual
Implemented in ExamineMemoryDlg.
Referenced by DebugInterfaceFactory::DeleteMemory(), and DebuggerManager::UpdateExamineMemory().
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp