Code::Blocks: ScopeDialog Class Reference
ScopeDialog Class Reference
Public Member Functions
ScopeDialog (wxWindow *parent, const wxString &title)
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Static Public Attributes
static const long ID_OPEN_FILES = wxNewId()
static const long ID_PROJECT_FILES = wxNewId()
Private Member Functions
void OnClose (cb_unused wxCloseEvent &event)
void OnOpenFilesClick (cb_unused wxCommandEvent &event)
void OnProjectFilesClick (cb_unused wxCommandEvent &event)
Private Attributes
wxButton * m_OpenFiles
wxButton * m_ProjectFiles
Detailed Description
Definition at line 66 of file coderefactoring.cpp.
Constructor & Destructor Documentation
ScopeDialog()
ScopeDialog::ScopeDialog (wxWindow * parent, const wxString & title) inline
Definition at line 69 of file coderefactoring.cpp.
References _(), _T, wxBoxSizer::Add(), wxBoxSizer::Fit(), ConfigManager::GetDataFolder(), ID_OPEN_FILES, ID_PROJECT_FILES, m_OpenFiles, m_ProjectFiles, OnClose(), OnOpenFilesClick(), OnProjectFilesClick(), wxBoxSizer::SetSizeHints(), wxALIGN_CENTER_HORIZONTAL, wxALIGN_CENTER_VERTICAL, wxALL, wxBOTTOM, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEVT_CLOSE_WINDOW, wxHORIZONTAL, wxID_ANY, wxLEFT, wxRIGHT, and wxVERTICAL.
Member Function Documentation
OnClose()
void ScopeDialog::OnClose (cb_unused wxCloseEvent & event) inline private
Definition at line 105 of file coderefactoring.cpp.
References wxID_CLOSE.
Referenced by ScopeDialog().
OnOpenFilesClick()
void ScopeDialog::OnOpenFilesClick (cb_unused wxCommandEvent & event) inline private
Definition at line 106 of file coderefactoring.cpp.
Referenced by ScopeDialog().
OnProjectFilesClick()
void ScopeDialog::OnProjectFilesClick (cb_unused wxCommandEvent & event) inline private
Definition at line 107 of file coderefactoring.cpp.
Referenced by ScopeDialog().
Member Data Documentation
ID_OPEN_FILES
const long ScopeDialog::ID_OPEN_FILES = wxNewId() static
Definition at line 101 of file coderefactoring.cpp.
Referenced by CodeRefactoring::Parse(), and ScopeDialog().
ID_PROJECT_FILES
const long ScopeDialog::ID_PROJECT_FILES = wxNewId() static
Definition at line 102 of file coderefactoring.cpp.
Referenced by CodeRefactoring::Parse(), and ScopeDialog().
m_OpenFiles
wxButton* ScopeDialog::m_OpenFiles private
Definition at line 109 of file coderefactoring.cpp.
Referenced by ScopeDialog().
m_ProjectFiles
wxButton* ScopeDialog::m_ProjectFiles private
Definition at line 110 of file coderefactoring.cpp.
Referenced by ScopeDialog().
The documentation for this class was generated from the following file:
coderefactoring.cpp