Code::Blocks: GdbCmd_InfoRegisters Class Reference
GdbCmd_InfoRegisters Class Reference
Command to obtain register info.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_InfoRegisters (DebuggerDriver *driver, wxString disassemblyFlavor=wxEmptyString)
void ParseOutput (const wxString &output)
Parses the command's output.
void ParseOutputFromOR32gdbPort (const wxString &output)
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
wxString m_disassemblyFlavor
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to obtain register info.
Definition at line 1263 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_InfoRegisters()
GdbCmd_InfoRegisters::GdbCmd_InfoRegisters (DebuggerDriver * driver, wxString disassemblyFlavor = wxEmptyString) inline
Parameters
dlg The disassembly dialog.
Definition at line 1271 of file gdb_commands.h.
References _T, and DebuggerCmd::m_Cmd.
Member Function Documentation
ParseOutput()
void GdbCmd_InfoRegisters::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 1278 of file gdb_commands.h.
References _T, Manager::Get(), GetArrayFromString(), wxArrayString::GetCount(), DebuggerManager::GetCPURegistersDialog(), Manager::GetDebuggerManager(), wxRegEx::GetMatch(), wxRegEx::Matches(), reRegisters(), and cbCPURegistersDlg::SetRegisterValue().
ParseOutputFromOR32gdbPort()
void GdbCmd_InfoRegisters::ParseOutputFromOR32gdbPort (const wxString & output) inline
Definition at line 1326 of file gdb_commands.h.
References _T, wxArrayString::Add(), Manager::Get(), GetArrayFromString(), wxArrayString::GetCount(), DebuggerManager::GetCPURegistersDialog(), Manager::GetDebuggerManager(), wxStringTokenizer::GetNextToken(), wxStringTokenizer::HasMoreTokens(), wxString::IsEmpty(), wxArrayString::Item(), cbCPURegistersDlg::SetRegisterValue(), wxEmptyString, wxT, and wxTOKEN_STRTOK.
Member Data Documentation
m_disassemblyFlavor
wxString GdbCmd_InfoRegisters::m_disassemblyFlavor private
Definition at line 1265 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h