Code::Blocks: WizPage Class Reference
WizPage Class Reference
#include <wizpage.h>
Public Member Functions
WizPage (const wxString &panelName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPage ()
void OnButton (wxCommandEvent &event)
Public Member Functions inherited from WizPageBase
WizPageBase (const wxString &pageName, wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
~WizPageBase ()
virtual bool SkipPage () const
virtual void OnPageChanging (wxWizardEvent &event)
virtual void OnPageChanged (wxWizardEvent &event)
virtual wxWizardPage * GetPrev () const
virtual wxWizardPage * GetNext () const
wxString GetPageName () const
bool GetSkipPage () const
void SetSkipPage (bool skip)
Public Member Functions inherited from wxWizardPageSimple
wxWizardPageSimple ()
wxWizardPageSimple (wxWizard *parent, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent=NULL, wxWizardPage *prev=NULL, wxWizardPage *next=NULL, const wxBitmap &bitmap=wxNullBitmap)
wxWizardPageSimple & Chain (wxWizardPageSimple *next)
void SetNext (wxWizardPage *next)
void SetPrev (wxWizardPage *prev)
Public Member Functions inherited from wxWizardPage
wxWizardPage ()
wxWizardPage (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
bool Create (wxWizard *parent, const wxBitmap &bitmap=wxNullBitmap)
virtual wxBitmap GetBitmap () const
Additional Inherited Members
Static Public Member Functions inherited from wxWizardPageSimple
static void Chain (wxWizardPageSimple *first, wxWizardPageSimple *second)
Detailed Description
Definition at line 58 of file wizpage.h.
Constructor & Destructor Documentation
WizPage()
WizPage::WizPage (const wxString & panelName, wxWizard * parent, const wxBitmap & bitmap = wxNullBitmap)
Definition at line 208 of file wizpage.cpp.
References wxXmlResource::Get(), and wxXmlResource::LoadPanel().
~WizPage()
WizPage::~WizPage ()
Definition at line 215 of file wizpage.cpp.
Member Function Documentation
OnButton()
void WizPage::OnButton (wxCommandEvent & event)
Definition at line 220 of file wizpage.cpp.
References _T, cbU2C(), LogManager::DebugLog(), ScriptingManager::DisplayErrors(), F(), Manager::Get(), Manager::GetLogManager(), and Manager::GetScriptingManager().
Referenced by WizPageBase::OnPageChanged().
The documentation for this class was generated from the following files:
wizpage.h
wizpage.cpp