Code::Blocks: cbTreeCtrl Class Reference
cbTreeCtrl Class Reference
#include <cbtreectrl.h>
Public Member Functions
cbTreeCtrl ()
cbTreeCtrl (wxWindow *parent, int id)
void SetCompareFunction (const int ptvs)
wxTreeItemId GetPrevVisible (const wxTreeItemId &item) const override
Public Member Functions inherited from wxTreeCtrl
wxTreeCtrl ()
wxTreeCtrl (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTR_DEFAULT_STYLE, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxTreeCtrlNameStr)
virtual ~wxTreeCtrl ()
virtual wxTreeItemId AddRoot (const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
wxTreeItemId AppendItem (const wxTreeItemId &parent, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
void AssignButtonsImageList (wxImageList *imageList)
void AssignImageList (wxImageList *imageList)
void AssignStateImageList (wxImageList *imageList)
virtual void Collapse (const wxTreeItemId &item)
void CollapseAll ()
void CollapseAllChildren (const wxTreeItemId &item)
virtual void CollapseAndReset (const wxTreeItemId &item)
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTR_DEFAULT_STYLE, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxTreeCtrlNameStr)
virtual void Delete (const wxTreeItemId &item)
virtual void DeleteAllItems ()
virtual void DeleteChildren (const wxTreeItemId &item)
virtual wxTextCtrl * EditLabel (const wxTreeItemId &item, wxClassInfo *textCtrlClass=wxCLASSINFO(wxTextCtrl))
void EnableBellOnNoMatch (bool on=true)
virtual void EndEditLabel (const wxTreeItemId &item, bool discardChanges=false)
virtual void EnsureVisible (const wxTreeItemId &item)
virtual void Expand (const wxTreeItemId &item)
void ExpandAll ()
void ExpandAllChildren (const wxTreeItemId &item)
virtual bool GetBoundingRect (const wxTreeItemId &item, wxRect &rect, bool textOnly=false) const
wxImageList * GetButtonsImageList () const
virtual size_t GetChildrenCount (const wxTreeItemId &item, bool recursively=true) const
virtual unsigned int GetCount () const
virtual wxTextCtrl * GetEditControl () const
virtual wxTreeItemId GetFirstChild (const wxTreeItemId &item, wxTreeItemIdValue &cookie) const
virtual wxTreeItemId GetFirstVisibleItem () const
virtual wxTreeItemId GetFocusedItem () const
virtual void ClearFocusedItem ()
virtual void SetFocusedItem (const wxTreeItemId &item)
wxImageList * GetImageList () const
virtual unsigned int GetIndent () const
virtual wxColour GetItemBackgroundColour (const wxTreeItemId &item) const
virtual wxTreeItemData * GetItemData (const wxTreeItemId &item) const
virtual wxFont GetItemFont (const wxTreeItemId &item) const
virtual int GetItemImage (const wxTreeItemId &item, wxTreeItemIcon which=wxTreeItemIcon_Normal) const
virtual wxTreeItemId GetItemParent (const wxTreeItemId &item) const
int GetItemState (const wxTreeItemId &item) const
virtual wxString GetItemText (const wxTreeItemId &item) const
virtual wxColour GetItemTextColour (const wxTreeItemId &item) const
virtual wxTreeItemId GetLastChild (const wxTreeItemId &item) const
virtual wxTreeItemId GetNextChild (const wxTreeItemId &item, wxTreeItemIdValue &cookie) const
virtual wxTreeItemId GetNextSibling (const wxTreeItemId &item) const
virtual wxTreeItemId GetNextVisible (const wxTreeItemId &item) const
virtual wxTreeItemId GetPrevSibling (const wxTreeItemId &item) const
bool GetQuickBestSize () const
virtual wxTreeItemId GetRootItem () const
virtual wxTreeItemId GetSelection () const
virtual size_t GetSelections (wxArrayTreeItemIds &selection) const
wxImageList * GetStateImageList () const
wxTreeItemId HitTest (const wxPoint &point, int &flags) const
wxTreeItemId InsertItem (const wxTreeItemId &parent, const wxTreeItemId &previous, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
wxTreeItemId InsertItem (const wxTreeItemId &parent, size_t pos, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
virtual bool IsBold (const wxTreeItemId &item) const
bool IsEmpty () const
virtual bool IsExpanded (const wxTreeItemId &item) const
virtual bool IsSelected (const wxTreeItemId &item) const
virtual bool IsVisible (const wxTreeItemId &item) const
virtual bool ItemHasChildren (const wxTreeItemId &item) const
wxTreeItemId PrependItem (const wxTreeItemId &parent, const wxString &text, int image=-1, int selImage=-1, wxTreeItemData *data=NULL)
virtual void ScrollTo (const wxTreeItemId &item)
virtual void SelectItem (const wxTreeItemId &item, bool select=true)
void SetButtonsImageList (wxImageList *imageList)
virtual void SetImageList (wxImageList *imageList)
virtual void SetIndent (unsigned int indent)
virtual void SetItemBackgroundColour (const wxTreeItemId &item, const wxColour &col)
virtual void SetItemBold (const wxTreeItemId &item, bool bold=true)
virtual void SetItemData (const wxTreeItemId &item, wxTreeItemData *data)
virtual void SetItemDropHighlight (const wxTreeItemId &item, bool highlight=true)
virtual void SetItemFont (const wxTreeItemId &item, const wxFont &font)
virtual void SetItemHasChildren (const wxTreeItemId &item, bool hasChildren=true)
virtual void SetItemImage (const wxTreeItemId &item, int image, wxTreeItemIcon which=wxTreeItemIcon_Normal)
void SetItemState (const wxTreeItemId &item, int state)
virtual void SetItemText (const wxTreeItemId &item, const wxString &text)
virtual void SetItemTextColour (const wxTreeItemId &item, const wxColour &col)
void SetQuickBestSize (bool quickBestSize)
virtual void SetStateImageList (wxImageList *imageList)
void SetWindowStyle (long styles)
virtual void SortChildren (const wxTreeItemId &item)
virtual void Toggle (const wxTreeItemId &item)
void ToggleItemSelection (const wxTreeItemId &item)
virtual void Unselect ()
virtual void UnselectAll ()
void UnselectItem (const wxTreeItemId &item)
virtual void SelectChildren (const wxTreeItemId &parent)
Protected Member Functions
void OnKeyDown (wxKeyEvent &event)
int OnCompareItems (const wxTreeItemId &item1, const wxTreeItemId &item2) override
Static Protected Member Functions
static int filesSort (const ProjectFile *arg1, const ProjectFile *arg2)
static int filesSortNameOnly (const ProjectFile *arg1, const ProjectFile *arg2)
Protected Attributes
int(* Compare)(const ProjectFile *arg1, const ProjectFile *arg2)
Detailed Description
Definition at line 20 of file cbtreectrl.h.
Constructor & Destructor Documentation
cbTreeCtrl() [1/2]
cbTreeCtrl::cbTreeCtrl ()
Definition at line 32 of file cbtreectrl.cpp.
cbTreeCtrl() [2/2]
cbTreeCtrl::cbTreeCtrl (wxWindow * parent, int id)
Definition at line 37 of file cbtreectrl.cpp.
References Compare, filesSort(), wxBORDER_NONE, wxDefaultPosition, wxDefaultSize, wxTR_EDIT_LABELS, wxTR_HAS_BUTTONS, and wxTR_MULTIPLE.
Member Function Documentation
filesSort()
int cbTreeCtrl::filesSort (const ProjectFile * arg1, const ProjectFile * arg2) static protected
Definition at line 135 of file cbtreectrl.cpp.
References ProjectFile::file, and wxFileName::GetFullPath().
Referenced by cbTreeCtrl(), and SetCompareFunction().
filesSortNameOnly()
int cbTreeCtrl::filesSortNameOnly (const ProjectFile * arg1, const ProjectFile * arg2) static protected
Definition at line 142 of file cbtreectrl.cpp.
References ProjectFile::file, and wxFileName::GetFullName().
Referenced by SetCompareFunction().
GetPrevVisible()
wxTreeItemId cbTreeCtrl::GetPrevVisible (const wxTreeItemId & item) const override virtual
Reimplemented from wxTreeCtrl.
Definition at line 53 of file cbtreectrl.cpp.
References wxTreeCtrl::GetItemParent(), wxTreeCtrl::GetLastChild(), wxTreeCtrl::GetPrevSibling(), wxMouseEvent::GetX(), wxTreeCtrl::HitTest(), wxTreeCtrl::IsExpanded(), wxTreeItemId::IsOk(), wxTreeCtrl::ItemHasChildren(), wxEVT_COMMAND_RIGHT_CLICK, and wxPostEvent().
OnCompareItems()
int cbTreeCtrl::OnCompareItems (const wxTreeItemId & item1, const wxTreeItemId & item2) override protected virtual
Reimplemented from wxTreeCtrl.
Definition at line 149 of file cbtreectrl.cpp.
References Compare, and wxTreeCtrl::GetItemData().
OnKeyDown()
void cbTreeCtrl::OnKeyDown (wxKeyEvent & event) protected
Definition at line 95 of file cbtreectrl.cpp.
References wxKeyboardState::GetModifiers(), wxTreeCtrl::GetSelections(), wxTreeItemId::IsOk(), WXK_NUMPAD_ENTER, WXK_RETURN, wxMOD_NONE, and wxPostEvent().
SetCompareFunction()
void cbTreeCtrl::SetCompareFunction (const int ptvs)
Definition at line 44 of file cbtreectrl.cpp.
References Compare, filesSort(), filesSortNameOnly(), ptvsHideFolderName, and ptvsUseFolders.
Referenced by ProjectManagerUI::BuildProjectTree().
Member Data Documentation
Compare
int(* cbTreeCtrl::Compare) (const ProjectFile *arg1, const ProjectFile *arg2) protected
Definition at line 47 of file cbtreectrl.h.
Referenced by cbTreeCtrl(), OnCompareItems(), and SetCompareFunction().
The documentation for this class was generated from the following files:
cbtreectrl.h
cbtreectrl.cpp