Code::Blocks: CfgMgrBldr Class Reference
CfgMgrBldr Class Reference
#include <configmanager.h>
Static Public Member Functions
static ConfigManager * GetConfigManager (const wxString &name_space)
Static Public Member Functions inherited from Mgr< CfgMgrBldr >
static bool Valid ()
static CfgMgrBldr * Get ()
static void Free ()
Protected Member Functions
CfgMgrBldr ()
~CfgMgrBldr ()
Protected Member Functions inherited from Mgr< CfgMgrBldr >
Mgr ()
virtual ~Mgr ()
Private Member Functions
void Flush ()
void Close ()
void SwitchTo (const wxString &absFN)
void SwitchToR (const wxString &absFN)
ConfigManager * Build (const wxString &name_space)
wxString FindConfigFile (const wxString &filename)
wxString DetermineExecutablePath ()
Private Attributes
NamespaceMap namespaces
TiXmlDocument * doc
TiXmlDocument * volatile_doc
wxCriticalSection cs
bool r
wxString cfg
Friends
class ConfigManager
class Mgr< CfgMgrBldr >
Detailed Description
Definition at line 374 of file configmanager.h.
Constructor & Destructor Documentation
CfgMgrBldr()
CfgMgrBldr::CfgMgrBldr () protected
Definition at line 176 of file configmanager.cpp.
References _T, cfg, doc, FindConfigFile(), Manager::Get(), ConfigManager::GetConfigFolder(), wxString::IsEmpty(), ConfigManager::MigrateFolders(), wxString::StartsWith(), SwitchTo(), SwitchToR(), and CfgMgrConsts::version.
~CfgMgrBldr()
CfgMgrBldr::~CfgMgrBldr () protected
Definition at line 338 of file configmanager.cpp.
References Close(), namespaces, and volatile_doc.
Member Function Documentation
Build()
ConfigManager * CfgMgrBldr::Build (const wxString & name_space) private
Definition at line 383 of file configmanager.cpp.
References _(), _T, cbC2U(), cbThrow, cbU2C(), ConfigManager, cs, doc, wxString::Format(), wxString::IsEmpty(), namespaces, wxString::StartsWith(), and volatile_doc.
Referenced by GetConfigManager().
Close()
void CfgMgrBldr::Close () private
Definition at line 366 of file configmanager.cpp.
References doc, and Flush().
Referenced by ~CfgMgrBldr().
DetermineExecutablePath()
wxString CfgMgrBldr::DetermineExecutablePath () private
Referenced by FindConfigFile().
FindConfigFile()
wxString CfgMgrBldr::FindConfigFile (const wxString & filename) private
Definition at line 204 of file configmanager.cpp.
References DetermineExecutablePath(), ConfigManager::GetUserDataFolder(), ConfigManager::has_alternate_user_data_path, ConfigManager::SetUserDataFolder(), wxEmptyString, and wxFileExists().
Referenced by CfgMgrBldr().
Flush()
void CfgMgrBldr::Flush () private
Definition at line 349 of file configmanager.cpp.
References _(), _T, cfg, doc, TinyXML::SaveDocument(), wxString::StartsWith(), and wxSafeShowMessage().
Referenced by Close(), and ConfigManager::Flush().
GetConfigManager()
ConfigManager * CfgMgrBldr::GetConfigManager (const wxString & name_space) static
Definition at line 377 of file configmanager.cpp.
References Build(), and Mgr< CfgMgrBldr >::Get().
Referenced by Manager::GetConfigManager().
SwitchTo()
void CfgMgrBldr::SwitchTo (const wxString & absFN) private
Definition at line 224 of file configmanager.cpp.
References _(), _T, wxString::append(), wxString::c_str(), cbC2U(), cbMessageBox(), cbThrow, doc, wxString::Format(), ConfigManager::GetRevisionNumber(), TinyXML::LoadDocument(), wxString::mb_str(), wxString::Printf(), CfgMgrConsts::version, wxICON_WARNING, and wxT.
Referenced by CfgMgrBldr(), and SwitchToR().
SwitchToR()
void CfgMgrBldr::SwitchToR (const wxString & absFN) private
Definition at line 289 of file configmanager.cpp.
References _T, cbC2U(), cbU2C(), cfg, LogManager::DebugLog(), doc, wxString::Empty(), Manager::Get(), wxURL::GetError(), wxURL::GetInputStream(), Manager::GetLogManager(), ConfigManager::GetProxy(), wxString::GetWriteBuf(), wxURL::SetProxy(), SwitchTo(), wxString::UngetWriteBuf(), wxEmptyString, and wxURL_NOERR.
Referenced by CfgMgrBldr().
Friends And Related Function Documentation
ConfigManager
friend class ConfigManager friend
Definition at line 376 of file configmanager.h.
Referenced by Build().
Mgr< CfgMgrBldr >
friend class Mgr< CfgMgrBldr > friend
Definition at line 377 of file configmanager.h.
Member Data Documentation
cfg
wxString CfgMgrBldr::cfg private
Definition at line 383 of file configmanager.h.
Referenced by CfgMgrBldr(), Flush(), and SwitchToR().
cs
wxCriticalSection CfgMgrBldr::cs private
Definition at line 381 of file configmanager.h.
Referenced by Build(), ConfigManager::Delete(), ConfigManager::DeleteAll(), and ConfigManager::Flush().
doc
TiXmlDocument* CfgMgrBldr::doc private
Definition at line 379 of file configmanager.h.
Referenced by Build(), CfgMgrBldr(), Close(), Flush(), SwitchTo(), and SwitchToR().
namespaces
NamespaceMap CfgMgrBldr::namespaces private
Definition at line 378 of file configmanager.h.
Referenced by Build(), ConfigManager::Delete(), ConfigManager::DeleteAll(), and ~CfgMgrBldr().
r
bool CfgMgrBldr::r private
Definition at line 382 of file configmanager.h.
volatile_doc
TiXmlDocument* CfgMgrBldr::volatile_doc private
Definition at line 380 of file configmanager.h.
Referenced by Build(), and ~CfgMgrBldr().
The documentation for this class was generated from the following files:
configmanager.h
configmanager.cpp