Code::Blocks: ParserThreadedTask Class Reference
ParserThreadedTask Class Reference
#include <parserthreadedtask.h>
Public Member Functions
ParserThreadedTask (Parser *parser, wxMutex &parserCS)
virtual int Execute ()
Override this function with the task's job Return value doesn't matter.
Public Member Functions inherited from cbThreadedTask
cbThreadedTask ()
cbThreadedTask ctor
virtual ~cbThreadedTask ()=0
cbThreadedTask dtor
void Abort ()
This function is called to tell the task to abort (check cbThreadPool::AbortAllTasks)
Private Attributes
Parser * m_Parser
wxMutex & m_ParserMutex
Additional Inherited Members
Protected Member Functions inherited from cbThreadedTask
bool TestDestroy () const
Be sure to call this function often. If it returns true, quit your task quickly.
bool Aborted () const
Same as TestDestroy()
Detailed Description
Definition at line 16 of file parserthreadedtask.h.
Constructor & Destructor Documentation
ParserThreadedTask()
ParserThreadedTask::ParserThreadedTask (Parser * parser, wxMutex & parserCS)
Definition at line 58 of file parserthreadedtask.cpp.
Member Function Documentation
Execute()
int ParserThreadedTask::Execute () virtual
Override this function with the task's job Return value doesn't matter.
Implements cbThreadedTask.
Definition at line 64 of file parserthreadedtask.cpp.
References _T, CC_LOCKER_TRACK_P_MTX_LOCK, CC_LOCKER_TRACK_P_MTX_UNLOCK, Parser::ClearPredefinedMacros(), wxString::IsEmpty(), Parser::m_BatchParseFiles, Parser::m_IgnoreThreadEvents, Parser::m_IsFirstBatch, Parser::m_IsParsing, m_Parser, m_ParserMutex, Parser::m_PredefinedMacros, Parser::Parse(), Parser::ParseBuffer(), and TRACE.
Member Data Documentation
m_Parser
Parser* ParserThreadedTask::m_Parser private
Definition at line 23 of file parserthreadedtask.h.
Referenced by Execute().
m_ParserMutex
wxMutex& ParserThreadedTask::m_ParserMutex private
Definition at line 24 of file parserthreadedtask.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
parserthreadedtask.h
parserthreadedtask.cpp