Code::Blocks: cbBreakpointsDlg Class Reference
cbBreakpointsDlg Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbBreakpointsDlg ()
virtual wxWindow * GetWindow ()=0
virtual bool AddBreakpoint (cbDebuggerPlugin *plugin, const wxString &filename, int line)=0
virtual bool RemoveBreakpoint (cbDebuggerPlugin *plugin, const wxString &filename, int line)=0
virtual void RemoveAllBreakpoints ()=0
virtual void EditBreakpoint (const wxString &filename, int line)=0
virtual void EnableBreakpoint (const wxString &filename, int line, bool enable)=0
virtual void Reload ()=0
Detailed Description
Definition at line 29 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
~cbBreakpointsDlg()
cbBreakpointsDlg::~cbBreakpointsDlg () virtual
Definition at line 11 of file cbdebugger_interfaces.cpp.
Member Function Documentation
AddBreakpoint()
virtual bool cbBreakpointsDlg::AddBreakpoint (cbDebuggerPlugin * plugin, const wxString & filename, int line) pure virtual
Implemented in BreakpointsDlg.
Referenced by cbEditor::AddBreakpoint(), and cbEditor::ToggleBreakpoint().
EditBreakpoint()
virtual void cbBreakpointsDlg::EditBreakpoint (const wxString & filename, int line) pure virtual
Implemented in BreakpointsDlg.
Referenced by cbEditor::OnContextMenuEntry().
EnableBreakpoint()
virtual void cbBreakpointsDlg::EnableBreakpoint (const wxString & filename, int line, bool enable) pure virtual
Implemented in BreakpointsDlg.
Referenced by cbEditor::OnContextMenuEntry().
GetWindow()
virtual wxWindow* cbBreakpointsDlg::GetWindow () pure virtual
Implemented in BreakpointsDlg.
Referenced by DebugInterfaceFactory::DeleteBreakpoints(), and DebuggerMenuHandler::RegisterDefaultWindowItems().
Reload()
virtual void cbBreakpointsDlg::Reload () pure virtual
Implemented in BreakpointsDlg.
Referenced by DebuggerGDB::CleanupWhenProjectClosed(), DebuggerMenuHandler::OnAddDataBreakpoint(), cbEditor::OnEditorModified(), DebuggerGDB::OnGDBTerminated(), WatchesDlg::OnMenuAddDataBreak(), GDB_driver::ParseOutput(), GdbCmd_AddBreakpoint::ParseOutput(), GdbCmd_AddDataBreakpoint::ParseOutput(), DebuggerManager::RefreshUI(), DebuggerGDB::RunToCursor(), and cbEditor::ToggleBreakpoint().
RemoveAllBreakpoints()
virtual void cbBreakpointsDlg::RemoveAllBreakpoints () pure virtual
Implemented in BreakpointsDlg.
Referenced by DebuggerMenuHandler::OnRemoveAllBreakpoints().
RemoveBreakpoint()
virtual bool cbBreakpointsDlg::RemoveBreakpoint (cbDebuggerPlugin * plugin, const wxString & filename, int line) pure virtual
Implemented in BreakpointsDlg.
Referenced by cbEditor::RemoveBreakpoint(), and cbEditor::ToggleBreakpoint().
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp