Code::Blocks: CompilerErrors Class Reference
CompilerErrors Class Reference
#include <compilererrors.h>
Public Member Functions
CompilerErrors ()
virtual ~CompilerErrors ()
void AddError (CompilerLineType lt, cbProject *project, const wxString &filename, long int line, const wxString &error)
void GotoError (int nr)
void Next ()
void Previous ()
void Clear ()
bool HasNextError () const
bool HasPreviousError () const
int GetCount () const
wxString GetErrorString (int index)
unsigned int GetCount (CompilerLineType lt) const
int GetFirstError () const
int GetFocusedError () const
Private Member Functions
void DoAddError (const CompileError &error)
void DoGotoError (const CompileError &error)
void DoClearErrorMarkFromAllEditors ()
int ErrorLineHasMore (const wxString &filename, long int line) const
Private Attributes
ErrorsArray m_Errors
int m_ErrorIndex
Detailed Description
Definition at line 26 of file compilererrors.h.
Constructor & Destructor Documentation
CompilerErrors()
CompilerErrors::CompilerErrors ()
Definition at line 24 of file compilererrors.cpp.
~CompilerErrors()
CompilerErrors::~CompilerErrors () virtual
Definition at line 30 of file compilererrors.cpp.
Member Function Documentation
AddError()
void CompilerErrors::AddError (CompilerLineType lt, cbProject * project, const wxString & filename, long int line, const wxString & error)
Definition at line 35 of file compilererrors.cpp.
References wxArrayString::Add(), DoAddError(), CompileError::errors, CompileError::filename, CompileError::line, CompileError::lineType, ParserConsts::lt, and CompileError::project.
Clear()
void CompilerErrors::Clear ()
Definition at line 104 of file compilererrors.cpp.
References DoClearErrorMarkFromAllEditors(), m_ErrorIndex, and m_Errors.
DoAddError()
void CompilerErrors::DoAddError (const CompileError & error) private
Definition at line 111 of file compilererrors.cpp.
References m_Errors.
Referenced by AddError().
DoClearErrorMarkFromAllEditors()
void CompilerErrors::DoClearErrorMarkFromAllEditors () private
Definition at line 220 of file compilererrors.cpp.
References Manager::Get(), EditorManager::GetBuiltinEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), and cbEditor::SetErrorLine().
Referenced by Clear(), and DoGotoError().
DoGotoError()
void CompilerErrors::DoGotoError (const CompileError & error) private
Definition at line 134 of file compilererrors.cpp.
References _T, EditorBase::Activate(), DoClearErrorMarkFromAllEditors(), ProjectFile::file, CompileError::filename, Manager::Get(), ProjectManager::GetActiveProject(), EditorManager::GetBuiltinEditor(), wxString::GetChar(), cbProject::GetCommonTopLevelPath(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), cbProject::GetFileByFilename(), cbProject::GetFilesList(), wxFileName::GetFullPath(), cbEditor::GetProjectFile(), Manager::GetProjectManager(), cbEditor::GotoLine(), IsSuffixOfPath(), wxString::Length(), CompileError::line, EditorManager::Open(), wxString::Prepend(), CompileError::project, cbEditor::SetErrorLine(), cbEditor::SetProjectFile(), wxString::StartsWith(), and cbEditor::UnfoldBlockFromLine().
Referenced by GotoError(), Next(), and Previous().
ErrorLineHasMore()
int CompilerErrors::ErrorLineHasMore (const wxString & filename, long int line) const private
Definition at line 123 of file compilererrors.cpp.
References m_Errors, and wxString::Matches().
GetCount() [1/2]
int CompilerErrors::GetCount () const inline
Definition at line 40 of file compilererrors.h.
GetCount() [2/2]
unsigned int CompilerErrors::GetCount (CompilerLineType lt) const
Definition at line 262 of file compilererrors.cpp.
References m_Errors.
GetErrorString()
wxString CompilerErrors::GetErrorString (int index)
Definition at line 241 of file compilererrors.cpp.
References wxArrayString::GetCount(), m_Errors, and wxEmptyString.
GetFirstError()
int CompilerErrors::GetFirstError () const
Definition at line 252 of file compilererrors.cpp.
References cltError, and m_Errors.
GetFocusedError()
int CompilerErrors::GetFocusedError () const inline
Definition at line 46 of file compilererrors.h.
GotoError()
void CompilerErrors::GotoError (int nr)
Definition at line 46 of file compilererrors.cpp.
References DoGotoError(), m_ErrorIndex, and m_Errors.
Referenced by CompilerMessages::OnClick().
HasNextError()
bool CompilerErrors::HasNextError () const
Definition at line 231 of file compilererrors.cpp.
References m_ErrorIndex, and m_Errors.
HasPreviousError()
bool CompilerErrors::HasPreviousError () const
Definition at line 236 of file compilererrors.cpp.
References m_ErrorIndex.
Next()
void CompilerErrors::Next ()
Definition at line 54 of file compilererrors.cpp.
References _T, cltError, DoGotoError(), m_ErrorIndex, and m_Errors.
Previous()
void CompilerErrors::Previous ()
Definition at line 79 of file compilererrors.cpp.
References _T, cltError, DoGotoError(), m_ErrorIndex, and m_Errors.
Member Data Documentation
m_ErrorIndex
int CompilerErrors::m_ErrorIndex private
Definition at line 53 of file compilererrors.h.
Referenced by Clear(), GotoError(), HasNextError(), HasPreviousError(), Next(), and Previous().
m_Errors
ErrorsArray CompilerErrors::m_Errors private
Definition at line 52 of file compilererrors.h.
Referenced by Clear(), DoAddError(), ErrorLineHasMore(), GetCount(), GetErrorString(), GetFirstError(), GotoError(), HasNextError(), Next(), and Previous().
The documentation for this class was generated from the following files:
compilererrors.h
compilererrors.cpp