Code::Blocks: dlgAbout Class Reference
dlgAbout Class Reference
#include <dlgabout.h>
Public Member Functions
dlgAbout (wxWindow *parent)
~dlgAbout ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Detailed Description
Definition at line 13 of file dlgabout.h.
Constructor & Destructor Documentation
dlgAbout()
dlgAbout::dlgAbout (wxWindow * parent)
Definition at line 43 of file dlgabout.cpp.
References _(), _T, appglobals::AppActualVersionVerb, appglobals::AppBuildTimestamp, appglobals::AppContactEmail, appglobals::AppName, appglobals::AppSDKVersion, appglobals::AppUrl, appglobals::AppVersion, cbMessageBox(), wxImage::ConvertAlphaToMask(), cbSplashScreen::DrawReleaseInfo(), wxString::Format(), wxXmlResource::Get(), wxImage::GetHeight(), wxScintilla::GetLibraryVersionInfo(), wxVersionInfo::GetMajor(), wxVersionInfo::GetMicro(), wxVersionInfo::GetMinor(), wxImage::GetWidth(), LICENSE_GPL, wxImage::LoadFile(), ConfigManager::ReadDataPath(), wxStaticBitmap::SetBitmap(), wxFont::SetPointSize(), wxBITMAP_TYPE_PNG, wxICON_EXCLAMATION, wxSCINTILLA_VERSION, and wxT.
~dlgAbout()
dlgAbout::~dlgAbout ()
Definition at line 169 of file dlgabout.cpp.
The documentation for this class was generated from the following files:
dlgabout.h
dlgabout.cpp