Code::Blocks: WatchRawDialog Class Reference
WatchRawDialog Class Reference
dialog to show the value of a watch
Static Public Member Functions
static WatchRawDialog * Create (const WatchesProperty *watch)
static void UpdateValue (const WatchesProperty *watch)
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Private Types
enum Type { TypeNormal, TypeDebug, TypeWatchTree }
typedef std::map< cbWatch const *, WatchRawDialog * > Map
Private Member Functions
WatchRawDialog ()
void OnClose (cb_unused wxCloseEvent &event)
void SetValue (const WatchesProperty *watch)
Static Private Member Functions
static void WatchToString (wxString &result, const cbWatch &watch, const wxString &indent=wxEmptyString)
Private Attributes
wxTextCtrl * m_text
Type m_type
Static Private Attributes
static Map s_dialogs
Additional Inherited Members
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
dialog to show the value of a watch
Member Typedef Documentation
typedef std::map<cbWatch const*, WatchRawDialog*> WatchRawDialog::Map private
Member Enumeration Documentation
enum WatchRawDialog::Type private
Enumerator
TypeNormal
TypeDebug
TypeWatchTree
Constructor & Destructor Documentation
WatchRawDialog::WatchRawDialog () inline private
Member Function Documentation
static WatchRawDialog* WatchRawDialog::Create (const WatchesProperty * watch) inline static
References cbAssert, WatchesProperty::GetWatch(), and s_dialogs.
Referenced by WatchRawDialogAdapter::DoShowDialog().
void WatchRawDialog::OnClose (cb_unused wxCloseEvent & event) inline private
void WatchRawDialog::SetValue (const WatchesProperty * watch) inline private
References WatchesProperty::GetWatch(), and WatchToString().
static void WatchRawDialog::UpdateValue (const WatchesProperty * watch) inline static
References WatchesProperty::GetWatch().
Referenced by AppendChildren(), and UpdateWatch().
static void WatchRawDialog::WatchToString (wxString & result, const cbWatch & watch, const wxString & indent = wxEmptyString) inline static private
References cbWatch::GetChild(), cbWatch::GetChildCount(), cbWatch::GetSymbol(), cbWatch::GetValue(), and WatchToString().
Member Data Documentation
wxTextCtrl* WatchRawDialog::m_text private
Type WatchRawDialog::m_type private
WatchRawDialog::Map WatchRawDialog::s_dialogs static private
Referenced by Create().
The documentation for this class was generated from the following file:
watchesdlg.cpp