Code::Blocks: EditArrayOrderDlg Class Reference
EditArrayOrderDlg Class Reference
#include <editarrayorderdlg.h>
Public Member Functions
EditArrayOrderDlg (wxWindow *parent, const wxArrayString &array)
~EditArrayOrderDlg ()
EditArrayOrderDlg & operator= (const EditArrayOrderDlg &)
void SetArray (const wxArrayString &array)
const wxArrayString & GetArray ()
void EndModal (int retCode)
void OnMoveUp (wxCommandEvent &event)
void OnMoveDown (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Private Member Functions
void DoFillList ()
Private Attributes
wxArrayString m_Array
Detailed Description
Definition at line 16 of file editarrayorderdlg.h.
Constructor & Destructor Documentation
EditArrayOrderDlg()
EditArrayOrderDlg::EditArrayOrderDlg (wxWindow * parent, const wxArrayString & array)
Definition at line 28 of file editarrayorderdlg.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadObject().
~EditArrayOrderDlg()
EditArrayOrderDlg::~EditArrayOrderDlg ()
Definition at line 37 of file editarrayorderdlg.cpp.
Member Function Documentation
DoFillList()
void EditArrayOrderDlg::DoFillList () private
Definition at line 41 of file editarrayorderdlg.cpp.
References wxArrayString::GetCount(), and m_Array.
EndModal()
void EditArrayOrderDlg::EndModal (int retCode)
Definition at line 85 of file editarrayorderdlg.cpp.
References wxArrayString::Add(), wxArrayString::Clear(), ScriptBindings::EndModal(), m_Array, and wxID_OK.
GetArray()
const wxArrayString& EditArrayOrderDlg::GetArray () inline
Definition at line 25 of file editarrayorderdlg.h.
References ScriptBindings::EndModal().
Referenced by ProjectOptionsDlg::OnBuildOrderClick(), and ScriptBindings::Register_UtilDialogs().
OnMoveDown()
void EditArrayOrderDlg::OnMoveDown (wxCommandEvent & event)
Definition at line 71 of file editarrayorderdlg.cpp.
OnMoveUp()
void EditArrayOrderDlg::OnMoveUp (wxCommandEvent & event)
Definition at line 57 of file editarrayorderdlg.cpp.
OnUpdateUI()
void EditArrayOrderDlg::OnUpdateUI (wxUpdateUIEvent & event)
Definition at line 49 of file editarrayorderdlg.cpp.
operator=()
EditArrayOrderDlg& EditArrayOrderDlg::operator= (const EditArrayOrderDlg &) inline
Definition at line 23 of file editarrayorderdlg.h.
SetArray()
void EditArrayOrderDlg::SetArray (const wxArrayString & array) inline
Definition at line 24 of file editarrayorderdlg.h.
Referenced by ScriptBindings::Register_UtilDialogs().
Member Data Documentation
m_Array
wxArrayString EditArrayOrderDlg::m_Array private
Definition at line 32 of file editarrayorderdlg.h.
Referenced by DoFillList(), and EndModal().
The documentation for this class was generated from the following files:
editarrayorderdlg.h
editarrayorderdlg.cpp