Code::Blocks: TargetListData Class Reference
TargetListData Class Reference
Store target UI data for every target in the list box control in the SelectTargetDlg.
Public Member Functions
TargetListData (const wxString &ExecParameters, const wxString &HostApp, bool RunHostAppInTerminal, bool DefaultExecTarget)
void SetExecParameters (const wxString &ExecParameters)
void SetHostApp (const wxString &hostApp)
void SetRunHostAppInTerminal (bool runAppInTerminal)
void SetDefaultExecTarget (bool defaultTarget)
const wxString & GetHostApp () const
const wxString & GetExecParameters () const
bool GetRunHostAppInTerminal () const
bool GetDefaultExecTarget () const
Public Member Functions inherited from wxClientData
wxClientData ()
virtual ~wxClientData ()
Private Attributes
wxString m_HostApp
wxString m_ExecParameters
bool m_RunHostAppInTerminal
bool m_DefaultExecTarget
Detailed Description
Store target UI data for every target in the list box control in the SelectTargetDlg.
This makes it possible to edit all targets in one go. It also make implementing the Cancel button possible.
Definition at line 29 of file selecttargetdlg.cpp.
Constructor & Destructor Documentation
TargetListData()
TargetListData::TargetListData (const wxString & ExecParameters, const wxString & HostApp, bool RunHostAppInTerminal, bool DefaultExecTarget) inline
Definition at line 32 of file selecttargetdlg.cpp.
Referenced by SelectTargetDlg::SelectTargetDlg().
Member Function Documentation
GetDefaultExecTarget()
bool TargetListData::GetDefaultExecTarget () const inline
Definition at line 57 of file selecttargetdlg.cpp.
References m_DefaultExecTarget.
GetExecParameters()
const wxString& TargetListData::GetExecParameters () const inline
Definition at line 55 of file selecttargetdlg.cpp.
References m_ExecParameters.
GetHostApp()
const wxString& TargetListData::GetHostApp () const inline
Definition at line 54 of file selecttargetdlg.cpp.
References m_HostApp.
GetRunHostAppInTerminal()
bool TargetListData::GetRunHostAppInTerminal () const inline
Definition at line 56 of file selecttargetdlg.cpp.
References m_RunHostAppInTerminal.
SetDefaultExecTarget()
void TargetListData::SetDefaultExecTarget (bool defaultTarget) inline
Definition at line 52 of file selecttargetdlg.cpp.
References m_DefaultExecTarget.
Referenced by SelectTargetDlg::UpdateSelected().
SetExecParameters()
void TargetListData::SetExecParameters (const wxString & ExecParameters) inline
Definition at line 41 of file selecttargetdlg.cpp.
References _T, m_ExecParameters, and wxString::Replace().
Referenced by SelectTargetDlg::UpdateSelected().
SetHostApp()
void TargetListData::SetHostApp (const wxString & hostApp) inline
Definition at line 50 of file selecttargetdlg.cpp.
References m_HostApp.
SetRunHostAppInTerminal()
void TargetListData::SetRunHostAppInTerminal (bool runAppInTerminal) inline
Definition at line 51 of file selecttargetdlg.cpp.
References m_RunHostAppInTerminal.
Member Data Documentation
m_DefaultExecTarget
bool TargetListData::m_DefaultExecTarget private
Definition at line 63 of file selecttargetdlg.cpp.
Referenced by GetDefaultExecTarget(), and SetDefaultExecTarget().
m_ExecParameters
wxString TargetListData::m_ExecParameters private
Definition at line 61 of file selecttargetdlg.cpp.
Referenced by GetExecParameters(), and SetExecParameters().
m_HostApp
wxString TargetListData::m_HostApp private
Definition at line 60 of file selecttargetdlg.cpp.
Referenced by GetHostApp(), and SetHostApp().
m_RunHostAppInTerminal
bool TargetListData::m_RunHostAppInTerminal private
Definition at line 62 of file selecttargetdlg.cpp.
Referenced by GetRunHostAppInTerminal(), and SetRunHostAppInTerminal().
The documentation for this class was generated from the following file:
selecttargetdlg.cpp