Code::Blocks: CompilerOWGenerator Class Reference
CompilerOWGenerator Class Reference
#include <compilerOWgenerator.h>
Public Member Functions
CompilerOWGenerator ()
virtual ~CompilerOWGenerator ()
virtual wxString SetupLibrariesDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup linker include dirs for build target.
virtual wxString SetupLinkerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup linker flags for build target.
virtual wxString SetupLinkLibraries (Compiler *compiler, ProjectBuildTarget *target)
Setup link libraries for build target.
Public Member Functions inherited from CompilerCommandGenerator
CompilerCommandGenerator ()
virtual ~CompilerCommandGenerator ()
virtual void Init (cbProject *project)
Initialize for use with the specified project.
virtual void GenerateCommandLine (wxString &macro, ProjectBuildTarget *target, ProjectFile *pf, const wxString &file, const wxString &object, const wxString &flat_object, const wxString &deps)
Get the command line to compile/link the specific file.
virtual const wxArrayString & GetCompilerSearchDirs (ProjectBuildTarget *target)
Get the full include dirs used in the actual command line.
virtual const wxArrayString & GetLinkerSearchDirs (ProjectBuildTarget *target)
Get the full linker dirs used in the actual command line.
Private Member Functions
wxString MapTargetType (const wxString &Opt, int target_type)
wxString MapDebugOptions (const wxString &Opt)
void MapDebuggerOptions (const wxString &Opt)
Private Attributes
wxString m_DebuggerType
Additional Inherited Members
Protected Member Functions inherited from CompilerCommandGenerator
virtual void DoBuildScripts (cbProject *project, CompileTargetBase *target, const wxString &funcName)
Apply pre-build scripts for base.
virtual wxString GetOrderedOptions (const ProjectBuildTarget *target, OptionsRelationType rel, const wxString &project_options, const wxString &target_options)
Arrange order of options.
virtual wxArrayString GetOrderedOptions (const ProjectBuildTarget *target, OptionsRelationType rel, const wxArrayString &project_options, const wxArrayString &target_options)
Arrange order of options.
virtual wxArrayString GetOrderedIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxArrayString GetOrderedLibrariesDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxArrayString GetOrderedResourceIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
virtual wxString SetupOutputFilenames (Compiler *compiler, ProjectBuildTarget *target)
Setup output filename for build target.
virtual wxString SetupIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup compiler include dirs for build target.
virtual wxString SetupResourceIncludeDirs (Compiler *compiler, ProjectBuildTarget *target)
Setup resource compiler include dirs for build target.
virtual wxString SetupCompilerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup compiler flags for build target.
virtual wxString SetupResourceCompilerOptions (Compiler *compiler, ProjectBuildTarget *target)
Setup resource compiler flags for build target.
virtual wxString FixupLinkLibraries (Compiler *compiler, const wxString &lib)
Fix library name based on advanced compiler settings.
virtual void FixPathSeparators (Compiler *compiler, wxString &inAndOut)
Static Protected Member Functions inherited from CompilerCommandGenerator
static wxString MakeOptString (const wxArrayString &arr, const wxString &opt, wxChar separator=_T(' '))
static wxString PathSearch (const wxArrayString &arr, const wxString &filename)
Protected Attributes inherited from CompilerCommandGenerator
OptionsMap m_Output
output filenames, per-target
OptionsMap m_StaticOutput
static output filenames, per-target
OptionsMap m_DefOutput
def output filenames, per-target
OptionsMap m_Inc
compiler 'include' dirs, per-target
OptionsMap m_Lib
linker 'include' dirs, per-target
OptionsMap m_RC
resource compiler 'include' dirs, per-target
OptionsMap m_CFlags
compiler flags, per-target
OptionsMap m_RCFlags
resource compiler flags, per-target
OptionsMap m_LDFlags
linker flags, per-target
OptionsMap m_LDAdd
link libraries, per-target
wxString m_PrjIncPath
directive to add the project's top-level path in compiler search dirs (ready for the command line)
SearchDirsMap m_CompilerSearchDirs
array of final compiler search dirs, per-target
SearchDirsMap m_LinkerSearchDirs
array of final linker search dirs, per-target
Detailed Description
Definition at line 13 of file compilerOWgenerator.h.
Constructor & Destructor Documentation
CompilerOWGenerator()
CompilerOWGenerator::CompilerOWGenerator ()
Definition at line 22 of file compilerOWgenerator.cpp.
References m_DebuggerType, and wxEmptyString.
~CompilerOWGenerator()
CompilerOWGenerator::~CompilerOWGenerator () virtual
Definition at line 28 of file compilerOWgenerator.cpp.
Member Function Documentation
MapDebuggerOptions()
void CompilerOWGenerator::MapDebuggerOptions (const wxString & Opt) private
Definition at line 259 of file compilerOWgenerator.cpp.
References _T, wxString::IsSameAs(), m_DebuggerType, and wxEmptyString.
Referenced by SetupLinkerOptions().
MapDebugOptions()
wxString CompilerOWGenerator::MapDebugOptions (const wxString & Opt) private
Definition at line 241 of file compilerOWgenerator.cpp.
References _T, wxString::IsSameAs(), m_DebuggerType, and wxEmptyString.
Referenced by SetupLinkerOptions().
MapTargetType()
wxString CompilerOWGenerator::MapTargetType (const wxString & Opt, int target_type) private
Definition at line 217 of file compilerOWgenerator.cpp.
References _T, wxString::IsSameAs(), ttConsoleOnly, ttDynamicLib, ttExecutable, ttStaticLib, and wxEmptyString.
Referenced by SetupLinkerOptions().
SetupLibrariesDirs()
wxString CompilerOWGenerator::SetupLibrariesDirs (Compiler * compiler, ProjectBuildTarget * target) virtual
Setup linker include dirs for build target.
Reimplemented from CompilerCommandGenerator.
Definition at line 33 of file compilerOWgenerator.cpp.
References _T, Manager::Get(), wxArrayString::GetCount(), CompileOptionsBase::GetLibDirs(), Manager::GetMacrosManager(), CompilerCommandGenerator::GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), Compiler::GetSwitches(), wxArrayString::IsEmpty(), wxString::IsSameAs(), CompilerSwitches::libDirs, ortLibDirs, wxString::RemoveLast(), MacrosManager::ReplaceMacros(), wxString::Right(), wxString::Trim(), and wxEmptyString.
SetupLinkerOptions()
wxString CompilerOWGenerator::SetupLinkerOptions (Compiler * compiler, ProjectBuildTarget * target) virtual
Setup linker flags for build target.
Reimplemented from CompilerCommandGenerator.
Definition at line 79 of file compilerOWgenerator.cpp.
References _T, wxArrayString::Add(), wxString::AfterFirst(), wxString::Append(), wxString::Find(), Manager::Get(), CompileOptionsBase::GetCompilerOptions(), wxArrayString::GetCount(), CompileOptionsBase::GetLinkerOptions(), Manager::GetMacrosManager(), CompilerCommandGenerator::GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), CompileTargetBase::GetTargetType(), wxArrayString::IsEmpty(), wxString::IsEmpty(), wxString::Length(), MapDebuggerOptions(), MapDebugOptions(), MapTargetType(), wxString::Matches(), wxString::Mid(), ortLinkerOptions, MacrosManager::ReplaceMacros(), wxString::StartsWith(), wxEmptyString, and wxNOT_FOUND.
SetupLinkLibraries()
wxString CompilerOWGenerator::SetupLinkLibraries (Compiler * compiler, ProjectBuildTarget * target) virtual
Setup link libraries for build target.
Reimplemented from CompilerCommandGenerator.
Definition at line 181 of file compilerOWgenerator.cpp.
References _T, wxArrayString::GetCount(), CompileOptionsBase::GetLinkLibs(), CompilerCommandGenerator::GetOrderedOptions(), ProjectBuildTarget::GetParentProject(), wxString::IsEmpty(), wxString::IsSameAs(), ortLinkerOptions, wxString::Prepend(), wxString::RemoveLast(), wxString::Right(), and wxString::Trim().
Member Data Documentation
m_DebuggerType
wxString CompilerOWGenerator::m_DebuggerType private
Definition at line 32 of file compilerOWgenerator.h.
Referenced by CompilerOWGenerator(), MapDebuggerOptions(), and MapDebugOptions().
The documentation for this class was generated from the following files:
compilerOWgenerator.h
compilerOWgenerator.cpp