Code::Blocks: GenericMultiLineNotesDlg Class Reference
GenericMultiLineNotesDlg Class Reference
#include <genericmultilinenotesdlg.h>
Public Member Functions
GenericMultiLineNotesDlg (wxWindow *parent, const wxString &caption=_("Notes"), const wxString &notes=wxEmptyString, bool readOnly=true)
virtual ~GenericMultiLineNotesDlg ()
GenericMultiLineNotesDlg & operator= (const GenericMultiLineNotesDlg &)
const wxString & GetNotes ()
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Attributes
wxString m_Notes
bool m_ReadOnly
Detailed Description
Definition at line 13 of file genericmultilinenotesdlg.h.
Constructor & Destructor Documentation
GenericMultiLineNotesDlg()
GenericMultiLineNotesDlg::GenericMultiLineNotesDlg (wxWindow * parent, const wxString & caption = _("Notes"), const wxString & notes = wxEmptyString, bool readOnly = true)
Definition at line 24 of file genericmultilinenotesdlg.cpp.
References _T, wxXmlResource::Get(), wxXmlResource::LoadObject(), and wxID_CANCEL.
~GenericMultiLineNotesDlg()
GenericMultiLineNotesDlg::~GenericMultiLineNotesDlg () virtual
Definition at line 50 of file genericmultilinenotesdlg.cpp.
Member Function Documentation
EndModal()
void GenericMultiLineNotesDlg::EndModal (int retCode)
Definition at line 55 of file genericmultilinenotesdlg.cpp.
References ScriptBindings::EndModal(), m_Notes, m_ReadOnly, and wxID_OK.
Referenced by GetNotes().
GetNotes()
const wxString& GenericMultiLineNotesDlg::GetNotes () inline
Definition at line 20 of file genericmultilinenotesdlg.h.
References EndModal(), and m_Notes.
Referenced by ScriptBindings::Register_UtilDialogs(), and cbProject::ShowNotes().
operator=()
GenericMultiLineNotesDlg& GenericMultiLineNotesDlg::operator= (const GenericMultiLineNotesDlg &) inline
Definition at line 18 of file genericmultilinenotesdlg.h.
Member Data Documentation
m_Notes
wxString GenericMultiLineNotesDlg::m_Notes protected
Definition at line 23 of file genericmultilinenotesdlg.h.
Referenced by EndModal(), and GetNotes().
m_ReadOnly
bool GenericMultiLineNotesDlg::m_ReadOnly protected
Definition at line 24 of file genericmultilinenotesdlg.h.
Referenced by EndModal().
The documentation for this class was generated from the following files:
genericmultilinenotesdlg.h
genericmultilinenotesdlg.cpp