Code::Blocks: cbStackFrame Class Reference
cbStackFrame Class Reference
#include <debuggermanager.h>
Public Member Functions
cbStackFrame ()
void SetNumber (int number)
void SetAddress (uint64_t address)
void SetSymbol (const wxString &symbol)
void SetFile (const wxString &filename, const wxString &line)
void MakeValid (bool flag)
int GetNumber () const
uint64_t GetAddress () const
wxString GetAddressAsString () const
const wxString & GetSymbol () const
const wxString & GetFilename () const
const wxString & GetLine () const
bool IsValid () const
Private Attributes
bool m_valid
Is this stack frame valid?
int m_number
Stack frame's number (used in backtraces).
uint64_t m_address
Stack frame's address.
wxString m_symbol
Current function name.
wxString m_file
Current file.
wxString m_line
Current line in file.
Detailed Description
Definition at line 111 of file debuggermanager.h.
Constructor & Destructor Documentation
cbStackFrame()
cbStackFrame::cbStackFrame ()
Definition at line 230 of file debuggermanager.cpp.
Member Function Documentation
GetAddress()
uint64_t cbStackFrame::GetAddress () const
Definition at line 266 of file debuggermanager.cpp.
References m_address.
Referenced by SUITE().
GetAddressAsString()
wxString cbStackFrame::GetAddressAsString () const
Definition at line 271 of file debuggermanager.cpp.
References cbDebuggerAddressToString(), m_address, and wxEmptyString.
Referenced by DisassemblyDlg::Clear(), and CdbCmd_Backtrace::ParseOutput().
GetFilename()
const wxString & cbStackFrame::GetFilename () const
Definition at line 284 of file debuggermanager.cpp.
References m_file.
Referenced by CdbCmd_Backtrace::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), and SUITE().
GetLine()
const wxString & cbStackFrame::GetLine () const
Definition at line 289 of file debuggermanager.cpp.
References m_line.
Referenced by CdbCmd_Backtrace::ParseOutput(), GdbCmd_Backtrace::ParseOutput(), and SUITE().
GetNumber()
int cbStackFrame::GetNumber () const
Definition at line 261 of file debuggermanager.cpp.
References m_number.
Referenced by GdbCmd_Backtrace::ParseOutput(), and SUITE().
GetSymbol()
const wxString & cbStackFrame::GetSymbol () const
Definition at line 279 of file debuggermanager.cpp.
References m_symbol.
Referenced by DisassemblyDlg::Clear(), CdbCmd_DisassemblyInit::ParseOutput(), and SUITE().
IsValid()
bool cbStackFrame::IsValid () const
Definition at line 294 of file debuggermanager.cpp.
References m_valid.
Referenced by DisassemblyDlg::Clear(), and CdbCmd_Backtrace::ParseOutput().
MakeValid()
void cbStackFrame::MakeValid (bool flag)
Definition at line 256 of file debuggermanager.cpp.
References m_valid.
Referenced by GdbCmd_Backtrace::MatchLine(), CdbCmd_Backtrace::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_DisassemblyInit::ParseOutput().
SetAddress()
void cbStackFrame::SetAddress (uint64_t address)
Definition at line 240 of file debuggermanager.cpp.
References m_address.
Referenced by GdbCmd_Backtrace::MatchLine(), CdbCmd_Backtrace::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_DisassemblyInit::ParseOutput().
SetFile()
void cbStackFrame::SetFile (const wxString & filename, const wxString & line)
Definition at line 250 of file debuggermanager.cpp.
References m_file, and m_line.
Referenced by GdbCmd_Backtrace::MatchLine(), and CdbCmd_Backtrace::ParseOutput().
SetNumber()
void cbStackFrame::SetNumber (int number)
Definition at line 235 of file debuggermanager.cpp.
References m_number.
Referenced by GdbCmd_Backtrace::MatchLine(), and CdbCmd_Backtrace::ParseOutput().
SetSymbol()
void cbStackFrame::SetSymbol (const wxString & symbol)
Definition at line 245 of file debuggermanager.cpp.
References m_symbol.
Referenced by GdbCmd_Backtrace::MatchLine(), CdbCmd_Backtrace::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_DisassemblyInit::ParseOutput().
Member Data Documentation
m_address
uint64_t cbStackFrame::m_address private
Stack frame's address.
Definition at line 132 of file debuggermanager.h.
Referenced by GetAddress(), GetAddressAsString(), and SetAddress().
m_file
wxString cbStackFrame::m_file private
Current file.
Definition at line 134 of file debuggermanager.h.
Referenced by GetFilename(), and SetFile().
m_line
wxString cbStackFrame::m_line private
Current line in file.
Definition at line 135 of file debuggermanager.h.
Referenced by GetLine(), and SetFile().
m_number
int cbStackFrame::m_number private
Stack frame's number (used in backtraces).
Definition at line 131 of file debuggermanager.h.
Referenced by cbThread::cbThread(), GetNumber(), cbThread::GetNumber(), and SetNumber().
m_symbol
wxString cbStackFrame::m_symbol private
Current function name.
Definition at line 133 of file debuggermanager.h.
Referenced by GetSymbol(), and SetSymbol().
m_valid
bool cbStackFrame::m_valid private
Is this stack frame valid?
Definition at line 130 of file debuggermanager.h.
Referenced by IsValid(), and MakeValid().
The documentation for this class was generated from the following files:
debuggermanager.h
debuggermanager.cpp