Code::Blocks: cbThreadPool::CountedPtr< T > Class Template Reference
cbThreadPool::CountedPtr< T > Class Template Reference
Josuttis' implementation of CountedPtr.
Public Member Functions
CountedPtr (T *p=0)
CountedPtr (const CountedPtr< T > &p) throw ()
~CountedPtr () throw ()
CountedPtr< T > & operator= (const CountedPtr< T > &p) throw ()
T & operator* () const throw ()
T * operator-> () const throw ()
Private Member Functions
void dispose ()
Private Attributes
T * ptr
long * count
Detailed Description
template<typename T>
class cbThreadPool::CountedPtr< T >
Josuttis' implementation of CountedPtr.
Constructor & Destructor Documentation
template<typename T> cbThreadPool::CountedPtr< T >::CountedPtr (T * p = 0) inline explicit
template<typename T> cbThreadPool::CountedPtr< T >::CountedPtr (const CountedPtr< T > & p) throw () inline
template<typename T > cbThreadPool::CountedPtr< T >::~CountedPtr () throw () inline
Member Function Documentation
template<typename T > void cbThreadPool::CountedPtr< T >::dispose () inline private
References ParserConsts::ptr().
template<typename T > T & cbThreadPool::CountedPtr< T >::operator* () const throw () inline
References ParserConsts::ptr().
template<typename T > T * cbThreadPool::CountedPtr< T >::operator-> () const throw () inline
References ParserConsts::ptr().
template<typename T> cbThreadPool::CountedPtr< T > & cbThreadPool::CountedPtr< T >::operator= (const CountedPtr< T > & p) throw () inline
Member Data Documentation
template<typename T> long* cbThreadPool::CountedPtr< T >::count private
template<typename T> T* cbThreadPool::CountedPtr< T >::ptr private
The documentation for this class was generated from the following file:
cbthreadpool.h