Code::Blocks: GDB_driver Class Reference
GDB_driver Class Reference
#include <gdb_driver.h>
Public Member Functions
GDB_driver (DebuggerGDB *plugin)
virtual ~GDB_driver ()
virtual wxString GetCommandLine (const wxString &debugger, const wxString &debuggee, const wxString &userArguments)
Get the command-line to launch the debugger.
virtual wxString GetCommandLine (const wxString &debugger, int pid, const wxString &userArguments)
Get the command-line to launch the debugger.
virtual void SetTarget (ProjectBuildTarget *target)
Sets the target.
virtual void Prepare (bool isConsole, int printElements)
Prepares the debugging process by setting up search dirs etc.
virtual void Start (bool breakOnEntry)
Begin the debugging process by launching a program.
virtual void Stop ()
Stop debugging.
virtual void Continue ()
virtual void Step ()
virtual void StepInstruction ()
virtual void StepIntoInstruction ()
virtual void StepIn ()
virtual void StepOut ()
virtual void SetNextStatement (const wxString &filename, int line)
virtual void Backtrace ()
virtual void Disassemble ()
virtual void CPURegisters ()
virtual void SwitchToFrame (size_t number)
virtual void SetVarValue (const wxString &var, const wxString &value)
virtual void MemoryDump ()
virtual void Attach (int pid)
Attach to process.
virtual void Detach ()
Detach from running process.
virtual void RunningThreads ()
void InfoFrame ()
void InfoDLL ()
void InfoFiles ()
void InfoFPU ()
void InfoSignals ()
void EnableCatchingThrow (bool enable)
virtual void SwitchThread (size_t threadIndex)
Request to switch to another thread.
virtual void AddBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp)
Add a breakpoint.
virtual void RemoveBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp)
Remove a breakpoint.
virtual void EvaluateSymbol (const wxString &symbol, const wxRect &tipRect)
Evaluate a symbol.
virtual void UpdateWatches (cb::shared_ptr< GDBWatch > localsWatch, cb::shared_ptr< GDBWatch > funcArgsWatch, WatchesContainer &watches)
Update watches.
virtual void UpdateWatch (const cb::shared_ptr< GDBWatch > &watch)
virtual void UpdateWatchLocalsArgs (cb::shared_ptr< GDBWatch > const &watch, bool locals)
virtual void ParseOutput (const wxString &output)
Parse debugger's output.
virtual bool IsDebuggingStarted () const
Is debugging started.
virtual bool UseDebugBreakProcess ()
Ask the driver if the debugger should be interrupted with DebugBreakProcess or Ctrl+C event.
virtual wxString GetDisassemblyFlavour (void)
wxString GetScriptedTypeCommand (const wxString &gdb_type, wxString &parse_func)
wxString AsmFlavour ()
Public Member Functions inherited from DebuggerDriver
DebuggerDriver (DebuggerGDB *plugin)
virtual ~DebuggerDriver ()
void Log (const wxString &msg)
void DebugLog (const wxString &msg)
DebuggerGDB * GetDebugger ()
virtual void AddDirectory (const wxString &dir)
Add a directory in search list.
virtual void ClearDirectories ()
Clear directories search list.
virtual void SetWorkingDirectory (const wxString &dir)
Set the working directory.
virtual void SetArguments (const wxString &args)
Set the execution arguments.
bool IsProgramStopped () const
Is the program stopped?
void MarkProgramStopped (bool stopped)
bool IsQueueBusy () const
Is the driver processing some commands?
void SetChildPID (long pid)
Set child PID (debuggee's).
long GetChildPID () const
Get the child's (debuggee's) PID.
wxString GetDebuggersWorkingDirectory () const
void ShowFile (const wxString &file, int line)
Show a file/line without changing the cursor.
void QueueCommand (DebuggerCmd *dcmd, QueuePriority prio=Low)
add a command in the queue. The DebuggerCmd will be deleted automatically when finished.
DebuggerCmd * CurrentCommand ()
returns the currently executing command
void RunQueue ()
runs the next command in the queue, if it is idle
void RemoveTopCommand (bool deleteIt=true)
removes the top command (it has finished)
const StackFrameContainer & GetStackFrames () const
returns the container with the current backtrace
StackFrameContainer & GetStackFrames ()
returns the container with the current backtrace
const ThreadsContainer & GetThreads () const
returns the thread container with the current list of threads
ThreadsContainer & GetThreads ()
returns the thread container with the current list of threads
const Cursor & GetCursor () const
Get debugger's cursor.
void SetCursor (const Cursor &cursor)
Set debugger's cursor.
void ResetCurrentFrame ()
int GetCurrentFrame () const
int GetUserSelectedFrame () const
void SetCurrentFrame (int number, bool user_selected)
void NotifyDebuggeeContinued ()
void NotifyCursorChanged ()
Called by implementations to notify cursor changes.
Private Member Functions
void InitializeScripting ()
void RegisterType (const wxString &name, const wxString &regex, const wxString &eval_func, const wxString &parse_func)
void HandleMainBreakPoint (const wxRegEx &reBreak, wxString line)
void DetectCygwinMount (void)
void CorrectCygwinPath (wxString &path)
RemoteDebugging * GetRemoteDebuggingInfo ()
Private Attributes
bool m_CygwinPresent
wxString m_CygdrivePrefix
TypesArray m_Types
bool m_BreakOnEntry
bool m_ManualBreakOnEntry
bool m_IsStarted
bool m_needsUpdate
bool m_forceUpdate
long m_GDBVersionMajor
long m_GDBVersionMinor
wxString flavour
bool m_attachedToProcess
ProjectBuildTarget * m_pTarget
RemoteDebugging m_MergedRDInfo
int m_catchThrowIndex
Additional Inherited Members
Public Types inherited from DebuggerDriver
enum QueuePriority { Low = 0, High }
The priority used when adding a command in the queue.
typedef std::vector< cb::shared_ptr< cbStackFrame > > StackFrameContainer
typedef std::vector< cb::shared_ptr< cbThread > > ThreadsContainer
Protected Member Functions inherited from DebuggerDriver
void ResetCursor ()
Called by implementations to reset the cursor.
Protected Attributes inherited from DebuggerDriver
DebuggerGDB * m_pDBG
wxArrayString m_Dirs
wxString m_WorkingDir
wxString m_Args
bool m_ProgramIsStopped
wxString m_LastCursorAddress
Cursor m_Cursor
long m_ChildPID
DebuggerCommands m_DCmds
bool m_QueueBusy
StackFrameContainer m_backtrace
ThreadsContainer m_threads
int m_currentFrameNo
int m_userSelectedFrameNo
Detailed Description
Definition at line 36 of file gdb_driver.h.
Constructor & Destructor Documentation
GDB_driver()
GDB_driver::GDB_driver (DebuggerGDB * plugin)
Definition at line 89 of file gdb_driver.cpp.
References m_forceUpdate, and m_needsUpdate.
~GDB_driver()
GDB_driver::~GDB_driver () virtual
Definition at line 105 of file gdb_driver.cpp.
Member Function Documentation
AddBreakpoint()
void GDB_driver::AddBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp) virtual
Add a breakpoint.
Parameters
bp The breakpoint to add.
editor The editor this breakpoint is set (might be NULL).
Implements DebuggerDriver.
Definition at line 676 of file gdb_driver.cpp.
References _T, DebuggerBreakpoint::bptData, wxRegEx::GetMatch(), wxString::IsSameAs(), wxRegEx::Matches(), DebuggerDriver::NotifyCursorChanged(), and DebuggerDriver::QueueCommand().
AsmFlavour()
wxString GDB_driver::AsmFlavour () inline
Definition at line 93 of file gdb_driver.h.
References ScriptedType::eval_func, ScriptedType::name, reBreak, and ScriptedType::regex.
Attach()
void GDB_driver::Attach (int pid) virtual
Attach to process.
Implements DebuggerDriver.
Definition at line 764 of file gdb_driver.cpp.
References m_attachedToProcess, m_IsStarted, DebuggerDriver::QueueCommand(), and DebuggerDriver::SetChildPID().
Backtrace()
void GDB_driver::Backtrace () virtual
Implements DebuggerDriver.
Definition at line 585 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
Continue()
void GDB_driver::Continue () virtual
Implements DebuggerDriver.
Definition at line 528 of file gdb_driver.cpp.
References GetRemoteDebuggingInfo(), RemoteDebugging::IsOk(), m_attachedToProcess, m_IsStarted, m_ManualBreakOnEntry, DebuggerDriver::QueueCommand(), DebuggerDriver::ResetCursor(), and wxT.
Referenced by HandleMainBreakPoint().
CorrectCygwinPath()
void GDB_driver::CorrectCygwinPath (wxString & path) private
Definition at line 420 of file gdb_driver.cpp.
References _T, DetectCygwinMount(), wxString::EndsWith(), g_EscapeChar, wxString::GetChar(), wxString::Len(), m_CygdrivePrefix, wxString::Remove(), wxString::Replace(), wxString::StartsWith(), and wxEmptyString.
Referenced by ParseOutput().
CPURegisters()
void GDB_driver::CPURegisters () virtual
Implements DebuggerDriver.
Definition at line 598 of file gdb_driver.cpp.
References flavour, and DebuggerDriver::QueueCommand().
Detach()
void GDB_driver::Detach () virtual
Detach from running process.
Implements DebuggerDriver.
Definition at line 772 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
DetectCygwinMount()
void GDB_driver::DetectCygwinMount (void) private
Definition at line 364 of file gdb_driver.cpp.
References BUFSIZE, m_CygdrivePrefix, m_CygwinPresent, and NULL.
Referenced by CorrectCygwinPath(), and Prepare().
Disassemble()
void GDB_driver::Disassemble () virtual
Implements DebuggerDriver.
Definition at line 590 of file gdb_driver.cpp.
References flavour, and DebuggerDriver::QueueCommand().
EnableCatchingThrow()
void GDB_driver::EnableCatchingThrow (bool enable) virtual
Implements DebuggerDriver.
Definition at line 657 of file gdb_driver.cpp.
References wxString::Format(), m_catchThrowIndex, DebuggerDriver::QueueCommand(), and wxT.
EvaluateSymbol()
void GDB_driver::EvaluateSymbol (const wxString & symbol, const wxRect & tipRect) virtual
Evaluate a symbol.
Parameters
symbol The symbol to evaluate.
tipRect The rect to use for the tip window.
Implements DebuggerDriver.
Definition at line 715 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
GetCommandLine() [1/2]
wxString GDB_driver::GetCommandLine (const wxString & debugger, const wxString & debuggee, const wxString & userArguments) virtual
Get the command-line to launch the debugger.
Implements DebuggerDriver.
Definition at line 189 of file gdb_driver.cpp.
References _T, DebuggerConfiguration::DisableInit, DebuggerGDB::GetActiveConfigEx(), DebuggerConfiguration::GetFlag(), DebuggerDriver::m_pDBG, and wxT.
GetCommandLine() [2/2]
virtual wxString GDB_driver::GetCommandLine (const wxString & debugger, int pid, const wxString & userArguments) virtual
Get the command-line to launch the debugger.
Implements DebuggerDriver.
GetDisassemblyFlavour()
wxString GDB_driver::GetDisassemblyFlavour (void) virtual
Definition at line 476 of file gdb_driver.cpp.
References flavour.
GetRemoteDebuggingInfo()
RemoteDebugging * GDB_driver::GetRemoteDebuggingInfo () private
Definition at line 341 of file gdb_driver.cpp.
References DebuggerGDB::GetRemoteDebuggingMap(), m_MergedRDInfo, DebuggerDriver::m_pDBG, m_pTarget, and RemoteDebugging::MergeWith().
Referenced by Continue(), Prepare(), Start(), and UseDebugBreakProcess().
GetScriptedTypeCommand()
wxString GDB_driver::GetScriptedTypeCommand (const wxString & gdb_type, wxString & parse_func)
Definition at line 174 of file gdb_driver.cpp.
References _T, ScriptedType::eval_func, m_Types, wxRegEx::Matches(), ScriptedType::parse_func, and ScriptedType::regex.
HandleMainBreakPoint()
void GDB_driver::HandleMainBreakPoint (const wxRegEx & reBreak, wxString line) private
Definition at line 1172 of file gdb_driver.cpp.
References _(), Cursor::address, Cursor::changed, Continue(), Cursor::file, wxRegEx::GetMatch(), DebuggerDriver::High, Cursor::line, cbDebuggerPlugin::Log(), m_BreakOnEntry, DebuggerDriver::m_Cursor, m_ManualBreakOnEntry, m_needsUpdate, DebuggerDriver::m_pDBG, wxRegEx::Matches(), DebuggerDriver::QueueCommand(), and wxString::ToLong().
Referenced by ParseOutput().
InfoDLL()
void GDB_driver::InfoDLL () virtual
Implements DebuggerDriver.
Definition at line 634 of file gdb_driver.cpp.
References _(), _T, and DebuggerDriver::QueueCommand().
InfoFiles()
void GDB_driver::InfoFiles () virtual
Implements DebuggerDriver.
Definition at line 642 of file gdb_driver.cpp.
References _(), _T, and DebuggerDriver::QueueCommand().
InfoFPU()
void GDB_driver::InfoFPU () virtual
Implements DebuggerDriver.
Definition at line 647 of file gdb_driver.cpp.
References _(), _T, and DebuggerDriver::QueueCommand().
InfoFrame()
void GDB_driver::InfoFrame () virtual
Implements DebuggerDriver.
Definition at line 629 of file gdb_driver.cpp.
References _(), _T, and DebuggerDriver::QueueCommand().
InfoSignals()
void GDB_driver::InfoSignals () virtual
Implements DebuggerDriver.
Definition at line 652 of file gdb_driver.cpp.
References _(), _T, and DebuggerDriver::QueueCommand().
InitializeScripting()
void GDB_driver::InitializeScripting () private
Definition at line 110 of file gdb_driver.cpp.
References _(), _T, wxString::c_str(), cbC2U(), cbDebuggerPlugin::DebugLog(), ScriptingManager::DisplayErrors(), wxString::Format(), Manager::Get(), DebuggerGDB::GetActiveConfigEx(), DebuggerConfiguration::GetFlag(), Manager::GetMacrosManager(), Manager::GetScriptingManager(), wxString::IsEmpty(), ScriptingManager::LoadScript(), ConfigManager::LocateDataFile(), cbDebuggerPlugin::Log(), DebuggerDriver::m_pDBG, DebuggerDriver::QueueCommand(), RegisterType(), MacrosManager::ReplaceMacros(), sdScriptsGlobal, sdScriptsUser, and DebuggerConfiguration::WatchScriptPrinters.
Referenced by Prepare().
IsDebuggingStarted()
virtual bool GDB_driver::IsDebuggingStarted () const inline virtual
Is debugging started.
Implements DebuggerDriver.
Definition at line 86 of file gdb_driver.h.
References ScriptedType::parse_func.
MemoryDump()
void GDB_driver::MemoryDump () virtual
Implements DebuggerDriver.
Definition at line 618 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
ParseOutput()
void GDB_driver::ParseOutput (const wxString & output) virtual
Parse debugger's output.
Implements DebuggerDriver.
Definition at line 777 of file gdb_driver.cpp.
References _(), _T, GdbCmd_ChangeFrame::AddrChgMode(), Cursor::address, wxString::AfterFirst(), wxString::BeforeFirst(), cbDebuggerPlugin::BringCBToFront(), Cursor::changed, wxString::Clear(), wxString::clear(), CorrectCygwinPath(), DebuggerDriver::CurrentCommand(), cbDebuggerPlugin::DebugLog(), InfoWindow::Display(), wxString::empty(), Cursor::file, wxString::First(), wxString::Format(), Cursor::function, g_EscapeChar, GDB_PROMPT, Manager::Get(), GetArrayFromString(), DebuggerState::GetBreakpoint(), DebuggerState::GetBreakpointByNumber(), DebuggerManager::GetBreakpointDialog(), wxArrayString::GetCount(), Manager::GetDebuggerManager(), wxRegEx::GetMatch(), DebuggerGDB::GetState(), HandleMainBreakPoint(), DebuggerState::HasBreakpoint(), wxArrayString::Item(), wxString::Last(), wxString::Left(), Cursor::line, DebuggerDriver::Log(), cbDebuggerPlugin::Log(), DebuggerDriver::m_ChildPID, DebuggerDriver::m_Cursor, m_CygwinPresent, DebuggerDriver::m_DCmds, m_forceUpdate, m_GDBVersionMajor, m_GDBVersionMinor, m_IsStarted, m_needsUpdate, DebuggerDriver::m_pDBG, DebuggerDriver::m_ProgramIsStopped, DebuggerDriver::m_QueueBusy, wxRegEx::Matches(), DebuggerDriver::NotifyCursorChanged(), DebuggerCmd::ParseOutput(), DebuggerDriver::QueueCommand(), reBreak, reBreak2, reBreak3, reCatchThrow, reCatchThrowNoFile, reChildPid1, reChildPid2, reInferiorExited, reInferiorExitedWithCode, cbBreakpointsDlg::Reload(), wxString::Remove(), DebuggerState::RemoveBreakpoint(), wxString::RemoveLast(), DebuggerDriver::RemoveTopCommand(), rePendingFound, rePendingFound1, reTempBreakFound, reThreadSwitch, reThreadSwitch2, DebuggerDriver::RunQueue(), DebuggerDriver::SetChildPID(), wxString::StartsWith(), wxString::ToLong(), UnixFilename(), wxEmptyString, wxNOT_FOUND, and wxT.
Prepare()
void GDB_driver::Prepare (bool isConsole, int printElements) virtual
Prepares the debugging process by setting up search dirs etc.
Parameters
isConsole If true, the debuggee is a console executable.
Implements DebuggerDriver.
Definition at line 220 of file gdb_driver.cpp.
References _T, RemoteDebugging::additionalCmds, RemoteDebugging::additionalCmdsBefore, RemoteDebugging::additionalShellCmdsAfter, RemoteDebugging::additionalShellCmdsBefore, DebuggerConfiguration::CatchExceptions, RemoteDebugging::connType, DetectCygwinMount(), wxString::empty(), flavour, wxString::Format(), FULL_GDB_PROMPT, Manager::Get(), DebuggerGDB::GetActiveConfigEx(), GetArrayFromString(), wxArrayString::GetCount(), DebuggerConfiguration::GetDisassemblyFlavorCommand(), DebuggerConfiguration::GetFlag(), DebuggerConfiguration::GetInitCommands(), Manager::GetMacrosManager(), GetRemoteDebuggingInfo(), InitializeScripting(), wxString::IsEmpty(), RemoteDebugging::IsOk(), DebuggerDriver::m_Args, m_catchThrowIndex, DebuggerDriver::m_Dirs, DebuggerDriver::m_pDBG, m_Types, DebuggerDriver::QueueCommand(), MacrosManager::ReplaceMacros(), RemoteDebugging::Serial, RemoteDebugging::serialBaud, and wxT.
RegisterType()
void GDB_driver::RegisterType (const wxString & name, const wxString & regex, const wxString & eval_func, const wxString & parse_func) private
Definition at line 153 of file gdb_driver.cpp.
References _(), wxRegEx::Compile(), ScriptedType::eval_func, cbDebuggerPlugin::Log(), DebuggerDriver::m_pDBG, m_Types, ScriptedType::name, ScriptedType::parse_func, ScriptedType::regex, and ScriptedType::regex_str.
Referenced by InitializeScripting().
RemoveBreakpoint()
void GDB_driver::RemoveBreakpoint (cb::shared_ptr< DebuggerBreakpoint > bp) virtual
Remove a breakpoint.
Parameters
bp The breakpoint to remove. If NULL, all reakpoints are removed.
Implements DebuggerDriver.
Definition at line 709 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
RunningThreads()
void GDB_driver::RunningThreads () virtual
Implements DebuggerDriver.
Definition at line 623 of file gdb_driver.cpp.
References Manager::Get(), and DebuggerDriver::QueueCommand().
SetNextStatement()
void GDB_driver::SetNextStatement (const wxString & filename, int line) virtual
Implements DebuggerDriver.
Definition at line 578 of file gdb_driver.cpp.
References wxString::c_str(), wxString::Format(), DebuggerDriver::QueueCommand(), DebuggerDriver::ResetCursor(), and wxT.
SetTarget()
void GDB_driver::SetTarget (ProjectBuildTarget * target) virtual
Sets the target.
Implements DebuggerDriver.
Definition at line 214 of file gdb_driver.cpp.
References m_pTarget.
SetVarValue()
void GDB_driver::SetVarValue (const wxString & var, const wxString & value) virtual
Implements DebuggerDriver.
Definition at line 612 of file gdb_driver.cpp.
References _T, wxString::c_str(), CleanStringValue(), wxString::Format(), and DebuggerDriver::QueueCommand().
Start()
void GDB_driver::Start (bool breakOnEntry) virtual
Begin the debugging process by launching a program.
Implements DebuggerDriver.
Definition at line 483 of file gdb_driver.cpp.
References _T, cbDisassemblyDlg::Clear(), GdbCmd_DisassemblyInit::Clear(), DebuggerConfiguration::DoNotRun, Manager::Get(), DebuggerGDB::GetActiveConfigEx(), Manager::GetDebuggerManager(), DebuggerManager::GetDisassemblyDialog(), DebuggerConfiguration::GetFlag(), GetRemoteDebuggingInfo(), RemoteDebugging::IsOk(), m_attachedToProcess, m_BreakOnEntry, m_IsStarted, m_ManualBreakOnEntry, DebuggerDriver::m_pDBG, DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
Step()
void GDB_driver::Step () virtual
Implements DebuggerDriver.
Definition at line 548 of file gdb_driver.cpp.
References _T, DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
StepIn()
void GDB_driver::StepIn () virtual
Implements DebuggerDriver.
Definition at line 566 of file gdb_driver.cpp.
References _T, DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
StepInstruction()
void GDB_driver::StepInstruction () virtual
Implements DebuggerDriver.
Definition at line 554 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
StepIntoInstruction()
void GDB_driver::StepIntoInstruction () virtual
Implements DebuggerDriver.
Definition at line 560 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
StepOut()
void GDB_driver::StepOut () virtual
Implements DebuggerDriver.
Definition at line 572 of file gdb_driver.cpp.
References _T, DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
Stop()
void GDB_driver::Stop () virtual
Stop debugging.
Implements DebuggerDriver.
Definition at line 518 of file gdb_driver.cpp.
References _T, DebuggerGDB::IsAttachedToProcess(), m_attachedToProcess, m_IsStarted, DebuggerDriver::m_pDBG, DebuggerDriver::QueueCommand(), DebuggerDriver::ResetCursor(), and wxT.
SwitchThread()
void GDB_driver::SwitchThread (size_t threadIndex) virtual
Request to switch to another thread.
Implements DebuggerDriver.
Definition at line 668 of file gdb_driver.cpp.
References _T, wxString::Format(), Manager::Get(), DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
SwitchToFrame()
void GDB_driver::SwitchToFrame (size_t number) virtual
Implements DebuggerDriver.
Definition at line 606 of file gdb_driver.cpp.
References _T, DebuggerDriver::QueueCommand(), and DebuggerDriver::ResetCursor().
UpdateWatch()
void GDB_driver::UpdateWatch (const cb::shared_ptr< GDBWatch > & watch) virtual
Implements DebuggerDriver.
Definition at line 752 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
UpdateWatches()
void GDB_driver::UpdateWatches (cb::shared_ptr< GDBWatch > localsWatch, cb::shared_ptr< GDBWatch > funcArgsWatch, WatchesContainer & watches) virtual
Update watches.
Parameters
doLocals Display values of local variables.
doArgs Display values of function arguments.
tree The watches tree control.
Implements DebuggerDriver.
Definition at line 720 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
UpdateWatchLocalsArgs()
void GDB_driver::UpdateWatchLocalsArgs (cb::shared_ptr< GDBWatch > const & watch, bool locals) virtual
Implements DebuggerDriver.
Definition at line 758 of file gdb_driver.cpp.
References DebuggerDriver::QueueCommand().
UseDebugBreakProcess()
bool GDB_driver::UseDebugBreakProcess () virtual
Ask the driver if the debugger should be interrupted with DebugBreakProcess or Ctrl+C event.
Implements DebuggerDriver.
Definition at line 468 of file gdb_driver.cpp.
References GetRemoteDebuggingInfo(), and RemoteDebugging::IsOk().
Member Data Documentation
flavour
wxString GDB_driver::flavour private
Definition at line 130 of file gdb_driver.h.
Referenced by CPURegisters(), Disassemble(), GetDisassemblyFlavour(), and Prepare().
m_attachedToProcess
bool GDB_driver::m_attachedToProcess private
Definition at line 132 of file gdb_driver.h.
Referenced by Attach(), Continue(), Start(), and Stop().
m_BreakOnEntry
bool GDB_driver::m_BreakOnEntry private
Definition at line 114 of file gdb_driver.h.
Referenced by HandleMainBreakPoint(), and Start().
m_catchThrowIndex
int GDB_driver::m_catchThrowIndex private
Definition at line 140 of file gdb_driver.h.
Referenced by EnableCatchingThrow(), and Prepare().
m_CygdrivePrefix
wxString GDB_driver::m_CygdrivePrefix private
Definition at line 108 of file gdb_driver.h.
Referenced by CorrectCygwinPath(), and DetectCygwinMount().
m_CygwinPresent
bool GDB_driver::m_CygwinPresent private
Definition at line 107 of file gdb_driver.h.
Referenced by DetectCygwinMount(), and ParseOutput().
m_forceUpdate
bool GDB_driver::m_forceUpdate private
Definition at line 125 of file gdb_driver.h.
Referenced by GDB_driver(), and ParseOutput().
m_GDBVersionMajor
long GDB_driver::m_GDBVersionMajor private
Definition at line 128 of file gdb_driver.h.
Referenced by ParseOutput().
m_GDBVersionMinor
long GDB_driver::m_GDBVersionMinor private
Definition at line 129 of file gdb_driver.h.
Referenced by ParseOutput().
m_IsStarted
bool GDB_driver::m_IsStarted private
Definition at line 121 of file gdb_driver.h.
Referenced by Attach(), Continue(), ParseOutput(), Start(), and Stop().
m_ManualBreakOnEntry
bool GDB_driver::m_ManualBreakOnEntry private
Definition at line 118 of file gdb_driver.h.
Referenced by Continue(), HandleMainBreakPoint(), and Start().
m_MergedRDInfo
RemoteDebugging GDB_driver::m_MergedRDInfo private
Definition at line 138 of file gdb_driver.h.
Referenced by GetRemoteDebuggingInfo().
m_needsUpdate
bool GDB_driver::m_needsUpdate private
Definition at line 124 of file gdb_driver.h.
Referenced by GDB_driver(), HandleMainBreakPoint(), and ParseOutput().
m_pTarget
ProjectBuildTarget* GDB_driver::m_pTarget private
Definition at line 135 of file gdb_driver.h.
Referenced by GetRemoteDebuggingInfo(), and SetTarget().
m_Types
TypesArray GDB_driver::m_Types private
Definition at line 110 of file gdb_driver.h.
Referenced by GetScriptedTypeCommand(), Prepare(), and RegisterType().
The documentation for this class was generated from the following files:
gdb_driver.h
gdb_driver.cpp