Code::Blocks: IPC Class Reference
IPC Class Reference
#include <ipc.h>
Public Member Functions
IPC ()
virtual ExitCode Entry ()
bool Server () const
void Shutdown ()
void Send (const wxString &value)
Public Member Functions inherited from wxThread
wxThread (wxThreadKind kind=wxTHREAD_DETACHED)
virtual ~wxThread ()
wxThreadError Create (unsigned int stackSize=0)
wxThreadError Delete (ExitCode *rc=NULL, wxThreadWait waitMode=wxTHREAD_WAIT_BLOCK)
wxThreadIdType GetId () const
wxThreadKind GetKind () const
unsigned int GetPriority () const
bool IsAlive () const
bool IsDetached () const
bool IsPaused () const
bool IsRunning () const
wxThreadError Kill ()
wxThreadError Pause ()
wxThreadError Resume ()
wxThreadError Run ()
void SetPriority (unsigned int priority)
virtual bool TestDestroy ()
ExitCode Wait (wxThreadWait flags=wxTHREAD_WAIT_BLOCK)
Private Attributes
volatile bool is_shutdown
SharedMemory shm
Additional Inherited Members
Public Types inherited from wxThread
typedef void * ExitCode
Static Public Member Functions inherited from wxThread
static int GetCPUCount ()
static wxThreadIdType GetCurrentId ()
static wxThreadIdType GetMainId ()
static bool IsMain ()
static bool SetConcurrency (size_t level)
static void Sleep (unsigned long milliseconds)
static wxThread * This ()
static void Yield ()
Protected Member Functions inherited from wxThread
void Exit (ExitCode exitcode=0)
Detailed Description
Definition at line 95 of file ipc.h.
Constructor & Destructor Documentation
IPC()
IPC::IPC () inline
Definition at line 101 of file ipc.h.
Member Function Documentation
Entry()
wxThread::ExitCode IPC::Entry () virtual
Implements wxThread.
Definition at line 51 of file ipc.cpp.
References _T, SharedMemory::BasePointer(), Manager::Get(), Manager::GetAppFrame(), is_shutdown, SharedMemory::Lock(), MainFrame::OnDropFiles(), SharedMemory::reader, shm, SharedMemory::Unlock(), wxStringTokenize(), and wxTOKEN_STRTOK.
Send()
void IPC::Send (const wxString & value)
Definition at line 17 of file ipc.cpp.
References _T, SharedMemory::BasePointer(), wxString::c_str(), cbThrow, wxString::length(), SharedMemory::Lock(), shm, SharedMemory::Size(), SharedMemory::Unlock(), and SharedMemory::writer.
Server()
bool IPC::Server () const inline
Definition at line 105 of file ipc.h.
References SharedMemory::Server().
Shutdown()
void IPC::Shutdown ()
Definition at line 41 of file ipc.cpp.
References is_shutdown, shm, SharedMemory::Unlock(), and SharedMemory::writer.
Member Data Documentation
is_shutdown
volatile bool IPC::is_shutdown private
Definition at line 97 of file ipc.h.
Referenced by Entry(), and Shutdown().
shm
SharedMemory IPC::shm private
Definition at line 98 of file ipc.h.
Referenced by Entry(), Send(), and Shutdown().
The documentation for this class was generated from the following files:
ipc.h
ipc.cpp