Code::Blocks: cbDebuggerPlugin Class Reference
cbDebuggerPlugin Class Reference abstract
Base class for debugger plugins.
#include <cbplugin.h>
Classes
struct WatchesDisabledMenuItems
Public Types
enum DebugWindows {
Backtrace, CPURegisters, Disassembly, ExamineMemory,
Threads, Watches
}
enum SyncEditorResult { SyncOk = 0, SyncFileNotFound, SyncFileUnknown }
Public Member Functions
cbDebuggerPlugin (const wxString &guiName, const wxString &settingsName)
virtual void OnAttach ()
Any descendent plugin should override this virtual method and perform any necessary initialization.
virtual void OnRelease (bool appShutDown)
virtual void BuildMenu (wxMenuBar *menuBar)
virtual void BuildModuleMenu (const ModuleType type, wxMenu *menu, const FileTreeData *data=nullptr)
virtual bool BuildToolBar (wxToolBar *toolBar)
virtual void EditorLinesAddedOrRemoved (cbEditor *editor, int startline, int lines)
Notify the debugger that lines were added or removed in an editor.
virtual void OnAttachReal ()=0
virtual void OnReleaseReal (bool appShutDown)=0
virtual void SetupToolsMenu (wxMenu &menu)=0
virtual bool ToolMenuEnabled () const
virtual bool SupportsFeature (cbDebuggerFeature::Flags flag)=0
virtual cbDebuggerConfiguration * LoadConfig (const ConfigManagerWrapper &config)=0
cbDebuggerConfiguration & GetActiveConfig ()
void SetActiveConfig (int index)
int GetIndexOfActiveConfig () const
virtual void OnConfigurationChange (bool isActive)
Called when the user clicks OK in Settings -> Debugger...
virtual bool Debug (bool breakOnEntry)=0
Start a new debugging process.
virtual void Continue ()=0
Continue running the debugged program.
virtual bool RunToCursor (const wxString &filename, int line, const wxString &line_text)=0
Run the debugged program until it reaches the cursor at the current editor.
virtual void SetNextStatement (const wxString &filename, int line)=0
Sets the position of the Program counter to the specified filename:line.
virtual void Next ()=0
Execute the next instruction and return control to the debugger.
virtual void NextInstruction ()=0
Execute the next instruction and return control to the debugger.
virtual void StepIntoInstruction ()=0
Execute the next instruction and return control to the debugger, if the instruction is a function call step into it.
virtual void Step ()=0
Execute the next instruction, stepping into function calls if needed, and return control to the debugger.
virtual void StepOut ()=0
Execute the next instruction, stepping out of function calls if needed, and return control to the debugger.
virtual void Break ()=0
Break the debugging process (stop the debuggee for debugging).
virtual void Stop ()=0
Stop the debugging process (exit debugging).
virtual bool IsRunning () const =0
Is the plugin currently debugging?
virtual bool IsStopped () const =0
Is the plugin stopped on breakpoint?
virtual bool IsBusy () const =0
Is the plugin processing something?
virtual int GetExitCode () const =0
Get the exit code of the last debug process.
virtual int GetStackFrameCount () const =0
virtual cb::shared_ptr< const cbStackFrame > GetStackFrame (int index) const =0
virtual void SwitchToFrame (int number)=0
virtual int GetActiveStackFrame () const =0
virtual cb::shared_ptr< cbBreakpoint > AddBreakpoint (const wxString &filename, int line)=0
Request to add a breakpoint.
virtual cb::shared_ptr< cbBreakpoint > AddDataBreakpoint (const wxString &dataExpression)=0
Request to add a breakpoint based on a data expression.
virtual int GetBreakpointsCount () const =0
virtual cb::shared_ptr< cbBreakpoint > GetBreakpoint (int index)=0
virtual cb::shared_ptr< const cbBreakpoint > GetBreakpoint (int index) const =0
virtual void UpdateBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint)=0
virtual void DeleteBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint)=0
virtual void DeleteAllBreakpoints ()=0
virtual void ShiftBreakpoint (int index, int lines_to_shift)=0
virtual void EnableBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint, bool enable)=0
virtual int GetThreadsCount () const =0
virtual cb::shared_ptr< const cbThread > GetThread (int index) const =0
virtual bool SwitchToThread (int thread_number)=0
virtual cb::shared_ptr< cbWatch > AddWatch (const wxString &symbol)=0
virtual void DeleteWatch (cb::shared_ptr< cbWatch > watch)=0
virtual bool HasWatch (cb::shared_ptr< cbWatch > watch)=0
virtual void ShowWatchProperties (cb::shared_ptr< cbWatch > watch)=0
virtual bool SetWatchValue (cb::shared_ptr< cbWatch > watch, const wxString &value)=0
virtual void ExpandWatch (cb::shared_ptr< cbWatch > watch)=0
virtual void CollapseWatch (cb::shared_ptr< cbWatch > watch)=0
virtual void UpdateWatch (cb::shared_ptr< cbWatch > watch)=0
virtual void OnWatchesContextMenu (wxMenu &menu, const cbWatch &watch, wxObject *property, int &disabledMenus)
virtual void SendCommand (const wxString &cmd, bool debugLog)=0
virtual void AttachToProcess (const wxString &pid)=0
virtual void DetachFromProcess ()=0
virtual bool IsAttachedToProcess () const =0
virtual void GetCurrentPosition (wxString &filename, int &line)=0
virtual void OnValueTooltip (const wxString &token, const wxRect &evalRect)
virtual bool ShowValueTooltip (int style)
virtual void RequestUpdate (DebugWindows window)=0
virtual wxString GetEditorWordAtCaret (const wxPoint *mousePosition=NULL)
void ClearActiveMarkFromAllEditors ()
SyncEditorResult SyncEditor (const wxString &filename, int line, bool setMarker=true)
void BringCBToFront ()
bool DragInProgress () const
void ShowLog (bool clear)
void Log (const wxString &msg, Logger::level level=Logger::info)
void DebugLog (const wxString &msg, Logger::level level=Logger::info)
bool HasDebugLog () const
void ClearLog ()
void SetupLog (int normalIndex)
wxString GetGUIName () const
wxString GetSettingsName () const
Public Member Functions inherited from cbPlugin
cbPlugin ()
In default cbPlugin's constructor the associated PluginInfo structure is filled with default values.
virtual ~cbPlugin ()
cbPlugin destructor.
virtual PluginType GetType () const
The plugin must return its type on request.
virtual int GetConfigurationPriority () const
Return the plugin's configuration priority.
virtual int GetConfigurationGroup () const
Return the configuration group for this plugin.
virtual cbConfigurationPanel * GetConfigurationPanel (cb_optional wxWindow *parent)
Return plugin's configuration panel.
virtual cbConfigurationPanel * GetProjectConfigurationPanel (cb_optional wxWindow *parent, cb_optional cbProject *project)
Return plugin's configuration panel for projects.
virtual void BuildMenu (cb_optional wxMenuBar *menuBar)
This method is called by Code::Blocks and is used by the plugin to add any menu items it needs on Code::Blocks's menu bar.
virtual void BuildModuleMenu (cb_optional const ModuleType type, cb_optional wxMenu *menu, cb_optional const FileTreeData *data=nullptr)
This method is called by Code::Blocks core modules (EditorManager, ProjectManager etc) and is used by the plugin to add any menu items it needs in the module's popup menu.
virtual bool BuildToolBar (cb_optional wxToolBar *toolBar)
This method is called by Code::Blocks and is used by the plugin to add any toolbar items it needs on Code::Blocks's toolbar.
virtual int GetToolBarPriority ()
This method return the priority of the plugin's toolbar, the less value indicates a more preceding position when C::B starts with no configuration file.
virtual void CreateStatusField (cbStatusBar *statusBar)
This method is called by Code::Blocks and is used by the plugin to add a field on Code::Blocks's statusbar.
bool IsAttached () const
See whether this plugin is attached or not.
virtual bool CanDetach () const
See whether this plugin can be detached (unloaded) or not.
Protected Types
enum StartType { StartTypeUnknown = 0, StartTypeRun, StartTypeStepInto }
Protected Member Functions
virtual void ConvertDirectory (wxString &str, wxString base=_T(""), bool relative=true)=0
virtual cbProject * GetProject ()=0
virtual void ResetProject ()=0
virtual void CleanupWhenProjectClosed (cbProject *project)=0
virtual bool CompilerFinished (bool compilerFailed, StartType startType)
Called when the compilation has finished.
void SwitchToDebuggingLayout ()
void SwitchToPreviousLayout ()
bool GetDebuggee (wxString &pathToDebuggee, wxString &workingDirectory, ProjectBuildTarget *target)
bool EnsureBuildUpToDate (StartType startType)
bool WaitingCompilerToFinish () const
int RunNixConsole (wxString &consoleTty)
void MarkAsStopped ()
Protected Member Functions inherited from cbPlugin
virtual void OnRelease (cb_optional bool appShutDown)
Any descendent plugin should override this virtual method and perform any necessary de-initialization.
virtual void NotImplemented (const wxString &log) const
This method logs a "Not implemented" message and is provided for convenience only.
Private Member Functions
void RegisterValueTooltip ()
void ProcessValueTooltip (CodeBlocksEvent &event)
void CancelValueTooltip (CodeBlocksEvent &event)
void OnEditorOpened (CodeBlocksEvent &event)
void OnProjectActivated (CodeBlocksEvent &event)
void OnProjectClosed (CodeBlocksEvent &event)
void OnCompilerFinished (CodeBlocksEvent &event)
void OnEditorHook (cbEditor *editor, wxScintillaEvent &event)
Private Attributes
wxString m_PreviousLayout
cbCompilerPlugin * m_pCompiler
bool m_WaitingCompilerToFinish
int m_EditorHookId
StartType m_StartType
bool m_DragInProgress
int m_ActiveConfig
int m_LogPageIndex
bool m_lastLineWasNormal
wxString m_guiName
wxString m_settingsName
Additional Inherited Members
Protected Attributes inherited from cbPlugin
PluginType m_Type
Holds the plugin's type.
bool m_IsAttached
Holds the "attached" state.
Detailed Description
Base class for debugger plugins.
This plugin type must offer some pre-defined debug facilities, on top of the generic plugin's.
Definition at line 397 of file cbplugin.h.
Member Enumeration Documentation
DebugWindows
enum cbDebuggerPlugin::DebugWindows
Enumerator
Backtrace
CPURegisters
Disassembly
ExamineMemory
Threads
Watches
Definition at line 580 of file cbplugin.h.
StartType
enum cbDebuggerPlugin::StartType protected
Enumerator
StartTypeUnknown
StartTypeRun
StartTypeStepInto
Definition at line 560 of file cbplugin.h.
SyncEditorResult
enum cbDebuggerPlugin::SyncEditorResult
Enumerator
SyncOk
SyncFileNotFound
SyncFileUnknown
Definition at line 596 of file cbplugin.h.
Constructor & Destructor Documentation
cbDebuggerPlugin()
cbDebuggerPlugin::cbDebuggerPlugin (const wxString & guiName, const wxString & settingsName)
Definition at line 127 of file cbplugin.cpp.
References cbPlugin::m_Type, and ptDebugger.
Member Function Documentation
AddBreakpoint()
virtual cb::shared_ptr<cbBreakpoint> cbDebuggerPlugin::AddBreakpoint (const wxString & filename, int line) pure virtual
Request to add a breakpoint.
Parameters
file The file to add the breakpoint based on a file/line pair.
line The line number to put the breakpoint in file.
Returns
True if succeeded, false if not.
Implemented in DebuggerGDB.
Referenced by BreakpointsDlg::AddBreakpoint(), and BreakpointsDlg::OnBreakpointAdd().
AddDataBreakpoint()
virtual cb::shared_ptr<cbBreakpoint> cbDebuggerPlugin::AddDataBreakpoint (const wxString & dataExpression) pure virtual
Request to add a breakpoint based on a data expression.
Parameters
dataExpression The data expression to add the breakpoint.
Returns
True if succeeded, false if not.
Implemented in DebuggerGDB.
Referenced by WatchesDlg::OnMenuAddDataBreak().
AddWatch()
virtual cb::shared_ptr<cbWatch> cbDebuggerPlugin::AddWatch (const wxString & symbol) pure virtual
Implemented in DebuggerGDB.
Referenced by WatchesDropTarget::OnDropText(), and WatchesDlg::RenameWatch().
AttachToProcess()
virtual void cbDebuggerPlugin::AttachToProcess (const wxString & pid) pure virtual
Implemented in DebuggerGDB.
Break()
virtual void cbDebuggerPlugin::Break () pure virtual
Break the debugging process (stop the debuggee for debugging).
Implemented in DebuggerGDB.
BringCBToFront()
void cbDebuggerPlugin::BringCBToFront ()
Definition at line 930 of file cbplugin.cpp.
References Manager::Get(), and Manager::GetAppWindow().
Referenced by DebuggerGDB::OnCursorChanged(), CDB_driver::ParseOutput(), and GDB_driver::ParseOutput().
BuildMenu()
void cbDebuggerPlugin::BuildMenu (wxMenuBar * menuBar) virtual
Definition at line 176 of file cbplugin.cpp.
References Manager::Get(), Manager::GetDebuggerManager(), DebuggerManager::GetMenu(), and cbPlugin::IsAttached().
BuildModuleMenu()
void cbDebuggerPlugin::BuildModuleMenu (const ModuleType type, wxMenu * menu, const FileTreeData * data = nullptr) virtual
Definition at line 238 of file cbplugin.cpp.
References DebuggerManager::BuildContextMenu(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), GetEditorWordAtCaret(), cbPlugin::IsAttached(), IsRunning(), and mtEditorManager.
BuildToolBar()
bool cbDebuggerPlugin::BuildToolBar (wxToolBar * toolBar) virtual
Definition at line 259 of file cbplugin.cpp.
CancelValueTooltip()
void cbDebuggerPlugin::CancelValueTooltip (CodeBlocksEvent & event) private
Definition at line 995 of file cbplugin.cpp.
References Manager::Get(), Manager::GetDebuggerManager(), DebuggerManager::GetInterfaceFactory(), and cbDebugInterfaceFactory::HideValueTooltip().
Referenced by RegisterValueTooltip().
CleanupWhenProjectClosed()
virtual void cbDebuggerPlugin::CleanupWhenProjectClosed (cbProject * project) protected pure virtual
Implemented in DebuggerGDB.
Referenced by OnProjectClosed().
ClearActiveMarkFromAllEditors()
void cbDebuggerPlugin::ClearActiveMarkFromAllEditors ()
Definition at line 296 of file cbplugin.cpp.
References Manager::Get(), EditorManager::GetBuiltinEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), and cbEditor::SetDebugLine().
Referenced by DebuggerGDB::OnGDBTerminated(), and DebuggerGDB::RunCommand().
ClearLog()
void cbDebuggerPlugin::ClearLog ()
Definition at line 573 of file cbplugin.cpp.
References TextCtrlLogger::Clear(), Manager::Get(), Manager::GetDebuggerManager(), and DebuggerManager::GetLogger().
CollapseWatch()
virtual void cbDebuggerPlugin::CollapseWatch (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in DebuggerGDB.
Referenced by WatchesDlg::OnCollapse(), and ValueTooltip::OnCollapse().
CompilerFinished()
virtual bool cbDebuggerPlugin::CompilerFinished (bool compilerFailed, StartType startType) inline protected virtual
Called when the compilation has finished.
The compilation is started when EnsureBuildUpToDate is called.
Parameters
compilerFailed the compilation failed for some reason.
startType it is the same value given to the Debug method, when the debugger session was started.
Returns
True if debug session is start, false if there are any errors or the users canceled the session.
Reimplemented in DebuggerGDB.
Definition at line 577 of file cbplugin.h.
Referenced by OnCompilerFinished().
Continue()
virtual void cbDebuggerPlugin::Continue () pure virtual
Continue running the debugged program.
Implemented in DebuggerGDB.
ConvertDirectory()
virtual void cbDebuggerPlugin::ConvertDirectory (wxString & str, wxString base = _T(""), bool relative = true) protected pure virtual
Implemented in DebuggerGDB.
Referenced by GetDebuggee().
Debug()
virtual bool cbDebuggerPlugin::Debug (bool breakOnEntry) pure virtual
Start a new debugging process.
Implemented in DebuggerGDB.
DebugLog()
void cbDebuggerPlugin::DebugLog (const wxString & msg, Logger::level level = Logger::info)
Definition at line 557 of file cbplugin.cpp.
References Manager::Get(), Manager::GetLogManager(), HasDebugLog(), cbPlugin::IsAttached(), LogManager::Log(), m_lastLineWasNormal, m_LogPageIndex, and wxT.
Referenced by DebuggerDriver::DebugLog(), DebuggerGDB::DoBreak(), DebuggerGDB::DoDebug(), DebuggerGDB::DoSendCommand(), DebuggerGDB::EnableBreakpoint(), GDB_driver::InitializeScripting(), DebuggerGDB::LaunchProcess(), CDB_driver::ParseOutput(), GDB_driver::ParseOutput(), RunNixConsole(), and DebuggerGDB::Stop().
DeleteAllBreakpoints()
virtual void cbDebuggerPlugin::DeleteAllBreakpoints () pure virtual
Implemented in DebuggerGDB.
DeleteBreakpoint()
virtual void cbDebuggerPlugin::DeleteBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint) pure virtual
Implemented in DebuggerGDB.
Referenced by EditorLinesAddedOrRemoved(), and BreakpointsDlg::OnRemove().
DeleteWatch()
virtual void cbDebuggerPlugin::DeleteWatch (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in DebuggerGDB.
Referenced by ValueTooltip::ClearWatch(), WatchesDlg::DeleteProperty(), WatchesDlg::OnMenuDeleteAll(), and WatchesDlg::RenameWatch().
DetachFromProcess()
virtual void cbDebuggerPlugin::DetachFromProcess () pure virtual
Implemented in DebuggerGDB.
DragInProgress()
bool cbDebuggerPlugin::DragInProgress () const
Definition at line 526 of file cbplugin.cpp.
References m_DragInProgress.
EditorLinesAddedOrRemoved()
void cbDebuggerPlugin::EditorLinesAddedOrRemoved (cbEditor * editor, int startline, int lines) virtual
Notify the debugger that lines were added or removed in an editor.
This causes the debugger to keep the breakpoints list in-sync with the editors (i.e. what the user sees).
Parameters
editor The editor in question.
startline The starting line this change took place.
lines The number of lines added or removed. If it's a positive number, lines were added. If it's a negative number, lines were removed.
Definition at line 379 of file cbplugin.cpp.
References DeleteBreakpoint(), GetBreakpoint(), GetBreakpointsCount(), EditorBase::GetFilename(), and ShiftBreakpoint().
Referenced by cbEditor::OnEditorModified().
EnableBreakpoint()
virtual void cbDebuggerPlugin::EnableBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint, bool enable) pure virtual
Implemented in DebuggerGDB.
Referenced by BreakpointsDlg::OnEnable().
EnsureBuildUpToDate()
bool cbDebuggerPlugin::EnsureBuildUpToDate (StartType startType) protected
Definition at line 687 of file cbplugin.cpp.
References _(), cbDebuggerCommonConfig::AutoBuild, cbCompilerPlugin::Build(), cbMessageBox(), Manager::Get(), PluginManager::GetCompilerOffers(), cbDebuggerCommonConfig::GetFlag(), Manager::GetPluginManager(), IsAttachedToProcess(), cbCompilerPlugin::IsRunning(), Log(), m_pCompiler, m_StartType, m_WaitingCompilerToFinish, and wxICON_WARNING.
Referenced by DebuggerGDB::Debug().
ExpandWatch()
virtual void cbDebuggerPlugin::ExpandWatch (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in DebuggerGDB.
Referenced by WatchesDlg::OnExpand(), and ValueTooltip::OnExpand().
GetActiveConfig()
cbDebuggerConfiguration & cbDebuggerPlugin::GetActiveConfig ()
Definition at line 272 of file cbplugin.cpp.
References cbAssert, Manager::Get(), DebuggerManager::GetAllDebuggers(), Manager::GetDebuggerManager(), and m_ActiveConfig.
Referenced by DebuggerGDB::GetActiveConfigEx(), and SwitchToDebuggingLayout().
GetActiveStackFrame()
virtual int cbDebuggerPlugin::GetActiveStackFrame () const pure virtual
Implemented in DebuggerGDB.
Referenced by BacktraceDlg::Reload().
GetBreakpoint() [1/2]
virtual cb::shared_ptr<cbBreakpoint> cbDebuggerPlugin::GetBreakpoint (int index) pure virtual
Implemented in DebuggerGDB.
Referenced by EditorLinesAddedOrRemoved(), HasBreakpoint(), and cbEditor::RefreshBreakpointMarkers().
GetBreakpoint() [2/2]
virtual cb::shared_ptr<const cbBreakpoint> cbDebuggerPlugin::GetBreakpoint (int index) const pure virtual
Implemented in DebuggerGDB.
GetBreakpointsCount()
virtual int cbDebuggerPlugin::GetBreakpointsCount () const pure virtual
Implemented in DebuggerGDB.
Referenced by EditorLinesAddedOrRemoved(), HasBreakpoint(), and cbEditor::RefreshBreakpointMarkers().
GetCurrentPosition()
virtual void cbDebuggerPlugin::GetCurrentPosition (wxString & filename, int & line) pure virtual
Implemented in DebuggerGDB.
Referenced by OnEditorOpened().
GetDebuggee()
bool cbDebuggerPlugin::GetDebuggee (wxString & pathToDebuggee, wxString & workingDirectory, ProjectBuildTarget * target) protected
Definition at line 629 of file cbplugin.cpp.
References _(), cbMessageBox(), ConvertDirectory(), wxString::empty(), Logger::error, Manager::Get(), CompileTargetBase::GetBasePath(), wxFileName::GetFullPath(), CompileTargetBase::GetHostApplication(), Manager::GetMacrosManager(), CompileTargetBase::GetOutputFilename(), ProjectBuildTarget::GetParentProject(), CompileTargetBase::GetTargetType(), CompileTargetBase::GetWorkingDir(), wxString::IsEmpty(), wxFileName::IsRelative(), Log(), wxFileName::MakeAbsolute(), MacrosManager::ReplaceEnvVars(), ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttExecutable, ttNative, ttStaticLib, and UnixFilename().
Referenced by DebuggerGDB::DoDebug().
GetEditorWordAtCaret()
wxString cbDebuggerPlugin::GetEditorWordAtCaret (const wxPoint * mousePosition = NULL) virtual
Definition at line 183 of file cbplugin.cpp.
References wxString::find(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), wxScintilla::GetSelectedText(), wxScintilla::GetSelectionEnd(), wxScintilla::GetSelectionStart(), wxScintilla::GetTextRange(), wxString::length(), wxString::npos, wxScintilla::PositionFromPoint(), wxScintilla::PositionFromPointClose(), wxString::Remove(), wxString::Trim(), wxScintilla::WordEndPosition(), wxScintilla::WordStartPosition(), wxEmptyString, wxSCI_INVALID_POSITION, wxT, wxPoint::x, and wxPoint::y.
Referenced by BuildModuleMenu(), and ProcessValueTooltip().
GetExitCode()
virtual int cbDebuggerPlugin::GetExitCode () const pure virtual
Get the exit code of the last debug process.
Implemented in DebuggerGDB.
GetGUIName()
wxString cbDebuggerPlugin::GetGUIName () const inline
Definition at line 618 of file cbplugin.h.
Referenced by DebuggerSettingsDlg::CreateConfig(), DebuggerManager::RegisterDebugger(), and SwitchToDebuggingLayout().
GetIndexOfActiveConfig()
int cbDebuggerPlugin::GetIndexOfActiveConfig () const
Definition at line 291 of file cbplugin.cpp.
References m_ActiveConfig.
GetProject()
virtual cbProject* cbDebuggerPlugin::GetProject () protected pure virtual
Implemented in DebuggerGDB.
Referenced by OnProjectActivated(), and OnProjectClosed().
GetSettingsName()
wxString cbDebuggerPlugin::GetSettingsName () const inline
Definition at line 619 of file cbplugin.h.
Referenced by DebuggerManager::ProcessSettings(), and DebuggerManager::RegisterDebugger().
GetStackFrame()
virtual cb::shared_ptr<const cbStackFrame> cbDebuggerPlugin::GetStackFrame (int index) const pure virtual
Implemented in DebuggerGDB.
Referenced by BacktraceDlg::Reload().
GetStackFrameCount()
virtual int cbDebuggerPlugin::GetStackFrameCount () const pure virtual
Implemented in DebuggerGDB.
Referenced by BacktraceDlg::Reload().
GetThread()
virtual cb::shared_ptr<const cbThread> cbDebuggerPlugin::GetThread (int index) const pure virtual
Implemented in DebuggerGDB.
Referenced by ThreadsDlg::Reload().
GetThreadsCount()
virtual int cbDebuggerPlugin::GetThreadsCount () const pure virtual
Implemented in DebuggerGDB.
Referenced by ThreadsDlg::Reload().
HasDebugLog()
bool cbDebuggerPlugin::HasDebugLog () const
Definition at line 568 of file cbplugin.cpp.
References cbDebuggerCommonConfig::GetFlag(), and cbDebuggerCommonConfig::ShowDebuggersLog.
Referenced by DebugLog(), and DebuggerGDB::DoSendCommand().
HasWatch()
virtual bool cbDebuggerPlugin::HasWatch (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in DebuggerGDB.
IsAttachedToProcess()
virtual bool cbDebuggerPlugin::IsAttachedToProcess () const pure virtual
Implemented in DebuggerGDB.
Referenced by EnsureBuildUpToDate(), DebuggerToolbarHandler::OnStop(), DebuggerToolbarHandler::OnUpdateUI(), and ToolMenuEnabled().
IsBusy()
virtual bool cbDebuggerPlugin::IsBusy () const pure virtual
Is the plugin processing something?
Implemented in DebuggerGDB.
IsRunning()
virtual bool cbDebuggerPlugin::IsRunning () const pure virtual
Is the plugin currently debugging?
Implemented in DebuggerGDB.
Referenced by BuildModuleMenu(), DisassemblyDlg::Clear(), BacktraceDlg::IsSwitchFrameEnabled(), OnEditorOpened(), OnProjectActivated(), OnProjectClosed(), DebuggerToolbarHandler::OnUpdateUI(), DebugLogPanel::OnUpdateUI(), CompilerGCC::StopRunningDebugger(), and ToolMenuEnabled().
IsStopped()
virtual bool cbDebuggerPlugin::IsStopped () const pure virtual
Is the plugin stopped on breakpoint?
Implemented in DebuggerGDB.
Referenced by BacktraceDlg::IsSwitchFrameEnabled(), DebuggerToolbarHandler::OnStop(), DebuggerToolbarHandler::OnUpdateUI(), and DebugLogPanel::OnUpdateUI().
LoadConfig()
virtual cbDebuggerConfiguration* cbDebuggerPlugin::LoadConfig (const ConfigManagerWrapper & config) pure virtual
Implemented in DebuggerGDB.
Referenced by DebuggerSettingsDlg::CreateConfig(), and DebuggerManager::ProcessSettings().
Log()
void cbDebuggerPlugin::Log (const wxString & msg, Logger::level level = Logger::info)
Definition at line 547 of file cbplugin.cpp.
References Manager::Get(), Manager::GetLogManager(), cbPlugin::IsAttached(), LogManager::Log(), m_lastLineWasNormal, m_LogPageIndex, wxEmptyString, and wxT.
Referenced by DebuggerGDB::AddSourceDir(), DebuggerState::ApplyBreakpoints(), DebuggerGDB::DoBreak(), DebuggerGDB::DoDebug(), EnsureBuildUpToDate(), GetDebuggee(), GDB_driver::HandleMainBreakPoint(), GDB_driver::InitializeScripting(), DebuggerGDB::LaunchProcess(), DebuggerDriver::Log(), DebuggerGDB::OnCursorChanged(), DebuggerGDB::OnGDBTerminated(), GDB_driver::ParseOutput(), GDB_driver::RegisterType(), DebuggerGDB::RunCommand(), RunNixConsole(), DebuggerGDB::SendCommand(), and SyncEditor().
MarkAsStopped()
void cbDebuggerPlugin::MarkAsStopped () protected
Definition at line 925 of file cbplugin.cpp.
References Manager::Get(), Manager::GetProjectManager(), and ProjectManager::SetIsRunning().
Referenced by DebuggerGDB::OnGDBTerminated(), and DebuggerGDB::RunCommand().
Next()
virtual void cbDebuggerPlugin::Next () pure virtual
Execute the next instruction and return control to the debugger.
Implemented in DebuggerGDB.
NextInstruction()
virtual void cbDebuggerPlugin::NextInstruction () pure virtual
Execute the next instruction and return control to the debugger.
Implemented in DebuggerGDB.
OnAttach()
void cbDebuggerPlugin::OnAttach () virtual
Any descendent plugin should override this virtual method and perform any necessary initialization.
This method is called by Code::Blocks (PluginManager actually) when the plugin has been loaded and should attach in Code::Blocks. When Code::Blocks starts up, it finds and loads all plugins but does not activate (attaches) them. It then activates all plugins that the user has selected to be activated on start-up.
This means that a plugin might be loaded but not activated...
Think of this method as the actual constructor...
Reimplemented from cbPlugin.
Definition at line 143 of file cbplugin.cpp.
References cbEVT_COMPILER_FINISHED, cbEVT_EDITOR_OPEN, cbEVT_PROJECT_ACTIVATE, cbEVT_PROJECT_CLOSE, Manager::Get(), Manager::GetDebuggerManager(), m_EditorHookId, m_StartType, OnAttachReal(), OnCompilerFinished(), OnEditorHook(), OnEditorOpened(), OnProjectActivated(), OnProjectClosed(), DebuggerManager::RegisterDebugger(), Manager::RegisterEventSink(), EditorHooks::RegisterHook(), RegisterValueTooltip(), StartTypeUnknown, SupportsFeature(), and cbDebuggerFeature::ValueTooltips.
OnAttachReal()
virtual void cbDebuggerPlugin::OnAttachReal () pure virtual
Implemented in DebuggerGDB.
Referenced by OnAttach().
OnCompilerFinished()
void cbDebuggerPlugin::OnCompilerFinished (CodeBlocksEvent & event) private
Definition at line 730 of file cbplugin.cpp.
References _(), wxString::AfterFirst(), wxString::BeforeFirst(), CompilerFinished(), wxString::Contains(), wxString::Format(), Manager::Get(), wxArrayString::GetCount(), cbCompilerPlugin::GetExitCode(), ProjectManager::GetIsRunning(), Manager::GetProjectManager(), wxArrayString::Item(), m_pCompiler, m_StartType, m_WaitingCompilerToFinish, AnnoyingDialog::rtNO, AnnoyingDialog::rtYES, ProjectManager::SetIsRunning(), ShowLog(), AnnoyingDialog::ShowModal(), wxString::ToLong(), wxString::Trim(), wxART_QUESTION, wxEmptyString, wxEXEC_SYNC, wxExecute(), wxGetProcessId(), wxT, and AnnoyingDialog::YES_NO.
Referenced by OnAttach().
OnConfigurationChange()
virtual void cbDebuggerPlugin::OnConfigurationChange (bool isActive) inline virtual
Called when the user clicks OK in Settings -> Debugger...
Reimplemented in DebuggerGDB.
Definition at line 435 of file cbplugin.h.
References UpdateWatch().
OnEditorHook()
void cbDebuggerPlugin::OnEditorHook (cbEditor * editor, wxScintillaEvent & event) private
Definition at line 518 of file cbplugin.cpp.
References m_DragInProgress.
Referenced by OnAttach().
OnEditorOpened()
void cbDebuggerPlugin::OnEditorOpened (CodeBlocksEvent & event) private
Definition at line 432 of file cbplugin.cpp.
References GetCurrentPosition(), EditorBase::GetFilename(), wxFileName::GetFullPath(), EditorBase::IsBuiltinEditor(), IsRunning(), wxString::IsSameAs(), wxFileName::Normalize(), cbEditor::RefreshBreakpointMarkers(), and cbEditor::SetDebugLine().
Referenced by OnAttach().
OnProjectActivated()
void cbDebuggerPlugin::OnProjectActivated (CodeBlocksEvent & event) private
Definition at line 462 of file cbplugin.cpp.
References _(), cbMessageBox(), Manager::Get(), CodeBlocksEvent::GetProject(), GetProject(), Manager::GetProjectManager(), IsRunning(), ProjectManager::SetProject(), Stop(), wxICON_WARNING, wxID_YES, and wxYES_NO.
Referenced by OnAttach().
OnProjectClosed()
void cbDebuggerPlugin::OnProjectClosed (CodeBlocksEvent & event) private
Definition at line 491 of file cbplugin.cpp.
References _(), CleanupWhenProjectClosed(), Manager::Get(), CodeBlocksEvent::GetProject(), GetProject(), IsRunning(), AnnoyingDialog::OK, ResetProject(), AnnoyingDialog::ShowModal(), Stop(), and wxART_WARNING.
Referenced by OnAttach().
OnRelease()
void cbDebuggerPlugin::OnRelease (bool appShutDown) virtual
Definition at line 166 of file cbplugin.cpp.
References Manager::Get(), Manager::GetDebuggerManager(), m_EditorHookId, OnReleaseReal(), Manager::RemoveAllEventSinksFor(), DebuggerManager::UnregisterDebugger(), and EditorHooks::UnregisterHook().
OnReleaseReal()
virtual void cbDebuggerPlugin::OnReleaseReal (bool appShutDown) pure virtual
Implemented in DebuggerGDB.
Referenced by OnRelease().
OnValueTooltip()
void cbDebuggerPlugin::OnValueTooltip (const wxString & token, const wxRect & evalRect) virtual
Reimplemented in DebuggerGDB.
Definition at line 951 of file cbplugin.cpp.
Referenced by ProcessValueTooltip().
OnWatchesContextMenu()
virtual void cbDebuggerPlugin::OnWatchesContextMenu (wxMenu & menu, const cbWatch & watch, wxObject * property, int & disabledMenus) inline virtual
Parameters
[out] disabledMenus A combination of WatchesDisabledMenuItems, which controls which of the default menu items are disabled
Reimplemented in DebuggerGDB.
Definition at line 540 of file cbplugin.h.
Referenced by WatchesDlg::OnPropertyRightClick().
ProcessValueTooltip()
void cbDebuggerPlugin::ProcessValueTooltip (CodeBlocksEvent & event) private
Definition at line 955 of file cbplugin.cpp.
References wxScintilla::CallTipActive(), cbStyledTextCtrl::CallTipCancel(), wxString::empty(), Manager::Get(), cbEditor::GetControl(), GetEditorWordAtCaret(), cbDebuggerCommonConfig::GetFlag(), EditorBase::IsBuiltinEditor(), EditorBase::IsContextMenuOpened(), OnValueTooltip(), cbDebuggerCommonConfig::RequireCtrlForTooltips, ShowValueTooltip(), wxGetKeyState(), WXK_CONTROL, wxPoint::x, and wxPoint::y.
Referenced by RegisterValueTooltip().
RegisterValueTooltip()
void cbDebuggerPlugin::RegisterValueTooltip () private
Definition at line 937 of file cbplugin.cpp.
References CancelValueTooltip(), cbEVT_EDITOR_TOOLTIP, cbEVT_EDITOR_TOOLTIP_CANCEL, Manager::Get(), ProcessValueTooltip(), and Manager::RegisterEventSink().
Referenced by OnAttach().
RequestUpdate()
virtual void cbDebuggerPlugin::RequestUpdate (DebugWindows window) pure virtual
Implemented in DebuggerGDB.
Referenced by DebuggerMenuHandler::DebuggerMenuHandler(), ExamineMemoryDlg::OnGo(), DisassemblyDlg::OnMixedModeCB(), and DisassemblyDlg::OnRefresh().
ResetProject()
virtual void cbDebuggerPlugin::ResetProject () protected pure virtual
Implemented in DebuggerGDB.
Referenced by OnProjectClosed().
RunNixConsole()
int cbDebuggerPlugin::RunNixConsole (wxString & consoleTty) protected
Definition at line 848 of file cbplugin.cpp.
References _(), _T, DebugLog(), DEFAULT_CONSOLE_TERM, Logger::error, F(), Manager::Get(), Manager::GetConfigManager(), Manager::GetMacrosManager(), Log(), ConfigManager::Read(), wxString::Replace(), MacrosManager::ReplaceEnvVars(), wxString::wx_str(), wxEmptyString, wxEXEC_ASYNC, wxExecute(), wxKill(), wxMilliSleep(), wxT, and Manager::Yield().
Referenced by DebuggerGDB::DoDebug().
RunToCursor()
virtual bool cbDebuggerPlugin::RunToCursor (const wxString & filename, int line, const wxString & line_text) pure virtual
Run the debugged program until it reaches the cursor at the current editor.
Implemented in DebuggerGDB.
SendCommand()
virtual void cbDebuggerPlugin::SendCommand (const wxString & cmd, bool debugLog) pure virtual
Implemented in DebuggerGDB.
Referenced by DebugLogPanel::OnEntryCommand(), and DebugLogPanel::OnLoadFile().
SetActiveConfig()
void cbDebuggerPlugin::SetActiveConfig (int index)
Definition at line 286 of file cbplugin.cpp.
References m_ActiveConfig.
Referenced by DebuggerManager::FindTargetsDebugger(), DebuggerManager::RegisterDebugger(), and DebuggerManager::SetActiveDebugger().
SetNextStatement()
virtual void cbDebuggerPlugin::SetNextStatement (const wxString & filename, int line) pure virtual
Sets the position of the Program counter to the specified filename:line.
Implemented in DebuggerGDB.
SetupLog()
void cbDebuggerPlugin::SetupLog (int normalIndex)
Definition at line 578 of file cbplugin.cpp.
References m_LogPageIndex.
Referenced by DebuggerSettingsDlg::OnOK(), and DebuggerManager::RegisterDebugger().
SetupToolsMenu()
virtual void cbDebuggerPlugin::SetupToolsMenu (wxMenu & menu) pure virtual
Implemented in DebuggerGDB.
Referenced by DebuggerToolbarHandler::OnToolInfo().
SetWatchValue()
virtual bool cbDebuggerPlugin::SetWatchValue (cb::shared_ptr< cbWatch > watch, const wxString & value) pure virtual
Implemented in DebuggerGDB.
Referenced by SetValue().
ShiftBreakpoint()
virtual void cbDebuggerPlugin::ShiftBreakpoint (int index, int lines_to_shift) pure virtual
Implemented in DebuggerGDB.
Referenced by EditorLinesAddedOrRemoved().
ShowLog()
void cbDebuggerPlugin::ShowLog (bool clear)
Definition at line 531 of file cbplugin.cpp.
References cbEVT_SHOW_LOG_MANAGER, cbEVT_SWITCH_TO_LOG_WINDOW, TextCtrlLogger::Clear(), Manager::Get(), Manager::GetDebuggerManager(), DebuggerManager::GetLogger(), and Manager::ProcessEvent().
Referenced by OnCompilerFinished(), SwitchToDebuggingLayout(), and SyncEditor().
ShowValueTooltip()
bool cbDebuggerPlugin::ShowValueTooltip (int style) virtual
Reimplemented in DebuggerGDB.
Definition at line 945 of file cbplugin.cpp.
Referenced by ProcessValueTooltip().
ShowWatchProperties()
virtual void cbDebuggerPlugin::ShowWatchProperties (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in DebuggerGDB.
Referenced by WatchesDlg::OnMenuProperties().
Step()
virtual void cbDebuggerPlugin::Step () pure virtual
Execute the next instruction, stepping into function calls if needed, and return control to the debugger.
Implemented in DebuggerGDB.
StepIntoInstruction()
virtual void cbDebuggerPlugin::StepIntoInstruction () pure virtual
Execute the next instruction and return control to the debugger, if the instruction is a function call step into it.
Implemented in DebuggerGDB.
StepOut()
virtual void cbDebuggerPlugin::StepOut () pure virtual
Execute the next instruction, stepping out of function calls if needed, and return control to the debugger.
Implemented in DebuggerGDB.
Stop()
virtual void cbDebuggerPlugin::Stop () pure virtual
Stop the debugging process (exit debugging).
Implemented in DebuggerGDB.
Referenced by OnProjectActivated(), OnProjectClosed(), and CompilerGCC::StopRunningDebugger().
SupportsFeature()
virtual bool cbDebuggerPlugin::SupportsFeature (cbDebuggerFeature::Flags flag) pure virtual
Implemented in DebuggerGDB.
Referenced by DebuggerMenuHandler::BuildContextMenu(), OnAttach(), cbEditor::OnBeforeBuildContextMenu(), WatchesDropTarget::OnDropText(), WatchesDlg::OnKeyDown(), WatchesDlg::OnPropertyRightClick(), WatchesDlg::OnPropertySelected(), WatchesDlg::RefreshUI(), DebuggerManager::RefreshUI(), and cbEditor::ToggleBreakpoint().
SwitchToDebuggingLayout()
void cbDebuggerPlugin::SwitchToDebuggingLayout () protected
Definition at line 583 of file cbplugin.cpp.
References _(), cbEVT_QUERY_VIEW_LAYOUT, cbEVT_SWITCH_VIEW_LAYOUT, LogManager::DebugLog(), F(), Manager::Get(), GetActiveConfig(), GetGUIName(), Manager::GetLogManager(), cbDebuggerConfiguration::GetName(), cbDebuggerCommonConfig::GetPerspective(), CodeBlocksLayoutEvent::layout, m_PreviousLayout, cbDebuggerCommonConfig::OnePerDebugger, cbDebuggerCommonConfig::OnePerDebuggerConfig, cbDebuggerCommonConfig::OnlyOne, Manager::ProcessEvent(), ShowLog(), wxString::wx_str(), and wxT.
Referenced by DebuggerGDB::DoDebug().
SwitchToFrame()
virtual void cbDebuggerPlugin::SwitchToFrame (int number) pure virtual
Implemented in DebuggerGDB.
Referenced by BacktraceDlg::OnSwitchFrame().
SwitchToPreviousLayout()
void cbDebuggerPlugin::SwitchToPreviousLayout () protected
Definition at line 617 of file cbplugin.cpp.
References _(), cbEVT_SWITCH_VIEW_LAYOUT, LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), wxString::IsEmpty(), CodeBlocksLayoutEvent::layout, m_PreviousLayout, Manager::ProcessEvent(), and wxString::wx_str().
Referenced by DebuggerGDB::OnGDBTerminated().
SwitchToThread()
virtual bool cbDebuggerPlugin::SwitchToThread (int thread_number) pure virtual
Implemented in DebuggerGDB.
Referenced by ThreadsDlg::OnSwitchThread().
SyncEditor()
cbDebuggerPlugin::SyncEditorResult cbDebuggerPlugin::SyncEditor (const wxString & filename, int line, bool setMarker = true)
Definition at line 307 of file cbplugin.cpp.
References _(), InfoWindow::Display(), Logger::error, FileTypeOf(), ftHeader, ftOther, ftResource, ftSource, ftTemplateSource, Manager::Get(), ProjectManager::GetActiveProject(), CompileTargetBase::GetBasePath(), EditorManager::GetBuiltinEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), cbProject::GetFileByFilename(), wxFileName::GetLongPath(), cbEditor::GetProjectFile(), Manager::GetProjectManager(), cbEditor::GotoLine(), wxFileName::IsRelative(), Log(), wxFileName::MakeAbsolute(), EditorManager::Open(), cbEditor::SetDebugLine(), cbEditor::SetProjectFile(), ShowLog(), SyncFileNotFound, SyncFileUnknown, SyncOk, and UnixFilename().
Referenced by DebuggerGDB::OnCursorChanged(), BacktraceDlg::OnJump(), and DebuggerGDB::OnShowFile().
ToolMenuEnabled()
bool cbDebuggerPlugin::ToolMenuEnabled () const virtual
Definition at line 264 of file cbplugin.cpp.
References Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetCurrentlyCompilingTarget(), Manager::GetProjectManager(), IsAttachedToProcess(), and IsRunning().
Referenced by DebuggerToolbarHandler::OnUpdateUI().
UpdateBreakpoint()
virtual void cbDebuggerPlugin::UpdateBreakpoint (cb::shared_ptr< cbBreakpoint > breakpoint) pure virtual
Implemented in DebuggerGDB.
Referenced by BreakpointsDlg::BreakpointProperties().
UpdateWatch()
virtual void cbDebuggerPlugin::UpdateWatch (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in DebuggerGDB.
Referenced by WatchesDlg::OnMenuUpdate().
WaitingCompilerToFinish()
bool cbDebuggerPlugin::WaitingCompilerToFinish () const inline protected
Definition at line 627 of file cbplugin.h.
Referenced by DebuggerGDB::Debug().
Member Data Documentation
m_ActiveConfig
int cbDebuggerPlugin::m_ActiveConfig private
Definition at line 647 of file cbplugin.h.
Referenced by GetActiveConfig(), GetIndexOfActiveConfig(), and SetActiveConfig().
m_DragInProgress
bool cbDebuggerPlugin::m_DragInProgress private
Definition at line 645 of file cbplugin.h.
Referenced by DragInProgress(), and OnEditorHook().
m_EditorHookId
int cbDebuggerPlugin::m_EditorHookId private
Definition at line 643 of file cbplugin.h.
Referenced by OnAttach(), and OnRelease().
m_guiName
wxString cbDebuggerPlugin::m_guiName private
Definition at line 651 of file cbplugin.h.
m_lastLineWasNormal
bool cbDebuggerPlugin::m_lastLineWasNormal private
Definition at line 650 of file cbplugin.h.
Referenced by DebugLog(), and Log().
m_LogPageIndex
int cbDebuggerPlugin::m_LogPageIndex private
Definition at line 649 of file cbplugin.h.
Referenced by DebugLog(), Log(), and SetupLog().
m_pCompiler
cbCompilerPlugin* cbDebuggerPlugin::m_pCompiler private
Definition at line 640 of file cbplugin.h.
Referenced by EnsureBuildUpToDate(), and OnCompilerFinished().
m_PreviousLayout
wxString cbDebuggerPlugin::m_PreviousLayout private
Definition at line 639 of file cbplugin.h.
Referenced by SwitchToDebuggingLayout(), and SwitchToPreviousLayout().
m_settingsName
wxString cbDebuggerPlugin::m_settingsName private
Definition at line 651 of file cbplugin.h.
m_StartType
StartType cbDebuggerPlugin::m_StartType private
Definition at line 644 of file cbplugin.h.
Referenced by EnsureBuildUpToDate(), OnAttach(), and OnCompilerFinished().
m_WaitingCompilerToFinish
bool cbDebuggerPlugin::m_WaitingCompilerToFinish private
Definition at line 641 of file cbplugin.h.
Referenced by EnsureBuildUpToDate(), and OnCompilerFinished().
The documentation for this class was generated from the following files:
cbplugin.h
cbplugin.cpp