Code::Blocks: EditArrayStringDlg Class Reference
EditArrayStringDlg Class Reference
#include <editarraystringdlg.h>
Public Member Functions
EditArrayStringDlg (wxWindow *parent, wxArrayString &array)
virtual ~EditArrayStringDlg ()
EditArrayStringDlg & operator= (const EditArrayStringDlg &)
virtual void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Protected Member Functions
void OnAdd (wxCommandEvent &event)
void OnEdit (wxCommandEvent &event)
void OnDelete (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Protected Attributes
wxArrayString & m_Array
Detailed Description
Definition at line 13 of file editarraystringdlg.h.
Constructor & Destructor Documentation
EditArrayStringDlg()
EditArrayStringDlg::EditArrayStringDlg (wxWindow * parent, wxArrayString & array)
Definition at line 31 of file editarraystringdlg.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadObject().
~EditArrayStringDlg()
EditArrayStringDlg::~EditArrayStringDlg () virtual
Definition at line 46 of file editarraystringdlg.cpp.
Member Function Documentation
EndModal()
void EditArrayStringDlg::EndModal (int retCode) virtual
Definition at line 51 of file editarraystringdlg.cpp.
References wxArrayString::Add(), wxArrayString::Clear(), ScriptBindings::EndModal(), m_Array, and wxID_OK.
OnAdd()
void EditArrayStringDlg::OnAdd (wxCommandEvent & event) protected
Definition at line 67 of file editarraystringdlg.cpp.
References _(), cbGetTextFromUser(), and wxString::IsEmpty().
OnDelete()
void EditArrayStringDlg::OnDelete (wxCommandEvent & event) protected
Definition at line 84 of file editarraystringdlg.cpp.
References _(), cbMessageBox(), wxID_YES, and wxYES_NO.
OnEdit()
void EditArrayStringDlg::OnEdit (wxCommandEvent & event) protected
Definition at line 74 of file editarraystringdlg.cpp.
References _(), cbGetTextFromUser(), and wxString::IsEmpty().
OnUpdateUI()
void EditArrayStringDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 93 of file editarraystringdlg.cpp.
operator=()
EditArrayStringDlg& EditArrayStringDlg::operator= (const EditArrayStringDlg &) inline
Definition at line 18 of file editarraystringdlg.h.
References ScriptBindings::EndModal().
Member Data Documentation
m_Array
wxArrayString& EditArrayStringDlg::m_Array protected
Definition at line 25 of file editarraystringdlg.h.
Referenced by EndModal().
The documentation for this class was generated from the following files:
editarraystringdlg.h
editarraystringdlg.cpp