Code::Blocks: CompilerOptionsDlg Class Reference
CompilerOptionsDlg Class Reference
#include <compileroptionsdlg.h>
Classes
struct CustomVarAction
Public Member Functions
CompilerOptionsDlg (wxWindow *parent, CompilerGCC *compiler, cbProject *project=0L, ProjectBuildTarget *target=0L)
~CompilerOptionsDlg ()
virtual wxString GetTitle () const
virtual wxString GetBitmapBaseName () const
virtual void OnApply ()
Called when the user chooses to apply the configuration.
virtual void OnCancel ()
Called when the user chooses to cancel the configuration.
Public Member Functions inherited from cbConfigurationPanel
cbConfigurationPanel ()
virtual ~cbConfigurationPanel ()
void SetParentDialog (wxWindow *dialog)
Sets the panel's parent dialog.
wxWindow * SetParentDialog ()
Gets the panel's parent dialog.
int cbMessageBox (const wxString &message, const wxString &caption=wxEmptyString, int style=wxOK, wxWindow *parent=NULL, int x=-1, int y=-1)
Call global cbMessageBox with m_parentDialog as parent window when no parent window specified.
Private Types
enum CustomVarActionType { CVA_Add, CVA_Edit, CVA_Remove }
Private Member Functions
void TextToOptions ()
void OptionsToText ()
void DoFillCompilerSets (int compilerIdx)
void DoFillCompilerPrograms ()
void DoFillVars ()
void DoFillOthers ()
void DoFillOptions ()
void DoFillCompilerDependentSettings ()
void DoSaveCompilerDependentSettings ()
void DoFillTree ()
void DoSaveOptions ()
void DoLoadOptions ()
void DoSaveCompilerPrograms ()
void DoSaveVars ()
void DoSaveCompilerDefinition ()
void CompilerChanged ()
void UpdateCompilerForTargets (int compilerIdx)
void AutoDetectCompiler ()
wxListBox * GetDirsListBox ()
CompileOptionsBase * GetVarsOwner ()
void ProjectTargetCompilerAdjust ()
checks if compiler changed for project/target and takes actions accordingly
void OnRealApply ()
void OnTreeSelectionChange (wxTreeEvent &event)
void OnTreeSelectionChanging (wxTreeEvent &event)
void OnCompilerChanged (wxCommandEvent &event)
void OnCategoryChanged (wxCommandEvent &event)
void OnOptionChanged (wxPropertyGridEvent &event)
void OnAddDirClick (wxCommandEvent &event)
void OnEditDirClick (wxCommandEvent &event)
void OnRemoveDirClick (wxCommandEvent &event)
void OnClearDirClick (wxCommandEvent &event)
void OnCopyDirsClick (wxCommandEvent &event)
void OnAddVarClick (wxCommandEvent &event)
void OnEditVarClick (wxCommandEvent &event)
void OnRemoveVarClick (wxCommandEvent &event)
void OnClearVarClick (wxCommandEvent &event)
void OnSetDefaultCompilerClick (wxCommandEvent &event)
void OnAddCompilerClick (wxCommandEvent &event)
void OnEditCompilerClick (wxCommandEvent &event)
void OnRemoveCompilerClick (wxCommandEvent &event)
void OnResetCompilerClick (wxCommandEvent &event)
void OnAddLibClick (wxCommandEvent &event)
void OnEditLibClick (wxCommandEvent &event)
void OnRemoveLibClick (wxCommandEvent &event)
void OnClearLibClick (wxCommandEvent &event)
void OnCopyLibsClick (wxCommandEvent &event)
void OnMoveLibUpClick (wxCommandEvent &event)
void OnMoveLibDownClick (wxCommandEvent &event)
void OnMoveDirUpClick (wxCommandEvent &event)
void OnMoveDirDownClick (wxCommandEvent &event)
void OnMasterPathClick (wxCommandEvent &event)
void OnAutoDetectClick (wxCommandEvent &event)
void OnSelectProgramClick (wxCommandEvent &event)
void OnAdvancedClick (wxCommandEvent &event)
void OnAddExtraPathClick (wxCommandEvent &event)
void OnEditExtraPathClick (wxCommandEvent &event)
void OnRemoveExtraPathClick (wxCommandEvent &event)
void OnClearExtraPathClick (wxCommandEvent &event)
void OnIgnoreAddClick (wxCommandEvent &event)
void OnIgnoreRemoveClick (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void OnDirty (wxCommandEvent &event)
void OnMyCharHook (wxKeyEvent &event)
void OnFlagsPopup (wxPropertyGridEvent &event)
void OnFlagsPopupClick (wxCommandEvent &event)
void OnOptionDoubleClick (wxPropertyGridEvent &event)
Private Attributes
wxPropertyGrid * m_FlagsPG
CompilerGCC * m_Compiler
CompilerOptions m_Options
wxArrayString m_LinkerOptions
wxArrayString m_LinkLibs
wxArrayString m_CompilerOptions
wxArrayString m_ResourceCompilerOptions
int m_CurrentCompilerIdx
cbProject * m_pProject
ProjectBuildTarget * m_pTarget
bool m_bDirty
true if a setting has changed since last save
bool m_bFlagsDirty
true if a flag (not its value) has changed since last save
std::vector< CustomVarAction > m_CustomVarActions
the actions carried out on the custom vars that need to be saved/applied
wxString m_NewProjectOrTargetCompilerId
keeps track of the changes of compiler of the selected project/target
bool m_BuildingTree
flag to ignore tree changing events while building it
Static Private Attributes
static int m_MenuOption = -1
Detailed Description
Definition at line 28 of file compileroptionsdlg.h.
Class Documentation
CompilerOptionsDlg::CustomVarAction
struct CompilerOptionsDlg::CustomVarAction
Definition at line 46 of file compileroptionsdlg.h.
Class Members
CustomVarActionType m_Action
wxString m_Key
wxString m_KeyValue
Member Enumeration Documentation
CustomVarActionType
enum CompilerOptionsDlg::CustomVarActionType private
Enumerator
CVA_Add
CVA_Edit
CVA_Remove
Definition at line 39 of file compileroptionsdlg.h.
Constructor & Destructor Documentation
CompilerOptionsDlg()
CompilerOptionsDlg::CompilerOptionsDlg (wxWindow * parent, CompilerGCC * compiler, cbProject * project = 0L, ProjectBuildTarget * target = 0L)
Definition at line 224 of file compileroptionsdlg.cpp.
References _(), _T, wxXmlResource::AttachUnknownControl(), wxBookCtrlBase::DeletePage(), DoFillCompilerDependentSettings(), DoFillCompilerSets(), DoFillOthers(), DoFillTree(), wxXmlResource::Get(), CompileOptionsBase::GetBuildScripts(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetCompilerIndex(), wxArrayString::GetCount(), CompilerFactory::GetDefaultCompilerID(), Compiler::GetOptions(), CompileTargetBase::GetTargetType(), cbProject::IsMakefileCustom(), wxXmlResource::LoadPanel(), m_CurrentCompilerIdx, m_FlagsPG, m_Options, m_pProject, m_pTarget, OnCompilerChanged(), wxString::Printf(), wxSizer::RecalcSizes(), wxBookCtrlBase::RemovePage(), CompilerFactory::SelectCompilerUI(), wxPropertyGrid::SetColumnProportion(), wxNotebook::SetSelection(), CompileOptionsBase::SupportsCurrentPlatform(), ttCommandsOnly, wxString::wx_str(), wxDefaultPosition, wxDefaultSize, wxPG_EX_HELP_AS_TOOLTIPS, wxPG_SPLITTER_AUTO_CENTER, wxT, and wxTAB_TRAVERSAL.
~CompilerOptionsDlg()
CompilerOptionsDlg::~CompilerOptionsDlg ()
Definition at line 392 of file compileroptionsdlg.cpp.
Member Function Documentation
AutoDetectCompiler()
void CompilerOptionsDlg::AutoDetectCompiler () private
Definition at line 1669 of file compileroptionsdlg.cpp.
References _(), adrDetected, adrGuessed, ArrayString2ListBox(), Compiler::AutoDetectInstallationDir(), cbConfigurationPanel::cbMessageBox(), ParserConsts::empty, CompilerFactory::GetCompiler(), Compiler::GetExtraPaths(), Compiler::GetMasterPath(), Compiler::GetName(), m_bDirty, m_CurrentCompilerIdx, wxString::Printf(), Compiler::SetExtraPaths(), Compiler::SetMasterPath(), wxString::wx_str(), wxICON_QUESTION, wxID_NO, and wxYES_NO.
Referenced by OnAutoDetectClick(), and OnResetCompilerClick().
CompilerChanged()
void CompilerOptionsDlg::CompilerChanged () private
Definition at line 1633 of file compileroptionsdlg.cpp.
References DoFillCompilerDependentSettings(), CompilerFactory::GetCompiler(), Compiler::GetID(), Compiler::GetOptions(), m_CurrentCompilerIdx, m_NewProjectOrTargetCompilerId, m_Options, and m_pProject.
Referenced by OnAddCompilerClick(), and OnCompilerChanged().
DoFillCompilerDependentSettings()
void CompilerOptionsDlg::DoFillCompilerDependentSettings () private
Definition at line 421 of file compileroptionsdlg.cpp.
References DoFillCompilerPrograms(), DoFillVars(), DoLoadOptions(), m_bDirty, and m_bFlagsDirty.
Referenced by CompilerChanged(), CompilerOptionsDlg(), OnAddCompilerClick(), OnRemoveCompilerClick(), OnResetCompilerClick(), and OnTreeSelectionChange().
DoFillCompilerPrograms()
void CompilerOptionsDlg::DoFillCompilerPrograms () private
Definition at line 467 of file compileroptionsdlg.cpp.
References _(), ArrayString2ListBox(), CompilerPrograms::C, CompilerPrograms::CPP, CompilerPrograms::DBGconfig, Manager::Get(), DebuggerManager::GetAllDebuggers(), CompilerFactory::GetCompiler(), DebuggerManager::PluginData::GetConfigurations(), Manager::GetDebuggerManager(), Compiler::GetExtraPaths(), Compiler::GetMasterPath(), Compiler::GetPrograms(), CompilerPrograms::LD, CompilerPrograms::LIB, m_CurrentCompilerIdx, m_pProject, CompilerPrograms::MAKE, wxChoice::SetSelection(), CompilerPrograms::WINDRES, and wxT.
Referenced by DoFillCompilerDependentSettings().
DoFillCompilerSets()
void CompilerOptionsDlg::DoFillCompilerSets (int compilerIdx) private
Definition at line 397 of file compileroptionsdlg.cpp.
References CompilerFactory::GetCompiler(), CompilerFactory::GetCompilersCount(), and wxChoice::SetSelection().
Referenced by CompilerOptionsDlg().
DoFillOptions()
void CompilerOptionsDlg::DoFillOptions () private
Definition at line 637 of file compileroptionsdlg.cpp.
References wxPropertyGrid::Append(), wxPropertyGrid::AppendIn(), CompOption::category, wxPropertyGrid::Clear(), wxPGProperty::GetChildCount(), CompilerOptions::GetCount(), CompilerOptions::GetOption(), wxPropertyGrid::GetRoot(), wxPGProperty::Item(), m_FlagsPG, m_Options, wxPropertyGrid::SetPropertyAttribute(), wxPropertyGrid::Sort(), wxPropertyGrid::SortChildren(), wxCHECK_VERSION, wxPG_BOOL_USE_CHECKBOX, and wxT.
Referenced by DoLoadOptions(), OnCategoryChanged(), and OnFlagsPopup().
DoFillOthers()
void CompilerOptionsDlg::DoFillOthers () private
Definition at line 535 of file compileroptionsdlg.cpp.
References _T, ArrayString2ListBox(), Manager::Get(), Manager::GetConfigManager(), m_pProject, ConfigManager::ReadArrayString(), wxSpinCtrl::SetRange(), wxCheckBox::SetValue(), and wxSpinCtrl::SetValue().
Referenced by CompilerOptionsDlg().
DoFillTree()
void CompilerOptionsDlg::DoFillTree () private
Definition at line 596 of file compileroptionsdlg.cpp.
References _(), wxTreeCtrl::AddRoot(), wxTreeCtrl::AppendItem(), wxTreeCtrl::DeleteAllItems(), wxTreeCtrl::Expand(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompileTargetBase::GetTitle(), m_BuildingTree, m_pProject, m_pTarget, and wxTreeCtrl::SelectItem().
Referenced by CompilerOptionsDlg().
DoFillVars()
void CompilerOptionsDlg::DoFillVars () private
Definition at line 514 of file compileroptionsdlg.cpp.
References _T, CompileOptionsBase::GetAllVars(), and GetVarsOwner().
Referenced by DoFillCompilerDependentSettings().
DoLoadOptions()
void CompilerOptionsDlg::DoLoadOptions () private
Definition at line 816 of file compileroptionsdlg.cpp.
References _(), ArrayString2ListBox(), ArrayString2TextCtrl(), DoFillOptions(), CompileOptionsBase::GetAlwaysRunPostBuildSteps(), CompileOptionsBase::GetCommandsAfterBuild(), CompileOptionsBase::GetCommandsBeforeBuild(), CompilerFactory::GetCompiler(), CompileOptionsBase::GetCompilerOptions(), CompileOptionsBase::GetIncludeDirs(), CompileOptionsBase::GetLibDirs(), CompileOptionsBase::GetLinkerOptions(), CompileOptionsBase::GetLinkLibs(), CompileTargetBase::GetMakeCommandFor(), CompileTargetBase::GetOptionRelation(), CompileOptionsBase::GetResourceCompilerOptions(), CompileOptionsBase::GetResourceIncludeDirs(), Compiler::GetSwitches(), CompileTargetBase::GetTitle(), CompilerSwitches::logging, m_CompilerOptions, m_CurrentCompilerIdx, m_LinkerOptions, m_LinkLibs, m_pProject, m_pTarget, m_ResourceCompilerOptions, mcAskRebuildNeeded, mcBuild, mcClean, mcCompileFile, mcDistClean, mcSilentBuild, ortCompilerOptions, ortIncludeDirs, ortLibDirs, ortLinkerOptions, ortResDirs, wxChoice::SetSelection(), and TextToOptions().
Referenced by DoFillCompilerDependentSettings().
DoSaveCompilerDefinition()
void CompilerOptionsDlg::DoSaveCompilerDefinition () private
Definition at line 1163 of file compileroptionsdlg.cpp.
References wxXmlNode::AddAttribute(), wxXmlNode::AddChild(), CompOption::additionalLibs, CompilerPrograms::C, CompOption::category, CompOption::checkAgainst, CompOption::checkMessage, clogFull, clogNone, clogSimple, cltError, cltInfo, cltNormal, cltWarning, CompilerPrograms::CPP, ctCompileObjectCmd, ctCompileResourceCmd, ctCount, ctGenDependenciesCmd, ctLinkConsoleExeCmd, ctLinkDynamicCmd, ctLinkExeCmd, ctLinkNativeCmd, ctLinkStaticCmd, CompilerPrograms::DBGconfig, DEFAULT_ARRAY_SEP, CompilerSwitches::defaultLogging, CompilerSwitches::defines, wxString::EndsWith(), CompOption::exclusive, CompilerSwitches::forceCompilerUseQuotes, CompilerSwitches::forceFwdSlashes, CompilerSwitches::forceLinkerUseQuotes, wxString::Format(), CompilerSwitches::genericSwitch, Compiler::GetCommandToolsVector(), CompilerFactory::GetCompiler(), Compiler::GetCOnlyFlags(), CompilerOptions::GetCount(), Compiler::GetCPPOnlyFlags(), ConfigManager::GetFolder(), Compiler::GetID(), wxXmlNode::GetNext(), CompilerOptions::GetOption(), Compiler::GetPrograms(), Compiler::GetRegExArray(), GetStringFromArray(), Compiler::GetSwitches(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, wxString::IsEmpty(), CompilerPrograms::LD, CompilerPrograms::LIB, CompilerSwitches::libDirs, CompilerSwitches::libDirSeparator, CompilerSwitches::libExtension, CompilerSwitches::libPrefix, CompilerSwitches::linkerNeedsLibExtension, CompilerSwitches::linkerNeedsLibPrefix, CompilerSwitches::linkerNeedsPathResolved, CompilerSwitches::linkLibs, CompilerSwitches::logging, ParserConsts::lt, m_CurrentCompilerIdx, m_Options, CompilerPrograms::MAKE, CompOption::name, CompilerSwitches::needDependencies, CompilerSwitches::objectExtension, CompilerSwitches::objectSeparator, CompOption::option, CompilerSwitches::PCHExtension, wxString::Replace(), wxXmlDocument::Save(), sdDataUser, wxXmlNode::SetNext(), Compiler::SetOptions(), wxXmlDocument::SetRoot(), wxXmlDocument::SetVersion(), CompilerSwitches::statusSuccess, CompOption::supersedes, CompilerSwitches::supportsPCH, wxString::Trim(), CompilerSwitches::Use83Paths, CompilerSwitches::UseFlatObjects, CompilerSwitches::UseFullSourcePaths, CompilerPrograms::WINDRES, wxDirExists(), wxEmptyString, wxMkdir(), wxT, wxXML_CDATA_SECTION_NODE, and wxXML_ELEMENT_NODE.
Referenced by DoSaveCompilerDependentSettings().
DoSaveCompilerDependentSettings()
void CompilerOptionsDlg::DoSaveCompilerDependentSettings () private
Definition at line 432 of file compileroptionsdlg.cpp.
References DoSaveCompilerDefinition(), DoSaveCompilerPrograms(), DoSaveOptions(), DoSaveVars(), m_bDirty, m_bFlagsDirty, and ProjectTargetCompilerAdjust().
Referenced by OnAddCompilerClick(), OnApply(), OnCompilerChanged(), and OnTreeSelectionChanging().
DoSaveCompilerPrograms()
void CompilerOptionsDlg::DoSaveCompilerPrograms () private
Definition at line 1092 of file compileroptionsdlg.cpp.
References CompilerPrograms::C, CompilerPrograms::CPP, CompilerPrograms::DBGconfig, CompilerFactory::GetCompiler(), wxChoice::GetSelection(), CompilerPrograms::LD, CompilerPrograms::LIB, ListBox2ArrayString(), m_CurrentCompilerIdx, m_pProject, CompilerPrograms::MAKE, Compiler::SetExtraPaths(), Compiler::SetMasterPath(), Compiler::SetPrograms(), DebuggerClientData::string, and CompilerPrograms::WINDRES.
Referenced by DoSaveCompilerDependentSettings().
DoSaveOptions()
void CompilerOptionsDlg::DoSaveOptions () private
Definition at line 992 of file compileroptionsdlg.cpp.
References _T, DoGetCompileOptions(), CompilerFactory::GetCompiler(), wxChoice::GetSelection(), Compiler::GetSwitches(), ListBox2ArrayString(), CompilerSwitches::logging, m_CompilerOptions, m_CurrentCompilerIdx, m_LinkerOptions, m_LinkLibs, m_pProject, m_pTarget, m_ResourceCompilerOptions, mcAskRebuildNeeded, mcBuild, mcClean, mcCompileFile, mcDistClean, mcSilentBuild, OptionsToText(), ortCompilerOptions, ortIncludeDirs, ortLibDirs, ortLinkerOptions, ortResDirs, CompileOptionsBase::SetAlwaysRunPostBuildSteps(), CompileOptionsBase::SetCommandsAfterBuild(), CompileOptionsBase::SetCommandsBeforeBuild(), CompileOptionsBase::SetCompilerOptions(), CompileOptionsBase::SetIncludeDirs(), CompileOptionsBase::SetLibDirs(), CompileOptionsBase::SetLinkerOptions(), CompileOptionsBase::SetLinkLibs(), CompileTargetBase::SetMakeCommandFor(), CompileTargetBase::SetOptionRelation(), CompileOptionsBase::SetResourceCompilerOptions(), CompileOptionsBase::SetResourceIncludeDirs(), and Compiler::SetSwitches().
Referenced by DoSaveCompilerDependentSettings().
DoSaveVars()
void CompilerOptionsDlg::DoSaveVars () private
Definition at line 1126 of file compileroptionsdlg.cpp.
References _T, wxString::AfterFirst(), wxString::BeforeFirst(), CVA_Add, CVA_Edit, CVA_Remove, GetVarsOwner(), CompilerOptionsDlg::CustomVarAction::m_Action, m_CustomVarActions, CompilerOptionsDlg::CustomVarAction::m_Key, CompilerOptionsDlg::CustomVarAction::m_KeyValue, CompileOptionsBase::SetVar(), wxString::Trim(), and CompileOptionsBase::UnsetVar().
Referenced by DoSaveCompilerDependentSettings().
GetBitmapBaseName()
virtual wxString CompilerOptionsDlg::GetBitmapBaseName () const inline virtual
Returns
the panel's bitmap base name. You must supply two bitmaps: <basename>.png and <basename>-off.png...
Implements cbConfigurationPanel.
Definition at line 35 of file compileroptionsdlg.h.
References _T, and OnApply().
GetDirsListBox()
wxListBox * CompilerOptionsDlg::GetDirsListBox () private
Definition at line 1715 of file compileroptionsdlg.cpp.
References wxNotebook::GetSelection().
Referenced by OnAddDirClick(), OnClearDirClick(), OnCopyDirsClick(), OnEditDirClick(), OnMoveDirDownClick(), OnMoveDirUpClick(), OnRemoveDirClick(), and OnUpdateUI().
GetTitle()
virtual wxString CompilerOptionsDlg::GetTitle () const inline virtual
Returns
the panel's title.
Implements cbConfigurationPanel.
Definition at line 34 of file compileroptionsdlg.h.
References _().
GetVarsOwner()
CompileOptionsBase * CompilerOptionsDlg::GetVarsOwner () private
Definition at line 1733 of file compileroptionsdlg.cpp.
References CompilerFactory::GetCompiler(), m_CurrentCompilerIdx, m_pProject, and m_pTarget.
Referenced by DoFillVars(), and DoSaveVars().
OnAddCompilerClick()
void CompilerOptionsDlg::OnAddCompilerClick (wxCommandEvent & event) private
Definition at line 2097 of file compileroptionsdlg.cpp.
References _(), cbGetTextFromUser(), cbConfigurationPanel::cbMessageBox(), CompilerChanged(), CompilerFactory::CreateCompilerCopy(), DoFillCompilerDependentSettings(), DoSaveCompilerDependentSettings(), CompilerFactory::GetCompiler(), CompilerFactory::GetCompilerIndex(), wxChoice::GetCount(), wxString::IsEmpty(), m_bDirty, m_CurrentCompilerIdx, wxChoice::SetSelection(), cbException::ShowErrorMessage(), wxCANCEL, wxICON_ERROR, wxICON_EXCLAMATION, wxID_CANCEL, wxID_NO, wxID_YES, wxNO, and wxYES.
OnAddDirClick()
void CompilerOptionsDlg::OnAddDirClick (wxCommandEvent & event) private
Definition at line 1832 of file compileroptionsdlg.cpp.
References _(), _T, CompileTargetBase::GetBasePath(), GetDirsListBox(), m_bDirty, m_pProject, PlaceWindow(), and wxID_OK.
OnAddExtraPathClick()
void CompilerOptionsDlg::OnAddExtraPathClick (wxCommandEvent & event) private
Definition at line 2374 of file compileroptionsdlg.cpp.
References _(), _T, cbConfigurationPanel::cbMessageBox(), EditPathDlg::GetPath(), wxArrayString::Index(), ListBox2ArrayString(), m_bDirty, PlaceWindow(), wxDialog::ShowModal(), wxICON_WARNING, wxID_OK, and wxNOT_FOUND.
OnAddLibClick()
void CompilerOptionsDlg::OnAddLibClick (wxCommandEvent & event) private
Definition at line 2227 of file compileroptionsdlg.cpp.
References _(), _T, GetArrayFromString(), CompileTargetBase::GetBasePath(), wxArrayString::GetCount(), m_bDirty, m_pProject, PlaceWindow(), and wxID_OK.
OnAddVarClick()
void CompilerOptionsDlg::OnAddVarClick (wxCommandEvent & event) private
Definition at line 1987 of file compileroptionsdlg.cpp.
References _(), _T, EditPairDlg::bmBrowseForDirectory, CVA_Add, m_bDirty, m_CustomVarActions, PlaceWindow(), QuoteString(), wxDialog::ShowModal(), wxString::Trim(), and wxID_OK.
OnAdvancedClick()
void CompilerOptionsDlg::OnAdvancedClick (wxCommandEvent & event) private
Definition at line 2654 of file compileroptionsdlg.cpp.
References _(), CompilerFactory::GetCompiler(), wxChoice::GetSelection(), AdvancedCompilerOptionsDlg::IsDirty(), PlaceWindow(), AnnoyingDialog::rtYES, wxDialog::ShowModal(), AnnoyingDialog::ShowModal(), and wxART_QUESTION.
OnApply()
void CompilerOptionsDlg::OnApply () virtual
Called when the user chooses to apply the configuration.
Implements cbConfigurationPanel.
Definition at line 2782 of file compileroptionsdlg.cpp.
References _(), _T, cbConfigurationPanel::cbMessageBox(), CompilerGCC::DoRegisterCompilers(), DoSaveCompilerDependentSettings(), Manager::Get(), Manager::GetConfigManager(), Manager::GetMacrosManager(), wxSpinCtrl::GetValue(), wxCheckBox::IsChecked(), CompilerGCC::IsRunning(), ListBox2ArrayString(), CompilerGCC::LoadOptions(), m_bDirty, m_Compiler, m_CurrentCompilerIdx, CompilerGCC::m_LogBuildProgressPercentage, m_pProject, ConfigManager::ReadBool(), ConfigManager::ReadInt(), CompilerGCC::ReAllocProcesses(), MacrosManager::Reset(), CompilerGCC::SaveOptions(), CompilerFactory::SaveSettings(), CompilerGCC::SetupEnvironment(), CompilerFactory::UnregisterCompilers(), ConfigManager::Write(), and wxICON_WARNING.
Referenced by GetBitmapBaseName().
OnAutoDetectClick()
void CompilerOptionsDlg::OnAutoDetectClick (wxCommandEvent & event) private
Definition at line 2609 of file compileroptionsdlg.cpp.
References AutoDetectCompiler().
OnCancel()
virtual void CompilerOptionsDlg::OnCancel () inline virtual
Called when the user chooses to cancel the configuration.
Implements cbConfigurationPanel.
Definition at line 37 of file compileroptionsdlg.h.
OnCategoryChanged()
void CompilerOptionsDlg::OnCategoryChanged (wxCommandEvent & event) private
Definition at line 1740 of file compileroptionsdlg.cpp.
References DoFillOptions().
OnClearDirClick()
void CompilerOptionsDlg::OnClearDirClick (wxCommandEvent & event) private
Definition at line 1899 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), GetDirsListBox(), m_bDirty, wxCANCEL, wxICON_QUESTION, wxID_OK, and wxOK.
OnClearExtraPathClick()
void CompilerOptionsDlg::OnClearExtraPathClick (wxCommandEvent & event) private
Definition at line 2444 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), m_bDirty, wxCANCEL, wxICON_QUESTION, wxID_OK, and wxOK.
OnClearLibClick()
void CompilerOptionsDlg::OnClearLibClick (wxCommandEvent & event) private
Definition at line 2319 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), m_bDirty, wxCANCEL, wxICON_QUESTION, wxID_OK, and wxOK.
OnClearVarClick()
void CompilerOptionsDlg::OnClearVarClick (wxCommandEvent & event) private
Definition at line 2057 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), CVA_Remove, wxString::IsEmpty(), m_bDirty, m_CustomVarActions, wxEmptyString, wxICON_QUESTION, wxID_YES, wxNO, and wxYES.
OnCompilerChanged()
void CompilerOptionsDlg::OnCompilerChanged (wxCommandEvent & event) private
Definition at line 1593 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), CompilerChanged(), DoSaveCompilerDependentSettings(), m_bDirty, m_bFlagsDirty, m_CurrentCompilerIdx, m_pProject, wxCANCEL, wxICON_EXCLAMATION, wxID_CANCEL, wxID_NO, wxID_YES, wxNO, and wxYES.
Referenced by CompilerOptionsDlg(), and OnTreeSelectionChange().
OnCopyDirsClick()
void CompilerOptionsDlg::OnCopyDirsClick (wxCommandEvent & event) private
Definition at line 1914 of file compileroptionsdlg.cpp.
References _(), _T, wxArrayString::Add(), CompileOptionsBase::AddIncludeDir(), CompileOptionsBase::AddLibDir(), CompileOptionsBase::AddResourceIncludeDir(), cbGetMultiChoiceDialog(), Manager::Get(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), GetDirsListBox(), Manager::GetLogManager(), wxNotebook::GetSelection(), CompileTargetBase::GetTitle(), LogManager::LogWarning(), and m_pProject.
OnCopyLibsClick()
void CompilerOptionsDlg::OnCopyLibsClick (wxCommandEvent & event) private
Definition at line 2331 of file compileroptionsdlg.cpp.
References _(), _T, wxArrayString::Add(), CompileOptionsBase::AddLinkLib(), cbGetMultiChoiceDialog(), Manager::Get(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), Manager::GetLogManager(), CompileTargetBase::GetTitle(), LogManager::LogWarning(), and m_pProject.
OnDirty()
void CompilerOptionsDlg::OnDirty (wxCommandEvent & event) private
Definition at line 1422 of file compileroptionsdlg.cpp.
References m_bDirty.
OnEditCompilerClick()
void CompilerOptionsDlg::OnEditCompilerClick (wxCommandEvent & event) private
Definition at line 2165 of file compileroptionsdlg.cpp.
References _(), cbGetTextFromUser(), CompilerFactory::GetCompiler(), wxString::IsEmpty(), m_CurrentCompilerIdx, Compiler::SetName(), wxChoice::SetSelection(), and wxChoice::SetString().
OnEditDirClick()
void CompilerOptionsDlg::OnEditDirClick (wxCommandEvent & event) private
Definition at line 1853 of file compileroptionsdlg.cpp.
References _(), _T, cbConfigurationPanel::cbMessageBox(), CompileTargetBase::GetBasePath(), GetDirsListBox(), m_bDirty, m_pProject, PlaceWindow(), wxICON_ERROR, and wxID_OK.
OnEditExtraPathClick()
void CompilerOptionsDlg::OnEditExtraPathClick (wxCommandEvent & event) private
Definition at line 2402 of file compileroptionsdlg.cpp.
References _(), _T, cbConfigurationPanel::cbMessageBox(), EditPathDlg::GetPath(), wxFileName::GetPathSeparator(), wxArrayString::Index(), ListBox2ArrayString(), m_bDirty, PlaceWindow(), wxDialog::ShowModal(), wxICON_WARNING, wxID_OK, and wxNOT_FOUND.
OnEditLibClick()
void CompilerOptionsDlg::OnEditLibClick (wxCommandEvent & event) private
Definition at line 2250 of file compileroptionsdlg.cpp.
References _(), _T, cbConfigurationPanel::cbMessageBox(), CompileTargetBase::GetBasePath(), m_bDirty, m_pProject, PlaceWindow(), wxICON_ERROR, and wxID_OK.
OnEditVarClick()
void CompilerOptionsDlg::OnEditVarClick (wxCommandEvent & event) private
Definition at line 2005 of file compileroptionsdlg.cpp.
References _(), _T, EditPairDlg::bmBrowseForDirectory, CVA_Edit, VariableListClientData::key, m_bDirty, m_CustomVarActions, PlaceWindow(), QuoteString(), wxDialog::ShowModal(), wxString::Trim(), VariableListClientData::value, and wxID_OK.
OnFlagsPopup()
void CompilerOptionsDlg::OnFlagsPopup (wxPropertyGridEvent & event) private
Definition at line 2918 of file compileroptionsdlg.cpp.
References _(), wxArrayString::Add(), CompOption::additionalLibs, CompilerOptions::AddOption(), wxMenu::Append(), wxMenu::AppendSeparator(), CompOption::category, CompOption::checkAgainst, CompOption::checkMessage, wxPropertyGrid::CollapseAll(), DoFillOptions(), CompOption::exclusive, wxPropertyGrid::ExpandAll(), CompilerFactory::GetCompiler(), Compiler::GetCOnlyFlags(), wxArrayString::GetCount(), CompilerOptions::GetCount(), Compiler::GetCPPOnlyFlags(), wxPropertyGrid::GetFirstChild(), wxPGProperty::GetLabel(), CompilerOptions::GetOption(), CompilerOptions::GetOptionByName(), wxPGProperty::GetParent(), wxArrayString::IsEmpty(), wxString::IsEmpty(), m_bDirty, m_bFlagsDirty, m_CurrentCompilerIdx, m_FlagsPG, m_MenuOption, m_Options, MakeUniqueString(), CompOption::name, OnFlagsPopupClick(), CompOption::option, PlaceWindow(), CompilerOptions::RemoveOption(), wxString::Replace(), Compiler::SetCOnlyFlags(), Compiler::SetCPPOnlyFlags(), wxDialog::ShowModal(), CompOption::supersedes, wxID_OK, wxRESIZE_BORDER, wxT, wxTE_MULTILINE, wxTextEntryDialogStyle, and wxVERTICAL.
OnFlagsPopupClick()
void CompilerOptionsDlg::OnFlagsPopupClick (wxCommandEvent & event) private
Definition at line 3116 of file compileroptionsdlg.cpp.
References m_MenuOption.
Referenced by OnFlagsPopup().
OnIgnoreAddClick()
void CompilerOptionsDlg::OnIgnoreAddClick (wxCommandEvent & event) private
Definition at line 2457 of file compileroptionsdlg.cpp.
References wxString::Len(), m_bDirty, and wxNOT_FOUND.
OnIgnoreRemoveClick()
void CompilerOptionsDlg::OnIgnoreRemoveClick (wxCommandEvent & event) private
Definition at line 2471 of file compileroptionsdlg.cpp.
References m_bDirty, and wxNOT_FOUND.
OnMasterPathClick()
void CompilerOptionsDlg::OnMasterPathClick (wxCommandEvent & event) private
Definition at line 2597 of file compileroptionsdlg.cpp.
References _(), ChooseDirectory(), wxString::IsEmpty(), and m_bDirty.
OnMoveDirDownClick()
void CompilerOptionsDlg::OnMoveDirDownClick (wxCommandEvent & event) private
Definition at line 2570 of file compileroptionsdlg.cpp.
References GetDirsListBox(), and m_bDirty.
OnMoveDirUpClick()
void CompilerOptionsDlg::OnMoveDirUpClick (wxCommandEvent & event) private
Definition at line 2545 of file compileroptionsdlg.cpp.
References GetDirsListBox(), and m_bDirty.
OnMoveLibDownClick()
void CompilerOptionsDlg::OnMoveLibDownClick (wxCommandEvent & event) private
Definition at line 2514 of file compileroptionsdlg.cpp.
References m_bDirty.
OnMoveLibUpClick()
void CompilerOptionsDlg::OnMoveLibUpClick (wxCommandEvent & event) private
Definition at line 2485 of file compileroptionsdlg.cpp.
References m_bDirty.
OnMyCharHook()
void CompilerOptionsDlg::OnMyCharHook (wxKeyEvent & event) private
Definition at line 2864 of file compileroptionsdlg.cpp.
References _T, wxXmlResource::GetXRCID(), m_MenuOption, WXK_DELETE, WXK_INSERT, WXK_NUMPAD_DELETE, WXK_NUMPAD_ENTER, WXK_NUMPAD_INSERT, and WXK_RETURN.
OnOptionChanged()
void CompilerOptionsDlg::OnOptionChanged (wxPropertyGridEvent & event) private
Definition at line 1745 of file compileroptionsdlg.cpp.
References _(), CompOption::additionalLibs, wxPropertyGridIterator::AtEnd(), CompOption::category, CompOption::checkAgainst, CompOption::checkMessage, CompOption::enabled, wxString::EndsWith(), CompOption::exclusive, GetArrayFromString(), wxVariant::GetBool(), CompilerOptions::GetCount(), wxPropertyGrid::GetIterator(), wxPGProperty::GetLabel(), CompilerOptions::GetOption(), CompilerOptions::GetOptionByAdditionalLibs(), CompilerOptions::GetOptionByName(), CompilerOptions::GetOptionByOption(), wxPGProperty::IsCategory(), wxString::IsEmpty(), wxVariant::IsNull(), m_bDirty, m_FlagsPG, m_Options, CompOption::name, AnnoyingDialog::OK, CompOption::option, wxPropertyGrid::SetPropertyValue(), AnnoyingDialog::ShowModal(), CompOption::supersedes, wxART_INFORMATION, wxEmptyString, and wxT.
OnOptionDoubleClick()
void CompilerOptionsDlg::OnOptionDoubleClick (wxPropertyGridEvent & event) private
Definition at line 3121 of file compileroptionsdlg.cpp.
References wxPropertyGrid::ChangePropertyValue(), wxPropertyGrid::GetPropertyValue(), and m_FlagsPG.
OnRealApply()
void CompilerOptionsDlg::OnRealApply () private
OnRemoveCompilerClick()
void CompilerOptionsDlg::OnRemoveCompilerClick (wxCommandEvent & event) private
Definition at line 2179 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), DoFillCompilerDependentSettings(), CompilerFactory::GetCompiler(), wxChoice::GetCount(), m_CurrentCompilerIdx, CompilerFactory::RemoveCompiler(), wxChoice::SetSelection(), wxICON_QUESTION, wxID_YES, wxNO, wxNO_DEFAULT, and wxYES.
OnRemoveDirClick()
void CompilerOptionsDlg::OnRemoveDirClick (wxCommandEvent & event) private
Definition at line 1881 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), GetDirsListBox(), m_bDirty, wxCANCEL, wxICON_QUESTION, wxID_OK, and wxOK.
OnRemoveExtraPathClick()
void CompilerOptionsDlg::OnRemoveExtraPathClick (wxCommandEvent & event) private
Definition at line 2435 of file compileroptionsdlg.cpp.
References m_bDirty.
OnRemoveLibClick()
void CompilerOptionsDlg::OnRemoveLibClick (wxCommandEvent & event) private
Definition at line 2288 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), m_bDirty, wxString::Printf(), wxCANCEL, wxICON_QUESTION, wxID_OK, and wxOK.
OnRemoveVarClick()
void CompilerOptionsDlg::OnRemoveVarClick (wxCommandEvent & event) private
Definition at line 2036 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), CVA_Remove, wxString::IsEmpty(), m_bDirty, m_CustomVarActions, wxEmptyString, wxICON_QUESTION, wxID_YES, and wxYES_NO.
OnResetCompilerClick()
void CompilerOptionsDlg::OnResetCompilerClick (wxCommandEvent & event) private
Definition at line 2197 of file compileroptionsdlg.cpp.
References _(), AutoDetectCompiler(), cbConfigurationPanel::cbMessageBox(), DoFillCompilerDependentSettings(), CompilerFactory::GetCompiler(), ConfigManager::GetDataFolder(), Compiler::GetID(), m_CurrentCompilerIdx, Compiler::Reset(), CompilerFactory::SaveSettings(), wxFileExists(), wxICON_QUESTION, wxID_YES, wxNO, wxNO_DEFAULT, wxRemoveFile(), wxT, and wxYES.
OnSelectProgramClick()
void CompilerOptionsDlg::OnSelectProgramClick (wxCommandEvent & event) private
Definition at line 2614 of file compileroptionsdlg.cpp.
References _(), _T, m_bDirty, PlaceWindow(), wxFileDialog::SetFilterIndex(), wxFD_FILE_MUST_EXIST, wxFD_OPEN, and wxID_OK.
OnSetDefaultCompilerClick()
void CompilerOptionsDlg::OnSetDefaultCompilerClick (wxCommandEvent & event) private
Definition at line 2082 of file compileroptionsdlg.cpp.
References _(), wxString::c_str(), cbConfigurationPanel::cbMessageBox(), CompilerFactory::GetDefaultCompiler(), Compiler::GetName(), wxChoice::GetSelection(), wxString::Printf(), CompilerFactory::SetDefaultCompiler(), and wxString::wx_str().
OnTreeSelectionChange()
void CompilerOptionsDlg::OnTreeSelectionChange (wxTreeEvent & event) private
Definition at line 1459 of file compileroptionsdlg.cpp.
References _(), DoFillCompilerDependentSettings(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetCompilerIndex(), wxTreeEvent::GetItem(), wxTreeCtrl::GetItemData(), Compiler::GetOptions(), ScopeTreeData::GetProject(), wxNotebook::GetSelection(), ScopeTreeData::GetTarget(), CompileTargetBase::GetTargetType(), cbProject::IsMakefileCustom(), m_BuildingTree, m_CurrentCompilerIdx, m_Options, m_pProject, m_pTarget, OnCompilerChanged(), wxString::Printf(), CompilerFactory::SelectCompilerUI(), wxNotebook::SetSelection(), CompileOptionsBase::SupportsCurrentPlatform(), ttCommandsOnly, and wxString::wx_str().
OnTreeSelectionChanging()
void CompilerOptionsDlg::OnTreeSelectionChanging (wxTreeEvent & event) private
Definition at line 1553 of file compileroptionsdlg.cpp.
References _(), DoSaveCompilerDependentSettings(), wxTreeCtrl::GetItemData(), wxTreeEvent::GetOldItem(), m_bDirty, m_bFlagsDirty, m_BuildingTree, AnnoyingDialog::rtCANCEL, AnnoyingDialog::rtNO, AnnoyingDialog::rtYES, AnnoyingDialog::ShowModal(), wxART_QUESTION, and AnnoyingDialog::YES_NO_CANCEL.
OnUpdateUI()
void CompilerOptionsDlg::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 2710 of file compileroptionsdlg.cpp.
References CompilerFactory::GetCompiler(), CompilerFactory::GetCompilerIndex(), CompilerFactory::GetDefaultCompiler(), GetDirsListBox(), wxTreeCtrl::GetItemData(), Compiler::GetParentID(), wxTreeCtrl::GetSelection(), ScopeTreeData::GetTarget(), wxString::IsEmpty(), m_pProject, and UpdateUIListBoxAndButtons().
OptionsToText()
void CompilerOptionsDlg::OptionsToText () private
Definition at line 914 of file compileroptionsdlg.cpp.
References _(), _T, wxArrayString::Add(), CompOption::additionalLibs, CompilerSwitches::defines, DoGetCompileOptions(), CompOption::enabled, CompilerSwitches::genericSwitch, CompilerFactory::GetCompiler(), wxArrayString::GetCount(), CompilerOptions::GetCount(), CompilerOptions::GetOption(), GetStringFromArray(), Compiler::GetSwitches(), wxArrayString::Index(), wxArrayString::Insert(), wxString::IsEmpty(), wxArrayString::IsEmpty(), m_CompilerOptions, m_LinkerOptions, m_LinkLibs, m_Options, CompOption::option, wxArrayString::Remove(), wxString::RemoveLast(), AnnoyingDialog::rtNO, AnnoyingDialog::ShowModal(), wxString::Trim(), wxART_QUESTION, wxNOT_FOUND, wxT, and AnnoyingDialog::YES_NO.
Referenced by DoSaveOptions().
ProjectTargetCompilerAdjust()
void CompilerOptionsDlg::ProjectTargetCompilerAdjust () private
checks if compiler changed for project/target and takes actions accordingly
Definition at line 1427 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), CompileTargetBase::GetCompilerID(), wxString::IsEmpty(), m_CurrentCompilerIdx, m_NewProjectOrTargetCompilerId, m_pProject, m_pTarget, CompileTargetBase::SetCompilerID(), cbProject::SetCompilerID(), UpdateCompilerForTargets(), wxEmptyString, and wxICON_EXCLAMATION.
Referenced by DoSaveCompilerDependentSettings().
TextToOptions()
void CompilerOptionsDlg::TextToOptions () private
Definition at line 691 of file compileroptionsdlg.cpp.
References _T, wxArrayString::Clear(), CompilerSwitches::defines, CompOption::enabled, CompilerFactory::GetCompiler(), wxArrayString::GetCount(), CompilerOptions::GetCount(), CompilerOptions::GetOption(), CompilerOptions::GetOptionByAdditionalLibs(), CompilerOptions::GetOptionByOption(), Compiler::GetSwitches(), wxArrayString::Item(), m_CompilerOptions, m_CurrentCompilerIdx, m_LinkerOptions, m_LinkLibs, m_Options, wxArrayString::RemoveAt(), wxString::StartsWith(), and wxString::Trim().
Referenced by DoLoadOptions().
UpdateCompilerForTargets()
void CompilerOptionsDlg::UpdateCompilerForTargets (int compilerIdx) private
Definition at line 1651 of file compileroptionsdlg.cpp.
References _(), cbConfigurationPanel::cbMessageBox(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompilerFactory::GetCompiler(), Compiler::GetID(), m_pProject, CompileTargetBase::SetCompilerID(), wxICON_QUESTION, wxID_YES, and wxYES_NO.
Referenced by ProjectTargetCompilerAdjust().
Member Data Documentation
m_bDirty
bool CompilerOptionsDlg::m_bDirty private
true if a setting has changed since last save
Definition at line 131 of file compileroptionsdlg.h.
Referenced by AutoDetectCompiler(), DoFillCompilerDependentSettings(), DoSaveCompilerDependentSettings(), OnAddCompilerClick(), OnAddDirClick(), OnAddExtraPathClick(), OnAddLibClick(), OnAddVarClick(), OnApply(), OnClearDirClick(), OnClearExtraPathClick(), OnClearLibClick(), OnClearVarClick(), OnCompilerChanged(), OnDirty(), OnEditDirClick(), OnEditExtraPathClick(), OnEditLibClick(), OnEditVarClick(), OnFlagsPopup(), OnIgnoreAddClick(), OnIgnoreRemoveClick(), OnMasterPathClick(), OnMoveDirDownClick(), OnMoveDirUpClick(), OnMoveLibDownClick(), OnMoveLibUpClick(), OnOptionChanged(), OnRemoveDirClick(), OnRemoveExtraPathClick(), OnRemoveLibClick(), OnRemoveVarClick(), OnSelectProgramClick(), and OnTreeSelectionChanging().
m_bFlagsDirty
bool CompilerOptionsDlg::m_bFlagsDirty private
true if a flag (not its value) has changed since last save
Definition at line 132 of file compileroptionsdlg.h.
Referenced by DoFillCompilerDependentSettings(), DoSaveCompilerDependentSettings(), OnCompilerChanged(), OnFlagsPopup(), and OnTreeSelectionChanging().
m_BuildingTree
bool CompilerOptionsDlg::m_BuildingTree private
flag to ignore tree changing events while building it
Definition at line 136 of file compileroptionsdlg.h.
Referenced by DoFillTree(), OnTreeSelectionChange(), and OnTreeSelectionChanging().
m_Compiler
CompilerGCC* CompilerOptionsDlg::m_Compiler private
Definition at line 122 of file compileroptionsdlg.h.
Referenced by OnApply().
m_CompilerOptions
wxArrayString CompilerOptionsDlg::m_CompilerOptions private
Definition at line 126 of file compileroptionsdlg.h.
Referenced by DoLoadOptions(), DoSaveOptions(), OptionsToText(), and TextToOptions().
m_CurrentCompilerIdx
int CompilerOptionsDlg::m_CurrentCompilerIdx private
Definition at line 128 of file compileroptionsdlg.h.
Referenced by AutoDetectCompiler(), CompilerChanged(), CompilerOptionsDlg(), DoFillCompilerPrograms(), DoLoadOptions(), DoSaveCompilerDefinition(), DoSaveCompilerPrograms(), DoSaveOptions(), GetVarsOwner(), OnAddCompilerClick(), OnApply(), OnCompilerChanged(), OnEditCompilerClick(), OnFlagsPopup(), OnRemoveCompilerClick(), OnResetCompilerClick(), OnTreeSelectionChange(), ProjectTargetCompilerAdjust(), and TextToOptions().
m_CustomVarActions
std::vector<CustomVarAction> CompilerOptionsDlg::m_CustomVarActions private
the actions carried out on the custom vars that need to be saved/applied
Definition at line 133 of file compileroptionsdlg.h.
Referenced by DoSaveVars(), OnAddVarClick(), OnClearVarClick(), OnEditVarClick(), and OnRemoveVarClick().
m_FlagsPG
wxPropertyGrid* CompilerOptionsDlg::m_FlagsPG private
Definition at line 121 of file compileroptionsdlg.h.
Referenced by CompilerOptionsDlg(), DoFillOptions(), OnFlagsPopup(), OnOptionChanged(), and OnOptionDoubleClick().
m_LinkerOptions
wxArrayString CompilerOptionsDlg::m_LinkerOptions private
Definition at line 124 of file compileroptionsdlg.h.
Referenced by DoLoadOptions(), DoSaveOptions(), OptionsToText(), and TextToOptions().
m_LinkLibs
wxArrayString CompilerOptionsDlg::m_LinkLibs private
Definition at line 125 of file compileroptionsdlg.h.
Referenced by DoLoadOptions(), DoSaveOptions(), OptionsToText(), and TextToOptions().
m_MenuOption
int CompilerOptionsDlg::m_MenuOption = -1 static private
Definition at line 137 of file compileroptionsdlg.h.
Referenced by OnFlagsPopup(), OnFlagsPopupClick(), and OnMyCharHook().
m_NewProjectOrTargetCompilerId
wxString CompilerOptionsDlg::m_NewProjectOrTargetCompilerId private
keeps track of the changes of compiler of the selected project/target
Definition at line 134 of file compileroptionsdlg.h.
Referenced by CompilerChanged(), and ProjectTargetCompilerAdjust().
m_Options
CompilerOptions CompilerOptionsDlg::m_Options private
Definition at line 123 of file compileroptionsdlg.h.
Referenced by CompilerChanged(), CompilerOptionsDlg(), DoFillOptions(), DoSaveCompilerDefinition(), OnFlagsPopup(), OnOptionChanged(), OnTreeSelectionChange(), OptionsToText(), and TextToOptions().
m_pProject
cbProject* CompilerOptionsDlg::m_pProject private
Definition at line 129 of file compileroptionsdlg.h.
Referenced by CompilerChanged(), CompilerOptionsDlg(), DoFillCompilerPrograms(), DoFillOthers(), DoFillTree(), DoLoadOptions(), DoSaveCompilerPrograms(), DoSaveOptions(), GetVarsOwner(), OnAddDirClick(), OnAddLibClick(), OnApply(), OnCompilerChanged(), OnCopyDirsClick(), OnCopyLibsClick(), OnEditDirClick(), OnEditLibClick(), OnTreeSelectionChange(), OnUpdateUI(), ProjectTargetCompilerAdjust(), and UpdateCompilerForTargets().
m_pTarget
ProjectBuildTarget* CompilerOptionsDlg::m_pTarget private
Definition at line 130 of file compileroptionsdlg.h.
Referenced by CompilerOptionsDlg(), DoFillTree(), DoLoadOptions(), DoSaveOptions(), GetVarsOwner(), OnTreeSelectionChange(), and ProjectTargetCompilerAdjust().
m_ResourceCompilerOptions
wxArrayString CompilerOptionsDlg::m_ResourceCompilerOptions private
Definition at line 127 of file compileroptionsdlg.h.
Referenced by DoLoadOptions(), and DoSaveOptions().
The documentation for this class was generated from the following files:
compileroptionsdlg.h
compileroptionsdlg.cpp