Code::Blocks: CompilerSettingsDlg Class Reference
CompilerSettingsDlg Class Reference
#include <compilersettingsdlg.h>
Public Member Functions
CompilerSettingsDlg (wxWindow *parent)
virtual ~CompilerSettingsDlg ()
virtual void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void OnPageChanging (wxListbookEvent &event)
void OnPageChanged (wxListbookEvent &event)
Private Member Functions
void AddPluginPanels ()
void UpdateListbookImages ()
Private Attributes
ConfigurationPanelsArray m_PluginPanels
wxImageList * m_pImageList
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 14 of file compilersettingsdlg.h.
Constructor & Destructor Documentation
CompilerSettingsDlg()
CompilerSettingsDlg::CompilerSettingsDlg (wxWindow * parent)
Definition at line 51 of file compilersettingsdlg.cpp.
References cbReadBatchBuildPlugins(), appglobals::DefaultBatchBuildArgs, PluginElement::fileName, Manager::Get(), Manager::GetPluginManager(), PluginManager::GetPlugins(), PluginElement::info, cbPlugin::IsAttached(), OnPageChanged(), OnPageChanging(), PluginElement::plugin, and PluginInfo::title.
~CompilerSettingsDlg()
CompilerSettingsDlg::~CompilerSettingsDlg () virtual
Definition at line 103 of file compilersettingsdlg.cpp.
References m_pImageList.
Member Function Documentation
AddPluginPanels()
void CompilerSettingsDlg::AddPluginPanels () private
Definition at line 109 of file compilersettingsdlg.cpp.
References base_imgs, cbLoadBitmap(), cgCompiler, Manager::Get(), cbConfigurationPanel::GetBitmapBaseName(), PluginManager::GetConfigurationPanels(), Manager::GetPluginManager(), cbConfigurationPanel::GetTitle(), ConfigManager::LocateDataFile(), m_pImageList, m_PluginPanels, sdDataGlobal, sdDataUser, cbConfigurationPanel::SetParentDialog(), and UpdateListbookImages().
EndModal()
void CompilerSettingsDlg::EndModal (int retCode) virtual
Definition at line 205 of file compilersettingsdlg.cpp.
References cbWriteBatchBuildPlugins(), appglobals::DefaultBatchBuildArgs, ScriptBindings::EndModal(), PluginElement::fileName, Manager::Get(), Manager::GetConfigManager(), Manager::GetPluginManager(), PluginManager::GetPlugins(), PluginElement::info, m_PluginPanels, cbConfigurationPanel::OnApply(), cbConfigurationPanel::OnCancel(), ConfigManager::Read(), Associations::SetBatchBuildOnly(), PluginInfo::title, and ConfigManager::Write().
OnPageChanged()
void CompilerSettingsDlg::OnPageChanged (wxListbookEvent & event) protected
Definition at line 198 of file compilersettingsdlg.cpp.
References UpdateListbookImages().
Referenced by CompilerSettingsDlg().
OnPageChanging()
void CompilerSettingsDlg::OnPageChanging (wxListbookEvent & event) protected
Definition at line 194 of file compilersettingsdlg.cpp.
Referenced by CompilerSettingsDlg().
UpdateListbookImages()
void CompilerSettingsDlg::UpdateListbookImages () private
Definition at line 166 of file compilersettingsdlg.cpp.
References Manager::Get(), IMAGES_COUNT, m_pImageList, m_PluginPanels, SetSettingsIconsStyle(), sisLargeIcons, and sisNoIcons.
Referenced by AddPluginPanels(), and OnPageChanged().
Member Data Documentation
m_pImageList
wxImageList* CompilerSettingsDlg::m_pImageList private
Definition at line 27 of file compilersettingsdlg.h.
Referenced by AddPluginPanels(), UpdateListbookImages(), and ~CompilerSettingsDlg().
m_PluginPanels
ConfigurationPanelsArray CompilerSettingsDlg::m_PluginPanels private
Definition at line 26 of file compilersettingsdlg.h.
Referenced by AddPluginPanels(), EndModal(), and UpdateListbookImages().
The documentation for this class was generated from the following files:
compilersettingsdlg.h
compilersettingsdlg.cpp