Code::Blocks: WorkspaceLoader Class Reference
WorkspaceLoader Class Reference
#include <workspaceloader.h>
Public Member Functions
WorkspaceLoader ()
virtual ~WorkspaceLoader ()
bool Open (const wxString &filename, wxString &Title)
bool Save (const wxString &title, const wxString &filename)
bool SaveLayout (const wxString &filename)
bool LoadLayout (const wxString &filename)
Public Member Functions inherited from IBaseWorkspaceLoader
IBaseWorkspaceLoader ()
virtual ~IBaseWorkspaceLoader ()
Detailed Description
Definition at line 16 of file workspaceloader.h.
Constructor & Destructor Documentation
WorkspaceLoader()
WorkspaceLoader::WorkspaceLoader ()
Definition at line 37 of file workspaceloader.cpp.
~WorkspaceLoader()
WorkspaceLoader::~WorkspaceLoader () virtual
Definition at line 42 of file workspaceloader.cpp.
Member Function Documentation
LoadLayout()
bool WorkspaceLoader::LoadLayout (const wxString & filename)
Definition at line 264 of file workspaceloader.cpp.
References _(), _T, cbC2U(), LogManager::DebugLog(), F(), wxString::Format(), Manager::Get(), Manager::GetEditorManager(), wxFileName::GetFullPath(), Manager::GetLogManager(), EditorManager::GetNotebook(), GetpMan(), GetpMsg(), ProjectManager::GetWorkspace(), Manager::IsBatchBuild(), wxString::IsEmpty(), ProjectManager::IsOpen(), TinyXML::LoadDocument(), cbAuiNotebook::LoadPerspective(), wxFileName::MakeAbsolute(), AnnoyingDialog::OK, wxString::Prepend(), cbWorkspace::SetPreferredTarget(), ProjectManager::SetProject(), AnnoyingDialog::ShowModal(), CfgMgrConsts::version, WORKSPACE_LAYOUT_FILE_VERSION_MAJOR, WORKSPACE_LAYOUT_FILE_VERSION_MINOR, wxString::wx_str(), wxART_INFORMATION, and wxART_WARNING.
Referenced by cbWorkspace::LoadLayout().
Open()
bool WorkspaceLoader::Open (const wxString & filename, wxString & Title) virtual
Implements IBaseWorkspaceLoader.
Definition at line 52 of file workspaceloader.cpp.
References _(), _T, ProjectManager::AddProjectDependency(), cbC2U(), cbMessageBox(), LogManager::DebugLog(), Manager::Get(), wxFileName::GetFullPath(), wxFileName::GetPath(), GetpMan(), GetpMsg(), Manager::GetProjectManager(), Manager::IsAppShuttingDown(), wxString::IsEmpty(), ProjectManager::IsOpen(), TinyXML::LoadDocument(), ProjectManager::LoadProject(), wxFileName::MakeAbsolute(), UnixFilename(), and wxICON_WARNING.
Save()
bool WorkspaceLoader::Save (const wxString & title, const wxString & filename) virtual
Implements IBaseWorkspaceLoader.
Definition at line 163 of file workspaceloader.cpp.
References cbSaveTinyXMLDocument(), cbU2C(), Manager::Get(), ProjectManager::GetDependenciesForProject(), CompileTargetBase::GetFilename(), wxFileName::GetPath(), Manager::GetProjectManager(), ProjectManager::GetProjects(), wxFileName::MakeRelativeTo(), UnixFilename(), and wxPATH_UNIX.
Referenced by cbWorkspace::Save().
SaveLayout()
bool WorkspaceLoader::SaveLayout (const wxString & filename)
Definition at line 205 of file workspaceloader.cpp.
References _T, cbSaveTinyXMLDocument(), cbU2C(), Manager::Get(), ProjectManager::GetActiveProject(), wxFileName::GetPath(), Manager::GetProjectManager(), ProjectManager::GetWorkspace(), wxString::IsEmpty(), wxFileName::MakeRelativeTo(), UnixFilename(), WORKSPACE_LAYOUT_FILE_VERSION_MAJOR, WORKSPACE_LAYOUT_FILE_VERSION_MINOR, and wxPATH_UNIX.
Referenced by cbWorkspace::SaveLayout().
The documentation for this class was generated from the following files:
workspaceloader.h
workspaceloader.cpp