Code::Blocks: ValueTooltip Class Reference
ValueTooltip Class Reference
#include <watchesdlg.h>
Public Member Functions
ValueTooltip (const cb::shared_ptr< cbWatch > &watch, wxWindow *parent)
~ValueTooltip ()
void Dismiss ()
void UpdateWatch ()
Protected Member Functions
virtual void OnDismiss ()
Private Member Functions
void Fit ()
void ClearWatch ()
void OnCollapse (wxPropertyGridEvent &event)
void OnExpand (wxPropertyGridEvent &event)
void OnTimer (wxTimerEvent &event)
Private Attributes
wxPropertyGrid * m_grid
wxBoxSizer * m_sizer
wxPanel * m_panel
wxTimer m_timer
int m_outsideCount
cb::shared_ptr< cbWatch > m_watch
Detailed Description
Definition at line 79 of file watchesdlg.h.
Constructor & Destructor Documentation
ValueTooltip()
ValueTooltip::ValueTooltip (const cb::shared_ptr< cbWatch > & watch, wxWindow * parent)
Definition at line 1158 of file watchesdlg.cpp.
References wxBoxSizer::Add(), wxPropertyGrid::Append(), wxBoxSizer::Fit(), wxNativeFontInfo::FromString(), cbDebuggerCommonConfig::GetValueTooltipFont(), m_grid, m_panel, m_sizer, m_timer, m_watch, wxPropertyGrid::SetColumnCount(), SetMinSize(), wxTimer::Start(), UpdateWatch(), wxALL, wxBORDER_NONE, wxDefaultPosition, wxEXPAND, wxID_ANY, wxPG_EX_DISABLE_TLP_TRACKING, wxPG_SPLITTER_AUTO_CENTER, wxVERTICAL, and wxWANTS_CHARS.
~ValueTooltip()
ValueTooltip::~ValueTooltip ()
Definition at line 1201 of file watchesdlg.cpp.
References ClearWatch().
Member Function Documentation
ClearWatch()
void ValueTooltip::ClearWatch () private
Definition at line 1214 of file watchesdlg.cpp.
References cbDebuggerPlugin::DeleteWatch(), Manager::Get(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), and m_watch.
Referenced by Dismiss(), OnDismiss(), and ~ValueTooltip().
Dismiss()
void ValueTooltip::Dismiss ()
Definition at line 1225 of file watchesdlg.cpp.
References ClearWatch(), m_timer, and wxTimer::Stop().
Referenced by DebugInterfaceFactory::HideValueTooltip(), and OnTimer().
Fit()
void ValueTooltip::Fit () private
Definition at line 1237 of file watchesdlg.cpp.
References wxBoxSizer::Fit(), m_grid, m_panel, m_sizer, SetMinSize(), wxPoint::x, and wxPoint::y.
Referenced by OnCollapse(), OnExpand(), and UpdateWatch().
OnCollapse()
void ValueTooltip::OnCollapse (wxPropertyGridEvent & event) private
Definition at line 1246 of file watchesdlg.cpp.
References cbDebuggerPlugin::CollapseWatch(), Fit(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), and WatchesProperty::GetWatch().
Referenced by WatchesDlg::RefreshUI().
OnDismiss()
void ValueTooltip::OnDismiss () protected virtual
Definition at line 1232 of file watchesdlg.cpp.
References ClearWatch().
OnExpand()
void ValueTooltip::OnExpand (wxPropertyGridEvent & event) private
Definition at line 1257 of file watchesdlg.cpp.
References cbDebuggerPlugin::ExpandWatch(), Fit(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), and WatchesProperty::GetWatch().
Referenced by WatchesDlg::RefreshUI().
OnTimer()
void ValueTooltip::OnTimer (wxTimerEvent & event) private
Definition at line 1268 of file watchesdlg.cpp.
References wxRect::Contains(), Dismiss(), wxRect::Inflate(), wxApp::IsActive(), m_outsideCount, wxGetMousePosition(), and wxTheApp.
Referenced by WatchesDlg::RefreshUI().
UpdateWatch()
void ValueTooltip::UpdateWatch ()
Definition at line 1206 of file watchesdlg.cpp.
References Fit(), GetRealRoot(), m_grid, and m_watch.
Referenced by DebugInterfaceFactory::UpdateValueTooltip(), and ValueTooltip().
Member Data Documentation
m_grid
wxPropertyGrid* ValueTooltip::m_grid private
Definition at line 103 of file watchesdlg.h.
Referenced by Fit(), UpdateWatch(), and ValueTooltip().
m_outsideCount
int ValueTooltip::m_outsideCount private
Definition at line 108 of file watchesdlg.h.
Referenced by OnTimer().
m_panel
wxPanel* ValueTooltip::m_panel private
Definition at line 105 of file watchesdlg.h.
Referenced by Fit(), and ValueTooltip().
m_sizer
wxBoxSizer* ValueTooltip::m_sizer private
Definition at line 104 of file watchesdlg.h.
Referenced by Fit(), and ValueTooltip().
m_timer
wxTimer ValueTooltip::m_timer private
Definition at line 107 of file watchesdlg.h.
Referenced by Dismiss(), and ValueTooltip().
m_watch
cb::shared_ptr<cbWatch> ValueTooltip::m_watch private
Definition at line 110 of file watchesdlg.h.
Referenced by ClearWatch(), UpdateWatch(), and ValueTooltip().
The documentation for this class was generated from the following files:
watchesdlg.h
watchesdlg.cpp