Code::Blocks: CompilerMessages Class Reference
CompilerMessages Class Reference
#include <compilermessages.h>
Public Member Functions
CompilerMessages (const wxArrayString &titles, const wxArrayInt &widths)
virtual ~CompilerMessages ()
virtual void SetCompilerErrors (CompilerErrors *errors)
virtual void FocusError (int nr)
void AutoFitColumns (int column)
virtual wxWindow * CreateControl (wxWindow *parent)
void DestroyControls ()
virtual bool HasFeature (Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (wxMenu &menu)
Public Member Functions inherited from ListCtrlLogger
ListCtrlLogger (const wxArrayString &titles, const wxArrayInt &widths, bool fixedPitchFont=false)
~ListCtrlLogger ()
virtual void CopyContentsToClipboard (bool selectionOnly=false)
virtual void UpdateSettings ()
virtual void Append (const wxString &msg, Logger::level lv=info)
virtual void Append (const wxArrayString &colValues, Logger::level lv=info, int autoSize=-1)
virtual size_t GetItemsCount () const
virtual void Clear ()
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool GetWrapMode () const
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Private Member Functions
void OnClick (wxCommandEvent &event)
void OnDoubleClick (wxCommandEvent &event)
void OnFit (wxCommandEvent &event)
void OnAutoFit (wxCommandEvent &event)
void FitColumns ()
Private Attributes
CompilerErrors * m_pErrors
bool m_autoFit
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Protected Member Functions inherited from ListCtrlLogger
wxString GetItemAsText (long item) const
Protected Attributes inherited from ListCtrlLogger
wxListCtrl * control
bool fixed
wxArrayString titles
wxArrayInt widths
ListStyles style [num_levels]
Detailed Description
Definition at line 15 of file compilermessages.h.
Constructor & Destructor Documentation
CompilerMessages()
CompilerMessages::CompilerMessages (const wxArrayString & titles, const wxArrayInt & widths)
Definition at line 37 of file compilermessages.cpp.
References Manager::Get(), Manager::GetConfigManager(), ConfigManager::ReadBool(), and wxT.
~CompilerMessages()
CompilerMessages::~CompilerMessages () virtual
Definition at line 44 of file compilermessages.cpp.
References OnAutoFit(), OnClick(), OnDoubleClick(), and OnFit().
Member Function Documentation
AppendAdditionalMenuItems()
void CompilerMessages::AppendAdditionalMenuItems (wxMenu & menu) virtual
Definition at line 97 of file compilermessages.cpp.
References _(), wxMenu::Append(), wxMenu::AppendCheckItem(), wxMenu::Check(), and m_autoFit.
Referenced by SetCompilerErrors().
AutoFitColumns()
void CompilerMessages::AutoFitColumns (int column) virtual
Reimplemented from ListCtrlLogger.
Definition at line 149 of file compilermessages.cpp.
References FitColumns(), and m_autoFit.
Referenced by SetCompilerErrors().
CreateControl()
wxWindow * CompilerMessages::CreateControl (wxWindow * parent) virtual
Reimplemented from ListCtrlLogger.
Definition at line 61 of file compilermessages.cpp.
References ListCtrlLogger::control, ListCtrlLogger::CreateControl(), Manager::Get(), Manager::GetAppWindow(), OnAutoFit(), OnClick(), OnDoubleClick(), and OnFit().
Referenced by SetCompilerErrors().
DestroyControls()
void CompilerMessages::DestroyControls ()
Definition at line 81 of file compilermessages.cpp.
References Manager::Get(), and Manager::GetAppWindow().
Referenced by SetCompilerErrors().
FitColumns()
void CompilerMessages::FitColumns () private
Definition at line 155 of file compilermessages.cpp.
References ListCtrlLogger::control, wxListCtrl::GetColumnCount(), wxListCtrl::GetColumnWidth(), wxListCtrl::SetColumnWidth(), and wxLIST_AUTOSIZE.
Referenced by AutoFitColumns(), OnFit(), and SetCompilerErrors().
FocusError()
void CompilerMessages::FocusError (int nr) virtual
Definition at line 105 of file compilermessages.cpp.
References ListCtrlLogger::control, wxListCtrl::EnsureVisible(), wxListCtrl::GetItemCount(), wxListCtrl::SetItemState(), wxLIST_STATE_FOCUSED, and wxLIST_STATE_SELECTED.
Referenced by SetCompilerErrors().
HasFeature()
bool CompilerMessages::HasFeature (Feature::Enum feature) const virtual
Reimplemented from ListCtrlLogger.
Definition at line 89 of file compilermessages.cpp.
References Logger::Feature::Additional, and ListCtrlLogger::HasFeature().
Referenced by SetCompilerErrors().
OnAutoFit()
void CompilerMessages::OnAutoFit (wxCommandEvent & event) private
Definition at line 143 of file compilermessages.cpp.
References Manager::Get(), Manager::GetConfigManager(), m_autoFit, ConfigManager::Write(), and wxT.
Referenced by CreateControl(), SetCompilerErrors(), and ~CompilerMessages().
OnClick()
void CompilerMessages::OnClick (wxCommandEvent & event) private
Definition at line 113 of file compilermessages.cpp.
References ListCtrlLogger::control, wxListCtrl::GetNextItem(), wxListCtrl::GetSelectedItemCount(), CompilerErrors::GotoError(), m_pErrors, wxLIST_NEXT_ALL, and wxLIST_STATE_SELECTED.
Referenced by CreateControl(), OnDoubleClick(), SetCompilerErrors(), and ~CompilerMessages().
OnDoubleClick()
void CompilerMessages::OnDoubleClick (wxCommandEvent & event) private
Definition at line 131 of file compilermessages.cpp.
References OnClick().
Referenced by CreateControl(), SetCompilerErrors(), and ~CompilerMessages().
OnFit()
void CompilerMessages::OnFit (wxCommandEvent & event) private
Definition at line 138 of file compilermessages.cpp.
References FitColumns().
Referenced by CreateControl(), SetCompilerErrors(), and ~CompilerMessages().
SetCompilerErrors()
virtual void CompilerMessages::SetCompilerErrors (CompilerErrors * errors) inline virtual
Definition at line 20 of file compilermessages.h.
References AppendAdditionalMenuItems(), AutoFitColumns(), CreateControl(), DestroyControls(), FitColumns(), FocusError(), HasFeature(), m_pErrors, OnAutoFit(), OnClick(), OnDoubleClick(), and OnFit().
Member Data Documentation
m_autoFit
bool CompilerMessages::m_autoFit private
Definition at line 39 of file compilermessages.h.
Referenced by AppendAdditionalMenuItems(), AutoFitColumns(), and OnAutoFit().
m_pErrors
CompilerErrors* CompilerMessages::m_pErrors private
Definition at line 38 of file compilermessages.h.
Referenced by OnClick(), and SetCompilerErrors().
The documentation for this class was generated from the following files:
compilermessages.h
compilermessages.cpp