Code::Blocks: cbThreadsDlg Class Reference
cbThreadsDlg Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbThreadsDlg ()
virtual wxWindow * GetWindow ()=0
virtual void Reload ()=0
virtual void EnableWindow (bool enable)=0
Detailed Description
Definition at line 93 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
~cbThreadsDlg()
cbThreadsDlg::~cbThreadsDlg () virtual
Definition at line 19 of file cbdebugger_interfaces.cpp.
Member Function Documentation
EnableWindow()
virtual void cbThreadsDlg::EnableWindow (bool enable) pure virtual
Implemented in ThreadsDlg.
Referenced by DebuggerManager::RefreshUI(), and DebuggerManager::SetInterfaceFactory().
GetWindow()
virtual wxWindow* cbThreadsDlg::GetWindow () pure virtual
Implemented in ThreadsDlg.
Referenced by DebugInterfaceFactory::DeleteThreads(), and DebuggerManager::UpdateThreads().
Reload()
virtual void cbThreadsDlg::Reload () pure virtual
Implemented in ThreadsDlg.
Referenced by GdbCmd_Threads::ParseOutput().
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp