Code::Blocks: AdvancedCompilerOptionsDlg Class Reference
AdvancedCompilerOptionsDlg Class Reference
#include <advancedcompileroptionsdlg.h>
Public Member Functions
AdvancedCompilerOptionsDlg (wxWindow *parent, const wxString &compilerId)
virtual ~AdvancedCompilerOptionsDlg ()
bool IsDirty () const
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Private Member Functions
void OnCommandsChange (wxCommandEvent &event)
void OnExtChange (wxCommandEvent &event)
void OnAddExt (wxCommandEvent &event)
void OnDelExt (wxCommandEvent &event)
void OnRegexChange (wxCommandEvent &event)
void OnRegexTest (wxCommandEvent &event)
void OnRegexAdd (wxCommandEvent &event)
void OnRegexDelete (wxCommandEvent &event)
void OnRegexDefaults (wxCommandEvent &event)
void OnRegexUp (wxSpinEvent &event)
void OnRegexDown (wxSpinEvent &event)
void EndModal (int retCode)
void ReadCompilerOptions ()
void WriteCompilerOptions ()
void ReadExtensions (int nr)
void DisplayCommand (int cmd, int ext)
void CheckForChanges ()
CompilerTool * GetCompilerTool (int cmd, int ext)
void SaveCommands (int cmd, int ext)
void FillRegexes ()
void FillRegexDetails (int index)
void SaveRegexDetails (int index)
DECLARE_EVENT_TABLE ()
Private Attributes
wxString m_CompilerId
int m_LastCmdIndex
int m_LastExtIndex
RegExArray m_Regexes
int m_SelectedRegex
bool m_bDirty
Have changes being made to settings in the dialog.
CompilerToolsVector m_Commands [ctCount]
Detailed Description
Definition at line 16 of file advancedcompileroptionsdlg.h.
Constructor & Destructor Documentation
AdvancedCompilerOptionsDlg()
AdvancedCompilerOptionsDlg::AdvancedCompilerOptionsDlg (wxWindow * parent, const wxString & compilerId)
Definition at line 69 of file advancedcompileroptionsdlg.cpp.
References _T, wxXmlResource::Get(), and wxXmlResource::LoadObject().
~AdvancedCompilerOptionsDlg()
AdvancedCompilerOptionsDlg::~AdvancedCompilerOptionsDlg () virtual
Definition at line 83 of file advancedcompileroptionsdlg.cpp.
Member Function Documentation
CheckForChanges()
void AdvancedCompilerOptionsDlg::CheckForChanges () private
Definition at line 230 of file advancedcompileroptionsdlg.cpp.
References m_LastCmdIndex, m_LastExtIndex, and SaveCommands().
Referenced by EndModal(), IsDirty(), OnCommandsChange(), and OnExtChange().
DECLARE_EVENT_TABLE()
AdvancedCompilerOptionsDlg::DECLARE_EVENT_TABLE () private
DisplayCommand()
void AdvancedCompilerOptionsDlg::DisplayCommand (int cmd, int ext) private
Definition at line 212 of file advancedcompileroptionsdlg.cpp.
References _T, GetCompilerTool(), GetStringFromArray(), m_LastCmdIndex, and m_LastExtIndex.
Referenced by IsDirty(), OnAddExt(), OnCommandsChange(), OnDelExt(), OnExtChange(), and ReadCompilerOptions().
EndModal()
void AdvancedCompilerOptionsDlg::EndModal (int retCode) private
Definition at line 491 of file advancedcompileroptionsdlg.cpp.
References CheckForChanges(), ScriptBindings::EndModal(), CompilerFactory::GetCompiler(), m_bDirty, m_CompilerId, m_Regexes, m_SelectedRegex, SaveRegexDetails(), Compiler::SetRegExArray(), WriteCompilerOptions(), and wxID_OK.
Referenced by IsDirty().
FillRegexDetails()
void AdvancedCompilerOptionsDlg::FillRegexDetails (int index) private
Definition at line 267 of file advancedcompileroptionsdlg.cpp.
References _T, ControlCharsToString(), RegExStruct::desc, RegExStruct::filename, RegExStruct::GetRegExString(), RegExStruct::line, RegExStruct::lt, m_Regexes, and RegExStruct::msg.
Referenced by FillRegexes(), IsDirty(), and OnRegexChange().
FillRegexes()
void AdvancedCompilerOptionsDlg::FillRegexes () private
Definition at line 253 of file advancedcompileroptionsdlg.cpp.
References RegExStruct::desc, FillRegexDetails(), m_Regexes, and m_SelectedRegex.
Referenced by IsDirty(), OnRegexAdd(), OnRegexDefaults(), OnRegexDelete(), OnRegexDown(), OnRegexUp(), and ReadCompilerOptions().
GetCompilerTool()
CompilerTool * AdvancedCompilerOptionsDlg::GetCompilerTool (int cmd, int ext) private
Definition at line 197 of file advancedcompileroptionsdlg.cpp.
References wxChoice::GetString(), wxString::IsEmpty(), and m_Commands.
Referenced by DisplayCommand(), IsDirty(), OnAddExt(), and SaveCommands().
IsDirty()
bool AdvancedCompilerOptionsDlg::IsDirty () const inline
Definition at line 21 of file advancedcompileroptionsdlg.h.
References CheckForChanges(), DisplayCommand(), EndModal(), FillRegexDetails(), FillRegexes(), GetCompilerTool(), m_bDirty, OnAddExt(), OnCommandsChange(), OnDelExt(), OnExtChange(), OnRegexAdd(), OnRegexChange(), OnRegexDefaults(), OnRegexDelete(), OnRegexDown(), OnRegexTest(), OnRegexUp(), ReadCompilerOptions(), ReadExtensions(), SaveCommands(), SaveRegexDetails(), and WriteCompilerOptions().
Referenced by CompilerOptionsDlg::OnAdvancedClick().
OnAddExt()
void AdvancedCompilerOptionsDlg::OnAddExt (wxCommandEvent & event) private
Definition at line 326 of file advancedcompileroptionsdlg.cpp.
References _(), cbGetTextFromUser(), CompilerTool::command, DisplayCommand(), GetCompilerTool(), wxChoice::GetSelection(), wxString::IsEmpty(), m_Commands, ReadExtensions(), and wxString::Trim().
Referenced by IsDirty(), and StringToControlChars().
OnCommandsChange()
void AdvancedCompilerOptionsDlg::OnCommandsChange (wxCommandEvent & event) private
Definition at line 309 of file advancedcompileroptionsdlg.cpp.
References CheckForChanges(), DisplayCommand(), and ReadExtensions().
Referenced by IsDirty(), and StringToControlChars().
OnDelExt()
void AdvancedCompilerOptionsDlg::OnDelExt (wxCommandEvent & event) private
Definition at line 344 of file advancedcompileroptionsdlg.cpp.
References _(), _T, cbMessageBox(), DisplayCommand(), wxChoice::GetSelection(), wxString::IsEmpty(), m_Commands, m_LastExtIndex, ReadExtensions(), wxChoice::SetSelection(), wxICON_ERROR, wxID_YES, and wxYES_NO.
Referenced by IsDirty(), and StringToControlChars().
OnExtChange()
void AdvancedCompilerOptionsDlg::OnExtChange (wxCommandEvent & event) private
Definition at line 318 of file advancedcompileroptionsdlg.cpp.
References CheckForChanges(), and DisplayCommand().
Referenced by IsDirty(), and StringToControlChars().
OnRegexAdd()
void AdvancedCompilerOptionsDlg::OnRegexAdd (wxCommandEvent & event) private
Definition at line 383 of file advancedcompileroptionsdlg.cpp.
References _(), _T, cltError, FillRegexes(), m_Regexes, m_SelectedRegex, and SaveRegexDetails().
Referenced by IsDirty(), and StringToControlChars().
OnRegexChange()
void AdvancedCompilerOptionsDlg::OnRegexChange (wxCommandEvent & event) private
Definition at line 365 of file advancedcompileroptionsdlg.cpp.
References FillRegexDetails(), m_SelectedRegex, SaveRegexDetails(), and wxNOT_FOUND.
Referenced by IsDirty(), and StringToControlChars().
OnRegexDefaults()
void AdvancedCompilerOptionsDlg::OnRegexDefaults (wxCommandEvent & event) private
Definition at line 402 of file advancedcompileroptionsdlg.cpp.
References _(), cbMessageBox(), FillRegexes(), CompilerFactory::GetCompiler(), Compiler::GetRegExArray(), Compiler::LoadDefaultRegExArray(), m_CompilerId, m_Regexes, m_SelectedRegex, wxICON_QUESTION, wxID_YES, wxNO_DEFAULT, and wxYES_NO.
Referenced by IsDirty(), and StringToControlChars().
OnRegexDelete()
void AdvancedCompilerOptionsDlg::OnRegexDelete (wxCommandEvent & event) private
Definition at line 391 of file advancedcompileroptionsdlg.cpp.
References _(), cbMessageBox(), FillRegexes(), m_Regexes, m_SelectedRegex, wxICON_QUESTION, wxID_YES, wxNO_DEFAULT, and wxYES_NO.
Referenced by IsDirty(), and StringToControlChars().
OnRegexDown()
void AdvancedCompilerOptionsDlg::OnRegexDown (wxSpinEvent & event) private
Definition at line 434 of file advancedcompileroptionsdlg.cpp.
References FillRegexes(), m_Regexes, m_SelectedRegex, and SaveRegexDetails().
Referenced by IsDirty(), and StringToControlChars().
OnRegexTest()
void AdvancedCompilerOptionsDlg::OnRegexTest (wxCommandEvent & event) private
Definition at line 447 of file advancedcompileroptionsdlg.cpp.
References _(), cbMessageBox(), Compiler::CheckForWarningsAndErrors(), cltError, cltInfo, cltNormal, CompilerFactory::GetCompiler(), Compiler::GetLastError(), Compiler::GetLastErrorFilename(), Compiler::GetLastErrorLine(), wxString::IsEmpty(), m_CompilerId, m_Regexes, m_SelectedRegex, wxString::Printf(), SaveRegexDetails(), Compiler::SetRegExArray(), wxString::wx_str(), wxICON_ERROR, and wxICON_INFORMATION.
Referenced by IsDirty(), and StringToControlChars().
OnRegexUp()
void AdvancedCompilerOptionsDlg::OnRegexUp (wxSpinEvent & event) private
Definition at line 421 of file advancedcompileroptionsdlg.cpp.
References FillRegexes(), m_Regexes, m_SelectedRegex, and SaveRegexDetails().
Referenced by IsDirty(), and StringToControlChars().
ReadCompilerOptions()
void AdvancedCompilerOptionsDlg::ReadCompilerOptions () private
Definition at line 88 of file advancedcompileroptionsdlg.cpp.
References Compiler::CommandTypeDescriptions, ctCount, CompilerSwitches::defines, DisplayCommand(), FillRegexes(), CompilerSwitches::forceCompilerUseQuotes, CompilerSwitches::forceFwdSlashes, CompilerSwitches::forceLinkerUseQuotes, CompilerSwitches::genericSwitch, Compiler::GetCommandToolsVector(), CompilerFactory::GetCompiler(), Compiler::GetRegExArray(), Compiler::GetSwitches(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, CompilerSwitches::libDirs, CompilerSwitches::libDirSeparator, CompilerSwitches::libExtension, CompilerSwitches::libPrefix, CompilerSwitches::linkerNeedsLibExtension, CompilerSwitches::linkerNeedsLibPrefix, CompilerSwitches::linkerNeedsPathResolved, CompilerSwitches::linkLibs, m_Commands, m_CompilerId, m_Regexes, m_SelectedRegex, CompilerSwitches::needDependencies, CompilerSwitches::objectExtension, CompilerSwitches::objectSeparator, CompilerSwitches::PCHExtension, ReadExtensions(), wxChoice::SetSelection(), CompilerSwitches::statusSuccess, CompilerSwitches::supportsPCH, CompilerSwitches::Use83Paths, CompilerSwitches::UseFlatObjects, and CompilerSwitches::UseFullSourcePaths.
Referenced by IsDirty().
ReadExtensions()
void AdvancedCompilerOptionsDlg::ReadExtensions (int nr) private
Definition at line 188 of file advancedcompileroptionsdlg.cpp.
References DEFAULT_ARRAY_SEP, wxChoice::FindString(), GetStringFromArray(), m_Commands, wxChoice::SetSelection(), and wxEmptyString.
Referenced by IsDirty(), OnAddExt(), OnCommandsChange(), OnDelExt(), and ReadCompilerOptions().
SaveCommands()
void AdvancedCompilerOptionsDlg::SaveCommands (int cmd, int ext) private
Definition at line 237 of file advancedcompileroptionsdlg.cpp.
References _T, GetArrayFromString(), GetCompilerTool(), and GetStringFromArray().
Referenced by CheckForChanges(), and IsDirty().
SaveRegexDetails()
void AdvancedCompilerOptionsDlg::SaveRegexDetails (int index) private
Definition at line 293 of file advancedcompileroptionsdlg.cpp.
References RegExStruct::desc, RegExStruct::filename, RegExStruct::line, RegExStruct::lt, m_Regexes, RegExStruct::msg, RegExStruct::SetRegExString(), and StringToControlChars().
Referenced by EndModal(), IsDirty(), OnRegexAdd(), OnRegexChange(), OnRegexDown(), OnRegexTest(), and OnRegexUp().
WriteCompilerOptions()
void AdvancedCompilerOptionsDlg::WriteCompilerOptions () private
Definition at line 137 of file advancedcompileroptionsdlg.cpp.
References ctCount, CompilerSwitches::defines, CompilerSwitches::forceCompilerUseQuotes, CompilerSwitches::forceFwdSlashes, CompilerSwitches::forceLinkerUseQuotes, CompilerSwitches::genericSwitch, Compiler::GetCommandToolsVector(), CompilerFactory::GetCompiler(), CompilerSwitches::includeDirs, CompilerSwitches::includeDirSeparator, wxString::IsEmpty(), CompilerSwitches::libDirs, CompilerSwitches::libDirSeparator, CompilerSwitches::libExtension, CompilerSwitches::libPrefix, CompilerSwitches::linkerNeedsLibExtension, CompilerSwitches::linkerNeedsLibPrefix, CompilerSwitches::linkerNeedsPathResolved, CompilerSwitches::linkLibs, m_Commands, m_CompilerId, CompilerSwitches::needDependencies, CompilerSwitches::objectExtension, CompilerSwitches::objectSeparator, CompilerSwitches::PCHExtension, Compiler::SetSwitches(), CompilerSwitches::statusSuccess, CompilerSwitches::supportsPCH, CompilerSwitches::Use83Paths, CompilerSwitches::UseFlatObjects, and CompilerSwitches::UseFullSourcePaths.
Referenced by EndModal(), and IsDirty().
Member Data Documentation
m_bDirty
bool AdvancedCompilerOptionsDlg::m_bDirty private
Have changes being made to settings in the dialog.
Definition at line 54 of file advancedcompileroptionsdlg.h.
Referenced by EndModal(), and IsDirty().
m_Commands
CompilerToolsVector AdvancedCompilerOptionsDlg::m_Commands[ctCount] private
Definition at line 55 of file advancedcompileroptionsdlg.h.
Referenced by GetCompilerTool(), OnAddExt(), OnDelExt(), ReadCompilerOptions(), ReadExtensions(), and WriteCompilerOptions().
m_CompilerId
wxString AdvancedCompilerOptionsDlg::m_CompilerId private
Definition at line 49 of file advancedcompileroptionsdlg.h.
Referenced by EndModal(), OnRegexDefaults(), OnRegexTest(), ReadCompilerOptions(), and WriteCompilerOptions().
m_LastCmdIndex
int AdvancedCompilerOptionsDlg::m_LastCmdIndex private
Definition at line 50 of file advancedcompileroptionsdlg.h.
Referenced by CheckForChanges(), and DisplayCommand().
m_LastExtIndex
int AdvancedCompilerOptionsDlg::m_LastExtIndex private
Definition at line 51 of file advancedcompileroptionsdlg.h.
Referenced by CheckForChanges(), DisplayCommand(), and OnDelExt().
m_Regexes
RegExArray AdvancedCompilerOptionsDlg::m_Regexes private
Definition at line 52 of file advancedcompileroptionsdlg.h.
Referenced by EndModal(), FillRegexDetails(), FillRegexes(), OnRegexAdd(), OnRegexDefaults(), OnRegexDelete(), OnRegexDown(), OnRegexTest(), OnRegexUp(), ReadCompilerOptions(), and SaveRegexDetails().
m_SelectedRegex
int AdvancedCompilerOptionsDlg::m_SelectedRegex private
Definition at line 53 of file advancedcompileroptionsdlg.h.
Referenced by EndModal(), FillRegexes(), OnRegexAdd(), OnRegexChange(), OnRegexDefaults(), OnRegexDelete(), OnRegexDown(), OnRegexTest(), OnRegexUp(), and ReadCompilerOptions().
The documentation for this class was generated from the following files:
advancedcompileroptionsdlg.h
advancedcompileroptionsdlg.cpp