Code::Blocks: IncrementalSelectIterator Class Reference
IncrementalSelectIterator Class Reference abstract
#include <incremental_select_helper.h>
Public Member Functions
virtual ~IncrementalSelectIterator ()
virtual int GetFilteredCount () const =0
virtual void Reset ()=0
virtual void AddIndex (int index)=0
virtual int GetUnfilteredIndex (int index) const =0
virtual int GetTotalCount () const =0
virtual const wxString & GetItemFilterString (int index) const =0
virtual wxString GetDisplayText (int index, int column) const =0
virtual int GetColumnWidth (int column) const
virtual void CalcColumnWidth (wxListCtrl &list)
Detailed Description
Definition at line 26 of file incremental_select_helper.h.
Constructor & Destructor Documentation
~IncrementalSelectIterator()
IncrementalSelectIterator::~IncrementalSelectIterator () virtual
Definition at line 18 of file incremental_select_helper.cpp.
Member Function Documentation
AddIndex()
virtual void IncrementalSelectIterator::AddIndex (int index) pure virtual
Implemented in IncrementalSelectIteratorIndexed.
Referenced by IncrementalSelectHandler::FilterItems(), and IncrementalSelectIteratorIndexed::~IncrementalSelectIteratorIndexed().
CalcColumnWidth()
void IncrementalSelectIterator::CalcColumnWidth (wxListCtrl & list) virtual
Reimplemented in IncrementalSelectArrayIterator, and GotoFunctionDlg::Iterator.
Definition at line 27 of file incremental_select_helper.cpp.
Referenced by IncrementalSelectHandler::Init().
GetColumnWidth()
int IncrementalSelectIterator::GetColumnWidth (int column) const virtual
Reimplemented in IncrementalSelectArrayIterator, and GotoFunctionDlg::Iterator.
Definition at line 22 of file incremental_select_helper.cpp.
References wxLIST_AUTOSIZE.
Referenced by FilterItemsFinalize().
GetDisplayText()
virtual wxString IncrementalSelectIterator::GetDisplayText (int index, int column) const pure virtual
Implemented in IncrementalSelectArrayIterator, and GotoFunctionDlg::Iterator.
Referenced by IncrementalListCtrl::OnGetItemText().
GetFilteredCount()
virtual int IncrementalSelectIterator::GetFilteredCount () const pure virtual
Implemented in IncrementalSelectIteratorIndexed.
Referenced by FilterItemsFinalize(), and IncrementalSelectIteratorIndexed::~IncrementalSelectIteratorIndexed().
GetItemFilterString()
virtual const wxString& IncrementalSelectIterator::GetItemFilterString (int index) const pure virtual
Implemented in IncrementalSelectArrayIterator, and GotoFunctionDlg::Iterator.
Referenced by IncrementalSelectHandler::FilterItems().
GetTotalCount()
virtual int IncrementalSelectIterator::GetTotalCount () const pure virtual
Implemented in IncrementalSelectArrayIterator, and GotoFunctionDlg::Iterator.
Referenced by IncrementalSelectHandler::FilterItems().
GetUnfilteredIndex()
virtual int IncrementalSelectIterator::GetUnfilteredIndex (int index) const pure virtual
Implemented in IncrementalSelectIteratorIndexed.
Referenced by IncrementalSelectHandler::GetSelection(), and IncrementalSelectIteratorIndexed::~IncrementalSelectIteratorIndexed().
Reset()
virtual void IncrementalSelectIterator::Reset () pure virtual
Implemented in IncrementalSelectIteratorIndexed.
Referenced by IncrementalSelectHandler::FilterItems(), and IncrementalSelectIteratorIndexed::~IncrementalSelectIteratorIndexed().
The documentation for this class was generated from the following files:
incremental_select_helper.h
incremental_select_helper.cpp