Code::Blocks: CdbCmd_InfoRegisters Class Reference
CdbCmd_InfoRegisters Class Reference
#include <cdb_commands.h>
Public Member Functions
CdbCmd_InfoRegisters (DebuggerDriver *driver)
void ParseOutput (const wxString &output)
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
virtual bool IsContinueCommand () const
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to run a disassembly. Use this instead of CdbCmd_DisassemblyInit, which is chained-called.
Constructor & Destructor Documentation
CdbCmd_InfoRegisters::CdbCmd_InfoRegisters (DebuggerDriver * driver) inline
Parameters
dlg The disassembly dialog.
References DebuggerCmd::m_Cmd.
Member Function Documentation
void CdbCmd_InfoRegisters::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
References Manager::Get(), GetArrayFromString(), DebuggerManager::GetCPURegistersDialog(), Manager::GetDebuggerManager(), and cbCPURegistersDlg::SetRegisterValue().
The documentation for this class was generated from the following file:
cdb_commands.h