Code::Blocks: CCManager Class Reference
CCManager Class Reference
Code Completion Plugin Manager.
#include <ccmanager.h>
Public Member Functions
cbCodeCompletionPlugin * GetProviderFor (cbEditor *ed=nullptr)
Get the ccPlugin instant for the cbEditor.
void RegisterCallTipChars (const wxString &chars, cbCodeCompletionPlugin *registrant)
Register a new set of characters that, when typed, invoke calltip requests.
void RegisterAutoLaunchChars (const wxString &chars, cbCodeCompletionPlugin *registrant)
Register a new set of characters that, when typed, auto-launch codecomplete requests.
void NotifyDocumentation ()
Let CCManager know that new results are available from cbCodeCompletionPlugin::GetDocumentation().
void NotifyPluginStatus ()
Let CCManager know that a change (e.g.
void InjectAutoCompShow (int lenEntered, const wxString &itemList)
If for some reason you need to use wxScintilla::AutoCompShow(), call this instead so CCManager does not step on you.
bool ProcessArrow (int key)
Used by cbStyledTextCtrl to process ArrowUp and ArrowDown key press.
void UpdateEnvSettings ()
Called after env settings have changed, so the changes can be applied.
Private Types
enum Direction { Previous, Next }
User click the next or previous small button of the tip window.
typedef std::map< cbCodeCompletionPlugin *, std::set< wxChar > > CCPluginCharMap
typedef std::vector< cbCodeCompletionPlugin::CCCallTip > CallTipVec
Private Member Functions
CCManager ()
~CCManager ()
void OnCompleteCode (CodeBlocksEvent &event)
Event handler to list the suggestion, when a user press Ctrl-space (by default).
void OnDeactivateApp (CodeBlocksEvent &event)
Event handler to avoid tooltips getting stuck active.
void OnDeactivateEd (CodeBlocksEvent &event)
Event handler to avoid tooltips getting stuck active.
void OnEditorOpen (CodeBlocksEvent &event)
Event handler to avoid tooltips getting stuck active.
void OnEditorClose (CodeBlocksEvent &event)
Event handler to avoid tooltips getting stuck active.
void OnEditorHook (cbEditor *ed, wxScintillaEvent &event)
Hook to the editor.
void OnEditorTooltip (CodeBlocksEvent &event)
Mouse hover event.
void OnShowCallTip (CodeBlocksEvent &event)
Event handler to show the call tip, when user press Ctrl-Shift-Space.
void OnAutocompleteSelect (wxListEvent &event)
Event handler to show documentation, when user changes autocomplete selection.
void OnAutocompleteHide (wxShowEvent &event)
Event handler to tear down documentation, when autocomplete closes.
void OnDeferredCallTipShow (wxCommandEvent &event)
Defer showing the calltip to avoid a crash issue.
void OnDeferredCallTipCancel (wxCommandEvent &event)
Defer canceling the calltip to avoid a crash issue.
void OnPopupScroll (wxMouseEvent &event)
Intercept cbStyledTextCtrl scroll events and forward to autocomplete/documentation popups.
void OnHtmlLink (wxHtmlLinkEvent &event)
A link is clicked in the document window.
void OnTimer (wxTimerEvent &event)
Grouped event handler for several timers.
void OnMenuSelect (wxCommandEvent &event)
Handle the CC related menu click.
void DoBufferedCC (cbStyledTextCtrl *stc)
CC launched in the same state as last run, display via cached data.
void DoHidePopup ()
Hide the documentation popup.
void DoShowDocumentation (cbEditor *ed)
Show the documentation popup.
void DoUpdateCallTip (cbEditor *ed)
Update which tip to show next and where to show it.
void AdvanceTip (Direction direction)
Switch the tip window to the next item.
void DoShowTips (const wxStringVec &tips, cbStyledTextCtrl *stc, int pos, int argsPos, int hlStart, int hlEnd)
Format tips by breaking long lines at (hopefully) logical places.
void CallSmartIndentCCDone (cbEditor *ed)
Code completion as just insert some text in the editor, ask the smart indent plugin to adjust the indent.
Private Attributes
CCPluginCharMap m_CallTipChars
Chars each plugin is interested in for calltip state.
CCPluginCharMap m_AutoLaunchChars
Chars each plugin is interested in for autocomplete.
int m_EditorHookID
int m_AutocompPosition
Location of caret when autocomplete timer starts, if caret is still there, launch autocomplete.
int m_CallTipActive
Is CCManager currently displaying a calltip, and if so, where.
int m_LastAutocompIndex
Index of currently selected entry in autocomplete popup.
int m_LastTipPos
Last location a tool/call tip was displayed.
int m_WindowBound
Right-most boundary the documentation popup is allowed to stretch to.
bool m_OwnsAutocomp
Do we control the current autocomplete popup?
CallTipVec m_CallTips
Cached calltips.
CallTipVec::const_iterator m_CurCallTip
Remember current choice.
std::map< int, size_t > m_CallTipChoiceDict
Remember past choices.
std::map< int, size_t > m_CallTipFuzzyChoiceDict
Remember past choices based on prefix.
wxTimer m_CallTipTimer
wxTimer m_AutoLaunchTimer
wxTimer m_AutocompSelectTimer
wxSize m_DocSize
Size of the documentation popup.
wxPoint m_DocPos
Location of the documentation popup.
wxListView * m_pAutocompPopup
cbEditor * m_pLastEditor
Last editor operated on.
cbCodeCompletionPlugin * m_pLastCCPlugin
The plugin handling m_pLastEditor.
UnfocusablePopupWindow * m_pPopup
Container for documentation popup.
wxHtmlWindow * m_pHtml
Documentation popup.
int m_LastACLaunchState [2]
std::vector< cbCodeCompletionPlugin::CCToken > m_AutocompTokens
Cached autocomplete list.
Friends
class Mgr< CCManager >
class Manager
Additional Inherited Members
Static Public Member Functions inherited from Mgr< CCManager >
static bool Valid ()
static CCManager * Get ()
static void Free ()
Protected Member Functions inherited from Mgr< CCManager >
Mgr ()
virtual ~Mgr ()
Detailed Description
Code Completion Plugin Manager.
This class manages all kinds of code completion plugins. For example, the native C/C++ code completion plugin, the Fortran code completion plugin and Python code completion plugin. The ccmanager asks some informations from the managed ccplugins. The major value passes from the ccmanager and the ccplugins are CCCallTip and CCToken.
The CCToken is needed when ccmanager needs to fill a code suggestion list, it is the ccplugin's duty to supply a collection of CCTokens.
When user is entering some function call statement, CCCallTip is used to show the function information, and especially it can highlight the current function argument.
Another kind of tip is the tooltip, this is the tip window shown when mouse hover on a specified token(such as variable token), ccmanager queries this information by asking CCToken information from ccplugin.
Definition at line 40 of file ccmanager.h.
Member Typedef Documentation
CallTipVec
typedef std::vector<cbCodeCompletionPlugin::CCCallTip> CCManager::CallTipVec private
Definition at line 172 of file ccmanager.h.
CCPluginCharMap
typedef std::map< cbCodeCompletionPlugin*, std::set<wxChar> > CCManager::CCPluginCharMap private
Definition at line 162 of file ccmanager.h.
Member Enumeration Documentation
Direction
enum CCManager::Direction private
User click the next or previous small button of the tip window.
Enumerator
Previous
Next
Definition at line 151 of file ccmanager.h.
Constructor & Destructor Documentation
CCManager()
CCManager::CCManager () private
Definition at line 257 of file ccmanager.cpp.
References _(), wxString::begin(), CCManagerHelper::BuildFontSizes(), cbEVT_APP_DEACTIVATED, cbEVT_COMPLETE_CODE, cbEVT_EDITOR_CLOSE, cbEVT_EDITOR_DEACTIVATED, cbEVT_EDITOR_OPEN, cbEVT_EDITOR_TOOLTIP, cbEVT_SHOW_CALL_TIP, wxString::end(), wxMenuBar::FindMenu(), Manager::Get(), Manager::GetAppFrame(), Manager::GetColourManager(), CCManagerHelper::GetDefaultHTMLFontSize(), wxMenuBar::GetMenu(), wxMenu::GetMenuItems(), idCallTipNext, idCallTipPrevious, idShowTooltip, wxMenu::Insert(), lsCaretStart, OnCompleteCode(), OnDeactivateApp(), OnDeactivateEd(), OnDeferredCallTipCancel(), OnDeferredCallTipShow(), OnEditorClose(), OnEditorHook(), OnEditorOpen(), OnEditorTooltip(), OnHtmlLink(), OnMenuSelect(), OnShowCallTip(), OnTimer(), ColourManager::RegisterColour(), Manager::RegisterEventSink(), EditorHooks::RegisterHook(), wxBORDER_SIMPLE, wxDefaultPosition, wxDefaultSize, wxEmptyString, wxEVT_TIMER, wxHW_SCROLLBAR_AUTO, wxID_ANY, wxSCI_INVALID_POSITION, wxT, and wxWHITE.
~CCManager()
CCManager::~CCManager () private
Definition at line 339 of file ccmanager.cpp.
References Manager::Get(), Manager::GetAppFrame(), idCallTipNext, idCallTipPrevious, idShowTooltip, OnHtmlLink(), OnMenuSelect(), Manager::RemoveAllEventSinksFor(), and EditorHooks::UnregisterHook().
Member Function Documentation
AdvanceTip()
void CCManager::AdvanceTip (Direction direction) private
Switch the tip window to the next item.
Definition at line 421 of file ccmanager.cpp.
CallSmartIndentCCDone()
void CCManager::CallSmartIndentCCDone (cbEditor * ed) private
Code completion as just insert some text in the editor, ask the smart indent plugin to adjust the indent.
Definition at line 1430 of file ccmanager.cpp.
References cbEVT_EDITOR_CC_DONE, Manager::Get(), and Manager::ProcessEvent().
DoBufferedCC()
void CCManager::DoBufferedCC (cbStyledTextCtrl * stc) private
CC launched in the same state as last run, display via cached data.
Definition at line 1219 of file ccmanager.cpp.
References wxString::Alloc(), wxScintilla::AutoCompActive(), wxScintilla::AutoCompSelect(), wxScintilla::AutoCompShow(), wxScintilla::CallTipActive(), cbCodeCompletionPlugin::CCToken::displayName, F(), wxString::Find(), lsCaretStart, lsTknStart, wxString::Mid(), wxString::RemoveLast(), and wxT.
DoHidePopup()
void CCManager::DoHidePopup () private
Hide the documentation popup.
Definition at line 1253 of file ccmanager.cpp.
References OnPopupScroll(), and wxEVT_MOUSEWHEEL.
DoShowDocumentation()
void CCManager::DoShowDocumentation (cbEditor * ed) private
Show the documentation popup.
Definition at line 1264 of file ccmanager.cpp.
References Manager::Get(), cbEditor::GetControl(), cbCodeCompletionPlugin::GetDocumentation(), wxString::IsEmpty(), OnPopupScroll(), wxEVT_MOUSEWHEEL, and wxT.
DoShowTips()
void CCManager::DoShowTips (const wxStringVec & tips, cbStyledTextCtrl * stc, int pos, int argsPos, int hlStart, int hlEnd) private
Format tips by breaking long lines at (hopefully) logical places.
Definition at line 1348 of file ccmanager.cpp.
References wxScintilla::CallTipActive(), cbStyledTextCtrl::CallTipCancel(), wxScintilla::CallTipSetHighlight(), wxScintilla::CallTipShow(), wxString::Clear(), wxString::Find(), CCManagerHelper::FindColumn(), wxScintilla::GetColumn(), wxScintilla::GetLineEndPosition(), wxScintilla::GetMarginWidth(), wxString::IsEmpty(), wxString::Length(), wxScintilla::LineFromPosition(), wxScintilla::LinesOnScreen(), wxString::Mid(), wxScintilla::PointFromPosition(), wxScintilla::PositionFromLine(), wxScintilla::PositionFromPoint(), CCManagerHelper::RipplePts(), wxScintilla::TextWidth(), wxString::Trim(), wxScintilla::WordStartPosition(), wxSCI_MARGIN_NUMBER, wxSCI_MARGIN_SYMBOL, wxSCI_STYLE_LINENUMBER, wxT, and wxPoint::y.
DoUpdateCallTip()
void CCManager::DoUpdateCallTip (cbEditor * ed) private
Update which tip to show next and where to show it.
Definition at line 1299 of file ccmanager.cpp.
References wxString::begin(), CCManagerHelper::CallTipToInt(), wxScintilla::GetCharAt(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), wxScintilla::GetTextRange(), wxScintilla::LineFromPosition(), wxString::npos, wxScintilla::PositionFromLine(), CCManagerHelper::RipplePts(), wxString::size(), wxScintilla::WordStartPosition(), wxIsspace(), wxSCI_INVALID_POSITION, and wxT.
GetProviderFor()
cbCodeCompletionPlugin * CCManager::GetProviderFor (cbEditor * ed = nullptr)
Get the ccPlugin instant for the cbEditor.
If the editor opened a c/c++ file, then it returns the native c/c++ ccPlugin.
Parameters
ed input editor, uses active editor if one is not passed; has (minimal) cache optimization
Definition at line 358 of file ccmanager.cpp.
References cbCodeCompletionPlugin::ccpsActive, cbCodeCompletionPlugin::ccpsUniversal, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), PluginManager::GetCodeCompletionOffers(), Manager::GetEditorManager(), Manager::GetPluginManager(), lsCaretStart, and wxSCI_INVALID_POSITION.
InjectAutoCompShow()
void CCManager::InjectAutoCompShow (int lenEntered, const wxString & itemList)
If for some reason you need to use wxScintilla::AutoCompShow(), call this instead so CCManager does not step on you.
Definition at line 408 of file ccmanager.cpp.
References wxScintilla::AutoCompShow(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), and Manager::GetEditorManager().
NotifyDocumentation()
void CCManager::NotifyDocumentation ()
Let CCManager know that new results are available from cbCodeCompletionPlugin::GetDocumentation().
Definition at line 395 of file ccmanager.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), and Manager::GetEditorManager().
NotifyPluginStatus()
void CCManager::NotifyPluginStatus ()
Let CCManager know that a change (e.g.
active lexer is switched) may invalidate cached active ccPlugin.
Definition at line 402 of file ccmanager.cpp.
Referenced by PluginsConfigurationDlg::EndModal(), and MainFrame::OnEditHighlightMode().
OnAutocompleteHide()
void CCManager::OnAutocompleteHide (wxShowEvent & event) private
Event handler to tear down documentation, when autocomplete closes.
Definition at line 1089 of file ccmanager.cpp.
References CALLTIP_REFRESH_DELAY, wxEVT_SHOW, and wxTIMER_ONE_SHOT.
Referenced by OnAutocompleteSelect().
OnAutocompleteSelect()
void CCManager::OnAutocompleteSelect (wxListEvent & event) private
Event handler to show documentation, when user changes autocomplete selection.
Definition at line 1044 of file ccmanager.cpp.
References AUTOCOMP_SELECT_DELAY, wxScintilla::AutoCompGetMaxHeight(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentLine(), Manager::GetEditorManager(), wxDisplay::GetFromWindow(), OnAutocompleteHide(), wxScintilla::TextHeight(), wxRect::width, wxEVT_SHOW, wxTIMER_ONE_SHOT, wxPoint::x, and wxPoint::y.
Referenced by OnEditorClose(), and OnEditorOpen().
OnCompleteCode()
void CCManager::OnCompleteCode (CodeBlocksEvent & event) private
Event handler to list the suggestion, when a user press Ctrl-space (by default).
Definition at line 490 of file ccmanager.cpp.
References wxString::Alloc(), wxScintilla::AutoCompActive(), wxScintilla::AutoCompSelect(), wxScintilla::AutoCompSetIgnoreCase(), wxScintilla::AutoCompSetMaxHeight(), wxScintilla::AutoCompSetOrder(), wxScintilla::AutoCompSetSeparator(), wxScintilla::AutoCompSetTypeSeparator(), wxScintilla::AutoCompShow(), wxScintilla::CallTipActive(), F(), FROM_TIMER, Manager::Get(), cbCodeCompletionPlugin::GetAutocompList(), EditorManager::GetBuiltinActiveEditor(), Manager::GetConfigManager(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), wxScintilla::GetTextRange(), lsCaretStart, lsTknStart, ConfigManager::ReadBool(), wxString::RemoveLast(), wxScintillaEvent::SetText(), wxScintilla::WordEndPosition(), wxScintilla::WordStartPosition(), wxSCI_ORDER_CUSTOM, wxSCI_ORDER_PRESORTED, and wxT.
Referenced by CCManager().
OnDeactivateApp()
void CCManager::OnDeactivateApp (CodeBlocksEvent & event) private
Event handler to avoid tooltips getting stuck active.
Definition at line 584 of file ccmanager.cpp.
References wxScintilla::CallTipActive(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), and wxSCI_INVALID_POSITION.
Referenced by CCManager().
OnDeactivateEd()
void CCManager::OnDeactivateEd (CodeBlocksEvent & event) private
Event handler to avoid tooltips getting stuck active.
Definition at line 604 of file ccmanager.cpp.
References wxScintilla::CallTipActive(), cbStyledTextCtrl::CallTipCancel(), Manager::Get(), EditorManager::GetBuiltinEditor(), cbEditor::GetControl(), CodeBlocksEvent::GetEditor(), Manager::GetEditorManager(), and wxSCI_INVALID_POSITION.
Referenced by CCManager().
OnDeferredCallTipCancel()
void CCManager::OnDeferredCallTipCancel (wxCommandEvent & event) private
Defer canceling the calltip to avoid a crash issue.
See also
CCManager::OnDeferredCallTipShow
Definition at line 1112 of file ccmanager.cpp.
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), and Manager::GetEditorManager().
Referenced by CCManager().
OnDeferredCallTipShow()
void CCManager::OnDeferredCallTipShow (wxCommandEvent & event) private
Defer showing the calltip to avoid a crash issue.
Launching this event directly seems to be a candidate for race condition and crash in OnShowCallTip() so we attempt to serialize it.
Definition at line 1101 of file ccmanager.cpp.
References cbEVT_SHOW_CALL_TIP, Manager::Get(), and Manager::ProcessEvent().
Referenced by CCManager().
OnEditorClose()
void CCManager::OnEditorClose (CodeBlocksEvent & event) private
Event handler to avoid tooltips getting stuck active.
Definition at line 655 of file ccmanager.cpp.
References Manager::Get(), EditorManager::GetBuiltinEditor(), cbEditor::GetControl(), CodeBlocksEvent::GetEditor(), Manager::GetEditorManager(), and OnAutocompleteSelect().
Referenced by CCManager().
OnEditorHook()
void CCManager::OnEditorHook (cbEditor * ed, wxScintillaEvent & event) private
Hook to the editor.
This is used so that we know some specific chars were entered, then we can decide whether it time to show a calltip or suggestion list.
Definition at line 767 of file ccmanager.cpp.
References wxScintilla::AutoCompActive(), wxScintilla::AutoCompCancel(), CALLTIP_REFRESH_DELAY, wxScintilla::CallTipActive(), cbEVT_COMPLETE_CODE, cbCodeCompletionPlugin::DoAutocomplete(), Manager::Get(), Manager::GetConfigManager(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), wxScintillaEvent::GetKey(), wxScintillaEvent::GetModificationType(), wxScintillaEvent::GetPosition(), wxScintillaEvent::GetText(), wxScintillaEvent::GetUpdated(), CCManagerHelper::IsPosVisible(), Manager::ProcessEvent(), ConfigManager::ReadInt(), SCROLL_REFRESH_DELAY, wxScintilla::WordStartPosition(), wxSCI_INVALID_POSITION, wxSCI_KEY_DOWN, wxSCI_KEY_LEFT, wxSCI_KEY_RIGHT, wxSCI_KEY_UP, wxSCI_PERFORMED_UNDO, wxSCI_UPDATE_H_SCROLL, wxSCI_UPDATE_V_SCROLL, wxT, and wxTIMER_ONE_SHOT.
Referenced by CCManager().
OnEditorOpen()
void CCManager::OnEditorOpen (CodeBlocksEvent & event) private
Event handler to avoid tooltips getting stuck active.
Definition at line 627 of file ccmanager.cpp.
References Manager::Get(), EditorManager::GetBuiltinEditor(), cbEditor::GetControl(), CodeBlocksEvent::GetEditor(), Manager::GetEditorManager(), OnAutocompleteSelect(), and setupColours().
Referenced by CCManager().
OnEditorTooltip()
void CCManager::OnEditorTooltip (CodeBlocksEvent & event) private
Mouse hover event.
Definition at line 670 of file ccmanager.cpp.
References wxScintilla::CallTipActive(), Manager::Get(), cbCodeCompletionPlugin::GetCallTips(), Manager::GetConfigManager(), cbEditor::GetControl(), wxScintilla::GetLength(), cbEditor::GetLineIndentString(), wxScintilla::GetTextRange(), cbCodeCompletionPlugin::GetTokenAt(), CodeBlocksEvent::GetX(), EditorBase::IsBuiltinEditor(), cbStyledTextCtrl::IsCharacter(), cbStyledTextCtrl::IsComment(), EditorBase::IsContextMenuOpened(), cbStyledTextCtrl::IsPreprocessor(), cbStyledTextCtrl::IsString(), wxString::Length(), wxScintilla::LineFromPosition(), wxString::npos, wxScintilla::PositionFromLine(), wxScintilla::PositionFromPointClose(), ConfigManager::ReadInt(), wxScintilla::WordEndPosition(), wxScintilla::WordStartPosition(), wxGetKeyState(), wxIsalpha(), WXK_CONTROL, wxSCI_INVALID_POSITION, and wxT.
Referenced by CCManager().
OnHtmlLink()
void CCManager::OnHtmlLink (wxHtmlLinkEvent & event) private
A link is clicked in the document window.
Definition at line 1132 of file ccmanager.cpp.
References wxString::IsEmpty(), and cbCodeCompletionPlugin::OnDocumentationLink().
Referenced by CCManager(), and ~CCManager().
OnMenuSelect()
void CCManager::OnMenuSelect (wxCommandEvent & event) private
Handle the CC related menu click.
Definition at line 1183 of file ccmanager.cpp.
References wxScintilla::CallTipActive(), cbEVT_EDITOR_TOOLTIP, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), wxScintilla::GetStyleAt(), idCallTipNext, idCallTipPrevious, idShowTooltip, wxScintilla::PointFromPosition(), Manager::ProcessEvent(), CodeBlocksEvent::SetEditor(), CodeBlocksEvent::SetX(), CodeBlocksEvent::SetY(), wxSCI_INVALID_POSITION, wxT, wxPoint::x, and wxPoint::y.
Referenced by CCManager(), and ~CCManager().
OnPopupScroll()
void CCManager::OnPopupScroll (wxMouseEvent & event) private
Intercept cbStyledTextCtrl scroll events and forward to autocomplete/documentation popups.
Definition at line 1120 of file ccmanager.cpp.
References wxMouseEvent::GetPosition(), and wxMouseEvent::GetWheelRotation().
Referenced by DoHidePopup(), and DoShowDocumentation().
OnShowCallTip()
void CCManager::OnShowCallTip (CodeBlocksEvent & event) private
Event handler to show the call tip, when user press Ctrl-Shift-Space.
Definition at line 937 of file ccmanager.cpp.
References CCManagerHelper::CallTipToInt(), FROM_TIMER, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbCodeCompletionPlugin::GetCallTips(), wxScintilla::GetCharAt(), Manager::GetConfigManager(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), wxScintilla::GetStyleAt(), wxScintilla::GetTextRange(), wxString::Length(), wxScintilla::LineFromPosition(), wxScintilla::PositionFromLine(), ConfigManager::ReadInt(), wxString::RemoveLast(), wxString::size(), wxScintilla::WordStartPosition(), wxIsspace(), wxSCI_INVALID_POSITION, and wxT.
Referenced by CCManager().
OnTimer()
void CCManager::OnTimer (wxTimerEvent & event) private
Grouped event handler for several timers.
Definition at line 1147 of file ccmanager.cpp.
References wxScintilla::AutoCompActive(), wxScintilla::AutoCompGetCurrent(), cbEVT_COMPLETE_CODE, FROM_TIMER, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), idAutocompSelectTimer, idAutoLaunchTimer, idCallTipTimer, Manager::ProcessEvent(), and wxSCI_INVALID_POSITION.
Referenced by CCManager().
ProcessArrow()
bool CCManager::ProcessArrow (int key)
Used by cbStyledTextCtrl to process ArrowUp and ArrowDown key press.
This is not intended to be called by ccPlugins.
Definition at line 441 of file ccmanager.cpp.
References wxScintilla::CallTipActive(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), Manager::GetEditorManager(), WXK_DOWN, and WXK_UP.
Referenced by cbStyledTextCtrl::OnKeyDown().
RegisterAutoLaunchChars()
void CCManager::RegisterAutoLaunchChars (const wxString & chars, cbCodeCompletionPlugin * registrant)
Register a new set of characters that, when typed, auto-launch codecomplete requests.
Use this if the default set is not appropriate.
Definition at line 389 of file ccmanager.cpp.
References wxString::begin(), and wxString::end().
RegisterCallTipChars()
void CCManager::RegisterCallTipChars (const wxString & chars, cbCodeCompletionPlugin * registrant)
Register a new set of characters that, when typed, invoke calltip requests.
Use this if the default set is not appropriate.
Definition at line 383 of file ccmanager.cpp.
References wxString::begin(), and wxString::end().
UpdateEnvSettings()
void CCManager::UpdateEnvSettings ()
Called after env settings have changed, so the changes can be applied.
Definition at line 640 of file ccmanager.cpp.
References Manager::Get(), EditorManager::GetBuiltinEditor(), Manager::GetColourManager(), EditorManager::GetEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), and setupColours().
Referenced by MainFrame::OnSettingsEnvironment().
Friends And Related Function Documentation
Manager
friend class Manager friend
Definition at line 44 of file ccmanager.h.
Mgr< CCManager >
friend class Mgr< CCManager > friend
Definition at line 43 of file ccmanager.h.
Member Data Documentation
m_AutocompPosition
int CCManager::m_AutocompPosition private
Location of caret when autocomplete timer starts, if caret is still there, launch autocomplete.
Definition at line 166 of file ccmanager.h.
m_AutocompSelectTimer
wxTimer CCManager::m_AutocompSelectTimer private
Definition at line 179 of file ccmanager.h.
m_AutocompTokens
std::vector<cbCodeCompletionPlugin::CCToken> CCManager::m_AutocompTokens private
Cached autocomplete list.
Definition at line 190 of file ccmanager.h.
m_AutoLaunchChars
CCPluginCharMap CCManager::m_AutoLaunchChars private
Chars each plugin is interested in for autocomplete.
Definition at line 164 of file ccmanager.h.
m_AutoLaunchTimer
wxTimer CCManager::m_AutoLaunchTimer private
Definition at line 178 of file ccmanager.h.
m_CallTipActive
int CCManager::m_CallTipActive private
Is CCManager currently displaying a calltip, and if so, where.
Definition at line 167 of file ccmanager.h.
m_CallTipChars
CCPluginCharMap CCManager::m_CallTipChars private
Chars each plugin is interested in for calltip state.
Definition at line 163 of file ccmanager.h.
m_CallTipChoiceDict
std::map<int, size_t> CCManager::m_CallTipChoiceDict private
Remember past choices.
Definition at line 175 of file ccmanager.h.
m_CallTipFuzzyChoiceDict
std::map<int, size_t> CCManager::m_CallTipFuzzyChoiceDict private
Remember past choices based on prefix.
Definition at line 176 of file ccmanager.h.
m_CallTips
CallTipVec CCManager::m_CallTips private
Cached calltips.
Definition at line 173 of file ccmanager.h.
m_CallTipTimer
wxTimer CCManager::m_CallTipTimer private
Definition at line 177 of file ccmanager.h.
m_CurCallTip
CallTipVec::const_iterator CCManager::m_CurCallTip private
Remember current choice.
Definition at line 174 of file ccmanager.h.
m_DocPos
wxPoint CCManager::m_DocPos private
Location of the documentation popup.
Definition at line 181 of file ccmanager.h.
m_DocSize
wxSize CCManager::m_DocSize private
Size of the documentation popup.
Definition at line 180 of file ccmanager.h.
m_EditorHookID
int CCManager::m_EditorHookID private
Definition at line 165 of file ccmanager.h.
m_LastACLaunchState
int CCManager::m_LastACLaunchState[2] private
Definition at line 189 of file ccmanager.h.
m_LastAutocompIndex
int CCManager::m_LastAutocompIndex private
Index of currently selected entry in autocomplete popup.
Definition at line 168 of file ccmanager.h.
m_LastTipPos
int CCManager::m_LastTipPos private
Last location a tool/call tip was displayed.
Definition at line 169 of file ccmanager.h.
m_OwnsAutocomp
bool CCManager::m_OwnsAutocomp private
Do we control the current autocomplete popup?
Definition at line 171 of file ccmanager.h.
m_pAutocompPopup
wxListView* CCManager::m_pAutocompPopup private
Definition at line 183 of file ccmanager.h.
m_pHtml
wxHtmlWindow* CCManager::m_pHtml private
Documentation popup.
Definition at line 188 of file ccmanager.h.
m_pLastCCPlugin
cbCodeCompletionPlugin* CCManager::m_pLastCCPlugin private
The plugin handling m_pLastEditor.
Definition at line 186 of file ccmanager.h.
m_pLastEditor
cbEditor* CCManager::m_pLastEditor private
Last editor operated on.
Definition at line 185 of file ccmanager.h.
m_pPopup
UnfocusablePopupWindow* CCManager::m_pPopup private
Container for documentation popup.
Definition at line 187 of file ccmanager.h.
m_WindowBound
int CCManager::m_WindowBound private
Right-most boundary the documentation popup is allowed to stretch to.
Definition at line 170 of file ccmanager.h.
The documentation for this class was generated from the following files:
ccmanager.h
ccmanager.cpp