Code::Blocks: cbSearchResultsLog Class Reference
cbSearchResultsLog Class Reference
#include <searchresultslog.h>
Public Member Functions
cbSearchResultsLog (const wxArrayString &titles, wxArrayInt &widths)
virtual ~cbSearchResultsLog ()
void FocusEntry (size_t index)
void SetBasePath (const wxString base)
virtual wxWindow * CreateControl (wxWindow *parent)
Public Member Functions inherited from ListCtrlLogger
ListCtrlLogger (const wxArrayString &titles, const wxArrayInt &widths, bool fixedPitchFont=false)
~ListCtrlLogger ()
virtual void CopyContentsToClipboard (bool selectionOnly=false)
virtual void UpdateSettings ()
virtual void Append (const wxString &msg, Logger::level lv=info)
virtual void Append (const wxArrayString &colValues, Logger::level lv=info, int autoSize=-1)
virtual size_t GetItemsCount () const
virtual void Clear ()
virtual bool HasFeature (Feature::Enum feature) const
virtual void AutoFitColumns (int column)
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool GetWrapMode () const
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Protected Member Functions
void OnDoubleClick (wxCommandEvent &event)
void SyncEditor (int selIndex)
Protected Member Functions inherited from ListCtrlLogger
wxString GetItemAsText (long item) const
Protected Attributes
wxString m_Base
Protected Attributes inherited from ListCtrlLogger
wxListCtrl * control
bool fixed
wxArrayString titles
wxArrayInt widths
ListStyles style [num_levels]
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Constructor & Destructor Documentation
cbSearchResultsLog::cbSearchResultsLog (const wxArrayString & titles, wxArrayInt & widths)
cbSearchResultsLog::~cbSearchResultsLog () virtual
Member Function Documentation
wxWindow * cbSearchResultsLog::CreateControl (wxWindow * parent) virtual
Reimplemented from ListCtrlLogger.
References ListCtrlLogger::control, ListCtrlLogger::CreateControl(), Manager::Get(), Manager::GetAppWindow(), and OnDoubleClick().
void cbSearchResultsLog::FocusEntry (size_t index)
References ListCtrlLogger::control, and SyncEditor().
Referenced by CodeRefactoring::DoFindReferences(), and FindReplace::FindInFiles().
void cbSearchResultsLog::OnDoubleClick (wxCommandEvent & event) protected
References ListCtrlLogger::control, and SyncEditor().
Referenced by CreateControl().
void cbSearchResultsLog::SetBasePath (const wxString base) inline
References m_Base.
Referenced by CodeRefactoring::DoFindReferences(), and FindReplace::FindInFiles().
void cbSearchResultsLog::SyncEditor (int selIndex) protected
References EditorBase::Activate(), ListCtrlLogger::control, Manager::Get(), cbEditor::GetControl(), Manager::GetEditorManager(), cbEditor::GotoLine(), m_Base, and EditorManager::Open().
Referenced by FocusEntry(), and OnDoubleClick().
Member Data Documentation
wxString cbSearchResultsLog::m_Base protected
Referenced by SetBasePath(), and SyncEditor().
The documentation for this class was generated from the following files:
searchresultslog.h
searchresultslog.cpp