Code::Blocks: EditorManager Class Reference
EditorManager Class Reference
#include <editormanager.h>
Public Member Functions
EditorManager & operator= (cb_unused const EditorManager &rhs)
cbAuiNotebook * GetNotebook ()
cbNotebookStack * GetNotebookStack ()
void DeleteNotebookStack ()
void RebuildNotebookStack ()
void RecreateOpenEditorStyles ()
int GetEditorsCount ()
EditorBase * IsOpen (const wxString &filename)
cbEditor * Open (const wxString &filename, int pos=0, ProjectFile *data=nullptr)
cbEditor * Open (LoaderBase *fileLdr, const wxString &filename, int pos=0, ProjectFile *data=nullptr)
EditorBase * GetEditor (int index)
EditorBase * GetEditor (const wxString &filename)
EditorBase * GetActiveEditor ()
cbEditor * GetBuiltinEditor (EditorBase *eb)
int FindPageFromEditor (EditorBase *eb)
cbEditor * IsBuiltinOpen (const wxString &filename)
cbEditor * GetBuiltinEditor (int index)
cbEditor * GetBuiltinEditor (const wxString &filename)
cbEditor * GetBuiltinActiveEditor ()
void ActivateNext ()
void ActivatePrevious ()
void SetActiveEditor (EditorBase *ed)
EditorColourSet * GetColourSet ()
void SetColourSet (EditorColourSet *theme)
cbEditor * New (const wxString &newFileName=wxEmptyString)
void AddCustomEditor (EditorBase *eb)
void RemoveCustomEditor (EditorBase *eb)
bool UpdateProjectFiles (cbProject *project)
bool SwapActiveHeaderSource ()
bool OpenContainingFolder ()
bool CloseActive (bool dontsave=false)
bool Close (const wxString &filename, bool dontsave=false)
bool Close (EditorBase *editor, bool dontsave=false)
bool Close (int index, bool dontsave=false)
bool QueryClose (EditorBase *editor)
bool QueryCloseAll ()
bool CloseAll (bool dontsave=false)
Closes all opened editors.
bool CloseAllExcept (EditorBase *editor, bool dontsave=false)
Closes all opened editors, except the editor passed as parameter.
bool CloseAllInTabCtrl (bool dontsave=false)
Closes all editors in the same tab control as the active editor.
bool CloseAllInTabCtrlExcept (EditorBase *editor, bool dontsave=false)
Closes all editors in the same tab control as the active editor, except the editor passed as parameter.
bool Save (const wxString &filename)
bool Save (int index)
bool SaveActive ()
bool SaveAs (int index)
bool SaveActiveAs ()
bool SaveAll ()
void Print (PrintScope ps, PrintColourMode pcm, bool line_numbers)
void HideNotebook ()
Hides the editor notebook for layout purposes.
void ShowNotebook ()
Shows the previously hidden editor notebook.
void CheckForExternallyModifiedFiles ()
Check if one of the open files has been modified outside the IDE.
void SetZoom (int zoom)
int GetZoom () const
void MarkReadOnly (int page, bool readOnly=true)
wxString GetSelectionClipboard ()
void SetSelectionClipboard (const wxString &data)
Static Public Member Functions
static bool CanShutdown ()
Static Public Member Functions inherited from Mgr< EditorManager >
static bool Valid ()
static EditorManager * Get ()
static void Free ()
Protected Member Functions
void AddEditorBase (EditorBase *eb)
void RemoveEditorBase (EditorBase *eb, bool deleteObject=true)
cbEditor * InternalGetBuiltinEditor (int page)
EditorBase * InternalGetEditorBase (int page)
Protected Member Functions inherited from Mgr< EditorManager >
Mgr ()
virtual ~Mgr ()
Private Member Functions
void OnGenericContextMenuHandler (wxCommandEvent &event)
void OnPageChanged (wxAuiNotebookEvent &event)
void OnPageChanging (wxAuiNotebookEvent &event)
void OnPageClose (wxAuiNotebookEvent &event)
void OnPageContextMenu (wxAuiNotebookEvent &event)
void OnClose (wxCommandEvent &event)
void OnCloseAll (wxCommandEvent &event)
void OnCloseAllOthers (wxCommandEvent &event)
void OnSave (wxCommandEvent &event)
void OnSaveAll (wxCommandEvent &event)
void OnSwapHeaderSource (wxCommandEvent &event)
void OnOpenContainingFolder (wxCommandEvent &event)
void OnTabPosition (wxCommandEvent &event)
void OnProperties (wxCommandEvent &event)
void OnAddFileToProject (wxCommandEvent &event)
void OnRemoveFileFromProject (wxCommandEvent &event)
void OnShowFileInTree (wxCommandEvent &event)
void OnAppDoneStartup (wxCommandEvent &event)
void OnAppStartShutdown (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void OnTreeItemSelected (wxTreeEvent &event)
void OnTreeItemActivated (wxTreeEvent &event)
void OnTreeItemRightClick (wxTreeEvent &event)
void CollectDefines (CodeBlocksEvent &event)
void OnAppActivated (CodeBlocksEvent &event)
EditorManager (cb_unused const EditorManager &rhs)
EditorManager ()
~EditorManager ()
void OnCheckForModifiedFiles (wxCommandEvent &event)
bool IsHeaderSource (const wxFileName &candidateFile, const wxFileName &activeFile, FileType ftActive, bool &isCandidate)
wxFileName FindHeaderSource (const wxArrayString &candidateFilesArray, const wxFileName &activeFile, bool &isCandidate)
bool CloseEditors (const std::vector< EditorBase *> &editors, bool dontsave=false)
Closes all editors passed to the function.
void GetEditorsInTabCtrl (std::vector< EditorBase *> &editors, EditorBase *editor)
Returns a vector with pointers to the editors that are in the same tab control as the passed editor.
Private Attributes
cbAuiNotebook * m_pNotebook
cbNotebookStack * m_pNotebookStackHead
cbNotebookStack * m_pNotebookStackTail
size_t m_nNotebookStackSize
EditorColourSet * m_Theme
int m_Zoom
bool m_isCheckingForExternallyModifiedFiles
EditorManagerInternalData * m_pData
Static Private Attributes
static bool s_CanShutdown = true
Friends
class Mgr< EditorManager >
class Manager
struct EditorManagerInternalData
Detailed Description
Definition at line 59 of file editormanager.h.
Constructor & Destructor Documentation
EditorManager() [1/2]
EditorManager::EditorManager (cb_unused const EditorManager & rhs) private
EditorManager() [2/2]
EditorManager::EditorManager () private
Definition at line 143 of file editormanager.cpp.
References _(), _T, cbEVT_APP_ACTIVATED, cbEVT_BUILDTARGET_SELECTED, cbEVT_PROJECT_ACTIVATE, cbEVT_WORKSPACE_LOADING_COMPLETE, CollectDefines(), COLORSET_DEFAULT, LogManager::DebugLog(), EditorManagerInternalData::EditorManagerInternalData(), Manager::Get(), Manager::GetAppWindow(), wxSystemSettings::GetColour(), Manager::GetColourManager(), Manager::GetConfigManager(), Manager::GetLogManager(), ID_NBEditorManager, OnAppActivated(), ConfigManager::ReadInt(), ColourManager::RegisterColour(), Manager::RegisterEventSink(), wxBLACK, wxCLIP_CHILDREN, wxDefaultPosition, wxDefaultSize, wxLIGHT_GREY, wxNO_FULL_REPAINT_ON_RESIZE, wxSYS_COLOUR_3DFACE, wxSYS_COLOUR_3DHIGHLIGHT, wxSYS_COLOUR_BTNFACE, wxSYS_COLOUR_BTNTEXT, and wxT.
~EditorManager()
EditorManager::~EditorManager () private
Definition at line 186 of file editormanager.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Member Function Documentation
ActivateNext()
void EditorManager::ActivateNext ()
Definition at line 440 of file editormanager.cpp.
Referenced by MainFrame::OnFileNext(), and ScriptBindings::RegisterBindings().
ActivatePrevious()
void EditorManager::ActivatePrevious ()
Definition at line 445 of file editormanager.cpp.
Referenced by MainFrame::OnFilePrev(), and ScriptBindings::RegisterBindings().
AddCustomEditor()
void EditorManager::AddCustomEditor (EditorBase * eb)
Definition at line 515 of file editormanager.cpp.
Referenced by EditorBase::EditorBase().
AddEditorBase()
void EditorManager::AddEditorBase (EditorBase * eb) protected
Definition at line 525 of file editormanager.cpp.
References EditorBase::GetTitle().
CanShutdown()
static bool EditorManager::CanShutdown () inline static
Definition at line 71 of file editormanager.h.
Referenced by MainFrame::OnApplicationClose(), MainFrame::OnFileCloseAllProjects(), MainFrame::OnFileCloseProject(), MainFrame::OnFileMenuUpdateUI(), and MainFrame::OnProjectMenuUpdateUI().
CheckForExternallyModifiedFiles()
void EditorManager::CheckForExternallyModifiedFiles ()
Check if one of the open files has been modified outside the IDE.
If so, ask to reload it.
Definition at line 808 of file editormanager.cpp.
References _(), _T, wxFile::Access(), wxArrayString::Add(), wxString::c_str(), cbMessageBox(), EditorBase::Close(), crAll, crCancel, crNo, crYes, ProjectManager::FindProjectForFile(), fvsMissing, fvsNormal, fvsReadOnly, Manager::Get(), cbProject::GetCheckForExternallyModifiedFiles(), cbEditor::GetControl(), wxArrayString::GetCount(), EditorBase::GetFilename(), ProjectFile::GetFileState(), cbEditor::GetLastModificationTime(), cbEditor::GetModified(), ProjectFile::GetParentProject(), cbEditor::GetProjectFile(), Manager::GetProjectManager(), wxScintilla::GetReadOnly(), GetStringFromArray(), cbEditor::IsOK(), EditorBase::IsReadOnly(), wxFileName::MakeAbsolute(), PlaceWindow(), wxString::Printf(), cbEditor::Reload(), EditorBase::Save(), ProjectFile::SetFileState(), EditorBase::SetModified(), cbEditor::SetModified(), cbEditor::SetReadOnly(), wxDialog::ShowModal(), cbEditor::Touch(), wxFile::write, wxCANCEL, wxFileExists(), wxICON_ERROR, wxICON_QUESTION, wxID_CANCEL, wxID_NO, wxID_YES, and wxYES_NO.
Referenced by MainFrame::OnFileNewWhat(), and ProjectFileOptionsDlg::OnReadOnlyCheck().
Close() [1/3]
bool EditorManager::Close (const wxString & filename, bool dontsave = false)
Definition at line 683 of file editormanager.cpp.
Referenced by cbProject::CloseAllFiles(), EditorBase::DisplayContextMenu(), ScriptBindings::EditorManager_Close(), cbEditor::OnClose(), ProjectManagerUI::OnCloseFile(), EditorBase::OnContextMenuEntry(), cbProject::RemoveFile(), and FindReplace::ReplaceInFiles().
Close() [2/3]
bool EditorManager::Close (EditorBase * editor, bool dontsave = false)
Definition at line 688 of file editormanager.cpp.
Close() [3/3]
bool EditorManager::Close (int index, bool dontsave = false)
Definition at line 704 of file editormanager.cpp.
CloseActive()
bool EditorManager::CloseActive (bool dontsave = false)
Definition at line 657 of file editormanager.cpp.
Referenced by MainFrame::OnFileClose(), and ScriptBindings::RegisterBindings().
CloseAll()
bool EditorManager::CloseAll (bool dontsave = false)
Closes all opened editors.
Definition at line 566 of file editormanager.cpp.
References _().
Referenced by MainFrame::OnFileCloseAll(), and ScriptBindings::RegisterBindings().
CloseAllExcept()
bool EditorManager::CloseAllExcept (EditorBase * editor, bool dontsave = false)
Closes all opened editors, except the editor passed as parameter.
Definition at line 591 of file editormanager.cpp.
CloseAllInTabCtrl()
bool EditorManager::CloseAllInTabCtrl (bool dontsave = false)
Closes all editors in the same tab control as the active editor.
Definition at line 603 of file editormanager.cpp.
Referenced by EditorBase::OnContextMenuEntry().
CloseAllInTabCtrlExcept()
bool EditorManager::CloseAllInTabCtrlExcept (EditorBase * editor, bool dontsave = false)
Closes all editors in the same tab control as the active editor, except the editor passed as parameter.
Definition at line 611 of file editormanager.cpp.
Referenced by EditorBase::OnContextMenuEntry().
CloseEditors()
bool EditorManager::CloseEditors (const std::vector< EditorBase *> & editors, bool dontsave = false) private
Closes all editors passed to the function.
Definition at line 633 of file editormanager.cpp.
CollectDefines()
void EditorManager::CollectDefines (CodeBlocksEvent & event) private
Definition at line 1748 of file editormanager.cpp.
References wxArrayString::Add(), AppendArray(), ExpandBackticks(), Manager::Get(), cbProject::GetActiveBuildTarget(), ProjectManager::GetActiveProject(), GetArrayFromString(), cbProject::GetBuildTarget(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompileOptionsBase::GetCompilerOptions(), Manager::GetConfigManager(), cbEditor::GetControl(), wxArrayString::GetCount(), ProjectBuildTarget::GetFilesList(), cbProject::GetFilesList(), cbEditor::GetLanguage(), Manager::GetProjectManager(), GetStringFromArray(), MakeUniqueArray(), wxString::Replace(), wxScintilla::SetKeyWords(), ConfigManager::Write(), wxNOT_FOUND, and wxT.
Referenced by EditorManager().
DeleteNotebookStack()
void EditorManager::DeleteNotebookStack ()
Definition at line 244 of file editormanager.cpp.
References cbNotebookStack::next.
Referenced by EnvironmentSettingsDlg::EndModal().
FindHeaderSource()
wxFileName EditorManager::FindHeaderSource (const wxArrayString & candidateFilesArray, const wxFileName & activeFile, bool & isCandidate) private
Definition at line 1049 of file editormanager.cpp.
References FileTypeOf(), wxArrayString::GetCount(), wxFileName::GetExt(), wxFileName::GetFullName(), and wxIsupper().
FindPageFromEditor()
int EditorManager::FindPageFromEditor (EditorBase * eb)
Definition at line 670 of file editormanager.cpp.
Referenced by EditorBase::SetTitle().
GetActiveEditor()
EditorBase * EditorManager::GetActiveEditor ()
Definition at line 431 of file editormanager.cpp.
Referenced by NativeParser::AddProjectToParser(), CompilerGCC::DoBuild(), MainFrame::DoUpdateAppTitle(), MainFrame::DoUpdateStatusBar(), MainFrame::OnEditBookmarksClearAll(), MainFrame::OnEditBookmarksNext(), MainFrame::OnEditBookmarksPrevious(), MainFrame::OnEditBookmarksToggle(), MainFrame::OnEditClearHistory(), MainFrame::OnEditCopy(), MainFrame::OnEditCut(), MainFrame::OnEditMenuUpdateUI(), CodeCompletion::OnEditorClosed(), MainFrame::OnEditorUpdateUI(), cbEditor::OnEditorUpdateUI(), MainFrame::OnEditPaste(), MainFrame::OnEditRedo(), MainFrame::OnEditSelectAll(), MainFrame::OnEditSelectNext(), MainFrame::OnEditSelectNextSkip(), MainFrame::OnEditUndo(), MainFrame::OnFileMenuUpdateUI(), CodeCompletion::OnReparsingTimer(), GdbCmd_AddBreakpointCondition::ParseOutput(), ScriptBindings::RegisterBindings(), MacrosManager::ReplaceMacros(), FindReplace::ShowFindDialog(), ProjectManagerUI::ShowMenu(), and DebugInterfaceFactory::ShowValueTooltip().
GetBuiltinActiveEditor()
cbEditor* EditorManager::GetBuiltinActiveEditor () inline
Definition at line 95 of file editormanager.h.
Referenced by EditorBase::DisplayContextMenu(), CodeCompletion::DoAllMethodsImpl(), CodeCompletion::DoClassMethodDeclImpl(), CodeRefactoring::DoFindReferences(), CodeCompletion::DoParseOpenedProjectAndActiveEditor(), CodeRefactoring::DoRenameSymbols(), MainFrame::DoUpdateStatusBar(), FindReplace::FindInFiles(), FindReplace::FindNext(), FindReplace::FindSelectedText(), NativeParser::GetCurrentProject(), cbDebuggerPlugin::GetEditorWordAtCaret(), NativeParser::GetParserInfoByCurrentEditor(), CCManager::GetProviderFor(), GetSelectedText(), CodeRefactoring::GetSymbolUnderCursor(), CodeCompletion::GotoFunctionPrevNext(), CCManager::InjectAutoCompShow(), NativeParser::MarkItemsByAI(), CCManager::NotifyDocumentation(), CodeBlocksApp::OnAppActivate(), CCManager::OnAutocompleteSelect(), CCManager::OnCompleteCode(), CCManager::OnDeactivateApp(), CCManager::OnDeferredCallTipCancel(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditEncoding(), MainFrame::OnEditEOLMode(), MainFrame::OnEditFoldAll(), MainFrame::OnEditFoldBlock(), MainFrame::OnEditGotoLineEnd(), MainFrame::OnEditGotoMatchingBrace(), MainFrame::OnEditHighlightMode(), MainFrame::OnEditInsertNewLine(), MainFrame::OnEditLineCopy(), MainFrame::OnEditLineCut(), MainFrame::OnEditLineDelete(), MainFrame::OnEditLineDuplicate(), MainFrame::OnEditLineMove(), MainFrame::OnEditLinePaste(), MainFrame::OnEditLineTranspose(), MainFrame::OnEditLowerCase(), MainFrame::OnEditMenuUpdateUI(), CodeCompletion::OnEditorActivatedTimer(), MainFrame::OnEditParaDown(), MainFrame::OnEditParaDownExtend(), MainFrame::OnEditParaUp(), MainFrame::OnEditParaUpExtend(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleAllFolds(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditToggleFoldBlock(), MainFrame::OnEditUncommentSelected(), MainFrame::OnEditUnfoldAll(), MainFrame::OnEditUnfoldBlock(), MainFrame::OnEditUpperCase(), MainFrame::OnEditWordPartLeft(), MainFrame::OnEditWordPartLeftExtend(), MainFrame::OnEditWordPartRight(), MainFrame::OnEditWordPartRightExtend(), MainFrame::OnEditZoomIn(), MainFrame::OnEditZoomOut(), MainFrame::OnEditZoomReset(), CodeCompletion::OnFunction(), CodeCompletion::OnGotoDeclaration(), CodeCompletion::OnGotoFunction(), MainFrame::OnHighlightMenu(), CCManager::OnMenuSelect(), CodeCompletion::OnOpenIncludeFile(), CodeCompletion::OnParserEnd(), CodeCompletion::OnParserStart(), NativeParser::OnParsingOneByOneTimer(), ProjectManagerUI::OnProperties(), CodeCompletion::OnRealtimeParsingTimer(), DebuggerMenuHandler::OnRunToCursor(), MainFrame::OnSearchFind(), MainFrame::OnSearchGotoLine(), MainFrame::OnSearchGotoNextChanged(), MainFrame::OnSearchGotoPrevChanged(), MainFrame::OnSearchReplace(), DebuggerMenuHandler::OnSetNextStatement(), MainFrame::OnShiftTab(), CCManager::OnShowCallTip(), CCManager::OnTimer(), DebuggerMenuHandler::OnToggleBreakpoint(), DebuggerMenuHandler::OnUpdateUI(), DebuggerToolbarHandler::OnUpdateUI(), CodeCompletion::OnUpdateUI(), CompilerGCC::OnUpdateUI(), MainFrame::OnViewMenuUpdateUI(), CodeRefactoring::Parse(), CodeCompletion::ParseFunctionsAndFillToolbar(), CompilerGCC::PrepareCompileFile(), PrintDialog::PrintDialog(), CCManager::ProcessArrow(), ScriptBindings::RegisterBindings(), ProjectLayoutLoader::Save(), CodeRefactoring::SearchInFiles(), ClassBrowser::UpdateClassBrowserView(), CodeCompletion::UpdateEditorSyntax(), and CodeRefactoring::VerifyResult().
GetBuiltinEditor() [1/3]
cbEditor * EditorManager::GetBuiltinEditor (EditorBase * eb)
Definition at line 308 of file editormanager.cpp.
References EditorBase::IsBuiltinEditor().
Referenced by cbDebuggerPlugin::ClearActiveMarkFromAllEditors(), CrashHandlerSaveEditorFiles(), CompilerErrors::DoClearErrorMarkFromAllEditors(), CompilerErrors::DoGotoError(), ScriptBindings::EditorManager_GetBuiltinEditor(), EditorConfigurationDlg::EndModal(), FindReplace::FindInFiles(), FindReplaceDlg::FindReplaceDlg(), FileManager::Load(), CCManager::OnDeactivateEd(), CodeCompletion::OnEditorActivated(), NativeParser::OnEditorActivated(), CCManager::OnEditorClose(), CodeCompletion::OnEditorClosed(), CCManager::OnEditorOpen(), CodeCompletion::OnEditorOpen(), MainFrame::OnEditUndo(), CompilerGCC::OnJobEnd(), CodeCompletion::OnParserEnd(), MainFrame::OnSearchMenuUpdateUI(), FindReplace::ReplaceInFiles(), FindReplace::ShowFindDialog(), cbDebuggerPlugin::SyncEditor(), and CCManager::UpdateEnvSettings().
GetBuiltinEditor() [2/3]
cbEditor* EditorManager::GetBuiltinEditor (int index) inline
Definition at line 93 of file editormanager.h.
References GetBuiltinEditor().
Referenced by GetBuiltinEditor().
GetBuiltinEditor() [3/3]
cbEditor* EditorManager::GetBuiltinEditor (const wxString & filename) inline
Definition at line 94 of file editormanager.h.
GetColourSet()
EditorColourSet* EditorManager::GetColourSet () inline
Definition at line 100 of file editormanager.h.
References wxEmptyString.
Referenced by EditorConfigurationDlg::ChangeTheme(), MainFrame::CreateMenubar(), DisassemblyDlg::DisassemblyDlg(), MainFrame::DoUpdateStatusBar(), ProjectFileOptionsDlg::FillGeneralProperties(), MainFrame::OnEditBoxCommentSelected(), MainFrame::OnEditCommentSelected(), MainFrame::OnEditHighlightMode(), MainFrame::OnEditStreamCommentSelected(), MainFrame::OnEditToggleCommentSelected(), MainFrame::OnEditUncommentSelected(), MainFrame::OnHighlightMenu(), and CodeCompletion::UpdateEditorSyntax().
GetEditor() [1/2]
EditorBase * EditorManager::GetEditor (int index)
Definition at line 331 of file editormanager.cpp.
Referenced by CrashHandlerSaveEditorFiles(), EditorBase::CreateContextSubMenu(), EditorConfigurationDlg::EndModal(), CodeRefactoring::GetOpenedFiles(), FileManager::Load(), CodeBlocksApp::LoadDelayedFiles(), BreakpointsDlg::OnBreakpointEdit(), MainFrame::OnFileMenuUpdateUI(), RefreshBreakpoints(), RecentItemsList::RefreshStartHerePage(), Wiz::RunFilesWizard(), MainFrame::ShowHideStartPage(), and CCManager::UpdateEnvSettings().
GetEditor() [2/2]
EditorBase* EditorManager::GetEditor (const wxString & filename) inline
Definition at line 85 of file editormanager.h.
GetEditorsCount()
int EditorManager::GetEditorsCount ()
Definition at line 286 of file editormanager.cpp.
Referenced by cbDebuggerPlugin::ClearActiveMarkFromAllEditors(), CrashHandlerSaveEditorFiles(), EditorBase::CreateContextSubMenu(), CompilerErrors::DoClearErrorMarkFromAllEditors(), CompilerErrors::DoGotoError(), EditorConfigurationDlg::EndModal(), FindReplace::FindInFiles(), FindReplaceDlg::FindReplaceDlg(), CodeRefactoring::GetOpenedFiles(), FileManager::Load(), CodeCompletion::OnEditorClosed(), MainFrame::OnFileMenuUpdateUI(), CodeCompletion::OnParserEnd(), RefreshBreakpoints(), FindReplace::ReplaceInFiles(), cbDebuggerPlugin::SyncEditor(), and CCManager::UpdateEnvSettings().
GetEditorsInTabCtrl()
void EditorManager::GetEditorsInTabCtrl (std::vector< EditorBase *> & editors, EditorBase * editor) private
Returns a vector with pointers to the editors that are in the same tab control as the passed editor.
Definition at line 621 of file editormanager.cpp.
GetNotebook()
cbAuiNotebook* EditorManager::GetNotebook () inline
Definition at line 73 of file editormanager.h.
Referenced by MainFrame::DoUpdateEditorStyle(), EditorConfigurationDlg::EndModal(), FindReplace::FindInFiles(), WorkspaceLoader::LoadLayout(), ProjectLayoutLoader::LoadNotebookLayout(), CodeBlocksApp::OnAppActivate(), MainFrame::OnFocusEditor(), ProjectManagerUI::OnProperties(), MainFrame::OnSwitchTabs(), MainFrame::OnViewHideEditorTabs(), cbEditor::OnZoom(), EditorBase::SetTitle(), and ProjectManager::WorkspaceChanged().
GetNotebookStack()
cbNotebookStack * EditorManager::GetNotebookStack ()
Definition at line 195 of file editormanager.cpp.
References cbNotebookStack::next, NULL, cbNotebookStack::window, and wxNOT_FOUND.
GetSelectionClipboard()
wxString EditorManager::GetSelectionClipboard ()
Definition at line 1971 of file editormanager.cpp.
GetZoom()
int EditorManager::GetZoom () const
Definition at line 1941 of file editormanager.cpp.
Referenced by EditorConfigurationDlg::EndModal(), and cbAuiNotebook::OnIdle().
HideNotebook()
void EditorManager::HideNotebook ()
Hides the editor notebook for layout purposes.
Definition at line 1719 of file editormanager.cpp.
Referenced by cbProject::CloseAllFiles(), and cbProject::LoadLayout().
InternalGetBuiltinEditor()
cbEditor * EditorManager::InternalGetBuiltinEditor (int page) protected
Definition at line 300 of file editormanager.cpp.
References EditorBase::IsBuiltinEditor().
InternalGetEditorBase()
EditorBase * EditorManager::InternalGetEditorBase (int page) protected
Definition at line 291 of file editormanager.cpp.
IsBuiltinOpen()
cbEditor* EditorManager::IsBuiltinOpen (const wxString & filename) inline
Definition at line 92 of file editormanager.h.
Referenced by BreakpointsDlg::BreakpointProperties(), CodeRefactoring::DoRenameSymbols(), BreakpointsDlg::EnableBreakpoint(), FindReplace::FindInFiles(), BreakpointsDlg::OnEnable(), CCDebugInfo::OnGoDeclClick(), CCDebugInfo::OnGoImplClick(), BreakpointsDlg::OnRemove(), cbProject::QueryCloseAllFiles(), ScriptBindings::RegisterBindings(), BreakpointsDlg::RemoveAllBreakpoints(), CodeRefactoring::SearchInFiles(), and CodeRefactoring::VerifyResult().
IsHeaderSource()
bool EditorManager::IsHeaderSource (const wxFileName & candidateFile, const wxFileName & activeFile, FileType ftActive, bool & isCandidate) private
Definition at line 1012 of file editormanager.cpp.
References _T, wxString::CmpNoCase(), wxFileName::FileExists(), FileTypeOf(), ftHeader, ftSource, ftTemplateSource, wxDir::GetAllFiles(), wxArrayString::GetCount(), wxFileName::GetFullName(), wxFileName::GetName(), wxFileName::GetPath(), wxDIR_FILES, and wxDIR_HIDDEN.
IsOpen()
EditorBase * EditorManager::IsOpen (const wxString & filename)
Definition at line 313 of file editormanager.cpp.
References g_EditorModified, EditorBase::GetFilename(), wxString::IsSameAs(), NULL, realpath(), and UnixFilename().
Referenced by ProjectManagerUI::DoOpenFile(), FindReplace::ReplaceInFiles(), and ProjectManagerUI::ShowMenu().
MarkReadOnly()
void EditorManager::MarkReadOnly (int page, bool readOnly = true)
Definition at line 1002 of file editormanager.cpp.
References _T, cbLoadBitmap(), ConfigManager::GetDataFolder(), and wxNullBitmap.
Referenced by EditorBase::SetTitle().
New()
cbEditor * EditorManager::New (const wxString & newFileName = wxEmptyString)
Definition at line 475 of file editormanager.cpp.
References _T, cbEVT_EDITOR_OPEN, FileTypeOf(), Manager::Get(), Manager::GetConfigManager(), cbEditor::GetControl(), EditorBase::GetFilename(), Manager::GetMacrosManager(), Manager::GetPluginManager(), wxString::IsEmpty(), wxFile::IsOpened(), PluginManager::NotifyPlugins(), wxString::Printf(), ConfigManager::Read(), MacrosManager::ReplaceMacros(), cbEditor::SetColourSet(), wxScintilla::SetText(), wxFile::write, wxDirExists(), wxEmptyString, wxFileExists(), and wxPathOnly().
Referenced by MainFrame::OnFileNewWhat(), and ScriptBindings::RegisterBindings().
OnAddFileToProject()
void EditorManager::OnAddFileToProject (wxCommandEvent & event) private
Definition at line 1668 of file editormanager.cpp.
References Manager::Get(), ProjectManager::GetActiveProject(), cbProject::GetFileByFilename(), Manager::GetProjectManager(), ProjectManager::GetUI(), and cbProjectManagerUI::RebuildTree().
OnAppActivated()
void EditorManager::OnAppActivated (CodeBlocksEvent & event) private
Definition at line 1946 of file editormanager.cpp.
References wxTextDataObject::GetText(), wxString::IsEmpty(), and wxTheClipboard.
Referenced by EditorManager().
OnAppDoneStartup()
void EditorManager::OnAppDoneStartup (wxCommandEvent & event) private
Definition at line 1704 of file editormanager.cpp.
OnAppStartShutdown()
void EditorManager::OnAppStartShutdown (wxCommandEvent & event) private
Definition at line 1709 of file editormanager.cpp.
OnCheckForModifiedFiles()
void EditorManager::OnCheckForModifiedFiles (wxCommandEvent & event) private
Definition at line 1714 of file editormanager.cpp.
OnClose()
void EditorManager::OnClose (wxCommandEvent & event) private
Definition at line 1603 of file editormanager.cpp.
OnCloseAll()
void EditorManager::OnCloseAll (wxCommandEvent & event) private
Definition at line 1608 of file editormanager.cpp.
OnCloseAllOthers()
void EditorManager::OnCloseAllOthers (wxCommandEvent & event) private
Definition at line 1613 of file editormanager.cpp.
OnGenericContextMenuHandler()
void EditorManager::OnGenericContextMenuHandler (wxCommandEvent & event) private
Definition at line 1359 of file editormanager.cpp.
References idNBSwitchFile1, idNBSwitchFileMax, idNBTabSplitHorz, idNBTabSplitVert, idNBTabUnsplit, cbEditor::Split(), cbEditor::stHorizontal, cbEditor::stVertical, and cbEditor::Unsplit().
OnOpenContainingFolder()
void EditorManager::OnOpenContainingFolder (wxCommandEvent & event) private
Definition at line 1633 of file editormanager.cpp.
OnPageChanged()
void EditorManager::OnPageChanged (wxAuiNotebookEvent & event) private
Definition at line 1379 of file editormanager.cpp.
References _T, cbEVT_EDITOR_ACTIVATED, cbEVT_EDITOR_SWITCHED, Manager::Get(), wxAuiNotebookEvent::GetOldSelection(), Manager::GetPluginManager(), wxAuiNotebookEvent::GetSelection(), cbNotebookStack::next, PluginManager::NotifyPlugins(), and cbNotebookStack::window.
OnPageChanging()
void EditorManager::OnPageChanging (wxAuiNotebookEvent & event) private
Definition at line 1427 of file editormanager.cpp.
References cbEVT_EDITOR_DEACTIVATED, Manager::Get(), Manager::GetPluginManager(), and PluginManager::NotifyPlugins().
OnPageClose()
void EditorManager::OnPageClose (wxAuiNotebookEvent & event) private
Definition at line 1439 of file editormanager.cpp.
References _T, cbEVT_EDITOR_SWITCHED, Manager::Get(), Manager::GetPluginManager(), wxAuiNotebookEvent::GetSelection(), cbNotebookStack::next, PluginManager::NotifyPlugins(), and cbNotebookStack::window.
OnPageContextMenu()
void EditorManager::OnPageContextMenu (wxAuiNotebookEvent & event) private
Definition at line 1485 of file editormanager.cpp.
References _(), _T, wxMenu::Append(), wxMenu::AppendCheckItem(), wxMenu::AppendSeparator(), PluginManager::AskPluginsForModuleMenu(), Associations::Check(), EditorMaxSwitchTo, wxMenu::Enable(), wxMenu::FindItemByPosition(), Manager::Get(), wxMenu::GetMenuItemCount(), EditorBase::GetModified(), Manager::GetPluginManager(), cbEditor::GetProjectFile(), wxAuiNotebookEvent::GetSelection(), EditorBase::GetShortName(), cbEditor::GetSplitType(), idNBAddFileToProject, idNBProperties, idNBRemoveFileFromProject, idNBShowFileInTree, idNBSwapHeaderSource, idNBSwitchFile1, idNBTabBottom, idNBTabClose, idNBTabCloseAll, idNBTabCloseAllOthers, idNBTabOpenContainingFolder, idNBTabSave, idNBTabSaveAll, idNBTabSplitHorz, idNBTabSplitVert, idNBTabTop, idNBTabUnsplit, mtEditorTab, cbEditor::stHorizontal, cbEditor::stNoSplit, cbEditor::stVertical, wxEmptyString, wxGetKeyState(), wxID_ANY, WXK_CONTROL, and wxT.
OnProperties()
void EditorManager::OnProperties (wxCommandEvent & event) private
Definition at line 1652 of file editormanager.cpp.
References Manager::Get(), cbEditor::GetProjectFile(), PlaceWindow(), wxDialog::ShowModal(), and ProjectFile::ShowOptions().
OnRemoveFileFromProject()
void EditorManager::OnRemoveFileFromProject (wxCommandEvent & event) private
Definition at line 1682 of file editormanager.cpp.
References Manager::Get(), ProjectFile::GetParentProject(), Manager::GetProjectManager(), ProjectManager::GetUI(), cbProjectManagerUI::RebuildTree(), and ProjectManager::RemoveFileFromProject().
OnSave()
void EditorManager::OnSave (wxCommandEvent & event) private
Definition at line 1618 of file editormanager.cpp.
OnSaveAll()
void EditorManager::OnSaveAll (wxCommandEvent & event) private
Definition at line 1623 of file editormanager.cpp.
OnShowFileInTree()
void EditorManager::OnShowFileInTree (wxCommandEvent & event) private
Definition at line 1693 of file editormanager.cpp.
References Manager::Get(), Manager::GetProjectManager(), ProjectManager::GetUI(), cbProjectManagerUI::ShowFileInTree(), and cbProjectManagerUI::SwitchToProjectsPage().
OnSwapHeaderSource()
void EditorManager::OnSwapHeaderSource (wxCommandEvent & event) private
Definition at line 1628 of file editormanager.cpp.
OnTabPosition()
void EditorManager::OnTabPosition (wxCommandEvent & event) private
Definition at line 1638 of file editormanager.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), idNBTabBottom, and ConfigManager::Write().
OnTreeItemActivated()
void EditorManager::OnTreeItemActivated (wxTreeEvent & event) private
OnTreeItemRightClick()
void EditorManager::OnTreeItemRightClick (wxTreeEvent & event) private
OnTreeItemSelected()
void EditorManager::OnTreeItemSelected (wxTreeEvent & event) private
OnUpdateUI()
void EditorManager::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 1731 of file editormanager.cpp.
References Manager::Get(), and cbEditor::GetControl().
Open() [1/2]
cbEditor * EditorManager::Open (const wxString & filename, int pos = 0, ProjectFile * data = nullptr)
Definition at line 352 of file editormanager.cpp.
Referenced by CompilerErrors::DoGotoError(), MainFrame::DoOpenFile(), CodeRefactoring::DoRenameSymbols(), ScriptBindings::EditorManager_Open(), NewFromTemplateDlg::EditScript(), cbProject::LoadLayout(), DocumentationHelper::OnDocumentationLink(), CCDebugInfo::OnGoDeclClick(), CCDebugInfo::OnGoImplClick(), CodeCompletion::OnGotoDeclaration(), ClassBrowser::OnJumpTo(), BreakpointsDlg::OnOpen(), CodeCompletion::OnOpenIncludeFile(), ProjectManagerUI::OnOpenWith(), ScriptingManager::OnScriptMenu(), ClassBrowser::OnTreeItemDoubleClick(), FindReplace::ReplaceInFiles(), cbSearchResultsLog::SyncEditor(), and cbDebuggerPlugin::SyncEditor().
Open() [2/2]
cbEditor * EditorManager::Open (LoaderBase * fileLdr, const wxString & filename, int pos = 0, ProjectFile * data = nullptr)
Definition at line 357 of file editormanager.cpp.
References _T, LogManager::DebugLog(), ProjectFile::file, ProjectManager::FindProjectForFile(), Manager::Get(), cbEditor::GetControl(), Manager::GetFileManager(), EditorBase::GetFilename(), wxFileName::GetFullPath(), Manager::GetLogManager(), cbEditor::GetProjectFile(), Manager::GetProjectManager(), EditorBase::IsBuiltinEditor(), ProjectManager::IsLoading(), cbEditor::IsOK(), FileManager::Load(), NormalizePath(), realpath(), cbEditor::SetProjectFile(), UnixFilename(), wxEmptyString, and wxFileExists().
OpenContainingFolder()
bool EditorManager::OpenContainingFolder ()
Definition at line 1084 of file editormanager.cpp.
References _T, DEFAULT_CONSOLE_SHELL, Manager::Get(), Manager::GetConfigManager(), EditorBase::GetFilename(), wxArrayString::IsEmpty(), wxString::IsEmpty(), ConfigManager::Read(), ConfigManager::ReadBool(), wxFileName::SplitPath(), wxString::StartsWith(), ConfigManager::Write(), wxEXEC_SYNC, and wxExecute().
Referenced by cbEditor::OnContextMenuEntry().
operator=()
EditorManager& EditorManager::operator= (cb_unused const EditorManager & rhs) inline
Definition at line 64 of file editormanager.h.
References _T, and cbThrow.
Print()
void EditorManager::Print (PrintScope ps, PrintColourMode pcm, bool line_numbers)
Definition at line 782 of file editormanager.cpp.
References cbEditor::Print(), psActiveEditor, psAllOpenEditors, and psSelection.
Referenced by MainFrame::OnFilePrint().
QueryClose()
bool EditorManager::QueryClose (EditorBase * editor)
Definition at line 662 of file editormanager.cpp.
References EditorBase::QueryClose().
Referenced by cbProject::QueryCloseAllFiles().
QueryCloseAll()
bool EditorManager::QueryCloseAll ()
Definition at line 580 of file editormanager.cpp.
RebuildNotebookStack()
void EditorManager::RebuildNotebookStack ()
Definition at line 257 of file editormanager.cpp.
References cbNotebookStack::next.
Referenced by EnvironmentSettingsDlg::EndModal().
RecreateOpenEditorStyles()
void EditorManager::RecreateOpenEditorStyles ()
Definition at line 268 of file editormanager.cpp.
References cbEditor::FixFoldState(), cbEditor::SaveFoldState(), and cbEditor::SetEditorStyle().
Referenced by MainFrame::OnSettingsEditor(), and MainFrame::OnSettingsEnvironment().
RemoveCustomEditor()
void EditorManager::RemoveCustomEditor (EditorBase * eb)
Definition at line 520 of file editormanager.cpp.
Referenced by EditorBase::~EditorBase().
RemoveEditorBase()
void EditorManager::RemoveEditorBase (EditorBase * eb, bool deleteObject = true) protected
Definition at line 536 of file editormanager.cpp.
References Manager::IsAppShuttingDown().
Save() [1/2]
bool EditorManager::Save (const wxString & filename)
Definition at line 712 of file editormanager.cpp.
References EditorBase::Save().
Referenced by CompilerGCC::CompileFileWithoutProject(), ScriptBindings::EditorManager_Save(), ProjectManagerUI::OnSaveFile(), and cbProject::SaveAllFiles().
Save() [2/2]
bool EditorManager::Save (int index)
Definition at line 724 of file editormanager.cpp.
References EditorBase::Save().
SaveActive()
bool EditorManager::SaveActive ()
Definition at line 736 of file editormanager.cpp.
References EditorBase::Save().
Referenced by ScriptBindings::RegisterBindings().
SaveActiveAs()
bool EditorManager::SaveActiveAs ()
Definition at line 756 of file editormanager.cpp.
References EditorBase::SaveAs().
Referenced by MainFrame::OnFileSaveAs(), and ScriptBindings::RegisterBindings().
SaveAll()
bool EditorManager::SaveAll ()
Definition at line 766 of file editormanager.cpp.
References _(), wxString::c_str(), cbMessageBox(), EditorBase::GetFilename(), EditorBase::GetModified(), wxString::Printf(), EditorBase::Save(), and wxICON_ERROR.
Referenced by EditorBase::OnContextMenuEntry(), MainFrame::OnFileSaveAll(), MainFrame::OnFileSaveAllFiles(), and ScriptBindings::RegisterBindings().
SaveAs()
bool EditorManager::SaveAs (int index)
Definition at line 748 of file editormanager.cpp.
References EditorBase::SaveAs().
Referenced by ScriptBindings::RegisterBindings().
SetActiveEditor()
void EditorManager::SetActiveEditor (EditorBase * ed)
Definition at line 450 of file editormanager.cpp.
References cbEVT_EDITOR_ACTIVATED, cbEVT_EDITOR_SWITCHED, Manager::Get(), Manager::GetPluginManager(), EditorBase::IsBuiltinEditor(), and PluginManager::NotifyPlugins().
Referenced by EditorBase::Activate(), EditorBase::OnContextMenuEntry(), and FindReplace::ReplaceInFiles().
SetColourSet()
void EditorManager::SetColourSet (EditorColourSet * theme)
Definition at line 336 of file editormanager.cpp.
References cbEditor::SetColourSet().
Referenced by EditorConfigurationDlg::EndModal().
SetSelectionClipboard()
void EditorManager::SetSelectionClipboard (const wxString & data)
Definition at line 1976 of file editormanager.cpp.
Referenced by cbEditor::OnEditorUpdateUI().
SetZoom()
void EditorManager::SetZoom (int zoom)
Definition at line 1936 of file editormanager.cpp.
Referenced by EditorConfigurationDlg::EndModal(), and cbEditor::OnZoom().
ShowNotebook()
void EditorManager::ShowNotebook ()
Shows the previously hidden editor notebook.
Definition at line 1725 of file editormanager.cpp.
Referenced by cbProject::CloseAllFiles(), and cbProject::LoadLayout().
SwapActiveHeaderSource()
bool EditorManager::SwapActiveHeaderSource ()
Definition at line 1134 of file editormanager.cpp.
References _(), _T, wxArrayString::Add(), ProjectManager::AddFileToProject(), ProjectFile::AutoGeneratedBy(), cbMessageBox(), wxArrayString::Clear(), FileFilters::CPP_EXT, ProjectFile::file, FileTypeOf(), ftHeader, ftSource, ftTemplateSource, ProjectFile::generatedFiles, Manager::Get(), ProjectManager::GetActiveProject(), wxDir::GetAllFiles(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), wxArrayString::GetCount(), cbProject::GetFileByFilename(), EditorBase::GetFilename(), cbProject::GetFilesList(), wxFileName::GetFullPath(), CompileOptionsBase::GetIncludeDirs(), Manager::GetMacrosManager(), ProjectFile::GetParentProject(), wxFileName::GetPath(), cbEditor::GetProjectFile(), Manager::GetProjectManager(), ProjectManager::GetUI(), FileFilters::H_EXT, wxArrayString::Index(), wxFileName::IsAbsolute(), wxFileName::Normalize(), cbProjectManagerUI::RebuildTree(), MacrosManager::ReplaceMacros(), cbEditor::SetProjectFile(), wxDIR_FILES, wxDIR_HIDDEN, wxICON_QUESTION, wxID_YES, wxNOT_FOUND, wxPATH_NORM_ALL, wxPATH_NORM_CASE, wxSetWorkingDirectory(), and wxYES_NO.
Referenced by cbEditor::OnContextMenuEntry(), MainFrame::OnEditSwapHeaderSource(), and ScriptBindings::RegisterBindings().
UpdateProjectFiles()
bool EditorManager::UpdateProjectFiles (cbProject * project)
Definition at line 546 of file editormanager.cpp.
References ProjectFile::editorTabPos, ProjectFile::GetParentProject(), cbEditor::GetProjectFile(), and cbEditor::UpdateProjectFile().
Referenced by ProjectManager::CloseProject().
Friends And Related Function Documentation
EditorManagerInternalData
friend struct EditorManagerInternalData friend
Definition at line 207 of file editormanager.h.
Manager
friend class Manager friend
Definition at line 70 of file editormanager.h.
Mgr< EditorManager >
friend class Mgr< EditorManager > friend
Definition at line 61 of file editormanager.h.
Member Data Documentation
m_isCheckingForExternallyModifiedFiles
bool EditorManager::m_isCheckingForExternallyModifiedFiles private
Definition at line 206 of file editormanager.h.
m_nNotebookStackSize
size_t EditorManager::m_nNotebookStackSize private
Definition at line 203 of file editormanager.h.
m_pData
EditorManagerInternalData* EditorManager::m_pData private
Definition at line 208 of file editormanager.h.
m_pNotebook
cbAuiNotebook* EditorManager::m_pNotebook private
Definition at line 200 of file editormanager.h.
m_pNotebookStackHead
cbNotebookStack* EditorManager::m_pNotebookStackHead private
Definition at line 201 of file editormanager.h.
m_pNotebookStackTail
cbNotebookStack* EditorManager::m_pNotebookStackTail private
Definition at line 202 of file editormanager.h.
m_Theme
EditorColourSet* EditorManager::m_Theme private
Definition at line 204 of file editormanager.h.
m_Zoom
int EditorManager::m_Zoom private
Definition at line 205 of file editormanager.h.
s_CanShutdown
bool EditorManager::s_CanShutdown = true static private
Definition at line 62 of file editormanager.h.
The documentation for this class was generated from the following files:
editormanager.h
editormanager.cpp