Code::Blocks: GdbCmd_Watch Class Reference
GdbCmd_Watch Class Reference
Command to get info about a watched variable.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_Watch (DebuggerDriver *driver, cb::shared_ptr< GDBWatch > watch)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
cb::shared_ptr< GDBWatch > m_watch
wxString m_ParseFunc
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to get info about a watched variable.
Definition at line 777 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_Watch()
GdbCmd_Watch::GdbCmd_Watch (DebuggerDriver * driver, cb::shared_ptr< GDBWatch > watch) inline
Definition at line 782 of file gdb_commands.h.
References Any, Binary, cbC2U(), cbU2C(), Char, Decimal, Float, Hex, Last, DebuggerCmd::m_Cmd, DebuggerCmd::m_pDriver, Undefined, and Unsigned.
Member Function Documentation
ParseOutput()
void GdbCmd_Watch::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 836 of file gdb_commands.h.
References cbC2U(), cbU2C(), Manager::Get(), Manager::GetLogManager(), LogManager::LogError(), and ParseGDBWatchValue().
Member Data Documentation
m_ParseFunc
wxString GdbCmd_Watch::m_ParseFunc private
Definition at line 780 of file gdb_commands.h.
m_watch
cb::shared_ptr<GDBWatch> GdbCmd_Watch::m_watch private
Definition at line 779 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h