Code::Blocks: SystemHeadersThread Class Reference
SystemHeadersThread Class Reference
#include <systemheadersthread.h>
Public Member Functions
SystemHeadersThread (wxEvtHandler *parent, wxCriticalSection *critSect, SystemHeadersMap &headersMap, const wxArrayString &incDirs)
virtual ~SystemHeadersThread ()
virtual void * Entry ()
Public Member Functions inherited from wxThread
wxThread (wxThreadKind kind=wxTHREAD_DETACHED)
virtual ~wxThread ()
wxThreadError Create (unsigned int stackSize=0)
wxThreadError Delete (ExitCode *rc=NULL, wxThreadWait waitMode=wxTHREAD_WAIT_BLOCK)
wxThreadIdType GetId () const
wxThreadKind GetKind () const
unsigned int GetPriority () const
bool IsAlive () const
bool IsDetached () const
bool IsPaused () const
bool IsRunning () const
wxThreadError Kill ()
wxThreadError Pause ()
wxThreadError Resume ()
wxThreadError Run ()
void SetPriority (unsigned int priority)
virtual bool TestDestroy ()
ExitCode Wait (wxThreadWait flags=wxTHREAD_WAIT_BLOCK)
Private Attributes
wxEvtHandler * m_Parent
wxCriticalSection * m_SystemHeadersThreadCS
SystemHeadersMap & m_SystemHeadersMap
wxArrayString m_IncludeDirs
Additional Inherited Members
Public Types inherited from wxThread
typedef void * ExitCode
Static Public Member Functions inherited from wxThread
static int GetCPUCount ()
static wxThreadIdType GetCurrentId ()
static wxThreadIdType GetMainId ()
static bool IsMain ()
static bool SetConcurrency (size_t level)
static void Sleep (unsigned long milliseconds)
static wxThread * This ()
static void Yield ()
Protected Member Functions inherited from wxThread
void Exit (ExitCode exitcode=0)
Detailed Description
Definition at line 25 of file systemheadersthread.h.
Constructor & Destructor Documentation
SystemHeadersThread()
SystemHeadersThread::SystemHeadersThread (wxEvtHandler * parent, wxCriticalSection * critSect, SystemHeadersMap & headersMap, const wxArrayString & incDirs)
Definition at line 114 of file systemheadersthread.cpp.
References wxThread::Create(), wxThread::SetPriority(), and wxTHREAD_JOINABLE.
~SystemHeadersThread()
SystemHeadersThread::~SystemHeadersThread () virtual
Definition at line 128 of file systemheadersthread.cpp.
References _T, and TRACE.
Member Function Documentation
Entry()
void * SystemHeadersThread::Entry () virtual
Implements wxThread.
Definition at line 133 of file systemheadersthread.cpp.
References _T, wxArrayString::Add(), wxString::Format(), wxArrayString::GetCount(), idSystemHeadersThreadError, idSystemHeadersThreadFinish, idSystemHeadersThreadUpdate, wxArrayString::IsEmpty(), wxDir::IsOpened(), m_IncludeDirs, m_Parent, m_SystemHeadersMap, m_SystemHeadersThreadCS, NULL, wxThread::TestDestroy(), TRACE, wxDir::Traverse(), wxDIR_DIRS, wxDIR_FILES, wxEmptyString, and wxPostEvent().
Member Data Documentation
m_IncludeDirs
wxArrayString SystemHeadersThread::m_IncludeDirs private
Definition at line 38 of file systemheadersthread.h.
Referenced by Entry().
m_Parent
wxEvtHandler* SystemHeadersThread::m_Parent private
Definition at line 35 of file systemheadersthread.h.
Referenced by Entry().
m_SystemHeadersMap
SystemHeadersMap& SystemHeadersThread::m_SystemHeadersMap private
Definition at line 37 of file systemheadersthread.h.
Referenced by Entry().
m_SystemHeadersThreadCS
wxCriticalSection* SystemHeadersThread::m_SystemHeadersThreadCS private
Definition at line 36 of file systemheadersthread.h.
Referenced by Entry().
The documentation for this class was generated from the following files:
systemheadersthread.h
systemheadersthread.cpp