Code::Blocks: ExternalDepsDlg Class Reference
ExternalDepsDlg Class Reference
#include <externaldepsdlg.h>
Public Member Functions
ExternalDepsDlg (wxWindow *parent, cbProject *project, ProjectBuildTarget *target)
virtual ~ExternalDepsDlg ()
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void FillAdditional ()
void FillExternal ()
void OnAddAdditional (wxCommandEvent &event)
void OnEditAdditional (wxCommandEvent &event)
void OnDelAdditional (wxCommandEvent &event)
void OnAddExternal (wxCommandEvent &event)
void OnEditExternal (wxCommandEvent &event)
void OnDelExternal (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
Protected Attributes
cbProject * m_pProject
ProjectBuildTarget * m_pTarget
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Constructor & Destructor Documentation
ExternalDepsDlg::ExternalDepsDlg (wxWindow * parent, cbProject * project, ProjectBuildTarget * target)
ExternalDepsDlg::~ExternalDepsDlg () virtual
Member Function Documentation
void ExternalDepsDlg::EndModal (int retCode)
References ScriptBindings::EndModal(), m_pTarget, ProjectBuildTarget::SetAdditionalOutputFiles(), and ProjectBuildTarget::SetExternalDeps().
void ExternalDepsDlg::FillAdditional () protected
References ProjectBuildTarget::GetAdditionalOutputFiles(), GetArrayFromString(), and m_pTarget.
void ExternalDepsDlg::FillExternal () protected
References GetArrayFromString(), ProjectBuildTarget::GetExternalDeps(), and m_pTarget.
void ExternalDepsDlg::OnAddAdditional (wxCommandEvent & event) protected
References DoAdd.
void ExternalDepsDlg::OnAddExternal (wxCommandEvent & event) protected
References DoAdd.
void ExternalDepsDlg::OnDelAdditional (wxCommandEvent & event) protected
References DoDel.
void ExternalDepsDlg::OnDelExternal (wxCommandEvent & event) protected
References DoDel.
void ExternalDepsDlg::OnEditAdditional (wxCommandEvent & event) protected
References DoEdit.
void ExternalDepsDlg::OnEditExternal (wxCommandEvent & event) protected
References DoEdit.
void ExternalDepsDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Member Data Documentation
cbProject* ExternalDepsDlg::m_pProject protected
ProjectBuildTarget* ExternalDepsDlg::m_pTarget protected
Referenced by EndModal(), FillAdditional(), and FillExternal().
The documentation for this class was generated from the following files:
externaldepsdlg.h
externaldepsdlg.cpp