Code::Blocks: ProjectTemplateLoader Class Reference
ProjectTemplateLoader Class Reference
#include <projecttemplateloader.h>
Public Member Functions
ProjectTemplateLoader ()
virtual ~ProjectTemplateLoader ()
bool Open (const wxString &filename)
Public Attributes
wxString m_Name
wxString m_Notice
int m_NoticeMsgType
wxString m_Title
wxString m_Category
wxString m_Bitmap
FileSetArray m_FileSets
TemplateOptionArray m_TemplateOptions
Protected Member Functions
void DoTemplate (TiXmlElement *parentNode)
void DoTemplateNotice (TiXmlElement *parentNode)
void DoFileSet (TiXmlElement *parentNode)
void DoFileSetFile (TiXmlElement *parentNode, FileSet &fs)
void DoOption (TiXmlElement *parentNode)
void DoOptionProject (TiXmlElement *parentNode, TemplateOption &to)
void DoOptionCompiler (TiXmlElement *parentNode, TemplateOption &to)
void DoOptionLinker (TiXmlElement *parentNode, TemplateOption &to)
Detailed Description
Definition at line 40 of file projecttemplateloader.h.
Constructor & Destructor Documentation
ProjectTemplateLoader()
ProjectTemplateLoader::ProjectTemplateLoader ()
Definition at line 25 of file projecttemplateloader.cpp.
~ProjectTemplateLoader()
ProjectTemplateLoader::~ProjectTemplateLoader () virtual
Definition at line 30 of file projecttemplateloader.cpp.
Member Function Documentation
DoFileSet()
void ProjectTemplateLoader::DoFileSet (TiXmlElement * parentNode) protected
Definition at line 100 of file projecttemplateloader.cpp.
References cbC2U(), DoFileSetFile(), wxString::IsEmpty(), m_FileSets, FileSet::name, and FileSet::title.
Referenced by DoTemplate().
DoFileSetFile()
void ProjectTemplateLoader::DoFileSetFile (TiXmlElement * parentNode, FileSet & fs) protected
Definition at line 121 of file projecttemplateloader.cpp.
References cbC2U(), FileSetFile::destination, FileSet::files, wxString::IsEmpty(), FileSetFile::source, and FileSetFile::targets.
Referenced by DoFileSet().
DoOption()
void ProjectTemplateLoader::DoOption (TiXmlElement * parentNode) protected
Definition at line 141 of file projecttemplateloader.cpp.
References _T, cbC2U(), DoOptionCompiler(), DoOptionLinker(), DoOptionProject(), wxString::IsEmpty(), m_TemplateOptions, TemplateOption::name, TemplateOption::notice, TemplateOption::noticeMsgType, wxString::Replace(), TemplateOption::useDefaultCompiler, wxICON_INFORMATION, and wxICON_WARNING.
Referenced by DoTemplate().
DoOptionCompiler()
void ProjectTemplateLoader::DoOptionCompiler (TiXmlElement * parentNode, TemplateOption & to) protected
Definition at line 186 of file projecttemplateloader.cpp.
References wxArrayString::Add(), cbC2U(), and TemplateOption::extraCFlags.
Referenced by DoOption().
DoOptionLinker()
void ProjectTemplateLoader::DoOptionLinker (TiXmlElement * parentNode, TemplateOption & to) protected
Definition at line 198 of file projecttemplateloader.cpp.
References wxArrayString::Add(), cbC2U(), and TemplateOption::extraLDFlags.
Referenced by DoOption().
DoOptionProject()
void ProjectTemplateLoader::DoOptionProject (TiXmlElement * parentNode, TemplateOption & to) protected
Definition at line 174 of file projecttemplateloader.cpp.
References cbC2U(), TemplateOption::file, and TemplateOption::useDefaultCompiler.
Referenced by DoOption().
DoTemplate()
void ProjectTemplateLoader::DoTemplate (TiXmlElement * parentNode) protected
Definition at line 66 of file projecttemplateloader.cpp.
References cbC2U(), DoFileSet(), DoOption(), DoTemplateNotice(), m_Bitmap, m_Category, m_Name, and m_Title.
Referenced by Open().
DoTemplateNotice()
void ProjectTemplateLoader::DoTemplateNotice (TiXmlElement * parentNode) protected
Definition at line 88 of file projecttemplateloader.cpp.
References _T, cbC2U(), m_Notice, m_NoticeMsgType, wxString::Replace(), wxICON_INFORMATION, and wxICON_WARNING.
Referenced by DoTemplate().
Open()
bool ProjectTemplateLoader::Open (const wxString & filename)
Definition at line 35 of file projecttemplateloader.cpp.
References _T, LogManager::DebugLog(), DoTemplate(), Manager::Get(), Manager::GetLogManager(), and wxString::mb_str().
Member Data Documentation
m_Bitmap
wxString ProjectTemplateLoader::m_Bitmap
Definition at line 53 of file projecttemplateloader.h.
Referenced by DoTemplate().
m_Category
wxString ProjectTemplateLoader::m_Category
Definition at line 52 of file projecttemplateloader.h.
Referenced by DoTemplate().
m_FileSets
FileSetArray ProjectTemplateLoader::m_FileSets
Definition at line 54 of file projecttemplateloader.h.
Referenced by DoFileSet().
m_Name
wxString ProjectTemplateLoader::m_Name
Definition at line 48 of file projecttemplateloader.h.
Referenced by DoTemplate().
m_Notice
wxString ProjectTemplateLoader::m_Notice
Definition at line 49 of file projecttemplateloader.h.
Referenced by DoTemplateNotice().
m_NoticeMsgType
int ProjectTemplateLoader::m_NoticeMsgType
Definition at line 50 of file projecttemplateloader.h.
Referenced by DoTemplateNotice().
m_TemplateOptions
TemplateOptionArray ProjectTemplateLoader::m_TemplateOptions
Definition at line 55 of file projecttemplateloader.h.
Referenced by DoOption().
m_Title
wxString ProjectTemplateLoader::m_Title
Definition at line 51 of file projecttemplateloader.h.
Referenced by DoTemplate(), and SortTemplates().
The documentation for this class was generated from the following files:
projecttemplateloader.h
projecttemplateloader.cpp