Code::Blocks: cbDisassemblyDlg Class Reference
cbDisassemblyDlg Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbDisassemblyDlg ()
virtual wxWindow * GetWindow ()=0
virtual void Clear (const cbStackFrame &frame)=0
virtual void AddAssemblerLine (uint64_t addr, const wxString &line)=0
virtual void AddSourceLine (int lineno, const wxString &line)=0
virtual bool SetActiveAddress (uint64_t addr)=0
virtual void CenterLine (int lineno)=0
virtual void CenterCurrentLine ()=0
virtual bool HasActiveAddr ()=0
virtual void EnableWindow (bool enable)=0
Detailed Description
Definition at line 57 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
~cbDisassemblyDlg()
cbDisassemblyDlg::~cbDisassemblyDlg () virtual
Definition at line 15 of file cbdebugger_interfaces.cpp.
Member Function Documentation
AddAssemblerLine()
virtual void cbDisassemblyDlg::AddAssemblerLine (uint64_t addr, const wxString & line) pure virtual
Implemented in DisassemblyDlg.
Referenced by CdbCmd_Disassembly::ParseOutput(), and GdbCmd_Disassembly::ParseOutput().
AddSourceLine()
virtual void cbDisassemblyDlg::AddSourceLine (int lineno, const wxString & line) pure virtual
Implemented in DisassemblyDlg.
Referenced by GdbCmd_Disassembly::ParseOutput().
CenterCurrentLine()
virtual void cbDisassemblyDlg::CenterCurrentLine () pure virtual
Implemented in DisassemblyDlg.
Referenced by GdbCmd_Disassembly::ParseOutput().
CenterLine()
virtual void cbDisassemblyDlg::CenterLine (int lineno) pure virtual
Implemented in DisassemblyDlg.
Clear()
virtual void cbDisassemblyDlg::Clear (const cbStackFrame & frame) pure virtual
Implemented in DisassemblyDlg.
Referenced by CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_StepOrNextInstruction::ParseOutput(), and GDB_driver::Start().
EnableWindow()
virtual void cbDisassemblyDlg::EnableWindow (bool enable) pure virtual
Implemented in DisassemblyDlg.
Referenced by DebuggerManager::RefreshUI(), and DebuggerManager::SetInterfaceFactory().
GetWindow()
virtual wxWindow* cbDisassemblyDlg::GetWindow () pure virtual
Implemented in DisassemblyDlg.
Referenced by DebugInterfaceFactory::DeleteDisassembly(), and DebuggerManager::UpdateDisassembly().
HasActiveAddr()
virtual bool cbDisassemblyDlg::HasActiveAddr () pure virtual
Implemented in DisassemblyDlg.
SetActiveAddress()
virtual bool cbDisassemblyDlg::SetActiveAddress (uint64_t addr) pure virtual
Implemented in DisassemblyDlg.
Referenced by DebuggerGDB::OnCursorChanged(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_StepOrNextInstruction::ParseOutput().
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp