Code::Blocks: DebuggerMenuHandler Class Reference
DebuggerMenuHandler Class Reference
#include <debuggermenu.h>
Classes
struct WindowMenuItem
Public Member Functions
DebuggerMenuHandler ()
void RegisterDefaultWindowItems ()
void AppendWindowMenuItems (wxMenu &menu)
virtual void SetActiveDebugger (cbDebuggerPlugin *active)
virtual void MarkActiveTargetAsValid (bool valid)
virtual void RebuildMenus ()
virtual void BuildContextMenu (wxMenu &menu, const wxString &word_at_caret, bool is_running)
virtual bool RegisterWindowMenu (const wxString &name, const wxString &help, cbDebuggerWindowMenuItem *item)
virtual void UnregisterWindowMenu (const wxString &name)
Public Member Functions inherited from cbDebuggerMenuHandler
virtual ~cbDebuggerMenuHandler ()
Private Types
typedef std::map< long, WindowMenuItem > WindowMenuItemsMap
Private Member Functions
void OnUpdateUI (wxUpdateUIEvent &event)
void OnStart (wxCommandEvent &event)
void OnBreak (wxCommandEvent &event)
void OnStop (wxCommandEvent &event)
void OnContinue (wxCommandEvent &event)
void OnNext (wxCommandEvent &event)
void OnNextInstr (wxCommandEvent &event)
void OnStepIntoInstr (wxCommandEvent &event)
void OnStep (wxCommandEvent &event)
void OnStepOut (wxCommandEvent &event)
void OnRunToCursor (wxCommandEvent &event)
void OnSetNextStatement (wxCommandEvent &event)
void OnToggleBreakpoint (wxCommandEvent &event)
void OnRemoveAllBreakpoints (wxCommandEvent &event)
void OnAddDataBreakpoint (wxCommandEvent &event)
void OnSendCommand (wxCommandEvent &event)
void OnAttachToProcess (wxCommandEvent &event)
void OnDetachFromProcess (wxCommandEvent &event)
void OnAddWatch (wxCommandEvent &event)
void OnActiveDebuggerClick (wxCommandEvent &event)
void OnActiveDebuggerTargetsDefaultClick (wxCommandEvent &event)
void LogActiveConfig ()
void OnWindowMenuItemUpdateUI (wxUpdateUIEvent &event)
void OnWindowMenuItemClicked (wxCommandEvent &event)
DECLARE_EVENT_TABLE ()
Private Attributes
WindowMenuItemsMap m_windowMenuItems
cbDebuggerPlugin * m_activeDebugger
wxString m_lastCommand
bool m_disableContinue
Detailed Description
Definition at line 15 of file debuggermenu.h.
Class Documentation
DebuggerMenuHandler::WindowMenuItem
struct DebuggerMenuHandler::WindowMenuItem
Definition at line 64 of file debuggermenu.h.
Class Members
wxString help
shared_ptr
< cbDebuggerWindowMenuItem > item
wxString name
Member Typedef Documentation
WindowMenuItemsMap
typedef std::map<long, WindowMenuItem> DebuggerMenuHandler::WindowMenuItemsMap private
Definition at line 69 of file debuggermenu.h.
Constructor & Destructor Documentation
DebuggerMenuHandler()
DebuggerMenuHandler::DebuggerMenuHandler ()
Definition at line 145 of file debuggermenu.cpp.
References cbEVT_HIDE_DOCK_WINDOW, cbEVT_SHOW_DOCK_WINDOW, Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), cbDebuggerWindowMenuItem::IsChecked(), cbDebuggerWindowMenuItem::IsEnabled(), IsWindowReallyShown(), cbDebuggerWindowMenuItem::OnClick(), Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, and cbDebuggerPlugin::RequestUpdate().
Member Function Documentation
AppendWindowMenuItems()
void DebuggerMenuHandler::AppendWindowMenuItems (wxMenu & menu)
Definition at line 316 of file debuggermenu.cpp.
References wxMenu::AppendCheckItem().
BuildContextMenu()
void DebuggerMenuHandler::BuildContextMenu (wxMenu & menu, const wxString & word_at_caret, bool is_running) virtual
Implements cbDebuggerMenuHandler.
Definition at line 405 of file debuggermenu.cpp.
References _(), cbDebuggerFeature::Breakpoints, wxString::c_str(), wxString::empty(), wxString::Format(), Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), wxMenu::Insert(), wxMenu::InsertSeparator(), cbDebuggerFeature::RunToCursor, cbDebuggerFeature::SetNextStatement, cbDebuggerPlugin::SupportsFeature(), and cbDebuggerFeature::Watches.
DECLARE_EVENT_TABLE()
DebuggerMenuHandler::DECLARE_EVENT_TABLE () private
LogActiveConfig()
void DebuggerMenuHandler::LogActiveConfig () private
Definition at line 503 of file debuggermenu.cpp.
References _(), Manager::Get(), DebuggerManager::GetAllDebuggers(), Manager::GetDebuggerManager(), cbDebuggerConfiguration::GetName(), and wxT.
MarkActiveTargetAsValid()
void DebuggerMenuHandler::MarkActiveTargetAsValid (bool valid) virtual
Implements cbDebuggerMenuHandler.
Definition at line 332 of file debuggermenu.cpp.
References _(), wxMenu::FindItem(), wxMenuItem::SetItemLabel(), and wxMenuItem::SetText().
OnActiveDebuggerClick()
void DebuggerMenuHandler::OnActiveDebuggerClick (wxCommandEvent & event) private
Definition at line 733 of file debuggermenu.cpp.
References Manager::Get(), DebuggerManager::GetAllDebuggers(), Manager::GetDebuggerManager(), and DebuggerManager::SetActiveDebugger().
Referenced by RebuildMenus().
OnActiveDebuggerTargetsDefaultClick()
void DebuggerMenuHandler::OnActiveDebuggerTargetsDefaultClick (wxCommandEvent & event) private
Definition at line 752 of file debuggermenu.cpp.
References Manager::Get(), Manager::GetDebuggerManager(), DebuggerToolbarHandler::OnDebugWindows(), DebuggerToolbarHandler::OnStop(), DebuggerToolbarHandler::OnToolInfo(), DebuggerToolbarHandler::OnUpdateUI(), and DebuggerManager::SetTargetsDefaultAsActiveDebugger().
OnAddDataBreakpoint()
void DebuggerMenuHandler::OnAddDataBreakpoint (wxCommandEvent & event) private
Definition at line 672 of file debuggermenu.cpp.
References cbAssert, wxString::empty(), Manager::Get(), DebuggerManager::GetBreakpointDialog(), Manager::GetDebuggerManager(), and cbBreakpointsDlg::Reload().
OnAddWatch()
void DebuggerMenuHandler::OnAddWatch (wxCommandEvent & event) private
Definition at line 710 of file debuggermenu.cpp.
References cbWatchesDlg::AddWatch(), cbEVT_SHOW_DOCK_WINDOW, wxString::empty(), Manager::Get(), Manager::GetDebuggerManager(), DebuggerManager::GetWatchesDialog(), cbWatchesDlg::GetWindow(), IsWindowReallyShown(), Manager::ProcessEvent(), and CodeBlocksDockEvent::pWindow.
OnAttachToProcess()
void DebuggerMenuHandler::OnAttachToProcess (wxCommandEvent & event) private
Definition at line 683 of file debuggermenu.cpp.
References _(), cbAssert, cbGetTextFromUser(), and wxString::empty().
OnBreak()
void DebuggerMenuHandler::OnBreak (wxCommandEvent & event) private
Definition at line 544 of file debuggermenu.cpp.
References cbAssert.
OnContinue()
void DebuggerMenuHandler::OnContinue (wxCommandEvent & event) private
Definition at line 558 of file debuggermenu.cpp.
References cbAssert.
OnDetachFromProcess()
void DebuggerMenuHandler::OnDetachFromProcess (wxCommandEvent & event) private
Definition at line 693 of file debuggermenu.cpp.
References cbAssert.
OnNext()
void DebuggerMenuHandler::OnNext (wxCommandEvent & event) private
Definition at line 568 of file debuggermenu.cpp.
References cbAssert.
OnNextInstr()
void DebuggerMenuHandler::OnNextInstr (wxCommandEvent & event) private
Definition at line 575 of file debuggermenu.cpp.
References cbAssert.
OnRemoveAllBreakpoints()
void DebuggerMenuHandler::OnRemoveAllBreakpoints (wxCommandEvent & event) private
Definition at line 666 of file debuggermenu.cpp.
References cbAssert, Manager::Get(), DebuggerManager::GetBreakpointDialog(), Manager::GetDebuggerManager(), and cbBreakpointsDlg::RemoveAllBreakpoints().
OnRunToCursor()
void DebuggerMenuHandler::OnRunToCursor (wxCommandEvent & event) private
Definition at line 624 of file debuggermenu.cpp.
References cbAssert, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentLine(), Manager::GetEditorManager(), EditorBase::GetFilename(), ProjectManager::GetIsRunning(), wxScintilla::GetLine(), Manager::GetProjectManager(), and ProjectManager::SetIsRunning().
OnSendCommand()
void DebuggerMenuHandler::OnSendCommand (wxCommandEvent & event) private
Definition at line 699 of file debuggermenu.cpp.
References _(), cbAssert, cbGetTextFromUser(), and wxString::IsEmpty().
OnSetNextStatement()
void DebuggerMenuHandler::OnSetNextStatement (wxCommandEvent & event) private
Definition at line 647 of file debuggermenu.cpp.
References cbAssert, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentLine(), Manager::GetEditorManager(), and EditorBase::GetFilename().
OnStart()
void DebuggerMenuHandler::OnStart (wxCommandEvent & event) private
Definition at line 517 of file debuggermenu.cpp.
References cbAssert, Manager::Get(), ProjectManager::GetIsRunning(), Manager::GetProjectManager(), and ProjectManager::SetIsRunning().
OnStep()
void DebuggerMenuHandler::OnStep (wxCommandEvent & event) private
Definition at line 589 of file debuggermenu.cpp.
References cbAssert, Manager::Get(), ProjectManager::GetIsRunning(), Manager::GetProjectManager(), and ProjectManager::SetIsRunning().
OnStepIntoInstr()
void DebuggerMenuHandler::OnStepIntoInstr (wxCommandEvent & event) private
Definition at line 582 of file debuggermenu.cpp.
References cbAssert.
OnStepOut()
void DebuggerMenuHandler::OnStepOut (wxCommandEvent & event) private
Definition at line 617 of file debuggermenu.cpp.
References cbAssert.
OnStop()
void DebuggerMenuHandler::OnStop (wxCommandEvent & event) private
Definition at line 551 of file debuggermenu.cpp.
References cbAssert.
OnToggleBreakpoint()
void DebuggerMenuHandler::OnToggleBreakpoint (wxCommandEvent & event) private
Definition at line 657 of file debuggermenu.cpp.
References cbAssert, Manager::Get(), EditorManager::GetBuiltinActiveEditor(), Manager::GetEditorManager(), and cbEditor::ToggleBreakpoint().
OnUpdateUI()
void DebuggerMenuHandler::OnUpdateUI (wxUpdateUIEvent & event) private
Definition at line 441 of file debuggermenu.cpp.
References cbDebuggerFeature::Breakpoints, wxMenuBar::Enable(), wxMenu::Enable(), wxMenu::FindItemByPosition(), Manager::Get(), ProjectManager::GetActiveProject(), Manager::GetAppFrame(), EditorManager::GetBuiltinActiveEditor(), cbProject::GetCurrentlyCompilingTarget(), Manager::GetEditorManager(), wxMenuItem::GetId(), ProjectManager::GetIsRunning(), wxMenu::GetMenuItemCount(), Manager::GetProjectManager(), NULL, cbDebuggerFeature::RunToCursor, and cbDebuggerFeature::SetNextStatement.
OnWindowMenuItemClicked()
void DebuggerMenuHandler::OnWindowMenuItemClicked (wxCommandEvent & event) private
Definition at line 309 of file debuggermenu.cpp.
Referenced by RegisterWindowMenu().
OnWindowMenuItemUpdateUI()
void DebuggerMenuHandler::OnWindowMenuItemUpdateUI (wxUpdateUIEvent & event) private
Definition at line 299 of file debuggermenu.cpp.
Referenced by RegisterWindowMenu().
RebuildMenus()
void DebuggerMenuHandler::RebuildMenus () virtual
Implements cbDebuggerMenuHandler.
Definition at line 346 of file debuggermenu.cpp.
References _(), wxMenu::AppendRadioItem(), cbAssert, wxMenu::Check(), Manager::Get(), DebuggerManager::GetAllDebuggers(), Manager::GetDebuggerManager(), DebuggerManager::IsActiveDebuggerTargetsDefault(), OnActiveDebuggerClick(), wxID_ANY, wxNewId(), and wxT.
RegisterDefaultWindowItems()
void DebuggerMenuHandler::RegisterDefaultWindowItems ()
Definition at line 202 of file debuggermenu.cpp.
References _(), cbDebuggerPlugin::Backtrace, cbDebuggerFeature::Callstack, cbEVT_HIDE_DOCK_WINDOW, cbEVT_SHOW_DOCK_WINDOW, cbDebuggerFeature::CPURegisters, cbDebuggerPlugin::CPURegisters, cbDebuggerFeature::Disassembly, cbDebuggerPlugin::Disassembly, cbDebuggerFeature::ExamineMemory, cbDebuggerPlugin::ExamineMemory, Manager::Get(), DebuggerManager::GetBacktraceDialog(), DebuggerManager::GetBreakpointDialog(), DebuggerManager::GetCPURegistersDialog(), Manager::GetDebuggerManager(), DebuggerManager::GetDisassemblyDialog(), DebuggerManager::GetExamineMemoryDialog(), DebuggerManager::GetThreadsDialog(), DebuggerManager::GetWatchesDialog(), cbBreakpointsDlg::GetWindow(), IsWindowReallyShown(), Manager::ProcessEvent(), CodeBlocksDockEvent::pWindow, cbDebuggerFeature::Threads, cbDebuggerPlugin::Threads, cbDebuggerFeature::Watches, and cbDebuggerPlugin::Watches.
RegisterWindowMenu()
bool DebuggerMenuHandler::RegisterWindowMenu (const wxString & name, const wxString & help, cbDebuggerWindowMenuItem * item) virtual
Implements cbDebuggerMenuHandler.
Definition at line 258 of file debuggermenu.cpp.
References _(), LogManager::DebugLog(), Logger::error, wxString::Format(), Manager::Get(), Manager::GetLogManager(), DebuggerMenuHandler::WindowMenuItem::help, DebuggerMenuHandler::WindowMenuItem::item, DebuggerMenuHandler::WindowMenuItem::name, OnWindowMenuItemClicked(), OnWindowMenuItemUpdateUI(), wxString::wx_str(), wxEVT_UPDATE_UI, and wxNewId().
SetActiveDebugger()
void DebuggerMenuHandler::SetActiveDebugger (cbDebuggerPlugin * active) virtual
Implements cbDebuggerMenuHandler.
Definition at line 327 of file debuggermenu.cpp.
UnregisterWindowMenu()
void DebuggerMenuHandler::UnregisterWindowMenu (const wxString & name) virtual
Implements cbDebuggerMenuHandler.
Definition at line 284 of file debuggermenu.cpp.
References wxEVT_UPDATE_UI.
Member Data Documentation
m_activeDebugger
cbDebuggerPlugin* DebuggerMenuHandler::m_activeDebugger private
Definition at line 72 of file debuggermenu.h.
m_disableContinue
bool DebuggerMenuHandler::m_disableContinue private
Definition at line 74 of file debuggermenu.h.
m_lastCommand
wxString DebuggerMenuHandler::m_lastCommand private
Definition at line 73 of file debuggermenu.h.
m_windowMenuItems
WindowMenuItemsMap DebuggerMenuHandler::m_windowMenuItems private
Definition at line 71 of file debuggermenu.h.
The documentation for this class was generated from the following files:
debuggermenu.h
debuggermenu.cpp