Code::Blocks: ProgressDialog Class Reference
ProgressDialog Class Reference
Public Member Functions
ProgressDialog ()
~ProgressDialog ()
ProgressDialog & operator= (const ProgressDialog &)
bool DoUpdate (int value, const wxString &newmsg)
Public Member Functions inherited from wxProgressDialog
wxProgressDialog (const wxString &title, const wxString &message, int maximum=100, wxWindow *parent=NULL, int style=wxPD_APP_MODAL|wxPD_AUTO_HIDE)
Public Member Functions inherited from wxGenericProgressDialog
wxGenericProgressDialog (const wxString &title, const wxString &message, int maximum=100, wxWindow *parent=NULL, int style=wxPD_AUTO_HIDE|wxPD_APP_MODAL)
virtual ~wxGenericProgressDialog ()
int GetValue () const
int GetRange () const
wxString GetMessage () const
virtual bool Pulse (const wxString &newmsg=wxEmptyString, bool *skip=NULL)
void Resume ()
void SetRange (int maximum)
bool WasCancelled () const
bool WasSkipped () const
virtual bool Update (int value, const wxString &newmsg=wxEmptyString, bool *skip=NULL)
Public Member Functions inherited from wxDialog
virtual int ShowModal ()
Detailed Description
Definition at line 22 of file sc_progress.cpp.
Constructor & Destructor Documentation
ProgressDialog()
ProgressDialog::ProgressDialog () inline
Definition at line 25 of file sc_progress.cpp.
References wxPD_APP_MODAL, wxPD_AUTO_HIDE, and wxPD_CAN_ABORT.
~ProgressDialog()
ProgressDialog::~ProgressDialog () inline
Definition at line 33 of file sc_progress.cpp.
Member Function Documentation
DoUpdate()
bool ProgressDialog::DoUpdate (int value, const wxString & newmsg) inline
Definition at line 42 of file sc_progress.cpp.
References DECLARE_INSTANCE_TYPE(), and wxGenericProgressDialog::Update().
Referenced by ScriptBindings::Register_ProgressDialog().
operator=()
ProgressDialog& ProgressDialog::operator= (const ProgressDialog &) inline
Definition at line 37 of file sc_progress.cpp.
References _T, and cbThrow.
The documentation for this class was generated from the following file:
sc_progress.cpp