Code::Blocks: FileLogger Class Reference
FileLogger Class Reference
a logger which prints messages to a file
#include <loggers.h>
Public Member Functions
FileLogger (const wxString &filename)
FileLogger ()
virtual void Append (const wxString &msg, cb_unused Logger::level lv)
virtual void Open (const wxString &filename)
virtual void Close ()
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void Append (const wxString &msg, Logger::level lv=info)=0
virtual void Clear ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual void UpdateSettings ()
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool GetWrapMode () const
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Protected Attributes
wxFFile f
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Detailed Description
a logger which prints messages to a file
Definition at line 40 of file loggers.h.
Constructor & Destructor Documentation
FileLogger() [1/2]
FileLogger::FileLogger (const wxString & filename) inline
Definition at line 45 of file loggers.h.
References _T.
FileLogger() [2/2]
FileLogger::FileLogger () inline
Definition at line 46 of file loggers.h.
Member Function Documentation
Append()
virtual void FileLogger::Append (const wxString & msg, cb_unused Logger::level lv) inline virtual
Definition at line 48 of file loggers.h.
References wxFFile::fp().
Close()
virtual void FileLogger::Close () inline virtual
Reimplemented in HTMLFileLogger.
Definition at line 55 of file loggers.h.
References wxFFile::Close(), and wxFFile::IsOpened().
Referenced by HTMLFileLogger::Close().
Open()
virtual void FileLogger::Open (const wxString & filename) inline virtual
Reimplemented in HTMLFileLogger.
Definition at line 54 of file loggers.h.
References _T, and wxFFile::Open().
Referenced by HTMLFileLogger::Open().
Member Data Documentation
f
wxFFile FileLogger::f protected
Definition at line 43 of file loggers.h.
The documentation for this class was generated from the following file:
loggers.h