Code::Blocks: ProjectManager Class Reference
ProjectManager Class Reference
The entry point singleton for working with projects.
#include <projectmanager.h>
Public Member Functions
cbProjectManagerUI & GetUI ()
void SetUI (cbProjectManagerUI *ui)
const FilesGroupsAndMasks * GetFilesGroupsAndMasks () const
FilesGroupsAndMasks * GetFilesGroupsAndMasks ()
wxString GetDefaultPath ()
Retrieve the default path for new projects.
void SetDefaultPath (const wxString &path)
Set the default path for new projects.
bool IsProjectStillOpen (cbProject *project)
Is this a valid project? (i.e.
cbProject * GetActiveProject ()
Retrieve the active project.
ProjectsArray * GetProjects ()
Retrieve an array of all the opened projects.
cbProject * IsOpen (const wxString &filename)
Check if a project is open based on the project's filename.
void SetProject (cbProject *project, bool refresh=true)
Set the active project.
cbProject * LoadProject (const wxString &filename, bool activateIt=true)
Load a project from disk.
void ReloadProject (cbProject *project)
Reloads a project and tries to keep everything the same (project order, dependencies, active project)
bool SaveProject (cbProject *project)
Save a project to disk.
bool SaveProjectAs (cbProject *project)
Save a project to disk, asking for a filename.
bool SaveActiveProject ()
Save the active project to disk.
bool SaveActiveProjectAs ()
Save the active project to disk, asking for a filename.
bool SaveAllProjects ()
Saves all projects to disk.
bool CloseProject (cbProject *project, bool dontsave=false, bool refresh=true)
Close a project.
bool CloseActiveProject (bool dontsave=false)
Close the active project.
bool CloseAllProjects (bool dontsave=false)
Close all projects.
cbProject * NewProject (const wxString &filename=wxEmptyString)
Create a new empty project.
int AddFileToProject (const wxString &filename, cbProject *project=nullptr, int target=-1)
Add a file to a project.
int AddFileToProject (const wxString &filename, cbProject *project, wxArrayInt &targets)
Add a file to a project.
int AddMultipleFilesToProject (const wxArrayString &filelist, cbProject *project, int target=-1)
Add multiple files to a project.
int AddMultipleFilesToProject (const wxArrayString &filelist, cbProject *project, wxArrayInt &targets)
Add multiple files to a project.
void RemoveFileFromProject (ProjectFile *pfile, cbProject *project)
Remove a file from a project.
bool LoadWorkspace (const wxString &filename=DEFAULT_WORKSPACE)
Load a workspace.
bool SaveWorkspace ()
Save the open workspace.
bool SaveWorkspaceAs (const wxString &filename)
Save the open workspace under a different filename.
bool CloseWorkspace ()
Close the workspace.
bool IsLoadingProject ()
Check if the project manager is loading a project.
bool IsLoadingWorkspace ()
Check if the project manager is loading a workspace.
bool IsLoading ()
Check if the project manager is loading a project/workspace.
bool IsClosingProject ()
Check if the project manager is closing a project.
bool IsClosingWorkspace ()
Check if the project manager is closing a workspace.
bool IsLoadingOrClosing ()
Check if the project manager is loading/closing a project/workspace.
cbWorkspace * GetWorkspace ()
Get the current workspace filename.
bool AddProjectDependency (cbProject *base, cbProject *dependsOn)
Adds a project as a dependency of another project.
void RemoveProjectDependency (cbProject *base, cbProject *doesNotDependOn)
Removes a project dependency.
void ClearProjectDependencies (cbProject *base)
Removes all dependencies from project base.
void RemoveProjectFromAllDependencies (cbProject *base)
Removes the project base from being a dependency of any other project.
const ProjectsArray * GetDependenciesForProject (cbProject *base)
Get the array of projects base depends on.
bool CausesCircularDependency (cbProject *base, cbProject *dependsOn)
Checks for circular dependencies between base and dependsOn.
void WorkspaceChanged ()
Sends message to the plugins that the workspace has been changed.
bool BeginLoadingProject ()
Begins the project loading process.
void EndLoadingProject (cbProject *project)
Ends the project loading process.
bool BeginLoadingWorkspace ()
Begins the workspace loading process.
void EndLoadingWorkspace ()
Ends the workspace loading process.
ProjectManager & operator= (cb_unused const ProjectManager &rhs)
void SetIsRunning (cbPlugin *plugin)
If a plugin runs the project executable, should not be able to run it too.
cbPlugin * GetIsRunning () const
cbProject * FindProjectForFile (const wxString &file, ProjectFile **resultFile, bool isRelative, bool isUnixFilename)
Return the project which has the file in it, also return the pointer to the ProjectFile object.
Static Public Member Functions
static bool CanShutdown ()
Can the app shutdown? (actually: is ProjectManager busy at the moment?)
static bool IsBusy ()
For use with plugins.
Static Public Member Functions inherited from Mgr< ProjectManager >
static bool Valid ()
static ProjectManager * Get ()
static void Free ()
Private Member Functions
ProjectManager (cb_unused const ProjectManager &rhs)
ProjectManager ()
~ProjectManager ()
void OnAppDoneStartup (CodeBlocksEvent &event)
int DoAddFileToProject (const wxString &filename, cbProject *project, wxArrayInt &targets)
Private Attributes
cbProjectManagerUI * m_ui
cbProject * m_pActiveProject
cbProject * m_pProjectToActivate
ProjectsArray * m_pProjects
DepsMap m_ProjectDeps
cbWorkspace * m_pWorkspace
FilesGroupsAndMasks * m_pFileGroups
bool m_IsLoadingProject
bool m_IsLoadingWorkspace
bool m_IsClosingProject
bool m_IsClosingWorkspace
wxString m_InitialDir
bool m_CanSendWorkspaceChanged
cbPlugin * m_RunningPlugin
Static Private Attributes
static bool s_CanShutdown = true
Friends
class Mgr< ProjectManager >
class Manager
Additional Inherited Members
Protected Member Functions inherited from Mgr< ProjectManager >
Mgr ()
virtual ~Mgr ()
Detailed Description
The entry point singleton for working with projects.
This is the project manager class. It handles all open projects and workspaces. It is through this class that you make requests about projects, like open a project, save it, set the active project (if more than one are opened), etc. To access a project, you must retrieve it from this class.
As all managers, this is a singleton class which you retrieve by asking the global Manager singleton. E.g. Manager::Get()->GetProjectManager()
Definition at line 142 of file projectmanager.h.
Constructor & Destructor Documentation
ProjectManager() [1/2]
ProjectManager::ProjectManager (cb_unused const ProjectManager & rhs) private
ProjectManager() [2/2]
ProjectManager::ProjectManager () private
Definition at line 75 of file projectmanager.cpp.
References cbEVT_APP_STARTUP_DONE, Manager::Get(), Manager::GetAppWindow(), ScriptBindings::IOLib::GetCwd(), m_InitialDir, m_pActiveProject, m_pFileGroups, m_pProjects, m_pProjectToActivate, OnAppDoneStartup(), and Manager::RegisterEventSink().
~ProjectManager()
ProjectManager::~ProjectManager () private
Definition at line 104 of file projectmanager.cpp.
References m_pFileGroups, m_pProjects, m_pWorkspace, and m_ui.
Member Function Documentation
AddFileToProject() [1/2]
int ProjectManager::AddFileToProject (const wxString & filename, cbProject * project = nullptr, int target = -1)
Add a file to a project.
This function comes in two versions. This version, expects a single build target index for the added file to belong to.
Parameters
filename The file to add to the project.
project The project to add this file to. If NULL, the active project is used.
target The index of the project's build target to add this file.
Returns
The build target's index that this file was added to.
Note
If the target index supplied is -1 then, if the project has exactly one build target, the file is added to this single build target. If the project has more than one build targets, a dialog appears so that the user can select which build target this file should belong to.
Definition at line 696 of file projectmanager.cpp.
References GetActiveProject().
Referenced by Wiz::CopyFiles(), MainFrame::OnFileNewWhat(), Wiz::RunProjectWizard(), and EditorManager::SwapActiveHeaderSource().
AddFileToProject() [2/2]
int ProjectManager::AddFileToProject (const wxString & filename, cbProject * project, wxArrayInt & targets)
Add a file to a project.
This function comes in two versions. This version, expects an array of build target indices for the added file to belong to.
Parameters
filename The file to add to the project.
project The project to add this file to. If NULL, the active project is used.
targets The array of the project's build targets indices to add this file.
Returns
The number of build targets this file was added to.
Note
If the targets array is empty then, if the project has exactly one build target, the file is added to this single build target. If the project has more than one build targets, a dialog appears so that the user can select which build targets (multiple) this file should belong to.
Also note than when this function returns, the targets array will contain the user-selected build targets.
Definition at line 708 of file projectmanager.cpp.
References cbEVT_PROJECT_FILE_ADDED, DoAddFileToProject(), Manager::Get(), GetActiveProject(), Manager::GetPluginManager(), and PluginManager::NotifyPlugins().
AddMultipleFilesToProject() [1/2]
int ProjectManager::AddMultipleFilesToProject (const wxArrayString & filelist, cbProject * project, int target = -1)
Add multiple files to a project.
This function comes in two versions. This version, expects a single build target index for the added files to belong to.
Parameters
filelist The files to add to the project.
project The project to add these files to. If NULL, the active project is used.
target The index of the project's build target to add these files.
Returns
The build target's index that these files were added to.
Note
If the target index supplied is -1 then, if the project has exactly one build target, the files are added to this single build target. If the project has more than one build targets, a dialog appears so that the user can select which build target these files should belong to.
Definition at line 724 of file projectmanager.cpp.
References GetActiveProject().
Referenced by ProjectManagerUI::OnAddFilesToProjectRecursively(), and ProjectManagerUI::OnAddFileToProject().
AddMultipleFilesToProject() [2/2]
int ProjectManager::AddMultipleFilesToProject (const wxArrayString & filelist, cbProject * project, wxArrayInt & targets)
Add multiple files to a project.
This function comes in two versions. This version, expects an array of build target indices for the added files to belong to.
Parameters
filelist The files to add to the project.
project The project to add this file to. If NULL, the active project is used.
targets The array of the project's build targets indices to add this file.
Returns
The number of build targets these files were added to.
Note
If the targets array is empty then, if the project has exactly one build target, the files are added to this single build target. If the project has more than one build targets, a dialog appears so that the user can select which build targets (multiple) these files should belong to.
Also note than when this function returns, the targets array will contain the user-selected build targets.
Definition at line 736 of file projectmanager.cpp.
References cbProject::BeginAddFiles(), cbEVT_PROJECT_FILE_ADDED, DoAddFileToProject(), cbProject::EndAddFiles(), Manager::Get(), GetActiveProject(), Manager::GetAppFrame(), Manager::GetPluginManager(), and PluginManager::NotifyPlugins().
AddProjectDependency()
bool ProjectManager::AddProjectDependency (cbProject * base, cbProject * dependsOn)
Adds a project as a dependency of another project.
Projects inside workspaces allow you to set dependencies between them. When project A depends on project B, this means that before building project A, project B will be built because it obviously generates code that project A depends upon.
Parameters
base The project to set a dependency for.
dependsOn the project that must be built before base project.
Definition at line 796 of file projectmanager.cpp.
References CausesCircularDependency(), LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), CompileTargetBase::GetTitle(), m_ProjectDeps, m_pWorkspace, and cbWorkspace::SetModified().
Referenced by WorkspaceLoader::Open(), ScriptBindings::RegisterBindings(), and ReloadProject().
BeginLoadingProject()
bool ProjectManager::BeginLoadingProject ()
Begins the project loading process.
Only to be used by code that needs it (e.g. project importers).
Returns
True on success, false on failure.
Note
This call must be "closed" by a call to EndLoadingProject()!
Definition at line 968 of file projectmanager.cpp.
References cbMessageBox(), Manager::Get(), m_IsLoadingProject, and s_CanShutdown.
Referenced by LoadProject(), and NewProject().
BeginLoadingWorkspace()
bool ProjectManager::BeginLoadingWorkspace ()
Begins the workspace loading process.
Only to be used by code that needs it (e.g. workspace importers).
Returns
True on success, false on failure.
Note
This call must be "closed" by a call to EndLoadingWorkspace()!
Definition at line 1038 of file projectmanager.cpp.
References cbProjectManagerUI::BeginLoadingWorkspace(), CloseWorkspace(), m_IsLoadingWorkspace, and m_ui.
Referenced by LoadWorkspace().
CanShutdown()
static bool ProjectManager::CanShutdown () inline static
Can the app shutdown? (actually: is ProjectManager busy at the moment?)
Definition at line 157 of file projectmanager.h.
Referenced by MainFrame::OnApplicationClose(), MainFrame::OnFileCloseAllProjects(), MainFrame::OnFileCloseProject(), MainFrame::OnFileMenuUpdateUI(), and MainFrame::OnProjectMenuUpdateUI().
CausesCircularDependency()
bool ProjectManager::CausesCircularDependency (cbProject * base, cbProject * dependsOn)
Checks for circular dependencies between base and dependsOn.
Returns
True if circular dependency is detected, false if it isn't.
Definition at line 772 of file projectmanager.cpp.
References GetDependenciesForProject().
Referenced by AddProjectDependency().
ClearProjectDependencies()
void ProjectManager::ClearProjectDependencies (cbProject * base)
Removes all dependencies from project base.
See also
AddProjectDependency()
Parameters
base The project to remove all dependencies from.
Definition at line 850 of file projectmanager.cpp.
References LogManager::DebugLog(), Manager::Get(), Manager::GetLogManager(), CompileTargetBase::GetTitle(), m_ProjectDeps, m_pWorkspace, and cbWorkspace::SetModified().
Referenced by ScriptBindings::RegisterBindings(), and ProjectDepsDlg::SaveList().
CloseActiveProject()
bool ProjectManager::CloseActiveProject (bool dontsave = false)
Close the active project.
Same as CloseProject(GetActiveProject()).
Returns
True if project was closed, false if not.
Definition at line 464 of file projectmanager.cpp.
References CloseProject(), m_pActiveProject, m_pProjects, and SetProject().
Referenced by MainFrame::OnFileCloseProject(), and ScriptBindings::RegisterBindings().
CloseAllProjects()
bool ProjectManager::CloseAllProjects (bool dontsave = false)
Close all projects.
Returns
True if all projects were closed, false if even one close operation failed.
Definition at line 378 of file projectmanager.cpp.
References CloseProject(), cbProjectManagerUI::FreezeTree(), Manager::IsAppShuttingDown(), m_InitialDir, m_IsClosingProject, m_pProjects, m_ui, cbProjectManagerUI::QueryCloseAllProjects(), cbProjectManagerUI::RebuildTree(), ScriptBindings::IOLib::SetCwd(), cbProjectManagerUI::UnfreezeTree(), and WorkspaceChanged().
Referenced by CloseWorkspace(), and ScriptBindings::RegisterBindings().
CloseProject()
bool ProjectManager::CloseProject (cbProject * project, bool dontsave = false, bool refresh = true)
Close a project.
Parameters
project A pointer to the project to close.
dontsave Force not (!) saving the project on close.
refresh Force a refresh of the project tree after closing a project.
Returns
True if project was closed, false if not.
Definition at line 412 of file projectmanager.cpp.
References cbEVT_PROJECT_CLOSE, cbProject::CloseAllFiles(), Manager::Get(), cbProject::GetCurrentlyCompilingTarget(), Manager::GetEditorManager(), Manager::GetPluginManager(), m_InitialDir, m_IsClosingProject, m_pActiveProject, m_pProjects, m_pWorkspace, m_ui, PluginManager::NotifyPlugins(), cbProjectManagerUI::QueryCloseProject(), cbProjectManagerUI::RemoveProject(), RemoveProjectFromAllDependencies(), cbProject::SaveLayout(), ScriptBindings::IOLib::SetCwd(), cbWorkspace::SetModified(), SetProject(), EditorManager::UpdateProjectFiles(), and WorkspaceChanged().
Referenced by CloseActiveProject(), CloseAllProjects(), ProjectManagerUI::OnCloseProject(), ScriptBindings::RegisterBindings(), and ReloadProject().
CloseWorkspace()
bool ProjectManager::CloseWorkspace ()
Close the workspace.
Returns
True if the workspace closes, false if not (the user is asked to save the workspace, if it is modified)
Definition at line 572 of file projectmanager.cpp.
References cbEVT_WORKSPACE_CLOSING_BEGIN, cbEVT_WORKSPACE_CLOSING_COMPLETE, CloseAllProjects(), cbProjectManagerUI::CloseWorkspace(), Manager::Get(), Manager::GetPluginManager(), Manager::IsBatchBuild(), m_IsClosingWorkspace, m_pWorkspace, m_ui, PluginManager::NotifyPlugins(), cbProjectManagerUI::QueryCloseWorkspace(), and WorkspaceChanged().
Referenced by BeginLoadingWorkspace(), MainFrame::DoCloseCurrentWorkspace(), EndLoadingWorkspace(), ProjectManagerUI::OnCloseWorkspace(), and ScriptBindings::RegisterBindings().
DoAddFileToProject()
int ProjectManager::DoAddFileToProject (const wxString & filename, cbProject * project, wxArrayInt & targets) private
Definition at line 655 of file projectmanager.cpp.
References ProjectFile::AddBuildTarget(), cbProject::AddFile(), cbProjectManagerUI::AskForMultiBuildTargetIndex(), CompileTargetBase::GetBasePath(), cbProject::GetBuildTarget(), cbProject::GetBuildTargetsCount(), CompileTargetBase::GetTitle(), and m_ui.
Referenced by AddFileToProject(), and AddMultipleFilesToProject().
EndLoadingProject()
void ProjectManager::EndLoadingProject (cbProject * project)
Ends the project loading process.
Only to be used by code that needs it (e.g. project importers).
Parameters
project The loaded project.
Note
A call to BeginLoadingProject() must have preceded.
Definition at line 987 of file projectmanager.cpp.
References UserVariableManager::Arrogate(), cbEVT_PROJECT_OPEN, cbProjectManagerUI::FinishLoadingProject(), Manager::Get(), cbProject::GetShowNotesOnLoad(), Manager::GetUserVariableManager(), cbProject::LoadLayout(), m_IsLoadingProject, m_IsLoadingWorkspace, m_pFileGroups, m_pProjects, m_pWorkspace, m_ui, Manager::ProcessEvent(), s_CanShutdown, cbWorkspace::SetModified(), cbProject::ShowNotes(), and WorkspaceChanged().
Referenced by LoadProject(), and NewProject().
EndLoadingWorkspace()
void ProjectManager::EndLoadingWorkspace ()
Ends the workspace loading process.
Only to be used by code that needs it (e.g. workspace importers).
Note
A call to BeginLoadingWorkspace() must have preceded.
Definition at line 1055 of file projectmanager.cpp.
References UserVariableManager::Arrogate(), cbEVT_PROJECT_OPEN, cbMessageBox(), CloseWorkspace(), cbProjectManagerUI::FinishLoadingWorkspace(), Manager::Get(), cbProject::GetNotes(), Manager::GetPluginManager(), cbProject::GetShowNotesOnLoad(), cbWorkspace::GetTitle(), Manager::GetUserVariableManager(), cbWorkspace::IsOK(), m_IsLoadingWorkspace, m_pActiveProject, m_pProjects, m_pProjectToActivate, m_pWorkspace, m_ui, PluginManager::NotifyPlugins(), SetProject(), cbProject::ShowNotes(), and WorkspaceChanged().
Referenced by LoadWorkspace().
FindProjectForFile()
cbProject * ProjectManager::FindProjectForFile (const wxString & file, ProjectFile ** resultFile, bool isRelative, bool isUnixFilename)
Return the project which has the file in it, also return the pointer to the ProjectFile object.
Definition at line 1132 of file projectmanager.cpp.
References cbProject::GetFileByFilename(), and m_pProjects.
Referenced by DebuggerState::AddBreakpoint(), EditorManager::CheckForExternallyModifiedFiles(), EditorManager::Open(), EditorBase::SetTitle(), and cbAuiNotebook::UniqueIdFromTooltip().
GetActiveProject()
cbProject* ProjectManager::GetActiveProject () inline
Retrieve the active project.
Most of the times, this is the function you 'll be calling in ProjectManager.
Returns
A pointer to the active project.
Definition at line 177 of file projectmanager.h.
Referenced by AddFileToProject(), AddMultipleFilesToProject(), cbEditor::AddToContextMenu(), CompilerGCC::AskForActiveProject(), ProjectManagerUI::AskForBuildTargetIndex(), ProjectManagerUI::AskForMultiBuildTargetIndex(), CodeBlocksApp::BatchJob(), EditorManager::CollectDefines(), DebuggerGDB::Debug(), CompilerErrors::DoGotoError(), cbEditor::DoInitializations(), CodeCompletion::DoParseOpenedProjectAndActiveEditor(), MainFrame::DoUpdateAppTitle(), FilePathPanel::FilePathPanel(), FindReplaceDlg::FindReplaceDlg(), DebuggerManager::FindTargetsDebugger(), NativeParser::GetCurrentProject(), MainFrame::GetEditorDescription(), NativeParser::GetProjectByFilename(), CompilerGCC::IsValidTarget(), ProjectManagerUI::OnAddFilesToProjectRecursively(), ProjectManagerUI::OnAddFileToProject(), EditorManager::OnAddFileToProject(), MainFrame::OnApplicationClose(), FilePathPanel::OnbtnBrowseClick(), ProjectManagerUI::OnCloseProject(), cbEditor::OnContextMenuEntry(), ProjectManagerUI::OnExecParameters(), MainFrame::OnFileMenuUpdateUI(), MainFrame::OnFileNewWhat(), MainFrame::OnFileSaveProject(), MainFrame::OnFileSaveProjectAs(), ProjectManagerUI::OnGotoFile(), ProjectManagerUI::OnKeyDown(), WizBuildTargetPanel::OnPageChanging(), NativeParser::OnParsingOneByOneTimer(), CompilerGCC::OnProjectActivated(), ProjectManagerUI::OnProjectFileActivated(), MainFrame::OnProjectMenuUpdateUI(), ProjectManagerUI::OnProperties(), DisassemblyDlg::OnSave(), ProjectManagerUI::OnSetActiveProject(), DebuggerMenuHandler::OnUpdateUI(), DebuggerToolbarHandler::OnUpdateUI(), CompilerGCC::OnUpdateUI(), CodeCompletion::OnWorkspaceChanged(), ProjectManagerUI::RebuildTree(), ScriptBindings::RegisterBindings(), MacrosManager::ReplaceMacros(), Wiz::RunTargetWizard(), WorkspaceLoader::SaveLayout(), FilePathPanel::SetAddToProject(), ProjectManagerUI::ShowMenu(), EditorManager::SwapActiveHeaderSource(), cbDebuggerPlugin::SyncEditor(), and cbDebuggerPlugin::ToolMenuEnabled().
GetDefaultPath()
wxString ProjectManager::GetDefaultPath ()
Retrieve the default path for new projects.
Returns
The default path for new projects. Contains trailing path separator.
Note
This might be empty if not configured before...
Definition at line 135 of file projectmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Read().
Referenced by WizProjectPathPanel::OnPageChanged(), and ScriptBindings::RegisterBindings().
GetDependenciesForProject()
const ProjectsArray * ProjectManager::GetDependenciesForProject (cbProject * base)
Get the array of projects base depends on.
Parameters
base The project to get its dependencies.
Returns
An array of project dependencies, or NULL if no dependencies are set for base.
Definition at line 907 of file projectmanager.cpp.
References m_ProjectDeps.
Referenced by CompilerGCC::CalculateProjectDependencies(), CausesCircularDependency(), ProjectDepsDlg::FillList(), ScriptBindings::RegisterBindings(), and WorkspaceLoader::Save().
GetFilesGroupsAndMasks() [1/2]
const FilesGroupsAndMasks* ProjectManager::GetFilesGroupsAndMasks () const inline
Definition at line 153 of file projectmanager.h.
Referenced by FileTypeOf(), ProjectManagerUI::FinishLoadingProject(), ProjectManagerUI::OnAddFilesToProjectRecursively(), ProjectManagerUI::OnViewFileMasks(), and ProjectManagerUI::RebuildTree().
GetFilesGroupsAndMasks() [2/2]
FilesGroupsAndMasks* ProjectManager::GetFilesGroupsAndMasks () inline
Definition at line 154 of file projectmanager.h.
GetIsRunning()
cbPlugin * ProjectManager::GetIsRunning () const
Definition at line 1127 of file projectmanager.cpp.
References m_RunningPlugin.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::KillProcess(), CompilerGCC::NotifyJobDone(), cbDebuggerPlugin::OnCompilerFinished(), DebuggerMenuHandler::OnRunToCursor(), DebuggerMenuHandler::OnStart(), DebuggerMenuHandler::OnStep(), DebuggerMenuHandler::OnUpdateUI(), DebuggerToolbarHandler::OnUpdateUI(), and CompilerGCC::OnUpdateUI().
GetProjects()
ProjectsArray* ProjectManager::GetProjects () inline
Retrieve an array of all the opened projects.
This is a standard wxArray containing pointers to projects. Using this array you can iterate through all the opened projects.
Returns
A pointer to the array containing the projects.
Definition at line 183 of file projectmanager.h.
References DEFAULT_WORKSPACE.
Referenced by CompilerGCC::CalculateProjectDependencies(), CompilerGCC::CalculateWorkspaceDependencies(), ProjectManagerUI::CheckForExternallyModifiedProjects(), cbProject::CreateUniqueFilename(), DebuggerGDB::DoDebug(), CompilerGCC::DoWorkspaceBuild(), ProjectDepsDlg::FillList(), FindReplace::FindInFiles(), FindReplaceDlg::FindReplaceDlg(), NativeParser::GetProjectByFilename(), ProjectManagerUI::MoveProjectDown(), ProjectManagerUI::MoveProjectUp(), ProjectManagerUI::OnCloseProject(), ProjectManagerUI::OnFindFile(), ProjectManagerUI::OnGotoFile(), NativeParser::OnParsingOneByOneTimer(), CodeCompletion::OnProjectSavedTimer(), FindReplaceDlg::OnSearchProject(), ProjectManagerUI::OnSetActiveProject(), CompilerGCC::PreprocessJob(), ProjectDepsDlg::ProjectDepsDlg(), ScriptBindings::ProjectManager_GetProject(), ScriptBindings::ProjectManager_GetProjectCount(), ProjectManagerUI::QueryCloseAllProjects(), ProjectManagerUI::RebuildTree(), FindReplace::ReplaceInFiles(), CompilerGCC::ResetBuildState(), WorkspaceLoader::Save(), ProjectDepsDlg::SaveList(), MainFrame::ShowHideStartPage(), and ProjectManagerUI::ShowMenu().
GetUI()
cbProjectManagerUI& ProjectManager::GetUI () inline
Definition at line 150 of file projectmanager.h.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects(), NativeParser::CreateClassBrowser(), CompilerGCC::DoSwitchProjectTemporarily(), ProjectFileOptionsDlg::EndModal(), TemplateManager::NewProjectFromUserTemplate(), EditorManager::OnAddFileToProject(), cbEditor::OnContextMenuEntry(), ProjectOptionsDlg::OnCreateImportFileClick(), CompilerGCC::OnProjectCompilerOptions(), ProjectOptionsDlg::OnProjectDepsClick(), EditorManager::OnRemoveFileFromProject(), CodeCompletion::OnSelectedFileReparse(), EditorManager::OnShowFileInTree(), ScriptBindings::ProjectManager_RebuildTree(), NativeParser::RemoveClassBrowser(), NativeParser::ReparseSelectedProject(), Wiz::RunProjectWizard(), ProjectFile::SetFileState(), and EditorManager::SwapActiveHeaderSource().
GetWorkspace()
cbWorkspace * ProjectManager::GetWorkspace ()
Get the current workspace filename.
Returns
The current workspace filename.
Definition at line 527 of file projectmanager.cpp.
References m_pWorkspace, cbWorkspace::SetModified(), and cbWorkspace::SetTitle().
Referenced by MacrosManager::ClearProjectKeys(), CompilerGCC::DoRecreateTargetMenu(), CompilerGCC::InitBuildLog(), WorkspaceLoader::LoadLayout(), ProjectManagerUI::MoveProjectDown(), ProjectManagerUI::MoveProjectUp(), ProjectManagerUI::OnCloseWorkspace(), MainFrame::OnFileMenuUpdateUI(), MainFrame::OnFileOpenDefWorkspace(), MainFrame::OnFileSaveAll(), MainFrame::OnFileSaveWorkspace(), MainFrame::OnFileSaveWorkspaceAs(), ProjectManagerUI::OnFindFile(), ProjectManagerUI::OnProjectFileActivated(), ProjectManagerUI::OnRenameWorkspace(), ProjectManagerUI::OnRightClick(), ProjectManagerUI::OnSaveAsWorkspace(), ProjectManagerUI::OnSaveWorkspace(), CompilerGCC::OnSelectTarget(), ProjectManagerUI::QueryCloseWorkspace(), ProjectManagerUI::RebuildTree(), WorkspaceLoader::SaveLayout(), SaveWorkspace(), SaveWorkspaceAs(), and ProjectManagerUI::ShowMenu().
IsBusy()
bool ProjectManager::IsBusy () static
For use with plugins.
Checks whether files in the project MAY be processed. This function has been made static for your convenience :)
Returns
true if Loading,closing a project/workspace, or if the app is shutting down. False otherwise
Definition at line 612 of file projectmanager.cpp.
References Manager::Get(), Manager::GetProjectManager(), Manager::IsAppShuttingDown(), and IsLoadingOrClosing().
Referenced by CodeCompletion::OnEditorActivated(), CodeCompletion::OnEditorSave(), CodeCompletion::OnProjectActivated(), CodeCompletion::OnReparsingTimer(), cbEditor::OnScintillaEvent(), CodeCompletion::OnToolbarTimer(), and WorkspaceChanged().
IsClosingProject()
bool ProjectManager::IsClosingProject ()
Check if the project manager is closing a project.
Returns
True if it's closing a project, false otherwise
Definition at line 644 of file projectmanager.cpp.
References m_IsClosingProject.
IsClosingWorkspace()
bool ProjectManager::IsClosingWorkspace ()
Check if the project manager is closing a workspace.
Returns
True if it's closing a workspace, false otherwise
Definition at line 649 of file projectmanager.cpp.
References m_IsClosingWorkspace.
IsLoading()
bool ProjectManager::IsLoading ()
Check if the project manager is loading a project/workspace.
Returns
True if it's loading a project/workspace, false otherwise
Definition at line 639 of file projectmanager.cpp.
References m_IsLoadingProject, and m_IsLoadingWorkspace.
Referenced by EditorManager::Open(), and UserVariableManager::Replace().
IsLoadingOrClosing()
bool ProjectManager::IsLoadingOrClosing ()
Check if the project manager is loading/closing a project/workspace.
Returns
True if it is loading/closing something, false otherwise
Definition at line 624 of file projectmanager.cpp.
References m_IsClosingProject, m_IsClosingWorkspace, m_IsLoadingProject, and m_IsLoadingWorkspace.
Referenced by IsBusy().
IsLoadingProject()
bool ProjectManager::IsLoadingProject ()
Check if the project manager is loading a project.
Returns
True if it's loading a project, false otherwise
Definition at line 629 of file projectmanager.cpp.
References m_IsLoadingProject.
Referenced by ProjectManagerUI::OnCloseProject(), and ProjectManagerUI::OnSaveProject().
IsLoadingWorkspace()
bool ProjectManager::IsLoadingWorkspace ()
Check if the project manager is loading a workspace.
Returns
True if it's loading a workspace, false otherwise
Definition at line 634 of file projectmanager.cpp.
References m_IsLoadingWorkspace.
IsOpen()
cbProject * ProjectManager::IsOpen (const wxString & filename)
Check if a project is open based on the project's filename.
Parameters
filename The project's filename. Must be an absolute path.
Returns
A pointer to the project if it is open, or NULL if it is not.
Definition at line 184 of file projectmanager.cpp.
References CompileTargetBase::GetFilename(), m_pProjects, and realpath().
Referenced by WorkspaceLoader::LoadLayout(), LoadProject(), NewProject(), WorkspaceLoader::Open(), MainFrame::OpenGeneric(), and ScriptBindings::RegisterBindings().
IsProjectStillOpen()
bool ProjectManager::IsProjectStillOpen (cbProject * project)
Is this a valid project? (i.e.
is it still open?)
Parameters
project The project to check its validity.
Returns
True if the project is valid (i.e. still open), false if not.
Definition at line 148 of file projectmanager.cpp.
References m_pProjects.
LoadProject()
cbProject * ProjectManager::LoadProject (const wxString & filename, bool activateIt = true)
Load a project from disk.
This function, internally, uses IsOpen() so that the same project can't be loaded twice.
Parameters
filename The project file's filename.
activateIt Active the project after loading.
Returns
If the function succeeds, a pointer to the newly opened project is returned. Else the return value is NULL.
Definition at line 210 of file projectmanager.cpp.
References BeginLoadingProject(), EndLoadingProject(), FileTypeOf(), ftCodeBlocksProject, Manager::Get(), PluginManager::GetMIMEHandlerForFile(), Manager::GetPluginManager(), cbProject::IsLoaded(), IsOpen(), m_IsLoadingWorkspace, m_pProjectToActivate, cbMimePlugin::OpenFile(), and SetProject().
Referenced by MainFrame::DoOpenProject(), TemplateManager::NewProjectFromUserTemplate(), WorkspaceLoader::Open(), ScriptBindings::RegisterBindings(), and ReloadProject().
LoadWorkspace()
bool ProjectManager::LoadWorkspace (const wxString & filename = DEFAULT_WORKSPACE)
Load a workspace.
Parameters
filename The workspace to open.
Returns
True if the workspace loads succefully, false if not.
Definition at line 539 of file projectmanager.cpp.
References BeginLoadingWorkspace(), cbEVT_WORKSPACE_LOADING_COMPLETE, EndLoadingWorkspace(), Manager::Get(), Manager::GetPluginManager(), cbWorkspace::IsOK(), m_pActiveProject, m_pProjects, m_pWorkspace, PluginManager::NotifyPlugins(), and SetProject().
Referenced by MainFrame::OnFileOpenDefWorkspace(), CodeBlocksApp::OnInit(), MainFrame::OpenGeneric(), and ScriptBindings::RegisterBindings().
NewProject()
cbProject * ProjectManager::NewProject (const wxString & filename = wxEmptyString)
Create a new empty project.
Parameters
filename the project's filename
Returns
A pointer to the new project if succesful, or NULL if not.
Note
When the new project is created, if no filename parameter was supplied, it asks the user where to save it. If the user cancels the Save dialog, then NULL is returned from this function.
Definition at line 350 of file projectmanager.cpp.
References BeginLoadingProject(), cbMessageBox(), EndLoadingProject(), IsOpen(), m_IsLoadingWorkspace, and SetProject().
Referenced by ScriptBindings::RegisterBindings(), and Wiz::RunProjectWizard().
OnAppDoneStartup()
void ProjectManager::OnAppDoneStartup (CodeBlocksEvent & event) private
Definition at line 917 of file projectmanager.cpp.
References m_CanSendWorkspaceChanged.
Referenced by ProjectManager().
operator=()
ProjectManager& ProjectManager::operator= (cb_unused const ProjectManager & rhs) inline
Definition at line 432 of file projectmanager.h.
References cbThrow.
ReloadProject()
void ProjectManager::ReloadProject (cbProject * project)
Reloads a project and tries to keep everything the same (project order, dependencies, active project)
Parameters
project the project that will be reloaded, the pointer will be invalid after the call.
Definition at line 277 of file projectmanager.cpp.
References AddProjectDependency(), CloseProject(), cbProjectManagerUI::FreezeTree(), CompileTargetBase::GetFilename(), cbWorkspace::GetModified(), LoadProject(), m_pActiveProject, m_pProjects, m_ProjectDeps, m_pWorkspace, m_ui, cbProjectManagerUI::RebuildTree(), cbWorkspace::SetModified(), and cbProjectManagerUI::UnfreezeTree().
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects().
RemoveFileFromProject()
void ProjectManager::RemoveFileFromProject (ProjectFile * pfile, cbProject * project)
Remove a file from a project.
Parameters
pfile The file to remove from the project.
project The project to remove this file from. If NULL, the active project is used.
Definition at line 940 of file projectmanager.cpp.
References ProjectFile::AutoGeneratedBy(), cbEVT_PROJECT_FILE_REMOVED, cbMessageBox(), LogManager::DebugLog(), ProjectFile::file, Manager::Get(), Manager::GetLogManager(), ProjectFile::GetParentProject(), Manager::GetPluginManager(), CompileTargetBase::GetTitle(), PluginManager::NotifyPlugins(), cbProject::RemoveFile(), and CodeBlocksEvent::SetProject().
Referenced by cbEditor::OnContextMenuEntry(), ProjectManagerUI::OnRemoveFileFromProject(), EditorManager::OnRemoveFileFromProject(), and ProjectManagerUI::RemoveFilesRecursively().
RemoveProjectDependency()
void ProjectManager::RemoveProjectDependency (cbProject * base, cbProject * doesNotDependOn)
Removes a project dependency.
See also
AddProjectDependency()
Parameters
base The project to remove a dependency from.
doesNotDependOn The project that is to stop being a dependency of project base.
Definition at line 827 of file projectmanager.cpp.
References LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), CompileTargetBase::GetTitle(), m_ProjectDeps, m_pWorkspace, and cbWorkspace::SetModified().
Referenced by ScriptBindings::RegisterBindings().
RemoveProjectFromAllDependencies()
void ProjectManager::RemoveProjectFromAllDependencies (cbProject * base)
Removes the project base from being a dependency of any other project.
See also
AddProjectDependency()
Parameters
base The project to remove from all dependencies.
Definition at line 866 of file projectmanager.cpp.
References LogManager::DebugLog(), F(), Manager::Get(), Manager::GetLogManager(), CompileTargetBase::GetTitle(), m_ProjectDeps, m_pWorkspace, and cbWorkspace::SetModified().
Referenced by CloseProject(), and ScriptBindings::RegisterBindings().
SaveActiveProject()
bool ProjectManager::SaveActiveProject ()
Save the active project to disk.
Same as SaveProject(GetActiveProject()).
Returns
True if saving was succesful, false if not.
Definition at line 498 of file projectmanager.cpp.
References m_pActiveProject, and SaveProject().
Referenced by MainFrame::OnFileSaveProject(), and ScriptBindings::RegisterBindings().
SaveActiveProjectAs()
bool ProjectManager::SaveActiveProjectAs ()
Save the active project to disk, asking for a filename.
Same as SaveProjectAs(GetActiveProject()).
Returns
True if saving was succesful, false if not.
Note
A false return value doesn't necessarily mean failure. The user might have cancelled the SaveAs dialog...
Definition at line 503 of file projectmanager.cpp.
References m_pActiveProject, and SaveProjectAs().
Referenced by MainFrame::OnFileSaveProjectAs(), and ScriptBindings::RegisterBindings().
SaveAllProjects()
bool ProjectManager::SaveAllProjects ()
Saves all projects to disk.
Returns
True if all projects were saved, false if even one save operation failed.
Definition at line 508 of file projectmanager.cpp.
References cbProjectManagerUI::FreezeTree(), cbProject::GetModified(), m_pProjects, m_ui, SaveProject(), and cbProjectManagerUI::UnfreezeTree().
Referenced by MainFrame::OnFileSaveAll(), MainFrame::OnFileSaveProjectAllProjects(), and ScriptBindings::RegisterBindings().
SaveProject()
bool ProjectManager::SaveProject (cbProject * project)
Save a project to disk.
Parameters
project A pointer to the project to save.
Returns
True if saving was succesful, false if not.
Definition at line 473 of file projectmanager.cpp.
References m_ui, cbProjectManagerUI::RebuildTree(), and cbProject::Save().
Referenced by ProjectManagerUI::OnSaveProject(), ScriptBindings::RegisterBindings(), SaveActiveProject(), and SaveAllProjects().
SaveProjectAs()
bool ProjectManager::SaveProjectAs (cbProject * project)
Save a project to disk, asking for a filename.
Parameters
project A pointer to the project to save.
Returns
True if saving was succesful, false if not.
Note
A false return value doesn't necessarily mean failure. The user might have cancelled the SaveAs dialog...
Definition at line 485 of file projectmanager.cpp.
References m_ui, cbProjectManagerUI::RebuildTree(), and cbProject::SaveAs().
Referenced by ScriptBindings::RegisterBindings(), and SaveActiveProjectAs().
SaveWorkspace()
bool ProjectManager::SaveWorkspace ()
Save the open workspace.
Returns
True if the workspace is saved succefully, false if not.
Definition at line 562 of file projectmanager.cpp.
References GetWorkspace(), and cbWorkspace::Save().
Referenced by MainFrame::OnFileSaveAll(), MainFrame::OnFileSaveWorkspace(), ProjectManagerUI::OnSaveWorkspace(), ProjectManagerUI::QueryCloseWorkspace(), and ScriptBindings::RegisterBindings().
SaveWorkspaceAs()
bool ProjectManager::SaveWorkspaceAs (const wxString & filename)
Save the open workspace under a different filename.
Parameters
filename The workspace to save.
Returns
True if the workspace is saved succefully, false if not.
Definition at line 567 of file projectmanager.cpp.
References GetWorkspace(), and cbWorkspace::SaveAs().
Referenced by MainFrame::OnFileSaveWorkspaceAs(), ProjectManagerUI::OnSaveAsWorkspace(), and ScriptBindings::RegisterBindings().
SetDefaultPath()
void ProjectManager::SetDefaultPath (const wxString & path)
Set the default path for new projects.
Note
ProjectManager doesn't use this by itself. It's only doing the book-keeping. Usually this is set/queried from project wizards...
Definition at line 143 of file projectmanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Referenced by WizProjectPathPanel::OnPageChanging(), and ScriptBindings::RegisterBindings().
SetIsRunning()
void ProjectManager::SetIsRunning (cbPlugin * plugin)
If a plugin runs the project executable, should not be able to run it too.
Definition at line 1122 of file projectmanager.cpp.
References m_RunningPlugin.
Referenced by CompilerGCC::KillProcess(), cbDebuggerPlugin::MarkAsStopped(), CompilerGCC::NotifyJobDone(), cbDebuggerPlugin::OnCompilerFinished(), DebuggerMenuHandler::OnRunToCursor(), DebuggerMenuHandler::OnStart(), DebuggerMenuHandler::OnStep(), and CompilerGCC::Run().
SetProject()
void ProjectManager::SetProject (cbProject * project, bool refresh = true)
Set the active project.
Use this function if you want to change the active project.
Parameters
project A pointer to the new active project.
refresh If true, refresh the project manager's tree, else do not refresh it.
Definition at line 159 of file projectmanager.cpp.
References cbWorkspace::ActiveProjectChanged(), cbEVT_PROJECT_ACTIVATE, Manager::Get(), Manager::GetPluginManager(), m_pActiveProject, m_pWorkspace, m_ui, PluginManager::NotifyPlugins(), and cbProjectManagerUI::UpdateActiveProject().
Referenced by CloseActiveProject(), CloseProject(), CompilerGCC::DoSwitchProjectTemporarily(), EndLoadingWorkspace(), WorkspaceLoader::LoadLayout(), LoadProject(), LoadWorkspace(), NewProject(), ProjectManagerUI::OnCloseProject(), ProjectManagerUI::OnFindFile(), cbDebuggerPlugin::OnProjectActivated(), ProjectManagerUI::OnProjectFileActivated(), ProjectManagerUI::OnProperties(), ProjectManagerUI::OnSetActiveProject(), MainFrame::OpenGeneric(), CompilerGCC::PrepareCompileFile(), and ScriptBindings::RegisterBindings().
SetUI()
void ProjectManager::SetUI (cbProjectManagerUI * ui)
Definition at line 129 of file projectmanager.cpp.
References m_ui.
WorkspaceChanged()
void ProjectManager::WorkspaceChanged ()
Sends message to the plugins that the workspace has been changed.
Definition at line 926 of file projectmanager.cpp.
References cbEVT_WORKSPACE_CHANGED, Manager::Get(), Manager::GetEditorManager(), EditorManager::GetNotebook(), Manager::GetPluginManager(), IsBusy(), m_CanSendWorkspaceChanged, cbAuiNotebook::MinimizeFreeSpace(), and PluginManager::NotifyPlugins().
Referenced by CloseAllProjects(), CloseProject(), CloseWorkspace(), EndLoadingProject(), EndLoadingWorkspace(), and CodeBlocksApp::OnInit().
Friends And Related Function Documentation
Manager
friend class Manager friend
Definition at line 147 of file projectmanager.h.
Mgr< ProjectManager >
friend class Mgr< ProjectManager > friend
Definition at line 146 of file projectmanager.h.
Member Data Documentation
m_CanSendWorkspaceChanged
bool ProjectManager::m_CanSendWorkspaceChanged private
Definition at line 466 of file projectmanager.h.
Referenced by OnAppDoneStartup(), and WorkspaceChanged().
m_InitialDir
wxString ProjectManager::m_InitialDir private
Definition at line 465 of file projectmanager.h.
Referenced by CloseAllProjects(), CloseProject(), and ProjectManager().
m_IsClosingProject
bool ProjectManager::m_IsClosingProject private
Definition at line 463 of file projectmanager.h.
Referenced by CloseAllProjects(), CloseProject(), IsClosingProject(), and IsLoadingOrClosing().
m_IsClosingWorkspace
bool ProjectManager::m_IsClosingWorkspace private
Definition at line 464 of file projectmanager.h.
Referenced by CloseWorkspace(), IsClosingWorkspace(), and IsLoadingOrClosing().
m_IsLoadingProject
bool ProjectManager::m_IsLoadingProject private
Definition at line 461 of file projectmanager.h.
Referenced by BeginLoadingProject(), EndLoadingProject(), IsLoading(), IsLoadingOrClosing(), and IsLoadingProject().
m_IsLoadingWorkspace
bool ProjectManager::m_IsLoadingWorkspace private
Definition at line 462 of file projectmanager.h.
Referenced by BeginLoadingWorkspace(), EndLoadingProject(), EndLoadingWorkspace(), IsLoading(), IsLoadingOrClosing(), IsLoadingWorkspace(), LoadProject(), and NewProject().
m_pActiveProject
cbProject* ProjectManager::m_pActiveProject private
Definition at line 455 of file projectmanager.h.
Referenced by CloseActiveProject(), CloseProject(), EndLoadingWorkspace(), LoadWorkspace(), ProjectManager(), ReloadProject(), SaveActiveProject(), SaveActiveProjectAs(), and SetProject().
m_pFileGroups
FilesGroupsAndMasks* ProjectManager::m_pFileGroups private
Definition at line 460 of file projectmanager.h.
Referenced by EndLoadingProject(), ProjectManager(), and ~ProjectManager().
m_pProjects
ProjectsArray* ProjectManager::m_pProjects private
Definition at line 457 of file projectmanager.h.
Referenced by CloseActiveProject(), CloseAllProjects(), CloseProject(), EndLoadingProject(), EndLoadingWorkspace(), FindProjectForFile(), IsOpen(), IsProjectStillOpen(), LoadWorkspace(), ProjectManager(), ReloadProject(), SaveAllProjects(), and ~ProjectManager().
m_pProjectToActivate
cbProject* ProjectManager::m_pProjectToActivate private
Definition at line 456 of file projectmanager.h.
Referenced by EndLoadingWorkspace(), LoadProject(), and ProjectManager().
m_ProjectDeps
DepsMap ProjectManager::m_ProjectDeps private
Definition at line 458 of file projectmanager.h.
Referenced by AddProjectDependency(), ClearProjectDependencies(), GetDependenciesForProject(), ReloadProject(), RemoveProjectDependency(), and RemoveProjectFromAllDependencies().
m_pWorkspace
cbWorkspace* ProjectManager::m_pWorkspace private
Definition at line 459 of file projectmanager.h.
Referenced by AddProjectDependency(), ClearProjectDependencies(), CloseProject(), CloseWorkspace(), EndLoadingProject(), EndLoadingWorkspace(), GetWorkspace(), LoadWorkspace(), ReloadProject(), RemoveProjectDependency(), RemoveProjectFromAllDependencies(), SetProject(), and ~ProjectManager().
m_RunningPlugin
cbPlugin* ProjectManager::m_RunningPlugin private
Definition at line 467 of file projectmanager.h.
Referenced by GetIsRunning(), and SetIsRunning().
m_ui
cbProjectManagerUI* ProjectManager::m_ui private
Definition at line 454 of file projectmanager.h.
Referenced by BeginLoadingWorkspace(), CloseAllProjects(), CloseProject(), CloseWorkspace(), DoAddFileToProject(), EndLoadingProject(), EndLoadingWorkspace(), ReloadProject(), SaveAllProjects(), SaveProject(), SaveProjectAs(), SetProject(), SetUI(), and ~ProjectManager().
s_CanShutdown
bool ProjectManager::s_CanShutdown = true static private
Definition at line 144 of file projectmanager.h.
Referenced by BeginLoadingProject(), and EndLoadingProject().
The documentation for this class was generated from the following files:
projectmanager.h
projectmanager.cpp