Code::Blocks: GdbCmd_FindTooltipAddress Class Reference
GdbCmd_FindTooltipAddress Class Reference
Command to get a symbol's type and use it for tooltip evaluation.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_FindTooltipAddress (DebuggerDriver *driver, const wxString &what, const wxRect &tiprect, const wxString &w_type=wxEmptyString)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
wxRect m_WinRect
wxString m_What
wxString m_Type
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to get a symbol's type and use it for tooltip evaluation.
Definition at line 978 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_FindTooltipAddress()
GdbCmd_FindTooltipAddress::GdbCmd_FindTooltipAddress (DebuggerDriver * driver, const wxString & what, const wxRect & tiprect, const wxString & w_type = wxEmptyString) inline
Parameters
tree The tree to display the watch.
Definition at line 985 of file gdb_commands.h.
References _T, DebuggerDriver::High, wxString::IsEmpty(), wxString::Last(), DebuggerCmd::m_Cmd, DebuggerCmd::m_pDriver, and DebuggerDriver::QueueCommand().
Member Function Documentation
ParseOutput()
void GdbCmd_FindTooltipAddress::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 1001 of file gdb_commands.h.
References wxRegEx::GetMatch(), DebuggerDriver::High, DebuggerCmd::m_pDriver, wxRegEx::Matches(), DebuggerDriver::QueueCommand(), and reGenericHexAddress().
Member Data Documentation
m_Type
wxString GdbCmd_FindTooltipAddress::m_Type private
Definition at line 982 of file gdb_commands.h.
m_What
wxString GdbCmd_FindTooltipAddress::m_What private
Definition at line 981 of file gdb_commands.h.
m_WinRect
wxRect GdbCmd_FindTooltipAddress::m_WinRect private
Definition at line 980 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h