Code::Blocks: NewFromTemplateDlg Class Reference
NewFromTemplateDlg Class Reference
#include <newfromtemplatedlg.h>
Public Member Functions
NewFromTemplateDlg (TemplateOutputType initial, const wxArrayString &user_templates)
virtual ~NewFromTemplateDlg ()
ProjectTemplateLoader * GetTemplate ()
cbWizardPlugin * GetWizard ()
int GetWizardIndex () const
cbWizardPlugin * GetSelectedTemplate ()
bool SelectedUserTemplate () const
wxString GetSelectedUserTemplate () const
void EndModal (int retCode)
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Protected Member Functions
void FillTemplate (ProjectTemplateLoader *pt)
void BuildCategories ()
void BuildCategoriesFor (TemplateOutputType otype, wxChoice *cat)
void BuildList ()
void BuildListFor (TemplateOutputType otype, wxListCtrl *list, const wxChoice *cat)
void ClearList ()
void ClearListFor (wxListCtrl *list)
void OnListRightClick (wxListEvent &event)
void OnListActivate (wxListEvent &event)
void OnCategoryChanged (wxCommandEvent &event)
void OnEditScript (wxCommandEvent &event)
void OnDiscardScript (wxCommandEvent &event)
void OnEditGlobalScript (wxCommandEvent &event)
void OnViewChange (wxCommandEvent &event)
void OnHelp (wxCommandEvent &event)
void OnUpdateUI (wxUpdateUIEvent &event)
void ChangeView ()
void EditScript (const wxString &filename)
wxListCtrl * GetVisibleListCtrl ()
wxChoice * GetVisibleCategory ()
TemplateOutputType GetVisibleOutputType () const
Private Attributes
ProjectTemplateLoader * m_Template
cbWizardPlugin * m_pWizard
int m_WizardIndex
PluginsArray m_Wizards
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 19 of file newfromtemplatedlg.h.
Constructor & Destructor Documentation
NewFromTemplateDlg()
NewFromTemplateDlg::NewFromTemplateDlg (TemplateOutputType initial, const wxArrayString & user_templates)
Definition at line 84 of file newfromtemplatedlg.cpp.
References Manager::Get(), PluginManager::GetOffersFor(), Manager::GetPluginManager(), ptWizard, SetSettingsIconsStyle(), and sisNoIcons.
~NewFromTemplateDlg()
NewFromTemplateDlg::~NewFromTemplateDlg () virtual
Definition at line 123 of file newfromtemplatedlg.cpp.
Member Function Documentation
BuildCategories()
void NewFromTemplateDlg::BuildCategories () protected
Definition at line 167 of file newfromtemplatedlg.cpp.
References totCustom, totFiles, totProject, and totTarget.
Referenced by GetWizardIndex().
BuildCategoriesFor()
void NewFromTemplateDlg::BuildCategoriesFor (TemplateOutputType otype, wxChoice * cat) protected
Definition at line 175 of file newfromtemplatedlg.cpp.
References cbWizardPlugin::GetCategory(), cbWizardPlugin::GetCount(), cbWizardPlugin::GetOutputType(), ListItemData::plugin, and SortTemplates().
Referenced by GetWizardIndex().
BuildList()
void NewFromTemplateDlg::BuildList () protected
Definition at line 221 of file newfromtemplatedlg.cpp.
References totCustom, totFiles, totProject, and totTarget.
Referenced by GetWizardIndex().
BuildListFor()
void NewFromTemplateDlg::BuildListFor (TemplateOutputType otype, wxListCtrl * list, const wxChoice * cat) protected
Definition at line 229 of file newfromtemplatedlg.cpp.
References cbWizardPlugin::GetBitmap(), cbWizardPlugin::GetCategory(), cbWizardPlugin::GetCount(), ConfigManager::GetFolder(), cbWizardPlugin::GetOutputType(), cbWizardPlugin::GetScriptFilename(), cbWizardPlugin::GetTitle(), ListItemData::ListItemData(), ListItemData::plugin, sdDataUser, and SortTemplates().
Referenced by GetWizardIndex().
ChangeView()
void NewFromTemplateDlg::ChangeView () protected
Definition at line 384 of file newfromtemplatedlg.cpp.
References totCustom, totFiles, totProject, and totTarget.
Referenced by GetWizardIndex().
ClearList()
void NewFromTemplateDlg::ClearList () protected
Definition at line 147 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex().
ClearListFor()
void NewFromTemplateDlg::ClearListFor (wxListCtrl * list) protected
Definition at line 155 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex().
EditScript()
void NewFromTemplateDlg::EditScript (const wxString & filename) protected
Definition at line 352 of file newfromtemplatedlg.cpp.
References cbMessageBox(), CreateDirRecursively(), ScriptBindings::EndModal(), Manager::Get(), cbEditor::GetControl(), Manager::GetEditorManager(), ConfigManager::GetFolder(), EditorManager::Open(), sdDataGlobal, sdDataUser, EditorBase::SetFilename(), and cbEditor::SetModified().
Referenced by GetWizardIndex().
EndModal()
void NewFromTemplateDlg::EndModal (int retCode)
Definition at line 516 of file newfromtemplatedlg.cpp.
References ScriptBindings::EndModal(), Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Referenced by GetWizardIndex().
FillTemplate()
void NewFromTemplateDlg::FillTemplate (ProjectTemplateLoader * pt) protected
Referenced by GetWizardIndex().
GetSelectedTemplate()
cbWizardPlugin * NewFromTemplateDlg::GetSelectedTemplate ()
Definition at line 322 of file newfromtemplatedlg.cpp.
References ListItemData::plugin, and ListItemData::wizPluginIndex.
Referenced by GetWizardIndex().
GetSelectedUserTemplate()
wxString NewFromTemplateDlg::GetSelectedUserTemplate () const
Definition at line 346 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex(), and TemplateManager::NewProjectFromUserTemplate().
GetTemplate()
ProjectTemplateLoader* NewFromTemplateDlg::GetTemplate () inline
Definition at line 25 of file newfromtemplatedlg.h.
References m_Template.
GetVisibleCategory()
wxChoice * NewFromTemplateDlg::GetVisibleCategory () protected
Definition at line 292 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex().
GetVisibleListCtrl()
wxListCtrl * NewFromTemplateDlg::GetVisibleListCtrl () protected
Definition at line 277 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex().
GetVisibleOutputType()
TemplateOutputType NewFromTemplateDlg::GetVisibleOutputType () const protected
Definition at line 307 of file newfromtemplatedlg.cpp.
References totCustom, totFiles, totProject, and totTarget.
Referenced by GetWizardIndex().
GetWizard()
cbWizardPlugin* NewFromTemplateDlg::GetWizard () inline
Definition at line 26 of file newfromtemplatedlg.h.
References m_pWizard.
Referenced by TemplateManager::NewFromTemplate().
GetWizardIndex()
int NewFromTemplateDlg::GetWizardIndex () const inline
Definition at line 27 of file newfromtemplatedlg.h.
References BuildCategories(), BuildCategoriesFor(), BuildList(), BuildListFor(), ChangeView(), ClearList(), ClearListFor(), EditScript(), EndModal(), FillTemplate(), GetSelectedTemplate(), GetSelectedUserTemplate(), GetVisibleCategory(), GetVisibleListCtrl(), GetVisibleOutputType(), m_WizardIndex, OnCategoryChanged(), OnDiscardScript(), OnEditGlobalScript(), OnEditScript(), OnHelp(), OnListActivate(), OnListRightClick(), OnUpdateUI(), OnViewChange(), and SelectedUserTemplate().
Referenced by TemplateManager::NewFromTemplate().
OnCategoryChanged()
void NewFromTemplateDlg::OnCategoryChanged (wxCommandEvent & event) protected
Definition at line 435 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex().
OnDiscardScript()
void NewFromTemplateDlg::OnDiscardScript (wxCommandEvent & event) protected
Definition at line 453 of file newfromtemplatedlg.cpp.
References cbMessageBox(), ConfigManager::GetFolder(), cbWizardPlugin::GetScriptFilename(), ListItemData::plugin, sdDataUser, and ListItemData::wizPluginIndex.
Referenced by GetWizardIndex().
OnEditGlobalScript()
void NewFromTemplateDlg::OnEditGlobalScript (wxCommandEvent & event) protected
Definition at line 477 of file newfromtemplatedlg.cpp.
References cbMessageBox().
Referenced by GetWizardIndex().
OnEditScript()
void NewFromTemplateDlg::OnEditScript (wxCommandEvent & event) protected
Definition at line 440 of file newfromtemplatedlg.cpp.
References cbWizardPlugin::GetScriptFilename(), ListItemData::plugin, and ListItemData::wizPluginIndex.
Referenced by GetWizardIndex().
OnHelp()
void NewFromTemplateDlg::OnHelp (wxCommandEvent & event) protected
Definition at line 490 of file newfromtemplatedlg.cpp.
References cbMessageBox(), ConfigManager::GetFolder(), and sdDataUser.
Referenced by GetWizardIndex().
OnListActivate()
void NewFromTemplateDlg::OnListActivate (wxListEvent & event) protected
Definition at line 430 of file newfromtemplatedlg.cpp.
References ScriptBindings::EndModal().
Referenced by GetWizardIndex().
OnListRightClick()
void NewFromTemplateDlg::OnListRightClick (wxListEvent & event) protected
Definition at line 404 of file newfromtemplatedlg.cpp.
References ConfigManager::GetFolder(), cbWizardPlugin::GetScriptFilename(), idDiscardWizardScript, idEditGlobalWizardScript, idEditWizardScript, idInfoWizardScript, ListItemData::plugin, sdDataUser, and ListItemData::wizPluginIndex.
Referenced by GetWizardIndex().
OnUpdateUI()
void NewFromTemplateDlg::OnUpdateUI (wxUpdateUIEvent & event) protected
Definition at line 508 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex().
OnViewChange()
void NewFromTemplateDlg::OnViewChange (wxCommandEvent & event) protected
Definition at line 485 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex().
SelectedUserTemplate()
bool NewFromTemplateDlg::SelectedUserTemplate () const
Definition at line 338 of file newfromtemplatedlg.cpp.
Referenced by GetWizardIndex(), TemplateManager::New(), and TemplateManager::NewProjectFromUserTemplate().
Member Data Documentation
m_pWizard
cbWizardPlugin* NewFromTemplateDlg::m_pWizard private
Definition at line 58 of file newfromtemplatedlg.h.
Referenced by GetWizard().
m_Template
ProjectTemplateLoader* NewFromTemplateDlg::m_Template private
Definition at line 57 of file newfromtemplatedlg.h.
Referenced by GetTemplate().
m_WizardIndex
int NewFromTemplateDlg::m_WizardIndex private
Definition at line 59 of file newfromtemplatedlg.h.
Referenced by GetWizardIndex().
m_Wizards
PluginsArray NewFromTemplateDlg::m_Wizards private
Definition at line 60 of file newfromtemplatedlg.h.
The documentation for this class was generated from the following files:
newfromtemplatedlg.h
newfromtemplatedlg.cpp