Code::Blocks: JobQueue Class Reference
JobQueue Class Reference
#include <backgroundthread.h>
Public Member Functions
void Push (AbstractJob *j)
AbstractJob * Pop ()
Private Attributes
wxCriticalSection c
Detailed Description
Definition at line 45 of file backgroundthread.h.
Member Function Documentation
Pop()
AbstractJob* JobQueue::Pop () inline
Definition at line 55 of file backgroundthread.h.
Referenced by BackgroundThread::Entry().
Push()
void JobQueue::Push (AbstractJob * j) inline
Definition at line 50 of file backgroundthread.h.
Referenced by BackgroundThread::Queue(), and BackgroundThreadPool::Queue().
Member Data Documentation
c
wxCriticalSection JobQueue::c private
Definition at line 47 of file backgroundthread.h.
The documentation for this class was generated from the following file:
backgroundthread.h