Code::Blocks: DebuggerSettingsPanel Class Reference
DebuggerSettingsPanel Class Reference
#include <debuggersettingspanel.h>
Public Member Functions
DebuggerSettingsPanel (wxWindow *parent, DebuggerSettingsDlg *dialog, cbDebuggerPlugin *plugin)
virtual ~DebuggerSettingsPanel ()
Private Member Functions
void OnButtonCreate (wxCommandEvent &event)
void OnButtonDelete (wxCommandEvent &event)
void OnButtonReset (wxCommandEvent &event)
Private Attributes
DebuggerSettingsDlg * m_dialog
cbDebuggerPlugin * m_plugin
Static Private Attributes
static const long ID_BUTTON_CREATE = wxNewId()
static const long ID_BUTTON_DELETE = wxNewId()
static const long ID_BUTTON_RESET = wxNewId()
static const long ID_TEXTCTRL_INFO = wxNewId()
Detailed Description
Definition at line 18 of file debuggersettingspanel.h.
Constructor & Destructor Documentation
DebuggerSettingsPanel()
DebuggerSettingsPanel::DebuggerSettingsPanel (wxWindow * parent, DebuggerSettingsDlg * dialog, cbDebuggerPlugin * plugin)
Definition at line 32 of file debuggersettingspanel.cpp.
References _(), _T, wxBoxSizer::Add(), wxBoxSizer::Fit(), OnButtonCreate(), OnButtonDelete(), OnButtonReset(), wxBoxSizer::SetSizeHints(), wxALIGN_BOTTOM, wxALL, wxBOTTOM, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxHORIZONTAL, wxID_ANY, wxLEFT, wxRIGHT, wxSHAPED, wxTAB_TRAVERSAL, and wxVERTICAL.
~DebuggerSettingsPanel()
DebuggerSettingsPanel::~DebuggerSettingsPanel () virtual
Definition at line 79 of file debuggersettingspanel.cpp.
Member Function Documentation
OnButtonCreate()
void DebuggerSettingsPanel::OnButtonCreate (wxCommandEvent & event) private
Definition at line 85 of file debuggersettingspanel.cpp.
References _(), cbMessageBox(), DebuggerSettingsDlg::CreateConfig(), wxString::empty(), m_dialog, m_plugin, PlaceWindow(), wxDialog::ShowModal(), wxICON_ERROR, and wxID_OK.
Referenced by DebuggerSettingsPanel().
OnButtonDelete()
void DebuggerSettingsPanel::OnButtonDelete (wxCommandEvent & event) private
Definition at line 102 of file debuggersettingspanel.cpp.
References DebuggerSettingsDlg::DeleteConfig(), m_dialog, and m_plugin.
Referenced by DebuggerSettingsPanel().
OnButtonReset()
void DebuggerSettingsPanel::OnButtonReset (wxCommandEvent & event) private
Definition at line 107 of file debuggersettingspanel.cpp.
References _(), cbMessageBox(), m_dialog, m_plugin, DebuggerSettingsDlg::ResetConfig(), wxICON_QUESTION, wxID_NO, and wxYES.
Referenced by DebuggerSettingsPanel().
Member Data Documentation
ID_BUTTON_CREATE
const long DebuggerSettingsPanel::ID_BUTTON_CREATE = wxNewId() static private
Definition at line 31 of file debuggersettingspanel.h.
ID_BUTTON_DELETE
const long DebuggerSettingsPanel::ID_BUTTON_DELETE = wxNewId() static private
Definition at line 32 of file debuggersettingspanel.h.
ID_BUTTON_RESET
const long DebuggerSettingsPanel::ID_BUTTON_RESET = wxNewId() static private
Definition at line 33 of file debuggersettingspanel.h.
ID_TEXTCTRL_INFO
const long DebuggerSettingsPanel::ID_TEXTCTRL_INFO = wxNewId() static private
Definition at line 34 of file debuggersettingspanel.h.
m_dialog
DebuggerSettingsDlg* DebuggerSettingsPanel::m_dialog private
Definition at line 45 of file debuggersettingspanel.h.
Referenced by OnButtonCreate(), OnButtonDelete(), and OnButtonReset().
m_plugin
cbDebuggerPlugin* DebuggerSettingsPanel::m_plugin private
Definition at line 46 of file debuggersettingspanel.h.
Referenced by OnButtonCreate(), OnButtonDelete(), and OnButtonReset().
The documentation for this class was generated from the following files:
debuggersettingspanel.h
debuggersettingspanel.cpp