Code::Blocks: cbExecuteProcess Class Reference
cbExecuteProcess Class Reference
#include <cbexecute.h>
Public Member Functions
cbExecuteProcess (wxArrayString *out, wxArrayString *err)
void FlushPipe ()
virtual void OnTerminate (int pid, int status)
bool Running ()
bool ExitCode ()
Public Member Functions inherited from wxProcess
wxProcess (wxEvtHandler *parent=NULL, int id=-1)
wxProcess (int flags)
virtual ~wxProcess ()
void CloseOutput ()
void Detach ()
wxInputStream * GetErrorStream () const
wxInputStream * GetInputStream () const
wxOutputStream * GetOutputStream () const
long GetPid () const
bool IsErrorAvailable () const
bool IsInputAvailable () const
bool IsInputOpened () const
void Redirect ()
void SetPriority (unsigned priority)
Private Attributes
wxInputStream * stream_stdout
wxInputStream * stream_stderr
wxArrayString * std_out
wxArrayString * std_err
bool running
int exitCode
Additional Inherited Members
Static Public Member Functions inherited from wxProcess
static bool Exists (int pid)
static wxKillError Kill (int pid, wxSignal sig=wxSIGTERM, int flags=wxKILL_NOCHILDREN)
static wxProcess * Open (const wxString &cmd, int flags=wxEXEC_ASYNC)
Detailed Description
Definition at line 21 of file cbexecute.h.
Constructor & Destructor Documentation
cbExecuteProcess()
cbExecuteProcess::cbExecuteProcess (wxArrayString * out, wxArrayString * err) inline
Definition at line 32 of file cbexecute.h.
References wxProcess::Redirect().
Member Function Documentation
ExitCode()
bool cbExecuteProcess::ExitCode () inline
Definition at line 76 of file cbexecute.h.
References exitCode.
Referenced by cbSyncExecute().
FlushPipe()
void cbExecuteProcess::FlushPipe () inline
Definition at line 37 of file cbexecute.h.
References wxArrayString::Add(), wxProcess::GetErrorStream(), wxProcess::GetInputStream(), and wxTextInputStream::ReadLine().
Referenced by OnTerminate().
OnTerminate()
virtual void cbExecuteProcess::OnTerminate (int pid, int status) inline virtual
Reimplemented from wxProcess.
Definition at line 65 of file cbexecute.h.
References FlushPipe().
Running()
bool cbExecuteProcess::Running () inline
Definition at line 72 of file cbexecute.h.
References running.
Referenced by cbSyncExecute().
Member Data Documentation
exitCode
int cbExecuteProcess::exitCode private
Definition at line 29 of file cbexecute.h.
Referenced by ExitCode().
running
bool cbExecuteProcess::running private
Definition at line 28 of file cbexecute.h.
Referenced by Running().
std_err
wxArrayString* cbExecuteProcess::std_err private
Definition at line 27 of file cbexecute.h.
std_out
wxArrayString* cbExecuteProcess::std_out private
Definition at line 26 of file cbexecute.h.
stream_stderr
wxInputStream* cbExecuteProcess::stream_stderr private
Definition at line 24 of file cbexecute.h.
stream_stdout
wxInputStream* cbExecuteProcess::stream_stdout private
Definition at line 23 of file cbexecute.h.
The documentation for this class was generated from the following file:
cbexecute.h