Code::Blocks: pfDetails Class Reference
pfDetails Class Reference
This is a helper class that caches various filenames for one ProjectFile.
#include <projectfile.h>
Public Member Functions
pfDetails (ProjectBuildTarget *target, ProjectFile *pf)
void Update (ProjectBuildTarget *target, ProjectFile *pf)
Public Attributes
wxString source_file
wxString object_file
wxString dep_file
wxString object_dir
wxString object_dir_flat
wxString dep_dir
wxString object_file_flat
wxString source_file_native
wxString object_file_native
wxString dep_file_native
wxString object_dir_native
wxString object_dir_flat_native
wxString dep_dir_native
wxString source_file_absolute_native
wxString object_file_absolute_native
wxString object_file_flat_absolute_native
wxString dep_file_absolute_native
wxString object_file_flat_native
Detailed Description
This is a helper class that caches various filenames for one ProjectFile.
These include the source filename, the generated object filename, relative and absolute versions of the above, etc. Mainly used by the compiler...
Definition at line 241 of file projectfile.h.
Constructor & Destructor Documentation
pfDetails()
pfDetails::pfDetails (ProjectBuildTarget * target, ProjectFile * pf)
Definition at line 343 of file projectfile.cpp.
Member Function Documentation
Update()
void pfDetails::Update (ProjectBuildTarget * target, ProjectFile * pf)
Definition at line 348 of file projectfile.cpp.
References cbMessageBox(), ProjectFile::file, FileTypeOf(), ftDynamicLib, ftHeader, ftObject, ftResource, ftResourceBin, ftStaticLib, ProjectFile::generatedFiles, Manager::Get(), CompileTargetBase::GetBasePath(), CompilerFactory::GetCompiler(), CompileTargetBase::GetCompilerID(), CompilerFactory::GetDefaultCompiler(), CompileTargetBase::GetDepsOutput(), cbProject::GetExtendedObjectNamesGeneration(), Manager::GetMacrosManager(), cbProject::GetModeForPCH(), CompileTargetBase::GetObjectOutput(), ProjectFile::GetObjName(), ProjectBuildTarget::GetParentProject(), ProjectFile::GetParentProject(), Compiler::GetSwitches(), CompileTargetBase::GetTitle(), CompilerSwitches::objectExtension, CompilerSwitches::PCHExtension, pchObjectDir, pchSourceDir, pchSourceFile, QuoteStringIfNeeded(), ProjectFile::relativeFilename, ProjectFile::relativeToCommonTopLevelPath, MacrosManager::ReplaceEnvVars(), MacrosManager::ReplaceMacros(), FileFilters::RESOURCEBIN_DOT_EXT, FileFilters::RESOURCEBIN_EXT, HTMLTags::sep, CompilerSwitches::supportsPCH, and UnixFilename().
Referenced by ProjectFile::DoUpdateFileDetails().
Member Data Documentation
dep_dir
wxString pfDetails::dep_dir
Definition at line 252 of file projectfile.h.
dep_dir_native
wxString pfDetails::dep_dir_native
Definition at line 260 of file projectfile.h.
dep_file
wxString pfDetails::dep_file
Definition at line 249 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand().
dep_file_absolute_native
wxString pfDetails::dep_file_absolute_native
Definition at line 264 of file projectfile.h.
Referenced by DirectCommands::GetTargetCleanCommands().
dep_file_native
wxString pfDetails::dep_file_native
Definition at line 257 of file projectfile.h.
object_dir
wxString pfDetails::object_dir
Definition at line 250 of file projectfile.h.
object_dir_flat
wxString pfDetails::object_dir_flat
Definition at line 251 of file projectfile.h.
object_dir_flat_native
wxString pfDetails::object_dir_flat_native
Definition at line 259 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand().
object_dir_native
wxString pfDetails::object_dir_native
Definition at line 258 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand().
object_file
wxString pfDetails::object_file
Definition at line 248 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand(), and DirectCommands::GetTargetLinkCommands().
object_file_absolute_native
wxString pfDetails::object_file_absolute_native
Definition at line 262 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand(), DirectCommands::GetTargetCleanCommands(), and DirectCommands::IsObjectOutdated().
object_file_flat
wxString pfDetails::object_file_flat
Definition at line 253 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand(), and DirectCommands::GetTargetLinkCommands().
object_file_flat_absolute_native
wxString pfDetails::object_file_flat_absolute_native
Definition at line 263 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand(), DirectCommands::GetTargetCleanCommands(), and DirectCommands::IsObjectOutdated().
object_file_flat_native
wxString pfDetails::object_file_flat_native
Definition at line 265 of file projectfile.h.
object_file_native
wxString pfDetails::object_file_native
Definition at line 256 of file projectfile.h.
Referenced by DirectCommands::GetTargetLinkCommands().
source_file
wxString pfDetails::source_file
Definition at line 247 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand().
source_file_absolute_native
wxString pfDetails::source_file_absolute_native
Definition at line 261 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand(), and DirectCommands::IsObjectOutdated().
source_file_native
wxString pfDetails::source_file_native
Definition at line 255 of file projectfile.h.
Referenced by DirectCommands::GetCompileFileCommand().
The documentation for this class was generated from the following files:
projectfile.h
projectfile.cpp