Code::Blocks: CompilerPanel Class Reference
CompilerPanel Class Reference
#include <compilerpanel.h>
Public Member Functions
CompilerPanel (wxWindow *parent, wxWindow *parentDialog)
virtual ~CompilerPanel ()
wxComboBox * GetCompilerCombo ()
void EnableConfigurationTargets (bool en)
void SetWantDebug (bool want)
bool GetWantDebug () const
void SetDebugName (const wxString &name)
wxString GetDebugName () const
void SetDebugOutputDir (const wxString &dir)
wxString GetDebugOutputDir () const
void SetDebugObjectOutputDir (const wxString &dir)
wxString GetDebugObjectOutputDir () const
void SetWantRelease (bool want)
bool GetWantRelease () const
void SetReleaseName (const wxString &name)
wxString GetReleaseName () const
void SetReleaseOutputDir (const wxString &dir)
wxString GetReleaseOutputDir () const
void SetReleaseObjectOutputDir (const wxString &dir)
wxString GetReleaseObjectOutputDir () const
Static Public Attributes
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_COMBOBOX1 = wxNewId()
static const long ID_CHECKBOX1 = wxNewId()
static const long ID_TEXTCTRL3 = wxNewId()
static const long ID_STATICTEXT3 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_TEXTCTRL2 = wxNewId()
static const long ID_CHECKBOX3 = wxNewId()
static const long ID_TEXTCTRL4 = wxNewId()
static const long ID_STATICTEXT7 = wxNewId()
static const long ID_TEXTCTRL5 = wxNewId()
static const long ID_STATICTEXT8 = wxNewId()
static const long ID_TEXTCTRL6 = wxNewId()
Private Member Functions
void OnDebugChange (wxCommandEvent &event)
void OnReleaseChange (wxCommandEvent &event)
Private Attributes
wxStaticBoxSizer * StaticBoxSizer2
wxTextCtrl * txtDbgObjOut
wxComboBox * cmbCompiler
wxTextCtrl * txtRelName
wxStaticText * StaticText1
wxBoxSizer * BoxSizer4
wxCheckBox * chkConfRelease
wxTextCtrl * txtDbgName
wxTextCtrl * txtRelObjOut
wxTextCtrl * txtRelOut
wxTextCtrl * txtDbgOut
wxBoxSizer * BoxSizer5
wxStaticBoxSizer * StaticBoxSizer1
wxCheckBox * chkConfDebug
wxWindow * m_parentDialog
Detailed Description
Definition at line 20 of file compilerpanel.h.
Constructor & Destructor Documentation
CompilerPanel()
CompilerPanel::CompilerPanel (wxWindow * parent, wxWindow * parentDialog)
Definition at line 44 of file compilerpanel.cpp.
References _(), _T, wxBoxSizer::Add(), wxFlexGridSizer::AddGrowableCol(), wxBoxSizer::Fit(), OnDebugChange(), OnReleaseChange(), wxBoxSizer::SetSizeHints(), wxALIGN_CENTER_VERTICAL, wxALIGN_TOP, wxALL, wxBOTTOM, wxCB_READONLY, wxCB_SIMPLE, wxDefaultPosition, wxDefaultSize, wxDefaultValidator, wxEmptyString, wxEXPAND, wxHORIZONTAL, wxID_ANY, wxLEFT, wxRIGHT, wxTAB_TRAVERSAL, wxTOP, and wxVERTICAL.
~CompilerPanel()
CompilerPanel::~CompilerPanel () virtual
Definition at line 122 of file compilerpanel.cpp.
Member Function Documentation
EnableConfigurationTargets()
void CompilerPanel::EnableConfigurationTargets (bool en)
Definition at line 153 of file compilerpanel.cpp.
References _(), chkConfDebug, chkConfRelease, wxBoxSizer::Show(), StaticBoxSizer1, StaticBoxSizer2, StaticText1, txtDbgName, txtDbgObjOut, txtDbgOut, txtRelName, txtRelObjOut, and txtRelOut.
Referenced by GetCompilerCombo(), and WizCompilerPanel::WizCompilerPanel().
GetCompilerCombo()
wxComboBox* CompilerPanel::GetCompilerCombo () inline
Definition at line 27 of file compilerpanel.h.
References cmbCompiler, and EnableConfigurationTargets().
Referenced by WizCompilerPanel::GetCompilerID(), and WizCompilerPanel::WizCompilerPanel().
GetDebugName()
wxString CompilerPanel::GetDebugName () const inline
Definition at line 33 of file compilerpanel.h.
References txtDbgName.
Referenced by WizCompilerPanel::GetDebugName().
GetDebugObjectOutputDir()
wxString CompilerPanel::GetDebugObjectOutputDir () const inline
Definition at line 37 of file compilerpanel.h.
References txtDbgObjOut.
Referenced by WizCompilerPanel::GetDebugObjectOutputDir().
GetDebugOutputDir()
wxString CompilerPanel::GetDebugOutputDir () const inline
Definition at line 35 of file compilerpanel.h.
References txtDbgOut.
Referenced by WizCompilerPanel::GetDebugOutputDir().
GetReleaseName()
wxString CompilerPanel::GetReleaseName () const inline
Definition at line 42 of file compilerpanel.h.
References txtRelName.
Referenced by WizCompilerPanel::GetReleaseName().
GetReleaseObjectOutputDir()
wxString CompilerPanel::GetReleaseObjectOutputDir () const inline
Definition at line 46 of file compilerpanel.h.
References txtRelObjOut.
Referenced by WizCompilerPanel::GetReleaseObjectOutputDir().
GetReleaseOutputDir()
wxString CompilerPanel::GetReleaseOutputDir () const inline
Definition at line 44 of file compilerpanel.h.
References txtRelOut.
Referenced by WizCompilerPanel::GetReleaseOutputDir().
GetWantDebug()
bool CompilerPanel::GetWantDebug () const inline
Definition at line 31 of file compilerpanel.h.
References chkConfDebug, and wxCheckBox::IsChecked().
Referenced by WizCompilerPanel::GetWantDebug().
GetWantRelease()
bool CompilerPanel::GetWantRelease () const inline
Definition at line 40 of file compilerpanel.h.
References chkConfRelease, and wxCheckBox::IsChecked().
Referenced by WizCompilerPanel::GetWantRelease().
OnDebugChange()
void CompilerPanel::OnDebugChange (wxCommandEvent & event) private
Definition at line 127 of file compilerpanel.cpp.
References _(), cbMessageBox(), chkConfDebug, chkConfRelease, wxCheckBox::IsChecked(), m_parentDialog, wxCheckBox::SetValue(), txtDbgName, txtDbgObjOut, txtDbgOut, and wxICON_WARNING.
Referenced by CompilerPanel().
OnReleaseChange()
void CompilerPanel::OnReleaseChange (wxCommandEvent & event) private
Definition at line 140 of file compilerpanel.cpp.
References _(), cbMessageBox(), chkConfDebug, chkConfRelease, wxCheckBox::IsChecked(), m_parentDialog, wxCheckBox::SetValue(), txtRelName, txtRelObjOut, txtRelOut, and wxICON_WARNING.
Referenced by CompilerPanel().
SetDebugName()
void CompilerPanel::SetDebugName (const wxString & name) inline
Definition at line 32 of file compilerpanel.h.
References txtDbgName.
Referenced by WizCompilerPanel::WizCompilerPanel().
SetDebugObjectOutputDir()
void CompilerPanel::SetDebugObjectOutputDir (const wxString & dir) inline
Definition at line 36 of file compilerpanel.h.
References txtDbgObjOut.
Referenced by WizCompilerPanel::WizCompilerPanel().
SetDebugOutputDir()
void CompilerPanel::SetDebugOutputDir (const wxString & dir) inline
Definition at line 34 of file compilerpanel.h.
References txtDbgOut.
Referenced by WizCompilerPanel::WizCompilerPanel().
SetReleaseName()
void CompilerPanel::SetReleaseName (const wxString & name) inline
Definition at line 41 of file compilerpanel.h.
References txtRelName.
Referenced by WizCompilerPanel::WizCompilerPanel().
SetReleaseObjectOutputDir()
void CompilerPanel::SetReleaseObjectOutputDir (const wxString & dir) inline
Definition at line 45 of file compilerpanel.h.
References txtRelObjOut.
Referenced by WizCompilerPanel::WizCompilerPanel().
SetReleaseOutputDir()
void CompilerPanel::SetReleaseOutputDir (const wxString & dir) inline
Definition at line 43 of file compilerpanel.h.
References txtRelOut.
Referenced by WizCompilerPanel::WizCompilerPanel().
SetWantDebug()
void CompilerPanel::SetWantDebug (bool want) inline
Definition at line 30 of file compilerpanel.h.
References chkConfDebug, and wxCheckBox::SetValue().
Referenced by WizCompilerPanel::WizCompilerPanel().
SetWantRelease()
void CompilerPanel::SetWantRelease (bool want) inline
Definition at line 39 of file compilerpanel.h.
References chkConfRelease, and wxCheckBox::SetValue().
Referenced by WizCompilerPanel::WizCompilerPanel().
Member Data Documentation
BoxSizer4
wxBoxSizer* CompilerPanel::BoxSizer4 private
Definition at line 79 of file compilerpanel.h.
BoxSizer5
wxBoxSizer* CompilerPanel::BoxSizer5 private
Definition at line 85 of file compilerpanel.h.
chkConfDebug
wxCheckBox* CompilerPanel::chkConfDebug private
Definition at line 87 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetWantDebug(), OnDebugChange(), OnReleaseChange(), and SetWantDebug().
chkConfRelease
wxCheckBox* CompilerPanel::chkConfRelease private
Definition at line 80 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetWantRelease(), OnDebugChange(), OnReleaseChange(), and SetWantRelease().
cmbCompiler
wxComboBox* CompilerPanel::cmbCompiler private
Definition at line 76 of file compilerpanel.h.
Referenced by GetCompilerCombo().
ID_CHECKBOX1
const long CompilerPanel::ID_CHECKBOX1 = wxNewId() static
Definition at line 52 of file compilerpanel.h.
ID_CHECKBOX3
const long CompilerPanel::ID_CHECKBOX3 = wxNewId() static
Definition at line 58 of file compilerpanel.h.
ID_COMBOBOX1
const long CompilerPanel::ID_COMBOBOX1 = wxNewId() static
Definition at line 51 of file compilerpanel.h.
ID_STATICTEXT1
const long CompilerPanel::ID_STATICTEXT1 = wxNewId() static
Definition at line 49 of file compilerpanel.h.
ID_STATICTEXT2
const long CompilerPanel::ID_STATICTEXT2 = wxNewId() static
Definition at line 50 of file compilerpanel.h.
ID_STATICTEXT3
const long CompilerPanel::ID_STATICTEXT3 = wxNewId() static
Definition at line 54 of file compilerpanel.h.
ID_STATICTEXT4
const long CompilerPanel::ID_STATICTEXT4 = wxNewId() static
Definition at line 56 of file compilerpanel.h.
ID_STATICTEXT7
const long CompilerPanel::ID_STATICTEXT7 = wxNewId() static
Definition at line 60 of file compilerpanel.h.
ID_STATICTEXT8
const long CompilerPanel::ID_STATICTEXT8 = wxNewId() static
Definition at line 62 of file compilerpanel.h.
ID_TEXTCTRL1
const long CompilerPanel::ID_TEXTCTRL1 = wxNewId() static
Definition at line 55 of file compilerpanel.h.
ID_TEXTCTRL2
const long CompilerPanel::ID_TEXTCTRL2 = wxNewId() static
Definition at line 57 of file compilerpanel.h.
ID_TEXTCTRL3
const long CompilerPanel::ID_TEXTCTRL3 = wxNewId() static
Definition at line 53 of file compilerpanel.h.
ID_TEXTCTRL4
const long CompilerPanel::ID_TEXTCTRL4 = wxNewId() static
Definition at line 59 of file compilerpanel.h.
ID_TEXTCTRL5
const long CompilerPanel::ID_TEXTCTRL5 = wxNewId() static
Definition at line 61 of file compilerpanel.h.
ID_TEXTCTRL6
const long CompilerPanel::ID_TEXTCTRL6 = wxNewId() static
Definition at line 63 of file compilerpanel.h.
m_parentDialog
wxWindow* CompilerPanel::m_parentDialog private
Definition at line 90 of file compilerpanel.h.
Referenced by OnDebugChange(), and OnReleaseChange().
StaticBoxSizer1
wxStaticBoxSizer* CompilerPanel::StaticBoxSizer1 private
Definition at line 86 of file compilerpanel.h.
Referenced by EnableConfigurationTargets().
StaticBoxSizer2
wxStaticBoxSizer* CompilerPanel::StaticBoxSizer2 private
Definition at line 74 of file compilerpanel.h.
Referenced by EnableConfigurationTargets().
StaticText1
wxStaticText* CompilerPanel::StaticText1 private
Definition at line 78 of file compilerpanel.h.
Referenced by EnableConfigurationTargets().
txtDbgName
wxTextCtrl* CompilerPanel::txtDbgName private
Definition at line 81 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetDebugName(), OnDebugChange(), and SetDebugName().
txtDbgObjOut
wxTextCtrl* CompilerPanel::txtDbgObjOut private
Definition at line 75 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetDebugObjectOutputDir(), OnDebugChange(), and SetDebugObjectOutputDir().
txtDbgOut
wxTextCtrl* CompilerPanel::txtDbgOut private
Definition at line 84 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetDebugOutputDir(), OnDebugChange(), and SetDebugOutputDir().
txtRelName
wxTextCtrl* CompilerPanel::txtRelName private
Definition at line 77 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetReleaseName(), OnReleaseChange(), and SetReleaseName().
txtRelObjOut
wxTextCtrl* CompilerPanel::txtRelObjOut private
Definition at line 82 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetReleaseObjectOutputDir(), OnReleaseChange(), and SetReleaseObjectOutputDir().
txtRelOut
wxTextCtrl* CompilerPanel::txtRelOut private
Definition at line 83 of file compilerpanel.h.
Referenced by EnableConfigurationTargets(), GetReleaseOutputDir(), OnReleaseChange(), and SetReleaseOutputDir().
The documentation for this class was generated from the following files:
compilerpanel.h
compilerpanel.cpp