Code::Blocks: ListCtrlLogger Class Reference
ListCtrlLogger Class Reference
a logger which prints messages to a wxListCtrl
#include <loggers.h>
Classes
struct ListStyles
Public Member Functions
ListCtrlLogger (const wxArrayString &titles, const wxArrayInt &widths, bool fixedPitchFont=false)
~ListCtrlLogger () override
void CopyContentsToClipboard (bool selectionOnly=false) override
void UpdateSettings () override
void Append (const wxString &msg, Logger::level lv=info) override
virtual void Append (const wxArrayString &colValues, Logger::level lv=info, int autoSize=-1)
virtual size_t GetItemsCount () const
void Clear () override
wxWindow * CreateControl (wxWindow *parent) override
bool HasFeature (Feature::Enum feature) const override
virtual void AutoFitColumns (int column)
Public Member Functions inherited from Logger
Logger ()
virtual ~Logger ()
virtual void CopyContentsToClipboard (cb_optional bool selectionOnly=false)
virtual wxWindow * CreateControl (cb_optional wxWindow *parent)
virtual bool GetWrapMode () const
virtual bool HasFeature (cb_optional Feature::Enum feature) const
virtual void AppendAdditionalMenuItems (cb_optional wxMenu &menu)
Protected Member Functions
wxString GetItemAsText (long item) const
Protected Attributes
wxListCtrl * control
bool fixed
wxArrayString titles
wxArrayInt widths
ListStyles style [num_levels]
Additional Inherited Members
Public Types inherited from Logger
enum level {
caption, info, warning, success,
error, critical, failure, pagetitle,
spacer, asterisk
}
enum { num_levels = asterisk +1 }
Detailed Description
a logger which prints messages to a wxListCtrl
Definition at line 120 of file loggers.h.
Class Documentation
ListCtrlLogger::ListStyles
struct ListCtrlLogger::ListStyles
Definition at line 129 of file loggers.h.
Class Members
wxColour colour
wxFont font
Constructor & Destructor Documentation
ListCtrlLogger()
ListCtrlLogger::ListCtrlLogger (const wxArrayString & titles, const wxArrayInt & widths, bool fixedPitchFont = false)
Definition at line 247 of file loggers.cpp.
References cbAssert, wxArrayString::GetCount(), titles, and widths.
~ListCtrlLogger()
ListCtrlLogger::~ListCtrlLogger () override
Definition at line 256 of file loggers.cpp.
References control.
Member Function Documentation
Append() [1/2]
void ListCtrlLogger::Append (const wxString & msg, Logger::level lv = info) override virtual
Implements Logger.
Definition at line 363 of file loggers.cpp.
References control, wxListCtrl::GetItemCount(), wxListCtrl::InsertItem(), wxListCtrl::SetItemFont(), wxListCtrl::SetItemTextColour(), and style.
Referenced by Append(), CodeRefactoring::DoFindReferences(), and FindReplace::LogSearch().
Append() [2/2]
void ListCtrlLogger::Append (const wxArrayString & colValues, Logger::level lv = info, int autoSize = -1) virtual
Definition at line 377 of file loggers.cpp.
References Append(), AutoFitColumns(), control, wxArrayString::GetCount(), wxListCtrl::GetItemCount(), wxListCtrl::SetItem(), and titles.
AutoFitColumns()
void ListCtrlLogger::AutoFitColumns (int column) virtual
Reimplemented in CompilerMessages.
Definition at line 430 of file loggers.cpp.
References control, wxListCtrl::SetColumnWidth(), and wxLIST_AUTOSIZE.
Referenced by Append().
Clear()
void ListCtrlLogger::Clear () override virtual
Reimplemented from Logger.
Definition at line 399 of file loggers.cpp.
References control, and wxListCtrl::DeleteAllItems().
Referenced by CodeRefactoring::DoFindReferences(), and FindReplace::FindInFiles().
CopyContentsToClipboard()
void ListCtrlLogger::CopyContentsToClipboard (bool selectionOnly = false) override
Definition at line 261 of file loggers.cpp.
References _T, control, GetItemAsText(), wxListCtrl::GetItemCount(), wxListCtrl::GetNextItem(), wxLIST_NEXT_ALL, wxLIST_STATE_SELECTED, and wxTheClipboard.
CreateControl()
wxWindow * ListCtrlLogger::CreateControl (wxWindow * parent) override
Definition at line 405 of file loggers.cpp.
References control, wxArrayString::GetCount(), wxListCtrl::InsertColumn(), titles, widths, wxDefaultPosition, wxDefaultSize, wxLC_REPORT, wxLC_SINGLE_SEL, and wxLIST_FORMAT_LEFT.
Referenced by cbSearchResultsLog::CreateControl(), CompilerMessages::CreateControl(), and cbSearchResultsLog::SetBasePath().
GetItemAsText()
wxString ListCtrlLogger::GetItemAsText (long item) const protected
Definition at line 288 of file loggers.cpp.
References _T, control, wxArrayString::GetCount(), wxListCtrl::GetItem(), titles, wxEmptyString, and wxLIST_MASK_TEXT.
Referenced by CopyContentsToClipboard().
GetItemsCount()
size_t ListCtrlLogger::GetItemsCount () const virtual
Definition at line 394 of file loggers.cpp.
References control, and wxListCtrl::GetItemCount().
Referenced by FindReplace::FindInFiles().
HasFeature()
bool ListCtrlLogger::HasFeature (Feature::Enum feature) const override
Definition at line 417 of file loggers.cpp.
References Logger::Feature::CanClear, and Logger::Feature::CanCopy.
Referenced by CompilerMessages::HasFeature().
UpdateSettings()
void ListCtrlLogger::UpdateSettings () override virtual
Reimplemented from Logger.
Definition at line 308 of file loggers.cpp.
References _T, Logger::caption, ListCtrlLogger::ListStyles::colour, control, Logger::critical, Logger::error, Logger::failure, fixed, ListCtrlLogger::ListStyles::font, Manager::Get(), wxSystemSettings::GetColour(), ColourManager::GetColour(), Manager::GetColourManager(), Manager::GetConfigManager(), wxListCtrl::GetItemCount(), wxListCtrl::GetItemFont(), Logger::num_levels, Logger::pagetitle, ConfigManager::ReadInt(), wxListCtrl::SetItemFont(), wxFont::SetPointSize(), wxFont::SetStyle(), wxFont::SetWeight(), Logger::spacer, style, Logger::success, Logger::warning, wxFONTFAMILY_DEFAULT, wxFONTFAMILY_MODERN, wxFONTSTYLE_ITALIC, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, wxFONTWEIGHT_NORMAL, wxSYS_COLOUR_WINDOWTEXT, and wxT.
Member Data Documentation
control
wxListCtrl* ListCtrlLogger::control protected
Definition at line 124 of file loggers.h.
Referenced by Append(), AutoFitColumns(), Clear(), CopyContentsToClipboard(), cbSearchResultsLog::CreateControl(), CompilerMessages::CreateControl(), CreateControl(), CompilerMessages::FitColumns(), cbSearchResultsLog::FocusEntry(), CompilerMessages::FocusError(), GetItemAsText(), GetItemsCount(), CompilerMessages::OnClick(), cbSearchResultsLog::OnDoubleClick(), cbSearchResultsLog::SyncEditor(), UpdateSettings(), and ~ListCtrlLogger().
fixed
bool ListCtrlLogger::fixed protected
Definition at line 125 of file loggers.h.
Referenced by UpdateSettings().
style
ListStyles ListCtrlLogger::style[num_levels] protected
Definition at line 134 of file loggers.h.
Referenced by Append(), and UpdateSettings().
titles
wxArrayString ListCtrlLogger::titles protected
Definition at line 126 of file loggers.h.
Referenced by Append(), CreateControl(), GetItemAsText(), and ListCtrlLogger().
widths
wxArrayInt ListCtrlLogger::widths protected
Definition at line 127 of file loggers.h.
Referenced by CreateControl(), and ListCtrlLogger().
The documentation for this class was generated from the following files:
loggers.h
loggers.cpp