Code::Blocks: wxScrollingPropertySheetDialog Class Reference
wxScrollingPropertySheetDialog Class Reference
#include <scrollingdialog.h>
Public Member Functions
wxScrollingPropertySheetDialog ()
wxScrollingPropertySheetDialog (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &sz=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=wxDialogNameStr)
virtual wxWindow * GetContentWindow () const
Returns the content window.
virtual bool Show (bool show=true)
Operations.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void Init ()
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
A wxPropertySheetDialog class that makes its content scroll if necessary.
Constructor & Destructor Documentation
wxScrollingPropertySheetDialog::wxScrollingPropertySheetDialog () inline
References Init().
wxScrollingPropertySheetDialog::wxScrollingPropertySheetDialog (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & sz = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE, const wxString & name = wxDialogNameStr) inline
References Init().
Member Function Documentation
wxWindow * wxScrollingPropertySheetDialog::GetContentWindow () const virtual
Returns the content window.
Reimplemented from wxDialogHelper.
void wxScrollingPropertySheetDialog::Init () private
wxScrollingPropertySheetDialog
References wxDialogHelper::SetDialog().
Referenced by wxScrollingPropertySheetDialog().
bool wxScrollingPropertySheetDialog::Show (bool show = true) virtual
Operations.
Override Show to rejig the control and sizer hierarchy if necessary.
Override Show to rejig the control and sizer hierarchy if necessary
References wxDialogHelper::CanDoLayoutAdaptation(), and wxDialogHelper::DoLayoutAdaptation().
int wxScrollingPropertySheetDialog::ShowModal () virtual
Override ShowModal to rejig the control and sizer hierarchy if necessary.
References wxDialogHelper::CanDoLayoutAdaptation(), and wxDialogHelper::DoLayoutAdaptation().
The documentation for this class was generated from the following files:
scrollingdialog.h
scrollingdialog.cpp