Code::Blocks: cbWatchesDlg Class Reference
cbWatchesDlg Class Reference abstract
#include <cbdebugger_interfaces.h>
Public Member Functions
virtual ~cbWatchesDlg ()
virtual wxWindow * GetWindow ()=0
virtual void UpdateWatches ()=0
virtual void AddWatch (cb::shared_ptr< cbWatch > watch)=0
virtual void AddSpecialWatch (cb::shared_ptr< cbWatch > watch, bool readonly)=0
virtual void RemoveWatch (cb::shared_ptr< cbWatch > watch)=0
virtual void RenameWatch (wxObject *prop, const wxString &newSymbol)=0
virtual void RefreshUI ()=0
Detailed Description
Definition at line 105 of file cbdebugger_interfaces.h.
Constructor & Destructor Documentation
~cbWatchesDlg()
cbWatchesDlg::~cbWatchesDlg () virtual
Definition at line 21 of file cbdebugger_interfaces.cpp.
Member Function Documentation
AddSpecialWatch()
virtual void cbWatchesDlg::AddSpecialWatch (cb::shared_ptr< cbWatch > watch, bool readonly) pure virtual
Implemented in WatchesDlg.
Referenced by DebuggerGDB::DoWatches().
AddWatch()
virtual void cbWatchesDlg::AddWatch (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in WatchesDlg.
Referenced by DebuggerMenuHandler::OnAddWatch(), and WatchesDropTarget::OnDropText().
GetWindow()
virtual wxWindow* cbWatchesDlg::GetWindow () pure virtual
Implemented in WatchesDlg.
Referenced by DebugInterfaceFactory::DeleteWatches(), DebuggerMenuHandler::OnAddWatch(), and DebuggerGDB::OnCursorChanged().
RefreshUI()
virtual void cbWatchesDlg::RefreshUI () pure virtual
Implemented in WatchesDlg.
Referenced by DebuggerManager::RefreshUI().
RemoveWatch()
virtual void cbWatchesDlg::RemoveWatch (cb::shared_ptr< cbWatch > watch) pure virtual
Implemented in WatchesDlg.
Referenced by DebuggerGDB::OnConfigurationChange().
RenameWatch()
virtual void cbWatchesDlg::RenameWatch (wxObject * prop, const wxString & newSymbol) pure virtual
Implemented in WatchesDlg.
Referenced by DebuggerGDB::OnMenuWatchDereference().
UpdateWatches()
virtual void cbWatchesDlg::UpdateWatches () pure virtual
Implemented in WatchesDlg.
Referenced by DbgCmd_UpdateWatchesTree::Action().
The documentation for this class was generated from the following files:
cbdebugger_interfaces.h
cbdebugger_interfaces.cpp