Code::Blocks: MarkFileAsLocalThreadedTask Class Reference
MarkFileAsLocalThreadedTask Class Reference
#include <parserthreadedtask.h>
Public Member Functions
MarkFileAsLocalThreadedTask (Parser *parser, cbProject *project)
virtual int Execute ()
Override this function with the task's job Return value doesn't matter.
Public Member Functions inherited from cbThreadedTask
cbThreadedTask ()
cbThreadedTask ctor
virtual ~cbThreadedTask ()=0
cbThreadedTask dtor
void Abort ()
This function is called to tell the task to abort (check cbThreadPool::AbortAllTasks)
Private Attributes
Parser * m_Parser
cbProject * m_Project
Additional Inherited Members
Protected Member Functions inherited from cbThreadedTask
bool TestDestroy () const
Be sure to call this function often. If it returns true, quit your task quickly.
bool Aborted () const
Same as TestDestroy()
Detailed Description
Definition at line 27 of file parserthreadedtask.h.
Constructor & Destructor Documentation
MarkFileAsLocalThreadedTask()
MarkFileAsLocalThreadedTask::MarkFileAsLocalThreadedTask (Parser * parser, cbProject * project)
Definition at line 111 of file parserthreadedtask.cpp.
Member Function Documentation
Execute()
int MarkFileAsLocalThreadedTask::Execute () virtual
Override this function with the task's job Return value doesn't matter.
Implements cbThreadedTask.
Definition at line 116 of file parserthreadedtask.cpp.
References CC_LOCKER_TRACK_TT_MTX_LOCK, CC_LOCKER_TRACK_TT_MTX_UNLOCK, ProjectFile::file, ParserCommon::FileType(), ParserCommon::ftOther, cbProject::GetFilesList(), ParserBase::GetTokenTree(), m_Parser, m_Project, TokenTree::MarkFileTokensAsLocal(), ProjectFile::relativeFilename, s_TokenTreeMutex, and TRACE.
Member Data Documentation
m_Parser
Parser* MarkFileAsLocalThreadedTask::m_Parser private
Definition at line 34 of file parserthreadedtask.h.
Referenced by Execute().
m_Project
cbProject* MarkFileAsLocalThreadedTask::m_Project private
Definition at line 35 of file parserthreadedtask.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
parserthreadedtask.h
parserthreadedtask.cpp