Code::Blocks: SelectTargetDlg Class Reference
SelectTargetDlg Class Reference
#include <selecttargetdlg.h>
Public Member Functions
SelectTargetDlg (wxWindow *parent, cbProject *project, int selected=0)
~SelectTargetDlg ()
void EndModal (int retCode)
int GetSelection () const
ProjectBuildTarget * GetSelectionTarget ()
Public Member Functions inherited from wxScrollingDialog
wxScrollingDialog ()
wxScrollingDialog (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
bool Create (wxWindow *parent, int id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=_("dialogBox"))
void Init ()
virtual bool Show (bool show=true)
Override Show to rejig the control and sizer hierarchy if necessary.
virtual int ShowModal ()
Override ShowModal to rejig the control and sizer hierarchy if necessary.
Public Member Functions inherited from wxDialogHelper
wxDialogHelper (wxDialog *dialog=NULL)
virtual ~wxDialogHelper ()
void Init ()
void SetDialog (wxDialog *dialog)
wxDialog * GetDialog () const
virtual bool DoLayoutAdaptation ()
Do the adaptation.
virtual bool CanDoLayoutAdaptation ()
Can we do the adaptation?
virtual wxWindow * GetContentWindow () const
Returns a content window if there is one.
void AddButtonId (wxWindowID id)
Add an id to the list of custom button identifiers that should be in the button sizer.
wxArrayInt & GetButtonIds ()
bool IsUserButtonId (wxWindowID id)
Is this id in the custom button id array?
void SetLayoutAdaptationLevel (int level)
Level of adaptation, from none (Level 0) to full (Level 3).
int GetLayoutAdaptationLevel () const
Get level of adaptation.
void SetLayoutAdaptationDone (bool adaptationDone)
Returns true if the adaptation has been done.
bool GetLayoutAdaptationDone () const
Private Member Functions
void OnListboxSelection (wxCommandEvent &event)
void OnListboxDClick (wxCommandEvent &event)
void OnCheckboxSelection (wxCommandEvent &event)
void OnHostApplicationButtonClick (wxCommandEvent &event)
void UpdateSelected ()
Private Attributes
cbProject * m_pProject
int m_Selected
Additional Inherited Members
Static Public Member Functions inherited from wxDialogHelper
static wxDialogLayoutAdapter * SetLayoutAdapter (wxDialogLayoutAdapter *adapter)
Set layout adapter class, returning old adapter.
static wxDialogLayoutAdapter * GetLayoutAdapter ()
static bool GetLayoutAdaptation ()
Global switch for layout adaptation.
static void SetLayoutAdaptation (bool enable)
Protected Attributes inherited from wxDialogHelper
wxDialog * m_dialog
bool m_layoutLayoutAdaptationDone
wxArrayInt m_buttonIds
int m_layoutAdaptationLevel
Static Protected Attributes inherited from wxDialogHelper
static wxDialogLayoutAdapter * sm_layoutAdapter = NULL
static bool sm_layoutAdaptation = true
Detailed Description
Definition at line 14 of file selecttargetdlg.h.
Constructor & Destructor Documentation
SelectTargetDlg()
SelectTargetDlg::SelectTargetDlg (wxWindow * parent, cbProject * project, int selected = 0)
Definition at line 33 of file selecttargetdlg.cpp.
References CompileTargetBase::GetTitle().
~SelectTargetDlg()
SelectTargetDlg::~SelectTargetDlg ()
Definition at line 63 of file selecttargetdlg.cpp.
Member Function Documentation
EndModal()
void SelectTargetDlg::EndModal (int retCode)
Definition at line 138 of file selecttargetdlg.cpp.
References ScriptBindings::EndModal(), cbProject::GetBuildTarget(), m_pProject, m_Selected, CompileTargetBase::SetExecutionParameters(), CompileTargetBase::SetHostApplication(), and CompileTargetBase::SetRunHostApplicationInTerminal().
Referenced by OnListboxDClick().
GetSelection()
int SelectTargetDlg::GetSelection () const inline
Definition at line 21 of file selecttargetdlg.h.
References GetSelectionTarget(), m_Selected, OnCheckboxSelection(), OnHostApplicationButtonClick(), OnListboxDClick(), OnListboxSelection(), and UpdateSelected().
Referenced by cbProject::SelectTarget().
GetSelectionTarget()
ProjectBuildTarget * SelectTargetDlg::GetSelectionTarget ()
Definition at line 82 of file selecttargetdlg.cpp.
References cbProject::GetBuildTarget(), m_pProject, and m_Selected.
Referenced by GetSelection().
OnCheckboxSelection()
void SelectTargetDlg::OnCheckboxSelection (wxCommandEvent & event) private
Definition at line 100 of file selecttargetdlg.cpp.
References m_pProject, and cbProject::SetDefaultExecuteTarget().
Referenced by GetSelection().
OnHostApplicationButtonClick()
void SelectTargetDlg::OnHostApplicationButtonClick (wxCommandEvent & event) private
Definition at line 109 of file selecttargetdlg.cpp.
References cbProject::GetCommonTopLevelPath(), m_pProject, and PlaceWindow().
Referenced by GetSelection().
OnListboxDClick()
void SelectTargetDlg::OnListboxDClick (wxCommandEvent & event) private
Definition at line 94 of file selecttargetdlg.cpp.
References EndModal(), and UpdateSelected().
Referenced by GetSelection().
OnListboxSelection()
void SelectTargetDlg::OnListboxSelection (wxCommandEvent & event) private
Definition at line 89 of file selecttargetdlg.cpp.
References UpdateSelected().
Referenced by GetSelection().
UpdateSelected()
void SelectTargetDlg::UpdateSelected () private
Definition at line 68 of file selecttargetdlg.cpp.
References cbProject::GetBuildTarget(), cbProject::GetDefaultExecuteTarget(), CompileTargetBase::GetExecutionParameters(), CompileTargetBase::GetHostApplication(), CompileTargetBase::GetRunHostApplicationInTerminal(), and m_pProject.
Referenced by GetSelection(), OnListboxDClick(), and OnListboxSelection().
Member Data Documentation
m_pProject
cbProject* SelectTargetDlg::m_pProject private
Definition at line 30 of file selecttargetdlg.h.
Referenced by EndModal(), GetSelectionTarget(), OnCheckboxSelection(), OnHostApplicationButtonClick(), and UpdateSelected().
m_Selected
int SelectTargetDlg::m_Selected private
Definition at line 31 of file selecttargetdlg.h.
Referenced by EndModal(), GetSelection(), and GetSelectionTarget().
The documentation for this class was generated from the following files:
selecttargetdlg.h
selecttargetdlg.cpp