Code::Blocks: CdbCmd_DisassemblyInit Class Reference
CdbCmd_DisassemblyInit Class Reference
Command to run a disassembly.
#include <cdb_commands.h>
Public Member Functions
CdbCmd_DisassemblyInit (DebuggerDriver *driver)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Static Private Attributes
static wxString LastAddr
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to run a disassembly.
Use this instead of CdbCmd_Disassembly, which is chain-called.
Definition at line 594 of file cdb_commands.h.
Constructor & Destructor Documentation
CdbCmd_DisassemblyInit()
CdbCmd_DisassemblyInit::CdbCmd_DisassemblyInit (DebuggerDriver * driver) inline
Definition at line 598 of file cdb_commands.h.
References _T, and DebuggerCmd::m_Cmd.
Member Function Documentation
ParseOutput()
void CdbCmd_DisassemblyInit::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 604 of file cdb_commands.h.
References _T, wxString::AfterLast(), cbDebuggerStringToAddress(), cbDisassemblyDlg::Clear(), Manager::Get(), GetArrayFromString(), wxArrayString::GetCount(), Manager::GetDebuggerManager(), DebuggerManager::GetDisassemblyDialog(), wxRegEx::GetMatch(), cbStackFrame::GetSymbol(), wxString::IsEmpty(), LastAddr, DebuggerDriver::Log(), DebuggerCmd::m_pDriver, cbStackFrame::MakeValid(), wxRegEx::Matches(), DebuggerDriver::QueueCommand(), reDisassemblyFile(), reDisassemblyFunc(), cbDisassemblyDlg::SetActiveAddress(), cbStackFrame::SetAddress(), cbStackFrame::SetSymbol(), and wxString::ToLong().
Member Data Documentation
LastAddr
wxString CdbCmd_DisassemblyInit::LastAddr static private
Definition at line 596 of file cdb_commands.h.
Referenced by ParseOutput().
The documentation for this class was generated from the following file:
cdb_commands.h