Code::Blocks: CompileTargetBase Class Reference
CompileTargetBase Class Reference
Base class for build target classes Each Code::Blocks project consists of at least one target.
#include <compiletargetbase.h>
Public Member Functions
CompileTargetBase ()
virtual ~CompileTargetBase ()
virtual void SetTargetFilenameGenerationPolicy (TargetFilenameGenerationPolicy prefix, TargetFilenameGenerationPolicy extension)
A target's filename can either be auto-generated based on the running platform, or completely specified by the user.
virtual void GetTargetFilenameGenerationPolicy (TargetFilenameGenerationPolicy &prefixOut, TargetFilenameGenerationPolicy &extensionOut) const
virtual const wxString & GetFilename () const
virtual const wxString & GetTitle () const
Read the target's title.
virtual void SetTitle (const wxString &title)
Set the target's title.
virtual void SetOutputFilename (const wxString &filename)
Set the target's output filename.
virtual void SetImportLibraryFilename (const wxString &filename)
Set the target's import library filename.
virtual void SetDefinitionFileFilename (const wxString &filename)
Set the target's definition file filename.
virtual void SetWorkingDir (const wxString &dirname)
Set the target's working dir on execution (valid only for executable targets)
virtual void SetObjectOutput (const wxString &dirname)
Set the target's objects output dir.
virtual void SetDepsOutput (const wxString &dirname)
Set the target's dependencies output dir.
virtual OptionsRelation GetOptionRelation (OptionsRelationType type) const
Read the target's options relation for type.
virtual void SetOptionRelation (OptionsRelationType type, OptionsRelation rel)
Set the target's options relation for type to rel.
virtual wxString GetWorkingDir ()
Read the target's working dir for execution (valid only for executable targets)
virtual wxString GetObjectOutput () const
Read the target's objects output dir.
virtual wxString GetDepsOutput () const
Read the target's dependencies output dir.
virtual wxString GetOutputFilename ()
Read the target's output filename.
virtual wxString SuggestOutputFilename ()
Suggest a filename based on the target's type.
virtual wxString GetExecutableFilename () const
Read the target's executable filename (produced if target type is ttExecutable)
virtual wxString GetDynamicLibFilename ()
Read the target's dynamic library filename (produced if target type is ttDynamicLib)
virtual wxString GetDynamicLibImportFilename ()
Read the target's dynamic library import filename (produced if target type is ttDynamicLib)
virtual wxString GetDynamicLibDefFilename ()
Read the target's dynamic library definition file filename (produced if target type is ttDynamicLib)
virtual wxString GetStaticLibFilename ()
Read the target's static library filename (produced if target type is ttStaticLib)
virtual wxString GetNativeFilename ()
Read the target's native filename (produced if target type is ttNative)
virtual wxString GetBasePath () const
Read the target's base path, e.g. if GetFilename() returns "/usr/local/bin/xxx", base path will return "/usr/local/bin".
virtual void SetTargetType (TargetType pt)
Set the target's type to pt.
virtual TargetType GetTargetType () const
Read the target's type.
virtual const wxString & GetExecutionParameters () const
Read the target's execution parameters.
virtual void SetExecutionParameters (const wxString &params)
Set the target's execution parameters to params.
virtual const wxString & GetHostApplication () const
Read the target's host application.
virtual void SetHostApplication (const wxString &app)
Set the target's host application to app.
virtual bool GetRunHostApplicationInTerminal () const
Get the flag if the host app should be run in terminal.
virtual void SetRunHostApplicationInTerminal (bool in_terminal)
virtual void SetCompilerID (const wxString &id)
! Set the flag if the host app should be run in terminal
virtual const wxString & GetCompilerID () const
Read the target's compiler.
virtual wxString GetMakeCommandFor (MakeCommand cmd) const
Get the "make" command used for cmd.
virtual void SetMakeCommandFor (MakeCommand cmd, const wxString &make)
Set the "make" command used for cmd.
virtual bool MakeCommandsModified () const
True if any of the "make" commands is modified.
Public Member Functions inherited from CompileOptionsBase
CompileOptionsBase ()
virtual ~CompileOptionsBase ()
virtual void AddPlatform (int platform)
virtual void RemovePlatform (int platform)
virtual void SetPlatforms (int platforms)
virtual int GetPlatforms () const
virtual bool SupportsCurrentPlatform () const
virtual void SetLinkerOptions (const wxArrayString &linkerOpts)
virtual const wxArrayString & GetLinkerOptions () const
virtual void AddLinkerOption (const wxString &option)
virtual void ReplaceLinkerOption (const wxString &option, const wxString &new_option)
virtual void RemoveLinkerOption (const wxString &option)
virtual void SetLinkLibs (const wxArrayString &linkLibs)
virtual const wxArrayString & GetLinkLibs () const
virtual void AddLinkLib (const wxString &option)
virtual void ReplaceLinkLib (const wxString &option, const wxString &new_option)
virtual void RemoveLinkLib (const wxString &option)
virtual void SetCompilerOptions (const wxArrayString &compilerOpts)
virtual const wxArrayString & GetCompilerOptions () const
virtual void AddCompilerOption (const wxString &option)
virtual void ReplaceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveCompilerOption (const wxString &option)
virtual void SetResourceCompilerOptions (const wxArrayString &resourceCompilerOpts)
virtual const wxArrayString & GetResourceCompilerOptions () const
virtual void AddResourceCompilerOption (const wxString &option)
virtual void ReplaceResourceCompilerOption (const wxString &option, const wxString &new_option)
virtual void RemoveResourceCompilerOption (const wxString &option)
virtual void SetIncludeDirs (const wxArrayString &includeDirs)
virtual const wxArrayString & GetIncludeDirs () const
virtual void AddIncludeDir (const wxString &option)
virtual void ReplaceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveIncludeDir (const wxString &option)
virtual void SetResourceIncludeDirs (const wxArrayString &resIncludeDirs)
virtual const wxArrayString & GetResourceIncludeDirs () const
virtual void AddResourceIncludeDir (const wxString &option)
virtual void ReplaceResourceIncludeDir (const wxString &option, const wxString &new_option)
virtual void RemoveResourceIncludeDir (const wxString &option)
virtual void SetLibDirs (const wxArrayString &libDirs)
virtual const wxArrayString & GetLibDirs () const
virtual void AddLibDir (const wxString &option)
virtual void ReplaceLibDir (const wxString &option, const wxString &new_option)
virtual void RemoveLibDir (const wxString &option)
virtual void SetCommandsBeforeBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsBeforeBuild () const
virtual void AddCommandsBeforeBuild (const wxString &command)
virtual void RemoveCommandsBeforeBuild (const wxString &command)
virtual void SetCommandsAfterBuild (const wxArrayString &commands)
virtual const wxArrayString & GetCommandsAfterBuild () const
virtual void AddCommandsAfterBuild (const wxString &command)
virtual void RemoveCommandsAfterBuild (const wxString &command)
virtual void SetBuildScripts (const wxArrayString &scripts)
virtual const wxArrayString & GetBuildScripts () const
virtual void AddBuildScript (const wxString &script)
virtual void RemoveBuildScript (const wxString &script)
virtual bool GetModified () const
virtual void SetModified (bool modified)
virtual bool GetAlwaysRunPostBuildSteps () const
virtual void SetAlwaysRunPostBuildSteps (bool always)
virtual bool SetVar (const wxString &key, const wxString &value, bool onlyIfExists=false)
virtual bool UnsetVar (const wxString &key)
virtual void UnsetAllVars ()
virtual bool HasVar (const wxString &key) const
virtual const wxString & GetVar (const wxString &key) const
virtual const StringHash & GetAllVars () const
Protected Attributes
wxString m_Filename
wxString m_Title
wxString m_OutputFilename
wxString m_ImportLibraryFilename
wxString m_DefinitionFileFilename
wxString m_WorkingDir
wxString m_ObjectOutput
wxString m_DepsOutput
wxString m_ExecutionParameters
wxString m_HostApplication
OptionsRelation m_OptionsRelation [ortLast]
TargetType m_TargetType
wxString m_CompilerId
wxString m_MakeCommands [mcLast]
bool m_MakeCommandsModified
bool m_RunHostApplicationInTerminal
TargetFilenameGenerationPolicy m_PrefixGenerationPolicy
TargetFilenameGenerationPolicy m_ExtensionGenerationPolicy
Protected Attributes inherited from CompileOptionsBase
int m_Platform
wxArrayString m_LinkerOptions
wxArrayString m_LinkLibs
wxArrayString m_CompilerOptions
wxArrayString m_ResourceCompilerOptions
wxArrayString m_IncludeDirs
wxArrayString m_ResIncludeDirs
wxArrayString m_LibDirs
wxArrayString m_CmdsBefore
wxArrayString m_CmdsAfter
wxArrayString m_Scripts
bool m_Modified
bool m_AlwaysRunPostCmds
StringHash m_Vars
Private Member Functions
void GenerateTargetFilename (wxString &filename) const
Friends
class cbProject
Detailed Description
Base class for build target classes Each Code::Blocks project consists of at least one target.
Each target has different settings, e.g.:
Build options,
Output type,
Execution parameters, etc.
This class holds the settings of one build target.
Definition at line 77 of file compiletargetbase.h.
Constructor & Destructor Documentation
CompileTargetBase()
CompileTargetBase::CompileTargetBase ()
Definition at line 23 of file compiletargetbase.cpp.
References _T, m_MakeCommands, m_MakeCommandsModified, m_OptionsRelation, mcAskRebuildNeeded, mcBuild, mcClean, mcCompileFile, mcDistClean, mcSilentBuild, orAppendToParentOptions, and ortLast.
~CompileTargetBase()
CompileTargetBase::~CompileTargetBase () virtual
Definition at line 46 of file compiletargetbase.cpp.
Member Function Documentation
GenerateTargetFilename()
void CompileTargetBase::GenerateTargetFilename (wxString & filename) const private
Definition at line 235 of file compiletargetbase.cpp.
References _T, wxString::Clear(), LogManager::DebugLog(), FileFilters::DYNAMICLIB_DOT_EXT, FileFilters::EXECUTABLE_DOT_EXT, F(), Manager::Get(), CompilerFactory::GetCompiler(), wxFileName::GetFullName(), wxFileName::GetFullPath(), Manager::GetLogManager(), wxFileName::GetName(), wxFileName::GetPath(), Compiler::GetSwitches(), wxString::IsEmpty(), CompilerSwitches::libExtension, CompilerSwitches::libPrefix, m_CompilerId, m_ExtensionGenerationPolicy, m_PrefixGenerationPolicy, m_TargetType, FileFilters::NATIVE_DOT_EXT, wxString::StartsWith(), FileFilters::STATICLIB_EXT, tgfpNone, tgfpPlatformDefault, ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttExecutable, ttNative, ttStaticLib, wxString::wx_str(), wxEmptyString, and wxT.
Referenced by GetDynamicLibFilename(), GetExecutableFilename(), GetNativeFilename(), GetStaticLibFilename(), and SetOutputFilename().
GetBasePath()
wxString CompileTargetBase::GetBasePath () const virtual
Read the target's base path, e.g. if GetFilename() returns "/usr/local/bin/xxx", base path will return "/usr/local/bin".
Definition at line 464 of file compiletargetbase.cpp.
References _T, wxFileName::GetPath(), wxString::IsEmpty(), and m_Filename.
Referenced by NativeParser::AddCompilerDirs(), cbProject::AddFile(), CompilerGCC::AddOutputLine(), cbProject::CalculateCommonTopLevelPath(), cbProject::cbProject(), DirectCommands::DirectCommands(), ProjectManager::DoAddFileToProject(), CompilerCommandGenerator::DoBuildScripts(), DebuggerGDB::DoDebug(), NativeParser::DoFullParsing(), cbEditor::DoInitializations(), ProjectLoader::DoUnits(), ProjectLoader::ExportTargetAsProject(), FindReplaceDlg::FindReplaceDlg(), CDB_driver::GetCommonCommandLine(), cbDebuggerPlugin::GetDebuggee(), GetDepsOutput(), cbProject::GetExecutionDir(), cbProject::GetFileByFilename(), cbProject::GetMakefile(), cbProject::GetMakefileExecutionDir(), GetObjectOutput(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), DirectCommands::GetTargetLinkCommands(), CompilerCommandGenerator::Init(), ProjectOptionsDlg::IsScriptValid(), CCOptionsProjectDlg::OnAdd(), DebuggerOptionsProjectDlg::OnAdd(), CompilerOptionsDlg::OnAddDirClick(), ProjectManagerUI::OnAddFilesToProjectRecursively(), ProjectManagerUI::OnAddFileToProject(), CompilerOptionsDlg::OnAddLibClick(), ProjectOptionsDlg::OnAddScript(), ProjectOptionsDlg::OnBrowseDefinitionFileFilenameClick(), ProjectOptionsDlg::OnBrowseDirClick(), ProjectOptionsDlg::OnBrowseImportLibraryFilenameClick(), ProjectOptionsDlg::OnBrowseOutputFilenameClick(), FilePathPanel::OnbtnBrowseClick(), CompilerGCC::OnCompileFileRequest(), CCOptionsProjectDlg::OnEdit(), DebuggerOptionsProjectDlg::OnEdit(), CompilerOptionsDlg::OnEditDirClick(), CompilerOptionsDlg::OnEditLibClick(), MainFrame::OnFileNewWhat(), ClassBrowser::OnJumpTo(), DisassemblyDlg::OnSave(), ClassBrowser::OnTreeItemDoubleClick(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), MacrosManager::ReplaceMacros(), Wiz::RunProjectWizard(), EditorManager::SwapActiveHeaderSource(), cbDebuggerPlugin::SyncEditor(), and pfDetails::Update().
GetCompilerID()
virtual const wxString& CompileTargetBase::GetCompilerID () const inline virtual
Read the target's compiler.
Definition at line 145 of file compiletargetbase.h.
Referenced by cbProject::AddBuildTarget(), NativeParser::AddCompilerDirs(), NativeParser::AddCompilerPredefinedMacros(), cbProject::AddFile(), NativeParser::AddProjectDefinedMacros(), DirectCommands::AreExternalDepsOutdated(), CompilerGCC::BuildStateManagement(), cbGetDynamicLinkerPathForTarget(), EditorManager::CollectDefines(), CompilerGCC::CompileFileDefault(), CompilerOptionsDlg::CompilerOptionsDlg(), ProjectLoader::DoBuildTargetOptions(), CompilerGCC::DoCleanWithMake(), DebuggerGDB::DoDebug(), ProjectLoader::ExportTargetAsProject(), ProjectFileOptionsDlg::FillCompilers(), DebuggerManager::FindTargetsDebugger(), CompilerCommandGenerator::GenerateCommandLine(), DirectCommands::GetCompileFileCommand(), CompilerGCC::GetCurrentCompilerID(), CompilerGCC::GetMakeCommandFor(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), CompilerCommandGenerator::Init(), DirectCommands::IsObjectOutdated(), TemplateManager::NewProjectFromUserTemplate(), CompilerGCC::OnCleanFile(), ProjectOptionsDlg::OnProjectTypeChanged(), CompilerOptionsDlg::OnTreeSelectionChange(), CompilerOptionsDlg::ProjectTargetCompilerAdjust(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), CompilerGCC::Run(), Wiz::RunTargetWizard(), cbProject::SetCompilerID(), ProjectFile::SetObjName(), pfDetails::Update(), and CompilerGCC::UseMake().
GetDepsOutput()
wxString CompileTargetBase::GetDepsOutput () const virtual
Read the target's dependencies output dir.
Definition at line 219 of file compiletargetbase.cpp.
References _T, GetBasePath(), wxFileName::GetPathSeparator(), wxString::IsEmpty(), m_DepsOutput, m_TargetType, wxString::Matches(), ttCommandsOnly, and wxEmptyString.
Referenced by ProjectLoader::ExportTargetAsProject(), ScriptBindings::RegisterBindings(), and pfDetails::Update().
GetDynamicLibDefFilename()
wxString CompileTargetBase::GetDynamicLibDefFilename () virtual
Read the target's dynamic library definition file filename (produced if target type is ttDynamicLib)
Definition at line 406 of file compiletargetbase.cpp.
References _T, LogManager::DebugLog(), F(), Manager::Get(), wxFileName::GetFullPath(), Manager::GetLogManager(), wxString::IsEmpty(), m_DefinitionFileFilename, m_TargetType, ttCommandsOnly, wxString::wx_str(), and wxEmptyString.
Referenced by ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), ProjectOptionsDlg::OnProjectTypeChanged(), ScriptBindings::RegisterBindings(), and CompilerCommandGenerator::SetupOutputFilenames().
GetDynamicLibFilename()
wxString CompileTargetBase::GetDynamicLibFilename () virtual
Read the target's dynamic library filename (produced if target type is ttDynamicLib)
Definition at line 362 of file compiletargetbase.cpp.
References _T, LogManager::DebugLog(), FileFilters::DYNAMICLIB_EXT, F(), GenerateTargetFilename(), Manager::Get(), wxFileName::GetFullPath(), Manager::GetLogManager(), wxFileName::GetName(), wxString::IsEmpty(), m_ExtensionGenerationPolicy, m_Filename, m_OutputFilename, m_PrefixGenerationPolicy, m_TargetType, wxFileName::SetExt(), wxFileName::SetName(), tgfpNone, ttCommandsOnly, wxString::wx_str(), and wxEmptyString.
Referenced by ScriptBindings::RegisterBindings(), and SuggestOutputFilename().
GetDynamicLibImportFilename()
wxString CompileTargetBase::GetDynamicLibImportFilename () virtual
Read the target's dynamic library import filename (produced if target type is ttDynamicLib)
Definition at line 390 of file compiletargetbase.cpp.
References _T, LogManager::DebugLog(), F(), Manager::Get(), wxFileName::GetFullPath(), Manager::GetLogManager(), wxString::IsEmpty(), m_ImportLibraryFilename, m_TargetType, ttCommandsOnly, wxString::wx_str(), and wxEmptyString.
Referenced by ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), ProjectOptionsDlg::OnProjectTypeChanged(), and CompilerCommandGenerator::SetupOutputFilenames().
GetExecutableFilename()
wxString CompileTargetBase::GetExecutableFilename () const virtual
Read the target's executable filename (produced if target type is ttExecutable)
Definition at line 320 of file compiletargetbase.cpp.
References _T, FileFilters::EXECUTABLE_EXT, GenerateTargetFilename(), wxFileName::GetFullPath(), m_ExtensionGenerationPolicy, m_Filename, m_PrefixGenerationPolicy, m_TargetType, wxFileName::SetExt(), tgfpNone, ttCommandsOnly, and wxEmptyString.
Referenced by ScriptBindings::RegisterBindings(), and SuggestOutputFilename().
GetExecutionParameters()
const wxString & CompileTargetBase::GetExecutionParameters () const virtual
Read the target's execution parameters.
Definition at line 489 of file compiletargetbase.cpp.
References m_ExecutionParameters.
Referenced by DebuggerGDB::DoDebug(), ProjectLoader::ExportTargetAsProject(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), CompilerGCC::Run(), and SelectTargetDlg::SelectTargetDlg().
GetFilename()
const wxString & CompileTargetBase::GetFilename () const virtual
Definition at line 66 of file compiletargetbase.cpp.
References m_Filename.
Referenced by ProjectManagerUI::BuildProjectTree(), ProjectManagerUI::CheckForExternallyModifiedProjects(), cbProject::CreateUniqueFilename(), DirectCommands::DirectCommands(), MainFrame::DoOpenProject(), cbProject::ExportTargetAsProject(), ProjectManager::IsOpen(), TemplateManager::NewProjectFromUserTemplate(), MainFrame::OnFileSaveProject(), MainFrame::OnFileSaveProjectAs(), ProjectManagerUI::OnFindFile(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), ProjectManager::ReloadProject(), Wiz::RunProjectWizard(), WorkspaceLoader::Save(), TemplateManager::SaveUserTemplate(), and DirectCommands::~DirectCommands().
GetHostApplication()
const wxString & CompileTargetBase::GetHostApplication () const virtual
Read the target's host application.
Definition at line 503 of file compiletargetbase.cpp.
References m_HostApplication.
Referenced by ProjectLoader::ExportTargetAsProject(), cbDebuggerPlugin::GetDebuggee(), ScriptBindings::RegisterBindings(), CompilerGCC::Run(), and SelectTargetDlg::SelectTargetDlg().
GetMakeCommandFor()
virtual wxString CompileTargetBase::GetMakeCommandFor (MakeCommand cmd) const inline virtual
Get the "make" command used for cmd.
Definition at line 146 of file compiletargetbase.h.
Referenced by CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), CompilerGCC::GetMakeCommandFor(), and ScriptBindings::RegisterBindings().
GetNativeFilename()
wxString CompileTargetBase::GetNativeFilename () virtual
Read the target's native filename (produced if target type is ttNative)
Definition at line 341 of file compiletargetbase.cpp.
References GenerateTargetFilename(), wxFileName::GetFullPath(), wxFileName::GetName(), wxString::IsEmpty(), m_ExtensionGenerationPolicy, m_Filename, m_OutputFilename, m_PrefixGenerationPolicy, m_TargetType, FileFilters::NATIVE_EXT, wxFileName::SetExt(), wxFileName::SetName(), tgfpNone, ttCommandsOnly, and wxEmptyString.
Referenced by SuggestOutputFilename().
GetObjectOutput()
wxString CompileTargetBase::GetObjectOutput () const virtual
Read the target's objects output dir.
Definition at line 203 of file compiletargetbase.cpp.
References _T, GetBasePath(), wxFileName::GetPathSeparator(), wxString::IsEmpty(), m_ObjectOutput, m_TargetType, wxString::Matches(), ttCommandsOnly, and wxEmptyString.
Referenced by ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), CompilerGCC::OnCleanFile(), ProjectOptionsDlg::OnProjectTypeChanged(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), CompilerMINGWGenerator::SetupIncludeDirs(), and pfDetails::Update().
GetOptionRelation()
OptionsRelation CompileTargetBase::GetOptionRelation (OptionsRelationType type) const virtual
Read the target's options relation for type.
Definition at line 149 of file compiletargetbase.cpp.
References m_OptionsRelation.
Referenced by CompilerOptionsDlg::DoLoadOptions(), ProjectLoader::ExportTargetAsProject(), CompilerCommandGenerator::GetOrderedOptions(), and ScriptBindings::RegisterBindings().
GetOutputFilename()
wxString CompileTargetBase::GetOutputFilename () virtual
Read the target's output filename.
Definition at line 162 of file compiletargetbase.cpp.
References wxString::IsEmpty(), m_OutputFilename, m_TargetType, SuggestOutputFilename(), ttCommandsOnly, and wxEmptyString.
Referenced by cbProject::AddBuildTarget(), CompilerGCC::DoRunQueue(), ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), cbDebuggerPlugin::GetDebuggee(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), GetWorkingDir(), TemplateManager::NewProjectFromUserTemplate(), ProjectOptionsDlg::OnProjectTypeChanged(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), CompilerGCC::Run(), and CompilerCommandGenerator::SetupOutputFilenames().
GetRunHostApplicationInTerminal()
bool CompileTargetBase::GetRunHostApplicationInTerminal () const virtual
Get the flag if the host app should be run in terminal.
Definition at line 517 of file compiletargetbase.cpp.
References m_RunHostApplicationInTerminal.
Referenced by ProjectLoader::ExportTargetAsProject(), ProjectBuildTarget::GetUseConsoleRunner(), CompilerGCC::Run(), and SelectTargetDlg::SelectTargetDlg().
GetStaticLibFilename()
wxString CompileTargetBase::GetStaticLibFilename () virtual
Read the target's static library filename (produced if target type is ttStaticLib)
Definition at line 422 of file compiletargetbase.cpp.
References _T, LogManager::DebugLog(), F(), GenerateTargetFilename(), Manager::Get(), CompilerFactory::GetCompiler(), wxFileName::GetFullPath(), Manager::GetLogManager(), wxFileName::GetName(), Compiler::GetSwitches(), wxString::IsEmpty(), CompilerSwitches::libExtension, CompilerSwitches::libPrefix, m_CompilerId, m_ExtensionGenerationPolicy, m_Filename, m_OutputFilename, m_PrefixGenerationPolicy, m_TargetType, wxFileName::SetExt(), wxFileName::SetName(), wxString::StartsWith(), FileFilters::STATICLIB_EXT, tgfpNone, ttCommandsOnly, ttStaticLib, wxString::wx_str(), and wxEmptyString.
Referenced by DirectCommands::GetTargetCleanCommands(), ScriptBindings::RegisterBindings(), and SuggestOutputFilename().
GetTargetFilenameGenerationPolicy()
void CompileTargetBase::GetTargetFilenameGenerationPolicy (TargetFilenameGenerationPolicy & prefixOut, TargetFilenameGenerationPolicy & extensionOut) const virtual
Definition at line 59 of file compiletargetbase.cpp.
References m_ExtensionGenerationPolicy, and m_PrefixGenerationPolicy.
Referenced by ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), TemplateManager::NewProjectFromUserTemplate(), and CompilerCommandGenerator::SetupOutputFilenames().
GetTargetType()
TargetType CompileTargetBase::GetTargetType () const virtual
Read the target's type.
Definition at line 484 of file compiletargetbase.cpp.
References m_TargetType.
Referenced by CompilerOptionsDlg::CompilerOptionsDlg(), DebuggerGDB::DoDebug(), ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), CDB_driver::GetCommonCommandLine(), cbDebuggerPlugin::GetDebuggee(), DirectCommands::GetTargetCleanCommands(), DirectCommands::GetTargetLinkCommands(), ProjectBuildTarget::GetUseConsoleRunner(), CompilerCommandGenerator::Init(), TemplateManager::NewProjectFromUserTemplate(), CompilerOptionsDlg::OnTreeSelectionChange(), ScriptBindings::RegisterBindings(), CompilerGCC::Run(), ProjectBuildTarget::SetTargetType(), CompilerOWGenerator::SetupLinkerOptions(), CompilerCommandGenerator::SetupOutputFilenames(), and ProjectBuildTarget::SetUseConsoleRunner().
GetTitle()
const wxString & CompileTargetBase::GetTitle () const virtual
Read the target's title.
Definition at line 71 of file compiletargetbase.cpp.
References m_Title.
Referenced by ProjectManager::AddProjectDependency(), NativeParser::AddProjectToParser(), DirectCommands::AreExternalDepsOutdated(), ProjectManagerUI::AskForBuildTargetIndex(), ProjectManagerUI::AskForMultiBuildTargetIndex(), CodeBlocksApp::BatchJob(), CompilerGCC::Build(), ProjectManagerUI::BuildProjectTree(), ProjectOptionsDlg::BuildScriptsTree(), CompilerGCC::CalculateProjectDependencies(), VirtualBuildTargetsDlg::CheckTargets(), CompilerGCC::Clean(), ProjectManager::ClearProjectDependencies(), DirectCommands::CompileFile(), CompilerGCC::CompileFileDefault(), ProjectLoader::ConvertVersion_Pre_1_1(), NativeParser::CreateParser(), NativeParser::DeleteParser(), ProjectManager::DoAddFileToProject(), ProjectOptionsDlg::DoBeforeTargetChange(), ProjectLoader::DoBuildTargetOptions(), ProjectOptionsDlg::DoCheckScripts(), DebuggerGDB::DoDebug(), CompilerOptionsDlg::DoFillTree(), NativeParser::DoFullParsing(), CompilerOptionsDlg::DoLoadOptions(), ProjectOptionsDlg::DoTargetChange(), ProjectLoader::DoUnitOptions(), MainFrame::DoUpdateAppTitle(), ProjectFile::DoUpdateFileDetails(), CompilerGCC::DoWorkspaceBuild(), cbProject::DuplicateBuildTarget(), ProjectLoader::ExportTargetAsProject(), cbProject::ExportTargetAsProject(), FilePathPanel::FilePathPanel(), ProjectOptionsDlg::FillBuildTargets(), ProjectDepsDlg::FillList(), FindReplace::FindInFiles(), FindReplaceDlg::FindReplaceDlg(), DebuggerManager::FindTargetsDebugger(), getBuildTargetName(), MainFrame::GetEditorDescription(), cbProject::GetFirstValidBuildTargetName(), ProjectBuildTarget::GetFullTitle(), CompilerGCC::GetMakeCommandFor(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), DirectCommands::GetProjectFilesSortedByWeight(), CompilerGCC::GetTargetIndexFromName(), DirectCommands::GetTargetLinkCommands(), cbProject::IndexOfBuildTargetName(), CompilerCommandGenerator::Init(), Parser::OnAllThreadsDone(), ProjectOptionsDlg::OnBuildOrderClick(), ProjectOptionsDlg::OnCopyBuildTargetClick(), CompilerOptionsDlg::OnCopyDirsClick(), CompilerOptionsDlg::OnCopyLibsClick(), ProjectOptionsDlg::OnCreateImportFileClick(), ProjectOptionsDlg::OnEditBuildTargetClick(), ProjectOptionsDlg::OnExportTargetClick(), ProjectOptionsDlg::OnFileMarkOffClick(), ProjectOptionsDlg::OnFileMarkOnClick(), ProjectOptionsDlg::OnFileToggleMarkClick(), ProjectManagerUI::OnFindFile(), ProjectManagerUI::OnGotoFile(), NativeParser::OnParserEnd(), NativeParser::OnParserStart(), CompilerGCC::OnProjectCompilerOptions(), ProjectManagerUI::OnProperties(), ProjectManagerUI::OnRemoveFileFromProject(), DisassemblyDlg::OnSave(), FindReplaceDlg::OnSearchProject(), ProjectLoader::Open(), CompilerGCC::PreprocessJob(), CompilerGCC::PrintBanner(), ProjectDepsDlg::ProjectDepsDlg(), ProjectFileOptionsDlg::ProjectFileOptionsDlg(), ProjectManagerUI::QueryCloseProject(), CompilerGCC::Rebuild(), MacrosManager::RecalcVars(), ScriptBindings::RegisterBindings(), cbProject::RemoveBuildTarget(), ProjectManager::RemoveFileFromProject(), ProjectManager::RemoveProjectDependency(), ProjectManager::RemoveProjectFromAllDependencies(), NativeParser::RemoveProjectFromParser(), cbProject::RenameBuildTarget(), FindReplace::ReplaceInFiles(), MacrosManager::ReplaceMacros(), ProjectLayoutLoader::Save(), ProjectDepsDlg::SaveList(), TemplateManager::SaveUserTemplate(), SelectTargetDlg::SelectTargetDlg(), cbEditor::SetProjectFile(), cbProject::SetTitle(), ProjectManagerUI::ShowMenu(), NativeParser::SwitchParser(), cbAuiNotebook::UniqueIdFromTooltip(), pfDetails::Update(), and CompilerGCC::UpdateProjectTargets().
GetWorkingDir()
wxString CompileTargetBase::GetWorkingDir () virtual
Read the target's working dir for execution (valid only for executable targets)
Definition at line 190 of file compiletargetbase.cpp.
References GetOutputFilename(), wxFileName::GetPath(), wxString::IsEmpty(), m_TargetType, m_WorkingDir, ttConsoleOnly, ttDynamicLib, ttExecutable, and wxEmptyString.
Referenced by ProjectOptionsDlg::DoTargetChange(), ProjectLoader::ExportTargetAsProject(), cbDebuggerPlugin::GetDebuggee(), ProjectOptionsDlg::OnProjectTypeChanged(), ScriptBindings::RegisterBindings(), and CompilerGCC::Run().
MakeCommandsModified()
virtual bool CompileTargetBase::MakeCommandsModified () const inline virtual
True if any of the "make" commands is modified.
Definition at line 148 of file compiletargetbase.h.
Referenced by ProjectLoader::ExportTargetAsProject(), and ScriptBindings::RegisterBindings().
SetCompilerID()
void CompileTargetBase::SetCompilerID (const wxString & id) virtual
! Set the flag if the host app should be run in terminal
Set the target's compiler
Reimplemented in cbProject.
Definition at line 530 of file compiletargetbase.cpp.
References m_CompilerId, and CompileOptionsBase::SetModified().
Referenced by cbProject::AddBuildTarget(), ProjectLoader::DoBuildTargetOptions(), CompilerOptionsDlg::ProjectTargetCompilerAdjust(), ScriptBindings::RegisterBindings(), Wiz::RunProjectWizard(), Wiz::RunTargetWizard(), cbProject::SetCompilerID(), cbProject::SetModeForPCH(), and CompilerOptionsDlg::UpdateCompilerForTargets().
SetDefinitionFileFilename()
void CompileTargetBase::SetDefinitionFileFilename (const wxString & filename) virtual
Set the target's definition file filename.
Definition at line 112 of file compiletargetbase.cpp.
References _T, wxString::IsEmpty(), m_DefinitionFileFilename, CompileOptionsBase::SetModified(), and UnixFilename().
Referenced by ProjectOptionsDlg::DoBeforeTargetChange(), and ProjectLoader::DoBuildTargetOptions().
SetDepsOutput()
void CompileTargetBase::SetDepsOutput (const wxString & dirname) virtual
Set the target's dependencies output dir.
Definition at line 141 of file compiletargetbase.cpp.
References m_DepsOutput, CompileOptionsBase::SetModified(), and UnixFilename().
Referenced by cbProject::AddBuildTarget(), ProjectLoader::DoBuildTargetOptions(), and ScriptBindings::RegisterBindings().
SetExecutionParameters()
void CompileTargetBase::SetExecutionParameters (const wxString & params) virtual
Set the target's execution parameters to params.
Definition at line 494 of file compiletargetbase.cpp.
References m_ExecutionParameters, and CompileOptionsBase::SetModified().
Referenced by ProjectLoader::DoBuildTargetOptions(), SelectTargetDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetHostApplication()
void CompileTargetBase::SetHostApplication (const wxString & app) virtual
Set the target's host application to app.
Definition at line 508 of file compiletargetbase.cpp.
References m_HostApplication, and CompileOptionsBase::SetModified().
Referenced by ProjectLoader::DoBuildTargetOptions(), SelectTargetDlg::EndModal(), and ScriptBindings::RegisterBindings().
SetImportLibraryFilename()
void CompileTargetBase::SetImportLibraryFilename (const wxString & filename) virtual
Set the target's import library filename.
Definition at line 99 of file compiletargetbase.cpp.
References _T, wxString::IsEmpty(), m_ImportLibraryFilename, CompileOptionsBase::SetModified(), and UnixFilename().
Referenced by ProjectOptionsDlg::DoBeforeTargetChange(), and ProjectLoader::DoBuildTargetOptions().
SetMakeCommandFor()
void CompileTargetBase::SetMakeCommandFor (MakeCommand cmd, const wxString & make) virtual
Set the "make" command used for cmd.
Definition at line 539 of file compiletargetbase.cpp.
References m_MakeCommands, m_MakeCommandsModified, and CompileOptionsBase::SetModified().
Referenced by ProjectLoader::DoMakeCommands(), CompilerOptionsDlg::DoSaveOptions(), and ScriptBindings::RegisterBindings().
SetObjectOutput()
void CompileTargetBase::SetObjectOutput (const wxString & dirname) virtual
Set the target's objects output dir.
Definition at line 133 of file compiletargetbase.cpp.
References m_ObjectOutput, CompileOptionsBase::SetModified(), and UnixFilename().
Referenced by cbProject::AddBuildTarget(), ProjectOptionsDlg::DoBeforeTargetChange(), ProjectLoader::DoBuildTargetOptions(), ScriptBindings::RegisterBindings(), Wiz::RunProjectWizard(), and Wiz::RunTargetWizard().
SetOptionRelation()
void CompileTargetBase::SetOptionRelation (OptionsRelationType type, OptionsRelation rel) virtual
Set the target's options relation for type to rel.
Definition at line 154 of file compiletargetbase.cpp.
References m_OptionsRelation, and CompileOptionsBase::SetModified().
Referenced by ProjectLoader::DoBuildTargetOptions(), CompilerOptionsDlg::DoSaveOptions(), and ScriptBindings::RegisterBindings().
SetOutputFilename()
void CompileTargetBase::SetOutputFilename (const wxString & filename) virtual
Set the target's output filename.
Definition at line 84 of file compiletargetbase.cpp.
References GenerateTargetFilename(), wxString::IsEmpty(), m_OutputFilename, CompileOptionsBase::SetModified(), SuggestOutputFilename(), and UnixFilename().
Referenced by cbProject::AddBuildTarget(), ProjectOptionsDlg::DoBeforeTargetChange(), ProjectLoader::DoBuildTargetOptions(), TemplateManager::NewProjectFromUserTemplate(), and ScriptBindings::RegisterBindings().
SetRunHostApplicationInTerminal()
void CompileTargetBase::SetRunHostApplicationInTerminal (bool in_terminal) virtual
Definition at line 522 of file compiletargetbase.cpp.
References m_RunHostApplicationInTerminal, and CompileOptionsBase::SetModified().
Referenced by ProjectLoader::DoBuildTargetOptions(), and SelectTargetDlg::EndModal().
SetTargetFilenameGenerationPolicy()
void CompileTargetBase::SetTargetFilenameGenerationPolicy (TargetFilenameGenerationPolicy prefix, TargetFilenameGenerationPolicy extension) virtual
A target's filename can either be auto-generated based on the running platform, or completely specified by the user.
Calling this function sets the filename generation method.
The filename is divided in 4 parts. Let's see how "Debug/libSomeLib.a"
is divided:
the directory part: Debug,
the filename's prefix: lib,
the base name: SomeLib and
the extension: a
Calling this function defines if the prefix and extension are auto-generated or are left as the user specified. So, if the prefix is set to auto-generated (i.e. tgfpPlatformDefault), it would be set depending on the running platform and compiler, e.g.:
Windows & GCC: lib
Windows & MSVC: <empty>
Linux & <*>: lib
The default generation policy is tgfpPlatformDefault for both the prefix and the extension.
Note
The ProjectLoader detects old projects when loaded and, for those, it sets the default generation policy to tgfpNone (i.e. no auto-generation) for both the prefix and the extension. This is done so the user doesn't notice any unexpected behaviour...
Definition at line 51 of file compiletargetbase.cpp.
References m_ExtensionGenerationPolicy, m_PrefixGenerationPolicy, and CompileOptionsBase::SetModified().
Referenced by ProjectOptionsDlg::DoBeforeTargetChange(), ProjectLoader::DoBuildTargetOptions(), and ScriptBindings::RegisterBindings().
SetTargetType()
void CompileTargetBase::SetTargetType (TargetType pt) virtual
Set the target's type to pt.
Reimplemented in ProjectBuildTarget.
Definition at line 474 of file compiletargetbase.cpp.
References m_OutputFilename, m_TargetType, CompileOptionsBase::SetModified(), and SuggestOutputFilename().
Referenced by ProjectOptionsDlg::EndModal(), ScriptBindings::RegisterBindings(), and ProjectBuildTarget::SetTargetType().
SetTitle()
void CompileTargetBase::SetTitle (const wxString & title) virtual
Set the target's title.
Reimplemented in cbProject.
Definition at line 76 of file compiletargetbase.cpp.
References m_Title, and CompileOptionsBase::SetModified().
Referenced by cbProject::AddBuildTarget(), cbProject::DuplicateBuildTarget(), ScriptBindings::RegisterBindings(), cbProject::RenameBuildTarget(), and cbProject::SetTitle().
SetWorkingDir()
void CompileTargetBase::SetWorkingDir (const wxString & dirname) virtual
Set the target's working dir on execution (valid only for executable targets)
Definition at line 125 of file compiletargetbase.cpp.
References m_WorkingDir, CompileOptionsBase::SetModified(), and UnixFilename().
Referenced by cbProject::AddBuildTarget(), ProjectOptionsDlg::DoBeforeTargetChange(), ProjectLoader::DoBuildTargetOptions(), ScriptBindings::RegisterBindings(), and Wiz::RunTargetWizard().
SuggestOutputFilename()
wxString CompileTargetBase::SuggestOutputFilename () virtual
Suggest a filename based on the target's type.
Definition at line 171 of file compiletargetbase.cpp.
References wxString::Clear(), GetDynamicLibFilename(), GetExecutableFilename(), wxFileName::GetFullName(), GetNativeFilename(), GetStaticLibFilename(), m_TargetType, ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttExecutable, ttNative, ttStaticLib, and UnixFilename().
Referenced by GetOutputFilename(), ScriptBindings::RegisterBindings(), SetOutputFilename(), and SetTargetType().
Friends And Related Function Documentation
cbProject
friend class cbProject friend
Definition at line 150 of file compiletargetbase.h.
Member Data Documentation
m_CompilerId
wxString CompileTargetBase::m_CompilerId protected
Definition at line 164 of file compiletargetbase.h.
Referenced by GenerateTargetFilename(), GetStaticLibFilename(), and SetCompilerID().
m_DefinitionFileFilename
wxString CompileTargetBase::m_DefinitionFileFilename protected
Definition at line 156 of file compiletargetbase.h.
Referenced by GetDynamicLibDefFilename(), and SetDefinitionFileFilename().
m_DepsOutput
wxString CompileTargetBase::m_DepsOutput protected
Definition at line 159 of file compiletargetbase.h.
Referenced by GetDepsOutput(), and SetDepsOutput().
m_ExecutionParameters
wxString CompileTargetBase::m_ExecutionParameters protected
Definition at line 160 of file compiletargetbase.h.
Referenced by GetExecutionParameters(), and SetExecutionParameters().
m_ExtensionGenerationPolicy
TargetFilenameGenerationPolicy CompileTargetBase::m_ExtensionGenerationPolicy protected
Definition at line 169 of file compiletargetbase.h.
Referenced by GenerateTargetFilename(), GetDynamicLibFilename(), GetExecutableFilename(), GetNativeFilename(), GetStaticLibFilename(), GetTargetFilenameGenerationPolicy(), and SetTargetFilenameGenerationPolicy().
m_Filename
wxString CompileTargetBase::m_Filename protected
Definition at line 152 of file compiletargetbase.h.
Referenced by cbProject::AddBuildTarget(), cbProject::AddFile(), cbProject::cbProject(), GetBasePath(), GetDynamicLibFilename(), GetExecutableFilename(), GetFilename(), cbProject::GetMakefile(), GetNativeFilename(), GetStaticLibFilename(), cbProject::LoadLayout(), cbProject::Open(), cbProject::Save(), cbProject::SaveAs(), and cbProject::SaveLayout().
m_HostApplication
wxString CompileTargetBase::m_HostApplication protected
Definition at line 161 of file compiletargetbase.h.
Referenced by GetHostApplication(), and SetHostApplication().
m_ImportLibraryFilename
wxString CompileTargetBase::m_ImportLibraryFilename protected
Definition at line 155 of file compiletargetbase.h.
Referenced by GetDynamicLibImportFilename(), and SetImportLibraryFilename().
m_MakeCommands
wxString CompileTargetBase::m_MakeCommands[mcLast] protected
Definition at line 165 of file compiletargetbase.h.
Referenced by CompileTargetBase(), and SetMakeCommandFor().
m_MakeCommandsModified
bool CompileTargetBase::m_MakeCommandsModified protected
Definition at line 166 of file compiletargetbase.h.
Referenced by CompileTargetBase(), and SetMakeCommandFor().
m_ObjectOutput
wxString CompileTargetBase::m_ObjectOutput protected
Definition at line 158 of file compiletargetbase.h.
Referenced by GetObjectOutput(), and SetObjectOutput().
m_OptionsRelation
OptionsRelation CompileTargetBase::m_OptionsRelation[ortLast] protected
Definition at line 162 of file compiletargetbase.h.
Referenced by CompileTargetBase(), GetOptionRelation(), and SetOptionRelation().
m_OutputFilename
wxString CompileTargetBase::m_OutputFilename mutable protected
Definition at line 154 of file compiletargetbase.h.
Referenced by GetDynamicLibFilename(), GetNativeFilename(), GetOutputFilename(), GetStaticLibFilename(), SetOutputFilename(), and SetTargetType().
m_PrefixGenerationPolicy
TargetFilenameGenerationPolicy CompileTargetBase::m_PrefixGenerationPolicy protected
Definition at line 168 of file compiletargetbase.h.
Referenced by GenerateTargetFilename(), GetDynamicLibFilename(), GetExecutableFilename(), GetNativeFilename(), GetStaticLibFilename(), GetTargetFilenameGenerationPolicy(), and SetTargetFilenameGenerationPolicy().
m_RunHostApplicationInTerminal
bool CompileTargetBase::m_RunHostApplicationInTerminal protected
Definition at line 167 of file compiletargetbase.h.
Referenced by GetRunHostApplicationInTerminal(), and SetRunHostApplicationInTerminal().
m_TargetType
TargetType CompileTargetBase::m_TargetType protected
Definition at line 163 of file compiletargetbase.h.
Referenced by GenerateTargetFilename(), GetDepsOutput(), GetDynamicLibDefFilename(), GetDynamicLibFilename(), GetDynamicLibImportFilename(), GetExecutableFilename(), GetNativeFilename(), GetObjectOutput(), GetOutputFilename(), GetStaticLibFilename(), GetTargetType(), GetWorkingDir(), SetTargetType(), and SuggestOutputFilename().
m_Title
wxString CompileTargetBase::m_Title protected
Definition at line 153 of file compiletargetbase.h.
Referenced by cbProject::cbProject(), GetTitle(), cbProject::Open(), SetTitle(), and cbProject::ShowNotes().
m_WorkingDir
wxString CompileTargetBase::m_WorkingDir protected
Definition at line 157 of file compiletargetbase.h.
Referenced by GetWorkingDir(), and SetWorkingDir().
The documentation for this class was generated from the following files:
compiletargetbase.h
compiletargetbase.cpp