Code::Blocks: PipedProcess Class Reference
PipedProcess Class Reference
#include <pipedprocess.h>
Public Member Functions
PipedProcess (PipedProcess **pvThis, wxEvtHandler *parent, int id=wxID_ANY, bool pipe=true, const wxString &dir=wxEmptyString)
~PipedProcess ()
virtual int Launch (const wxString &cmd, unsigned int pollingInterval=100)
virtual void SendString (const wxString &text)
virtual bool HasInput ()
virtual int GetPid ()
void ForfeitStreams ()
Public Member Functions inherited from wxProcess
wxProcess (wxEvtHandler *parent=NULL, int id=-1)
wxProcess (int flags)
virtual ~wxProcess ()
void CloseOutput ()
void Detach ()
wxInputStream * GetErrorStream () const
wxInputStream * GetInputStream () const
wxOutputStream * GetOutputStream () const
long GetPid () const
bool IsErrorAvailable () const
bool IsInputAvailable () const
bool IsInputOpened () const
void Redirect ()
void SetPriority (unsigned priority)
Protected Member Functions
virtual void OnTerminate (int pid, int status)
virtual void OnTimer (wxTimerEvent &event)
virtual void OnIdle (wxIdleEvent &event)
Protected Attributes
wxEvtHandler * m_Parent
int m_Id
int m_Pid
wxTimer m_timerPollProcess
Private Attributes
PipedProcess ** m_pvThis
Additional Inherited Members
Static Public Member Functions inherited from wxProcess
static bool Exists (int pid)
static wxKillError Kill (int pid, wxSignal sig=wxSIGTERM, int flags=wxKILL_NOCHILDREN)
static wxProcess * Open (const wxString &cmd, int flags=wxEXEC_ASYNC)
Detailed Description
Definition at line 18 of file pipedprocess.h.
Constructor & Destructor Documentation
PipedProcess()
PipedProcess::PipedProcess (PipedProcess ** pvThis, wxEvtHandler * parent, int id = wxID_ANY, bool pipe = true, const wxString & dir = wxEmptyString)
Definition at line 111 of file pipedprocess.cpp.
References wxString::empty(), UnixFilename(), and wxSetWorkingDirectory().
~PipedProcess()
PipedProcess::~PipedProcess ()
Definition at line 126 of file pipedprocess.cpp.
Member Function Documentation
ForfeitStreams()
void PipedProcess::ForfeitStreams ()
Definition at line 154 of file pipedprocess.cpp.
References wxTextInputStream::GetInputStream().
GetPid()
virtual int PipedProcess::GetPid () inline virtual
Definition at line 28 of file pipedprocess.h.
References wxProcess::OnTerminate().
HasInput()
bool PipedProcess::HasInput () virtual
Definition at line 171 of file pipedprocess.cpp.
References cbEVT_PIPEDPROCESS_STDERR, cbEVT_PIPEDPROCESS_STDOUT, wxTextInputStream::GetInputStream(), cbTextInputStream::ReadLine(), and wxPostEvent().
Referenced by ToolsManager::OnIdle().
Launch()
int PipedProcess::Launch (const wxString & cmd, unsigned int pollingInterval = 100) virtual
Definition at line 131 of file pipedprocess.cpp.
References wxEXEC_ASYNC, and wxExecute().
OnIdle()
void PipedProcess::OnIdle (wxIdleEvent & event) protected virtual
Definition at line 227 of file pipedprocess.cpp.
OnTerminate()
void PipedProcess::OnTerminate (int pid, int status) protected virtual
Reimplemented from wxProcess.
Definition at line 206 of file pipedprocess.cpp.
References cbEVT_PIPEDPROCESS_TERMINATED, and wxPostEvent().
OnTimer()
void PipedProcess::OnTimer (wxTimerEvent & event) protected virtual
Definition at line 222 of file pipedprocess.cpp.
References wxWakeUpIdle().
SendString()
void PipedProcess::SendString (const wxString & text) virtual
Definition at line 142 of file pipedprocess.cpp.
References _T, and wxTextOutputStream::WriteString().
Referenced by DebuggerGDB::DoSendCommand().
Member Data Documentation
m_Id
int PipedProcess::m_Id protected
Definition at line 35 of file pipedprocess.h.
m_Parent
wxEvtHandler* PipedProcess::m_Parent protected
Definition at line 34 of file pipedprocess.h.
m_Pid
int PipedProcess::m_Pid protected
Definition at line 36 of file pipedprocess.h.
m_pvThis
PipedProcess** PipedProcess::m_pvThis private
Definition at line 39 of file pipedprocess.h.
m_timerPollProcess
wxTimer PipedProcess::m_timerPollProcess protected
Definition at line 37 of file pipedprocess.h.
The documentation for this class was generated from the following files:
pipedprocess.h
pipedprocess.cpp