Code::Blocks: DisassemblyDlg Class Reference
DisassemblyDlg Class Reference
#include <disassemblydlg.h>
Public Member Functions
DisassemblyDlg (wxWindow *parent)
wxWindow * GetWindow ()
void Clear (const cbStackFrame &frame)
void AddAssemblerLine (uint64_t addr, const wxString &line)
void AddSourceLine (int lineno, const wxString &line)
bool SetActiveAddress (uint64_t addr)
void CenterLine (int lineno)
void CenterCurrentLine ()
bool HasActiveAddr ()
void EnableWindow (bool enable)
Public Member Functions inherited from cbDisassemblyDlg
virtual ~cbDisassemblyDlg ()
Protected Member Functions
void OnSave (wxCommandEvent &event)
void OnRefresh (wxCommandEvent &event)
void OnMixedModeCB (wxCommandEvent &event)
void OnAdjustLine (wxCommandEvent &event)
Protected Attributes
wxScintilla * m_pCode
uint64_t m_LastActiveAddr
bool m_HasActiveAddr
wxString m_FrameFunction
wxString m_FrameAddress
bool m_ClearFlag
std::vector< char > m_LineTypes
Private Member Functions
DECLARE_EVENT_TABLE ()
Private Attributes
wxCheckBox * m_MixedModeCB
Detailed Description
Definition at line 18 of file disassemblydlg.h.
Constructor & Destructor Documentation
DisassemblyDlg()
DisassemblyDlg::DisassemblyDlg (wxWindow * parent)
Definition at line 48 of file disassemblydlg.cpp.
References _T, EditorColourSet::Apply(), wxXmlResource::AttachUnknownControl(), DEBUG_MARKER, DEBUG_STYLE, wxNativeFontInfo::FromString(), wxXmlResource::Get(), Manager::Get(), EditorManager::GetColourSet(), Manager::GetConfigManager(), Manager::GetEditorManager(), EditorColourSet::GetHighlightLanguage(), wxString::IsEmpty(), ConfigManager::Read(), wxFont::SetNativeFontInfo(), wxDefaultPosition, wxEmptyString, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, wxID_ANY, wxSCI_LEX_ASM, wxSCI_MARGIN_SYMBOL, wxSCI_STYLE_DEFAULT, and wxScintilla.
Member Function Documentation
AddAssemblerLine()
void DisassemblyDlg::AddAssemblerLine (uint64_t addr, const wxString & line) virtual
Implements cbDisassemblyDlg.
Definition at line 125 of file disassemblydlg.cpp.
References wxScintilla::AppendText(), cbDebuggerAddressToString(), wxScintilla::ClearAll(), m_ClearFlag, m_LastActiveAddr, m_LineTypes, m_pCode, SetActiveAddress(), wxScintilla::SetReadOnly(), and wxT.
Referenced by GetWindow().
AddSourceLine()
void DisassemblyDlg::AddSourceLine (int lineno, const wxString & line) virtual
Implements cbDisassemblyDlg.
Definition at line 140 of file disassemblydlg.cpp.
References _T, wxScintilla::AppendText(), wxString::c_str(), wxScintilla::ClearAll(), m_ClearFlag, m_LineTypes, m_pCode, wxString::Printf(), and wxScintilla::SetReadOnly().
Referenced by GetWindow().
CenterCurrentLine()
void DisassemblyDlg::CenterCurrentLine () virtual
Implements cbDisassemblyDlg.
Definition at line 169 of file disassemblydlg.cpp.
References CenterLine(), wxScintilla::GetCurrentLine(), and m_pCode.
Referenced by GetWindow().
CenterLine()
void DisassemblyDlg::CenterLine (int lineno) virtual
Implements cbDisassemblyDlg.
Definition at line 157 of file disassemblydlg.cpp.
References wxScintilla::LinesOnScreen(), m_pCode, and wxScintilla::SetFirstVisibleLine().
Referenced by CenterCurrentLine(), GetWindow(), OnAdjustLine(), and SetActiveAddress().
Clear()
void DisassemblyDlg::Clear (const cbStackFrame & frame) virtual
Implements cbDisassemblyDlg.
Definition at line 91 of file disassemblydlg.cpp.
References _(), _T, wxScintilla::ClearAll(), DEBUG_MARKER, Manager::Get(), DebuggerManager::GetActiveDebugger(), cbStackFrame::GetAddressAsString(), Manager::GetDebuggerManager(), cbStackFrame::GetSymbol(), cbDebuggerPlugin::IsRunning(), cbStackFrame::IsValid(), m_ClearFlag, m_FrameAddress, m_FrameFunction, m_HasActiveAddr, m_LineTypes, m_pCode, wxScintilla::MarkerDeleteAll(), wxScintilla::SetReadOnly(), and wxScintilla::SetText().
Referenced by GetWindow().
DECLARE_EVENT_TABLE()
DisassemblyDlg::DECLARE_EVENT_TABLE () private
EnableWindow()
void DisassemblyDlg::EnableWindow (bool enable) virtual
Implements cbDisassemblyDlg.
Definition at line 279 of file disassemblydlg.cpp.
Referenced by HasActiveAddr().
GetWindow()
wxWindow* DisassemblyDlg::GetWindow () inline virtual
Implements cbDisassemblyDlg.
Definition at line 23 of file disassemblydlg.h.
References AddAssemblerLine(), AddSourceLine(), CenterCurrentLine(), CenterLine(), Clear(), and SetActiveAddress().
HasActiveAddr()
bool DisassemblyDlg::HasActiveAddr () inline virtual
Implements cbDisassemblyDlg.
Definition at line 31 of file disassemblydlg.h.
References EnableWindow(), m_HasActiveAddr, OnAdjustLine(), OnMixedModeCB(), OnRefresh(), and OnSave().
OnAdjustLine()
void DisassemblyDlg::OnAdjustLine (wxCommandEvent & event) protected
Definition at line 214 of file disassemblydlg.cpp.
References CenterLine(), wxScintilla::GetCurrentLine(), wxScintilla::GetFirstVisibleLine(), wxScintilla::LinesOnScreen(), and m_pCode.
Referenced by HasActiveAddr().
OnMixedModeCB()
void DisassemblyDlg::OnMixedModeCB (wxCommandEvent & event) protected
Definition at line 267 of file disassemblydlg.cpp.
References cbAssert, cbDebuggerPlugin::Disassembly, Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), DebuggerManager::IsDisassemblyMixedMode(), m_MixedModeCB, cbDebuggerPlugin::RequestUpdate(), DebuggerManager::SetDisassemblyMixedMode(), and wxCheckBox::SetValue().
Referenced by HasActiveAddr().
OnRefresh()
void DisassemblyDlg::OnRefresh (wxCommandEvent & event) protected
Definition at line 260 of file disassemblydlg.cpp.
References cbAssert, cbDebuggerPlugin::Disassembly, Manager::Get(), DebuggerManager::GetActiveDebugger(), Manager::GetDebuggerManager(), and cbDebuggerPlugin::RequestUpdate().
Referenced by HasActiveAddr().
OnSave()
void DisassemblyDlg::OnSave (wxCommandEvent & event) protected
Definition at line 231 of file disassemblydlg.cpp.
References _(), _T, cbMessageBox(), cbSaveToFile(), Manager::Get(), ProjectManager::GetActiveProject(), CompileTargetBase::GetBasePath(), FileFilters::GetFilterAll(), wxFileDialog::GetPath(), Manager::GetProjectManager(), wxScintilla::GetText(), CompileTargetBase::GetTitle(), m_FrameAddress, m_FrameFunction, m_pCode, PlaceWindow(), wxFileDialog::ShowModal(), wxEmptyString, wxFD_OVERWRITE_PROMPT, wxFD_SAVE, wxICON_ERROR, and wxID_OK.
Referenced by HasActiveAddr().
SetActiveAddress()
bool DisassemblyDlg::SetActiveAddress (uint64_t addr) virtual
Implements cbDisassemblyDlg.
Definition at line 176 of file disassemblydlg.cpp.
References _T, wxString::AfterFirst(), wxString::BeforeFirst(), cbDebuggerStringToAddress(), CenterLine(), DEBUG_MARKER, Manager::Get(), Manager::GetDebuggerManager(), wxScintilla::GetFirstVisibleLine(), wxScintilla::GetLine(), wxScintilla::GetLineCount(), wxScintilla::GetLineVisible(), wxScintilla::GotoLine(), DebuggerManager::IsDisassemblyMixedMode(), wxScintilla::LinesOnScreen(), m_HasActiveAddr, m_LastActiveAddr, m_LineTypes, m_pCode, wxScintilla::MarkerAdd(), and wxScintilla::MarkerDeleteAll().
Referenced by AddAssemblerLine(), and GetWindow().
Member Data Documentation
m_ClearFlag
bool DisassemblyDlg::m_ClearFlag protected
Definition at line 45 of file disassemblydlg.h.
Referenced by AddAssemblerLine(), AddSourceLine(), and Clear().
m_FrameAddress
wxString DisassemblyDlg::m_FrameAddress protected
Definition at line 44 of file disassemblydlg.h.
Referenced by Clear(), and OnSave().
m_FrameFunction
wxString DisassemblyDlg::m_FrameFunction protected
Definition at line 43 of file disassemblydlg.h.
Referenced by Clear(), and OnSave().
m_HasActiveAddr
bool DisassemblyDlg::m_HasActiveAddr protected
Definition at line 42 of file disassemblydlg.h.
Referenced by Clear(), HasActiveAddr(), and SetActiveAddress().
m_LastActiveAddr
uint64_t DisassemblyDlg::m_LastActiveAddr protected
Definition at line 41 of file disassemblydlg.h.
Referenced by AddAssemblerLine(), and SetActiveAddress().
m_LineTypes
std::vector<char> DisassemblyDlg::m_LineTypes protected
Definition at line 46 of file disassemblydlg.h.
Referenced by AddAssemblerLine(), AddSourceLine(), Clear(), and SetActiveAddress().
m_MixedModeCB
wxCheckBox* DisassemblyDlg::m_MixedModeCB private
Definition at line 49 of file disassemblydlg.h.
Referenced by OnMixedModeCB().
m_pCode
wxScintilla* DisassemblyDlg::m_pCode protected
Definition at line 40 of file disassemblydlg.h.
Referenced by AddAssemblerLine(), AddSourceLine(), CenterCurrentLine(), CenterLine(), Clear(), OnAdjustLine(), OnSave(), and SetActiveAddress().
The documentation for this class was generated from the following files:
disassemblydlg.h
disassemblydlg.cpp