Code::Blocks: GdbCmd_AddBreakpoint Class Reference
GdbCmd_AddBreakpoint Class Reference
Command to add a breakpoint.
#include <gdb_commands.h>
Public Member Functions
GdbCmd_AddBreakpoint (DebuggerDriver *driver, cb::shared_ptr< DebuggerBreakpoint > bp)
void ParseOutput (const wxString &output)
Parses the command's output.
Public Member Functions inherited from DebuggerCmd
DebuggerCmd (DebuggerDriver *driver, const wxString &cmd=_T(""), bool logToNormalLog=false)
virtual ~DebuggerCmd ()
virtual void Action ()
Executes an action.
virtual bool IsContinueCommand () const
Tells if the command is a continue type command (continue, step, next and run to cursor commands should be marked as such)
Private Attributes
cb::shared_ptr< DebuggerBreakpoint > m_BP
Additional Inherited Members
Public Attributes inherited from DebuggerCmd
wxString m_Cmd
the actual command
Protected Attributes inherited from DebuggerCmd
DebuggerDriver * m_pDriver
the driver
bool m_LogToNormalLog
if true, log to normal log, else the debug log
Detailed Description
Command to add a breakpoint.
Definition at line 432 of file gdb_commands.h.
Constructor & Destructor Documentation
GdbCmd_AddBreakpoint()
GdbCmd_AddBreakpoint::GdbCmd_AddBreakpoint (DebuggerDriver * driver, cb::shared_ptr< DebuggerBreakpoint > bp) inline
Parameters
bp The breakpoint to set.
Definition at line 437 of file gdb_commands.h.
References _T, DebuggerBreakpoint::bptCode, DebuggerBreakpoint::bptData, wxString::Format(), and DebuggerCmd::m_Cmd.
Member Function Documentation
ParseOutput()
void GdbCmd_AddBreakpoint::ParseOutput (const wxString & output) inline virtual
Parses the command's output.
Parameters
The output. This is the full output up to (and including) the prompt.
Reimplemented from DebuggerCmd.
Definition at line 481 of file gdb_commands.h.
References _(), _T, DebuggerCmd::DebuggerCmd(), wxString::Format(), Manager::Get(), DebuggerManager::GetBreakpointDialog(), Manager::GetDebuggerManager(), wxRegEx::GetMatch(), DebuggerDriver::High, DebuggerDriver::Log(), DebuggerCmd::m_pDriver, wxRegEx::Matches(), DebuggerDriver::QueueCommand(), reBreakpoint(), reDataBreakpoint(), reHWBreakpoint(), cbBreakpointsDlg::Reload(), rePendingBreakpoint(), and reTemporaryBreakpoint().
Member Data Documentation
m_BP
cb::shared_ptr<DebuggerBreakpoint> GdbCmd_AddBreakpoint::m_BP private
Definition at line 434 of file gdb_commands.h.
The documentation for this class was generated from the following file:
gdb_commands.h