Code::Blocks: compilergcc.cpp File Reference
compilergcc.cpp File Reference
#include <sdk.h>
#include <wx/frame.h>
#include <wx/gauge.h>
#include <wx/listctrl.h>
#include <wx/xrc/xmlres.h>
#include <wx/sizer.h>
#include <wx/button.h>
#include <wx/stattext.h>
#include <wx/statline.h>
#include <wx/ffile.h>
#include <wx/utils.h>
#include <wx/uri.h>
#include <wx/xml/xml.h>
#include <prep.h>
#include <manager.h>
#include <sdk_events.h>
#include <pipedprocess.h>
#include <configmanager.h>
#include <compilercommandgenerator.h>
#include <debuggermanager.h>
#include <incremental_select_helper.h>
#include <logmanager.h>
#include <macrosmanager.h>
#include <projectmanager.h>
#include <editormanager.h>
#include <scriptingmanager.h>
#include <configurationpanel.h>
#include <pluginmanager.h>
#include <cbeditor.h>
#include <annoyingdialog.h>
#include <filefilters.h>
#include <infowindow.h>
#include "compilergcc.h"
#include "compileroptionsdlg.h"
#include "directcommands.h"
#include "globals.h"
#include "cbworkspace.h"
#include "cbstyledtextctrl.h"
#include "compilerMINGW.h"
#include "compilerGNUARM.h"
#include "compilerMSVC.h"
#include "compilerMSVC8.h"
#include "compilerMSVC10.h"
#include "compilerOW.h"
#include "compilerCYGWIN.h"
#include "compilerLCC.h"
#include "compilerKeilC51.h"
#include "compilerIAR.h"
#include "compilerICC.h"
#include "compilerGDC.h"
#include "compilerGNUFortran.h"
#include "compilerG95.h"
#include "compilerXML.h"
#include <scripting/bindings/sc_base_types.h>
Classes
class BuildLogger
Namespaces
ScriptBindings
Functions
void ScriptBindings::gBuildLog (const wxString &msg)
static wxString getBuildTargetName (const ProjectBuildTarget *bt)
wxString StateToString (BuildState bs)
Variables
static int ScriptBindings::gBuildLogId = -1
const int idBuildLog = wxNewId()
int idTimerPollCompiler = XRCID("idTimerPollCompiler")
int idMenuCompile = XRCID("idCompilerMenuCompile")
int idMenuCompileTarget = wxNewId()
int idMenuCompileFromProjectManager = wxNewId()
int idMenuProjectCompilerOptions = wxNewId()
int idMenuProjectCompilerOptionsFromProjectManager = wxNewId()
int idMenuProjectProperties = wxNewId()
int idMenuTargetCompilerOptions = wxNewId()
int idMenuTargetCompilerOptionsSub = wxNewId()
int idMenuCompileFile = XRCID("idCompilerMenuCompileFile")
int idMenuCompileFileFromProjectManager = wxNewId()
int idMenuCleanFileFromProjectManager = wxNewId()
int idMenuRebuild = XRCID("idCompilerMenuRebuild")
int idMenuRebuildTarget = wxNewId()
int idMenuRebuildFromProjectManager = wxNewId()
int idMenuClean = XRCID("idCompilerMenuClean")
int idMenuBuildWorkspace = XRCID("idCompilerMenuBuildWorkspace")
int idMenuRebuildWorkspace = XRCID("idCompilerMenuRebuildWorkspace")
int idMenuCleanWorkspace = XRCID("idCompilerMenuCleanWorkspace")
int idMenuCleanTarget = wxNewId()
int idMenuCleanFromProjectManager = wxNewId()
int idMenuCompileAndRun = XRCID("idCompilerMenuCompileAndRun")
int idMenuRun = XRCID("idCompilerMenuRun")
int idMenuKillProcess = XRCID("idCompilerMenuKillProcess")
int idMenuSelectTarget = XRCID("idCompilerMenuSelectTarget")
const int maxTargetInMenus = 40
int idMenuSelectTargetOther [maxTargetInMenus]
int idMenuSelectTargetDialog = wxNewId()
int idMenuSelectTargetHasMore = wxNewId()
int idMenuNextError = XRCID("idCompilerMenuNextError")
int idMenuPreviousError = XRCID("idCompilerMenuPreviousError")
int idMenuClearErrors = XRCID("idCompilerMenuClearErrors")
int idMenuSettings = XRCID("idCompilerMenuSettings")
int idToolTarget = XRCID("idToolTarget")
int idGCCProcess1 = wxNewId()
int idGCCProcess2 = wxNewId()
int idGCCProcess3 = wxNewId()
int idGCCProcess4 = wxNewId()
int idGCCProcess5 = wxNewId()
int idGCCProcess6 = wxNewId()
int idGCCProcess7 = wxNewId()
int idGCCProcess8 = wxNewId()
int idGCCProcess9 = wxNewId()
int idGCCProcess10 = wxNewId()
int idGCCProcess11 = wxNewId()
int idGCCProcess12 = wxNewId()
int idGCCProcess13 = wxNewId()
int idGCCProcess14 = wxNewId()
int idGCCProcess15 = wxNewId()
int idGCCProcess16 = wxNewId()
Function Documentation
getBuildTargetName()
static wxString getBuildTargetName (const ProjectBuildTarget * bt) inline static
Definition at line 2053 of file compilergcc.cpp.
References _(), and CompileTargetBase::GetTitle().
Referenced by CompilerGCC::BuildStateManagement(), and CompilerGCC::DoCleanWithMake().
StateToString()
wxString StateToString (BuildState bs) inline
Definition at line 2177 of file compilergcc.cpp.
References _T, bsNone, bsProjectDone, bsProjectPostBuild, bsProjectPreBuild, bsTargetBuild, bsTargetClean, bsTargetDone, bsTargetPostBuild, and bsTargetPreBuild.
Variable Documentation
idBuildLog
const int idBuildLog = wxNewId()
Definition at line 88 of file compilergcc.cpp.
Referenced by BuildLogger::CreateControl(), and CompilerGCC::TextURL().
idGCCProcess1
int idGCCProcess1 = wxNewId()
Definition at line 212 of file compilergcc.cpp.
Referenced by CompilerGCC::DoRunQueue(), and CompilerGCC::OnGCCTerminated().
idGCCProcess10
int idGCCProcess10 = wxNewId()
Definition at line 221 of file compilergcc.cpp.
idGCCProcess11
int idGCCProcess11 = wxNewId()
Definition at line 222 of file compilergcc.cpp.
idGCCProcess12
int idGCCProcess12 = wxNewId()
Definition at line 223 of file compilergcc.cpp.
idGCCProcess13
int idGCCProcess13 = wxNewId()
Definition at line 224 of file compilergcc.cpp.
idGCCProcess14
int idGCCProcess14 = wxNewId()
Definition at line 225 of file compilergcc.cpp.
idGCCProcess15
int idGCCProcess15 = wxNewId()
Definition at line 226 of file compilergcc.cpp.
idGCCProcess16
int idGCCProcess16 = wxNewId()
Definition at line 227 of file compilergcc.cpp.
idGCCProcess2
int idGCCProcess2 = wxNewId()
Definition at line 213 of file compilergcc.cpp.
idGCCProcess3
int idGCCProcess3 = wxNewId()
Definition at line 214 of file compilergcc.cpp.
idGCCProcess4
int idGCCProcess4 = wxNewId()
Definition at line 215 of file compilergcc.cpp.
idGCCProcess5
int idGCCProcess5 = wxNewId()
Definition at line 216 of file compilergcc.cpp.
idGCCProcess6
int idGCCProcess6 = wxNewId()
Definition at line 217 of file compilergcc.cpp.
idGCCProcess7
int idGCCProcess7 = wxNewId()
Definition at line 218 of file compilergcc.cpp.
idGCCProcess8
int idGCCProcess8 = wxNewId()
Definition at line 219 of file compilergcc.cpp.
idGCCProcess9
int idGCCProcess9 = wxNewId()
Definition at line 220 of file compilergcc.cpp.
idMenuBuildWorkspace
int idMenuBuildWorkspace = XRCID("idCompilerMenuBuildWorkspace")
Definition at line 188 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuClean
int idMenuClean = XRCID("idCompilerMenuClean")
Definition at line 187 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuCleanFileFromProjectManager
int idMenuCleanFileFromProjectManager = wxNewId()
Definition at line 183 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnCleanFile().
idMenuCleanFromProjectManager
int idMenuCleanFromProjectManager = wxNewId()
Definition at line 192 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnClean().
idMenuCleanTarget
int idMenuCleanTarget = wxNewId()
Definition at line 191 of file compilergcc.cpp.
idMenuCleanWorkspace
int idMenuCleanWorkspace = XRCID("idCompilerMenuCleanWorkspace")
Definition at line 190 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuClearErrors
int idMenuClearErrors = XRCID("idCompilerMenuClearErrors")
Definition at line 207 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuCompile
int idMenuCompile = XRCID("idCompilerMenuCompile")
Definition at line 173 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuCompileAndRun
int idMenuCompileAndRun = XRCID("idCompilerMenuCompileAndRun")
Definition at line 193 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuCompileFile
int idMenuCompileFile = XRCID("idCompilerMenuCompileFile")
Definition at line 181 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuCompileFileFromProjectManager
int idMenuCompileFileFromProjectManager = wxNewId()
Definition at line 182 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnCompileFile().
idMenuCompileFromProjectManager
int idMenuCompileFromProjectManager = wxNewId()
Definition at line 175 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnCompile().
idMenuCompileTarget
int idMenuCompileTarget = wxNewId()
Definition at line 174 of file compilergcc.cpp.
idMenuKillProcess
int idMenuKillProcess = XRCID("idCompilerMenuKillProcess")
Definition at line 195 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuNextError
int idMenuNextError = XRCID("idCompilerMenuNextError")
Definition at line 205 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuPreviousError
int idMenuPreviousError = XRCID("idCompilerMenuPreviousError")
Definition at line 206 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuProjectCompilerOptions
int idMenuProjectCompilerOptions = wxNewId()
Definition at line 176 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuProjectCompilerOptionsFromProjectManager
int idMenuProjectCompilerOptionsFromProjectManager = wxNewId()
Definition at line 177 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), and CompilerGCC::Dispatcher().
idMenuProjectProperties
int idMenuProjectProperties = wxNewId()
Definition at line 178 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildMenu(), ProjectManagerUI::CreateMenu(), ProjectManagerUI::OnProperties(), and CompilerGCC::OnUpdateUI().
idMenuRebuild
int idMenuRebuild = XRCID("idCompilerMenuRebuild")
Definition at line 184 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuRebuildFromProjectManager
int idMenuRebuildFromProjectManager = wxNewId()
Definition at line 186 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnRebuild().
idMenuRebuildTarget
int idMenuRebuildTarget = wxNewId()
Definition at line 185 of file compilergcc.cpp.
idMenuRebuildWorkspace
int idMenuRebuildWorkspace = XRCID("idCompilerMenuRebuildWorkspace")
Definition at line 189 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildModuleMenu(), CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuRun
int idMenuRun = XRCID("idCompilerMenuRun")
Definition at line 194 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher(), and CompilerGCC::OnUpdateUI().
idMenuSelectTarget
int idMenuSelectTarget = XRCID("idCompilerMenuSelectTarget")
Definition at line 196 of file compilergcc.cpp.
Referenced by CompilerGCC::BuildMenu(), and CompilerGCC::OnUpdateUI().
idMenuSelectTargetDialog
int idMenuSelectTargetDialog = wxNewId()
Definition at line 202 of file compilergcc.cpp.
Referenced by CompilerGCC::DoRecreateTargetMenu(), and CompilerGCC::OnSelectTarget().
idMenuSelectTargetHasMore
int idMenuSelectTargetHasMore = wxNewId()
Definition at line 203 of file compilergcc.cpp.
Referenced by CompilerGCC::DoRecreateTargetMenu().
idMenuSelectTargetOther
int idMenuSelectTargetOther[maxTargetInMenus]
Definition at line 201 of file compilergcc.cpp.
Referenced by CompilerGCC::DoRecreateTargetMenu(), CompilerGCC::DoUpdateTargetMenu(), CompilerGCC::OnAttach(), and CompilerGCC::OnSelectTarget().
idMenuSettings
int idMenuSettings = XRCID("idCompilerMenuSettings")
Definition at line 208 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher().
idMenuTargetCompilerOptions
int idMenuTargetCompilerOptions = wxNewId()
Definition at line 179 of file compilergcc.cpp.
Referenced by CompilerGCC::Dispatcher().
idMenuTargetCompilerOptionsSub
int idMenuTargetCompilerOptionsSub = wxNewId()
Definition at line 180 of file compilergcc.cpp.
idTimerPollCompiler
int idTimerPollCompiler = XRCID("idTimerPollCompiler")
Definition at line 172 of file compilergcc.cpp.
Referenced by CompilerGCC::OnAttach().
idToolTarget
int idToolTarget = XRCID("idToolTarget")
Definition at line 210 of file compilergcc.cpp.
Referenced by CompilerGCC::OnSelectTarget().
maxTargetInMenus
const int maxTargetInMenus = 40
Definition at line 200 of file compilergcc.cpp.
Referenced by CompilerGCC::DoRecreateTargetMenu(), CompilerGCC::DoUpdateTargetMenu(), and CompilerGCC::OnAttach().