Code::Blocks: compileroptionsdlg.cpp File Reference
compileroptionsdlg.cpp File Reference
#include <sdk.h>
#include <prep.h>
#include <wx/filedlg.h>
#include <wx/propgrid/propgrid.h>
#include <wx/xml/xml.h>
#include "advancedcompileroptionsdlg.h"
#include "annoyingdialog.h"
#include "cbexception.h"
#include "compilergcc.h"
#include "compileroptionsdlg.h"
#include "debuggermanager.h"
#include "editpathdlg.h"
#include "editpairdlg.h"
#include "compilerflagdlg.h"
Classes
class ScopeTreeData
struct DebuggerClientData
struct VariableListClientData
Functions
void ArrayString2ListBox (const wxArrayString &array, wxListBox *control)
void ListBox2ArrayString (wxArrayString &array, const wxListBox *control)
void ArrayString2TextCtrl (const wxArrayString &array, wxTextCtrl *control)
void DoGetCompileOptions (wxArrayString &array, const wxTextCtrl *control)
static void QuoteString (wxString &value, const wxString &caption)
static void UpdateUIListBoxAndButtons (wxListBox &list, wxButton &edit, wxButton &del, wxButton &clear, wxButton &copy, wxButton &up, wxButton &down)
Function Documentation
ArrayString2ListBox()
void ArrayString2ListBox (const wxArrayString & array, wxListBox * control) inline
Definition at line 444 of file compileroptionsdlg.cpp.
References wxArrayString::GetCount().
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), CompilerOptionsDlg::DoFillCompilerPrograms(), CompilerOptionsDlg::DoFillOthers(), and CompilerOptionsDlg::DoLoadOptions().
ArrayString2TextCtrl()
void ArrayString2TextCtrl (const wxArrayString & array, wxTextCtrl * control) inline
Definition at line 752 of file compileroptionsdlg.cpp.
References _T, and wxArrayString::GetCount().
Referenced by CompilerOptionsDlg::DoLoadOptions().
DoGetCompileOptions()
void DoGetCompileOptions (wxArrayString & array, const wxTextCtrl * control) inline
Definition at line 766 of file compileroptionsdlg.cpp.
References _T, wxArrayString::Add(), wxArrayString::Clear(), wxString::Find(), wxString::IsEmpty(), wxString::Left(), wxString::Remove(), wxString::Replace(), and wxString::Strip().
Referenced by CompilerOptionsDlg::DoSaveOptions(), and CompilerOptionsDlg::OptionsToText().
ListBox2ArrayString()
void ListBox2ArrayString (wxArrayString & array, const wxListBox * control) inline
Definition at line 455 of file compileroptionsdlg.cpp.
References wxArrayString::Add(), wxArrayString::Clear(), and wxString::IsEmpty().
Referenced by CompilerOptionsDlg::DoSaveCompilerPrograms(), CompilerOptionsDlg::DoSaveOptions(), CompilerOptionsDlg::OnAddExtraPathClick(), CompilerOptionsDlg::OnApply(), and CompilerOptionsDlg::OnEditExtraPathClick().
QuoteString()
static void QuoteString (wxString & value, const wxString & caption) static
Definition at line 1976 of file compileroptionsdlg.cpp.
References _(), NeedQuotes(), QuoteStringIfNeeded(), AnnoyingDialog::rtSAVE_CHOICE, AnnoyingDialog::rtYES, AnnoyingDialog::ShowModal(), wxART_QUESTION, wxT, and AnnoyingDialog::YES_NO.
Referenced by CompilerOptionsDlg::OnAddVarClick(), and CompilerOptionsDlg::OnEditVarClick().
UpdateUIListBoxAndButtons()
static void UpdateUIListBoxAndButtons (wxListBox & list, wxButton & edit, wxButton & del, wxButton & clear, wxButton & copy, wxButton & up, wxButton & down) static
Definition at line 2680 of file compileroptionsdlg.cpp.
Referenced by CompilerOptionsDlg::OnUpdateUI().