Code::Blocks: compilercommandgenerator.cpp File Reference
compilercommandgenerator.cpp File Reference
#include "sdk_precomp.h"
#include "compilercommandgenerator.h"
#include <wx/intl.h>
#include <wx/filename.h>
#include "cbexception.h"
#include "cbproject.h"
#include "compilerfactory.h"
#include "compiler.h"
#include "manager.h"
#include "configmanager.h"
#include "logmanager.h"
#include "macrosmanager.h"
#include "scriptingmanager.h"
#include "filefilters.h"
#include "scripting/bindings/sc_base_types.h"
#include "scripting/sqplus/sqplus.h"
Functions
wxString UnquoteStringIfNeeded (const wxString &str)
Function Documentation
UnquoteStringIfNeeded()
wxString UnquoteStringIfNeeded (const wxString & str) inline
Definition at line 31 of file compilercommandgenerator.cpp.
References _T, wxString::GetChar(), wxString::IsEmpty(), wxString::Last(), wxString::Length(), and wxString::Mid().
Referenced by CompilerCommandGenerator::GenerateCommandLine(), CompilerCommandGenerator::GetOrderedIncludeDirs(), CompilerCommandGenerator::GetOrderedLibrariesDirs(), CompilerCommandGenerator::GetOrderedResourceIncludeDirs(), CompilerCommandGenerator::GetProcessedIncludeDir(), and CompilerCommandGenerator::SetupOutputFilenames().