Code::Blocks: configmanager.cpp File Reference
configmanager.cpp File Reference
#include "sdk_precomp.h"
#include "crc32.h"
#include <wx/url.h>
#include <wx/stream.h>
#include <wx/stdpaths.h>
#include <wx/filename.h>
#include <shlobj.h>
#include "tinywxuni.h"
#include <stdlib.h>
Namespaces
CfgMgrConsts
Functions
void to_upper (wxString &s)
void to_lower (wxString &s)
static wxString getCompilerPluginFilename ()
wxArrayString cbReadBatchBuildPlugins ()
Read the list of batch build plugins and return them.
void cbWriteBatchBuildPlugins (wxArrayString bbplugins, wxWindow *messageBoxParent)
Write the list of batch build plugins in the config.
Variables
const wxString CfgMgrConsts::app_path (_T("app_path"))
const wxString CfgMgrConsts::data_path (_T("data_path"))
const wxString CfgMgrConsts::dotDot (_T(".."))
const int CfgMgrConsts::version = 1
Function Documentation
cbReadBatchBuildPlugins()
wxArrayString cbReadBatchBuildPlugins ()
Read the list of batch build plugins and return them.
The list won't be empty; at least the compiler plugin will be added to the to it. The list contain the library names of the plugins and differs on every OS.
Definition at line 1716 of file configmanager.cpp.
References _T, wxArrayString::Add(), Manager::Get(), getCompilerPluginFilename(), Manager::GetConfigManager(), wxArrayString::GetCount(), and ConfigManager::ReadArrayString().
Referenced by CompilerSettingsDlg::CompilerSettingsDlg(), and PluginManager::ScanForPlugins().
cbWriteBatchBuildPlugins()
void cbWriteBatchBuildPlugins (wxArrayString bbplugins, wxWindow * messageBoxParent)
Write the list of batch build plugins in the config.
Parameters
bbpluigns List of library plugin names.
messageBoxParent Set as a parent to the message box that will be shown in case of errors.
Definition at line 1727 of file configmanager.cpp.
References _(), _T, wxArrayString::Add(), cbMessageBox(), Manager::Get(), getCompilerPluginFilename(), Manager::GetConfigManager(), wxArrayString::Index(), ConfigManager::Write(), wxICON_WARNING, and wxNOT_FOUND.
Referenced by CompilerSettingsDlg::EndModal().
getCompilerPluginFilename()
static wxString getCompilerPluginFilename () static
Definition at line 1706 of file configmanager.cpp.
References wxT.
Referenced by cbReadBatchBuildPlugins(), and cbWriteBatchBuildPlugins().
to_lower()
void to_lower (wxString & s) inline
Definition at line 455 of file configmanager.cpp.
References wxString::c_str(), wxString::length(), and wxString::wx_str().
Referenced by ConfigManager::AssertPath(), and ConfigManager::DeleteSubPath().
to_upper()
void to_upper (wxString & s) inline
Definition at line 437 of file configmanager.cpp.
References wxString::c_str(), wxString::length(), and wxString::wx_str().
Referenced by ConfigManager::AssertPath().