Code::Blocks: config-testsuite.cpp File Reference
config-testsuite.cpp File Reference
Functions
m DebugLog ("APP_PATH="+c->Read("app_path"))
c SetPath ("/foo")
c SetPath ("/bar/some/path")
c SetPath ("/bar/another")
c SetPath ("/bar/yetanother")
c SetPath ("/trailing/slash/")
c SetPath ("../upalevel")
c Write ("myname","Thomas")
c Write ("/top","bottom")
c Write ("/foo/blah", 5)
c Write ("/foo/honk", 2)
c Write ("/foo/honk", 44.8)
m DebugLog (wxString("key_exists /foo/zork=")<< c->Exists("/foo/zork"))
m DebugLog (wxString("key_exists /foo/honk=")<< c->Exists("/foo/honk"))
c Set ("prz")
c UnSet ("prz")
m DebugLog (wxString("exists blah=")<< c->Exists("/foo/blah"))
m DebugLog (wxString("exists honk=")<< c->Exists("/foo/honk"))
m DebugLog (wxString("exists invalid=")<< c->Exists("/invalid"))
m DebugLog (wxString("read /foo/blah=")<< c->ReadInt("/foo/blah",-1))
m DebugLog (wxString("read /foo/honk=")<< c->ReadInt("/foo/honk",-1))
m DebugLog (wxString("read /foo/honk=")<< c->ReadDouble("/foo/honk",-5.5))
m DebugLog (wxString("read /invalid=")<< c->ReadInt("/invalid", 4242))
as Add ("some")
as Add ("items")
as Add ("in a wxArrayString")
as Add ("saved")
as Add ("here in config")
c Write ("/trailing/slash/data", as)
for (unsigned int i=0;i< as.GetCount();++i) m-> DebugLog(wxString("arraystring element: ")<< as[i])
c WriteBinary ("/trailing/slash/window-layout", wxString("Binary data. This can be anything which fits in a wxString or a pointer plus a size_t argument."))
m DebugLog (c->ReadBinary("/trailing/slash/window-layout"))
enumerated Clear ()
MySerializableLongIntClass serialLong (5)
MySerializableLongIntClass otherSerialLong (0)
serialLong Print ()
c Write ("nonsense", serialLong)
c Read ("nonsense",&otherSerialLong)
c Write ("/foo/thismapsletters", map)
m DebugLog (pam["a"])
m DebugLog (pam["b"])
m DebugLog (pam["c"])
c Write ("boo",(OldConfigManagerContainer::SerializableObjectMap *)&objMap1)
c Read< MySerializableLongIntClass > ("boo",(OldConfigManagerContainer::SerializableObjectMap *)&objMap2)
c Write ("/foo/one_or_zero", true)
m DebugLog (wxString("read /foo/one_or_zero=")<< c->ReadBool("/foo/one_or_zero"))
c Write ("/foo/one_or_zero", false)
cv Write ("word","table")
m DebugLog (wxString("main word:")<< c->Read("word"))
m DebugLog (wxString("volatile word:")<< cv->Read("word"))
m DebugLog (wxString("volatile top:")<< cv->Read("/top"))
sset insert ("zac")
sset insert ("boing")
sset insert ("boom")
sset insert ("Was würde der Fürst von Thurn & Taxis zu Umlauten sagen?")
c Write ("unique_strings", sset)
sset clear ()
for (OldConfigManagerContainer::StringSet::iterator it=sset.begin();it!=sset.end();++it) m-> DebugLog(*it)
c Write ("ints2strings", imap)
for (OldConfigManagerContainer::IntToStringMap::iterator it=imap.begin();it!=imap.end();++it)
wxColour red (255, 0, 0)
c Write ("red", red)
c Read ("not_red",&col)
cstr sprintf ("not red : %d %d %d",(int) col.Red(),(int) col.Green(),(int) col.Blue())
m DebugLog (cstr)
c Read ("red",&col)
cstr sprintf (" red : %d %d %d",(int) col.Red(),(int) col.Green(),(int) col.Blue())
Variables
ConfigManager * c = Manager::Get()->GetConfigManager("main")
MessageManager * m = Manager::Get()->GetMessageManager()
wxArrayString as = c->ReadArrayString("/trailing/slash/data")
wxArrayString enumerated = c->EnumerateSubPaths("/")
OldConfigManagerContainer::StringToStringMap map = "the letter A"
OldConfigManagerContainer::StringToStringMap pam = c->ReadSSMap("/foo/thismapsletters")
MyThingieMap objMap1 = new MySerializableLongIntClass(1234)
MyThingieMap objMap2
ConfigManager * cv = Manager::Get()->GetConfigManager("volatile:main")
OldConfigManagerContainer::StringSet sset = c->ReadSSet("unique_strings")
OldConfigManagerContainer::IntToStringMap imap = "poof"
wxString cstr
wxColour col
Function Documentation
as Add ("some")
as Add ("items")
as Add ("in a wxArrayString")
as Add ("saved")
as Add ("here in config")
enumerated Clear ()
Referenced by ScriptBindings::Register_wxTypes().
imap clear ()
Referenced by MultiSelectDlg::OnWildcard(), and Compiler::Reset().
m DebugLog ()
m DebugLog (wxString("key_exists /foo/zork=")<< c->Exists("/foo/zork"))
m DebugLog (wxString("key_exists /foo/honk=")<< c->Exists("/foo/honk"))
m DebugLog (wxString("exists blah=")<< c->Exists("/foo/blah"))
m DebugLog (wxString("exists honk=")<< c->Exists("/foo/honk"))
m DebugLog (wxString("exists invalid=")<< c->Exists("/invalid"))
m DebugLog (wxString("read /foo/blah=")<< c->ReadInt("/foo/blah",-1))
m DebugLog (wxString("read /foo/honk=")<< c->ReadInt("/foo/honk",-1))
m DebugLog (wxString("read /foo/honk=")<< c->ReadDouble("/foo/honk",-5.5))
m DebugLog (wxString("read /invalid=")<< c->ReadInt("/invalid", 4242))
m DebugLog (c-> ReadBinary"/trailing/slash/window-layout")
m DebugLog (pam ["a"])
m DebugLog (pam ["b"])
m DebugLog (pam ["c"])
m DebugLog (wxString("read /foo/one_or_zero=")<< c->ReadBool("/foo/one_or_zero"))
m DebugLog (wxString("main word:")<< c->Read("word"))
m DebugLog (wxString("volatile word:")<< cv->Read("word"))
m DebugLog (wxString("volatile top:")<< cv->Read("/top"))
m DebugLog (cstr)
for ()
for (OldConfigManagerContainer::StringSet::iterator it = sset.begin();it!=sset.end();++it) -> DebugLog(*it)
for (OldConfigManagerContainer::IntToStringMap::iterator it = imap.begin(); it != imap.end(); ++it)
sset insert ("zac")
Referenced by SearchTree< T >::AddItem(), cbEditor::AddToContextMenu(), and MenuItemsManager::CreateFromString().
sset insert ("boing")
sset insert ("boom")
sset insert ("Was würde der Fürst von Thurn & Taxis zu Umlauten sagen?")
MySerializableLongIntClass otherSerialLong (0)
otherSerialLong Print ()
c Read ("nonsense" , & otherSerialLong)
Referenced by CompilerXML::AutoDetectInstallationDir(), CompilerLCC::AutoDetectInstallationDir(), CompilerIAR::AutoDetectInstallationDir(), CompilerCYGWIN::AutoDetectInstallationDir(), CompilerGDC::AutoDetectInstallationDir(), CompilerKeilC51::AutoDetectInstallationDir(), CompilerMSVC::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerGNUFortran::AutoDetectInstallationDir(), CompilerG95::AutoDetectInstallationDir(), CompilerMINGW::AutoDetectInstallationDir(), cbEditor::CreateEditor(), EditorManager::EditorManager(), and CompilerGCC::OnAttach().
c Read ("not_red" , & col)
c Read ("red" , & col)
c Read< MySerializableLongIntClass > ("boo" , (OldConfigManagerContainer::SerializableObjectMap *)& objMap2)
wxColour red (255 , 0 , 0)
MySerializableLongIntClass serialLong (5)
c Set ("prz")
Referenced by ScriptBindings::Register_wxTypes(), and sq_rawset().
c SetPath ("/foo")
c SetPath ("/bar/some/path")
c SetPath ("/bar/another")
c SetPath ("/bar/yetanother")
c SetPath ("/trailing/slash/")
c SetPath ("../upalevel")
cstr sprintf ("not red : %d %d %d" , (int) col.Red() , (int) col.Green() , (int) col.Blue())
Referenced by ScriptBindings::wxString_AddChar().
cstr sprintf (" red : %d %d %d" , (int) col.Red() , (int) col.Green() , (int) col.Blue())
c UnSet ("prz")
c Write ("myname" , "Thomas")
c Write ("/top" , "bottom")
c Write ("/foo/blah" , 5)
c Write ("/foo/honk" , 2)
c Write ("/foo/honk" , 44. 8)
c Write ("/trailing/slash/data" , as)
c Write ("nonsense" , serialLong)
c Write ("/foo/thismapsletters" , map)
c Write ("boo" , (OldConfigManagerContainer::SerializableObjectMap *)& objMap1)
c Write ("/foo/one_or_zero" , true)
c Write ("/foo/one_or_zero" , false)
cv Write ("word" , "table")
c Write ("unique_strings" , sset)
c Write ("ints2strings" , imap)
c Write ("red" , red)
c WriteBinary ("/trailing/slash/window-layout" , wxString("Binary data. This can be anything which fits in a wxString or a pointer plus a size_t argument."))
Variable Documentation
wxArrayString as = c->ReadArrayString("/trailing/slash/data")
Referenced by LogManager::ListAvailable(), ConfigManager::ReadArrayString(), and ConfigManager::Write().
ConfigManager* c = Manager::Get()->GetConfigManager("main")
Referenced by _io_file_lexfeed_ASCII(), _io_file_lexfeed_UCS2_BE(), _io_file_lexfeed_UCS2_LE(), _io_file_lexfeed_UTF8(), _stream_readn(), _stream_writen(), CfgMgrBldr::Build(), ConfigManager::Collapse(), NativeParserBase::CountCommas(), CreateStaticNamespace(), Tokenizer::CurrentCharMoveNext(), wxBase64::Decode(), EncodingDetector::DetectEncodingEx(), Tokenizer::DoGetToken(), wxBase64::Encode(), ConfigManager::EnumerateKeys(), ConfigManager::EnumerateSubPaths(), NativeParserBase::FindFunctionOpenParenthesis(), NativeParserBase::GetCallTipHighlight(), cbSmartIndentPlugin::GetFirstBraceInLine(), cbDebuggerCommonConfig::GetFlag(), cbSmartIndentPlugin::GetLastNonCommentWord(), cbSmartIndentPlugin::GetLastNonWhitespaceChars(), Doxygen::DoxygenParser::GetLineArgument(), cbSmartIndentPlugin::GetNextNonWhitespaceCharOfLine(), cbSmartIndentPlugin::GetNextNonWhitespaceCharOnLine(), cbDebuggerCommonConfig::GetPerspective(), cbDebuggerCommonConfig::GetValueTooltipFont(), Doxygen::DoxygenParser::GetWordArgument(), ParserThread::HandleIncludes(), cbAuiNotebook::LoadPerspective(), number_delegate_tochar(), UsrGlblMgrEditDialog::OnFS(), ConfigManager::Read(), ConfigManagerWrapper::Read(), ConfigManagerWrapper::ReadBool(), ConfigManagerWrapper::ReadDouble(), ConfigManagerWrapper::ReadInt(), cbTextInputStream::ReadLine(), MacrosManager::RecalcVars(), cbEditor::RefreshBreakpointMarkers(), ParserThread::RemoveTemplateArgs(), ScriptSecurityWarningDlg::ScriptSecurityWarningDlg(), cbDebuggerCommonConfig::SetFlag(), EditorColourSet::SetKeywords(), ConfigManager::SetNodeText(), cbDebuggerCommonConfig::SetPerspective(), cbDebuggerCommonConfig::SetValueTooltipFont(), Tokenizer::SkipComment(), Tokenizer::SkipUnwanted(), sq_bindenv(), sq_getclosureinfo(), sq_getfunctioninfo(), sq_getlocal(), sqstd_rex_class(), SUITE(), CfgMgrBldr::SwitchTo(), CfgMgrBldr::SwitchToR(), SQCompiler::ThrowError(), pfDetails::Update(), URLEncode(), ConfigManagerWrapper::Write(), and ScriptBindings::wx_GetColourFromUser().
wxColour col
Referenced by BlendTextColour().
wxString cstr
ConfigManager* cv = Manager::Get()->GetConfigManager("volatile:main")
enumerated = c->EnumerateSubPaths("/")
imap = "poof"
MessageManager* m = Manager::Get()->GetMessageManager()
Referenced by CreateClass(), CreateStaticNamespace(), Manager::LoadMenu(), Manager::LoadMenuBar(), and wxScintillaEvent::SetModifiers().
map["c"] = "the letter A"
Referenced by ProjectLoader::SaveEnvironment().
objMap1["a"] = new MySerializableLongIntClass(1234)
objMap2
OldConfigManagerContainer::StringToStringMap pam = c->ReadSSMap("/foo/thismapsletters")
sset = c->ReadSSet("unique_strings")