Code::Blocks: crashhandler.cpp File Reference
crashhandler.cpp File Reference
#include "sdk.h"
#include "cbstyledtextctrl.h"
#include "crashhandler.h"
#include <shlobj.h>
Functions
void CrashHandlerSaveEditorFiles (wxString &buf)
LONG WINAPI CrashHandlerFunc (PEXCEPTION_POINTERS ExceptionInfo)
Function Documentation
CrashHandlerFunc()
LONG WINAPI CrashHandlerFunc (PEXCEPTION_POINTERS ExceptionInfo)
Definition at line 83 of file crashhandler.cpp.
References _(), _T, wxString::c_str(), CrashHandlerSaveEditorFiles(), and wxString::Printf().
Referenced by CrashHandler::CrashHandler().
CrashHandlerSaveEditorFiles()
void CrashHandlerSaveEditorFiles (wxString & buf) inline
Definition at line 26 of file crashhandler.cpp.
References _(), _T, cbSaveToFile(), wxDateTime::Format(), wxString::Format(), Manager::Get(), EditorManager::GetBuiltinEditor(), cbEditor::GetControl(), EditorManager::GetEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), cbEditor::GetEncoding(), EditorBase::GetFilename(), ConfigManager::GetHomeFolder(), wxScintilla::GetText(), cbEditor::GetUseBom(), wxDateTime::Now(), NULL, wxDirExists(), wxFileExists(), wxMkdir(), wxRmdir(), and wxT.
Referenced by CrashHandlerFunc().