Code::Blocks: debuggermanager.h File Reference
debuggermanager.h File Reference
#include <map>
#include <vector>
#include <wx/string.h>
#include "prep.h"
#include "settings.h"
#include "manager.h"
#include "configmanager.h"
Classes
class cbBreakpoint
class cbWatch
class cbStackFrame
class cbThread
class cbDebuggerConfiguration
struct cbDebuggerCommonConfig
class DebuggerManager
struct DebuggerManager::PluginData
Functions
cb::shared_ptr< cbWatch > DLLIMPORT cbGetRootWatch (cb::shared_ptr< cbWatch > watch)
DLLIMPORT wxString cbDetectDebuggerExecutable (const wxString &exeName)
Tries to detect the path to the debugger's executable.
DLLIMPORT uint64_t cbDebuggerStringToAddress (const wxString &address)
Convert a string in hex form to a uint64_t number.
DLLIMPORT wxString cbDebuggerAddressToString (uint64_t address)
Convert a uint64_t variable to a hex string that will look like an address.
Function Documentation
cbDebuggerAddressToString()
DLLIMPORT wxString cbDebuggerAddressToString (uint64_t address)
Convert a uint64_t variable to a hex string that will look like an address.
Definition at line 481 of file debuggermanager.cpp.
Referenced by DisassemblyDlg::AddAssemblerLine(), and cbStackFrame::GetAddressAsString().
cbDebuggerStringToAddress()
DLLIMPORT uint64_t cbDebuggerStringToAddress (const wxString & address)
Convert a string in hex form to a uint64_t number.
Returns
The uint64_t representation of the string or 0 when the string can't be converted.
Definition at line 471 of file debuggermanager.cpp.
Referenced by GdbCmd_Backtrace::MatchLine(), DebuggerGDB::OnCursorChanged(), CdbCmd_Backtrace::ParseOutput(), CdbCmd_Disassembly::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_Disassembly::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_StepOrNextInstruction::ParseOutput(), and DisassemblyDlg::SetActiveAddress().
cbDetectDebuggerExecutable()
DLLIMPORT wxString cbDetectDebuggerExecutable (const wxString & exeName)
Tries to detect the path to the debugger's executable.
Definition at line 443 of file debuggermanager.cpp.
References cbFindFileInPATH(), ConfigManager::GetExecutableFolder(), and HTMLTags::sep.
Referenced by DebuggerConfiguration::GetDebuggerExecutable().
cbGetRootWatch()
cb::shared_ptr<cbWatch> DLLIMPORT cbGetRootWatch (cb::shared_ptr< cbWatch > watch)
Definition at line 205 of file debuggermanager.cpp.
Referenced by DebuggerManager::GetDebuggerHavingWatch(), WatchesDlg::OnMenuUpdate(), WatchesDlg::OnPropertyRightClick(), and DebuggerGDB::SetWatchValue().