Code::Blocks: debugger_defs.h File Reference
debugger_defs.h File Reference
#include <wx/string.h>
#include <wx/dynarray.h>
#include <deque>
#include <vector>
#include "debuggermanager.h"
Classes
struct Cursor
Debugger cursor info.
class DebuggerCmd
Basic interface for debugger commands.
class DebuggerInfoCmd
This command is similar to DebuggerCmd The only difference is that instead of logging its output in the debugger log, it displays it in a dialog.
class DebuggerContinueBaseCmd
Base class for all Continue type of commands.
class DbgCmd_UpdateWatchesTree
Action-only debugger command to signal the watches tree to update.
struct DebuggerBreakpoint
Debugger breakpoint interface.
class GDBWatch
Typedefs
typedef std::deque< cb::shared_ptr< DebuggerBreakpoint > > BreakpointsList
typedef std::vector< cb::shared_ptr< GDBWatch > > WatchesContainer
Enumerations
enum WatchFormat {
Undefined = 0, Decimal, Unsigned, Hex,
Binary, Char, Float, Last,
Any
}
Watch variable format.
enum DebuggerLanguage { dl_Cpp = 0, dl_Fortran }
Functions
bool IsPointerType (wxString type)
wxString CleanStringValue (wxString value)
Variables
const int DEBUGGER_CURSOR_CHANGED
wxCommandEvent ID fired when the cursor has changed.
const int DEBUGGER_SHOW_FILE_LINE
wxCommandEvent ID fired to display a file/line (w/out changing the cursor)
DebuggerLanguage g_DebugLanguage
Typedef Documentation
BreakpointsList
typedef std::deque<cb::shared_ptr<DebuggerBreakpoint> > BreakpointsList
Definition at line 191 of file debugger_defs.h.
WatchesContainer
typedef std::vector<cb::shared_ptr<GDBWatch> > WatchesContainer
Definition at line 261 of file debugger_defs.h.
Enumeration Type Documentation
DebuggerLanguage
enum DebuggerLanguage
Enumerator
dl_Cpp
C++ or C language.
dl_Fortran
Fortran language.
Definition at line 266 of file debugger_defs.h.
WatchFormat
enum WatchFormat
Watch variable format.
Note
not all formats are implemented for all debugger drivers.
Enumerator
Undefined
Format is undefined (whatever the debugger uses by default).
Decimal
Variable should be displayed as decimal.
Unsigned
Variable should be displayed as unsigned.
Hex
Variable should be displayed as hexadecimal (e.g. 0xFFFFFFFF).
Binary
Variable should be displayed as binary (e.g. 00011001).
Char
Variable should be displayed as a single character (e.g. 'x').
Float
Variable should be displayed as floating point number (e.g. 14.35)
Last
used for iterations
Any
used for watches searches
Definition at line 197 of file debugger_defs.h.
Function Documentation
CleanStringValue()
wxString CleanStringValue (wxString value)
Definition at line 327 of file debugger_defs.cpp.
References wxString::EndsWith(), wxString::RemoveLast(), and wxT.
Referenced by DebuggerGDB::AddWatch(), EditWatchDlg::EndModal(), EditBreakpointDlg::EndModal(), GdbCmd_ExamineMemory::GdbCmd_ExamineMemory(), DataBreakpointDlg::GetDataExpression(), DebuggerGDB::SendCommand(), and GDB_driver::SetVarValue().
IsPointerType()
bool IsPointerType (wxString type)
Definition at line 309 of file debugger_defs.cpp.
References wxString::Contains(), wxString::EndsWith(), wxString::Trim(), and wxT.
Referenced by GdbCmd_TooltipEvaluation::GdbCmd_TooltipEvaluation(), GDBWatch::IsPointerType(), DebuggerGDB::OnWatchesContextMenu(), and SUITE().
Variable Documentation
DEBUGGER_CURSOR_CHANGED
const int DEBUGGER_CURSOR_CHANGED
wxCommandEvent ID fired when the cursor has changed.
Definition at line 27 of file debugger_defs.cpp.
Referenced by DebuggerDriver::NotifyCursorChanged().
DEBUGGER_SHOW_FILE_LINE
const int DEBUGGER_SHOW_FILE_LINE
wxCommandEvent ID fired to display a file/line (w/out changing the cursor)
Definition at line 28 of file debugger_defs.cpp.
Referenced by DebuggerDriver::ShowFile().
g_DebugLanguage
DebuggerLanguage g_DebugLanguage
Definition at line 334 of file debugger_defs.cpp.
Referenced by GdbCmd_Watch::GdbCmd_Watch(), ParseGDBWatchValue(), GdbCmd_DebugLanguage::ParseOutput(), and DebuggerGDB::SetWatchValue().