Code::Blocks: debuggersettingsdlg.cpp File Reference
debuggersettingsdlg.cpp File Reference
#include "sdk.h"
#include "debuggersettingsdlg.h"
#include <wx/string.h>
#include <wx/intl.h>
#include <wx/choicdlg.h>
#include "cbexception.h"
#include "cbplugin.h"
#include <wx/button.h>
#include <wx/font.h>
#include "debuggermanager.h"
#include "debuggersettingspanel.h"
#include "debuggersettingscommonpanel.h"
Functions
size_t FindPageIndex (wxTreebook *treebook, wxWindow *page)
Function Documentation
size_t FindPageIndex (wxTreebook * treebook, wxWindow * page) inline
Referenced by DebuggerSettingsDlg::CreateConfig(), DebuggerSettingsDlg::DeleteConfig(), and DebuggerSettingsDlg::ResetConfig().