Code::Blocks: debuggermanager.cpp File Reference
debuggermanager.cpp File Reference
#include "sdk_precomp.h"
#include <algorithm>
#include <sstream>
#include <wx/toolbar.h>
#include "debuggermanager.h"
#include "annoyingdialog.h"
#include "cbdebugger_interfaces.h"
#include "loggers.h"
#include "manager.h"
Classes
class DebugTextCtrlLogger
class DebugLogPanel
Functions
bool TestIfMarkedForRemoval (cb::shared_ptr< cbWatch > watch)
cb::shared_ptr< cbWatch > DLLIMPORT cbGetRootWatch (cb::shared_ptr< cbWatch > watch)
wxString cbDetectDebuggerExecutable (const wxString &exeName)
Tries to detect the path to the debugger's executable.
uint64_t cbDebuggerStringToAddress (const wxString &address)
Convert a string in hex form to a uint64_t number.
wxString cbDebuggerAddressToString (uint64_t address)
Convert a uint64_t variable to a hex string that will look like an address.
void ReadActiveDebuggerConfig (wxString &name, int &configIndex)
void WriteActiveDebuggerConfig (const wxString &name, int configIndex)
void RefreshBreakpoints (cb_unused const cbDebuggerPlugin *plugin)
Function Documentation
cbDebuggerAddressToString()
wxString cbDebuggerAddressToString (uint64_t address)
Convert a uint64_t variable to a hex string that will look like an address.
Definition at line 481 of file debuggermanager.cpp.
Referenced by DisassemblyDlg::AddAssemblerLine(), and cbStackFrame::GetAddressAsString().
cbDebuggerStringToAddress()
uint64_t cbDebuggerStringToAddress (const wxString & address)
Convert a string in hex form to a uint64_t number.
Returns
The uint64_t representation of the string or 0 when the string can't be converted.
Definition at line 471 of file debuggermanager.cpp.
References wxString::empty(), and wxString::utf8_str().
Referenced by GdbCmd_Backtrace::MatchLine(), DebuggerGDB::OnCursorChanged(), CdbCmd_Backtrace::ParseOutput(), CdbCmd_Disassembly::ParseOutput(), CdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_Disassembly::ParseOutput(), GdbCmd_DisassemblyInit::ParseOutput(), GdbCmd_StepOrNextInstruction::ParseOutput(), and DisassemblyDlg::SetActiveAddress().
cbDetectDebuggerExecutable()
wxString cbDetectDebuggerExecutable (const wxString & exeName)
Tries to detect the path to the debugger's executable.
Definition at line 443 of file debuggermanager.cpp.
References cbFindFileInPATH(), wxString::empty(), ConfigManager::GetExecutableFolder(), wxFileName::GetPathSeparator(), HTMLTags::sep, wxDirExists(), wxEmptyString, wxFileExists(), and wxT.
Referenced by DebuggerConfiguration::GetDebuggerExecutable().
cbGetRootWatch()
cb::shared_ptr<cbWatch> DLLIMPORT cbGetRootWatch (cb::shared_ptr< cbWatch > watch)
Definition at line 205 of file debuggermanager.cpp.
Referenced by DebuggerManager::GetDebuggerHavingWatch(), WatchesDlg::OnMenuUpdate(), WatchesDlg::OnPropertyRightClick(), and DebuggerGDB::SetWatchValue().
ReadActiveDebuggerConfig()
void ReadActiveDebuggerConfig (wxString & name, int & configIndex) inline
Definition at line 668 of file debuggermanager.cpp.
References _T, wxString::empty(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::Read(), ConfigManager::ReadInt(), wxEmptyString, and wxT.
Referenced by DebuggerManager::DebuggerManager(), and DebuggerManager::RegisterDebugger().
RefreshBreakpoints()
void RefreshBreakpoints (cb_unused const cbDebuggerPlugin * plugin) inline
Definition at line 1158 of file debuggermanager.cpp.
References Manager::Get(), EditorManager::GetEditor(), Manager::GetEditorManager(), EditorManager::GetEditorsCount(), and EditorBase::IsBuiltinEditor().
Referenced by DebuggerManager::RefreshUI().
TestIfMarkedForRemoval()
bool TestIfMarkedForRemoval (cb::shared_ptr< cbWatch > watch) inline
Definition at line 71 of file debuggermanager.cpp.
Referenced by cbWatch::RemoveMarkedChildren().
WriteActiveDebuggerConfig()
void WriteActiveDebuggerConfig (const wxString & name, int configIndex) inline
Definition at line 678 of file debuggermanager.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), ConfigManager::Write(), and wxT.
Referenced by DebuggerManager::FindTargetsDebugger(), and DebuggerManager::SetActiveDebugger().