Code::Blocks: debuggergdb.cpp File Reference
debuggergdb.cpp File Reference
#include <sdk.h>
#include <algorithm>
#include <wx/app.h>
#include <wx/txtstrm.h>
#include <wx/regex.h>
#include <wx/msgdlg.h>
#include <wx/frame.h>
#include <wx/menu.h>
#include <wx/filedlg.h>
#include "cbproject.h"
#include "manager.h"
#include "configmanager.h"
#include "logmanager.h"
#include "projectmanager.h"
#include "pluginmanager.h"
#include "editormanager.h"
#include "macrosmanager.h"
#include "cbeditor.h"
#include "projectbuildtarget.h"
#include "sdk_events.h"
#include "compilerfactory.h"
#include "xtra_res.h"
#include "scrollingdialog.h"
#include "globals.h"
#include <wx/tokenzr.h>
#include "editarraystringdlg.h"
#include "projectloader_hooks.h"
#include "annoyingdialog.h"
#include "cbstyledtextctrl.h"
#include "compilercommandgenerator.h"
#include <cbdebugger_interfaces.h>
#include "editbreakpointdlg.h"
#include "databreakpointdlg.h"
#include "debuggerdriver.h"
#include "debuggergdb.h"
#include "debuggeroptionsdlg.h"
#include "debuggeroptionsprjdlg.h"
#include "editwatchdlg.h"
Macros
#define implement_debugger_toolbar
Enumerations
enum DebugCommandConst {
CMD_CONTINUE, CMD_STEP, CMD_STEPIN, CMD_STEPOUT,
CMD_STEP_INSTR, CMD_STEP_INTO_INSTR, CMD_STOP, CMD_BACKTRACE,
CMD_DISASSEMBLE, CMD_REGISTERS, CMD_MEMORYDUMP, CMD_RUNNINGTHREADS
}
Functions
BOOL WINAPI HandlerRoutine (cb_unused DWORD dwCtrlType)
Variables
const wxString g_EscapeChar = wxChar(26)
Macro Definition Documentation
#define implement_debugger_toolbar
Enumeration Type Documentation
enum DebugCommandConst
Enumerator
CMD_CONTINUE
CMD_STEP
CMD_STEPIN
CMD_STEPOUT
CMD_STEP_INSTR
CMD_STEP_INTO_INSTR
CMD_STOP
CMD_BACKTRACE
CMD_DISASSEMBLE
CMD_REGISTERS
CMD_MEMORYDUMP
CMD_RUNNINGTHREADS
Function Documentation
BOOL WINAPI HandlerRoutine (cb_unused DWORD dwCtrlType) inline
Referenced by DebuggerGDB::DoDebug(), and DebuggerGDB::KillConsole().
Variable Documentation
const wxString g_EscapeChar = wxChar(26)
Referenced by GDB_driver::CorrectCygwinPath(), and GDB_driver::ParseOutput().