Code::Blocks: debugger_interface_creator.cpp File Reference
debugger_interface_creator.cpp File Reference
#include <sdk.h>
#include "debugger_interface_creator.h"
#include "backtracedlg.h"
#include "breakpointsdlg.h"
#include "cbstyledtextctrl.h"
#include "cpuregistersdlg.h"
#include "disassemblydlg.h"
#include "examinememorydlg.h"
#include "threadsdlg.h"
#include "watchesdlg.h"
Functions
void RemoveDockWindow (wxWindow *window)
Function Documentation
RemoveDockWindow()
void RemoveDockWindow (wxWindow * window) inline
Definition at line 25 of file debugger_interface_creator.cpp.
References cbEVT_REMOVE_DOCK_WINDOW, Manager::Get(), Manager::ProcessEvent(), and CodeBlocksDockEvent::pWindow.
Referenced by DebugInterfaceFactory::DeleteBacktrace(), DebugInterfaceFactory::DeleteBreakpoints(), DebugInterfaceFactory::DeleteCPURegisters(), DebugInterfaceFactory::DeleteDisassembly(), DebugInterfaceFactory::DeleteMemory(), DebugInterfaceFactory::DeleteThreads(), and DebugInterfaceFactory::DeleteWatches().