Code::Blocks: debugger_defs.cpp File Reference
debugger_defs.cpp File Reference
#include "sdk.h"
#include <cbdebugger_interfaces.h>
#include "debugger_defs.h"
#include "debuggerdriver.h"
#include <wx/arrimpl.cpp>
Classes
class DebuggerInfoWindow
Functions
bool IsPointerType (wxString type)
wxString CleanStringValue (wxString value)
Variables
const int DEBUGGER_CURSOR_CHANGED = wxNewId()
wxCommandEvent ID fired when the cursor has changed.
const int DEBUGGER_SHOW_FILE_LINE = wxNewId()
wxCommandEvent ID fired to display a file/line (w/out changing the cursor)
Function Documentation
CleanStringValue()
wxString CleanStringValue (wxString value)
Definition at line 314 of file debugger_defs.cpp.
Referenced by DebuggerGDB::AddWatch(), EditWatchDlg::EndModal(), EditBreakpointDlg::EndModal(), GdbCmd_ExamineMemory::GdbCmd_ExamineMemory(), DataBreakpointDlg::GetDataExpression(), DebuggerGDB::SendCommand(), and GDB_driver::SetVarValue().
IsPointerType()
bool IsPointerType (wxString type)
Definition at line 296 of file debugger_defs.cpp.
Referenced by GdbCmd_TooltipEvaluation::GdbCmd_TooltipEvaluation(), DebuggerGDB::OnWatchesContextMenu(), and SUITE().
Variable Documentation
DEBUGGER_CURSOR_CHANGED
const int DEBUGGER_CURSOR_CHANGED = wxNewId()
wxCommandEvent ID fired when the cursor has changed.
Definition at line 27 of file debugger_defs.cpp.
Referenced by DebuggerDriver::NotifyCursorChanged().
DEBUGGER_SHOW_FILE_LINE
const int DEBUGGER_SHOW_FILE_LINE = wxNewId()
wxCommandEvent ID fired to display a file/line (w/out changing the cursor)
Definition at line 28 of file debugger_defs.cpp.
Referenced by DebuggerDriver::ShowFile().