Code::Blocks: debuggergdb_test_common.h File Reference
debuggergdb_test_common.h File Reference
#include <UnitTest++.h>
#include <wx/string.h>
Functions
std::ostream & operator<< (std::ostream &stream, wxString const &s)
std::ostream & operator<< (std::ostream &stream, wxChar const *s)
std::ostream & operator<< (std::ostream &stream, cbWatch const &w)
bool operator== (wxString const &s, cbWatch const &w)
Function Documentation
operator<<() [1/3]
std::ostream& operator<< (std::ostream & stream, wxString const & s) inline
Definition at line 5 of file debuggergdb_test_common.h.
References wxString::utf8_str().
Referenced by operator<<().
operator<<() [2/3]
std::ostream& operator<< (std::ostream & stream, wxChar const * s) inline
Definition at line 10 of file debuggergdb_test_common.h.
References operator<<(), operator==(), and wxString::utf8_str().
operator<<() [3/3]
std::ostream& operator<< (std::ostream & stream, cbWatch const & w)
Definition at line 38 of file debuggergdb_test_parser.cpp.
References WatchToString().
operator==()
bool operator== (wxString const & s, cbWatch const & w)
Definition at line 43 of file debuggergdb_test_parser.cpp.
References WatchToString().
Referenced by operator<<().