Code::Blocks: debuggergdb_test_backtrace.cpp File Reference
debuggergdb_test_backtrace.cpp File Reference
#include "debuggergdb_test_common.h"
#include "gdb_commands.h"
Functions
SUITE (GDBStackFrameParser)
Function Documentation
SUITE (GDBStackFrameParser)
References cbStackFrame::GetAddress(), cbStackFrame::GetFilename(), cbStackFrame::GetLine(), cbStackFrame::GetNumber(), cbStackFrame::GetSymbol(), and GdbCmd_Backtrace::MatchLine().