Code::Blocks: debuggergdb_test_parser.cpp File Reference
debuggergdb_test_parser.cpp File Reference
#include "debuggergdb_test_common.h"
#include "parsewatchvalue.h"
Functions
wxString WatchToString (cbWatch const &watch)
wxString getName (cbWatch const &watch)
std::ostream & operator<< (std::ostream &stream, cbWatch const &w)
bool operator== (wxString const &s, cbWatch const &w)
SUITE (WatchToString)
SUITE (GDBWatchParser)
Function Documentation
getName()
wxString getName (cbWatch const & watch) inline
Definition at line 31 of file debuggergdb_test_parser.cpp.
References cbWatch::GetSymbol().
Referenced by SUITE().
operator<<()
std::ostream& operator<< (std::ostream & stream, cbWatch const & w)
Definition at line 38 of file debuggergdb_test_parser.cpp.
References WatchToString().
operator==()
bool operator== (wxString const & s, cbWatch const & w)
Definition at line 43 of file debuggergdb_test_parser.cpp.
References WatchToString().
Referenced by operator<<().
SUITE() [1/2]
SUITE (WatchToString)
Definition at line 48 of file debuggergdb_test_parser.cpp.
References cbWatch::AddChild(), GDBWatch::SetValue(), and wxT.
SUITE() [2/2]
SUITE (GDBWatchParser)
Definition at line 124 of file debuggergdb_test_parser.cpp.
References getName(), ParseGDBWatchValue(), and wxT.
WatchToString()
wxString WatchToString (cbWatch const & watch)
Definition at line 4 of file debuggergdb_test_parser.cpp.
References cbWatch::GetChild(), cbWatch::GetChildCount(), cbWatch::GetSymbol(), cbWatch::GetValue(), and wxT.
Referenced by operator<<(), operator==(), WatchRawDialog::SetValue(), and WatchRawDialog::WatchToString().