Code::Blocks: directcommands.cpp File Reference
directcommands.cpp File Reference
#include <sdk.h>
#include <wx/intl.h>
#include <wx/filename.h>
#include <wx/msgdlg.h>
#include <wx/stream.h>
#include <wx/wfstream.h>
#include <wx/txtstrm.h>
#include <wx/regex.h>
#include <compiler.h>
#include <cbproject.h>
#include <projectbuildtarget.h>
#include <globals.h>
#include <manager.h>
#include <logmanager.h>
#include <configmanager.h>
#include <macrosmanager.h>
#include "directcommands.h"
#include "compilercommandgenerator.h"
#include "compilergcc.h"
#include "cbexception.h"
#include "filefilters.h"
#include <depslib.h>
Functions
static int MySortProjectFilesByWeight (ProjectFile **one, ProjectFile **two)
Variables
const wxString COMPILER_SIMPLE_LOG (_T("SLOG:"))
const wxString COMPILER_NOTE_LOG (_T("SLOG:NLOG:"))
const wxString COMPILER_WARNING_LOG (_T("SLOG:WLOG:"))
const wxString COMPILER_ERROR_LOG (_T("SLOG:ELOG:"))
const wxString COMPILER_TARGET_CHANGE (_T("TGT:"))
const wxString COMPILER_WAIT (_T("WAIT"))
const wxString COMPILER_WAIT_LINK (_T("LINK"))
const wxString COMPILER_NOTE_ID_LOG = COMPILER_NOTE_LOG.AfterFirst(wxT(':'))
const wxString COMPILER_WARNING_ID_LOG = COMPILER_WARNING_LOG.AfterFirst(wxT(':'))
const wxString COMPILER_ERROR_ID_LOG = COMPILER_ERROR_LOG.AfterFirst(wxT(':'))
Function Documentation
MySortProjectFilesByWeight()
static int MySortProjectFilesByWeight (ProjectFile ** one, ProjectFile ** two) static
Definition at line 131 of file directcommands.cpp.
Referenced by DirectCommands::GetProjectFilesSortedByWeight().
Variable Documentation
COMPILER_ERROR_ID_LOG
const wxString COMPILER_ERROR_ID_LOG = COMPILER_ERROR_LOG.AfterFirst(wxT(':'))
Definition at line 43 of file directcommands.cpp.
Referenced by CompilerGCC::LogMessage().
COMPILER_ERROR_LOG
const wxString COMPILER_ERROR_LOG(_T("SLOG:ELOG:"))
Referenced by CompilerGCC::BuildStateManagement(), and CompilerGCC::DoCleanWithMake().
COMPILER_NOTE_ID_LOG
const wxString COMPILER_NOTE_ID_LOG = COMPILER_NOTE_LOG.AfterFirst(wxT(':'))
Definition at line 41 of file directcommands.cpp.
Referenced by CompilerGCC::LogMessage().
COMPILER_NOTE_LOG
const wxString COMPILER_NOTE_LOG(_T("SLOG:NLOG:"))
Referenced by DirectCommands::GetTargetLinkCommands().
COMPILER_SIMPLE_LOG
const wxString COMPILER_SIMPLE_LOG(_T("SLOG:"))
Referenced by CompilerGCC::AddToCommandQueue(), CompilerGCC::BuildStateManagement(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetCompileSingleFileCommand(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), DirectCommands::GetTargetLinkCommands(), and CompilerGCC::LogMessage().
COMPILER_TARGET_CHANGE
const wxString COMPILER_TARGET_CHANGE(_T("TGT:"))
Referenced by CompilerGCC::AddToCommandQueue(), DirectCommands::CompileFile(), and DirectCommands::GetTargetLinkCommands().
COMPILER_WAIT
const wxString COMPILER_WAIT(_T("WAIT"))
Referenced by DirectCommands::AddCommandsToArray(), CompilerGCC::AddToCommandQueue(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetPostBuildCommands(), DirectCommands::GetPreBuildCommands(), and DirectCommands::GetTargetCompileCommands().
COMPILER_WAIT_LINK
const wxString COMPILER_WAIT_LINK(_T("LINK"))
Referenced by DirectCommands::AddCommandsToArray(), and CompilerGCC::AddToCommandQueue().
COMPILER_WARNING_ID_LOG
const wxString COMPILER_WARNING_ID_LOG = COMPILER_WARNING_LOG.AfterFirst(wxT(':'))
Definition at line 42 of file directcommands.cpp.
Referenced by CompilerGCC::LogMessage().
COMPILER_WARNING_LOG
const wxString COMPILER_WARNING_LOG(_T("SLOG:WLOG:"))
Referenced by DirectCommands::CompileFile(), DirectCommands::GetTargetCompileCommands(), and DirectCommands::GetTargetLinkCommands().