Code::Blocks: editorcolourset.cpp File Reference
editorcolourset.cpp File Reference
#include "sdk_precomp.h"
#include <wx/regex.h>
#include <wx/txtstrm.h>
#include <wx/wfstream.h>
#include "cbcolourmanager.h"
#include "cbstyledtextctrl.h"
#include "editorcolourset.h"
#include "editorlexerloader.h"
#include "filefilters.h"
Functions
static int CompareStringNoCase (const wxString &first, const wxString &second)
static OptionColour * GetDefaultOption (OptionSet &mset)
Function Documentation
CompareStringNoCase()
static int CompareStringNoCase (const wxString & first, const wxString & second) static
Definition at line 241 of file editorcolourset.cpp.
References wxString::CmpNoCase().
Referenced by EditorColourSet::GetAllHighlightLanguages().
GetDefaultOption()
static OptionColour* GetDefaultOption (OptionSet & mset) static
Definition at line 526 of file editorcolourset.cpp.
References OptionSet::m_Colours, OptionColour::name, OptionColour::value, and wxT.
Referenced by EditorColourSet::SetName().