Code::Blocks: editorbase.cpp File Reference
editorbase.cpp File Reference
#include "sdk_precomp.h"
#include "cbauibook.h"
#include "cbstyledtextctrl.h"
Classes
struct EditorBaseInternalData
Functions
int editorbase_RegisterId (int id)
Variables
const int EditorMaxSwitchTo = 255
const int idSwitchFile1 = wxNewId()
const int idSwitchFileMax = editorbase_RegisterId(idSwitchFile1 + EditorMaxSwitchTo -1)
const int idCloseMe = wxNewId()
const int idCloseAll = wxNewId()
const int idCloseAllOthers = wxNewId()
const int idSaveMe = wxNewId()
const int idSaveAll = wxNewId()
const int idSwitchTo = wxNewId()
const long idGoogle = wxNewId()
const long idMsdn = wxNewId()
const long idStackOverflow = wxNewId()
const long idCodeProject = wxNewId()
Function Documentation
editorbase_RegisterId()
int editorbase_RegisterId (int id) inline
Definition at line 31 of file editorbase.cpp.
Variable Documentation
EditorMaxSwitchTo
const int EditorMaxSwitchTo = 255
Definition at line 51 of file editorbase.cpp.
Referenced by EditorBase::CreateContextSubMenu().
idCloseAll
const int idCloseAll = wxNewId()
Definition at line 56 of file editorbase.cpp.
Referenced by EditorBase::BasicAddToContextMenu(), and EditorBase::OnContextMenuEntry().
idCloseAllOthers
const int idCloseAllOthers = wxNewId()
Definition at line 57 of file editorbase.cpp.
Referenced by EditorBase::BasicAddToContextMenu(), and EditorBase::OnContextMenuEntry().
idCloseMe
const int idCloseMe = wxNewId()
Definition at line 55 of file editorbase.cpp.
Referenced by EditorBase::BasicAddToContextMenu(), and EditorBase::OnContextMenuEntry().
idCodeProject
const long idCodeProject = wxNewId()
Definition at line 66 of file editorbase.cpp.
Referenced by EditorBase::DisplayContextMenu(), and EditorBase::OnContextMenuEntry().
idGoogle
const long idGoogle = wxNewId()
Definition at line 63 of file editorbase.cpp.
Referenced by EditorBase::DisplayContextMenu(), and EditorBase::OnContextMenuEntry().
idMsdn
const long idMsdn = wxNewId()
Definition at line 64 of file editorbase.cpp.
Referenced by EditorBase::DisplayContextMenu(), and EditorBase::OnContextMenuEntry().
idSaveAll
const int idSaveAll = wxNewId()
Definition at line 59 of file editorbase.cpp.
Referenced by EditorBase::BasicAddToContextMenu(), and EditorBase::OnContextMenuEntry().
idSaveMe
const int idSaveMe = wxNewId()
Definition at line 58 of file editorbase.cpp.
Referenced by EditorBase::BasicAddToContextMenu(), and EditorBase::OnContextMenuEntry().
idStackOverflow
const long idStackOverflow = wxNewId()
Definition at line 65 of file editorbase.cpp.
Referenced by EditorBase::DisplayContextMenu(), and EditorBase::OnContextMenuEntry().
idSwitchFile1
const int idSwitchFile1 = wxNewId()
Definition at line 52 of file editorbase.cpp.
Referenced by EditorBase::CreateContextSubMenu(), and EditorBase::OnContextMenuEntry().
idSwitchFileMax
const int idSwitchFileMax = editorbase_RegisterId(idSwitchFile1 + EditorMaxSwitchTo -1)
Definition at line 53 of file editorbase.cpp.
Referenced by EditorBase::OnContextMenuEntry().
idSwitchTo
const int idSwitchTo = wxNewId()
Definition at line 60 of file editorbase.cpp.
Referenced by EditorBase::BasicAddToContextMenu(), EditorBase::CreateContextSubMenu(), and EditorBase::DisplayContextMenu().