Code::Blocks: editormanager.cpp File Reference
editormanager.cpp File Reference
#include "sdk_precomp.h"
#include "annoyingdialog.h"
#include "cbstyledtextctrl.h"
#include "cbcolourmanager.h"
#include <wx/bmpbuttn.h>
#include <wx/clipbrd.h>
#include <wx/fontutil.h>
#include <wx/progdlg.h>
#include "cbauibook.h"
#include "editorcolourset.h"
#include "confirmreplacedlg.h"
#include "filefilters.h"
#include "projectfileoptionsdlg.h"
#include "filegroupsandmasks.h"
Classes
struct EditorManagerInternalData
struct EditorManagerInternalData * This is the private data holder for the EditorManager * All data not relevant to other classes should go here *
Functions
int cbRegisterId (int id)
Variables
int ID_NBEditorManager = wxNewId()
int ID_EditorManager = wxNewId()
int idEditorManagerCheckFiles = wxNewId()
static const int idNBTabSplitHorz = wxNewId()
static const int idNBTabSplitVert = wxNewId()
static const int idNBTabUnsplit = wxNewId()
static const int idNBTabClose = wxNewId()
static const int idNBTabCloseAll = wxNewId()
static const int idNBTabCloseAllOthers = wxNewId()
static const int idNBTabSave = wxNewId()
static const int idNBTabSaveAll = wxNewId()
static const int idNBSwapHeaderSource = wxNewId()
static const int idNBTabOpenContainingFolder = wxNewId()
static const int idNBTabTop = wxNewId()
static const int idNBTabBottom = wxNewId()
static const int idNBProperties = wxNewId()
static const int idNBAddFileToProject = wxNewId()
static const int idNBRemoveFileFromProject = wxNewId()
static const int idNBShowFileInTree = wxNewId()
static const int EditorMaxSwitchTo = 255
static const int idNBSwitchFile1 = wxNewId()
static const int idNBSwitchFileMax = cbRegisterId(idNBSwitchFile1 + EditorMaxSwitchTo - 1)
Function Documentation
cbRegisterId()
int cbRegisterId (int id) inline
Definition at line 63 of file editormanager.cpp.
References wxRegisterId().
Variable Documentation
EditorMaxSwitchTo
const int EditorMaxSwitchTo = 255 static
Definition at line 87 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
ID_EditorManager
int ID_EditorManager = wxNewId()
Definition at line 56 of file editormanager.cpp.
ID_NBEditorManager
int ID_NBEditorManager = wxNewId()
Definition at line 55 of file editormanager.cpp.
Referenced by EditorManager::EditorManager().
idEditorManagerCheckFiles
int idEditorManagerCheckFiles = wxNewId()
Definition at line 57 of file editormanager.cpp.
Referenced by CodeBlocksApp::OnAppActivate().
idNBAddFileToProject
const int idNBAddFileToProject = wxNewId() static
Definition at line 82 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBProperties
const int idNBProperties = wxNewId() static
Definition at line 81 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBRemoveFileFromProject
const int idNBRemoveFileFromProject = wxNewId() static
Definition at line 83 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBShowFileInTree
const int idNBShowFileInTree = wxNewId() static
Definition at line 84 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBSwapHeaderSource
const int idNBSwapHeaderSource = wxNewId() static
Definition at line 77 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBSwitchFile1
const int idNBSwitchFile1 = wxNewId() static
Definition at line 88 of file editormanager.cpp.
Referenced by EditorManager::OnGenericContextMenuHandler(), and EditorManager::OnPageContextMenu().
idNBSwitchFileMax
const int idNBSwitchFileMax = cbRegisterId(idNBSwitchFile1 + EditorMaxSwitchTo - 1) static
Definition at line 89 of file editormanager.cpp.
Referenced by EditorManager::OnGenericContextMenuHandler().
idNBTabBottom
const int idNBTabBottom = wxNewId() static
Definition at line 80 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu(), and EditorManager::OnTabPosition().
idNBTabClose
const int idNBTabClose = wxNewId() static
Definition at line 72 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBTabCloseAll
const int idNBTabCloseAll = wxNewId() static
Definition at line 73 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBTabCloseAllOthers
const int idNBTabCloseAllOthers = wxNewId() static
Definition at line 74 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBTabOpenContainingFolder
const int idNBTabOpenContainingFolder = wxNewId() static
Definition at line 78 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBTabSave
const int idNBTabSave = wxNewId() static
Definition at line 75 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBTabSaveAll
const int idNBTabSaveAll = wxNewId() static
Definition at line 76 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBTabSplitHorz
const int idNBTabSplitHorz = wxNewId() static
Definition at line 69 of file editormanager.cpp.
Referenced by EditorManager::OnGenericContextMenuHandler(), and EditorManager::OnPageContextMenu().
idNBTabSplitVert
const int idNBTabSplitVert = wxNewId() static
Definition at line 70 of file editormanager.cpp.
Referenced by EditorManager::OnGenericContextMenuHandler(), and EditorManager::OnPageContextMenu().
idNBTabTop
const int idNBTabTop = wxNewId() static
Definition at line 79 of file editormanager.cpp.
Referenced by EditorManager::OnPageContextMenu().
idNBTabUnsplit
const int idNBTabUnsplit = wxNewId() static
Definition at line 71 of file editormanager.cpp.
Referenced by EditorManager::OnGenericContextMenuHandler(), and EditorManager::OnPageContextMenu().