Code::Blocks: encodingdetector.cpp File Reference
encodingdetector.cpp File Reference
#include "sdk_precomp.h"
#include "encodingdetector.h"
#include "filemanager.h"
#include "nsError.h"
#include "nsUniversalDetector.h"
#include <wx/encconv.h>
Functions
wxString makeStringNoNull (const wxWCharBuffer &wideBuff)
Convert the char buffer to wxString and if there are any null-terminating characters at the end - remove them.
Function Documentation
makeStringNoNull()
wxString makeStringNoNull (const wxWCharBuffer & wideBuff) inline
Convert the char buffer to wxString and if there are any null-terminating characters at the end - remove them.
Definition at line 419 of file encodingdetector.cpp.
References wxString::empty(), wxString::find_last_not_of(), wxString::npos, wxString::resize(), and wxT.
Referenced by EncodingDetector::ConvertToWxString().