Code::Blocks: gdb_commands.h File Reference
gdb_commands.h File Reference
#include <map>
#include <wx/string.h>
#include <wx/regex.h>
#include <wx/tipwin.h>
#include <wx/tokenzr.h>
#include <cbeditor.h>
#include <cbdebugger_interfaces.h>
#include <configmanager.h>
#include <globals.h>
#include <manager.h>
#include <editormanager.h>
#include <infowindow.h>
#include <logmanager.h>
#include <macrosmanager.h>
#include <scriptingmanager.h>
#include <sqplus.h>
#include <scripting/bindings/sc_base_types.h>
#include "debugger_defs.h"
#include "debuggergdb.h"
#include "gdb_driver.h"
#include "remotedebugging.h"
#include "parsewatchvalue.h"
Classes
class GdbCmd_AddSourceDir
Command to add a search directory for source files in debugger's paths.
class GdbCmd_SetDebuggee
Command to the set the file to be debugged.
class GdbCmd_AddSymbolFile
Command to the add symbol files.
class GdbCmd_SetArguments
Command to set the arguments to the debuggee.
class GdbCmd_AttachToProcess
Command to the attach to a process.
class GdbCmd_Detach
Command to the detach from the process.
class GdbCmd_AddBreakpointCondition
Utility command to set a breakpoint condition.
class GdbCmd_AddBreakpoint
Command to add a breakpoint.
class GdbCmd_AddDataBreakpoint
Command to add a data breakpoint.
class GdbCmd_RemoveBreakpoint
Command to remove a breakpoint.
class GdbCmd_SetCatch
Command to setup an exception breakpoint (for a throw or a catch).
class GdbCmd_Continue
Command that notifies the debugger plugin that the debuggee has been continued.
class GdbCmd_Start
class GdbCmd_InfoProgram
Command to get info about current program and state.
class GdbCmd_Threads
Command to get info about running threads.
class GdbCmd_Watch
Command to get info about a watched variable.
class GdbCmd_FindWatchType
Command to get a watched variable's type.
class GdbCmd_TooltipEvaluation
Command to display a tooltip about a variables value.
class GdbCmd_FindTooltipAddress
Command to get a symbol's type and use it for tooltip evaluation.
class GdbCmd_FindTooltipType
Command to get a symbol's type and use it for tooltip evaluation.
class GdbCmd_LocalsFuncArgs
class GdbCmd_ChangeFrame
Command to change the current frame.
class GdbCmd_Backtrace
Command to run a backtrace.
class GdbCmd_InfoRegisters
Command to obtain register info.
class GdbCmd_Disassembly
Command to run a disassembly.
class GdbCmd_DisassemblyInit
Command to initialize a disassembly.
class GdbCmd_ExamineMemory
Command to examine a memory region.
class GdbCmd_RemoteBaud
class GdbCmd_RemoteTarget
class GdbCmd_StepOrNextInstruction
class GdbCmd_StepInstruction
class GdbCmd_StepIntoInstruction
class GdbCmd_FindCursor
Command which tries to find the current cursor position.
Functions
static wxRegEx reBT0 (_T("#([0-9]+)[ \+(.+)[ \at[ \(.+):([0-9]+)"))
static wxRegEx reBT1 (_T("#([0-9]+)[ \+0x([A-Fa-f0-9]+)[ \+in[ \+(.+)[ \+(\[^)]*\)[ \"))
static wxRegEx reBTX (_T("#([0-9]+)[ \+0x([A-Fa-f0-9]+)[ \+in[ \+([^(]+)[ \*(\[^)]*\[ \*\[^)]*\)"))
static wxRegEx reBT2 (_T("\[ \+[atfrom]+[ \+(.*):([0-9]+)"))
static wxRegEx reBT3 (_T("\[ \+[atfrom]+[ \+(.*)"))
static wxRegEx reBT4 (_T("#([0-9]+)[ \]+(.+)[ \]in[ \](.+)"))
static wxRegEx reBreakpoint (_T("Breakpoint ([0-9]+) at (0x[0-9A-Fa-f]+)"))
static wxRegEx rePendingBreakpoint (_T("Breakpoint ([0-9]+)[ \\\.+):([0-9]+)(\)\[ \pending\"))
static wxRegEx reHWBreakpoint (_T("Hardware assisted breakpoint ([0-9]+) at (0x[0-9A-Fa-f]+)"))
static wxRegEx reDataBreakpoint (_T("Hardware watchpoint ([0-9]+):.*"))
static wxRegEx reTemporaryBreakpoint (wxT("^[Tt]emporary[ \breakpoint[ \([0-9]+)[ \at.*"))
static wxRegEx reRegisters (_T("([A-z0-9]+)[ \+(0x[0-9A-Fa-f]+)[ \+(.*)"))
static wxRegEx reDisassembly (_T("(0x[0-9A-Za-z]+)[ \+<.*>:[ \+(.*)"))
static wxRegEx reDisassemblySource (_T("([0-9]+)[ \(.*)"))
static wxRegEx reDisassemblyInit (_T("^[ \*Stack level [0-9]+, frame at (0x[A-Fa-f0-9]+):"))
static wxRegEx reDisassemblyInitSymbol (_T("[ \*[er]ip[ \+=[ \+0x[0-9a-f]+[ \+in[ \+(.+)\(.+):([0-9]+)\;"))
static wxRegEx reDisassemblyInitFunc (_T("eip = (0x[A-Fa-f0-9]+) in ([^;]*)"))
static wxRegEx reDisassemblyInitFuncOR32 (_T("PC = (0x[A-Fa-f0-9]+) in ([^;]*)"))
static wxRegEx reDisassemblyCurPC (_T("=>[ \+(0x[A-Fa-f0-9]+)"))
static wxRegEx reInfoProgramThread (_T("\LWP[ \([0-9]+)\"))
static wxRegEx reInfoProgramProcess (_T("child process ([0-9]+)"))
static wxRegEx reInfoThreads (_T("(\*)[ \*([0-9]+)[ \(.*)"))
static wxRegEx reGenericHexAddress (_T("(0x[A-Fa-f0-9]+)"))
static wxRegEx reExamineMemoryLine (wxT("[ \*(0x[0-9a-f]+)[ <.+>:[ \+(.+)"))
static wxRegEx reStepI (wxT("(((.*)[a-zA-Z]:)?.*)?:(\+):(middle|beg):(.*)"), wxRE_ADVANCED)
static wxRegEx reStepI2 (_T("\(0x[A-Fa-f0-9]+)\+(\+)\+in (.*)"), wxRE_ADVANCED)
static wxRegEx reStepI3 (_T("^(0x[A-Fa-f0-9]+) in (.*)? from (.*)"))
static wxRegEx reStepI4 (_T("^(0x[A-Fa-f0-9]+) in (.*)? at (.*)"))
static wxRegEx reNextI (_T("\a\a(([a-zA-Z]:)?.*?):([0-9]*):([0-9]*):(middle|beg):(.*)"), wxRE_ADVANCED)
Function Documentation
reBreakpoint()
static wxRegEx reBreakpoint (_T("Breakpoint ([0-9]+) at (0x[0-9A-Fa-f]+)")) static
Referenced by GdbCmd_AddBreakpoint::ParseOutput().
reBT0()
static wxRegEx reBT0 (_T("#([0-9]+)[ \(.+)[ \t[ \.+):([0-9]+)")) static
Referenced by GdbCmd_Backtrace::MatchLine().
reBT1()
static wxRegEx reBT1 (_T("#([0-9]+)[ \x([A-Fa-f0-9]+)[ \n[ \.+)[ \\)]*\ \) static
Referenced by GdbCmd_Backtrace::MatchLine().
reBT2()
static wxRegEx reBT2 (_T("\ \[atfrom]+[ \(.*):([0-9]+)")) static
Referenced by GdbCmd_Backtrace::MatchLine().
reBT3()
static wxRegEx reBT3 (_T("\ \[atfrom]+[ \(.*)")) static
Referenced by GdbCmd_Backtrace::MatchLine().
reBT4()
static wxRegEx reBT4 (_T("#([0-9]+)[ \+(.+)[ \in[ \(.+)")) static
Referenced by GdbCmd_Backtrace::MatchLine().
reBTX()
static wxRegEx reBTX (_T("#([0-9]+)[ \x([A-Fa-f0-9]+)[ \n[ \[^(]+)[ \\)]*\\^)]*\) static
Referenced by GdbCmd_Backtrace::MatchLine().
reDataBreakpoint()
static wxRegEx reDataBreakpoint (_T("Hardware watchpoint ([0-9]+):.*")) static
Referenced by GdbCmd_AddBreakpoint::ParseOutput().
reDisassembly()
static wxRegEx reDisassembly (_T("(0x[0-9A-Za-z]+)[ <.*>:[ \(.*)")) static
Referenced by GdbCmd_Disassembly::ParseOutput().
reDisassemblyCurPC()
static wxRegEx reDisassemblyCurPC (_T("=>[ \(0x[A-Fa-f0-9]+)")) static
Referenced by GdbCmd_DisassemblyInit::ParseOutput().
reDisassemblyInit()
static wxRegEx reDisassemblyInit (_T("^[ \Stack level [0-9]+, frame at (0x[A-Fa-f0-9]+):")) static
Referenced by GdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_FindCursor::ParseOutput().
reDisassemblyInitFunc()
static wxRegEx reDisassemblyInitFunc (_T("eip = (0x[A-Fa-f0-9]+) in ([^;]*)")) static
Referenced by GdbCmd_DisassemblyInit::ParseOutput().
reDisassemblyInitFuncOR32()
static wxRegEx reDisassemblyInitFuncOR32 (_T("PC = (0x[A-Fa-f0-9]+) in ([^;]*)")) static
reDisassemblyInitSymbol()
static wxRegEx reDisassemblyInitSymbol (_T("[ \[er]ip[ \=[ \0x[0-9a-f]+[ \in[ \(.+)\.+):([0-9]+)\")) static
Referenced by GdbCmd_DisassemblyInit::ParseOutput(), and GdbCmd_FindCursor::ParseOutput().
reDisassemblySource()
static wxRegEx reDisassemblySource (_T("([0-9]+)[ \.*)")) static
Referenced by GdbCmd_Disassembly::ParseOutput().
reExamineMemoryLine()
static wxRegEx reExamineMemoryLine (wxT("[ \(0x[0-9a-f]+)[ \.+>:[ \(.+)")) static
Referenced by GdbCmd_ExamineMemory::ParseOutput().
reGenericHexAddress()
static wxRegEx reGenericHexAddress (_T("(0x[A-Fa-f0-9]+)")) static
Referenced by GdbCmd_AddDataBreakpoint::ParseOutput(), and GdbCmd_FindTooltipAddress::ParseOutput().
reHWBreakpoint()
static wxRegEx reHWBreakpoint (_T("Hardware assisted breakpoint ([0-9]+) at (0x[0-9A-Fa-f]+)")) static
Referenced by GdbCmd_AddBreakpoint::ParseOutput().
reInfoProgramProcess()
static wxRegEx reInfoProgramProcess (_T("child process ([0-9]+)")) static
Referenced by GdbCmd_InfoProgram::ParseOutput().
reInfoProgramThread()
static wxRegEx reInfoProgramThread (_T("\WP[ \[0-9]+)\)) static
Referenced by GdbCmd_InfoProgram::ParseOutput().
reInfoThreads()
static wxRegEx reInfoThreads (_T("(\)[ \([0-9]+)[ \.*)")) static
Referenced by GdbCmd_Threads::ParseOutput().
reNextI()
static wxRegEx reNextI (_T("\\(([a-zA-Z]:)?.*?):([0-9]*):([0-9]*):(middle|beg):(.*)") , wxRE_ADVANCED) static
rePendingBreakpoint()
static wxRegEx rePendingBreakpoint (_T("Breakpoint ([0-9]+)[ \+):([0-9]+)(\ \nding\) static
Referenced by GdbCmd_AddBreakpoint::ParseOutput().
reRegisters()
static wxRegEx reRegisters (_T("([A-z0-9]+)[ \(0x[0-9A-Fa-f]+)[ \(.*)")) static
Referenced by GdbCmd_InfoRegisters::ParseOutput().
reStepI()
static wxRegEx reStepI (wxT("(((.*)[a-zA-Z]:)?.*)?:(\):(middle|beg):(.*)") , wxRE_ADVANCED) static
Referenced by GdbCmd_StepOrNextInstruction::ParseOutput().
reStepI2()
static wxRegEx reStepI2 (_T("\0x[A-Fa-f0-9]+)\(\)\in (.*)") , wxRE_ADVANCED) static
Referenced by GdbCmd_StepOrNextInstruction::ParseOutput().
reStepI3()
static wxRegEx reStepI3 (_T("^(0x[A-Fa-f0-9]+) in (.*)? from (.*)")) static
Referenced by GdbCmd_StepOrNextInstruction::ParseOutput().
reStepI4()
static wxRegEx reStepI4 (_T("^(0x[A-Fa-f0-9]+) in (.*)? at (.*)")) static
Referenced by GdbCmd_StepOrNextInstruction::ParseOutput().
reTemporaryBreakpoint()
static wxRegEx reTemporaryBreakpoint (wxT("^[Tt]emporary[ \reakpoint[ \[0-9]+)[ \t.*")) static
Referenced by GdbCmd_AddBreakpoint::ParseOutput().