Code::Blocks: gdb_driver.cpp File Reference
gdb_driver.cpp File Reference
#include <sdk.h>
#include "gdb_driver.h"
#include "gdb_commands.h"
#include "debuggeroptionsdlg.h"
#include "debuggerstate.h"
#include <cbdebugger_interfaces.h>
#include <manager.h>
#include <macrosmanager.h>
#include <configmanager.h>
#include <scriptingmanager.h>
#include <globals.h>
#include <infowindow.h>
#include "wx/msw/wrapwin.h"
#include <wx/arrimpl.cpp>
Macros
#define GDB_PROMPT _T("cb_gdb:")
#define FULL_GDB_PROMPT _T(">>>>>>") GDB_PROMPT
Enumerations
enum { BUFSIZE = 64 }
Functions
WX_DEFINE_OBJARRAY (TypesArray)
static wxRegEx reThreadSwitch (_T("^\Switching to thread .*\#0[ \+(0x[A-Fa-f0-9]+) in (.*) from (.*)"))
static wxRegEx reThreadSwitch2 (_T("^\Switching to thread .*\#0[ \+(0x[A-Fa-f0-9]+) in (.*) from (.*):([0-9]+)"))
static wxRegEx reBreak (_T("\2*([A-Za-z]*[:]*)([^:]+):([0-9]+):[0-9]+:[begmidl]+:(0x[0-9A-Fa-f]+)"))
static wxRegEx reBreak2 (_T("^(0x[A-Fa-f0-9]+) in (.*) from (.*)"))
static wxRegEx reBreak3 (_T("^(0x[A-Fa-f0-9]+) in (.*)"))
static wxRegEx reCatchThrow (_T("^Catchpoint ([0-9]+) \exception thrown\, (0x[0-9a-f]+) in (.+) from (.+)$"))
static wxRegEx reCatchThrowNoFile (_T("^Catchpoint ([0-9]+) \exception thrown\, (0x[0-9a-f]+) in (.+)$"))
static wxRegEx rePendingFound (_T("^Pending[ \+breakpoint[ \+[\+([A-Za-z]:)([^:]+):([0-9]+)\*"))
static wxRegEx rePendingFound1 (_T("^Breakpoint[ \+([0-9]+),.*"))
static wxRegEx reTempBreakFound (wxT("^[Tt]emporary[ \breakpoint[ \([0-9]+),.*"))
static wxRegEx reChildPid1 (_T("Thread[ \+[xA-Fa-f0-9-]+[ \+\LWP ([0-9]+)\]"))
static wxRegEx reChildPid2 (_T("\New [tT]hread[ \+[0-9]+\[xA-Fa-f0-9-]+\"))
static wxRegEx reAttachedChildPid (wxT("Attaching to process ([0-9]+)"))
static wxRegEx reInferiorExited (wxT("^\Inferior[ \].+[ \]exited normally\$"), wxRE_EXTENDED)
static wxRegEx reInferiorExitedWithCode (wxT("^\[Ii]nferior[ \].+[ \]exited[ \]with[ \]code[ \]([0-9]+)\$"), wxRE_EXTENDED)
DECLARE_INSTANCE_TYPE (GDB_driver)
Macro Definition Documentation
FULL_GDB_PROMPT
#define FULL_GDB_PROMPT _T(">>>>>>") GDB_PROMPT
Definition at line 37 of file gdb_driver.cpp.
Referenced by GDB_driver::Prepare().
GDB_PROMPT
#define GDB_PROMPT _T("cb_gdb:")
Definition at line 36 of file gdb_driver.cpp.
Referenced by GDB_driver::ParseOutput().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BUFSIZE
Definition at line 361 of file gdb_driver.cpp.
Function Documentation
DECLARE_INSTANCE_TYPE()
DECLARE_INSTANCE_TYPE (GDB_driver)
reAttachedChildPid()
static wxRegEx reAttachedChildPid (wxT("Attaching to process ([0-9]+)")) static
reBreak()
static wxRegEx reBreak (_T("\*([A-Za-z]*[:]*)([^:]+):([0-9]+):[0-9]+:[begmidl]+:(0x[0-9A-Fa-f]+)")) static
Referenced by GDB_driver::AsmFlavour(), and GDB_driver::ParseOutput().
reBreak2()
static wxRegEx reBreak2 (_T("^(0x[A-Fa-f0-9]+) in (.*) from (.*)")) static
Referenced by GDB_driver::ParseOutput().
reBreak3()
static wxRegEx reBreak3 (_T("^(0x[A-Fa-f0-9]+) in (.*)")) static
Referenced by GDB_driver::ParseOutput().
reCatchThrow()
static wxRegEx reCatchThrow (_T("^Catchpoint ([0-9]+) \xception thrown\ (0x[0-9a-f]+) in (.+) from (.+)$")) static
Referenced by GDB_driver::ParseOutput().
reCatchThrowNoFile()
static wxRegEx reCatchThrowNoFile (_T("^Catchpoint ([0-9]+) \xception thrown\ (0x[0-9a-f]+) in (.+)$")) static
Referenced by GDB_driver::ParseOutput().
reChildPid1()
static wxRegEx reChildPid1 (_T("Thread[ \[xA-Fa-f0-9-]+[ \\WP ([0-9]+)\")) static
Referenced by GDB_driver::ParseOutput().
reChildPid2()
static wxRegEx reChildPid2 (_T("\ew [tT]hread[ \[0-9]+\xA-Fa-f0-9-]+\)) static
Referenced by GDB_driver::ParseOutput().
reInferiorExited()
static wxRegEx reInferiorExited (wxT("^\nferior[ \.+[ \exited normally\") , wxRE_EXTENDED) static
Referenced by GDB_driver::ParseOutput().
reInferiorExitedWithCode()
static wxRegEx reInferiorExitedWithCode (wxT("^\Ii]nferior[ \.+[ \exited[ \with[ \code[ \([0-9]+)\") , wxRE_EXTENDED) static
Referenced by GDB_driver::ParseOutput().
rePendingFound()
static wxRegEx rePendingFound (_T("^Pending[ \breakpoint[ \[\([A-Za-z]:)([^:]+):([0-9]+)\")) static
Referenced by GDB_driver::ParseOutput().
rePendingFound1()
static wxRegEx rePendingFound1 (_T("^Breakpoint[ \([0-9]+),.*")) static
Referenced by GDB_driver::ParseOutput().
reTempBreakFound()
static wxRegEx reTempBreakFound (wxT("^[Tt]emporary[ \reakpoint[ \[0-9]+),.*")) static
Referenced by GDB_driver::ParseOutput().
reThreadSwitch()
static wxRegEx reThreadSwitch (_T("^\witching to thread .*\0[ \(0x[A-Fa-f0-9]+) in (.*) from (.*)")) static
Referenced by GDB_driver::ParseOutput().
reThreadSwitch2()
static wxRegEx reThreadSwitch2 (_T("^\witching to thread .*\0[ \(0x[A-Fa-f0-9]+) in (.*) from (.*):([0-9]+)")) static
Referenced by GDB_driver::ParseOutput().
WX_DEFINE_OBJARRAY()
WX_DEFINE_OBJARRAY (TypesArray)