Code::Blocks: incremental_select_helper.cpp File Reference
incremental_select_helper.cpp File Reference
#include "sdk_precomp.h"
#include "incremental_select_helper.h"
Typedefs
typedef int wxStandardID
Functions
void FilterItemsFinalize (wxListCtrl &list, IncrementalSelectIterator &iterator)
static wxStandardID KeyDownAction (wxKeyEvent &event, int &selected, int selectedMax)
Variables
const long ID_TEXTCTRL1 = wxNewId()
const long ID_RESULT_LIST = wxNewId()
Typedef Documentation
wxStandardID
typedef int wxStandardID
Definition at line 199 of file incremental_select_helper.cpp.
Function Documentation
FilterItemsFinalize()
void FilterItemsFinalize (wxListCtrl & list, IncrementalSelectIterator & iterator)
Definition at line 103 of file incremental_select_helper.cpp.
References wxListCtrl::GetColumnCount(), IncrementalSelectIterator::GetColumnWidth(), IncrementalSelectIterator::GetFilteredCount(), wxListCtrl::SetColumnWidth(), wxListCtrl::SetItemCount(), wxListCtrl::SetItemState(), and wxLIST_STATE_SELECTED.
Referenced by IncrementalSelectHandler::FilterItems().
KeyDownAction()
static wxStandardID KeyDownAction (wxKeyEvent & event, int & selected, int selectedMax) static
Definition at line 202 of file incremental_select_helper.cpp.
References wxKeyEvent::GetKeyCode(), wxGetKeyState(), wxID_CANCEL, wxID_LOWEST, wxID_OK, WXK_CONTROL, WXK_DOWN, WXK_END, WXK_ESCAPE, WXK_HOME, WXK_NUMPAD_DOWN, WXK_NUMPAD_ENTER, WXK_NUMPAD_PAGEDOWN, WXK_NUMPAD_PAGEUP, WXK_NUMPAD_UP, WXK_PAGEDOWN, WXK_PAGEUP, WXK_RETURN, and WXK_UP.
Referenced by IncrementalSelectHandler::OnKeyDown().
Variable Documentation
ID_RESULT_LIST
const long ID_RESULT_LIST = wxNewId()
Definition at line 357 of file incremental_select_helper.cpp.
Referenced by IncrementalSelectDialog::BuildContent().
ID_TEXTCTRL1
const long ID_TEXTCTRL1 = wxNewId()
Definition at line 356 of file incremental_select_helper.cpp.
Referenced by IncrementalSelectDialog::BuildContent(), BuildTargetPanel::BuildTargetPanel(), CCDebugInfo::CCDebugInfo(), CompilerPanel::CompilerPanel(), FilePathPanel::FilePathPanel(), GenericSelectPath::GenericSelectPath(), ProjectPathPanel::ProjectPathPanel(), and ScriptConsole::ScriptConsole().