Code::Blocks: infowindow.cpp File Reference
infowindow.cpp File Reference
#include "sdk_precomp.h"
#include <wx/intl.h>
#include <wx/stattext.h>
#include <wx/sizer.h>
#include <wx/settings.h>
#include <wx/statbmp.h>
#include <wx/panel.h>
#include <wx/frame.h>
#include "infowindow.h"
#include "manager.h"
#include <limits>
#include <wx/display.h>
Classes
class ForwardingTextControl
Functions
const wxColour titleBackground (96, 96, 96)
const wxColour textBackground (255, 255, 160)
const wxColour textForeground (0, 0, 0)
Variables
const char * iBitmap []
Function Documentation
const wxColour textBackground (255 , 255 , 160)
Referenced by InfoWindow::InfoWindow().
const wxColour textForeground (0 , 0 , 0)
Referenced by InfoWindow::InfoWindow().
const wxColour titleBackground (96 , 96 , 96)
Referenced by InfoWindow::InfoWindow().
Variable Documentation
const char* iBitmap[]
Referenced by InfoWindow::InfoWindow().