Code::Blocks: ipc.cpp File Reference
ipc.cpp File Reference
#include "ipc.h"
#include "main.h"
#include <wx/tokenzr.h>
Functions
const wxString g_failed_shm (_T("Failed creating shared memory initialising IPC (error 0x00000d04)."))
const wxString g_failed_sem (_T("Failed creating semaphore/mutex initialising IPC (error 0x007f0002)."))
Function Documentation
g_failed_sem()
const wxString g_failed_sem (_T("Failed creating semaphore/mutex initialising IPC (error 0x007f0002)."))
Referenced by SharedMemory::SharedMemory().
g_failed_shm()
const wxString g_failed_shm (_T("Failed creating shared memory initialising IPC (error 0x00000d04)."))
Referenced by IPC::Entry(), and SharedMemory::SharedMemory().