Code::Blocks: loggers.cpp File Reference
loggers.cpp File Reference
#include "sdk_precomp.h"
#include <wx/clipbrd.h>
#include <wx/dataobj.h>
#include <wx/wupdlock.h>
#include "loggers.h"
#include "cbcolourmanager.h"
Typedefs
typedef const char * wxStringSucks
Functions
wxColour BlendTextColour (wxColour col)
Typedef Documentation
wxStringSucks
typedef const char* wxStringSucks
Definition at line 472 of file loggers.cpp.
Function Documentation
BlendTextColour()
wxColour BlendTextColour (wxColour col)
Definition at line 29 of file loggers.cpp.
References wxColour::Blue(), wxSystemSettings::GetColour(), wxColour::Green(), wxColour::Red(), wxSYS_COLOUR_WINDOW, and wxSYS_COLOUR_WINDOWTEXT.
Referenced by CSS::CSS().