Code::Blocks: logmanager.h File Reference
logmanager.h File Reference
#include "manager.h"
#include "logger.h"
#include <map>
Classes
struct LogSlot
class LogManager
struct LogManager::InstantiatorBase
struct LogManager::Instantiator< type, requires_filename >
Functions
wxString F (const wxChar *msg,...)
sprintf-like function
wxString F (const wxString &msg,...)
Function Documentation
F() [1/2]
wxString F (const wxChar * msg, ...) inline
sprintf-like function
Warning
NOT thread safe within a single compilation unit due to use of static temp_string.
Definition at line 20 of file logmanager.h.
References _T, and wxString::FormatV().
Referenced by cbProject::AddBuildTarget(), NativeParser::AddIncludeDirsToParser(), ClassBrowserBuilderThread::AddMembersOf(), ClassBrowserBuilderThread::AddNodes(), CompilerGCC::AddOutputLine(), ProjectManager::AddProjectDependency(), NativeParser::AddProjectToParser(), Wiz::AddWizard(), NativeParser::AI(), DirectCommands::AreExternalDepsOutdated(), CompilerGDC::AutoDetectInstallationDir(), NativeParserBase::BreakUpComponents(), ProjectManagerUI::BuildProjectTree(), CompilerGCC::BuildStateManagement(), ClassBrowserBuilderThread::BuildTree(), cbProject::CalculateCommonTopLevelPath(), CompilerGCC::CalculateProjectDependencies(), EditorHooks::CallHooks(), cbEditorInternalData::cbEditorInternalData(), Compiler::Compiler(), CompilerFactory::CreateCompilerCopy(), NativeParser::CreateParser(), cbProject::DefineVirtualBuildTarget(), NativeParser::DeleteParser(), EncodingDetector::DetectEncoding(), DirectCommands::DirectCommands(), DebuggerGDB::DoBreak(), CCManager::DoBufferedCC(), CompilerGCC::DoCleanWithMake(), CodeCompletion::DoCodeComplete(), CodeCompletion::DoCodeCompletePreprocessor(), NativeParser::DoFullParsing(), ProjectLoader::DoUnits(), CompilerGCC::DoWorkspaceBuild(), EnvironmentSettingsDlg::EnvironmentSettingsDlg(), ToolsManager::Execute(), PluginManager::ExecutePlugin(), ExpandBackticks(), ClassBrowserBuilderThread::ExpandItem(), ClassBrowserBuilderThread::ExpandNamespaces(), NativeParserBase::FindAIMatches(), NativeParser::FindCurrentFunctionStart(), CfgMgrBldr::Flush(), CompilerCommandGenerator::GenerateCommandLine(), Wiz::GenerateFile(), NativeParserBase::GenerateResultSet(), CompileTargetBase::GenerateTargetFilename(), NativeParser::GetAllPathsByFilename(), DirectCommands::GetCompileFileCommand(), CompileTargetBase::GetDynamicLibDefFilename(), CompileTargetBase::GetDynamicLibFilename(), CompileTargetBase::GetDynamicLibImportFilename(), CompileTargetBase::GetStaticLibFilename(), Tokenizer::HandleUndefs(), AnnoyingDialog::Init(), CompilerGCC::KillProcess(), cbWorkspace::Load(), EditorColourSet::LoadAvailableSets(), ScriptingManager::LoadBuffer(), WorkspaceLoader::LoadLayout(), cbWorkspace::LoadLayout(), PluginManager::LoadPlugin(), CompilerFactory::LoadSettings(), ToolsManager::LoadTools(), TemplateManager::LoadUserTemplates(), Compiler::MakeInvalidCompilerMessages(), NativeParser::MarkItemsByAI(), ConfigManager::MigrateFolders(), TemplateManager::NewProjectFromUserTemplate(), cbEditorPrintout::OnBeginDocument(), AnnoyingDialog::OnButton(), WizPage::OnButton(), CompilerGCC::OnCleanFile(), CompilerGCC::OnCompileFileRequest(), CCManager::OnCompleteCode(), CodeCompletion::OnGotoFunction(), MainFrame::OnHelpPluginMenu(), CodeBlocksApp::OnInit(), NativeParser::OnParserEnd(), NativeParser::OnParserStart(), MainFrame::OnPluginLoaded(), MainFrame::OnPluginsExecuteMenu(), cbEditorPrintout::OnPrintPage(), ProjectFileOptionsDlg::OnReadOnlyCheck(), ProjectManagerUI::OnRemoveFileFromProject(), CodeCompletion::OnReparsingTimer(), ToolsManager::OnToolTerminated(), ProjectLayoutLoader::Open(), ProjectLoader::Open(), cbEditor::Open(), EditorManager::OpenContainingFolder(), OpenContainingFolderData::OpenContainingFolderData(), NativeParser::ParseBufferForUsingNamespace(), NativeParser::ParseFunctionArguments(), CodeCompletion::ParseFunctionsAndFillToolbar(), NativeParser::ParseLocalBlock(), CompilerGCC::PreprocessJob(), Manager::ProcessEvent(), ParserThread::ReadClsNames(), ParserThread::ReadVarNames(), ScriptingManager::RegisterScriptMenu(), CompilerFactory::RemoveCompiler(), CCTreeCtrl::RemoveDoubles(), NativeParser::RemoveObsoleteParsers(), ProjectManager::RemoveProjectDependency(), ProjectManager::RemoveProjectFromAllDependencies(), NativeParser::RemoveProjectFromParser(), cbProject::ReOrderTargets(), EncodingDetector::Report(), NativeParserBase::ResolveExpression(), CompilerGCC::Run(), cbDebuggerPlugin::RunNixConsole(), Wiz::RunProjectWizard(), CompilerGCC::RunSingleFile(), MainFrame::RunStartupScripts(), cbWorkspace::Save(), CompilerGCC::SaveBuildLog(), cbWorkspace::SaveLayout(), TemplateManager::SaveUserTemplate(), PluginManager::ScanForPlugins(), ClassBrowserBuilderThread::SelectItem(), CompilerGCC::SetupEnvironment(), CompilerCommandGenerator::SetupOutputFilenames(), NativeParser::SwitchParser(), cbDebuggerPlugin::SwitchToDebuggingLayout(), cbDebuggerPlugin::SwitchToPreviousLayout(), ProjectFileOptionsDlg::ToggleFileReadOnly(), and DirectCommands::~DirectCommands().
F() [2/2]
wxString F (const wxString & msg, ...) inline
Definition at line 37 of file logmanager.h.
References _T, wxString::FormatV(), and wxString::Replace().