Code::Blocks: macrosmanager.cpp File Reference
macrosmanager.cpp File Reference
#include "sdk_precomp.h"
#include <wx/menu.h>
#include "cbworkspace.h"
#include "projectmanager.h"
#include "editormanager.h"
#include "logmanager.h"
#include "macrosmanager.h"
#include "scriptingmanager.h"
#include "manager.h"
#include "cbproject.h"
#include "cbeditor.h"
#include "uservarmanager.h"
#include "configmanager.h"
#include "globals.h"
#include "compilerfactory.h"
#include "compiler.h"
#include <wx/stdpaths.h>
#include <cstdlib>
#include "scripting/sqplus/sqplus.h"
#include "scripting/bindings/scriptbindings.h"
#include "cbstyledtextctrl.h"
Functions
static const wxString const_COIN (_T("COIN"))
static const wxString const_RANDOM (_T("RANDOM"))
static const wxString toNativePath (_T("$TO_NATIVE_PATH{"))
static const wxString toUnixPath (_T("$TO_UNIX_PATH{"))
static const wxString toWindowsPath (_T("$TO_WINDOWS_PATH{"))
wxString GetSelectedText ()
Function Documentation
static const wxString const_COIN (_T("COIN")) static
Referenced by MacrosManager::ReplaceMacros().
static const wxString const_RANDOM (_T("RANDOM")) static
Referenced by MacrosManager::ReplaceMacros().
wxString GetSelectedText ()
References Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), wxScintilla::GetSelectedText(), wxScintilla::GetTextRange(), wxScintilla::WordEndPosition(), and wxScintilla::WordStartPosition().
Referenced by MacrosManager::RecalcVars().
static const wxString toNativePath (_T("$TO_NATIVE_PATH{")) static
Referenced by MacrosManager::ReplaceMacros().
static const wxString toUnixPath (_T("$TO_UNIX_PATH{")) static
Referenced by MacrosManager::ReplaceMacros().
static const wxString toWindowsPath (_T("$TO_WINDOWS_PATH{")) static
Referenced by MacrosManager::ReplaceMacros().