Code::Blocks: main.cpp File Reference
main.cpp File Reference
#include <sdk.h>
#include "app.h"
#include "appglobals.h"
#include "batchbuild.h"
#include "cbauibook.h"
#include "cbstyledtextctrl.h"
#include "compilersettingsdlg.h"
#include "debuggersettingsdlg.h"
#include "dlgabout.h"
#include "dlgaboutplugin.h"
#include "environmentsettingsdlg.h"
#include "infopane.h"
#include "infowindow.h"
#include "main.h"
#include "notebookstyles.h"
#include "printdlg.h"
#include "scriptconsole.h"
#include "scriptingsettingsdlg.h"
#include "startherepage.h"
#include "switcherdlg.h"
#include "cbstatusbar.h"
#include "loggers.h"
#include <wx/display.h>
#include <wx/dnd.h>
#include <wx/fileconf.h>
#include <wx/filename.h>
#include <wx/gdicmn.h>
#include <wx/printdlg.h>
#include <wx/sstream.h>
#include <wx/tipdlg.h>
#include <wx/tokenzr.h>
#include <wx/xrc/xmlres.h>
#include <annoyingdialog.h>
#include <cbexception.h>
#include <cbplugin.h>
#include <cbproject.h>
#include <cbworkspace.h>
#include <ccmanager.h>
#include <configmanager.h>
#include <debuggermanager.h>
#include <editorcolourset.h>
#include <editormanager.h>
#include <filefilters.h>
#include <globals.h>
#include <logmanager.h>
#include <personalitymanager.h>
#include <pluginmanager.h>
#include <projectmanager.h>
#include <scriptingmanager.h>
#include <sdk_events.h>
#include <templatemanager.h>
#include <toolsmanager.h>
#include <uservarmanager.h>
#include "debugger_interface_creator.h"
#include "debuggermenu.h"
#include "cbcolourmanager.h"
#include "editorconfigurationdlg.h"
#include "projectmanagerui.h"
Classes
class cbFileDropTarget
Enumerations
enum {
wxID_CBFILE01 = 5060, wxID_CBFILE02, wxID_CBFILE03, wxID_CBFILE04,
wxID_CBFILE05, wxID_CBFILE06, wxID_CBFILE07, wxID_CBFILE08,
wxID_CBFILE09, wxID_CBFILE10, wxID_CBFILE11, wxID_CBFILE12,
wxID_CBFILE13, wxID_CBFILE14, wxID_CBFILE15, wxID_CBFILE16,
wxID_CBFILE17, wxID_CBFILE18, wxID_CBFILE19, wxID_CBFILE20,
wxID_CBFILE21, wxID_CBFILE22, wxID_CBFILE23, wxID_CBFILE24,
wxID_CBFILE25, wxID_CBFILE26, wxID_CBFILE27, wxID_CBFILE28,
wxID_CBFILE29, wxID_CBFILE30, wxID_CBFILE31, wxID_CBFILE32
}
Functions
DECLARE_INSTANCE_TYPE (MainFrame)
void InitToolbar (wxToolBar *tb)
static void InsertNewLine (bool below)
Variables
static const wxString gDefaultLayout = _T("Code::Blocks default")
static wxString gDefaultLayoutData
static wxString gDefaultMessagePaneLayoutData
static const wxString gMinimalLayout = _T("Code::Blocks minimal")
static wxString gMinimalLayoutData
static wxString gMinimalMessagePaneLayoutData
int idToolNew = XRCID("idToolNew")
int idFileNew = XRCID("idFileNew")
int idFileNewEmpty = XRCID("idFileNewEmpty")
int idFileNewProject = XRCID("idFileNewProject")
int idFileNewTarget = XRCID("idFileNewTarget")
int idFileNewFile = XRCID("idFileNewFile")
int idFileNewCustom = XRCID("idFileNewCustom")
int idFileNewUser = XRCID("idFileNewUser")
int idFileOpen = XRCID("idFileOpen")
int idFileReopen = XRCID("idFileReopen")
int idFileOpenRecentFileClearHistory = XRCID("idFileOpenRecentFileClearHistory")
int idFileOpenRecentProjectClearHistory = XRCID("idFileOpenRecentProjectClearHistory")
int idFileImportProjectDevCpp = XRCID("idFileImportProjectDevCpp")
int idFileImportProjectMSVC = XRCID("idFileImportProjectMSVC")
int idFileImportProjectMSVCWksp = XRCID("idFileImportProjectMSVCWksp")
int idFileImportProjectMSVS = XRCID("idFileImportProjectMSVS")
int idFileImportProjectMSVSWksp = XRCID("idFileImportProjectMSVSWksp")
int idFileSave = XRCID("idFileSave")
int idFileSaveAs = XRCID("idFileSaveAs")
int idFileSaveAllFiles = XRCID("idFileSaveAllFiles")
int idFileSaveProject = XRCID("idFileSaveProject")
int idFileSaveProjectAs = XRCID("idFileSaveProjectAs")
int idFileSaveProjectAllProjects = XRCID("idFileSaveProjectAllProjects")
int idFileSaveProjectTemplate = XRCID("idFileSaveProjectTemplate")
int idFileOpenDefWorkspace = XRCID("idFileOpenDefWorkspace")
int idFileSaveWorkspace = XRCID("idFileSaveWorkspace")
int idFileSaveWorkspaceAs = XRCID("idFileSaveWorkspaceAs")
int idFileSaveAll = XRCID("idFileSaveAll")
int idFileCloseWorkspace = XRCID("idFileCloseWorkspace")
int idFileClose = XRCID("idFileClose")
int idFileCloseAll = XRCID("idFileCloseAll")
int idFileCloseProject = XRCID("idFileCloseProject")
int idFileCloseAllProjects = XRCID("idFileCloseAllProjects")
int idFilePrintSetup = XRCID("idFilePrintSetup")
int idFilePrint = XRCID("idFilePrint")
int idFileExit = XRCID("idFileExit")
int idEditUndo = XRCID("idEditUndo")
int idEditRedo = XRCID("idEditRedo")
int idEditClearHistory = XRCID("idEditClearHistory")
int idEditCopy = XRCID("idEditCopy")
int idEditCut = XRCID("idEditCut")
int idEditPaste = XRCID("idEditPaste")
int idEditSwapHeaderSource = XRCID("idEditSwapHeaderSource")
int idEditGotoMatchingBrace = XRCID("idEditGotoMatchingBrace")
int idEditHighlightMode = XRCID("idEditHighlightMode")
int idEditHighlightModeText = XRCID("idEditHighlightModeText")
int idEditBookmarks = XRCID("idEditBookmarks")
int idEditBookmarksToggle = XRCID("idEditBookmarksToggle")
int idEditBookmarksPrevious = XRCID("idEditBookmarksPrevious")
int idEditBookmarksNext = XRCID("idEditBookmarksNext")
int idEditBookmarksClearAll = XRCID("idEditBookmarksClearAll")
int idEditFolding = XRCID("idEditFolding")
int idEditFoldAll = XRCID("idEditFoldAll")
int idEditUnfoldAll = XRCID("idEditUnfoldAll")
int idEditToggleAllFolds = XRCID("idEditToggleAllFolds")
int idEditFoldBlock = XRCID("idEditFoldBlock")
int idEditUnfoldBlock = XRCID("idEditUnfoldBlock")
int idEditToggleFoldBlock = XRCID("idEditToggleFoldBlock")
int idEditEOLMode = XRCID("idEditEOLMode")
int idEditEOLCRLF = XRCID("idEditEOLCRLF")
int idEditEOLCR = XRCID("idEditEOLCR")
int idEditEOLLF = XRCID("idEditEOLLF")
int idEditEncoding = XRCID("idEditEncoding")
int idEditEncodingDefault = XRCID("idEditEncodingDefault")
int idEditEncodingUseBom = XRCID("idEditEncodingUseBom")
int idEditEncodingAscii = XRCID("idEditEncodingAscii")
int idEditEncodingUtf7 = XRCID("idEditEncodingUtf7")
int idEditEncodingUtf8 = XRCID("idEditEncodingUtf8")
int idEditEncodingUnicode = XRCID("idEditEncodingUnicode")
int idEditEncodingUtf16 = XRCID("idEditEncodingUtf16")
int idEditEncodingUtf32 = XRCID("idEditEncodingUtf32")
int idEditEncodingUnicode16BE = XRCID("idEditEncodingUnicode16BE")
int idEditEncodingUnicode16LE = XRCID("idEditEncodingUnicode16LE")
int idEditEncodingUnicode32BE = XRCID("idEditEncodingUnicode32BE")
int idEditEncodingUnicode32LE = XRCID("idEditEncodingUnicode32LE")
int idEditSpecialCommands = XRCID("idEditSpecialCommands")
int idEditSpecialCommandsMovement = XRCID("idEditSpecialCommandsMovement")
int idEditParaUp = XRCID("idEditParaUp")
int idEditParaUpExtend = XRCID("idEditParaUpExtend")
int idEditParaDown = XRCID("idEditParaDown")
int idEditParaDownExtend = XRCID("idEditParaDownExtend")
int idEditWordPartLeft = XRCID("idEditWordPartLeft")
int idEditWordPartLeftExtend = XRCID("idEditWordPartLeftExtend")
int idEditWordPartRight = XRCID("idEditWordPartRight")
int idEditWordPartRightExtend = XRCID("idEditWordPartRightExtend")
int idEditSpecialCommandsZoom = XRCID("idEditSpecialCommandsZoom")
int idEditZoomIn = XRCID("idEditZoomIn")
int idEditZoomOut = XRCID("idEditZoomOut")
int idEditZoomReset = XRCID("idEditZoomReset")
int idEditSpecialCommandsLine = XRCID("idEditSpecialCommandsLine")
int idEditLineCut = XRCID("idEditLineCut")
int idEditLineDelete = XRCID("idEditLineDelete")
int idEditLineDuplicate = XRCID("idEditLineDuplicate")
int idEditLineTranspose = XRCID("idEditLineTranspose")
int idEditLineCopy = XRCID("idEditLineCopy")
int idEditLinePaste = XRCID("idEditLinePaste")
int idEditLineUp = XRCID("idEditLineUp")
int idEditLineDown = XRCID("idEditLineDown")
int idEditSpecialCommandsCase = XRCID("idEditSpecialCommandsCase")
int idEditUpperCase = XRCID("idEditUpperCase")
int idEditLowerCase = XRCID("idEditLowerCase")
int idEditSpecialCommandsOther = XRCID("idEditSpecialCommandsOther")
int idEditInsertNewLine = XRCID("idEditInsertNewLine")
int idEditGotoLineEnd = XRCID("idEditGotoLineEnd")
int idEditInsertNewLineBelow = XRCID("idEditInsertNewLineBelow")
int idEditInsertNewLineAbove = XRCID("idEditInsertNewLineAbove")
int idEditSelectAll = XRCID("idEditSelectAll")
int idEditSelectNext = XRCID("idEditSelectNext")
int idEditSelectNextSkip = XRCID("idEditSelectNextSkip")
int idEditCommentSelected = XRCID("idEditCommentSelected")
int idEditUncommentSelected = XRCID("idEditUncommentSelected")
int idEditToggleCommentSelected = XRCID("idEditToggleCommentSelected")
int idEditStreamCommentSelected = XRCID("idEditStreamCommentSelected")
int idEditBoxCommentSelected = XRCID("idEditBoxCommentSelected")
int idEditShowCallTip = XRCID("idEditShowCallTip")
int idEditCompleteCode = wxNewId()
int idViewLayoutDelete = XRCID("idViewLayoutDelete")
int idViewLayoutSave = XRCID("idViewLayoutSave")
int idViewToolbars = XRCID("idViewToolbars")
int idViewToolFit = XRCID("idViewToolFit")
int idViewToolOptimize = XRCID("idViewToolOptimize")
int idViewToolMain = XRCID("idViewToolMain")
int idViewToolDebugger = XRCID("idViewToolDebugger")
int idViewManager = XRCID("idViewManager")
int idViewLogManager = XRCID("idViewLogManager")
int idViewStartPage = XRCID("idViewStartPage")
int idViewStatusbar = XRCID("idViewStatusbar")
int idViewScriptConsole = XRCID("idViewScriptConsole")
int idViewHideEditorTabs = XRCID("idViewHideEditorTabs")
int idViewFocusEditor = XRCID("idViewFocusEditor")
int idViewFocusManagement = XRCID("idViewFocusManagement")
int idViewFocusLogsAndOthers = XRCID("idViewFocusLogsAndOthers")
int idViewSwitchTabs = XRCID("idViewSwitchTabs")
int idViewFullScreen = XRCID("idViewFullScreen")
int idSearchFind = XRCID("idSearchFind")
int idSearchFindInFiles = XRCID("idSearchFindInFiles")
int idSearchFindNext = XRCID("idSearchFindNext")
int idSearchFindPrevious = XRCID("idSearchFindPrevious")
int idSearchFindSelectedNext = XRCID("idSearchFindSelectedNext")
int idSearchFindSelectedPrevious = XRCID("idSearchFindSelectedPrevious")
int idSearchReplace = XRCID("idSearchReplace")
int idSearchReplaceInFiles = XRCID("idSearchReplaceInFiles")
int idSearchGotoLine = XRCID("idSearchGotoLine")
int idSearchGotoNextChanged = XRCID("idSearchGotoNextChanged")
int idSearchGotoPreviousChanged = XRCID("idSearchGotoPreviousChanged")
int idSettingsEnvironment = XRCID("idSettingsEnvironment")
int idSettingsGlobalUserVars = XRCID("idSettingsGlobalUserVars")
int idSettingsEditor = XRCID("idSettingsEditor")
int idSettingsCompiler = XRCID("idSettingsCompiler")
int idSettingsDebugger = XRCID("idSettingsDebugger")
int idPluginsManagePlugins = XRCID("idPluginsManagePlugins")
int idSettingsScripting = XRCID("idSettingsScripting")
int idHelpTips = XRCID("idHelpTips")
int idHelpPlugins = XRCID("idHelpPlugins")
int idLeftSash = XRCID("idLeftSash")
int idBottomSash = XRCID("idBottomSash")
int idCloseFullScreen = XRCID("idCloseFullScreen")
int idFileNext = wxNewId()
int idFilePrev = wxNewId()
int idShiftTab = wxNewId()
int idCtrlAltTab = wxNewId()
int idStartHerePageLink = wxNewId()
int idHighlightButton = wxNewId()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
wxID_CBFILE01
wxID_CBFILE02
wxID_CBFILE03
wxID_CBFILE04
wxID_CBFILE05
wxID_CBFILE06
wxID_CBFILE07
wxID_CBFILE08
wxID_CBFILE09
wxID_CBFILE10
wxID_CBFILE11
wxID_CBFILE12
wxID_CBFILE13
wxID_CBFILE14
wxID_CBFILE15
wxID_CBFILE16
wxID_CBFILE17
wxID_CBFILE18
wxID_CBFILE19
wxID_CBFILE20
wxID_CBFILE21
wxID_CBFILE22
wxID_CBFILE23
wxID_CBFILE24
wxID_CBFILE25
wxID_CBFILE26
wxID_CBFILE27
wxID_CBFILE28
wxID_CBFILE29
wxID_CBFILE30
wxID_CBFILE31
wxID_CBFILE32
Definition at line 101 of file main.cpp.
Function Documentation
DECLARE_INSTANCE_TYPE()
DECLARE_INSTANCE_TYPE (MainFrame)
Referenced by MainFrame::SetupDebuggerUI().
InitToolbar()
void InitToolbar (wxToolBar * tb) inline
Definition at line 1618 of file main.cpp.
Referenced by MainFrame::DoAddPluginToolbar().
InsertNewLine()
static void InsertNewLine (bool below) static
Definition at line 3151 of file main.cpp.
References wxScintilla::AutoCompActive(), wxScintilla::AutoCompCancel(), wxScintilla::BeginUndoAction(), wxScintilla::EndUndoAction(), Manager::Get(), EditorManager::GetBuiltinActiveEditor(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), Manager::GetEditorManager(), wxScintilla::GetEOLMode(), GetEOLStr(), wxScintilla::HomeDisplay(), wxScintilla::InsertText(), wxScintilla::LineDown(), and wxScintilla::LineEndDisplay().
Referenced by MainFrame::OnEditInsertNewLineAbove(), and MainFrame::OnEditInsertNewLineBelow().
Variable Documentation
gDefaultLayout
const wxString gDefaultLayout = _T("Code::Blocks default") static
Definition at line 87 of file main.cpp.
Referenced by MainFrame::LoadViewLayout(), MainFrame::OnLayoutQuery(), and MainFrame::OnViewLayoutDelete().
gDefaultLayoutData
wxString gDefaultLayoutData static
Definition at line 88 of file main.cpp.
Referenced by MainFrame::OnViewLayoutDelete().
gDefaultMessagePaneLayoutData
wxString gDefaultMessagePaneLayoutData static
Definition at line 89 of file main.cpp.
Referenced by MainFrame::OnViewLayoutDelete().
gMinimalLayout
const wxString gMinimalLayout = _T("Code::Blocks minimal") static
Definition at line 91 of file main.cpp.
Referenced by MainFrame::OnViewLayoutDelete().
gMinimalLayoutData
wxString gMinimalLayoutData static
Definition at line 92 of file main.cpp.
Referenced by MainFrame::OnViewLayoutDelete().
gMinimalMessagePaneLayoutData
wxString gMinimalMessagePaneLayoutData static
Definition at line 93 of file main.cpp.
Referenced by MainFrame::OnViewLayoutDelete().
idBottomSash
int idBottomSash = XRCID("idBottomSash")
Definition at line 298 of file main.cpp.
idCloseFullScreen
int idCloseFullScreen = XRCID("idCloseFullScreen")
Definition at line 299 of file main.cpp.
Referenced by MainFrame::CreateIDE().
idCtrlAltTab
int idCtrlAltTab = wxNewId()
Definition at line 304 of file main.cpp.
Referenced by MainFrame::MainFrame().
idEditBookmarks
int idEditBookmarks = XRCID("idEditBookmarks")
Definition at line 184 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditBookmarksClearAll
int idEditBookmarksClearAll = XRCID("idEditBookmarksClearAll")
Definition at line 188 of file main.cpp.
idEditBookmarksNext
int idEditBookmarksNext = XRCID("idEditBookmarksNext")
Definition at line 187 of file main.cpp.
idEditBookmarksPrevious
int idEditBookmarksPrevious = XRCID("idEditBookmarksPrevious")
Definition at line 186 of file main.cpp.
idEditBookmarksToggle
int idEditBookmarksToggle = XRCID("idEditBookmarksToggle")
Definition at line 185 of file main.cpp.
idEditBoxCommentSelected
int idEditBoxCommentSelected = XRCID("idEditBoxCommentSelected")
Definition at line 251 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditClearHistory
int idEditClearHistory = XRCID("idEditClearHistory")
Definition at line 176 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditCommentSelected
int idEditCommentSelected = XRCID("idEditCommentSelected")
Definition at line 247 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditCompleteCode
int idEditCompleteCode = wxNewId()
Definition at line 253 of file main.cpp.
Referenced by MainFrame::CreateMenubar(), and MainFrame::OnEditMenuUpdateUI().
idEditCopy
int idEditCopy = XRCID("idEditCopy")
Definition at line 177 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditCut
int idEditCut = XRCID("idEditCut")
Definition at line 178 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditEncoding
int idEditEncoding = XRCID("idEditEncoding")
Definition at line 200 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditEncodingAscii
int idEditEncodingAscii = XRCID("idEditEncodingAscii")
Definition at line 203 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingDefault
int idEditEncodingDefault = XRCID("idEditEncodingDefault")
Definition at line 201 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUnicode
int idEditEncodingUnicode = XRCID("idEditEncodingUnicode")
Definition at line 206 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUnicode16BE
int idEditEncodingUnicode16BE = XRCID("idEditEncodingUnicode16BE")
Definition at line 209 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUnicode16LE
int idEditEncodingUnicode16LE = XRCID("idEditEncodingUnicode16LE")
Definition at line 210 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUnicode32BE
int idEditEncodingUnicode32BE = XRCID("idEditEncodingUnicode32BE")
Definition at line 211 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUnicode32LE
int idEditEncodingUnicode32LE = XRCID("idEditEncodingUnicode32LE")
Definition at line 212 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUseBom
int idEditEncodingUseBom = XRCID("idEditEncodingUseBom")
Definition at line 202 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUtf16
int idEditEncodingUtf16 = XRCID("idEditEncodingUtf16")
Definition at line 207 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUtf32
int idEditEncodingUtf32 = XRCID("idEditEncodingUtf32")
Definition at line 208 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUtf7
int idEditEncodingUtf7 = XRCID("idEditEncodingUtf7")
Definition at line 204 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEncodingUtf8
int idEditEncodingUtf8 = XRCID("idEditEncodingUtf8")
Definition at line 205 of file main.cpp.
Referenced by MainFrame::OnEditEncoding(), and MainFrame::OnEditMenuUpdateUI().
idEditEOLCR
int idEditEOLCR = XRCID("idEditEOLCR")
Definition at line 198 of file main.cpp.
Referenced by MainFrame::OnEditEOLMode(), and MainFrame::OnEditMenuUpdateUI().
idEditEOLCRLF
int idEditEOLCRLF = XRCID("idEditEOLCRLF")
Definition at line 197 of file main.cpp.
Referenced by MainFrame::OnEditEOLMode(), and MainFrame::OnEditMenuUpdateUI().
idEditEOLLF
int idEditEOLLF = XRCID("idEditEOLLF")
Definition at line 199 of file main.cpp.
Referenced by MainFrame::OnEditEOLMode(), and MainFrame::OnEditMenuUpdateUI().
idEditEOLMode
int idEditEOLMode = XRCID("idEditEOLMode")
Definition at line 196 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditFoldAll
int idEditFoldAll = XRCID("idEditFoldAll")
Definition at line 190 of file main.cpp.
idEditFoldBlock
int idEditFoldBlock = XRCID("idEditFoldBlock")
Definition at line 193 of file main.cpp.
idEditFolding
int idEditFolding = XRCID("idEditFolding")
Definition at line 189 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditGotoLineEnd
int idEditGotoLineEnd = XRCID("idEditGotoLineEnd")
Definition at line 241 of file main.cpp.
idEditGotoMatchingBrace
int idEditGotoMatchingBrace = XRCID("idEditGotoMatchingBrace")
Definition at line 181 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditHighlightMode
int idEditHighlightMode = XRCID("idEditHighlightMode")
Definition at line 182 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditHighlightModeText
int idEditHighlightModeText = XRCID("idEditHighlightModeText")
Definition at line 183 of file main.cpp.
Referenced by MainFrame::CreateMenubar(), MainFrame::OnEditHighlightMode(), MainFrame::OnEditMenuUpdateUI(), and MainFrame::OnHighlightMenu().
idEditInsertNewLine
int idEditInsertNewLine = XRCID("idEditInsertNewLine")
Definition at line 240 of file main.cpp.
idEditInsertNewLineAbove
int idEditInsertNewLineAbove = XRCID("idEditInsertNewLineAbove")
Definition at line 243 of file main.cpp.
idEditInsertNewLineBelow
int idEditInsertNewLineBelow = XRCID("idEditInsertNewLineBelow")
Definition at line 242 of file main.cpp.
idEditLineCopy
int idEditLineCopy = XRCID("idEditLineCopy")
Definition at line 232 of file main.cpp.
idEditLineCut
int idEditLineCut = XRCID("idEditLineCut")
Definition at line 228 of file main.cpp.
idEditLineDelete
int idEditLineDelete = XRCID("idEditLineDelete")
Definition at line 229 of file main.cpp.
idEditLineDown
int idEditLineDown = XRCID("idEditLineDown")
Definition at line 235 of file main.cpp.
idEditLineDuplicate
int idEditLineDuplicate = XRCID("idEditLineDuplicate")
Definition at line 230 of file main.cpp.
idEditLinePaste
int idEditLinePaste = XRCID("idEditLinePaste")
Definition at line 233 of file main.cpp.
idEditLineTranspose
int idEditLineTranspose = XRCID("idEditLineTranspose")
Definition at line 231 of file main.cpp.
idEditLineUp
int idEditLineUp = XRCID("idEditLineUp")
Definition at line 234 of file main.cpp.
Referenced by MainFrame::OnEditLineMove().
idEditLowerCase
int idEditLowerCase = XRCID("idEditLowerCase")
Definition at line 238 of file main.cpp.
idEditParaDown
int idEditParaDown = XRCID("idEditParaDown")
Definition at line 217 of file main.cpp.
idEditParaDownExtend
int idEditParaDownExtend = XRCID("idEditParaDownExtend")
Definition at line 218 of file main.cpp.
idEditParaUp
int idEditParaUp = XRCID("idEditParaUp")
Definition at line 215 of file main.cpp.
idEditParaUpExtend
int idEditParaUpExtend = XRCID("idEditParaUpExtend")
Definition at line 216 of file main.cpp.
idEditPaste
int idEditPaste = XRCID("idEditPaste")
Definition at line 179 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditRedo
int idEditRedo = XRCID("idEditRedo")
Definition at line 175 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditSelectAll
int idEditSelectAll = XRCID("idEditSelectAll")
Definition at line 244 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditSelectNext
int idEditSelectNext = XRCID("idEditSelectNext")
Definition at line 245 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditSelectNextSkip
int idEditSelectNextSkip = XRCID("idEditSelectNextSkip")
Definition at line 246 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditShowCallTip
int idEditShowCallTip = XRCID("idEditShowCallTip")
Definition at line 252 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditSpecialCommands
int idEditSpecialCommands = XRCID("idEditSpecialCommands")
Definition at line 213 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditSpecialCommandsCase
int idEditSpecialCommandsCase = XRCID("idEditSpecialCommandsCase")
Definition at line 236 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditSpecialCommandsLine
int idEditSpecialCommandsLine = XRCID("idEditSpecialCommandsLine")
Definition at line 227 of file main.cpp.
idEditSpecialCommandsMovement
int idEditSpecialCommandsMovement = XRCID("idEditSpecialCommandsMovement")
Definition at line 214 of file main.cpp.
idEditSpecialCommandsOther
int idEditSpecialCommandsOther = XRCID("idEditSpecialCommandsOther")
Definition at line 239 of file main.cpp.
idEditSpecialCommandsZoom
int idEditSpecialCommandsZoom = XRCID("idEditSpecialCommandsZoom")
Definition at line 223 of file main.cpp.
idEditStreamCommentSelected
int idEditStreamCommentSelected = XRCID("idEditStreamCommentSelected")
Definition at line 250 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditSwapHeaderSource
int idEditSwapHeaderSource = XRCID("idEditSwapHeaderSource")
Definition at line 180 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditToggleAllFolds
int idEditToggleAllFolds = XRCID("idEditToggleAllFolds")
Definition at line 192 of file main.cpp.
idEditToggleCommentSelected
int idEditToggleCommentSelected = XRCID("idEditToggleCommentSelected")
Definition at line 249 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditToggleFoldBlock
int idEditToggleFoldBlock = XRCID("idEditToggleFoldBlock")
Definition at line 195 of file main.cpp.
idEditUncommentSelected
int idEditUncommentSelected = XRCID("idEditUncommentSelected")
Definition at line 248 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditUndo
int idEditUndo = XRCID("idEditUndo")
Definition at line 174 of file main.cpp.
Referenced by MainFrame::OnEditMenuUpdateUI().
idEditUnfoldAll
int idEditUnfoldAll = XRCID("idEditUnfoldAll")
Definition at line 191 of file main.cpp.
idEditUnfoldBlock
int idEditUnfoldBlock = XRCID("idEditUnfoldBlock")
Definition at line 194 of file main.cpp.
idEditUpperCase
int idEditUpperCase = XRCID("idEditUpperCase")
Definition at line 237 of file main.cpp.
idEditWordPartLeft
int idEditWordPartLeft = XRCID("idEditWordPartLeft")
Definition at line 219 of file main.cpp.
idEditWordPartLeftExtend
int idEditWordPartLeftExtend = XRCID("idEditWordPartLeftExtend")
Definition at line 220 of file main.cpp.
idEditWordPartRight
int idEditWordPartRight = XRCID("idEditWordPartRight")
Definition at line 221 of file main.cpp.
idEditWordPartRightExtend
int idEditWordPartRightExtend = XRCID("idEditWordPartRightExtend")
Definition at line 222 of file main.cpp.
idEditZoomIn
int idEditZoomIn = XRCID("idEditZoomIn")
Definition at line 224 of file main.cpp.
idEditZoomOut
int idEditZoomOut = XRCID("idEditZoomOut")
Definition at line 225 of file main.cpp.
idEditZoomReset
int idEditZoomReset = XRCID("idEditZoomReset")
Definition at line 226 of file main.cpp.
idFileClose
int idFileClose = XRCID("idFileClose")
Definition at line 166 of file main.cpp.
Referenced by MainFrame::MainFrame(), and MainFrame::OnFileMenuUpdateUI().
idFileCloseAll
int idFileCloseAll = XRCID("idFileCloseAll")
Definition at line 167 of file main.cpp.
Referenced by MainFrame::MainFrame(), and MainFrame::OnFileMenuUpdateUI().
idFileCloseAllProjects
int idFileCloseAllProjects = XRCID("idFileCloseAllProjects")
Definition at line 169 of file main.cpp.
Referenced by MainFrame::OnProjectMenuUpdateUI().
idFileCloseProject
int idFileCloseProject = XRCID("idFileCloseProject")
Definition at line 168 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI(), and MainFrame::OnProjectMenuUpdateUI().
idFileCloseWorkspace
int idFileCloseWorkspace = XRCID("idFileCloseWorkspace")
Definition at line 165 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileExit
int idFileExit = XRCID("idFileExit")
Definition at line 172 of file main.cpp.
idFileImportProjectDevCpp
int idFileImportProjectDevCpp = XRCID("idFileImportProjectDevCpp")
Definition at line 149 of file main.cpp.
idFileImportProjectMSVC
int idFileImportProjectMSVC = XRCID("idFileImportProjectMSVC")
Definition at line 150 of file main.cpp.
idFileImportProjectMSVCWksp
int idFileImportProjectMSVCWksp = XRCID("idFileImportProjectMSVCWksp")
Definition at line 151 of file main.cpp.
idFileImportProjectMSVS
int idFileImportProjectMSVS = XRCID("idFileImportProjectMSVS")
Definition at line 152 of file main.cpp.
idFileImportProjectMSVSWksp
int idFileImportProjectMSVSWksp = XRCID("idFileImportProjectMSVSWksp")
Definition at line 153 of file main.cpp.
idFileNew
int idFileNew = XRCID("idFileNew")
Definition at line 138 of file main.cpp.
idFileNewCustom
int idFileNewCustom = XRCID("idFileNewCustom")
Definition at line 143 of file main.cpp.
Referenced by MainFrame::OnFileNewWhat().
idFileNewEmpty
int idFileNewEmpty = XRCID("idFileNewEmpty")
Definition at line 139 of file main.cpp.
Referenced by MainFrame::OnFileNewWhat().
idFileNewFile
int idFileNewFile = XRCID("idFileNewFile")
Definition at line 142 of file main.cpp.
Referenced by MainFrame::OnFileNewWhat().
idFileNewProject
int idFileNewProject = XRCID("idFileNewProject")
Definition at line 140 of file main.cpp.
Referenced by MainFrame::OnFileNew(), MainFrame::OnFileNewWhat(), and MainFrame::OnStartHereLink().
idFileNewTarget
int idFileNewTarget = XRCID("idFileNewTarget")
Definition at line 141 of file main.cpp.
Referenced by MainFrame::OnFileNewWhat().
idFileNewUser
int idFileNewUser = XRCID("idFileNewUser")
Definition at line 144 of file main.cpp.
Referenced by MainFrame::OnFileNewWhat().
idFileNext
int idFileNext = wxNewId()
Definition at line 301 of file main.cpp.
Referenced by MainFrame::MainFrame().
idFileOpen
int idFileOpen = XRCID("idFileOpen")
Definition at line 145 of file main.cpp.
idFileOpenDefWorkspace
int idFileOpenDefWorkspace = XRCID("idFileOpenDefWorkspace")
Definition at line 161 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileOpenRecentFileClearHistory
int idFileOpenRecentFileClearHistory = XRCID("idFileOpenRecentFileClearHistory")
Definition at line 147 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileOpenRecentProjectClearHistory
int idFileOpenRecentProjectClearHistory = XRCID("idFileOpenRecentProjectClearHistory")
Definition at line 148 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFilePrev
int idFilePrev = wxNewId()
Definition at line 302 of file main.cpp.
Referenced by MainFrame::MainFrame().
idFilePrint
int idFilePrint = XRCID("idFilePrint")
Definition at line 171 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFilePrintSetup
int idFilePrintSetup = XRCID("idFilePrintSetup")
Definition at line 170 of file main.cpp.
idFileReopen
int idFileReopen = XRCID("idFileReopen")
Definition at line 146 of file main.cpp.
idFileSave
int idFileSave = XRCID("idFileSave")
Definition at line 154 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileSaveAll
int idFileSaveAll = XRCID("idFileSaveAll")
Definition at line 164 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileSaveAllFiles
int idFileSaveAllFiles = XRCID("idFileSaveAllFiles")
Definition at line 156 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileSaveAs
int idFileSaveAs = XRCID("idFileSaveAs")
Definition at line 155 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileSaveProject
int idFileSaveProject = XRCID("idFileSaveProject")
Definition at line 157 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI(), and MainFrame::OnProjectMenuUpdateUI().
idFileSaveProjectAllProjects
int idFileSaveProjectAllProjects = XRCID("idFileSaveProjectAllProjects")
Definition at line 159 of file main.cpp.
Referenced by MainFrame::OnProjectMenuUpdateUI().
idFileSaveProjectAs
int idFileSaveProjectAs = XRCID("idFileSaveProjectAs")
Definition at line 158 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI(), and MainFrame::OnProjectMenuUpdateUI().
idFileSaveProjectTemplate
int idFileSaveProjectTemplate = XRCID("idFileSaveProjectTemplate")
Definition at line 160 of file main.cpp.
Referenced by MainFrame::OnProjectMenuUpdateUI().
idFileSaveWorkspace
int idFileSaveWorkspace = XRCID("idFileSaveWorkspace")
Definition at line 162 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idFileSaveWorkspaceAs
int idFileSaveWorkspaceAs = XRCID("idFileSaveWorkspaceAs")
Definition at line 163 of file main.cpp.
Referenced by MainFrame::OnFileMenuUpdateUI().
idHelpPlugins
int idHelpPlugins = XRCID("idHelpPlugins")
Definition at line 295 of file main.cpp.
Referenced by MainFrame::CreateMenubar().
idHelpTips
int idHelpTips = XRCID("idHelpTips")
Definition at line 294 of file main.cpp.
idHighlightButton
int idHighlightButton = wxNewId()
Definition at line 306 of file main.cpp.
Referenced by MainFrame::DoCreateStatusBar().
idLeftSash
int idLeftSash = XRCID("idLeftSash")
Definition at line 297 of file main.cpp.
idPluginsManagePlugins
int idPluginsManagePlugins = XRCID("idPluginsManagePlugins")
Definition at line 291 of file main.cpp.
idSearchFind
int idSearchFind = XRCID("idSearchFind")
Definition at line 274 of file main.cpp.
Referenced by MainFrame::OnSearchMenuUpdateUI().
idSearchFindInFiles
int idSearchFindInFiles = XRCID("idSearchFindInFiles")
Definition at line 275 of file main.cpp.
Referenced by MainFrame::OnSearchFind().
idSearchFindNext
int idSearchFindNext = XRCID("idSearchFindNext")
Definition at line 276 of file main.cpp.
Referenced by MainFrame::OnSearchMenuUpdateUI().
idSearchFindPrevious
int idSearchFindPrevious = XRCID("idSearchFindPrevious")
Definition at line 277 of file main.cpp.
Referenced by MainFrame::OnSearchFindNext(), and MainFrame::OnSearchMenuUpdateUI().
idSearchFindSelectedNext
int idSearchFindSelectedNext = XRCID("idSearchFindSelectedNext")
Definition at line 278 of file main.cpp.
Referenced by MainFrame::OnSearchMenuUpdateUI().
idSearchFindSelectedPrevious
int idSearchFindSelectedPrevious = XRCID("idSearchFindSelectedPrevious")
Definition at line 279 of file main.cpp.
Referenced by MainFrame::OnSearchFindNextSelected(), and MainFrame::OnSearchMenuUpdateUI().
idSearchGotoLine
int idSearchGotoLine = XRCID("idSearchGotoLine")
Definition at line 282 of file main.cpp.
Referenced by MainFrame::OnSearchMenuUpdateUI().
idSearchGotoNextChanged
int idSearchGotoNextChanged = XRCID("idSearchGotoNextChanged")
Definition at line 283 of file main.cpp.
Referenced by MainFrame::OnSearchMenuUpdateUI().
idSearchGotoPreviousChanged
int idSearchGotoPreviousChanged = XRCID("idSearchGotoPreviousChanged")
Definition at line 284 of file main.cpp.
Referenced by MainFrame::OnSearchMenuUpdateUI().
idSearchReplace
int idSearchReplace = XRCID("idSearchReplace")
Definition at line 280 of file main.cpp.
Referenced by MainFrame::OnSearchMenuUpdateUI().
idSearchReplaceInFiles
int idSearchReplaceInFiles = XRCID("idSearchReplaceInFiles")
Definition at line 281 of file main.cpp.
Referenced by MainFrame::OnSearchReplace().
idSettingsCompiler
int idSettingsCompiler = XRCID("idSettingsCompiler")
Definition at line 289 of file main.cpp.
idSettingsDebugger
int idSettingsDebugger = XRCID("idSettingsDebugger")
Definition at line 290 of file main.cpp.
idSettingsEditor
int idSettingsEditor = XRCID("idSettingsEditor")
Definition at line 288 of file main.cpp.
idSettingsEnvironment
int idSettingsEnvironment = XRCID("idSettingsEnvironment")
Definition at line 286 of file main.cpp.
idSettingsGlobalUserVars
int idSettingsGlobalUserVars = XRCID("idSettingsGlobalUserVars")
Definition at line 287 of file main.cpp.
idSettingsScripting
int idSettingsScripting = XRCID("idSettingsScripting")
Definition at line 292 of file main.cpp.
idShiftTab
int idShiftTab = wxNewId()
Definition at line 303 of file main.cpp.
Referenced by MainFrame::MainFrame().
idStartHerePageLink
int idStartHerePageLink = wxNewId()
Definition at line 305 of file main.cpp.
Referenced by StartHerePage::LinkClicked().
idToolNew
int idToolNew = XRCID("idToolNew")
Definition at line 137 of file main.cpp.
idViewFocusEditor
int idViewFocusEditor = XRCID("idViewFocusEditor")
Definition at line 268 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewFocusLogsAndOthers
int idViewFocusLogsAndOthers = XRCID("idViewFocusLogsAndOthers")
Definition at line 270 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewFocusManagement
int idViewFocusManagement = XRCID("idViewFocusManagement")
Definition at line 269 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewFullScreen
int idViewFullScreen = XRCID("idViewFullScreen")
Definition at line 272 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewHideEditorTabs
int idViewHideEditorTabs = XRCID("idViewHideEditorTabs")
Definition at line 267 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewLayoutDelete
int idViewLayoutDelete = XRCID("idViewLayoutDelete")
Definition at line 255 of file main.cpp.
idViewLayoutSave
int idViewLayoutSave = XRCID("idViewLayoutSave")
Definition at line 256 of file main.cpp.
Referenced by MainFrame::DoSelectLayout(), MainFrame::OnViewLayoutDelete(), and MainFrame::SaveViewLayout().
idViewLogManager
int idViewLogManager = XRCID("idViewLogManager")
Definition at line 263 of file main.cpp.
Referenced by MainFrame::OnToggleBar(), and MainFrame::OnViewMenuUpdateUI().
idViewManager
int idViewManager = XRCID("idViewManager")
Definition at line 262 of file main.cpp.
Referenced by MainFrame::OnToggleBar(), and MainFrame::OnViewMenuUpdateUI().
idViewScriptConsole
int idViewScriptConsole = XRCID("idViewScriptConsole")
Definition at line 266 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewStartPage
int idViewStartPage = XRCID("idViewStartPage")
Definition at line 264 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewStatusbar
int idViewStatusbar = XRCID("idViewStatusbar")
Definition at line 265 of file main.cpp.
Referenced by MainFrame::OnViewMenuUpdateUI().
idViewSwitchTabs
int idViewSwitchTabs = XRCID("idViewSwitchTabs")
Definition at line 271 of file main.cpp.
Referenced by MainFrame::CreateMenubar().
idViewToolbars
int idViewToolbars = XRCID("idViewToolbars")
Definition at line 257 of file main.cpp.
idViewToolDebugger
int idViewToolDebugger = XRCID("idViewToolDebugger")
Definition at line 261 of file main.cpp.
Referenced by MainFrame::OnToggleBar(), and MainFrame::SetChecksForViewToolbarsMenu().
idViewToolFit
int idViewToolFit = XRCID("idViewToolFit")
Definition at line 258 of file main.cpp.
idViewToolMain
int idViewToolMain = XRCID("idViewToolMain")
Definition at line 260 of file main.cpp.
Referenced by MainFrame::DoAddPluginToolbar(), MainFrame::OnToggleBar(), MainFrame::OnViewMenuUpdateUI(), MainFrame::PluginsUpdated(), and MainFrame::SetChecksForViewToolbarsMenu().
idViewToolOptimize
int idViewToolOptimize = XRCID("idViewToolOptimize")
Definition at line 259 of file main.cpp.