Code::Blocks: TokenizerConsts Namespace Reference
TokenizerConsts Namespace Reference
Functions
const wxString colon (_T(":"))
const wxString colon_colon (_T("::"))
const wxString equal (_T("="))
const wxString kw_if (_T("if"))
const wxString kw_ifdef (_T("ifdef"))
const wxString kw_ifndef (_T("ifndef"))
const wxString kw_elif (_T("elif"))
const wxString kw_elifdef (_T("elifdef"))
const wxString kw_elifndef (_T("elifndef"))
const wxString kw_else (_T("else"))
const wxString kw_endif (_T("endif"))
const wxString hash (_T("#"))
const wxString tabcrlf (_T("\\))
const wxString kw_define (_T("define"))
const wxString kw_undef (_T("undef"))
Function Documentation
colon()
const wxString TokenizerConsts::colon (_T(":"))
Referenced by Tokenizer::Lex().
colon_colon()
const wxString TokenizerConsts::colon_colon (_T("::"))
Referenced by Tokenizer::Lex().
equal()
const wxString TokenizerConsts::equal (_T("="))
Referenced by Tokenizer::Lex().
hash()
const wxString TokenizerConsts::hash (_T("#"))
kw_define()
const wxString TokenizerConsts::kw_define (_T("define"))
Referenced by Tokenizer::GetPreprocessorType().
kw_elif()
const wxString TokenizerConsts::kw_elif (_T("elif"))
Referenced by Tokenizer::GetPreprocessorType().
kw_elifdef()
const wxString TokenizerConsts::kw_elifdef (_T("elifdef"))
Referenced by Tokenizer::GetPreprocessorType().
kw_elifndef()
const wxString TokenizerConsts::kw_elifndef (_T("elifndef"))
Referenced by Tokenizer::GetPreprocessorType().
kw_else()
const wxString TokenizerConsts::kw_else (_T("else"))
Referenced by Tokenizer::GetPreprocessorType().
kw_endif()
const wxString TokenizerConsts::kw_endif (_T("endif"))
Referenced by Tokenizer::GetPreprocessorType().
kw_if()
const wxString TokenizerConsts::kw_if (_T("if"))
Referenced by Tokenizer::GetPreprocessorType().
kw_ifdef()
const wxString TokenizerConsts::kw_ifdef (_T("ifdef"))
Referenced by Tokenizer::GetPreprocessorType().
kw_ifndef()
const wxString TokenizerConsts::kw_ifndef (_T("ifndef"))
Referenced by Tokenizer::GetPreprocessorType().
kw_undef()
const wxString TokenizerConsts::kw_undef (_T("undef"))
Referenced by Tokenizer::GetPreprocessorType().
tabcrlf()
const wxString TokenizerConsts::tabcrlf (_T("\))