Code::Blocks: ExpressionConsts Namespace Reference
ExpressionConsts Namespace Reference
Functions
const wxString Plus (_T("+"))
const wxString Subtract (_T("-"))
const wxString Multiply (_T("*"))
const wxString Divide (_T("/"))
const wxString LParenthesis (_T("("))
const wxString RParenthesis (_T(")"))
const wxString Mod (_T("%"))
const wxString Power (_T("^"))
const wxString BitwiseAnd (_T("&"))
const wxString BitwiseOr (_T("|"))
const wxString And (_T("&&"))
const wxString Or (_T("||"))
const wxString Not (_T("!"))
const wxString Equal (_T("=="))
const wxString Unequal (_T("!="))
const wxString GT (_T(">"))
const wxString LT (_T("<"))
const wxString GTOrEqual (_T(">="))
const wxString LTOrEqual (_T("<="))
const wxString LShift (_T("<<"))
const wxString RShift (_T(">>"))
Function Documentation
And()
const wxString ExpressionConsts::And (_T("&&"))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().
BitwiseAnd()
const wxString ExpressionConsts::BitwiseAnd (_T("&"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
BitwiseOr()
const wxString ExpressionConsts::BitwiseOr (_T("|"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
Divide()
const wxString ExpressionConsts::Divide (_T("/"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
Equal()
const wxString ExpressionConsts::Equal (_T("=="))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().
GT()
const wxString ExpressionConsts::GT (_T(">"))
Referenced by MacrosManager::EvalCondition(), ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
GTOrEqual()
const wxString ExpressionConsts::GTOrEqual (_T(">="))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().
LParenthesis()
const wxString ExpressionConsts::LParenthesis ()
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
LShift()
const wxString ExpressionConsts::LShift (_T("<<"))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().
LT()
const wxString ExpressionConsts::LT (_T("<"))
Referenced by MacrosManager::EvalCondition(), ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
LTOrEqual()
const wxString ExpressionConsts::LTOrEqual (_T("<="))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().
Mod()
const wxString ExpressionConsts::Mod (_T("%"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
Multiply()
const wxString ExpressionConsts::Multiply (_T("*"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
Not()
const wxString ExpressionConsts::Not (_T("!"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
Or()
const wxString ExpressionConsts::Or (_T("||"))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().
Plus()
const wxString ExpressionConsts::Plus (_T("+"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
Power()
const wxString ExpressionConsts::Power (_T("^"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
RParenthesis()
const wxString ExpressionConsts::RParenthesis (_T(")")
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
RShift()
const wxString ExpressionConsts::RShift (_T(">>"))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().
Subtract()
const wxString ExpressionConsts::Subtract (_T("-"))
Referenced by ExpressionNode::GetNodeTypePriority(), and ExpressionNode::ParseNodeType().
Unequal()
const wxString ExpressionConsts::Unequal (_T("!="))
Referenced by ExpressionNode::GetNodeTypePriority(), ExpressionNode::IsBinaryOperator(), and ExpressionNode::ParseNodeType().