Code::Blocks: Wizard Namespace Reference
Wizard Namespace Reference
Functions
void FillCompilerControl (wxItemContainer *control, const wxString &compilerID, const wxString &validCompilerIDs)
Function Documentation
FillCompilerControl()
void Wizard::FillCompilerControl (wxItemContainer * control, const wxString & compilerID, const wxString & validCompilerIDs)
Definition at line 38 of file wizpage.cpp.
References CompilerFactory::CompilerInheritsFrom(), GetArrayFromString(), CompilerFactory::GetCompiler(), CompilerFactory::GetCompilersCount(), CompilerFactory::GetDefaultCompilerID(), Compiler::GetID(), and Compiler::GetName().
Referenced by Wiz::FillContainerWithCompilers(), WizBuildTargetPanel::WizBuildTargetPanel(), and WizCompilerPanel::WizCompilerPanel().