Code::Blocks: platform Namespace Reference
platform Namespace Reference
Enumerations
enum windows_version_t {
winver_NotWindows = 0, winver_UnknownWindows, winver_Windows9598ME, winver_WindowsNT2000,
winver_WindowsXP, winver_WindowsServer2003, winver_WindowsVista, winver_Windows7
}
Functions
DLLIMPORT windows_version_t WindowsVersion ()
bool move (wxString const &old_name, wxString const &new_name)
windows_version_t cb_get_os ()
Enumeration Type Documentation
windows_version_t
enum platform::windows_version_t
Enumerator
winver_NotWindows
winver_UnknownWindows
winver_Windows9598ME
winver_WindowsNT2000
winver_WindowsXP
winver_WindowsServer2003
winver_WindowsVista
winver_Windows7
Definition at line 391 of file globals.h.
Function Documentation
cb_get_os()
windows_version_t platform::cb_get_os ()
Definition at line 1275 of file globals.cpp.
References winver_NotWindows, winver_UnknownWindows, winver_Windows7, winver_Windows9598ME, winver_WindowsNT2000, winver_WindowsServer2003, winver_WindowsVista, and winver_WindowsXP.
Referenced by WindowsVersion().
move()
bool platform::move (wxString const & old_name, wxString const & new_name) inline
Definition at line 195 of file filemanager.cpp.
Referenced by FileManager::Load(), FileManager::Save(), and FileManager::SaveUTF8().
WindowsVersion()
windows_version_t platform::WindowsVersion ()
Definition at line 1316 of file globals.cpp.
References cb_get_os().
Referenced by Associations::DoClearAssociation(), Associations::DoSetAssociation(), ExpandBackticks(), and Manager::LoadToolBar().