Code::Blocks: HTMLTags Namespace Reference
HTMLTags Namespace Reference
Functions
static const wxString nbsp (_T("&nbsp;"))
Variables
static const wxString br = _T("<br>")
static const wxString sep = _T(" ")
static const wxString b1 = _T("<b>")
static const wxString b0 = _T("</b>")
static const wxString a1 = _T("<a>")
static const wxString a0 = _T("</a>")
static const wxString i1 = _T("<i>")
static const wxString i0 = _T("</i>")
static const wxString pre1 = _T("<pre>")
static const wxString pre0 = _T("</pre>")
static const wxString tab = nbsp + nbsp + nbsp
Function Documentation
nbsp()
static const wxString HTMLTags::nbsp (_T("&nbsp;")) static
Referenced by DocumentationHelper::GenerateHTML().
Variable Documentation
a0
const wxString HTMLTags::a0 = _T("</a>") static
Definition at line 394 of file doxygen_parser.cpp.
a1
const wxString HTMLTags::a1 = _T("<a>") static
Definition at line 393 of file doxygen_parser.cpp.
b0
const wxString HTMLTags::b0 = _T("</b>") static
Definition at line 391 of file doxygen_parser.cpp.
Referenced by DocumentationHelper::DoxygenToHTML(), and DocumentationHelper::GenerateHTML().
b1
const wxString HTMLTags::b1 = _T("<b>") static
Definition at line 390 of file doxygen_parser.cpp.
Referenced by ScriptBindings::cbProject_AddFile(), AnnoyingDialog::Init(), and AnnoyingDialog::~AnnoyingDialog().
br
const wxString HTMLTags::br = _T("<br>") static
Definition at line 388 of file doxygen_parser.cpp.
Referenced by DocumentationHelper::DoxygenToHTML(), and DocumentationHelper::GenerateHTML().
i0
const wxString HTMLTags::i0 = _T("</i>") static
Definition at line 397 of file doxygen_parser.cpp.
i1
const wxString HTMLTags::i1 = _T("<i>") static
Definition at line 396 of file doxygen_parser.cpp.
pre0
const wxString HTMLTags::pre0 = _T("</pre>") static
Definition at line 400 of file doxygen_parser.cpp.
Referenced by DocumentationHelper::DoxygenToHTML().
pre1
const wxString HTMLTags::pre1 = _T("<pre>") static
Definition at line 399 of file doxygen_parser.cpp.
Referenced by DocumentationHelper::DoxygenToHTML().
sep
const wxString HTMLTags::sep = _T(" ") static
Definition at line 389 of file doxygen_parser.cpp.
Referenced by CompilerGDC::AutoDetectInstallationDir(), CompilerGNUARM::AutoDetectInstallationDir(), CompilerMSVC::AutoDetectInstallationDir(), CompilerMSVC10::AutoDetectInstallationDir(), CompilerGNUFortran::AutoDetectInstallationDir(), CompilerMSVC8::AutoDetectInstallationDir(), CompilerG95::AutoDetectInstallationDir(), CompilerMINGW::AutoDetectInstallationDir(), CompilerICC::AutoDetectInstallationDir(), cbProject::CalculateCommonTopLevelPath(), cbDetectDebuggerExecutable(), cbFindFileInPATH(), cbTextInputStream::cbTextInputStream(), ProjectManagerUI::CheckForExternallyModifiedProjects(), DocumentationHelper::GenerateHTML(), Compiler::LoadSettings(), TemplateManager::NewProjectFromUserTemplate(), Wiz::OnAttach(), cbEditor::SaveAs(), CompilerMINGWGenerator::SetupIncludeDirs(), CompilerMINGW::SetVersionString(), and pfDetails::Update().
tab
const wxString HTMLTags::tab = nbsp + nbsp + nbsp static
Definition at line 403 of file doxygen_parser.cpp.
Referenced by DocumentationHelper::DoxygenToHTML(), and cbAuiNotebook::LoadPerspective().