Code::Blocks: CfgMgrConsts Namespace Reference
CfgMgrConsts Namespace Reference
Variables
const wxString app_path (_T("app_path"))
const wxString data_path (_T("data_path"))
const wxString dotDot (_T(".."))
const int version = 1
Variable Documentation
app_path
const wxString CfgMgrConsts::app_path(_T("app_path"))
Referenced by ConfigManager::Read(), and ConfigManager::Write().
data_path
const wxString CfgMgrConsts::data_path(_T("data_path"))
Referenced by ConfigManager::Read(), and ConfigManager::Write().
dotDot
const wxString CfgMgrConsts::dotDot(_T(".."))
Referenced by ConfigManager::AssertPath().
version
const int CfgMgrConsts::version = 1
Definition at line 80 of file configmanager.cpp.
Referenced by CompilerICC::AutoDetectInstallationDir(), CfgMgrBldr::CfgMgrBldr(), PluginManager::InstallPlugin(), WorkspaceLoader::LoadLayout(), Compiler::LoadSettings(), PluginsConfigurationDlg::OnExport(), ProjectLayoutLoader::Open(), ProjectLoader::Open(), PluginManager::ReadManifestFile(), and CfgMgrBldr::SwitchTo().