Code::Blocks: ScriptBindings Namespace Reference
ScriptBindings Namespace Reference
Namespaces
IOLib
ScriptPluginWrapper
Classes
struct IONamespace
class XrcDialog
Functions
void RegisterBindings ()
void Register_Constants ()
int ShowDialog (const wxString &xrc, const wxString &dlgName, const wxString &callback)
void EndModal (int retCode)
SQInteger XrcId (HSQUIRRELVM v)
void Register_Dialog ()
void gDebugLog (const wxString &msg)
void gErrorLog (const wxString &msg)
void gWarningLog (const wxString &msg)
void gLog (const wxString &msg)
int gMessage (const wxString &msg, const wxString &caption, int buttons)
void gShowMessage (const wxString &msg)
void gShowMessageWarn (const wxString &msg)
void gShowMessageError (const wxString &msg)
void gShowMessageInfo (const wxString &msg)
wxString gReplaceMacros (const wxString &buffer)
SQInteger IsNull (HSQUIRRELVM v)
ProjectManager * getPM ()
EditorManager * getEM ()
ConfigManager * getCM ()
CompilerFactory * getCF ()
UserVariableManager * getUVM ()
ScriptingManager * getSM ()
bool InstallPlugin (const wxString &pluginName, bool allUsers, bool confirm)
int ExecutePlugin (const wxString &pluginName)
int ConfigurePlugin (const wxString &pluginName)
void CallMenu (const wxString &menuPath)
void Include (const wxString &filename)
SQInteger Require (HSQUIRRELVM v)
SQInteger wx_GetColourFromUser (HSQUIRRELVM v)
long wx_GetNumberFromUser (const wxString &message, const wxString &prompt, const wxString &caption, long value)
wxString wx_GetPasswordFromUser (const wxString &message, const wxString &caption, const wxString &default_value)
wxString wx_GetTextFromUser (const wxString &message, const wxString &caption, const wxString &default_value)
long wxString_ToLong (wxString const &str)
void Register_Globals ()
void Register_IO ()
void Register_ScriptPlugin ()
void Register_ProgressDialog ()
SQInteger EditArrayFileDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
SQInteger EditArrayFileDlg_Ctor (HSQUIRRELVM v)
SQInteger EditArrayOrderDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
SQInteger EditArrayOrderDlg_Ctor (HSQUIRRELVM v)
SQInteger EditArrayStringDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
SQInteger EditArrayStringDlg_Ctor (HSQUIRRELVM v)
SQInteger EditPairDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
SQInteger EditPairDlg_Ctor (HSQUIRRELVM v)
SQInteger EditPathDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
SQInteger EditPathDlg_Ctor (HSQUIRRELVM v)
SQInteger GenericMultiLineNotesDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
SQInteger GenericMultiLineNotesDlg_Ctor (HSQUIRRELVM v)
SQInteger ShowModalForDialogs (HSQUIRRELVM v)
void Register_UtilDialogs ()
SQInteger wxArrayString_Index (HSQUIRRELVM v)
SQInteger wxArrayString_SetItem (HSQUIRRELVM v)
SQInteger wxColour_OpToString (HSQUIRRELVM v)
SQInteger wxFileName_OpToString (HSQUIRRELVM v)
SQInteger wxPoint_OpCmp (HSQUIRRELVM v)
SQInteger wxPoint_x (HSQUIRRELVM v)
SQInteger wxPoint_y (HSQUIRRELVM v)
wxString static_ (const SQChar *str)
wxString static_T (const SQChar *str)
SQInteger wxString_OpAdd (HSQUIRRELVM v)
SQInteger wxString_OpCmp (HSQUIRRELVM v)
SQInteger wxString_OpToString (HSQUIRRELVM v)
SQInteger wxString_AddChar (HSQUIRRELVM v)
SQInteger wxString_GetChar (HSQUIRRELVM v)
SQInteger wxString_Matches (HSQUIRRELVM v)
SQInteger wxString_AfterFirst (HSQUIRRELVM v)
SQInteger wxString_AfterLast (HSQUIRRELVM v)
SQInteger wxString_BeforeFirst (HSQUIRRELVM v)
SQInteger wxString_BeforeLast (HSQUIRRELVM v)
SQInteger wxString_Replace (HSQUIRRELVM v)
void Register_wxTypes ()
SQInteger ConfigManager_Read (HSQUIRRELVM v)
SQInteger ConfigManager_Write (HSQUIRRELVM v)
SQInteger EditorManager_GetBuiltinEditor (HSQUIRRELVM v)
SQInteger EditorManager_Open (HSQUIRRELVM v)
SQInteger EditorManager_Close (HSQUIRRELVM v)
SQInteger EditorManager_Save (HSQUIRRELVM v)
SQInteger cbProject_RemoveFile (HSQUIRRELVM v)
SQInteger cbProject_AddFile (HSQUIRRELVM v)
SQInteger cbProject_GetBuildTarget (HSQUIRRELVM v)
SQInteger cbProject_RenameBuildTarget (HSQUIRRELVM v)
SQInteger cbProject_DuplicateBuildTarget (HSQUIRRELVM v)
SQInteger cbProject_RemoveBuildTarget (HSQUIRRELVM v)
SQInteger cbProject_ExportTargetAsProject (HSQUIRRELVM v)
SQInteger ProjectManager_AddFileToProject (HSQUIRRELVM v)
SQInteger ProjectManager_GetProjectCount (HSQUIRRELVM v)
SQInteger ProjectManager_GetProject (HSQUIRRELVM v)
SQInteger ProjectManager_RebuildTree (HSQUIRRELVM v)
SQInteger cbEditor_SetText (HSQUIRRELVM v)
SQInteger cbEditor_GetText (HSQUIRRELVM v)
SQInteger CompilerFactory_GetCompilerIndex (HSQUIRRELVM v)
wxString CompilerFactory_GetCompilerIDByName (const wxString &name)
void gBuildLog (const wxString &msg)
Variables
wxString s_PathSep = wxFILE_SEP_PATH
XrcDialog * s_ActiveDialog = nullptr
const char * s_cbScriptPlugin
static int gBuildLogId = -1
Class Documentation
ScriptBindings::IONamespace
struct ScriptBindings::IONamespace
Definition at line 231 of file sc_io.cpp.
Function Documentation
CallMenu()
void ScriptBindings::CallMenu (const wxString & menuPath)
Definition at line 96 of file sc_globals.cpp.
References cbMessageBox(), Manager::Get(), and Manager::GetAppFrame().
Referenced by Register_Globals().
cbEditor_GetText()
SQInteger ScriptBindings::cbEditor_GetText (HSQUIRRELVM v)
Definition at line 353 of file scriptbindings.cpp.
References cbEditor::GetControl(), and wxScintilla::GetText().
Referenced by RegisterBindings().
cbEditor_SetText()
SQInteger ScriptBindings::cbEditor_SetText (HSQUIRRELVM v)
Definition at line 337 of file scriptbindings.cpp.
References cbEditor::GetControl(), and wxScintilla::SetText().
Referenced by RegisterBindings().
cbProject_AddFile()
SQInteger ScriptBindings::cbProject_AddFile (HSQUIRRELVM v)
Definition at line 171 of file scriptbindings.cpp.
References cbProject::AddFile(), and HTMLTags::b1.
Referenced by RegisterBindings().
cbProject_DuplicateBuildTarget()
SQInteger ScriptBindings::cbProject_DuplicateBuildTarget (HSQUIRRELVM v)
Definition at line 223 of file scriptbindings.cpp.
References cbProject::DuplicateBuildTarget().
Referenced by RegisterBindings().
cbProject_ExportTargetAsProject()
SQInteger ScriptBindings::cbProject_ExportTargetAsProject (HSQUIRRELVM v)
Definition at line 254 of file scriptbindings.cpp.
References cbProject::ExportTargetAsProject().
Referenced by RegisterBindings().
cbProject_GetBuildTarget()
SQInteger ScriptBindings::cbProject_GetBuildTarget (HSQUIRRELVM v)
Definition at line 192 of file scriptbindings.cpp.
References cbProject::GetBuildTarget().
Referenced by RegisterBindings().
cbProject_RemoveBuildTarget()
SQInteger ScriptBindings::cbProject_RemoveBuildTarget (HSQUIRRELVM v)
Definition at line 240 of file scriptbindings.cpp.
References cbProject::RemoveBuildTarget().
Referenced by RegisterBindings().
cbProject_RemoveFile()
SQInteger ScriptBindings::cbProject_RemoveFile (HSQUIRRELVM v)
Definition at line 157 of file scriptbindings.cpp.
References cbProject::RemoveFile().
Referenced by RegisterBindings().
cbProject_RenameBuildTarget()
SQInteger ScriptBindings::cbProject_RenameBuildTarget (HSQUIRRELVM v)
Definition at line 209 of file scriptbindings.cpp.
References cbProject::RenameBuildTarget().
Referenced by RegisterBindings().
CompilerFactory_GetCompilerIDByName()
wxString ScriptBindings::CompilerFactory_GetCompilerIDByName (const wxString & name)
Definition at line 378 of file scriptbindings.cpp.
References CompilerFactory::GetCompilerByName(), and Compiler::GetID().
Referenced by RegisterBindings().
CompilerFactory_GetCompilerIndex()
SQInteger ScriptBindings::CompilerFactory_GetCompilerIndex (HSQUIRRELVM v)
Definition at line 369 of file scriptbindings.cpp.
References CompilerFactory::GetCompilerIndex().
Referenced by RegisterBindings().
ConfigManager_Read()
SQInteger ScriptBindings::ConfigManager_Read (HSQUIRRELVM v)
Definition at line 41 of file scriptbindings.cpp.
References Manager::Get(), Manager::GetConfigManager(), ConfigManager::Read(), ConfigManager::ReadBool(), ConfigManager::ReadDouble(), and ConfigManager::ReadInt().
Referenced by RegisterBindings().
ConfigManager_Write()
SQInteger ScriptBindings::ConfigManager_Write (HSQUIRRELVM v)
Definition at line 63 of file scriptbindings.cpp.
References Manager::Get(), Manager::GetConfigManager(), and ConfigManager::Write().
Referenced by RegisterBindings().
ConfigurePlugin()
int ScriptBindings::ConfigurePlugin (const wxString & pluginName)
Definition at line 91 of file sc_globals.cpp.
Referenced by Register_Globals().
EditArrayFileDlg_Ctor()
SQInteger ScriptBindings::EditArrayFileDlg_Ctor (HSQUIRRELVM v)
Definition at line 36 of file sc_util_dialogs.cpp.
References EditArrayFileDlg_Dtor().
Referenced by Register_UtilDialogs().
EditArrayFileDlg_Dtor()
SQInteger ScriptBindings::EditArrayFileDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
Definition at line 31 of file sc_util_dialogs.cpp.
Referenced by EditArrayFileDlg_Ctor().
EditArrayOrderDlg_Ctor()
SQInteger ScriptBindings::EditArrayOrderDlg_Ctor (HSQUIRRELVM v)
Definition at line 74 of file sc_util_dialogs.cpp.
References EditArrayOrderDlg_Dtor().
Referenced by Register_UtilDialogs().
EditArrayOrderDlg_Dtor()
SQInteger ScriptBindings::EditArrayOrderDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
Definition at line 69 of file sc_util_dialogs.cpp.
Referenced by EditArrayOrderDlg_Ctor().
EditArrayStringDlg_Ctor()
SQInteger ScriptBindings::EditArrayStringDlg_Ctor (HSQUIRRELVM v)
Definition at line 95 of file sc_util_dialogs.cpp.
References EditArrayStringDlg_Dtor().
Referenced by Register_UtilDialogs().
EditArrayStringDlg_Dtor()
SQInteger ScriptBindings::EditArrayStringDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
Definition at line 90 of file sc_util_dialogs.cpp.
Referenced by EditArrayStringDlg_Ctor().
EditorManager_Close()
SQInteger ScriptBindings::EditorManager_Close (HSQUIRRELVM v)
Definition at line 131 of file scriptbindings.cpp.
References EditorManager::Close(), Manager::Get(), and Manager::GetEditorManager().
Referenced by RegisterBindings().
EditorManager_GetBuiltinEditor()
SQInteger ScriptBindings::EditorManager_GetBuiltinEditor (HSQUIRRELVM v)
Definition at line 103 of file scriptbindings.cpp.
References Manager::Get(), EditorManager::GetBuiltinEditor(), and Manager::GetEditorManager().
Referenced by RegisterBindings().
EditorManager_Open()
SQInteger ScriptBindings::EditorManager_Open (HSQUIRRELVM v)
Definition at line 119 of file scriptbindings.cpp.
References Manager::Get(), Manager::GetEditorManager(), and EditorManager::Open().
Referenced by RegisterBindings().
EditorManager_Save()
SQInteger ScriptBindings::EditorManager_Save (HSQUIRRELVM v)
Definition at line 144 of file scriptbindings.cpp.
References Manager::Get(), Manager::GetEditorManager(), and EditorManager::Save().
Referenced by RegisterBindings().
EditPairDlg_Ctor()
SQInteger ScriptBindings::EditPairDlg_Ctor (HSQUIRRELVM v)
Definition at line 114 of file sc_util_dialogs.cpp.
References EditPairDlg_Dtor().
Referenced by Register_UtilDialogs().
EditPairDlg_Dtor()
SQInteger ScriptBindings::EditPairDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
Definition at line 109 of file sc_util_dialogs.cpp.
Referenced by EditPairDlg_Ctor().
EditPathDlg_Ctor()
SQInteger ScriptBindings::EditPathDlg_Ctor (HSQUIRRELVM v)
Definition at line 156 of file sc_util_dialogs.cpp.
References EditPathDlg_Dtor().
Referenced by Register_UtilDialogs().
EditPathDlg_Dtor()
SQInteger ScriptBindings::EditPathDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
Definition at line 151 of file sc_util_dialogs.cpp.
Referenced by EditPathDlg_Ctor().
EndModal()
void ScriptBindings::EndModal (int retCode)
Definition at line 112 of file sc_dialog.cpp.
References cbMessageBox().
Referenced by UsrGlblMgrEditDialog::DoClose(), NewFromTemplateDlg::EditScript(), CompilerFlagDlg::EndModal(), PrintDialog::EndModal(), ProjectDepsDlg::EndModal(), EditArrayFileDlg::EndModal(), CompilerSettingsDlg::EndModal(), EditArrayStringDlg::EndModal(), EditToolDlg::EndModal(), EditWatchDlg::EndModal(), SelectTargetDlg::EndModal(), EnvironmentSettingsDlg::EndModal(), ExternalDepsDlg::EndModal(), GenericMultiLineNotesDlg::EndModal(), EditBreakpointDlg::EndModal(), ProjectFileOptionsDlg::EndModal(), EditPairDlg::EndModal(), BatchLogWindow::EndModal(), EditArrayOrderDlg::EndModal(), PluginsConfigurationDlg::EndModal(), ScriptSecurityWarningDlg::EndModal(), ProjectOptionsDlg::EndModal(), EditPathDlg::EndModal(), ProjectsFileMasksDlg::EndModal(), NewFromTemplateDlg::EndModal(), AdvancedCompilerOptionsDlg::EndModal(), ScriptingSettingsDlg::EndModal(), EditorConfigurationDlg::EndModal(), cbConfigurationDialog::EndModal(), EditArrayOrderDlg::GetArray(), EditPathDlg::GetPath(), IncrementalSelectListBase::KeyDownAction(), wxSwitcherDialog::OnActivate(), GetUserVariableDialog::OnActivated(), ConfirmReplaceDlg::OnAll(), ConfirmReplaceDlg::OnAllInFile(), ManageAssocsDialog::OnApply(), AnnoyingDialog::OnButton(), SelectIncludeFile::OnCancel(), ConfirmReplaceDlg::OnCancel(), ManageAssocsDialog::OnCancel(), GetUserVariableDialog::OnCancel(), AskAssocDialog::OnCharHook(), ManageAssocsDialog::OnClearAll(), wxSwitcherDialog::OnCloseWindow(), GotoFunctionDlg::OnColumnSelect(), AskAssocDialog::OnESC(), NewFromTemplateDlg::OnListActivate(), ConfirmReplaceDlg::OnNo(), SelectIncludeFile::OnOk(), DebuggerSettingsDlg::OnOK(), GetUserVariableDialog::OnOK(), AskAssocDialog::OnOK(), IncrementalSelectListBase::OnSelect(), ConfirmReplaceDlg::OnSkipFile(), ConfirmReplaceDlg::OnYes(), EditArrayFileDlg::operator=(), EditArrayStringDlg::operator=(), EditPairDlg::operator=(), and Register_Dialog().
ExecutePlugin()
int ScriptBindings::ExecutePlugin (const wxString & pluginName)
Definition at line 87 of file sc_globals.cpp.
References PluginManager::ExecutePlugin(), Manager::Get(), and Manager::GetPluginManager().
Referenced by Register_Globals().
gBuildLog()
void ScriptBindings::gBuildLog (const wxString & msg)
Definition at line 81 of file compilergcc.cpp.
References Manager::Get(), Manager::GetLogManager(), and LogManager::Log().
Referenced by CompilerGCC::OnAttach().
gDebugLog()
void ScriptBindings::gDebugLog (const wxString & msg)
Definition at line 33 of file sc_globals.cpp.
References LogManager::DebugLog(), Manager::Get(), and Manager::GetLogManager().
Referenced by Register_Globals().
GenericMultiLineNotesDlg_Ctor()
SQInteger ScriptBindings::GenericMultiLineNotesDlg_Ctor (HSQUIRRELVM v)
Definition at line 231 of file sc_util_dialogs.cpp.
References GenericMultiLineNotesDlg_Dtor().
Referenced by Register_UtilDialogs().
GenericMultiLineNotesDlg_Dtor()
SQInteger ScriptBindings::GenericMultiLineNotesDlg_Dtor (SQUserPointer up, cb_unused SQInteger size)
Definition at line 226 of file sc_util_dialogs.cpp.
Referenced by GenericMultiLineNotesDlg_Ctor().
gErrorLog()
void ScriptBindings::gErrorLog (const wxString & msg)
Definition at line 34 of file sc_globals.cpp.
References Manager::Get(), Manager::GetLogManager(), and LogManager::LogError().
Referenced by Register_Globals().
getCF()
CompilerFactory* ScriptBindings::getCF ()
Definition at line 64 of file sc_globals.cpp.
Referenced by Register_Globals().
getCM()
ConfigManager* ScriptBindings::getCM ()
Definition at line 60 of file sc_globals.cpp.
References Manager::Get(), and Manager::GetConfigManager().
Referenced by Register_Globals().
getEM()
EditorManager* ScriptBindings::getEM ()
Definition at line 56 of file sc_globals.cpp.
References Manager::Get(), and Manager::GetEditorManager().
Referenced by Register_Globals().
getPM()
ProjectManager* ScriptBindings::getPM ()
Definition at line 52 of file sc_globals.cpp.
References Manager::Get(), and Manager::GetProjectManager().
Referenced by Register_Globals().
getSM()
ScriptingManager* ScriptBindings::getSM ()
Definition at line 73 of file sc_globals.cpp.
References Manager::Get(), and Manager::GetScriptingManager().
Referenced by Include(), Register_Globals(), and Require().
getUVM()
UserVariableManager* ScriptBindings::getUVM ()
Definition at line 69 of file sc_globals.cpp.
References Manager::Get(), and Manager::GetUserVariableManager().
Referenced by Register_Globals().
gLog()
void ScriptBindings::gLog (const wxString & msg)
Definition at line 36 of file sc_globals.cpp.
References Manager::Get(), Manager::GetLogManager(), and LogManager::Log().
Referenced by Register_Globals().
gMessage()
int ScriptBindings::gMessage (const wxString & msg, const wxString & caption, int buttons)
Definition at line 37 of file sc_globals.cpp.
References cbMessageBox().
Referenced by Register_Globals().
gReplaceMacros()
wxString ScriptBindings::gReplaceMacros (const wxString & buffer)
Definition at line 42 of file sc_globals.cpp.
References Manager::Get(), Manager::GetMacrosManager(), and MacrosManager::ReplaceMacros().
Referenced by Register_Globals().
gShowMessage()
void ScriptBindings::gShowMessage (const wxString & msg)
Definition at line 38 of file sc_globals.cpp.
References cbMessageBox().
Referenced by Register_Globals().
gShowMessageError()
void ScriptBindings::gShowMessageError (const wxString & msg)
Definition at line 40 of file sc_globals.cpp.
References cbMessageBox().
Referenced by Register_Globals().
gShowMessageInfo()
void ScriptBindings::gShowMessageInfo (const wxString & msg)
Definition at line 41 of file sc_globals.cpp.
References cbMessageBox().
Referenced by Register_Globals().
gShowMessageWarn()
void ScriptBindings::gShowMessageWarn (const wxString & msg)
Definition at line 39 of file sc_globals.cpp.
References cbMessageBox().
Referenced by Register_Globals().
gWarningLog()
void ScriptBindings::gWarningLog (const wxString & msg)
Definition at line 35 of file sc_globals.cpp.
References Manager::Get(), Manager::GetLogManager(), and LogManager::LogWarning().
Referenced by Register_Globals().
Include()
void ScriptBindings::Include (const wxString & filename)
Definition at line 157 of file sc_globals.cpp.
References getSM(), and ScriptingManager::LoadScript().
Referenced by Register_Globals().
InstallPlugin()
bool ScriptBindings::InstallPlugin (const wxString & pluginName, bool allUsers, bool confirm)
Definition at line 77 of file sc_globals.cpp.
References cbMessageBox(), Manager::Get(), Manager::GetPluginManager(), and PluginManager::InstallPlugin().
Referenced by Register_Globals().
IsNull()
SQInteger ScriptBindings::IsNull (HSQUIRRELVM v)
Definition at line 44 of file sc_globals.cpp.
References sq_getinstanceup().
Referenced by Register_Globals().
ProjectManager_AddFileToProject()
SQInteger ScriptBindings::ProjectManager_AddFileToProject (HSQUIRRELVM v)
Definition at line 268 of file scriptbindings.cpp.
References Manager::Get().
Referenced by RegisterBindings().
ProjectManager_GetProject()
SQInteger ScriptBindings::ProjectManager_GetProject (HSQUIRRELVM v)
Definition at line 299 of file scriptbindings.cpp.
References ProjectManager::GetProjects().
Referenced by RegisterBindings().
ProjectManager_GetProjectCount()
SQInteger ScriptBindings::ProjectManager_GetProjectCount (HSQUIRRELVM v)
Definition at line 285 of file scriptbindings.cpp.
References ProjectManager::GetProjects().
Referenced by RegisterBindings().
ProjectManager_RebuildTree()
SQInteger ScriptBindings::ProjectManager_RebuildTree (HSQUIRRELVM v)
Definition at line 320 of file scriptbindings.cpp.
References ProjectManager::GetUI(), and cbProjectManagerUI::RebuildTree().
Referenced by RegisterBindings().
Register_Constants()
void ScriptBindings::Register_Constants ()
Definition at line 29 of file sc_consts.cpp.
References FileFilters::ASM_DOT_EXT, FileFilters::ASM_EXT, BIND_INT_CONSTANT, BIND_INT_CONSTANT_NAMED, BIND_WXSTR_CONSTANT_NAMED, FileFilters::C_DOT_EXT, FileFilters::C_EXT, FileFilters::CC_DOT_EXT, FileFilters::CC_EXT, FileFilters::CODEBLOCKS_DOT_EXT, FileFilters::CODEBLOCKS_EXT, FileFilters::CPLPL_DOT_EXT, FileFilters::CPLPL_EXT, FileFilters::CPP_DOT_EXT, FileFilters::CPP_EXT, FileFilters::CXX_DOT_EXT, FileFilters::CXX_EXT, FileFilters::D_DOT_EXT, FileFilters::D_EXT, FileFilters::DEVCPP_DOT_EXT, FileFilters::DEVCPP_EXT, FileFilters::DYNAMICLIB_DOT_EXT, FileFilters::DYNAMICLIB_EXT, FileFilters::EXECUTABLE_DOT_EXT, FileFilters::EXECUTABLE_EXT, FileFilters::F03_DOT_EXT, FileFilters::F03_EXT, FileFilters::F08_DOT_EXT, FileFilters::F08_EXT, FileFilters::F77_DOT_EXT, FileFilters::F77_EXT, FileFilters::F90_DOT_EXT, FileFilters::F90_EXT, FileFilters::F95_DOT_EXT, FileFilters::F95_EXT, FileFilters::F_DOT_EXT, FileFilters::F_EXT, FileFilters::FOR_DOT_EXT, FileFilters::FOR_EXT, FileFilters::FPP_DOT_EXT, FileFilters::FPP_EXT, FileTreeData::ftdkFile, FileTreeData::ftdkFolder, FileTreeData::ftdkProject, FileTreeData::ftdkUndefined, FileTreeData::ftdkVirtualFolder, FileTreeData::ftdkVirtualGroup, FileFilters::H_DOT_EXT, FileFilters::H_EXT, FileFilters::HH_DOT_EXT, FileFilters::HH_EXT, FileFilters::HPLPL_DOT_EXT, FileFilters::HPLPL_EXT, FileFilters::HPP_DOT_EXT, FileFilters::HPP_EXT, FileFilters::HXX_DOT_EXT, FileFilters::HXX_EXT, FileFilters::INL_EXT, FileFilters::JAVA_DOT_EXT, FileFilters::JAVA_EXT, mcAskRebuildNeeded, mcBuild, mcClean, mcCompileFile, mcDistClean, mcSilentBuild, FileFilters::MSVC10_DOT_EXT, FileFilters::MSVC10_EXT, FileFilters::MSVC6_DOT_EXT, FileFilters::MSVC6_EXT, FileFilters::MSVC6_WORKSPACE_DOT_EXT, FileFilters::MSVC6_WORKSPACE_EXT, FileFilters::MSVC7_DOT_EXT, FileFilters::MSVC7_EXT, FileFilters::MSVC7_WORKSPACE_DOT_EXT, FileFilters::MSVC7_WORKSPACE_EXT, mtEditorManager, mtLogManager, mtOpenFilesList, mtProjectManager, mtUnknown, FileFilters::NATIVE_DOT_EXT, FileFilters::OBJECT_DOT_EXT, FileFilters::OBJECT_EXT, orAppendToParentOptions, orPrependToParentOptions, ortCompilerOptions, ortIncludeDirs, ortLibDirs, ortLinkerOptions, ortResDirs, orUseParentOptionsOnly, orUseTargetOptionsOnly, pchObjectDir, pchSourceDir, pchSourceFile, pcmAsIs, pcmBlackAndWhite, pcmColourOnWhite, pcmInvertColours, PLUGIN_SDK_VERSION_MAJOR, PLUGIN_SDK_VERSION_MINOR, PLUGIN_SDK_VERSION_RELEASE, psActiveEditor, psAllOpenEditors, psSelection, FileFilters::RESOURCE_DOT_EXT, FileFilters::RESOURCE_EXT, FileFilters::RESOURCEBIN_DOT_EXT, FileFilters::RESOURCEBIN_EXT, FileFilters::S62_DOT_EXT, FileFilters::S62_EXT, FileFilters::S_DOT_EXT, FileFilters::S_EXT, FileFilters::SCRIPT_DOT_EXT, FileFilters::SCRIPT_EXT, sdAllGlobal, sdAllKnown, sdAllUser, sdBase, sdConfig, sdCurrent, sdDataGlobal, sdDataUser, sdHome, sdPath, sdPluginsGlobal, sdPluginsUser, sdScriptsGlobal, sdScriptsUser, sdTemp, spAll, spMac, spUnix, spWindows, FileFilters::SS_DOT_EXT, FileFilters::SS_EXT, FileFilters::STATICLIB_DOT_EXT, FileFilters::STATICLIB_EXT, FileFilters::TCC_DOT_EXT, FileFilters::TCC_EXT, tgfpNone, tgfpPlatformDefault, totCustom, totFiles, totProject, totTarget, FileFilters::TPP_DOT_EXT, FileFilters::TPP_EXT, ttCommandsOnly, ttConsoleOnly, ttDynamicLib, ttExecutable, ttNative, ttStaticLib, FileFilters::WORKSPACE_DOT_EXT, FileFilters::WORKSPACE_EXT, FileFilters::XML_DOT_EXT, FileFilters::XML_EXT, FileFilters::XRCRESOURCE_DOT_EXT, and FileFilters::XRCRESOURCE_EXT.
Referenced by RegisterBindings().
Register_Dialog()
void ScriptBindings::Register_Dialog ()
Definition at line 142 of file sc_dialog.cpp.
References EndModal(), ShowDialog(), and XrcId().
Referenced by RegisterBindings().
Register_Globals()
void ScriptBindings::Register_Globals ()
Definition at line 200 of file sc_globals.cpp.
References CallMenu(), ConfigurePlugin(), InfoWindow::Display(), EscapeSpaces(), ExecutePlugin(), FileTypeOf(), gDebugLog(), gErrorLog(), GetArrayFromString(), getCF(), getCM(), getEM(), ConfigManager::GetFolder(), GetPlatformsFromString(), getPM(), getSM(), GetStringFromArray(), GetStringFromPlatforms(), getUVM(), gLog(), gMessage(), gReplaceMacros(), gShowMessage(), gShowMessageError(), gShowMessageInfo(), gShowMessageWarn(), gWarningLog(), Include(), InstallPlugin(), IsNull(), ConfigManager::LocateDataFile(), NotifyMissingFile(), Require(), UnixFilename(), URLEncode(), wx_GetColourFromUser(), wx_GetNumberFromUser(), wx_GetPasswordFromUser(), wx_GetTextFromUser(), and wxString_ToLong().
Referenced by RegisterBindings().
Register_IO()
void ScriptBindings::Register_IO ()
Definition at line 233 of file sc_io.cpp.
References ScriptBindings::IOLib::ChooseDir(), ScriptBindings::IOLib::ChooseFile(), ScriptBindings::IOLib::CopyFile(), ScriptBindings::IOLib::CreateDirRecursively(), ScriptBindings::IOLib::DirectoryExists(), ScriptBindings::IOLib::Execute(), ScriptBindings::IOLib::ExecuteAndGetOutput(), ScriptBindings::IOLib::ExecuteAndGetOutputAndError(), ScriptBindings::IOLib::FileExists(), ScriptBindings::IOLib::GetCwd(), ScriptBindings::IOLib::ReadFileContents(), ScriptBindings::IOLib::RemoveDir(), ScriptBindings::IOLib::RemoveFile(), ScriptBindings::IOLib::RenameFile(), ScriptBindings::IOLib::SetCwd(), and ScriptBindings::IOLib::WriteFileContents().
Referenced by RegisterBindings().
Register_ProgressDialog()
void ScriptBindings::Register_ProgressDialog ()
Definition at line 52 of file sc_progress.cpp.
References ProgressDialog::DoUpdate().
Referenced by RegisterBindings().
Register_ScriptPlugin()
void ScriptBindings::Register_ScriptPlugin ()
Definition at line 339 of file sc_plugin.cpp.
References cbC2U(), cbMessageBox(), ScriptBindings::ScriptPluginWrapper::ExecutePlugin(), ScriptBindings::ScriptPluginWrapper::GetPlugin(), ScriptBindings::ScriptPluginWrapper::RegisterPlugin(), sq_getprintfunc(), and sq_setprintfunc().
Referenced by RegisterBindings().
Register_UtilDialogs()
void ScriptBindings::Register_UtilDialogs ()
Definition at line 273 of file sc_util_dialogs.cpp.
References EditPairDlg::bmBrowseForDirectory, EditPairDlg::bmBrowseForFile, EditPairDlg::bmDisable, EditArrayFileDlg_Ctor(), EditArrayOrderDlg_Ctor(), EditArrayStringDlg_Ctor(), EditPairDlg_Ctor(), EditPathDlg_Ctor(), GenericMultiLineNotesDlg_Ctor(), EditArrayOrderDlg::GetArray(), GenericMultiLineNotesDlg::GetNotes(), EditPathDlg::GetPath(), EditArrayOrderDlg::SetArray(), and ShowModalForDialogs().
Referenced by RegisterBindings().
Register_wxTypes()
void ScriptBindings::Register_wxTypes ()
Definition at line 258 of file sc_wxtypes.cpp.
References FileFilters::Add(), ScriptBindings::IOLib::RemoveDir(), ScriptBindings::IOLib::SetCwd(), static_(), static_T(), wxArrayString_Index(), wxArrayString_SetItem(), wxColour_OpToString(), wxFileName_OpToString(), wxPoint_OpCmp(), wxString_AddChar(), wxString_AfterFirst(), wxString_AfterLast(), wxString_BeforeFirst(), wxString_BeforeLast(), wxString_GetChar(), wxString_Matches(), wxString_OpAdd(), wxString_OpCmp(), wxString_OpToString(), and wxString_Replace().
Referenced by RegisterBindings().
RegisterBindings()
void ScriptBindings::RegisterBindings ()
Definition at line 384 of file scriptbindings.cpp.
References EditorBase::Activate(), EditorManager::ActivateNext(), EditorManager::ActivatePrevious(), cbEditor::AddBreakpoint(), CompileOptionsBase::AddBuildScript(), ProjectFile::AddBuildTarget(), cbProject::AddBuildTarget(), CompileOptionsBase::AddCommandsAfterBuild(), CompileOptionsBase::AddCommandsBeforeBuild(), CompileOptionsBase::AddCompilerOption(), CompileOptionsBase::AddIncludeDir(), CompileOptionsBase::AddLibDir(), CompileOptionsBase::AddLinkerOption(), CompileOptionsBase::AddLinkLib(), CompileOptionsBase::AddPlatform(), ProjectManager::AddProjectDependency(), CompileOptionsBase::AddResourceCompilerOption(), CompileOptionsBase::AddResourceIncludeDir(), cbProject::AddToExtensions(), PluginInfo::author, PluginInfo::authorEmail, PluginInfo::authorWebsite, cbEditor::AutoComplete(), ProjectFile::buildTargets, cbProject::BuildTargetValid(), cbProject::CanAddToVirtualBuildTarget(), EditorBase::CanPaste(), EditorBase::CanRedo(), EditorBase::CanUndo(), cbEditor_GetText(), cbEditor_SetText(), cbProject_AddFile(), cbProject_DuplicateBuildTarget(), cbProject_ExportTargetAsProject(), cbProject_GetBuildTarget(), cbProject_RemoveBuildTarget(), cbProject_RemoveFile(), cbProject_RenameBuildTarget(), cbThrow, cbEditor::ClearAllBookmarks(), ProjectManager::ClearProjectDependencies(), EditorBase::Close(), EditorManager::CloseActive(), ProjectManager::CloseActiveProject(), EditorManager::CloseAll(), cbProject::CloseAllFiles(), ProjectManager::CloseAllProjects(), ProjectManager::CloseProject(), ProjectManager::CloseWorkspace(), ProjectFile::compile, CompilerFactory_GetCompilerIDByName(), CompilerFactory_GetCompilerIndex(), CompilerFactory::CompilerInheritsFrom(), ProjectFile::compilerVar, ConfigManager_Read(), ConfigManager_Write(), EditorBase::Copy(), EditorBase::Cut(), cbProject::DefineVirtualBuildTarget(), PluginInfo::description, EditorManager_Close(), EditorManager_GetBuiltinEditor(), EditorManager_Open(), EditorManager_Save(), UserVariableManager::Exists(), ProjectFile::file, cbEditor::FoldAll(), cbEditor::FoldBlockFromLine(), cbProject::GetActiveBuildTarget(), EditorManager::GetActiveEditor(), ProjectManager::GetActiveProject(), ProjectBuildTarget::GetAdditionalOutputFiles(), CompileOptionsBase::GetAlwaysRunPostBuildSteps(), ProjectFile::GetBaseName(), CompileTargetBase::GetBasePath(), CompileOptionsBase::GetBuildScripts(), ProjectFile::GetBuildTargets(), cbProject::GetBuildTargetsCount(), EditorManager::GetBuiltinActiveEditor(), cbProject::GetCheckForExternallyModifiedFiles(), CompileOptionsBase::GetCommandsAfterBuild(), CompileOptionsBase::GetCommandsBeforeBuild(), cbProject::GetCommonTopLevelPath(), CompileTargetBase::GetCompilerID(), CompileOptionsBase::GetCompilerOptions(), CompilerFactory::GetCompilerVersionString(), ProjectBuildTarget::GetCreateDefFile(), ProjectBuildTarget::GetCreateStaticLib(), cbProject::GetCurrentlyCompilingTarget(), ProjectFile::GetCustomBuildCommand(), CompilerFactory::GetDefaultCompilerID(), cbProject::GetDefaultExecuteTarget(), ProjectManager::GetDefaultPath(), ProjectManager::GetDependenciesForProject(), CompileTargetBase::GetDepsOutput(), CompileTargetBase::GetDynamicLibDefFilename(), CompileTargetBase::GetDynamicLibFilename(), CompileTargetBase::GetExecutableFilename(), CompileTargetBase::GetExecutionParameters(), cbProject::GetExpandedVirtualBuildTargetGroup(), cbProject::GetExtendedObjectNamesGeneration(), ProjectBuildTarget::GetExternalDeps(), ProjectBuildTarget::GetFile(), cbProject::GetFile(), cbProject::GetFileByFilename(), FileTreeData::GetFileIndex(), EditorBase::GetFilename(), CompileTargetBase::GetFilename(), ProjectBuildTarget::GetFilesCount(), cbProject::GetFilesCount(), cbProject::GetFirstValidBuildTargetName(), FileTreeData::GetFolder(), ProjectBuildTarget::GetFullTitle(), CompileTargetBase::GetHostApplication(), CompileOptionsBase::GetIncludeDirs(), ProjectBuildTarget::GetIncludeInTargetAll(), FileTreeData::GetKind(), CompileOptionsBase::GetLibDirs(), cbEditor::GetLineIndentInSpaces(), cbEditor::GetLineIndentString(), CompileOptionsBase::GetLinkerOptions(), CompileOptionsBase::GetLinkLibs(), CompileTargetBase::GetMakeCommandFor(), cbProject::GetMakefile(), cbProject::GetModeForPCH(), EditorBase::GetModified(), CompileOptionsBase::GetModified(), cbProject::GetModified(), cbProject::GetNotes(), CompileTargetBase::GetObjectOutput(), ProjectFile::GetObjName(), CompileTargetBase::GetOptionRelation(), CompileTargetBase::GetOutputFilename(), ProjectBuildTarget::GetParentProject(), ProjectFile::GetParentProject(), CompileOptionsBase::GetPlatforms(), FileTreeData::GetProject(), FileTreeData::GetProjectFile(), cbEditor::GetProjectFile(), CompileOptionsBase::GetResourceCompilerOptions(), CompileOptionsBase::GetResourceIncludeDirs(), EditorBase::GetShortName(), cbProject::GetShowNotesOnLoad(), CompileTargetBase::GetStaticLibFilename(), CompileTargetBase::GetTargetType(), EditorBase::GetTitle(), CompileTargetBase::GetTitle(), ProjectBuildTarget::GetUseConsoleRunner(), ProjectFile::GetUseCustomBuildCommand(), CompileOptionsBase::GetVar(), cbProject::GetVirtualBuildTargetGroup(), cbProject::GetVirtualBuildTargets(), CompileTargetBase::GetWorkingDir(), EditorBase::GotoLine(), cbEditor::GotoNextBookmark(), cbEditor::GotoNextBreakpoint(), cbEditor::GotoPreviousBookmark(), cbEditor::GotoPreviousBreakpoint(), cbEditor::HasBookmark(), cbEditor::HasBreakpoint(), EditorBase::HasSelection(), cbProject::HasVirtualBuildTarget(), EditorBase::IsBuiltinEditor(), EditorManager::IsBuiltinOpen(), cbProject::IsMakefileCustom(), ProjectManager::IsOpen(), EditorBase::IsReadOnly(), CompilerFactory::IsValidCompilerID(), PluginInfo::license, ProjectFile::link, cbProject::LoadLayout(), ProjectManager::LoadProject(), ProjectManager::LoadWorkspace(), CompileTargetBase::MakeCommandsModified(), PluginInfo::name, EditorManager::New(), ProjectManager::NewProject(), EditorBase::Paste(), cbEditor::Print(), ProjectManager_AddFileToProject(), ProjectManager_GetProject(), ProjectManager_GetProjectCount(), ProjectManager_RebuildTree(), EditorBase::Redo(), Register_Constants(), Register_Dialog(), Register_Globals(), Register_IO(), Register_ProgressDialog(), Register_ScriptPlugin(), Register_UtilDialogs(), Register_wxTypes(), ScriptingManager::RegisterScriptMenu(), ProjectFile::relativeFilename, ProjectFile::relativeToCommonTopLevelPath, cbEditor::Reload(), cbEditor::RemoveBreakpoint(), CompileOptionsBase::RemoveBuildScript(), ProjectFile::RemoveBuildTarget(), CompileOptionsBase::RemoveCommandsAfterBuild(), CompileOptionsBase::RemoveCommandsBeforeBuild(), CompileOptionsBase::RemoveCompilerOption(), CompileOptionsBase::RemoveIncludeDir(), CompileOptionsBase::RemoveLibDir(), CompileOptionsBase::RemoveLinkerOption(), CompileOptionsBase::RemoveLinkLib(), CompileOptionsBase::RemovePlatform(), ProjectManager::RemoveProjectDependency(), ProjectManager::RemoveProjectFromAllDependencies(), CompileOptionsBase::RemoveResourceCompilerOption(), CompileOptionsBase::RemoveResourceIncludeDir(), cbProject::RemoveVirtualBuildTarget(), ProjectFile::RenameBuildTarget(), CompileOptionsBase::ReplaceCompilerOption(), CompileOptionsBase::ReplaceIncludeDir(), CompileOptionsBase::ReplaceLibDir(), CompileOptionsBase::ReplaceLinkerOption(), CompileOptionsBase::ReplaceLinkLib(), CompileOptionsBase::ReplaceResourceCompilerOption(), CompileOptionsBase::ReplaceResourceIncludeDir(), EditorBase::Save(), cbEditor::Save(), cbProject::Save(), EditorManager::SaveActive(), EditorManager::SaveActiveAs(), ProjectManager::SaveActiveProject(), ProjectManager::SaveActiveProjectAs(), EditorManager::SaveAll(), cbProject::SaveAllFiles(), ProjectManager::SaveAllProjects(), EditorManager::SaveAs(), cbEditor::SaveAs(), cbProject::SaveLayout(), ProjectManager::SaveProject(), ProjectManager::SaveProjectAs(), ProjectManager::SaveWorkspace(), ProjectManager::SaveWorkspaceAs(), cbProject::SelectTarget(), cbProject::SetActiveBuildTarget(), ProjectBuildTarget::SetAdditionalOutputFiles(), CompileOptionsBase::SetAlwaysRunPostBuildSteps(), CompileOptionsBase::SetBuildScripts(), cbProject::SetCheckForExternallyModifiedFiles(), CompileOptionsBase::SetCommandsAfterBuild(), CompileOptionsBase::SetCommandsBeforeBuild(), CompileTargetBase::SetCompilerID(), CompileOptionsBase::SetCompilerOptions(), ProjectBuildTarget::SetCreateDefFile(), ProjectBuildTarget::SetCreateStaticLib(), cbProject::SetCurrentlyCompilingTarget(), ProjectFile::SetCustomBuildCommand(), cbProject::SetDefaultExecuteTarget(), ProjectManager::SetDefaultPath(), CompileTargetBase::SetDepsOutput(), cbEditor::SetEditorTitle(), CompileTargetBase::SetExecutionParameters(), cbProject::SetExtendedObjectNamesGeneration(), ProjectBuildTarget::SetExternalDeps(), FileTreeData::SetFileIndex(), EditorBase::SetFilename(), FileTreeData::SetFolder(), CompileTargetBase::SetHostApplication(), CompileOptionsBase::SetIncludeDirs(), ProjectBuildTarget::SetIncludeInTargetAll(), FileTreeData::SetKind(), CompileOptionsBase::SetLibDirs(), CompileOptionsBase::SetLinkerOptions(), CompileOptionsBase::SetLinkLibs(), CompileTargetBase::SetMakeCommandFor(), cbProject::SetMakefile(), cbProject::SetMakefileCustom(), cbProject::SetModeForPCH(), EditorBase::SetModified(), CompileOptionsBase::SetModified(), cbProject::SetModified(), cbProject::SetNotes(), CompileTargetBase::SetObjectOutput(), ProjectFile::SetObjName(), CompileTargetBase::SetOptionRelation(), CompileTargetBase::SetOutputFilename(), CompileOptionsBase::SetPlatforms(), FileTreeData::SetProject(), ProjectManager::SetProject(), FileTreeData::SetProjectFile(), CompileOptionsBase::SetResourceCompilerOptions(), CompileOptionsBase::SetResourceIncludeDirs(), cbProject::SetShowNotesOnLoad(), CompileTargetBase::SetTargetFilenameGenerationPolicy(), CompileTargetBase::SetTargetType(), EditorBase::SetTitle(), CompileTargetBase::SetTitle(), cbProject::SetTitle(), ProjectBuildTarget::SetUseConsoleRunner(), ProjectFile::SetUseCustomBuildCommand(), CompileOptionsBase::SetVar(), CompileTargetBase::SetWorkingDir(), cbProject::ShowNotes(), CompileTargetBase::SuggestOutputFilename(), CompileOptionsBase::SupportsCurrentPlatform(), EditorManager::SwapActiveHeaderSource(), PluginInfo::thanksTo, EditorBase::ThereAreOthers(), PluginInfo::title, cbEditor::ToggleAllFolds(), cbEditor::ToggleBookmark(), cbEditor::ToggleBreakpoint(), cbEditor::ToggleFoldBlockFromLine(), cbEditor::Touch(), EditorBase::Undo(), cbEditor::UnfoldAll(), cbEditor::UnfoldBlockFromLine(), CompileOptionsBase::UnsetAllVars(), CompileOptionsBase::UnsetVar(), PluginInfo::version, and ProjectFile::weight.
Referenced by ScriptingManager::ScriptingManager().
Require()
SQInteger ScriptBindings::Require (HSQUIRRELVM v)
Definition at line 161 of file sc_globals.cpp.
References cbU2C(), getSM(), and ScriptingManager::LoadScript().
Referenced by Register_Globals().
ShowDialog()
int ScriptBindings::ShowDialog (const wxString & xrc, const wxString & dlgName, const wxString & callback)
Definition at line 79 of file sc_dialog.cpp.
References cbMessageBox(), LogManager::DebugLog(), Manager::Get(), Manager::GetLogManager(), ConfigManager::LocateDataFile(), s_ActiveDialog, sdScriptsGlobal, sdScriptsUser, wxScrollingDialog::ShowModal(), and ScriptBindings::XrcDialog::XrcDialog().
Referenced by Register_Dialog().
ShowModalForDialogs()
SQInteger ScriptBindings::ShowModalForDialogs (HSQUIRRELVM v)
Definition at line 264 of file sc_util_dialogs.cpp.
References wxScrollingDialog::ShowModal(), and sq_getinstanceup().
Referenced by Register_UtilDialogs().
static_()
wxString ScriptBindings::static_ (const SQChar * str)
Definition at line 104 of file sc_wxtypes.cpp.
References cbC2U().
Referenced by Register_wxTypes().
static_T()
wxString ScriptBindings::static_T (const SQChar * str)
Definition at line 110 of file sc_wxtypes.cpp.
References cbC2U().
Referenced by Register_wxTypes().
wx_GetColourFromUser()
SQInteger ScriptBindings::wx_GetColourFromUser (HSQUIRRELVM v)
Definition at line 172 of file sc_globals.cpp.
References Manager::Get().
Referenced by Register_Globals().
wx_GetNumberFromUser()
long ScriptBindings::wx_GetNumberFromUser (const wxString & message, const wxString & prompt, const wxString & caption, long value)
Definition at line 178 of file sc_globals.cpp.
Referenced by Register_Globals().
wx_GetPasswordFromUser()
wxString ScriptBindings::wx_GetPasswordFromUser (const wxString & message, const wxString & caption, const wxString & default_value)
Definition at line 182 of file sc_globals.cpp.
Referenced by Register_Globals().
wx_GetTextFromUser()
wxString ScriptBindings::wx_GetTextFromUser (const wxString & message, const wxString & caption, const wxString & default_value)
Definition at line 186 of file sc_globals.cpp.
References cbGetTextFromUser().
Referenced by Register_Globals().
wxArrayString_Index()
SQInteger ScriptBindings::wxArrayString_Index (HSQUIRRELVM v)
Definition at line 25 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxArrayString_SetItem()
SQInteger ScriptBindings::wxArrayString_SetItem (HSQUIRRELVM v)
Definition at line 39 of file sc_wxtypes.cpp.
References sq_throwerror().
Referenced by Register_wxTypes().
wxColour_OpToString()
SQInteger ScriptBindings::wxColour_OpToString (HSQUIRRELVM v)
Definition at line 56 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxFileName_OpToString()
SQInteger ScriptBindings::wxFileName_OpToString (HSQUIRRELVM v)
Definition at line 67 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxPoint_OpCmp()
SQInteger ScriptBindings::wxPoint_OpCmp (HSQUIRRELVM v)
Definition at line 79 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxPoint_x()
SQInteger ScriptBindings::wxPoint_x (HSQUIRRELVM v)
Definition at line 86 of file sc_wxtypes.cpp.
wxPoint_y()
SQInteger ScriptBindings::wxPoint_y (HSQUIRRELVM v)
Definition at line 92 of file sc_wxtypes.cpp.
wxString_AddChar()
SQInteger ScriptBindings::wxString_AddChar (HSQUIRRELVM v)
Definition at line 156 of file sc_wxtypes.cpp.
References cbC2U().
Referenced by Register_wxTypes().
wxString_AfterFirst()
SQInteger ScriptBindings::wxString_AfterFirst (HSQUIRRELVM v)
Definition at line 180 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxString_AfterLast()
SQInteger ScriptBindings::wxString_AfterLast (HSQUIRRELVM v)
Definition at line 196 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxString_BeforeFirst()
SQInteger ScriptBindings::wxString_BeforeFirst (HSQUIRRELVM v)
Definition at line 212 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxString_BeforeLast()
SQInteger ScriptBindings::wxString_BeforeLast (HSQUIRRELVM v)
Definition at line 228 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxString_GetChar()
SQInteger ScriptBindings::wxString_GetChar (HSQUIRRELVM v)
Definition at line 166 of file sc_wxtypes.cpp.
References cbU2C().
Referenced by Register_wxTypes().
wxString_Matches()
SQInteger ScriptBindings::wxString_Matches (HSQUIRRELVM v)
Definition at line 173 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxString_OpAdd()
SQInteger ScriptBindings::wxString_OpAdd (HSQUIRRELVM v)
Definition at line 116 of file sc_wxtypes.cpp.
References cbC2U().
Referenced by Register_wxTypes().
wxString_OpCmp()
SQInteger ScriptBindings::wxString_OpCmp (HSQUIRRELVM v)
Definition at line 140 of file sc_wxtypes.cpp.
References cbC2U().
Referenced by Register_wxTypes().
wxString_OpToString()
SQInteger ScriptBindings::wxString_OpToString (HSQUIRRELVM v)
Definition at line 149 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxString_Replace()
SQInteger ScriptBindings::wxString_Replace (HSQUIRRELVM v)
Definition at line 244 of file sc_wxtypes.cpp.
Referenced by Register_wxTypes().
wxString_ToLong()
long ScriptBindings::wxString_ToLong (wxString const & str)
Definition at line 191 of file sc_globals.cpp.
Referenced by Register_Globals().
XrcId()
SQInteger ScriptBindings::XrcId (HSQUIRRELVM v)
Definition at line 123 of file sc_dialog.cpp.
References cbC2U(), and cbMessageBox().
Referenced by Register_Dialog().
Variable Documentation
gBuildLogId
int ScriptBindings::gBuildLogId = -1 static
Definition at line 78 of file compilergcc.cpp.
Referenced by CompilerGCC::OnAttach(), and CompilerGCC::OnRelease().
s_ActiveDialog
XrcDialog* ScriptBindings::s_ActiveDialog = nullptr
Definition at line 48 of file sc_dialog.cpp.
Referenced by ShowDialog().
s_cbScriptPlugin
const char* ScriptBindings::s_cbScriptPlugin
Definition at line 298 of file sc_plugin.cpp.
s_PathSep
wxString ScriptBindings::s_PathSep = wxFILE_SEP_PATH
Definition at line 27 of file sc_consts.cpp.