Code::Blocks: FileFilters Namespace Reference
FileFilters Namespace Reference
Provides functions and constants regarding file extension filters present in file dialogs throughout Code::Blocks.
Functions
DLLIMPORT void AddDefaultFileFilters ()
Adds file filters for various supported projects and workspaces.
DLLIMPORT bool Add (const wxString &name, const wxString &mask)
Add a new extension filter.
DLLIMPORT wxString GetFilterString (const wxString &ext=wxEmptyString)
Generates and returns the filter string for use in file dialogs.
DLLIMPORT wxString GetFilterAll ()
Generates a simple special filter "All files".
DLLIMPORT size_t GetIndexForFilterAll ()
Get the filter index for the special "All files" filter.
DLLIMPORT bool GetFilterNameFromIndex (const wxString &FiltersList, int Index, wxString &FilterName)
Get the Filter name for the Index-th filter in the FiltersList.
DLLIMPORT bool GetFilterIndexFromName (const wxString &FiltersList, const wxString &FilterName, int &Index)
Get the index of the filter 'FilterName' in the FiltersList.
Variables
const DLLIMPORT wxString WORKSPACE_EXT = _T("workspace")
const DLLIMPORT wxString CODEBLOCKS_EXT = _T("cbp")
const DLLIMPORT wxString DEVCPP_EXT = _T("dev")
const DLLIMPORT wxString MSVC6_EXT = _T("dsp")
const DLLIMPORT wxString MSVC6_WORKSPACE_EXT = _T("dsw")
const DLLIMPORT wxString MSVC7_EXT = _T("vcproj")
const DLLIMPORT wxString MSVC7_WORKSPACE_EXT = _T("sln")
const DLLIMPORT wxString MSVC10_EXT = _T("vcxproj")
const DLLIMPORT wxString XCODE1_EXT = _T("xcode")
const DLLIMPORT wxString XCODE2_EXT = _T("xcodeproj")
const DLLIMPORT wxString ASM_EXT = _T("asm")
const DLLIMPORT wxString D_EXT = _T("d")
const DLLIMPORT wxString F_EXT = _T("f")
const DLLIMPORT wxString F77_EXT = _T("f77")
const DLLIMPORT wxString F90_EXT = _T("f90")
const DLLIMPORT wxString F95_EXT = _T("f95")
const DLLIMPORT wxString FOR_EXT = _T("for")
const DLLIMPORT wxString FPP_EXT = _T("fpp")
const DLLIMPORT wxString F03_EXT = _T("f03")
const DLLIMPORT wxString F08_EXT = _T("f08")
const DLLIMPORT wxString JAVA_EXT = _T("java")
const DLLIMPORT wxString C_EXT = _T("c")
const DLLIMPORT wxString CC_EXT = _T("cc")
const DLLIMPORT wxString CPP_EXT = _T("cpp")
const DLLIMPORT wxString CXX_EXT = _T("cxx")
const DLLIMPORT wxString CPLPL_EXT = _T("c++")
const DLLIMPORT wxString INL_EXT = _T("inl")
const DLLIMPORT wxString TPP_EXT = _T("tpp")
const DLLIMPORT wxString TCC_EXT = _T("tcc")
const DLLIMPORT wxString H_EXT = _T("h")
const DLLIMPORT wxString HH_EXT = _T("hh")
const DLLIMPORT wxString HPP_EXT = _T("hpp")
const DLLIMPORT wxString HXX_EXT = _T("hxx")
const DLLIMPORT wxString HPLPL_EXT = _T("h++")
const DLLIMPORT wxString S_EXT = _T("s")
const DLLIMPORT wxString SS_EXT = _T("ss")
const DLLIMPORT wxString S62_EXT = _T("s62")
const DLLIMPORT wxString OBJECT_EXT = _T("o")
const DLLIMPORT wxString XRCRESOURCE_EXT = _T("xrc")
const DLLIMPORT wxString STATICLIB_EXT = _T("a")
const DLLIMPORT wxString DYNAMICLIB_EXT = _T("dll")
const DLLIMPORT wxString EXECUTABLE_EXT = _T("exe")
const DLLIMPORT wxString NATIVE_EXT = _T("sys")
const DLLIMPORT wxString RESOURCE_EXT = _T("rc")
const DLLIMPORT wxString RESOURCEBIN_EXT = _T("res")
const DLLIMPORT wxString XML_EXT = _T("xml")
const DLLIMPORT wxString SCRIPT_EXT = _T("script")
const DLLIMPORT wxString WORKSPACE_DOT_EXT = _T('.') + FileFilters::WORKSPACE_EXT
const DLLIMPORT wxString CODEBLOCKS_DOT_EXT = _T('.') + FileFilters::CODEBLOCKS_EXT
const DLLIMPORT wxString DEVCPP_DOT_EXT = _T('.') + FileFilters::DEVCPP_EXT
const DLLIMPORT wxString MSVC6_DOT_EXT = _T('.') + FileFilters::MSVC6_EXT
const DLLIMPORT wxString MSVC6_WORKSPACE_DOT_EXT = _T('.') + FileFilters::MSVC6_WORKSPACE_EXT
const DLLIMPORT wxString MSVC7_DOT_EXT = _T('.') + FileFilters::MSVC7_EXT
const DLLIMPORT wxString MSVC7_WORKSPACE_DOT_EXT = _T('.') + FileFilters::MSVC7_WORKSPACE_EXT
const DLLIMPORT wxString MSVC10_DOT_EXT = _T('.') + FileFilters::MSVC10_EXT
const DLLIMPORT wxString XCODE1_DOT_EXT = _T('.') + FileFilters::XCODE1_EXT
const DLLIMPORT wxString XCODE2_DOT_EXT = _T('.') + FileFilters::XCODE2_EXT
const DLLIMPORT wxString ASM_DOT_EXT = _T('.') + FileFilters::ASM_EXT
const DLLIMPORT wxString D_DOT_EXT = _T('.') + FileFilters::D_EXT
const DLLIMPORT wxString F_DOT_EXT = _T('.') + FileFilters::F_EXT
const DLLIMPORT wxString F77_DOT_EXT = _T('.') + FileFilters::F77_EXT
const DLLIMPORT wxString F90_DOT_EXT = _T('.') + FileFilters::F90_EXT
const DLLIMPORT wxString F95_DOT_EXT = _T('.') + FileFilters::F95_EXT
const DLLIMPORT wxString FOR_DOT_EXT = _T('.') + FileFilters::FOR_EXT
const DLLIMPORT wxString FPP_DOT_EXT = _T('.') + FileFilters::FPP_EXT
const DLLIMPORT wxString F03_DOT_EXT = _T('.') + FileFilters::F03_EXT
const DLLIMPORT wxString F08_DOT_EXT = _T('.') + FileFilters::F08_EXT
const DLLIMPORT wxString JAVA_DOT_EXT = _T('.') + FileFilters::JAVA_EXT
const DLLIMPORT wxString C_DOT_EXT = _T('.') + FileFilters::C_EXT
const DLLIMPORT wxString CC_DOT_EXT = _T('.') + FileFilters::CC_EXT
const DLLIMPORT wxString CPP_DOT_EXT = _T('.') + FileFilters::CPP_EXT
const DLLIMPORT wxString CXX_DOT_EXT = _T('.') + FileFilters::CXX_EXT
const DLLIMPORT wxString CPLPL_DOT_EXT = _T('.') + FileFilters::CPLPL_EXT
const DLLIMPORT wxString INL_DOT_EXT = _T('.') + FileFilters::INL_EXT
const DLLIMPORT wxString TPP_DOT_EXT = _T('.') + FileFilters::TPP_EXT
const DLLIMPORT wxString TCC_DOT_EXT = _T('.') + FileFilters::TCC_EXT
const DLLIMPORT wxString H_DOT_EXT = _T('.') + FileFilters::H_EXT
const DLLIMPORT wxString HH_DOT_EXT = _T('.') + FileFilters::HH_EXT
const DLLIMPORT wxString HPP_DOT_EXT = _T('.') + FileFilters::HPP_EXT
const DLLIMPORT wxString HXX_DOT_EXT = _T('.') + FileFilters::HXX_EXT
const DLLIMPORT wxString HPLPL_DOT_EXT = _T('.') + FileFilters::HPLPL_EXT
const DLLIMPORT wxString S_DOT_EXT = _T('.') + FileFilters::S_EXT
const DLLIMPORT wxString SS_DOT_EXT = _T('.') + FileFilters::SS_EXT
const DLLIMPORT wxString S62_DOT_EXT = _T('.') + FileFilters::S62_EXT
const DLLIMPORT wxString OBJECT_DOT_EXT = _T('.') + FileFilters::OBJECT_EXT
const DLLIMPORT wxString XRCRESOURCE_DOT_EXT = _T('.') + FileFilters::XRCRESOURCE_EXT
const DLLIMPORT wxString STATICLIB_DOT_EXT = _T('.') + FileFilters::STATICLIB_EXT
const DLLIMPORT wxString DYNAMICLIB_DOT_EXT = _T('.') + FileFilters::DYNAMICLIB_EXT
const DLLIMPORT wxString EXECUTABLE_DOT_EXT = _T('.') + FileFilters::EXECUTABLE_EXT
const DLLIMPORT wxString NATIVE_DOT_EXT = _T('.') + FileFilters::NATIVE_EXT
const DLLIMPORT wxString RESOURCE_DOT_EXT = _T('.') + FileFilters::RESOURCE_EXT
const DLLIMPORT wxString RESOURCEBIN_DOT_EXT = _T('.') + FileFilters::RESOURCEBIN_EXT
const DLLIMPORT wxString XML_DOT_EXT = _T('.') + FileFilters::XML_EXT
const DLLIMPORT wxString SCRIPT_DOT_EXT = _T('.') + FileFilters::SCRIPT_EXT
Detailed Description
Provides functions and constants regarding file extension filters present in file dialogs throughout Code::Blocks.
Function Documentation
Add()
bool FileFilters::Add (const wxString & name, const wxString & mask)
Add a new extension filter.
Parameters
name The filter's name.
mask The extension masks comma-separated string (i.e. "*.cpp,*.c").
Returns
True if added sucessfully, false if not (i.e. empty arguments).
Definition at line 41 of file filefilters.cpp.
References _T, wxString::IsEmpty(), wxString::npos, wxString::Replace(), and s_Filters.
Referenced by AddDefaultFileFilters(), CreateDefaultDelegate(), and EditorColourSet::SetFileMasks().
AddDefaultFileFilters()
void FileFilters::AddDefaultFileFilters ()
Adds file filters for various supported projects and workspaces.
Definition at line 23 of file filefilters.cpp.
References _(), _T, Add(), and s_Filters.
Referenced by MainFrame::MainFrame().
GetFilterAll()
wxString FileFilters::GetFilterAll ()
Generates a simple special filter "All files".
No other filters are added.
Returns
the "All files" filter.
Definition at line 98 of file filefilters.cpp.
References _(), and s_LastFilterAllIndex.
Referenced by GetFilterString(), EditArrayFileDlg::OnAdd(), EditPairDlg::OnBrowse(), ProjectOptionsDlg::OnBrowseDefinitionFileFilenameClick(), ProjectOptionsDlg::OnBrowseImportLibraryFilenameClick(), ProjectOptionsDlg::OnBrowseOutputFilenameClick(), EditArrayFileDlg::OnEdit(), BacktraceDlg::OnSave(), and DisassemblyDlg::OnSave().
GetFilterIndexFromName()
bool FileFilters::GetFilterIndexFromName (const wxString & FiltersList, const wxString & FilterName, int & Index)
Get the index of the filter 'FilterName' in the FiltersList.
Parameters
FiltersList The list of Filters
FilterName Name of the filter we want to know the index of
Index Receives the index of the filter if found
Returns
filter found : yes/no.
Definition at line 112 of file filefilters.cpp.
References _T, GetArrayFromString(), and wxArrayString::GetCount().
Referenced by MainFrame::DoOnFileOpen(), and cbEditor::SaveAs().
GetFilterNameFromIndex()
bool FileFilters::GetFilterNameFromIndex (const wxString & FiltersList, int Index, wxString & FilterName)
Get the Filter name for the Index-th filter in the FiltersList.
Parameters
FiltersList The list of Filters
Index The index in the FiltersList of the filter we want to know the name of
FilterName Receives the filters name if found
Returns
filter found : yes/no.
Definition at line 130 of file filefilters.cpp.
References _T, GetArrayFromString(), and wxArrayString::GetCount().
Referenced by MainFrame::DoOnFileOpen(), and cbEditor::SaveAs().
GetFilterString()
wxString FileFilters::GetFilterString (const wxString & ext = wxEmptyString)
Generates and returns the filter string for use in file dialogs.
Parameters
ext If not empty, only filters matching this extension will be returned. Note that ext must include the separating dot. It can be a full filename if you want, but it cannot be just the extension (without the separating dot).
Returns
The filter string.
Definition at line 60 of file filefilters.cpp.
References _T, GetArrayFromString(), wxArrayString::GetCount(), GetFilterAll(), wxString::IsEmpty(), wxString::Matches(), s_Filters, and s_LastFilterAllIndex.
Referenced by MainFrame::DoOnFileOpen(), ProjectManagerUI::OnAddFileToProject(), ScriptingSettingsDlg::OnBrowse(), MainFrame::OnFileImportProjectDevCpp(), MainFrame::OnFileImportProjectMSVC(), MainFrame::OnFileImportProjectMSVCWksp(), MainFrame::OnFileImportProjectMSVS(), MainFrame::OnFileImportProjectMSVSWksp(), cbWorkspace::SaveAs(), cbEditor::SaveAs(), and cbProject::SaveAs().
GetIndexForFilterAll()
size_t FileFilters::GetIndexForFilterAll ()
Get the filter index for the special "All files" filter.
Returns
the "All files" filter index.
Definition at line 107 of file filefilters.cpp.
References s_LastFilterAllIndex.
Referenced by MainFrame::DoOnFileOpen(), and ProjectManagerUI::OnAddFileToProject().
Variable Documentation
ASM_DOT_EXT
const wxString FileFilters::ASM_DOT_EXT = _T('.') + FileFilters::ASM_EXT
Definition at line 215 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
ASM_EXT
const wxString FileFilters::ASM_EXT = _T("asm")
Definition at line 156 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
C_DOT_EXT
const wxString FileFilters::C_DOT_EXT = _T('.') + FileFilters::C_EXT
Definition at line 226 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
C_EXT
const wxString FileFilters::C_EXT = _T("c")
Definition at line 167 of file filefilters.cpp.
Referenced by cbProject::AddFile(), ProjectLoader::ExportTargetAsProject(), FileTypeOf(), and ScriptBindings::Register_Constants().
CC_DOT_EXT
const wxString FileFilters::CC_DOT_EXT = _T('.') + FileFilters::CC_EXT
Definition at line 227 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
CC_EXT
const wxString FileFilters::CC_EXT = _T("cc")
Definition at line 168 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
CODEBLOCKS_DOT_EXT
const wxString FileFilters::CODEBLOCKS_DOT_EXT = _T('.') + FileFilters::CODEBLOCKS_EXT
Definition at line 206 of file filefilters.cpp.
Referenced by ProjectPathPanel::OntxtPrjTitleText(), and ScriptBindings::Register_Constants().
CODEBLOCKS_EXT
const wxString FileFilters::CODEBLOCKS_EXT = _T("cbp")
Definition at line 147 of file filefilters.cpp.
Referenced by cbProject::CreateUniqueFilename(), Associations::DoClearAssociation(), Associations::DoSetAssociation(), FileTypeOf(), ScriptBindings::Register_Constants(), and cbProject::SaveAs().
CPLPL_DOT_EXT
const wxString FileFilters::CPLPL_DOT_EXT = _T('.') + FileFilters::CPLPL_EXT
Definition at line 232 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
CPLPL_EXT
const wxString FileFilters::CPLPL_EXT = _T("c++")
Definition at line 173 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
CPP_DOT_EXT
const wxString FileFilters::CPP_DOT_EXT = _T('.') + FileFilters::CPP_EXT
Definition at line 228 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
CPP_EXT
const wxString FileFilters::CPP_EXT = _T("cpp")
Definition at line 169 of file filefilters.cpp.
Referenced by FileTypeOf(), ScriptBindings::Register_Constants(), and EditorManager::SwapActiveHeaderSource().
CXX_DOT_EXT
const wxString FileFilters::CXX_DOT_EXT = _T('.') + FileFilters::CXX_EXT
Definition at line 231 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
CXX_EXT
const wxString FileFilters::CXX_EXT = _T("cxx")
Definition at line 172 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
D_DOT_EXT
const wxString FileFilters::D_DOT_EXT = _T('.') + FileFilters::D_EXT
Definition at line 216 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
D_EXT
const wxString FileFilters::D_EXT = _T("d")
Definition at line 157 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
DEVCPP_DOT_EXT
const wxString FileFilters::DEVCPP_DOT_EXT = _T('.') + FileFilters::DEVCPP_EXT
Definition at line 207 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
DEVCPP_EXT
const wxString FileFilters::DEVCPP_EXT = _T("dev")
Definition at line 148 of file filefilters.cpp.
Referenced by FileTypeOf(), MainFrame::OnFileImportProjectDevCpp(), and ScriptBindings::Register_Constants().
DYNAMICLIB_DOT_EXT
const wxString FileFilters::DYNAMICLIB_DOT_EXT = _T('.') + FileFilters::DYNAMICLIB_EXT
Definition at line 250 of file filefilters.cpp.
Referenced by CompileTargetBase::GenerateTargetFilename(), PluginManager::InstallPlugin(), and ScriptBindings::Register_Constants().
DYNAMICLIB_EXT
const wxString FileFilters::DYNAMICLIB_EXT = _T("dll")
Definition at line 191 of file filefilters.cpp.
Referenced by FileTypeOf(), CompileTargetBase::GetDynamicLibFilename(), ProjectOptionsDlg::OnProjectTypeChanged(), and ScriptBindings::Register_Constants().
EXECUTABLE_DOT_EXT
const wxString FileFilters::EXECUTABLE_DOT_EXT = _T('.') + FileFilters::EXECUTABLE_EXT
Definition at line 251 of file filefilters.cpp.
Referenced by CompileTargetBase::GenerateTargetFilename(), and ScriptBindings::Register_Constants().
EXECUTABLE_EXT
const wxString FileFilters::EXECUTABLE_EXT = _T("exe")
Definition at line 192 of file filefilters.cpp.
Referenced by FileTypeOf(), CompilerCommandGenerator::GenerateCommandLine(), DirectCommands::GetCleanSingleFileCommand(), DirectCommands::GetCompileSingleFileCommand(), CompileTargetBase::GetExecutableFilename(), ProjectOptionsDlg::OnProjectTypeChanged(), ScriptBindings::Register_Constants(), and CompilerGCC::RunSingleFile().
F03_DOT_EXT
const wxString FileFilters::F03_DOT_EXT = _T('.') + FileFilters::F03_EXT
Definition at line 223 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
F03_EXT
const wxString FileFilters::F03_EXT = _T("f03")
Definition at line 164 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
F08_DOT_EXT
const wxString FileFilters::F08_DOT_EXT = _T('.') + FileFilters::F08_EXT
Definition at line 224 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
F08_EXT
const wxString FileFilters::F08_EXT = _T("f08")
Definition at line 165 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
F77_DOT_EXT
const wxString FileFilters::F77_DOT_EXT = _T('.') + FileFilters::F77_EXT
Definition at line 218 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
F77_EXT
const wxString FileFilters::F77_EXT = _T("f77")
Definition at line 159 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
F90_DOT_EXT
const wxString FileFilters::F90_DOT_EXT = _T('.') + FileFilters::F90_EXT
Definition at line 219 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
F90_EXT
const wxString FileFilters::F90_EXT = _T("f90")
Definition at line 160 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
F95_DOT_EXT
const wxString FileFilters::F95_DOT_EXT = _T('.') + FileFilters::F95_EXT
Definition at line 220 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
F95_EXT
const wxString FileFilters::F95_EXT = _T("f95")
Definition at line 161 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
F_DOT_EXT
const wxString FileFilters::F_DOT_EXT = _T('.') + FileFilters::F_EXT
Definition at line 217 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
F_EXT
const wxString FileFilters::F_EXT = _T("f")
Definition at line 158 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
FOR_DOT_EXT
const wxString FileFilters::FOR_DOT_EXT = _T('.') + FileFilters::FOR_EXT
Definition at line 221 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
FOR_EXT
const wxString FileFilters::FOR_EXT = _T("for")
Definition at line 162 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
FPP_DOT_EXT
const wxString FileFilters::FPP_DOT_EXT = _T('.') + FileFilters::FPP_EXT
Definition at line 222 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
FPP_EXT
const wxString FileFilters::FPP_EXT = _T("fpp")
Definition at line 163 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
H_DOT_EXT
const wxString FileFilters::H_DOT_EXT = _T('.') + FileFilters::H_EXT
Definition at line 234 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
H_EXT
const wxString FileFilters::H_EXT = _T("h")
Definition at line 175 of file filefilters.cpp.
Referenced by FileTypeOf(), ScriptBindings::Register_Constants(), and EditorManager::SwapActiveHeaderSource().
HH_DOT_EXT
const wxString FileFilters::HH_DOT_EXT = _T('.') + FileFilters::HH_EXT
Definition at line 235 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
HH_EXT
const wxString FileFilters::HH_EXT = _T("hh")
Definition at line 176 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
HPLPL_DOT_EXT
const wxString FileFilters::HPLPL_DOT_EXT = _T('.') + FileFilters::HPLPL_EXT
Definition at line 238 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
HPLPL_EXT
const wxString FileFilters::HPLPL_EXT = _T("h++")
Definition at line 179 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
HPP_DOT_EXT
const wxString FileFilters::HPP_DOT_EXT = _T('.') + FileFilters::HPP_EXT
Definition at line 236 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
HPP_EXT
const wxString FileFilters::HPP_EXT = _T("hpp")
Definition at line 177 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
HXX_DOT_EXT
const wxString FileFilters::HXX_DOT_EXT = _T('.') + FileFilters::HXX_EXT
Definition at line 237 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
HXX_EXT
const wxString FileFilters::HXX_EXT = _T("hxx")
Definition at line 178 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
INL_DOT_EXT
const wxString FileFilters::INL_DOT_EXT = _T('.') + FileFilters::INL_EXT
Definition at line 233 of file filefilters.cpp.
INL_EXT
const wxString FileFilters::INL_EXT = _T("inl")
Definition at line 174 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
JAVA_DOT_EXT
const wxString FileFilters::JAVA_DOT_EXT = _T('.') + FileFilters::JAVA_EXT
Definition at line 225 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
JAVA_EXT
const wxString FileFilters::JAVA_EXT = _T("java")
Definition at line 166 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
MSVC10_DOT_EXT
const wxString FileFilters::MSVC10_DOT_EXT = _T('.') + FileFilters::MSVC10_EXT
Definition at line 210 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
MSVC10_EXT
const wxString FileFilters::MSVC10_EXT = _T("vcxproj")
Definition at line 151 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
MSVC6_DOT_EXT
const wxString FileFilters::MSVC6_DOT_EXT = _T('.') + FileFilters::MSVC6_EXT
Definition at line 208 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
MSVC6_EXT
const wxString FileFilters::MSVC6_EXT = _T("dsp")
Definition at line 149 of file filefilters.cpp.
Referenced by FileTypeOf(), MainFrame::OnFileImportProjectMSVC(), and ScriptBindings::Register_Constants().
MSVC6_WORKSPACE_DOT_EXT
const wxString FileFilters::MSVC6_WORKSPACE_DOT_EXT = _T('.') + FileFilters::MSVC6_WORKSPACE_EXT
Definition at line 211 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
MSVC6_WORKSPACE_EXT
const wxString FileFilters::MSVC6_WORKSPACE_EXT = _T("dsw")
Definition at line 152 of file filefilters.cpp.
Referenced by FileTypeOf(), MainFrame::OnFileImportProjectMSVCWksp(), and ScriptBindings::Register_Constants().
MSVC7_DOT_EXT
const wxString FileFilters::MSVC7_DOT_EXT = _T('.') + FileFilters::MSVC7_EXT
Definition at line 209 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
MSVC7_EXT
const wxString FileFilters::MSVC7_EXT = _T("vcproj")
Definition at line 150 of file filefilters.cpp.
Referenced by FileTypeOf(), MainFrame::OnFileImportProjectMSVS(), and ScriptBindings::Register_Constants().
MSVC7_WORKSPACE_DOT_EXT
const wxString FileFilters::MSVC7_WORKSPACE_DOT_EXT = _T('.') + FileFilters::MSVC7_WORKSPACE_EXT
Definition at line 212 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
MSVC7_WORKSPACE_EXT
const wxString FileFilters::MSVC7_WORKSPACE_EXT = _T("sln")
Definition at line 153 of file filefilters.cpp.
Referenced by FileTypeOf(), MainFrame::OnFileImportProjectMSVSWksp(), and ScriptBindings::Register_Constants().
NATIVE_DOT_EXT
const wxString FileFilters::NATIVE_DOT_EXT = _T('.') + FileFilters::NATIVE_EXT
Definition at line 252 of file filefilters.cpp.
Referenced by CompileTargetBase::GenerateTargetFilename(), and ScriptBindings::Register_Constants().
NATIVE_EXT
const wxString FileFilters::NATIVE_EXT = _T("sys")
Definition at line 193 of file filefilters.cpp.
Referenced by FileTypeOf(), CompileTargetBase::GetNativeFilename(), and ProjectOptionsDlg::OnProjectTypeChanged().
OBJECT_DOT_EXT
const wxString FileFilters::OBJECT_DOT_EXT = _T('.') + FileFilters::OBJECT_EXT
Definition at line 242 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
OBJECT_EXT
const wxString FileFilters::OBJECT_EXT = _T("o")
Definition at line 183 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
RESOURCE_DOT_EXT
const wxString FileFilters::RESOURCE_DOT_EXT = _T('.') + FileFilters::RESOURCE_EXT
Definition at line 245 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
RESOURCE_EXT
const wxString FileFilters::RESOURCE_EXT = _T("rc")
Definition at line 186 of file filefilters.cpp.
Referenced by cbProject::AddFile(), ProjectLoader::ExportTargetAsProject(), FileTypeOf(), and ScriptBindings::Register_Constants().
RESOURCEBIN_DOT_EXT
const wxString FileFilters::RESOURCEBIN_DOT_EXT = _T('.') + FileFilters::RESOURCEBIN_EXT
Definition at line 246 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants(), ProjectFile::SetObjName(), and pfDetails::Update().
RESOURCEBIN_EXT
const wxString FileFilters::RESOURCEBIN_EXT = _T("res")
Definition at line 187 of file filefilters.cpp.
Referenced by FileTypeOf(), ScriptBindings::Register_Constants(), ProjectFile::SetObjName(), and pfDetails::Update().
S62_DOT_EXT
const wxString FileFilters::S62_DOT_EXT = _T('.') + FileFilters::S62_EXT
Definition at line 241 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
S62_EXT
const wxString FileFilters::S62_EXT = _T("s62")
Definition at line 182 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
S_DOT_EXT
const wxString FileFilters::S_DOT_EXT = _T('.') + FileFilters::S_EXT
Definition at line 239 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
S_EXT
const wxString FileFilters::S_EXT = _T("s")
Definition at line 180 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
SCRIPT_DOT_EXT
const wxString FileFilters::SCRIPT_DOT_EXT = _T('.') + FileFilters::SCRIPT_EXT
Definition at line 248 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
SCRIPT_EXT
const wxString FileFilters::SCRIPT_EXT = _T("script")
Definition at line 189 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
SS_DOT_EXT
const wxString FileFilters::SS_DOT_EXT = _T('.') + FileFilters::SS_EXT
Definition at line 240 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
SS_EXT
const wxString FileFilters::SS_EXT = _T("ss")
Definition at line 181 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
STATICLIB_DOT_EXT
const wxString FileFilters::STATICLIB_DOT_EXT = _T('.') + FileFilters::STATICLIB_EXT
Definition at line 244 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
STATICLIB_EXT
const wxString FileFilters::STATICLIB_EXT = _T("a")
Definition at line 185 of file filefilters.cpp.
Referenced by FileTypeOf(), CompileTargetBase::GenerateTargetFilename(), CompileTargetBase::GetStaticLibFilename(), ProjectOptionsDlg::OnProjectTypeChanged(), and ScriptBindings::Register_Constants().
TCC_DOT_EXT
const wxString FileFilters::TCC_DOT_EXT = _T('.') + FileFilters::TCC_EXT
Definition at line 230 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
TCC_EXT
const wxString FileFilters::TCC_EXT = _T("tcc")
Definition at line 171 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
TPP_DOT_EXT
const wxString FileFilters::TPP_DOT_EXT = _T('.') + FileFilters::TPP_EXT
Definition at line 229 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
TPP_EXT
const wxString FileFilters::TPP_EXT = _T("tpp")
Definition at line 170 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
WORKSPACE_DOT_EXT
const wxString FileFilters::WORKSPACE_DOT_EXT = _T('.') + FileFilters::WORKSPACE_EXT
Definition at line 205 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
WORKSPACE_EXT
const wxString FileFilters::WORKSPACE_EXT = _T("workspace")
Definition at line 146 of file filefilters.cpp.
Referenced by Associations::DoClearAssociation(), Associations::DoSetAssociation(), FileTypeOf(), cbWorkspace::Load(), ScriptBindings::Register_Constants(), and cbWorkspace::SaveAs().
XCODE1_DOT_EXT
const wxString FileFilters::XCODE1_DOT_EXT = _T('.') + FileFilters::XCODE1_EXT
Definition at line 213 of file filefilters.cpp.
XCODE1_EXT
const wxString FileFilters::XCODE1_EXT = _T("xcode")
Definition at line 154 of file filefilters.cpp.
Referenced by FileTypeOf().
XCODE2_DOT_EXT
const wxString FileFilters::XCODE2_DOT_EXT = _T('.') + FileFilters::XCODE2_EXT
Definition at line 214 of file filefilters.cpp.
XCODE2_EXT
const wxString FileFilters::XCODE2_EXT = _T("xcodeproj")
Definition at line 155 of file filefilters.cpp.
Referenced by FileTypeOf().
XML_DOT_EXT
const wxString FileFilters::XML_DOT_EXT = _T('.') + FileFilters::XML_EXT
Definition at line 247 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
XML_EXT
const wxString FileFilters::XML_EXT = _T("xml")
Definition at line 188 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().
XRCRESOURCE_DOT_EXT
const wxString FileFilters::XRCRESOURCE_DOT_EXT = _T('.') + FileFilters::XRCRESOURCE_EXT
Definition at line 243 of file filefilters.cpp.
Referenced by ScriptBindings::Register_Constants().
XRCRESOURCE_EXT
const wxString FileFilters::XRCRESOURCE_EXT = _T("xrc")
Definition at line 184 of file filefilters.cpp.
Referenced by FileTypeOf(), and ScriptBindings::Register_Constants().