Code::Blocks: ParserConsts Namespace Reference
ParserConsts Namespace Reference
Functions
const wxString empty (_T(""))
const wxChar null (_T('\0'))
const wxChar eol_chr (_T('\n'))
const wxString space (_T(" "))
const wxChar space_chr (_T(' '))
const wxChar tab_chr (_T('\t'))
const wxString equals (_T("="))
const wxChar equals_chr (_T('='))
const wxString hash (_T("#"))
const wxChar hash_chr (_T('#'))
const wxString plus (_T("+"))
const wxChar plus_chr (_T('+'))
const wxString dash (_T("-"))
const wxChar dash_chr (_T('-'))
const wxString ptr (_T("*"))
const wxChar ptr_chr (_T(' *'))
const wxString ref (_T("&"))
const wxChar ref_chr (_T('&'))
const wxString comma (_T(","))
const wxChar comma_chr (_T(','))
const wxString dot (_T("."))
const wxChar dot_chr (_T('.'))
const wxString colon (_T(":"))
const wxChar colon_chr (_T(':'))
const wxString semicolon (_T(";"))
const wxChar semicolon_chr (_T(';'))
const wxChar opbracket_chr (_T('('))
const wxChar clbracket_chr (_T(')'))
const wxString opbracket (_T("("))
const wxString clbracket (_T(")"))
const wxString opbrace (_T("{"))
const wxChar opbrace_chr (_T('{'))
const wxString clbrace (_T("}"))
const wxChar clbrace_chr (_T('}'))
const wxString oparray (_T("["))
const wxChar oparray_chr (_T('['))
const wxString clarray (_T("]"))
const wxChar clarray_chr (_T(']'))
const wxString tilde (_T("~"))
const wxString lt (_T("<"))
const wxChar lt_chr (_T('<'))
const wxString gt (_T(">"))
const wxChar gt_chr (_T('>'))
const wxChar underscore_chr (_T('_'))
const wxChar question_chr (_T('?'))
const wxString dcolon (_T("::"))
const wxString opbracesemicolon (_T("{;"))
const wxString commaclbrace (_T(",}"))
const wxString semicolonopbrace (_T(";{"))
const wxString semicolonclbrace (_T(";}"))
const wxString gtsemicolon (_T(">;"))
const wxString quot (_T("\))
const wxString kw_do (_T("do"))
const wxString kw_if (_T("if"))
const wxString spaced_colon (_T(" : "))
const wxString kw__C_ (_T("\\))
const wxString kw_for (_T("for"))
const wxString kw_try (_T("try"))
const wxString commasemicolonopbrace (_T(",;{"))
const wxString kw___at (_T("__at"))
const wxString kw_else (_T("else"))
const wxString kw_enum (_T("enum"))
const wxString kw_elif (_T("elif"))
const wxString kw_case (_T("case"))
const wxString kw__CPP_ (_T("\++\))
const wxString kw___asm (_T("__asm"))
const wxString kw_catch (_T("catch"))
const wxString kw_class (_T("class"))
const wxString kw_const (_T("const"))
const wxString kw_union (_T("union"))
const wxString kw_using (_T("using"))
const wxString kw_throw (_T("throw"))
const wxString kw_while (_T("while"))
const wxString kw_delete (_T("delete"))
const wxString kw_extern (_T("extern"))
const wxString kw_friend (_T("friend"))
const wxString kw_inline (_T("inline"))
const wxString kw_public (_T("public"))
const wxString kw_return (_T("return"))
const wxString kw_static (_T("static"))
const wxString kw_struct (_T("struct"))
const wxString kw_switch (_T("switch"))
const wxString kw_include (_T("include"))
const wxString kw_private (_T("private"))
const wxString kw_typedef (_T("typedef"))
const wxString kw_virtual (_T("virtual"))
const wxString kw_noexcept (_T("noexcept"))
const wxString kw_operator (_T("operator"))
const wxString kw_template (_T("template"))
const wxString kw_typename (_T("typename"))
const wxString kw_volatile (_T("volatile"))
const wxString kw_namespace (_T("namespace"))
const wxString kw_protected (_T("protected"))
const wxString kw_declspec (_T("__declspec"))
const wxString kw_attribute (_T("__attribute__"))
Function Documentation
clarray()
const wxString ParserConsts::clarray (_T("]"))
Referenced by ParserThread::DoParse(), and ParserThread::ReadVarNames().
clarray_chr()
const wxChar ParserConsts::clarray_chr (_T(']'))
Referenced by ParserThread::GetBaseArgs().
clbrace()
const wxString ParserConsts::clbrace (_T("}"))
Referenced by ParserThread::CalcEnumExpression(), ParserThread::HandleEnum(), ParserThread::HandleFunction(), and ParserThread::ParseBufferForNamespaces().
clbrace_chr()
const wxChar ParserConsts::clbrace_chr (_T('}'))
Referenced by ParserThread::DoParse().
clbracket()
const wxString ParserConsts::clbracket (_T(")")
clbracket_chr()
const wxChar ParserConsts::clbracket_chr (_T(')')
Referenced by ParserThread::GetBaseArgs(), and ParserThread::HandleTypedef().
colon()
const wxString ParserConsts::colon (_T(":"))
Referenced by ParserThread::DoParse(), ParserThread::HandleClass(), ParserThread::HandleEnum(), ParserThread::HandleForLoopArguments(), and ParserThread::HandleFunction().
colon_chr()
const wxChar ParserConsts::colon_chr (_T(':'))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), and ParserThread::GetTokenBaseType().
comma()
const wxString ParserConsts::comma (_T(","))
Referenced by ParserThread::CalcEnumExpression(), ParserThread::DoParse(), ParserThread::HandleClass(), ParserThread::HandleEnum(), ParserThread::HandleForLoopArguments(), ParserThread::HandleTypedef(), ParserThread::ReadClsNames(), ParserThread::ReadVarNames(), and ParserThread::SplitTemplateActualParameters().
comma_chr()
const wxChar ParserConsts::comma_chr (_T(','))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::GetTemplateArgArray(), and ParserThread::HandleClass().
commaclbrace()
const wxString ParserConsts::commaclbrace (_T(",}"))
Referenced by ParserThread::CalcEnumExpression(), and ParserThread::HandleEnum().
commasemicolonopbrace()
const wxString ParserConsts::commasemicolonopbrace (_T(",;{"))
Referenced by ParserThread::DoParse().
dash()
const wxString ParserConsts::dash (_T("-"))
Referenced by ParserThread::DoParse().
dash_chr()
const wxChar ParserConsts::dash_chr (_T('-'))
Referenced by ParserThread::DoParse().
dcolon()
const wxString ParserConsts::dcolon (_T("::"))
Referenced by ParserThread::CalcEnumExpression(), ParserThread::DoAddToken(), ParserThread::DoParse(), Token::GetNamespace(), ParserThread::HandleClass(), ParserThread::HandleNamespace(), ParserThread::HandleTypedef(), ParserThread::ParseBufferForNamespaces(), and ParserThread::ParseBufferForUsingNamespace().
dot()
const wxString ParserConsts::dot (_T("."))
dot_chr()
const wxChar ParserConsts::dot_chr (_T('.'))
Referenced by ParserThread::DoParse().
empty()
const wxString ParserConsts::empty (_T(""))
Referenced by CompilerOptionsDlg::AutoDetectCompiler(), CompilerFactory::GetDefaultCompilerID(), and cbAuiNotebook::SavePerspective().
eol_chr()
const wxChar ParserConsts::eol_chr (_T('\n'))
Referenced by ParserThread::GetBaseArgs().
equals()
const wxString ParserConsts::equals (_T("="))
Referenced by ParserThread::DoParse(), ParserThread::HandleClass(), ParserThread::HandleEnum(), ParserThread::HandleForLoopArguments(), ParserThread::HandleFunction(), ParserThread::HandleNamespace(), and ParserThread::ParseBufferForNamespaces().
equals_chr()
const wxChar ParserConsts::equals_chr (_T('='))
Referenced by ParserThread::DoParse().
gt()
const wxString ParserConsts::gt (_T(">"))
Referenced by ParserThread::GetTemplateArgs(), ParserThread::HandleClass(), ParserThread::RemoveTemplateArgs(), ParserThread::SkipAngleBraces(), and ParserThread::SplitTemplateActualParameters().
gt_chr()
const wxChar ParserConsts::gt_chr (_T('>'))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::GetTemplateArgArray(), ParserThread::HandleIncludes(), and ParserThread::RemoveTemplateArgs().
gtsemicolon()
const wxString ParserConsts::gtsemicolon (_T(">;"))
hash()
const wxString ParserConsts::hash (_T("#"))
hash_chr()
const wxChar ParserConsts::hash_chr (_T('#'))
Referenced by ParserThread::DoParse().
kw___asm()
const wxString ParserConsts::kw___asm (_T("__asm"))
Referenced by ParserThread::DoParse().
kw___at()
const wxString ParserConsts::kw___at (_T("__at"))
Referenced by ParserThread::DoParse().
kw__C_()
const wxString ParserConsts::kw__C_ (_T("\))
Referenced by ParserThread::DoParse().
kw__CPP_()
const wxString ParserConsts::kw__CPP_ (_T("\\)
Referenced by ParserThread::DoParse().
kw_attribute()
const wxString ParserConsts::kw_attribute (_T("__attribute__"))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), and ParserThread::HandleClass().
kw_case()
const wxString ParserConsts::kw_case (_T("case"))
Referenced by ParserThread::DoParse().
kw_catch()
const wxString ParserConsts::kw_catch (_T("catch"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleFunction().
kw_class()
const wxString ParserConsts::kw_class (_T("class"))
Referenced by ParserThread::DoParse(), ParserThread::HandleEnum(), ParserThread::HandleTypedef(), and ParserThread::SplitTemplateFormalParameters().
kw_const()
const wxString ParserConsts::kw_const (_T("const"))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::GetTokenBaseType(), ParserThread::HandleFunction(), and ParserThread::HandleTypedef().
kw_declspec()
const wxString ParserConsts::kw_declspec (_T("__declspec"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleClass().
kw_delete()
const wxString ParserConsts::kw_delete (_T("delete"))
Referenced by ParserThread::DoParse().
kw_do()
const wxString ParserConsts::kw_do (_T("do"))
Referenced by ParserThread::DoParse().
kw_elif()
const wxString ParserConsts::kw_elif (_T("elif"))
kw_else()
const wxString ParserConsts::kw_else (_T("else"))
Referenced by ParserThread::DoParse().
kw_enum()
const wxString ParserConsts::kw_enum (_T("enum"))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), and ParserThread::HandleTypedef().
kw_extern()
const wxString ParserConsts::kw_extern (_T("extern"))
Referenced by ParserThread::DoParse().
kw_for()
const wxString ParserConsts::kw_for (_T("for"))
Referenced by ParserThread::DoParse().
kw_friend()
const wxString ParserConsts::kw_friend (_T("friend"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleFunction().
kw_if()
const wxString ParserConsts::kw_if (_T("if"))
Referenced by ParserThread::DoParse().
kw_include()
const wxString ParserConsts::kw_include (_T("include"))
Referenced by ParserThread::DoParse().
kw_inline()
const wxString ParserConsts::kw_inline (_T("inline"))
Referenced by ParserThread::DoParse().
kw_namespace()
const wxString ParserConsts::kw_namespace (_T("namespace"))
Referenced by ParserThread::DoParse(), ParserThread::ParseBufferForNamespaces(), and ParserThread::ParseBufferForUsingNamespace().
kw_noexcept()
const wxString ParserConsts::kw_noexcept (_T("noexcept"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleFunction().
kw_operator()
const wxString ParserConsts::kw_operator (_T("operator"))
Referenced by ParserThread::DoParse().
kw_private()
const wxString ParserConsts::kw_private (_T("private"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleClass().
kw_protected()
const wxString ParserConsts::kw_protected (_T("protected"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleClass().
kw_public()
const wxString ParserConsts::kw_public (_T("public"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleClass().
kw_return()
const wxString ParserConsts::kw_return (_T("return"))
Referenced by ParserThread::DoParse().
kw_static()
const wxString ParserConsts::kw_static (_T("static"))
Referenced by ParserThread::DoParse().
kw_struct()
const wxString ParserConsts::kw_struct (_T("struct"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleTypedef().
kw_switch()
const wxString ParserConsts::kw_switch (_T("switch"))
Referenced by ParserThread::DoParse().
kw_template()
const wxString ParserConsts::kw_template (_T("template"))
Referenced by ParserThread::DoParse().
kw_throw()
const wxString ParserConsts::kw_throw (_T("throw"))
Referenced by ParserThread::HandleFunction().
kw_try()
const wxString ParserConsts::kw_try (_T("try"))
Referenced by ParserThread::HandleFunction().
kw_typedef()
const wxString ParserConsts::kw_typedef (_T("typedef"))
Referenced by ParserThread::DoParse().
kw_typename()
const wxString ParserConsts::kw_typename (_T("typename"))
Referenced by ParserThread::SplitTemplateFormalParameters().
kw_union()
const wxString ParserConsts::kw_union (_T("union"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleTypedef().
kw_using()
const wxString ParserConsts::kw_using (_T("using"))
Referenced by ParserThread::DoParse(), ParserThread::ParseBufferForNamespaces(), and ParserThread::ParseBufferForUsingNamespace().
kw_virtual()
const wxString ParserConsts::kw_virtual (_T("virtual"))
Referenced by ParserThread::DoParse().
kw_volatile()
const wxString ParserConsts::kw_volatile (_T("volatile"))
Referenced by ParserThread::DoParse(), and ParserThread::GetBaseArgs().
kw_while()
const wxString ParserConsts::kw_while (_T("while"))
Referenced by ParserThread::DoParse().
lt()
const wxString ParserConsts::lt (_T("<"))
Referenced by CompilerErrors::AddError(), ParserThread::DoParse(), CompilerOptionsDlg::DoSaveCompilerDefinition(), ParserThread::GetTemplateArgs(), ParserThread::HandleClass(), ParserThread::HandleTypedef(), ParserThread::RemoveTemplateArgs(), ParserThread::SkipAngleBraces(), and ParserThread::SplitTemplateActualParameters().
lt_chr()
const wxChar ParserConsts::lt_chr (_T('<'))
Referenced by ParserThread::GetBaseArgs(), ParserThread::GetTemplateArgArray(), ParserThread::HandleIncludes(), ParserThread::HandleTypedef(), and ParserThread::RemoveTemplateArgs().
null()
const wxChar ParserConsts::null (_T('\0'))
Referenced by ParserThread::GetBaseArgs(), and ParserThread::SkipToOneOfChars().
oparray()
const wxString ParserConsts::oparray (_T("["))
Referenced by ParserThread::ReadVarNames().
oparray_chr()
const wxChar ParserConsts::oparray_chr (_T('['))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), and ParserThread::HandleFunction().
opbrace()
const wxString ParserConsts::opbrace (_T("{"))
Referenced by ParserThread::DoParse(), ParserThread::HandleClass(), ParserThread::HandleEnum(), ParserThread::HandleFunction(), ParserThread::HandleNamespace(), ParserThread::ParseBufferForNamespaces(), and ParserThread::ParseBufferForUsingNamespace().
opbrace_chr()
const wxChar ParserConsts::opbrace_chr (_T('{'))
Referenced by ParserThread::DoParse(), and ParserThread::HandleEnum().
opbracesemicolon()
const wxString ParserConsts::opbracesemicolon (_T("{;"))
opbracket()
const wxString ParserConsts::opbracket ()
opbracket_chr()
const wxChar ParserConsts::opbracket_chr ()
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::HandleClass(), and ParserThread::HandleTypedef().
plus()
const wxString ParserConsts::plus (_T("+"))
plus_chr()
const wxChar ParserConsts::plus_chr (_T('+'))
Referenced by ParserThread::DoParse().
ptr()
const wxString ParserConsts::ptr (_T("*"))
Referenced by BlockAllocator< T, pool_size, debug >::AllocBlockPushBack(), cbThreadPool::CountedPtr< wxSemaphore >::dispose(), ParserThread::DoParse(), NativeParserBase::GenerateResultSet(), ParserThread::GetBaseArgs(), ParserThread::HandleFunction(), ParserThread::HandleTypedef(), CodeCompletion::OnGotoFunction(), BlockAllocated< T, pool_size, debug >::operator delete(), cbThreadPool::CountedPtr< wxSemaphore >::operator*(), cbThreadPool::CountedPtr< wxSemaphore >::operator->(), ConfigManager::ReadAppPath(), ParserThread::ReadClsNames(), and ParserThread::ReadVarNames().
ptr_chr()
const wxChar ParserConsts::ptr_chr (_T(' *'))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::GetTokenBaseType(), ParserThread::HandleClass(), ParserThread::HandleConditionalArguments(), ParserThread::HandleForLoopArguments(), and ParserThread::HandleTypedef().
question_chr()
const wxChar ParserConsts::question_chr (_T('?'))
Referenced by ParserThread::DoParse().
quot()
const wxString ParserConsts::quot (_T("\)
ref()
const wxString ParserConsts::ref (_T("&"))
Referenced by CreateDefaultDelegate(), ParserThread::HandleTypedef(), and DirectCommands::IsObjectOutdated().
ref_chr()
const wxChar ParserConsts::ref_chr (_T('&'))
Referenced by ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::GetTokenBaseType(), ParserThread::HandleClass(), ParserThread::HandleConditionalArguments(), and ParserThread::HandleForLoopArguments().
semicolon()
const wxString ParserConsts::semicolon (_T(";"))
Referenced by ParserThread::DoParse(), ParserThread::GetTemplateArgs(), ParserThread::HandleClass(), ParserThread::HandleEnum(), ParserThread::HandleForLoopArguments(), ParserThread::HandleFunction(), ParserThread::HandleTypedef(), ParserThread::ReadClsNames(), ParserThread::ReadVarNames(), and ParserThread::SkipAngleBraces().
semicolon_chr()
const wxChar ParserConsts::semicolon_chr (_T(';'))
Referenced by ParserThread::DoParse().
semicolonclbrace()
const wxString ParserConsts::semicolonclbrace (_T(";}"))
Referenced by ParserThread::DoParse(), ParserThread::ParseBufferForNamespaces(), and ParserThread::ParseBufferForUsingNamespace().
semicolonopbrace()
const wxString ParserConsts::semicolonopbrace (_T(";{"))
Referenced by ParserThread::DoParse(), and ParserThread::HandleNamespace().
space()
const wxString ParserConsts::space (_T(" "))
Referenced by cbEditorInternalData::GetUrl(), ParserThread::HandleClass(), ParserThread::RemoveTemplateArgs(), and wxScintilla::wxScintilla().
space_chr()
const wxChar ParserConsts::space_chr (_T(' '))
Referenced by ParserThread::DoAddToken(), ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::GetTemplateArgArray(), ParserThread::HandleClass(), and ParserThread::HandleTypedef().
spaced_colon()
const wxString ParserConsts::spaced_colon (_T(" : "))
tab_chr()
const wxChar ParserConsts::tab_chr (_T('\t'))
tilde()
const wxString ParserConsts::tilde (_T("~"))
Referenced by ParserThread::DoAddToken(), and ParserThread::HandleFunction().
underscore_chr()
const wxChar ParserConsts::underscore_chr (_T('_'))
Referenced by ParserThread::CalcEnumExpression(), ParserThread::DoParse(), ParserThread::GetBaseArgs(), ParserThread::GetTokenBaseType(), ParserThread::HandleEnum(), ParserThread::ReadClsNames(), and ParserThread::ReadVarNames().