Code::Blocks: LibLoader Namespace Reference
LibLoader Namespace Reference
Classes
struct RefCountedLib
Typedefs
typedef std::map< wxString, RefCountedLib > Libs
Functions
wxDynamicLibrary * LoadLibrary (const wxString &filename)
void RemoveLibrary (wxDynamicLibrary *lib)
void Cleanup ()
Variables
Libs s_Libs
Typedef Documentation
Libs
typedef std::map<wxString, RefCountedLib> LibLoader::Libs
Definition at line 98 of file pluginmanager.cpp.
Function Documentation
Cleanup()
void LibLoader::Cleanup () inline
Definition at line 143 of file pluginmanager.cpp.
References Manager::IsAppShuttingDown(), LibLoader::RefCountedLib::lib, and PluginManager::s_SafeMode.
Referenced by PluginManager::UnloadAllPlugins().
LoadLibrary()
wxDynamicLibrary* LibLoader::LoadLibrary (const wxString & filename) inline
Definition at line 101 of file pluginmanager.cpp.
References LibLoader::RefCountedLib::RefCountedLib().
Referenced by DebuggerGDB::DebuggerGDB(), PluginManager::LoadPlugin(), and UsesCommonControls6().
RemoveLibrary()
void LibLoader::RemoveLibrary (wxDynamicLibrary * lib) inline
Definition at line 118 of file pluginmanager.cpp.
References Manager::IsAppShuttingDown(), LibLoader::RefCountedLib::lib, and LibLoader::RefCountedLib::ref.
Referenced by PluginManager::LoadPlugin(), and PluginManager::UnloadPlugin().
Variable Documentation
s_Libs
Libs LibLoader::s_Libs
Definition at line 99 of file pluginmanager.cpp.