Code::Blocks: appglobals Namespace Reference
appglobals Namespace Reference
Classes
struct Localisation
Variables
const wxString AppVendor = _T("Code::Blocks")
const wxString AppName = _T("Code::Blocks")
const wxString AppVersion = _T("svn build")
const wxString AppActualVersionVerb = _T("svn build rev ") + ConfigManager::GetRevisionString()
const wxString AppActualVersion = _T("svn-r") + ConfigManager::GetRevisionString()
const wxString AppSDKVersion
const wxString AppUrl = _T("http://www.codeblocks.org")
const wxString AppContactEmail = _T("info@codeblocks.org")
const wxString AppPlatform = _T("Windows")
const wxString AppWXAnsiUnicode = platform::unicode ? wxT("unicode") : wxT("ANSI")
const wxString bit_type = wxT(" - 32 bit")
const wxString AppBuildTimestamp
const wxString DefaultBatchBuildArgs = _T("-na -nd -ns --batch-build-notify")
Class Documentation
appglobals::Localisation
struct appglobals::Localisation
Definition at line 21 of file appglobals.h.
Class Members
int locale_code
wxString name
Variable Documentation
AppActualVersion
const wxString appglobals::AppActualVersion = _T("svn-r") + ConfigManager::GetRevisionString()
Definition at line 27 of file appglobals.cpp.
Referenced by CodeBlocksApp::CheckVersion(), and StartHerePage::StartHerePage().
AppActualVersionVerb
const wxString appglobals::AppActualVersionVerb = _T("svn build rev ") + ConfigManager::GetRevisionString()
Definition at line 26 of file appglobals.cpp.
Referenced by dlgAbout::dlgAbout(), CodeBlocksApp::OnInit(), and StartHerePage::StartHerePage().
AppBuildTimestamp
const wxString appglobals::AppBuildTimestamp
Initial value:
= (wxString(wxT(__DATE__)) + wxT(", ")
                                            + wxT(__TIME__) + wxT(" - wx")
                                            + wxString(wxT(wxVERSION_NUM_DOT_STRING))
                                            + wxT(" (") + AppPlatform + wxT(", ")
                                            + AppWXAnsiUnicode + wxT(")") + bit_type )
Definition at line 66 of file appglobals.cpp.
Referenced by dlgAbout::dlgAbout(), and CodeBlocksApp::OnInit().
AppContactEmail
const wxString appglobals::AppContactEmail = _T("info@codeblocks.org")
Definition at line 40 of file appglobals.cpp.
Referenced by dlgAbout::dlgAbout().
AppName
const wxString appglobals::AppName = _T("Code::Blocks")
Definition at line 22 of file appglobals.cpp.
Referenced by dlgAbout::dlgAbout(), MainFrame::DoUpdateAppTitle(), MainFrame::DoUpdateStatusBar(), CodeBlocksApp::InitXRCStuff(), MainFrame::MainFrame(), CodeBlocksApp::OnBatchBuildDone(), CodeBlocksApp::OnFatalException(), and CodeBlocksApp::OnInit().
AppPlatform
const wxString appglobals::AppPlatform = _T("Windows")
Definition at line 43 of file appglobals.cpp.
Referenced by StartHerePage::StartHerePage().
AppSDKVersion
const wxString appglobals::AppSDKVersion
Initial value:
= wxString::Format(wxT("%d.%d.%d"),
                                                            static_cast<int>(PLUGIN_SDK_VERSION_MAJOR),
                                                            static_cast<int>(PLUGIN_SDK_VERSION_MINOR),
                                                            static_cast<int>(PLUGIN_SDK_VERSION_RELEASE))
Definition at line 34 of file appglobals.cpp.
Referenced by dlgAbout::dlgAbout().
AppUrl
const wxString appglobals::AppUrl = _T("http://www.codeblocks.org")
Definition at line 39 of file appglobals.cpp.
Referenced by dlgAbout::dlgAbout().
AppVendor
const wxString appglobals::AppVendor = _T("Code::Blocks")
Definition at line 21 of file appglobals.cpp.
AppVersion
const wxString appglobals::AppVersion = _T("svn build")
Definition at line 25 of file appglobals.cpp.
Referenced by dlgAbout::dlgAbout(), MainFrame::DoUpdateAppTitle(), and MainFrame::MainFrame().
AppWXAnsiUnicode
const wxString appglobals::AppWXAnsiUnicode = platform::unicode ? wxT("unicode") : wxT("ANSI")
Definition at line 58 of file appglobals.cpp.
Referenced by StartHerePage::StartHerePage().
bit_type
const wxString appglobals::bit_type = wxT(" - 32 bit")
Definition at line 63 of file appglobals.cpp.
Referenced by StartHerePage::StartHerePage().
DefaultBatchBuildArgs
const wxString appglobals::DefaultBatchBuildArgs = _T("-na -nd -ns --batch-build-notify")
Definition at line 72 of file appglobals.cpp.
Referenced by CompilerSettingsDlg::CompilerSettingsDlg(), Associations::DoClearAssociation(), Associations::DoSetAssociation(), and CompilerSettingsDlg::EndModal().