Code::Blocks: ProjectLoaderHooks Namespace Reference
ProjectLoaderHooks Namespace Reference
Provides static functions to add hooks to the project loading/saving procedure.
Classes
class HookFunctor
Functor class for use as a project loading/saving hook.
class HookFunctorBase
Abstract base hook functor interface.
Typedefs
typedef std::map< int, HookFunctorBase * > HookFunctorsMap
Functions
DLLIMPORT int RegisterHook (HookFunctorBase *functor)
Register a project loading/saving hook.
DLLIMPORT HookFunctorBase * UnregisterHook (int id, bool deleteHook=true)
Unregister a previously registered project loading/saving hook.
DLLIMPORT bool HasRegisteredHooks ()
Are there any hooks registered?
DLLIMPORT void CallHooks (cbProject *project, TiXmlElement *elem, bool isLoading)
Call all registered hooks using the supplied parameters.
Variables
static HookFunctorsMap s_HookFunctorsMap
static int s_UniqueID = 0
Detailed Description
Provides static functions to add hooks to the project loading/saving procedure.
Typedef Documentation
typedef std::map<int, HookFunctorBase*> ProjectLoaderHooks::HookFunctorsMap
Function Documentation
void ProjectLoaderHooks::CallHooks (cbProject * project, TiXmlElement * elem, bool isLoading)
Call all registered hooks using the supplied parameters.
This is called by ProjectLoader.
Parameters
project The project in question.
elem The XML element under which the called hook can read/write.
isLoading True if the project is being loaded, false if being saved.
References ProjectLoaderHooks::HookFunctorBase::Call(), and s_HookFunctorsMap.
Referenced by ProjectLoader::ExportTargetAsProject(), and ProjectLoader::Open().
bool ProjectLoaderHooks::HasRegisteredHooks ()
Are there any hooks registered?
Returns
True if any hooks are registered, false if none.
References s_HookFunctorsMap.
Referenced by ProjectLoader::ExportTargetAsProject().
int ProjectLoaderHooks::RegisterHook (ProjectLoaderHooks::HookFunctorBase * functor)
Register a project loading/saving hook.
Parameters
functor The functor to use as a callback.
Returns
An ID. Use this to unregister your hook later.
References s_HookFunctorsMap, and s_UniqueID.
Referenced by NativeParser::NativeParser(), and DebuggerGDB::OnAttachReal().
ProjectLoaderHooks::HookFunctorBase * ProjectLoaderHooks::UnregisterHook (int id, bool deleteHook = true)
Unregister a previously registered project loading/saving hook.
Parameters
id The hook's ID. You should have the ID from when RegisterHook() was called.
deleteHook If true, the hook will be deleted (default). If not, it's up to you to delete it.
Returns
The functor. If deleteHook was true, it always returns NULL.
References s_HookFunctorsMap.
Referenced by DebuggerGDB::OnReleaseReal(), and NativeParser::~NativeParser().
Variable Documentation
HookFunctorsMap ProjectLoaderHooks::s_HookFunctorsMap static
Referenced by CallHooks(), HasRegisteredHooks(), RegisterHook(), and UnregisterHook().
int ProjectLoaderHooks::s_UniqueID = 0 static
Referenced by RegisterHook().