Code::Blocks: SqPlus Namespace Reference
SqPlus Namespace Reference
Classes
struct TypeInfo< unsigned short >
Functions
static SQInteger getVarInfo (StackHandler &sa, VarRefPtr &vr)
static SQInteger getInstanceVarInfo (StackHandler &sa, VarRefPtr &vr, SQUserPointer &data)
static SQInteger setVar (StackHandler &sa, VarRef *vr, void *data)
static SQInteger getVar (StackHandler &sa, VarRef *vr, void *data)
SQInteger setVarFunc (HSQUIRRELVM v)
SQInteger getVarFunc (HSQUIRRELVM v)
SQInteger setInstanceVarFunc (HSQUIRRELVM v)
SQInteger getInstanceVarFunc (HSQUIRRELVM v)
BOOL_T CreateClass (HSQUIRRELVM v, SquirrelObject &newClass, SQUserPointer classType, const SQChar *name, const SQChar *baseName)
SquirrelObject RegisterClassType (HSQUIRRELVM v, const SQChar *scriptClassName, SQUserPointer classType, SQFUNCTION constructor)
Function Documentation
CreateClass()
BOOL_T SqPlus::CreateClass (HSQUIRRELVM v, SquirrelObject & newClass, SQUserPointer classType, const SQChar * name, const SQChar * baseName)
Definition at line 262 of file SqPlus.cpp.
References sq_get(), sq_gettop(), sq_newclass(), sq_pop(), sq_pushroottable(), sq_pushstring(), sq_settop(), and sq_settypetag().
Referenced by RegisterClassType().
getInstanceVarFunc()
SQInteger SqPlus::getInstanceVarFunc (HSQUIRRELVM v)
Definition at line 248 of file SqPlus.cpp.
References getInstanceVarInfo(), and getVar().
getInstanceVarInfo()
static SQInteger SqPlus::getInstanceVarInfo (StackHandler & sa, VarRefPtr & vr, SQUserPointer & data) static
Definition at line 24 of file SqPlus.cpp.
Referenced by getInstanceVarFunc(), and setInstanceVarFunc().
getVar()
static SQInteger SqPlus::getVar (StackHandler & sa, VarRef * vr, void * data) static
Definition at line 137 of file SqPlus.cpp.
References CreateNativeClassInstance().
Referenced by getInstanceVarFunc(), and getVarFunc().
getVarFunc()
SQInteger SqPlus::getVarFunc (HSQUIRRELVM v)
Definition at line 223 of file SqPlus.cpp.
References getVar(), and getVarInfo().
getVarInfo()
static SQInteger SqPlus::getVarInfo (StackHandler & sa, VarRefPtr & vr) static
Definition at line 6 of file SqPlus.cpp.
Referenced by getVarFunc(), and setVarFunc().
RegisterClassType()
SquirrelObject SqPlus::RegisterClassType (HSQUIRRELVM v, const SQChar * scriptClassName, SQUserPointer classType, SQFUNCTION constructor)
Definition at line 286 of file SqPlus.cpp.
References CreateClass(), sq_gettop(), and sq_settop().
setInstanceVarFunc()
SQInteger SqPlus::setInstanceVarFunc (HSQUIRRELVM v)
Definition at line 236 of file SqPlus.cpp.
References getInstanceVarInfo(), and setVar().
setVar()
static SQInteger SqPlus::setVar (StackHandler & sa, VarRef * vr, void * data) static
Definition at line 63 of file SqPlus.cpp.
References CreateNativeClassInstance().
Referenced by setInstanceVarFunc(), and setVarFunc().
setVarFunc()
SQInteger SqPlus::setVarFunc (HSQUIRRELVM v)
Definition at line 212 of file SqPlus.cpp.
References getVarInfo(), and setVar().