Code::Blocks: Associations Namespace Reference
Associations Namespace Reference
Classes
struct Assoc
Functions
unsigned int CountAssocs ()
void SetCore ()
void SetAll ()
void ClearAll ()
void SetBatchBuildOnly ()
bool Check ()
void DoSetAssociation (const wxString &ext, const wxString &descr, const wxString &exe, int icoNum)
bool DoCheckAssociation (const wxString &ext, const wxString &descr, const wxString &exe, int icoNum)
void DoClearAssociation (const wxString &ext)
void UpdateChanges ()
Class Documentation
Associations::Assoc
struct Associations::Assoc
Definition at line 32 of file associations.h.
Class Members
wxString descr
wxString ext
int index
Function Documentation
Check()
bool Associations::Check ()
Definition at line 133 of file associations.cpp.
References DoCheckAssociation().
Referenced by CodeBlocksApp::InitAssociations(), and EditorManager::OnPageContextMenu().
ClearAll()
void Associations::ClearAll ()
Definition at line 122 of file associations.cpp.
References CountAssocs(), DoClearAssociation(), and UpdateChanges().
Referenced by ManageAssocsDialog::OnClearAll(), and wxScintilla::wxScintilla().
CountAssocs()
unsigned int Associations::CountAssocs ()
Definition at line 79 of file associations.cpp.
References knownTypes.
Referenced by ClearAll(), ManageAssocsDialog::ManageAssocsDialog(), and SetAll().
DoCheckAssociation()
bool Associations::DoCheckAssociation (const wxString & ext, const wxString & descr, const wxString & exe, int icoNum)
Referenced by DoCheckAssociation(), DoClearAssociation(), and ManageAssocsDialog::ManageAssocsDialog().
DoClearAssociation()
void Associations::DoClearAssociation (const wxString & ext)
Definition at line 200 of file associations.cpp.
References _T, wxString::c_str(), FileFilters::CODEBLOCKS_EXT, DDE_SERVICE, DDE_TOPIC, appglobals::DefaultBatchBuildArgs, wxRegKey::DeleteSelf(), DoCheckAssociation(), wxRegKey::Exists(), wxString::Format(), Manager::Get(), Manager::GetConfigManager(), wxString::IsSameAs(), NULL, ManageAssocsDialog::OnApply(), ManageAssocsDialog::OnCancel(), ManageAssocsDialog::OnClearAll(), wxRegKey::Open(), wxRegKey::QueryValue(), ConfigManager::Read(), wxRegKey::SetName(), wxString::StartsWith(), platform::WindowsVersion(), platform::winver_Windows9598ME, FileFilters::WORKSPACE_EXT, and wxEmptyString.
Referenced by ClearAll(), and ManageAssocsDialog::OnApply().
DoSetAssociation()
void Associations::DoSetAssociation (const wxString & ext, const wxString & descr, const wxString & exe, int icoNum)
Definition at line 146 of file associations.cpp.
References _T, FileFilters::CODEBLOCKS_EXT, wxRegKey::Create(), DDE_SERVICE, DDE_TOPIC, appglobals::DefaultBatchBuildArgs, wxString::Format(), Manager::Get(), Manager::GetConfigManager(), wxString::IsSameAs(), ConfigManager::Read(), wxRegKey::SetName(), platform::WindowsVersion(), platform::winver_Windows9598ME, and FileFilters::WORKSPACE_EXT.
Referenced by DoSetAssociation().
SetAll()
void Associations::SetAll ()
Definition at line 111 of file associations.cpp.
References CountAssocs(), DoSetAssociation(), and UpdateChanges().
Referenced by CodeBlocksApp::InitAssociations().
SetBatchBuildOnly()
void Associations::SetBatchBuildOnly ()
Definition at line 84 of file associations.cpp.
References DoSetAssociation(), and UpdateChanges().
Referenced by CompilerSettingsDlg::EndModal().
SetCore()
void Associations::SetCore ()
Definition at line 100 of file associations.cpp.
References DoSetAssociation(), and UpdateChanges().
Referenced by CodeBlocksApp::InitAssociations(), and EnvironmentSettingsDlg::OnSetAssocs().
UpdateChanges()
void Associations::UpdateChanges ()
Definition at line 95 of file associations.cpp.
Referenced by ClearAll(), ManageAssocsDialog::OnApply(), ManageAssocsDialog::OnClearAll(), SetAll(), SetBatchBuildOnly(), and SetCore().