Code::Blocks: ScriptBindings::ScriptPluginWrapper Namespace Reference
ScriptBindings::ScriptPluginWrapper Namespace Reference
Classes
struct MenuCallback
Typedefs
typedef std::map< int, MenuCallback > ModuleMenuCallbacks
typedef std::map< wxString, SquirrelObject > ScriptPlugins
typedef std::map< wxString, MenuItemsManager > ScriptPluginsMenus
Functions
wxArrayInt CreateMenu (wxMenuBar *mbar)
wxArrayInt CreateModuleMenu (const ModuleType type, wxMenu *menu, const FileTreeData *data)
void OnScriptMenu (int id)
void OnScriptModuleMenu (int id)
wxArrayInt CreateMenu (const wxString &name)
SQInteger RegisterPlugin (HSQUIRRELVM v)
SQInteger GetPlugin (HSQUIRRELVM v)
int ExecutePlugin (const wxString &name)
Variables
ModuleMenuCallbacks s_MenuCallbacks
ScriptPlugins s_ScriptPlugins
ScriptPluginsMenus s_ScriptPluginsMenus
Class Documentation
ScriptBindings::ScriptPluginWrapper::MenuCallback
struct ScriptBindings::ScriptPluginWrapper::MenuCallback
Definition at line 22 of file sc_plugin.cpp.
Class Members
int menuIndex
SquirrelObject object
Typedef Documentation
ModuleMenuCallbacks
typedef std::map<int, MenuCallback> ScriptBindings::ScriptPluginWrapper::ModuleMenuCallbacks
Definition at line 27 of file sc_plugin.cpp.
ScriptPlugins
typedef std::map<wxString, SquirrelObject> ScriptBindings::ScriptPluginWrapper::ScriptPlugins
Definition at line 31 of file sc_plugin.cpp.
ScriptPluginsMenus
typedef std::map<wxString, MenuItemsManager> ScriptBindings::ScriptPluginWrapper::ScriptPluginsMenus
Definition at line 35 of file sc_plugin.cpp.
Function Documentation
CreateMenu() [1/2]
wxArrayInt ScriptBindings::ScriptPluginWrapper::CreateMenu (wxMenuBar * mbar)
Referenced by MainFrame::CreateMenubar(), and RegisterPlugin().
CreateMenu() [2/2]
wxArrayInt ScriptBindings::ScriptPluginWrapper::CreateMenu (const wxString & name)
Definition at line 42 of file sc_plugin.cpp.
References _(), cbC2U(), cbMessageBox(), MenuItemsManager::CreateFromString(), wxArrayString::GetCount(), ScriptBindings::ScriptPluginWrapper::MenuCallback::menuIndex, ScriptBindings::ScriptPluginWrapper::MenuCallback::object, wxICON_ERROR, and wxNewId().
CreateModuleMenu()
wxArrayInt ScriptBindings::ScriptPluginWrapper::CreateModuleMenu (const ModuleType type, wxMenu * menu, const FileTreeData * data)
Definition at line 104 of file sc_plugin.cpp.
References _(), wxMenu::Append(), cbC2U(), cbMessageBox(), wxArrayString::GetCount(), ScriptBindings::ScriptPluginWrapper::MenuCallback::menuIndex, ScriptBindings::ScriptPluginWrapper::MenuCallback::object, wxICON_ERROR, and wxNewId().
Referenced by PluginManager::AskPluginsForModuleMenu().
ExecutePlugin()
int ScriptBindings::ScriptPluginWrapper::ExecutePlugin (const wxString & name)
Definition at line 271 of file sc_plugin.cpp.
References _(), cbC2U(), cbMessageBox(), and wxICON_ERROR.
Referenced by ScriptBindings::Register_ScriptPlugin().
GetPlugin()
SQInteger ScriptBindings::ScriptPluginWrapper::GetPlugin (HSQUIRRELVM v)
Definition at line 249 of file sc_plugin.cpp.
References wxString::find().
Referenced by ScriptBindings::Register_ScriptPlugin().
OnScriptMenu()
void ScriptBindings::ScriptPluginWrapper::OnScriptMenu (int id)
Definition at line 162 of file sc_plugin.cpp.
References _(), cbC2U(), cbMessageBox(), ScriptBindings::ScriptPluginWrapper::MenuCallback::menuIndex, ScriptBindings::ScriptPluginWrapper::MenuCallback::object, and wxICON_ERROR.
Referenced by PluginManager::GetSafeMode(), PluginManager::OnScriptMenu(), ScriptingManager::OnScriptPluginMenu(), and ScriptingManager::operator=().
OnScriptModuleMenu()
void ScriptBindings::ScriptPluginWrapper::OnScriptModuleMenu (int id)
Definition at line 187 of file sc_plugin.cpp.
References _(), cbC2U(), cbMessageBox(), ScriptBindings::ScriptPluginWrapper::MenuCallback::menuIndex, ScriptBindings::ScriptPluginWrapper::MenuCallback::object, and wxICON_ERROR.
Referenced by PluginManager::GetSafeMode(), and PluginManager::OnScriptModuleMenu().
RegisterPlugin()
SQInteger ScriptBindings::ScriptPluginWrapper::RegisterPlugin (HSQUIRRELVM v)
Definition at line 212 of file sc_plugin.cpp.
References _(), CreateMenu(), wxString::find(), Manager::Get(), Manager::GetLogManager(), Manager::GetScriptingManager(), LogManager::Log(), PluginInfo::name, ScriptingManager::RegisterScriptPlugin(), and sq_throwerror().
Referenced by ScriptBindings::Register_ScriptPlugin().
Variable Documentation
s_MenuCallbacks
ModuleMenuCallbacks ScriptBindings::ScriptPluginWrapper::s_MenuCallbacks
Definition at line 28 of file sc_plugin.cpp.
s_ScriptPlugins
ScriptPlugins ScriptBindings::ScriptPluginWrapper::s_ScriptPlugins
Definition at line 32 of file sc_plugin.cpp.
s_ScriptPluginsMenus
ScriptPluginsMenus ScriptBindings::ScriptPluginWrapper::s_ScriptPluginsMenus
Definition at line 36 of file sc_plugin.cpp.