Code::Blocks: CCDebugInfoHelper Namespace Reference
CCDebugInfoHelper Namespace Reference
Functions
void SaveCCDebugInfo (const wxString &fileDesc, const wxString &content)
Function Documentation
SaveCCDebugInfo()
void CCDebugInfoHelper::SaveCCDebugInfo (const wxString & fileDesc, const wxString & content) inline
Definition at line 68 of file ccdebuginfo.cpp.
References _(), _T, cbMessageBox(), Manager::Get(), wxFileDialog::GetPath(), CCDebugInfo::ID_BUTTON1, CCDebugInfo::ID_BUTTON2, CCDebugInfo::ID_BUTTON3, CCDebugInfo::ID_BUTTON4, CCDebugInfo::ID_BUTTON5, CCDebugInfo::ID_BUTTON6, CCDebugInfo::ID_BUTTON7, CCDebugInfo::ID_BUTTON8, CCDebugInfo::ID_COMBOBOX1, CCDebugInfo::ID_COMBOBOX2, CCDebugInfo::ID_COMBOBOX3, CCDebugInfo::ID_LISTBOX1, CCDebugInfo::ID_LISTBOX2, CCDebugInfo::ID_LISTBOX3, CCDebugInfo::ID_NOTEBOOK1, CCDebugInfo::ID_PANEL1, CCDebugInfo::ID_PANEL2, CCDebugInfo::ID_PANEL3, CCDebugInfo::ID_PANEL4, CCDebugInfo::ID_STATICTEXT1, CCDebugInfo::ID_STATICTEXT10, CCDebugInfo::ID_STATICTEXT12, CCDebugInfo::ID_STATICTEXT14, CCDebugInfo::ID_STATICTEXT16, CCDebugInfo::ID_STATICTEXT18, CCDebugInfo::ID_STATICTEXT2, CCDebugInfo::ID_STATICTEXT20, CCDebugInfo::ID_STATICTEXT24, CCDebugInfo::ID_STATICTEXT26, CCDebugInfo::ID_STATICTEXT28, CCDebugInfo::ID_STATICTEXT33, CCDebugInfo::ID_STATICTEXT35, CCDebugInfo::ID_STATICTEXT37, CCDebugInfo::ID_STATICTEXT39, CCDebugInfo::ID_STATICTEXT4, CCDebugInfo::ID_STATICTEXT41, CCDebugInfo::ID_STATICTEXT6, CCDebugInfo::ID_STATICTEXT8, CCDebugInfo::ID_TEXTCTRL1, PlaceWindow(), wxFileDialog::ShowModal(), wxFile::Write(), wxFile::write, wxFD_OVERWRITE_PROMPT, wxFD_SAVE, wxID_OK, and wxNewId().
Referenced by CCDebugInfo::OnSave().