Code::Blocks: wxCrc32 Namespace Reference
wxCrc32 Namespace Reference
Functions
DLLIMPORT wxUint32 FromFile (const wxString &filename)
DLLIMPORT wxUint32 FromString (const wxString &text)
Function Documentation
FromFile()
wxUint32 wxCrc32::FromFile (const wxString & filename)
Definition at line 55 of file crc32.cpp.
References cbReadFileContents(), FromString(), and wxString::IsEmpty().
Referenced by ScriptingManager::IsScriptTrusted(), and ScriptingManager::TrustScript().
FromString()
wxUint32 wxCrc32::FromString (const wxString & text)
Definition at line 64 of file crc32.cpp.
References GetCRC32Table(), wxString::IsEmpty(), and NULL.
Referenced by FromFile(), ConfigManager::ReadBinary(), and ConfigManager::WriteBinary().