Code::Blocks: InsertClassMethodDlgHelper Namespace Reference
InsertClassMethodDlgHelper Namespace Reference
Functions
void DoFillMethodsFor (wxCheckListBox *clb, Token *parentToken, const wxString &ns, bool includePrivate, bool includeProtected, bool includePublic)
Function Documentation
DoFillMethodsFor()
void InsertClassMethodDlgHelper::DoFillMethodsFor (wxCheckListBox * clb, Token * parentToken, const wxString & ns, bool includePrivate, bool includeProtected, bool includePublic) inline
Definition at line 31 of file insertclassmethoddlg.cpp.
References _T, TokenTree::at(), wxCheckListBox::FindString(), Token::GetFormattedArgs(), Token::GetTree(), Token::m_Children, Token::m_DirectAncestors, Token::m_FullType, Token::m_Name, Token::m_Scope, Token::m_TokenKind, InsertClassMethodDlg::OnClassesChange(), InsertClassMethodDlg::OnCodeChange(), InsertClassMethodDlg::OnFilterChange(), TokenTree::RecalcInheritanceChain(), wxString::Replace(), tkConstructor, tkDestructor, tkFunction, tsPrivate, tsProtected, tsPublic, and wxNOT_FOUND.
Referenced by InsertClassMethodDlg::FillMethods().