Code::Blocks: TinyXML Namespace Reference
TinyXML Namespace Reference
Functions
bool SaveDocument (const wxString &, TiXmlDocument *)
bool LoadDocument (const wxString &filename, TiXmlDocument *doc)
TiXmlDocument * LoadDocument (const wxString &filename)
Function Documentation
LoadDocument() [1/2]
bool TinyXML::LoadDocument (const wxString & filename, TiXmlDocument * doc)
Definition at line 13 of file tinywxuni.cpp.
References wxFile::Access(), wxFile::Length(), wxFile::Read(), and wxFile::read.
Referenced by LoadDocument(), WorkspaceLoader::LoadLayout(), WorkspaceLoader::Open(), ProjectLayoutLoader::Open(), ProjectLoader::Open(), and CfgMgrBldr::SwitchTo().
LoadDocument() [2/2]
TiXmlDocument * TinyXML::LoadDocument (const wxString & filename)
Definition at line 34 of file tinywxuni.cpp.
References LoadDocument().
SaveDocument()
bool TinyXML::SaveDocument (const wxString & filename, TiXmlDocument * doc)
Definition at line 45 of file tinywxuni.cpp.
References Manager::Get(), Manager::GetFileManager(), and FileManager::SaveUTF8().
Referenced by cbSaveTinyXMLDocument(), and CfgMgrBldr::Flush().