Code::Blocks: CCManagerHelper Namespace Reference
CCManagerHelper Namespace Reference
Functions
void RipplePts (int &ptA, int &ptB, int len, int delta)
int FindColumn (int line, int column, wxScintilla *stc)
bool IsPosVisible (int pos, wxScintilla *stc)
static int CallTipToInt (const wxString &firstTip, int numPages)
static void BuildFontSizes (int *sizes, int size)
static int GetDefaultHTMLFontSize ()
Function Documentation
BuildFontSizes()
static void CCManagerHelper::BuildFontSizes (int * sizes, int size) static
Definition at line 84 of file ccmanager.cpp.
Referenced by CCManager::CCManager().
CallTipToInt()
static int CCManagerHelper::CallTipToInt (const wxString & firstTip, int numPages) static
Definition at line 71 of file ccmanager.cpp.
References wxString::begin(), wxString::end(), and wxString::Length().
Referenced by CCManager::DoUpdateCallTip(), and CCManager::OnShowCallTip().
FindColumn()
int CCManagerHelper::FindColumn (int line, int column, wxScintilla * stc) inline
Definition at line 51 of file ccmanager.cpp.
References wxScintilla::GetColumn(), wxScintilla::GetLineEndPosition(), and wxScintilla::PositionFromLine().
Referenced by CCManager::DoShowTips(), and wxScintilla::wxScintilla().
GetDefaultHTMLFontSize()
static int CCManagerHelper::GetDefaultHTMLFontSize () static
Definition at line 99 of file ccmanager.cpp.
References wxFont::GetPointSize(), and wxNORMAL_FONT.
Referenced by CCManager::CCManager().
IsPosVisible()
bool CCManagerHelper::IsPosVisible (int pos, wxScintilla * stc) inline
Definition at line 63 of file ccmanager.cpp.
References wxScintilla::GetFirstVisibleLine(), wxScintilla::LineFromPosition(), wxScintilla::LinesOnScreen(), and wxScintilla::VisibleFromDocLine().
Referenced by CCManager::OnEditorHook().
RipplePts()
void CCManagerHelper::RipplePts (int & ptA, int & ptB, int len, int delta) inline
Definition at line 40 of file ccmanager.cpp.
Referenced by CCManager::DoShowTips(), and CCManager::DoUpdateCallTip().