Code::Blocks: ParserCommon Namespace Reference
ParserCommon Namespace Reference
Enumerations
enum ParserState { ptCreateParser = 1, ptReparseFile = 2, ptAddFileToParser = 3, ptUndefined = 4 }
enum EFileType { ftHeader, ftSource, ftOther }
the enum type of the file type
Functions
EFileType FileType (const wxString &filename, bool force_refresh=false)
return a file type, which can be either header files or implementation files or other files
Variables
static const int PARSER_BATCHPARSE_TIMER_DELAY = 300
static const int PARSER_BATCHPARSE_TIMER_RUN_IMMEDIATELY = 10
static const int PARSER_BATCHPARSE_TIMER_DELAY_LONG = 1000
static const int PARSER_REPARSE_TIMER_DELAY = 100
static volatile Parser * s_CurrentParser = nullptr
static wxMutex s_ParserMutex
int idParserStart = wxNewId()
int idParserEnd = wxNewId()
Enumeration Type Documentation
EFileType
enum ParserCommon::EFileType
the enum type of the file type
Enumerator
ftHeader
ftSource
ftOther
Definition at line 25 of file parser_base.h.
ParserState
enum ParserCommon::ParserState
Enumerator
ptCreateParser
the Parser object is newly created, and we are parsing the predefined macro buffer, the source files, and finally mark the project's tokens as local
ptReparseFile
some files are changed by the user, so we are parsing the changed files
ptAddFileToParser
the user has add some files to the cbproject, so we are parsing the new added files
ptUndefined
non of the above three status, this means our Parser has finish all the jobs, and it is in idle mode
Definition at line 88 of file parser.h.
Function Documentation
FileType()
ParserCommon::EFileType ParserCommon::FileType (const wxString & filename, bool force_refresh = false)
return a file type, which can be either header files or implementation files or other files
Parameters
filename the input file name
force_refresh read the user's option of file extension to classify the file type
Definition at line 125 of file parser_base.cpp.
References _T, wxArrayString::Add(), wxString::AfterLast(), wxArrayString::Clear(), wxString::Find(), ftHeader, ftOther, ftSource, Manager::Get(), Manager::GetConfigManager(), wxArrayString::GetCount(), wxStringTokenizer::GetNextToken(), wxStringTokenizer::HasMoreTokens(), wxString::IsEmpty(), wxString::Len(), wxString::Lower(), ConfigManager::Read(), ConfigManager::ReadBool(), wxString::SubString(), wxString::Trim(), and wxNOT_FOUND.
Referenced by NativeParser::AddFileToParser(), NativeParser::DoFullParsing(), MarkFileAsLocalThreadedTask::Execute(), CodeRefactoring::GetAllProjectFiles(), CodeCompletion::GetProviderStatusFor(), ParserThread::HandleIncludes(), NativeParser::OnEditorActivated(), NativeParserHelper::ParserDirTraverser::OnFile(), Parser::ReadOptions(), NativeParser::RemoveProjectFromParser(), and NativeParser::ReparseFile().
Variable Documentation
idParserEnd
int ParserCommon::idParserEnd = wxNewId()
Definition at line 94 of file parser.cpp.
Referenced by CodeCompletion::CodeCompletion(), NativeParser::NativeParser(), Parser::OnAllThreadsDone(), CodeCompletion::~CodeCompletion(), and NativeParser::~NativeParser().
idParserStart
int ParserCommon::idParserStart = wxNewId()
Definition at line 93 of file parser.cpp.
Referenced by CodeCompletion::CodeCompletion(), NativeParser::NativeParser(), Parser::OnBatchTimer(), CodeCompletion::~CodeCompletion(), and NativeParser::~NativeParser().
PARSER_BATCHPARSE_TIMER_DELAY
const int ParserCommon::PARSER_BATCHPARSE_TIMER_DELAY = 300 static
Definition at line 77 of file parser.cpp.
Referenced by Parser::AddBatchParse(), Parser::AddParse(), and Parser::AddPredefinedMacros().
PARSER_BATCHPARSE_TIMER_DELAY_LONG
const int ParserCommon::PARSER_BATCHPARSE_TIMER_DELAY_LONG = 1000 static
Definition at line 79 of file parser.cpp.
Referenced by Parser::OnBatchTimer().
PARSER_BATCHPARSE_TIMER_RUN_IMMEDIATELY
const int ParserCommon::PARSER_BATCHPARSE_TIMER_RUN_IMMEDIATELY = 10 static
Definition at line 78 of file parser.cpp.
Referenced by Parser::OnAllThreadsDone().
PARSER_REPARSE_TIMER_DELAY
const int ParserCommon::PARSER_REPARSE_TIMER_DELAY = 100 static
Definition at line 80 of file parser.cpp.
Referenced by Parser::Reparse(), and Parser::ReparseModifiedFiles().
s_CurrentParser
volatile Parser* ParserCommon::s_CurrentParser = nullptr static
Definition at line 84 of file parser.cpp.
Referenced by Parser::OnAllThreadsDone(), Parser::OnBatchTimer(), and Parser::~Parser().
s_ParserMutex
wxMutex ParserCommon::s_ParserMutex static
Definition at line 91 of file parser.cpp.
Referenced by Parser::AddBatchParse(), Parser::AddParse(), Parser::AddPredefinedMacros(), Parser::ClearPredefinedMacros(), Parser::Done(), Parser::IsFileParsed(), Parser::NotDoneReason(), Parser::OnBatchTimer(), and Parser::~Parser().