Code::Blocks: wxBase64 Namespace Reference
wxBase64 Namespace Reference
Functions
DLLIMPORT wxString Encode (const wxUint8 *pData, size_t len)
DLLIMPORT wxString Encode (const wxString &data)
DLLIMPORT wxString Decode (const wxString &data)
Function Documentation
Decode()
wxString wxBase64::Decode (const wxString & data)
Definition at line 91 of file base64.cpp.
References _T, wxString::Alloc(), wxString::Append(), fillchar, wxString::Find(), wxString::Length(), and wxASSERT_MSG.
Referenced by ConfigManager::Read(), and ConfigManager::ReadBinary().
Encode() [1/2]
wxString wxBase64::Encode (const wxUint8 * pData, size_t len)
Definition at line 48 of file base64.cpp.
References wxString::Alloc(), wxString::Append(), and fillchar.
Referenced by Encode(), ConfigManager::Write(), and ConfigManager::WriteBinary().
Encode() [2/2]
wxString wxBase64::Encode (const wxString & data)
Definition at line 43 of file base64.cpp.
References wxString::c_str(), Encode(), and wxString::Length().