Code::Blocks: ScriptBindings::IOLib Namespace Reference
ScriptBindings::IOLib Namespace Reference
Functions
bool SecurityAllows (const wxString &operation, const wxString &descr)
wxString GetCwd ()
void SetCwd (const wxString &dir)
bool CreateDirRecursively (const wxString &full_path, int perms)
wxString ChooseDir (const wxString &message, const wxString &initialPath, bool showCreateDirButton)
bool RemoveDir (const wxString &src)
bool DirectoryExists (const wxString &dir)
bool CopyFile (const wxString &src, const wxString &dst, bool overwrite)
bool RenameFile (const wxString &src, const wxString &dst)
bool RemoveFile (const wxString &src)
bool FileExists (const wxString &file)
wxString ChooseFile (const wxString &title, const wxString &defaultFile, const wxString &filter)
wxString ReadFileContents (const wxString &filename)
bool WriteFileContents (const wxString &filename, const wxString &contents)
int Execute (const wxString &command)
wxString ExecuteAndGetOutput (const wxString &command)
wxString ExecuteAndGetOutputAndError (const wxString &command, bool prepend_error=true)
Function Documentation
ChooseDir()
wxString ScriptBindings::IOLib::ChooseDir (const wxString & message, const wxString & initialPath, bool showCreateDirButton)
Definition at line 85 of file sc_io.cpp.
References ChooseDirectory(), Manager::Get(), and wxEmptyString.
Referenced by ScriptBindings::Register_IO().
ChooseFile()
wxString ScriptBindings::IOLib::ChooseFile (const wxString & title, const wxString & defaultFile, const wxString & filter)
Definition at line 151 of file sc_io.cpp.
References Manager::Get(), wxFileDialog::GetPath(), PlaceWindow(), wxFileDialog::ShowModal(), wxEmptyString, wxFD_OPEN, and wxID_OK.
Referenced by ScriptBindings::Register_IO().
CopyFile()
bool ScriptBindings::IOLib::CopyFile (const wxString & src, const wxString & dst, bool overwrite)
Definition at line 106 of file sc_io.cpp.
References _T, wxString::c_str(), wxString::Format(), Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), SecurityAllows(), wxCopyFile(), wxEmptyString, and wxFileExists().
Referenced by ScriptBindings::Register_IO().
CreateDirRecursively()
bool ScriptBindings::IOLib::CreateDirRecursively (const wxString & full_path, int perms)
Definition at line 76 of file sc_io.cpp.
References _T, Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), SecurityAllows(), and wxEmptyString.
Referenced by Wiz::CopyFiles(), NewFromTemplateDlg::EditScript(), PluginManager::ExtractFile(), DirectCommands::GetCompileFileCommand(), DirectCommands::GetTargetLinkCommands(), ConfigManager::InitPaths(), ConfigManager::MigrateFolders(), TemplateManager::NewProjectFromUserTemplate(), ScriptBindings::Register_IO(), Wiz::RunProjectWizard(), TemplateManager::SaveUserTemplate(), and ConfigManager::SetUserDataFolder().
DirectoryExists()
bool ScriptBindings::IOLib::DirectoryExists (const wxString & dir)
Definition at line 99 of file sc_io.cpp.
References Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), wxDirExists(), and wxEmptyString.
Referenced by ScriptBindings::Register_IO().
Execute()
int ScriptBindings::IOLib::Execute (const wxString & command)
Definition at line 183 of file sc_io.cpp.
References _T, SecurityAllows(), wxEXEC_NODISABLE, and wxExecute().
Referenced by PluginManager::ExecutePlugin(), ToolsManager::GetToolsCount(), and ScriptBindings::Register_IO().
ExecuteAndGetOutput()
wxString ScriptBindings::IOLib::ExecuteAndGetOutput (const wxString & command)
Definition at line 191 of file sc_io.cpp.
References _T, GetStringFromArray(), SecurityAllows(), wxEmptyString, wxEXEC_NODISABLE, and wxExecute().
Referenced by ScriptBindings::Register_IO().
ExecuteAndGetOutputAndError()
wxString ScriptBindings::IOLib::ExecuteAndGetOutputAndError (const wxString & command, bool prepend_error = true)
Definition at line 202 of file sc_io.cpp.
References _T, GetStringFromArray(), wxArrayString::IsEmpty(), SecurityAllows(), wxEmptyString, wxEXEC_NODISABLE, and wxExecute().
Referenced by ScriptBindings::Register_IO().
FileExists()
bool ScriptBindings::IOLib::FileExists (const wxString & file)
Definition at line 144 of file sc_io.cpp.
References Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), wxEmptyString, and wxFileExists().
Referenced by ScriptBindings::Register_IO().
GetCwd()
wxString ScriptBindings::IOLib::GetCwd ()
Definition at line 66 of file sc_io.cpp.
References wxGetCwd().
Referenced by ScriptBindings::Register_IO().
ReadFileContents()
wxString ScriptBindings::IOLib::ReadFileContents (const wxString & filename)
Definition at line 165 of file sc_io.cpp.
References cbReadFileContents(), Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), and wxEmptyString.
Referenced by ScriptBindings::Register_IO().
RemoveDir()
bool ScriptBindings::IOLib::RemoveDir (const wxString & src)
Definition at line 90 of file sc_io.cpp.
References _T, Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), SecurityAllows(), wxEmptyString, and wxRmdir().
Referenced by ScriptBindings::Register_IO().
RemoveFile()
bool ScriptBindings::IOLib::RemoveFile (const wxString & src)
Definition at line 134 of file sc_io.cpp.
References _T, Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), SecurityAllows(), wxEmptyString, wxFileExists(), and wxRemoveFile().
Referenced by ProjectBuildTarget::GetFilesCount(), ScriptBindings::Register_IO(), and cbProject::SetProjectNode().
RenameFile()
bool ScriptBindings::IOLib::RenameFile (const wxString & src, const wxString & dst)
Definition at line 120 of file sc_io.cpp.
References _T, wxString::c_str(), wxString::Format(), Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), SecurityAllows(), wxEmptyString, wxFileExists(), and wxRenameFile().
Referenced by ScriptBindings::Register_IO().
SecurityAllows()
bool ScriptBindings::IOLib::SecurityAllows (const wxString & operation, const wxString & descr)
Definition at line 33 of file sc_io.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), ScriptSecurityWarningDlg::GetResponse(), Manager::GetScriptingManager(), wxDialog::ShowModal(), ssrAllow, ssrAllowAll, ssrTrust, ssrTrustPermanently, ScriptingManager::TrustCurrentlyRunningScript(), ConfigManager::Write(), and wxID_OK.
Referenced by CopyFile(), CreateDirRecursively(), Execute(), ExecuteAndGetOutput(), ExecuteAndGetOutputAndError(), RemoveDir(), RemoveFile(), RenameFile(), and WriteFileContents().
SetCwd()
void ScriptBindings::IOLib::SetCwd (const wxString & dir)
Definition at line 71 of file sc_io.cpp.
References wxSetWorkingDirectory().
Referenced by ScriptBindings::Register_IO().
WriteFileContents()
bool ScriptBindings::IOLib::WriteFileContents (const wxString & filename, const wxString & contents)
Definition at line 173 of file sc_io.cpp.
References _T, cbWrite(), Manager::Get(), wxFileName::GetFullPath(), NormalizePath(), SecurityAllows(), wxFile::write, and wxEmptyString.
Referenced by ScriptBindings::Register_IO().