Code::Blocks: newfromtemplatedlg.cpp File Reference
newfromtemplatedlg.cpp File Reference
#include "sdk_precomp.h"
#include "cbstyledtextctrl.h"
#include <wx/listbook.h>
#include <wx/radiobox.h>
#include "newfromtemplatedlg.h"
#include "projecttemplateloader.h"
Classes
struct ListItemData
Functions
int wxCALLBACK SortTemplates (wxIntPtr item1, wxIntPtr item2, cb_unused wxIntPtr sortData)
Variables
static int idEditWizardScript = wxNewId()
static int idDiscardWizardScript = wxNewId()
static int idInfoWizardScript = wxNewId()
static int idEditGlobalWizardScript = wxNewId()
Function Documentation
SortTemplates()
int wxCALLBACK SortTemplates (wxIntPtr item1, wxIntPtr item2, cb_unused wxIntPtr sortData) inline
Definition at line 199 of file newfromtemplatedlg.cpp.
References cbWizardPlugin::GetTitle(), ProjectTemplateLoader::m_Title, ListItemData::plugin, ListItemData::pt, and ListItemData::wizPluginIndex.
Referenced by NewFromTemplateDlg::BuildListFor().
Variable Documentation
idDiscardWizardScript
int idDiscardWizardScript = wxNewId() static
Definition at line 48 of file newfromtemplatedlg.cpp.
Referenced by NewFromTemplateDlg::OnListRightClick().
idEditGlobalWizardScript
int idEditGlobalWizardScript = wxNewId() static
Definition at line 50 of file newfromtemplatedlg.cpp.
Referenced by NewFromTemplateDlg::OnListRightClick().
idEditWizardScript
int idEditWizardScript = wxNewId() static
Definition at line 47 of file newfromtemplatedlg.cpp.
Referenced by NewFromTemplateDlg::OnListRightClick().
idInfoWizardScript
int idInfoWizardScript = wxNewId() static
Definition at line 49 of file newfromtemplatedlg.cpp.
Referenced by NewFromTemplateDlg::OnListRightClick().