Code::Blocks: parsewatchvalue.h File Reference
parsewatchvalue.h File Reference
#include "debugger_defs.h"
Classes
struct GDBLocalVariable
Functions
cb::shared_ptr< GDBWatch > AddChild (cb::shared_ptr< GDBWatch > parent, wxString const &str_name)
bool ParseGDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const &value)
bool ParseCDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const &value)
void TokenizeGDBLocals (std::vector< GDBLocalVariable > &results, wxString const &value)
Function Documentation
AddChild()
cb::shared_ptr<GDBWatch> AddChild (cb::shared_ptr< GDBWatch > parent, wxString const & str_name) inline
Definition at line 310 of file parsewatchvalue.cpp.
References cbWatch::AddChild(), and regexRepeatedChar().
ParseCDBWatchValue()
bool ParseCDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const & value)
Definition at line 714 of file parsewatchvalue.cpp.
References Token::AddChild(), GetArrayFromString(), and NULL.
Referenced by CdbCmd_Watch::ParseOutput(), and SUITE().
ParseGDBWatchValue()
bool ParseGDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const & value)
Definition at line 640 of file parsewatchvalue.cpp.
References ParseGDBWatchValue(), RemoveWarnings(), and Token::start.
TokenizeGDBLocals()
void TokenizeGDBLocals (std::vector< GDBLocalVariable > & results, wxString const & value)
Definition at line 848 of file parsewatchvalue.cpp.
References Token::start.
Referenced by GdbCmd_LocalsFuncArgs::ParseOutput(), and SUITE().