Code::Blocks: parsewatchvalue.cpp File Reference
parsewatchvalue.cpp File Reference
#include <sdk.h>
#include "parsewatchvalue.h"
Classes
struct Token
a symbol found in the parsed files, it can be many kinds, such as a variable, a class and so on.
Functions
int DetectRepeatingSymbols (wxString const &str, int pos)
bool GetNextToken (wxString const &str, int pos, Token &token)
cb::shared_ptr< GDBWatch > AddChild (cb::shared_ptr< GDBWatch > parent, wxString const &full_value, Token &name)
cb::shared_ptr< GDBWatch > AddChild (cb::shared_ptr< GDBWatch > parent, wxString const &str_name)
bool ParseGDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const &value, int &start, int length)
wxString RemoveWarnings (wxString const &input)
void RemoveBefore (wxString &str, const wxString &s)
bool ParseGDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const &inputValue)
bool ParseCDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const &value)
void TokenizeGDBLocals (std::vector< GDBLocalVariable > &results, wxString const &value)
Variables
wxRegEx regexRepeatedChars (wxT("^((\'.{1,6}\')|('.{1,6}'))[ \](<repeats[ \][0-9]+[ \]times>)"), wxRE_ADVANCED)
wxRegEx regexRepeatedChar (wxT(".+[ \](<repeats[ \][0-9]+[ \]times>)$"))
Function Documentation
AddChild() [1/2]
cb::shared_ptr<GDBWatch> AddChild (cb::shared_ptr< GDBWatch > parent, wxString const & full_value, Token & name) inline
Definition at line 294 of file parsewatchvalue.cpp.
References cbWatch::AddChild(), and Token::ExtractString().
Referenced by GdbCmd_LocalsFuncArgs::ParseOutput().
AddChild() [2/2]
cb::shared_ptr<GDBWatch> AddChild (cb::shared_ptr< GDBWatch > parent, wxString const & str_name) inline
Definition at line 310 of file parsewatchvalue.cpp.
References cbWatch::AddChild(), regexRepeatedChar, and wxT.
DetectRepeatingSymbols()
int DetectRepeatingSymbols (wxString const & str, int pos) inline
Definition at line 77 of file parsewatchvalue.cpp.
References wxRegEx::GetMatch(), wxString::length(), wxRegEx::Matches(), regexRepeatedChars, Token::start, wxString::substr(), and wxT.
Referenced by GetNextToken().
GetNextToken()
bool GetNextToken (wxString const & str, int pos, Token & token) inline
Definition at line 117 of file parsewatchvalue.cpp.
References _T, Token::CloseBrace, Token::Comma, DetectRepeatingSymbols(), Token::end, Token::Equal, Token::hasRepeatedChar, wxString::length(), Token::OpenBrace, Token::start, Token::String, Token::Token(), Token::type, and wxT.
Referenced by ParseGDBWatchValue().
ParseCDBWatchValue()
bool ParseCDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const & value)
Definition at line 714 of file parsewatchvalue.cpp.
References Token::AddChild(), GetArrayFromString(), wxArrayString::GetCount(), wxRegEx::GetMatch(), wxRegEx::IsValid(), wxRegEx::Matches(), NULL, and wxT.
Referenced by CdbCmd_Watch::ParseOutput(), and SUITE().
ParseGDBWatchValue() [1/2]
bool ParseGDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const & value, int & start, int length) inline
Definition at line 327 of file parsewatchvalue.cpp.
References Token::AddChild(), Token::CloseBrace, Token::Comma, wxString::empty(), Token::end, Token::Equal, Token::ExtractString(), wxString::find(), wxString::find_last_of(), wxString::Format(), GetNextToken(), Token::hasRepeatedChar, wxString::length(), wxRegEx::Matches(), wxString::npos, Token::OpenBrace, Token::start, wxString::StartsWith(), Token::String, Token::Trim(), Token::type, Token::Undefined, wxEmptyString, wxIsdigit(), and wxT.
Referenced by ParseGDBWatchValue(), GdbCmd_Watch::ParseOutput(), GdbCmd_TooltipEvaluation::ParseOutput(), GdbCmd_LocalsFuncArgs::ParseOutput(), and SUITE().
ParseGDBWatchValue() [2/2]
bool ParseGDBWatchValue (cb::shared_ptr< GDBWatch > watch, wxString const & inputValue)
Definition at line 640 of file parsewatchvalue.cpp.
References wxString::empty(), wxString::EndsWith(), wxString::find(), wxString::length(), wxString::npos, ParseGDBWatchValue(), wxString::RemoveLast(), RemoveWarnings(), Token::start, wxString::substr(), wxString::Trim(), wxEmptyString, and wxT.
RemoveBefore()
void RemoveBefore (wxString & str, const wxString & s) inline
Definition at line 630 of file parsewatchvalue.cpp.
References wxString::find(), wxString::length(), wxString::npos, wxString::Remove(), and wxString::Trim().
RemoveWarnings()
wxString RemoveWarnings (wxString const & input) inline
Definition at line 600 of file parsewatchvalue.cpp.
References wxString::find(), wxString::length(), wxString::npos, wxString::StartsWith(), wxString::substr(), and wxT.
Referenced by ParseGDBWatchValue().
TokenizeGDBLocals()
void TokenizeGDBLocals (std::vector< GDBLocalVariable > & results, wxString const & value)
Definition at line 848 of file parsewatchvalue.cpp.
References wxString::length(), Token::start, and wxT.
Referenced by GdbCmd_LocalsFuncArgs::ParseOutput(), and SUITE().
Variable Documentation
regexRepeatedChar
wxRegEx regexRepeatedChar(wxT(".+[ \t](<repeats[ \t][0-9]+[ \t]times>)$"))
Referenced by AddChild().
regexRepeatedChars
wxRegEx regexRepeatedChars(wxT("^((\\'.{1,6}\\')|('.{1,6}'))[ \t](<repeats[ \t][0-9]+[ \t]times>)"), wxRE_ADVANCED)
Referenced by DetectRepeatingSymbols().