Code::Blocks: pluginmanager.cpp File Reference
pluginmanager.cpp File Reference
#include "sdk_precomp.h"
#include <wx/dir.h>
#include <wx/filesys.h>
#include <wx/intl.h>
#include <wx/menu.h>
#include <wx/string.h>
#include "pluginmanager.h"
#include "cbexception.h"
#include "cbplugin.h"
#include "infowindow.h"
#include "logmanager.h"
#include "macrosmanager.h"
#include "manager.h"
#include "editormanager.h"
#include "configmanager.h"
#include "personalitymanager.h"
#include "scriptingmanager.h"
#include "globals.h"
#include "sdk_events.h"
#include <wx/dynlib.h>
#include <wx/progdlg.h>
#include <wx/utils.h>
#include <wx/filename.h>
#include <wx/wfstream.h>
#include <wx/zipstrm.h>
#include <wx/txtstrm.h>
#include "filefilters.h"
#include "tinyxml/tinyxml.h"
#include "annoyingdialog.h"
#include "pluginsconfigurationdlg.h"
#include "scripting/bindings/sc_plugin.h"
Classes
struct LibLoader::RefCountedLib
Namespaces
LibLoader
Macros
#define SIGN(a) (a>0?1:(a<0?-1:0))
Typedefs
typedef std::map< wxString,
RefCountedLib > LibLoader::Libs
Functions
void VersionStringToNumbers (const wxString &version, long *major, long *minor, long *release)
int CompareVersions (const wxString &new_version, const wxString &old_version)
wxDynamicLibrary * LibLoader::LoadLibrary (const wxString &filename)
void LibLoader::RemoveLibrary (wxDynamicLibrary *lib)
void LibLoader::Cleanup ()
int SortByConfigurationPriority (cbPlugin **first, cbPlugin **second)
Variables
Libs LibLoader::s_Libs
Macro Definition Documentation
#define SIGN (a) (a>0?1:(a<0?-1:0))
Referenced by CompareVersions().
Function Documentation
int CompareVersions (const wxString & new_version, const wxString & old_version) inline
References SIGN, and VersionStringToNumbers().
Referenced by PluginManager::InstallPlugin().
int SortByConfigurationPriority (cbPlugin ** first, cbPlugin ** second) inline
Referenced by PluginManager::GetConfigurationPanels().
void VersionStringToNumbers (const wxString & version, long * major, long * minor, long * release) inline
Referenced by CompareVersions().