Code::Blocks: printing_types.h File Reference
printing_types.h File Reference
#include "settings.h"
#include <wx/print.h>
Enumerations
enum PrintScope { psSelection, psActiveEditor, psAllOpenEditors }
enum PrintColourMode { pcmBlackAndWhite, pcmColourOnWhite, pcmInvertColours, pcmAsIs }
Functions
DLLIMPORT void InitPrinting ()
DLLIMPORT void DeInitPrinting ()
Variables
wxPrinter * g_printer
wxPageSetupData * g_pageSetupData
Enumeration Type Documentation
PrintColourMode
enum PrintColourMode
Enumerator
pcmBlackAndWhite
pcmColourOnWhite
pcmInvertColours
pcmAsIs
Definition at line 27 of file printing_types.h.
PrintScope
enum PrintScope
Enumerator
psSelection
psActiveEditor
psAllOpenEditors
Definition at line 19 of file printing_types.h.
Function Documentation
DeInitPrinting()
DLLIMPORT void DeInitPrinting ()
Definition at line 52 of file printing_types.cpp.
References g_printer.
Referenced by cbEditor::Print(), and MainFrame::~MainFrame().
InitPrinting()
DLLIMPORT void InitPrinting ()
Definition at line 25 of file printing_types.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), wxPrintDialogData::GetPrintData(), wxPrinter::GetPrintDialogData(), ConfigManager::ReadInt(), wxPrintData::SetOrientation(), wxPrintData::SetPaperId(), wxLANDSCAPE, wxPAPER_A4, and wxPORTRAIT.
Referenced by cbEditor::Print().
Variable Documentation
g_pageSetupData
wxPageSetupData* g_pageSetupData
g_printer
wxPrinter* g_printer
Definition at line 20 of file printing_types.cpp.
Referenced by DeInitPrinting(), cbEditorPrintout::GetPageInfo(), and cbEditor::Print().