Code::Blocks: printing_types.cpp File Reference
printing_types.cpp File Reference
#include "sdk_precomp.h"
#include "printing_types.h"
Functions
void InitPrinting ()
void DeInitPrinting ()
Variables
wxPrinter * g_printer = nullptr
Function Documentation
DeInitPrinting()
void DeInitPrinting ()
Definition at line 52 of file printing_types.cpp.
References g_printer.
Referenced by cbEditor::Print(), and MainFrame::~MainFrame().
InitPrinting()
void InitPrinting ()
Definition at line 25 of file printing_types.cpp.
References _T, Manager::Get(), Manager::GetConfigManager(), wxPrintDialogData::GetPrintData(), wxPrinter::GetPrintDialogData(), ConfigManager::ReadInt(), wxPrintData::SetOrientation(), wxPrintData::SetPaperId(), wxLANDSCAPE, wxPAPER_A4, and wxPORTRAIT.
Referenced by cbEditor::Print().
Variable Documentation
g_printer
wxPrinter* g_printer = nullptr
Definition at line 20 of file printing_types.cpp.
Referenced by DeInitPrinting(), cbEditorPrintout::GetPageInfo(), and cbEditor::Print().