Code::Blocks: projectmanagerui.cpp File Reference
projectmanagerui.cpp File Reference
#include "sdk.h"
#include "projectmanagerui.h"
#include <unordered_map>
#include <wx/dataobj.h>
#include <wx/dnd.h>
#include "cbauibook.h"
#include "cbcolourmanager.h"
#include "confirmreplacedlg.h"
#include "filefilters.h"
#include "filegroupsandmasks.h"
#include "multiselectdlg.h"
#include "projectdepsdlg.h"
#include "projectfileoptionsdlg.h"
#include "projectoptionsdlg.h"
#include "projectsfilemasksdlg.h"
#include "goto_file.h"
#include "startherepage.h"
Classes
struct ProjectFileRelativePathCmp
struct cbStringHash
Functions
template<typename Func >
static void applyFileOptionChange (std::set< cbProject *> &modified, wxTreeCtrl &tree, Func func)
Find all selected tree items which are files and call the func on them.
Function Documentation
applyFileOptionChange()
template<typename Func > static void applyFileOptionChange (std::set< cbProject *> & modified, wxTreeCtrl & tree, Func func) static
Find all selected tree items which are files and call the func on them.
The function is expected to return true when it made modifications to the ProjectFile parameter, and false when it didn't. The modified parameter will be filled with the set of modified projects.
Definition at line 1790 of file projectmanagerui.cpp.
References FileTreeData::ftdkFile, wxTreeCtrl::GetItemData(), FileTreeData::GetKind(), ProjectFile::GetParentProject(), FileTreeData::GetProjectFile(), and wxTreeCtrl::GetSelections().
Referenced by ProjectManagerUI::OnFileOptions().