Code::Blocks: projectfileoptionsdlg.cpp File Reference
projectfileoptionsdlg.cpp File Reference
#include "sdk_precomp.h"
#include "cbproject.h"
#include "compilerfactory.h"
#include "editormanager.h"
#include "editorcolourset.h"
#include "logmanager.h"
#include "projectmanager.h"
#include <wx/xrc/xmlres.h>
#include <wx/intl.h>
#include <wx/choice.h>
#include <wx/checkbox.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#include <wx/filename.h>
#include <wx/file.h>
#include <wx/checklst.h>
#include <wx/stattext.h>
#include <wx/sizer.h>
#include "projectfileoptionsdlg.h"
#include <wx/slider.h>
#include <wx/notebook.h>
#include <wx/textfile.h>
Functions
void AnalyseLine (const CommentToken &language, wxString line, bool &comment, bool &code, bool &multi_line_comment)
void CountLines (wxFileName filename, const CommentToken &language, long int &code_lines, long int &codecomments_lines, long int &comment_lines, long int &empty_lines, long int &total_lines)
Function Documentation
void AnalyseLine (const CommentToken & language, wxString line, bool & comment, bool & code, bool & multi_line_comment) inline
Referenced by CountLines().
void CountLines (wxFileName filename, const CommentToken & language, long int & code_lines, long int & codecomments_lines, long int & comment_lines, long int & empty_lines, long int & total_lines) inline
References AnalyseLine().
Referenced by ProjectFileOptionsDlg::FillGeneralProperties().