Code::Blocks: safedelete.h File Reference
safedelete.h File Reference
#include <map>
#include <vector>
#include <list>
#include <deque>
#include <algorithm>
Classes
struct SeqDelete
Functions
template<typename T >
void Delete (std::vector< T > &s)
template<typename T >
void Delete (std::list< T > &s)
template<typename T >
void Delete (std::deque< T > &s)
template<typename T , typename U >
void Delete (std::map< T, U > &s)
Function Documentation
Delete() [1/4]
template<typename T > void Delete (std::vector< T > & s) inline
Definition at line 20 of file safedelete.h.
Referenced by cbProject::ClearAllProperties(), CompilerGCC::DoRunQueue(), CompilerGCC::FreeProcesses(), ParserThread::InitTokenizer(), EditorColourSet::LoadAvailableSets(), cbProject::Open(), SeqDelete::operator()(), ConfigManager::ReadAppPath(), CCTreeCtrl::RemoveDoubles(), BackgroundThread::~BackgroundThread(), BackgroundThreadPool::~BackgroundThreadPool(), NativeParser::~NativeParser(), and ParserBase::~ParserBase().
Delete() [2/4]
template<typename T > void Delete (std::list< T > & s) inline
Definition at line 21 of file safedelete.h.
Delete() [3/4]
template<typename T > void Delete (std::deque< T > & s) inline
Definition at line 22 of file safedelete.h.
Delete() [4/4]
template<typename T , typename U > void Delete (std::map< T, U > & s) inline
Definition at line 23 of file safedelete.h.