Code::Blocks: scriptingmanager.cpp File Reference
scriptingmanager.cpp File Reference
#include <sdk_precomp.h>
#include "crc32.h"
#include "menuitemsmanager.h"
#include "genericmultilinenotesdlg.h"
#include "sqplus.h"
#include "scriptbindings.h"
#include "sc_plugin.h"
#include "sqstdstring.h"
Functions
void PrintSquirrelToWxString (wxString &msg, const SQChar *s, va_list &vl)
static void ScriptsPrintFunc (HSQUIRRELVM, const SQChar *s,...)
static void CaptureScriptOutput (HSQUIRRELVM, const SQChar *s,...)
Variables
static wxString s_ScriptErrors
static wxString capture
Function Documentation
CaptureScriptOutput()
static void CaptureScriptOutput (HSQUIRRELVM , const SQChar * s, ...) static
Definition at line 74 of file scriptingmanager.cpp.
References wxString::append(), capture, and PrintSquirrelToWxString().
Referenced by ScriptingManager::LoadBufferRedirectOutput().
PrintSquirrelToWxString()
void PrintSquirrelToWxString (wxString & msg, const SQChar * s, va_list & vl)
Definition at line 43 of file scriptingmanager.cpp.
References cbC2U().
Referenced by CaptureScriptOutput(), and ScriptsPrintFunc().
ScriptsPrintFunc()
static void ScriptsPrintFunc (HSQUIRRELVM , const SQChar * s, ...) static
Definition at line 63 of file scriptingmanager.cpp.
References PrintSquirrelToWxString().
Referenced by ScriptingManager::LoadBufferRedirectOutput(), and ScriptingManager::ScriptingManager().
Variable Documentation
capture
wxString capture static
Definition at line 41 of file scriptingmanager.cpp.
Referenced by CaptureScriptOutput(), ScriptingManager::LoadBufferRedirectOutput(), and sqstd_rex_matchnode().
s_ScriptErrors
wxString s_ScriptErrors static
Definition at line 40 of file scriptingmanager.cpp.
Referenced by ScriptingManager::GetErrorString().