Code::Blocks: scriptconsole.cpp File Reference
scriptconsole.cpp File Reference
#include <sdk.h>
#include <sqplus.h>
#include "scriptconsole.h"
#include <wx/filedlg.h>
#include <wx/settings.h>
#include <wx/string.h>
#include <wx/intl.h>
#include <wx/font.h>
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/artprov.h>
Functions
static void ScriptConsolePrintFunc (HSQUIRRELVM, const SQChar *s,...)
Variables
static ScriptConsole * s_Console = nullptr
static SQPRINTFUNCTION s_OldPrintFunc = nullptr
Function Documentation
ScriptConsolePrintFunc()
static void ScriptConsolePrintFunc (HSQUIRRELVM , const SQChar * s, ...) static
Definition at line 47 of file scriptconsole.cpp.
References cbC2U(), Manager::Get(), Manager::GetScriptingManager(), ScriptingManager::InjectScriptOutput(), and ScriptConsole::Log().
Referenced by ScriptConsole::ScriptConsole().
Variable Documentation
s_Console
ScriptConsole* s_Console = nullptr static
Definition at line 44 of file scriptconsole.cpp.
s_OldPrintFunc
SQPRINTFUNCTION s_OldPrintFunc = nullptr static
Definition at line 45 of file scriptconsole.cpp.
Referenced by ScriptConsole::ScriptConsole(), and ScriptConsole::~ScriptConsole().