Code::Blocks: scriptingmanager.h File Reference
scriptingmanager.h File Reference
#include <map>
#include <set>
#include "settings.h"
#include "manager.h"
#include "menuitemsmanager.h"
#include <wx/intl.h>
Classes
class ScriptingManager
Provides scripting in Code::Blocks.
struct ScriptingManager::TrustedScriptProps
Script trusts container struct.
struct ScriptingManager::MenuBoundScript
Typedefs
typedef char SQChar
Functions
void PrintSquirrelToWxString (wxString &msg, const SQChar *s, va_list &vl)
Class Documentation
ScriptingManager::TrustedScriptProps
struct ScriptingManager::TrustedScriptProps
Script trusts container struct.
Definition at line 56 of file scriptingmanager.h.
Class Members
wxUint32 crc
bool permanent
ScriptingManager::MenuBoundScript
struct ScriptingManager::MenuBoundScript
Definition at line 239 of file scriptingmanager.h.
Class Members
bool isFunc
wxString scriptOrFunc
Typedef Documentation
SQChar
typedef char SQChar
Definition at line 258 of file scriptingmanager.h.
Function Documentation
PrintSquirrelToWxString()
void PrintSquirrelToWxString (wxString & msg, const SQChar * s, va_list & vl)
Definition at line 43 of file scriptingmanager.cpp.
References cbC2U().
Referenced by CaptureScriptOutput(), and ScriptsPrintFunc().