Code::Blocks: sdk_events.cpp File Reference
sdk_events.cpp File Reference
#include "sdk_precomp.h"
Variables
const wxEventType cbEVT_APP_STARTUP_DONE = wxNewEventType()
const wxEventType cbEVT_APP_START_SHUTDOWN = wxNewEventType()
const wxEventType cbEVT_APP_ACTIVATED = wxNewEventType()
const wxEventType cbEVT_APP_DEACTIVATED = wxNewEventType()
const wxEventType cbEVT_APP_CMDLINE = wxNewEventType()
const wxEventType cbEVT_PLUGIN_ATTACHED = wxNewEventType()
const wxEventType cbEVT_PLUGIN_RELEASED = wxNewEventType()
const wxEventType cbEVT_PLUGIN_INSTALLED = wxNewEventType()
const wxEventType cbEVT_PLUGIN_UNINSTALLED = wxNewEventType()
const wxEventType cbEVT_PLUGIN_LOADING_COMPLETE = wxNewEventType()
const wxEventType cbEVT_EDITOR_CLOSE = wxNewEventType()
const wxEventType cbEVT_EDITOR_OPEN = wxNewEventType()
const wxEventType cbEVT_EDITOR_SWITCHED = wxNewEventType()
const wxEventType cbEVT_EDITOR_ACTIVATED = wxNewEventType()
const wxEventType cbEVT_EDITOR_DEACTIVATED = wxNewEventType()
const wxEventType cbEVT_EDITOR_BEFORE_SAVE = wxNewEventType()
const wxEventType cbEVT_EDITOR_SAVE = wxNewEventType()
const wxEventType cbEVT_EDITOR_MODIFIED = wxNewEventType()
const wxEventType cbEVT_EDITOR_TOOLTIP = wxNewEventType()
const wxEventType cbEVT_EDITOR_TOOLTIP_CANCEL = wxNewEventType()
const wxEventType cbEVT_EDITOR_SPLIT = wxNewEventType()
const wxEventType cbEVT_EDITOR_UNSPLIT = wxNewEventType()
const wxEventType cbEVT_EDITOR_UPDATE_UI = wxNewEventType()
const wxEventType cbEVT_EDITOR_CC_DONE = wxNewEventType()
const wxEventType cbEVT_PROJECT_NEW = wxNewEventType()
const wxEventType cbEVT_PROJECT_CLOSE = wxNewEventType()
const wxEventType cbEVT_PROJECT_OPEN = wxNewEventType()
const wxEventType cbEVT_PROJECT_SAVE = wxNewEventType()
const wxEventType cbEVT_PROJECT_ACTIVATE = wxNewEventType()
const wxEventType cbEVT_PROJECT_BEGIN_ADD_FILES = wxNewEventType()
const wxEventType cbEVT_PROJECT_END_ADD_FILES = wxNewEventType()
const wxEventType cbEVT_PROJECT_BEGIN_REMOVE_FILES = wxNewEventType()
const wxEventType cbEVT_PROJECT_END_REMOVE_FILES = wxNewEventType()
const wxEventType cbEVT_PROJECT_FILE_ADDED = wxNewEventType()
const wxEventType cbEVT_PROJECT_FILE_REMOVED = wxNewEventType()
const wxEventType cbEVT_PROJECT_FILE_CHANGED = wxNewEventType()
const wxEventType cbEVT_PROJECT_POPUP_MENU = wxNewEventType()
const wxEventType cbEVT_PROJECT_TARGETS_MODIFIED = wxNewEventType()
const wxEventType cbEVT_PROJECT_RENAMED = wxNewEventType()
const wxEventType cbEVT_PROJECT_OPTIONS_CHANGED = wxNewEventType()
const wxEventType cbEVT_WORKSPACE_CHANGED = wxNewEventType()
const wxEventType cbEVT_WORKSPACE_LOADING_COMPLETE = wxNewEventType()
const wxEventType cbEVT_WORKSPACE_CLOSING_BEGIN = wxNewEventType()
const wxEventType cbEVT_WORKSPACE_CLOSING_COMPLETE = wxNewEventType()
const wxEventType cbEVT_BUILDTARGET_ADDED = wxNewEventType()
const wxEventType cbEVT_BUILDTARGET_REMOVED = wxNewEventType()
const wxEventType cbEVT_BUILDTARGET_RENAMED = wxNewEventType()
const wxEventType cbEVT_BUILDTARGET_SELECTED = wxNewEventType()
const wxEventType cbEVT_PIPEDPROCESS_STDOUT = wxNewEventType()
const wxEventType cbEVT_PIPEDPROCESS_STDERR = wxNewEventType()
const wxEventType cbEVT_PIPEDPROCESS_TERMINATED = wxNewEventType()
const wxEventType cbEVT_THREADTASK_STARTED = wxNewEventType()
const wxEventType cbEVT_THREADTASK_ENDED = wxNewEventType()
const wxEventType cbEVT_THREADTASK_ALLDONE = wxNewEventType()
const wxEventType cbEVT_ADD_DOCK_WINDOW = wxNewEventType()
const wxEventType cbEVT_REMOVE_DOCK_WINDOW = wxNewEventType()
const wxEventType cbEVT_SHOW_DOCK_WINDOW = wxNewEventType()
const wxEventType cbEVT_HIDE_DOCK_WINDOW = wxNewEventType()
const wxEventType cbEVT_UPDATE_VIEW_LAYOUT = wxNewEventType()
const wxEventType cbEVT_QUERY_VIEW_LAYOUT = wxNewEventType()
const wxEventType cbEVT_SWITCH_VIEW_LAYOUT = wxNewEventType()
const wxEventType cbEVT_SWITCHED_VIEW_LAYOUT = wxNewEventType()
const wxEventType cbEVT_DOCK_WINDOW_VISIBILITY = wxNewEventType()
const wxEventType cbEVT_MENUBAR_CREATE_BEGIN = wxNewEventType()
const wxEventType cbEVT_MENUBAR_CREATE_END = wxNewEventType()
const wxEventType cbEVT_COMPILER_STARTED = wxNewEventType()
const wxEventType cbEVT_COMPILER_FINISHED = wxNewEventType()
const wxEventType cbEVT_COMPILER_SET_BUILD_OPTIONS = wxNewEventType()
const wxEventType cbEVT_CLEAN_PROJECT_STARTED = wxNewEventType()
const wxEventType cbEVT_CLEAN_WORKSPACE_STARTED = wxNewEventType()
const wxEventType cbEVT_COMPILER_SETTINGS_CHANGED = wxNewEventType()
const wxEventType cbEVT_COMPILE_FILE_REQUEST = wxNewEventType()
const wxEventType cbEVT_DEBUGGER_STARTED = wxNewEventType()
const wxEventType cbEVT_DEBUGGER_PAUSED = wxNewEventType()
const wxEventType cbEVT_DEBUGGER_FINISHED = wxNewEventType()
const wxEventType cbEVT_ADD_LOG_WINDOW = wxNewEventType()
const wxEventType cbEVT_REMOVE_LOG_WINDOW = wxNewEventType()
const wxEventType cbEVT_HIDE_LOG_WINDOW = wxNewEventType()
const wxEventType cbEVT_SWITCH_TO_LOG_WINDOW = wxNewEventType()
const wxEventType cbEVT_GET_ACTIVE_LOG_WINDOW = wxNewEventType()
const wxEventType cbEVT_SHOW_LOG_MANAGER = wxNewEventType()
const wxEventType cbEVT_HIDE_LOG_MANAGER = wxNewEventType()
const wxEventType cbEVT_LOCK_LOG_MANAGER = wxNewEventType()
const wxEventType cbEVT_UNLOCK_LOG_MANAGER = wxNewEventType()
const wxEventType cbEVT_CBAUIBOOK_LEFT_DCLICK = wxNewEventType()
const wxEventType cbEVT_COMPLETE_CODE = wxNewEventType()
const wxEventType cbEVT_SHOW_CALL_TIP = wxNewEventType()
const wxEventType cbEVT_SETTINGS_CHANGED = wxNewEventType()
Variable Documentation
cbEVT_ADD_DOCK_WINDOW
const wxEventType cbEVT_ADD_DOCK_WINDOW = wxNewEventType()
Definition at line 129 of file sdk_events.cpp.
Referenced by DebugInterfaceFactory::CreateBacktrace(), DebugInterfaceFactory::CreateBreapoints(), NativeParser::CreateClassBrowser(), DebugInterfaceFactory::CreateCPURegisters(), DebugInterfaceFactory::CreateDisassembly(), DebugInterfaceFactory::CreateMemory(), DebugInterfaceFactory::CreateThreads(), DebugInterfaceFactory::CreateWatches(), and MainFrame::RegisterEvents().
cbEVT_ADD_LOG_WINDOW
const wxEventType cbEVT_ADD_LOG_WINDOW = wxNewEventType()
Definition at line 162 of file sdk_events.cpp.
Referenced by CodeBlocksLogEvent::CodeBlocksLogEvent(), FindReplace::CreateSearchLog(), DebuggerManager::GetLogger(), CompilerGCC::OnAttach(), and MainFrame::RegisterEvents().
cbEVT_APP_ACTIVATED
const wxEventType cbEVT_APP_ACTIVATED = wxNewEventType()
Definition at line 70 of file sdk_events.cpp.
Referenced by EditorManager::EditorManager(), and CodeBlocksApp::OnAppActivate().
cbEVT_APP_CMDLINE
const wxEventType cbEVT_APP_CMDLINE = wxNewEventType()
Definition at line 72 of file sdk_events.cpp.
Referenced by GetResourcesDir().
cbEVT_APP_DEACTIVATED
const wxEventType cbEVT_APP_DEACTIVATED = wxNewEventType()
Definition at line 71 of file sdk_events.cpp.
Referenced by CCManager::CCManager(), and CodeBlocksApp::OnAppActivate().
cbEVT_APP_START_SHUTDOWN
const wxEventType cbEVT_APP_START_SHUTDOWN = wxNewEventType()
Definition at line 69 of file sdk_events.cpp.
Referenced by MainFrame::OnApplicationClose().
cbEVT_APP_STARTUP_DONE
const wxEventType cbEVT_APP_STARTUP_DONE = wxNewEventType()
Definition at line 68 of file sdk_events.cpp.
Referenced by CodeCompletion::OnAttach(), CodeBlocksApp::OnInit(), and ProjectManager::ProjectManager().
cbEVT_BUILDTARGET_ADDED
const wxEventType cbEVT_BUILDTARGET_ADDED = wxNewEventType()
Definition at line 116 of file sdk_events.cpp.
Referenced by cbProject::AddBuildTarget(), DebuggerOptionsProjectDlg::DebuggerOptionsProjectDlg(), and cbProject::DuplicateBuildTarget().
cbEVT_BUILDTARGET_REMOVED
const wxEventType cbEVT_BUILDTARGET_REMOVED = wxNewEventType()
Definition at line 117 of file sdk_events.cpp.
Referenced by DebuggerOptionsProjectDlg::DebuggerOptionsProjectDlg(), and cbProject::RemoveBuildTarget().
cbEVT_BUILDTARGET_RENAMED
const wxEventType cbEVT_BUILDTARGET_RENAMED = wxNewEventType()
Definition at line 118 of file sdk_events.cpp.
Referenced by DebuggerOptionsProjectDlg::DebuggerOptionsProjectDlg(), and cbProject::RenameBuildTarget().
cbEVT_BUILDTARGET_SELECTED
const wxEventType cbEVT_BUILDTARGET_SELECTED = wxNewEventType()
Definition at line 119 of file sdk_events.cpp.
Referenced by cbProject::ClearAllProperties(), DebuggerManager::DebuggerManager(), EditorManager::EditorManager(), DebuggerGDB::OnAttachReal(), and cbProject::SetActiveBuildTarget().
cbEVT_CBAUIBOOK_LEFT_DCLICK
const wxEventType cbEVT_CBAUIBOOK_LEFT_DCLICK = wxNewEventType()
Definition at line 173 of file sdk_events.cpp.
Referenced by cbAuiNotebook::OnTabCtrlDblClick().
cbEVT_CLEAN_PROJECT_STARTED
const wxEventType cbEVT_CLEAN_PROJECT_STARTED = wxNewEventType()
Definition at line 151 of file sdk_events.cpp.
Referenced by CompilerGCC::NotifyCleanProject().
cbEVT_CLEAN_WORKSPACE_STARTED
const wxEventType cbEVT_CLEAN_WORKSPACE_STARTED = wxNewEventType()
Definition at line 152 of file sdk_events.cpp.
Referenced by CompilerGCC::NotifyCleanWorkspace().
cbEVT_COMPILE_FILE_REQUEST
const wxEventType cbEVT_COMPILE_FILE_REQUEST = wxNewEventType()
Definition at line 155 of file sdk_events.cpp.
Referenced by CompilerGCC::OnAttach().
cbEVT_COMPILER_FINISHED
const wxEventType cbEVT_COMPILER_FINISHED = wxNewEventType()
Definition at line 149 of file sdk_events.cpp.
Referenced by CompilerGCC::NotifyJobDone(), cbDebuggerPlugin::OnAttach(), and CodeBlocksApp::OnInit().
cbEVT_COMPILER_SET_BUILD_OPTIONS
const wxEventType cbEVT_COMPILER_SET_BUILD_OPTIONS = wxNewEventType()
Definition at line 150 of file sdk_events.cpp.
Referenced by CompilerCommandGenerator::Init().
cbEVT_COMPILER_SETTINGS_CHANGED
const wxEventType cbEVT_COMPILER_SETTINGS_CHANGED = wxNewEventType()
Definition at line 153 of file sdk_events.cpp.
Referenced by CompilerFactory::LoadSettings(), and CompilerFactory::SaveSettings().
cbEVT_COMPILER_STARTED
const wxEventType cbEVT_COMPILER_STARTED = wxNewEventType()
Definition at line 148 of file sdk_events.cpp.
Referenced by CompilerGCC::DoPrepareQueue().
cbEVT_COMPLETE_CODE
const wxEventType cbEVT_COMPLETE_CODE = wxNewEventType()
Definition at line 176 of file sdk_events.cpp.
Referenced by CCManager::CCManager(), MainFrame::OnEditCompleteCode(), CCManager::OnEditorHook(), and CCManager::OnTimer().
cbEVT_DEBUGGER_FINISHED
const wxEventType cbEVT_DEBUGGER_FINISHED = wxNewEventType()
Definition at line 159 of file sdk_events.cpp.
Referenced by DebuggerGDB::OnGDBTerminated().
cbEVT_DEBUGGER_PAUSED
const wxEventType cbEVT_DEBUGGER_PAUSED = wxNewEventType()
Definition at line 158 of file sdk_events.cpp.
Referenced by DebuggerGDB::DoBreak().
cbEVT_DEBUGGER_STARTED
const wxEventType cbEVT_DEBUGGER_STARTED = wxNewEventType()
Definition at line 157 of file sdk_events.cpp.
Referenced by DebuggerGDB::DoDebug().
cbEVT_DOCK_WINDOW_VISIBILITY
const wxEventType cbEVT_DOCK_WINDOW_VISIBILITY = wxNewEventType()
Definition at line 142 of file sdk_events.cpp.
Referenced by MainFrame::OnRequestHideDockWindow(), MainFrame::OnRequestShowDockWindow(), and MainFrame::RegisterEvents().
cbEVT_EDITOR_ACTIVATED
const wxEventType cbEVT_EDITOR_ACTIVATED = wxNewEventType()
Definition at line 83 of file sdk_events.cpp.
Referenced by CodeCompletion::OnAttach(), EditorManager::OnPageChanged(), MainFrame::RegisterEvents(), and EditorManager::SetActiveEditor().
cbEVT_EDITOR_BEFORE_SAVE
const wxEventType cbEVT_EDITOR_BEFORE_SAVE = wxNewEventType()
Definition at line 85 of file sdk_events.cpp.
Referenced by cbEditor::Save().
cbEVT_EDITOR_CC_DONE
const wxEventType cbEVT_EDITOR_CC_DONE = wxNewEventType()
Definition at line 93 of file sdk_events.cpp.
Referenced by CCManager::CallSmartIndentCCDone(), and cbSmartIndentPlugin::OnAttach().
cbEVT_EDITOR_CLOSE
const wxEventType cbEVT_EDITOR_CLOSE = wxNewEventType()
Definition at line 80 of file sdk_events.cpp.
Referenced by CCManager::CCManager(), CodeCompletion::OnAttach(), MainFrame::RegisterEvents(), and EditorBase::~EditorBase().
cbEVT_EDITOR_DEACTIVATED
const wxEventType cbEVT_EDITOR_DEACTIVATED = wxNewEventType()
Definition at line 84 of file sdk_events.cpp.
Referenced by CCManager::CCManager(), DebugInterfaceFactory::DebugInterfaceFactory(), and EditorManager::OnPageChanging().
cbEVT_EDITOR_MODIFIED
const wxEventType cbEVT_EDITOR_MODIFIED = wxNewEventType()
Definition at line 87 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents(), and cbEditor::SetModified().
cbEVT_EDITOR_OPEN
const wxEventType cbEVT_EDITOR_OPEN = wxNewEventType()
Definition at line 81 of file sdk_events.cpp.
Referenced by CCManager::CCManager(), EditorManager::New(), CodeCompletion::OnAttach(), cbDebuggerPlugin::OnAttach(), cbEditor::Open(), and MainFrame::RegisterEvents().
cbEVT_EDITOR_SAVE
const wxEventType cbEVT_EDITOR_SAVE = wxNewEventType()
Definition at line 86 of file sdk_events.cpp.
Referenced by CodeCompletion::OnAttach(), MainFrame::RegisterEvents(), and cbEditor::Save().
cbEVT_EDITOR_SPLIT
const wxEventType cbEVT_EDITOR_SPLIT = wxNewEventType()
Definition at line 90 of file sdk_events.cpp.
Referenced by cbEditor::Split().
cbEVT_EDITOR_SWITCHED
const wxEventType cbEVT_EDITOR_SWITCHED = wxNewEventType()
Definition at line 82 of file sdk_events.cpp.
Referenced by EditorManager::OnPageChanged(), EditorManager::OnPageClose(), and EditorManager::SetActiveEditor().
cbEVT_EDITOR_TOOLTIP
const wxEventType cbEVT_EDITOR_TOOLTIP = wxNewEventType()
Definition at line 88 of file sdk_events.cpp.
Referenced by CCManager::CCManager(), cbStyledTextCtrl::EmulateDwellStart(), cbEditor::OnEditorDwellStart(), CCManager::OnMenuSelect(), and cbDebuggerPlugin::RegisterValueTooltip().
cbEVT_EDITOR_TOOLTIP_CANCEL
const wxEventType cbEVT_EDITOR_TOOLTIP_CANCEL = wxNewEventType()
Definition at line 89 of file sdk_events.cpp.
Referenced by cbEditor::OnEditorDwellEnd(), and cbDebuggerPlugin::RegisterValueTooltip().
cbEVT_EDITOR_UNSPLIT
const wxEventType cbEVT_EDITOR_UNSPLIT = wxNewEventType()
Definition at line 91 of file sdk_events.cpp.
Referenced by cbEditor::Unsplit().
cbEVT_EDITOR_UPDATE_UI
const wxEventType cbEVT_EDITOR_UPDATE_UI = wxNewEventType()
Definition at line 92 of file sdk_events.cpp.
Referenced by cbEditor::OnEditorUpdateUI(), and MainFrame::RegisterEvents().
cbEVT_GET_ACTIVE_LOG_WINDOW
const wxEventType cbEVT_GET_ACTIVE_LOG_WINDOW = wxNewEventType()
Definition at line 166 of file sdk_events.cpp.
Referenced by CompilerGCC::OnJobEnd(), and MainFrame::RegisterEvents().
cbEVT_HIDE_DOCK_WINDOW
const wxEventType cbEVT_HIDE_DOCK_WINDOW = wxNewEventType()
Definition at line 132 of file sdk_events.cpp.
Referenced by DebuggerMenuHandler::DebuggerMenuHandler(), CodeCompletion::OnViewClassBrowser(), DebuggerMenuHandler::RegisterDefaultWindowItems(), MainFrame::RegisterEvents(), and MainFrame::ShowHideScriptConsole().
cbEVT_HIDE_LOG_MANAGER
const wxEventType cbEVT_HIDE_LOG_MANAGER = wxNewEventType()
Definition at line 168 of file sdk_events.cpp.
Referenced by CompilerGCC::NotifyJobDone(), CompilerGCC::OnJobEnd(), and MainFrame::RegisterEvents().
cbEVT_HIDE_LOG_WINDOW
const wxEventType cbEVT_HIDE_LOG_WINDOW = wxNewEventType()
Definition at line 164 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents().
cbEVT_LOCK_LOG_MANAGER
const wxEventType cbEVT_LOCK_LOG_MANAGER = wxNewEventType()
Definition at line 169 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents().
cbEVT_MENUBAR_CREATE_BEGIN
const wxEventType cbEVT_MENUBAR_CREATE_BEGIN = wxNewEventType()
Definition at line 144 of file sdk_events.cpp.
Referenced by ToolsManager::Configure(), and MainFrame::CreateMenubar().
cbEVT_MENUBAR_CREATE_END
const wxEventType cbEVT_MENUBAR_CREATE_END = wxNewEventType()
Definition at line 146 of file sdk_events.cpp.
Referenced by ToolsManager::Configure(), and MainFrame::CreateMenubar().
cbEVT_PIPEDPROCESS_STDERR
const wxEventType cbEVT_PIPEDPROCESS_STDERR = wxNewEventType()
Definition at line 122 of file sdk_events.cpp.
Referenced by PipedProcess::HasInput().
cbEVT_PIPEDPROCESS_STDOUT
const wxEventType cbEVT_PIPEDPROCESS_STDOUT = wxNewEventType()
Definition at line 121 of file sdk_events.cpp.
Referenced by PipedProcess::HasInput().
cbEVT_PIPEDPROCESS_TERMINATED
const wxEventType cbEVT_PIPEDPROCESS_TERMINATED = wxNewEventType()
Definition at line 123 of file sdk_events.cpp.
Referenced by PipedProcess::OnTerminate().
cbEVT_PLUGIN_ATTACHED
const wxEventType cbEVT_PLUGIN_ATTACHED = wxNewEventType()
Definition at line 74 of file sdk_events.cpp.
Referenced by cbPlugin::Attach(), and MainFrame::RegisterEvents().
cbEVT_PLUGIN_INSTALLED
const wxEventType cbEVT_PLUGIN_INSTALLED = wxNewEventType()
Definition at line 76 of file sdk_events.cpp.
Referenced by PluginManager::InstallPlugin(), and MainFrame::RegisterEvents().
cbEVT_PLUGIN_LOADING_COMPLETE
const wxEventType cbEVT_PLUGIN_LOADING_COMPLETE = wxNewEventType()
Definition at line 78 of file sdk_events.cpp.
Referenced by DebuggerManager::DebuggerManager(), and MainFrame::ScanForPlugins().
cbEVT_PLUGIN_RELEASED
const wxEventType cbEVT_PLUGIN_RELEASED = wxNewEventType()
Definition at line 75 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents(), and cbPlugin::Release().
cbEVT_PLUGIN_UNINSTALLED
const wxEventType cbEVT_PLUGIN_UNINSTALLED = wxNewEventType()
Definition at line 77 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents(), and PluginManager::UninstallPlugin().
cbEVT_PROJECT_ACTIVATE
const wxEventType cbEVT_PROJECT_ACTIVATE = wxNewEventType()
Definition at line 99 of file sdk_events.cpp.
Referenced by DebuggerManager::DebuggerManager(), EditorManager::EditorManager(), CodeCompletion::OnAttach(), CompilerGCC::OnAttach(), cbDebuggerPlugin::OnAttach(), MainFrame::RegisterEvents(), and ProjectManager::SetProject().
cbEVT_PROJECT_BEGIN_ADD_FILES
const wxEventType cbEVT_PROJECT_BEGIN_ADD_FILES = wxNewEventType()
Definition at line 100 of file sdk_events.cpp.
Referenced by cbProject::BeginAddFiles().
cbEVT_PROJECT_BEGIN_REMOVE_FILES
const wxEventType cbEVT_PROJECT_BEGIN_REMOVE_FILES = wxNewEventType()
Definition at line 102 of file sdk_events.cpp.
Referenced by cbProject::BeginRemoveFiles().
cbEVT_PROJECT_CLOSE
const wxEventType cbEVT_PROJECT_CLOSE = wxNewEventType()
Definition at line 96 of file sdk_events.cpp.
Referenced by ProjectManager::CloseProject(), CodeCompletion::OnAttach(), CompilerGCC::OnAttach(), cbDebuggerPlugin::OnAttach(), and MainFrame::RegisterEvents().
cbEVT_PROJECT_END_ADD_FILES
const wxEventType cbEVT_PROJECT_END_ADD_FILES = wxNewEventType()
Definition at line 101 of file sdk_events.cpp.
Referenced by cbProject::EndAddFiles().
cbEVT_PROJECT_END_REMOVE_FILES
const wxEventType cbEVT_PROJECT_END_REMOVE_FILES = wxNewEventType()
Definition at line 103 of file sdk_events.cpp.
Referenced by cbProject::EndRemoveFiles().
cbEVT_PROJECT_FILE_ADDED
const wxEventType cbEVT_PROJECT_FILE_ADDED = wxNewEventType()
Definition at line 104 of file sdk_events.cpp.
Referenced by ProjectManager::AddFileToProject(), ProjectManager::AddMultipleFilesToProject(), and CodeCompletion::OnAttach().
cbEVT_PROJECT_FILE_CHANGED
const wxEventType cbEVT_PROJECT_FILE_CHANGED = wxNewEventType()
Definition at line 106 of file sdk_events.cpp.
Referenced by CodeCompletion::OnAttach().
cbEVT_PROJECT_FILE_REMOVED
const wxEventType cbEVT_PROJECT_FILE_REMOVED = wxNewEventType()
Definition at line 105 of file sdk_events.cpp.
Referenced by CodeCompletion::OnAttach(), and ProjectManager::RemoveFileFromProject().
cbEVT_PROJECT_NEW
const wxEventType cbEVT_PROJECT_NEW = wxNewEventType()
Definition at line 95 of file sdk_events.cpp.
Referenced by MainFrame::OnFileNewWhat().
cbEVT_PROJECT_OPEN
const wxEventType cbEVT_PROJECT_OPEN = wxNewEventType()
Definition at line 97 of file sdk_events.cpp.
Referenced by DebuggerManager::DebuggerManager(), ProjectManager::EndLoadingProject(), ProjectManager::EndLoadingWorkspace(), TemplateManager::NewProjectFromUserTemplate(), CompilerGCC::OnAttach(), MainFrame::OnFileNewWhat(), and MainFrame::RegisterEvents().
cbEVT_PROJECT_OPTIONS_CHANGED
const wxEventType cbEVT_PROJECT_OPTIONS_CHANGED = wxNewEventType()
Definition at line 110 of file sdk_events.cpp.
Referenced by ProjectManagerUI::CheckForExternallyModifiedProjects().
cbEVT_PROJECT_POPUP_MENU
const wxEventType cbEVT_PROJECT_POPUP_MENU = wxNewEventType()
Definition at line 107 of file sdk_events.cpp.
cbEVT_PROJECT_RENAMED
const wxEventType cbEVT_PROJECT_RENAMED = wxNewEventType()
Definition at line 109 of file sdk_events.cpp.
Referenced by cbProject::SetTitle().
cbEVT_PROJECT_SAVE
const wxEventType cbEVT_PROJECT_SAVE = wxNewEventType()
Definition at line 98 of file sdk_events.cpp.
Referenced by CodeCompletion::OnAttach(), cbProject::Save(), and cbProject::SaveAs().
cbEVT_PROJECT_TARGETS_MODIFIED
const wxEventType cbEVT_PROJECT_TARGETS_MODIFIED = wxNewEventType()
Definition at line 108 of file sdk_events.cpp.
Referenced by cbProject::AddBuildTarget(), cbProject::DefineVirtualBuildTarget(), cbProject::DuplicateBuildTarget(), ProjectOptionsDlg::OnAddBuildTargetClick(), CompilerGCC::OnAttach(), ProjectOptionsDlg::OnBuildOrderClick(), ProjectOptionsDlg::OnBuildTargetChanged(), ProjectOptionsDlg::OnCopyBuildTargetClick(), ProjectOptionsDlg::OnEditBuildTargetClick(), ProjectOptionsDlg::OnRemoveBuildTargetClick(), cbProject::RemoveBuildTarget(), cbProject::RemoveVirtualBuildTarget(), and cbProject::RenameBuildTarget().
cbEVT_QUERY_VIEW_LAYOUT
const wxEventType cbEVT_QUERY_VIEW_LAYOUT = wxNewEventType()
Definition at line 136 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents(), and cbDebuggerPlugin::SwitchToDebuggingLayout().
cbEVT_REMOVE_DOCK_WINDOW
const wxEventType cbEVT_REMOVE_DOCK_WINDOW = wxNewEventType()
Definition at line 130 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents(), NativeParser::RemoveClassBrowser(), and RemoveDockWindow().
cbEVT_REMOVE_LOG_WINDOW
const wxEventType cbEVT_REMOVE_LOG_WINDOW = wxNewEventType()
Definition at line 163 of file sdk_events.cpp.
Referenced by DebuggerManager::HideLogger(), CompilerGCC::OnRelease(), and MainFrame::RegisterEvents().
cbEVT_SETTINGS_CHANGED
const wxEventType cbEVT_SETTINGS_CHANGED = wxNewEventType()
Definition at line 179 of file sdk_events.cpp.
Referenced by DebuggerManager::DebuggerManager(), MainFrame::OnSettingsCompiler(), MainFrame::OnSettingsDebugger(), MainFrame::OnSettingsEditor(), MainFrame::OnSettingsEnvironment(), and MainFrame::OnSettingsPlugins().
cbEVT_SHOW_CALL_TIP
const wxEventType cbEVT_SHOW_CALL_TIP = wxNewEventType()
Definition at line 177 of file sdk_events.cpp.
Referenced by CCManager::CCManager(), CCManager::OnDeferredCallTipShow(), and MainFrame::OnEditShowCallTip().
cbEVT_SHOW_DOCK_WINDOW
const wxEventType cbEVT_SHOW_DOCK_WINDOW = wxNewEventType()
Definition at line 131 of file sdk_events.cpp.
Referenced by DebuggerMenuHandler::DebuggerMenuHandler(), DebuggerMenuHandler::OnAddWatch(), CodeCompletion::OnViewClassBrowser(), DebuggerMenuHandler::RegisterDefaultWindowItems(), MainFrame::RegisterEvents(), DebuggerManager::ShowBacktraceDialog(), MainFrame::ShowHideScriptConsole(), and ProjectManagerUI::SwitchToProjectsPage().
cbEVT_SHOW_LOG_MANAGER
const wxEventType cbEVT_SHOW_LOG_MANAGER = wxNewEventType()
Definition at line 167 of file sdk_events.cpp.
Referenced by CodeRefactoring::DoFindReferences(), FindReplace::FindInFiles(), CompilerGCC::OnJobEnd(), CompilerGCC::PrintBanner(), MainFrame::RegisterEvents(), and cbDebuggerPlugin::ShowLog().
cbEVT_SWITCH_TO_LOG_WINDOW
const wxEventType cbEVT_SWITCH_TO_LOG_WINDOW = wxNewEventType()
Definition at line 165 of file sdk_events.cpp.
Referenced by CompilerGCC::ClearLog(), CodeRefactoring::DoFindReferences(), ToolsManager::Execute(), FindReplace::FindInFiles(), CompilerGCC::OnJobEnd(), MainFrame::RegisterEvents(), cbDebuggerPlugin::ShowLog(), and CompilerGCC::StartCompileFile().
cbEVT_SWITCH_VIEW_LAYOUT
const wxEventType cbEVT_SWITCH_VIEW_LAYOUT = wxNewEventType()
Definition at line 138 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents(), cbDebuggerPlugin::SwitchToDebuggingLayout(), and cbDebuggerPlugin::SwitchToPreviousLayout().
cbEVT_SWITCHED_VIEW_LAYOUT
const wxEventType cbEVT_SWITCHED_VIEW_LAYOUT = wxNewEventType()
Definition at line 140 of file sdk_events.cpp.
Referenced by MainFrame::LoadViewLayout().
cbEVT_THREADTASK_ALLDONE
const wxEventType cbEVT_THREADTASK_ALLDONE = wxNewEventType()
Definition at line 127 of file sdk_events.cpp.
Referenced by Parser::ConnectEvents(), Parser::DisconnectEvents(), and cbThreadPool::WaitingThread().
cbEVT_THREADTASK_ENDED
const wxEventType cbEVT_THREADTASK_ENDED = wxNewEventType()
Definition at line 126 of file sdk_events.cpp.
Referenced by cbThreadPool::TaskDone().
cbEVT_THREADTASK_STARTED
const wxEventType cbEVT_THREADTASK_STARTED = wxNewEventType()
Definition at line 125 of file sdk_events.cpp.
cbEVT_UNLOCK_LOG_MANAGER
const wxEventType cbEVT_UNLOCK_LOG_MANAGER = wxNewEventType()
Definition at line 170 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents().
cbEVT_UPDATE_VIEW_LAYOUT
const wxEventType cbEVT_UPDATE_VIEW_LAYOUT = wxNewEventType()
Definition at line 134 of file sdk_events.cpp.
Referenced by MainFrame::RegisterEvents(), and CodeCompletion::RereadOptions().
cbEVT_WORKSPACE_CHANGED
const wxEventType cbEVT_WORKSPACE_CHANGED = wxNewEventType()
Definition at line 111 of file sdk_events.cpp.
Referenced by CodeCompletion::OnAttach(), and ProjectManager::WorkspaceChanged().
cbEVT_WORKSPACE_CLOSING_BEGIN
const wxEventType cbEVT_WORKSPACE_CLOSING_BEGIN = wxNewEventType()
Definition at line 113 of file sdk_events.cpp.
Referenced by ProjectManager::CloseWorkspace().
cbEVT_WORKSPACE_CLOSING_COMPLETE
const wxEventType cbEVT_WORKSPACE_CLOSING_COMPLETE = wxNewEventType()
Definition at line 114 of file sdk_events.cpp.
Referenced by ProjectManager::CloseWorkspace().
cbEVT_WORKSPACE_LOADING_COMPLETE
const wxEventType cbEVT_WORKSPACE_LOADING_COMPLETE = wxNewEventType()
Definition at line 112 of file sdk_events.cpp.
Referenced by EditorManager::EditorManager(), and ProjectManager::LoadWorkspace().