Code::Blocks: sqdebug.cpp File Reference
sqdebug.cpp File Reference
#include "sqpcheader.h"
#include <stdarg.h>
#include "sqvm.h"
#include "sqfuncproto.h"
#include "sqclosure.h"
#include "sqstring.h"
Functions
SQRESULT sq_getfunctioninfo (HSQUIRRELVM v, SQInteger level, SQFunctionInfo *fi)
SQRESULT sq_stackinfos (HSQUIRRELVM v, SQInteger level, SQStackInfos *si)
Function Documentation
sq_getfunctioninfo()
SQRESULT sq_getfunctioninfo (HSQUIRRELVM v, SQInteger level, SQFunctionInfo * fi)
Definition at line 11 of file sqdebug.cpp.
References sq_throwerror().
sq_stackinfos()
SQRESULT sq_stackinfos (HSQUIRRELVM v, SQInteger level, SQStackInfos * si)
Definition at line 28 of file sqdebug.cpp.
References GetTypeName(), and IdType2Name().
Referenced by base_getstackinfos(), and sqstd_printcallstack().