Code::Blocks: sqstdaux.cpp File Reference
sqstdaux.cpp File Reference
#include <squirrel.h>
#include <sqstdaux.h>
#include <assert.h>
Functions
void sqstd_printcallstack (HSQUIRRELVM v)
static SQInteger _sqstd_aux_printerror (HSQUIRRELVM v)
void _sqstd_compiler_error (HSQUIRRELVM v, const SQChar *sErr, const SQChar *sSource, SQInteger line, SQInteger column)
void sqstd_seterrorhandlers (HSQUIRRELVM v)
Function Documentation
_sqstd_aux_printerror()
static SQInteger _sqstd_aux_printerror (HSQUIRRELVM v) static
Definition at line 99 of file sqstdaux.cpp.
References sq_getprintfunc(), sq_getstring(), sq_gettop(), and sqstd_printcallstack().
Referenced by sqstd_seterrorhandlers().
_sqstd_compiler_error()
void _sqstd_compiler_error (HSQUIRRELVM v, const SQChar * sErr, const SQChar * sSource, SQInteger line, SQInteger column)
Definition at line 117 of file sqstdaux.cpp.
References sq_getprintfunc().
Referenced by sqstd_seterrorhandlers().
sqstd_printcallstack()
void sqstd_printcallstack (HSQUIRRELVM v)
Definition at line 6 of file sqstdaux.cpp.
References sq_getbool(), sq_getfloat(), sq_getinteger(), sq_getlocal(), sq_getprintfunc(), sq_getstring(), sq_gettype(), sq_pop(), and sq_stackinfos().
Referenced by _sqstd_aux_printerror().
sqstd_seterrorhandlers()
void sqstd_seterrorhandlers (HSQUIRRELVM v)
Definition at line 125 of file sqstdaux.cpp.
References _sqstd_aux_printerror(), _sqstd_compiler_error(), sq_newclosure(), sq_setcompilererrorhandler(), and sq_seterrorhandler().