Code::Blocks: sqstdstream.cpp File Reference
sqstdstream.cpp File Reference
#include <new>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <squirrel.h>
#include <sqstdio.h>
#include <sqstdblob.h>
#include "sqstdstream.h"
#include "sqstdblobimpl.h"
Macros
#define SETUP_STREAM(v)
#define SAFE_READN(ptr, len)
Functions
SQInteger _stream_readblob (HSQUIRRELVM v)
SQInteger _stream_readn (HSQUIRRELVM v)
SQInteger _stream_writeblob (HSQUIRRELVM v)
SQInteger _stream_writen (HSQUIRRELVM v)
SQInteger _stream_seek (HSQUIRRELVM v)
SQInteger _stream_tell (HSQUIRRELVM v)
SQInteger _stream_len (HSQUIRRELVM v)
SQInteger _stream_flush (HSQUIRRELVM v)
SQInteger _stream_eos (HSQUIRRELVM v)
void init_streamclass (HSQUIRRELVM v)
SQRESULT declare_stream (HSQUIRRELVM v, const SQChar *name, SQUserPointer typetag, const SQChar *reg_name, SQRegFunction *methods, SQRegFunction *globals)
Variables
static SQRegFunction _stream_methods []
Macro Definition Documentation
SAFE_READN
#define SAFE_READN (ptr, len)
Value:
{ \
    if(self->Read(ptr,len) != len) return sq_throwerror(v,_SC("io error")); \
    }
Definition at line 37 of file sqstdstream.cpp.
Referenced by _stream_readn().
SETUP_STREAM
#define SETUP_STREAM (v)
Value:
SQStream *self = NULL; \
    if(SQ_FAILED(sq_getinstanceup(v,1,(SQUserPointer*)&self,(SQUserPointer)SQSTD_STREAM_TYPE_TAG))) \
        return sq_throwerror(v,_SC("invalid type tag")); \
    if(!self->IsValid())  \
        return sq_throwerror(v,_SC("the stream is invalid"));
Definition at line 12 of file sqstdstream.cpp.
Referenced by _stream_eos(), _stream_flush(), _stream_len(), _stream_readblob(), _stream_readn(), _stream_seek(), _stream_tell(), _stream_writeblob(), and _stream_writen().
Function Documentation
_stream_eos()
SQInteger _stream_eos (HSQUIRRELVM v)
Definition at line 226 of file sqstdstream.cpp.
References SETUP_STREAM, sq_pushinteger(), and sq_pushnull().
_stream_flush()
SQInteger _stream_flush (HSQUIRRELVM v)
Definition at line 216 of file sqstdstream.cpp.
References SETUP_STREAM, sq_pushinteger(), and sq_pushnull().
_stream_len()
SQInteger _stream_len (HSQUIRRELVM v)
Definition at line 209 of file sqstdstream.cpp.
References SETUP_STREAM, and sq_pushinteger().
_stream_readblob()
SQInteger _stream_readblob (HSQUIRRELVM v)
Definition at line 19 of file sqstdstream.cpp.
References SETUP_STREAM, sq_getinteger(), sq_getscratchpad(), sq_throwerror(), and sqstd_createblob().
_stream_readn()
SQInteger _stream_readn (HSQUIRRELVM v)
Definition at line 40 of file sqstdstream.cpp.
References SAFE_READN, SETUP_STREAM, sq_getinteger(), sq_pushfloat(), sq_pushinteger(), and sq_throwerror().
_stream_seek()
SQInteger _stream_seek (HSQUIRRELVM v)
Definition at line 183 of file sqstdstream.cpp.
References SETUP_STREAM, sq_getinteger(), sq_gettop(), sq_pushinteger(), and sq_throwerror().
_stream_tell()
SQInteger _stream_tell (HSQUIRRELVM v)
Definition at line 202 of file sqstdstream.cpp.
References SETUP_STREAM, and sq_pushinteger().
_stream_writeblob()
SQInteger _stream_writeblob (HSQUIRRELVM v)
Definition at line 100 of file sqstdstream.cpp.
References SETUP_STREAM, sq_pushinteger(), sq_throwerror(), sqstd_getblob(), and sqstd_getblobsize().
_stream_writen()
SQInteger _stream_writen (HSQUIRRELVM v)
Definition at line 114 of file sqstdstream.cpp.
References SETUP_STREAM, sq_getfloat(), sq_getinteger(), and sq_throwerror().
declare_stream()
SQRESULT declare_stream (HSQUIRRELVM v, const SQChar * name, SQUserPointer typetag, const SQChar * reg_name, SQRegFunction * methods, SQRegFunction * globals)
Definition at line 280 of file sqstdstream.cpp.
References init_streamclass(), sq_get(), sq_gettop(), sq_gettype(), sq_newclass(), sq_newclosure(), sq_pop(), sq_pushregistrytable(), sq_pushstring(), sq_remove(), sq_setnativeclosurename(), sq_setparamscheck(), sq_settop(), sq_settypetag(), and sq_throwerror().
Referenced by sqstd_register_bloblib(), and sqstd_register_iolib().
init_streamclass()
void init_streamclass (HSQUIRRELVM v)
Definition at line 249 of file sqstdstream.cpp.
References _stream_methods, sq_get(), sq_newclass(), sq_newclosure(), sq_pop(), sq_pushregistrytable(), sq_pushroottable(), sq_pushstring(), sq_setparamscheck(), and sq_settypetag().
Referenced by declare_stream().
Variable Documentation
_stream_methods
SQRegFunction _stream_methods[] static
Initial value:
= {
    _DECL_STREAM_FUNC(readblob,2,_SC("xn")),
    _DECL_STREAM_FUNC(readn,2,_SC("xn")),
    _DECL_STREAM_FUNC(writeblob,-2,_SC("xx")),
    _DECL_STREAM_FUNC(writen,3,_SC("xnn")),
    _DECL_STREAM_FUNC(seek,-2,_SC("xnn")),
    _DECL_STREAM_FUNC(tell,1,_SC("x")),
    _DECL_STREAM_FUNC(len,1,_SC("x")),
    _DECL_STREAM_FUNC(eos,1,_SC("x")),
    _DECL_STREAM_FUNC(flush,1,_SC("x")),
    {0,0}
}
Definition at line 236 of file sqstdstream.cpp.
Referenced by init_streamclass().