Code::Blocks: SquirrelBindingsUtilsWin32.cpp File Reference
SquirrelBindingsUtilsWin32.cpp File Reference
#include "SquirrelBindingsUtilsWin32.h"
Functions
SQInteger refcounted_release_hook (SQUserPointer p, SQInteger)
static BOOL __CreateRefCountedInstance (HSQUIRRELVM v, const SQChar *classname, IUnknown *pRC, SQRELEASEHOOK hook)
SQInteger construct_RefCounted (IUnknown *p)
BOOL CreateRefCountedInstance (HSQUIRRELVM v, const SQChar *classname, IUnknown *pRC)
Function Documentation
__CreateRefCountedInstance()
static BOOL __CreateRefCountedInstance (HSQUIRRELVM v, const SQChar * classname, IUnknown * pRC, SQRELEASEHOOK hook) static
Definition at line 15 of file SquirrelBindingsUtilsWin32.cpp.
References CreateNativeClassInstance().
Referenced by CreateRefCountedInstance().
construct_RefCounted()
SQInteger construct_RefCounted (IUnknown * p)
Definition at line 21 of file SquirrelBindingsUtilsWin32.cpp.
References refcounted_release_hook(), sq_setinstanceup(), and sq_setreleasehook().
CreateRefCountedInstance()
BOOL CreateRefCountedInstance (HSQUIRRELVM v, const SQChar * classname, IUnknown * pRC)
Definition at line 29 of file SquirrelBindingsUtilsWin32.cpp.
References __CreateRefCountedInstance(), and refcounted_release_hook().
refcounted_release_hook()
SQInteger refcounted_release_hook (SQUserPointer p, SQInteger)
Definition at line 8 of file SquirrelBindingsUtilsWin32.cpp.
Referenced by construct_RefCounted(), and CreateRefCountedInstance().