Code::Blocks: SquirrelBindingsUtils.cpp File Reference
SquirrelBindingsUtils.cpp File Reference
#include "sqplus.h"
Functions
BOOL_T CreateStaticNamespace (HSQUIRRELVM v, ScriptNamespaceDecl *sn)
BOOL_T CreateClass (HSQUIRRELVM v, SquirrelClassDecl *cd)
BOOL_T CreateNativeClassInstance (HSQUIRRELVM v, const SQChar *classname, SQUserPointer ud, SQRELEASEHOOK hook)
Function Documentation
CreateClass()
BOOL_T CreateClass (HSQUIRRELVM v, SquirrelClassDecl * cd)
Definition at line 60 of file SquirrelBindingsUtils.cpp.
References NULL, sq_get(), sq_gettop(), sq_newclass(), sq_newclosure(), sq_pop(), sq_pushroottable(), sq_pushstring(), sq_setnativeclosurename(), sq_setparamscheck(), sq_settop(), and sq_settypetag().
CreateNativeClassInstance()
BOOL_T CreateNativeClassInstance (HSQUIRRELVM v, const SQChar * classname, SQUserPointer ud, SQRELEASEHOOK hook)
Definition at line 101 of file SquirrelBindingsUtils.cpp.
References sq_createinstance(), sq_gettop(), sq_pushroottable(), sq_pushstring(), sq_rawget(), sq_remove(), sq_setinstanceup(), sq_setreleasehook(), and sq_settop().
Referenced by __CreateRefCountedInstance(), SqPlus::getVar(), and SqPlus::setVar().
CreateStaticNamespace()
BOOL_T CreateStaticNamespace (HSQUIRRELVM v, ScriptNamespaceDecl * sn)
Definition at line 5 of file SquirrelBindingsUtils.cpp.
References NULL, sq_newclosure(), sq_newtable(), sq_pop(), sq_pushfloat(), sq_pushinteger(), sq_pushroottable(), sq_pushstring(), sq_setdelegate(), sq_setnativeclosurename(), and sq_setparamscheck().