Code::Blocks: startherepage.cpp File Reference
startherepage.cpp File Reference
#include <sdk.h>
#include <wx/dataobj.h>
#include <wx/intl.h>
#include <wx/utils.h>
#include <wx/sizer.h>
#include <wx/settings.h>
#include <manager.h>
#include <logmanager.h>
#include <projectmanager.h>
#include <templatemanager.h>
#include <pluginmanager.h>
#include <editormanager.h>
#include <configmanager.h>
#include "startherepage.h"
#include "main.h"
#include "appglobals.h"
#include "cbcolourmanager.h"
#include "recentitemslist.h"
#include <wx/clipbrd.h>
#include <wx/docview.h>
#include <wx/wxhtml.h>
Classes
class MyHtmlWin
Variables
const wxString g_StartHereTitle = _("Start here")
int idWin = wxNewId()
Variable Documentation
const wxString g_StartHereTitle = _("Start here")
Referenced by MainFrame::OnFileMenuUpdateUI(), MainFrame::OnToggleStartPage(), MainFrame::OnViewMenuUpdateUI(), RecentItemsList::RefreshStartHerePage(), and MainFrame::ShowHideStartPage().
int idWin = wxNewId()
Referenced by StartHerePage::StartHerePage().