Code::Blocks: OpenContainingFolderData Struct Reference
OpenContainingFolderData Struct Reference
Public Member Functions
OpenContainingFolderData ()
OpenContainingFolderData (const wxString &command, bool select)
Public Attributes
wxString command
bool supportSelect
Detailed Description
Definition at line 1081 of file editormanager.cpp.
Constructor & Destructor Documentation
OpenContainingFolderData() [1/2]
OpenContainingFolderData::OpenContainingFolderData () inline
Definition at line 1086 of file editormanager.cpp.
OpenContainingFolderData() [2/2]
OpenContainingFolderData::OpenContainingFolderData (const wxString & command, bool select) inline
Definition at line 1087 of file editormanager.cpp.
References _T, cbDEFAULT_OPEN_FOLDER_CMD, LogManager::DebugLog(), DEFAULT_CONSOLE_SHELL, wxString::EndsWith(), F(), wxString::find(), Manager::Get(), wxArrayString::GetCount(), Manager::GetLogManager(), wxString::length(), wxString::npos, ConfigManager::Read(), wxString::StartsWith(), wxString::substr(), wxString::wx_str(), wxEXEC_SYNC, wxExecute(), wxStringTokenize(), and wxT.
Member Data Documentation
command
wxString OpenContainingFolderData::command
Definition at line 1083 of file editormanager.cpp.
Referenced by EditorManager::OpenContainingFolder().
supportSelect
bool OpenContainingFolderData::supportSelect
Definition at line 1084 of file editormanager.cpp.
Referenced by EditorManager::OpenContainingFolder().
The documentation for this struct was generated from the following file:
editormanager.cpp