Code::Blocks: cbEditorInternalData Struct Reference
cbEditorInternalData Struct Reference
Public Member Functions
cbEditorInternalData (cbEditor *owner, LoaderBase *fileLoader=nullptr)
~cbEditorInternalData ()
void StripTrailingSpaces ()
Strip trailing blanks before saving.
void EnsureFinalLineEnd ()
Add extra blank line to the file.
void EnsureConsistentLineEnds ()
Make sure all the lines end with the same EOL mode.
void SetLineNumberColWidth (bool both=true)
Set line number column width.
void SetFoldingColWidth (bool both=true)
wxString GetUrl ()
Static Public Member Functions
static wxString GetLineIndentString (int line, cbStyledTextCtrl *stc)
static int DetectIndentStyle (cbStyledTextCtrl *stc)
Detect the indentation style used in a document.
Public Attributes
cbEditor * m_pOwner
bool m_strip_trailing_spaces
bool m_ensure_final_line_end
bool m_ensure_consistent_line_ends
int m_LastMarginMenuLine
int m_LastDebugLine
bool mFoldingLimit
int mFoldingLimitLevel
wxFontEncoding m_encoding
bool m_useByteOrderMark
int m_byteOrderMarkLength
int m_lineNumbersWidth
int m_lineNumbersWidth2
LoaderBase * m_pFileLoader
Detailed Description
Definition at line 94 of file cbeditor.cpp.
Constructor & Destructor Documentation
cbEditorInternalData()
cbEditorInternalData::cbEditorInternalData (cbEditor * owner, LoaderBase * fileLoader = nullptr) inline
Definition at line 98 of file cbeditor.cpp.
References _T, LogManager::DebugLog(), F(), Manager::Get(), EncodingDetector::GetBOMSizeInBytes(), EncodingDetector::GetFontEncoding(), Manager::GetLogManager(), wxLocale::GetSystemEncoding(), EncodingDetector::IsOK(), m_byteOrderMarkLength, m_encoding, m_pFileLoader, m_useByteOrderMark, wxStopWatch::Time(), and EncodingDetector::UsesBOM().
~cbEditorInternalData()
cbEditorInternalData::~cbEditorInternalData () inline
Definition at line 131 of file cbeditor.cpp.
References m_pFileLoader.
Member Function Documentation
DetectIndentStyle()
static int cbEditorInternalData::DetectIndentStyle (cbStyledTextCtrl * stc) inline static
Detect the indentation style used in a document.
Values for the thresholds are from trial and error over many example files. If this function is not certain on the style used, it will return -1.
Definition at line 400 of file cbeditor.cpp.
References wxString::Find(), wxScintilla::GetLineCount(), GetLineIndentString(), wxString::IsEmpty(), wxString::Length(), wxNOT_FOUND, and wxT.
Referenced by cbEditor::InternalSetEditorStyleAfterFileOpen().
EnsureConsistentLineEnds()
void cbEditorInternalData::EnsureConsistentLineEnds () inline
Make sure all the lines end with the same EOL mode.
Definition at line 183 of file cbeditor.cpp.
References wxScintilla::ConvertEOLs(), cbEditor::GetControl(), and wxScintilla::GetEOLMode().
Referenced by cbEditor::Save().
EnsureFinalLineEnd()
void cbEditorInternalData::EnsureFinalLineEnd () inline
Add extra blank line to the file.
Definition at line 172 of file cbeditor.cpp.
References cbEditor::GetControl(), wxScintilla::GetEOLMode(), GetEOLStr(), wxScintilla::GetLineCount(), wxScintilla::InsertText(), and wxScintilla::PositionFromLine().
Referenced by cbEditor::Save().
GetLineIndentString()
static wxString cbEditorInternalData::GetLineIndentString (int line, cbStyledTextCtrl * stc) inline static
Definition at line 373 of file cbeditor.cpp.
References _T, wxScintilla::GetCurrentPos(), wxScintilla::GetLine(), wxString::Length(), and wxScintilla::LineFromPosition().
Referenced by DetectIndentStyle(), and cbEditor::GetLineIndentString().
GetUrl()
wxString cbEditorInternalData::GetUrl () inline
Definition at line 304 of file cbeditor.cpp.
References wxString::Find(), wxString::find_last_not_of(), wxScintilla::GetCharAt(), cbEditor::GetControl(), wxScintilla::GetCurrentPos(), wxScintilla::GetLexer(), wxScintilla::GetLineCount(), wxScintilla::GetLineEndPosition(), wxRegEx::GetMatch(), wxScintilla::GetSelectedText(), wxScintilla::GetStyleAt(), wxScintilla::GetTextRange(), wxString::Length(), wxRegEx::Matches(), wxString::Replace(), ParserConsts::space, wxEmptyString, wxSCI_C_STRING, wxSCI_C_STRINGEOL, wxSCI_LEX_CPP, and wxT.
Referenced by cbEditor::AddToContextMenu(), and cbEditor::OnContextMenuEntry().
SetFoldingColWidth()
void cbEditorInternalData::SetFoldingColWidth (bool both = true) inline
Definition at line 278 of file cbeditor.cpp.
References C_FOLDING_MARGIN, cbEditor::GetControl(), wxFont::GetPointSize(), wxScintilla::GetZoom(), cbEditor::m_pControl, cbEditor::m_pControl2, wxScintilla::SetMarginWidth(), wxScintilla::StyleGetFont(), and wxSCI_STYLE_DEFAULT.
Referenced by cbEditor::OnZoom().
SetLineNumberColWidth()
void cbEditorInternalData::SetLineNumberColWidth (bool both = true) inline
Set line number column width.
Definition at line 191 of file cbeditor.cpp.
References _T, C_LINE_MARGIN, Manager::Get(), Manager::GetConfigManager(), cbEditor::GetControl(), wxScintilla::GetLineCount(), m_lineNumbersWidth, m_lineNumbersWidth2, cbEditor::m_pControl, cbEditor::m_pControl2, ConfigManager::ReadBool(), ConfigManager::ReadInt(), wxScintilla::SetMarginWidth(), wxScintilla::TextWidth(), and wxSCI_STYLE_LINENUMBER.
Referenced by cbEditor::OnEditorModified(), cbEditor::OnZoom(), cbEditor::SetEditorStyleAfterFileOpen(), and cbEditor::SetProjectFile().
StripTrailingSpaces()
void cbEditorInternalData::StripTrailingSpaces () inline
Strip trailing blanks before saving.
Definition at line 143 of file cbeditor.cpp.
References _T, wxScintilla::GetCharAt(), cbEditor::GetControl(), wxScintilla::GetLexer(), wxScintilla::GetLineCount(), wxScintilla::GetLineEndPosition(), wxScintilla::PositionFromLine(), wxScintilla::ReplaceTarget(), wxScintilla::SetTargetEnd(), wxScintilla::SetTargetStart(), and wxSCI_LEX_DIFF.
Referenced by cbEditor::Save().
Member Data Documentation
m_byteOrderMarkLength
int cbEditorInternalData::m_byteOrderMarkLength
Definition at line 493 of file cbeditor.cpp.
Referenced by cbEditorInternalData(), and cbEditor::Open().
m_encoding
wxFontEncoding cbEditorInternalData::m_encoding
Definition at line 491 of file cbeditor.cpp.
Referenced by cbEditorInternalData(), cbEditor::CreateEditor(), cbEditor::GetEncoding(), cbEditor::Open(), and cbEditor::SetEncoding().
m_ensure_consistent_line_ends
bool cbEditorInternalData::m_ensure_consistent_line_ends
Definition at line 483 of file cbeditor.cpp.
Referenced by cbEditor::Save(), and cbEditor::SetEditorStyleBeforeFileOpen().
m_ensure_final_line_end
bool cbEditorInternalData::m_ensure_final_line_end
Definition at line 482 of file cbeditor.cpp.
Referenced by cbEditor::Save(), and cbEditor::SetEditorStyleBeforeFileOpen().
m_LastDebugLine
int cbEditorInternalData::m_LastDebugLine
Definition at line 486 of file cbeditor.cpp.
Referenced by cbEditor::SetDebugLine().
m_LastMarginMenuLine
int cbEditorInternalData::m_LastMarginMenuLine
Definition at line 485 of file cbeditor.cpp.
Referenced by cbEditor::OnBeforeBuildContextMenu(), and cbEditor::OnContextMenuEntry().
m_lineNumbersWidth
int cbEditorInternalData::m_lineNumbersWidth
Definition at line 495 of file cbeditor.cpp.
Referenced by SetLineNumberColWidth().
m_lineNumbersWidth2
int cbEditorInternalData::m_lineNumbersWidth2
Definition at line 496 of file cbeditor.cpp.
Referenced by SetLineNumberColWidth().
m_pFileLoader
LoaderBase* cbEditorInternalData::m_pFileLoader
Definition at line 498 of file cbeditor.cpp.
Referenced by cbEditorInternalData(), cbEditor::DoInitializations(), cbEditor::Open(), and ~cbEditorInternalData().
m_pOwner
cbEditor* cbEditorInternalData::m_pOwner
Definition at line 96 of file cbeditor.cpp.
m_strip_trailing_spaces
bool cbEditorInternalData::m_strip_trailing_spaces
Definition at line 481 of file cbeditor.cpp.
Referenced by cbEditor::Save(), and cbEditor::SetEditorStyleBeforeFileOpen().
m_useByteOrderMark
bool cbEditorInternalData::m_useByteOrderMark
Definition at line 492 of file cbeditor.cpp.
Referenced by cbEditorInternalData(), cbEditor::GetUseBom(), cbEditor::Open(), and cbEditor::SetUseBom().
mFoldingLimit
bool cbEditorInternalData::mFoldingLimit
Definition at line 488 of file cbeditor.cpp.
Referenced by cbEditor::DoFoldLine(), and cbEditor::SetEditorStyleBeforeFileOpen().
mFoldingLimitLevel
int cbEditorInternalData::mFoldingLimitLevel
Definition at line 489 of file cbeditor.cpp.
Referenced by cbEditor::DoFoldLine(), and cbEditor::SetEditorStyleBeforeFileOpen().
The documentation for this struct was generated from the following file:
cbeditor.cpp