Code::Blocks: Doxygen::DoxygenParser Struct Reference
Doxygen::DoxygenParser Struct Reference
#include <doxygen_parser.h>
Public Member Functions
DoxygenParser ()
int FindNextKeyword (const wxString &doc)
int GetArgument (const wxString &doc, int range, wxString &output)
int GetPosition () const
void ReplaceInDoc (wxString &doc, size_t start, size_t count, const wxString &str)
void ReplaceCurrentKeyword (wxString &doc, const wxString &str)
Static Public Attributes
static const wxString Keywords []
static const int KwCount = sizeof(DoxygenParser::Keywords)/sizeof(DoxygenParser::Keywords[0])
static const wxString NewLineReplacment = _T("\n")
Protected Member Functions
int CheckKeyword (const wxString &doc)
int GetParagraphArgument (const wxString &doc, wxString &output)
void GetWordArgument (const wxString &doc, wxString &output)
void GetBlockArgument (const wxString &doc, wxString &output)
int GetLineArgument (const wxString &doc, wxString &output)
bool IsKeywordBegin (const wxString &doc) const
bool IsOneOf (wxChar c, const wxChar *chars) const
bool IsEnd (const wxString &doc) const
int GetEndLine (const wxString &doc) const
bool SkipDecorations (const wxString &doc)
bool HandleNewLine (const wxString &doc, wxString &output, const wxString &replaceWith=NewLineReplacment)
Protected Attributes
int m_FoundKw
int m_Pos
Constructor & Destructor Documentation
Doxygen::DoxygenParser::DoxygenParser ()
References Doxygen::KEYWORDS_COUNT, and KwCount.
Member Function Documentation
int Doxygen::DoxygenParser::CheckKeyword (const wxString & doc) protected
References IsOneOf(), Keywords, Doxygen::KEYWORDS_COUNT, KwCount, m_FoundKw, m_Pos, and Doxygen::NO_KEYWORD.
Referenced by FindNextKeyword(), and GetLineArgument().
int Doxygen::DoxygenParser::FindNextKeyword (const wxString & doc)
References CheckKeyword(), IsKeywordBegin(), Doxygen::KEYWORDS_COUNT, m_Pos, and Doxygen::NO_KEYWORD.
Referenced by DocumentationHelper::DoxygenToHTML().
int Doxygen::DoxygenParser::GetArgument (const wxString & doc, int range, wxString & output)
References GetBlockArgument(), GetLineArgument(), GetParagraphArgument(), GetWordArgument(), m_Pos, Doxygen::RANGE_BLOCK, Doxygen::RANGE_LINE, Doxygen::RANGE_PARAGRAPH, Doxygen::RANGE_WORD, and SkipDecorations().
Referenced by DocumentationHelper::DoxygenToHTML().
void Doxygen::DoxygenParser::GetBlockArgument (const wxString & doc, wxString & output) protected
Referenced by GetArgument().
int Doxygen::DoxygenParser::GetEndLine (const wxString & doc) const protected
References m_Pos.
int Doxygen::DoxygenParser::GetLineArgument (const wxString & doc, wxString & output) protected
References c, CheckKeyword(), IsKeywordBegin(), m_Pos, Doxygen::NESTED_KEYWORDS_BEGIN, and Doxygen::NO_KEYWORD.
Referenced by GetArgument(), and GetParagraphArgument().
int Doxygen::DoxygenParser::GetParagraphArgument (const wxString & doc, wxString & output) protected
References GetLineArgument(), HandleNewLine(), and m_Pos.
Referenced by GetArgument().
int Doxygen::DoxygenParser::GetPosition () const
References m_Pos.
Referenced by DocumentationHelper::DoxygenToHTML().
void Doxygen::DoxygenParser::GetWordArgument (const wxString & doc, wxString & output) protected
References c, and m_Pos.
Referenced by GetArgument().
bool Doxygen::DoxygenParser::HandleNewLine (const wxString & doc, wxString & output, const wxString & replaceWith = NewLineReplacment) protected
Returns
true if m_Pos has changed
References SkipDecorations().
Referenced by GetParagraphArgument().
bool Doxygen::DoxygenParser::IsEnd (const wxString & doc) const protected
References m_Pos.
Referenced by SkipDecorations().
bool Doxygen::DoxygenParser::IsKeywordBegin (const wxString & doc) const protected
References m_Pos.
Referenced by FindNextKeyword(), and GetLineArgument().
bool Doxygen::DoxygenParser::IsOneOf (wxChar c, const wxChar * chars) const protected
Referenced by CheckKeyword(), and SkipDecorations().
void Doxygen::DoxygenParser::ReplaceCurrentKeyword (wxString & doc, const wxString & str)
References m_FoundKw, m_Pos, and ReplaceInDoc().
Referenced by DocumentationHelper::DoxygenToHTML().
void Doxygen::DoxygenParser::ReplaceInDoc (wxString & doc, size_t start, size_t count, const wxString & str)
References m_Pos.
Referenced by ReplaceCurrentKeyword().
bool Doxygen::DoxygenParser::SkipDecorations (const wxString & doc) protected
Returns
true if m_Pos has changed
References IsEnd(), IsOneOf(), and m_Pos.
Referenced by GetArgument(), and HandleNewLine().
Member Data Documentation
const wxString Doxygen::DoxygenParser::Keywords static
Initial value:
= {
        _T(""),
        _T("param"),
        _T("return"), _T("result"),
        _T("brief"), _T("short"),
        _T("sa"), _T("see"),
        _T("class"), _T("struct"),
        _T("union"),
        _T("enum"),
        _T("namespace"),
        _T("fn"),
        _T("var"),
        _T("def"),
        _T("code"),
        _T("endcode"),
        _T("b"),
    }
Referenced by CheckKeyword().
const int Doxygen::DoxygenParser::KwCount = sizeof(DoxygenParser::Keywords)/sizeof(DoxygenParser::Keywords[0]) static
Referenced by CheckKeyword(), and DoxygenParser().
int Doxygen::DoxygenParser::m_FoundKw protected
Referenced by CheckKeyword(), and ReplaceCurrentKeyword().
int Doxygen::DoxygenParser::m_Pos protected
Referenced by CheckKeyword(), FindNextKeyword(), GetArgument(), GetEndLine(), GetLineArgument(), GetParagraphArgument(), GetPosition(), GetWordArgument(), IsEnd(), IsKeywordBegin(), ReplaceCurrentKeyword(), ReplaceInDoc(), and SkipDecorations().
const wxString Doxygen::DoxygenParser::NewLineReplacment = _T("\n") static
The documentation for this struct was generated from the following files:
doxygen_parser.h
doxygen_parser.cpp