Code::Blocks: cbThreadPool::cbThreadedTaskElement Struct Reference
cbThreadPool::cbThreadedTaskElement Struct Reference
All tasks are added to one of these. It'll also save the autodelete value.
Public Member Functions
cbThreadedTaskElement (cbThreadedTask *_task=nullptr, bool _autodelete=false)
void Delete ()
It'll delete the task only if it was set to.
Public Attributes
cbThreadedTask * task
bool autodelete
Detailed Description
All tasks are added to one of these. It'll also save the autodelete value.
Definition at line 210 of file cbthreadpool.h.
Constructor & Destructor Documentation
cbThreadedTaskElement()
cbThreadPool::cbThreadedTaskElement::cbThreadedTaskElement (cbThreadedTask * _task = nullptr, bool _autodelete = false) inline
Definition at line 212 of file cbthreadpool.h.
Member Function Documentation
Delete()
void cbThreadPool::cbThreadedTaskElement::Delete () inline
It'll delete the task only if it was set to.
Definition at line 220 of file cbthreadpool.h.
Referenced by cbThreadPool::AbortAllTasks(), cbThreadPool::cbWorkerThread::Entry(), and cbThreadPool::~cbThreadPool().
Member Data Documentation
autodelete
bool cbThreadPool::cbThreadedTaskElement::autodelete
Definition at line 230 of file cbthreadpool.h.
task
cbThreadedTask* cbThreadPool::cbThreadedTaskElement::task
Definition at line 229 of file cbthreadpool.h.
Referenced by cbThreadPool::cbWorkerThread::Entry().
The documentation for this struct was generated from the following file:
cbthreadpool.h