Code::Blocks: NativeParserBase::ParserComponent Struct Reference
NativeParserBase::ParserComponent Struct Reference
a long statement can be divided to a ParserComponent chain.
#include <nativeparser_base.h>
Public Member Functions
ParserComponent ()
operator type
void Clear ()
Public Attributes
wxString component
ParserTokenType tokenType
name
OperatorType tokenOperatorType
type
Detailed Description
a long statement can be divided to a ParserComponent chain.
e.g. for a statement like below:
Ogre::Root::getSingleton().|
a chains of four ParserComponents will be generated and list below:
Ogre             [pttNamespace]
Root             [pttClass]
getSingleton     [pttFunction]
(empty space)    [pttSearchText]
Definition at line 61 of file nativeparser_base.h.
Constructor & Destructor Documentation
ParserComponent()
NativeParserBase::ParserComponent::ParserComponent () inline
operator type
Definition at line 67 of file nativeparser_base.h.
References Clear().
Member Function Documentation
Clear()
void NativeParserBase::ParserComponent::Clear () inline
Definition at line 68 of file nativeparser_base.h.
References NativeParserBase::AddTemplateAlias(), NativeParserBase::BreakUpComponents(), NativeParserBase::CleanupSearchScope(), NativeParserBase::CollectSearchScopes(), NativeParserBase::ComputeCallTip(), NativeParserBase::DependsOnAllocator(), NativeParserBase::FindAIMatches(), NativeParserBase::FindCCTokenStart(), NativeParserBase::FindCurrentFunctionScope(), NativeParserBase::FindFunctionOpenParenthesis(), NativeParserBase::GenerateResultSet(), NativeParserBase::GetCallTipHighlight(), NativeParserBase::GetCCToken(), NativeParserBase::GetNextCCToken(), NativeParserBase::GetTokenFromCurrentLine(), NativeParserBase::IsAllocator(), NativeParserBase::NativeParserBase(), NativeParserBase::otOperatorUndefined, NativeParserBase::PrettyPrintToken(), NativeParserBase::pttUndefined, NativeParserBase::RemoveLastFunctionChildren(), NativeParserBase::Reset(), NativeParserBase::ResolveActualType(), NativeParserBase::ResolveExpression(), NativeParserBase::ResolveOperator(), NativeParserBase::ResolveTemplateMap(), tokenOperatorType, tokenType, wxEmptyString, and NativeParserBase::~NativeParserBase().
Referenced by ParserComponent(), and NativeParserBase::Reset().
Member Data Documentation
component
wxString NativeParserBase::ParserComponent::component
Definition at line 63 of file nativeparser_base.h.
Referenced by NativeParserBase::BreakUpComponents(), NativeParserBase::FindAIMatches(), NativeParser::ParseBufferForUsingNamespace(), NativeParserBase::ResolveActualType(), and NativeParserBase::ResolveExpression().
tokenOperatorType
OperatorType NativeParserBase::ParserComponent::tokenOperatorType
type
Definition at line 65 of file nativeparser_base.h.
Referenced by NativeParserBase::BreakUpComponents(), Clear(), and NativeParserBase::ResolveExpression().
tokenType
ParserTokenType NativeParserBase::ParserComponent::tokenType
name
Definition at line 64 of file nativeparser_base.h.
Referenced by NativeParserBase::BreakUpComponents(), Clear(), NativeParserBase::FindAIMatches(), and NativeParserBase::ResolveExpression().
The documentation for this struct was generated from the following file:
nativeparser_base.h