Code::Blocks: cbDebuggerCommonConfig Struct Reference
cbDebuggerCommonConfig Struct Reference
#include <debuggermanager.h>
Public Types
enum Flags {
AutoBuild = 0, AutoSwitchFrame, ShowDebuggersLog, JumpOnDoubleClick,
RequireCtrlForTooltips, ShowTemporaryBreakpoints
}
enum Perspective { OnlyOne = 0, OnePerDebugger, OnePerDebuggerConfig }
Static Public Member Functions
static bool GetFlag (Flags flag)
static void SetFlag (Flags flag, bool value)
static wxString GetValueTooltipFont ()
static void SetValueTooltipFont (const wxString &font)
static Perspective GetPerspective ()
static void SetPerspective (int perspective)
Detailed Description
Definition at line 191 of file debuggermanager.h.
Member Enumeration Documentation
Flags
enum cbDebuggerCommonConfig::Flags
Enumerator
AutoBuild
AutoSwitchFrame
ShowDebuggersLog
JumpOnDoubleClick
RequireCtrlForTooltips
ShowTemporaryBreakpoints
Definition at line 193 of file debuggermanager.h.
Perspective
enum cbDebuggerCommonConfig::Perspective
Enumerator
OnlyOne
OnePerDebugger
OnePerDebuggerConfig
Definition at line 203 of file debuggermanager.h.
Member Function Documentation
GetFlag()
bool cbDebuggerCommonConfig::GetFlag (Flags flag) static
Definition at line 366 of file debuggermanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), ConfigManager::ReadBool(), and wxT.
Referenced by DebuggerSettingsCommonPanel::DebuggerSettingsCommonPanel(), cbDebuggerPlugin::EnsureBuildUpToDate(), cbDebuggerPlugin::HasDebugLog(), DebuggerGDB::OnCursorChanged(), BacktraceDlg::OnDoubleClick(), BacktraceDlg::OnListRightClick(), BreakpointsDlg::OnShowTemp(), BreakpointsDlg::OnUpdateUI(), GdbCmd_Backtrace::ParseOutput(), cbDebuggerPlugin::ProcessValueTooltip(), and BreakpointsDlg::Reload().
GetPerspective()
cbDebuggerCommonConfig::Perspective cbDebuggerCommonConfig::GetPerspective () static
Definition at line 438 of file debuggermanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), ConfigManager::ReadInt(), and wxT.
Referenced by DebuggerSettingsCommonPanel::DebuggerSettingsCommonPanel(), and cbDebuggerPlugin::SwitchToDebuggingLayout().
GetValueTooltipFont()
wxString cbDebuggerCommonConfig::GetValueTooltipFont () static
Definition at line 415 of file debuggermanager.cpp.
References wxString::empty(), Manager::Get(), Manager::GetConfigManager(), wxSystemSettings::GetFont(), wxFont::GetNativeFontInfo(), wxFont::GetPointSize(), ConfigManager::Read(), wxFont::SetPointSize(), wxNativeFontInfo::ToString(), wxSYS_DEFAULT_GUI_FONT, and wxT.
Referenced by DebuggerSettingsCommonPanel::DebuggerSettingsCommonPanel(), and ValueTooltip::ValueTooltip().
SetFlag()
void cbDebuggerCommonConfig::SetFlag (Flags flag, bool value) static
Definition at line 388 of file debuggermanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), ConfigManager::Write(), and wxT.
Referenced by BacktraceDlg::OnSettingJumpDefault(), BacktraceDlg::OnSettingSwitchDefault(), BreakpointsDlg::OnShowTemp(), and DebuggerSettingsCommonPanel::SaveChanges().
SetPerspective()
void cbDebuggerCommonConfig::SetPerspective (int perspective) static
Definition at line 447 of file debuggermanager.cpp.
References Manager::Get(), Manager::GetConfigManager(), ConfigManager::Write(), and wxT.
Referenced by DebuggerSettingsCommonPanel::SaveChanges().
SetValueTooltipFont()
void cbDebuggerCommonConfig::SetValueTooltipFont (const wxString & font) static
Definition at line 427 of file debuggermanager.cpp.
References wxString::empty(), Manager::Get(), Manager::GetConfigManager(), ConfigManager::Write(), and wxT.
Referenced by DebuggerSettingsCommonPanel::SaveChanges().
The documentation for this struct was generated from the following files:
debuggermanager.h
debuggermanager.cpp