Code::Blocks: DebuggerManager::PluginData Struct Reference
DebuggerManager::PluginData Struct Reference
#include <debuggermanager.h>
Public Member Functions
PluginData ()
ConfigurationVector & GetConfigurations ()
const ConfigurationVector & GetConfigurations () const
cbDebuggerConfiguration * GetConfiguration (int index)
void ClearConfigurations ()
Private Attributes
ConfigurationVector m_configurations
int m_lastConfigID
Friends
class DebuggerManager
Detailed Description
Definition at line 243 of file debuggermanager.h.
Constructor & Destructor Documentation
PluginData()
DebuggerManager::PluginData::PluginData () inline
Definition at line 247 of file debuggermanager.h.
Member Function Documentation
ClearConfigurations()
void DebuggerManager::PluginData::ClearConfigurations () inline
Definition at line 254 of file debuggermanager.h.
Referenced by DebuggerManager::ProcessSettings().
GetConfiguration()
cbDebuggerConfiguration * DebuggerManager::PluginData::GetConfiguration (int index)
Definition at line 685 of file debuggermanager.cpp.
References cbAssert.
GetConfigurations() [1/2]
ConfigurationVector& DebuggerManager::PluginData::GetConfigurations () inline
Definition at line 249 of file debuggermanager.h.
Referenced by DebuggerSettingsDlg::DebuggerSettingsDlg(), CompilerOptionsDlg::DoFillCompilerPrograms(), DebuggerManager::FindTargetsDebugger(), and DebuggerManager::ProcessSettings().
GetConfigurations() [2/2]
const ConfigurationVector& DebuggerManager::PluginData::GetConfigurations () const inline
Definition at line 250 of file debuggermanager.h.
Friends And Related Function Documentation
DebuggerManager
friend class DebuggerManager friend
Definition at line 245 of file debuggermanager.h.
Member Data Documentation
m_configurations
ConfigurationVector DebuggerManager::PluginData::m_configurations private
Definition at line 261 of file debuggermanager.h.
m_lastConfigID
int DebuggerManager::PluginData::m_lastConfigID private
Definition at line 262 of file debuggermanager.h.
Referenced by DebuggerManager::ProcessSettings().
The documentation for this struct was generated from the following files:
debuggermanager.h
debuggermanager.cpp