Code::Blocks: systemheadersthread.cpp File Reference
systemheadersthread.cpp File Reference
#include <sdk.h>
#include "systemheadersthread.h"
Classes
class HeaderDirTraverser
Macros
#define CC_SYSTEMHEADERSTHREAD_DEBUG_OUTPUT 0
#define TRACE(format, args...)
#define TRACE2(format, args...)
Variables
long idSystemHeadersThreadFinish = wxNewId()
long idSystemHeadersThreadUpdate = wxNewId()
long idSystemHeadersThreadError = wxNewId()
Macro Definition Documentation
CC_SYSTEMHEADERSTHREAD_DEBUG_OUTPUT
#define CC_SYSTEMHEADERSTHREAD_DEBUG_OUTPUT 0
Definition at line 21 of file systemheadersthread.cpp.
TRACE
#define TRACE (format, args...)
Definition at line 48 of file systemheadersthread.cpp.
Referenced by HeaderDirTraverser::AddLock(), SystemHeadersThread::Entry(), and SystemHeadersThread::~SystemHeadersThread().
TRACE2
#define TRACE2 (format, args...)
Definition at line 49 of file systemheadersthread.cpp.
Variable Documentation
idSystemHeadersThreadError
long idSystemHeadersThreadError = wxNewId()
Definition at line 58 of file systemheadersthread.cpp.
Referenced by CodeCompletion::CodeCompletion(), SystemHeadersThread::Entry(), and CodeCompletion::~CodeCompletion().
idSystemHeadersThreadFinish
long idSystemHeadersThreadFinish = wxNewId()
Definition at line 54 of file systemheadersthread.cpp.
Referenced by CodeCompletion::CodeCompletion(), SystemHeadersThread::Entry(), and CodeCompletion::~CodeCompletion().
idSystemHeadersThreadUpdate
long idSystemHeadersThreadUpdate = wxNewId()
Definition at line 56 of file systemheadersthread.cpp.
Referenced by CodeCompletion::CodeCompletion(), SystemHeadersThread::Entry(), and CodeCompletion::~CodeCompletion().