Code::Blocks: uservarmanager.cpp File Reference
uservarmanager.cpp File Reference
#include "sdk_precomp.h"
#include "uservarmanager.h"
#include "configmanager.h"
#include "logmanager.h"
#include "projectmanager.h"
#include "macrosmanager.h"
#include "manager.h"
#include "cbexception.h"
#include "infowindow.h"
#include <wx/button.h>
#include "scrollingdialog.h"
#include <wx/intl.h>
#include <wx/xrc/xmlres.h>
#include <wx/textctrl.h>
#include <wx/splitter.h>
#include "annoyingdialog.h"
#include <wx/choice.h>
#include <wx/textdlg.h>
#include <ctype.h>
Classes
class UsrGlblMgrEditDialog
Functions
const wxString cBase (_T("base"))
const wxString cDir (_T("dir"))
const wxChar cSlash (_T('/'))
const wxString cSlashBase (_T("/base"))
const wxString cInclude (_T("include"))
const wxString cLib (_T("lib"))
const wxString cObj (_T("obj"))
const wxString cBin (_T("bin"))
const wxString cCflags (_T("cflags"))
const wxString cLflags (_T("lflags"))
const wxString cSets (_T("/sets/"))
const wxArrayString builtinMembers ((size_t) 7, bim)
Variables
const wxChar * bim []
Function Documentation
const wxArrayString builtinMembers ((size_t) 7, bim)
Referenced by UsrGlblMgrEditDialog::Load(), and UsrGlblMgrEditDialog::Save().
const wxString cBase (_T("base"))
Referenced by UserVariableManager::Replace().
const wxString cBin (_T("bin"))
Referenced by UserVariableManager::Replace().
const wxString cCflags (_T("cflags"))
const wxString cDir (_T("dir"))
const wxString cInclude (_T("include"))
Referenced by UserVariableManager::Replace().
const wxString cLflags (_T("lflags"))
const wxString cLib (_T("lib"))
Referenced by UserVariableManager::Replace().
const wxString cObj (_T("obj"))
Referenced by UserVariableManager::Replace().
const wxString cSets (_T("/sets/"))
Referenced by UsrGlblMgrEditDialog::CloneSet(), UsrGlblMgrEditDialog::DeleteSet(), UsrGlblMgrEditDialog::DeleteVar(), UserVariableManager::Exists(), UsrGlblMgrEditDialog::Load(), UserVariableManager::Preempt(), UserVariableManager::Replace(), UsrGlblMgrEditDialog::Save(), and UsrGlblMgrEditDialog::UpdateChoices().
const wxChar cSlash (_T('/'))
const wxString cSlashBase (_T("/base"))
Variable Documentation
const wxChar* bim[]
Initial value:
=
{
    _T("base"),
    _T("include"),
    _T("lib"),
    _T("obj"),
    _T("bin"),
    _T("cflags"),
}