Code::Blocks: watchesdlg.cpp File Reference
watchesdlg.cpp File Reference
#include "sdk.h"
#include <numeric>
#include <map>
#include <algorithm>
#include <wx/propgrid/propgrid.h>
#include "watchesdlg.h"
#include "cbcolourmanager.h"
#include "debuggermanager.h"
Classes
struct WatchesDlg::WatchItemPredicate
class cbDummyEditor
class cbTextCtrlAndButtonTooltipEditor
class WatchesProperty
class WatchRawDialogAdapter
class WatchRawDialog
dialog to show the value of a watch
class WatchesDropTarget
Macros
#define wxPG_EX_DISABLE_TLP_TRACKING 0x00000000
Typedefs
typedef wxString wxPG_CONST_WXCHAR_PTR
Functions
IMPLEMENT_DYNAMIC_CLASS (cbDummyEditor, wxPGEditor)
IMPLEMENT_DYNAMIC_CLASS (cbTextCtrlAndButtonTooltipEditor, wxPGTextCtrlAndButtonEditor)
IMPLEMENT_DYNAMIC_CLASS (WatchesProperty, wxStringProperty)
void AppendChildren (wxPropertyGrid &grid, wxPGProperty &property, cbWatch &watch, bool readonly, const wxColour &changedColour)
void UpdateWatch (wxPropertyGrid *grid, wxPGProperty *property, cb::shared_ptr< cbWatch > watch, bool readonly)
void SetValue (WatchesProperty *prop)
wxPGProperty * GetRealRoot (wxPropertyGrid *grid)
void GetColumnWidths (wxClientDC &dc, wxPropertyGrid *grid, wxPGProperty *root, int width[3])
void GetColumnWidths (wxPropertyGrid *grid, wxPGProperty *root, int width[3])
void SetMinSize (wxPropertyGrid *grid)
Variables
static wxPGEditor * watchesDummyEditor = nullptr
static wxPGEditor * watchesPropertyEditor = nullptr
Macro Definition Documentation
wxPG_EX_DISABLE_TLP_TRACKING
#define wxPG_EX_DISABLE_TLP_TRACKING 0x00000000
Referenced by ValueTooltip::ValueTooltip(), and WatchesDlg::WatchesDlg().
Typedef Documentation
wxPG_CONST_WXCHAR_PTR
typedef wxString wxPG_CONST_WXCHAR_PTR
Definition at line 72 of file watchesdlg.cpp.
Function Documentation
AppendChildren()
void AppendChildren (wxPropertyGrid & grid, wxPGProperty & property, cbWatch & watch, bool readonly, const wxColour & changedColour) inline
Definition at line 411 of file watchesdlg.cpp.
References wxPropertyGrid::AppendIn(), wxString::empty(), wxPropertyGrid::EnableProperty(), cbWatch::GetChild(), cbWatch::GetChildCount(), wxPropertyGrid::IsPropertyEnabled(), wxPropertyGrid::SetPropertyAttribute(), wxPropertyGrid::SetPropertyColoursToDefault(), wxPropertyGrid::SetPropertyHelpString(), wxPropertyGrid::SetPropertyTextColour(), WatchRawDialog::UpdateValue(), wxEmptyString, and wxT.
Referenced by UpdateWatch().
GetColumnWidths() [1/2]
void GetColumnWidths (wxClientDC & dc, wxPropertyGrid * grid, wxPGProperty * root, int width[3]) inline
Definition at line 1016 of file watchesdlg.cpp.
References wxPGProperty::GetChildCount(), wxPGProperty::IsExpanded(), and wxPGProperty::Item().
Referenced by GetColumnWidths(), and SetMinSize().
GetColumnWidths() [2/2]
void GetColumnWidths (wxPropertyGrid * grid, wxPGProperty * root, int width[3]) inline
Definition at line 1055 of file watchesdlg.cpp.
References GetColumnWidths().
GetRealRoot()
wxPGProperty* GetRealRoot (wxPropertyGrid * grid) inline
Definition at line 1010 of file watchesdlg.cpp.
Referenced by SetMinSize(), and ValueTooltip::UpdateWatch().
IMPLEMENT_DYNAMIC_CLASS() [1/3]
IMPLEMENT_DYNAMIC_CLASS (cbDummyEditor , wxPGEditor)
Referenced by wxToolBarAddOnXmlHandler::CanHandle(), CCTreeCtrlExpandedItemData::CCTreeCtrlExpandedItemData(), cbTextCtrlAndButtonTooltipEditor::CreateControls(), cbDummyEditor::OnEvent(), and WatchRawDialogAdapter::WatchRawDialogAdapter().
IMPLEMENT_DYNAMIC_CLASS() [2/3]
IMPLEMENT_DYNAMIC_CLASS (cbTextCtrlAndButtonTooltipEditor , wxPGTextCtrlAndButtonEditor)
IMPLEMENT_DYNAMIC_CLASS() [3/3]
IMPLEMENT_DYNAMIC_CLASS (WatchesProperty , wxStringProperty)
SetMinSize()
void SetMinSize (wxPropertyGrid * grid) inline
Definition at line 1062 of file watchesdlg.cpp.
References GetColumnWidths(), wxPropertyGrid::GetLastItem(), wxSystemSettings::GetMetric(), GetRealRoot(), wxPropertyGrid::GetRoot(), wxPropertyGrid::GetVerticalSpacing(), wxRect::height, wxPropertyGrid::IsPropertyExpanded(), wxPropertyGrid::ResetColumnSizes(), wxPropertyGrid::SetColumnProportion(), wxRect::width, wxPG_ITERATE_ALL, wxPG_ITERATE_DEFAULT, wxSYS_SCREEN_X, and wxSYS_SCREEN_Y.
Referenced by GotoFile::AddControlBelowList(), ValueTooltip::Fit(), GetUserVariableDialog::GetUserVariableDialog(), and ValueTooltip::ValueTooltip().
SetValue()
void SetValue (WatchesProperty * prop) inline
Definition at line 493 of file watchesdlg.cpp.
References Manager::Get(), DebuggerManager::GetDebuggerHavingWatch(), Manager::GetDebuggerManager(), WatchesProperty::GetWatch(), and cbDebuggerPlugin::SetWatchValue().
Referenced by UsrGlblMgrEditDialog::Load(), and WatchesDlg::OnPropertyChanged().
UpdateWatch()
void UpdateWatch (wxPropertyGrid * grid, wxPGProperty * property, cb::shared_ptr< cbWatch > watch, bool readonly) inline
Definition at line 451 of file watchesdlg.cpp.
References AppendChildren(), wxString::empty(), Manager::Get(), ColourManager::GetColour(), Manager::GetColourManager(), wxPGProperty::GetName(), wxPropertyGrid::SetPropertyAttribute(), wxPropertyGrid::SetPropertyColoursToDefault(), wxPropertyGrid::SetPropertyHelpString(), wxPropertyGrid::SetPropertyLabel(), wxPropertyGrid::SetPropertyName(), wxPropertyGrid::SetPropertyTextColour(), WatchRawDialog::UpdateValue(), wxEmptyString, and wxT.
Referenced by cbDebuggerPlugin::OnConfigurationChange(), WatchesDlg::RenameWatch(), and WatchesDlg::UpdateWatches().
Variable Documentation
watchesDummyEditor
wxPGEditor* watchesDummyEditor = nullptr static
Definition at line 113 of file watchesdlg.cpp.
Referenced by WatchesProperty::DoGetEditorClass(), and WatchesDlg::WatchesDlg().
watchesPropertyEditor
wxPGEditor* watchesPropertyEditor = nullptr static
Definition at line 137 of file watchesdlg.cpp.
Referenced by WatchesProperty::DoGetEditorClass(), and WatchesDlg::WatchesDlg().