Code::Blocks: wizpage.cpp File Reference
wizpage.cpp File Reference
#include <sdk.h>
#include <wx/ctrlsub.h>
#include <manager.h>
#include <logmanager.h>
#include <configmanager.h>
#include <projectmanager.h>
#include <scriptingmanager.h>
#include <compilerfactory.h>
#include <compiler.h>
#include <macrosmanager.h>
#include <cbproject.h>
#include <cbexception.h>
#include <scripting/bindings/sc_base_types.h>
#include "wizpage.h"
#include "infopanel.h"
#include "projectpathpanel.h"
#include "compilerpanel.h"
#include "buildtargetpanel.h"
#include "filepathpanel.h"
#include "genericselectpath.h"
#include "genericsinglechoicelist.h"
Namespaces
Wizard
Functions
void Wizard::FillCompilerControl (wxItemContainer *control, const wxString &compilerID, const wxString &validCompilerIDs)
wxString AppendPathSepIfNeeded (const wxString &path)
Function Documentation
wxString AppendPathSepIfNeeded (const wxString & path)
Referenced by WizCompilerPanel::GetDebugObjectOutputDir(), WizCompilerPanel::GetDebugOutputDir(), WizProjectPathPanel::GetPath(), WizCompilerPanel::GetReleaseObjectOutputDir(), WizCompilerPanel::GetReleaseOutputDir(), WizBuildTargetPanel::GetTargetObjectOutputDir(), and WizBuildTargetPanel::GetTargetOutputDir().