Code::Blocks: workspaceloader.cpp File Reference
workspaceloader.cpp File Reference
#include "sdk_precomp.h"
#include <wx/confbase.h>
#include <wx/fileconf.h>
#include <wx/intl.h>
#include <wx/string.h>
#include "workspaceloader.h"
#include "manager.h"
#include "projectmanager.h"
#include "logmanager.h"
#include "cbproject.h"
#include "globals.h"
#include "cbworkspace.h"
#include "editormanager.h"
#include "cbauibook.h"
#include "annoyingdialog.h"
#include "tinyxml/tinyxml.h"
#include "tinyxml/tinywxuni.h"
Functions
ProjectManager * GetpMan ()
LogManager * GetpMsg ()
Function Documentation
ProjectManager* GetpMan () inline
References Manager::Get(), and Manager::GetProjectManager().
Referenced by WorkspaceLoader::LoadLayout(), and WorkspaceLoader::Open().
LogManager* GetpMsg () inline
References Manager::Get(), and Manager::GetLogManager().
Referenced by WorkspaceLoader::LoadLayout(), and WorkspaceLoader::Open().